### PR TITLE
fabric 1.13.1

### PR DESCRIPTION
**Pull request by ploxiln**
also a big update to paramiko 2.1.1
which uses the python package "cryptography"

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Comment by stxml** [comment]
Crashes once it tries to connect to remote. Seems like it's connected to the switch to paramiko.

`  File "/usr/local/Cellar/fabric/1.13.1/libexec/lib/python2.7/site-packages/fabric/main.py", line 756, in main
    *args, **kwargs
  File "/usr/local/Cellar/fabric/1.13.1/libexec/lib/python2.7/site-packages/fabric/tasks.py", line 386, in execute
    multiprocessing
  File "/usr/local/Cellar/fabric/1.13.1/libexec/lib/python2.7/site-packages/fabric/tasks.py", line 276, in _execute
    return task.run(*args, **kwargs)
  File "/usr/local/Cellar/fabric/1.13.1/libexec/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/usr/local/Cellar/fabric/1.13.1/libexec/lib/python2.7/site-packages/fabric/decorators.py", line 56, in inner_decorator
    return func(*args, **kwargs)
  File "/Users/stm/Projects/go.Workspace/src/github.com/stxml/mansion/fabfile/__init__.py", line 85, in log
    sudo('sudo journalctl -a -u mansion --since yesterday --no-pager')
  File "/usr/local/Cellar/fabric/1.13.1/libexec/lib/python2.7/site-packages/fabric/network.py", line 683, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/fabric/1.13.1/libexec/lib/python2.7/site-packages/fabric/operations.py", line 1148, in sudo
    capture_buffer_size=capture_buffer_size,
  File "/usr/local/Cellar/fabric/1.13.1/libexec/lib/python2.7/site-packages/fabric/operations.py", line 930, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/usr/local/Cellar/fabric/1.13.1/libexec/lib/python2.7/site-packages/fabric/state.py", line 424, in default_channel
    chan = _open_session()
  File "/usr/local/Cellar/fabric/1.13.1/libexec/lib/python2.7/site-packages/fabric/state.py", line 416, in _open_session
    return connections[env.host_string].get_transport().open_session()
  File "/usr/local/Cellar/fabric/1.13.1/libexec/lib/python2.7/site-packages/fabric/network.py", line 159, in __getitem__
    self.connect(key)
  File "/usr/local/Cellar/fabric/1.13.1/libexec/lib/python2.7/site-packages/fabric/network.py", line 151, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/usr/local/Cellar/fabric/1.13.1/libexec/lib/python2.7/site-packages/fabric/network.py", line 434, in connect
    client.load_system_host_keys()
  File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/paramiko/client.py", line 101, in load_system_host_keys
    self._system_host_keys.load(filename)
  File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/paramiko/hostkeys.py", line 101, in load
    e = HostKeyEntry.from_line(line, lineno)
  File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/paramiko/hostkeys.py", line 335, in from_line
    key = ECDSAKey(data=decodebytes(key), validate_point=False)
  File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/paramiko/ecdsakey.py", line 138, in __init__
    self.verifying_key = numbers.public_key(backend=default_backend())
  File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 71, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 28, in _available_backends
    "cryptography.backends"
  File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 51, in <module>
    from cryptography.hazmat.bindings._openssl import ffi as _ffi
ImportError: dlopen(/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so, 2): Symbol not found: _getentropy
  Referenced from: /usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so`

**Comment by ploxiln** [comment]
Please, in the future, try to format and isolate the error message a bit better. This is more readable:

```
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/paramiko/client.py", line 101, in load_system_host_keys self._system_host_keys.load(filename)
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/paramiko/hostkeys.py", line 101, in load e = HostKeyEntry.from_line(line, lineno)
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/paramiko/hostkeys.py", line 335, in from_line key = ECDSAKey(data=decodebytes(key), validate_point=False)
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/paramiko/ecdsakey.py", line 138, in __init__ self.verifying_key = numbers.public_key(backend=default_backend())
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 71, in default_backend _default_backend = MultiBackend(_available_backends())
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 28, in _available_backends "cryptography.backends"
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module> from cryptography.hazmat.backends.openssl.backend import backend
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 51, in <module> from cryptography.hazmat.bindings._openssl
    import ffi as _ffi
    ImportError: dlopen(/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so, 2):
    Symbol not found: _getentropy
    Referenced from: /usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
    Expected in: /usr/lib/libSystem.B.dylib in /usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
```

So, FWIW, I did test connecting to hosts on my own system which is running OS X 10.11. Unfortunately that is not tested in the formula test block (and it wouldn't be easy to do so) so it's possible that something goes wrong with the module build on another version of macOS. What version of MacOS are you running?

Also, it is possible to downgrade back to paramiko 1.x, if that's the best solution for now.

**Comment by ploxiln** [comment]
Also, for what it's worth, the openssl binding seems linked correctly on my system:

```
$ otool -L /usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so 
/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so:
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by stxml** [comment]
I'm using 10.11.6 and it seems the problem has appeared before.

http://stackoverflow.com/questions/37270345/issue-with-python-2-7-paramiko-in-mac-os-elcapitan#37271641

```
/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so:
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```

**Comment by ploxiln** [comment]
This looks like the problem described here: https://gitlab.com/gnutls/gnutls/issues/142

> So it's defined but not actually available on 10.11, and you won't find that out at build time unless you pass -no_weak_imports in LDFLAGS. (Note that you can't easily do that because that flag is not supported on earlier versions of Xcode, including the CLT 7.3.1 which is the latest available for 10.11. So even if Xcode 8 is installed, using -no_weak_imports can still fail, which is a case you have to be prepared to handle if you use that flag.)

> But assuming you don't pass -no_weak_imports it will find getentropy is defined in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/random.h and compile, but then crash at run time. So a somewhat more robust approach is to check that it both builds and executes, since simply successfully compiling does not mean you actually have the symbol available at run-time anymore.

That doesn't explain why I don't seem to have the problem ...

**Comment by stxml** [comment]
Maybe the latest Security Update changed something?

**Comment by ploxiln** [comment]
I created an issue for this, #8044, and also figured out that if you have the recent Command Line Tools update installed (from the Mac App Store around December 13th), and install with `--build-from-source`, it works (the bottle doesn't work).

**Pull request closed without merging**
