### PR TITLE
azion 1.23.0

### PR DESCRIPTION
**Pull request by tiagokrebs**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>## Changelog
### New Features
* a8379e67 feat: check prefixg
* fa10b3c8 feat: check version node
### Improvements
* dc72c61e chore: add info messages during deploy
* 86347b4a chore: add timestamp to edge-application name
* d0717ad8 chore: adjusted for regex
* c72355ee chore: code field does not pack in table space
* 07880429 chore: update doApplication

</pre>
</details>

### CODE REVIEW

**Comment by PatrickMenoti** [comment]
The new changes affected the test (the behavior is slightly different now)
Should I update the tests and keep this PR open? Or close this one and release a new one once the tests have been updated?

**Comment by p-linnane** [comment]
We can just update the text in the test in this PR to match the new one.

**Comment by PatrickMenoti** [comment]
I have the updated test in this PR: https://github.com/Homebrew/homebrew-core/pull/171061

**Comment by PatrickMenoti** [comment]
> We can just update the text in the test in this PR to match the new one.

The text is the same... we just need to test `build` instead of `dev` now

**Comment by PatrickMenoti** [comment]
If the two PRs is not the best solution, we could do it here @p-linnane 
It's just like I said it: the test should be changed from `dev` to `build`

**Comment by PatrickMenoti** [comment]
> I have the updated test in this PR: #171061

The test PR has been merged @p-linnane

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
