### PR TITLE
Bottle unneeded (a)

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Extracted from https://github.com/Homebrew/homebrew-core/pull/79448
Part of https://github.com/Homebrew/homebrew-core/issues/75943

### CODE REVIEW

**Comment by carlocab** [comment]
ARM
```
Error: 2 failed steps!
brew test --verbose ant@1.9
brew test --verbose autoenv
```
`ant@1.9` needs a Java dependency and presumably a modification to its wrapper script to make it more like `ant`. Not sure what happened to `autoenv` -- the test failed from timing out.

**Comment by cho-m** [comment]
`autoenv` may be related to https://github.com/inishchith/autoenv/pull/190 (fix for freezing on Catalina); however, the last release was back in 2016 and the fix was never released.

**Comment by cho-m** [comment]
@nandahkrishna Extracting `autoenv` to separate PR may be fastest way to merge this.

`autoenv` in its current state should not be bottled on Catalina & Big Sur as it is clearly broken.
Either need to try patching (or backport the fix), or choose to restrict only up to Mojave

**Comment by nandahkrishna** [comment]
Sorry, missed your earlier comment. I've removed `autoenv` here and will create a separate PR shortly.

**Review by cho-m — APPROVED** [review]

**Comment by carlocab** [comment]
No `all` bottle:

`autospy` - 5c95c8f06607979d7aac3b6d4342235c9163e977
`archey` - b6d706c499b9f5a01d46937615846b32757b33d1
`app-engine-python` - 809af0b129b3ecb6ad14f5eb7d30a719b65281cc
`automysqlbackup` - e91352a0c339a2468bd6183b56b45178b6129537

**Pull request closed without merging**
