### PR TITLE
rust 1.12.0

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by zmwangx** [comment]
There's concern in #5185 that the `cargo` we ship is outdated. Maybe we should use the just released [0.13.0](https://github.com/rust-lang/cargo/releases/tag/0.13.0)?

**Comment by zmwangx** [comment]
I also wonder if we should update the bootstrap `cargo`. It's still stuck at the 1.3.0 period.

**Comment by alex** [comment]
@zmwangx I can upgrade the cargo if you'd like, that one hadn't been released at the time I sent this :-) Let me know if you prefer.

**Comment by zmwangx** [comment]
I'm not a rust user so I'm just making wild guesses :)

**Comment by alex** [comment]
@zmwangx since jenkins hadn't started yet, I went ahead and did the cargo 0.13.0 as well

**Comment by zmwangx** [comment]
Cool, I'll make sure the first commit is removed from queue.

**Comment by alexcrichton** [comment]
Ah yes Cargo doesn't track the same version number as rustc itself, so 0.13.0 used here is indeed correct!


Also it's ok to not worry too much about updating the Cargo bootstrap binary. If needed it can be updated, but if the compile succeeds then you should be A-OK

**Comment by zmwangx** [comment]
Merged as 18a8389. Thank you for another contribution to Homebrew!

**Pull request closed without merging**
