### PR TITLE
scspell 2.2 (new formula)

### PR DESCRIPTION
**Pull request by robredpath**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by robredpath** [comment]
So, this fails 'brew audit' because the upstream GH repo isn't popular enough. Happy to close this and just use this for myself if necessary, but figured it'd be rude not to try contributing upstream.

**Comment by gromgit** [comment]
You can still make this formula available to others by [creating your own tap](https://docs.brew.sh/Taps).

**Comment by robredpath** [comment]
Thanks @gromgit ; I've created https://github.com/OpenDataServices/homebrew-tap for anyone who's interested!

**Comment by jonchang** [comment]
Thanks for taking the initiative to submit this to Homebrew, but we won't be accepting it at this time due to the reasons here: https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff

**Pull request closed without merging**
