### PR TITLE
protobuf 22.3, protobuf@21 21.12 (new formula)

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Split out from #123507.

`protobuf` 22.0 carries breaking changes. Given that `grpc`'s support for `protobuf` 22.0 is still in progress: if we depend `grpc` on a newly-created `protobuf@21`, a considerable number of dependents will have to switch to it. So, we'd like to put the `protobuf` update on hold until `grpc` supports it.

See discussion in https://github.com/Homebrew/homebrew-core/pull/123507#issuecomment-1437085159.

### CODE REVIEW

**Comment by carlocab** [comment]
Do we have a timeline for when `grpc` will support the latest `protobuf`?

**Comment by ZhongRuoyu** [comment]
> Do we have a timeline for when `grpc` will support the latest `protobuf`?

Couldn't tell from the [list of PRs](https://github.com/grpc/grpc/pulls?q=is%3Apr+is%3Aopen+protobuf+22) on GitHub. The gRPC team requires that questions be sent to Google Groups instead, so I did this: https://groups.google.com/g/grpc-io/c/j3JvnUT7rg8

Meanwhile, do we want a `protobuf@21`?

**Comment by SMillerDev** [comment]
Seems like `protobuf@21` is the way to go

**Comment by carlocab** [comment]
gRPC can use the latest protobuf in version 1.55. https://github.com/grpc/grpc/commit/0f1afec5a8906ae3f00d58ff2499ad7e7cfb577e

**Comment by ZhongRuoyu** [comment]
protobuf 23 support has also landed, and will be backported to 1.55: https://github.com/grpc/grpc/pull/33053

**Comment by carlocab** [comment]
Cherry-picked onto #131405.

**Pull request closed without merging**
