### PR TITLE
dotnet@6 6.0.133

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
```
  libc++abi: terminating due to uncaught exception of type PAL_SEHException
```
Annoyingly, only Ventura is failing so hard to debug. I guess I can try out the Ventura bottle on Sonoma to see if it fails there (differentiating build environment vs runtime).

Could also try linking Xcode.app or `llvm`'s libc++abi instead to see if it helps.

**Comment by cho-m** [comment]
Can reproduce failure with Ventura bottle on Sonoma machine while Sonoma bottle works. Seems to be issue of how bottle was built rather than runtime.

**Comment by cho-m** [comment]
I think we should just drop the Ventura bottles and merge this. It only has a few more months to EOL so not really worth figuring out how to get problematic Xcode 15.2 to build this (given it builds on Sonoma / Xcode 15.3, it is probably a fixed bug).

**Review by p-linnane — APPROVED** [review]
Some bottles are better than none.

**Review by carlocab — APPROVED** [review]

**Comment by cho-m** [comment]
Going to merge so I can continue ICU PR.

**Pull request merged**
