### PR TITLE
clac 0.3.0 (new formula)

### PR DESCRIPTION
**Pull request by djanowski**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
Error: 3 problems in 1 formula
clac:
  * C: 2: col 9: Description shouldn't start with an indefinite article i.e. "A"
  * C: 2: col 11: Description should use "command-line" instead of "command line"
  * fully scope test shell_output calls e.g. shell_output "#{bin}/clac"
```

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
Would you mind squashing this to a single commit, to keep our commit history tidy?

**Comment by djanowski** [comment]
@apjanke Done!

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks for your contribution to Homebrew, @djanowski! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
