### PR TITLE
nettle 3.9.1

### PR DESCRIPTION
**Pull request by razvanazamfirei**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by carlocab** [comment]
Needs rebase.

**Comment by carlocab** [comment]
I'm a little unclear on why these revision bumps are needed -- `nettle` didn't bump it's SO version, so there shouldn't be any `brew linkage` failures. At least, not any that are due to `nettle`.

**Comment by razvanazamfirei** [comment]
@carlocab, the bumped formulas had linkage failures during the first few CI runs. I bumped them to try to fix it, but might have been unnecessary.

**Review by chenrui333 — APPROVED** [review]

**Comment by carlocab** [comment]
> @carlocab, the bumped formulas had linkage failures during the first few CI runs. I bumped them to try to fix it, but might have been unnecessary.

Note that it's important to distinguish between `brew linkage` failures that are errors (bad, probably needs revision bumps), and ones that are warnings (typically `brew linkage --cached --test --strict`, less bad, but revision bumps will not help). I suspect `gstreamer` was the latter kind.

**Comment by p-linnane** [comment]
@carlocab Do we want to merge this then? Or drop the revision bumps?

**Pull request merged**
