### PR TITLE
pushpin 1.38.0

### PR DESCRIPTION
**Pull request by jkarneges**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by jkarneges** [comment]
Linux build step `brew install --verbose --build-bottle pushpin` failing with:
```
Error: "No boost package found"
```

However, the earlier `brew fetch` is installing boost:
```
brew fetch --retry ... boost ...
```

Based on pushpin's `build.rs` file, the only way to get the "No boost" error message is if neither `/usr/include/boost/version.hpp` nor `/usr/local/include/boost/version.hpp` exist. Is it possible linuxbrew puts boost somewhere else?

**Comment by p-linnane** [comment]
It's not in either of those paths. You can specify it by passing `#{Formula["boost"].include}` to reference the correct directory.

**Comment by SMillerDev** [comment]
```console
    = note: /home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: cannot find -lQt5Core: No such file or directory
            /home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: cannot find -lQt5Network: No such file or directory
            collect2: error: ld returned 1 exit status
```

**Comment by jkarneges** [comment]
Finally got this working. Will clean this up and rebase soon.

**Review by chenrui333 — APPROVED** [review]

**Comment by jkarneges** [comment]
I noticed the CI arm builds succeed but don't actually do anything:

```
==> brew deps --tree --annotate --include-build --include-test pushpin
==> SKIPPED pushpin
Warning: pushpin has dependencies without compatible bottles:
  mongrel2

All steps passed!
```

Does this mean pushpin is not buildable/bottled on arm? The mongrel2 dependency is optional (and deprecated even) and could be skipped on arm.

**Comment by p-linnane** [comment]
> Does this mean pushpin is not buildable/bottled on arm? The mongrel2 dependency is optional (and deprecated even) and could be skipped on arm.

Correct. We can't build bottles for an OS if it has unbottled dependencies.

**Pull request merged**
