### PR TITLE
dafny 3.4.2

### PR DESCRIPTION
**Pull request by tchajed**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by SMillerDev** [comment]
If it's not broken we should use the Homebrew version.

**Comment by tchajed** [comment]
Well I did a quick test on my current project and it immediately failed due to a change in non-linear arithmetic reasoning from Z3. I think you should consider point releases of Z3 to be breaking changes, since the exact queries on which it succeeds do change (and it doesn't just get strictly better, unfortunately).

**Comment by carlocab** [comment]
I think we should consider deprecating this formula. I don't think its analytics (~80 monthly installs) justify the amount of extra maintenance work a `resource`d `z3` entails. But I leave this up to you, since you seem to have done most of the work of keeping this formula up-to-date.

**Comment by tchajed** [comment]
I would be pretty sad to see this go, as installing Dafny on macOS would become a manual process. One thing that might be reducing installs is that the VSCode plugin (which likely most people use) automatically downloads a binary release rather than relying on the system to have Dafny. That doesn't work for my project because I also compile and execute code from Dafny, but it would be enough to try it out and learn verification.

What is the "extra maintenance work" from this resource'd Z3? Is it just checking that the version is still up-to-date? That's something I'm quite happy to keep doing (and Amazon folks working on Dafny full-time could take that over from me I believe).

Both Dafny and F* recommend a fixed version of Z3 (see the [F* advice](https://github.com/FStarLang/FStar/blob/master/INSTALL.md#runtime-dependency-particular-version-of-z3)), distributed as a binary release, because these systems push the Z3 solver's boundaries and those boundaries are highly unstable. These systems would have a really hard time keeping up-to-date with Z3, or even worse supporting multiple versions.

**Comment by SMillerDev** [comment]
The whole problem is mostly https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#stuff-that-requires-vendored-versions-of-homebrew-formulae

And really if you are fine taking up the maintenance work for dafny a Dafny tap where it doesn't fall to the homebrew maintainers to review and maintain this seems like the best way forward.

**Review by carlocab — APPROVED** [review]
It's a bit more than just checking the version -- there are security implications from shipping outdated software.

I'm fine with this for now (though I won't argue if @SMillerDev has stronger objections), but going forward I'd really like to see the Dafny project try to support the latest version of z3. This may require working with their upstream (i.e. the z3 project) to try to provide a semi-stable API between releases, but this is really something that ought to be done.

**Pull request closed without merging**
