### PR TITLE
azure-cli 0.9.20

### PR DESCRIPTION
**Pull request by xyziemba**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by mikemcquaid** [comment]
The test is failing, looks like it may need updated: http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/653/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_azure_cli/

**Comment by xyziemba** [comment]
Fixed. Azure-cli started popping a dialog on first run, so I added a line to answer the dialog.

Should I squash the commits?

**Comment by apjanke** [comment]
I squashed the commits while pulling this, but yes, in general, audit and test fixes should be squashed into the same commits as formula version bumps.

Merged. Thank you for your contribution to Homebrew!

**Comment by DomT4** [comment]
Didn't close automatically. Closed via https://github.com/Homebrew/homebrew-core/commit/6acefe8fc6fa570d67db4d00f67069930c203ccb, for reference.

**Comment by apjanke** [comment]
> Didn't close automatically.

That's my fault. I lost the "Closes #XXXX" comment when squashing. Maybe I can adjust `brew pull` to handle that more conveniently.

**Comment by DomT4** [comment]
Yeah, noticed it was missing, just didn't want to poke you about it. It doesn't happen very often to any maintainer so we've mostly sighed at ourselves and closed manually where it does, but if you wanted to rework `brew pull` more I'm sure there'd be interest.

**Pull request closed without merging**
