### PR TITLE
pcap_dnsproxy: fix case sensitivity problem of configuration path

### PR DESCRIPTION
**Pull request by chengr28**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fix case sensitivity problem (change all paths to lowercase), this problem will make pcap_dnsproxy cannot find out the configuration location in a case sensitive file system. Please visit this [issue](https://github.com/chengr28/Pcap_DNSProxy/issues/238) to get more information, thanks a lot.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @chengr28 for the pull request!

**Comment by ilovezfs** [comment]
@fxcoudert This needed a new bottle.

**Comment by fxcoudert** [comment]
@ilovezfs for the plist?

**Comment by ilovezfs** [comment]
For the config file path. That is stored in the bottle in the .bottle directory.

**Comment by fxcoudert** [comment]
Bottle updated in https://github.com/Homebrew/homebrew-core/commit/821b4ab56abd9f6de4dcacb7f7f69711852eeadf

**Comment by ilovezfs** [comment]
Thanks!

**Pull request merged**
