### PR TITLE
astgen 2.14.0 (new formula)

### PR DESCRIPTION
**Pull request by iandinwoodie**
Signed-off-by: Ian Dinwoodie <dinwoodieian@gmail.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iandinwoodie** [comment]
@SMillerDev I have not checked the box for passing `brew audit --new <formula>` since the formula fails the notability requirement check.

**Comment by chenrui333** [comment]
there are build failures

```
  $ pkg . --no-bytecode --no-native-build --public --compress GZip --targets node16-linux-x64,node16-macos-x64,node16-win-x64,node16-macos-arm64
  > pkg@5.8.0
  compression:  GZip
  > Fetching base Node.js binaries to PKG_CACHE_PATH
  
  
  
  
  
  
  
  
  Done in 23.57s.
  Error: An exception occurred within a child process:
    TypeError: no implicit conversion of nil into String
```

**Comment by SMillerDev** [comment]
That looks like it's pulling in its own nodejs.

**Comment by iandinwoodie** [comment]
@SMillerDev you are correct; I did not notice that despite it clearly saying:

```bash
> Fetching base Node.js binaries
```

I found out the reason that node binaries were being fetched was because `vercel/pkg` uses patched node binaries for packaging executables. I've updated the formula so that `vercel/pkg` builds the patched node binaries instead of fetching them. As a result, the time spent building is comparable to the node formula.

The updated commit also addresses the build failure pointed out by @chenrui333 which was resulting from poorly formed logic in my formula.

**Comment by SMillerDev** [comment]
It really shouldn't be building it's own version of Homebrew formulae either. What do they patch and can it be upstreamed instead?

**Comment by iandinwoodie** [comment]
@SMillerDev I figured out that that the post-install packaging (which is what was utilizing the patched node binaries) is not necessary. Instead, `astgen` can be installed just the same following the instructions in the [Node for Formula Authors](https://docs.brew.sh/Node-for-Formula-Authors) guide. The resulting formula is much lighter and cleaner, and still passes its tests. The only difference is that `astgen` now has a required node dependency, but that is preferable the prior behavior in my opinion.

**Comment by iandinwoodie** [comment]
@chenrui333 gentle ping for a review if you have a chance. This fails audit due to the notability requirements, but @SMillerDev stated that this could be overridden by maintainers. This formula is a dependency of another new formula that does meet the notability requirements.

**Comment by chenrui333** [comment]
let me quickly check on some formula refinements and I think we can re-run and merge after.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
