### PR TITLE
libffi 3.3

### PR DESCRIPTION
**Pull request by plicease**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
It looks like all depending on `libffi` formulae require a revision bump:

```
conan
ecl
gforth
glib
gnu-smalltalk
gobject-introspection
guile
idris
llvm
llvm@6
llvm@7
llvm@8
micropython
moarvm
p11-kit
php
pypy
pypy3
rakudo-star
sagittarius-scheme
sslyze
yosys
```

**Comment by plicease** [comment]
CI seems stuck.  It also seems to be trying the wrong commit.

**Comment by bayandin** [comment]
CI is still building, a lot of formulae depends on libffi (directly or transitively) and CI testing them all.

At this moment it found these problems:

- `brew linkage --test duplicity`
```
Broken dependencies:
  /usr/local/opt/libffi/lib/libffi.6.dylib (libffi)
```

- `brew linkage --test gjs`
```
Broken dependencies:
  /usr/local/opt/libffi/lib/libffi.6.dylib (libffi)
```

- `brew test --verbose gst-python`
```
Testing gst-python
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200111-365-165nnfb.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gst-python.rb --verbose
==> /usr/local/opt/gstreamer/bin/gst-inspect-1.0 python

** (gst-plugin-scanner:418): CRITICAL **: 05:01:35.630: pygobject initialization failed
No such element or plugin 'python'
```

- `brew test --verbose mat2`
```
Testing mat2
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200111-24391-1epdqjb.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mat2.rb --verbose
==> /usr/local/Cellar/mat2/0.10.0/bin/mat2 -l
Traceback (most recent call last):
  File "/usr/local/Cellar/mat2/0.10.0/libexec/bin/mat2", line 14, in <module>
    from libmat2 import parser_factory, UNSUPPORTED_EXTENSIONS
  File "/usr/local/Cellar/mat2/0.10.0/lib/python3.7/site-packages/libmat2/parser_factory.py", line 31, in <module>
    __load_all_parsers()
  File "/usr/local/Cellar/mat2/0.10.0/lib/python3.7/site-packages/libmat2/parser_factory.py", line 28, in __load_all_parsers
    importlib.import_module('.' + name, package='libmat2')
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/Cellar/mat2/0.10.0/lib/python3.7/site-packages/libmat2/pdf.py", line 14, in <module>
    import gi
  File "/usr/local/opt/pygobject3/lib/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: dlopen(/usr/local/opt/pygobject3/lib/python3.7/site-packages/gi/_gi.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
  Referenced from: /usr/local/opt/pygobject3/lib/python3.7/site-packages/gi/_gi.cpython-37m-darwin.so
  Reason: image not found
```

- `brew test --verbose oclgrind`
```
Testing oclgrind
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200111-72050-hhm051.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/oclgrind.rb --verbose
==> /usr/bin/clang rot13.c -o rot13 -framework OpenCL
==> [#<Pathname:/usr/local/Cellar/oclgrind/19.10/bin/oclgrind>, "./rot13"]
1 error generated.
Error: oclgrind: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<nil>.
```

- `brew linkage --test ocrmypdf`
```
Broken dependencies:
  /usr/local/opt/libffi/lib/libffi.6.dylib (libffi)
```

- `brew linkage --test pygobject3`
```
Broken dependencies:
  /usr/local/opt/libffi/lib/libffi.6.dylib (libffi)
```

- `brew test --verbose pympress`
```
Traceback (most recent call last):
  File "/usr/local/Cellar/pympress/1.5.1/bin/pympress", line 11, in <module>
    load_entry_point('pympress==1.5.1', 'gui_scripts', 'pympress')()
  File "/usr/local/Cellar/pympress/1.5.1/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/pympress/1.5.1/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/pympress/1.5.1/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/Cellar/pympress/1.5.1/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/pympress/1.5.1/libexec/lib/python3.7/site-packages/pympress/__main__.py", line 66, in <module>
    import gi
  File "/usr/local/opt/pygobject3/lib/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: dlopen(/usr/local/opt/pygobject3/lib/python3.7/site-packages/gi/_gi.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
  Referenced from: /usr/local/opt/pygobject3/lib/python3.7/site-packages/gi/_gi.cpython-37m-darwin.so
  Reason: image not found
```

- `brew linkage --test rakudo`
```
Broken dependencies:
  /usr/local/opt/libffi/lib/libffi.6.dylib (libffi)
```

- `brew test --verbose xdot`
```
Testing xdot
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200111-89315-6n34qf.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xdot.rb --verbose
==> /usr/local/Cellar/xdot/1.1/bin/xdot --help
Traceback (most recent call last):
  File "/usr/local/Cellar/xdot/1.1/libexec/bin/xdot", line 11, in <module>
    load_entry_point('xdot==1.1', 'gui_scripts', 'xdot')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/xdot/1.1/libexec/lib/python3.7/site-packages/xdot/__init__.py", line 26, in <module>
    from . import ui
  File "/usr/local/Cellar/xdot/1.1/libexec/lib/python3.7/site-packages/xdot/ui/__init__.py", line 3, in <module>
    from .window import DotWidget, DotWindow
  File "/usr/local/Cellar/xdot/1.1/libexec/lib/python3.7/site-packages/xdot/ui/window.py", line 24, in <module>
    import gi
  File "/usr/local/lib/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/gi/_gi.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/libffi/lib/libffi.6.dylib
  Referenced from: /usr/local/lib/python3.7/site-packages/gi/_gi.cpython-37m-darwin.so
  Reason: image not found
```

**Comment by bayandin** [comment]
> It also seems to be trying the wrong commit.

It doesn't, It just GitHub sorts commits by commit date, but CI mark is added to the latest commit in you're branch (or vice versa).

**Comment by bayandin** [comment]
We have quite a lot of `brew linkage --test` fails for formulae which don't depend on `libffi` directly, does it mean that we need to add `depends_on "libffi"` to them @fxcoudert?

**Comment by fxcoudert** [comment]
@plicease hi, and thanks for helping Homebrew by creating this pull request. As this is a formula with a *lot* of dependents, and the version bump breaks ABI compatibility, testing will be slow. Please be patient (CI may take 1 or 2 days to complete), and do not force push until a full cycle has been through, and you have made significant changes. Our CI resources are limited.

> does it mean that we need to add depends_on "libffi" to them

No, they have `libffi` as indirect dependency, and link against it. There's nothing wrong with it, but it means they will have to be revision-bumped, too.

---

Right now, testing shows:

- Further revision bumps needed: `duplicity gjs ocrmypdf pygobject3 rakudo xdot`
- `mat2` and `pympress` failures are related to `pygobject3`
- `gst-python` I can't say for sure from the output, but I think it's also due to `pygobject3`
- `oclgrind` test has wrong ruby syntax 😮

**Comment by fxcoudert** [comment]
Revision bumps added, rebased on top of master. Fingers crossed…

**Comment by bayandin** [comment]
It looks like revision bump for `micropython` got lost during rebasing

**Comment by fxcoudert** [comment]
- `micropython` revision was lost, sorry
- `p11-kit` has a false-positive from a new audit
- `idris` fails to build from source
- `conan idris pypy` need `revision` before `head`

**Comment by plicease** [comment]
I wasn't sure how to interpret the diagnostics from the last round of CI.  The logs seem to be gone now.  Is it worth rebasing this on the current master and trying again?  Please let me know if I can help.

**Comment by SMillerDev** [comment]
If the logs are gone that's needed indeed.

**Comment by chenrui333** [comment]
Aborted the catalina build (since both highsierra and mojave already failed.)

**Comment by plicease** [comment]
This one seems not to have to do with libffi:

```
failed: brew audit guile --online

Stacktrace

        Error: 1 problem in 1 formula detected
guile:
  * Stable: The URL https://ftp.gnu.org/gnu/guile/guile-2.2.6.tar.xz is not reachable
```

That URL is reachable from my laptop at least.

**Pull request closed without merging**
