### PR TITLE
launch_socket_server: add default plist.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Add a default plist to launch_socket_server which does the most useful typical configuration for a Homebrew user: proxy everything on localhost:8080 to localhost:80 so you can use e.g. `nginx` on port 80 as a non-root user.

Also, while we're here, simplify installation to install all the same files using `make install` and do some general cleanup.

CC @josh @mistydemeo

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@apjanke Can you remember if the test was ever passing here on Mavericks? It looks like the CI was never green for this.

**Comment by mistydemeo** [comment]
According to the documentation it should work on 10.9, but maybe we should just set a minimum OS X tag of 10.10.

**Comment by mistydemeo** [comment]
Let's bump the revision, it'd be useful to be able to know that people with the latest version installed have the plist.

**Comment by apjanke** [comment]
> Can you remember if the test was ever passing here on Mavericks?

Sorry, don't remember.

**Pull request closed without merging**
