### PR TITLE
handbrake 1.4.1

### PR DESCRIPTION
**Pull request by zuisong**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by danielnachun** [comment]
This is probably failing because the linker flag `-framework DiskArbitration` is missing:
```
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -pipe -Wl,-S -fmessage-length=0 -Wall -arch x86_64 -g0 -O3 -mfpmath=sse -msse2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -I./libhb/ -I./contrib/include -I./contrib/include/libxml2 -o HandBrakeCLI test/parsecsv.o test/test.o ./libhb/libhandbrake.a -framework IOKit -framework CoreServices -framework CoreText -framework CoreGraphics -framework AudioToolbox -framework VideoToolbox -framework CoreMedia -framework CoreVideo -framework Foundation -L./contrib/lib -lass -lavformat -lavfilter -lavcodec -lavutil -lswresample -lpostproc -lmp3lame -ldvdnav -ldvdread -lfribidi -lswscale -lvpx -ltheoraenc -ltheoradec -lvorbis -lvorbisenc -logg -lx264 -lbluray -lfreetype -lxml2 -lbz2 -lz -ljansson -lharfbuzz -lopus -lspeex -llzma -ldav1d -lturbojpeg -lzimg -lx265 -liconv
Undefined symbols for architecture x86_64:
  "_DADiskCopyDescription", referenced from:
      _mount_get_mountpoint in libbluray.a(libbluray_la-mount_darwin.o)
  "_DADiskCreateFromBSDName", referenced from:
      _mount_get_mountpoint in libbluray.a(libbluray_la-mount_darwin.o)
  "_DASessionCreate", referenced from:
      _mount_get_mountpoint in libbluray.a(libbluray_la-mount_darwin.o)
  "_kDADiskDescriptionVolumePathKey", referenced from:
      _mount_get_mountpoint in libbluray.a(libbluray_la-mount_darwin.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [HandBrakeCLI] Error 1
```
Those missing symbols are described here:  https://developer.apple.com/documentation/diskarbitration/dadisk_h.  I'm not sure why the link doesn't add that framework.  What's the best way for us to link that framework?  Appending to `LDFLAGS`?

**Comment by SMillerDev** [comment]
I'd suggest creating an issue upstream at least.

**Comment by cho-m** [comment]
> This is probably failing because the linker flag `-framework DiskArbitration` is missing:

Applied patch with a simple fix, which worked on CI.
Also created upstream PR for it https://github.com/HandBrake/HandBrake/pull/3790 and added to comment.

ARM build is also successful.

**Review by cho-m — APPROVED** [review]
Upstream has merged PR, so I think it is safe to use patch.

**Pull request closed without merging**
