### PR TITLE
vtk 8.0.1

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
http://www.vtk.org/ still says 8.0.0

**Comment by iMichka** [comment]
https://blog.kitware.com/vtk-8-0-1-released/ :)

**Comment by ilovezfs** [comment]
That's cheating.

**Comment by iMichka** [comment]
Actually I saw it on twitter first.

They always need one day or 2 to update all the links.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
