### PR TITLE
git-interactive-rebase-tool 2.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
Error: git-interactive-rebase-tool: failed
An exception occurred within a child process:
  Timeout::Error: execution expired
```

**Comment by MitMaro** [comment]
Hey! Author of git-interactive-rebase-tool here!

I'm not surprised that the existing tests fail here. Version 2.0.0 was a breaking version and the switch from curses to Crossterm (don't worry if that means nothing) probably changed how the TTY/PTY input works from Ruby.

I am interested in getting the tool back to a working state in homebrew, so I can take a look this weekend if no one else figures it out beforehand.

**Comment by carlocab** [comment]
Thanks for taking a look, @MitMaro!

Btw, while you're here: do you mind clarifying whether your license is `GPL-3.0-only` or `GPL-3.0-or-later`?

**Comment by MitMaro** [comment]
> Btw, while you're here: do you mind clarifying whether your license is `GPL-3.0-only` or `GPL-3.0-or-later`?

Should be `GPL-3.0-or-later`. :)

**Comment by carlocab** [comment]
Thanks; I opened #70533 to update the license.

**Pull request closed without merging**
