### PR TITLE
molten-vk: disable

### PR DESCRIPTION
**Pull request by iMonZ**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This formula is outdated and broken that's why a temporary [cask](https://github.com/Homebrew/homebrew-cask/pull/98204) is created.

After the cask is merged this formula can be disabled until someone fixes the issues

### CODE REVIEW

**Comment by carlocab** [comment]
As I mentioned in #69185,

1. this formula has bottles that pass the test block (verified locally on Big Sur);
2. the current version (1.0.41) seems to have been released only last April; and,
3. the formula has about 100 monthly installs.

This means that in its current state the formula doesn't appear to be broken, nor is it anywhere near outdated enough to deprecate or disable.

However, I'm willing to see what others' opinions are on this.

**Comment by iMonZ** [comment]
> As I mentioned in #69185,
> 
> 1. this formula has bottles that pass the test block (verified locally on Big Sur);
> 2. the current version (1.0.41) seems to have been released only last April; and,
> 3. the formula has about 100 monthly installs.
> 
> This means that in its current state the formula doesn't appear to be broken, nor is it anywhere near outdated enough to deprecate or disable.
> 
> However, I'm willing to see what others' opinions are on this.

A lot of the Vulkan features are not working on BigSur on this version. (which lead to crashes)
This Vulkan version also doesn't work native with the latest apple devices (M1 Devices)
which mean that it takes longer to implement the native silicon support for a wide range.

And yes every around 2 months we get an update and April last year is outdated

That is why a cask is better in the current situation as a temporary solution.

**Comment by SMillerDev** [comment]
> This formula is outdated and broken that's why a temporary cask is created.

How can it be broken as a formula but work when compiled into a binary by upstream? That means the current version could also be fixed right?

**Comment by iMonZ** [comment]
> > This formula is outdated and broken that's why a temporary cask is created.
> 
> How can it be broken as a formula but work when compiled into a binary by upstream? That means the current version could also be fixed right?

It could be fixed but no one has done that yet. (I tried a few things like using there own dependencies script instead of cloning every repo or using recent dependencies but without any luck.)

If you are able to fix the compilation and bump the version to 1.2.162.1 this pr can be closed immediately)
Otherwise its better for everyone to disable this formula

**Comment by fxcoudert** [comment]
I strongly second @carlocab and @SMillerDev: the formula needs to be fixed, not disabled. In the meantime, we ship a version that builds and passes minimal tests on all macOS versions we have (including Apple Silicon).

**Comment by fxcoudert** [comment]
Closing, in line with the cask PR

**Comment by SMillerDev** [comment]
@iMonZ since I have no idea what is broken, how about making a PR that adds tests that catch the issues that are there for Big Sur? Then we can work from there.

**Pull request closed without merging**
