### PR TITLE
gh 2.32.0

### PR DESCRIPTION
**Pull request by vilmibm**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by vilmibm** [comment]
I'm new to this and honestly don't know what the changes to `bottle` are in the previous bump: https://github.com/Homebrew/homebrew-core/pull/134341

Why are they not in this PR? What are they? Forgive my ignorance.

**Comment by p-linnane** [comment]
This PR is building bottles for the new version of `gh`. Once a maintainer approves it, our workflows will upload the built bottles to GitHub Packages and push their hashes to this PR. Then this will be merged. So you shouldn't expect to see any changes to the bottle block until all the testing is complete and approved.

**Comment by p-linnane** [comment]
cc @mislav. Not sure if the autobump is broken here.

**Review by p-linnane — APPROVED** [review]

**Comment by vilmibm** [comment]
our autobump is indeed broken and mislav no longer works at GitHub, hence my doing the manual bump.

**Comment by p-linnane** [comment]
> our autobump is indeed broken and mislav no longer works at GitHub, hence my doing the manual bump.

Got it. Thanks for the heads up! This is good to go and should be merged shortly.

**Pull request merged**
