### PR TITLE
sshrc: delete

### LINKED ISSUE #50444: Formula 'sshrc' source disappeared, formula should be removed
The formula 'sshrc'[1] no longer works because the source repository[2] has been deleted. In fact, the whole github account has been deleted.

[1] https://github.com/Homebrew/homebrew-core/blob/master/Formula/sshrc.rb
[2] https://github.com/Russell91/sshrc

### PR DESCRIPTION
**Pull request by samford**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I noticed in the past that `sshrc` fails `brew livecheck` due to the upstream repository and release archives not existing anymore. There's an open issue for this problem (#50444), so here's a PR to address it (closes #50444).

Here's the install analytics data for `sshrc`:

| Days | Installs |
| - | - |
| 30d | 111 |
| 90d | 292 |
| 365d | 1,394 |

Apparently some people still use this even though it's not publicly available anymore.

### CODE REVIEW

**Comment by zbeekman** [comment]
So upstream completely disappeared? All traces?

**Comment by zbeekman** [comment]
In general, those usage numbers are not huge, but it still may have a pretty big impact... I guess users who have it installed will still have it installed after this, so I'm 👍 to merge.

**Comment by zbeekman** [comment]
(no sign of upstream using the Google machine either...)

**Comment by samford** [comment]
I looked through GitHub and did an outside search as well and didn't find anything too meaningful. From what I've seen, it doesn't seem like ownership was transferred to someone else or there's another fork, etc.

There's another [sshrc on GitHub](https://github.com/danrabinowitz/sshrc) with the same description ("Bring your .bashrc, .vimrc, etc. with you when you SSH") but the last commit was from six years ago.

There's [a snapshot of some of the GitHub pages in the Wayback Machine](https://web.archive.org/web/20190325123227/https://github.com/Russell91/sshrc) if you want to poke around for more information. I can look into this a bit more later when I have time if we're not satisfied with the evidence so far.

**Comment by zbeekman** [comment]
@samford I'm happy to remove this after some searching and realizing that existing users won't be impacted really, others just won't be able to install this for themselves. Generally, if things are really stable, no bugs, no problems when dependencies upgrade I'm in favor of leaving things in Homebrew. But if upstream has completely disappeared, then it should be removed. We can't even tell how it's licensed for crying outloud! (Not without wayback machine at least)

**Review by zbeekman — APPROVED** [review]
LGTM

**Comment by zbeekman** [comment]
merging 🍻

**Comment by krc** [comment]
That sucks. There is also https://github.com/amaya382/anyrc which is related, but I haven't used it yet.

**Pull request closed without merging**
