### PR TITLE
sqlite 3.36.0

### PR DESCRIPTION
**Pull request by gromgit**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by gromgit** [comment]
Wow! Such error! This is gonna take a while...

11-arm:
```
Error: 12 failed steps!
brew install --only-dependencies cake
brew install cake
brew test --retry --verbose cargo-watch
brew fetch --retry editorconfig
brew test --retry --verbose game-music-emu
brew test --retry --verbose lean
brew test --retry --verbose mathlibtools
brew test --retry --verbose monkeysphere
brew test --retry --verbose mytop
brew install --only-dependencies paket
brew install paket
brew install --only-dependencies --include-test x86_64-elf-gdb
```
11-intel:
```
Error: 18 failed steps!
brew test --retry --verbose asuka
brew test --retry --verbose cargo-watch
brew test --retry --verbose corral
brew test --retry --verbose creduce
brew test --retry --verbose game-music-emu
brew test --retry --verbose hyperkit
brew test --retry --verbose innotop
brew test --retry --verbose lean
brew test --retry --verbose llvm@7
brew test --retry --verbose llvm@8
brew test --retry --verbose llvm@9
brew test --retry --verbose mathlibtools
brew test --retry --verbose monkeysphere
brew test --retry --verbose mytop
brew test --retry --verbose openslide
brew test --retry --verbose ponyc
brew test --retry --verbose wasm-pack
brew install --only-dependencies --include-test x86_64-elf-gdb
```
10.15:
```
Error: 7 failed steps!
brew test --retry --verbose cargo-watch
brew test --retry --verbose hyperkit
brew test --retry --verbose lean
brew test --retry --verbose mathlibtools
brew test --retry --verbose subversion
brew test --retry --verbose wasm-pack
brew install --only-dependencies --include-test x86_64-elf-gdb
```
10.14:
```
Error: 8 failed steps!
brew test --retry --verbose cargo-watch
brew test --retry --verbose hyperkit
brew test --retry --verbose lean
brew test --retry --verbose mathlibtools
brew test --retry --verbose opencascade
brew test --retry --verbose swift
brew test --retry --verbose wasm-pack
brew install --only-dependencies --include-test x86_64-elf-gdb
```

**Comment by carlocab** [comment]
`mathlibtools` and `lean` is a `test-bot` bug. They depend on `coreutils`, but `coreutils` was `unlink`ed at some earlier stage.

A number of the Big Sur failures (e.g. `asuka`, `creduce`, `llvm@{7,8,9}`) have no bottles.

**Comment by carlocab** [comment]
Similar failures on #79585. Any test that failed there too is unlikely to be due to either version bump (i.e. this one or `gdbm`).

**Comment by gromgit** [comment]
Thanks much, @carlocab! Indeed, aside from those you mention, there are at least a couple more (`hyperkit` and `wasm-pack`) that are carry-overs from the last version bump (#75515). I'll reformat and annotate the failure list above, so that whoever does the next version bump gets a running start on dealing with expected failures.

**Comment by carlocab** [comment]
`game-music-emu` is a bit weird, since we do this:

https://github.com/Homebrew/homebrew-core/blob/978f0c8e049b18994f47c75789f26e8cd1dfb5a1/Formula/game-music-emu.rb#L23

It's easy enough to point this to the right dylib by adding the `RPATH`
```
MacOS.sdk_path/"usr/lib/clang/12.0.5/lib/darwin/libclang_rt.ubsan_osx_dynamic.dylib"
```
but this is fragile, as this path changes between Xcode/CLT/macOS version bumps.

`x86_64-elf-gdb` should also not be a problem given #78811.

**Comment by carlocab** [comment]
Interestingly, even the Catalina and Mojave bottles for `game-music-emu` have linkage with `libclang_rt.ubsan_osx_dynamic.dylib`.
```
❯ otool -L */lib/libgme.dylib
0.6.3_2-bigsur/lib/libgme.dylib:
        @@HOMEBREW_PREFIX@@/opt/game-music-emu/lib/libgme.0.dylib (compatibility version 0.0.0, current version 0.6.3)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
        @rpath/libclang_rt.ubsan_osx_dynamic.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
0.6.3_2-catalina/lib/libgme.dylib:
        @@HOMEBREW_PREFIX@@/opt/game-music-emu/lib/libgme.0.dylib (compatibility version 0.0.0, current version 0.6.3)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
        @rpath/libclang_rt.ubsan_osx_dynamic.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
0.6.3_2-mojave/lib/libgme.dylib:
        @@HOMEBREW_PREFIX@@/opt/game-music-emu/lib/libgme.0.dylib (compatibility version 0.0.0, current version 0.6.3)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
        @rpath/libclang_rt.ubsan_osx_dynamic.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```
It's only on Big Sur that the linker can't find the library, though. This might be why:
```
❯ for lib in */lib/libgme.dylib; do echo "$(printf '=%.0s' {1..30})\n$lib\n$(printf '=%.0s' {1..30})" && otool -l $lib | rg -A2 LC_RPATH; done
==============================
0.6.3_2-bigsur/lib/libgme.dylib
==============================
          cmd LC_RPATH
      cmdsize 32
         path @executable_path (offset 12)
--
          cmd LC_RPATH
      cmdsize 128
         path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/lib/darwin (offset 12)
==============================
0.6.3_2-catalina/lib/libgme.dylib
==============================
          cmd LC_RPATH
      cmdsize 32
         path @executable_path (offset 12)
--
          cmd LC_RPATH
      cmdsize 128
         path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/lib/darwin (offset 12)
==============================
0.6.3_2-mojave/lib/libgme.dylib
==============================
          cmd LC_RPATH
      cmdsize 32
         path @executable_path (offset 12)
--
          cmd LC_RPATH
      cmdsize 128
         path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/lib/darwin (offset 12)
```
The `LC_RPATH` entries are valid on Mojave and Catalina, but not on Big Sur (but they were correct at build-time).

**Comment by gromgit** [comment]
OK, `mytop`, `innotop` and `game-music-emu` all failed local testing (Intel Big Sur) from bottles, but I've rev-bumped all three and they pass locally now.

I suspect `ponyc` also needs a rebuild, but I ran out of space locally. Will fix that later today (0230J now).

**Comment by gromgit** [comment]
`ponyc` bottle fails locally on Intel Big Sur, despite #76829:
```
$ brew info ponyc
ponyc: stable 0.41.0 (bottled)
Object-oriented, actor-model, capabilities-secure programming language
https://www.ponylang.org/
/usr/local/Cellar/ponyc/0.41.0 (193 files, 28.4MB) *
  Poured from bottle on 2021-06-21 at 16:05:46
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ponyc.rb
License: BSD-2-Clause
==> Dependencies
Build: cmake ✔
==> Analytics
install: 69 (30 days), 405 (90 days), 1,631 (365 days)
install-on-request: 61 (30 days), 377 (90 days), 1,480 (365 days)
build-error: 0 (30 days)

$ ponyc
out of memory: : Invalid argument
Abort trap: 6
```
Rebuilding from source yields the same crash.

Also, @chenrui333 reported a 0.41.1 build failure with exactly the same symptoms: https://github.com/ponylang/ponyc/issues/3764. As suggested there, I tried wiping my existing CLT and manually reinstalling the latest CLT download (12.5), but both bottle and source builds continue failing in the same way.

I've confirmed that neither `ponyc` nor `corral` (which is just a `ponyc` dependency manager, and in fact runs the same test case) use SQLite in any way, so I propose ignoring those failures for the purpose of this PR.

**Comment by cho-m** [comment]
Looks like homepage update (#79685) caused conflict.

There is an open issue for dealing with some conflicts due to cross `binutils` (maybe v2.36.1) https://github.com/Homebrew/homebrew-core/issues/78849#issuecomment-856387840. Either setting `--libdir` or deleting files are options.

**Comment by carlocab** [comment]
Oops. Let me rebase this.

**Comment by carlocab** [comment]
ARM

```
Error: 9 failed steps!
brew install --only-dependencies cake
brew install cake
brew test --retry --verbose cargo-watch
brew test --retry --verbose lean
brew test --retry --verbose mathlibtools
brew test --retry --verbose monkeysphere
brew install --only-dependencies paket
brew install paket
brew install --only-dependencies --include-test x86_64-elf-gdb
```

Big Sur

```
Error: 14 failed steps!
brew test --retry --verbose asuka
brew test --retry --verbose cargo-watch
brew test --retry --verbose corral
brew test --retry --verbose creduce
brew test --retry --verbose hyperkit
brew test --retry --verbose lean
brew test --retry --verbose llvm@7
brew test --retry --verbose llvm@8
brew test --retry --verbose llvm@9
brew test --retry --verbose mathlibtools
brew test --retry --verbose monkeysphere
brew test --retry --verbose ponyc
brew test --retry --verbose wasm-pack
brew install --only-dependencies --include-test x86_64-elf-gdb
```

Catalina

```
Error: 7 failed steps!
brew test --retry --verbose cargo-watch
brew test --retry --verbose hyperkit
brew test --retry --verbose lean
brew test --retry --verbose mathlibtools
brew test --retry --verbose subversion
brew test --retry --verbose wasm-pack
brew install --only-dependencies --include-test x86_64-elf-gdb
```

Mojave

```
Error: 8 failed steps!
brew test --retry --verbose cargo-watch
brew test --retry --verbose hyperkit
brew test --retry --verbose lean
brew test --retry --verbose mathlibtools
brew test --retry --verbose opencascade
brew test --retry --verbose swift
brew test --retry --verbose wasm-pack
brew install --only-dependencies --include-test x86_64-elf-gdb
```

**Review by carlocab — APPROVED** [review]
LGTM. Thanks @gromgit.

**Pull request closed without merging**
