### PR TITLE
rsyslog 8.26.0

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by woodruffw** [comment]
Looks like a new dep:

```
configure: error: Package requirements (libfastjson >= 0.99.3) were not met:

No package 'libfastjson' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables JSON_C_CFLAGS
and JSON_C_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by nijikon** [comment]
Yup, just wanted to push it here to start work.

**Comment by nijikon** [comment]
rsyslog/liblogging#40

**Comment by rgerhards** [comment]
good point. Fixed one dangling issue today, should be able to craft the release very soon (today or tomorrow).

**Comment by dunn** [comment]
The new release got tagged.

**Comment by fxcoudert** [comment]
```
srutils.c:459:2: error: must use 'struct' tag to refer to type 'tm'
        tm.tv_sec = tv.tv_sec;
        ^
        struct 
srutils.c:459:4: error: expected identifier or '('
        tm.tv_sec = tv.tv_sec;
          ^
srutils.c:460:2: error: must use 'struct' tag to refer to type 'tm'
        tm.tv_nsec = tv.tv_usec * 1000;
        ^
        struct 
srutils.c:460:4: error: expected identifier or '('
        tm.tv_nsec = tv.tv_usec * 1000;
          ^
srutils.c:463:22: error: use of undeclared identifier 'tm'
        return ((long long) tm.tv_sec) * 1000 + (tm.tv_nsec / 1000000);
                            ^
srutils.c:463:43: error: use of undeclared identifier 'tm'
        return ((long long) tm.tv_sec) * 1000 + (tm.tv_nsec / 1000000);
                                                 ^
```

**Comment by fxcoudert** [comment]
*“macOS is not a supported platform for rsyslog”* says upstream.

**Comment by fxcoudert** [comment]
```
lookup.c:961:35: error: too many arguments to function call, expected 1, have 2
        pthread_setname_np(lu->reloader, reloader_thd_name);
```

This assumes Linux-style `pthread_setname_np`, which has different prototype from macOS. Trying to say we don't have it at all.

**Comment by fxcoudert** [comment]
`mmexternal.c:37:10: fatal error: 'wait.h' file not found`: next patch

**Comment by fxcoudert** [comment]
```
  CCLD     msggen
ld: unknown option: --whole-archive
```

**Comment by fxcoudert** [comment]
Reporting these fixes upstream: https://github.com/rsyslog/rsyslog/issues/1495

**Comment by fxcoudert** [comment]
```
../../runtime/glbl.h:35:10: fatal error: 'liblogging/stdlog.h' file not found
#include <liblogging/stdlog.h>
```

**Pull request closed without merging**
