### PR TITLE
ripgrep 0.10.0

### PR DESCRIPTION
**Pull request by mrclmh**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by BurntSushi** [comment]
I'm not sure how Homebrew deals with optional system dependencies, but folks will probably want to be able to use ripgrep's PCRE2 support (an opt-in feature new in `0.10.0` via the `-P` flag). Does this update allow for that?

**Comment by mmoehring** [comment]
Good point. No, this was just intended as a version bump and I have no idea how to include the optional flag. So I'm closing this PR and someone with more knowledge about Formula should create a new PR with the flags.

**Comment by BurntSushi** [comment]
@mmoehring I don't know what Homebrew's policy is on things like this, but I suspect a version bump would be a fine first step with a TODO to add PCRE2 support.

**Comment by skunkworker** [comment]
I've got a updated formula that works but should PCRE2 support be included or just optional?

**Comment by BurntSushi** [comment]
Thanks! I think I just don't know enough about Homebrew to answer unfortunately. PCRE2 is a definitively optional dependency of ripgrep itself. On the other hand, I think Homebrew packages PCRE2 so it doesn't seem like a huge burden to just require it. It would be best to try and get feedback from a Homebrew maintainer though!

**Comment by skunkworker** [comment]
I'll have the pull request with optional pcre2 support up once it's done installing and testing.

**Comment by wabain** [comment]
I don't know Homebrew in any depth but the [git formula](https://github.com/Homebrew/homebrew-core/blob/735f5f5e3d79fb663ae5818ebdab5874d3d8b442/Formula/git.rb) might be a good guide on PCRE2 integration. It seems to have it as an optional dependency.

**Comment by skunkworker** [comment]
@wabain I'm doing something similar.

**Comment by skunkworker** [comment]
https://github.com/Homebrew/homebrew-core/pull/31899

**Pull request closed without merging**
