### PR TITLE
gdbm 1.22

### PR DESCRIPTION
**Pull request by owenvoke**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
All macOS errors are pre-existing with the mathplotlib one being in @BrewTestBot.

@Homebrew/linux can we merge this?

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Linux failures look like the recurring Java-dependents problem. I don't think we even test Java-dependents on `openjdk` PRs on Linux.

**Comment by iMichka** [comment]
Yes, this can be merged. I found the issue with openjdk with the help of @Bo89, we are working on a fix. But these issues are unrelated so you can go ahead.

**Comment by SMillerDev** [comment]
Thanks @owenvoke and others!

**Comment by owenvoke** [comment]
Thanks all 👍🏻

**Pull request closed without merging**
