### PR TITLE
open-babel: minor tweaks

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Continuing my war on Java.

### CODE REVIEW

**Comment by ilovezfs** [comment]
would leave out the python changes

**Comment by DomT4** [comment]
But but backticks.

**Comment by DomT4** [comment]
Also it is actually finding `/usr/bin/python` as the interpreter 🙈, kinda rendering our dependency pointless.

**Comment by ilovezfs** [comment]
Cortisone may be an effective treatment for Domitus.

**Comment by DomT4** [comment]
Can we keep the Python changes on the basis that it is addressing an actual issue that isn't simply me being anal 😇.

**Comment by ilovezfs** [comment]
I'd rather not.

**Comment by DomT4** [comment]
So how do you want to handle the Python issue discovered? We could just remove the dependency, I guess.

**Comment by ilovezfs** [comment]
I'd leave it for now.

**Comment by DomT4** [comment]
Done. You are thoroughly depressing me this evening.

**Comment by ilovezfs** [comment]
I am confident you will recover.

**Comment by DomT4** [comment]
I'm formally closer to 30 than 20 in two days time; you can take a punt on how I'm doing this week.

**Comment by ilovezfs** [comment]
:older_man:

**Comment by DomT4** [comment]
Certainly feel it! 😅.

**Comment by ilovezfs** [comment]
https://www.youtube.com/watch?v=bfpPArfDTGw

**Comment by DomT4** [comment]
Well, it's not _that_ bad. There's healthy competition on that whole worst day so far thing.

**Comment by ilovezfs** [comment]
:tada:

**Comment by DomT4** [comment]
Ta! The last two on my list to look at are the ones you pointed out were broken:
```
portmidi --with-java
opencolorio --with-java
```

**Comment by ilovezfs** [comment]
I'd vote for :fire: those options
```
Josephs-MacBook-Pro:~ joe$ brew formula-analytics portmidi
install events in the last 30 days for portmidi
=====================================================================================================
1 | portmidi                                                                        | 2,542 | 100.00%
=====================================================================================================

install_on_request events
=====================================================================================================
1 | portmidi                                                                        | 2,198 | 100.00%
=====================================================================================================

BuildError events
=====================================================================================================
1 | portmidi                                                                            | 1 | 100.00%
=====================================================================================================
Josephs-MacBook-Pro:~ joe$ brew formula-analytics opencolorio
install events in the last 30 days for opencolorio
=====================================================================================================
1 | opencolorio                                                                       | 164 |  79.23%
2 | opencolorio --with-python                                                         |  39 |  18.84%
3 | opencolorio --with-docs --with-python                                             |   3 |   1.45%
4 | opencolorio --with-test                                                           |   1 |   0.48%
=====================================================================================================
Total                                                                                 | 207 |    100%
=====================================================================================================

install_on_request events
=====================================================================================================
1 | opencolorio                                                                        | 55 |  59.14%
2 | opencolorio --with-python                                                          | 36 |  38.71%
3 | opencolorio --with-docs --with-python                                              |  2 |   2.15%
=====================================================================================================
Total                                                                                  | 93 |    100%
=====================================================================================================

BuildError events
=====================================================================================================
1 | opencolorio                                                                         | 1 | 100.00%
=====================================================================================================
Josephs-MacBook-Pro:~ joe$ 
```

**Comment by DomT4** [comment]
Certainly makes my life easier if we just prune 'em.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-core/pull/23734

**Pull request merged**
