### PR TITLE
dvc 2.0.17

### PR DESCRIPTION
**Pull request by efiop**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Thanks, @efiop. I just noticed you use a `tabulate` resource -- that's actually provided by the `python-tabulate` formula.

Can we replace that resource with a `depends_on "python-tabulate"`? You can add `tabulate` to `exclude_packages` for `dvc` in `pypi_formula_mappings.json`.

**Comment by efiop** [comment]
@carlocab Oh, nice catch. Let me try...

**Comment by efiop** [comment]
@carlocab Adjusted. Thank you! :pray:

**Comment by carlocab** [comment]
Actually (apologies for not noticing earlier) it looks like your `protobuf` resource can also be replaced by the formula?

I'm less certain now since I don't really know `protobuf`. However, the version looks the same, and the `test` in the `protobuf` formula `import`s a Python module?

**Comment by carlocab** [comment]
ARM build succeeded, so I guess that worked.

**Comment by efiop** [comment]
@carlocab Thanks for the help!

**Comment by carlocab** [comment]
No problem. Thanks for your work on `dvc`.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
