### PR TITLE
rdiff-backup: revert from 2.4.0 to 2.2.6

### PR DESCRIPTION
**Pull request by samford**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

`rdiff-backup` 2.4.0 was erroneously published and removed sometime after the formula was upgraded. At the moment, 2.2.6 is the latest available version on PyPI. The main developer of the project has [acknowledged this issue](https://github.com/orgs/Homebrew/discussions/4882) and requested the formula be reverted to 2.2.6, as there won't be a 2.4.0 or higher release in the foreseeable future.

With that in mind, this PR downgrades the formula from 2.4.0 to 2.2.6. Per our internal discussion about how we handle downgrades, I haven't bumped the `version_scheme` here. Any users on 2.4.0 who wish to downgrade will need to run `brew reinstall rdiff-backup` after this is merged.

### CODE REVIEW

**Comment by samford** [comment]
`brew audit` is predictably failing with `stable version should not decrease (from 2.4.0 to 2.2.6)`.

How should we resolve this these days without using `version_scheme`?

**Comment by cho-m** [comment]
Only option I can think of other than `version_scheme` would be to revert to https://github.com/Homebrew/homebrew-core/commit/4603ab2cbb2c9aee34de3beb06bc237cf5d19e18 in syntax PR. And then create separate PR to apply any in-between changes (e.g. https://github.com/Homebrew/homebrew-core/commit/dd801cd432bd9651f8d99c471a21cd265a462715) perhaps with revision bump.

Cons are that it won't downgrade users and may cause issues when 2.4.0 is actually released.

**Comment by MikeMcQuaid** [comment]
> `brew audit` is predictably failing with `stable version should not decrease (from 2.4.0 to 2.2.6)`.
> 
> How should we resolve this these days without using `version_scheme`?

I think we can just try to merge without this and it won't break `master`.

If it does: we should fix this with a label tweak or something.

**Comment by MikeMcQuaid** [comment]
@SMillerDev If they haven't already upgraded: yes. If they have: not unless they `brew reinstall`.

**Comment by samford** [comment]
> I think we can just try to merge without this and it won't break `master`.

If there weren't any changes between the version bump and now, we could seemingly just do a straightforward revert and use the bottles for 2.2.6 (correct me if I'm wrong). The trouble is that we need new bottles for 2.2.6 because there were changes to the `rdiff-backup` formula in the interim time (https://github.com/Homebrew/homebrew-core/pull/151123). What @cho-m suggested above is also the only solution that I could think of within our current constraints.

> If it does: we should fix this with a label tweak or something.

That said, I was thinking that it may be nice to have a `CI-downgrade` label to skip this specific audit and allow CI to run when we need new bottles. It wouldn't be necessary when we can do a simple revert but it would save us a lot of trouble in situations like this.

I suppose the question is whether it's possible to skip that particular audit while allowing all the others to run (or how much of a challenge it would be to make that possible).

**Comment by MikeMcQuaid** [comment]
> I was thinking that it may be nice to have a `CI-downgrade` label to skip this specific audit and allow CI to run when we need new bottles.

Sounds good 👍🏻 

> I suppose the question is whether it's possible to skip that particular audit while allowing all the others to run (or how much of a challenge it would be to make that possible).

No(t yet), I think. We can in exceptional cases merge 🔴 CI but would be good to get a better solution here.

**Comment by samford** [comment]
All the pieces are now in place to skip the "stable version should not decrease" audit, so I applied the new CI-version-downgrade label and rebased this (to pick up the workflow change).

I bumped the revision in a previous PR, so this should produce 2.2.6_1 bottles at this point. Anyone on 2.4.0 who wants to downgrade after this is merged will need to run `brew reinstall rdiff-backup`.

-----

Past that, I'm not sure if we will need to manually remove the 2.4.0 bottles after this. Will there be bottle issues if/when a 2.4.0 version is released in the future? I'm also not sure how removing the bottles would impact users but I figured it was worth mentioning, at least.

**Review by SMillerDev — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks @samford! @Homebrew/maintainers If you can keep your eye out for any other times we might need to merge a 🔴 PR: it would be good to create an issue (or ideally do the work yourself) to be like @samford has been here and improve our workflow ❤️

**Pull request merged**
