### PR TITLE
eva: update sha

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

https://github.com/Homebrew/homebrew-core/actions/runs/3308140594/jobs/5460303767
relates to #113717

### CODE REVIEW

**Comment by Bo98** [comment]
This was already discussed upstream btw: https://github.com/nerdypepper/eva/issues/46#issuecomment-1286584491

**Comment by chenrui333** [comment]
> This was already discussed upstream btw: [nerdypepper/eva#46 (comment)](https://github.com/nerdypepper/eva/issues/46#issuecomment-1286584491)

Cool!

**Comment by Bo98** [comment]
Given the large time gap, and that several code changes will have been made between the original tag nand the retag, we should probably revision bump since it's effectively a new version.

**Comment by chenrui333** [comment]
> Given the large time gap, and that several code changes will have been made between the original tag and the retag, we should probably revision bump since it's effectively a new version.

let me check if they can do another release.

**Comment by chenrui333** [comment]
#115197

**Pull request closed without merging**
