### PR TITLE
rust 1.48

### PR DESCRIPTION
**Pull request by toxeus**
Bump rust to 1.48.

### CODE REVIEW

**Comment by chenrui333** [comment]
11.0
```
Error: 9 failed steps!
brew test --retry --verbose asuka
brew test --retry --verbose asuka
brew install --build-from-source deno
brew install --build-from-source echoprint-codegen
brew install --build-from-source findomain
brew test --retry --verbose ktmpl
brew test --retry --verbose kubie
brew test --retry --verbose nushell
brew install --build-from-source visp
```

10.4:

```
Error: 4 failed steps!
brew install --build-from-source findomain
brew test --retry --verbose ktmpl
brew test --retry --verbose kubie
brew test --retry --verbose nushell
```

**Comment by felixbuenemann** [comment]
With the following changes it also works on Apple Silicone (M1) without Rosetta 2:

```diff
--- rust.rb	2020-11-22 01:46:51.000000000 +0100
+++ rust.rb	2020-11-22 01:47:40.000000000 +0100
@@ -79,8 +79,17 @@
     else
       args << "--release-channel=stable"
     end
-    system "./configure", *args
-    system "make"
+    # Cross-compile arm64 with x86_64 bootstrap compiler.
+    if Hardware::CPU.arch == :arm64
+      args << "--build=x86_64-apple-darwin"
+      args << "--host=aarch64-apple-darwin"
+      args << "--target=aarch64-apple-darwin"
+      system "./configure", *args
+      system "arch", "-x86_64", "make"
+    else
+      system "./configure", *args
+      system "make"
+    end
     system "make", "install"
 
     resource("cargobootstrap").stage do
```

This uses Rosetta 2 to cross-compile to arm64.

I'm currently checking that this doesn't break the x86_64 build on arm64 systems.

**Comment by nnghuy** [comment]
> With the following changes it also works on Apple Silicone (M1) without Rosetta 2:
> 
> ```diff
> ...
> ```
> 
> This uses Rosetta 2 to cross-compile to arm64.
> 
> I'm currently checking that this doesn't break the x86_64 build on arm64 systems.

Have you built from scratch using the updated formula in this PR? It has your changes, but I'm getting an error during `arch -x86_64 make`.

```
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error

error: could not compile `std`.

To learn more, run the command again with --verbose.
command did not execute successfully: "/private/tmp/rust-20201122-13812-19nrsvy/rustc-1.48.0-src/build/x86_64-apple-darwin/stage0/bin/cargo" "build" "--target" "aarch64-apple-darwin" "-Zbinary-dep-depinfo" "-j" "8" "--release" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "/private/tmp/rust-20201122-13812-19nrsvy/rustc-1.48.0-src/library/test/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit code: 101
failed to run: /private/tmp/rust-20201122-13812-19nrsvy/rustc-1.48.0-src/build/bootstrap/debug/bootstrap build --stage 2
Build completed unsuccessfully in 0:37:37
```

Not sure if your original steps differed from the formula's somehow.

**Comment by felixbuenemann** [comment]
@nnghuy I need to retry, I ran into that issue before and reported it upstream: https://github.com/rust-lang/rust/issues/79280

However for me it went away after re-running make with `arch -x86_64`. Maybe I did another step that I forgot about, since I did quite a lot of trial and error to fix this in the debug shell when the build failed.

**Comment by toxeus** [comment]
There are packages that fail that are unrelated to this change. I'm actually not on macOS and therefore it's impossible for me to reproduce the failing cases locally. I would be thankful for some help in debugging them.

**Comment by carlocab** [comment]
The test failures may just need to be rebuilt. Try giving them a revision bump.

**Comment by carlocab** [comment]
I've picked up your commit and added it to this PR: https://github.com/Homebrew/homebrew-core/pull/66285

Hopefully, this resolves some of the failing tests.

**Comment by carlocab** [comment]
Actually, looking more closely at the logs, I don't think rebuilding them will work. Errors might have to be fixed upstream.

**Comment by fxcoudert** [comment]
Given our limited number of CI nodes, we can't test parallel PRs that build the same formula update, for large formulas (such as rust). Therefore, I am cancelling the tests here, and closing the PR, in favour of #66285

Many thanks @toxeus for starting our update process!

**Pull request closed without merging**
