### PR TITLE
icu4c bottles

### PR DESCRIPTION
**Pull request by carlocab**
These are the commits from a manual bottle upload for #88210.

Closes #88210.

### CODE REVIEW

**Comment by carlocab** [comment]
Marking as `do not merge` while I'm still uploading bottles.

**Comment by carlocab** [comment]
Note: missing from here are `sile` and `tectonic` due to merge conflicts.

**Review by Bo98 — APPROVED** [review]

**Comment by carlocab** [comment]
Oops. Not good...
```
Error: Failure while executing; `/usr/local/bin/skopeo copy --all oci:postgresql@13--13.6_1 docker://ghcr.io/homebrew/core/postgresql/13:13.6_1 --dest-creds=carlocab:******` exited with 1. Here's the output:
Getting image list signatures
Copying 6 of 6 images in list
Copying image sha256:0b8aa0b812b31963b62604824acb2704dfbb46828a523e1430840f4566f5f6b9 (1/6)
Getting image source signatures
Copying blob sha256:534d397d5c3b16a415992c92ed77be9b96f8409d3c1d9aa5edf9b6850702953d
time="2022-03-03T09:10:54+08:00" level=fatal msg="writing blob: initiating layer upload to /v2/homebrew/core/postgresql/13/blobs/uploads/ in ghcr.io: denied: permission_denied: write_package"
```

**Comment by Bo98** [comment]
Probably not necessary but I've disabled autopublish until this is merged.

If nothing else is merged in the meantime you can probably actually do a `git merge --ff-only` and it'll keep all the commits intact without needing to rebase again.

**Comment by Bo98** [comment]
> Oops. Not good...

Only BrewTestBot had access. Fixed now.

**Comment by carlocab** [comment]
> > Oops. Not good...
> 
> Only BrewTestBot had access. Fixed now.

Yup, figured that was the case. Thanks.

> Can use BrewTestBot credentials in 1Password if you want.

Oh, nice tip. I'll try that if I run into another permission failure.

**Comment by Bo98** [comment]
Fixed php@8.0 and boost@1.76 too.

**Comment by carlocab** [comment]
```
Error: Failure while executing; `/usr/local/bin/skopeo copy --all oci:swift--5.5.3 docker://ghcr.io/homebrew/core/swift:5.5.3 --dest-creds=BrewTestBot:******` exited with 1. Here's the output:
Getting image list signatures
Copying 6 of 6 images in list
Copying image sha256:b6f9b01d01b4557dd65cdfab413632737fef037524696310a53a783a1e0b9d84 (1/6)
Getting image source signatures
Copying blob sha256:cbe320f8be4b54d1db4d4d5e6d5c23587de344a713d52998b0c78e1343557b86
Copying config sha256:a33c2ae2ec1e141db96a96d9389f9f01bd735c4cac9f44073f925365ba3dfdf2
Writing manifest to image destination
Storing signatures
Copying image sha256:bb70ce161bf6ab2aaaeddef9f3d28a03d668d19eb28f957efd4bbd4217c95294 (2/6)
Getting image source signatures
Copying blob sha256:d5c9dc4810f42dde1dc4a84a33ac1353aa7365d880e5a49b692b577db5d77817
time="2022-03-03T09:37:01+08:00" level=fatal msg="writing blob: Get \"https://ghcr.io/token?account=BrewTestBot&scope=repository%3Ahomebrew%2Fcore%2Fswift%3Apull%2Cpush&service=ghcr.io\": dial tcp 20.205.243.164:443: connect: operation timed out"
```
Ugh. Trying again...

**Comment by carlocab** [comment]
```
==> Uploaded to https://github.com/orgs/homebrew/packages/container/package/core/swift
```
🎉

**Comment by carlocab** [comment]
All uploaded.

**Comment by Bo98** [comment]
pr-publish squashes commits but it doesn't really matter

**Comment by carlocab** [comment]
Oops

**Comment by cho-m** [comment]
Since we didn't test dependents on Intel macOS and Linux, probably need to check for broken linkage.

**Comment by carlocab** [comment]
The formulae that use `icu4c` and don't register as having ARM bottles with `brew unbottled` (and are therefore candidates for possible broken linkage) are:
```
autorest
aws-google-auth
binwalk
bit
bond
couchdb
couchdb-lucene
fdroidserver
gradio
kibana@6
ocrmypdf
openj9
opentsdb
pillow
trezor-agent
truffle
urweb
woob
wxpython
```
Though, I think most of these actually have ARM bottles and are unlikely to be broken.

**Comment by carlocab** [comment]
Of these, the ones that actually don't have ARM bottles are
```
bit
bond
couchdb
couchdb-lucene
gradio
kibana@6
openj9
opentsdb
truffle
urweb
```

**Pull request closed without merging**
