### PR TITLE
postgresql 11.5

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
image

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by alebcay** [comment]
`libpqxx` needs a revision bump. In addition, there's this error on Sierra and High Sierra:
```
running bootstrap script ... 2019-08-11 23:08:59.271 BST [20796] FATAL:  could not create shared memory segment: No space left on device
2019-08-11 23:08:59.271 BST [20796] DETAIL:  Failed system call was shmget(key=5432001, size=56, 03600).
2019-08-11 23:08:59.271 BST [20796] HINT:  This error does *not* mean that you have run out of disk space.  It occurs either if all available shared memory IDs have been taken, in which case you need to raise the SHMMNI parameter in your kernel, or because the system's overall limit for shared memory has been reached.
	The PostgreSQL documentation contains more information about shared memory configuration.
child process exited with exit code 1
```
This latter error is currently affecting any PR that has `postgresql` as a dependency somewhere, on Sierra and High Sierra.

**Comment by chenrui333** [comment]
@alebcay, going to bump the `libpqxx`.

**Comment by chenrui333** [comment]
squashed the changes.

**Comment by Moisan** [comment]
Thank you @chenrui333 and @alebcay !

**Pull request closed without merging**
