### PR TITLE
libsbol 2.3.2

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Test fails:

```
In file included from test.cpp:1:
In file included from /usr/local/Cellar/libsbol/2.3.2/include/sbol/sbol.h:30:
In file included from /usr/local/Cellar/libsbol/2.3.2/include/sbol/document.h:30:
In file included from /usr/local/Cellar/libsbol/2.3.2/include/sbol/componentdefinition.h:30:
/usr/local/Cellar/libsbol/2.3.2/include/sbol/component.h:32:10: fatal error: 'measurement.h' file not found
#include "measurement.h"
         ^~~~~~~~~~~~~~~
```

**Comment by igas** [comment]
@fxcoudert  I looked into it and I think it's upstream issue, reported: https://github.com/SynBioDex/libSBOL/issues/215

**Comment by Moisan** [comment]
Thank you @igas for the rebase and squashing! I didn't want to force push on your PR :).

**Comment by igas** [comment]
@Moisan you can do it next time ;)

**Pull request closed without merging**
