### PR TITLE
cpio (new formula)

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alebcay** [comment]
Should this be `keg_only`? Seeing as macOS already ships with `/usr/bin/cpio`.

**Comment by iMichka** [comment]
Agreed. I did not even realise macOs was providing it. I added the necessary line.

**Comment by iMichka** [comment]
Follow up PR in brew: https://github.com/Homebrew/brew/pull/7838

**Comment by iMichka** [comment]
@retokromer regarding `--enable-mt`:
- it's not a default flag if we need to enable it
- we would like to keep Mac and Linux formulae as close as possible 
- there is not `if OS.mac? / if OS.linux?` allowed in homebrew-core. I still need to thing about how we will handle different flags in this repo (as we want to merge the linux and Mac repos later on).

So I propose to keep it simple to begin with.

**Comment by retokromer** [comment]
@iMichka No problem! I use an alternate formula that includes it. I will try to check if/how `mt` can be compiled on macOS as well.

**Pull request closed without merging**
