### PR TITLE
v8 10.0.139.15

### PR DESCRIPTION
**Pull request by chrmoritz**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

This needs a long timeout and `v8` should be added to:
https://github.com/Homebrew/homebrew-core/blob/b4438083d1ae2192cfc655551efab5c6e8b0722c/.github/workflows/triage.yml#L137-L139

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can you make a PR for that list?

**Comment by chrmoritz** [comment]
sure: #99850

**Comment by chenrui333** [comment]
> Can you make a PR for that list?

added it into that list.

**Comment by chrmoritz** [comment]
The macOS 12 bot looks stuck though.
It should have finished 2 hours ago.

**Review by chenrui333 — APPROVED** [review]

**Comment by bayandin** [comment]
Thanks @chrmoritz 🎉

**Pull request closed without merging**
