### PR TITLE
jpeg-turbo 3.0.0

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  The following tests FAILED:
  	246 - djpeg12-shared-3x2-float-prog-cmp (Failed)
  	541 - djpeg12-static-3x2-float-prog-cmp (Failed)
  Errors while running CTest
  Output from these tests are in: /tmp/jpeg-turbo-20230703-3944-6vlzui/libjpeg-turbo-3.0.0/build/Testing/Temporary/LastTest.log
```

**Comment by chenrui333** [comment]
relates to https://github.com/libjpeg-turbo/libjpeg-turbo/issues/705

**Comment by chenrui333** [comment]
🤞

**Comment by chenrui333** [comment]
> ```
>   The following tests FAILED:
>   	246 - djpeg12-shared-3x2-float-prog-cmp (Failed)
>   	541 - djpeg12-static-3x2-float-prog-cmp (Failed)
>   Errors while running CTest
>   Output from these tests are in: /tmp/jpeg-turbo-20230703-3944-6vlzui/libjpeg-turbo-3.0.0/build/Testing/Temporary/LastTest.log
> ```

only failed on 13-arm

**Review by carlocab — APPROVED** [review]

**Pull request merged**
