### PR TITLE
git-lfs 2.9.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
On Catalina (test failure):

```
==> git init
Initialized empty Git repository in /private/tmp/git-lfs-test-20191018-42001-13u090c/.git/
==> git lfs track test
/usr/local/bin/git-lfs: /usr/local/bin/git-lfs: cannot execute binary file
```

On Mojave (build failure):
```
==> gem install ronn
Successfully installed mustache-1.1.0
Building native extensions.  This could take a while...
ERROR:  Error installing ronn:
	ERROR: Failed to build gem native extension.

    current directory: /private/tmp/git-lfs-20191018-68359-kiz07/git-lfs-2.9.0/src/github.com/git-lfs/git-lfs/.gem_home/gems/rdiscount-2.2.0.1/ext
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20191018-68371-6y65rn.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /private/tmp/git-lfs-20191018-68359-kiz07/git-lfs-2.9.0/src/github.com/git-lfs/git-lfs/.gem_home/gems/rdiscount-2.2.0.1 for inspection.
Results logged to /private/tmp/git-lfs-20191018-68359-kiz07/git-lfs-2.9.0/src/github.com/git-lfs/git-lfs/.gem_home/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1/gem_make.out
```

**Comment by chenrui333** [comment]
bump the version to v2.9.1

**Comment by Bo98** [comment]
```

**Comment by Bo98** [comment]
```
==> git lfs track test
/usr/local/bin/git-lfs: /usr/local/bin/git-lfs: cannot execute binary file
Error: git-lfs: failed
```

This might be https://github.com/Homebrew/brew/issues/6539

**Comment by chenrui333** [comment]
Circle back on this.

**Comment by chenrui333** [comment]
Tested on my catalina machine, seems working fine

$ brew test --verbose git-lfs
Testing git-lfs
/usr/bin/sandbox-exec -f /private/tmp/homebrew20191128-30869-1b6u9gm.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git-lfs.rb --verbose
==> git init
Initialized empty Git repository in /private/tmp/git-lfs-test-20191128-30870-e6ocdz/.git/
==> git lfs track test
Tracking "test"

**Comment by Bo98** [comment]
The Catalina failure is the `tar` bug. Mojave failure I think can be fixed by adjusting the SDK path (I'll check later).

**Comment by chenrui333** [comment]
Pushed a new release and rebased to master (give another try on this PR)

**Comment by fxcoudert** [comment]
On Mojave:

```
==> gem install ronn
Successfully installed mustache-1.1.1
Building native extensions.  This could take a while...
ERROR:  Error installing ronn:
	ERROR: Failed to build gem native extension.

    current directory: /private/tmp/git-lfs-20191228-50033-1a6g4ls/git-lfs-2.9.2/src/github.com/git-lfs/git-lfs/.gem_home/gems/rdiscount-2.2.0.1/ext
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20191228-50047-x6c9kn.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /private/tmp/git-lfs-20191228-50033-1a6g4ls/git-lfs-2.9.2/src/github.com/git-lfs/git-lfs/.gem_home/gems/rdiscount-2.2.0.1 for inspection.
Results logged to /private/tmp/git-lfs-20191228-50033-1a6g4ls/git-lfs-2.9.2/src/github.com/git-lfs/git-lfs/.gem_home/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1/gem_make.out
```

**Comment by bk2204** [comment]
From Googling, it looks like the problem is that we're using XCode 11 on Mojave, which installs the 10.15 SDK with Ruby 2.6 (Catalina's) development headers, not Ruby 2.3 (Mojave's).  I think the easiest way to solve this would be something like the following:

```diff
diff --git a/Formula/git-lfs.rb b/Formula/git-lfs.rb
index b88cc89fa7..c2d9bd5979 100644
--- a/Formula/git-lfs.rb
+++ b/Formula/git-lfs.rb
@@ -12,10 +12,7 @@ class GitLfs < Formula
   end
 
   depends_on "go" => :build
-  uses_from_macos "ruby"
-
-  # System Ruby uses old TLS versions no longer supported by RubyGems.
-  depends_on "ruby" => :build if MacOS.version <= :sierra
+  depends_on "ruby" => :build
 
   def install
     ENV["GIT_LFS_SHA"] = ""
```

This is completely untested, since I'm running Catalina, not Mojave, but presumably it should work.

**Comment by chenrui333** [comment]
Let me give a try.

**Comment by chenrui333** [comment]
Now it is the tar issue with the Catalina:

```
14:17:06 ==> git lfs track test
14:17:06 /usr/local/bin/git-lfs: /usr/local/bin/git-lfs: cannot execute binary file
14:17:06 Error: git-lfs: failed
14:17:06 Failed executing:
```

**Comment by chenrui333** [comment]
Relates to #6539

**Pull request closed without merging**
