### PR TITLE
apache-arrow 0.7.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
Well bummer. Still [not happy with Xcode 9](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/9381/version=sierra/testReport/junit/brew-test-bot/sierra/install_apache_arrow/).

```
INFOCompiler command: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
INFOCompiler version: Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

INFOCompiler id: AppleClang
CMake Error at cmake_modules/CompilerInfo.cmake:77 (message):
  Unknown compiler.  Version info:

  Apple LLVM version 9.0.0 (clang-900.0.37)

  Target: x86_64-apple-darwin16.7.0

  Thread model: posix

  InstalledDir:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin


Call Stack (most recent call first):
  CMakeLists.txt:253 (include)
```

**Comment by cosmo0920** [comment]
This building failure will fix in 0.7.1.
ref: https://issues.apache.org/jira/browse/ARROW-1591

**Comment by ilovezfs** [comment]
Thanks for the help @como0920!

**Pull request closed without merging**
