### PR TITLE
gpsd 3.25

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
  Missing libraries:
    unexpected (libgps.so.29)
```

**Comment by chenrui333** [comment]
```
  In file included from src/configuration.h:50,
                   from src/configuration.c:46:
  src/gpsdclient.h:64:8: error: redefinition of ‘struct fixsource_t’
     64 | struct fixsource_t {
        |        ^~~~~~~~~~~
  In file included from src/gpsdclient.h:49,
                   from src/configuration.h:50,
                   from src/configuration.c:46:
  /home/linuxbrew/.linuxbrew/include/gps.h:2714:8: note: originally defined here
   2714 | struct fixsource_t
        |        ^~~~~~~~~~~
```

**Comment by chenrui333** [comment]
raised an issue for olsrd to support gpsd 3.25, https://github.com/OLSR/olsrd/issues/118

**Comment by danielnachun** [comment]
I believe this needs some `CFLAGS` now that we are using a newer GCC.  I'm looking into the solution.

**Comment by chenrui333** [comment]
> I believe this needs some `CFLAGS` now that we are using a newer GCC. I'm looking into the solution.
> 
> EDIT: the issue might be with `gpsd` as you noted.

yeah, that is also a type definition change :)

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
