### PR TITLE
gdal 2.2.4

### PR DESCRIPTION
**Pull request by fxcoudert**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by rundel** [comment]
I was going to create a pull request for this, my version of [gdal.rb](https://github.com/rundel/homebrew-core/blob/gdal_update/Formula/gdal.rb) was based on the osgeo4mac keg if it is useful at all.

**Comment by fxcoudert** [comment]
@rundel can you point me to your version of the formula? I'd be interested to see if we can simplify, because the current one is a mess :(

**Comment by rundel** [comment]
It is here: https://github.com/rundel/homebrew-core/blob/gdal_update/Formula/gdal.rb. In  terms of clarity I don't think it is much better unfortunately.

**Comment by resistor4u** [comment]
@rundel so is the formula you posted building and working?

**Comment by rundel** [comment]
It worked in my limited testing, but I didn't try anything with mysql. I don't remember if I tried it with --with-complete.

**Comment by rundel** [comment]
It looks like this along with proj 5.0.1 resolves #25594.

**Pull request closed without merging**
