### PR TITLE
python 3.7.5

### PR DESCRIPTION
**Pull request by fxcoudert**
- Updating python to 3.7.5 (supersedes https://github.com/Homebrew/homebrew-core/pull/46002)
- Updating setuptools & pip to latest (https://github.com/Homebrew/homebrew-core/pull/46004)
- While we work on python 3.8.0: https://github.com/Homebrew/homebrew-core/pull/45337

### CODE REVIEW

**Comment by fxcoudert** [comment]
@chenrui333 if you cancel a CI job, can you put a note (here or privately on slack) as to why you cancelled it?

@BrewTestBot test this please

**Comment by chenrui333** [comment]
@fxcoudert yeah, that is very good. 

Before I aborted the build, the Mojave build already failed, the other two seems building forever (like 2 or 3 hours), that is why I aborted.

**Comment by chenrui333** [comment]
Somehow, I failed to preserve the failure log (which I should do), I will be mindful next time for sure. Thanks!

**Comment by fxcoudert** [comment]
In cases of complex builds (like this one), it may happen that we can merge even though the build is not exactly “clean” (audits that can be safely ignored, random network failures, etc). And yes, they will take a lot of time, but we shouldn't abort them unless there is a *hard* failure, i.e. something we know will definitely prevent merging.

Unless there is a strong compelling need for it, please let it finish (especially if opened by a fellow maintainer)… it would have allowed to merge this earlier.

**Pull request closed without merging**
