### PR TITLE
abseil: make bottle relocatable

### PR DESCRIPTION
**Pull request by carlocab**
See 52203dd1ff12ce953014f477abc2bfde651ac5fb and 068fcb91aa8d9b9ccf7ef17fad0f8951cd7ef28c.

-----

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by carlocab** [comment]
I _think_ this is the right way to do this for Linux. @Homebrew/linux, can one of you have a look?

See also #75449.

**Comment by carlocab** [comment]
From the bottle `json` files:
```
❯ jq '.[].bottle.cellar' <abseil--20210324.0.*.bottle.json
"any"
"any"
"any"
"any"
```

**Comment by danielnachun** [comment]
Shouldn't the `RPATH` be rewritten by `install_name_tool` on macOS?  My understanding of binary relocation is that the RPATH can be updated using `install_name_tool` on macOS and `patchelf.rb` on Linux.  The harder problem is when there are strings in the `.rodata` section of an ELF (or the equivalent location in a Mach-O on macOS), and that's why I want to implement https://github.com/Homebrew/brew/issues/10846 to fix that.

**Comment by carlocab** [comment]
I don't think we do any `RPATH` re-writing on macOS, so we rely on the build system to specify this correctly. When it doesn't, we can give it hints, but it seems we've given a suboptimal one here.

Do you do `RPATH` rewriting on Linux?

**Comment by danielnachun** [comment]
> I don't think we do any `RPATH` re-writing on macOS, so we rely on the build system to specify this correctly. When it doesn't, we can give it hints, but it seems we've given a suboptimal one here.

It looks like we sort of do this by rewriting the lib paths in https://github.com/Homebrew/brew/blob/a654730accaaadff4d28ed8678b88baed693d621/Library/Homebrew/extend/os/mac/keg_relocate.rb#L42, and then try to remove the RPATHs afterward if the lib paths no longer use them.  In theory I think we should fully rewrite the `RPATH` on macOS when pouring bottles and I will have to investigate this as part of https://github.com/Homebrew/brew/issues/10846, but that can't be changed now.  

> Do you do `RPATH` rewriting on Linux?

That is what `patchelf.rb` (and formerly the `patchelf` formula) is used for.  

> [Homebrew/brew#10846](https://github.com/Homebrew/brew/issues/10846) would be good to have, but I think that wherever we can get relocation for free, we should take it.

100% agreed on this!

**Comment by danielnachun** [comment]
My guess is that this change will have no affect on Linux either way because the RPATHs are ignored when determining a bottle cellar.  I can test this locally if you want me to just to be sure.

**Comment by carlocab** [comment]
Actually it looks like this is already relocatable on Linux:

https://github.com/Homebrew/linuxbrew-core/blob/008365c9444c63af980f2302be56f2f401536bdc/Formula/abseil.rb

I'm just more concerned about whether the specific `rpath` argument here might break anything. I suppose I could always just set it to `opt_lib`, as it is in the current version of the formula on Linux, but we don't want that on macOS as that breaks relocatability.

Knowing the correct thing to pass to `CMAKE_INSTALL_RPATH` might be useful for other formulae though.

**Comment by danielnachun** [comment]
> Actually it looks like this is already relocatable on Linux:
> 
> https://github.com/Homebrew/linuxbrew-core/blob/008365c9444c63af980f2302be56f2f401536bdc/Formula/abseil.rb
> 
> I'm just more concerned about whether the specific `rpath` argument here might break anything. I suppose I could always just set it to `opt_lib`, as it is in the current version of the formula on Linux, but we don't want that on macOS as that breaks relocatability.

I would say we should take the safe route in that case and use `opt_lib` on Linux, since it will be ignored when determining the cellar, and rewritten as needed if the user has a non-standard install prefix.

> Knowing the correct thing to pass to `CMAKE_INSTALL_RPATH` might be useful for other formulae though.

Yes, that could be useful if it improves relocatability on macOS.  It's possible that as part of https://github.com/Homebrew/brew/issues/10846 we will eventually not need to set the `RPATH` like this, but until then I think we should use this approach to eliminate "trivial" cases where the only reason a binary can't be relocated is because of the RPATH.

**Comment by carlocab** [comment]
Done.

**Comment by carlocab** [comment]
Needs the next `brew` release tag.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
