### PR TITLE
flint, glibc, oil, onefetch: separate system args

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Needed for https://github.com/Homebrew/brew/pull/10873

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Review by SMillerDev — APPROVED** [review]

**Comment by carlocab** [comment]
Looks like the Linux runner tried (and failed) to build `onefetch`. Should it be skipping that here? @iMichka

**Comment by iMichka** [comment]
You need to move the glibc formula to a separate PR as it is a linux-only formula, so that you avoid linux builds for the other formulae.

**Comment by carlocab** [comment]
> You need to move the glibc formula to a separate PR as it is a linux-only formula, so that you avoid linux builds for the other formulae.

This differs from the behaviour of the ARM runner, though. It skips formulae that haven't been bottled for ARM even if there are modified formulae an a PR that have.

**Comment by SMillerDev** [comment]
> This differs from the behaviour of the ARM runner, though. It skips formulae that haven't been bottled for ARM even if there are modified formulae an a PR that have.

Some bikeshed ding: For me this way is much preferred. Here you can at least see why/what it is doing at a glance.

**Comment by carlocab** [comment]
Would you rather the ARM runner always attempt a build then?

Not opposed to that; I'd just like to clarify. It may not even be a bad idea; our ARM runners spend a lot of time idling anyway.

**Comment by iMichka** [comment]
I though I had disabled builds for Linux when there is not bottle: https://github.com/Homebrew/homebrew-test-bot/pull/579
Looks like it did not work.

**Comment by Bo98** [comment]
> Looks like it did not work.

Because `HOMEBREW_REQUIRE_BOTTLED_LINUX` isn't set anywhere.

But `onefetch` should still work however. It appears to be a dependency bug that I'll look into.

In any case, it does not block this PR from being merged.

**Pull request merged**
