### PR TITLE
semgrep 1.82.0

### PR DESCRIPTION
**Pull request by branchv**
semgrep: migrate to `python@3.12`

### CODE REVIEW

**Comment by branchvincent** [comment]
Unrelated issue on linux:

```console
==> opam install --deps-only -y .
  Warning:  Failed checks on semgrep package definition from source at
            git+file:///tmp/semgrep-20240707-21900-rd915v#HEAD:
             warning 62: License doesn't adhere to the SPDX standard, see
                https://spdx.org/licenses/ : "LGPL-2.1"
  Warning:  Opam packages conf-gmp.4, conf-libcurl.1, conf-libev.4-12,
            conf-libpcre.1 and conf-pkg-config.3 depend on the following system
            packages that are no longer installed: libcurl4-gnutls-dev libev-dev
            libgmp-dev libpcre3-dev pkg-config
  Error:  Package conflict!
    * Missing dependency:
      - conf-libcurl.1: no longer available
  
  No solution found, exiting
```

**Comment by supergibbs** [comment]
Any update on this? VS Code extension is complaining about an outdated CLI version now and 1.81.0 was just released.

image

**Comment by branchvincent** [comment]
We need to figure out https://github.com/Homebrew/homebrew-core/pull/176636#issuecomment-2212640312, @amchiclet do by chance understand what's wrong here?

**Comment by amchiclet** [comment]
@branchvincent hey, thanks for flagging this. Let me bring it up with the team.

**Comment by amchiclet** [comment]
@branchvincent it's not obvious to the team what this might be the root cause. Sorry, it may take a while for the team to get to this. They're aware that the brew release has failed for a bit, but everyone right now seems quite occupied with other items.

I'm a little less involved in the release than before, but I'll do my best to help debug during my available time and to make it known more to the team if it doesn't get resolved and causes a lot of issues.

**Comment by amchiclet** [comment]
Also, the CI failure says that if I use the formula in this PR for homebrew on linux or WSL, it will fail. Is that correct?

**Comment by supergibbs** [comment]
> Also, the CI failure says that if I use the formula in this PR for homebrew on linux or WSL, it will fail. Is that correct?

I've only installed with homebrew on MacOS but semgrep itself definitely runs on linux

Does it have something to do with semgrep [requiring v1 here](https://github.com/semgrep/semgrep/blob/develop/semgrep.opam#L66)?

**Comment by amchiclet** [comment]
> Does it have something to do with semgrep [requiring v1 here](https://github.com/semgrep/semgrep/blob/develop/semgrep.opam#L66)?

It's possible. If I have some time, I'll test it out.

**Comment by amchiclet** [comment]
I've tried not pinning `conf-libcurl.1`, but that didn't help for me. I think I got more errors, but I forgot to log them. But more importantly, we need conf-libcurl.1; [otherwise we run into issues building for Windows](https://github.com/semgrep/semgrep/blob/5df0c5e4a089d5ce6752b3ae3ef9e24fd35e7dbf/dune-project#L511).

My hypothesis is that something happened between opam (one of the build dependencies) version 2.1.5 and 2.2.0. The [release date of 2.2.0](https://github.com/ocaml/opam/releases/tag/2.2.0) seems to be a possible explanation of the errors we are seeing just now and not earlier.

On my linux machine, pinning opam to 2.1.5 allows me to build semgrep successfully.

```
depends_on "opam" => ["2.1.5", :build]
```

I don't know if there's anything else going on or whether it will build successfully in homebrew-core's CI though. I assume it is the cause of the failure.

Ideally we would try to make our build work with the newest version of everything, but in this case, I think we're OK sticking to opam 2.1.5 meanwhile to unblock our newer releases. It's a package manager, and not a library, so that makes it a bit less bad. And I'll file a ticket to the team.

@branchvincent do you have strong oppositions against pinning opam to 2.1.5 to try to unblock this release?

The other error that @supergibbs linked seems to be something else. We probably need to try to tackle one error at a time.

**Comment by amchiclet** [comment]
Actually 2.1.6 may work. I thought 2.1.5 was the latest before 2.2.0 and only tried that.

**Comment by amchiclet** [comment]
Sadly, no luck with the version thing: https://github.com/Homebrew/homebrew-core/pull/179033

**Comment by amchiclet** [comment]
I think the brew on linux issue is resolved. Hopefully [the PR to fix that](https://github.com/Homebrew/homebrew-core/pull/179033) gets merged soon.

**Review by chenrui333 — APPROVED** [review]

**Comment by branchvincent** [comment]
@amchiclet thank you again, really appreciate you taking the time to fix this 💯 

One last thing, `semgrep` is currently pinned to [`glom~=22.1`](https://github.com/semgrep/semgrep/blob/1ba95d39097d5b6c0b5a1e17694e113503c85428/cli/setup.py#L122) which fails to build from source with python 3.12 and is [fixed](https://github.com/mahmoud/glom/commit/1f883f0db898d6b15fcc0f293225dcccc16b2a57) in the latest version. It would be great if semgrep could allow that version

**Comment by supergibbs** [comment]
> @amchiclet thank you again, really appreciate you taking the time to fix this 💯
> 
I second that, you too @branchvincent for keeping semgrep updated in brew. Thanks!

**Comment by amchiclet** [comment]
@branchvincent We appreciate you helping us move forward to python 3.12! ❤️ Not to mention, you also helped unblock a pip upgrade failure before.

Do you by any chance know if the latest glom would still work with python 3.11? Or do we also need to migrate our makefiles to work with 3.12 in one step?

**Comment by branchvincent** [comment]
@supergibbs thanks for the kind words 😄 

@amchiclet yea latest `glom` still supports and works with python 3.7+! (3.8+ after https://github.com/mahmoud/glom/pull/283)

**Pull request merged**
