### PR TITLE
apache-flink 1.7.2

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Looks like we're having trouble determining mirrors.

**Comment by alebcay** [comment]
@BrewTestBot test this please

**Comment by alebcay** [comment]
I'm not really sure how to go about fixing this, but I can replicate this issue with the current version of `apache-flink` (1.7.1).

**Comment by alebcay** [comment]
This now updates `apache-flink` to 1.7.2 and should fix the URL/mirror issue (also addressed in #37356, fixes #37256).

**Comment by fxcoudert** [comment]
Thanks @alebcay

**Pull request merged**
