### PR TITLE
kvazaar 1.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by woodruffw** [comment]
Upstream is checking to see if they're in a `git` repository for some reason?

```
==> ./autogen.sh
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
glibtoolize: copying file 'build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:64: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:65: error: possibly undefined macro: AC_MSG_ERROR
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
```

**Comment by ilovezfs** [comment]
The git error is probably a red herring. The autoconf issue is the real bug.

**Comment by ilovezfs** [comment]
It needed `depends_on "pkg-config" => :build` to get passed that.

**Comment by ilovezfs** [comment]
Now I get
```
Last 15 lines from /Users/joe/Library/Logs/Homebrew/kvazaar/test.01.kvazaar:
/usr/local/Cellar/kvazaar/1.0.0/bin/kvazaar
-i
lm20.avi
--input-res
16x16
-o
lm20.hevc

Compiled: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3
Detected: INTEL, flags: MMX SSE SSE2 SSE3 SSSE3 SSE41 SSE42 AVX AVX2
Available: avx(11) avx2(41) sse2(2) sse41(1) 
In use: avx(2) avx2(41) 
Disabling TMVP because GOP is used.
--owf=auto value set to 0.
Assertion failed: (!(children_allow_slice || children_allow_tile)), function kvz_encoder_state_init, file encoder_state-ctors_dtors.c, line 508.
Error: kvazaar: failed
Failed executing: /usr/local/Cellar/kvazaar/1.0.0/bin/kvazaar -i lm20.avi --input-res 16x16 -o lm20.hevc
```

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
The bug is caused by https://github.com/ultravideo/kvazaar/commit/19d423ab295bb53270035bc8a5c59f0298346a11.

**Comment by ilovezfs** [comment]
Reported here: https://github.com/ultravideo/kvazaar/issues/153

Still seems to be possible even with the revert, though it resolved on 2/3 of the nodes.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
