### PR TITLE
pip-audit: revert to 2.4.14

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by p-linnane — DISMISSED** [review]

**Comment by iMichka** [comment]
We updated in #121978, but that release was yanked. We are now 3 days later, proposing to bump the version scheme to get this fixed. But we can also revert without version scheme bump.

CC @woodruffw

**Review by woodruffw — DISMISSED** [review]

**Comment by woodruffw** [comment]
LGTM! Sorry about the bad version; I'll follow up to see whether this is something we can handle in livecheck (maybe respecting the yanked attr on PyPI?)

**Comment by woodruffw** [comment]
Yep, it looks like `livecheck` is somewhat naive and doesn't check the simple index response -- I'll work on a fix to handled yanked releases.

**Comment by p-linnane** [comment]
Since the bottle already exists someone with appropriate permissions will need to delete the bottles for 2.4.14 and 2.4.15.

**Comment by chenrui333** [comment]
we can do revision instead.

**Comment by samford** [comment]
> Yep, it looks like `livecheck` is somewhat naive and doesn't check the simple index response -- I'll work on a fix to handled yanked releases.

I looked into this after you mentioned it tonight and it seems like the issue may just be that the formula was updated to 2.4.15 before it was yanked. The `Pypi` strategy matches the version from the tarball link by default, which is currently the latest non-yanked version (2.4.14). Was this giving you something different previously (such that we would need to modify the `Pypi` strategy)?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
it is good now

```
==> Upgrading 1 outdated package:
pip-audit 2.4.15 -> 2.4.14_1
==> Fetching pip-audit
==> Downloading https://ghcr.io/v2/homebrew/core/pip-audit/manifests/2.4.14_1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pip-audit/blobs/sha256:f358c8f70d3e50833ef5abb8be367e8f8a3502bf70919
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:f358c8f70d3e50833ef5abb8be367e8f
######################################################################## 100.0%
==> Upgrading pip-audit
  2.4.15 -> 2.4.14_1

==> Pouring pip-audit--2.4.14_1.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/pip-audit/2.4.14_1: 1,406 files, 16.2MB
```

**Pull request closed without merging**
