### PR TITLE
kubevela 1.1.10

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> make vela-cli VELA_VERSION=1.1.9
  make: docker: Command not found
  Makefile:282: *** recipe commences before first target.  Stop.
```

**Comment by chenrui333** [comment]
@carlocab do you have any ideas that why does the linux build need `docker` but the macOS builds do not?

**Comment by carlocab** [comment]
No idea. I don't understand why `make` is calling `docker`. Probably worth reporting upstream. In the meantime, you can probably fix this by running `go build` directly, as in the `Makefile`:

https://github.com/oam-dev/kubevela/blob/34aa74ff480479ec00d274471f1b61cbcad5ca01/Makefile#L64-L65

The variables are set in https://github.com/oam-dev/kubevela/blob/34aa74ff480479ec00d274471f1b61cbcad5ca01/Makefile#L6-L12.

**Comment by chenrui333** [comment]
agree, switching to use a more native `go build`

**Review by carlocab — COMMENTED** [review]
Has the Makefile issue been reported upstream?

We should add a test to check for the version now that we're passing it via `-ldflags`.

**Comment by carlocab** [comment]
ping @chenrui333

**Comment by chenrui333** [comment]
> Has the Makefile issue been reported upstream?

sorry about the delay, reporting the issue now.

**Comment by carlocab** [comment]
Great; I think we can merge this if you add a version test in the `test` block.

**Comment by chenrui333** [comment]
yeah, doing that now. :)

**Comment by chenrui333** [comment]
the `vela version` is blocked by the kuberentes connectivity issue.

**Comment by sunny0826** [comment]
@chenrui333 @carlocab Can you merge this PR?

**Comment by carlocab** [comment]
That's a little hard to do now that it's closed and there's still changes outstanding.

But you can open a new one that includes the necessary changes and we can merge that.

**Comment by chenrui333** [comment]
Superseded by #90348

**Pull request closed without merging**
