### PR TITLE
pngpaste 1.0.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍

**Comment by ilovezfs** [comment]
1.0.1 actually looks older than 0.2.1 and development seems to be halted.

I smell :skull:

**Comment by DomT4** [comment]
Oh, that is... strange. Yeah, if you don't get a clarification from upstream I'd feel free to 💀.

**Comment by ilovezfs** [comment]
Upstream has taken down the old tags with the higher numbers now that the issue has been brought to their attention.

https://github.com/jcsalterego/pngpaste/issues/6#issuecomment-231515033

**Pull request closed without merging**
