### PR TITLE
sd-local 1.0.13 (new formula)

### PR DESCRIPTION
**Pull request by ibu1224**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

**Comment by ibu1224** [comment]
@chenrui333 
The repository to be added is a new project for the local use of the following repositories
https://github.com/screwdriver-cd/screwdriver

The services offered in the above repositories have many users.

For this PR to be merged, it must meet the following conditions?
```
GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
```

**Comment by SMillerDev** [comment]
Hi, this seems like a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by ibu1224** [comment]
@SMillerDev 
ok, thank you

**Pull request closed without merging**
