### PR TITLE
orientdb 2.2.27

### PR DESCRIPTION
**Pull request by robfrank**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@brewtestbot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
Failing with a SHA mismatch. I get the same locally.

```
==> Verifying orientdb-2.2.27.tar.gz checksum
Error: SHA256 mismatch
Expected: 948d36dd758a58473e36481e86836e4d3b7d1c5b520dc3f32840ffc4da2f425c
Actual: a368db8b1fc82613475d7b23d293d741cc012753d1d81cef1d399bddce1b7657
Archive: /Users/brew/Library/Caches/Homebrew/orientdb-2.2.27.tar.gz
```

Have they republished the file since this PR was first posted?

**Comment by robfrank** [comment]
my fault, sorry. Should I close this PR or use --force ? :
```shell
brew bump-formula-pr --strict orientdb --url=https://orientdb.com/download.php\?file\=orientdb-community-importers-2.2.27.tar.gz --sha256=a368db8b1fc82613475d7b23d293d741cc012753d1d81cef1d399bddce1b7657
Error: These open pull requests may be duplicates:
orientdb 2.2.27 https://github.com/Homebrew/homebrew-core/pull/18056
Duplicate PRs should not be opened. Use --force to override this error.
```

**Comment by dunn** [comment]
Force-pushing is fine!

**Pull request closed without merging**
