### PR TITLE
arpack 3.7.0

### PR DESCRIPTION
**Pull request by profnote**

### CODE REVIEW

**Comment by mistydemeo** [comment]
Looks like something is funny about the configure script:

```
checking for mpif.h... yes
./configure: line 25533: syntax error near unexpected token `EIGEN3,'
./configure: line 25533: `	PKG_CHECK_MODULES(EIGEN3, eigen3 >= 3.2)'
```

**Comment by alebcay** [comment]
I just messed with this a few hours ago. Needs a `depends_on "pkg-config" => :build`.

**Comment by brettkoonce** [comment]
kk, will drop.  just trying to walk some people through things, we will find a different package.

**Comment by alebcay** [comment]
No worries, just wanted to point out what the issue was.

**Comment by mistydemeo** [comment]
Updated via #37213.

**Pull request closed without merging**
