### PR TITLE
Subversion 1.11.0

### PR DESCRIPTION
**Pull request by mistydemeo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is a followup to #33530. It includes the original commit, and two further commits which fix building on macOS 10.13 with Xcode 10+:

* Reference zlib inside the MacOS SDK path. Otherwise, Subversion will add `-I/usr/include` to the `CPPFLAGS`, wreaking havoc with systems that still have that path from Xcode 9.
* Unset `SDKROOT` when building. Setting it breaks Ruby's ability to build test programs (see https://github.com/Homebrew/homebrew-core/pull/33530#issuecomment-450112779), which trips up Subversion's configure script. This doesn't appear to have any adverse effect on the rest of the build.

cc @brainy

### CODE REVIEW

**Comment by lembacon** [comment]
Once this one gets merged, we can proceed with #34649. ❤️

**Comment by lembacon** [comment]
Now fails on Sierra,

```
18:50:48 configure: error: subversion requires zlib
```

**Comment by lembacon** [comment]
It works. Thanks @mistydemeo and @brainy! ❤️

**Comment by MikeMcQuaid** [comment]
@mistydemeo Nice work on this!

> * Setting it breaks Ruby's ability to build test programs

Could this be what's causing issues with `brew style` installing `rubocop` (or anything requiring native extensions) on 10.12/10.13?

**Comment by reitermarkus** [comment]
@MikeMcQuaid, are you talking about the same problem I am thinking of? I am only aware of it affecting 10.14 though. See https://github.com/Homebrew/homebrew-cask/issues/52775#issuecomment-444545063.

**Comment by MikeMcQuaid** [comment]
@reitermarkus It could be we've seen it on 10.13 too due to an Xcode 10 bug.

**Comment by mistydemeo** [comment]
@MikeMcQuaid Reading up on that issue, I believe this one is distinct.

**Pull request closed without merging**
