### PR TITLE
less: upgrade less to 593

### PR DESCRIPTION
**Pull request by zchee**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
This doesn't appear to have been announced as a stable release from what I can see?

**Comment by zchee** [comment]
@Bo98 See https://github.com/gwsw/less/releases.
Also, try to click `Bugs and Enhancement Requests` on the https://greenwoodsoftware.com/less/index.html page. https://github.com/gwsw/less is the author of the greenwoodsoftware.com site repository.

**Comment by Bo98** [comment]
590 for example went through a beta stage between 3 June before coming stable on 10 July. Is 593 also a beta?

**Comment by zchee** [comment]
@Bo98 I don't know whether the this version is stable. I found 593 release on GitHub "less" release page, then sent PR.

Maybe we would be better to ask to @\gwsw if you certainly want to this version is stable or not.

**Comment by Moisan** [comment]
[Upstream homepage](http://greenwoodsoftware.com/less/) says
> The current released version is less-590. It was released for general use on 10 Jul 2021.

**Pull request closed without merging**
