### PR TITLE
subfinder 2.5.0

### PR DESCRIPTION
**Pull request by bevanjkay**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
```
  [INF] Loading the default
  [FTL] Could not read providers from /Users/brew/.config/subfinder/provider-config.yaml: open /Users/brew/.config/subfinder/provider-config.yaml: no such file or directory
```

**Comment by bevanjkay** [comment]
@cho-m I'm not sure what to do here. I can get the tests working locally, but the binary has to be run twice before it will output correctly.
The first run generates a config file, and then the second migrates the config file to a new format and continues. This doesn't seem to happen in the testpath.

**Comment by cho-m** [comment]
Not sure what is best way to proceed.

Also, it looks like `subfinder` is using `/Users/brew/.config/...` even though we try to isolate tests to `HOME=#{testpath}`. Could be that following code isn't impacted by `HOME` environment variable https://github.com/projectdiscovery/subfinder/blob/v2.5.0/v2/pkg/runner/options.go#L258-L264
```go
func userHomeDir() string {
	usr, err := user.Current()
	if err != nil {
		gologger.Fatal().Msgf("Could not get user home directory: %s\n", err)
	}
	return usr.HomeDir
}
```

This may be related to test results in CI.

---

The change in behavior seems to be from https://github.com/projectdiscovery/subfinder/pull/498

Homebrew's existing test checked that running `subfinder` autogenerated the `config.yaml` and then outputted result. Now, it looks like there is failure if neither `config.yaml` nor `provider-config.yaml` exist (though the code to autogenerate `config.yaml` still exists).

We could change testcase to create a local `provider-config.yaml` (or `config.yaml`), use `-pc`/`-provider-config` (or `-config` for older YAML) to load it, and verify the output results.

**Comment by cho-m** [comment]
Not sure what is best way to proceed.

Also, it looks like `subfinder` is using `/Users/brew/.config/...` even though we try to isolate tests to `HOME=#{testpath}`. Could be that following code isn't impacted by `HOME` environment variable https://github.com/projectdiscovery/subfinder/blob/v2.5.0/v2/pkg/runner/options.go#L258-L264
```go
func userHomeDir() string {
	usr, err := user.Current()
	if err != nil {
		gologger.Fatal().Msgf("Could not get user home directory: %s\n", err)
	}
	return usr.HomeDir
}
```

This may be related to test results in CI.

---

The change in behavior seems to be from https://github.com/projectdiscovery/subfinder/pull/498

Homebrew's existing test checked that running `subfinder` autogenerated the `config.yaml` and then outputted result. Now, it looks like there is failure if neither `config.yaml` nor `provider-config.yaml` exist (though the code to autogenerate `config.yaml` still exists).

We could change testcase to create a local `provider-config.yaml` (or `config.yaml`), use `-pc`/`-provider-config` (or `-config` for older YAML) to load it, and verify the output results.

**Comment by bevanjkay** [comment]
@cho-m It seems that the test fails for the other assertion also (`subfinder brew.sh` expects to see `docs.brew.sh`) - because the config file is not yet generated, so the command returns an error instead.

**Comment by cho-m** [comment]
The problem is the inconsistent home directory.

`subfinder` always looks for default configs in user's directory (e.g. `/Users/$USER/.config/subfinder/` on macOS), but it writes to `$HOME/.config/subfinder/`. 

Since Homebrew overrides `HOME`, it means the autogenerated `#{testpath}/.config/subfinder/config.yaml` is not found.

**Pull request closed without merging**
