### PR TITLE
*: Stop using `head?` conditionals in test blocks

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

- I thought it didn't make much sense to have `head?` conditionals in test blocks since we don't test `HEAD` builds on CI, and the formulae test blocks are mostly for CI confidence.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Makes sense to me but interested if other @homebrew/core folks disagree.

**Review by chenrui333 — APPROVED** [review]
make sense 👍

**Comment by MikeMcQuaid** [comment]
Let's hold off merging until some other folks have a chance to give input (e.g. until tomorrow UK time)

**Comment by MikeMcQuaid** [comment]
Making a draft so @BrewTestBot leaves it alone until tomorrow. Naughty 🤖 !

**Comment by carlocab** [comment]
`build.head?` can be removed, it's definitely nonsense.

I'm less certain about `head?`. In theory, `--HEAD` installs are ideally for upstream to use to test their builds so they can do something like `brew install --HEAD foo && brew test foo` in their CI. In practice, almost no upstream maintainers do this (I can think of maybe 2, but not necessarily in CI).

This means that the impact of removing it is likely small, so it maybe doesn't hurt too much. OTOH, we probably want to be nice to upstream maintainers that do rely on it, if any.

**Comment by MikeMcQuaid** [comment]
> `build.head?` can be removed, it's definitely nonsense.

That is just `brew test --HEAD` or not, right?

> OTOH, we probably want to be nice to upstream maintainers that do rely on it, if any.

Agreed. A middle ground here could be: we remove them all, if upstream specifically requests that we re-add them: we re-add with a comment linking to them asking for it. How's that sound @carlocab?

**Comment by carlocab** [comment]
> > `build.head?` can be removed, it's definitely nonsense.
> 
> That is just `brew test --HEAD` or not, right?

Huh, maybe 😅. Can't remember if I tested that or not when I was looking at `build.head?` usage in `test` blocks. Though not sure why it would be needed if you just used `head?` instead.

> > OTOH, we probably want to be nice to upstream maintainers that do rely on it, if any.
> 
> Agreed. A middle ground here could be: we remove them all, if upstream specifically requests that we re-add them: we re-add with a comment linking to them asking for it. How's that sound @carlocab?

Yes, sounds fine to me.

**Review by p-linnane — APPROVED** [review]

**Comment by branchvincent** [comment]
Works for me, we could also remove the inverse: [`build.stable?`](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-core+%2Ftest+do%5Cn%28.%7C%5Cn%29*%28head%7Cstable%29%5C%3F%2F&type=code&p=1)

**Comment by MikeMcQuaid** [comment]
Thanks again @issyl0!

**Comment by issyl0** [comment]
> Works for me, we could also remove the inverse: [`build.stable?`](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-core+%2Ftest+do%5Cn%28.%7C%5Cn%29*%28head%7Cstable%29%5C%3F%2F&type=code&p=1)

I'll get on it!

**Comment by chenrui333** [comment]
yeah, I almost never find myself using build.head for tests, nor have I seen anyone else use it either.

**Pull request merged**
