### PR TITLE
Migrate airshare to python@3.9

### PR DESCRIPTION
**Pull request by fxcoudert**
First try of a script to migrate formulas to python 3.9

### CODE REVIEW

**Comment by Rylan12** [comment]
```
==> python3.9 -s /private/tmp/airshare--homebrew-virtualenv-20201006-28967-iy8m9f/target/bin/virtualenv -p python3.9 /usr/local/Cellar/airshare/0.1.6_1/libexec
Already using interpreter /usr/local/opt/python@3.9/bin/python3.9
Using base prefix '/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9'
New python executable in /usr/local/Cellar/airshare/0.1.6_1/libexec/bin/python3.9
Also creating executable in /usr/local/Cellar/airshare/0.1.6_1/libexec/bin/python
ERROR: The executable /usr/local/Cellar/airshare/0.1.6_1/libexec/bin/python3.9 is not functioning
ERROR: It thinks sys.prefix is '/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9' (should be '/usr/local/Cellar/airshare/0.1.6_1/libexec')
ERROR: virtualenv is not compatible with this system or executable
```

So it looks like `virtualenv` 16.4.7 is not compatible with Python 3.9. I've checked locally, `virtualenv` 16.4.10 (the latest version that's below 20.0.0) doesn't work either. 

We may need to update the `homebrew-virtualenv` resource to 20.0.33. It was briefly discussed here: https://github.com/Homebrew/brew/pull/8379#discussion_r472935656

**Comment by fxcoudert** [comment]
I'm re-running CI, to check the `virtualenv` fix at https://github.com/Homebrew/brew/pull/8873
Even if CI is green, this should not be merged before the next Brew tag ships, expected on Monday 2020-10-12.

**Comment by fxcoudert** [comment]
Test failed on 10.15 only, probably a network fluke or certificate issue:

```
ConnectionRefusedError: [Errno 61] Connection refused
```

**Comment by fxcoudert** [comment]
I tried re-running the tests, but it's giving tons of unrelated audits:
`GitHub patches should end with .patch, not .diff`

**Pull request closed without merging**
