### PR TITLE
erlang: Fix issue of openssl version

### PR DESCRIPTION
**Pull request by zacky1972**
Erlang/OTP 25.1+ recommends to use openssl@3 instead of openssl@1.1. So, this PR changes the dependency of erlang onto openssl@3.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

erlang: Fix issue of openssl version

Erlang/OTP 25.1+ recommends to use openssl@3 instead of openssl@1.1.
So, this PR changes the dependency of erlang onto openssl@3.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
@zacky1972 I've just inspected `tsung`. It does not link with any `openssl` (in fact, it provides no binary files other than erlang beam files). So, we should be able to get rid of the audit failure by adding `tsung` to `audit_exceptions/versioned_dependencies_conflicts_allowlist.json`. Could you do this and resurrect the PR?

**Comment by zacky1972** [comment]
Failed: 

```
could not write file '../specs/erl_prim_loader.specs': no such file or directory
```

I'm investigating this, now.

**Comment by zacky1972** [comment]
Hmm, 

Fail to `brew install --verbose --build-bottle erlang`, but my environment (macOS 13 arm64) does not reproduce this.

> GEN	../specs/specs_erl_prim_loader.xml
>  could not write file '../specs/erl_prim_loader.specs': no such file or directory
>  make[2]: *** [../specs/specs_erl_prim_loader.xml] Error 2
>  make[1]: *** [docs] Error 2
>  make: *** [docs] Error 2

Can anyone help me?

**Comment by carlocab** [comment]
By the way, could you squash the two commits that modify `ejabberd` together?

**Pull request closed without merging**
