### PR TITLE
wireguard-tools 0.0.20180202

### PR DESCRIPTION
**Pull request by zx2c4**
Simple version bump.

```
  * curve25519-fiat32: uninline certain functions
  
  This results in much smaller code size and significanat speed gains on smaller
  hardware.
  
  * poly1305: add poly-specific self-tests
  
  Poly is easy to get wrong, so we've added quite a few tests that examine
  certain edge cases and places where other implementations of historically
  failed.
  
  * tools: dedup secret normalization
  * tools: share curve25519 implementations with kernel
  * contrib: keygen-html: share curve25519 implementation with kernel
  
  There is now only one place where we ship 25519 code.
  
  * qemu: disable PIE for compilation
  * qemu: disable AVX-512 in userland
  * qemu: update base versions
  
  Test suite enhancements.
  
  * device: let udev know what kind of device we are
  
  This enables folks to query the device type via udev, which is what systemd's
  networkctl uses.
  
  * tools: fread doesn't change errno
  
  This fixes clearing pre-shared keys on old glibc.
  
  * chacha20poly1305: use existing rol32 function
  * chacha20poly1305: better buffer alignment
  
  Small enhancements.
  
  * curve25519: verify that specialized basepoint implementations are correct
  
  Since some implementations have a specialized function for computing
  basepoints, it's important to do some basic sanity checking with them.
  
  * curve25519: replace hacl64 with fiat64
  
  For about 24 hours, fiat64 was faster.
  
  * curve25519: replace fiat64 with faster hacl64
  
  Then hacl64 caught up, so we moved back to it.
  
  * curve25519: break more things with more test cases
  
  These extra test cases help break the current "rfc7748_precomputed"
  implementation, which we're not using here at the moment, but it is still
  useful to ensure that we don't fall victim to the same bugs.
```

### CODE REVIEW

**Comment by ilovezfs** [comment]
As noted in https://github.com/Homebrew/homebrew-core/pull/23063 the build now fails on macOS. Please report this bug upstream if you'd like to see it upgraded in Homebrew.

**Comment by zx2c4** [comment]
I didn't know that. Please report these issues upstream next time, or simply @ me into the report.

**Comment by zx2c4** [comment]
Do you have a useful build log you could give me so I can diagnose the error?

**Comment by ilovezfs** [comment]
@zx2c4 I was planning on it. I just haven't had a chance yet.  The build log is here:
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/17844/version=high_sierra/console

locally,
```
==> Downloading https://git.zx2c4.com/WireGuard/snapshot/WireGuard-0.0.20180202.tar.xz
Already downloaded: /Users/joe/Library/Caches/Homebrew/wireguard-tools-0.0.20180202.tar.xz
==> Verifying wireguard-tools-0.0.20180202.tar.xz checksum
tar xJf /Users/joe/Library/Caches/Homebrew/wireguard-tools-0.0.20180202.tar.xz
==> make BASHCOMPDIR=/usr/local/Cellar/wireguard-tools/0.0.20180202/etc/bash_completion.d WITH_BASHCOMPLETION=yes WITH_WGQUICK=no WITH_SYSTEMDUNITS=no PREFIX=/usr/local/Cellar/wireguard-tools/0.0.20180202 -C src/tools install
  CC      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/wg.o
  CC      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/config.o
  CC      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/curve25519.o
curve25519.c:10:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^
1 error generated.
make: *** [curve25519.o] Error 1
```

and if that is changed from endian.h to machine/endian.h (or even I think `sys/types.h` which includes machine/endian.h we get)

```
bash-3.2$ make BASHCOMPDIR=/usr/local/Cellar/wireguard-tools/0.0.20180202/etc/bash_completion.d WITH_BASHCOMPLETION=yes WITH_WGQUICK=no WITH_SYSTEMDUNITS=no PREFIX=/usr/local/Cellar/wireguard-tools/0.0.20180202 -C src/tools install
  CC      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/curve25519.o
  CC      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/encoding.o
  CC      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/genkey.o
  CC      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/ipc.o
  CC      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/mnlg.o
  CC      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/pubkey.o
  CC      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/set.o
  CC      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/setconf.o
  CC      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/show.o
  CC      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/showconf.o
  CC      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/terminal.o
  LD      /private/tmp/wireguard-tools-20180203-65458-1ar7nqb/WireGuard-0.0.20180202/src/tools/wg
Undefined symbols for architecture x86_64:
  "_htole64", referenced from:
      _curve25519_generic in curve25519.o
  "_le64toh", referenced from:
      _curve25519_generic in curve25519.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [wg] Error 1
```

A fix will involve something like https://gist.github.com/panzi/6856583#file-portable_endian-h-L20-L42

which defines the missing macros.

**Comment by zx2c4** [comment]
@ilovezfs Thanks for the report. You can incorporate this upstream patch into the recipe until the next snapshot, which should fix the issue: https://git.zx2c4.com/WireGuard/patch/?id=d99954e0376d50c31f052cd6455e8665d9d9dd66

**Comment by zx2c4** [comment]
Great, thanks for bumping. Looks like the CI build succeeded and this can now be merged.

**Comment by ilovezfs** [comment]
@zx2c4 actually the patch needs to go in https://github.com/Homebrew/formula-patches because the checksums of cgit patches are not stable due to the signature at the bottom, which can randomly change :(

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks again @zx2c4! Shipped.

**Comment by zx2c4** [comment]
Great, thanks!

**Comment by ilovezfs** [comment]
You're welcome! Sorry for not reporting it.

**Pull request closed without merging**
