### PR TITLE
open-mpi 4.0.0

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by apjanke** [comment]
scalapack builds are failing due to a link error.

```
CMakeFiles/scalapack.dir/SRC/dlamov.c.o CMakeFiles/scalapack.dir/SRC/zlamov.c.o -L/usr/local/opt/veclibfort/lib -lvecLibFort -L/usr/local/opt/veclibfort/lib -lvecLibFort 
Undefined symbols for architecture x86_64:
  "_MPI_Attr_get", referenced from:
      _blacs_get_ in blacs_get_.c.o
      _Cblacs_get in blacs_get_-C.c.o
  "_MPI_Type_struct", referenced from:
      _igamx2d_ in igamx2d_.c.o
      _sgamx2d_ in sgamx2d_.c.o
      _dgamx2d_ in dgamx2d_.c.o
      _cgamx2d_ in cgamx2d_.c.o
      _zgamx2d_ in zgamx2d_.c.o
      _igamn2d_ in igamn2d_.c.o
      _sgamn2d_ in sgamn2d_.c.o
      ...
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libscalapack.dylib] Error 1
make[1]: *** [CMakeFiles/scalapack.dir/all] Error 2
make: *** [all] Error 2

```

cp2k builds are failing because the sourceforge download URL is 404. #34992 will fix.

```
        ==> Downloading https://downloads.sourceforge.net/project/cp2k/cp2k-5.1.tar.bz2
curl: (22) The requested URL returned error: 404 Not Found
==> Retrying download
==> Downloading https://downloads.sourceforge.net/project/cp2k/cp2k-5.1.tar.bz2
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "cp2k"
Download failed: https://downloads.sourceforge.net/project/cp2k/cp2k-5.1.tar.bz2
```

nwchem is also failing due to the scalapack 404 error.

**Comment by apjanke** [comment]
Yeah, exported symbols changed:

Before:

```
[/usr/local/opt/open-mpi]
$ grep -r _MPI_Attr_get *
Binary file lib/libmpi.40.dylib matches
Binary file lib/libmpi.dylib matches
[/usr/local/opt/open-mpi]
$ grep -r _MPI_Type_struct *
Binary file lib/libmpi.40.dylib matches
Binary file lib/libmpi.dylib matches
```
After:
```
[/usr/local/opt/open-mpi]
$ grep -r _MPI_Attr_get *
[/usr/local/opt/open-mpi]
$ grep -r _MPI_Type_struct *
[/usr/local/opt/open-mpi]
$
```

Looking at doco pages for [MPI_Attr_get](https://www.open-mpi.org/doc/v2.0/man3/MPI_Attr_get.3.php) and [MPI_Type_struct](https://www.open-mpi.org/doc/v3.1/man3/MPI_Type_struct.3.php), they're deprecated; I guess open-mpi 4.0.0 is when they actually got removed. Sounds like upstream scalapack may need to be updated for open-mpi 4.0/MPI-3.0 compatibility? FAQ about legacy build failures with Open MPI 4.0 is [here](https://www.open-mpi.org/faq/?category=mpi-removed).

The references are in the BLACS library included with scalapack. Doesn't look like BLACS has been updated in quite a while.

Related upstream bug reports in Open-MPI:
* https://github.com/open-mpi/ompi/issues/6149
* https://github.com/open-mpi/ompi/issues/6114

Reading through these, the removal of these symbols may have been unintentional. If I'm looking at the dates right, the fixes for those issues did not make it in to Open-MPI 4.0.0.

Using the `--enable-mpi-compatibility` switch in the openmpi build does not fix this.

**Comment by apjanke** [comment]
After reading through all their FAQs and stuff, I'm now pretty confident that:
* The removal of the symbols in the dylib (as opposed to just the prototypes in `mpi.h`) is a bug in Open MPI 4.0.0.
* We should use the `--enable-mpi1-compatibility` option to get stuff building against Open MPI 4.0.0 in this PR.
* The need for `--enable-mpi1-compatibility` will go away in 4.0.1 when they fix this regression.

**Comment by Moisan** [comment]
Thanks a lot @apjanke for all the investigation on this!

**Pull request closed without merging**
