### PR TITLE
poppler 0.68.0

### PR DESCRIPTION
**Pull request by DomT4**

### CODE REVIEW

**Comment by DomT4** [comment]
Super.

```
[  9%] Building CXX object CMakeFiles/poppler.dir/fofi/FoFiEncodings.cc.o
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -Dpoppler_EXPORTS -I/tmp/poppler-20180822-26497-ef488y/poppler-0.68.0 -I/tmp/poppler-20180822-26497-ef488y/poppler-0.68.0/fofi -I/tmp/poppler-20180822-26497-ef488y/poppler-0.68.0/goo -I/tmp/poppler-20180822-26497-ef488y/poppler-0.68.0/poppler -I/usr/local/include -I/usr/local/include/freetype2 -I/usr/local/include/openjpeg-2.3  -DNDEBUG -fPIC   -std=c++11 -o CMakeFiles/poppler.dir/fofi/FoFiEncodings.cc.o -c /tmp/poppler-20180822-26497-ef488y/poppler-0.68.0/fofi/FoFiEncodings.cc
/tmp/poppler-20180822-26497-ef488y/poppler-0.68.0/goo/JpegWriter.cc:146:39: error: assigning to 'boolean' from incompatible type 'bool'
  priv->cinfo.optimize_coding = priv->optimize;
                                ~~~~~~^~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/poppler.dir/goo/JpegWriter.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/poppler.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by edporras** [comment]
Hi, I've submitted a PR to the poppler team. Well, I'm new to gitlab so I think that's what I did 😀. See: https://gitlab.freedesktop.org/poppler/poppler/merge_requests/18

**Comment by DomT4** [comment]
Nice! That seems to work for me locally so I've pushed it in this PR to see if CI is happy as well. Thanks for looking at this @edporras 🍻

**Comment by DomT4** [comment]
Merged. Thank you again for the giant assist @edporras!

**Comment by edporras** [comment]
The [PR (or MR, I guess)](https://gitlab.freedesktop.org/poppler/poppler/merge_requests/18) was finally approved for poppler but one of the devs mentioned the problem is caused because homebrew is using `libjpeg` instead of [libjpeg-turbo](https://github.com/Homebrew/homebrew-core/blob/master/Formula/jpeg-turbo.rb). I haven't looked but I assume the latter does not define `boolean` as a `typedef enum` which seems to be the root of the problem and he seemed to hint that most linuxes are now using the latter as the default due to performance. Perhaps we can switch brew's poppler to use it with an option to fallback to `libjpeg`?

**Comment by DomT4** [comment]
I know Debian have and I'm not opposed to moving Homebrew's default `jpeg` provider over to `libjpeg-turbo`, but such a move basically involves testing every single formula that uses `jpeg` for compatibility and then moving them all over with `revision` bumps, which is... a bit of a process.

It's difficult to do it piecemeal, because generally having two libraries doing the same thing in a recursive dependency tree is asking for trouble, so even with `poppler` we're talking about making sure all of these formulae are using `libjpeg-turbo` as well:
```
diff-pdf
efl
evince
mat
nuxeo
pdf2svg
pdfgrep
pdfpc
pdfsandwich
pdftoedn
pdftoipe
pqiv
vips
```
and then everything that `brew uses --recursive` those formulae as well, and then you start to see why it's a huge PITA 😅.

**Pull request closed without merging**
