### PR TITLE
Azure CLI 2.30.0

### PR DESCRIPTION
**Pull request by azclibot**
The latest release of the Azure CLI

### CODE REVIEW

**Comment by carlocab** [comment]
I'm not sure we want to migrate this to Python 3.10 yet, as @azclibot will just change that back to Python 3.9 at the next version bump.

See #78022, https://github.com/Azure/azure-cli/blob/46cc1357893c3a7231a55aa6b24c8e2ee8a9081d/scripts/release/homebrew/docker/formula_template.txt#L20

**Comment by jiasli** [comment]
Can we keep Python 3.9 for now and get it merged first? We will support Python 3.10 asap: https://github.com/Azure/azure-cli/issues/19857

**Comment by carlocab** [comment]
@jiasli do you mean we should merge this as-is, or change it back to `python@3.9` and then merge this?

If we merge this as-is then the dependency gets changed to `python@3.10`.

**Comment by jiasli** [comment]
Please revert to 3.9, as https://github.com/Homebrew/homebrew-core/pull/88586/commits/75b9fdf0498ff4b13c3305cdc9ba7669d7716c3a does. https://github.com/Homebrew/homebrew-core/pull/88586/commits/512a1a8956ec90b7be9ff175836d1ae6b7210d15 is not submitted by us and should be reverted.

**Comment by carlocab** [comment]
75b9fdf0498ff4b13c3305cdc9ba7669d7716c3a changes the bottle block, so that will need to be fixed.

**Comment by branchvincent** [comment]
reverted and apologies, I saw https://github.com/Azure/azure-cli/pull/20041 referencing #86758 and assumed 3.10 support was ready

**Review by carlocab — APPROVED** [review]

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
