### PR TITLE
buku: migrate to `python@3.12`

### PR DESCRIPTION
**Pull request by chenrui333**
buku: migrate to `python@3.12`

### CODE REVIEW

**Comment by chenrui333** [comment]
`    ModuleNotFoundError: No module named 'imp'`

**Comment by chenrui333** [comment]
- https://github.com/Knio/dominate/issues/182

**Comment by chenrui333** [comment]
wait for the new release for this PR change, https://github.com/Knio/dominate/pull/184

**Comment by Knio** [comment]
published 2.9.0

**Comment by chenrui333** [comment]
> published 2.9.0

@Knio thanks for the new release, it works for me in my local build.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
