### PR TITLE
jasper 4.0.0

### PR DESCRIPTION
**Pull request by SMillerDev**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
somehow it is referencing the qt `6.4.0_1` which does not exist. 

```
  ==> Downloading https://ghcr.io/v2/homebrew/core/qt/manifests/6.4.0_1
  curl: (22) The requested URL returned error: 404
  Error: cpi: Failed to download resource "qt_bottle_manifest"
```

**Comment by chenrui333** [comment]
ok, this (`qt: revision bump (jasper 4.0.0)`) did not get built for linux, weird.

**Comment by chenrui333** [comment]
Give it another shot.

**Comment by cho-m** [comment]
Cancelling as `qt` failed again even with self-hosted runner. Running out of space:
`/tmp/qt-20221109-127700-ir3mjm/qt-everywhere-src-6.4.0/qtdeclarative/src/quick/scenegraph/util/qsgvertexcolormaterial.h:21:2: fatal error: cannot write PCH file: No space left on device`

**Comment by cho-m** [comment]
`pyqt` is failing via dependent testing. Looks like it ended up hardcoding `sip` python path. Will revert some changes from my PR #115811 as it is probably due to installing `sip` into venv
```
  ==> Testing pyqt
  ==> /opt/homebrew/Cellar/pyqt/6.4.0/bin/pyuic6 -V
  /opt/homebrew/Cellar/pyqt/6.4.0/bin/pyuic6: line 2: /opt/homebrew/Cellar/sip/6.7.4_1/libexec/bin/python3.11: No such file or directory
  /opt/homebrew/Cellar/pyqt/6.4.0/bin/pyuic6: line 2: exec: /opt/homebrew/Cellar/sip/6.7.4_1/libexec/bin/python3.11: cannot execute: No such file or directory
```

**Comment by cho-m** [comment]
Linux no longer fails to build `qt`, but now fails on `ufraw`:
```
  In file included from /home/linuxbrew/.linuxbrew/Cellar/glib/2.74.0/include/glib-2.0/glib/glib-typeof.h:41,
                   from /home/linuxbrew/.linuxbrew/Cellar/glib/2.74.0/include/glib-2.0/glib/gatomic.h:30,
                   from /home/linuxbrew/.linuxbrew/Cellar/glib/2.74.0/include/glib-2.0/glib/gthread.h:34,
                   from /home/linuxbrew/.linuxbrew/Cellar/glib/2.74.0/include/glib-2.0/glib/gasyncqueue.h:34,
                   from /home/linuxbrew/.linuxbrew/Cellar/glib/2.74.0/include/glib-2.0/glib.h:34,
                   from uf_glib.h:20,
                   from ufraw.h:21,
                   from ufraw_settings.cc:17:
  /usr/include/c++/11/type_traits:44:3: error: template with C linkage
     44 |   template<typename... _Elements>
        |   ^~~~~~~~
```

**Comment by cho-m** [comment]
`ufraw` doesn't seem to be maintained anymore and some Linux distros have been dropping it (e.g. Debian/Ubuntu and Gentoo).

Fedora is using some fixes from unofficial fork which is owned by one of their maintainers. The fix we might want from that fork is https://github.com/sergiomb2/ufraw/commit/c56f8be3caf1cf3d9a5c80597bdbaf1325faacc0

Currently, `ufraw` is used by `zbar` and `nuxeo`. I am dropping it from `zbar` in #115952. Not sure how it is used in `nuxeo`. If we can drop it there, then we can consider deprecation.

**Comment by SMillerDev** [comment]
`nuxeo` test work fine in a system without `ufraw`. Made a PR now.

**Comment by SMillerDev** [comment]
Let's rebase this after the merge of https://github.com/Homebrew/homebrew-core/pull/116630

**Comment by SMillerDev** [comment]
Okay, let's try this again

**Comment by cho-m** [comment]
Sadly, `qt` has started to fail again on Linux. Looks like issue with CMake 3.25.0+ (https://bugreports.qt.io/browse/QTBUG-109046). May need to backport patch as fix is in unreleased 6.4.2:
```
==> ./configure -release -prefix /home/linuxbrew/.linuxbrew -extprefix /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0_1 -archdatadir share/qt -datadir share/qt -examplesdir share/qt/examples -testsdir share/qt/tests -no-feature-relocatable -system-sqlite -no-sql-mysql -no-sql-odbc -no-sql-psql -- -DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=FIRST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DINSTALL_MKSPECSDIR=share/qt/mkspecs -DFEATURE_pkg_config=ON -DQT_FEATURE_avx2=OFF -DQT_FEATURE_webengine_proprietary_codecs=ON -DQT_FEATURE_webengine_kerberos=ON -DQT_BUILD_INTERNALS_RELOCATABLE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0_1 -DQT_FEATURE_webengine_system_alsa=ON -DQT_FEATURE_webengine_system_icu=ON -DQT_FEATURE_webengine_system_libevent=ON -DQT_FEATURE_webengine_system_libpng=ON -DQT_FEATURE_webengine_system_libxml=ON -DQT_FEATURE_webengine_system_libwebp=ON -DQT_FEATURE_webengine_system_minizip=ON -DQT_FEATURE_webengine_system_opus=ON -DQT_FEATURE_webengine_system_poppler=ON -DQT_FEATURE_webengine_system_pulseaudio=ON -DQT_FEATURE_webengine_system_zlib=ON
  + mkdir -p qtbase
  + cd qtbase
  + exec /tmp/qt-20221205-128099-19t54ou/qt-everywhere-src-6.4.0/qtbase/configure -top-level -release -prefix /home/linuxbrew/.linuxbrew -extprefix /home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0_1 -archdatadir share/qt -datadir share/qt -examplesdir share/qt/examples -testsdir share/qt/tests -no-feature-relocatable -system-sqlite -no-sql-mysql -no-sql-odbc -no-sql-psql -- -DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=FIRST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DINSTALL_MKSPECSDIR=share/qt/mkspecs -DFEATURE_pkg_config=ON -DQT_FEATURE_avx2=OFF -DQT_FEATURE_webengine_proprietary_codecs=ON -DQT_FEATURE_webengine_kerberos=ON -DQT_BUILD_INTERNALS_RELOCATABLE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/qt/6.4.0_1 -DQT_FEATURE_webengine_system_alsa=ON -DQT_FEATURE_webengine_system_icu=ON -DQT_FEATURE_webengine_system_libevent=ON -DQT_FEATURE_webengine_system_libpng=ON -DQT_FEATURE_webengine_system_libxml=ON -DQT_FEATURE_webengine_system_libwebp=ON -DQT_FEATURE_webengine_system_minizip=ON -DQT_FEATURE_webengine_system_opus=ON -DQT_FEATURE_webengine_system_poppler=ON -DQT_FEATURE_webengine_system_pulseaudio=ON -DQT_FEATURE_webengine_system_zlib=ON
  CMake Warning (dev) at qtbase/cmake/QtBuildInformation.cmake:257 (set):
    Cannot set "__qt_configure_reports": current scope has no parent.
  Call Stack (most recent call first):
    qtsensors/src/sensors/configure.cmake:45 (qt_configure_add_report)
    qtbase/cmake/QtProcessConfigureArgs.cmake:242 (include)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  
  CMake Error at qtwebengine/configure.cmake:63 (check_for_ulimit):
    Unknown CMake command "check_for_ulimit".
  Call Stack (most recent call first):
    qtbase/cmake/QtProcessConfigureArgs.cmake:242 (include)
```

**Comment by SMillerDev** [comment]
@cho-m how do you feel about fixing QT in a separate PR? I can't even find the commit that fixes that issue atm.

**Comment by cho-m** [comment]
> @cho-m how do you feel about fixing QT in a separate PR? I can't even find the commit that fixes that issue atm.

That is fine with me. I think all the Linux failures are due to Qt, which will be retested in followup PR.

I think commit is https://github.com/qt/qtwebengine/commit/517d0890f9e95c841bea3421f2455651ca0d8070

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
