### PR TITLE
postgresql 9.6.2

### PR DESCRIPTION
**Pull request by neutric**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by neutric** [comment]
I'll bump the revision for packages in `brew uses postgresql` as soon as the above is green.

**Comment by neutric** [comment]
The source file for `pg_top` is not accessible at the moment, as pgFoundry, the host, is undergoing a rebuild from scratch. That'll make the revision built fail. Maybe get it from [here](https://github.com/markwkm/pg_top)? Furthermore, `pgcli`, `pgpool-ii`, `postgis`, and `temporal_tables`, have new versions, and [`libpqxx`](http://pqxx.org/development/libpqxx/) [recommends building from trunk](http://pqxx.org/development/libpqxx/wiki/DownloadPage). Should those formulae be updated here or can that be done in a separate PR once this is merged?

**Comment by neutric** [comment]
Zabbix DL failed for Yosemite, the rest looks fine.

**Comment by neutric** [comment]
Related PRs: #9810, #9817

**Comment by neutric** [comment]
@ilovezfs Can you selectively restart Jenkins for Yosemite only?

**Comment by ilovezfs** [comment]
No, but we can just do zabbix in a separate PR

**Comment by neutric** [comment]
So remove it here by resetting git to the commit before zabbix and then force push? Would a testthisplease instead be too burdensome on the infrastructure? And what about those formulae using postgresql that have newer versions? If I remember correctly from yesterday, at least one of them didn't look straight-forward, which is why I wanted to keep them out of here.

**Comment by ilovezfs** [comment]
>So remove it here by resetting git to the commit before zabbix and then force push?

Nope, you don't need to do anything.

>Would a testthisplease instead be too burdensome on the infrastructure?

Not really, but it's not necessary.

>And what about those formulae using postgresql that have newer versions?

Which are you thinking of? You can open PRs for them after this ships.

**Comment by ilovezfs** [comment]
@neutric thanks for doing this big PR. Mind opening a `zabbix: revision for postgresql` PR now? Note the revision subjects usually don't include the version number and have a lower case r in revision (I standardized them before pushing this PR).

**Comment by neutric** [comment]
@ilovezfs Thanks for fixing the subjects! Working on the zabbix PR...

**Comment by ilovezfs** [comment]
@neutric note you can use https://fossies.org/linux/misc/zabbix-3.2.3.tar.gz as a mirror for it too

**Comment by neutric** [comment]
Will do!

**Pull request closed without merging**
