### PR TITLE
carthage 0.31.0

### PR DESCRIPTION
**Pull request by tmspzz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Update Carthage to 0.31.0

### CODE REVIEW

**Comment by fxcoudert** [comment]
With Xcode 10 (High Sierra, Mojave) we get:

```
install_name_tool -rpath "/Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks" "@executable_path/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks" "/usr/local/Cellar/carthage/0.31.0/bin/carthage"
Error: Failed changing dylib ID of /usr/local/Cellar/carthage/0.31.0/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Result.framework/Versions/A/Result
  from @rpath/Result.framework/Versions/A/Result
    to /usr/local/opt/carthage/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Result.framework/Versions/A/Result
Error: Failed to fix install linkage
```

which we have known for a while (#28817), but I do not know how to fix.

**Comment by blender** [comment]
@fxcoudert 

@jdhealy and I have looked into this and we think that something has changed in Mach-O and this calculation might be incorrect now https://github.com/Homebrew/brew/blob/5772493e247e75af6da77854a17ba8831b6aba94/Library/Homebrew/vendor/bundle-standalone/ruby/2.3.0/gems/ruby-macho-2.0.0/lib/macho/macho_file.rb#L177-L187

homebrew injects `headerpad_max_install_names` to the LD commands so `Result.framework` should already be built with `headerpad_max_install_names`

**Comment by woodruffw** [comment]
Yeah, I'm going to look into the offset calculation this evening; Apple may have changed it in the latest `libmacho`. Of course, it doesn't help that they haven't released the latest `cctools` source yet 🙄

**Comment by woodruffw** [comment]
Did some quick tests, and the `low_fileoff` calculation used to determine whether additional header padding is needed *appears* to be correct -- `install_name_tool` and ruby-macho agree on it for the test suite. The one edge case is when a binary's sections contain no segments, but even then ruby-macho fails safe by assuming a `low_fileoff` at the end of the file.

I'm installing Xcode now to see if that behavior holds for `Result.framework` -- it's possible (although unlikely) that Apple has added a new section type that needs to be handled specially (like `S_ZEROFILL` and `S_THREAD_LOCAL_ZEROFILL`) in the offset calculation.

**Comment by woodruffw** [comment]
Alright, I was able to reproduce this with `Tentacle.framework`:

```
Changing dylib ID of /usr/local/Cellar/carthage/0.30.1/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle
  from @rpath/Tentacle.framework/Versions/A/Tentacle
    to /usr/local/opt/carthage/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle
Error: Failed changing dylib ID of /usr/local/Cellar/carthage/0.30.1/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle
  from @rpath/Tentacle.framework/Versions/A/Tentacle
    to /usr/local/opt/carthage/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle
Error: Failed to fix install linkage
The formula built, but you may encounter issues using it or linking other
formula against it.
==> Updated load commands do not fit in the header of /usr/local/Cellar/carthage/0.30.1/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle. /usr/local/Cellar/carthage/0.30.1/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle needs to be relinked, possibly with -headerpad or -headerpad_max_install_names
```

Interestingly, ruby-macho and `install_name_tool` agree about the `low_fileoff`:

```irb
>> macho.send(:low_fileoff)
4864
```
(and my patched `install_name_tool`):

```bash
$ ./misc/install_name_tool  ~/tmp/foo 
(low_fileoff=4864)
```

So there's something unusual going on here.

**Comment by woodruffw** [comment]
Spoke too soon: `install_name_tool` agrees that the Mach-O header is too small for the updated dylib ID:

```bash
$ ./misc/install_name_tool -id "/usr/local/opt/carthage/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Tentacle.framework/Versions/A/Tentacle" ~/tmp/foo

error: ./misc/install_name_tool: changing install names or rpaths can't be redone for: /home/william/tmp/foo (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names) (low_fileoff=4864)
```

So, we're back to https://github.com/Homebrew/brew/issues/4979#issuecomment-424328472, but with a twist: the `01.make.cc` logs agree that `-headerpad_max_install_names` is getting passed to *some* parts of the build, although I'm not familiar enough with the Framework building process to tell which parts. The `grep`ped log is here: https://hastebin.com/wipucekohu.sql

Does anybody actually know whether Swift's toolchain uses `ld` internally? Homebrew sets `-headerpad_max_install_names` for all linker invocations, but makes it look as if Swift has its own internal linker.

**Comment by jdhealy** [comment]
Big thanks for looking into this, @woodruffw… Tremendously appreciated 👏

**Comment by ikesyo** [comment]
This would be helpful: https://github.com/realm/SwiftLint/blob/bf85625ed8486e2ced9ee0881565b66f6c554a24/Makefile#L5-L8

**Comment by blender** [comment]
@ikesyo homebrew does that for us 

https://github.com/Homebrew/brew/blob/4897ec02d0f00c37a21ddaa0bebff6b83b27d027/Library/Homebrew/extend/ENV/std.rb#L44

**Comment by ikesyo** [comment]
But `LDFLAGS` seems not the same as `OTHER_LDFLAGS`.

**Comment by ikesyo** [comment]
Switching to use SwiftPM-built binary will be another solution: `make swiftpm_install`. How do you think?

**Comment by basememara** [comment]
What are the disadvantages of that? It seems SwiftPM would be the modern way to go?

**Comment by woodruffw** [comment]
Yeah, a static build would resolve this particular issue. I haven't looked into `OTHER_LDFLAGS` too deeply yet, but a quick search indicates that Xcode *does* indeed treat it differently/separate from plain old `LDFLAGS`. So maybe (if a static build isn't feasible) that'll be an avenue for feeding `-headerpad_max_install_names` into swift's linker invocation.

**Comment by ikesyo** [comment]
Let's close this.

**Pull request closed without merging**
