### PR TITLE
mesos 1.9.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
14:54:30 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libprotobuf-lite.a(arenastring.o) has no symbols
14:54:30 libtool: link: ( cd ".libs" && rm -f "libprotobuf-lite.la" && ln -s "../libprotobuf-lite.la" "libprotobuf-lite.la" )
14:54:30 touch protobuf-3.5.0-build-stamp
14:54:30 make[2]: *** [all-recursive] Error 1
14:54:30 make[1]: *** [all] Error 2
14:54:30 make: *** [all-recursive] Error 1

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by qianzhangxa** [comment]
@chenrui333  Is this PR blocked by the build error that you mentioned in your previous comment? Can you please let me know the specific macOS version used to build Mesos 1.9.0 in the CI check? Thanks!

**Comment by chenrui333** [comment]
@qianzhangxa, yeah, we have it run under Mojave, Catalina, and High Sierra.

**Comment by qianzhangxa** [comment]
@chenrui333  I tried it on my Mac (Catalina), it can build successfully. Can you please trigger the CI build again?

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by Bo98** [comment]
Since this involves a move to Python 3, let's revisit this after Python 3.8 (#45337).

**Comment by qianzhangxa** [comment]
@Bo98 Did you mean the build error was caused by Python? Actually I have rebuilt Mesos 1.9.0 on macOS Catalina with the exactly same steps as the CI build, and it succeeded.

**Comment by Bo98** [comment]
I've not seen the full logs so I don't know. I just put this on pause since this pull request wasn't just a 1.9.0 update but also a move to Python 3. I wanted to avoid this formula breaking as it would need to be rebuilt when we move to Python 3.8.

Progress can still be made on this pull request however. I can see if I can reproduce it locally.

**Comment by chenrui333** [comment]
@qianzhangxa feel free to submit a new PR, I am gonna to close this one. 

Thanks everyone!

**Pull request closed without merging**
