### PR TITLE
gnuradio 3.8.0.0

### PR DESCRIPTION
**Pull request by fxcoudert**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
The C test is giving me crazy output:

```
==> ./test
/private/tmp/gnuradio-test-20190902-38984-1p3s6uq/.gnuradio/prefs/vmcircbuf_default_factory: No such file or directory
vmcircbuf_createfilemapping: createfilemapping is not available
gr::vmcircbuf_sysv_shm: shmget (1): No space left on device
gr::vmcircbuf_sysv_shm: shmget (1): No space left on device
gr::vmcircbuf_sysv_shm: shmget (1): No space left on device
gr::vmcircbuf_sysv_shm: shmget (1): Invalid argument
gr::vmcircbuf_sysv_shm: shmget (1): Invalid argument
gr::vmcircbuf_sysv_shm: shmget (1): Invalid argument
gr::vmcircbuf_mmap_shm_open: mmap or shm_open is not available
```

and Python is not built correctly:

```
==> python3 /private/tmp/gnuradio-test-20190902-38984-1p3s6uq/test.py
Traceback (most recent call last):
  File "/private/tmp/gnuradio-test-20190902-38984-1p3s6uq/test.py", line 1, in <module>
    from gnuradio import blocks
ModuleNotFoundError: No module named 'gnuradio'
```

**Comment by jonchang** [comment]
Found a flag to pass to cmake, let's see if it works...

**Comment by jonchang** [comment]
Build failure is being caused by https://github.com/gnuradio/gnuradio/pull/2781. I think we can pass `GR_PYTHON_DIR` to cmake to avoid this Debianism...

**Comment by jonchang** [comment]
Regression caused by https://github.com/gnuradio/gnuradio/pull/2230 made linking to python stop using `-undefined dynamic_lookup`

**Comment by kaslr** [comment]
@jonchang Any update? Could you please add GRC enabled for the gui usage?

**Comment by jonchang** [comment]
I haven't been able to work on this, but this contains prior art that you may find useful when updating the gnuradio formula.

**Comment by kaslr** [comment]
Thanks! I'm trying to fix that.

**Pull request closed without merging**
