### PR TITLE
terragrunt 0.19.20

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
see https://github.com/Homebrew/homebrew-core/pull/43121

**Comment by chenrui333** [comment]
@SMillerDev, i think I am trying to help (at least from what I can see), and for keeping the formula up to date, it does require some sort of collaborations.

My full skill set is with Golang and its ecosystem, with that being said, I do want to push this PR further.

**Comment by CodingMadeEasy** [comment]
Can this please be merged? I'm waiting for this update

**Comment by javian** [comment]
Thanks @chenrui333

**Pull request closed without merging**
