### PR TITLE
imagemagick 7.0.8-46

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zbeekman** [comment]
@lembacon Can you please remind me why we're setting the `url` to our own bintray mirror? Also, does the mirror get updated automatically?

**Comment by SMillerDev** [comment]
Doesn't get updated automatically and the explanation is in the formula above the url.

**Comment by lembacon** [comment]
> Doesn't get updated automatically and the explanation is in the formula above the url.

Will need to manually run `brew mirror imagemagick`.

**Comment by zbeekman** [comment]
> Doesn't get updated automatically and the explanation is in the formula above the url.

He has eyes, but cannot see! doh! Thanks for the reminders.

**Pull request closed without merging**
