### PR TITLE
livekit-cli 1.2.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Not marked as latest: https://github.com/livekit/livekit-cli/releases

**Comment by davidzhao** [comment]
Just released now! https://github.com/livekit/livekit-cli/releases/tag/v1.2.4

**Comment by p-linnane** [comment]
Thanks for the heads up @davidzhao.

**Review by p-linnane — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @davidzhao!

**Pull request merged**
