### PR TITLE
getmail6 6.18.13

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ZhongRuoyu — COMMENTED** [review]
Not marked as the latest release yet: https://github.com/getmail6/getmail6/releases

**Comment by p-linnane** [comment]
Added a livecheck.

**Comment by p-linnane** [comment]
Opened an upstream issue: https://github.com/getmail6/getmail6/issues/171

**Comment by p-linnane** [comment]
Marked as latest now.

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
