### PR TITLE
nagios 4.4.10

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
- also relates to https://github.com/Homebrew/homebrew-core/issues/120521

**Comment by p-linnane** [comment]
Rerunning. Looks like `11-arm64` was having issues:
```
The self-hosted runner: bigsur-arm-2 lost communication with the server. Verify the machine is running and has a healthy network connection. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

**Comment by chenrui333** [comment]
> * also relates to [Nagios formula Caveats is outdated #120521](https://github.com/Homebrew/homebrew-core/issues/120521)

we should probably update caveats

**Comment by chenrui333** [comment]
> > * also relates to [Nagios formula Caveats is outdated #120521](https://github.com/Homebrew/homebrew-core/issues/120521)
> 
> we should probably update caveats

after readings the bug report, probably worth another PR to address it.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
