### PR TITLE
cataclysm 0.E-2

### PR DESCRIPTION
**Pull request by jfchevrette**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Bumps from 0.E to point release 0.E-2 which has a bunch of fixes

### CODE REVIEW

**Comment by jfchevrette** [comment]
Not sure why this failed. I ran the same on my local up-to-date 10.15 macOS and it does not produce an error.

**Comment by issyl0** [comment]
I can't reproduce the Catalina test failure locally either. 🤔

**Comment by jfchevrette** [comment]
I have rebased the branch. Lets see if this helps.

**Comment by jfchevrette** [comment]
This does not fail for me on 10.15. I'm not sure what is going on here.

**Pull request closed without merging**
