### PR TITLE
securefs 0.14.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  CMake Error at CMakeLists.txt:77 (find_package):
    Could not find a package configuration file provided by "absl" with any of
    the following names:
  
      abslConfig.cmake
      absl-config.cmake
  
    Add the installation prefix of "absl" to CMAKE_PREFIX_PATH or set
    "absl_DIR" to a directory containing one of the above files.  If "absl"
    provides a separate development package or SDK, be sure it has been
    installed.
```

**Comment by danielnachun** [comment]
Adding `pkg-config` resolved the issue of not being able to find `abseil`, but there is a new issue - `securefs` now depends on `cryptopp`, which does not currently have a formula.  I will try to make one in the next few days, but any other contributors should feel free do this before me.

**Comment by ZhongRuoyu** [comment]
> `securefs` now depends on `cryptopp`, which does not currently have a formula

Adding the formula in #141277.

**Review by p-linnane — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
Needs a rebase.

**Pull request merged**
