### PR TITLE
code-server 3.10.1

### PR DESCRIPTION
**Pull request by cdrci**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
@cdrci looks like your base branch is not up to date, can you please do a rebase? Thanks!

**Comment by code-asher** [comment]
Ahhh it looks like we have a bug with the bot that submits these PRs. I don't think we have a good way to make the bot rebase right now so could we close this one and I'll open another with the correct base?

**Comment by nandahkrishna** [comment]
No worries, did it for you here.

**Comment by code-asher** [comment]
Thank you!! <3

**Review by nandahkrishna — APPROVED** [review]

**Pull request closed without merging**
