### PR TITLE
python-platformdirs: remove

### PR DESCRIPTION
**Pull request by cho-m**
Formula added in https://github.com/Homebrew/homebrew-core/pull/155441 on 2023-11-24.

Need revision bump for `abi3audit` and `black` prior to merge.

```
==> Analytics
install: 20,150 (30 days), 56,374 (90 days), 56,379 (365 days)
install-on-request: 397 (30 days), 705 (90 days), 702 (365 days)
build-error: 0 (30 days)
```

<details>
<summary>Bottle contents</summary>

```console
❯ tar -ztvf $(brew --cache --quiet python-platformdirs)
drwxr-xr-x  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/
drwxr-xr-x  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/.brew/
-rw-r--r--  0 0      0        1121 Feb  1  2020 python-platformdirs/4.2.0/.brew/python-platformdirs.rb
-rw-r--r--  0 0      0        1089 Feb  1  2020 python-platformdirs/4.2.0/LICENSE
-rw-r--r--  0 0      0        9340 Feb  1  2020 python-platformdirs/4.2.0/README.rst
drwxr-xr-x  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/
drwxr-xr-x  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/
drwxr-xr-x  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/
drwxr-xr-x  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs/
-r--r--r--  0 0      0       22134 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs/__init__.py
-r--r--r--  0 0      0        1489 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs/__main__.py
-r--r--r--  0 0      0        7582 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs/android.py
-r--r--r--  0 0      0        8940 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs/api.py
-r--r--r--  0 0      0        5620 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs/macos.py
-r--r--r--  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs/py.typed
-r--r--r--  0 0      0       10591 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs/unix.py
-r--r--r--  0 0      0         411 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs/version.py
-r--r--r--  0 0      0       10008 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs/windows.py
drwxr-xr-x  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs-4.2.0.dist-info/
-r--r--r--  0 0      0           4 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs-4.2.0.dist-info/INSTALLER
-r--r--r--  0 0      0       11366 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs-4.2.0.dist-info/METADATA
-r--r--r--  0 0      0        1334 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs-4.2.0.dist-info/RECORD
-r--r--r--  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs-4.2.0.dist-info/REQUESTED
-r--r--r--  0 0      0          87 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs-4.2.0.dist-info/WHEEL
-r--r--r--  0 0      0         106 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs-4.2.0.dist-info/direct_url.json
drwxr-xr-x  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs-4.2.0.dist-info/licenses/
-r--r--r--  0 0      0        1089 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.11/site-packages/platformdirs-4.2.0.dist-info/licenses/LICENSE
drwxr-xr-x  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/
drwxr-xr-x  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/
drwxr-xr-x  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs/
-r--r--r--  0 0      0       22134 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs/__init__.py
-r--r--r--  0 0      0        1489 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs/__main__.py
-r--r--r--  0 0      0        7582 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs/android.py
-r--r--r--  0 0      0        8940 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs/api.py
-r--r--r--  0 0      0        5620 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs/macos.py
-r--r--r--  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs/py.typed
-r--r--r--  0 0      0       10591 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs/unix.py
-r--r--r--  0 0      0         411 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs/version.py
-r--r--r--  0 0      0       10008 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs/windows.py
drwxr-xr-x  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs-4.2.0.dist-info/
-r--r--r--  0 0      0           4 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs-4.2.0.dist-info/INSTALLER
-r--r--r--  0 0      0       11366 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs-4.2.0.dist-info/METADATA
-r--r--r--  0 0      0        1334 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs-4.2.0.dist-info/RECORD
-r--r--r--  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs-4.2.0.dist-info/REQUESTED
-r--r--r--  0 0      0          87 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs-4.2.0.dist-info/WHEEL
-r--r--r--  0 0      0         106 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs-4.2.0.dist-info/direct_url.json
drwxr-xr-x  0 0      0           0 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs-4.2.0.dist-info/licenses/
-r--r--r--  0 0      0        1089 Feb  1  2020 python-platformdirs/4.2.0/lib/python3.12/site-packages/platformdirs-4.2.0.dist-info/licenses/LICENSE
```
</details>

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Comment by scentoni** [comment]
This removal seems to have messed up my brew installation.
```
# brew doctor
...
Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  python-attrs
  python-platformdirs
...
```
and
```
$ brew uninstall python-platformdirs
Error: Refusing to uninstall /usr/local/Cellar/python-platformdirs/4.2.0
because it is required by ansible-lint, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies python-platformdirs
```

**Comment by p-linnane** [comment]
Apologies @scentoni. We missed revision bumping that formula. This will be fixed by https://github.com/Homebrew/homebrew-core/pull/163944.

**Comment by p-linnane** [comment]
As a workaround you should be able to run `brew reinstall ansible-lint` for now.

**Comment by cho-m** [comment]
`ansible-lint` is a bit odd as it doesn't have a direct dependency on those. It has an indirect dependency via `black`.

This may be related to new feature that avoids upgrading some formulae based on tab info.

**Pull request merged**
