### PR TITLE
openshift-cli: add "oc" alias

### PR DESCRIPTION
**Pull request by cblecker**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Add "oc" as an alias for the openshift-cli tool (oc is the main binary provided by the Formula)

### CODE REVIEW

**Comment by fxcoudert** [comment]
Really? `oc` is not descriptive at all, and if all projects claim two-letter aliases life is going to be hard in the future :)

Looking at upstream's webpage, I don't see `oc` being used anywhere as project name or alias.

**Comment by cblecker** [comment]
@fxcoudert The `oc` utility is the cli tool for controlling an OpenShift cluster.. this is in a similar vein to `kubectl` being the name of the cli tool for controlling a vanilla Kubernetes cluster. The documentation specifically for the CLI tool is here: https://docs.okd.io/latest/cli_reference/index.html

I understand if policy-wise, this isn't something Homebrew wants to support (two-letter alias).. I just know I've done `brew install oc --HEAD --fetch-HEAD` enough times before 🤦‍♂️ and repeating it with `openshift-cli` that figured I must not be the only one lol.

The biggest driver behind this is that `oc` is the name of the actual binary.. and unless you know that `openshift-cli` is the name of the formula, you might not know that Homebrew has it in their library already.

**Comment by zbeekman** [comment]
Are you using https://github.com/Homebrew/homebrew-command-not-found?

For me, if I try running `oc` I get:

```
$ oc
The program 'oc' is currently not installed. You can install it by typing:
  brew install openshift-cli
```

This seems sufficient. I'm going to close this as won't fix.

**Comment by cblecker** [comment]
@zbeekman I'm not, due to the processing time in my terminal.

I'm okay with this being WONTFIX, but I would suggest some clarifying guidelines (what qualifies for an Alias entry, and what doesn't) would be helpful to contributors.

Thank you both!

**Comment by zbeekman** [comment]
> I'm okay with this being WONTFIX, but I would suggest some clarifying guidelines (what qualifies for an Alias entry, and what doesn't) would be helpful to contributors.

Thanks for the input. If you have some suggested text for improving guidelines for aliases, it would be helpful to us if you shared it.

Thanks again!

**Pull request closed without merging**
