### PR TITLE
zint 2.7.1

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
[ 31%] Building C object backend/CMakeFiles/zint.dir/gs1.c.o
cd /tmp/zint-20200201-46108-uva0w0/zint-2.7.0/zint-build/backend && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DZINT_VERSION=\"2.6.7\" -Dzint_EXPORTS -I/tmp/zint-20200201-46108-uva0w0/zint-2.7.0/zint-build/backend -I/tmp/zint-20200201-46108-uva0w0/zint-2.7.0/backend  -DNDEBUG -mmacosx-version-min=10.14 -fPIC   -Wall -o CMakeFiles/zint.dir/gs1.c.o   -c /tmp/zint-20200201-46108-uva0w0/zint-2.7.0/backend/gs1.c
/tmp/zint-20200201-46108-uva0w0/zint-2.7.0/backend/reedsol.c:52:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [backend/CMakeFiles/zint.dir/reedsol.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [backend/CMakeFiles/zint.dir/all] Error 2
make: *** [all] Error 2

**Comment by mistydemeo** [comment]
`malloc.h` is a non-POSIX, Linux-specific header: https://stackoverflow.com/a/12973361

**Comment by mistydemeo** [comment]
Looks like they actually added this for Microsoft compilers, but it's been fixed upstream: https://sourceforge.net/p/zint/code/ci/ce8aa928469fe14262165fbed01f20f53aa9c6de/

**Comment by alebcay** [comment]
In macOS, malloc lives at `malloc/malloc.h`. I'll try and open a bug upstream soon.

**Comment by mistydemeo** [comment]
They already committed the fix in that patch. https://sourceforge.net/p/zint/code/ci/ce8aa928469fe14262165fbed01f20f53aa9c6de/

```diff
--- a/backend/reedsol.c
+++ b/backend/reedsol.c
@@ -49,7 +49,9 @@
 // size.
 
 #include <stdio.h>		// only needed for debug (main)
+#ifdef _MSC_VER
 #include <malloc.h>
+#endif
 #include "reedsol.h"
 static int logmod; // 2**symsize - 1
 static int rlen;
```

**Pull request closed without merging**
