### PR TITLE
sdl2 2.0.9

### PR DESCRIPTION
**Pull request by evgeniron**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Many tests failing on Sierra and High Sierra with:

```
dyld: Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
  Referenced from: /usr/local/opt/sdl2_ttf/lib/libSDL2_ttf-2.0.0.dylib
  Reason: Incompatible library version: libSDL2_ttf-2.0.0.dylib requires version 5.0.0 or later, but libSDL2-2.0.0.dylib provides version 1.0.0
```

although they are working for Mojave.

**Comment by edward-zhu** [comment]
I found there is a suspicious change in 2.0.9 and am wondering if that cause the problem. But I don't have a machine running sierra.

https://hg.libsdl.org/SDL/diff/1a1133e9c7d4/build-scripts/ltmain.sh

**Comment by fxcoudert** [comment]
@BrewTestBot test this please
We might have to revision-bump the whole lot…

**Comment by robert-wallis** [comment]
Good call Edward!  Looks like they reverted that change https://hg.libsdl.org/SDL/rev/d274fa9731b1

**Comment by fxcoudert** [comment]
Thanks @edward-zhu and @robert-wallis, applying that revert commit as patch should fix the issue.

**Comment by edward-zhu** [comment]
Thanks!

**Pull request closed without merging**
