### PR TITLE
libsodium 1.0.10

### PR DESCRIPTION
**Pull request by woobs**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by apjanke** [comment]
The test is failing for some php-version-specific things because `test-bot` isn't capable of shuffling around the conflicting formulae.

```
All Failed Tests
Test Name
	
Duration
	
Age
 brew-test-bot.el_capitan.install php54-libsodium	0.55 sec	1
 brew-test-bot.el_capitan.install php55-libsodium	0.56 sec	1
 brew-test-bot.el_capitan.install php56-libsodium	0.57 sec	1
 brew-test-bot.el_capitan.install php70-libsodium	0.57 sec	1
```

```
        ==> Installing php54-libsodium from homebrew/php
==> Installing dependencies for homebrew/php/php54-libsodium: php54
==> Installing homebrew/php/php54-libsodium dependency: php54
Error: Cannot install homebrew/php/php54 because conflicting formulae are installed.

  php53: because different php versions install the same binaries.

Please `brew unlink php53` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
```

I don't remember this happening with the last libsodium update. Have you seen this before?

**Comment by DomT4** [comment]
False positives that shouldn't be happening here. Can be ignored.

**Comment by woobs** [comment]
Yeah, not an issue before and this minor version update simply redefined an AVX2 symbol for old GCC versions.

**Comment by DomT4** [comment]
I've thrown it back on the build queue because `postinstall` fell apart on Mavericks. I suspect that was a network glitch, but easy enough to get CI to check again.

**Comment by woobs** [comment]
Cool, we could also skip this release since it will have absolutely no functional impact on end-users.  I debated whether to even submit the PR because of that.

**Comment by DomT4** [comment]
People will expect the "latest", even if the latest doesn't have any impact on end-users, so we'll carry it.

**Comment by apjanke** [comment]
Test failure is due to a GitHub connection failure, looks like.

```
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/Homebrew/homebrew-core/ +refs/pull/*:refs/remotes/origin/pr/*" returned status code 128:
stdout: 
stderr: remote: GitHub is offline for maintenance. See http://status.github.com for more info.
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': The requested URL returned error: 503

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1719)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1463)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:63)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:314)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:808)
	... 11 more
```

Going to give this a few minutes and requeue it.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/330867b75c716678e1a5ab9ec5877f3ade808dc9. Thank you for another contribution to Homebrew @woobs! :smiley_cat:

**Pull request closed without merging**
