### PR TITLE
pdns 4.3.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
license header ref (`pdns/dns.hh`)

```
/*
 * This file is part of PowerDNS or dnsdist.
 * Copyright -- PowerDNS.COM B.V. and its contributors
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * In addition, for the avoidance of any doubt, permission is granted to
 * link this program with OpenSSL and to (re)distribute the binaries
 * produced as the result of such linking.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
```

**Comment by chenrui333** [comment]
<details>
<summary>build failure</summary>

```
==> make install
Making install in ext
Making install in ipcrypt
  CC       ipcrypt.lo
  CCLD     libipcrypt.la
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in json11
  CXX      json11.lo
  CXXLD    libjson11.la
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in yahttp
Making install in yahttp
  CXX      reqresp.lo
  CXX      router.lo
  CXXLD    libyahttp.la
make[4]: Nothing to be done for `install-exec-am'.
make[4]: Nothing to be done for `install-data-am'.
                                                                                                ^
ws-auth.cc:2332:86: error: use of undeclared identifier '_1'; did you mean 'boost::placeholders::_1'?
      d_ws->registerWebHandler("/", boost::bind(&AuthWebServer::indexfunction, this, _1, _2));
                                                                                     ^~
                                                                                     boost::placeholders::_1
/usr/local/include/boost/bind/placeholders.hpp:46:38: note: 'boost::placeholders::_1' declared here
BOOST_STATIC_CONSTEXPR boost::arg<1> _1;
                                     ^
ws-auth.cc:2332:90: error: use of undeclared identifier '_2'
      d_ws->registerWebHandler("/", boost::bind(&AuthWebServer::indexfunction, this, _1, _2));
                                                                                         ^
In file included from ws-auth.cc:26:
In file included from ./dynlistener.hh:30:
In file included from ./iputils.hh:32:
In file included from ./misc.hh:31:
In file included from /usr/local/include/boost/multi_index/ordered_index.hpp:17:
In file included from /usr/local/include/boost/multi_index/detail/ord_index_impl.hpp:81:
/usr/local/include/boost/bind/bind.hpp:398:9: error: no matching function for call to object of type 'boost::_mfi::mf2<void, AuthWebServer, HttpRequest *, HttpResponse *>'
        unwrapper<F>::unwrap(f, 0)(a[base_type::a1_], a[base_type::a2_], a[base_type::a3_]);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/bind/bind.hpp:1318:16: note: in instantiation of function template specialization 'boost::_bi::list3<boost::_bi::value<AuthWebServer *>, boost::arg<1>, boost::_bi::value<std::__1::placeholders::__ph<2> > >::operator()<boost::_mfi::mf2<void, AuthWebServer, HttpRequest *, HttpResponse *>, boost::_bi::rrlist2<HttpRequest *, HttpResponse *> >' requested here
        return l_( type<result_type>(), f_, a, 0 );
               ^
/usr/local/include/boost/function/function_template.hpp:158:33: note: in instantiation of function template specialization 'boost::_bi::bind_t<void, boost::_mfi::mf2<void, AuthWebServer, HttpRequest *, HttpResponse *>, boost::_bi::list3<boost::_bi::value<AuthWebServer *>, boost::arg<1>, boost::_bi::value<std::__1::placeholders::__ph<2> > > >::operator()<HttpRequest *, HttpResponse *>' requested here
          BOOST_FUNCTION_RETURN((*f)(BOOST_FUNCTION_ARGS));
                                ^
/usr/local/include/boost/function/function_template.hpp:940:53: note: in instantiation of member function 'boost::detail::function::void_function_obj_invoker2<boost::_bi::bind_t<void, boost::_mfi::mf2<void, AuthWebServer, HttpRequest *, HttpResponse *>, boost::_bi::list3<boost::_bi::value<AuthWebServer *>, boost::arg<1>, boost::_bi::value<std::__1::placeholders::__ph<2> > > >, void, HttpRequest *, HttpResponse *>::invoke' requested here
        { { &manager_type::manage }, &invoker_type::invoke };
                                                    ^
/usr/local/include/boost/function/function_template.hpp:720:13: note: in instantiation of function template specialization 'boost::function2<void, HttpRequest *, HttpResponse *>::assign_to<boost::_bi::bind_t<void, boost::_mfi::mf2<void, AuthWebServer, HttpRequest *, HttpResponse *>, boost::_bi::list3<boost::_bi::value<AuthWebServer *>, boost::arg<1>, boost::_bi::value<std::__1::placeholders::__ph<2> > > > >' requested here
      this->assign_to(f);
            ^
/usr/local/include/boost/function/function_template.hpp:1086:5: note: in instantiation of function template specialization 'boost::function2<void, HttpRequest *, HttpResponse *>::function2<boost::_bi::bind_t<void, boost::_mfi::mf2<void, AuthWebServer, HttpRequest *, HttpResponse *>, boost::_bi::list3<boost::_bi::value<AuthWebServer *>, boost::arg<1>, boost::_bi::value<std::__1::placeholders::__ph<2> > > > >' requested here
    base_type(f)
    ^
ws-auth.cc:2331:46: note: in instantiation of function template specialization 'boost::function<void (HttpRequest *, HttpResponse *)>::function<boost::_bi::bind_t<void, boost::_mfi::mf2<void, AuthWebServer, HttpRequest *, HttpResponse *>, boost::_bi::list3<boost::_bi::value<AuthWebServer *>, boost::arg<1>, boost::_bi::value<std::__1::placeholders::__ph<2> > > > >' requested here
      d_ws->registerWebHandler("/style.css", boost::bind(&AuthWebServer::cssfunction, this, _1, _2));
                                             ^
/usr/local/include/boost/bind/mem_fn_template.hpp:278:7: note: candidate function not viable: no known conversion from 'std::__1::placeholders::__ph<2>' to 'HttpResponse *' for 3rd argument
    R operator()(T * p, A1 a1, A2 a2) const
      ^
/usr/local/include/boost/bind/mem_fn_template.hpp:283:25: note: candidate function not viable: no known conversion from 'std::__1::placeholders::__ph<2>' to 'HttpResponse *' for 3rd argument
    template<class U> R operator()(U & u, A1 a1, A2 a2) const
                        ^
/usr/local/include/boost/bind/mem_fn_template.hpp:291:25: note: candidate function not viable: no known conversion from 'std::__1::placeholders::__ph<2>' to 'HttpResponse *' for 3rd argument
    template<class U> R operator()(U const & u, A1 a1, A2 a2) const
                        ^
/usr/local/include/boost/bind/mem_fn_template.hpp:299:7: note: candidate function not viable: no known conversion from 'AuthWebServer *' to 'AuthWebServer &' for 1st argument; dereference the argument with *
    R operator()(T & t, A1 a1, A2 a2) const
      ^
5 errors generated.
make[2]: *** [ws-auth.o] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
```

</details>

**Comment by chenrui333** [comment]
known issue with boost 1.73.x (see https://github.com/PowerDNS/pdns/issues/9200)

**Comment by chenrui333** [comment]
```
==> brew audit pdns --online --git --skip-style
==> FAILED
Error: 1 problem in 1 formula detected
pdns:
  * The plist first ProgramArguments value does not exist:
      /usr/local/opt/pdns/bin/pdns_server
```

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
