### PR TITLE
libcouchbase 3.2.2

### PR DESCRIPTION
**Pull request by avsej**
This pull request updates libcouchbase formula after 3.2.2 release.

### CODE REVIEW

**Review by carlocab — DISMISSED** [review]
Thanks @avsej!

**Comment by carlocab** [comment]
Can you reopen your PR with a branch not named `master`? That's what causes the merge failure. Thanks!

**Comment by avsej** [comment]
@carlocab do you mean I have to rename my branch? upstream also using `master`.

**Comment by SMillerDev** [comment]
Just the branch that you made the pull request from. Unfortunately we have some issues with our automation if the branch is called `master`

**Comment by carlocab** [comment]
Your branch is still named `master`; you'll need to create a new branch with a different name and open a new PR using that new branch.

**Comment by avsej** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-core/pull/85773

**Comment by carlocab** [comment]
Ah, there we go. Thanks @avsej!

**Pull request closed without merging**
