### PR TITLE
go 1.17.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by jidicula** [comment]
Should this be reopened?

**Comment by SMillerDev** [comment]
> Most definitely; we need the newest Go version ;)

Let me know if you need anyone to review the PRs for the build failures

**Comment by helloPiers** [comment]
Hi - I'm just a homebrew user (albeit a Patreon contributing one). I don't really understand the way things are done, or if 6 days is long to wait for a point release - but the failures above look like timeouts? They're all failed between 391 and 2136 minutes.

**Comment by SMillerDev** [comment]
Well, nobody seems to have time to investigate and fix them. So nothing is happening. If you want to help you can check if these things also fail when you run the command on your own device (with the older Go)

**Comment by chipdude** [comment]
after hand-editing to 1.17.3 it worked fine for me

**Comment by noah-friedman** [comment]
> after hand-editing to 1.17.3 it worked fine for me

@chipdude How would I go about doing that?

**Comment by andig** [comment]
Please restart CI.

**Comment by SMillerDev** [comment]
I think only one formula was fixed so that wouldn't help much

**Comment by patrickhoefler** [comment]
Here's a quick overview of all the (Intel-based) CI steps that are currently failing:

- [ ] `brew fetch --build-from-source --retry bosh-cli`
- [ ] `brew fetch --build-from-source --retry kyma-cli`
- [ ] `brew install --build-from-source envoy@1.18`
- [ ] `brew install --build-from-source hasura-cli`
- [ ] `brew install --build-from-source ship`
- [ ] `brew test --retry --verbose envoy`
- [ ] `brew test --retry --verbose envoy@1.18`
- [ ] `brew test --retry --verbose func-e`
- [ ] `brew test --retry --verbose goproxy`
- [x] `brew test --retry --verbose nats-server` https://github.com/Homebrew/homebrew-core/pull/89168
- [ ] `brew test --retry --verbose nats-streaming-server` https://github.com/Homebrew/homebrew-core/pull/89339
- [ ] `brew test --retry --verbose termshark`
- [ ] `brew test --retry --verbose vgrep`

**Comment by patrickhoefler** [comment]
Several of the issues mentioned above are still unfixed, but none (including the fixed ones) seem related to the patch release of Go 1.17.3.

**Comment by andig** [comment]
One of the typical problems is changing release hashes upstream that need manual confirmation. Could we discuss if we could a) accept those automatically (security?) or b) ignore these failures?

**Comment by SMillerDev** [comment]
>Could we discuss if we could 
a) accept those automatically (security?) or 

We can't accept these automatically because it can just as well be that the upstream download was compromised.

> b) ignore these failures?

We don't want to do this either because that way it'll never be fixed.

The best way is C) people who encounter them ask upstream for clarification.

**Comment by andig** [comment]
> The best way is C) people who encounter them ask upstream for clarification.

I had suggested in discussions to automate some of the steps. This seems like a good candiate (open upstream issue, link to PR). The discussion got nowhere. Restart?

**Comment by modprobe** [comment]
This might be a stupid question, but if none of the CI failures relate to updating the `go` formula, what's blocking this from being merged?

**Comment by andig** [comment]
The point is imho that when upgrading one formula then others should still keep working with it. 

What bugs me is that the „other“ formulas are already broken. They will continue working at the current version, but not once rebuilt. That needs to be fixed sooner or later. The problem I see is that we tie fixing everything else to the point in time of releasing the modified formula. It would be more efficient/ less manual work to only do this when the other formulas are bumped. That reasoning should hold at least for minor version bumps (bug fixes) vs sha mismatches.

**Comment by iMichka** [comment]
If improvements have to be made in our process, we can discuss this in https://github.com/Homebrew/discussions/. Any feedback is welcome there, and we are open to adjust things if we can make this better for everyone.

Right now the rule is: CI is in place and flags things as broken for a good reason. As long as CI is not green, we would like to avoid merging this. The rationale is that if we always merge with red CI, why have a CI at all and not just disable all the checks? It's a gentle nudge to tell contributors and maintainers: please fix things.

So please let's have a constructive discussion at https://github.com/Homebrew/discussions/ if necessary, and let's keep the focus on the content of this pull request and the necessary fixes. Thanks :)

**Comment by SMillerDev** [comment]
> They will continue working at the current version, but not once rebuilt. That needs to be fixed sooner or later.

The problem there is that if it's not sooner it's never. And we do want to make sure that the things we ship work.

**Comment by chipdude** [comment]
> Right now the rule is: CI is in place and flags things as broken for a good reason. As long as CI is not green, we would like to avoid merging this. The rationale is that if we always merge with red CI, why have a CI at all and not just disable all the checks? It's a gentle nudge to tell contributors and maintainers: please fix things.

That's a bad rationale. The developers who upgraded golang, and the users who use it, are being subjected to continued delay of a SECURITY fix because the CI process has changed since the last release? Penalizing the wrong people here.

Release security fixes. There's your reason.

**Comment by SMillerDev** [comment]
> That's a bad rationale. The developers who upgraded golang, and the users who use it, are being subjected to continued delay of a SECURITY fix because the CI process has changed since the last release? Penalizing the wrong people here.

The CI process has always been this way and we're not trying to penalize anyone. There is really no telling if something is broken until we resolve all the issues. Luckily the Go community for Homebrew has been absolutely awful and rather complains about the process than actually help us move the PR forward. The notable exception there is patrickhoefler who is actually trying to get this merged instead of trying to fight the people who will merge this on their rationale.

**Comment by andig** [comment]
> > That's a bad rationale. The developers who upgraded golang, and the users who use it, are being subjected to continued delay of a SECURITY fix because the CI process has changed since the last release? Penalizing the wrong people here.
> 
> The CI process has always been this way and we're not trying to penalize anyone. There is really no telling if something is broken until we resolve all the issues. Luckily the Go community for Homebrew has been absolutely awful and rather complains about the process than actually help us move the PR forward. The notable exception there is patrickhoefler who is actually trying to get this merged instead of trying to fight the people who will merge this on their rationale.

Thank you for making this repo a hostile place: https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+author%3A%40me+is%3Aclosed

**Comment by iMichka** [comment]
I already wrote a few comments above that this pull request is not the right place to continue this discussion and asked that this was moved to  https://github.com/Homebrew/discussions/.

It's also a shame that I have to remember you all our code of conduct: https://github.com/Homebrew/.github/blob/HEAD/CODE_OF_CONDUCT.md#code-of-conduct

I locked the comments here, only maintainers can now write here.

@andig first and last warning: please watch your tone. Thanks

**Comment by iMichka** [comment]
I re-opened this, as things should have hopefully calmed down. We can now continue on working on fixing the last tests to get this done. If we get the list https://github.com/Homebrew/homebrew-core/pull/88775#issuecomment-968122564 done, we will re-run CI and have a look at what remains to be fixed.

**Comment by andig** [comment]
Looked into envoy:

```
 Minitest::Assertion: Expected /envoy +version: [a-f0-9]{40}\/1.20\.[0-9]+\// to match "looking up the latest Envoy version\ndownloading https://archive.tetratelabs.io/envoy/download/v1.20.0/envoy-v1.20.0-darwin-amd64.tar.xz\nstarting: /private/tmp/func-e-test-20211109-60020-4g0mc8/.func-
```

The Minitest assertion is not part of the envoy formula- not sure where that's coming from.

**Comment by andig** [comment]
ship:

```
==> Installing ship
==> make VERSION=0.55.0 build-minimal

Last 15 lines from /Users/andig/Library/Logs/Homebrew/ship/01.make:
node-pre-gyp ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node@14/14.18.1/bin/node /private/tmp/ship-20211117-88286-24ldn8/ship-0.55.0/web/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/private/tmp/ship-20211117-88286-24ldn8/ship-0.55.0/web/app/node_modules/fsevents/lib/binding/Release/node-v83-darwin-arm64/fse.node --module_name=fse --module_path=/private/tmp/ship-20211117-88286-24ldn8/ship-0.55.0/web/app/node_modules/fsevents/lib/binding/Release/node-v83-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83 --python=/opt/homebrew/opt/python@3.9/bin/python3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/private/tmp/ship-20211117-88286-24ldn8/ship-0.55.0/web/app/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
node-pre-gyp ERR! System Darwin 21.1.0
node-pre-gyp ERR! command \"/opt/homebrew/Cellar/node@14/14.18.1/bin/node\" \"/private/tmp/ship-20211117-88286-24ldn8/ship-0.55.0/web/app/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /private/tmp/ship-20211117-88286-24ldn8/ship-0.55.0/web/app/node_modules/fsevents
node-pre-gyp ERR! node -v v14.18.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute '/opt/homebrew/Cellar/node@14/14.18.1/bin/node /private/tmp/ship-20211117-88286-24ldn8/ship-0.55.0/web/app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/private/tmp/ship-20211117-88286-24ldn8/ship-0.55.0/web/app/node_modules/fsevents/lib/binding/Release/node-v83-darwin-arm64/fse.node --module_name=fse --module_path=/private/tmp/ship-20211117-88286-24ldn8/ship-0.55.0/web/app/node_modules/fsevents/lib/binding/Release/node-v83-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83 --python=/opt/homebrew/opt/python@3.9/bin/python3' (1)"
info This module is OPTIONAL, you can safely ignore this error
make[1]: *** [.state/package] Error 1
make: *** [build-ui] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting
```

ship looks like a commercial app. I'd suggest to let ship maintainers fix the build if necessary.

**Comment by andig** [comment]
The hasura message is funny:

```
❯ brew info ship
ship: stable 0.55.0 (bottled)
Reducing the overhead of maintaining 3rd-party applications in Kubernetes
https://www.replicated.com/ship
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ship.rb
License: Apache-2.0
==> Dependencies
Build: go ✔, node@14 ✔, yarn ✔
==> Analytics
install: 9 (30 days), 28 (90 days), 223 (365 days)
install-on-request: 9 (30 days), 28 (90 days), 223 (365 days)
build-error: 1 (30 days)

~/htdocs/evcc fix/openwb*
❯ brew install --build-from-source hasura-cli
==> Downloading https://github.com/hasura/graphql-engine/archive/v2.0.10.tar.gz
==> Downloading from https://codeload.github.com/hasura/graphql-engine/tar.gz/v2.0.10
## # -#O=-
==> npm install -ddd --build-from-source --cache=/Users/andig/Library/Caches/Homebrew/npm_cache
==> npm run prebuild
==> ./node_modules/.bin/pkg ./build/command.js --output ./bin/cli-ext-hasura -t host
Last 15 lines from /Users/andig/Library/Logs/Homebrew/hasura-cli/03.pkg:
2021-11-17 17:40:37 +0000

./node_modules/.bin/pkg
./build/command.js
--output
./bin/cli-ext-hasura
-t
host

> pkg@5.2.1
> Error! No available node version satisfies 'node17'
```

It depends on node14, but complains about 17. No idea what to do there.

Apart from those two it might be good time for restarting CI- everything else has direct fixes or might depend on those fixes.

**Comment by samford** [comment]
Apparently `golang.org` now redirects to `go.dev`. We'll want to update related URLs but, considering how long it takes to run CI, I'm not sure if we want to handle it in this PR or in a follow-up.

**Comment by SMillerDev** [comment]
If you can rebase it while you're at it, I think this PR is due for a rerun.

**Comment by samford** [comment]
Rebased, updated the related URLs to `go.dev`, and added `branch: "master"` to `head` (to resolve the audit error).

**Comment by andig** [comment]
As for ship: no feedback on the ticket, latest commit from Jan 21

**Review by GwynethLlewelyn — COMMENTED** [review]
Looks good to me...

**Comment by andig** [comment]
New failures:
- akamai
- awsweeper
- func-e
- vgrep

**Review by carlocab — APPROVED** [review]
This is a security release; let's move this along.

**Comment by GwynethLlewelyn** [comment]
... and now, **1.17._5_** is out...

**Pull request closed without merging**
