### PR TITLE
liqoctl 0.3.0 (new formula)

### PR DESCRIPTION
**Pull request by ferhaty**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
That's weird. What happens when you run
```
liqoctl install kind 2>&1 1> /dev/null
```
?

**Comment by ferhaty** [comment]
> That's weird. What happens when you run
> 
> ```
> liqoctl install kind 2>&1 1> /dev/null
> ```
> 
> ?

```
$ liqoctl install kind 2>&1 1> /dev/null
Error: kube-controller-manager not found
Error: kube-controller-manager not found
```

**Comment by ferhaty** [comment]
`liqoctl install kind &> /dev/null` doesn't print anything.

**Comment by carlocab** [comment]
`sh` is terrible. Ok, let's do `assert_empty`.

**Review by dawidd6 — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
