### PR TITLE
unison 2.51.2

### PR DESCRIPTION
**Pull request by CorentinDeBoisset**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by EugenMayer** [comment]
just in case a good reason for an update should be given, 2.51.2 is fixing issues with AFPS under High Sierra

**Comment by fxcoudert** [comment]
Thanks @coreoas for the pull request!

**Comment by mLewisLogic** [comment]
Not leaving the 2.48.15 version brings sadness.
Client/server have to be in version lockstep. Latest version isn't avail in many linux package managers, making me regret not having pinned this package before it updated.

**Comment by ilovezfs** [comment]
@mLewisLogic you can probably install 2.51.2 via Linuxbrew.

**Comment by mLewisLogic** [comment]
@ilovezfs didn't even know that existed! Solved my problem.

Unison still feels like a special case where keeping historic versions has more value than for most packages. The lockstep version requirement is unduly strict and forces an all-or-nothing upgrade across various OSes.

**Pull request closed without merging**
