### PR TITLE
gobackup 2.0.2

### PR DESCRIPTION
**Pull request by huacnlee**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/brew/pull/15368

**Comment by chenrui333** [comment]
```
  error An unexpected error occurred: "ENOENT: no such file or directory, open '/private/tmp/gobackup-20230505-63890-83kmj6/gobackup-2.0.2/.brew_home/Library/Caches/Yarn/v6/npm-@swc-core-linux-arm64-musl-1.3.40-77a8be0ca808312415a615cb4e683032281a5a87-integrity/node_modules/@swc/core-linux-arm64-musl/.yarn-metadata.json'".
```

**Comment by huacnlee** [comment]
Not need to release

**Comment by huacnlee** [comment]
Just make a note.

The CI failed reason is npm download timeout.

image

**Pull request closed without merging**
