### PR TITLE
infracost 0.9.18

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by aliscott** [comment]
@SMillerDev can we close this PR please and we'll submit another one for infracost v0.9.18. We're having issues with our release process?

**Comment by aliscott** [comment]
@SMillerDev @Porkepix this PR was created for an unpublished release which had to be pulled so it has an incorrect SHA.

**Comment by SMillerDev** [comment]
Just make a PR to update the SHA, it's the easiest way to fix this.

**Comment by aliscott** [comment]
Thanks @SMillerDev, done in https://github.com/Homebrew/homebrew-core/pull/95228.

**Pull request closed without merging**
