### PR TITLE
node 11.14.0

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zbeekman** [comment]
What about icu4c #38706 ?

**Comment by zbeekman** [comment]
Hmmm that was the wrong PR I linked. #38439

**Comment by lembacon** [comment]
ICU 64.2 RC has been released, the stable release is expected to arrive next Wednesday, so I'd say let's wait for another week.

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
