### PR TITLE
swift 3.0.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
I'm not sure if this should be `depends_on :el_capitan` or if there's a way to maintain the Yosemite compatibility.

**Comment by mistydemeo** [comment]
Hm, I wouldn't have expected breakage on a point release.

**Comment by ilovezfs** [comment]
@mistydemeo not sure how to explain this, but it looks like 3.0.1 is also broken ... https://bot.brew.sh/job/Homebrew%20Testing/1181/

**Comment by ilovezfs** [comment]
@mistydemeo ah well there's the explanation. 3.0.1 was pulled without a Yosemite bottle: https://github.com/Homebrew/homebrew-core/pull/6645

**Comment by MikeMcQuaid** [comment]
> I'm not sure if this should be depends_on :el_capitan or if there's a way to maintain the Yosemite compatibility.

Almost certainly the dependency is on a Xcode or Clang version but if it's building with the CLT we don't have a great way of articulating that currently so 👍

**Comment by JCount** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
