### PR TITLE
php@7.3 7.3.31

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by derrabus** [comment]
Looks like the Ubuntu build tries to install two versions of OpenSSL that don't like each other. 🤔

**Comment by Bo98** [comment]
`git` uses OpenSSL 3, and I don't think it should be yet.

OpenSSL 1.1 should also really be made keg-only.

**Comment by Bo98** [comment]
I've fixed the dep tree now. Should hopefully work after a rebase.

**Comment by bevanjkay** [comment]
@Bo98 passed on Linux this time around. Thanks!

**Review by SMillerDev — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Pull request closed without merging**
