### PR TITLE
openjdk@8 1.8.0+302

### PR DESCRIPTION
**Pull request by yurikoles**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by yurikoles** [comment]
I think that CI-long-timeout is required.

**Comment by yurikoles** [comment]
Linux is expected to fail because #80957 isn't merged yet.

**Comment by SMillerDev** [comment]
No ARM support yet?

**Comment by yurikoles** [comment]
They seem to only fix critical and security issues in this major release from 2014

**Comment by SMillerDev** [comment]
I read some talk about backporting it, I guess not any time soon then.

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Thanks @yurikoles  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
