### PR TITLE
sdl2 2.28.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
`brew test --retry --verbose portablegl`

**Comment by chenrui333** [comment]
let ship and followup on 13-arm test failure for `portablegl`

**Review by p-linnane — APPROVED** [review]

**Comment by chenrui333** [comment]
> `brew test --retry --verbose portablegl`

failed in my local as well after the upgrade, https://gist.github.com/chenrui333/b2415de703f19bae2fb2b9a687057f06

**Comment by chenrui333** [comment]
also same test failure againsst sdl2 2.28.2
https://gist.github.com/chenrui333/628e70e1c5ab0f0839c1d045abccc043

**Pull request merged**
