### PR TITLE
kubernetes-helm 2.6.0

### PR DESCRIPTION
**Pull request by scottrigby**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @scottrigby for your contribution to Homebrew! We couldn't do it without contributors like you,  you rock!

**Comment by scottrigby** [comment]
@fxcoudert closed without merge?

**Comment by fxcoudert** [comment]
@scottrigby merged in https://github.com/Homebrew/homebrew-core/commit/ea2be7521224d2173caa07fd144759feb6f906d3

**Comment by scottrigby** [comment]
Ha never mind, Thanks! 🍾

**Pull request closed without merging**
