### PR TITLE
libsndfile: add static lib

### PR DESCRIPTION
**Pull request by jeroen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

No revision bump needed because this only adds a file to the bottle, no other changes.

Some precedents: https://github.com/Homebrew/homebrew-core/pulls?q=static+is%3Apr+author%3Ajeroen+is%3Aclosed

### CODE REVIEW

**Comment by jeroen** [comment]
I think this needs the `long-run` tag.

**Comment by fxcoudert** [comment]
I don't think we want to add static libraries to all our formulas, so this is not a justification in itself. It's a very stable library, there is no demonstrated need for static libraries.

**Comment by fxcoudert** [comment]
Also, it basically doubles the build time :(

**Comment by jeroen** [comment]
It add like 1 minute of build time. It really helps people that need to build a static application or bindings (without dlls).

**Comment by iMichka** [comment]
Rebuilding with long run CI.
Given https://github.com/Homebrew/homebrew-core/pull/162352#issuecomment-1940781416, this should be OK to ship.

**Review by iMichka — APPROVED** [review]

**Pull request merged**
