### PR TITLE
graphviz migrated to cask

### PR DESCRIPTION
**Pull request by AnastasiaSulyagina**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?

---

Deleting graphviz from homebrew-core as part of deduplication process . See context [here](https://github.com/caskroom/homebrew-cask/issues/15603). 

_Please note that this PR is created to continue case-by-case discussions from thread linked above and if decision is made not to remove the formula, PR will be closed._

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 I thought this was being kept.

**Comment by AnastasiaSulyagina** [comment]
Have not found any final decision, maybe just got lost in all the comments

**Comment by ilovezfs** [comment]
@AnastasiaSulyagina I'm thinking of

https://github.com/Homebrew/homebrew-core/pull/3103#issuecomment-233685716

```
brew uses --recursive graphviz
bokken                            gprof2dot                         homebrew/php/mondrian           
eralchemy                         makefile2graph                    homebrew/php/php-plantumlwriter 
fobis                             plantuml                          homebrew/science/pnapi          
ford                              simgrid                         
gammaray                          xdot 
```

**Comment by AnastasiaSulyagina** [comment]
Yep, I definitely did. Closed

**Comment by ilovezfs** [comment]
@AnastasiaSulyagina Thanks!

**Comment by DomT4** [comment]
Yeah. My personal hard red lines on these is:
* If we move the formula, are we going to have to remove a number of other related formulae for no reason beyond wanting to move this one, regardless of any other factors like the dependent formulae being popular, easy to maintain, etc?
* If we move the formula but don't scrap the dependent formulae, are we essentially saying we're going to start building against upstream packages or app bundles we have no control over?

If the answer to either question is "yes", it's going to take a very strong & measured argument to get me to cross back over from the red line.

**Pull request closed without merging**
