### PR TITLE
libgrape-lite 0.2.2

### PR DESCRIPTION
**Pull request by kou**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sighingnow** [comment]
Thank you @kou. I was just on the way for this PR :heart:

**Comment by kou** [comment]
This was needed for #114034. :-)
https://github.com/Homebrew/homebrew-core/actions/runs/3334613017/jobs/5517795642

**Comment by kou** [comment]
I think that the failure is a network problem:

https://github.com/Homebrew/homebrew-core/actions/runs/3334869103/jobs/5518300832#step:10:112

```text
  curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
  Error: vineyard: Failed to download resource "llvm"
  Download failed: https://ghcr.io/v2/homebrew/core/llvm/blobs/sha256:932da8904c78c7501328b4e0be25d14c731f42826c2343ba9a0e2290bd16c777
```

Could someone restart the job?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks!!

**Pull request closed without merging**
