### PR TITLE
zellij 0.17.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
on linux
```
warning: be sure to add `/home/linuxbrew/.linuxbrew/Cellar/zellij/0.16.0/bin` to your PATH to be able to run the installed binaries
Error: Failure while executing; `/home/linuxbrew/.linuxbrew/Cellar/zellij/0.16.0/bin/zellij setup --generate-completion bash` exited with 1. Here's the output:
```

**Comment by chenrui333** [comment]
cc @cho-m

**Comment by cho-m** [comment]
The CI logs aren't very helpful here as it only shows that the compilation was successful, but failed running completion command without any useful stdout/stderr.

The may need to be built outside CI to see what is issue when running the command.

**Comment by chenrui333** [comment]
cargo download issue
```
error: failed to compile `zellij v0.17.0 (/tmp/zellij-20210918-6436-bxhp00/zellij-0.17.0)`, intermediate artifacts can be found at `/tmp/zellij-20210918-6436-bxhp00/zellij-0.17.0/target`

Caused by:
  failed to download from `https://crates.io/api/v1/crates/generational-arena/0.2.8/download`

Caused by:
  [92] Stream error in the HTTP/2 framing layer (HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1))
```

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
