### PR TITLE
python-yq 2.14.0

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by branchvincent** [comment]
`error: could not create '/opt/homebrew/lib/python3.10/site-packages/argcomplete': Operation not permitted`

**Comment by cho-m** [comment]
Same Python 3.10 issue seen in `pybind11` (#94696) and `mercurial` (#95399). Still need someone to debug issue to find why mkdir is failing.

This PR has an easier fix since we can switch to virtualenv `pip install` to avoid issues using deprecated setuptools.

**Comment by carlocab** [comment]
`mkdir` is failing because it's trying to write outside the formula prefix:
```
/opt/homebrew/lib/python3.10/site-packages/argcomplete
```
This is not allowed by our sandbox.

**Comment by cho-m** [comment]
> `mkdir` is failing because it's trying to write outside the formula prefix:

I also debugged that at https://github.com/Homebrew/homebrew-core/pull/95399#issuecomment-1046644550 where the install scheme patched into Python 3.10.2 is not capable of understanding `--prefix`.

I am guessing this was set to allow packages to find other installed packages, but it breaks installation via distutils `install_lib`. Unless there is another solution we can use inside `python@3.10` formula, we can go with alternatives like:
- `python-yq` - switch to `virtualenv_install_with_resources`
- `mercurial` - inreplace the Makefile to install with `--install-lib`, `--install-scripts`
- `pybind11` - add `"--install-lib=#{prefix/site_packages}"` as argument to install step

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
