### PR TITLE
workflows: add autopublish workflow

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Automation process continues. In this PR - new workflow for running `brew pr-automerge --publish` once every hour.

### CODE REVIEW

**Comment by dawidd6** [comment]
I believe that would lead us to @BrewTestBot pinging itself in the comments, so I would propose a new way handling this: slapping labels on PRs, like:
- publish workflow run started: `upload/in_progress`
- publish workflow failed: `upload/failed` (and post a comment)
- publish workflow completed `upload/completed` (or skip this entirely)

Every new workflow run would just remove all those `upload/` prefixed labels at the beginning.

**Comment by dawidd6** [comment]
Also, won't work for `new formula` PRs, cause `brew` won't find new formulae in the tap, so for now we could just skip those with this label.

**Comment by jonchang** [comment]
Honestly I'm pretty ambivalent on the whole pinging thing to begin with. I'd be OK with not doing the ping if the actor is brewtestbot. Thoughts?

I'd like to see this merged without `--publish` just so we can verify that it works well. If it does we can crank this up to once every 15 mintues with `--publish`.

Should test-bot remove the `ready to merge` label on failed uploads to avoid endless restarts?

**Comment by SMillerDev** [comment]
I'd say the labels are a good way since maintainers need to know that an action would conflict. And it can then check `if Ready to merge && !upload failed`. But leaving the comment system when the user isn't testbot seems nice for clarity.

**Pull request merged**
