### PR TITLE
awscli 1.16.270

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
22:26:12 ==> /usr/local/Cellar/conjure-up/2.6.9/bin/conjure-up --version
22:26:12 Error: conjure-up: failed
22:26:12 An exception occurred within a child process:
22:26:12   Test::Unit::AssertionFailedError: <0> expected but was
22:26:12 <nil>.

**Comment by chenrui333** [comment]
same as what happened in https://github.com/Homebrew/homebrew-core/pull/45368

**Comment by chenrui333** [comment]
Trying to rebuild conjure-up, got the following build error.
```
  subprocess.CalledProcessError: Command '['make', 'check']' returned non-zero exit status 2.
  Building wheel for PyNaCl (PEP 517): finished with status 'error'
  ERROR: Failed building wheel for PyNaCl
  Running setup.py clean for PyNaCl
  Running command /usr/local/Cellar/conjure-up/2.6.9_1/libexec/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-26yyu7l6/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-26yyu7l6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  running clean
  removing 'build/temp.macosx-10.14-x86_64-3.7' (and everything under it)
  removing 'build/lib.macosx-10.14-x86_64-3.7' (and everything under it)
  'build/bdist.macosx-10.14-x86_64' does not exist -- can't clean it
  'build/scripts-3.7' does not exist -- can't clean it
  removing 'build'
Failed to build PyNaCl
Cleaning up...
  Removing source in /private/tmp/pip-req-build-26yyu7l6
Removed build tracker '/private/tmp/pip-req-tracker-ck12yfwg'
ERROR: Could not build wheels for PyNaCl which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/conjure-up/2.6.9_1/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/conjure-up/2.6.9_1/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 426, in run
    ", ".join(r.name for r in build_failures)))
pip._internal.exceptions.InstallationError: Could not build wheels for PyNaCl which use PEP 517 and cannot be installed directly
ln -s ../Cellar/conjure-up/2.6.9/bin/conjure-down conjure-down
ln -s ../Cellar/conjure-up/2.6.9/bin/conjure-up conjure-up
ln -s ../Cellar/conjure-up/2.6.9/bin/kv-cli kv-cli
```

**Comment by chenrui333** [comment]
Maybe relates to this, https://github.com/pyca/pynacl/issues/555

**Comment by chenrui333** [comment]
Relates to https://github.com/Homebrew/homebrew-core/pull/44831

**Comment by Bo98** [comment]
Superseded by the already merged #46687.

**Pull request closed without merging**
