### PR TITLE
kubebuilder 3.11.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Not marked as latest: https://github.com/kubernetes-sigs/kubebuilder/releases

**Comment by p-linnane** [comment]
Same label issue as #134309

**Comment by chenrui333** [comment]
I saw the label is latest?
image

**Review by p-linnane — APPROVED** [review]
Marked as latest now.

**Pull request merged**
