### PR TITLE
node 7.7.1

### PR DESCRIPTION
**Pull request by JCount**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
Any chance you can pick up the test issue I highlighted in the other thread? ❤️. Looks like `bit` is checking for updates automatically on run, how fun.

**Comment by JCount** [comment]
@DomT4 Yes, I saw `bit`'s behavior, 😡 . (I am currently working on trimming the fat off the test.)

**Comment by JCount** [comment]
7.7.1 still bundles `npm` 4.1.2, so no need to update the version.

**Comment by DomT4** [comment]
Thanks for sorting this @JCount 🙌 . Just another day in dev paradise 🙈.

**Pull request closed without merging**
