### PR TITLE
ssh-vault 0.12.7

### PR DESCRIPTION
**Pull request by nbari**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by nandahkrishna** [comment]
@nbari The action was probably not configured correctly, as it did not update the `tag` and `revision` but changed just the `url`. I've fixed this and updated the formula to use the archive URL instead.

**Comment by nbari** [comment]
hi @nandahkrishna, many thanks, the app works on M1/arm64 how to adjust the formula?

**Review by nandahkrishna — COMMENTED** [review]
Great. We can use the patch I've given below then. Could you apply this patch and update the pull request? (I can do it if you aren't able to.)
```diff
diff --git a/Formula/ssh-vault.rb b/Formula/ssh-vault.rb
index b955209e48..3686296cf1 100644
--- a/Formula/ssh-vault.rb
+++ b/Formula/ssh-vault.rb
@@ -13,19 +13,11 @@ class SshVault < Formula
     sha256 cellar: :any_skip_relocation, high_sierra: "c6cf671474c67600ddac7bbcae909797c8ba26e16692533b5e82faa153ea9d77"
   end
 
-  depends_on "dep" => :build
   depends_on "go" => :build
 
   def install
-    ENV["GOPATH"] = buildpath
-    ENV["GO111MODULE"] = "auto"
-    (buildpath/"src/github.com/ssh-vault/ssh-vault").install buildpath.children
-    cd "src/github.com/ssh-vault/ssh-vault" do
-      system "dep", "ensure", "-vendor-only"
-      ldflags = "-s -w -X main.version=#{version}"
-      system "go", "build", "-ldflags", ldflags, "-o", "#{bin}/ssh-vault", "cmd/ssh-vault/main.go"
-      prefix.install_metafiles
-    end
+    ldflags = "-s -w -X main.version=#{version}"
+    system "go", "build", *std_go_args(ldflags: ldflags), "cmd/ssh-vault/main.go"
   end
 
   test do
```

**Comment by nbari** [comment]
Hi @nandahkrishna if you could help me applying the patch I would appreciate it 👍

**Review by nandahkrishna — APPROVED** [review]
Thanks @nbari, this has been bottled for ARM.

**Comment by nbari** [comment]
@nabarunnag many thanks 👍

**Pull request closed without merging**
