### PR TITLE
elm 0.17

### PR DESCRIPTION
**Pull request by jtwebman**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by ilovezfs** [comment]
Do you know if all the gymnastics in `def install` are actually still required for 0.17?

**Comment by jtwebman** [comment]
@ilovezfs what do you mean by gymnastics?

**Comment by ilovezfs** [comment]
@jtwebman Compare, for example, git-annex which only needs to do
```
install_cabal_package :using => ["alex", "happy", "c2hs"], :flags => ["webapp"] 
```
and agda which only needs to do
```
install_cabal_package :using => ["alex", "happy", "cpphs"]
```
Currently elm is not making any use of that newer method and I'm wondering if that still has to remain true.

**Comment by jtwebman** [comment]
@ilovezfs I am not sure, I was just updating it to the latest packages as it was released a few days ago now. The main people on Elm don't see brew as one of the official packages.

**Comment by jtwebman** [comment]
@ilovezfs Looks like this is still needed from the build from source hs file. 

https://github.com/elm-lang/elm-platform/blob/master/installers/BuildFromSource.hs

**Comment by ilovezfs** [comment]
@jtwebman 

>The main people on Elm don't see brew as one of the official packages.

Do you have citation(s) for this? Are there particular concerns they've expressed?

**Comment by ilovezfs** [comment]
@jtwebman Thank you for that link it. That helps explain why this install method is the way it is. We should probably have a comment with that link in the formula.

Reading through that, it does make me wonder if we could simplify this formula by relying more heavily on the upstream build script which a) uses a sandbox just as we do b) handles the vendoring of each of the resources the formula is doing manually c) performs the directories' gymnastics the formula is doing manually.

**Comment by jtwebman** [comment]
@ilovezfs I have no concern with it I was just updating this because our team uses brew more then the npm way to install Elm. I am sure changes could be made but this works now so I hope we can get this pull request merged and then we can work on a better way to build it.

**Comment by ilovezfs** [comment]
Thank you for your contribution to Homebrew @jtwebman :tada:

**Comment by jtwebman** [comment]
@ilovezfs No merge, just closed?

**Comment by ilovezfs** [comment]
@jtwebman Yup it gets rebased on origin/master so that there aren't any merge commits. Also, in this case I squashed it down to a single commit, and set the standard bump subject.

**Comment by DomT4** [comment]
> I guess you guys just move the commit.

We cherry-pick commits that need bottle updates, in particular. Commit credit is still fully assigned to you.

**Comment by jtwebman** [comment]
@ilovezfs @DomT4 Awesome, I actually kind of like it this way!

**Pull request closed without merging**
