### PR TITLE
lighthouse 2.4.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
    make[2]: *** [CMakeFiles/libprotobuf-lite.dir/Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/src/google/protobuf/stubs/strutil.cc.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/src/google/protobuf/stubs/strutil.cc:1255:19: error: expected unqualified-id
      } else if (std::isnan(value)) {
                      ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/math.h:165:5: note: expanded from macro 'isnan'
        ( sizeof(x) == sizeof(float)  ? __inline_isnanf((float)(x))          \
        ^
    /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/src/google/protobuf/stubs/strutil.cc:1373:19: error: expected unqualified-id
      } else if (std::isnan(value)) {
                      ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/math.h:165:5: note: expanded from macro 'isnan'
        ( sizeof(x) == sizeof(float)  ? __inline_isnanf((float)(x))          \
        ^
```

**Comment by carlocab** [comment]
Probably a file called `VERSION` (or `version`) somewhere in the include path that isn't a header. It breaks the build of the `protobuf` vendored at https://github.com/tokio-rs/prost/tree/4459a1e36a63a0e10e418b823957cc80d9fbc744/protobuf.

**Comment by terorie** [comment]
Will investigate this further

**Comment by carlocab** [comment]
@terorie, it might help to persuade this to use Homebrew's `protobuf` instead of vendoring to avoid the build error.

CC @michaelsproul, since you were looking at #103752.

**Comment by carlocab** [comment]
Let's re-run without failing fast to get a better look at the error across different systems. My guess is that this should fail on every macOS runner.

**Comment by carlocab** [comment]
It fails at building on ARM Big Sur too, but with a different error:
```
    In file included from /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/src/google/protobuf/arenastring.cc:31:
    In file included from /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/src/google/protobuf/arenastring.h:38:
    In file included from /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/src/google/protobuf/stubs/logging.h:36:
    In file included from /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/src/google/protobuf/stubs/status.h:36:
    In file included from /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/src/google/protobuf/stubs/stringpiece.h:155:
    In file included from /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.4/third-party/protobuf/src/google/protobuf/stubs/hash.h:38:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/unordered_map:411:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/__hash_table:18:
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:321:9: error: no member named 'signbit' in the global namespace
    using ::signbit;
          ~~^
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:322:9: error: no member named 'fpclassify' in the global namespace
    using ::fpclassify;
          ~~^
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:323:9: error: no member named 'isfinite' in the global namespace
    using ::isfinite;
          ~~^
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:324:9: error: no member named 'isinf' in the global namespace
    using ::isinf;
          ~~^
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:325:9: error: no member named 'isnan' in the global namespace
    using ::isnan;
          ~~^
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:326:9: error: no member named 'isnormal' in the global namespace
    using ::isnormal;
          ~~^
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/cmath:327:7: error: no member named 'isgreater' in the global namespace; did you mean '::std::greater'?
    using ::isgreater;
          ^~
    /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include/c++/v1/functional:738:29: note: '::std::greater' declared here
    struct _LIBCPP_TEMPLATE_VIS greater : binary_function<_Tp, _Tp, bool>
                                ^
```
I don't think this is an `#include <version>` problem.

This is usually a consequence of some sort of SDK mismatch, I think.

**Comment by terorie** [comment]
I remember seeing this C++ error on an unrelated project. Related StackOverflow post: https://stackoverflow.com/questions/58628377/catalina-c-using-cmath-headers-yield-error-no-member-named-signbit-in-th

**Comment by carlocab** [comment]
> I remember seeing this C++ error on an unrelated project.

I've seen this error quite a lot across different formulae. I haven't quite figured out the cause, however. I believe there isn't a consistent single one. That is, many different things could lead to this particular error, so it's a bit difficult to pin down the exact cause from seeing only this.

**Comment by terorie** [comment]
`PROTOC_NO_VENDOR` might work, testing … https://github.com/tokio-rs/prost/blob/master/prost-build/README.md

**Comment by terorie** [comment]
@chenrui333 @carlocab fix is here: 

```patch
From 84a8b59e3a759906759378f1e3027b96e80e70c8 Mon Sep 17 00:00:00 2001
From: Richard Patel <me@terorie.dev>
Date: Thu, 4 Aug 2022 02:23:11 +0200
Subject: [PATCH] lighthouse fix

---
 Formula/lighthouse.rb | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/Formula/lighthouse.rb b/Formula/lighthouse.rb
index 5b6739259d5..666cd6506ad 100644
--- a/Formula/lighthouse.rb
+++ b/Formula/lighthouse.rb
@@ -17,6 +17,8 @@ class Lighthouse < Formula
   depends_on "cmake" => :build
   depends_on "rust" => :build
 
+  depends_on "protobuf"
+
   uses_from_macos "zlib"
 
   on_linux do
@@ -24,6 +26,8 @@ class Lighthouse < Formula
   end
 
   def install
+    ENV["PROTOC_NO_VENDOR"] = "1"
+
     system "cargo", "install", *std_cargo_args(path: "./lighthouse")
   end
 
-- 
2.32.1 (Apple Git-133)

```

**Comment by carlocab** [comment]
Great find; thanks, @terorie! I remember looking at the `prost` README, but I missed this one.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
