### PR TITLE
libpqxx 7.6.0

### PR DESCRIPTION
**Pull request by lacasaprivata2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks, @vitruvvius. For future reference, our preferred commit message format here is
```
libpqxx 7.6.0
```
Please see the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit) referenced in the PR template:

> The preferred commit message format for simple version updates is `foobar 7.3`

**Comment by vitruvvius** [comment]
Thank you - accidentially forgot to change the hash, not sure logic behind the rest of these other errors

**Comment by vitruvvius** [comment]
would you mind taking this to completion?

**Comment by carlocab** [comment]
The main failure is
```
brew linkage --test osm2pgrouting
```
which we can fix with a revision bump. Doing that for you.

**Review by miccal — APPROVED** [review]

**Pull request closed without merging**
