### PR TITLE
flow 0.62.0

### PR DESCRIPTION
**Pull request by JCount**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
01:35:46 ==> brew test flow --verbose
01:35:47 ==> FAILED
01:35:47 Testing flow
01:35:47 /usr/bin/sandbox-exec -f /tmp/homebrew20171223-88034-1c1r3cq.sb /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/flow.rb --verbose
01:35:47 ==> /usr/local/Cellar/flow/0.62.0/bin/flow init /tmp/flow-test-20171223-88035-1pw8i6f
01:35:47 ==> /usr/local/Cellar/flow/0.62.0/bin/flow check /tmp/flow-test-20171223-88035-1pw8i6f
01:35:47 .flowconfig:8 Redundant argument. This argument doesn't change any lint settings.
01:35:47 Error: flow: failed
01:35:47 <2> expected but was
01:35:47 <8>.
```

**Comment by JCount** [comment]
Tracking the original #22057 PR.

**Comment by samwgoldman** [comment]
Sorry, I messed up the tag on GitHub, so the build script was pulling the wrong source tarball and ran into an issue that's on master.

I force-pushed the tag to GitHub just now, so just re-running the test should pass.

**Comment by ilovezfs** [comment]
Thanks @samwgoldman. I've updated the checksum and requeued CI.

**Pull request closed without merging**
