### PR TITLE
elm: un-deprecate

### PR DESCRIPTION
**Pull request by wolfadex**
Uses stable ghc 9.4
Last commit on project in Sep. 2023
Meets cited criteria in deprecation PR

The Elm formula was [recently deprecated](https://github.com/Homebrew/homebrew-core/pull/141941) citing a dependency on an older version of ghc (v8.10) and being unable to compile on ARM based Macs "in a few years". Since then the Elm [compiler has been updated](https://github.com/elm/compiler/commit/0421dfbe48e53d880a401e201890eac0b3de5f06) to a much newer version of ghc (v9.4).

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

I still need to address the last 3 checkboxes. Will be doing so later today.

### CODE REVIEW

**Comment by Bo98** [comment]
Thanks for doing this! The change doesn't appear to have been tagged in a release yet so you'll need to apply the change as a patch.

**Comment by wolfadex** [comment]
> Thanks for doing this! The change doesn't appear to have been tagged in a release yet (latest is still 0.19.1 from 2019) so you'll need to apply upstream's change as a patch.

@Bo98 thanks for the feedback, though I'm not sure I understand. I was wondering while reading the Formula file if I need to change a sha somewhere. Do you mean I need to change [lines 4 & 5](https://github.com/Homebrew/homebrew-core/blob/b615d5df8b0bfc33b7a3f14a790a0d31f6d0f182/Formula/e/elm.rb#L4-L5)
```rb
  url "https://github.com/elm/compiler/archive/0.19.1.tar.gz"
  sha256 "aa161caca775cef1bbb04bcdeb4471d3aabcf87b6d9d9d5b0d62d3052e8250b1"
```
to point specifically at this new release? If so, how might I branch based on the target, to use either the previous build for Intel based Macs and the new build only for ARM based Macs?

**Comment by iMichka** [comment]
Thanks for working on this. Can we wait for #141617 to be shipped? It will provide a new `ghc@9.4` formula that can be used here.

**Comment by wolfadex** [comment]
@iMichka I think that's reasonable to wait for.

**Comment by iMichka** [comment]
Could you remove the merge commit ? Best is to have only one single commit at the end. Thanks.

**Comment by ahankinson** [comment]
Adding this `patch` block will apply the latest changes in the elm repo to get it to build on the newer haskell compiler. 

```
patch do
    # These patches allow elm to build on ghc 9.4+. 
    url "https://github.com/elm/compiler/commit/0421dfbe48e53d880a401e201890eac0b3de5f06.patch?full_index=1"
    sha256 "b498e39112ab7306b18b47821e799bf436d0c2151836187388c2a6b6f32bd437"
end
```

Tested on my M1 Macbook Pro, and it seems to work now.

**Comment by chenrui333** [comment]
@wolfadex ping, can you do a rebase to the latest master rather than merge into your branch?

**Comment by wolfadex** [comment]
I've run short on time to address the necessary changes and @ahankinson has offered to make a fresh PR to address these issues.

**Comment by chenrui333** [comment]
#152453

**Comment by chenrui333** [comment]
Thanks @wolfadex and @ahankinson!

**Pull request closed without merging**
