### PR TITLE
apr-util: add openssl 1.1 support

### PR DESCRIPTION
**Pull request by ilovezfs**
:recommended so CI tests it, but may want to start out with it :optional

CC @DomT4

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
👍 on adding this option for testing but if we do go for on-by-default I think it's probably worth not having an option.

**Comment by DomT4** [comment]
You'll want to check how much `brew uses apr-util` stuff also `brew uses openssl` and then see if those can be moved across to `openssl@1.1` as well, but whilst patching crypto support is hairy I think if folks want to move forwards on `openssl@1.1` transitions `apr-util` will need to be shunted across due to its increasingly wide usage.

**Comment by DomT4** [comment]
Colour me pleasantly surprised `serf` actually builds with `openssl@1.1`. There's some redundant logic further down the `subversion` formula about `apr=/usr/` etc that can be shrunk since Homebrew has adopted a love of using its Apr formulae rather than clinging onto the system for 10.11 and lower.

**Comment by ilovezfs** [comment]
Looks like the relevant brew uses set, assuming no undeclared dependencies on openssl, is apib, freeswitch, hydra, nginx, passenger, subversion, and subversion18.

**Comment by ilovezfs** [comment]
If I also include the dependencies of the reverse dependencies, then that adds to the set curl, freetds, homebrew/dupes/openldap, ldns, libevent, libssh, libssh2, mysql, nghttp2, postgresql, python, rtmpdump, and spdylay.

**Comment by ilovezfs** [comment]
reverse dependencies that use openssl:

- [ ] apib
- [ ] freeswitch
- [ ] hydra
- [ ] nginx
- [ ] passenger
- [ ] subversion
- [ ] homebrew/versions/subversion18

---

dependencies of reverse dependencies that use openssl:

- [ ] curl (optional)
- [ ] freetds
- [ ] homebrew/dupes/openldap
- [ ] ldns
- [ ] libevent
- [ ] libssh
- [ ] libssh2
- [ ] mysql
- [ ] nghttp2
- [ ] postgresql
- [ ] python
- [ ] rtmpdump
- [ ] spdylay

**Comment by ilovezfs** [comment]
Working the tree back to reverse dependencies of the dependencies of the reverse dependencies, the scope reaches to

- [ ] ansible
- [ ] certbot
- [ ] efl
- [ ] eralchemy
- [ ] ffmpeg
- [ ] folly
- [ ] gearman
- [ ] getdns
- [ ] gloox
- [ ] gpac
- [ ] gst-plugins-bad
- [ ] gwenhywfar
- [ ] homebrew/dupes/openssh
- [ ] homebrew/python/pyrit
- [ ] homebrew/science/blat
- [ ] homebrew/science/gdcm
- [ ] homebrew/science/kent-tools
- [ ] homebrew/science/openimageio
- [ ] homebrew/science/root
- [ ] homebrew/science/root6
- [ ] homebrew/science/ucsc-genome-browser
- [ ] homebrew/versions/ffmpeg28
- [ ] homebrew/versions/gst-plugins-bad010
- [ ] homebrew/versions/node010
- [ ] homebrew/versions/postgresql93
- [ ] homebrew/versions/postgresql94
- [ ] homebrew/versions/thrift090
- [ ] innotop
- [ ] inspircd
- [ ] knot
- [ ] kore
- [ ] libcouchbase
- [ ] libdap
- [ ] libgda
- [ ] libimobiledevice
- [ ] libopendkim
- [ ] libtorrent-rasterbar
- [ ] libxmlsec1
- [ ] libzdb
- [ ] megatools
- [ ] midnight-commander
- [ ] mitmproxy
- [ ] mycli
- [ ] mydumper
- [ ] mysql-connector-c++
- [ ] mytop
- [ ] nagios-plugins
- [ ] net-snmp
- [ ] nrpe
- [ ] nsd
- [ ] nut
- [ ] ooniprobe
- [ ] openconnect
- [ ] opensaml
- [ ] osquery
- [ ] percona-toolkit
- [ ] percona-xtrabackup
- [ ] pgcli
- [ ] ponyc
- [ ] postgres-xc
- [ ] profanity
- [ ] psqlodbc
- [ ] pure-ftpd
- [ ] pwntools
- [ ] qca
- [ ] qt
- [ ] radare2
- [ ] rtags
- [ ] rust
- [ ] sane-backends
- [ ] sslsplit
- [ ] sstp-client
- [ ] strongswan
- [ ] sysbench
- [ ] thrift
- [ ] tlsdate
- [ ] tor
- [ ] unbound
- [ ] upscaledb
- [ ] urweb
- [ ] uwsgi
- [ ] xml-tooling-c

**Comment by ilovezfs** [comment]
And taking into account the dependencies of the reverse dependencies of the dependencies of the reverse dependencies:

- [ ] afflib
- [ ] asio
- [ ] botan
- [ ] cpp-netlib
- [ ] libewf
- [ ] libstrophe
- [ ] mongodb
- [ ] neon
- [ ] pkcs11-helper
- [ ] pulseaudio
- [ ] pypy
- [ ] python3
- [ ] srtp
- [ ] xml-security-c
- [ ] xrootd
- [ ] yara

**Comment by DomT4** [comment]
I think you're noticing why I was worried this could take Homebrew years to get done 😄. Debian has patched an awful lot in their unstable distro, so Homebrew could go for an en mass update using Debian patching, but uncertain if those patches went upstream, have been reviewed/accepted upstream/etc.

**Comment by ilovezfs** [comment]
@DomT4 I think it also shows why simultaneously having multiple versions of the same library in core is :no_good_man:

**Comment by DomT4** [comment]
Heh, well, that ship has probably sailed or is about to sail with version support, because there's pretty significant demand there to stop breaking taps on `boost` updates, etc regularly.

But OpenSSL in Homebrew is inherently complicated because almost anything that touches crypto/ssl on OS X uses or can use OpenSSL but the system ships garbage, which means relying on Homebrew's OpenSSL 100%. Even stuff like killing SSLv3 for `openssl` which is desirable is more or less impossible to do now thanks to how wide a revision season it would need.

**Comment by ilovezfs** [comment]
>Heh, well, that ship has probably sailed or is about to sail with version support, because there's pretty significant demand there to stop breaking taps on boost updates, etc regularly.

We may hard code the bottle versions instead.

**Comment by MikeMcQuaid** [comment]
> We may hard code the bottle versions instead.

That would be an "as well" rather than "instead"; it doesn't help anyone building from source.

**Comment by DomT4** [comment]
I think any versioning solution is going to end up being overwhelmingly complicated, to be honest. I agree the version support needs to improve, but across my time in Homebrew up to last month nobody, myself included, had really fleshed out a mechanism that didn't have serious issues around either complexity, heavy maintainer burden, or potential security implications. The whole thing is a bit of an endless nightmare.

**Comment by ilovezfs** [comment]
>I think any versioning solution is going to end up being overwhelmingly complicated, to be honest. I agree the version support needs to improve, but across my time in Homebrew up to last month nobody, myself included, had really fleshed out a mechanism that didn't have serious issues around either complexity, heavy maintainer burden, or potential security implications. The whole thing is a bit of an endless nightmare.

This.

**Comment by ilovezfs** [comment]
The scope of this PR might as well be all of https://github.com/Homebrew/homebrew-core/issues/4543 so I'm closing this out.

**Comment by MikeMcQuaid** [comment]
> I think any versioning solution is going to end up being overwhelmingly complicated, to be honest. I agree the version support needs to improve, but across my time in Homebrew up to last month nobody, myself included, had really fleshed out a mechanism that didn't have serious issues around either complexity, heavy maintainer burden, or potential security implications. The whole thing is a bit of an endless nightmare.

> more or less impossible to do now thanks to how wide a revision season it would need.

It's just going to be different. It's far from an insurmountable problem as pretty much every other package manager has better versioning support that we do and it's the number 1 recurring complaint about Homebrew. Regardless, it doesn't really matter as I'm the only person actively working on making this better so as long as I decide to keep working on it: it'll get better.

> That would be an "as well" rather than "instead"; it doesn't help anyone building from source.

Instead of the 👎 on this @ilovezfs a reason explaining what your objection is and how you propose helping people building from source would be good.

**Comment by ilovezfs** [comment]
>every other package manager has better versioning support that we do 

In the past you've been extremely quick to dismiss arguments that use that as a justification. People can feel free to use one of those other package managers.

>Instead of the :-1: on this @ilovezfs a reason explaining what your objection is 

It's will be a lot of extra, ongoing – in perpetuity – maintainer work (and I'm _not_ talking about the homebrew/brew changes you're volunteering to keep working on; the point is about the work in homebrew/core) for little benefit. The cost-benefit analysis is not even close.

>and how you propose helping people building from source would be good.

We could have a source build mode available that always builds a bottle and then installs it, and keep the bottle in the cache, using the same pegging strategy as the non-source builders.

**Comment by MikeMcQuaid** [comment]
> It will be a lot of extra, ongoing – in perpetuity – maintainer work (and I'm not talking about the homebrew/brew changes you're volunteering to keep working on; the point is about the work in homebrew/core) for little benefit. The cost-benefit analysis is not even close.

At the bare minimum there will be no more work than homebrew/versions while having the benefit that we don't intentionally break things. You are welcome to say "I'm not willing to maintain old versions of software" and that's fine. I have to use homebrew/versions every day to do my job and the current experience is not good enough and I'm going to make it better.

> We could have a source build mode available that always builds a bottle and then installs it, and keep the bottle in the cache, using the same pegging strategy as the non-source builders.

Which is essentially equivalent to not using `brew cleanup` or fixing it so it doesn't clean up linked directories. I'm all for that but it's not really a long-term solution.

**Comment by ilovezfs** [comment]
I'm tired of wasting my breath on this conversation. Do whatever you want.

**Pull request closed without merging**
