### PR TITLE
ssh-audit 2.3.1

### PR DESCRIPTION
**Pull request by 404NetworkError**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /usr/local/Cellar/ssh-audit/2.3.1/bin/ssh-audit -nt 0 ssh.github.com
Traceback (most recent call last):
  File "/usr/local/Cellar/ssh-audit/2.3.1/bin/ssh-audit", line 10, in <module>
    from ssh_audit.ssh_audit import main  # noqa: E402
ModuleNotFoundError: No module named 'ssh_audit'
Error: ssh-audit: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </\[exception\]/> was expected to be =~
<"">.
```

**Comment by bayandin** [comment]
I would suggest to bottle this package with venv and download it from pypi, should be something like this:

```ruby
class SshAudit < Formula
  include Language::Python::Virtualenv

  desc "SSH server & client auditing"
  homepage "https://github.com/jtesta/ssh-audit"
  url "https://files.pythonhosted.org/packages/61/09/d4ec73164f4548b7352389117ed0a30e47c444a76c18046421e22311f8ea/ssh-audit-2.3.1.tar.gz"
  sha256 "84d3294b25f3a1ce0a5f14094e80d85cfded3b5ef941c0df131cf7485d449b6b"
  license "MIT"
  head "https://github.com/jtesta/ssh-audit.git"

  depends_on "python@3.9"

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "(gen)", shell_output("#{bin}/ssh-audit -nt 10 ssh.github.com", 1)
  end
end
```

**Comment by 404NetworkError** [comment]
Thanks for the suggestion @bayandin!

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @bayandin!

**Pull request closed without merging**
