### PR TITLE
mesa 20.3.1

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
10.14
```
../src/util/u_queue.c:186:7: error: implicit declaration of function 'timespec_get' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      timespec_get(&ts, TIME_UTC);
      ^
1 error generated.
```

I think this can be fixed by passing a `-Wno-implicit-function-declaration` flag. Though, I'm surprised to see this in 10.14, and _only_ in 10.14...

**Comment by alebcay** [comment]
I personally think this is instead an issue with `timespec_get` not being available in (some versions of) macOS? At least that's what I gather from https://gitlab.freedesktop.org/mesa/mesa/-/issues/1020 and https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/2267.

**Comment by carlocab** [comment]
They can both be issues... but the one you point out would certainly be a much bigger hurdle.

**Comment by SMillerDev** [comment]
@yurikoles might have an idea

**Comment by yurikoles** [comment]
I had sent a [MR](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/6935) two months ago, but I didn't get any feedback so far. 

Could you please try to add it as a patch?

**Comment by fxcoudert** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-core/pull/67153

**Pull request closed without merging**
