### PR TITLE
JSON-Fortran and FORD new versions

### PR DESCRIPTION
**Pull request by zbeekman**
JSON-Fortran 5.0.0 released. Includes work around for regression in GFortran 6.1 (See PR #676 for more info/context)
FORD 4.6.0 released

### CODE REVIEW

**Comment by zbeekman** [comment]
what the heck, test failure? Investigating...

**Comment by UniqMartin** [comment]
> what the heck, test failure? Investigating...

I'm not sure why it's failing either. However, unless there are compelling reasons (maybe there are for these two) to bundle them together, we prefer to have individual PRs for individual formulae. Thus the ideal version bump PR is titled `<formula> <version>` and consists of a single commit with identical commit subject (see also our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document). This has the great benefit of updates not blocking each other in case of problems and allows us to (re-)run CI builds with more granularity.

Don't get me wrong, your numerous contributions are much appreciated! But as a regular contributor I wanted to make sure you're aware of our workflow and conventions, that I believe help everyone. [The PR template](https://github.com/Homebrew/homebrew-core/blob/master/.github/PULL_REQUEST_TEMPLATE.md), that you didn't retain in your PR body, contains a checklist that both serves as a subtle reminder for some of these things and links to relevant documentation.

**Comment by zbeekman** [comment]
Roger, sorry about that... I'll split the PR, and use github instead of hub to open the PR.

**Comment by UniqMartin** [comment]
Thanks! I didn't realize that you're using `hub` to create the PRs. This explains the missing templates and is something that possibly needs to be addressed by `hub` somehow.

**Comment by zbeekman** [comment]
also, I am a relatively frequent contributor, but GCC 6.1 is the most complicated contribution I've attempted to date... I don't have the rules memorized and am doing my best to adhere to best practices, and rules. I know you guys have a ton to keep up with, and appreciate your hard work you put in. I am more than happy to be corrected and told what I need to do to fix things.

**Comment by DomT4** [comment]
What's the status here?

**Comment by zbeekman** [comment]
Hi @DomT4,
Sorry I was away for the weekend... I'm about to open two new PRs with the formulas individually, and run down the JSON-Fortran build faulure...

**Comment by zbeekman** [comment]
I have confirmed that the JSON-Fortran build failure occurs due to the FORD upgrade... Investigating further.

**Comment by DomT4** [comment]
No worries at all! Thanks for the update.

**Comment by UniqMartin** [comment]
Thanks for submitting as separate PRs! I guess this can be closed now in favor of #1578 and #1580.

**Comment by zbeekman** [comment]
@UniqMartin yup, I was going to close this but time got away from me last night.

**Comment by UniqMartin** [comment]
@zbeekman No worries and thanks for working on this and other GCC/FORTRAN-related issues. We're lacking a bit in expertise in these areas and your work on this stuff in Homebrew is much appreciated!

**Pull request closed without merging**
