### PR TITLE
phpstan 1.10.0

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by derrabus** [comment]
@ondrejmirtes Apparently, bumping via GitHub Actions has failed this time: https://github.com/phpstan/phpstan/actions/runs/4233361640

**Review by SMillerDev — APPROVED** [review]

**Comment by ondrejmirtes** [comment]
@derrabus No idea why it failed with: `Error: No available formula with the name "phpstan".`

Hopefully it's gonna work next time. Thanks for the manual bump!

**Comment by ondrejmirtes** [comment]
Nope, still failing: https://github.com/phpstan/phpstan/actions/runs/4237210132/jobs/7362917458

No idea why...

**Comment by derrabus** [comment]
@ondrejmirtes We should probably report this to the author of the action.

**Comment by ondrejmirtes** [comment]
Yes, please do :)

**Comment by SMillerDev** [comment]
@dawidd6 any ideas?

**Comment by derrabus** [comment]
I've opened dawidd6/action-homebrew-bump-formula#51

**Pull request closed without merging**
