### PR TITLE
braid 1.1.3

### PR DESCRIPTION
**Pull request by ekesken**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
Thanks @ekesken!

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by ekesken** [comment]
test failed with error:

```
==> Applying patch
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
Error: Patch failed to apply: aborted.
```

@BrewTestBot can you re-test this please :)

**Comment by ekesken** [comment]
@lembacon anything I can do to fix the problem with tests?

**Comment by lembacon** [comment]
> @lembacon anything I can do to fix the problem with tests?

No, and don't worry. Our CI is having some issues right now, it should be back very soon. 😅

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
