### PR TITLE
libdrm: Added cairo as dependency

### PR DESCRIPTION
**Pull request by pmaas**
Building libdrm failed because of missing cairo.h:

```
tests/util/libutil.a.p/pattern.c.o.d -o tests/util/libutil.a.p/pattern.c.o -c ../tests/util/pattern.c
../tests/util/pattern.c:34:10: fatal error: cairo.h: No such file or directory
   34 | #include <cairo.h>
      |          ^~~~~~~~~
compilation terminated.
```

After adding cairo as dependency, everything works as expected.

### CODE REVIEW

**Comment by EvgenEgorov** [comment]
Hello!
I'm experiencing the same problem - I can't install libdrm because of cairo.h file missing

`d -o tests/util/libutil.a.p/pattern.c.o -c ../tests/util/pattern.c
../tests/util/pattern.c:34:10: fatal error: cairo.h: No such file or directory
   34 | #include <cairo.h>
      |          ^~~~~~~~~
compilation terminated.
`

Could you please explain what should I do to solve this problem?

**Comment by pmaas** [comment]
@EvgenEgorov I don't know Homebrew in detail and I'm not sure if this is the right way, but for me the issue was fixed after adding this line to the libdrm formula:
```
depends_on "cairo" => :build 
```
See: https://github.com/Homebrew/homebrew-core/pull/100868/files

**Comment by iMichka** [comment]
Looking at https://www.linuxfromscratch.org/blfs/view/svn/x/libdrm.html, `cairo` is necessary for the tests only.
It's weird that the tests are pre-compiled at build time though ... (one can see that in the error log provided by @pmaas )

Either we find a meson configuration flag that allows to disallow the tests, or we set:
`depends_on "cairo" => [:build, :test]`

**Comment by Bo98** [comment]
> maybe passing `-Dcairo-tests=false` to meson will work

**Review by SMillerDev — APPROVED** [review]
Thanks @pmaas  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
