### PR TITLE
dbus 1.11.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
I hate `dbus` bumps, they always silently break _something_. :shipit:.

**Comment by ilovezfs** [comment]
@DomT4 You're slipping! PR currently kills the mirror inappropriately.

**Comment by DomT4** [comment]
Oh, it's also a development release 🙈

**Comment by DomT4** [comment]
Apparently, anyway:
> # releases: even (1.10.x) = stable, odd (1.11.x) = development

**Comment by DomT4** [comment]
You may have to revert yourself here 😄

> The current stable branch is D-Bus 1.10.x. This is the recommended version for most purposes.
> The current development branch is D-Bus 1.11.x, which will lead to a 1.12.x stable branch in future.

**Comment by ilovezfs** [comment]
let's just move it to the devel block.

**Comment by DomT4** [comment]
👍. Will need to revert the bottle update at least, but then you could just push a quick commit to restore the URL to what it was & add this as `devel`.

**Pull request closed without merging**
