### PR TITLE
emqx 5.1.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre># v5.1.3

## Bug Fixes

- [#11306](https://github.com/emqx/emqx/pull/11306) Fixed rule action metrics inconsistency where dropped requests were not accounted for.

- [#11327](https://github.com/emqx/emqx/pull/11327) Update ekka to version 0.15.8, mria to version 0.5.10, and optvar to 1.0.5.
  This fixes occasional assertion failures:
  `{{badmatch,noproc},[{optvar,read,2,[{file,"optvar.erl"},{line,140}]},{optvar,read,1,[{file,"optvar.erl"},{line,124}]},...`

- [#11337](https://github.com/emqx/emqx/pull/11337) Fix HTTP API error when a publish topic rewrite rule targets a topic with wildcards. Now it returns error 400 (Bad Match) instead of error 500 (Internal Error).

- [#11346](https://github.com/emqx/emqx/pull/11346) Update ekka to version 0.15.9.
  This fixes dangling etcd locks occurred if acquiring the lock failed with a timeout.

- [#11352](https://github.com/emqx/emqx/pull/11352) Fixed this [#11345](https://github.com/emqx/emqx/issues/11345) crash issue when starting on Windows or any other platform without RocksDB support.
</pre>
</details>

### CODE REVIEW

**Comment by id** [comment]
Not sure what to do with this error.
Why `/opt/openssl@3/lib/libcrypto.3.dylib` is unexpected?

**Comment by chenrui333** [comment]
> Not sure what to do with this error. Why `/opt/openssl@3/lib/libcrypto.3.dylib` is unexpected?

yeah, bit interesting, let's see how it goes with a rerun.

**Comment by chenrui333** [comment]
#138228

**Comment by chenrui333** [comment]
let's see how it goes with the new release.

**Pull request closed without merging**
