### PR TITLE
perl 5.24.1

### PR DESCRIPTION
**Pull request by mkjaer**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by JCount** [comment]
@mkjaer It looks like vim needs a revision bump.

**Comment by mkjaer** [comment]
There is already a pull request for [vim](https://github.com/Homebrew/homebrew-core/pull/10219) to the latest version.

**Comment by JCount** [comment]
I missed that, thank you for pointing it out.

**Comment by fxcoudert** [comment]
@JCount `vim` update has been committed

**Comment by JCount** [comment]
Thank you for your contribution, @mkjaer! 😄

**Pull request closed without merging**
