### PR TITLE
edencommon fb303 fbthrift fizz folly mvfst proxygen wangle watchman 2024.01.08.00

### PR DESCRIPTION
**Pull request by timsutton**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by timsutton** [comment]
I expect this to fail with a similar error I saw with `proxygen` in last week's update:
```
Consolidate compiler generated dependencies of target hq
ld: Undefined symbols:
  quic::samples::HQLoggerHelper::HQLoggerHelper(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, quic::QuicNodeType), referenced from:
      std::__1::__shared_ptr_emplace<quic::samples::HQLoggerHelper, std::__1::allocator<quic::samples::HQLoggerHelper>>::__shared_ptr_emplace[abi:v160006]<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool, quic::QuicNodeType>(std::__1::allocator<quic::samples::HQLoggerHelper>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool&&, quic::QuicNodeType&&) in Client.cpp.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [proxygen/httpclient/samples/httperf2/liblibhttperf2.dylib] Error 1
make[1]: *** [proxygen/httpclient/samples/httperf2/CMakeFiles/libhttperf2.dir/all] Error 2
```

**Comment by p-linnane** [comment]
Yes, `proxygen` has been broken since September. Unless upstream can help us here, we will probably need to deprecate it.  Not sure if anyone has reached out to them yet.

**Comment by timsutton** [comment]
Mind if we also set no fast fail on this one? I see the monterey arm64 build fails for maybe an arch mismatch issue, which is different than the error above. It's possible there could be multiple separate issues. I'm happy to open an issue upstream, just would like a current reference for the errors I can point someone to.

**Comment by timsutton** [comment]
Reported upstream here: https://github.com/facebook/proxygen/issues/479

**Comment by timsutton** [comment]
Now I understand a bit better: the proxygen issue is with the provided sample client/server code, but the library itself builds. The `test` block though relies on some of the built samples targets. But at least it points to a possibility that we can either patch the sample code or pick a different working subset of the samples in order to have a functional test.

**Comment by timsutton** [comment]
[Comparison between](https://github.com/facebook/proxygen/compare/v2023.09.04.00..v2023.09.11.00) 2023.09.04 (the last built bottle) of proxygen and 2023.09.11. A lot of the code changes were around Quic being built by default instead of optionally.

**Comment by p-linnane** [comment]
Thanks for opening the upstream issue. I've added the "in progress" label so stalebot won't close this while we wait to hear back.

**Comment by SMillerDev** [comment]
Should this be closed in favour of https://github.com/Homebrew/homebrew-core/pull/160044?

**Comment by timsutton** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-core/pull/160044

**Pull request closed without merging**
