### PR TITLE
netcdf 4.7.0

### PR DESCRIPTION
**Pull request by luzpaz**
Created manually

### CODE REVIEW

**Comment by luzpaz** [comment]
Need some assistance.

**Comment by fxcoudert** [comment]
See previous try at https://github.com/Homebrew/homebrew-core/pull/41109

**Comment by luzpaz** [comment]
@fxcoudert sorry, not sure what I'm missing do i need to alter cmake flags ?

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by luzpaz** [comment]
```
HTTP ERROR 404
Problem accessing /job/Homebrew%20Core%20Pull%20Requests/45851/. Reason:

    Not Found
```

**Comment by luzpaz** [comment]
help requested

**Comment by SMillerDev** [comment]
If you rebase this (which is needed anyway) it'll build again

**Comment by luzpaz** [comment]
rebased...test failing in CI

**Comment by luzpaz** [comment]
Seems like the issues encountered are fixed in the latest release. https://github.com/Unidata/netcdf-c/releases/v4.7.1

Will update the formula accordingly

**Pull request closed without merging**
