### PR TITLE
swi-prolog 7.7.20 cmake based build

### PR DESCRIPTION
**Pull request by JanWielemaker**
This commit serves two purposes: use the new cmake build system (the autoconf
build system will be discontinued shortly) and refresh the default package
and dependency selection to better reflect the other distributions of the system.

Currently the --HEAD uses the cmake based build while the default formulae
still builds 7.6.4.  7.8.0 will be the next stable release that will only
support cmake.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Current analytics on the options:

```
==> install_on_request (30 days)
Index | Name (with options)                                   | Count |  Percent
-----:|-------------------------------------------------------|------:|--------:
01    | swi-prolog                                            | 1,039 |   88.35%
02    | swi-prolog --HEAD                                     |    89 |    7.57%
03    | swi-prolog --with-libarchive                          |    13 |    1.11%
04    | swi-prolog --with-jpl --with-xpce --with-libarchive   |     8 |    0.68%
05    | swi-prolog --with-jpl                                 |     7 |    0.60%
06    | swi-prolog --HEAD --with-xpce                         |     4 |    0.34%
07    | swi-prolog --devel --with-libarchive                  |     3 |    0.26%
08    | swi-prolog --devel --with-xpce --with-libarchive      |     3 |    0.26%
09    | swi-prolog --with-jpl --with-xpce                     |     3 |    0.26%
10    | swi-prolog --with-xpce                                |     3 |    0.26%
11    | swi-prolog --HEAD --with-xpce --with-libarchive       |     2 |    0.17%
12    | swi-prolog --with-xpce --with-libarchive              |     2 |    0.17%
Total |                                                       | 1,176 |  100.00%
```

Thus:

- 👎 on making `:x11` requirement a default
- Making `libarchive` default: why not, but can't it build against the system libarchive instead?
- We try to cut down the number of options, so the `:recommended` should be made mandatory.

**Comment by JanWielemaker** [comment]
Thanks for looking into this.    The deps:

  - `:x11` provides the development tools.   You typically should want those, except for deployment in an environment where it is not needed.  I recon MacOS is for Prolog primarily a development platform.  It is also default for the Macports version (AFAIK) and the Macports is the MacOS port that is around much longer and advertised as first way to get SWI-Prolog on the Mac.   I do understand that demanding `x11` increases the footprint considerably which could be a fair reason to not make it the default.
  - `libarchive` is used by the package manager and a rather modest dependency.  It doesn't compile with the MacOS version.  I do not recall why.
  - If `:recommended` is not recommended, fine by me
  - There are surely people using the database adapters.   The only way to get them otherwise is compile from source or use one of the other Mac versions (Macports or the Mac bundle we provide).

As is, Homebrew is a small distribution channel for SWI-prolog which has about a thousand installations per day on all platforms combined.  I do not know whether the rather minimal version provided by Homebrew plays a role in this.

Feel free to change the `:optional`, `:recommended`, etc. as you seem fit with this feedback.  May main goal was to make sure the formulae keeps working while SWI-Prolog replaces autotools with cmake.

**Comment by SMillerDev** [comment]
@JanWielemaker could you make the changes to remove the options and make them default? As for X11, support for it on macOS is just a mess so we'd prefer not to have dependencies on that in homebrew-core.

**Comment by fxcoudert** [comment]
No activity, closing for now

**Pull request closed without merging**
