### PR TITLE
caddy 0.10.10

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

---

### CODE REVIEW

**Comment by vszakats** [comment]
Thank you @zmwangx!

**Comment by perroud** [comment]
@zmwangx any chance to get Caddy with and without plugins or Caddy with all plugins, available at https://caddyserver.com/download ?

Thank you very much.

**Comment by zmwangx** [comment]
@perroud Sorry for the slow reply here.

> Caddy with all plugins

I totally understand the value of this, but it's not easy. The plugins are scattered all over GitHub without a vetted and preferably vendored subset, and I don't know a central registry other than the download and docs page. I'm not sure if plugins can conflict with each other.

Basically, if you want this, you or someone else needs to come forth and pledge long term support for this --full option, and even then we might need input from caddy's upstream for which plugins to include, as opposed to including everything, which AFAICT has close-to-none bar of entry and is hence very bad for security.

**Comment by mholt** [comment]
Yeah... only choose plugins you trust. You add all as a whole at your own peril.

**Pull request closed without merging**
