### PR TITLE
mlt 7.0.1

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Details on new `cmake` build posted in previous attempt (7.0.0): https://github.com/Homebrew/homebrew-core/pull/76612#issuecomment-832151319

**Wasn't sure if `--disable-sdl` is same as `-DMOD_SDL1=OFF`**

### CODE REVIEW

**Comment by cho-m** [comment]
Let's give ARM a try based on comment that it is "fixed on the v7 branch": https://github.com/mltframework/mlt/issues/677

**Comment by carlocab** [comment]
Needs an `RPATH` fix. I think
```ruby
ENV.append "LDFLAGS", "-Wl,-rpath,#{rpath}"
```
should do it, but I want to have a look at the layout of the bottle first. Especially since the version we have now (6.26.1) doesn't seem to be making use of `RPATH`s.

**Comment by carlocab** [comment]
Had a look at the bottle. Looks like this needs
```
-DCMAKE_INSTALL_RPATH=#{opt_lib}
```
probably with a comment that we can't use `#rpath` here.

I also wonder if `mlt` can be switched to the newer `opencv` instead of `opencv@3`.

**Comment by cho-m** [comment]
I do see commits to support newer `opencv` so will try run with that: https://github.com/mltframework/mlt/commit/750917db30cecc543119c2164204b7dfe7a9fcd0

**Comment by cho-m** [comment]
For `opencv` dependency, build worked for me locally.

For `synfig` build failure, it still fails on configure step after `RPATH` changes:
```make
checking LIBPANGO_LIBS... -L/usr/local/Cellar/glib/2.68.2/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/cairo/1.16.0_5/lib -L/usr/local/Cellar/harfbuzz/2.8.1/lib -L/usr/local/Cellar/pango/1.48.5/lib -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lharfbuzz -lcairo
checking for mlt++... configure: error:  ** You need to install mlt++.
```

**Comment by carlocab** [comment]
Yes, the `RPATH` change is just for fixing the `mlt` test failure on ARM.

Not sure why `synfig` is failing. Did `mlt` stop shipping `pc` files?

**Comment by carlocab** [comment]
Ah, no. They still ship `pc` files, but versioned ones:
```
❯ ls ~/Downloads/bottles/mlt/7.0.1/lib/pkgconfig
mlt++-7.pc  mlt-framework-7.pc
```
The existing version of `mlt` ships unversioned `pc` files:
```
❯ ls mlt/6.26.1/lib/pkgconfig
mlt++.pc  mlt-framework.pc
```
We could maybe install unversioned symlinks in `lib/pkgconfig`.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
