### PR TITLE
perl 5.30.2

### PR DESCRIPTION
**Pull request by mhassan1**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Everything looks good except `brew audit`:
`* C: 40: col 5: Formulae in homebrew/core (except e.g. cryptography, libraries) should not run build-time checks`

Is the correct course of action to open a PR with `rubocop/lines`?

Edit: removed `make test` from formula, instead

### CODE REVIEW

**Comment by SMillerDev** [comment]
subversion, vim and weechat need a revision bump: https://docs.brew.sh/Manpage#bump-revision-options-formula

**Comment by SMillerDev** [comment]
Thanks @mhassan1 ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by mhassan1** [comment]
I see checks are failing, but I'm not sure why. I see an error in `brew test --verbose viewvc`: `Timeout::Error: execution expired`. Any ideas?

**Comment by mhassan1** [comment]
> I see checks are failing, but I'm not sure why. I see an error in `brew test --verbose viewvc`: `Timeout::Error: execution expired`. Any ideas?

I see that same error here: https://github.com/Homebrew/homebrew-core/pull/52260

**Comment by mhassan1** [comment]
@SMillerDev Are the above CI failures blocking the merge? I see those are caused by unrelated `viewvc`. Do I need to do anything else?

**Comment by SMillerDev** [comment]
@dawidd6 Why did you remove the label?

**Comment by dawidd6** [comment]
Cause checks were red. Now it is ready to merge.

**Comment by Bo98** [comment]
Thank you @mhassan1.

**Pull request closed without merging**
