### PR TITLE
Kick Assembler 4.19 (new formula)

### PR DESCRIPTION
**Pull request by ahacop**
Homepage: http://www.theweb.dk/KickAssembler/

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
> Kick Assembler is the combination of an assembler for doing 6510 machine code and a high level script language.

I'm wondering how widely used that is, or whether it's a bit of a niche for Homebrew…

**Comment by ahacop** [comment]
Not sure how widely used it is, but a similar assembler for 8-bit computers, [dasm](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dasm.rb), is part of core.

**Comment by fxcoudert** [comment]
Hi @ahacop, thanks for the pull request. We're going to decline, it seems a very niche tool with low usage. `dasm` is part of core, but it has very low usage (12 installs per month) and covers several 8-bit processors.

We recommend that you maintain the formula in a personal tap, which is seamless for users due to Homebrew's modular nature: https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md

**Comment by ahacop** [comment]
:+1:

**Pull request closed without merging**
