### PR TITLE
Make ansible bottle relocatable

### PR DESCRIPTION
**Pull request by lucafavatella**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
  - I have installed but only with bottle:
    - `brew install --build-bottle ansible`
    - `brew bottle --verbose ansible`
    - `brew test ansible`
    - `brew audit ansible`
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
  - I ran only `brew audit ansible`

---

This shall make the bottle relocatable.

### CODE REVIEW

**Comment by DomT4** [comment]
Interesting. What are the downsides to turning optimisation off here?

Thoughts @MikeMcQuaid & @tdsmith?

**Comment by lucafavatella** [comment]
I see that in pyrax optimize was introduced in [this commit](https://github.com/rackspace/pyrax/commit/114f6d963d89e526dbd0661f893d5e1cc777ff45) and I did not manage to identify any specific reason why it was introduced hence I think it fits in the "other improvements" of that commit message.

I did not test pyrax-related features in this ansible formula.

**Comment by lucafavatella** [comment]
BTW Debian deletes *.pyc and *.pyo and generates those in the post-install - [ref1](https://www.debian.org/doc/packaging-manuals/python-policy/ch-module_packages.html#s-byte_compilation) [ref2](https://alioth.debian.org/scm/loggerhead/pkg-python/python-defaults-debian/view/head:/dh_python2?start_revid=420#L387). So it appears that a piece of logic for *.pyc and *.pyo could go in one of the scripts in the brew repo.

For this ansible formula I noticed the only files hindering relocatability were *.pyo in pyrax hence I propose this minimal change.

**Comment by tdsmith** [comment]
The .pyo optimizations aren't very important; this looks like a good solution.

**Comment by MikeMcQuaid** [comment]
> BTW Debian deletes *.pyc and *.pyo and generates those in the post-install - ref1 ref2. So it appears that a piece of logic for *.pyc and *.pyo could go in one of the scripts in the brew repo.

I think I'd rather see a generic solution for all Python bottles here; delete all `.pyo` when bottling like we do with `.pyc`: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/keg.rb#L398-L400 https://github.com/Homebrew/brew/blob/96cbce015e0b327bd7d30fc101cbd25452cd2fd8/Library/Homebrew/keg.rb#L488-L490

**Comment by tdsmith** [comment]
Perfect; I wanted to check whether we did that but I was on my phone. :) :+1: to letting the bottle cleaner take care of it.

**Comment by lucafavatella** [comment]
> I think I'd rather see a generic solution for all Python bottles here; delete all .pyo when bottling like we do with .pyc: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/keg.rb#L398-L400 https://github.com/Homebrew/brew/blob/96cbce015e0b327bd7d30fc101cbd25452cd2fd8/Library/Homebrew/keg.rb#L488-L490

Initial draft at https://github.com/lucafavatella/brew/commit/c7b84b1f43785e20607d9c6e30266d4f84305024 , I am giving it a try

**Comment by lucafavatella** [comment]
> Initial draft at lucafavatella/brew@c7b84b1 , I am giving it a try

Looks working - closing this and opening PR in brew.

**Pull request closed without merging**
