### PR TITLE
scala@2.11: migrate to openjdk@8

### PR DESCRIPTION
**Pull request by hyuraku**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
openjdk@8 migration (#63290)

### CODE REVIEW

**Comment by SMillerDev** [comment]
> Last 2.11.x maintenance release:
    Scala 2.11.12 - Released on November 9, 2017

I think this formula should be disabled, or at least deprecated instead.

**Comment by hyuraku** [comment]
> formula should be disabled, at least deprecated instead.

I understood because the scala team said ` the 2.11.x series is no longer actively maintained.` in https://github.com/scala/scala/releases/tag/v2.11.12

Should I get the `scala@2.11` removed?

**Comment by SMillerDev** [comment]
Not removed just yet, but please do add a `deprecated` stanza.

**Comment by jonchang** [comment]
Thanks @hyuraku!

**Pull request merged**
