### PR TITLE
php 8.2.13

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
```console
  /tmp/php-20231123-12877-g28xz/php-8.2.13/ext/dom/document.c:1437:29: error: ‘xmlSaveNoEmptyTags’ undeclared (first use in this function)
```

**Comment by derrabus** [comment]
The build passes on my Mac. I don't have Linux machine where I could reproduce the issue. 😕

**Comment by cho-m** [comment]
If you want, you can try to reproduce it by modifying formula to use brew's `libxml2`.

The failure is due to changes in `libxml2` 2.12.x where they removed an `#include <libxml/globals.h>` from `libxml2/parser.h` (https://gitlab.gnome.org/GNOME/libxml2/-/commit/11a1839ddd67457a68ce938157b3525159a198c8#c3ed02e4e4c07d9d56312d86765e2399a632b3c2_826_821).

PHP 8.3.x did add an extra header as part of https://github.com/php/php-src/commit/4bee5743e965b8c1aaa58d1a428eccdddb776304#diff-43e33fdca0e567799ffad75db31cd46285f355cba931ad6def08a7678c564969R26 which would fix issue.

**Comment by derrabus** [comment]
Okay, so that means the new PHP releases did not cause this issue and we wouldn't be able to build new bottles on Linux with the current formulae either? In that case, we could merge the version bumps at (this PR and #155313) because they don't break anything that isn't already broken.

**Comment by derrabus** [comment]
Seems like they've fixed this already: https://github.com/php/php-src/commit/6a76e5d0a2dcf46b4ab74cc3ffcbfeb860c4fdb3

**Comment by derrabus** [comment]
I've included the fix from upstream. Thanks for the hint @cho-m!

**Comment by derrabus** [comment]
This PR is ready, but I'd prefer to merge #155397 instead.

**Review by SMillerDev — APPROVED** [review]
Thanks @derrabus  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by chenrui333** [comment]
Thanks @derrabus !  Close this in favor of #155397

**Pull request closed without merging**
