### PR TITLE
boost-python3 1.70.0

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by scpeters** [comment]
@fxcoudert can this be merged independently of #38890 ?

**Comment by zbeekman** [comment]
gah! My bad.

Also, @chenrui333 *please check of existing open PRs!*

Let me know if I should revert.

**Comment by chenrui333** [comment]
Do you want me to run against that PR, `#38890` locally?

**Comment by zbeekman** [comment]
No thank you. I just need to figure out what the right course of action is here. My proposed solution is #40303 and then adding a revision bump in the other one.

**Pull request closed without merging**
