### PR TITLE
wget 1.19.2

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chdiza** [comment]
@ilovezfs Even better, you can drop this block:
```
    # Fixes undefined symbols _iconv, _iconv_close, _iconv_open
    # Reported 10 Jun 2016: https://savannah.gnu.org/bugs/index.php?48193
    ENV.append "LDFLAGS", "-liconv"
```
They pulled that fix in.

**Comment by zmwangx** [comment]
Yeah, thanks @chdiza.

**Comment by chdiza** [comment]
Whoops, sorry for pinging the wrong person!

**Comment by JCount** [comment]
Thanks @zmwangx!

**Pull request closed without merging**
