### PR TITLE
erlang 25.0 erlang@24 24.3.4 rabbitmq 3.10.2

### PR DESCRIPTION
**Pull request by fishtreesugar**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
It seems rebuild of `rabbitmq` didn't help, the test still fails

```
==> Testing rabbitmq
  ==> /opt/homebrew/Cellar/rabbitmq/3.10.1_1/sbin/rabbitmq-diagnostics wait --pid 1157
  =ERROR REPORT==== 18-May-2022::07:34:03.747357 ===
  beam/beam_load.c(551): Error loading function elixir:start/2: op put_tuple u x:
  Error: test failed
    please re-compile this module with an Erlang/OTP 25 compiler
  
  
  =ERROR REPORT==== 18-May-2022::07:34:03.747367 ===
  Loading of /opt/homebrew/Cellar/rabbitmq/3.10.1_1/escript/rabbitmq-diagnostics/elixir.beam failed: badfile
  
  =CRASH REPORT==== 18-May-2022::07:34:03.747437 ===
    crasher:
      initial call: application_master:init/4
      pid: <0.80.0>
      registered_name: []
      exception exit: {bad_return,
                          {{elixir,start,[normal,[]]},
                           {'EXIT',
                               {undef,
                                   [{elixir,start,[normal,[]],[]},
                                    {application_master,start_it_old,4,
                                        [{file,"application_master.erl"},
                                         {line,293}]}]}}}}
        in function  application_master:init/4 (application_master.erl, line 142)
      ancestors: [<0.79.0>]
      message_queue_len: 1
      messages: [{'EXIT',<0.81.0>,normal}]
      links: [<0.79.0>,<0.44.0>]
      dictionary: []
      trap_exit: true
      status: running
      heap_size: 987
      stack_size: 28
      reductions: 157
    neighbours:
  
  =INFO REPORT==== 18-May-2022::07:34:03.7[65](https://github.com/Homebrew/homebrew-core/runs/6491154073?check_suite_focus=true#step:6:66)318 ===
      application: elixir
      exited: {bad_return,
                  {{elixir,start,[normal,[]]},
                   {'EXIT',
                       {undef,
                           [{elixir,start,[normal,[]],[]},
                            {application_master,start_it_old,4,
                                [{file,"application_master.erl"},
                                 {line,293}]}]}}}}
      type: temporary
  
  ERROR! Failed to start Elixir.
  error: {error,
             {elixir,
                 {bad_return,
                     {{elixir,start,[normal,[]]},
                      {'EXIT',
                          {undef,
                              [{elixir,start,[normal,[]],[]},
                               {application_master,start_it_old,4,
                                   [{file,"application_master.erl"},
                                    {line,293}]}]}}}}}}
  Killing child processes...
  2022-05-18 07:34:04.013883-07:00 [noti] <0.59.0> SIGTERM received - shutting down
  2022-05-18 07:34:04.013883-07:00 [noti] <0.59.0> 
  Error: rabbitmq: failed
  An exception occurred within a child process:
    BuildError: Failed executing: /opt/homebrew/Cellar/rabbitmq/3.10.1_1/sbin/rabbitmq-diagnostics wait --pid 1157
```

**Comment by idyll** [comment]
The error above looks like the issue is we need a new version of Elixir compiled against OTP25. 

See José's comment here:

https://github.com/elixir-lang/elixir/issues/11220

**Comment by fishtreesugar** [comment]
Thx, IIUC, rabbitmq bundle a precompiled elixir in it’s cli tools

**Comment by bayandin** [comment]
`rabbitmq` 3.10.2 should have fixed CLI tools. I also added a versioned formula for `erlang@24`.

**Review by bayandin — APPROVED** [review]
Thanks @fishtreesugar 🎉

**Pull request closed without merging**
