### PR TITLE
gstreamer 1.18.0

### PR DESCRIPTION
**Pull request by tschoonj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by tschoonj** [comment]
WIP: my plan is to push all GStreamer packages in this PR.

**Comment by SMillerDev** [comment]
Can you make this PR "only updates" and do things like renaming in a separate one? It's becoming hard to keep track now.

**Comment by tschoonj** [comment]
I can and I will

**Comment by SMillerDev** [comment]
Are the patches anywhere upstream where we can pull from instead?

**Comment by tschoonj** [comment]
I guess so, but it is worth doing the rebuild for? Takes a long time...

**Comment by SMillerDev** [comment]
It is, cause that will make it a lot easier to trace it and determine if it's still needed.

**Comment by tschoonj** [comment]
Done!

**Review by SMillerDev — APPROVED** [review]
Thanks @tschoonj  ! Without your contributions it'd be impossible to keep homebrew going. You can feel good knowing that you've made the world a lot better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
