### PR TITLE
 sdl2_mixer: remove non-functional smpeg2 option

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [no] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
sdl2_mixer: add option to build with mpg123, remove smpeg2
 - Currently the smpeg2 option in the formula is non-functional,
and its upstream has had very little activity recently. mpg123,
however, has what appearers to be a fairly active upstream and
seems to be the SDL_mixer project's current preferred external
mpeg implementation.

-----
ponscripter-sekai: delete
 - This formula no longer builds, is not under development that seems
to indicate that this will change, and currently is used very little.
as such, simply delete the formula as it no longer builds correctly.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Looks like `ponscripter-sekai` really needs `smpeg2`

**Comment by ilovezfs** [comment]
maybe it gets linked statically and that's why it appears to do nothing

**Comment by ilovezfs** [comment]
Looks like the default changed from yes to no for enable-music-mp3-smpeg, with the latest version of sdl2_mixer. So ponscripter-sekai is currently broken regardless of this PR.

And even better: --enable-music-mp3-smpeg results in build failure for sdl2_mixer.

**Comment by JCount** [comment]
Oh the news just keeps getting better...

**Comment by fxcoudert** [comment]
`ponscripter-sekai` has 5 installs a month, its last release was in April 2014, it has had not commits since September 2015, and fails our current GitHub notoriety standards.

I'd say: we remove the `smpeg2` option from `sdl2_mixer`, and we probably remove `ponscripter-sekai` altogether.

**Review by fxcoudert — APPROVED** [review]

**Comment by ilovezfs** [comment]
I don't think sdl2_mixer needs the revision bump.

**Comment by JCount** [comment]
@ilovezfs Good point, I meant to remove that when I changed the PR. 👍

**Pull request merged**
