### PR TITLE
hpp-fcl 1.7.5 (new formula)

### PR DESCRIPTION
**Pull request by jcarpent**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by jcarpent** [comment]
Similarly to eigenpy (#83480), hpp-fcl is not `notable enough` but it will be used as a strong dependency for notable projects.
@carlocab Would it be possible to not consider as a strict limitation the limited notability of this package?

**Comment by carlocab** [comment]
This one falls too far short of our notability requirement, I think.

If this is a required dependency of other formulae you would like to add, you can declare this as a `resource` in those formulae instead.

Also, please don't mark steps in the PR template as done when you didn't do them, or if the requirement hasn't actually been met.

**Comment by jcarpent** [comment]
> If this is a required dependency of other formulae you would like to add, you can declare this as a `resource` in those formulae instead.

Thanks for your quick feedback @carlocab. Could you provide some guidance for declaring this package as a `resource`. I was not able to find the proper documentation for this feature in the cookbook.

**Comment by carlocab** [comment]
Just grep `resource .* do` in this repo; there are a few hundred examples. You can also look for the term "resource" in the [Formula Cookbook](https://docs.brew.sh/Formula-Cookbook), for example: https://docs.brew.sh/Formula-Cookbook#specifying-gems-python-modules-go-projects-etc-as-dependencies

**Pull request closed without merging**
