### PR TITLE
pbzx 1.0.2 (new formula)

### PR DESCRIPTION
**Pull request by vladimyr**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Prior request: https://github.com/Homebrew/homebrew-core/issues/28818
Resolves upstream issue: https://github.com/NiklasRosenstein/pbzx/issues/4

### CODE REVIEW

**Comment by aaronliu0130** [comment]
@vladimyr I'm afraid that this formula doesn't meet the notability guidelines. Your repository needs to have at least 30 watchers and forks, with 75 stars if I remember correctly. You need to make that repository notable enough.
[Workaround:
If we wait long enough, the Earth will eventually be consumed by the Sun.](https://www.xkcd.com/1822/)

**Comment by vladimyr** [comment]
@aaronliu0130 Notability is checked by audit command and build bot https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L583-L587 Later would close my PR immediately if it doesn't meet criteria.
That being said, yes it is low in popularity and you may have a valid point but your smug tone does not help!

**Comment by SMillerDev** [comment]
Hi, this seems like a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by SMillerDev** [comment]
@aaronliu0130 it's not helpful to suggest people wait until they're dead. Please adjust your communication to the Code of Conduct. https://github.com/Homebrew/.github/blob/master/CODE_OF_CONDUCT.md#code-of-conduct

**Comment by vladimyr** [comment]
@SMillerDev Acknowledged, moving to personal tap. I'm curious is this your personal assessment or based on numbers? The reason I'm asking is to figure out if an update to the audit command is needed? If so, I can do quick PR. 💡

**Comment by SMillerDev** [comment]
The audit failure is an indicator here for me, but it's not a hard rule (maintainers can override it as they see fit). However, that in combination with the software type (unlikely to grow fast in popularity) makes me think I'm going to honor the audit. It's not that difficult to maintain a tap anyway (I think all core maintainers maintain a tap on the side for niche stuff)

I think the current levels for the audit are fair, if I'd make a change to them I'd put them higher if anything.

**Comment by vladimyr** [comment]
> However, that in combination with the software type (unlikely to grow fast in popularity) makes me think I'm going to honor the audit.

Sure, I'm not trying to question your judgment 👍 

> if I'd make a change to them I'd put them higher if anything.

And that is exactly what I'm _asking_ for 😃

**Comment by vladimyr** [comment]
>The audit failure is an indicator here for me, but it's not a hard rule (maintainers can override it as they see fit).

What do you mean by this? You were talking about hypothetical audit failure on notability basis or failed checks on current PR? If later please help me understand why did it fail in the first place.

**Comment by SMillerDev** [comment]
The failed check on this pull request was an audit failure, it's in the build logs.

**Pull request closed without merging**
