### PR TITLE
ponyc 0.3.1

### PR DESCRIPTION
**Pull request by SeanTAllen**

### CODE REVIEW

**Comment by SeanTAllen** [comment]
I'm unclear why this failed. It appears to be related to mavericks? I followed the checklist on my machine and everything passed. Did I do something wrong?

**Comment by DomT4** [comment]
Not your fault, as such.

I'm _fairly_ sure `stdatomic.h` wasn't available prior to 10.10, so trying to include it on 10.9 would be expected to fall apart & kill the build. Given that Mavericks failed where Yosemite/El Cap did not I'd guess it's picking up the system `stdatomic.h` rather than the one from our `llvm` formula.

Try something like:
```ruby
def install
  ENV.prepend "CFLAGS", "-I#{Formula["llvm"].opt_lib}/clang/#{Formula["llvm"].version}/include"
```

**Comment by SeanTAllen** [comment]
@DomT4 thanks. trying that now

**Comment by SeanTAllen** [comment]
hmm, closing this and reopening to try and get the CI to run again.

**Comment by SeanTAllen** [comment]
@DomT4 i did another PR to get CI to run and that just failed for everything: https://github.com/Homebrew/homebrew-core/pull/4824

**Pull request closed without merging**
