### PR TITLE
Remove cputhrottle Formula

### PR DESCRIPTION
**Pull request by apeschel**
cputhrottle appears to have been broken long ago by OS security changes.
Unless someone can confirm actually being able to get this program to
work correctly, it should probably be cleaned from this repo.

Reference: <https://stackoverflow.com/a/54243427/84955>

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [N/A] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [N/A] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [N/A] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by apeschel** [comment]
Fixes: https://github.com/Homebrew/homebrew-core/issues/31494

**Comment by claui** [comment]
@apeschel Thanks for the PR! I can confirm that `cputhrottle` doesn’t work with SIP enabled.

@fxcoudert Can you still [not reproduce the issue](https://github.com/Homebrew/homebrew-core/issues/31494#issuecomment-420665043) even with SIP enabled?

**Comment by fxcoudert** [comment]
@claui I can reproduce. Question is: what is the last macOS version that the software supports?

**Comment by claui** [comment]
@fxcoudert SIP is preventing `cputhrottle` to attach to a process, so Yosemite should be the last macOS version to support that.

**Review by claui — APPROVED** [review]

**Comment by claui** [comment]
Thanks again @apeschel for your contribution! 🍻

**Pull request merged**
