### PR TITLE
docfx 2.70.0

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>

## Docfx as .NET Foundation Project

Starting from `v2.70.0`, docfx has been fully transitioned to be a .NET Foundation project entirely driven by the community for the interest of the community.

Given the ownership change, we are renaming the NuGet package names, assembly names and namespace names from `Microsoft.DocAsCode.*` to `Docfx.*`.

### 💥 Breaking Changes
* Microsoft.DocAsCode.* -> Docfx.* by @yufeih in https://github.com/dotnet/docfx/pull/8943
* Drop Docfx.MarkdigEngine.Validators by @yufeih in https://github.com/dotnet/docfx/pull/8971
* Drop support for md.style by @yufeih in https://github.com/dotnet/docfx/pull/8973
### 🎉 New Features
* Sign and publish as .NET foundation by @yufeih in https://github.com/dotnet/docfx/pull/8931
* Expand active page when it has subpages on modern template by @MihkelAuv in https://github.com/dotnet/docfx/pull/8896
* Enable invariant culture by @yufeih in https://github.com/dotnet/docfx/pull/8897
* Add redirection document type by @filzrev in https://github.com/dotnet/docfx/pull/8892
* Add open browser options to `docfx serve` command by @filzrev in https://github.com/dotnet/docfx/pull/8934
* Add PDF generation ability to `Docfx.App` by @dpvreony in https://github.com/dotnet/docfx/pull/8939
### 🐞 Bug Fixes
* Fix scroll into view in TOC by @MihkelAuv in https://github.com/dotnet/docfx/pull/8898
* Fix console logger message format by @filzrev in https://github.com/dotnet/docfx/pull/8916
* Fix serialization related property name problems by @filzrev in https://github.com/dotnet/docfx/pull/8941
* Remove tab group hash function by @yufeih in https://github.com/dotnet/docfx/pull/8942
* See/seealso tag copies href when a child node exist by @yufeih in https://github.com/dotnet/docfx/pull/8974
* Display unresolved cref by @yufeih in https://github.com/dotnet/docfx/pull/8975
* Fix for modifying an enumerated collection while traversing it. by @mihtjel in https://github.com/dotnet/docfx/pull/8972
* Backport triple colon extension updates by @yufeih in https://github.com/dotnet/docfx/pull/9000
### 🔧 Engineering
* Fix warning NU1701 by @filzrev in https://github.com/dotnet/docfx/pull/8904
* Apply build-in code formatters by @filzrev in https://github.com/dotnet/docfx/pull/8912
* Add default launchSettings.json by @filzrev in https://github.com/dotnet/docfx/pull/8935
* Remove obsolete warning suppression. and fix deprecated APIs by @filzrev in https://github.com/dotnet/docfx/pull/8937
* Add FluentAssertions nuget package to test projects by @filzrev in https://github.com/dotnet/docfx/pull/8946
* Update SpellingExclusions.dic by @filzrev in https://github.com/dotnet/docfx/pull/8970
* Change dependabot schedule to daily by @filzrev in https://github.com/dotnet/docfx/pull/8982
* Update NuGet package version of ICSharpCode.Decompiler by @filzrev in https://github.com/dotnet/docfx/pull/8983
* Add Visual Studio Spell Check config settings. And fix reported spellings problems by @filzrev in https://github.com/dotnet/docfx/pull/8940
### 📄 Documentation
* Typo fix by @novialriptide in https://github.com/dotnet/docfx/pull/8908
* Copyedits of CLI and docfx.json pages by @rgarrity in https://github.com/dotnet/docfx/pull/8989
* Add doc comments to docfx.json related config files. by @filzrev in https://github.com/dotnet/docfx/pull/8969

## New Contributors
* @MihkelAuv made their first contribution in https://github.com/dotnet/docfx/pull/8896
* @novialriptide made their first contribution in https://github.com/dotnet/docfx/pull/8908
* @mihtjel made their first contribution in https://github.com/dotnet/docfx/pull/8972
* @dpvreony made their first contribution in https://github.com/dotnet/docfx/pull/8939
* @rgarrity made their first contribution in https://github.com/dotnet/docfx/pull/8989

**Full Changelog**: https://github.com/dotnet/docfx/compare/v2.67.5...v2.70.0</pre>
</details>

### CODE REVIEW

**Comment by osalbahr** [comment]
```console
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew install docfx
docfx 2.63.0 is already installed but outdated (so it will be upgraded).
==> Fetching docfx
==> Downloading https://ghcr.io/v2/homebrew/core/docfx/manifests/2.70.0
curl: (22) The requested URL returned error: 404

Error: docfx: Failed to download resource "docfx_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/docfx/manifests/2.70.0
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew install docfx -v
docfx 2.63.0 is already installed but outdated (so it will be upgraded).
==> Fetching docfx
==> Downloading https://ghcr.io/v2/homebrew/core/docfx/manifests/2.70.0
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.1.3-23-gd2863d0\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.5\)\ curl/8.1.2 --header Accept-Language:\ en --fail --retry 3 --header Accept:\ application/vnd.oci.image.index.v1\+json --header Authorization:\ Bearer\ QQ== --remote-time --output /Users/dracula/Library/Caches/Homebrew/downloads/02f6a242d205a524f05e2ba2e731490f09b96852a777b0d73ded532612d51ae8--docfx-2.70.0.bottle_manifest.json.incomplete --location https://ghcr.io/v2/homebrew/core/docfx/manifests/2.70.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    70    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Error: docfx: Failed to download resource "docfx_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/docfx/manifests/2.70.0
```

I don't understand where it's getting the manifest url from.

**Comment by chenrui333** [comment]
docfx needs dotnet 8, so it wont be buildable as of now.

**Comment by osalbahr** [comment]
> you need to do brew `instal -s xxx` (to install from source)

Oh. Yeah I overlooked that, my b.

> docfx needs dotnet 8, so it wont be buildable as of now.

Works on my end. I don't know if this is an issue only in macOS 11-arm-64.
```console
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew install -s docfx
docfx 2.63.0 is already installed but outdated (so it will be upgraded).
==> Fetching docfx
==> Downloading https://github.com/dotnet/docfx/archive/refs/tags/v2.70.0.tar.gz
Already downloaded: /Users/dracula/Library/Caches/Homebrew/downloads/a36ad492f253f3ca2049c1b0c65f7dc6595a8e576c2737e62236a0a52709e930--docfx-2.70.0.tar.gz
==> Upgrading docfx
  2.63.0 -> 2.70.0 

==> dotnet publish src/docfx --configuration Release --framework net7.0 --output
🍺  /usr/local/Cellar/docfx/2.70.0: 96 files, 34MB, built in 46 seconds
==> Running `brew cleanup docfx`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /usr/local/Cellar/docfx/2.63.0... (189 files, 44.3MB)
Removing: /Users/dracula/Library/Caches/Homebrew/docfx--2.63.0... (15.4MB)
$ brew test docfx
==> Testing docfx
==> /usr/local/Cellar/docfx/2.70.0/bin/docfx init -q
$ brew config
HOMEBREW_VERSION: 4.1.3-23-gd2863d0
ORIGIN: https://github.com/Homebrew/brew
HEAD: d2863d05b33177626e66fd4be75e92bcc3f14c99
Last commit: 6 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9cc0f9120963af86205b2547f385b2be5f48554d
Core tap last commit: 2 hours ago
Core tap branch: bump-docfx-2.70.0
Core tap JSON: 02 Aug 13:33 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.41.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
```

**Comment by chenrui333** [comment]
>   /opt/homebrew/Cellar/dotnet/7.0.100/libexec/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 7.0 or lower, or use a version of the .NET SDK that supports .NET 8.0. [/private/tmp/docfx-20230802-74229-osmsm4/docfx-2.70.0/src/docfx/docfx.csproj::TargetFramework=net8.0]

this is on the CI

**Comment by chenrui333** [comment]
actually you are right, it looks like it only happens on ci. 🤔

**Comment by osalbahr** [comment]
> actually you are right, it looks like it only happens on ci. 🤔

Yeah, it’s odd. Does it pass locally for you too?

**Comment by chenrui333** [comment]
yeah, passed in my local as well, this is my full build log, https://gist.github.com/chenrui333/f5cf7fc2246402d2f081032a50e8791d

**Comment by chenrui333** [comment]
well, that did not quite work.

**Comment by chenrui333** [comment]
@shawnfunke can you help take a look at this build? Thanks!

**Comment by shawnfunke** [comment]
The reason this fails is because this runs inside of GitHub Actions. In that case it'll add .NET 8 as a additional target framework. Here it uses `TargetFrameworks` instead of `TargetFramework` so using the arguments in the code below fixes the above issue.

```props
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <TargetFrameworks>net6.0;net7.0</TargetFrameworks>
    <TargetFrameworks Condition=" '$(ContinuousIntegrationBuild)' == 'true' ">$(TargetFrameworks);net8.0</TargetFrameworks>
```

https://github.com/dotnet/docfx/blob/fc7deda119eebd830a2d37882698dcbaedaec24b/Directory.Build.props#L3-L5

```ruby
    # specify the target framework to only target the currently used version of
    # .NET, otherwise additional frameworks will be added due to this running
    # inside of GitHub Actions, for details see:
    # https://github.com/dotnet/docfx/blob/fc7deda119eebd830a2d37882698dcbaedaec24b/Directory.Build.props#L3-L5
    args = %W[
      --configuration Release
      --framework net#{dotnet.version.major_minor}
      --output #{libexec}
      --runtime #{os}-#{arch}
      --no-self-contained
      -p:Version=#{version}
      -p:TargetFrameworks=net#{dotnet.version.major_minor}
    ]
```

**Comment by chenrui333** [comment]
ah, I see, that makes sense.

**Comment by chenrui333** [comment]
Thanks @shawnfunke!

**Comment by shawnfunke** [comment]
@chenrui333 no problem, feel free to ask at anytime. I wonder if `GITHUB_ACTIONS` should be set to `true` by default when using `brew install --build-from-source` to prevent these kind of issues. What do you think @chenrui333 @MikeMcQuaid?

**Comment by chenrui333** [comment]
> @chenrui333 no problem, feel free to ask at anytime. I wonder if `GITHUB_ACTIONS` should be set to `true` by default when using `brew install --build-from-source` to prevent these kind of issues. What do you think @chenrui333 @MikeMcQuaid?
looks like it is indeed used pretty extensively by dotnet community, https://grep.app/search?q=GITHUB_ACTIONS&filter[path.pattern][0]=Directory.Build.props (but we dont have many dotnet formulae yet though), for now, I would say just override via dotnet build option. Once we have more, we can update test-bot for this.

**Review by chenrui333 — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
> @chenrui333 no problem, feel free to ask at anytime. I wonder if `GITHUB_ACTIONS` should be set to `true` by default when using `brew install --build-from-source` to prevent these kind of issues. What do you think @chenrui333 @MikeMcQuaid?

That seems very odd. Upstream should provide a better toggle than `GITHUB_ACTIONS` for this behaviour change.

**Comment by MikeMcQuaid** [comment]
My suggestion would be the opposite: we should not pass through that variable through to builds implicitly. `ENV.delete("GITHUB_ACTIONS")` would fix for now and can add to Homebrew/brew to remove properly later.

**Comment by shawnfunke** [comment]
> My suggestion would be the opposite: we should not pass through that variable through to builds implicitly. `ENV.delete("GITHUB_ACTIONS")` would fix for now and can add to Homebrew/brew to remove properly later.

There's already another workaround being used for this build that will do the job for now.

Sure the other way around works as well. I am not sure where to start with making this change as I'm not to familiar with the code base of Brew itself. I would guess that it would be here: [`Library/Homebrew/upgrade.rb#L184`](https://github.com/Homebrew/brew/blob/a2b49440e76b9e935e2a061c60ad3085393e9269/Library/Homebrew/upgrade.rb#L184). I do not foresee this breaking many, if any formulae. Doing a quick [code search](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-core%20ENV%5B%22GITHUB_ACTIONS%22%5D&type=code) I only see one usage in a test so it should probably be removed there as well, that seems to be implemented [here](https://github.com/Homebrew/brew/blob/a2b49440e76b9e935e2a061c60ad3085393e9269/Library/Homebrew/formula.rb#L2478).

**Comment by chenrui333** [comment]
the build option with `TargetFrameworks` is pretty robust for now (we can revisit the GITHUB_ACTIONS usage later if needed :) )

**Pull request merged**
