### PR TITLE
ircii: downgrade URL to HTTP

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

---

Cert expired Sep 12, 2016.
#6408.

### CODE REVIEW

**Comment by dunn** [comment]
Have you emailed the developers about it?  I can, just checking.

**Comment by zmwangx** [comment]
@dunn I haven't. I checked the communications channels: according to http://www.eterna.com.au/ircii/ there's a seemingly unarchived user mailing list with "almost no traffic", then according to http://www.eterna.com.au/ircii/bugs.html the only way to report bugs is via `ircbug`. I looked at the script, and the destination is ircii-bugs@eterna.com.au, but you need to fill out a fairly confusing template, which is hard because cert expired on website isn't really a bug.

**Comment by djmoch** [comment]
Another option would be to use the `--insecure` flag in `curl` to perform the download until their hosting provider can get their act together. I haven't thought through all of the implications of that, nor do I know if that's even an option you can set in the formula; I just wanted to suggest that as an option.

In any case, if I can do anything to help get this resolved soon, let me know.

**Comment by zmwangx** [comment]
@djmoch Hey, are you related to the ircII project somehow, or do you know any details? (Guessing from the sentence "until their hosting provider can get their act together".)

As for `-k`, it's not supported by brew and I don't think it is any better than changing the URL to HTTP.

**Comment by djmoch** [comment]
I'm not. I just did a little poking around and initially thought the expired cert was for `*.warped.com`, but now I'm not so sure. Could be a problem with the hosting provider or the ircii project. 

My feeling on HTTPS vs HTTP is that HTTPS still provides some benefit over HTTP since HTTP could theoretically be tampered with at any point in-transit, while that would cause errors in HTTPS (assuming you establish your session with the real endpoint). But that's all moot since brew doesn't support it.

**Comment by zmwangx** [comment]
No one tampers with the SHA-256 check, unless your machine is hacked.

**Comment by djmoch** [comment]
I was just going to mention that. You're completely right. I'm just being paranoid.

**Comment by dunn** [comment]
There's also `ircii AT eterna.com.au`; I just sent an email there.

**Comment by zmwangx** [comment]
Ah yeah I missed that.

**Comment by ilovezfs** [comment]
Looks like there are https mirrors with the same checksum

https://mirrors.ocf.berkeley.edu/debian/pool/main/i/ircii/ircii_20151120.orig.tar.bz2
https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/i/ircii/ircii_20151120.orig.tar.bz2

**Comment by zmwangx** [comment]
Hmm why the merge?

**Comment by ilovezfs** [comment]
Certs expired. Checksum matches. This is good enough for me.

**Comment by zmwangx** [comment]
I thought it wasn't ;)

**Comment by ilovezfs** [comment]
It is when we have 117 open PRs.

**Comment by djmoch** [comment]
Still no bottle?

**Comment by dunn** [comment]
@djmoch I'll add one with #6896.

**Pull request merged**
