### PR TITLE
Update recipe to Liquigraph 3.0.2

### PR DESCRIPTION
**Pull request by fbiville**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fbiville** [comment]
@ilovezfs is there a way to enforce a JDK 8, instead of a JDK 9? 
Neo4j, hence Liquigraph, is not ready for JDK 9 (that's why the build fails).

**Comment by fbiville** [comment]
Shall I replace `1.8+` with `1.8` or something like that?

**Comment by ilovezfs** [comment]
yes. see https://github.com/Homebrew/homebrew-core/pull/21823#issuecomment-352264607

**Comment by ilovezfs** [comment]
You need to use a wrapper script too.

**Comment by fbiville** [comment]
I have looked at some example listed in the comment you pointed me too, but I'm not sure what wrapper script refers to.

**Comment by ilovezfs** [comment]
```
diff --git a/Formula/liquigraph.rb b/Formula/liquigraph.rb
index 2de3ad3550..1cb8f6373a 100644
--- a/Formula/liquigraph.rb
+++ b/Formula/liquigraph.rb
@@ -22,9 +22,9 @@ class Liquigraph < Formula
     system "mvn", "-B", "-q", "-am", "-pl", "liquigraph-cli", "clean", "package", "-DskipTests"
     (buildpath/"binaries").mkpath
     system "tar", "xzf", "liquigraph-cli/target/liquigraph-cli-bin.tar.gz", "-C", "binaries"
-    libexec.install "binaries/liquigraph-cli/liquigraph.sh" => "liquigraph"
+    libexec.install "binaries/liquigraph-cli/liquigraph.sh"
     libexec.install "binaries/liquigraph-cli/liquigraph-cli.jar"
-    bin.install_symlink libexec/"liquigraph"
+    (bin/"liquigraph").write_env_script libexec/"liquigraph.sh", Language::Java.java_home_env("1.8")
   end
 
   test do
```

**Comment by ilovezfs** [comment]
Thanks for the upgrade @fbiville!

**Comment by fbiville** [comment]
Awesome, thank YOU! Happy new year!

**Pull request closed without merging**
