### PR TITLE
ansible: Add dnspython to make the dig lookup work

### PR DESCRIPTION
**Pull request by denefoster**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by denefoster** [comment]
Not sure I understand why the test is failing with:

Formula has invalid versioned aliases:
ansible@2.2

I've added the correct (as far as I can tell) link for 2.3, which is what I'm changing, if someone point me in the right direction that'd be great

**Comment by JCount** [comment]
The issue likely is that your PR adds the new alias, but it does not remove the old alias at https://github.com/Homebrew/homebrew-core/blob/master/Aliases/ansible%402.2 which is still pointing to `ansible.rb`.

**Comment by denefoster** [comment]
Fair enough, just curious there's an existing 2.2 alias for the 2.3 formula. 

Removed in a new commit now, but still confused as to how that was there and passing previously !

**Comment by JCount** [comment]
Thank you for your contribution, @denefoster! 🎉

**Pull request closed without merging**
