### PR TITLE
Go 1.10

### PR DESCRIPTION
**Pull request by leonklingele**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by commitay** [comment]
Thanks @leonklingele!

**Comment by im-kulikov** [comment]
@commitay any explanations?

**Comment by cixtor** [comment]
@im-kulikov no need to explain, Go 1.10 is already in the Homebrew repository:

```
$ brew update
$ brew info go
go: stable 1.10 (bottled), HEAD
Open source programming language to build simple/reliable/efficient software
https://golang.org
/usr/local/Cellar/go/1.10 (8,150 files, 336.9MB) *
  Poured from bottle on 2018-02-16 at 21:25:00
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/go.rb
```

**Comment by im-kulikov** [comment]
Oh.. great news.. yeasterday, I cannot find it

**Pull request closed without merging**
