### PR TITLE
sleuthkit: add dependency

### PR DESCRIPTION
**Pull request by rishwanth1995**
- added postgresql as the optional dependency, since the
  new version of sleuthkit also works with postgresql.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
We're trying to limit the number of options in Homebrew, because they are seldom tested and tend to break over time, so unless you expect significant usage, I think we should decline. @ilovezfs your opinion?

**Comment by commitay** [comment]
Not directly related to this but I'm looking at making `sleuthkit` optionless and requiring everything so it can be used as a dep for an `autopsy` update.

https://github.com/sleuthkit/autopsy/blob/develop/Running_Linux_OSX.txt#L28

postgresql would still be optional but it would be the only one.

Only thing is the analytics don't really support it.

```
install events in the last 365 days
================================================================================
 1 | sleuthkit                                                | 13,587 |  97.78%
 2 | sleuthkit --with-jni --with-afflib --with-libewf         |     93 |   0.67%
 3 | sleuthkit --with-afflib --with-libewf                    |     82 |   0.59%
 4 | sleuthkit --with-libewf                                  |     77 |   0.55%
 5 | sleuthkit --with-jni --with-debug --with-afflib --with-l |     15 |   0.11%
 6 | sleuthkit --with-afflib                                  |     12 |   0.09%
 7 | sleuthkit --with-jni                                     |     10 |   0.07%
 8 | sleuthkit --with-jni --with-debug                        |     10 |   0.07%
 9 | sleuthkit --with-debug --with-afflib --with-libewf       |      4 |   0.03%
10 | sleuthkit --with-jni --with-afflib                       |      3 |   0.02%
11 | sleuthkit --with-debug                                   |      1 |   0.01%
12 | sleuthkit --with-jni --with-libewf                       |      1 |   0.01%
================================================================================
Total                                                         | 13,895 |    100%

```

**Comment by ilovezfs** [comment]
Is it sufficient to

```
depends_on "libpq"
```

to get the functionality?

**Comment by rishwanth1995** [comment]
Yes, libpq is sufficient. Many user think sleuthkit provides all the functionality out of the box and so  they only do `brew install sleuthkit` instead of with options. I think @commitay idea works well in this situation, so it will be easier for users to run autopsy on mac.

**Comment by commitay** [comment]
Opened https://github.com/Homebrew/homebrew-core/pull/28238 to discuss requiring the other deps and options.

**Pull request closed without merging**
