### PR TITLE
openjdk 20

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

As mentioned in [jdk-dev mailing list](https://mail.openjdk.org/pipermail/jdk-dev/2023-March/007517.html), build 36 ([`jdk-20+36`](https://github.com/openjdk/jdk20u/releases/tag/jdk-20%2B36)) is the GA build:

> Build 36 is therefore now the GA build, ready for production use.

[`jdk-19-ga`](https://github.com/openjdk/jdk/releases/tag/jdk-19-ga) was tagged 4 months after the [GA release date](https://openjdk.org/projects/jdk/19/), so it's probably not worth the wait. (See also: #111280.)

To-do list: https://github.com/Homebrew/homebrew-core/pull/126319#issuecomment-1481373661

Failures to follow up: https://github.com/Homebrew/homebrew-core/pull/126319#issuecomment-1500599745

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
Now that the two `gradle` PRs above are merged, we should be able to get rid of several other build failures.

**Comment by ashr123** [comment]
what about the usage of gradle 8?

**Comment by ZhongRuoyu** [comment]
> what about the usage of gradle 8?

What do you mean by that? Our Gradle 8 now runs on Java 17, but that does not affect how it builds Java projects.

**Comment by ashr123** [comment]
> > what about the usage of gradle 8?
> 
> What do you mean by that? Our Gradle 8 now runs on Java 17, but that does not affect how it builds Java projects.

I understood it the other way around, sorry 😄

**Comment by Porkepix** [comment]
Runner `13` seems to be stuck and have no output for quite a long time.

**Comment by ashr123** [comment]
@ZhongRuoyu is there any progress about merging OpenJDK 20?

**Comment by ZhongRuoyu** [comment]
> @ZhongRuoyu is there any progress about merging OpenJDK 20?

As you can see in the checklist above, all the trivial failures have been resolved, and we are only left with few non-trivial ones. I will continue investigating them in my free time, but help is welcome and appreciated.

If you are in a hurry, you may consider installing [OpenJDK's prebuilt binaries](https://jdk.java.net/20/) or the [`temurin` cask](https://formulae.brew.sh/cask/temurin).

**Comment by ZhongRuoyu** [comment]
I'm stumped on the remaining failures in [this checklist](https://github.com/Homebrew/homebrew-core/pull/126319#issuecomment-1481373661). Would appreciate some help here. Cc @Homebrew/core

**Comment by carlocab** [comment]
I suggest dropping https://github.com/Homebrew/homebrew-core/labels/CI-build-dependents-from-source to see if the failures still happen. If not, we can fix them after merging, probably by using an older OpenJDK.

**Comment by ZhongRuoyu** [comment]
This should be good to merge now. Except for `11-arm64` runner flakiness, the only dependant failure was with `trino`.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
