### PR TITLE
formulae: clang build patches

### PR DESCRIPTION
**Pull request by fxcoudert**
…

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by fxcoudert** [comment]
I don't understand the Linux failure :(

**Comment by Bo98** [comment]
`-fcommon` should fix Linux

**Comment by fxcoudert** [comment]
But why is it a regression?

**Comment by Bo98** [comment]
`-fno-common` became the default with GCC 10. Linux bottle probably was built with GCC 5 when we used Ubuntu 16.04.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
