### PR TITLE
vert.x 3.3.3

### PR DESCRIPTION
**Pull request by cescoffier**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Update the vert.x formula to 3.3.3.

### CODE REVIEW

**Comment by zmwangx** [comment]
The test could be improved, both style-wise and functionality-wise.

```ruby
  test do
    (testpath/"HelloWorld.java").write <<-EOS.undent
      import io.vertx.core.AbstractVerticle;
      public class HelloWorld extends AbstractVerticle {
        public void start() {
          System.out.println("Hello World!");
          vertx.close();
          System.exit(0);
        }
      }
    EOS
    output = shell_output("#{bin}/vertx run HelloWorld.java")
    assert_equal "Hello World!\n", output
  end
```

**Comment by cescoffier** [comment]
@zmwangx thanks for the feedback, I've incorporated your changes.

**Comment by zmwangx** [comment]
👍

**Comment by zmwangx** [comment]
Merged as 5660753. Thank you for your contribution to Homebrew!

**Pull request merged**
