### PR TITLE
Add protobuf 3.9.2 as protobuf@3.9

### PR DESCRIPTION
**Pull request by janten**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This just adds the explicit `protobuf@3.9` name, which went away with the [update to protobuf 3.10](https://github.com/Homebrew/homebrew-core/commit/6fbb6c073785ae14809240681df63b1d4995b16b).

### CODE REVIEW

**Comment by fxcoudert** [comment]
We do not aim to support every possible version of the software. We ship the latest version for each formula, and versioned formulas under very strict conditions: https://docs.brew.sh/Versions

**Comment by SMillerDev** [comment]
As far as I know upstream doesn't plan to support this version, in which case homebrew won't either.

**Comment by janten** [comment]
@fxcoudert, @SMillerDev There are existing versioned formulae for protobuf 3.1, 3.6, and 3.7. Why would version 3.9 not be supported in the same way? Since at most five versions of a formula are to be supported at any time, could we do a rolling schedule where 3.1 gets replaced by 3.9?

**Comment by jonchang** [comment]
Yes, good points.

* 3.1 should probably be replaced since it's only used by two formulae with very low install counts. Also doesn't support python 3.
* 3.6 has no core consumers and could probably be removed.
* 3.7 is only used by `protobuf-swift` and is much less popular than `swift-protobuf` which doesn't need an old version of protobuf

**Comment by jonchang** [comment]
Thanks for contributing! Unfortunately I don't think we'll be merging this into Homebrew, so I'll close this pull request.

**Pull request closed without merging**
