### PR TITLE
gauge 1.5.0

### PR DESCRIPTION
**Pull request by gaugebot**
gauge 1.5.0 

 Please cc getgauge/core for any issue.

### CODE REVIEW

**Comment by p-linnane** [comment]
This was bumped in #134673. Was the tag force pushed?

**Comment by p-linnane** [comment]
cc @haroon-sheikh

**Comment by haroon-sheikh** [comment]
Yep @p-linnane. Had to push the tag due to an error.

**Comment by haroon-sheikh** [comment]
Sorry for the trouble, is there anything I can do to help?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> Sorry for the trouble, is there anything I can do to help?

should be all good

**Pull request merged**
