### PR TITLE
pyqt 5.14.0 sip 4.19.20 qscintilla2 2.11.4

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by bayandin** [comment]
```
Error copying libpyqt5.dylib to /usr/local/Cellar/qt/5.14.0/plugins/designer/libpyqt5.dylib: Cannot create /usr/local/Cellar/qt/5.14.0/plugins/designer/libpyqt5.dylib for output
```

**Comment by fxcoudert** [comment]
After discussion in https://github.com/Homebrew/homebrew-core/pull/44964 and on the SIP/PyQt mailing list, the SIP author suggested installing sip vendored in each formula that requires it, rather than as a specific formula (because other formulas want to write in SIP paths).

**Comment by bayandin** [comment]
> After discussion in #44964 and on the SIP/PyQt mailing list, the SIP author suggested installing sip vendored in each formula that requires it, rather than as a specific formula (because other formulas want to write in SIP paths).

Tried this one (with `sip` 5.0.1 and using `sip-install`), but it failed with the same error as I posted above (can't copy `libpyqt5.dylib` to `qt` formula path).
For the current setup, I found an argument `--designer-plugindir=` which helps to fix the problem, for the new setup it requires to have a closed look at `sip-install` (and probably could be done separately if this one passes CI).

**Comment by fxcoudert** [comment]
```
==> make install
cd Qsci/ && ( test -e Makefile || /usr/local/opt/qt/bin/qmake -o Makefile /private/tmp/qscintilla2-20191227-22915-1pk0ct9/QScintilla-2.11.4/Python/Qsci/Qsci.pro ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile install
/usr/local/opt/qt/bin/qmake -install qinstall /private/tmp/qscintilla2-20191227-22915-1pk0ct9/QScintilla-2.11.4/Python/Qsci.pyi /usr/local/Cellar/qscintilla2/2.11.4/lib/python3.7/site-packages/PyQt5/Qsci.pyi
/usr/local/opt/python/bin/python3.7 /private/tmp/qscintilla2-20191227-22915-1pk0ct9/QScintilla-2.11.4/Python/mk_distinfo.py "" /usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/QScintilla-2.11.4.dist-info installed.txt
/usr/local/opt/qt/bin/qmake -install qinstall /private/tmp/qscintilla2-20191227-22915-1pk0ct9/QScintilla-2.11.4/Python/QScintilla2.api /usr/local/Cellar/qscintilla2/2.11.4/qsci/api/python/QScintilla2.api
unable to create /usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/QScintilla-2.11.4.dist-info
make: *** [install_distinfo] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by bayandin** [comment]
> ```
> ==> make install
> cd Qsci/ && ( test -e Makefile || /usr/local/opt/qt/bin/qmake -o Makefile /private/tmp/qscintilla2-20191227-22915-1pk0ct9/QScintilla-2.11.4/Python/Qsci/Qsci.pro ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile install
> /usr/local/opt/qt/bin/qmake -install qinstall /private/tmp/qscintilla2-20191227-22915-1pk0ct9/QScintilla-2.11.4/Python/Qsci.pyi /usr/local/Cellar/qscintilla2/2.11.4/lib/python3.7/site-packages/PyQt5/Qsci.pyi
> /usr/local/opt/python/bin/python3.7 /private/tmp/qscintilla2-20191227-22915-1pk0ct9/QScintilla-2.11.4/Python/mk_distinfo.py "" /usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/QScintilla-2.11.4.dist-info installed.txt
> /usr/local/opt/qt/bin/qmake -install qinstall /private/tmp/qscintilla2-20191227-22915-1pk0ct9/QScintilla-2.11.4/Python/QScintilla2.api /usr/local/Cellar/qscintilla2/2.11.4/qsci/api/python/QScintilla2.api
> unable to create /usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/QScintilla-2.11.4.dist-info
> make: *** [install_distinfo] Error 1
> make: *** Waiting for unfinished jobs....
> ```

Fixed by disabled creating of dist-info for QScintilla

**Comment by fxcoudert** [comment]
Catalina node lost connection. Testing was otherwise all good.
@BrewTestBot test this please, again

**Comment by fxcoudert** [comment]
Thanks @bayandin you rock! 🎸

**Pull request closed without merging**
