### PR TITLE
libsmf: fix build on Apple Silicon and deprecate

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can we submit this patch upstream?

**Comment by cho-m** [comment]
> Can we submit this patch upstream?

Not sure if upstream is still alive:
- https://sourceforge.net/projects/libsmf/ mentions development moved to https://github.com/nilsgey/libsmf
- https://github.com/nilsgey/libsmf is dead
- Google search shows a fork at https://github.com/stump/libsmf 
- MacPorts maintainer created issue in that repo: https://github.com/stump/libsmf/issues/10

**Comment by SMillerDev** [comment]
Can you also add deprecation then? Or does it still have dependencies?

**Comment by cho-m** [comment]
> Can you also add deprecation then? Or does it still have dependencies?

No usage in other formulae. Added deprecation and URLs to GitHub repos.

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
