### PR TITLE
gitlab-gem 4.15.0

### PR DESCRIPTION
**Pull request by Bo98**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
I suppose this could use `uses_from_macos "ruby", :since => :catalina` when that's a thing

**Comment by issyl0** [comment]
I had this exact problem with a Ruby gem in a tap and settled on `depends_on "ruby"` on all OS versions. It's unideal, but "when it's a thing" is a not very well defined timeframe.

**Comment by Bo98** [comment]
> not very well defined timeframe

Potentially the new release of brew: Homebrew/brew#7458 but yeah, that's probably a couple weeks away so I probably shouldn't wait for that.

**Comment by Bo98** [comment]
Oops forgot about this.

**Comment by issyl0** [comment]
I was just about to rebase and see if it works with the new brew release, but it looks like you're on it so I'll leave it for you!

**Comment by Bo98** [comment]
I did force push about 5 minutes ago but GitHub is not playing ball just now.

**Comment by Bo98** [comment]
Alright GitHub is definitely broken. Picking up commits which shouldn't be here.

**Comment by Bo98** [comment]
`git rebase --onto 24d9e4007a4d7a107504f2fa6f4cacca54aa9a00 gitlab-gem-4.14.1^ gitlab-gem-4.14.1`

🙈

**Pull request closed without merging**
