### PR TITLE
syncthing-inotify 0.8.4

### PR DESCRIPTION
**Pull request by Clete2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)? (AGAIN I have an issue with RuboCop. Don't know what my issue is but I think it should work

---

### CODE REVIEW

**Comment by Clete2** [comment]
Same issue as #5511 which worked just fine. Something wrong with the build and Go. Should be good to merge regardless.

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
It's not good to merge, since the build is failing and we can't produce bottles:
```
==> godep restore
godep: Dep (github.com/cenkalti/backoff) restored, but was unable to load it with error:
	Package (math/rand) not found
godep: Dep (github.com/syncthing/syncthing/lib/ignore) restored, but was unable to load it with error:
	Package (bufio) not found
godep: Dep (github.com/zillode/notify) restored, but was unable to load it with error:
	Package (runtime/cgo) not found
godep: Error checking some deps.

**Comment by Clete2** [comment]
Can you help me understand how to setup a local environment that compiles as if I was on Yosemite or El Capitan? I cannot reproduce the error as I am on Sierra. I am willing to work to fix it but I don't know how to set Homebrew to act like a different OS version.

**Comment by ilovezfs** [comment]
I believe You just need to set GOROOT like this https://github.com/Homebrew/homebrew-core/blob/8bba35f0d9478e282b78f90c3ea0e7ed8e1d600c/Formula/gauge.rb#L26

**Comment by leonyu** [comment]
@Clete2 instead of using `godep`, just straight up `go get && get build` works for me: 

screen shot 2016-10-26 at 3 25 47 am

**Comment by ilovezfs** [comment]
We don't use `go get`.

**Comment by ilovezfs** [comment]
@leonyu also what I already suggested above does indeed work.
```
==> Summary
🍺  /usr/local/Cellar/syncthing-inotify/0.8.4: 4 files, 4.4M, built in 23 seconds
```

**Comment by ilovezfs** [comment]
@Clete2 FYI I just pushed the relevant commit to your master branch.

**Comment by Clete2** [comment]
@ilovezfs Thank you. I intended to do so but have been busy. I appreciate it.

**Comment by ilovezfs** [comment]
@Clete2 no problem. I just didn't want you to be surprised that a random commit showed up in your fork's master branch. In the future, I'd suggest opening PRs from a separate branch other than master.

**Comment by Clete2** [comment]
@ilovezfs I usually make separate branches, but haven't been bothering when I'm only making one change. I am surprised you had permission to push. Maybe because you are an owner of the main repo, you can push to forked ones. Interesting.

P.S. I love ZFS too. Have 2 machines running RAID-Z in geographically separate locations (800+ miles apart) solid for 2+ years with very little intervention. Using it to backup with CrashPlan & rsync. Crossing my fingers, no drive failures yet.

**Comment by Clete2** [comment]
Merge? Build passed.

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Sorry for the wait! Merged as e5d01d3c2d1642623f784e854858e7184e2d0171 and 7ace4e04057149c09030bbbefd30cbd05266dfe7.

**Pull request closed without merging**
