### PR TITLE
php 7.4.2

### PR DESCRIPTION
**Pull request by chelout**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Thanks @chelout!!

**Comment by ngocphamm** [comment]
Well the version is not officially out yet, 18 hours after the PR was opened... 

https://www.php.net/
https://web.archive.org/web/20200122234953/https://www.php.net/

**Comment by chenrui333** [comment]
That is interesting, so that is kind of pre-release?

**Comment by chenrui333** [comment]
@ngocphamm My understanding is just a well-crafted release notes missing before it gets officially announced.

**Comment by ngocphamm** [comment]
@chenrui333 Yeah I'm not 100% sure as I'm not anyway involved in PHP release process. The version was tagged 2 days ago so I guess it's technically ready, just not having an official release notes on the web, like you said.

https://github.com/php/php-src/tags

**Comment by chenrui333** [comment]
Yeah, let's keep an eye on it. :)

**Comment by chenrui333** [comment]
Thanks for bringing this into our attention.

**Comment by shivammathur** [comment]
@chenrui333 @chelout Now sure when `--with-pdo-odbc=unixODB` was added, but shouldn't the `,` in [L149](https://github.com/Homebrew/homebrew-core/blob/2bfb924f6fd765b006d45e6f0b36c35ad53b8b40/Formula/php.rb#L149) be an `=`.

**Comment by SMillerDev** [comment]
Generally upstream tags and builds on Tuesday, tests and does validation and then releases on Thursday.

**Comment by chelout** [comment]
Well php 7.4.2 officially released https://www.php.net/downloads.php#v7.4.2 sha256 remains unchanged

**Pull request closed without merging**
