### PR TITLE
arm-linux-gnueabihf-binutils 2.31

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@haraldF do you mind taking a look at figuring out what's wrong here and working with upstream to get it fixed? I'm slightly concerned this seems more geared toward Linux and already broke.

```
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl -g -O2 -DENABLE_PLUGINS -DLOCALEDIR=\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\" -g -O2 -g -O2 -c testplug.c -o libldtestplug_la-testplug.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl -g -O2 -DENABLE_PLUGINS -DLOCALEDIR=\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\" -g -O2 -g -O2 -c testplug2.c -o libldtestplug2_la-testplug2.o >/dev/null 2>&1
clang++ -DHAVE_CONFIG_H -I.  -I. -I./../include -I./../elfcpp -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\"" -DBINDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/bin\"" -DTOOLBINDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/arm-linux-gnueabihf/bin\"" -DTOOLLIBDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/arm-linux-gnueabihf/lib\"" -I./../intl  -W -Wall    -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -frandom-seed=icf.o -I./../zlib -pthread -g -O2 -c -o icf.o icf.cc
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -g -O2 -g -O2 -c -o libldtestplug3_la-testplug3.lo `test -f 'testplug3.c' || echo './'`testplug3.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl -g -O2 -DENABLE_PLUGINS -DLOCALEDIR=\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\" -g -O2 -g -O2 -c testplug3.c  -fno-common -DPIC -o .libs/libldtestplug3_la-testplug3.o
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl -g -O2 -DENABLE_PLUGINS -DLOCALEDIR=\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\" -g -O2 -g -O2 -c testplug3.c -o libldtestplug3_la-testplug3.o >/dev/null 2>&1
gold-threads.cc:288:13: error: expected expression
    : once_(PTHREAD_ONCE_INIT)
            ^
/usr/include/pthread.h:210:27: note: expanded from macro 'PTHREAD_ONCE_INIT'
#define PTHREAD_ONCE_INIT {_PTHREAD_ONCE_SIG_init, {0}}
                          ^
1 error generated.
make[4]: *** [gold-threads.o] Error 1
make[4]: *** Waiting for unfinished jobs....
/bin/sh ./libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -g -O2 -g -O2 -c -o libldtestplug4_la-testplug4.lo `test -f 'testplug4.c' || echo './'`testplug4.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl -g -O2 -DENABLE_PLUGINS -DLOCALEDIR=\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\" -g -O2 -g -O2 -c testplug4.c  -fno-common -DPIC -o .libs/libldtestplug4_la-testplug4.o
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c `test -f ldgram.c || echo ./`ldgram.c 
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl -g -O2 -DENABLE_PLUGINS -DLOCALEDIR=\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\" -g -O2 -g -O2 -c testplug4.c -o libldtestplug4_la-testplug4.o >/dev/null 2>&1
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c ./ldlex-wrapper.c 
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -o lexsup.o lexsup.c
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -o ldlang.o ldlang.c
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -o mri.o mri.c
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -o ldctor.o ldctor.c
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -DDEFAULT_EMULATION='"armelf_linux_eabi"' \
	  -DBINDIR='"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/bin"' -DTOOLBINDIR='"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/arm-linux-gnueabihf/bin"' \
	  -DTARGET='"arm-unknown-linux-gnueabihf"' -DTARGET_SYSTEM_ROOT=\"\" \
	  ./ldmain.c
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-gold] Error 2
make[1]: clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -o ldwrite.o ldwrite.c
*** Waiting for unfinished jobs....
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -o ldexp.o ldexp.c
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -o ldemul.o ldemul.c
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -o ldver.o ldver.c
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -o ldmisc.o ldmisc.c
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -DSCRIPTDIR='"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/arm-linux-gnueabihf/lib"' -DBINDIR='"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/bin"' \
	  -DTOOLBINDIR='"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/arm-linux-gnueabihf/bin"' \
	  ./ldfile.c
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -o ldcref.o ldcref.c
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -o plugin.o plugin.c
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -o ldbuildid.o ldbuildid.c
cp ./emultempl/astring.sed stringify.sed
/bin/sh ./libtool  --tag=CC   --mode=link clang -g -O2 -g -O2 -no-undefined -rpath /nowhere -Wl,-no_pie  -o libldtestplug.la  libldtestplug_la-testplug.lo  
/bin/sh ./libtool  --tag=CC   --mode=link clang -g -O2 -g -O2 -no-undefined -rpath /nowhere -Wl,-no_pie  -o libldtestplug2.la  libldtestplug2_la-testplug2.lo  
libtool: link: clang -dynamiclib  -o .libs/libldtestplug.0.dylib  .libs/libldtestplug_la-testplug.o    -Wl,-no_pie   -install_name  /nowhere/libldtestplug.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
/bin/sh ./libtool  --tag=CC   --mode=link clang -g -O2 -g -O2 -no-undefined -rpath /nowhere -Wl,-no_pie  -o libldtestplug3.la  libldtestplug3_la-testplug3.lo  
libtool: link: clang -dynamiclib  -o .libs/libldtestplug2.0.dylib  .libs/libldtestplug2_la-testplug2.o    -Wl,-no_pie   -install_name  /nowhere/libldtestplug2.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
libtool: link: dsymutil .libs/libldtestplug.0.dylib || :
warning: no debug symbols in executable (-arch x86_64)
libtool: link: (cd ".libs" && rm -f "libldtestplug.dylib" && ln -s "libldtestplug.0.dylib" "libldtestplug.dylib")
libtool: link: ar rc .libs/libldtestplug.a  libldtestplug_la-testplug.o
libtool: link: clang -dynamiclib  -o .libs/libldtestplug3.0.dylib  .libs/libldtestplug3_la-testplug3.o    -Wl,-no_pie   -install_name  /nowhere/libldtestplug3.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
libtool: link: ranlib .libs/libldtestplug.a
libtool: link: dsymutil .libs/libldtestplug2.0.dylib || :
warning: no debug symbols in executable (-arch x86_64)
libtool: link: (cd ".libs" && rm -f "libldtestplug2.dylib" && ln -s "libldtestplug2.0.dylib" "libldtestplug2.dylib")
libtool: link: ( cd ".libs" && rm -f "libldtestplug.la" && ln -s "../libldtestplug.la" "libldtestplug.la" )
/bin/sh ./libtool  --tag=CC   --mode=link clang -g -O2 -g -O2 -no-undefined -rpath /nowhere -Wl,-no_pie  -o libldtestplug4.la  libldtestplug4_la-testplug4.lo  
libtool: link: ar rc .libs/libldtestplug2.a  libldtestplug2_la-testplug2.o
libtool: link: ranlib .libs/libldtestplug2.a
libtool: link: ( cd ".libs" && rm -f "libldtestplug2.la" && ln -s "../libldtestplug2.la" "libldtestplug2.la" )
base=`echo earmelf_linux_eabi.c | sed -e 's,e\(.*\).c,\1,'`; \
	/Applications/Xcode.app/Contents/Developer/usr/bin/make run-genscripts "script_target=$base" "script_tdirname=tdir_$base"
libtool: link: dsymutil .libs/libldtestplug3.0.dylib || :
warning: no debug symbols in executable (-arch x86_64)
LIB_PATH='' /bin/sh ./genscripts.sh "." "/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/lib" "/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31" "/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31" x86_64-apple-darwin17.7.0 arm-unknown-linux-gnueabihf arm-linux-gnueabihf "armelf_linux_eabi armelfb_linux_eabi" "/usr/local/lib /lib /usr/lib" no yes armelf_linux_eabi "arm-linux-gnueabihf"
libtool: link: (cd ".libs" && rm -f "libldtestplug3.dylib" && ln -s "libldtestplug3.0.dylib" "libldtestplug3.dylib")
libtool: link: ar rc .libs/libldtestplug3.a  libldtestplug3_la-testplug3.o
libtool: link: ranlib .libs/libldtestplug3.a
libtool: link: clang -dynamiclib  -o .libs/libldtestplug4.0.dylib  .libs/libldtestplug4_la-testplug4.o    -Wl,-no_pie   -install_name  /nowhere/libldtestplug4.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
libtool: link: ( cd ".libs" && rm -f "libldtestplug3.la" && ln -s "../libldtestplug3.la" "libldtestplug3.la" )
base=`echo earmelfb_linux_eabi.c | sed -e 's,e\(.*\).c,\1,'`; \
	/Applications/Xcode.app/Contents/Developer/usr/bin/make run-genscripts "script_target=$base" "script_tdirname=tdir_$base"
LIB_PATH='' /bin/sh ./genscripts.sh "." "/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/lib" "/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31" "/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31" x86_64-apple-darwin17.7.0 arm-unknown-linux-gnueabihf arm-linux-gnueabihf "armelf_linux_eabi armelfb_linux_eabi" "/usr/local/lib /lib /usr/lib" no yes armelfb_linux_eabi "arm-linux-gnueabihf"
libtool: link: dsymutil .libs/libldtestplug4.0.dylib || :
warning: no debug symbols in executable (-arch x86_64)
libtool: link: (cd ".libs" && rm -f "libldtestplug4.dylib" && ln -s "libldtestplug4.0.dylib" "libldtestplug4.dylib")
libtool: link: ar rc .libs/libldtestplug4.a  libldtestplug4_la-testplug4.o
libtool: link: ranlib .libs/libldtestplug4.a
libtool: link: ( cd ".libs" && rm -f "libldtestplug4.la" && ln -s "../libldtestplug4.la" "libldtestplug4.la" )
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -o earmelf_linux_eabi.o earmelf_linux_eabi.c
clang -DHAVE_CONFIG_H -I.  -I. -I. -I../bfd -I./../bfd -I./../include -I./../intl  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/usr/local/Cellar/arm-linux-gnueabihf-binutils/2.31/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -c -o earmelfb_linux_eabi.o earmelfb_linux_eabi.c
/bin/sh ./libtool  --tag=CC   --mode=link clang -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2  -Wl,-no_pie  -o ld-new ldgram.o ldlex-wrapper.o lexsup.o ldlang.o mri.o ldctor.o ldmain.o ldwrite.o ldexp.o ldemul.o ldver.o ldmisc.o ldfile.o ldcref.o plugin.o ldbuildid.o earmelf_linux_eabi.o earmelfb_linux_eabi.o  ../bfd/libbfd.la ../libiberty/libiberty.a ./../intl/libintl.a -liconv 
libtool: link: clang -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=FALSE -g -O2 -Wl,-no_pie -o ld-new ldgram.o ldlex-wrapper.o lexsup.o ldlang.o mri.o ldctor.o ldmain.o ldwrite.o ldexp.o ldemul.o ldver.o ldmisc.o ldfile.o ldcref.o plugin.o ldbuildid.o earmelf_linux_eabi.o earmelfb_linux_eabi.o  ../bfd/.libs/libbfd.a -L/private/tmp/arm-linux-gnueabihf-binutils-20180714-58284-1y5pxph/binutils-2.31/zlib -ldl -lz ../libiberty/libiberty.a ./../intl/libintl.a -liconv
make: *** [all] Error 2
```

**Comment by haraldF** [comment]
@ilovezfs thanks for looking into this. I wonder how that code could have ever compiled, it's also bending the rules on Linux...

I have a preliminary patch, will open an upstream bug and hopefully get this fixed.

```diff
diff --git a/gold/gold-threads.cc b/gold/gold-threads.cc
index 3c53dff1d7..0025e09803 100644
--- a/gold/gold-threads.cc
+++ b/gold/gold-threads.cc
@@ -278,6 +278,8 @@ Condvar::~Condvar()
 
 #ifdef ENABLE_THREADS
 
+static pthread_once_t static_initializer_helper = PTHREAD_ONCE_INIT;
+
 // Class Once_initialize.  This exists to hold a pthread_once_t
 // structure for Once.
 
@@ -285,7 +287,7 @@ class Once_initialize
 {
  public:
   Once_initialize()
-    : once_(PTHREAD_ONCE_INIT)
+    : once_(static_initializer_helper)
   { }
 
   // Return a pointer to the pthread_once_t variable.
```

**Comment by ilovezfs** [comment]
Thanks @haraldF!

**Comment by haraldF** [comment]
Upstream bug: https://sourceware.org/bugzilla/show_bug.cgi?id=23424

**Pull request closed without merging**
