### PR TITLE
ponyc 0.27.0

### PR DESCRIPTION
**Pull request by SeanTAllen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SeanTAllen** [comment]
I was asked to note when we finally dropped LLVM 3.9.1 as a requirement. That time is now. Sadly there doesn't seem to be a way to specifically target "LLVM 7" rather than "LLVM" so eventually, if you upgrade LLVM to mean 8 instead of 7, I'll have to issue a PR to switch specifically to 7.

**Comment by fxcoudert** [comment]
Well, the test should catch that, shouldn't it? In that case, it will be done during the llvm update.

**Comment by SeanTAllen** [comment]
@fxcoudert yes, the test will catch it. Good to know that it will be caught then.

**Comment by fxcoudert** [comment]
Thanks for the update and clear explanation!

**Pull request closed without merging**
