### PR TITLE
spirv-headers: include two extension patches

### PR DESCRIPTION
**Pull request by pthariensflame**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Includes SPV_EXT_shader_tile_image and SPV_KHR_ray_tracing_position_fetch.
Unblocks #129684.

### CODE REVIEW

**Comment by pthariensflame** [comment]
@carlocab

**Comment by carlocab** [comment]
Can you include this commit at #129684 so we can test that the patch works in CI too?

**Comment by pthariensflame** [comment]
I guess there needs to be a bit more incorporated here.  :/

**Comment by pthariensflame** [comment]
Figured out the other half needed.

**Comment by carlocab** [comment]
Let's keep everything at #129684 to avoid doubling up on CI runs.

**Comment by pthariensflame** [comment]
Okay!

**Pull request closed without merging**
