### PR TITLE
rrdtool 1.7.1

### PR DESCRIPTION
**Pull request by gordolio**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

First PR to homebrew. Go easy on me. Thanks! :)

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks for the pull request! Got some questions:

Doesn't this require ruby of the site install is enabled? 
Is the patch no longer needed?

**Comment by gordolio** [comment]
The original patch removed a comical message about ordering a CD from the project's website and also removed 5 `sleep 1` statements. This PR just comments out the `sleep 1` statements via `inreplace`.

You're right on the ruby site install. I'll fix it and add tests to verify that both the ruby and perl bindings work.

**Comment by zbeekman** [comment]
ping @gordolio

**Comment by fxcoudert** [comment]
Given no response, closing for now.

**Pull request closed without merging**
