### PR TITLE
go: do not install test/debug files

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
See https://github.com/Homebrew/brew/issues/10696

**Comment by carlocab** [comment]
There are only 95 failures on ARM, so it seems like there are at least a handful of formulae that are actually building but haven't been bottled yet. I'm going to look into those and dispatch bottle jobs for them.

**Comment by carlocab** [comment]
Whoops; I guess I underestimate how many would fail there 😅

**Comment by iMichka** [comment]
Let's merge this, the errors are unrelated (mostly ARM failures due to unbottted stuff, and transient network errors (I hope)).

**Pull request merged**
