### PR TITLE
virtualpg: add livecheck, update license

### PR DESCRIPTION
**Pull request by chenrui333**
virtualpg: add livecheck, update license

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
License LGTM

**Review by samford — DISMISSED** [review]

**Review by samford — APPROVED** [review]
I usually don't rebase using the github.com interface but I figured I would give it a try for once. It dismissed my review and added a merge commit, so it seems like rebasing outside of github.com (and pushing the branch) is still preferable for me but it's good to know. Approving this again.

**Comment by carlocab** [comment]
I don't actually understand how that happened... I usually just use the GitHub rebase-and-merge interface for PRs that can be merged without bottles or commit message revisions. Do you just use the CLI otherwise?

**Comment by samford** [comment]
@carlocab I haven't tried using rebase-and-merge when there's a merge conflict (we had one from the `virtualpg` 2.0.1 PR in this instance) but this PR needed to be squash-and-merge'd anyway, so I had to rebase it and resolve the conflict first.

I resolved the merge conflict using the github.com interface this time and that's what created the merge commit. I usually fix merge conflicts locally by simply checking out the PR branch, rebasing the commits, and pushing to the branch (which avoids the unnecessary merge commit).

**Comment by carlocab** [comment]
Ah, I see. Yes, you don't want to use the GitHub web UI to resolve merge conflicts. It should work fine when there aren't any and the commit structure can be rebased as is, though.

**Comment by samford** [comment]
> I haven't tried using rebase-and-merge when there's a merge conflict but this PR needed to be squash-and-merge'd anyway, so I had to rebase it and resolve the conflict first. It should work fine when there aren't any and the commit structure can be rebased as is, though.

Yep, I've used rebase-and-merge without any problems on PRs where there are multiple commits that we want to preserve, the commits are good, and there aren't any merge conflicts. I just wanted to satisfy my curiosity about what happens if you resolve a merge conflict using the GitHub web interface (and it didn't matter in this case due to the impending squash-and-merge). Needless to say, I don't plan to ever do that again, ahah.

**Comment by carlocab** [comment]
Yes, I have to say, I too have been curious about the merge-conflict-resolution web interface. However, I've been too concerned about breaking something to give it a try 😅 Good to know!

**Pull request merged**
