### PR TITLE
qbs 1.10.0

### PR DESCRIPTION
**Pull request by jakepetroules**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jakepetroules** [comment]
By the way, should we be passing `CONFIG+=qbs_disable_rpath` to qmake? Homebrew doesn't want ports using rpath, right? @ilovezfs?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@jakepetroules we usually rewrite rpath automatically though not always so yes it's usually best to disable it where possible yourself.

**Comment by jakepetroules** [comment]
OK, I disabled it now.

**Comment by ilovezfs** [comment]
Thanks @jakepetroules!

**Pull request closed without merging**
