### PR TITLE
http_load: enable openssl by default

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by vszakats** [comment]
Is there any comments or anything to fix on this PR to be accepted for merge?

**Comment by ilovezfs** [comment]
This change is not really justified by the analytics (3% of users are using the option), but there are only 60 installs total in the last month so I guess it's not a huge deal one way or the other.

**Comment by vszakats** [comment]
If there's nothing major against, as the web shift to HTTPS, I think it'd be nice to have support for it by default. OpenSSL is installed anyway on most systems and the build overhead is practically zero (it's a very low-footprint tool anyway.)

**Comment by ilovezfs** [comment]
Shipped! Thanks @vszakats :)

**Pull request closed without merging**
