### PR TITLE
Import formulae from homebrew/python.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
The other two are going to homebrew/science because they have hard homebrew/science dependencies.

Also see https://github.com/Homebrew/homebrew-python/pull/388 and https://github.com/Homebrew/homebrew-science/pull/4894.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
CC @tdsmith for thoughts on whether all these should be imported and if any of them should be keg-only.

**Comment by tdsmith** [comment]
Packaging Python libraries is swimming against the current for us; Homebrew can't do it well, Homebrew can't even interoperate well with pip, and the python ecosystem has made huge strides in delivering pre-built packages. A few libraries haven't caught up and tap support for those is fine but I don't like the precedent of moving these into core because we might attract more of them and that would be bad. I don't even think that moving numpy and scipy into core really provides value for most people most of the time; pip will work better. It makes some of our dependency logic for bindings a little simpler but accepting that a complex package like gnuradio is going to be a little inelegant might be better than carrying python libraries in earnest in core. Delivering these as keg only wouldn't be helpful. 

Anyway, -1 on anything but numpy and scipy; -0 on those. On my phone right now but willing to elaborate on anything here.

**Comment by MikeMcQuaid** [comment]
@tdsmith Great, thanks. Will wait around for a longer response. Just so it's clear: the homebrew/python tap is going to get burned down anyway. Is it worth importing any of these into e.g. homebrew/science if needed instead or just killing them entirely? With `numpy` and `scipy`: I'm basically figuring that it's useful if we would ever need this for our formulae, if it saves mass vendoring or compilation time with bottles. If none of these are the case: let's not add.

**Comment by tdsmith** [comment]
I don't really understand why killing the tap is helpful but that doesn't
change the calculus. Scipy is legitimately slow to build and needs numpy.

**Comment by MikeMcQuaid** [comment]
> I don't really understand why killing the tap is helpful

We're killing all taps that are maintained purely by a subset of maintainers. This is because they offer a worse user experience, don't get e.g. updated/CI tested for reverse dependency failures and generally the same level of support and care as homebrew/core.

> but that doesn't change the calculus.

Cool, good to know.

> Scipy is legitimately slow to build and needs numpy.

Ok, cool. Let's add both and nothing else.

**Comment by ilovezfs** [comment]
I'm trying to reconcile the viewpoint expressed above with the insanity of the practice of copy-pasting the exact same patch to `cryptography` into every formula that needs it. Ditto `pillow`.

**Comment by tdsmith** [comment]
You could try asking either project to do a release.

**Comment by ilovezfs** [comment]
That's completely beside the point.

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by tdsmith** [comment]
Insofar as that's two (responsive and friendly!) projects out of hundreds of resourced packages, I'm not sure I am :)

> Will wait around for a longer response.

FWIW, I didn't have anything to add unless you wanted me to elaborate on something.

**Comment by MikeMcQuaid** [comment]
> FWIW, I didn't have anything to add unless you wanted me to elaborate on something.

@tdsmith No, all good, thanks. Just didn't want you to feel rushed or anything.

**Pull request closed without merging**
