### PR TITLE
jasper 3.0.0

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
Not too sure what to do here, sorry.

**Comment by SMillerDev** [comment]
Can you compile it locally from source?

**Comment by miccal** [comment]
No - it seems the file `CMakeLists.txt` no longer resides at `jasper-3.0.0/build/build/cmake/src/CMakeFiles/CMakeTmp/CMakeLists.txt` but now is at `jasper-3.0.0/CMakeLists.txt`.

**Comment by miccal** [comment]
Version 3.0.1 is out, so I am going to close this for now.

**Pull request closed without merging**
