### PR TITLE
readosm 1.1.0a

### PR DESCRIPTION
**Pull request by zachauten**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
From https://www.gaia-gis.it/fossil/readosm/index

> ReadOSM is licensed under the MPL tri-license terms; you are free to choose the best-fit license between:
>
> the MPL 1.1
>the GPL v2.0 or any subsequent version
>the LGPL v2.1 or any subsequent version

**Comment by bayandin** [comment]
```
==> FAILED
Error: 1 problem in 1 formula detected
readosm:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      share/doc/readosm/examples/Makefile
      share/doc/readosm/examples/test_osm2
      share/doc/readosm/examples/test_osm3
      share/doc/readosm/examples/test_osm1
```

**Comment by zachauten** [comment]
Added licenses, still need to figure out where it's recording the shims.

**Comment by chenrui333** [comment]
#65824

**Pull request closed without merging**
