### PR TITLE
mimirtool 2.3.1 (new formula)

### PR DESCRIPTION
**Pull request by jvasallo**
Adding mimirtool (a component of mimir) to homebrew-core to allow users of mimir to install mimirtool via brew.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by gromgit** [comment]
@jvasallo, did you actually run `brew audit --new mimirtool` as you claimed in the PR description? It would've thrown out **twenty-nine** issues, including this one that's an absolulte no-no for Homebrew core inclusion:
```
  * 11: col 9: https://github.com/grafana/mimir/releases/download/mimir-2.3.1/mimirtool-darwin-arm64 looks like a binary package, not a source archive; homebrew/core is source-only.
```
ProTip: Adding the `--fix` flag to `brew audit` runs automatically fixes up simple stuff for you, and tells you what it can't fix.

**Comment by jvasallo** [comment]
> @jvasallo, did you actually run `brew audit --new mimirtool` as you claimed in the PR description? It would've thrown out **twenty-nine** issues, including this one that's an absolute no-no for Homebrew core inclusion:
> 
> ```
>   * 11: col 9: https://github.com/grafana/mimir/releases/download/mimir-2.3.1/mimirtool-darwin-arm64 looks like a binary package, not a source archive; homebrew/core is source-only.
> ```
> 
> ProTip: Adding the `--fix` flag to `brew audit` runs automatically fixes up simple stuff for you, and tells you what it can't fix.

I am sorry, I could have sworn I did. I will update my comment, but it is definitely not passing the minimum checks. Again, apologies, new to contributing in Homebrew core. 👍🏽 

Follow-up on the one that is probably going to be the biggest issue; binary packages. The tool is part of a bigger application/solution: Grafana Mimir. I am not entirely sure I can just compile the source for the tool (mimirtool), does this mean I probably can't contribute it to Homebrew in it's current iteration and need to add the entire package (i.e all of the components that encompass Mimir)? I am only an end user trying to make it easier to install an operational tool versus the entire application. Any guidance/recommendations would be appreciated; regardless thank you!

**Comment by gromgit** [comment]
>  I am not entirely sure I can just compile the source for the tool (mimirtool), does this mean I probably can't contribute it to Homebrew in it's current iteration and need to add the entire package (i.e all of the components that encompass Mimir)?

Building from source is a basic requirement for all Homebrew core formulae. If it's not possible to build a standalone `mimirtool` without building all of Mimir, then the formula would have to pull down the entire Mimir source distribution.

Whether the final formula then installs just `mimirtool`, or all of Mimir, is up to the contributor. The `postgresql` formulae, for instance, package the end-user CLI `psql` along with the server binaries, but I can imagine someone wanting to put server and client components in separate formulae, but both building from the same source tarball.

**Comment by jvasallo** [comment]
> > I am not entirely sure I can just compile the source for the tool (mimirtool), does this mean I probably can't contribute it to Homebrew in it's current iteration and need to add the entire package (i.e all of the components that encompass Mimir)?
> 
> Building from source is a basic requirement for all Homebrew core formulae. If it's not possible to build a standalone `mimirtool` without building all of Mimir, then the formula would have to pull down the entire Mimir source distribution.
> 
> Whether the final formula then installs just `mimirtool`, or all of Mimir, is up to the contributor. The `postgresql` formulae, for instance, package the end-user CLI `psql` along with the server binaries, but I can imagine someone wanting to put server and client components in separate formulae, but both building from the same source tarball.

Perfect example, let me take a peek at that and see if I can come up with something similar. Appreciate the review all. 👍

**Pull request closed without merging**
