### PR TITLE
pdftohtml: add missing test and license

### PR DESCRIPTION
**Pull request by gromgit**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by gromgit** [comment]
Odd that `brew audit --strict --online --git --fix pdftohtml` didn't catch the missing license. Was the license check relaxed recently?

**Comment by gromgit** [comment]
FYI, `pdftohtml` doesn't have a declared license, but since it's derived from `xpdf` which _is_ licensed under `GPL-2.0-only`, I'm assuming implicit virality.

**Review by SMillerDev — APPROVED** [review]

**Review by nandahkrishna — APPROVED** [review]
This was included in the README, so 👍🏼:
```
Pdftohtml is licensed under the GNU General Public License (GPL), version
2. See COPYING. 
```

**Comment by gromgit** [comment]
> This was included in the README

There isn't one in the declared source tarball. Are we looking at different things?

**Comment by nandahkrishna** [comment]
Oops, you're right – I was looking at `0.39` instead.

**Pull request closed without merging**
