### PR TITLE
Fix bug #6889 mysql++ blocks mysql

### PR DESCRIPTION
**Pull request by Jose123456**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Also added a trivial test

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Fails to build: https://bot.brew.sh/job/Homebrew%20Core/11360/version=any_sierra/testReport/junit/brew-test-bot/sierra/install_mysql__/

**Comment by Jose123456** [comment]
Finally figured it out. BTW, the custom `MysqlClientRequirement` in [`mysql-connector-c++.rb`] (https://github.com/Homebrew/homebrew-core/blob/master/Formula/mysql-connector-c++.rb) should probably be removed and replaced with the `mysql` requirement from [here](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/requirements.rb#L56).

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `mysql++: use mysql instead of connector.`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

**Comment by Jose123456** [comment]
You're welcome and thank you for the merge.

**Pull request closed without merging**
