### PR TITLE
termbox 1.1.0 (import from head-only)

### PR DESCRIPTION
**Pull request by bfontaine**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

https://github.com/Homebrew/homebrew-head-only/pull/218

### CODE REVIEW

**Comment by DomT4** [comment]
Test failed but otherwise seems okay 👍.

**Comment by bfontaine** [comment]
```
==> ./test
tb_shutdown() should not be called twice.
Error: termbox: failed
Failed executing: ./test 
```

Weird, I had no issue locally.

**Comment by DomT4** [comment]
Maybe worth chucking in a `return 0;` in case the test is tripping over itself or something? Not sure.

**Comment by bfontaine** [comment]
Looking at the source code I guess the code that gets the terminal width fails because it runs in a noninteractive session; thus `tb_shutdown()` thinks the variable that holds it was already reset.

**Comment by DomT4** [comment]
Nice sleuthing! :shipit:

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by apjanke** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
