### PR TITLE
phpunit 9.2.1

### PR DESCRIPTION
**Pull request by bepsvpt**
---

Debug Info:
- homebrew updater version: 1.0.6
- formula new file size: 3,090,067 bytes
- formula fetch time: 3.2 seconds

Pull request opened by [homebrew-updater](https://github.com/bepsvpt/homebrew-updater) project.

Open a new [issue](https://github.com/bepsvpt/homebrew-updater/issues) to monitor new formula.

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Comment by Bo98** [comment]
This has a merge conflict

**Comment by bepsvpt** [comment]
Resolved.

**Comment by SMillerDev** [comment]
Can you also squash the commits into one `phpunit 9.2.1`

**Comment by Bo98** [comment]
Since this can be merged via GitHub UI (no bottles), I'll just use the "squash and merge".

**Pull request merged**
