### PR TITLE
molten-vk 1.2.9

### PR DESCRIPTION
**Pull request by nik312123**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.
<details>
  <summary>release notes</summary>
  <pre>- Add support for extensions:
	- `VK_EXT_host_image_copy`
- To support legacy apps, restore `MoltenVK/dylib` directory via symlink to `MoltenVK/dynamic/dylib`.
- Enhancements to `MVKPerformanceStatistics`. Add `MVKPerformanceTracker::previous`, 
  `MVKQueuePerformance::waitSubmitCommandBuffers`, and `MVKQueuePerformance::waitPresentSwapchains`.
- Add `MVK_CONFIG_SHADER_DUMP_DIR` configuration parameter to optionally dump shaders to files.
- Return **MoltenVK** log level string in `pMessageIdName` field of debug utils callback data.
- Fix crash when using `VK_EXT_metal_objects` under _ARC_.
- Fix deadlock when creating a swapchain on a thread other than the main thread.
- Fix potential memory leak in `vkQueueWaitIdle()`.
- Fix argument buffer padding on shader conversion.
- Avoid atomic image usage if native atomics are not supported on the platform.
- Ensure buffer bindings are actually used to avoid potential overrun on Metal buffer indexes.
- Update dependency libraries to match _Vulkan SDK 1.3.283_.
- Update `MVK_PRIVATE_API_VERSION` to `41`.
- Update to latest SPIRV-Cross:
  - MSL: Add support for overlapping bindings.
  - MSL: Use recursive template for `spvArrayCopy()`.
  - MSL: Improve argument buffer descriptor aliasing implementation.
  - MSL: Workaround compiler issue with image fence when used as reference.
  - MSL: Fix SUMulExtended for 64-bit inputs.
  - MSL: Handle Atomic{S,U}{Min,Max} with mismatched image sign.
  - MSL: Handle missing FP16 trancendental overloads.
  - MSL: Remove pointer wrapper stored in `spvDescriptorArray()` to avoid potential Metal compiler bug. 
  - MSL: Fix argument buffer padding.
</pre>
</details>

### CODE REVIEW

**Comment by nik312123** [comment]
Could someone with triage access to the repository please add a help-wanted label?

**Comment by alebcay** [comment]
Sorry for the noise and repeated force pushes, I think I managed to fix the build failure. Also, thanks for contributing to Homebrew!

@fxcoudert - it looks like the extra `xcodebuild` steps aren't needed anymore on Sonoma, even if using `clang` >= 1500. Not sure exactly why.

**Review by carlocab — APPROVED** [review]
Thanks!

**Review by chenrui333 — COMMENTED** [review]
thanks!

**Pull request merged**
