### PR TITLE
arangodb 3.7.7

### PR DESCRIPTION
**Pull request by KVS85**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by KVS85** [comment]
https://github.com/Homebrew/homebrew-core/commit/7cb8e28d74076c824a2be6d8f970f7a7ae9533eb#diff-8c95868bc3323b2d39b21cb97e67f5f80db3e9a59bdd1101530a2721e8089a6b is generally correct (kudos to @chenrui333) but `0.14.18` Starter appeared by mistake and will be removed.

New Starter release with additional fixed (v0.15+) will be included in later ArangoDB releases.

**Review by carlocab — CHANGES_REQUESTED** [review]
Please add `revision 1` (in between the `license` and `head` lines), and use the commit message `arangodb: update resource`. Thanks!

**Comment by carlocab** [comment]
Sorry, should've been clearer in my last comment: squash your commits together, please. Thank you.

**Comment by KVS85** [comment]
> Sorry, should've been clearer in my last comment: squash your commits together, please. Thank you.

Done.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Thanks, @KVS85!

**Pull request closed without merging**
