### PR TITLE
glslviewer 1.5 (new formula)

### PR DESCRIPTION
**Pull request by andystanton**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by andystanton** [comment]
The application is a command line tool but launches a window, which fails in Jenkins with the following error:

```
22:09:21 ABORT: GLFW create window failed
22:09:21 Error: glslviewer: failed
```

Even running the tool without args requires window creation. What do the project maintainers recommend for the test?

**Comment by andystanton** [comment]
@ilovezfs any suggestions? Any execution of the app will result in a window being created which fails in Jenkins. Should I have an empty test block?

**Comment by dunn** [comment]
Looking at the project README, there's a `--headless` option that should work.

**Comment by andystanton** [comment]
@dunn Doh I missed that! However the headless mode uses GLFW's headless windowing still requires a display and fails in Jenkins:

```
       Testing glslviewer
/usr/bin/sandbox-exec -f /tmp/homebrew20171107-45628-v7ac9r.sb /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glslviewer.rb --verbose
==> /usr/local/Cellar/glslviewer/1.3/bin/glslViewer /tmp/glslviewer-test-20171107-45629-1g5p9lo/test.frag -s 0 --headless
2017-11-07 18:04:59.093 glslViewer[45637:23679043] *** attempt to register for all distributed notifications thwarted by sandboxing.

Date/Time:     Tue Nov  7 18:04:59 2017
OS Version:    17A362a
Application:   glslViewer

Backtrace:
0   CoreFoundation                      0x00007fff3db19349 __CFGenerateReport + 281
1   CoreFoundation                      0x00007fff3da74ea5 __CFXNotificationRegisterObserver + 1045
2   CoreFoundation                      0x00007fff3d97345e _CFXNotificationRegisterObserver + 14
3   Foundation                          0x00007fff3fa281b4 -[NSDistributedNotificationCenter addObserver:selector:name:object:suspensionBehavior:] + 239
4   Foundation                          0x00007fff3fa3124a -[NSDistributedNotificationCenter addObserver:selector:name:object:] + 29
5   libglfw.3.dylib                     0x000000010fad6567 _glfwPlatformInit + 172
6   libglfw.3.dylib                     0x000000010fad34ef glfwInit + 42
7   glslViewer                          0x000000010fa33412 _Z6initGLRN3glm5tvec4IiLNS_9precisionE0EEEb + 34
8   glslViewer                          0x000000010fa351f6 main + 2726
9   libdyld.dylib                       0x00007fff64f4b145 start + 1
10  ???                                 0x0000000000000005 0x0 + 5
GLFW error 0x10009: NSGL: Failed to find a suitable pixel format
ABORT: GLFW create window failed
Error: glslviewer: failed
```

Also the window is initialised before the validation is performed, so even with just `glslViewer --headless` will fail without a display:

https://github.com/patriciogonzalezvivo/glslViewer/blob/2c949e54d8f1d0845a02cee55ec0ad103a1a3824/src/main.cpp#L159

https://github.com/patriciogonzalezvivo/glslViewer/blob/2c949e54d8f1d0845a02cee55ec0ad103a1a3824/src/main.cpp#L321

This application will only work with an empty test block. Is this permitted?

**Comment by dunn** [comment]
> This application will only work with an empty test block. Is this permitted?

Unfortunately not.  Is there a library interface we can write a tiny test app to use?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by yvan-sraka** [comment]
It seems that there is something strange with the continuous integration here!

```
HTTP ERROR 404

Problem accessing /job/Homebrew%20Core%20Pull%20Requests/12716/. Reason:

    Not Found

Powered by Jetty:// 9.4.z-SNAPSHOT
```

I have the above error when I try to reach: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/12716/

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
@yvan-sraka we only keep builds for (I think) a week, so that's what happened.

**Comment by ilovezfs** [comment]
3 days.

**Comment by yvan-sraka** [comment]
Ok, so the backtrace is:

```
failed: brew test glslviewer --verbose

        Testing glslviewer
/usr/bin/sandbox-exec -f /tmp/homebrew20171123-79907-9l02uv.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glslviewer.rb --verbose
==> /usr/local/Cellar/glslviewer/1.3/bin/glslViewer /tmp/glslviewer-test-20171123-79908-780jqw/test.frag -s 0 --headless
2017-11-23 15:23:03.494 glslViewer[79916:14716202] *** attempt to register for all distributed notifications thwarted by sandboxing.

Date/Time:     Thu Nov 23 15:23:03 2017
OS Version:    16G1036
Application:   glslViewer

Backtrace:
0   CoreFoundation                      0x00007fff835bcb9a __CFGenerateReport + 282
1   CoreFoundation                      0x00007fff83513c02 __CFXNotificationRegisterObserver + 1058
2   CoreFoundation                      0x00007fff8341cacd _CFXNotificationRegisterObserver + 29
3   Foundation                          0x00007fff84e7dc05 -[NSDistributedNotificationCenter addObserver:selector:name:object:suspensionBehavior:] + 177
4   Foundation                          0x00007fff84e8707f -[NSDistributedNotificationCenter addObserver:selector:name:object:] + 29
5   libglfw.3.dylib                     0x000000010ad6045e _glfwPlatformInit + 175
6   libglfw.3.dylib                     0x000000010ad5d319 glfwInit + 42
7   glslViewer                          0x000000010acbd412 _Z6initGLRN3glm5tvec4IiLNS_9precisionE0EEEb + 34
8   glslViewer                          0x000000010acbf1f6 main + 2726
9   libdyld.dylib                       0x00007fff99026235 start + 1
GLFW error 0x10009: NSGL: Failed to find a suitable pixel format
ABORT: GLFW create window failed
Error: glslviewer: failed
Failed executing: /usr/local/Cellar/glslviewer/1.3/bin/glslViewer /tmp/glslviewer-test-20171123-79908-780jqw/test.frag -s 0 --headless
/usr/local/Homebrew/Library/Homebrew/formula.rb:1796:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1734:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1734:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glslviewer.rb:56:in `block in <class:Glslviewer>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1640:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1639:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:834:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1638:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1632:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by ilovezfs** [comment]
```
Error Message

failed: brew test glslviewer --verbose

Stacktrace

        Testing glslviewer
/usr/bin/sandbox-exec -f /tmp/homebrew20171123-79907-9l02uv.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glslviewer.rb --verbose
==> /usr/local/Cellar/glslviewer/1.3/bin/glslViewer /tmp/glslviewer-test-20171123-79908-780jqw/test.frag -s 0 --headless
2017-11-23 15:23:03.494 glslViewer[79916:14716202] *** attempt to register for all distributed notifications thwarted by sandboxing.

Date/Time:     Thu Nov 23 15:23:03 2017
OS Version:    16G1036
Application:   glslViewer

Backtrace:
0   CoreFoundation                      0x00007fff835bcb9a __CFGenerateReport + 282
1   CoreFoundation                      0x00007fff83513c02 __CFXNotificationRegisterObserver + 1058
2   CoreFoundation                      0x00007fff8341cacd _CFXNotificationRegisterObserver + 29
3   Foundation                          0x00007fff84e7dc05 -[NSDistributedNotificationCenter addObserver:selector:name:object:suspensionBehavior:] + 177
4   Foundation                          0x00007fff84e8707f -[NSDistributedNotificationCenter addObserver:selector:name:object:] + 29
5   libglfw.3.dylib                     0x000000010ad6045e _glfwPlatformInit + 175
6   libglfw.3.dylib                     0x000000010ad5d319 glfwInit + 42
7   glslViewer                          0x000000010acbd412 _Z6initGLRN3glm5tvec4IiLNS_9precisionE0EEEb + 34
8   glslViewer                          0x000000010acbf1f6 main + 2726
9   libdyld.dylib                       0x00007fff99026235 start + 1
GLFW error 0x10009: NSGL: Failed to find a suitable pixel format
ABORT: GLFW create window failed
Error: glslviewer: failed
Failed executing: /usr/local/Cellar/glslviewer/1.3/bin/glslViewer /tmp/glslviewer-test-20171123-79908-780jqw/test.frag -s 0 --headless
/usr/local/Homebrew/Library/Homebrew/formula.rb:1796:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1734:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1734:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glslviewer.rb:56:in `block in <class:Glslviewer>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1640:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1639:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:834:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1638:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1632:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'

      
```

**Comment by andystanton** [comment]
An update on the status of this PR:

* The build fails in Travis because the current released version of glslViewer always tries to create a window, regardless of what command line options it receives.
* I created a [PR in glslViewer](https://github.com/patriciogonzalezvivo/glslViewer/pull/88) to add a `--help` command that does not create a window to address this.
* That PR has been merged but is not yet part of a release.
* I requested that the project owner release a version of glslViewer with the change a [couple of days ago](https://github.com/patriciogonzalezvivo/glslViewer/issues/35#issuecomment-346576678).
* Until glslViewer is released with the `--help` command, there is no way for the Homebrew formula to have a test block that passes in Travis.

**Comment by dunn** [comment]
Thank you so much!

If you expect a new release in the next couple of days, we can wait for that.

**Comment by andystanton** [comment]
@dunn I've updated the PR with the latest version as released by @patriciogonzalezvivo today so it's ready to go!

**Comment by dunn** [comment]
Thank you for all your work! Merged as 71fe9808d5d6543329fd6c00a485a24c74edbfe8.

**Pull request closed without merging**
