### PR TITLE
rtx 1.8.0 (new formula)

### PR DESCRIPTION
**Pull request by jdx**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

See the project here: https://github.com/jdxcode/rtx

### CODE REVIEW

**Comment by jdxcode** [comment]
failing because the repo is too new, but it'll be ok next week. I'll mark this ready for review next week

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff
> We frown on authors submitting their own work unless it is very popular.

**Comment by jdxcode** [comment]
this is passing the checks now. I suppose I'll leave it for you to decide if this meets the bar for self-submission. Right now we're using a custom tap which is fine, but I feel some users may prefer to fetch this without using a custom tap.

**Review by carlocab — APPROVED** [review]
It shows up on our analytics, so it seems like there would be interest from enough of our users (presumably there will be more who would install this if it were in homebrew/core), so I'm ok to merge this.

**Review by SMillerDev — APPROVED** [review]

**Comment by jdxcode** [comment]
thanks for the help everyone!

What's the best way to handle updates? This is under active development so I'm making pretty frequent releases. I was thinking I could put `brew bump-formula-pr` into the github release action but not sure if that's something you guys encourage or not.

**Comment by carlocab** [comment]
You can try this action: https://github.com/dawidd6/action-homebrew-bump-formula

**Pull request closed without merging**
