### PR TITLE
libgcrypt 1.7.4

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by nijikon** [comment]
This is interesting actually :) Was hoping it will fail. Locally this happens:
```
==> make check
Making check in compat
make[1]: Nothing to be done for `check'.
Making check in mpi
make[1]: Nothing to be done for `check'.
Making check in cipher
make[1]: Nothing to be done for `check'.
Making check in random
make[1]: Nothing to be done for `check'.
Making check in src
make[1]: Nothing to be done for `check'.
Making check in doc
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-am
make[2]: Nothing to be done for `check-am'.
Making check in tests
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
version:1.7.4:
ciphers:arcfour:blowfish:cast5:des:aes:twofish:serpent:rfc2268:seed:camellia:idea:salsa20:gost28147:chacha20:
pubkeys:dsa:elgamal:rsa:ecc:
digests:crc:gostr3411-94::md4:md5:rmd160:sha1:sha256:sha512:sha3:tiger:whirlpool:stribog:
rnd-mod:linux:
cpu-arch:x86:
mpi-asm:generic/mpih-add1.c:generic/mpih-sub1.c:generic/mpih-mul1.c:generic/mpih-mul2.c:generic/mpih-mul3.c:generic/mpih-lshift.c:generic/mpih-rshift.c:
hwflist:intel-cpu:intel-fast-shld:intel-bmi2:intel-ssse3:intel-sse4.1:intel-pclmul:intel-aesni:intel-rdrand:intel-avx:intel-avx2:
fips-mode:n:n:
rng-type:standard:1:
PASS: version
PASS: mpitests
PASS: t-sexp
PASS: t-convert
PASS: t-mpi-bit
PASS: t-mpi-point
PASS: curves
PASS: t-lock
PASS: prime
/bin/sh: line 1: 73481 Segmentation fault: 11  GCRYPT_IN_REGRESSION_TEST=1 ${dir}$tst
FAIL: basic
PASS: keygen
PASS: pubkey
PASS: hmac
PASS: hashtest
PASS: t-kdf
PASS: keygrip
PASS: fips186-dsa
/bin/sh: line 1: 73632 Segmentation fault: 11  GCRYPT_IN_REGRESSION_TEST=1 ${dir}$tst
FAIL: aeswrap
PASS: pkcs1v2
PASS: random
PASS: dsa-rfc6979
      256 of 1026 tests done
      512 of 1026 tests done
      768 of 1026 tests done
      1024 of 1026 tests done
      1026 tests done
PASS: t-ed25519
      18 tests done
PASS: t-cv25519
Note: benchmark running in quick regression test mode.
MD5              0ms    10ms    10ms    10ms     0ms
SHA1             0ms    10ms    10ms    10ms     0ms
RIPEMD160       10ms     0ms    20ms     0ms    10ms
TIGER192         0ms     0ms    20ms    10ms     0ms
SHA256           0ms    10ms    20ms    10ms     0ms
SHA384           0ms    10ms    20ms    10ms     0ms
SHA512           0ms    10ms    10ms    10ms    10ms
SHA224           0ms    10ms    10ms    10ms    10ms
MD4              0ms     0ms    20ms    10ms     0ms
CRC32            0ms     0ms    10ms    10ms     0ms
CRC32RFC1510     0ms     0ms    10ms    10ms     0ms
CRC24RFC2440     0ms     0ms    10ms    10ms     0ms
WHIRLPOOL       10ms    10ms    30ms    10ms    10ms
TIGER            0ms     0ms    20ms    10ms     0ms
TIGER2           0ms     0ms    20ms     0ms    10ms
GOSTR3411_94    20ms    30ms    40ms    30ms    20ms
STRIBOG256      20ms    10ms    30ms    20ms    20ms
STRIBOG512      10ms    20ms    30ms    20ms    20ms
GOSTR3411_CP    20ms    30ms    40ms    30ms    20ms
SHA3-224        10ms     0ms    30ms    10ms    10ms
SHA3-256         0ms    10ms    30ms    10ms     0ms
SHA3-384        10ms    10ms    30ms    10ms    10ms
SHA3-512        10ms    10ms    30ms    20ms    10ms
SHAKE128         0ms    10ms    20ms    10ms
SHAKE256        10ms     0ms    30ms    10ms

HMAC_SHA256             10ms     0ms    10ms
HMAC_SHA224             10ms     0ms    10ms
HMAC_SHA512             10ms     0ms    10ms
HMAC_SHA384              0ms     0ms    10ms
HMAC_SHA1                0ms     0ms    10ms
HMAC_MD5                 0ms    10ms     0ms
HMAC_MD4                 0ms    10ms     0ms
HMAC_RIPEMD160           0ms    10ms     0ms
HMAC_TIGER               0ms    10ms     0ms
HMAC_WHIRLPOOL          20ms    10ms    10ms
HMAC_GOSTR3411_94       30ms    20ms    30ms
HMAC_STRIBOG256         20ms    10ms    20ms
HMAC_STRIBOG512         20ms    20ms    20ms
HMAC_SHA3_224           10ms     0ms    10ms
HMAC_SHA3_256           10ms     0ms    10ms
HMAC_SHA3_384           10ms    10ms    10ms
HMAC_SHA3_512           10ms    10ms    20ms
/bin/sh: line 1: 73751 Segmentation fault: 11  GCRYPT_IN_REGRESSION_TEST=1 ${dir}$tst
FAIL: benchmark
/bin/sh: line 1: 73769 Segmentation fault: 11  GCRYPT_IN_REGRESSION_TEST=1 ${dir}$tst
FAIL: bench-slope
SKIP: hashtest-256g
======================================
4 of 25 tests failed
(1 test was not run)
Please report to http://bugs.gnupg.org
======================================
make[2]: *** [check-TESTS] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
==> Sandbox log
Dec 10 11:57:54 sandboxd[145]: mdworker(60940) deny mach-lookup com.apple.bird.token (import fstype:hfs fsflag:480D000 flags:240000005E diag:0 isXCode:0 uti:com.apple.mail.emlx plugin:/Library/Spotlight/Mail.mdimporter - find suspect file using: sudo mdutil -t 122335765)

==> Formula
Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libgcrypt.rb
==> Configuration
HOMEBREW_VERSION: 1.1.2-53-gf02491180
ORIGIN: https://github.com/Homebrew/brew
HEAD: f02491180b199c370d1f930eb6fa50326e14348a
Last commit: 19 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2a5075beb38af040d059b617940de77099efcb03
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/n/.rvm/rubies/ruby-2.3.3/bin/ruby
Java: 1.8.0_45
macOS: 10.11.6-x86_64
Xcode: 8.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
MACOSX_DEPLOYMENT_TARGET: 10.11
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.11
HOMEBREW_VERBOSE: 1
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/libgpg-error/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: libgcrypt 1.7.4 did not build
Logs:
     /Users/n/Library/Logs/Homebrew/libgcrypt/00.options.out
     /Users/n/Library/Logs/Homebrew/libgcrypt/01.configure
     /Users/n/Library/Logs/Homebrew/libgcrypt/01.configure.cc
     /Users/n/Library/Logs/Homebrew/libgcrypt/02.make
     /Users/n/Library/Logs/Homebrew/libgcrypt/02.make.cc
     /Users/n/Library/Logs/Homebrew/libgcrypt/03.install_name_tool
     /Users/n/Library/Logs/Homebrew/libgcrypt/04.make
     /Users/n/Library/Logs/Homebrew/libgcrypt/build.sandbox.log
     /Users/n/Library/Logs/Homebrew/libgcrypt/config.log
READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
libgcrypt 1.7.4 https://github.com/Homebrew/homebrew-core/pull/7750
```

**Comment by ilovezfs** [comment]
Locally I bet that happens with 1.7.3 also, no?

**Comment by ilovezfs** [comment]
@nijikon yeah this happens locally for me too with 1.7.3 and 1.7.4. I first noticed it on November 13. It only happens if you --build-from-source but doesn't happen if you --build-bottle, so we can work around it with

```
diff --git a/Formula/libgcrypt.rb b/Formula/libgcrypt.rb
index 09f8393..db81359 100644
--- a/Formula/libgcrypt.rb
+++ b/Formula/libgcrypt.rb
@@ -25,6 +25,8 @@ class Libgcrypt < Formula
   end
 
   def install
+    ENV["HOMEBREW_OPTFLAGS"] = "-march=#{Hardware.oldest_cpu}" unless build.bottle?
+
     ENV.universal_binary if build.universal?
     # Temporary hack to get libgcrypt building on macOS 10.12.
```

**Comment by ilovezfs** [comment]
And it looks like even with the hack, the build will still fail with gcc6 interestingly.

What's the output of `brew ruby -e 'puts Hardware::CPU.family'` for you? This seems to affect skylake but not ivybridge, and I'm not sure about haswell and broadwell.

**Comment by ilovezfs** [comment]
@nijikon also do you mind removing https://github.com/polishgeeks/homebrew-core/blob/e7cb7a9baaee4c84dee9af247a2ba0200179c5ea/Formula/libgcrypt.rb#L36 so we can see if that's still needed?

**Review by ilovezfs — APPROVED** [review]

**Comment by adamliter** [comment]
Hi, I was wondering if any of you are having [this problem](http://apple.stackexchange.com/q/264350/85567) with `libgcrypt` 1.7.4. In brief, I'm no longer able to use `gpg2` with `--require-secmem`.

**Comment by DomT4** [comment]
Can reproduce the above FWIW. Seems likely to be the changes related to [this](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=libgcrypt.git;a=blobdiff;f=NEWS;h=722172a3e51c0514822ad81cf90f7de800fbae41;hp=0aaf8630acd5a53f31044804ac20cdefd492037d;hb=677ddf5bbd9c172a72607c7d5d7006907071c2cf;hpb=95bac312644ad45e486c94c2efd25d0748b9a20b).

**Comment by adamliter** [comment]
@DomT4 Glad someone else can reproduce it, too. I sent mail to the libgcrypt development list, but I don't think it's gone through yet because I'm not a subscriber to the mailing list. I really know absolutely nothing about what's going on here, though, so I have no idea what needs to be done.

**Comment by adamliter** [comment]
And after reading what you linked to, I guess that suggests this might not be a bug. 😝 I'm not really sure.

**Comment by DomT4** [comment]
Yeah, I'm not sure if it's intentional or just another case of _"Hey this behaves sanely on other BSD systems, I'm sure it will on macOS as well"_.

**Comment by adamliter** [comment]
I can report back if/when I hear anything from the mailing list.

**Comment by f3l1x** [comment]
```
$ gpg2 --version 
gpg (GnuPG) 2.0.30
libgcrypt 1.7.4
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA, RSA, ELG, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

Same warning guys. Installed today.

**Comment by ilovezfs** [comment]
It's deliberate: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=libgcrypt.git;a=patch;h=73dca02b9cc6d542af153c527190832f9c421ef3.

**Comment by whitslack** [comment]
Libgcrypt 1.7.4 completely breaks KWallet5, which starts [complaining](https://github.com/KDE/kwallet/blob/master/src/runtime/kwalletd/backend/kwalletbackend.cc#L135) "Can't get secure memory" and refuses to open wallet files. Downgrading to libgcrypt 1.7.3 restores correct functionality. Took me a while to figure this out.

**Comment by miccal** [comment]
You can disable the "Warning: using insecure memory!" message when using `gpg2` by following the instructions in the last paragraph [here](https://lists.gnupg.org/pipermail/gnupg-users/2015-December/054771.html).

**Comment by ilovezfs** [comment]
So apparently upstream expects us to explain this to every user in perpetuity, and expects everyone to add that entry to their config or stare at the warning? I'm not even sure where to start.

**Comment by DomT4** [comment]
Fixed by https://github.com/Homebrew/homebrew-core/pull/7893, apparently.

**Pull request closed without merging**
