### PR TITLE
swi-prolog: remove clang paths

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by danielnachun — DISMISSED** [review]

**Comment by Bo98** [comment]
This is a shim bypass and should be deleted entirely, with whatever problem it had with the shims fixed properly.

**Comment by danielnachun** [comment]
I checked the other 14 formulae that explicitly reference `/usr/bin/clang` or `/usr/bin/clang++` and it appears in most of these cases that it is to avoid shim references.  I removed the shim bypasses in this formula and bottled it locally and it doesn't complain about shims, so even if that avoiding shim references was the reason for adding this before, it doesn't seem to be now.

**Comment by Bo98** [comment]
> I checked the other 14 formulae that explicitly reference `/usr/bin/clang` or `/usr/bin/clang++` and it appears in most of these cases that it is to avoid shim references.

It's ok (and the correct solution) if it replaces some header file or something that's used only at runtime. This `CMAKE_C_COMPILER` is bypassing it at build time which should never be done.

**Comment by iMichka** [comment]
Looks like CI is happy when I remove the paths.

**Review by Bo98 — APPROVED** [review]

**Pull request merged**
