### PR TITLE
libcork 0.15.0 (new formula)

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by SMillerDev** [comment]
```
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/shared-test-ring-buffer.dir/test-ring-buffer.c.o  -o shared-test-ring-buffer ../src/libcork.16.0.1.dylib 
Undefined symbols for architecture x86_64:
  "__ck_assert_failed", referenced from:
      _test_ring_buffer_1 in test-ring-buffer.c.o
      _test_ring_buffer_2 in test-ring-buffer.c.o
  "__mark_point", referenced from:
      _test_ring_buffer_1 in test-ring-buffer.c.o
      _test_ring_buffer_2 in test-ring-buffer.c.o
  "__tcase_add_test", referenced from:
      _test_suite in test-ring-buffer.c.o
  "_srunner_create", referenced from:
      _main in test-ring-buffer.c.o
  "_srunner_free", referenced from:
      _main in test-ring-buffer.c.o
  "_srunner_ntests_failed", referenced from:
      _main in test-ring-buffer.c.o
  "_srunner_run_all", referenced from:
      _main in test-ring-buffer.c.o
  "_suite_add_tcase", referenced from:
      _test_suite in test-ring-buffer.c.o
  "_suite_create", referenced from:
      _test_suite in test-ring-buffer.c.o
  "_tcase_create", referenced from:
      _test_suite in test-ring-buffer.c.o
  "_tcase_fn_start", referenced from:
      _test_ring_buffer_1 in test-ring-buffer.c.o
      _test_ring_buffer_2 in test-ring-buffer.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tests/shared-test-ring-buffer] Error 1
make[1]: *** [tests/CMakeFiles/shared-test-ring-buffer.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by alebcay** [comment]
I am unable to reproduce the CI errors locally (in Mojave).

**Comment by fxcoudert** [comment]
Given it doesn't look actively maintained, and doesn't build on CI… should we close this @alebcay?

**Comment by alebcay** [comment]
Sounds like a good plan.

**Pull request closed without merging**
