### PR TITLE
Bash no longer depends on readline.

### PR DESCRIPTION
**Pull request by richardkmichael**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Don't we lose functionality if we don't link against readline?

**Comment by richardkmichael** [comment]
@fxcoudert What functionality do you mean?  bash compiles against a bundled readline, as I mentioned.  This is happening today, as the formula is now.  (Check with `otool -L $(type -P bash)`, it is not dynamically linked against homebrew installed readline.)

**Comment by richardkmichael** [comment]
FWIW, linking against readline is desired, then `--with-installed-readline` must be added back to configure.

The resulting bash file size will be about 25% smaller, but I guess no one cares about 250K, and perhaps bash prefer maintainers builtin readline usage.

```
 # bash built-in static, as is today.
$ ls -Ll $(type -P bash)
-r-xr-xr-x 1 testuser admin 949360 Apr  6 12:10 /usr/local/bin/bash

 # bash dynamic readline from homebrew.
$ ls -Ll $(type -P bash)
-r-xr-xr-x 1 testuser admin 746952 Apr  6 16:25 /usr/local/bin/bash
```

**Comment by ilovezfs** [comment]
The default changed in 4.4 and we didn't notice. Nice catch @richardkmichael!

Using the bundled readline is nicer for a login shell anyway so that it doesn't break when the readline dylib version changes, which led to people filing issues here.

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @richardkmichael! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
