### PR TITLE
daq 2.0.7

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> make install
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /private/tmp/daq-20200418-86480-16pqyia/daq-2.0.7/missing aclocal-1.15 -I m4
/private/tmp/daq-20200418-86480-16pqyia/daq-2.0.7/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [aclocal.m4] Error 127
```

**Comment by Bo98** [comment]
`depends_on "automake" => :build`

**Comment by Bo98** [comment]
Oh, it needs automake 1.15 specifically? Bit weird.

**Comment by Bo98** [comment]
Because we `autoreconf`, the patch doesn't work anymore.

**Comment by bayandin** [comment]
Thanks @Bo98!

If it's ok to keep this patch in the formula, then it's ready to merge, otherwise, I could move the patch to formula-patches (for me it looks more natural to keep it inlined)

**Comment by Bo98** [comment]
I think it's ok. The patch won't be needed when 3.0 is released anyway.

**Comment by chenrui333** [comment]
@bayandin, thanks the fix, I kind of like the inlined fix as well (the code is just side by side)!

**Review by bayandin — APPROVED** [review]

**Pull request closed without merging**
