### PR TITLE
apache-arrow, apache-arrow-glib 6.0.0

### PR DESCRIPTION
**Pull request by daipom**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by daipom** [comment]
There seems to be some kind of problem around here.

```
 /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libgrpc++.so.1.41: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
collect2: error: ld returned 1 exit status
```

I will check it.

**Comment by carlocab** [comment]
> There seems to be some kind of problem around here.
> 
> ```
>  /home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libgrpc++.so.1.41: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
> collect2: error: ld returned 1 exit status
> ```
> 
> I will check it.

I think this will be fixed by adding
```ruby
on_linux do
  depends_on "gcc"
end

fails_with gcc: "5"
```
to `apache-arrow`.

Can you also check if `apache-arrow` still needs LLVM 12?

**Comment by kou** [comment]
Apache Arrow 6.0.0 supports LLVM 13.

**Review by carlocab — APPROVED** [review]
Thanks @daipom, @kou!

**Comment by kou** [comment]
Thanks!

**Comment by daipom** [comment]
Thank you very much!

**Pull request closed without merging**
