### PR TITLE
zeek 3.0.0 (new formula)

### PR DESCRIPTION
**Pull request by dominiklohmann**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`bro` has been renamed to `zeek` for version 3+. The formulas can coexist as far as I can tell.

### CODE REVIEW

**Comment by dominiklohmann** [comment]
> * Dependency 'bison' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.

I have tried this, but we need `bison>=2.5`, and macOS ships with `bison==2.3`. I have decided to revert back to `depends_on`.

**Comment by dominiklohmann** [comment]
There's a conflict in this with `caf`, because `zeek` / `bro` export a custom version of `caf`.

Any advice?

**Comment by Bo98** [comment]
Try depend on `caf and use `--with-caf=#{Formula["caf"].opt_prefix}`.

**Comment by dominiklohmann** [comment]
> Try depend on `caf` and use `--with-caf=#{Formula["caf"].opt_prefix}`.

This really is an upstream issue. `zeek` then has a version mismatch for `broker` (not available on Homebrew), which—yet again—uses its own version of `caf`.

**Comment by Bo98** [comment]
Interesting, I expected it to just pass on`CAF_ROOT_DIR` (`—with-caf`) to broker.

Sounds like a bit of a mess if the option doesn’t really work properly.

**Comment by Bo98** [comment]
Just tried it out on `bro` and it passes it to `broker` just fine, but `caf` is missing a required OpenSSL module. It might be worth adding that so that we can make `bro`/`zeek` depend on `caf`. Let's see how #46735 turns out.

**Comment by EricFromCanada** [comment]
Instead of adding a new (duplicate) formula, `bro` should be renamed to `zeek` much like #37587, once #46782 is merged.

**Comment by chenrui333** [comment]
I think I messed up a little bit (as I was under wrong impression), I will close this PR in favor of renaming the formula in a new PR.

Thanks @dominiklohmann for bringing the formula renaming thing into our attention!! Feel free to submit new PRs!

**Comment by dominiklohmann** [comment]
@chenrui333 thanks for taking over—sorry I didn't reply sooner, had to push this further down my backlog.

**Pull request closed without merging**
