### PR TITLE
libdrm 2.4.117

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  meson.build:56:27: ERROR: <PythonExternalProgram 'python3' -> ['/home/linuxbrew/.linuxbrew/opt/python@3.12/bin/python3.12']> is not a valid python or it is missing distutils
```

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/151906

**Comment by SMillerDev** [comment]
Meson was merged, here we go again

**Comment by chenrui333** [comment]
```
brew linkage --test easy-tag
brew linkage --test gnumeric
brew linkage --test mesa
```

- easy-tag, need rev bump per libid3tag
- gnumeric revision bump per perl upgrade is already handled
- mesa, need revision bump per libdrm upgrade

https://github.com/Homebrew/homebrew-core/actions/runs/6605187639/job/17940171273?pr=151896

**Comment by chenrui333** [comment]
mesa build issue `meson.build:1704:6: ERROR: Dependency "libdrm_intel" not found, tried pkgconfig`

**Comment by chenrui333** [comment]
mesa needs to be upgraded to `23.2.1`

**Pull request closed without merging**
