### PR TITLE
mikutter: Fix gem dependencies.

### PR DESCRIPTION
**Pull request by midchildan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
What are the changes based on? I notice some go up and some go down. Thanks!

**Comment by midchildan** [comment]
It's based on a script I wrote. -> https://github.com/midchildan/resona

**Comment by ilovezfs** [comment]
@midchildan nice work!

**Comment by ilovezfs** [comment]
@midchildan Thanks for the PR! Shipped.

**Pull request closed without merging**
