### PR TITLE
hugo 0.69.0

### PR DESCRIPTION
**Pull request by peaceiris**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DirtyF** [comment]
What about updating the other SHA for macOS?
```
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "hugo"
Download failed: https://homebrew.bintray.com/bottles/hugo-0.69.0.catalina.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

**Comment by peaceiris** [comment]
After merging this Pull Request, you can do `wget https://homebrew.bintray.com/bottles/hugo-0.69.0.catalina.bottle.tar.gz`

**Comment by SMillerDev** [comment]
It needs to be merged before you can install the bottles.

**Comment by SMillerDev** [comment]
Thanks @peaceiris! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
