### PR TITLE
envoy 1.24.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dio** [comment]
This is interesting. The test caught by [an error](https://github.com/Homebrew/homebrew-core/actions/runs/3277236248/jobs/5394354433#step:6:1374) since: `[-Werror,-Wrange-loop-analysis]`.

<details>

external/v8/src/compiler/js-native-context-specialization.cc:2333:23: error: loop variable 'map' of type 'const v8::internal::compiler::MapRef' creates a copy from type 'const v8::internal::compiler::MapRef' [-Werror,-Wrange-loop-analysis]
      for (const MapRef map : access_info.lookup_start_object_maps()) {
                        ^
  external/v8/src/compiler/js-native-context-specialization.cc:2333:10: note: use reference type 'const v8::internal::compiler::MapRef &' to prevent copying
      for (const MapRef map : access_info.lookup_start_object_maps()) {
           ^~~~~~~~~~~~~~~~~~
                        &
  1 error generated.

</details>

This is interesting since the previous version (1.23.1) depends on the same v8 version (10.4.132.18). Do we have a different compiler version now? (probably this one is clang 12?)

We have two options:

1. Submit another patch to fix v8 (envoy patches v8) [^1]
2. Add a line in .bazelrc: `build:macos --copt='-Wno-error=range-loop-analysis'`


[^1] the patch:
```
diff --git a/bazel/v8.patch b/bazel/v8.patch
index 03c849156a..1b7a8f27b1 100644
--- a/bazel/v8.patch
+++ b/bazel/v8.patch
@@ -363,3 +363,16 @@ index 131ff9614e..6455f8757d 100644
      char filename[] = "/tmp/v8_tmp_file_for_testing_XXXXXX";
      fd = mkstemp(filename);
      if (fd != -1) CHECK_EQ(0, unlink(filename));
+diff --git a/src/compiler/js-native-context-specialization.cc b/src/compiler/js-native-context-specialization.cc
+index 729d8ac99f..c1b0f7e0ba 100644
+--- a/src/compiler/js-native-context-specialization.cc
++++ b/src/compiler/js-native-context-specialization.cc
+@@ -2330,7 +2330,7 @@ Node* JSNativeContextSpecialization::InlinePropertyGetterCall(
+ 
+   if (access_info.IsDictionaryProtoAccessorConstant()) {
+     // For fast mode holders we recorded dependencies in BuildPropertyLoad.
+-    for (const MapRef map : access_info.lookup_start_object_maps()) {
++    for (const MapRef& map : access_info.lookup_start_object_maps()) {
+       dependencies()->DependOnConstantInDictionaryPrototypeChain(
+           map, access_info.name(), constant, PropertyKind::kAccessor);
+     }

```

**Comment by dio** [comment]
Ah, sorry, we re-enabled wasm support with the v8 engine (default). Hence, this happens. 

I vote for: creating `user.bazelrc` with the following content:

```
build:macos --copt='-Wno-error=range-loop-analysis'
```

Since it will be cleaner and when we do `envoy --version` it will print "Clean" instead of "Modified".

**Comment by dio** [comment]
Also, `1.24.0` https://github.com/envoyproxy/envoy/pull/23561 is happening.

**Comment by chenrui333** [comment]
> Also, `1.24.0` [envoyproxy/envoy#23561](https://github.com/envoyproxy/envoy/pull/23561) is happening.

yeah, gonna try that.

**Comment by dio** [comment]
@chenrui333 I have successfully tested the following formula on Catalina, Monterey, and Ventura locally:

- https://gist.github.com/dio/9cf30c3e20abdf8368d7cf8ac7b75964

Feel free to modify this PR with it. Or please let me know if you want me to submit another PR.

Also, seems like we need to move the "versioned" `envoy@1.18` one (to 1.23.2 (?)) after 1.24.0 is successfully built as "stable" since the only reason we have that was wasm support (1.24.0 has wasm support).

Thank you!

**Comment by dio** [comment]
@chenrui333 sorry, do you want to modify this PR, or I can submit another one? Thank you!

**Comment by chenrui333** [comment]
> @chenrui333 sorry, do you want to modify this PR, or I can submit another one? Thank you!

yeah, sounds good to me (always feel free to submit a new one :) )

**Pull request closed without merging**
