### PR TITLE
shyaml 0.5.0

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zmwangx** [comment]
shyaml 0.5.0 is not on PyPI yet.

I'm switching to git here because autogen.sh (invoked by setuptools) now requires git to
generate version info. Alternatively, we can wait for a PyPI tarball which wouldn't have this requirement.

**Comment by ilovezfs** [comment]
now on pypi

**Comment by zmwangx** [comment]
```
                                                                                
                                                                                
                                                  ;ldddddddooc.       ,ldddddxxd
                                                 .oO00OOOO00KK.       o0000000KK
                                                 .oO00OOOOO0K0,      .oO000000KK
                                                 .okOOOOOOOO0O.       lO00OO0000
                                                 .oO0OOOOOO00O.       lO00000000
                                                 .okOOOOOOOOOk.       lkOOO00000
                                          ........:,cllc,lll;c........coc:ood:cd
                                         .','','.,:;cllc;lll:c,';,',;,lolcdddlld
                                         ...lc....cc....lc...'lc...,oc...,dl...c
                                           .,,.  .,,.  .,,.. .,,....;,...':;...,
                                        ........................................
    .. ..   .    .   .                     .,,.  .,,.  .,,.  .;,.  .;,.  .:;...,
   .c,'cc'';c,'',c,',:;'                   .c:.  .cc.  .c:.  .c:.. 'l:...,oc...:
    ,;;;;,,,''''''''..;oxl'           .................................'''''''''
    .............  ......;ldl;;:::::;,'',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;
     ............     ......''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;:::::
      ..............  ..........................................................
      .................................... cKK; .oK0,..xKO'..dX0,..xX0,..xXK;.;0
        ....................................''....,'....,.....,'....,'...';,...,
         .......................................................................
          'cllooddddddddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxx
           .cdxxkOOO000000000000000000000000000000000000000000000KKKKKKKKKKKKKKK
             ,ldxxkkOO00000000000000000000000000000000000000000K0KKKKKKKKKKKKKKK
               ,lddxkkOOO00000000000000000000000000000000000000KKKKKKKKKKKKKKKKK
                 'coddxkkOOOO00000000000000000000000000000000000000000000KKKKKKK
                   .,cooddxxxkkkkkkkkkkkOkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOO0000000
                       ..',;:ccllooodddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                                                                                
```

**Comment by JCount** [comment]
@zmwangx A 🚢 as you requested. 😄

**Pull request closed without merging**
