### PR TITLE
Update for apache-geode 1.10.0

### PR DESCRIPTION
**Pull request by dickcav**
- [ x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [no ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ idk] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [idk, I'm on Linux ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Review by Moisan — CHANGES_REQUESTED** [review]
`geode` now supports java >= 1.8 since [this issue](https://issues.apache.org/jira/browse/GEODE-3) has been resolved. Could you remove the comment regarding the issue and replace the java dependency by the following line please?
```
depends_on :java => "1.8+"
```

**Comment by dickcav** [comment]
submitting new PR to replace this one.

**Pull request closed without merging**
