### PR TITLE
khiva 0.5.0 (new formula)

### PR DESCRIPTION
**Pull request by ankane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Efficient algorithms to analyze time series data.

Notes:
- Uses Git URL since it has a submodule that's needed to build

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]
lgtm

**Comment by gromgit** [comment]
> * Uses Git URL since it has a submodule that's needed to build

Is it version-pinned? If not, then every build potentially pulls down a different codebase.

**Comment by ankane** [comment]
Git submodules are always pinned to a specific commit.

**Comment by chenrui333** [comment]
@ankane, thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by ankane** [comment]
Thanks @chenrui333!

**Pull request closed without merging**
