### PR TITLE
taisei 1.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
needs rewrite with meson, which then fails

```
==> ninja install
[1/5] Generating macOS property list with a custom command.
[2/5] Generating version information with a custom command.
[2/3] Installing files.
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open input file: /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/MacOS/dylibs/libSDL2-2.0.0.dylib for writing (Permission denied)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't lseek to offset: 0 in file: /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/MacOS/dylibs/libSDL2-2.0.0.dylib for writing (Bad file descriptor)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't write new headers in file: /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/MacOS/dylibs/libSDL2-2.0.0.dylib (Bad file descriptor)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't close written on input file: /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/MacOS/dylibs/libSDL2-2.0.0.dylib (Bad file descriptor)
otool -L /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/MacOS/Taisei
install_name_tool /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/MacOS/Taisei -change /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib @executable_path/dylibs/libSDL2-2.0.0.dylib
Installing /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib as /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/MacOS/dylibs/libSDL2-2.0.0.dylib
otool -L /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/MacOS/dylibs/libSDL2-2.0.0.dylib
install_name_tool /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/MacOS/dylibs/libSDL2-2.0.0.dylib -change /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib @executable_path/dylibs/libSDL2-2.0.0.dylib
Traceback (most recent call last):
  File "/private/tmp/taisei-20180126-94329-1kda40j/scripts/macos-install-dylibs.py", line 78, in <module>
    new_files = fix_libs(exe_path)
  File "/private/tmp/taisei-20180126-94329-1kda40j/scripts/macos-install-dylibs.py", line 75, in fix_libs
    fix(opath)
  File "/private/tmp/taisei-20180126-94329-1kda40j/scripts/macos-install-dylibs.py", line 70, in fix
    fix(dst_lib_path)
  File "/private/tmp/taisei-20180126-94329-1kda40j/scripts/macos-install-dylibs.py", line 63, in fix
    install_name_tool(path, '-change', lib, '@executable_path/dylibs/{0}'.format(dst_lib_path.name))
  File "/private/tmp/taisei-20180126-94329-1kda40j/scripts/macos-install-dylibs.py", line 37, in func
    return subprocess.check_output(cmd, universal_newlines=True)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['install_name_tool', PosixPath('/usr/local/Cellar/taisei/1.2/Taisei.app/Contents/MacOS/dylibs/libSDL2-2.0.0.dylib'), '-change', '/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib', '@executable_path/dylibs/libSDL2-2.0.0.dylib']' returned non-zero exit status 1.
Installing src/Taisei to /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/MacOS/Taisei
Stripping target 'src/Taisei'
Installing resources/00-taisei.zip to /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/Resources/data/00-taisei.zip
Installing misc/Info.plist to /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/Info.plist
Installing doc/README.txt to /usr/local/Cellar/taisei/1.2/README.txt
Installing doc/STORY.txt to /usr/local/Cellar/taisei/1.2/STORY.txt
Installing doc/ENVIRON.html to /usr/local/Cellar/taisei/1.2/ENVIRON.html
Installing doc/GAME.html to /usr/local/Cellar/taisei/1.2/GAME.html
Installing /private/tmp/taisei-20180126-94329-1kda40j/COPYING to /usr/local/Cellar/taisei/1.2
Installing /private/tmp/taisei-20180126-94329-1kda40j/misc/gamecontrollerdb/gamecontrollerdb.txt to /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/Resources/data
Installing /private/tmp/taisei-20180126-94329-1kda40j/misc/icons/Taisei.icns to /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/Resources
Running custom install script '/usr/local/opt/python3/bin/python3.6 /private/tmp/taisei-20180126-94329-1kda40j/scripts/macos-install-dylibs.py   '
Failed to run install script '/usr/local/opt/python3/bin/python3.6 /private/tmp/taisei-20180126-94329-1kda40j/scripts/macos-install-dylibs.py   '
FAILED: meson-install 
/usr/local/opt/python3/bin/python3.6 /usr/local/Cellar/meson/0.44.0_1/libexec/bin/meson --internal install /private/tmp/taisei-20180126-94329-1kda40j/build/meson-private/install.dat
ninja: build stopped: subcommand failed.
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: ninja install
```

**Comment by Akaricchi** [comment]
Should be installed with `DESTDIR` set to a user-writable prefix first, then copied to the real prefix.

**Comment by mistydemeo** [comment]
Fixed by installing with `-Dmacos_bundle=false`.

**Comment by Akaricchi** [comment]
@mistydemeo that is strange, then. Any idea why else could `install_name_tool` fail with a permission error here?

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open input file: /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/MacOS/dylibs/libSDL2-2.0.0.dylib for writing (Permission denied)
```

I'd like to fix it upstream if I screwed this one up somehow.

**Comment by mistydemeo** [comment]
I suspect it's probably in this step:

```
Installing /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib as /usr/local/Cellar/taisei/1.2/Taisei.app/Contents/MacOS/dylibs/libSDL2-2.0.0.dylib
```

Does that step change permissions when it copies it? While the Homebrew prefix is user-owned (and hence user-writable), the files are set to `-r--r--r--` during the install stage as a form of soft write-protection. Since they're user-owned, and so's the destination path, the user would have permission to ensure they're `+w` before trying to alter them.

**Comment by ilovezfs** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/23809

**Pull request closed without merging**
