### PR TITLE
Update formulae to use full_index patches

### PR DESCRIPTION
**Pull request by mistydemeo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?

-----

Companion to Homebrew/brew#2837, which will look for these URLs in audit.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@misty one commit per formula would be preferred.

**Comment by mistydemeo** [comment]
@ilovezfs Done.

**Comment by ilovezfs** [comment]
Thanks!

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Merged! Thanks @mistydemeo!

**Pull request merged**
