### PR TITLE
boost*: move from bintray

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
See #74335

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by Bo98** [comment]
Is there any difference at all between the source archive and the Git repo? Sometimes source archives add a version file or something so it's important to double check.

As for upstream's stand on Bintray: they will be providing an alternative. 1.76 is going to be released within the next couple weeks, so it's probably then that they'll be migrating.

**Comment by carlocab** [comment]
```
/Users/brew/actions-runner-x86_64/_work/_temp/d2a9ace3-1578-46d8-853f-4666cd5f0941.sh: line 3:  8532 Illegal instruction: 4  brew test-bot --only-formulae
```

**Comment by carlocab** [comment]
Boost has a migration plan. They just haven't announced yet.

https://github.com/boostorg/boost/issues/499

**Comment by Pesa** [comment]
> Boost has a migration plan. They just haven't announced yet.
> 
> [boostorg/boost#499](https://github.com/boostorg/boost/issues/499)

https://lists.boost.org/Archives/boost/2021/04/251436.php

**Comment by carlocab** [comment]
Migrating everything but `boost-python` in #75459 and #75461.

However, it seems like Boost is sticking the JFrog, so I'd guess their Bintray URLs are going to be redirected anyway, maybe.

**Pull request closed without merging**
