### PR TITLE
dar 2.4.22

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍

**Comment by ilovezfs** [comment]
BTW if anyone has downloaded Xcode 8, dar 2.5 probably works now as `thread_local` is supposedly supported. I wonder if we have any way of dealing with that in the formula since 2.5 will only be available to 10.12 (and probably 10.11).

**Comment by DomT4** [comment]
`depends_on :macos => :el_capitan` when the time comes.

**Comment by ilovezfs** [comment]
Right, but 2.4* won't actually be deprecated at that point.

**Comment by DomT4** [comment]
Either we don't update it, or we cap it above the last supported build system. That's the choice here, really.

**Comment by ilovezfs** [comment]
Yeah, pretty awful :)

**Comment by DomT4** [comment]
Come September we'll only support 10.10 - 10.12 anyway, so that'll only be one officially supported OS X release you can't install it on. The alternative would be to add the more incompatible version as a `devel do` block but that smells hackish.

**Comment by ilovezfs** [comment]
Not sure what demand looks like, but since we're talking about archives, a homebrew/versions `dar24` maybe warranted at that point.

**Comment by DomT4** [comment]
Prior to your version update today, 10 bottled downloads in the last 30 days.

**Comment by ilovezfs** [comment]
It's selling like hotcakes.

**Comment by DomT4** [comment]
204 in the last year, which is, er, mildly better. 3 days of that, including today, account for 40 of that number though.

**Pull request closed without merging**
