### PR TITLE
hasura-cli 2.10.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by iMichka — CHANGES_REQUESTED** [review]
Not marked as stable release yet on GitHub

**Comment by chenrui333** [comment]
Actually this might be a tag promotion issue on their end.

**Review by SMillerDev — DISMISSED** [review]

**Review by iMichka — DISMISSED** [review]
Looks good now

**Comment by branchvincent** [comment]
Merged in #108247

**Pull request closed without merging**
