### PR TITLE
ruby: rubygems 2.7.6

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alex** [comment]
Jenkins failures don't appear to be caused by this patch.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by alex** [comment]
Hmm, not sure if these test failures are relevant or not.

**Comment by ilovezfs** [comment]
Yup it's being caused by this PR.

**Comment by alex** [comment]
I think this is caused because rubygems 2.7.6 upgrades the version of bundler that it includes, but I'm not clear why.

**Comment by ilovezfs** [comment]
@alex there's probably a better fix but this should work.

**Comment by alex** [comment]
👍

**Comment by ilovezfs** [comment]
Thanks @alex!

**Comment by alex** [comment]
Thank you!

**Pull request closed without merging**
