### PR TITLE
oras 1.0.0-rc.1

### PR DESCRIPTION
**Pull request by qweeah**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by qweeah** [comment]
@chenrui333 Can you help review this PR? We want to release this RC version to Homebrew. Thanks in advance.

**Comment by p-linnane** [comment]
What do you need help with? Looks like everything is passing on CI. 
Once this is the latest stable we can update to it. We do not update to RC or beta versions from stable.

**Comment by qweeah** [comment]
@p-linnane Thanks for the info. It does make sense since Homebrew only keep one built version.

**Comment by SMillerDev** [comment]
If upstream says it's stable we ship it. If upstream says it's a release candidate we don't.

**Pull request closed without merging**
