### PR TITLE
kubernetes-helm 2.4.1

### PR DESCRIPTION
**Pull request by cblecker**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cblecker** [comment]
unrelated style failure due to inability to download rubocop

**Comment by ilovezfs** [comment]
What's the rationale for a new option as opposed to always including tiller?

**Comment by cblecker** [comment]
I was on the fence about this, as tiller is very helpful in certain circumstances.. but I opted for the option because tiller isn't distributed with the official helm binaries. However, it's helpful in certain circumstances to run tiller on your local system for things like testing.

Ultimately, I could just remove the option and put in the the bottle if you think that's worth it. I guess it wouldn't harm things to include it.

**Comment by dimm0** [comment]
Current helm version is broken: https://github.com/kubernetes/helm/issues/2376

**Comment by cblecker** [comment]
Ah, thanks for the heads up @dimm0.

>> homebrew maintainers: please hold on merging. thank you!

**Comment by cblecker** [comment]
@ilovezfs I've removed the option, and am just going to add tiller to the bottle. I've also skipped 2.4.0 as it had a critical bug that merited the release of 2.4.1

**Comment by dimm0** [comment]
Interesting, I also had problems with vbom.ml/util when was trying to build helm... Eventually it started working

**Comment by cblecker** [comment]
CI seems to have an issue pulling `bitbucket.org/ww/goautoneg`. I can pull it locally, including after clearing my glide cache. `brew install --build-bottle Formula/kubernetes-helm.rb` also works.

**Comment by databus23** [comment]
https://github.com/kubernetes/helm/issues/2343

Helm 2.4.0 reintroduced mercurial as a build dependency. Maybe this is missing?

**Comment by cblecker** [comment]
Line 16:
`depends_on :hg => :build`

mercurial is already a build-time dependency in the formula :)

**Comment by ilovezfs** [comment]
For me it's getting stuck on `[INFO]	--> Fetching k8s.io/kubernetes.` :confused:

**Comment by cblecker** [comment]
I tried rebasing, and it's still erroring in the same place via CI:
```
�[0;33m[WARN]	�[mUnable to checkout bitbucket.org/ww/goautoneg
�[0;31m[ERROR]	�[mUpdate failed for bitbucket.org/ww/goautoneg: Unable to get repository
```

However, I've built it locally without error. Is there a connectivity issue with CI?

@ilovezfs: the kubernetes repo is very large (my working copy is over 162Mb of source code, and a git tree of 438Mb).. is it possible it's just stalling to download for you locally? INFO messages from glide shouldn't be an issue.

**Comment by ilovezfs** [comment]
@cblecker this was broken by https://github.com/Homebrew/homebrew-test-bot/pull/72.

CC @MikeMcQuaid

**Comment by cblecker** [comment]
Awesome! Thanks for tracking that down @ilovezfs!

**Comment by ilovezfs** [comment]
@cblecker you're welcome!

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Shipped! Thanks @cblecker

**Pull request closed without merging**
