### PR TITLE
ccache: Enable link-time-optimization and run test suite

### PR DESCRIPTION
**Pull request by gjasny**
Compiling ccache with LTO reduces the startup time by 50%.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by gjasny** [comment]
@carlocab This is the follow-up PR to #83628.

**Comment by SMillerDev** [comment]
We don't want to run testsuites of software unless it's something like encryption software. We expect upstream to run their unittests and we just test the brew install.

**Comment by bernhardkaindl** [comment]
> I know we normally don't like test suites, but I'm inclined to give this one a pass. It doesn't take too long, and we don't actually test this formula properly since doing so would be too complicated. It probably entails compiling something non-trivial, changing some of the code, and then compiling it again.

Absolutely true, enabling LTO is in another universe of possible issues than say, a php developer who meryely writes in a script language would be used to:

When enabling LTO, this does not mean just "Link time optimisations", but actually, the entire program becomes one compilation unit. The sort of bugs which can show up then is not something, in which the application developer has a lot of confidence, it's mostly a architecture thing.

Sure, some shady applications do things like initializing global variables from the .init section of an EFL object file, which broke at least on one case in the past when I enabled LTO. But when the application is programmed in a clean way, testing if an LTO build worked correctly is different from the ususal: Yeah it can do thing A, hence it must work fine.

My experience with LTO on different processor architecures is the following:
LTO Bug can show up where you least expect them, it  depends to 100% on the CPU architecture.

What this boils down to is that testing LTO is actually that the compiler didn't miscompile stuff.

Over the years, the confidence in gcc LTO-generated-code correctness rose. 

With gcc-7, LTO on x86 and x86_64 was rather good, but there were still some problems with things like symbol versioning. gcc-10 introduced a new mechanism for symbol versioning which works with LTO, and with Fedora 33, Red Hat was able to enable LTO for compilation of RPMs by default, at least for x86_64.

So, for x86_64, when we compile with gcc-10 or newer, we can have high confidence that LTO won't cause any regressions.

Nonetheless, when enabling LTO, expecially when we build for architectures like aarch64, it would likely be a good idea to still run the whole test suite of have tests which cover most of the generated machine code.

As said by someone previously, users typically don't run "brew test <formula>", but when a dev, homebrew dev or system engineer runs a test, he wants to know that the test actually exercises the testee, not just ensure that no files are missing (which is all what a usual brew test does). And especially with LTO, I'd recommend having the test done.

If some tests only run in the "do install" step, that's fine too: It covers the code paths and this is what counts on a test: To know that the code generated by the compiler and linked by the linker works as fully as we can know.

**Comment by gjasny** [comment]
I also tried copying the ccache `test` directory to `pkgshare` and wire up its `run` script within the `test`. But I hit more homebrew specific shenanigans within the test environment.

At the moment the problems seem to outweigh the benefits.

**Comment by bernhardkaindl** [comment]
Well, this is a perfect example where just running the normal test suite like it is designed usually during the package build is easy and just makes sense.

I urge Homebrew devs to strongy reconsider dropping the policy of not running tests during the build.

**Pull request closed without merging**
