### PR TITLE
krakend 2.0.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Need to migrate test's v2 (`krakend 1.x`) configs to v3 (`krakend 2.x`) https://www.krakend.io/docs/configuration/migrating/

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
Bottle upload [failed](https://github.com/Homebrew/homebrew-core/runs/5492058093?check_suite_focus=true#step:10:129) with
```
==> Uploading krakend--2.0.0.arm64_big_sur.bottle.tar.gz
==> Uploading krakend--2.0.0.catalina.bottle.tar.gz
==> Uploading krakend--2.0.0.x86_64_linux.bottle.tar.gz
==> Uploading krakend--2.0.0.big_sur.bottle.tar.gz
==> Uploading krakend--2.0.0.arm64_monterey.bottle.tar.gz
Error: invalid compressed data -- crc error
```
@Homebrew/brew does this look familiar to anyone? Rerunning does not help.

**Comment by cho-m** [comment]
I think we are going to have to re-run CI. Looks like a corrupt tarball.

[CI output](https://github.com/Homebrew/homebrew-core/runs/5490383393?check_suite_focus=true#step:9:40)
```
  bottle do
    sha256 cellar: :any_skip_relocation, arm64_monterey: "e15432c07387e5e8baa11d98b2c0af7218f9713a80d165857ae482f2f28c4d7f"
  end
```

Local download of bottles:
```console
❯ sha256sum krakend--2.0.0.arm64_monterey.bottle.tar.gz
0a96d8e53ee51ab683f1914065ea827e588af294483a5cbed9a7db2d1cc2515b  krakend--2.0.0.arm64_monterey.bottle.tar.gz
```

**Comment by carlocab** [comment]
Ok, let's rerun the build.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
