### PR TITLE
clingo: add necessary link_overwrites

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Ref: https://github.com/Homebrew/homebrew-core/pull/20281#issuecomment-347064707

### CODE REVIEW

**Comment by JCount** [comment]
@DomT4 Makes sense something like this would be needed, given how the formulae are not actually being migrated in the usual way. I somehow overlooked it, I suppose.

I'll merge this for now, so that installs work, but a better long-term solution _could_ be possible.

**Comment by JCount** [comment]
Thanks @DomT4 for catching this one. 😸

**Comment by DomT4** [comment]
> I somehow overlooked it, I suppose.

It's not something most people know about, to be honest, and certainly not something people routinely remember to check for. I remember Xu discussing the original implementation back in 2015 & I looked over the `clingo` PR very briefly and didn't remember the linking would be an issue until it happened, so 🙈.

> but a better long-term solution could be possible.

Various options have been discussed on this but nothing decided, as far as I know. As an absolute minimum it doesn't seem unreasonable to essentially transform explicitly deleted formulae into `keg_only` installations. We could do that pretty easily, and it's not _overly_ invasive.

**Comment by ilovezfs** [comment]
Or leave it to users to handle.

**Comment by DomT4** [comment]
That was pretty comprehensively rejected by Mike as an idea in 2015, hence the current dance.

**Comment by ilovezfs** [comment]
In any case, I think these should be removed at the next version upgrade or something like that. This is pretty gross.

**Comment by DomT4** [comment]
Yes, I don't particularly disagree with that. I've suggested to you in the past some of the older ones can certainly be removed by now, given to run into problems with those formulae you'd have had to avoid upgrading anything for half a year or more.

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:Formula joe$ ag link_overwrite
clingo.rb
22:  link_overwrite "bin/clasp"
23:  link_overwrite "bin/clingo"
24:  link_overwrite "bin/gringo"
25:  link_overwrite "bin/lpconvert"
26:  link_overwrite "bin/reify"

glib-networking.rb
20:  link_overwrite "lib/gio/modules"

groonga.rb
50:  link_overwrite "lib/groonga/plugins/normalizers/"
51:  link_overwrite "share/doc/groonga-normalizer-mysql/"
52:  link_overwrite "lib/pkgconfig/groonga-normalizer-mysql.pc"

gst-python.rb
21:  link_overwrite "lib/python2.7/site-packages/gi/overrides"

mecab-ipadic.rb
25:  link_overwrite "lib/mecab/dic"

mecab-unidic-extended.rb
17:  link_overwrite "lib/mecab/dic"

mecab-jumandic.rb
23:  link_overwrite "lib/mecab/dic"

mecab-unidic.rb
20:  link_overwrite "lib/mecab/dic"

mono.rb
18:  link_overwrite "bin/fsharpi"
19:  link_overwrite "bin/fsharpiAnyCpu"
20:  link_overwrite "bin/fsharpc"
21:  link_overwrite "bin/fssrgen"
22:  link_overwrite "lib/mono"
23:  link_overwrite "lib/cli"
```
So I think this goes in the "too rare to care" bucket in terms of how much I'm going to be thinking about it. lol

**Pull request closed without merging**
