### PR TITLE
Sqlite-family 3.19.1

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks for cleaning up after me.

**Comment by DomT4** [comment]
No worries! These usually get forgotten. To be honest part of me wishes we just had a `sqlite-misc` formula rather than carry round so many copies, but eh.

**Comment by DomT4** [comment]
Hold off on this. They just cut `3.19.1` so I'll bump again & kick `sqlite` here as well.

**Review by ilovezfs — DISMISSED** [review]
what he said

**Comment by DomT4** [comment]
Should be alright now, providing CI is happy.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@DomT4 don't worry about Mesos https://github.com/Homebrew/homebrew-core/pull/13876

**Comment by ilovezfs** [comment]
Thanks Dom

:sparkler:

**Comment by DomT4** [comment]
Thanks for merging 🍻

**Pull request closed without merging**
