### PR TITLE
pillow: use Python's `libexec/"bin"`

### PR DESCRIPTION
**Pull request by carlocab**
Needed for #107517.

### CODE REVIEW

**Comment by carlocab** [comment]
It seems like this can't find any of the required libraries. Smells like a `setuptools` regression. CC @Bo98 @cho-m in case you have ideas here.

**Comment by cho-m** [comment]
Looks like 1 regression fix was merged in 63.4.0 for finding libraries:  https://github.com/pypa/setuptools/pull/3480. Sounds related.

**Comment by carlocab** [comment]
> Looks like 1 regression fix was merged in 63.4.0 for finding libraries: [pypa/setuptools#3480](https://github.com/pypa/setuptools/pull/3480). Sounds related. Probably worth trying build with a newer copy of `setuptools >= 63.4.0`.

I plan to update to the latest `setuptools` at #107517. We should probably just fix the Python references in the `test` in the meantime since we can't build this for now.

**Comment by carlocab** [comment]
Trying this as syntax-only for now to enable a merge, since we can't build this without updating `setuptools`.

**Comment by carlocab** [comment]
Or, I suppose we can vendor `setuptools` here in the meantime.

**Comment by cho-m** [comment]
I don't mind either way. I think a newer `setuptools` with `distutils` fix will work.

Since issue seems to be in `distutils`, a workaround would be to use the stdlib copy (`ENV["SETUPTOOLS_USE_DISTUTILS"] = "stdlib"`).

**Comment by carlocab** [comment]
Using the latest `setuptools` seems to work.

**Pull request closed without merging**
