### PR TITLE
victoriametrics 1.89.1

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
No error, but this failed to autosquash for some reason 😅

**Comment by carlocab** [comment]
I think the squashed commits get lost when `git-try-push` does `git rebase`...

**Comment by carlocab** [comment]
> I think the squashed commits get lost when `git-try-push` does `git rebase`...

Yea, I think that's it. [When `git-try-push` does](https://github.com/Homebrew/homebrew-core/actions/runs/4552738249/jobs/8028455659#step:14:35)
```
/usr/bin/git pull --rebase --autostash https://github.com/ZhongRuoyu/homebrew-core.git bump-victoriametrics-1.89.1
```
the autosquashed changes get destroyed. Not quite sure how to handle that. CC @dawidd6 for thoughts.

**Comment by carlocab** [comment]
> Here's another PR, if you want it: #126952

Thanks! I don't have time to look at it anymore for now, but I'll check back later. Don't feel the need to delay merging that one if needed.

**Review by carlocab — APPROVED** [review]

**Comment by dawidd6** [comment]
I think the pull-rebase can be skipped in a workflow like that. AFAIK it was done like that to get the latest changes from master, rebase on top of it and the be able to push it cleanly.

**Pull request merged**
