### PR TITLE
sourcekitten 0.12.1

### PR DESCRIPTION
**Pull request by jpsim**
Thanks!

### CODE REVIEW

**Comment by UniqMartin** [comment]
The build fails on Yosemite, because it is stuck at Xcode 7.2. However, SourceKitten 0.12.1 now requires Xcode 7.3 (https://github.com/jpsim/SourceKitten/tree/0.12.1#installation), so that limits it to El Capitan. Please adjust the

```
depends_on :xcode => ["7.1", :build]
```

line in the formula accordingly and push an update to this PR. Thanks!

**Comment by jpsim** [comment]
Alright done! I didn't know CI had Xcode 7.3 now. Is there somewhere the Xcode versions available for CI are documented?

**Comment by mikemcquaid** [comment]
@jpsim We don't document but it but you can see it e.g. http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/747/version=el_capitan/testReport/brew-test-bot/el_capitan/config/

**Comment by mikemcquaid** [comment]
@jpsim Thanks!

**Pull request closed without merging**
