### PR TITLE
minizip 1.3.1

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> Testing hashcat
  ==> /opt/homebrew/Cellar/hashcat/6.2.6_1/bin/hashcat_bin --benchmark -m 0 -D 1,2 -w 2
  clGetDeviceIDs(): CL_INVALID_VALUE
  
  No devices found/left.
  
  hashcat (v6.2.6) starting in benchmark mode
  
  Started: Wed Jan 24 15:19:51 2024
  Stopped: Wed Jan 24 15:19:52 2024
```

**Comment by krehel** [comment]
Related: https://github.com/hashcat/hashcat/issues/3525

**Comment by stavikpetr** [comment]
Status? 👀

**Comment by chenrui333** [comment]
> @chenrui333 @p-linnane This was good to merge I think, and I guess now CI work is lost and will need to be redone?

yeah, you are right, it should be good for the merge.

posted the previous run log in here, https://github.com/Homebrew/homebrew-core/actions/runs/7773162900/job/21196846749

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
