### PR TITLE
Migrating gauge formula to getgauge/releases tap.

### PR DESCRIPTION
**Pull request by bugdiver**
Ref: https://github.com/getgauge/homebrew-releases

### CODE REVIEW

**Comment by ilovezfs** [comment]
See comment here: https://github.com/Homebrew/homebrew-core/pull/25316#issuecomment-373339894

**Comment by ilovezfs** [comment]
@sriv I am going to assume you didn't know about this.

**Comment by sriv** [comment]
@ilovezfs - sorry about this. I wasn't aware. We discussed third-party tap as an option before your comment on #25316.

**Comment by ilovezfs** [comment]
@sriv no worries. FYI https://github.com/Homebrew/homebrew-core/pull/25316#issuecomment-373697199

**Pull request closed without merging**
