### PR TITLE
gdk-pixbuf 2.34.0

### PR DESCRIPTION
**Pull request by blogabe**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
### Description

An even numbered minor release which is more table that the odd
numbered experimental releases.  This would update the existing 2.32.3
version in homebrew.

### CODE REVIEW

**Comment by UniqMartin** [comment]
Thanks for your contribution, but there's already an open pull request (#267) that will update this formula and a bunch of other Gnome-related formulae. Not sure what the status of that is (feel free to ask there), but closing because of this.

**Comment by blogabe** [comment]
Since https://github.com/Homebrew/homebrew-core/pull/267 is now closed, is it time to re-open this PR?

**Comment by DomT4** [comment]
If Tom doesn't want to pick the PR back up I'll re-file it soon. Let's not dive in individually just yet.

**Comment by blogabe** [comment]
Sounds good.  Thank you!

**Pull request closed without merging**
