### PR TITLE
easyengine 4.6.0

### PR DESCRIPTION
**Pull request by mrrobot47**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
This was already updated 2 pull requests ago: https://formulae.brew.sh/formula/easyengine

**Comment by mrrobot47** [comment]
Previously wrong binary was uploaded. This PR updates the binary sha256 to match the actual binary in release now.

**Comment by SMillerDev** [comment]
So it's retagged? Because the [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do. So I'd like to see an official mention from upstream that this happened then.

**Comment by mrrobot47** [comment]
No, it was not retagged! We had put in automation to generate release and upload binary to the release. 
Due to a small error in that, it uploaded the nightly binary instead of stable one when release was generated.

I simply updated the binary with stable one in release.

**Comment by SMillerDev** [comment]
So the content of the release changed without the number changing. That's a retag in my book.

**Pull request closed without merging**
