### PR TITLE
doctl 1.2.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Also,
- fix audit error about redundant to_s inside interpolation
- fix warning about trying to stage empty resources array

### CODE REVIEW

**Comment by DomT4** [comment]
Someone filed a PR earlier FWIW: https://github.com/Homebrew/homebrew-core/pull/1778 😜

**Comment by ilovezfs** [comment]
@DomT4 ah ok. Then I guess we can fix the audit error and warning separately.

**Comment by DomT4** [comment]
You could always `brew pull` the older PR into your branch, add a separate commit on top of it with your audit changes, push here & then merge 'em together. I do that sometimes if prior PRs are "incomplete".

**Comment by ilovezfs** [comment]
Since the two changes here don't actually affect the bottle, I think we can pull his, and then pull this without updating the bottle?

**Comment by ilovezfs** [comment]
ah now I understand

**Comment by UniqMartin** [comment]
@ilovezfs #1778 has been merged in case you want to follow up with your tweaks.

**Comment by ilovezfs** [comment]
@UniqMartin Thanks for the heads up. Voilà: https://github.com/Homebrew/homebrew-core/pull/1789

**Pull request closed without merging**
