### PR TITLE
simgrid 3.30

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Raised an license issue in the upstream, https://framagit.org/simgrid/simgrid/-/issues/101

**Comment by mquinson** [comment]
Hello, I'm upstream, summoned by @chenrui333 :) Thanks for that.

Where can I see the full logs of the failed build? I'm surprised that the detection of cgraph went wrong so I'm wondering how you're calling cmake. I could probably help with the full logs.

**Comment by mquinson** [comment]
You should simply remove that line: https://github.com/Homebrew/homebrew-core/blob/f6b84960c1bf938f28e1f3a779eccfa296b676d3/Formula/simgrid.rb#L28

This dependency is not really important for simgrid to run. Alternatively, you should maybe install cgraph manually? It comes with graphviz on my system, but I'm not sure.

While I'm here, I think you should install pybind11 before building simgrid, that's a real increment for the users. And I'm a bit surprised that you build with `optimizations=off` to cmake.

Thanks again for your time and support for this software,
Mt

**Comment by chenrui333** [comment]
@mquinson the full log should be in here, https://github.com/Homebrew/homebrew-core/runs/5023776116

**Comment by chenrui333** [comment]
ping @mquinson

**Comment by chenrui333** [comment]
you can also see the new attempt with 3.31 #97890

**Comment by mquinson** [comment]
https://github.com/Homebrew/homebrew-core/pull/94257#issuecomment-1029438692

**Pull request closed without merging**
