### PR TITLE
Cd to botan--git folder if build HEAD version

### PR DESCRIPTION
**Pull request by catap**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
This is actually a bug in brew. Thanks for reporting.

**Comment by ilovezfs** [comment]
@catap this should be fixed now if you `brew update`. Thanks again for the quick PR.

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/brew/issues/2715.

**Comment by catap** [comment]
@ilovezfs, yes, it fixed. Thanks!

**Comment by ilovezfs** [comment]
You're welcome!

**Pull request closed without merging**
