### PR TITLE
opus-tools 0.1.10

### PR DESCRIPTION
**Pull request by rillian**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
No tests.
-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Download failures: https://bot.brew.sh/job/Homebrew%20Core/15149/version=sierra/testReport/junit/brew-test-bot/sierra/fetch_opus_tools/

**Comment by rillian** [comment]
Sorry, looks like there was a mirror hiccup. Can you please retrigger? We've checked all the mirror hosts manually and it should be consistently available now.

**Comment by woodruffw** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
Download failing: https://bot.brew.sh/job/Homebrew%20Core/15372/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/fetch_opus_tools/

**Comment by rillian** [comment]
Sigh. We bumped the mirrors again, and all 6 ip addresses show the file for me, but for the avoidance of doubt I pushed a commit to switch to the mozilla.org mirror, which is hosted on s3.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
