### PR TITLE
bazel 0.3.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
This one can be fun to update, but seems to have passed okay, so 👍

**Comment by ilovezfs** [comment]
Yes especially since the build system goes down two different roads depending on whether you already have bazel, which is particularly "fun."

**Comment by UniqMartin** [comment]
Maybe it should bootstrap itself to avoid being overly funny. :wink:

**Comment by UniqMartin** [comment]
@ilovezfs Do you know whether it can be convinced to build in the current directory (or at least respect `$TMPDIR`) instead of dumping hundreds of megabytes in `/var/tmp/_bazel_<user>` where they will never be cleaned up on most OS X machines? This affects our CI and users that build from source.

**Comment by ilovezfs** [comment]
@UniqMartin I'm sure it can. That's "interesting" behavior!

**Comment by UniqMartin** [comment]
> I'm sure it can. That's "interesting" behavior!

I'm not entirely sure it can. 😢 Seems to be hardcoded in [`src/main/cpp/blaze_util_darwin.cc`](https://github.com/bazelbuild/bazel/blob/0.3.0/src/main/cpp/blaze_util_darwin.cc#L36-L38).

**Comment by ilovezfs** [comment]
https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/blaze_startup_options_common.cc#L29-L35

**Comment by ilovezfs** [comment]
Ya that works. `ENV["TEST_TMPDIR"] = "#{HOMEBREW_CACHE}/googlish"` leads to
```
iMac-TMP:~ joe$ ls ~/Library/Caches/Homebrew/googlish/
_bazel_joe
```

**Comment by ilovezfs** [comment]
92M still leaked to `/var/tmp/_bazel_joe` so may have to set another var too.

**Comment by UniqMartin** [comment]
Thanks for looking into this!

**Comment by m3drano** [comment]
ping?

**Comment by UniqMartin** [comment]
In my opinion the fact that Bazel is hard-coded to work with `/var/tmp` needs to be fixed upstream. (@ilovezfs Did you happen to report this when you poked this issue?) But this doesn't need to stop us from shipping the update. We've lived with this problem for quite a while and we'll be fine ignoring it (or postponing its resolution) a bit longer …

**Comment by DomT4** [comment]
^ 👍, although potentially worth setting the `ENV["TEST_TMPDIR"]` variable with an explanation linking back to this discussion so it isn't completely forgotten in time. At least _limits_ how much is dumped onto the filesystem in an unexpected location 😕.

**Comment by damienmg** [comment]
This is fixed at HEAD using WORKDIR environment variable to prevent writing it to /var/tmp (so next release will fix it, we can apply the patch to 0.3.0 in between). Do you want me or someone from the Bazel team to take over?

**Comment by UniqMartin** [comment]
@damienmg Sorry for the delay with this and thanks for the upstream changes! I'll merge this as-is as soon as the just triggered test bot run finishes (the previous one was too long ago) and would appreciate if you opened a PR afterwards that added the necessary patch to the formula.

**Comment by damienmg** [comment]
Ok thanks for the quick answer, I'll make the PR later today.

**Comment by UniqMartin** [comment]
@damienmg This failed unfortunately as the SHA-256 checksum no longer matches. Has the the 0.3.0 release been re-tagged/re-published? It would explain this mismatch. I think in this case it's fine if you opened a new PR with this version bump and the patch for the `/var/tmp` behavior to replace this PR. (And I strongly suspect @ilovezfs will be fine with this solution, too.)

**Comment by damienmg** [comment]
Yes sorry for that, we had to retag the release for shipping some GPL source code (we have GPLv2 with classpath exception dependency and to comply with the GPL we need to have the source in our zip).

**Comment by damienmg** [comment]
(not with the patch, it is a legal requirement, not a technical issue).

**Comment by ilovezfs** [comment]
Sorry, didn't notice the ping here.

I'll update the checksum, but not do the TEST_TMPDIR thing that we'd been discussing. Then @damienmg (or whoever he'd like!) can open a fresh PR with the proper upstream fix and any other tweaks, etc.

**Comment by UniqMartin** [comment]
> Sorry, didn't notice the ping here.

No worries! Thanks for responding so quickly and for refreshing this PR.

> I'll update the checksum, but not do the TEST_TMPDIR thing that we'd been discussing. Then @damienmg (or whoever he'd like!) can open a fresh PR with the proper upstream fix and any other tweaks, etc.

I agree. Let's get this merged as-is when the bot is ready and then follow up with a new PR.

**Comment by ilovezfs** [comment]
@UniqMartin there are two bazel PRs sitting out at the door step too. I'm inclined to close both of them since upstream is about to open a PR.

**Comment by UniqMartin** [comment]
> @UniqMartin there are two bazel PRs sitting out at the door step too. I'm inclined to close both of them since upstream is about to open a PR.

Thanks, I didn't notice them! Makes sense to me if pointed to this discussion. Any follow-up PR would ideally contain all of those minor fixes and the patch that has been mentioned here.

**Comment by ilovezfs** [comment]
:ship: 'd

**Comment by ilovezfs** [comment]
@damienmg I've closed #2921 so that it won't conflict with the PR you're planning. The goal of #2921 was to address https://github.com/bazelbuild/bazel/issues/1503. It would be great if you could incorporate a fix for that issue as part of your PR. (Of course, the fix doesn't need to be exactly the same as what was proposed in #2921 if there's a better approach).

**Comment by damienmg** [comment]
Everybody: sorry I have been pretty busy and in holidays for the last week. We are cutting a new release in Bazel which contains the temporary files fix. I will send a PR for 0.3.1 with all the related fixes once we release (on Friday probably).

**Comment by ilovezfs** [comment]
@damienmg Thanks for the update. Did you have a chance to review
https://github.com/Homebrew/homebrew-core/pull/2921 and
https://github.com/bazelbuild/bazel/issues/1503

Is that fixed in the new release?

**Comment by damienmg** [comment]
I will add this change in 0.3.1 yes (I am waiting for it now because it is easier to just use the patch from upstream rather than patching the source in the recipe). Sorry for the delay.

**Comment by ilovezfs** [comment]
@damienmg Excellent! Don't worry about the delay :)

**Comment by damienmg** [comment]
0.3.2 is here, sent out #3427 :)

**Comment by ilovezfs** [comment]
@damienmg awesome, thank you.

**Pull request closed without merging**
