### PR TITLE
istio 0.1.6 (new formula)

### PR DESCRIPTION
**Pull request by InTheCloudDan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is a formula to install [Istio](https://istio.io). An open platform to connect, manage, and secure microservices.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Homebrew formulas build software from source.

**Comment by stealthybox** [comment]
This would be good to submit as a cask: https://github.com/caskroom/homebrew-cask

**Comment by MPV** [comment]
I created a pull request for a cask for Istio: 
https://github.com/caskroom/homebrew-cask/pull/42802

**Comment by MPV** [comment]
Istio (in binary format) was rejected as a cask and suggested as a core formula instead: 
> Please submit this to Homebrew/core building from source or consider creating your own tap.
>-- https://github.com/caskroom/homebrew-cask/pull/42802

**Comment by MPV** [comment]
FYI: I created a new pull request for adding Istio (0.4.0), this time built from source: https://github.com/Homebrew/homebrew-core/pull/22897

**Pull request closed without merging**
