### PR TITLE
libxml2: fix pkg-config file

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
This should fix the issue reported here: https://github.com/Homebrew/homebrew-core/pull/103721#issuecomment-1158235748, https://github.com/OSGeo/gdal/issues/5934.  I've added a test to make sure that `pkg-config` also works, as were only testing `xml2-config` before and that allowed this problem to slip by.  Thanks @rouault for reporting this!

**Comment by rouault** [comment]
Thanks for the quick fix. (While investigating I realize my build recipee does *not* actually use pkg-config as I thought, but has just a LibXML2_ROOT=/usr/local/opt/libxml2 argument passed to CMake ... it's annoying that including libxml2 leaks those implementation details, but that's another story...)

**Comment by Bo98** [comment]
CMake's `FindLibXml2` should use pkg-config internally.

We also ship a `libxml2-config.cmake` which should operate correctly, but I'm guessing it doesn't take priority.

**Comment by rouault** [comment]
> CMake's `FindLibXml2` should use pkg-config internally.

yes, that should do it (pkg-config wasn't installed...)

**Review by Bo98 — APPROVED** [review]

**Pull request closed without merging**
