### PR TITLE
node 8.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by corbinu** [comment]
Is there a reason this installs npm 4.2 rather than 5 as is standard with node 8?

**Comment by ilovezfs** [comment]
@corbinu see https://github.com/Homebrew/homebrew-core/pull/14085 and https://github.com/Homebrew/homebrew-core/issues/14108

**Comment by corbinu** [comment]
ok cool thanks!

**Comment by ilovezfs** [comment]
@corbinu now shipped with npm 5 (https://github.com/Homebrew/homebrew-core/pull/14085)

**Comment by lvieirajr** [comment]
How can we install node 7 now?
There is no option to install it... 
screen shot 2017-06-07 at 4 36 08 pm

**Comment by matteocrippa** [comment]
@ilovezfs it has been just released `8.1.0` patch for some big issues with zlib and other stuff

**Comment by ilovezfs** [comment]
@matteocrippa https://github.com/Homebrew/homebrew-core/pull/14367.

**Comment by ilovezfs** [comment]
@lvieirajr node 7 is not an LTS release. See https://github.com/Homebrew/homebrew-core/issues/14118.

**Pull request closed without merging**
