### PR TITLE
bazel: patch bazel for macOS 10.12 Sierra

### PR DESCRIPTION
**Pull request by ed-flanagan**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---
- Use nanosleep(2) instead of poll(2) to sleep
- See
  https://github.com/bazelbuild/bazel/commit/fefd2329f4812bcb513294fdf417fc726a86ddfd

---

Referenced:
- https://github.com/Homebrew/homebrew-core/issues/4841
- https://github.com/bazelbuild/bazel/issues/1767
- https://github.com/Homebrew/homebrew-core/pull/5041
- https://github.com/bazelbuild/bazel/commit/fefd2329f4812bcb513294fdf417fc726a86ddfd

### CODE REVIEW

**Comment by ilovezfs** [comment]
I think I'd like to wait on a new release here... CC @damieng for thoughts

**Comment by zmwangx** [comment]
Nice, but you need to put it into a stable block:

```ruby
  desc "Google's own build tool"
  homepage "https://www.bazel.io/"
  head "https://github.com/bazelbuild/bazel.git"

  stable do
    url "https://github.com/bazelbuild/bazel/archive/0.3.1.tar.gz"
    sha256 "52beafc9d78fc315115226f31425e21df1714d96c7dfcdeeb02306e2fe028dd8"

    # Fix build on macOS 10.12 Sierra
    patch do
      url "https://github.com/bazelbuild/bazel/commit/fefd2329f4812bcb513294fdf417fc726a86ddfd.diff"
      sha256 "73455ede4acb9e40923838cb66750a5baacc6b6f8eaaeed72df02dbca38bbe73"
    end
  end

  bottle do
    cellar :any_skip_relocation
    sha256 "fda77dc7aa1722d9586ec0a4148357ba89436d641c278e7a93da2486ba059059" => :el_capitan
    sha256 "0fcea9e375d29bda7c7e291172cd59d235512952a377f469e684315c109f6dfb" => :yosemite
  end
```

**Comment by ed-flanagan** [comment]
Placed the patch in the `stable` block.

**Comment by mblair** [comment]
@ilovezfs did you mean @damienmg?

**Comment by ilovezfs** [comment]
@mblair yes, thanks

**Comment by damieng** [comment]
That's good because I had no idea what this was about :)

**Comment by ilovezfs** [comment]
I think I'd like to wait on a new release here... CC @damienmg for thoughts

**Comment by damienmg** [comment]
We just pushed a canary today. We have a 1 week baking but we are basically blocking on a couple of bugfixes. I still believe we should be able to release by next tuesday.

**Comment by zmwangx** [comment]
Next Tuesday is a week from now, and bazel is popular enough to be on my #4841 list. What about we ship the patch now so people at least have something to work with.

**Comment by damienmg** [comment]
This patch is pretty much harmless and fixes the sierra issue so SGTM

**Comment by zmwangx** [comment]
@ilovezfs I'll leave the decision to you.

**Comment by ilovezfs** [comment]
If @damienmg is happy to :boat: then no objection from me!

**Comment by zmwangx** [comment]
:shipit:

**Comment by ilovezfs** [comment]
@ed-flanagan thanks for your contribution to Homebrew! :tada:

**Pull request closed without merging**
