### PR TITLE
mdxmini: remove dead homepage URL

### PR DESCRIPTION
**Pull request by mitchblank**
cc @mistydemeo  @BouKiCHi

### CODE REVIEW

**Comment by carlocab** [comment]
Probs not syntax-only, though, since we want to try to build a Big Sur bottle (and perhaps an ARM one too).

Or do we just want that done in a separate job to avoid needlessly getting rid of the old bottles? Because that can work too.

**Comment by Bo98** [comment]
> Or do we just want that done in a separate job to avoid needlessly getting rid of the old bottles?

Yes please.

**Comment by mitchblank** [comment]
> Probs not syntax-only, though, since we want to try to build a Big Sur bottle (and perhaps an ARM one too).

Yeah I've got a few formula that are on my "syntax now fixed, need manual rebottle" list.  Every so often I bother @fxcoudert about them and he runs them for me.  I need to sweep through them and figure out which ones are ready again

**Review by carlocab — APPROVED** [review]
Ok, sounds good. Merging this then dispatching separate bottle jobs.

**Comment by carlocab** [comment]
ARM: https://github.com/Homebrew/homebrew-core/actions/runs/559428548
Big Sur: https://github.com/Homebrew/homebrew-core/actions/runs/559429068

**Comment by carlocab** [comment]
The runner got stuck on the upload stage, so I just restarted it.

**Pull request merged**
