### PR TITLE
tree-sitter 0.21.0

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by clason** [comment]
Just wait a bit, the release is running as we speak. I just want to give the (extensive) CI here a head start.

**Comment by clason** [comment]
@chenrui333  The release is published, by the way: https://github.com/tree-sitter/tree-sitter/releases/tag/v0.21.0

**Review by p-linnane — APPROVED** [review]
Thanks @clason!

**Review by carlocab — APPROVED** [review]

**Comment by chenrui333** [comment]
looks like a timing issue :)

**Pull request merged**
