### PR TITLE
fail2ban: add HEAD, bump stable version to 0.9.4, & add devel version 0.10

### PR DESCRIPTION
**Pull request by Jerzerak**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---
- Add HEAD spec
- Bump stable version from 0.8.14 to 0.9.4
- Add devel version 0.10

### CODE REVIEW

**Comment by DomT4** [comment]
Everything failed to build 😸

**Comment by Jerzerak** [comment]
@DomT4 I know, just wanted to get this PR out of my local queue of updates while I still remembered it was there...I'll fix everything tomorrow

**Comment by apjanke** [comment]
Might be worth an upstream bug report to request support for full `--prefix` support in their installer. Looks like their `setup.py` script is using absolute paths for its data file locations so `--prefix` doesn't affect them.

**Comment by ilovezfs** [comment]
@Jerzerak there's an 0.9.5 now if you'd like to refresh this: https://github.com/fail2ban/fail2ban/releases/tag/0.9.5

**Comment by dunn** [comment]
🔔

**Comment by apjanke** [comment]
Closing due to inactivity. Feel free to reopen if you find time to pursue this.

**Pull request closed without merging**
