### PR TITLE
boost@1.67 1.67.0

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

From @MikeMcQuaid,

> but I said this when we originally discussed versioned formulae and was overruled :wink:
we should use versioned formulae to reduce the need to do what we’re doing
so we can upgrade in batches and then switch over the `boost` formula only when everything has been built against it

So, let's try adding a versioned `boost@1.67` prior to #30914. 🤓

### CODE REVIEW

**Comment by DomT4** [comment]
I thought @MikeMcQuaid's point was more to introduce a `boost@1.68` formula and move everything compatible over to it, and then make `boost` an alias to that formula when everything's compatible. I don't mind trying it that way, as something of a _trial_.

It does feel like we're overcomplicating the `boost` update somehow though. Previous releases broke much less & I can't recall us adding that many more `boost`-using formulae since the last time.

**Comment by DomT4** [comment]
Killed the build temporarily to give Mike time to elaborate/clarify.

**Comment by MikeMcQuaid** [comment]
> I thought @MikeMcQuaid's point was more to introduce a boost@1.68 formula and move everything compatible over to it, and then make boost an alias to that formula when everything's compatible. I don't mind trying it that way, as something of a trial.

I'm happy with either approach. If this one works and gets us a green build and an upgrade: what do you think about trying it, @DomT4?

**Comment by DomT4** [comment]
I think an issue with this approach, which presumably means we upgrade the `boost` itself, is that we still pulverise third-party taps. That's an issue today but this approach doesn't lessen that blow, and I think that's worth remembering/considering.

An issue with doing it the other way is that if I recall correctly _(which I may well not be)_ `boost-python` formulae have some significant issues being built against a `keg_only` version of `boost`, which a new versioned formulae would have to be.

I don't mind trying this way but I'd like some reassurance this actually leaves us with an upgradable `boost` and we're not going to end up with this PR merged but the `boost` PR sitting there for weeks to come.

**Comment by lembacon** [comment]
> I don't mind trying this way but I'd like some reassurance this actually leaves us with an upgradable `boost` and we're not going to end up with this PR merged but the `boost` PR sitting there for weeks to come regardless.

I assume that #30914 should get a green build after making these seven formulae depend on `boost@1.67`, as these formulae caused those remaining failures.

> An issue with doing it the other way is that if I recall correctly _(which I may well not be)_ `boost-python` formulae have some significant issues being built against a `keg_only` version of `boost`, which a new versioned formulae would have to be.

Another downside of the other approach is that we may need to add versioned formulae for `boost-bcp@1.68`, `boost-mpi@1.68`, `boost-python@1.68`, `boost-python3@1.68` and `boost-build@1.68` alongside `boost@1.68`. Fortunately, aforementioned seven formulae only depend on `boost`, so we only need a versioned `boost@1.67` for this approach.

**Comment by lembacon** [comment]
Just restarted the CI job. 🤫

**Comment by DomT4** [comment]
Did the one I set going last night before I went to bed hit the GitHub downtime or was there another CI-based failure?

**Comment by scpeters** [comment]
@domt4 said:

> I thought @MikeMcQuaid's point was more to introduce a boost@1.68 formula and move everything compatible over to it, and then make boost an alias to that formula when everything's compatible. I don't mind trying it that way, as something of a trial.

> I think an issue with this approach, which presumably means we upgrade the boost formula itself, is that we still pulverise third-party taps. That's an issue today but this approach doesn't lessen that blow, and I think that's worth remembering/considering.

If we try the `boost@new` approach, I'd be happy to do some testing with my 3rd-party tap to see if it makes my life easier.

If we did try changing the alias when everything's compatible, I think we'd have to change the audit that would complain "Dependency boost is an alias; use the canonical name boost@X"

* https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L388-L391

@lembacon said:

> Another downside of the other approach is that we may need to add versioned formulae for boost-bcp@1.68, boost-mpi@1.68, boost-python@1.68, boost-python3@1.68 and boost-build@1.68 alongside boost@1.68. Fortunately, aforementioned seven formulae only depend on boost, so we only need a versioned boost@1.67 for this approach.

This is a practical point in favor of the approach in this PR. I'm not sure that boost@1.68 would be better, but I would be interested in testing it if we do try it.

**Comment by MikeMcQuaid** [comment]
> I think we'd have to change the audit that would complain "Dependency boost is an alias; use the canonical name boost@X"

@scpeters I think this could be changed now to be only for the core tap.

**Comment by scpeters** [comment]
@MikeMcQuaid I've opened https://github.com/Homebrew/brew/pull/4715 to continue discussion about the audit for alias dependencies

**Comment by lembacon** [comment]
We've eventually got a successful CI run, except an audit failure and a style failure.

```
09:33:53 ==> brew audit boost@1.67 --online --new-formula
09:34:59 ==> FAILED
09:34:59 Error: 1 problem in 1 formula
09:34:59 boost@1.67:
09:34:59   * `bottle` is not defined
```

```
12:14:29 ==> brew style ledger
12:14:32 ==> FAILED
12:14:32 == /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ledger.rb ==
12:14:32 C: 94: 35: Use %r around regular expression.
12:14:32 
12:14:32 1 file inspected, 1 offense detected
```

The first one is intended as `boost@1.67` is a new formula. The latter can be fixed easily. I will not push a new commit to fix it right now, since we do not want to trigger another _endless_ CI run.

Regarding `ledger`, it depends on `boost-python`. I originally attempted to create a versioned `boost-python@1.67` for it, but it turns out that we cannot easily let `cmake` detect `boost@1.67` and `boost-python@1.67` libraries from two different non-standard locations without hacking into `FindBoost.cmake` which seems undesirable. Vendor `boost` 1.67 into `ledger` is probably the best we can do at the moment. (🤢🤮, I know…)

Thoughts? @DomT4

**Comment by DomT4** [comment]
Think it's worth filing bug reports upstream for all of these & linking those bug reports into each formulae but beside that I have no objection.

**Comment by lembacon** [comment]
@🤖 🤫

**Comment by lembacon** [comment]
Superseded by #32610.

**Pull request closed without merging**
