### PR TITLE
simdutf 3.2.2

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  duplicate symbol 'setup_performance_counters()' in:
      CMakeFiles/benchmark.dir/benchmark.cpp.o
      src/libsimdutf_benchmarks_benchmark.a(benchmark_base.cpp.o)
  duplicate symbol '_regs' in:
      CMakeFiles/benchmark.dir/benchmark.cpp.o
      src/libsimdutf_benchmarks_benchmark.a(benchmark_base.cpp.o)
  duplicate symbol '_counter_map' in:
      CMakeFiles/benchmark.dir/benchmark.cpp.o
      src/libsimdutf_benchmarks_benchmark.a(benchmark_base.cpp.o)
  duplicate symbol '_counters_1' in:
      CMakeFiles/benchmark.dir/benchmark.cpp.o
      src/libsimdutf_benchmarks_benchmark.a(benchmark_base.cpp.o)
  duplicate symbol '_counters_0' in:
      CMakeFiles/benchmark.dir/benchmark.cpp.o
      src/libsimdutf_benchmarks_benchmark.a(benchmark_base.cpp.o)
  duplicate symbol 'setup_performance_counters()' in:
      CMakeFiles/benchmark.dir/benchmark.cpp.o
      src/libsimdutf_benchmarks_benchmark.a(benchmark.cpp.o)
  duplicate symbol '_regs' in:
      CMakeFiles/benchmark.dir/benchmark.cpp.o
      src/libsimdutf_benchmarks_benchmark.a(benchmark.cpp.o)
  duplicate symbol '_counter_map' in:
      CMakeFiles/benchmark.dir/benchmark.cpp.o
      src/libsimdutf_benchmarks_benchmark.a(benchmark.cpp.o)
  duplicate symbol '_counters_1' in:
      CMakeFiles/benchmark.dir/benchmark.cpp.o
      src/libsimdutf_benchmarks_benchmark.a(benchmark.cpp.o)
  duplicate symbol '_counters_0' in:
      CMakeFiles/benchmark.dir/benchmark.cpp.o
      src/libsimdutf_benchmarks_benchmark.a(benchmark.cpp.o)
  ld: 10 duplicate symbols for architecture arm64
```

**Comment by p-linnane** [comment]
Opened an issue upstream: https://github.com/simdutf/simdutf/issues/218

**Comment by lemire** [comment]
Please try version 3.2.2.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @lemire!

**Pull request closed without merging**
