### PR TITLE
elm-format 0.8.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
23:46:54 optparse-applicative-0.14.3.0 (latest: 0.15.0.0) (new package)
23:46:54 bifunctors-5.5.4 (via: profunctors-5.4 semigroupoids-5.3.2) (new package)
23:46:54 semigroupoids-5.3.2 (via: free-5.1.1) (new package)
23:46:54 profunctors-5.4 (via: free-5.1.1) (new package)
23:46:54 free-5.1.1 (new package)
23:46:54 cabal: The following packages are likely to be broken by the reinstalls:
23:46:54 Cabal-2.4.0.1
23:46:54 Use --force-reinstalls if you want to install anyway.
23:46:54

**Review by ghost — APPROVED** [review]

**Comment by avh4** [comment]
FYI, the elm-format build process has changed -- probably the best way to do things for the homebrew build is to create `./generated/Build_elm_format.hs` with the content (`#{tag}` needs to be interpolated):

```	
module Build_elm_format where

gitDescribe :: String
gitDescribe = "#{tag}"
```

the cabal build should succeed after that file is generated.

**Comment by chenrui333** [comment]
Trying to fix this now.

**Comment by chenrui333** [comment]
Squash the changes now.

**Comment by chenrui333** [comment]
@Moisan @lembacon ready for merge

**Pull request closed without merging**
