### PR TITLE
libheif 1.1.0 (new formula)

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

* Fails the GitHub notability check but does have a Debian package: https://packages.debian.org/sid/libheif-dev

### CODE REVIEW

**Comment by ilovezfs** [comment]
Adding `#include <stdlib.h>` to `encoder.cc` fixes it.

What's with CMake not working?

**Comment by DomT4** [comment]
To be honest, unsure. Unless there's a motivation to not use the autotools I tend to not bother checking `CMake` stuff as it's an extra dependency to lug around. I can look into it, if you like.

**Comment by DomT4** [comment]
https://github.com/strukturag/libheif/issues/22

**Comment by DomT4** [comment]
We should be good to go here whenever CI is happy. It'll still whinge about GitHub notability but as mentioned there's a Debian package so 🤷‍♂️.

**Comment by ilovezfs** [comment]
What animal makes a "whinge" sound?

**Comment by DomT4** [comment]
> What animal makes a "whinge" sound?

Me, most mornings, after realising how little sleep I've managed overnight. Thanks for the merge!

**Pull request closed without merging**
