### PR TITLE
git-town 0.10.1

### PR DESCRIPTION
**Pull request by charlierudolph**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
The `broken pipe` is not directly related to this change. We've seen a few `broken pipe` errors with `--online` recently and haven't managed to nail them down. Is there anything in your `brew doctor` output?

**Comment by charlierudolph** [comment]
Looks like an installed formula had a missing dependency. Installed and it now works.

One note: on the contributing doc for submitting a version upgrade, it says your should `git commit` after using `brew audit`. Where are you suppose to do that exactly? I used Github to propose a change to this file and then just went through the local build process to verify it worked.

**Comment by charlierudolph** [comment]
In case it helps the missing dependency was `pcre2` which is a dependency of `fish`

**Comment by DomT4** [comment]
> Installed and it now works.

Just to clarify, you mean `brew audit --strict --online` now works?

> on the contributing doc for submitting a version upgrade, it says your should git commit after using brew audit. Where are you suppose to do that exactly?

Did you edit the file directly on GitHub? That documentation more or less assumes you're editing files locally & then pushing them to a remote, because that's the most common use case.

If you're contributing directly from the GitHub website, without ever using a local editor or git process, you can safely ignore the instructions around `git commit`.

**Comment by charlierudolph** [comment]
> Just to clarify, you mean brew audit --strict --online now works?

Yep

**Comment by DomT4** [comment]
Strange. Thanks for the diagnostic information here. Have raised it with the rest of the team, and hopefully with others encountering the same issue we'll be able to nail down a root cause sooner rather than later.

Merged in https://github.com/Homebrew/homebrew-core/commit/801e685fc720cd7bc0e9a1f411a7bfc473893432. Thank you for another contribution to Homebrew @charlierudolph! 😺

**Pull request merged**
