### PR TITLE
asyncapi 0.35.0

### PR DESCRIPTION
**Pull request by asyncapi-bot-eve**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by carlocab** [comment]
Hi, @derberg. I noticed you're the one who added the [workflow](https://github.com/asyncapi/cli/blob/3784f0f3c39c7cf45a67c2910eb0e18edeb4fa73/.github/workflows/bump-homebrew-formula.yml) for this automated version bump.

We've had 3 PRs today from @asyncapi-bot-eve. This isn't the first time we've had [multiple PRs in a day](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+is%3Aclosed+in%3Atitle+asyncapi+) from your bot. Our CI is self-hosted (and limited!), so we'd appreciate it if there were some way to limit the number of PRs opened on our side.

**Comment by chenrui333** [comment]
cc @derberg

**Comment by chenrui333** [comment]
@derberg no worries, and appreciate the fix on the pipeline improvements! 🍻

**Comment by carlocab** [comment]
Thanks @derberg!

**Pull request closed without merging**
