### PR TITLE
semgrep 1.23.0

### PR DESCRIPTION
**Pull request by semgrep-release**
Bump semgrep to version

### CODE REVIEW

**Comment by spencerdrak** [comment]
Looks like something here has gone wrong with our tagging again - I'll investigate. @p-linnane - should I close and re-open another PR?

**Comment by p-linnane** [comment]
No, it's fine. I fixed the commit message.

**Comment by chenrui333** [comment]
`    Errno::ENOENT: No such file or directory - _build/install/default/bin/spacegrep`

**Comment by chenrui333** [comment]
Got this error while building locally

```
==> opam install --deps-only -y .
[NOTE] External dependency handling not supported for OS family 'macos'.
       You can disable this check using 'opam option --global depext=false'
Nothing to do.
# Run eval $(opam env) to update the current shell environment
==> opam exec -- make core
rm -f bin
/Applications/Xcode.app/Contents/Developer/usr/bin/make minimal-build
dune build _build/install/default/bin/semgrep-core _build/install/default/bin/osemgrep
File "languages/html/tree-sitter/semgrep-html/lib/dune", line 1, characters 0-1277:
 1 | (library
 2 |   (public_name tree-sitter-lang.html)
 3 |   (name tree_sitter_html)
....
42 |            -I .)
43 |   )
44 | )
Error: Public library tree-sitter-lang.html is defined twice:
- languages/tree-sitter-lang/semgrep-html/lib/dune:1
- languages/html/tree-sitter/semgrep-html/lib/dune:1
make[1]: *** [minimal-build] Error 1
```

**Comment by spencerdrak** [comment]
@chenrui33 Yep, I think we've identified the fix and are going to push a change for it shortly.

**Review by chenrui333 — DISMISSED** [review]

**Pull request closed without merging**
