### PR TITLE
ansible 2.4.3.0

### PR DESCRIPTION
**Pull request by Josh-Tilles**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ilovezfs — DISMISSED** [review]
This needs all the resource blocks updated too using https://github.com/tdsmith/homebrew-pypi-poet/

**Comment by MerelyAPseudonym** [comment]
@ilovezfs I actually just finished doing that a moment ago, only to discover that the only change `poet_lint` wanted to see was to move the two “extras for requests[security]” resources (`pyOpenSSL` and `ndg-httpsclient`) into the sorted list of resources below them. So, perhaps I did something incorrectly, but I don't think any further updates are necessary.

**Comment by ilovezfs** [comment]
You need to use a clean virtualenv.

**Comment by ilovezfs** [comment]
@MerelyAPseudonym I've pushed the resource updates to your branch.

**Comment by ilovezfs** [comment]
Thanks for the PR @MerelyAPseudonym! Shipped.

**Comment by MerelyAPseudonym** [comment]
@ilovezfs Thanks for getting this over the finish line! FYI, I figured out the discrepancy: I was _only_ following the instructions from the formula: https://github.com/Homebrew/homebrew-core/blob/099a7a00a4e189b5344d8a665694763858e8064b/Formula/ansible.rb#L68-L69

Had I started from a fresh virtualenv (as you recommended) and consulted `homebrew-pypi-poet`’s README, I think I would have been able to generate the resources updates. I’ll keep that in mind next time 😉

**Pull request closed without merging**
