### PR TITLE
semgrep 0.67.0

### PR DESCRIPTION
**Pull request by brendongo**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mjambon** [comment]
"CI / tests (10.14)" fails to download an archive with curl, citing exit code 60. From curl's man page, exit code 60 is:
```
       60     Peer certificate cannot be authenticated with known CA  certificates.
```
Downloading I could do `curl -L -o foo https://opam.ocaml.org/index.tar.gz` without an error. I suppose we should just re-run the job or workflow.

**Comment by carlocab** [comment]
How does `opam` decide which `curl` to use for the download? Does it just check `PATH`? I think we can use Homebrew `curl` to get around the cert error for now.

**Comment by mjambon** [comment]
At a glance, it looks like a `PATH` lookup similar to the `which` command is performed by opam using some custom code in `core/opamSystem.ml` (this is the default mode, used by the `OpamDownload.download_command`).

Also, according to [this](https://github.com/ocaml/opam/blob/53cc23e08c61948bd5e2c92ef2442a7d38a910c4/src/repository/opamRepositoryConfig.ml#L56), opam will prefer wget over curl if it's available (on Darwin).

There's also the file [~/.opam/config](https://opam.ocaml.org/doc/Manual.html#config) where we can specify whether we want curl or wget or something else. If we specify anything else than just `curl` or `wget`, we have to specify the full command template which is more complicated.

Here's the things that seem worth trying:
* install wget and see if opam uses it instead of curl (see source code cited above)
* set PATH to find brew's curl first (see source code cited above)
* set OPAMCURL to be the path to brew's curl (see `opam --help`)

I haven't tried those things yet. Also I don't have a mac and I'm not familiar with brew.

**Comment by carlocab** [comment]
Using `wget` seems reasonable. I don't have push access to your PR branch, so someone else will have to apply this:
```diff
diff --git a/Formula/semgrep.rb b/Formula/semgrep.rb
index 58e79fd1a95..19c31f5eeba 100644
--- a/Formula/semgrep.rb
+++ b/Formula/semgrep.rb
@@ -28,6 +28,9 @@ class Semgrep < Formula
   depends_on "ocaml" => :build
   depends_on "opam" => :build
   depends_on "pkg-config" => :build
+  # Temporary fix for curl cert issues.
+  # TODO: Remove when Mojave curl issue is fixed.
+  depends_on "wget" => :build
   depends_on "pcre"
   depends_on "python@3.9"
   depends_on "tree-sitter"
```

**Comment by brendongo** [comment]
I can add that diff

**Review by carlocab — APPROVED** [review]
Thanks, @brendongo, @mjambon!

**Pull request closed without merging**
