### PR TITLE
imath 3.1.5

### PR DESCRIPTION
**Pull request by triallax**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by mhmdanas** [comment]
Was I supposed to only revbump dependents which had failing tests in the CI? I only revbumped direct dependents, but it feels like I did something incorrectly.

**Comment by SMillerDev** [comment]
Only the ones with a linkage failure.

**Comment by Bo98** [comment]
Those two are actually warnings rather than errors it looks like so revision bumping won't fix them. The failure was just some network blip that probably won't happen on a second run.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @mhmdanas!

**Pull request closed without merging**
