### PR TITLE
tkey-ssh-agent: Use correct ldflags

### PR DESCRIPTION
**Pull request by johan-carlberg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you add a test for this like:
```rb
  assert_match version.to_s, shell_output("#{bin}/tkey-ssh-agent --version")
```

**Comment by carlocab** [comment]
Don't mind the https://github.com/Homebrew/homebrew-core/labels/do%20not%20merge label; I just need to do some testing on our CI at the moment. Will remove it after.

**Comment by carlocab** [comment]
@BrewTestBot isn't able to push to your fork, so I've opened #127173 to replace this.

**Comment by carlocab** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/f26ff7645011f0ff12af95fd025a74f0ac590e0e.

**Pull request closed without merging**
