### PR TITLE
mycli 1.12.0

### PR DESCRIPTION
**Pull request by tsroten**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

- Updates mycli to version 1.12.0
- Updates CLI Helpers dependency to fix a bug under Python 2.7

### CODE REVIEW

**Review by fxcoudert — CHANGES_REQUESTED** [review]
Resource that need to be updated: prompt_toolkit 1.0.15, pycparser 2.18, cryptography 2.0.2

**Comment by tsroten** [comment]
@fxcoudert Thanks for pointing those out. I'll push an update in just a bit. :smile:

**Comment by tsroten** [comment]
@fxcoudert Ok, I've updated the versions for prompt_toolkit and pycparser.

I did not update cryptography because cryptography >=2.0.0 does not support Python 3.3. Mycli still supports Python 3.3 and plans to until its end-of-life date (September 29, 2017).

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @tsroten for the pull request!

**Pull request closed without merging**
