### PR TITLE
node 17.7.1

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~ ✅

### CODE REVIEW

**Comment by carlocab** [comment]
`autorest` failed everywhere and looks like it could be a genuine regression. @chenrui333 do you mind taking a look since you changed the test recently?

**Comment by chenrui333** [comment]
Sure, let me take a look.

**Comment by chenrui333** [comment]
I can reproduce the issue in my local, and it is reported in [here](https://github.com/Azure/autorest/issues/4409)

**Comment by cho-m** [comment]
Either can wait for `node 17.7.1` (https://github.com/nodejs/node/pull/42285) which may be out quickly due to breakage or apply commit https://github.com/nodejs/node/commit/f91950c43eb3934249616838013aa953344c766c

**Comment by chenrui333** [comment]
Should be fixed with [this](https://github.com/Azure/autorest/pull/4463).

**Comment by Bo98** [comment]
Let's wait until 17.7.1.

**Comment by derrabus** [comment]
17.7.1 has been released. I've updated the PR.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
