### PR TITLE
sourcery 2.1.8

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>prerelease notes</summary>
  <pre>## What's Changed
* ClosureParameter isVariadic Support by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1268
* Update Usage.md to include --parseDocumentation option by @MarcoEidinger in https://github.com/krzysztofzablocki/Sourcery/pull/1272
* Format processing time log message by @MontakOleg in https://github.com/krzysztofzablocki/Sourcery/pull/1274
* Fixed swift-package-manager version by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1280
* Added isSet to TypeName by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1281
* chore(deps): bump nokogiri from 1.15.4 to 1.16.2 by @dependabot in https://github.com/krzysztofzablocki/Sourcery/pull/1273
* Implement GenericRequirement support for member type disambiguation by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1283
* Add generic requirements to Method by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1284
* Recognize subclasses with generics by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1287
* Implemented typealias unboxing during type resolution by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1288
* Added documentation to typealias by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1289
* [Bugfix][AutoMockable.stencil]- inout with multiple parameters & optional any parameter in completion handler by @paul1893 in https://github.com/krzysztofzablocki/Sourcery/pull/1290
* [Syntax][AutoMockable.stencil]- Avoid side effect by @paul1893 in https://github.com/krzysztofzablocki/Sourcery/pull/1291
* Substitute underlying type from typealias by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1292
* Added support for multiline documentation comments by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1293
* Update SwiftSyntax dependency to 510.0.0 by @calda in https://github.com/krzysztofzablocki/Sourcery/pull/1294
* Resolved all SwiftSyntax Warnings by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1295
* Trailing Annotation Parsing by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1296
* Fixed Crash in AnnotationParser by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1297
* Disabled Optimization During Generated Code Verification by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1300
* Adjusted file structure to accommodate two generated files by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1299
* Expand --serialParse flag to also apply to Composer.uniqueTypesAndFunctions by @calda in https://github.com/krzysztofzablocki/Sourcery/pull/1301
* Make AutoMockable Generate Compilable Swift Code by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1304
* Fix Closure Parameter CVarArg with Existential by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1305
* Update Changelog by @art-divin in https://github.com/krzysztofzablocki/Sourcery/pull/1307

## New Contributors
* @MarcoEidinger made their first contribution in https://github.com/krzysztofzablocki/Sourcery/pull/1272
* @MontakOleg made their first contribution in https://github.com/krzysztofzablocki/Sourcery/pull/1274
* @calda made their first contribution in https://github.com/krzysztofzablocki/Sourcery/pull/1294

**Full Changelog**: https://github.com/krzysztofzablocki/Sourcery/compare/2.1.7...2.1.8</pre>
</details>

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  sourcery
    * 2.1.8 is a GitHub pre-release.
```

**Comment by art-divin** [comment]
👋🏻  Hello,

artifacts are now available, and Sourcery 2.1.8 is available for brew release. Marked Sourcery as release-ready.

Thank you very much @Porkepix for your PR! 

cc @chenrui333

**Comment by art-divin** [comment]
Hey @chenrui333 👋🏻 

Whenever I try to create a PR right now, I receive an error that this PR is a duplicate, even though this one does not do the actual bump:

```
Error: These open pull requests may be duplicates:
sourcery: add livecheck and autobump https://github.com/Homebrew/homebrew-core/pull/166663
Duplicate PRs should not be opened.
Manually open these PRs if you are sure that they are not duplicates.
```

Could you please assist how to proceed?

Thank you! 🙏🏻

**Comment by chenrui333** [comment]
yeah, totally.

**Review by chenrui333 — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
