### PR TITLE
kubeaudit 0.22.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ZhongRuoyu — COMMENTED** [review]
Not the latest release yet: https://github.com/Shopify/kubeaudit/releases

**Comment by chenrui333** [comment]
close it for now.

**Comment by ZhongRuoyu** [comment]
The release was re-tagged so I'm opening #126306.

**Comment by chenrui333** [comment]
Thanks @ZhongRuoyu!

**Pull request closed without merging**
