### PR TITLE
protobuf 25.0

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
https://github.com/Homebrew/homebrew-core/actions/runs/6726867634/job/18283891423#step:3:938:

```
  creating build
  error: could not create 'build': File exists
```

A `BUILD` file was added, which failed on macOS's case-insensitive filesystem. https://github.com/protocolbuffers/protobuf/blob/v25.0/python/BUILD

**Comment by chenrui333** [comment]
you can also update `build` -> `_build` in 

```
    system "cmake", "-S", ".", "-B", "build", *cmake_args, *std_cmake_args
    system "cmake", "--build", "build"
    system "cmake", "--install", "build"
```

**Comment by ZhongRuoyu** [comment]
> you can also update `build` -> `_build`

It's not related; the CMake `build` directory that we create is in the top-level directory, but the problematic file is `python/BUILD` which we haven't touched.

**Comment by chenrui333** [comment]
> > you can also update `build` -> `_build`
> 
> It's not related; the CMake `build` directory that we create is in the top-level directory, but the problematic file is `python/BUILD` which we haven't touched.

I see 👍

**Comment by p-linnane** [comment]
Force pushed to resolve `apache-arrow` conflict.

**Review by p-linnane — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
