### PR TITLE
molecule 2.22

### PR DESCRIPTION
**Pull request by dawidd6**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
I removed the `enum34` resource since its goal is to backport python 3.4 enums. No need for it when using python > 3.4

**Comment by bayandin** [comment]
Installing of the formula fails with `AttributeError: 'SpecifierSet' object has no attribute 'split'`, we need to add this patch https://github.com/ansible/molecule/pull/2381

**Comment by dawidd6** [comment]
Thanks guys, squashed and added the patch.

**Comment by dawidd6** [comment]
```
==> Downloading https://github.com/ansible/molecule/commit/a348075f19aa504471cdd910dd6d283e7d2ae6df.patch
cp -p /Users/brew/Library/Caches/Homebrew/downloads/86aebe9e004a5275124cfb0d1f9a03c492d47834dd0e65ac1863f51001ab84c9--a348075f19aa504471cdd910dd6d283e7d2ae6df.patch /private/tmp/molecule--patch-20191217-48893-2nq4vd/a348075f19aa504471cdd910dd6d283e7d2ae6df.patch
Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/86aebe9e004a5275124cfb0d1f9a03c492d47834dd0e65ac1863f51001ab84c9--a348075f19aa504471cdd910dd6d283e7d2ae6df.patch
==> Verifying 86aebe9e004a5275124cfb0d1f9a03c492d47834dd0e65ac1863f51001ab84c9--a348075f19aa504471cdd910dd6d283e7d2ae6df.patch checksum
==> Patching
==> Applying a348075f19aa504471cdd910dd6d283e7d2ae6df.patch
patch -g 0 -f -p1 -i /private/tmp/molecule--patch-20191217-48893-2nq4vd/a348075f19aa504471cdd910dd6d283e7d2ae6df.patch
patching file .travis.yml
patching file pyproject.toml
patching file setup.py
Hunk #1 FAILED at 23.
Hunk #2 succeeded at 38 (offset 1 line).
1 out of 2 hunks FAILED -- saving rejects to file setup.py.rej
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/molecule--patch-20191217-48893-2nq4vd/a348075f19aa504471cdd910dd6d283e7d2ae6df.patch` exited with 1.
```

Maybe we should just wait for next stable release?

**Comment by iMichka** [comment]
FYI I moved this to system Python 2 for the time being: #48409

**Comment by dawidd6** [comment]
Thanks for heads up @iMichka. Rebased.

**Comment by dawidd6** [comment]
Not gonna work on this. Will wait for next `3.0` release.

**Pull request closed without merging**
