### PR TITLE
dotnet 6.0.104

### PR DESCRIPTION
**Pull request by Bo98**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
GitHub runners don't have enough disk space (temp is about ~40-50GB at end of build).

May be able to reduce requirement by trying `p:CleanWhileBuilding` (https://github.com/dotnet/source-build/issues/2782#issuecomment-1055809244).

**Comment by cho-m** [comment]
I'm guessing GNU vs BSD `df`. May need to report upstream and/or temporarily switch to `coreutils`:
```
DirSize Before Building source-build-reference-packages
    df --block-size=1M /private/tmp/d20220414-99118-19dsb29/
    df: illegal option -- -
    usage: df [-b | -H | -h | -k | -m | -g | -P] [-ailn] [-T type] [-t] [filesystem ...]
  /private/tmp/d20220414-99118-19dsb29/repos/Directory.Build.targets(564,5): error MSB3073: The command "df --block-size=1M /private/tmp/d20220414-99118-19dsb29/" exited with code 64. [/private/tmp/d20220414-99118-19dsb29/repos/source-build-reference-packages.proj]
```

**Comment by Bo98** [comment]
Added an `inreplace` that I think covers it. Should be upstreamed if it works.

**Comment by Bo98** [comment]
GNU coreutils should support `-m`: https://github.com/coreutils/coreutils/blob/bcfbcef928cd540e53d35fc2869d9def2fedeb84/src/df.c#L1662

Alternative is the `BLOCKSIZE` environment variable.

**Comment by cho-m** [comment]
Error from trying to use system libunwind on macOS:
```
CMake Error at /tmp/d20220414-50201-dyxnox/src/runtime.be98e88c760526452df94ef452fff4602fb5bded/artifacts/source-build/self/src/eng/native/functions.cmake:109 (message):
          Cannot find libunwind.  Try installing libunwind8-dev or libunwind-devel.
```

**Comment by Bo98** [comment]
Odd since I assumed it was on by default: https://github.com/dotnet/runtime/blob/9c9ebb945eff9eb8fd02189ff93fb743235413c3/src/coreclr/pal/src/CMakeLists.txt#L3.

**Comment by cho-m** [comment]
Specifically, error is happening in https://github.com/dotnet/runtime/blob/v6.0.4/src/native/corehost/apphost/static/CMakeLists.txt#L214-L220
```cmake
# On *BSD, we always use the libunwind that's part of the OS
if(CLR_CMAKE_TARGET_FREEBSD)
  set(CLR_CMAKE_USE_SYSTEM_LIBUNWIND 1)
endif()

if(CLR_CMAKE_USE_SYSTEM_LIBUNWIND)
    find_unwind_libs(UNWIND_LIBS)
```

In other CMakeLists.txt, they avoid trying to find library on macOS https://github.com/dotnet/runtime/blob/v6.0.4/src/coreclr/pal/src/CMakeLists.txt#L19-L20
```cmake
elseif(NOT CLR_CMAKE_TARGET_OSX)
  find_unwind_libs(UNWIND_LIBS)
```

**Comment by Bo98** [comment]
libunwind lies in the system dylib and so does not require linker flags, which is why there's a macOS conditional (the else condition was added at a later time for some DWARF handling - it initially just no-oped).

I've pushed what I think the correct patch is - or it's at least consistent with how it worked in the past.

**Comment by Bo98** [comment]
Looks like we're now hitting https://github.com/dotnet/msbuild/issues/7229.

**Comment by cho-m** [comment]
> Looks like we're now hitting [dotnet/msbuild#7229](https://github.com/dotnet/msbuild/issues/7229).

May want to add patch as resource and copy into https://github.com/dotnet/installer/tree/v6.0.104/src/SourceBuild/tarball/patches/msbuild

**Comment by Bo98** [comment]
Patches upstreamed:
* https://github.com/dotnet/installer/pull/13653
* https://github.com/dotnet/runtime/pull/68116

**Comment by Bo98** [comment]
> Error from trying to use system libunwind on macOS

Seems like `CLR_CMAKE_USE_SYSTEM_LIBUNWIND` has changed recently to now only be supported on Linux (source-build used to set it for all OS unconditionally until https://github.com/dotnet/runtime/commit/b9f273a254f02038216295f49be77faa015036b5), so while it's not worth changing now since CI takes a while, for the next version it can be tidied up to just have a `if OS.linux?` conditional instead rather than fix the CMake logic.

**Review by cho-m — APPROVED** [review]
LGTM.
May need to figure out a `livecheck` in separate PR as default git tags will end up picking 6.0.2XX.

**Comment by Bo98** [comment]
> May need to figure out a `livecheck` in separate PR as default git tags will end up picking 6.0.2XX.

Seems like it would be something like:
* Scan https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json for the latest release not a preview or EOL.
* Get the specific release json (e.g. https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/6.0/releases.json), get the latest release there and find the oldest SDK for that release.

**Pull request closed without merging**
