### PR TITLE
libzt 1.3.4

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Duplicate of #73353.

**Comment by carlocab** [comment]
@dawidd6 is there a way to reduce the number of duplicates being opened? I think I close 2-3 duplicate PRs from the bump action a day these days.

**Comment by dawidd6** [comment]
@carlocab not much to do in the Action itself as it is a wrapper on `brew livecheck` + `brew bump-formula-pr`. Duplicates happen sometimes because GitHub search API lags behind and we use it to determine if there already are similar PRs created.

**Comment by carlocab** [comment]
@chenrui333 can you make your script run less often? I think that might help a bit with the search API lag.

**Pull request closed without merging**
