### PR TITLE
code-server 4.6.1-1

### PR DESCRIPTION
**Pull request by jsjoeio**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jsjoeio** [comment]
Done with my fixups!

**Comment by jsjoeio** [comment]
https://github.com/Homebrew/homebrew-core/runs/8213642274?check_suite_focus=true#step:4:1902

I'm not too sure why these errors are happening all of the sudden or how to fix them. Any ideasZ?

**Comment by jsjoeio** [comment]
I'm a bit perplexed at what's going on. Here is what's supposed to happen:
1. homebrew gets code-server from npm
2. homebrew runs `npm install --unsafe-perm --omit=dev`
3. that installs dependencies like `@coder/logger`

The only thing different between 4.6.0 and this release is we changed the command from `yarn` to `npm` and added some shrinkwrap stuff ([1](https://github.com/coder/code-server/pull/5071/files#diff-9efc23615796709119daa0db0050a3b67205c9c8ee6d23a2ef635a88958ae777), [2](https://github.com/coder/code-server/pull/5010/files#diff-471375dd1b99488272fffd0471bbd64b79dfd813b8d5b631b0f072a8ca40fcaa)).

In 4.6.0. the `node_modules` live at `/usr/local/Cellar/code-server/4.6.0/libexec/node_modules`. Not sure why they're missing with this version. I will continue investigating.

**Comment by jsjoeio** [comment]
I tried reproducing this locally without any luck.
1. download https://registry.npmjs.org/code-server/-/code-server-4.6.1-1.tgz
2. unpack and `cd package`
3. run `npm install --unsafe-perm --omit dev`
4. run `node . --extensions-dir=. --install-extension wesbos.theme-cobalt2`

I get a different error though:
```shell
Installing extensions...
connect ECONNREFUSED 127.0.0.1:3000
```

**Comment by jsjoeio** [comment]
One thing that's interesting to me is that `*Language::Node.std_npm_install_args` adds the `--global` flag, which didn't happen when we used `yarn`. I wonder if that's the issue here.

**Review by carlocab — APPROVED** [review]
Thanks! I've been meaning to look into this, but there are way too many PRs here. Glad you were able to work it out.

**Comment by jsjoeio** [comment]
> Thanks! I've been meaning to look into this, but there are way too many PRs here. Glad you were able to work it out.

No worries! Appreciate y'all for rebasing and having great docs! Have an awesome Thursday!

**Pull request closed without merging**
