### PR TITLE
dmd: testing Monterey linker failure

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Testing `dmd` issue from #98444

### CODE REVIEW

**Comment by Bo98** [comment]
Maybe try: https://github.com/dlang/dmd/commit/d06857e5cf430a566b78264a1635149ce864ed88

Also worth invesigating this:

```
  posix.mak:42: ===== DEPRECATION NOTICE ===== 
  posix.mak:43: ===== DEPRECATION: posix.mak is deprecated. Please use src/build.d instead.
  posix.mak:44: ============================== 
```

**Comment by cho-m** [comment]
> Also worth invesigating this:
> 
> ```
>   posix.mak:42: ===== DEPRECATION NOTICE ===== 
>   posix.mak:43: ===== DEPRECATION: posix.mak is deprecated. Please use src/build.d instead.
>   posix.mak:44: ============================== 
> ```

I think the build now needs to be bootstrapped. `./build.d` is supposed to use `dmd` from path.

We can either do this by:
1. use the official pre-builts, just like how we handle Java, Haskell, etc.
2. using another formula like `ldc`, which is what we do for SBCL. This is how ArchLinux does build

Probably 1st option would be needed on Linux, so might as well do it on macOS too.

**Comment by carlocab** [comment]
Could use `gdc` on Linux too.

**Comment by cho-m** [comment]
> Could use `gdc` on Linux too.

Potential risk would be `gdc` is part of `gcc` and has some chance of causes linkage to newer GCC libs. Though `ldc` does use `llvm@12`, but we haven't hit any linkage for macOS formulae that I switched to `ldc` (only system `/usr/lib/libSystem.B.dylib`).

**Comment by cho-m** [comment]
Current failure is pre-built for bootstrapping has the same issue, so it cannot build `dmd`. In this case, either need to wait for next release with new pre-builts or use `ldc`. May trying the latter first.

**Pull request closed without merging**
