### PR TITLE
mu: add dependency texinfo

### PR DESCRIPTION
**Pull request by tani**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

As I faced build errors when I try to install mu, I added this dependency.

### CODE REVIEW

**Comment by Bo98** [comment]
`texinfo` is included with macOS so can you clarify what build error you had?

**Comment by tani** [comment]
I see. When I install mu in **Ubuntu** with linuxbrew, I got some errors to build. Should I reopen this issue in Linuxbre-core?
As I know that linuxbrew maintainers sometimes recommend to open issue about an Fomula in `homebrew-core`, I created it. But this is linuxbrew specific error you said.

**Comment by Bo98** [comment]
In that case, you likely want `uses_from_macos "texinfo" => :build`. It is like a `depends_on` that only applies to Linux.

**Comment by tani** [comment]
Thank you for an advice! I'll transfer this issue to linuxbrew-core and close this issue.

**Comment by Bo98** [comment]
`uses_from_macos` can be submitted to homebrew-core, as long as you've tested it locally as we don't have Linux CI here.

**Comment by tani** [comment]
Give me a moment, I test it.

**Comment by tani** [comment]
@Bo98 Okay, I success to install mu locally. Thanks.

**Comment by SMillerDev** [comment]
Please squash your commits into one `mu: add texinfo dependency`

**Comment by tani** [comment]
@SMillerDev I have done it.

**Comment by Bo98** [comment]
The Linux maintainers merge periodically so you should see this in linuxbrew-core within the next day or two.

**Pull request merged**
