### PR TITLE
luarocks: build bottle for ARM

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Good. Sadly, it looks like all our luarockt formulas actually use luajit:

```
corsixth: unbottled deps: luajit luarocks
lmod: unbottled deps: luajit luarocks
neovim: unbottled deps: luajit luarocks
sile: unbottled deps: luajit luarocks
vis: unbottled deps: luajit luarocks
```

**Comment by carlocab** [comment]
Whoops. I was hoping there were some out there that actually depended on `lua`. Well, at least ARM users can get a `luarocks` bottle if they want one now...

**Comment by carlocab** [comment]
@fxcoudert something's wrong with that list. Only `neovim` actually depends on `luajit`; the rest do not. I've dispatched bottle jobs for them already.

**Comment by carlocab** [comment]
```
==> FAILED
Uninstalling cmake... (6,376 files, 62.3MB)
Uninstalling lua... (28 files, 459.8KB)
Error: No such file or directory @ realpath_rec - /opt/homebrew/Cellar/lua
```
Weird. Will try again.

**Pull request closed without merging**
