### PR TITLE
geode: fix to use secure url

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by vszakats** [comment]
Hm, unexpected:
```
==> Downloading https://www.apache.org/dyn/closer.cgi?filename=incubator/geode/1.0.0-incubating.M2/apache-geode-1.0.0-incubating.M2.tar.gz&action=download
Error: invalid byte sequence in UTF-8
Please report this bug:
    https://git.io/brew-troubleshooting
```
The URL works fine when testing it locally with both curl and wget.

**Comment by UniqMartin** [comment]
> The URL works fine when testing it locally with both curl and wget.

Have you tried locally with `brew fetch`? We're using a custom `CurlApacheMirrorDownloadStrategy` for Apache URLs. It attempts to download a JSON file with information about mirrors and uses that to select a suitable mirror. Apparently there's either an issue with that JSON file or with the way we infer the URL for that JSON file from the original download URL.

It seems that for this “magic” behavior to work correctly, the URL needs to be `https://www.apache.org/dyn/closer.cgi?path=incubator/geode/1.0.0-incubating.M2/apache-geode-1.0.0-incubating.M2.tar.gz` which I inferred by looking at other formulae with Apache-hosted downloads.

Somewhat unrelated, but I wonder if we should bother to make that change. I can see that HTTPS is desirable, but the official download link on the project page is HTTP and the HTTPS download link still redirects to some insecure URL, thus it doesn't improve the situation significantly. (Feel free to ignore me if this discussion has been had before and I missed it.)

**Comment by DomT4** [comment]
Can reproduce locally. Martin's suggested URL is the correct one.

> Somewhat unrelated, but I wonder if we should bother to make that change. I can see that HTTPS is desirable, but the official download link on the project page is HTTP and the HTTPS download link still redirects to some insecure URL, thus it doesn't improve the situation significantly. (Feel free to ignore me if this discussion has been had before and I missed it.)

A long time ago now, but the decision was reached to support this kind of thing alongside implementing the feature that tells users where redirects are happening. We already did so for Apache, it was just introduced for everything else as well for clarity.

**Comment by vszakats** [comment]
Thank you folks. I'll go with Martin's URL. The strange thing is that this was the first URL I tested, but for some reason didn't work locally &mdash; most likely due to some stupid mistake on my part.

**Comment by UniqMartin** [comment]
Merged in 07d77e224438db4e24e301b21bdcc2dae88a0b8e. Thank you for another contribution to Homebrew, @vszakats! :tada:

**Pull request closed without merging**
