### PR TITLE
faust 2.69.3

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
need a long build for another run

**Comment by chenrui333** [comment]
> Looks like it didn't need a long build?

https://github.com/Homebrew/homebrew-core/actions/runs/6877700742/attempts/1
image

this did timeout in the first attempt

**Review by chenrui333 — APPROVED** [review]

**Comment by p-linnane** [comment]
arm64 runners have a 45 minute timeout, while x86_64 has 90 minutes.

**Review by p-linnane — APPROVED** [review]

**Comment by p-linnane** [comment]
Yeah if a job on arm64 needs more than 45 minutes the odds are very good it will need more than 90 on x86_64. For this, `faust` was probably pulled from the bottle cache on the last run, and this latest run only had to build `csound`.

**Comment by chenrui333** [comment]
needs a rebase and re-bottle due to the merge conflict with csound py3.12 update, https://github.com/Homebrew/homebrew-core/pull/154412

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
`csound` rebuilt and published at Homebrew/homebrew-core#154880.

**Pull request merged**
