### PR TITLE
nvc 1.5.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
I think we can switch this from `llvm@11` to `llvm`. Don't forget the `llvm@11` reference in the `install` method.

**Comment by carlocab** [comment]
Nope, failed to build. [Upstream CI](https://github.com/nickg/nvc/blob/5f56922030ee9fc9aa8028b8dd7df408f3a86d58/.github/workflows/build-test.yml#L43) uses the `llvm` formula though.

Maybe we also need the `--enable-vhpi` flag?

**Comment by nandahkrishna** [comment]
Still fails, checked locally as well.

**Comment by carlocab** [comment]
Very weird. Can we try running `autogen` unconditionally? We'll need to move the deps out of the `head` block though.

**Comment by nandahkrishna** [comment]
That results in the same error 😅:
```
==> make
Last 15 lines from /Users/nanda/Library/Logs/Homebrew/nvc/04.make:
  AR       lib/libfst.a
  CXXLD    bin/nvc
Undefined symbols for architecture x86_64:
  "_LLVMInitializeX86AsmPrinter", referenced from:
      _cgen in libcgen.a(lib_libcgen_a-cgen.o)
  "_LLVMInitializeX86Target", referenced from:
      _cgen in libcgen.a(lib_libcgen_a-cgen.o)
  "_LLVMInitializeX86TargetInfo", referenced from:
      _cgen in libcgen.a(lib_libcgen_a-cgen.o)
  "_LLVMInitializeX86TargetMC", referenced from:
      _cgen in libcgen.a(lib_libcgen_a-cgen.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [bin/nvc] Error 1
make: *** [all] Error 2
```

**Comment by nandahkrishna** [comment]
The `--HEAD` build works fine and passes all tests. I think https://github.com/nickg/nvc/commit/251e18d4560a43ce25ff48ca07c5e186dc3399e6 is required.

**Comment by carlocab** [comment]
I've gotten the tarball to build with llvm 12. Issue may not be that. Just poking at it some more.

**Comment by carlocab** [comment]
Tried building outside of `brew`. Encountered the same error as in this PR. Then, I tried applying the change at #76646 (just do `ln -s $(brew --prefix llvm)/lib/libLLVM.dylib $(brew --prefix llvm)/lib/libLLVM-12.dylib`). This allows me to build successfully outside of `brew`.

When I try to build with `brew` using a patched `llvm` as in #76646, the build fails, except with a different error, which shows up later in the build:
```
  NVC      lib/ieee/IEEE.STD_LOGIC_MISC
ld: file too small (length=0) file '/private/tmp/nvc-20210514-18670-17vg8it/nvc-1.5.1/lib/nvc/_NVC.ENV-body.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
** Fatal: /usr/bin/clang failed with status 1
make[1]: *** [lib/nvc/NVC.ENV] Error 1
```
Seems related to this step
https://github.com/Homebrew/homebrew-core/blob/e1bbe4490b16a46689fc17f74140f8720fe4edf6/Formula/nvc.rb#L34
as I didn't run it when I tried building outside of `brew`.

**Comment by carlocab** [comment]
Oops, no it's not. Looks like the step I highlighted above doesn't do anything:
```
❯ ./tools/fetch-ieee.sh
The IEEE standard library sources are now included in the repository for
convenience. They can also be download from the IEEE SA:

  https://standards.ieee.org/content/dam/ieee-standards/standards/web/download/

Note that the license forbids the distribution of modifications.
```

**Comment by carlocab** [comment]
I don't really understand why deparallelizing the build helps here. I've tried several times now to build outside of `brew` with `make -j4` and I can't reproduce the build failure.

**Comment by carlocab** [comment]
Let's try a parallel build here. Maybe my computer just sucks.

**Comment by nandahkrishna** [comment]
Works now 🎉, this should be good to go?

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
