### PR TITLE
libqalculate 3.16.1

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
This is an update only for `libqalculate`. `qalculate-gtk` has not been updated. See https://qalculate.github.io

**Comment by chenrui333** [comment]
maybe we can wait a bit?

**Comment by carlocab** [comment]
It looks like it was on purpose:

>.: 2021-01-09 :. Qalculate! version 3.16.1 released
>
>This version primarily fixes an issue which may cause the deletion of all user data for data sets. qalculate-gtk has not been updated.

This ships a bugfix, so I think it's better not to wait.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Sounds good!

**Pull request closed without merging**
