### PR TITLE
zplug 2.0.0 (new formula)

### PR DESCRIPTION
**Pull request by NigoroJr**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
### Description

zplug is a next-generation plugin manager for zsh.

I've triple-checked the cookbook, but please let me know if I'm doing anything wrong and I'll fix that ASAP.

### CODE REVIEW

**Comment by NigoroJr** [comment]
Hmm... I wonder why the test is failing. It says it can't find target `test`, but I can definitely run it on my machine.

**Comment by UniqMartin** [comment]
> Hmm... I wonder why the `test` is failing. It says it can't find target test, but I can definitely run it on my machine.

That's because the test runs after the installation and starts off with an empty directory. You no longer have access to the sources and what was built, except for the things that have been installed to `prefix`.

**Comment by NigoroJr** [comment]
Ah, I see. Should I remove the `test` part of the formula then? Or make it so that it's somewhere along the line of:

```zsh
shell_output("zsh -c \"source #{opt_prefix}/init.zsh && (( $+functions[zplug] ))\"")
```

like pyenv?

**Comment by mikemcquaid** [comment]
@NigoroJr A test like that looks good 👍

**Comment by NigoroJr** [comment]
Thanks, @mikemcquaid. I have updated the tests and rerun `brew audit`. Let's see how the it comes out this time...

**Comment by apjanke** [comment]
Success!

Merged in 9eaf1fd119def5b79b4d376ac0443e71cf6f04a4. Thank you for your contribution to Homebrew!

For future reference, we prefer that PRs like this be squashed to a single commit, to maintain a tidy commit history. Homebrew gets a _lot_ of commits. For this PR, I squashed the commits while pulling them in.

**Comment by NigoroJr** [comment]
Thanks for merging!

> we prefer that PRs like this be squashed to a single commit

Gotcha. I'll keep that in mind!

**Pull request closed without merging**
