### PR TITLE
shadowsocks-libev 3.0.5

### PR DESCRIPTION
**Pull request by icpz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by lcdtyph** [comment]
@ilovezfs 
Sorry but how could I fix this ?

```Error Message

failed: brew pull --clean https://github.com/Homebrew/homebrew-core/pull/11400
Stacktrace

        ==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-core/pull/11400.patch
==> Applying patch
Applying: shadowsocks-libev 3.0.5
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
error: Unable to create '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git/logs/refs/remotes/origin/pr/3416/merge.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
error: failed to run reflog
Resolve operation not in progress, we are not resuming.
Error: Patch failed to apply: aborted.```

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by lcdtyph** [comment]
@ilovezfs Thanks!

**Comment by fxcoudert** [comment]
Thanks @lcdtyph for your contribution to Homebrew!

**Pull request closed without merging**
