### PR TITLE
mongodb 3.6.0

### PR DESCRIPTION
**Pull request by ehershey**

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
`stable do` block should be removed since stable is now the only spec in the formula.

**Comment by ilovezfs** [comment]
Also the versioned symlink needs to be renamed mongodb@3.4 -> mongodb@3.6 in Aliases directory

**Comment by ehershey** [comment]
Thanks, @ilovezfs. I made the changes you requested.

**Comment by ehershey** [comment]
Fixed whitespace style error

**Comment by lafama** [comment]
Will this fix this issue
```
1. brew install mongodb --devel
2. Error: mongodb 3.4.10 is already installed
3. To upgrade to 3.6.0, run `brew upgrade mongod`
```

**Comment by ilovezfs** [comment]
@lafama it will but actually you just need to
```
brew upgrade mongodb --devel
```

**Comment by Ben305** [comment]
Seems ready to go, doesn't it?

**Comment by lafama** [comment]
@ilovezfs  Thank you. This worked

**Comment by alcaeus** [comment]
Question: should the current formula be kept as `mongodb@3.4`, similar to 2.6, 3.0 and 3.2?

**Comment by ilovezfs** [comment]
Thanks for the PR @ehershey! I'm going to close this in favor of https://github.com/Homebrew/homebrew-core/pull/21523 which also has a new mongodb@3.4 included and some of the remaining style issues fixed.

**Pull request closed without merging**
