### PR TITLE
bazel 0.19.0

### PR DESCRIPTION
**Pull request by mandrean**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by apjanke** [comment]
Build failed.

Error log excerpt:

```
ERROR: /private/tmp/bazel-20181029-7568-1qx9q2p/sources/src/java_tools/junitrunner/java/com/google/testing/junit/runner/util/BUILD:5:1: Compiling Java headers src/java_tools/junitrunner/java/com/google/testing/junit/runner/util/libutil-hjar.jar (16 files) failed (Exit 1) java failed: error executing command external/embedded_jdk/bin/java -Xverify:none -XX:+UseParallelOldGC -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' ... (remaining 54 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Unrecognized VM option 'CompactStrings'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

This "Unrecognized VM option 'CompactStrings'" error sounds like it's using a Java 9+ option when running against a Java 8 JRE/JDK. Or maybe that option was removed for Java 11; the build box has Java 8 and Java 11.

```
Java: 11, 1.8.0_181
```

**Comment by apjanke** [comment]
I was able to get the build working by changing the formula to use Java 9 or 11:

```
  depends_on :java => "9"
...
      bin.env_script_all_files(libexec/"bin", Language::Java.java_home_env("9"))
```
or
```
  depends_on :java => "11"
...
      bin.env_script_all_files(libexec/"bin", Language::Java.java_home_env("11"))
```

A quick glance around the Bazel docs suggests they're currently targeting Java 9, and [don't have Java 10 or 11 support yet](https://github.com/bazelbuild/bazel/issues/5723). (But I don't know if that lack of support means that you can't build Bazel with Java 10/11, or just that you can't build Java 10/11 stuff with Bazel.) This might be an issue for Homebrew since we don't have Java 9 on the CI boxes, apparently.

**Comment by mandrean** [comment]
@apjanke Good investigations. But where did you find the docs about them targeting Java 9?

From what I can see, the docs say Java 8? https://docs.bazel.build/versions/master/install-compile-source.html

>*Build Bazel from scratch (bootstrapping)*
>*2.1.* Install the prerequisites
>* JDK 8. You must install version 8 of the JDK. Versions other than 8 are not supported.

**Comment by apjanke** [comment]
Perhaps that doc is out of date? I shouldn't have said "docs"; I was looking in the bug tracker and directly at the [default_java_toolchain.bzl](https://github.com/bazelbuild/bazel/blob/917d0cd725aa6c796573dbafd3cb78ec484ee40a/tools/jdk/default_java_toolchain.bzl) file used during the bootstrap build, which sure looks like it's defaulting to JDK9.

```
DEFAULT_TOOLCHAIN_CONFIGURATION = {
...
   "jvm_opts": JDK9_JVM_OPTS,
```

But Bazel's complicated and I'm no expert; I may be misunderstanding it.

Oh look, here's an upstream bug report about what looks like this exact same problem on Linux! https://github.com/bazelbuild/bazel/issues/6550

**Comment by katre** [comment]
Actually, sorry, I don't know what I need to do to update the formula. Is this something you can help me figure out? I'm the Bazel release manager for thre 0.19.0 release but I am not a Mac user.

**Comment by apjanke** [comment]
Thanks @katre!

> Actually, sorry, I don't know what I need to do to update the formula. Is this something you can help me figure out? 

I think you can just change the `"1.8"`s to `"9"` or `"11"` in the formula in this PR, like so:

```
--- a/Formula/bazel.rb
+++ b/Formula/bazel.rb
@@ -11,7 +11,7 @@ class Bazel < Formula
     sha256 "2d0d0b81b801212fddc912f934c8f1327306021786231f9a80e4ae42589f3f76" => :sierra
   end

-  depends_on :java => "1.8"
+  depends_on :java => "11"
   depends_on :macos => :yosemite

   def install
@@ -28,7 +28,7 @@ class Bazel < Formula

       bin.install "scripts/packages/bazel.sh" => "bazel"
       bin.install "output/bazel" => "bazel-real"
-      bin.env_script_all_files(libexec/"bin", Language::Java.java_home_env("1.8"))
+      bin.env_script_all_files(libexec/"bin", Language::Java.java_home_env("11"))

       bash_completion.install "bazel-bin/scripts/bazel-complete.bash"
       zsh_completion.install "scripts/zsh_completion/_bazel"
```

(This might be our first formula that requires Java 9 or 11, so I'm not sure which the Homebrew maintainers would prefer. Probably 11, because it's the one that's currently supported by Oracle/OpenJDK?)

I think @mandrean needs to do that since this here is his PR. Or maybe one can make a PR to the PR?

**Comment by apjanke** [comment]
I created a PR on this PR; I hope that's the right procedure.

https://github.com/mandrean/homebrew-core/pull/1

**Comment by apjanke** [comment]
Sorry to be a pesterer, but would you mind squashing the commits in this PR to a single commit, to keep the future Homebrew commit history tidy?

**Comment by mandrean** [comment]
So, homebrew team, any status on when build servers gets to have Java 11?

**Comment by apjanke** [comment]
FWIW, I also remember getting this same build failure when trying to build Bazel locally on my machine that has all of JDK 1.7, 1.8, 9, 10, and 11 installed. (OpenJDK for Java 11, not Oracle JDK, but that shouldn't make any difference.)

**Comment by apjanke** [comment]
Here's the similar, but more readable, error I get when building Bazel 0.19.0 on my local Mac:

```
ERROR: /Users/janke/tmp/bazel/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/BUILD:15:1: Building src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libdependency.jar (3 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed (Exit 1): java failed: error executing command
  (cd /var/folders/_4/9mx5ryp52bb_z6drbcbrhwl40000gn/T/bazel_lFsP4NPx/out/execroot/io_bazel && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  external/embedded_jdk/bin/java -Xmx512m -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -jar bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_VanillaJavaBuilder_deploy.jar @bazel-out/darwin-opt/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libdependency.jar-0.params)
src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/dependency/StrictJavaDepsPlugin.java:180: error: incompatible types: int cannot be converted to com.sun.tools.javac.code.Lint.LintCategory
note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 199.954s, Critical Path: 79.93s, Remote (0.00% of the time): [queue: 0.00%, setup: 0.00%, process: 0.00%]
INFO: 1074 processes: 1009 local, 65 worker.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
```

That mentions running annotation processors. Perhaps it is related to this prior INFO item which pops up a few times:

```
INFO: From JavacBootstrap src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar [for host]:
warning: Implicitly compiled files were not subject to annotation processing.
  Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.
```

**Comment by apjanke** [comment]
I think this looks like an upstream issue in Bazel 0.19.0, not your formula change or Homebrew's build system, and have reported it upstream at https://github.com/bazelbuild/bazel/issues/6590.

**Comment by apjanke** [comment]
I steered you wrong: per https://github.com/bazelbuild/bazel/issues/6590#issuecomment-435658131, Bazel does not support Java 11 yet. (It uses JDK internals, so it is in fact tied to the earlier JDK version.) You'll need to change those `"11"`s to `"9"`s. Sorry.

**Comment by mandrean** [comment]
Alright! No worries. Pushed changes.

**Comment by katre** [comment]
@apjanke Sorry, I should have noted that and flagged it. Thanks everyone for the help with this.

**Comment by SMillerDev** [comment]
@apjanke any idea what's going wrong now?

**Comment by apjanke** [comment]
Here's the [error message](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/32919/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/install_bazel/):

```
ERROR: /private/tmp/bazel-20181104-38474-1dju6q1/sources/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/BUILD:15:1: Building src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libdependency.jar (3 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed (Exit 1): java failed: error executing command 
  (cd /private/tmp/bazel_NRcCWtzU/out/execroot/io_bazel && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
  external/embedded_jdk/bin/java -Xmx512m -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -jar bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_VanillaJavaBuilder_deploy.jar @bazel-out/darwin-opt/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/libdependency.jar-0.params)
3 actions running
    .../com/google/devtools/build/importdeps:import_deps_checker; 0s worker
    .../com/google/devtools/build/buildjar/javac/plugins:dependency; 0s worker
    //third_party/jarjar:jarjar_command; 0s worker

src/java_tools/buildjar/java/com/google/devtools/build/buildjar/javac/plugins/dependency/StrictJavaDepsPlugin.java:180: error: incompatible types: int cannot be converted to com.sun.tools.javac.code.Lint.LintCategory
note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
3 actions running
    .../com/google/devtools/build/importdeps:import_deps_checker; 0s worker
    .../com/google/devtools/build/buildjar/javac/plugins:dependency; 0s worker
    //third_party/jarjar:jarjar_command; 0s worker

```

This looks like the same thing I saw in https://github.com/bazelbuild/bazel/issues/6590. That was caused by bootstrapping against JDK 11 instead of 9. Looks like this is somehow calling the `javac` from JDK 11 even though your formula specifies 9 in the `depends_on :java` line.

I can reproduce this on my local machine with JDKs 8, 9, and 11 installed.

I think this is a bug in `brew`, not an issue with your formula. Check out [the `initialize` code for `JavaRequirement`](https://github.com/Homebrew/brew/blob/d06795fd79bd21832305dbd9182a5283f150e2ba/Library/Homebrew/requirements/java_requirement.rb#L28-L31):

```
  def initialize(tags = [])
    puts "initialize(#{tags})"
    @version = tags.shift if /(\d+\.)+\d/ =~ tags.first
    super(tags)
  end
```

That `/(\d+\.)+\d/` is requiring the Java version tag to be in the form `<X>.<Y>`. But Java version 9 and higher do not have a dot in their versions; they may be single numbers now. So it's silently ignoring the `"9"`, and falling back to the default JDK on the machine, which is JDK 11. I think this means that Java version requirements higher than 8 are currently being ignored by `brew`.

I will report this as a bug against `brew`.

**Comment by apjanke** [comment]
And once that's fixed, I think we're going to have the problem that Java 9 is not installed on the CI machines.

**Comment by jmhodges** [comment]
Would be great to see this happen!

**Comment by SMillerDev** [comment]
@apjanke should this pass CI now?

**Comment by igas** [comment]
0.19.2 been released, I think we should update this MR

@mandrean can you do this please?

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
CI is now passing but that's because this isn't being run. Can someone confirm that Bazel cannot work with either Java 11 or Java 8? If so, I guess we'll just remove it from Homebrew.

**Comment by hcoona** [comment]
@igas @apjanke @mandrean The brew built version of bazel 0.20.0 doesn't support JDK 9 while the official released version does.

The built version:
```
$ env JAVA_HOME=(/usr/libexec/java_home -version 9) bazel build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java9 --java_toolchain=@bazel_tools//tools/jdk:toolchain_java9 //...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 5646fbb2-8374-4e47-860a-4203d2a48caa
INFO: Analysed target ... (25 packages loaded, 592 targets configured).
INFO: Found 1 target...
ERROR: .../BUILD:13:1: Building ... (1 source file) failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /.../0926d26bc16597f859f8bcd601adcfa7/bazel-workers/worker-0-Javac.log ---8<---8<---
Unrecognized VM option 'CompactStrings'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
---8<---8<--- End of log ---8<---8<---
Target //... failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.801s, Critical Path: 0.88s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

$ bazel version
INFO: Invocation ID: 90330171-5f2a-4971-a0d1-830166271577
Build label: 0.20.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Nov 30 20:40:12 2018 (1543610412)
Build timestamp: 1543610412
Build timestamp as int: 1543610412
```

The official released version (https://github.com/bazelbuild/bazel/releases/tag/0.20.0)
```
~/Downloads/bazel-0.20.0-darwin-x86_64 build --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java9 --java_toolchain=@bazel_tools//tools/jdk:toolchain_java9 //...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: a813738b-d53d-49fa-8316-ca36a77f79e7
INFO: Analysed target //... (25 packages loaded, 481 targets configured).
INFO: Found 1 target...
Target //... up-to-date:
  bazel-bin/...
  bazel-bin/...
INFO: Elapsed time: 19.653s, Critical Path: 7.72s
INFO: 4 processes: 3 darwin-sandbox, 1 worker.
INFO: Build completed successfully, 7 total actions

$ ~/Downloads/bazel-0.20.0-darwin-x86_64 version
INFO: Invocation ID: db7189c8-58be-4780-89fa-f8e94b042916
Build label: 0.20.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Nov 30 14:38:25 2018 (1543588705)
Build timestamp: 1543588705
Build timestamp as int: 1543588705
```

**Comment by igas** [comment]
@hcoona your snippet using prebuilt binary while brew compiles from source. If you know how to build bazel to the same binary with java 8 or 11 PR would be much appreciated.

**Comment by hcoona** [comment]
@igas It's the point that our build is somehow different with the official one. I wonder why we don't use the officially prebuilt one?

I didn't know much about the building bazel, but I think there should be some guides in the bazel project. Maybe we could peek the build process from the bazel CI.

**Comment by igas** [comment]
bazel using jdk that is not on brew CI, so we pass some additional flags, which may be incorrect as I'm not familiar with bazel itself. Regarding building from source you can read more [here in the docs](https://docs.brew.sh/Acceptable-Formulae)

**Comment by igas** [comment]
> I think there should be some guides in the bazel project.
there are https://docs.bazel.build/versions/master/install-compile-source.html#bootstrap-unix-prereq but they are outdated, as it errors with jdk8 and changelog says it's jdk9/10 depending on latest versions.

**Pull request closed without merging**
