### PR TITLE
micro 1.1.4

### PR DESCRIPTION
**Pull request by zyedidia**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@zyedidia are you considering using a go vendor directory in the future? That would be great from a downstream perspective.

Also, in the absence of vendoring, currently "make build" is running
```
==> make build
go get -d ./cmd/micro
```
which could potentially invoke a naked `go get` if someone fails to fully update the resource blocks in the future.

Do you mind changing it to use `make build-quick`, which appears to skip the deps target?

**Comment by zyedidia** [comment]
I have considered using govendor at various points but I never really put in the time to actually use it in the project. Honestly I think it's unlikely that I switch to govendor, especially considering that an official dependency management system for Go might be coming soon.

I have now switched the install to use `build-quick` instead of `build`.

**Comment by ilovezfs** [comment]
Thanks!

>considering that an official dependency management system for Go might be coming soon

cool

**Comment by ilovezfs** [comment]
Shipped! Thanks @zyedidia

**Pull request closed without merging**
