### PR TITLE
gdal 3.6.0 cfitsio 4.2.0

### PR DESCRIPTION
**Pull request by mistydemeo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This is an alternate take on #115583. gdal now uses cmake exclusively, and the old buildsystem is gone. The majority of the build options we had to specify before are no longer relevant in this new version; they're pulled in automatically without explicit configuration options.

It'd be useful to get someone with experience with the package to ensure that all expected behaviour is here. It passes `brew test` though.

I had to revision bump all of its dependents because the dylib revision was increased.

cc @chenrui333

### CODE REVIEW

**Comment by kylebarron** [comment]
Thanks for starting this! I don't know anything about homebrew packaging, but would love to see this update, so let me know if I can help somehow.

Also in GDAL 3.5 and 3.6, GDAL has added some optional support for connecting to [Apache Arrow](https://arrow.apache.org/). From the GDAL docs it [looks like](https://gdal.org/development/building_from_source.html#arrow) it will be picked up automatically if arrow is on the host system. So I'd guess adding that would be as simple as a new `depends_on "apache-arrow"` line?  I'd love to see that as part of the homebrew; I can make a PR for that if that's simpler

**Comment by mistydemeo** [comment]
Thank you! I appreciate having input from someone familiar with gdal. I'll see if I can add that.

**Comment by mistydemeo** [comment]
Pushed an update with Arrow. It picked it up and built with it.

**Comment by cho-m** [comment]
On Linux, Python libs are being written into `HOMEBREW_PREFIX/lib` directly probably due to Homebrew's Python 3.10+ patch. This seems to be happening during CMake build so either need to disable Python bindings there or add a work around similar to other formulae:
```
  running install_lib
  creating /home/linuxbrew/.linuxbrew/lib/python3.10/site-packages/osgeo_utils
  copying build/lib.linux-x86_64-cpython-310/osgeo_utils/pct2rgb.py -> /home/linuxbrew/.linuxbrew/lib/python3.10/site-packages/osgeo_utils
  copying build/lib.linux-x86_64-cpython-310/osgeo_utils/rgb2pct.py -> /home/linuxbrew/.linuxbrew/lib/python3.10/site-packages/osgeo_utils
```

This then conflicts with copy that is built in separate step:
```
  creating /home/linuxbrew/.linuxbrew/Cellar/gdal/3.6.0/lib/python3.10/site-packages/osgeo_utils
  copying build/lib.linux-x86_64-cpython-310/osgeo_utils/pct2rgb.py -> /home/linuxbrew/.linuxbrew/Cellar/gdal/3.6.0/lib/python3.10/site-packages/osgeo_utils
  copying build/lib.linux-x86_64-cpython-310/osgeo_utils/rgb2pct.py -> /home/linuxbrew/.linuxbrew/Cellar/gdal/3.6.0/lib/python3.10/site-packages/osgeo_utils
```

---

On side note, was Homebrew supposed to be allowed to write directly into `HOMEBREW_PREFIX/lib` during `install` block?

**Comment by mistydemeo** [comment]
Sorry for the delay, been on vacation this week. I'll push an attempted fix soon.

**Comment by mistydemeo** [comment]
> On side note, was Homebrew supposed to be allowed to write directly into `HOMEBREW_PREFIX/lib` during `install`?

I certainly didn't think so.

**Comment by chenrui333** [comment]
Maybe we can also merge [cfitsio 4.2.0](https://github.com/Homebrew/homebrew-core/pull/115970) into here to save some build time.

**Comment by mistydemeo** [comment]
Good idea. Please make sure not to remove the `CI-long-timeout` label though, it needs that!

**Comment by chenrui333** [comment]
> Good idea. Please make sure not to remove the `CI-long-timeout` label though, it needs that!

I will add that, right now there are some concurrency issue (we only allow two PRs tagged with that label at one time), so that label technically does not work.

**Comment by SMillerDev** [comment]
If this PR is not running it should not have that label since that will prevent any other slow builds from running.

**Comment by chenrui333** [comment]
rebased the PR and kicked a run

**Comment by chenrui333** [comment]
Some minor issue with `siril` build

```
  Error: The `brew link` step did not complete successfully
  Could not symlink include/exiv2/basicio.hpp
  Target /opt/homebrew/include/exiv2/basicio.hpp
  is a symlink belonging to dronedb. You can unlink it:
    brew unlink dronedb
  
  To force the link and overwrite all conflicting files:
    brew link --overwrite exiv2
  
  To list all files that would be deleted:
    brew link --overwrite --dry-run exiv2
  
  Possible conflicting files are:
  /opt/homebrew/include/exiv2/basicio.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/basicio.hpp
  /opt/homebrew/include/exiv2/bmffimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/bmffimage.hpp
  /opt/homebrew/include/exiv2/bmpimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/bmpimage.hpp
  /opt/homebrew/include/exiv2/config.h -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/config.h
  /opt/homebrew/include/exiv2/convert.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/convert.hpp
  /opt/homebrew/include/exiv2/cr2image.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/cr2image.hpp
  /opt/homebrew/include/exiv2/crwimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/crwimage.hpp
  /opt/homebrew/include/exiv2/datasets.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/datasets.hpp
  /opt/homebrew/include/exiv2/easyaccess.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/easyaccess.hpp
  /opt/homebrew/include/exiv2/epsimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/epsimage.hpp
  /opt/homebrew/include/exiv2/error.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/error.hpp
  /opt/homebrew/include/exiv2/exif.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/exif.hpp
  /opt/homebrew/include/exiv2/exiv2.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/exiv2.hpp
  /opt/homebrew/include/exiv2/exiv2lib_export.h -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/exiv2lib_export.h
  /opt/homebrew/include/exiv2/exv_conf.h -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/exv_conf.h
  /opt/homebrew/include/exiv2/futils.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/futils.hpp
  /opt/homebrew/include/exiv2/gifimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/gifimage.hpp
  /opt/homebrew/include/exiv2/http.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/http.hpp
  /opt/homebrew/include/exiv2/image.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/image.hpp
  /opt/homebrew/include/exiv2/ini.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/ini.hpp
  /opt/homebrew/include/exiv2/iptc.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/iptc.hpp
  /opt/homebrew/include/exiv2/jp2image.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/jp2image.hpp
  /opt/homebrew/include/exiv2/jpgimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/jpgimage.hpp
  /opt/homebrew/include/exiv2/metadatum.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/metadatum.hpp
  /opt/homebrew/include/exiv2/mrwimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/mrwimage.hpp
  /opt/homebrew/include/exiv2/orfimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/orfimage.hpp
  /opt/homebrew/include/exiv2/pgfimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/pgfimage.hpp
  /opt/homebrew/include/exiv2/pngimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/pngimage.hpp
  /opt/homebrew/include/exiv2/preview.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/preview.hpp
  /opt/homebrew/include/exiv2/properties.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/properties.hpp
  /opt/homebrew/include/exiv2/psdimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/psdimage.hpp
  /opt/homebrew/include/exiv2/quicktimevideo.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/quicktimevideo.hpp
  /opt/homebrew/include/exiv2/rafimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/rafimage.hpp
  /opt/homebrew/include/exiv2/rw2image.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/rw2image.hpp
  /opt/homebrew/include/exiv2/slice.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/slice.hpp
  /opt/homebrew/include/exiv2/tags.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/tags.hpp
  /opt/homebrew/include/exiv2/tgaimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/tgaimage.hpp
  /opt/homebrew/include/exiv2/tiffimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/tiffimage.hpp
  /opt/homebrew/include/exiv2/types.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/types.hpp
  /opt/homebrew/include/exiv2/value.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/value.hpp
  /opt/homebrew/include/exiv2/version.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/version.hpp
  /opt/homebrew/include/exiv2/webpimage.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/webpimage.hpp
  /opt/homebrew/include/exiv2/xmp_exiv2.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/xmp_exiv2.hpp
  /opt/homebrew/include/exiv2/xmpsidecar.hpp -> /opt/homebrew/Cellar/dronedb/1.0.11_1/include/exiv2/xmpsidecar.hpp
  /opt/homebrew/share/man/man1/exiv2.1 -> /opt/homebrew/Cellar/dronedb/1.0.11_1/share/man/man1/exiv2.1
  Error: Could not symlink lib/cmake/exiv2/exiv2Config-release.cmake
  Target /opt/homebrew/lib/cmake/exiv2/exiv2Config-release.cmake
  is a symlink belonging to dronedb. You can unlink it:
    brew unlink dronedb
  
  To force the link and overwrite all conflicting files:
    brew link --overwrite dronedb
  
  To list all files that would be deleted:
    brew link --overwrite --dry-run dronedb
```

**Comment by chenrui333** [comment]
symlink conflict btw exiv2 and dronedb
```
  Error: The `brew link` step did not complete successfully
  Could not symlink include/exiv2/basicio.hpp
  Target /opt/homebrew/include/exiv2/basicio.hpp
  is a symlink belonging to dronedb. You can unlink it:
    brew unlink dronedb
  
  To force the link and overwrite all conflicting files:
    brew link --overwrite exiv2
  
  To list all files that would be deleted:
    brew link --overwrite --dry-run exiv2
```

**Comment by chenrui333** [comment]
Filed an issue for the dronedb build

**Comment by chenrui333** [comment]
need a rebase for `poppler 22.11.0` and `dronedb fix`

**Comment by mistydemeo** [comment]
Rui, please let me know if you plan to push commits to my PR - otherwise it might introduce conflicts in what I'm working on.

**Comment by chenrui333** [comment]
> Rui, please let me know if you plan to push commits to my PR - otherwise it might introduce conflicts in what I'm working on.

I can push right now.

**Comment by chenrui333** [comment]
I am done

**Comment by chenrui333** [comment]
`siril` now builds/tests out fine in my local.

**Comment by chenrui333** [comment]
> Rui, please let me know if you plan to push commits to my PR - otherwise it might introduce conflicts in what I'm working on.

let me know if you are up for a new run.

**Comment by kylebarron** [comment]
does this just need to be tested again? We need to wait for the `ci-long-timeout` badge to be available again?

**Comment by mistydemeo** [comment]
There's currently two PRs up with "long timeout". I'll get this running when one finishes.

**Comment by fxcoudert** [comment]
Further revisions needed: `dronedb gmt mapserver osmcoastline pdal`

**Comment by chenrui333** [comment]
Should be good now

**Review by chenrui333 — DISMISSED** [review]

**Comment by mistydemeo** [comment]
Linux failure in siril:

```
algos/siril_wcs.c:32:10: fatal error: wcslib.h: No such file or directory
[1683](https://github.com/Homebrew/homebrew-core/actions/runs/3615463926/jobs/6092661960#step:7:1690)
     32 | #include <wcslib.h>
[1684](https://github.com/Homebrew/homebrew-core/actions/runs/3615463926/jobs/6092661960#step:7:1691)
        |          ^~~~~~~~~~
```

Looks like it needs `wcslib`. Added as a dep.

**Comment by SMillerDev** [comment]
```
 `brew linkage --cached --test --strict gdal` failed on macOS Ventura (13) on Apple Silicon!

Files with missing rpath:
  /opt/homebrew/Cellar/gdal/3.6.0/lib/python3.10/site-packages/osgeo/_gdal.cpython-310-darwin.so
  /opt/homebrew/Cellar/gdal/3.6.0/lib/python3.10/site-packages/osgeo/_gdal_array.cpython-310-darwin.so
  /opt/homebrew/Cellar/gdal/3.6.0/lib/python3.10/site-packages/osgeo/_gdalconst.cpython-310-darwin.so
  /opt/homebrew/Cellar/gdal/3.6.0/lib/python3.10/site-packages/osgeo/_gnm.cpython-310-darwin.so
  /opt/homebrew/Cellar/gdal/3.6.0/lib/python3.10/site-packages/osgeo/_ogr.cpython-310-darwin.so
  /opt/homebrew/Cellar/gdal/3.6.0/lib/python3.10/site-packages/osgeo/_osr.cpython-310-darwin.so
```

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
`Error: Bottles are for cpl 7.2.2_1 but formula is version 7.2.3_1!`

**Comment by chenrui333** [comment]
unfortunately need another run due to the version bumps of the formulae.

**Review by chenrui333 — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
Would be good to know if some of the new dependencies for the dependents aren't just opportunistic linkage.

**Pull request closed without merging**
