### PR TITLE
gnu-getopt 2.37.1

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
==> Pouring hardlink--0.3.0.x86_64_linux.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /home/linuxbrew/.linuxbrew
Could not symlink bin/hardlink
Target /home/linuxbrew/.linuxbrew/bin/hardlink
is a symlink belonging to util-linux. You can unlink it:
  brew unlink util-linux

To force the link and overwrite all conflicting files:
  brew link --overwrite hardlink

To list all files that would be deleted:
  brew link --overwrite --dry-run hardlink

Possible conflicting files are:
/home/linuxbrew/.linuxbrew/bin/hardlink -> /home/linuxbrew/.linuxbrew/Cellar/util-linux/2.37/bin/hardlink
/home/linuxbrew/.linuxbrew/share/man/man1/hardlink.1 -> /home/linuxbrew/.linuxbrew/Cellar/util-linux/2.37/share/man/man1/hardlink.1
```

**Comment by miccal** [comment]
Thank you @dawidd6.

**Comment by carlocab** [comment]
A bunch of the errors look like
```
Error: Failed to install service files
```

**Review by SMillerDev — APPROVED** [review]
Only a linux hardlink failure remaining, I think this can be merged

**Pull request closed without merging**
