### PR TITLE
fix distcc url

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by zmwangx** [comment]
Could you please ask them to tag releases on GitHub? (For the record, I've seen https://github.com/distcc/distcc/issues/159.)

Also, `distcc 3.2rc1` was added four years ago in 28289ed, in the relatively early days of Homebrew. Nowadays we're unlikely to accept `rc1` as stable. We probably need an actual stable release, or boneyard (it is in the least installed camp anyway).

**Comment by yurikoles** [comment]
@zmwangx so we need to move it to boneyard? 
Also, I have problems building HEAD on Sierra.

**Comment by zmwangx** [comment]
We need to talk to upelstream first, some are very cooperative (not this one I'm afraid, but it doesn't hurt to try). But I'd even head won't build — that's a bigger problem.

**Comment by yurikoles** [comment]
Here is upstream issue I had reported https://github.com/distcc/distcc/issues/197

**Comment by zmwangx** [comment]
What about another issue regarding releases? Thanks.

**Comment by yurikoles** [comment]
Here it is: https://github.com/Homebrew/homebrew-core/issues/4958

**Comment by zmwangx** [comment]
@yurikoles No, not an issue on our issue tracker... We're not release managers for distcc.

**Comment by yurikoles** [comment]
@zmwangx please merge, as it's minor edit just to keep distcc formulae working.

**Comment by zmwangx** [comment]
Actually no, I'd rather see the whole situation sorted out or directly throw it to boneyard, sorry. I don't think this require an urgent fix. You can always install your changes locally, by the way.

**Comment by yurikoles** [comment]
Sorry, I had forgot to mention: current link to source code returns 404 since Google Code site is discontinued.

**Comment by zmwangx** [comment]
I know, and still, I don't think it's an urgent issue given the negligible install event count.

**Comment by yurikoles** [comment]
For example, It's impossible to install current distcc formula on Sierra, since its provides no bottle nor source code.

**Comment by zmwangx** [comment]
Yeah, and it's not an urgent issue, as I said. Consider it dead before the underlying issue is resolved. No point in downloading from Debian if you can't download it from an official source.

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
