### PR TITLE
istioctl 1.6.4

### PR DESCRIPTION
**Pull request by rytswd**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
+ cp -R /private/tmp/istioctl-20200701-6543-14fwa68/src/istio.io/istio/operator/scripts/../data/examples /private/tmp/istioctl-20200701-6543-14fwa68/src/istio.io/istio/operator/scripts/../data/translateConfig /private/tmp/istioctl-20200701-6543-14fwa68/src/istio.io/istio/operator/scripts/../data/versions.yaml /var/folders/g4/hmj3z8n96sb6nldr3_0gm7040000gp/T/istio-charts.XXXXXXXXXX.8ahJEP2C
+ cd /var/folders/g4/hmj3z8n96sb6nldr3_0gm7040000gp/T/istio-charts.XXXXXXXXXX.8ahJEP2C
+ go-bindata --nocompress --nometadata --pkg vfs -o /private/tmp/istioctl-20200701-6543-14fwa68/src/istio.io/istio/operator/scripts/../../operator/pkg/vfs/assets.gen.go ./...
+ rm -Rf /var/folders/g4/hmj3z8n96sb6nldr3_0gm7040000gp/T/istio-charts.XXXXXXXXXX.8ahJEP2C
Skipping envoy debug. Set DEBUG_IMAGE to download.
/private/tmp/istioctl-20200701-6543-14fwa68/src/istio.io/istio/out/linux_amd64/release /private/tmp/istioctl-20200701-6543-14fwa68/src/istio.io/istio
Downloading Envoy: curl -fLSs https://storage.googleapis.com/istio-build/proxy/envoy-alpha-80ad06b26b3f97606143871e16268eb036ca7dcd.tar.gz to /private/tmp/istioctl-20200701-6543-14fwa68/src/istio.io/istio/out/linux_amd64/release/envoy-80ad06b26b3f97606143871e16268eb036ca7dcd
curl: (22) The requested URL returned error: 404 
make: *** [/private/tmp/istioctl-20200701-6543-14fwa68/src/istio.io/istio/out/darwin_amd64/istio_is_init] Error 22
```

**Comment by chenrui333** [comment]
tested in my local, should be good.

With that being said, rebased to master and kick off a new run.

**Comment by rytswd** [comment]
Ah sorry missed this, thank you for the help @chenrui333 !

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@rytswd no problem at all.

**Pull request closed without merging**
