### PR TITLE
openssl: remove support for universal build

### PR DESCRIPTION
**Pull request by andrewying**
macOS is now 64-bit only and thus the previous 32-bit options & universal options are removed

Apologies for any error in advance: new contributor...

### CODE REVIEW

**Comment by fxcoudert** [comment]
While dropping universal build is OK, we want to keep 32-bit support where it is already existent. See how this was done in #11784 (which was never merged because it triggered a failure in `osc`).

**Comment by ilovezfs** [comment]
@andrewying @fxcoudert I still think this is something we should do. I was unaware #11784 had been dropped.

**Comment by fxcoudert** [comment]
Dropping universal is OK. Removing 32-bit build probably not (and it's easy to keep it).  To be honest, I had forgotten about #117784 I thought it had been merged at some point :)

**Comment by ilovezfs** [comment]
>Removing 32-bit build probably not

Please elaborate.

**Comment by fxcoudert** [comment]
```
[fx:/usr … homebrew-core/Formula] master ± grep -l prefer_64_bit *|wc -l
      76
```

**Comment by ilovezfs** [comment]
Yeah. I'm not totally sure why those haven't been axed yet.

**Comment by fxcoudert** [comment]
We removed universal support in a consistent manner. I'm happy for us to remove 32-bit support if it is decided and we do so consistently. Right now, it does not look like it ;)

**Comment by ilovezfs** [comment]
@fxcoudert so to be clear, there's no reason here other than `MacOS.prefer_64_bit?` hasn't been formally deprecated yet with an audit?

**Comment by fxcoudert** [comment]
Yeah, I'd rather we have a uniform policy :)
But if it's decided, I'm happy to help phase out 32-bit support.

**Comment by MikeMcQuaid** [comment]
CC @mistydemeo as the 32-bit stuff may be for Tigerbrew. If not: cool.

**Comment by andrewying** [comment]
@ilovezfs: yeah I'm just not sure how exactly I can deal with the error for `osc` - a bit lost there...

**Comment by ilovezfs** [comment]
@andrewying the osc thing has been going on in CI for a long time and is unrelated to this PR.

**Comment by andrewying** [comment]
Oh... so will the new commit be alright (assuming everything else is alright for the build)?

**Comment by fxcoudert** [comment]
Many thanks @andrewying for this pull request!

**Pull request merged**
