### PR TITLE
gdbm 1.24

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by bevanjkay — APPROVED** [review]

**Comment by chenrui333** [comment]
still in progress

**Review by bevanjkay — APPROVED** [review]

**Review by iMichka — CHANGES_REQUESTED** [review]
Not sure that going through the Ukrainian website is the best option here. Especially that this a fully different domain, so are we sure who is the owner of https://www.gnu.org.ua ?

**Comment by chenrui333** [comment]
@iMichka I feel it is fine, it is owned by @graygnuorg

whois info, https://www.whois.com/whois/gnu.org.ua

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
I see, there is a redirection from https://www.gnu.org/software/gdbm/ to https://www.gnu.org.ua/software/gdbm/, ok for me

**Comment by chenrui333** [comment]
Thanks!

**Pull request merged**
