### PR TITLE
glog 0.6.0

### PR DESCRIPTION
**Pull request by yurikoles**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by yurikoles** [comment]
A lot of revision bumps, runners need more time. Please add label `long build`.

**Comment by yurikoles** [comment]
Rebased and force-pushed to trigger rebuild, last one failed due to unrelated error on GH:
```
Stable: The source URL https://github.com/facebook/watchman/archive/v2022.03.21.00.tar.gz is not reachable (HTTP status code 500)
```

**Comment by yurikoles** [comment]
Unrelated error on Linux while building `folly`:

```
  /tmp/folly-20220411-41345-17tqgft/folly-2022.03.21.00/folly/init/Init.cpp:79:34: error: invalid conversion from 'void (*)() noexcept' to 'google::logging_fail_func_t' {aka 'void (*)() __attribute__((noreturn))'} [-fpermissive]
     79 |   google::InstallFailureFunction(abort);
        |                                  ^~~~~
        |                                  |
        |                                  void (*)() noexcept
  In file included from /tmp/folly-20220411-41345-17tqgft/folly-2022.03.21.00/folly/init/Init.cpp:19:
  /home/linuxbrew/.linuxbrew/include/glog/logging.h:642:61: note:   initializing argument 1 of 'void google::InstallFailureFunction(google::logging_fail_func_t)'
    642 | GLOG_EXPORT void InstallFailureFunction(logging_fail_func_t fail_func);
        |                                         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
```

Could you please enable `CI-no-fail-fast` to at least isolate Linux?

**Comment by cho-m** [comment]
`folly` error on Linux is definitely due to `glog` changes to function declarations and will need an upstream fix in `folly` before we can merge this PR.

Related `glog` changes: https://github.com/google/glog/commit/0b83bb203d0e6d0b3f351d76306d41bf928e72ac

---

The failure only happens on Linux because the corresponding code is only enabled there, i.e.

https://github.com/facebook/folly/blob/v2022.04.11.00/folly/init/Init.cpp#L77-L79
```c
#if FOLLY_USE_SYMBOLIZER
  // Don't use glog's DumpStackTraceAndExit; rely on our signal handler.
  google::InstallFailureFunction(abort);
```

https://github.com/facebook/folly/blob/v2022.04.11.00/CMake/folly-deps.cmake#L177-L179
```cmake
if (NOT WIN32 AND NOT APPLE)
  set(FOLLY_USE_SYMBOLIZER ON)
endif()
```

**Comment by yurikoles** [comment]
Reported: https://github.com/facebook/folly/issues/1759

**Comment by yurikoles** [comment]
Whoops, I failed to respond on time. Please reopen.

**Comment by chenrui333** [comment]
@yurikoles just reopened it and also cancelled the build, feel free to add some patch and trigger a new run.

**Comment by yurikoles** [comment]
We need a `CI-long-timeout` here.

**Comment by yurikoles** [comment]
@chenrui333 could you please review ported patch? https://github.com/Homebrew/formula-patches/pull/858

**Comment by yurikoles** [comment]
All checks passed.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
