### PR TITLE
awscli 2.7.9

### PR DESCRIPTION
**Pull request by doeber**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
    ImportError: /tmp/pip-build-env-j1qi9gh_/normal/lib/python3.9/site-packages/_awscrt.cpython-39-x86_64-linux-gnu.so: undefined symbol: EVP_aead_aes_128_gcm_tls13
    error: subprocess-exited-with-error
```

**Comment by chenrui333** [comment]
same error
```
        import _awscrt
    ImportError: /tmp/pip-build-env-peudepdw/normal/lib/python3.9/site-packages/_awscrt.cpython-39-x86_64-linux-gnu.so: undefined symbol: EVP_aead_aes_128_gcm_tls13
    error: subprocess-exited-with-error
```

**Comment by cho-m** [comment]
The workaround I added to avoid Homebrew's OpenSSL in build environment didn't work in newer `awscrt`.

It looks like they are now using `self.build_temp`, which adds another subdirectory (`temp.linux-x86_64-3.9`) as seen in logs:
`-- Installing: /tmp/awscli--awscrt-20220618-30023-15nc410/awscrt-0.13.11/build/temp.linux-x86_64-3.9/deps/install/lib/libcrypto.a`

Updating the path should work, though I am not sure if there is an easy way to get path without having to manually construct from OS/Arch/PythonVersion.

Alternatively, could try modifying build environment to avoid `openssl@1.1` libraries, which exist due to Python dependency and how Homebrew's environment is set up.

---

I believe this is only seen on Linux as the particular feature is only enabled there.

**Comment by danielnachun** [comment]
I think using `temp.linux-x86_64-#{Language::Python.major_minor_version}` is an acceptable fix here - his is a pretty standard triple format.

**Review by danielnachun — APPROVED** [review]
This is fixed now.

**Pull request closed without merging**
