### PR TITLE
yarn 1.17.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by igas** [comment]
Thank you @chenrui333!

**Comment by MikeN123** [comment]
1.17.0 is a pre-release, not a stable.

**Comment by alaycock** [comment]
Can this be reverted, I'd prefer to be on the stable branch, not a pre-release branch.

**Comment by fxcoudert** [comment]
Reverted in 9efcd2625a5f18b3d184a4aee1e1b58cedad6b99
@chenrui333 before bumping formulas please check that they're stable releases

**Comment by chenrui333** [comment]
yeah, we have comment added into the formula code, so I dont think it would happen next time.

**Comment by fxcoudert** [comment]
I mean not only `yarn`, it should be a general rule: if you open a PR (by hand or through `bump-formula-pr`), you need to check that it's a stable version. It is a manual step, and it has to be done.

**Comment by chenrui333** [comment]
Sure, but I do think the stable version vs pre-release is not used consistently across the repos. 

For example, I know some repo is always using pre-release (could not remember the exact name off my head). Yeah, but if they do have the naming convention of stable is always preferred, we should do it.

**Comment by chenrui333** [comment]
We are also using yarn, but not the latest though.

**Comment by chenrui333** [comment]
Sounds like we might want to add this check into the `brew bump-formula-pr` process as well.

**Comment by SMillerDev** [comment]
It's not something that can always be determined by looking at Github, nor do Github releases always mean that something is actually released. You as a user of bump-formula-pr have to check that your bump is correct.

**Pull request closed without merging**
