### PR TITLE
sysdig 0.31.3

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

A follow-up to #123507. Marking as draft because I haven't got it to work yet.

Previous attempt: #116224. Logs were lost, unfortunately.

### CODE REVIEW

**Comment by carlocab** [comment]
```
  [ 16%] Built target re2
``` 
https://github.com/Homebrew/homebrew-core/actions/runs/4445842080/jobs/7805568977?pr=125925#step:7:592

suspicious

**Comment by ZhongRuoyu** [comment]
> suspicious

Ahem, thanks; I was specifically looking at the Linux build so I missed that. [`valijson` too](https://github.com/Homebrew/homebrew-core/actions/runs/4445842080/jobs/7805568977?pr=125925#step:7:115):

```
  -- Found tbb: include: /opt/homebrew/include/tbb, lib: /opt/homebrew/lib/libtbb.dylib
  -- Found jsoncpp: include: /opt/homebrew/include, lib: /opt/homebrew/lib/libjsoncpp.dylib
  -- Using bundled valijson in '/tmp/sysdig-20230317-6959-19a87v8/sysdig-0.30.2/build/valijson-prefix/src/valijson'
  -- Using bundled re2 in '/tmp/sysdig-20230317-6959-19a87v8/sysdig-0.30.2/build/re2-prefix/src/re2'
  -- Using jsoncpp: include: /opt/homebrew/include, lib: /opt/homebrew/lib/libjsoncpp.dylib
  -- Found LuaJIT: include: /opt/homebrew/include/luajit-2.1, lib: /opt/homebrew/lib/libluajit.dylib
  -- Found yamlcpp: include: /opt/homebrew/include, lib: /opt/homebrew/lib/libyaml-cpp.dylib
  -- Found njson: include: /opt/homebrew/include
```

**Comment by carlocab** [comment]
```
  /Applications/Xcode.app/Contents/Developer/usr/bin/make -C /lib/modules/22.3.0/build M=/tmp/sysdig-20230318-7321-gnyv8z/sysdig-0.30.2/build/driver/src modules
  make: *** /lib/modules/22.3.0/build: No such file or directory.  Stop.
```
https://github.com/Homebrew/homebrew-core/actions/runs/4456660398/jobs/7827293630?pr=125925#step:7:170

Almost definitely a bug in the `Makefile`.

**Comment by ZhongRuoyu** [comment]
That's [this one](https://github.com/falcosecurity/libs/blob/0.9.1/driver/Makefile.in#L14-L16):

```makefile
TOP := $(shell pwd)
all:
	$(MAKE) -C $(KERNELDIR) M=$(TOP) modules
```

Though I have no idea why it was invoked on macOS, because it's supposed to be guarded by [this](https://github.com/falcosecurity/libs/blob/0.9.1/CMakeLists.txt#L57-L70):

```cmake
if(CMAKE_SYSTEM_NAME MATCHES "Linux" AND USE_BUNDLED_DRIVER)
	# Driver version
	if(NOT DEFINED DRIVER_VERSION)
		get_drivers_version(DRIVER_VERSION)
	endif()

	message(STATUS "Driver version: ${DRIVER_VERSION}")

	add_subdirectory(driver ${PROJECT_BINARY_DIR}/driver)
endif()

if(NOT CMAKE_BUILD_TYPE)
	SET(CMAKE_BUILD_TYPE Release)
endif()
```

**Comment by carlocab** [comment]
`-DUSE_BUNDLED_DRIVER=OFF`? I'd download the logs and check the CMake cache to see what `CMAKE_SYSTEM_NAME` is.

**Comment by ZhongRuoyu** [comment]
> I'd download the logs and check the CMake cache to see what `CMAKE_SYSTEM_NAME` is.

That's not in `CMakeCache.txt`. But I see no `CMAKE_SYSTEM_NAME` overrides (otherwise that'd be a sign of cross-compiling), so it really should be `Darwin`. (Played around with this locally.)

> `-DUSE_BUNDLED_DRIVER=OFF`?

`CMakeCache.txt` does suggest this though:

```cmake
USE_BUNDLED_DRIVER:BOOL=OFF
```

That should be controlled by [this](https://github.com/draios/sysdig/blob/0.30.2/cmake/modules/falcosecurity-libs.cmake#L24-L25), where `falcosecurity` is added as a module:

```cmake
# explicitly disable the bundled driver, since we pull it separately
set(USE_BUNDLED_DRIVER OFF CACHE BOOL "")
```

(The comment is not true because we do have `FALCOSECURITY_LIBS_SOURCE_DIR` set; nothing is pulled.)

**Comment by ZhongRuoyu** [comment]
The macOS issue should be unrelated to the Linux one. I'll revisit both locally.

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
