### PR TITLE
liblzf 3.6 (new formula)

### PR DESCRIPTION
**Pull request by John-Colvin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by UniqMartin** [comment]
This library has been last updated over five years ago, so I'm not sure it meets our [criteria for only including actively maintained software](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#niche-or-self-submitted-stuff). It seems simple enough that it can get away with few and infrequent updates, but five years is still a very long time. Can you elaborate a little bit on why we would want to have this formula in Homebrew and/or why my reasoning doesn't apply? Thanks!

**Comment by mikemcquaid** [comment]
If it works without patching and has a good test I'm 🆗 with it being included.

**Comment by John-Colvin** [comment]
It's had more recent activity in the cvs repository (I think mainly performance improvements, didn't look too thoroughly though), but for whatever reason they haven't made a release.

**Comment by UniqMartin** [comment]
> If it works without patching and has a good test I'm :ok: with it being included.

It does and I guess it's not going to be a big troublemaker. Also the fact that there's upstream activity in the repository is encouraging.

Merged in 37371300ffeadb67062c5772f806e79f0d5ac4a2. Thank you for another contribution to Homebrew, @John-Colvin! :tada:

**Pull request closed without merging**
