### PR TITLE
dosbox-x 0.83.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
 clang++ -DHAVE_CONFIG_H -I. -I..  -I../include "-DRESDIR=\"/usr/local/Cellar/dosbox-x/0.83.3/share/dosbox-x\"" -Wno-int-to-void-pointer-cast   -Wno-address-of-packed-member   -Wno-format-zero-length   -Wno-missing-field-initializers   -Wno-strict-aliasing   -Wno-implicit-fallthrough   -Wno-deprecated-declarations   -Wconversion-null   -Wsign-promo   -Wlogical-op   -pedantic   -Wunused   -Wextra   -Wall  -I/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/libpng/linux-host/include -I/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/zlib/linux-host/include  -I/usr/local/include -I/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/sdl/linux-host/include/SDL -D_GNU_SOURCE=1 -D_THREAD_SAFE -I/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/sdlnet/linux-host/include -I/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/sdlnet/linux-host/include/SDL  -I/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/libpng/linux-host/include -I/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/zlib/linux-host/include -std=gnu++11  -O2 -msse  -Wall   -Wextra   -Wunused   -pedantic   -Wlogical-op   -Wsign-promo   -Wconversion-null   -Wno-deprecated-declarations   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast  -I/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/sdlnet/linux-host/include -I/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/sdlnet/linux-host/include/SDL  -c -o dosbox.o dosbox.cpp
 clang++  -I/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/libpng/linux-host/include -I/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/zlib/linux-host/include -std=gnu++11  -O2 -msse  -Wall   -Wextra   -Wunused   -pedantic   -Wlogical-op   -Wsign-promo   -Wconversion-null   -Wno-deprecated-declarations   -Wno-implicit-fallthrough   -Wno-strict-aliasing   -Wno-missing-field-initializers   -Wno-format-zero-length   -Wno-address-of-packed-member   -Wno-int-to-void-pointer-cast  -I/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/sdlnet/linux-host/include -I/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/sdlnet/linux-host/include/SDL   -L/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/libpng/linux-host/lib -L/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/zlib/linux-host/lib  -L/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/sdlnet/linux-host/lib -o dosbox-x dosbox.o  debug/libdebug.a dos/libdos.a shell/libshell.a builtin/libbuiltin.a ints/libints.a misc/libmisc.a hardware/serialport/libserial.a hardware/parport/libparallel.a libs/porttalk/libporttalk.a gui/libgui.a libs/gui_tk/libgui_tk.a hardware/libhardware.a cpu/libcpu.a hardware/reSID/libresid.a fpu/libfpu.a gui/libgui.a output/liboutput.a hardware/mame/libmame.a libs/zmbv/libzmbv.a aviwriter/libaviwriter.a  xBRZ/libxbrz.a mt32/libmt32.a -L/private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/sdl/linux-host/lib /private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/sdl/linux-host/lib/libSDLmain.a /private/tmp/dosbox-x-20200701-25276-26eldd/dosbox-x-dosbox-x-v0.83.3/vs2015/sdl/linux-host/lib/libSDL.a -Wl,-framework,OpenGL -Wl,-framework,Cocoa -Wl,-framework,ApplicationServices -Wl,-framework,Carbon -Wl,-framework,AudioToolbox -Wl,-framework,AudioUnit -Wl,-framework,IOKit -framework Carbon -framework CoreFoundation -framework CoreMIDI -framework AudioUnit -framework AudioToolbox -framework ApplicationServices -framework AppKit -lncurses -lz -lpng -lz -lpcap -lfluidsynth -framework OpenGL
 Making all in include
 make[2]: Nothing to be done for `all'.
 make[2]: Nothing to be done for `all-am'.
 [34m==>[0m [1mmake install[0m
 install -D -d /usr/local/Cellar/dosbox-x/0.83.3/bin
 install: illegal option -- D
 usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
                [-o owner] file1 file2
        install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
                [-o owner] file1 ... fileN directory
        install -d [-v] [-g group] [-m mode] [-o owner] directory ...
 make: *** [install] Error 64
```

**Comment by SeekingMeaning** [comment]
Fix: joncampbell123/dosbox-x#1715

Temporary fix: `inreplace "Makefile.am", "install -D -d", "install -d"`

**Comment by SMillerDev** [comment]
Please use the PR to patch it.

**Comment by SeekingMeaning** [comment]
Pull request was merged and should be in next release :tada:

**Comment by SeekingMeaning** [comment]
This can be closed now

**Pull request closed without merging**
