### PR TITLE
buildozer 4.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
duplicate PR

**Comment by carlocab** [comment]
```
ERROR: /private/var/tmp/_bazel_brew/a89ee758951f33c806bb204a3ec68497/external/zlib/BUILD.bazel:31:11: Compiling adler32.c failed: (Exit 1): wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 32 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 32 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
clang: error: unknown argument: '-fdebug-compilation-dir'
```

**Comment by chenrui333** [comment]
relates to bazelbuild/bazel#12882

**Comment by carlocab** [comment]
Would the same patch as in #70328 work here?

**Comment by chenrui333** [comment]
yeah, it should be the same patch (as the error is the same)

**Pull request closed without merging**
