### PR TITLE
xorgproto 2023.1

### PR DESCRIPTION
**Pull request by chiefmikey**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Error: The `brew link` step did not complete successfully
Could not symlink share/man/man3/Regexp.3
Target /opt/homebrew/share/man/man3/Regexp.3
is a symlink belonging to tcl-tk. You can unlink it:
  brew unlink tcl-tk

To force the link and overwrite all conflicting files:
  brew link --overwrite ivtools

To list all files that would be deleted:
  brew link --overwrite --dry-run ivtools
```

**Comment by carlocab** [comment]
@gromgit, suggestions for dealing with the `brew link` conflict quoted above? Rename `RegExp.3` to `Tcl_RegExp.3`, maybe?

**Comment by gromgit** [comment]
I'd be more inclined to adopt the Debian/Ubuntu approach, and rename all `.3` to `.3tcl`. This preserves the expected names that developers would run `man` on, and they can always be explicit about section numbers if they're targeting the Tcl version.

I'll put out a PR for Tcl that does the above shortly.

**Comment by gromgit** [comment]
May be a good time to rerun CI, now that the manpage issue has been resolved?

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
None of the failures seem related

**Pull request merged**
