### PR TITLE
llvm@9: use elfutils on Linux

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
We should be able to automerge this and just rebuild the bottles. Oldest bottle is Mojave anyway.

**Review by SMillerDev — DISMISSED** [review]

**Comment by iMichka** [comment]
You really need to bump the revision for Linux as you are changing a dependency. As the dependency tree is computed based on installed formulae / what's inside the bottle (and not from the .rb file), if you install the old llvm@11 bottle on Linux, you will still end up with the wrong dependency tree.

**Comment by SMillerDev** [comment]
Doesn't this also update the bottles?

**Comment by cho-m** [comment]
I thought a rebuild would upload the new bottles.

If we actually have some Linux users in `homebrew-core`, then the revision bump should be mandatory. In case that we haven't started userbase migration (i.e. publicly-visible instructions on migrating, updated install scripts, etc), then it may be possible to just keep rebuilding the bottles until then.

In the case of core merger, bumping revision doesn't make it easier here as `llvm@9` already has a large revision spread between cores: `revision OS.mac? ? 2 : 6`.

**Comment by iMichka** [comment]
Right. A bottle rebuild is enough :)

**Review by iMichka — DISMISSED** [review]

**Comment by cho-m** [comment]
Not sure why bottle upload keeps failing. It happened twice now. Since we have uploaded other `llvm` bottles recently, it shouldn't be the size.

I am considering rebasing and re-run CI at this point to recreate the bottles in case something is corrupt:
```
==> Uploading llvm@9--9.0.1_2.mojave.bottle.3.tar.gz
==> Uploading llvm@9--9.0.1_2.catalina.bottle.3.tar.gz
==> Uploading llvm@9--9.0.1_2.big_sur.bottle.3.tar.gz
Error: Failure while executing; `/home/linuxbrew/.linuxbrew/bin/brew pr-upload --debug --committer=BrewTestBot\ \<1589480\+BrewTestBot@users.noreply.github.com\> --root-url=https://ghcr.io/v2/homebrew/core` was terminated by uncaught signal KILL.
```

**Comment by iMichka** [comment]
Rebasing is probably the thing to do.

**Review by SMillerDev — DISMISSED** [review]

**Comment by cho-m** [comment]
Same issue. I don't know what is happening with GitHub packages. One more simple attempt would be a revision bump.

**Comment by cho-m** [comment]
I was hoping to try an isolated revision bump, but it looks like there is a dependent formula `oclgrind` that references the versioned Cellar path. The quick attempt would be to bump that revision, but the better fix would be to find a way to use `opt_lib` path install.
```
==> /usr/local/Cellar/oclgrind/19.10_3/bin/oclgrind ./rot13 2>&1
1 error generated.
fatal error: malformed or corrupted AST file: 'could not find file '/usr/local/Cellar/llvm@9/9.0.1_2/lib/clang/9.0.1/include/opencl-c-base.h' referenced by AST file '/usr/local/Cellar/oclgrind/19.10_3/lib/../include/oclgrind//opencl-c-1.2-64.pch''
```

Though, it looks like `oclgrind` doesn't even have a Big Sur bottle, so not sure if trying to rebuild will work.

**Comment by cho-m** [comment]
Still failed with revision bumps.

May be something wrong with Homebrew's logic/tools or a problem in GitHub package.

**Comment by cho-m** [comment]
Trying in new PR #84825 to see if it helps.

**Pull request closed without merging**
