### PR TITLE
bagit: move to python version

### PR DESCRIPTION
**Pull request by chenrui333**
Move to bagit-python

---

previous PR #56973

### CODE REVIEW

**Review by mistydemeo — DISMISSED** [review]

**Comment by chenrui333** [comment]
Since this is a formula rewrite, reset the version.

**Comment by SMillerDev** [comment]
I think I'd prefer a new formula with `bagit-python` and a formula_renames entry where you delete the current version. That will make it clearer for users.

**Review by MikeMcQuaid — DISMISSED** [review]
> I think I'd prefer a new formula with `bagit-python` and a formula_renames entry where you delete the current version. That will make it clearer for users.

I would normally agree but in this case where the previous was called `bagit-java` and they are both made my the same organisation I think it does make sense in this case to just alter the existing formula.

**Review by MikeMcQuaid — DISMISSED** [review]

**Comment by Bo98** [comment]
This is already merged: https://github.com/Homebrew/homebrew-core/commit/b200ed376eba806fa6074a3a30b7a7dfb5b529ab

**Pull request closed without merging**
