### PR TITLE
misc formulae: switch postgresql dependency to libpq

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by MikeMcQuaid — DISMISSED** [review]
Thanks for this, great work! Feel free to 🚢 this before https://github.com/Homebrew/homebrew-core/pull/107726 and I'll rebase.

**Comment by carlocab** [comment]
We might also want to consider making `libpq` not-keg-only.

**Comment by MikeMcQuaid** [comment]
> We might also want to consider making `libpq` not-keg-only.

This seems like a good idea, assuming the conflicts with `brew install postgres@14` aren't too gnarly.

**Comment by bayandin** [comment]
Dropping from the PR extension that requires real PostgreSQL:
- `citus`
- `pg_cron`
- `pg_partman`
- `pgroonga`
- `postgis`
- `temporal_tables`
- `wal2json`

**Review by MikeMcQuaid — DISMISSED** [review]

**Comment by Bo98** [comment]
> Dropping from the PR extensions that require real PostgreSQL:
> 
> * `citus`
> * `pg_cron`
> * `pg_partman`
> * `pgroonga`
> * `postgis`
> * `temporal_tables`
> * `wal2json`

Would be good to investigate at some point whether it's possible to make them version-agnostic, since they defeat the point of making PostgreSQL versioned only.

**Comment by bayandin** [comment]
`brew test --verbose qt-postgresql` fails on Linux, looks like a preexisting one, and should be fixed by https://github.com/Homebrew/homebrew-core/pull/107400

**Review by SMillerDev — DISMISSED** [review]

**Pull request closed without merging**
