### PR TITLE
formulae: add linux only dependencies

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
`zip, unzip, libedit, openssl@1.1` seems to be allowed to be put as `uses_from_macos`:

https://github.com/Homebrew/brew/blob/7d78949479d2673d6c3453d5bde069a16b110e2d/Library/Homebrew/rubocops/uses_from_macos.rb#L62

Or am I reading this list wrong?

**Comment by iMichka** [comment]
I checked, you are right for 3:
uses_from_macos "libedit"
uses_from_macos "zip"
uses_from_macos "unzip"

These two are used like this everywhere:
depends_on "xz"
depends_on "openssl@1.1"

This is because on Mac we want to use the brewed versions instead of the system version. I think because our openssl is newer, and because our xz contains lzma, which the system one does not (if I recall well).

I'll update the PR accordingly

**Comment by dawidd6** [comment]
But in this case where we put `depends_on` in `on_linux` block it's actually the same as putting it in `uses_from_macos`. Both solutions are no-op on macOS.

**Comment by iMichka** [comment]
Regarding: `depends_on "openssl@1.1"`: you can't really use `uses_from_macos "openssl@1.1"`, because that should be `uses_from_macos "openssl@1.0"` I guess, which is an older version. I think this might be confusing.

I agree it is a no-op. Maybe we should just plain `depends_on "openssl@1.1"` in this case, without the `on_linux` block. I am unsure as why this dependency is only needed on linux: does the library just use openssl on linux but not on Mac? How do I convey that message with the DSL? Or does it silently link against system openssl on Mac? In this case we should be using `depends_on "openssl@1.1"` with the `on_linux` block.

Regarding `xz`, it is sort of the same idea: it is maybe just needed on Linux but non on Mac? Who knows.

So either we keep these two in `on_linux` blocks, or we remove the `on_linux` blocks and make it a plain Mac dependency, even if the Mac build might not need it.

**Comment by dawidd6** [comment]
Yep, I would guess it links against macOS provided openssl.

**Comment by iMichka** [comment]
I think I will just use a plain depends_on for the openssl/xz formulae, that's easier and this is what we probably already have done in some places.

**Pull request merged**
