### PR TITLE
haskell-stack 2.5.1, bond 9.0.4

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Picks up from https://github.com/Homebrew/homebrew-core/pull/62939, https://github.com/Homebrew/homebrew-core/pull/65587

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Nice work!

**Comment by chenrui333** [comment]
try to build for arm as well.

**Comment by carlocab** [comment]
We can't; no `ghc` for arm yet 😞

**Comment by carlocab** [comment]
Reopening to restart tests without ARM.

**Comment by chenrui333** [comment]
Got you.

**Pull request closed without merging**
