### PR TITLE
bareos-client 20.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
[ 94%] Linking CXX static library libfd_objects.a
cd /tmp/bareos-client-20201218-97550-18xsbo2/bareos-Release-20.0.0/build/core/src/filed && /usr/local/Cellar/cmake/3.19.1/bin/cmake -P CMakeFiles/fd_objects.dir/cmake_clean_target.cmake
cd /tmp/bareos-client-20201218-97550-18xsbo2/bareos-Release-20.0.0/build/core/src/filed && /usr/local/Cellar/cmake/3.19.1/bin/cmake -E cmake_link_script CMakeFiles/fd_objects.dir/link.txt --verbose=1
/usr/bin/ar qc libfd_objects.a CMakeFiles/fd_objects.dir/accurate.cc.o CMakeFiles/fd_objects.dir/authenticate.cc.o CMakeFiles/fd_objects.dir/crypto.cc.o CMakeFiles/fd_objects.dir/evaluate_job_command.cc.o CMakeFiles/fd_objects.dir/fd_plugins.cc.o CMakeFiles/fd_objects.dir/fileset.cc.o CMakeFiles/fd_objects.dir/sd_cmds.cc.o CMakeFiles/fd_objects.dir/verify.cc.o CMakeFiles/fd_objects.dir/accurate_htable.cc.o CMakeFiles/fd_objects.dir/backup.cc.o CMakeFiles/fd_objects.dir/dir_cmd.cc.o CMakeFiles/fd_objects.dir/filed_globals.cc.o CMakeFiles/fd_objects.dir/heartbeat.cc.o CMakeFiles/fd_objects.dir/socket_server.cc.o CMakeFiles/fd_objects.dir/verify_vol.cc.o CMakeFiles/fd_objects.dir/accurate_lmdb.cc.o CMakeFiles/fd_objects.dir/compression.cc.o CMakeFiles/fd_objects.dir/estimate.cc.o CMakeFiles/fd_objects.dir/filed_conf.cc.o CMakeFiles/fd_objects.dir/restore.cc.o CMakeFiles/fd_objects.dir/status.cc.o
/usr/bin/ranlib libfd_objects.a
[ 94%] Built target fd_objects
make: *** [all] Error 2
```

**Comment by rivimey** [comment]
I got a very similar error when trying to compile from source on MacOS.

`cd /tmp/bareos-client-20210120-44610-ehd6bt/bareos-Release-19.2.9/build/core/src/filed && /usr/local/Cellar/cmake/3.19.3/bin/cmake -E cmake_link_script CMakeFiles/fd_objects.dir/link.txt --verbose=1
/usr/bin/ar qc libfd_objects.a CMakeFiles/fd_objects.dir/accurate.cc.o CMakeFiles/fd_objects.dir/authenticate.cc.o CMakeFiles/fd_objects.dir/crypto.cc.o CMakeFiles/fd_objects.dir/evaluate_job_command.cc.o CMakeFiles/fd_objects.dir/fd_plugins.cc.o CMakeFiles/fd_objects.dir/fileset.cc.o CMakeFiles/fd_objects.dir/sd_cmds.cc.o CMakeFiles/fd_objects.dir/verify.cc.o CMakeFiles/fd_objects.dir/accurate_htable.cc.o CMakeFiles/fd_objects.dir/backup.cc.o CMakeFiles/fd_objects.dir/dir_cmd.cc.o CMakeFiles/fd_objects.dir/filed_globals.cc.o CMakeFiles/fd_objects.dir/heartbeat.cc.o CMakeFiles/fd_objects.dir/socket_server.cc.o CMakeFiles/fd_objects.dir/verify_vol.cc.o CMakeFiles/fd_objects.dir/accurate_lmdb.cc.o CMakeFiles/fd_objects.dir/compression.cc.o CMakeFiles/fd_objects.dir/estimate.cc.o CMakeFiles/fd_objects.dir/filed_conf.cc.o CMakeFiles/fd_objects.dir/restore.cc.o CMakeFiles/fd_objects.dir/status.cc.o
/usr/bin/ranlib libfd_objects.a
[ 79%] Built target fd_objects
make: *** [all] Error 2

`

**Comment by rivimey** [comment]
@chenrui333 I have no idea why you closed this but then added help wanted.

**Comment by chenrui333** [comment]
@rivimey, sorry about confusion. I was encouraging more folks creating new PRs on top of this (since I could not make it forward).

**Pull request closed without merging**
