### PR TITLE
sourcery 0.16.1

### PR DESCRIPTION
**Pull request by Liquidsoul**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Liquidsoul** [comment]
It is strange that the mojave CI build fails now because the related code has successfully compiled in version `0.16.0` 🤔
Anyway, I do not think we really care for mojave support for Sourcery as it is a Swift project.

**Comment by SMillerDev** [comment]
> It is strange that the mojave CI build fails now because the related code has successfully compiled in version `0.16.0` 🤔
> Anyway, I do not think we really care for mojave support for Sourcery as it is a Swift project.

Why would you not care for the latest version of macOS then?

**Comment by Liquidsoul** [comment]
Wow, sorry, I think I am a bit tired and mixed up the macOS versions 😅 
I think that the problem comes from the swift version used by the Jenkins runner which is different with the one we support.

**Comment by SMillerDev** [comment]
Does it not work with the latest xcode?

**Comment by Liquidsoul** [comment]
We build the tool in the formula with the swift package manager and it appears that they may have change something about the default targeted OS. So, the command now requires that we specify the target OS. I have updated the formula to specify that we only support starting from 10.11.

I don't know if my change triggered jenkins or if something else needs to be done to run it with the new changes.

**Comment by SMillerDev** [comment]
It's triggered.

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by fxcoudert** [comment]
Thanks @Liquidsoul

**Pull request closed without merging**
