### PR TITLE
node 8.7.0

### PR DESCRIPTION
**Pull request by dio-az**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@chrmoritz it looks like node@4 and node@6 are struggling with the new npm.

**Comment by chrmoritz** [comment]
Looks like `npx` isn't working well with the `--cache=` parameter for at least quite some versions (It's installing to the passed in cache location but trying it to execute the package form the default location). It's even already failing with the npx version shipped with the current `npm@5.2.0`. I don't know why `shell_output` didn't complain about the wrong exit code before, but we should change the last test line to just to fix the test:

```ruby
assert_match "< hello >", shell_output("#{HOMEBREW_PREFIX}/bin/npx cowsay hello")
```

**Comment by ilovezfs** [comment]
@chrmoritz any idea why it doesn't affect node 8?

**Comment by chrmoritz** [comment]
Oh sry, I was wrong. It`s about npx not resolving `~` correctly in the path passed in to `--cache=`.
`npx --cache=/Users/chrmoritz/Library/Caches/Homebrew/npm_cache cowsay hello` is working, but  `npx --cache=~/Library/Caches/Homebrew/npm_cache cowsay hello` is failing (independent of if you use node 8.7 or node 8.6 or node@6 or node@4).

**Comment by chrmoritz** [comment]
After bisecting `npx` version, the error from CI (`spawn '/usr/local/Cellar/node@6/6.11.4/bin/node' ENOENT`) was introduced between `npx@9.2.0` and `npx@9.2.1` in this commit: https://github.com/zkat/npx/commit/761dfe9bd73e0aca8170d23187e4fbce0ef7a647. It's caused by the `@` in the path to node (moving `node@6` to `node6` in the Cellar fixes the issue).

**Comment by ilovezfs** [comment]
@chrmoritz ah OK. We're definitely not going to rename the formulae, so it would be great if we could get an upstream fix for that.

**Comment by chrmoritz** [comment]
@ilovezfs: Sure, I just renamed it to confirming the issue is caused by the `@` in the path.

Maybe we should split up this PR again and ship node 8.7.0 with npm 5.4.2 now (as it's not affected) and ship the npm 5.4.2 update to the versioned formulaes later, when we have a fix for them.

**Comment by ilovezfs** [comment]
@chrmoritz we need the npm versions to be consistent across the formulae so this is blocked until we can resolve the @ issue.

**Comment by ilovezfs** [comment]
>Maybe we should split up this PR again and ship node 8.7.0 with npm 5.4.2 now (as it's not affected) and ship the npm 5.4.2 update to the versioned formulaes later, when we have a fix for them.

Last time we did that there were a ton of issues filed about it. So I'm not eager to do that again.

**Comment by ilovezfs** [comment]
@chrmoritz is it feasible to revert https://github.com/zkat/npx/commit/761dfe9bd73e0aca8170d23187e4fbce0ef7a647? It claims to be fixing a Windows issue.

**Comment by chrmoritz** [comment]
It a fix for the Windows only issue https://github.com/zkat/npx/issues/62. Reverting https://github.com/zkat/npx/commit/761dfe9bd73e0aca8170d23187e4fbce0ef7a647 could be a temporary option for us.

**Comment by ilovezfs** [comment]
It looks like it doesn't revert cleanly so we're probably stuck until upstream fixes it.

**Comment by chrmoritz** [comment]
Found a fix. On unix `child_process.spawn` doesn't like to have quotation marks `'` inside the path string, but npx tries to escape the path after finding any special character like our `@` (likely to support paths with spaces on Windows ...).

```diff
diff --git a/index.js b/index.js
index 097d67c..c210d3d 100644
--- a/index.js
+++ b/index.js
@@ -232,7 +232,7 @@ function installPackages (specs, prefix, opts) {
       return opts.npm
     }
   }).then(npmPath => {
-    return child.escapeArg(npmPath, true)
+    return process.platform === 'win32' ? child.escapeArg(npmPath, true) : npmPath
   }).then(npmPath => {
     return child.spawn(npmPath, args, {
       stdio: [0, 'pipe', opts.q ? 'ignore' : 2]
```

Will try to upstream it after having lunch.

**Comment by ilovezfs** [comment]
@chrmoritz thanks :)

**Comment by ilovezfs** [comment]
@chrmoritz PR refreshed.

**Comment by ilovezfs** [comment]
Thanks for your contribution to Homebrew @diogoazevedos! Shipped.

**Pull request closed without merging**
