### PR TITLE
harfbuzz 1.3.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
more #linkfail

```
==> FAILED
Error: 1 problem in 1 formula
harfbuzz:
  * Formulae are required to declare all linked dependencies.
    Please add all linked dependencies to the formula with:
      depends_on "cairo" => :linked
      depends_on "gettext" => :linked
```

**Comment by DomT4** [comment]
I loathe that check already.

👍 once the audit is happy.

**Comment by ilovezfs** [comment]
Yeah so far feels pretty useless since it keeps wanting to add stuff with `:linked` due to recommended things, but then it can't be scoped to the build.with? for that option. This one is especially broken since cairo is *supposed* to be `:optional`. But perhaps configure has some kind `--without-cairo` to fix it so I don't have to make cairo flat out required.

**Comment by ilovezfs** [comment]
```
  --with-cairo=[yes/no/auto]
                          Use cairo [default=auto]
```
well that looks promising.

**Comment by DomT4** [comment]
> but then it can't be scoped to the build.with? for that option

Yup. It also fails in hilarious ways on `depends_on "horse" if build.with? "jockey"` style dependencies, as does a lot of our dependency system really. I'm still not in love with this being a fatal check but there we go.

Changes pushed LGTM.

**Comment by ilovezfs** [comment]
@DomT4 surely the commit message isn't "ideal" :)

**Comment by DomT4** [comment]
You can write whatever you like in the commit message. I'll only bother checking the summaries & commits themselves 😉.

**Comment by ilovezfs** [comment]
Don't worry, I "fixed" it in post :)

**Pull request closed without merging**
