### PR TITLE
peg: add livecheck and license

### PR DESCRIPTION
**Pull request by samford**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

By default, livecheck is unable to identify versions for `peg`, as no strategies apply to the URLs it checks. This PR adds a `livecheck` block that checks the [`homepage`](https://www.piumarta.com/software/peg/) where the `stable` archive is found.

This also adds `license all_of: ["MIT", "BSD-2-Clause"]` information. `peg` is MIT licensed according to the homepage ("`peg` is distributed under the MIT license") and `LICENSE.txt` file found in the latest tarball:

```
Copyright (c) 2007-2013, Ian Piumarta
All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the 'Software'), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, and/or sell copies of the
Software, and to permit persons to whom the Software is furnished to do so,
provided that the above copyright notice(s) and this permission notice appear
in all copies or substantial portions of the Software.  Inclusion of the
above copyright notice(s) and this permission notice in supporting
documentation would be appreciated but is not required.

THE SOFTWARE IS PROVIDED 'AS IS'.  USE ENTIRELY AT YOUR OWN RISK.
```

The part that appears to be `BSD-2-Clause` is `getopt` for Windows, found in the `win` directory of the latest tarball. The license in `getopt.c` is as follows:

```
/*
 * Copyright (c) 2002 Todd C. Miller <Todd.Miller@courtesan.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 * Sponsored in part by the Defense Advanced Research Projects
 * Agency (DARPA) and Air Force Research Laboratory, Air Force
 * Materiel Command, USAF, under agreement number F39502-99-1-0512.
 */
/*-
 * Copyright (c) 2000 The NetBSD Foundation, Inc.
 * All rights reserved.
 *
 * This code is derived from software contributed to The NetBSD Foundation
 * by Dieter Baron and Thomas Klausner.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
```

I'm definitely not an expert on licenses, so it would probably be good for someone else to comment on the license situation.

### CODE REVIEW

**Comment by Rylan12** [comment]
If the `getopt` in the `win` folder isn't used for macOS or Linux installs, I don't think we need to list it. In other formulae, we don't list formulae for parts of the source that aren't used (e.g. documentation that isn't installed).

**Comment by samford** [comment]
I've updated this to `license "MIT"` with the above in mind, as the files in the `win` folder (e.g., `getopt.c`, etc.) are only used in Windows builds. Thanks for confirming, @Rylan12!

**Comment by Rylan12** [comment]
✅ on the license. I'm not at all familiar with `livecheck` so if you want an approval on that I can't really weigh in.

I'll try to read the docs later today when I've got some more time so I at least have some sense.

**Comment by samford** [comment]
I was only interested in feedback on the license, so I'll go ahead and merge this 👍

---

@Rylan12 The main sources of livecheck-related documentation at the moment are my [draft documentation PR](https://github.com/Homebrew/brew/pull/7937) (which I need revisit and rework to address feedback) and the various technical documentation:

* [Class: `Livecheck` (the `Formula` DSL)](https://rubydoc.brew.sh/Livecheck.html)
* [Module: `Homebrew::Livecheck`](https://rubydoc.brew.sh/Homebrew/Livecheck.html) (the implementation behind the `brew livecheck` command)
* [Module: `Homebrew::Livecheck::Strategy`](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy.html) (the module where livecheck's built-in strategies are found)

Some of the documentation will change when I start working on it again (soon), so there's no rush for you to learn about livecheck right now. I've put quite a bit of work into the current documentation but there are still some areas that can be improved. I was planning on announcing the documentation to other maintainers once's it's ready (so anyone who're interested can become more familiar with how livecheck works).

However, if you dig into it before the draft documentation PR is finished/merged, feel free to message me on Slack with any questions that arise (or hop into the #livecheck channel). I also encourage folks to request my review on livecheck-related PRs/issues, since I'm sometimes busy and will miss things if they're not brought to my attention.

**Comment by Rylan12** [comment]
Thanks, that's very helpful! I'll review those when I have some time.

**Pull request merged**
