### PR TITLE
scw 2.1.0

### PR DESCRIPTION
**Pull request by jerome-quere**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jerome-quere** [comment]
Test failures do not seem related to the PR

**Comment by Moisan** [comment]
> Test failures do not seem related to the PR

You are right. Could you remove your last commit? We should be good to merge after that.

**Comment by jerome-quere** [comment]
✅ Done

**Comment by jerome-quere** [comment]
@Moisan Do I need to do something for this PR to get merged?

**Comment by chenrui333** [comment]
some CI flakiness, let me rerun the job (should be good to go if CI is all green), thanks for the patience.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
