### PR TITLE
unar 1.10

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---
- Removed legacy build steps;
- Added more substantial tests.

### CODE REVIEW

**Comment by zmwangx** [comment]
Build fails on Mavericks. I don't have a Mavericks environment to investigate the issue.

**Comment by mikemcquaid** [comment]
@zmwangx Want to try a `fails_with :clang` with the Mavericks build number?

**Comment by zmwangx** [comment]
@mikemcquaid Added. That basically means this formula can no longer be built on Mavericks, though, and I'm not sure if that's true.

**Comment by mikemcquaid** [comment]
Doesn't work with e.g. GCC?  Might be worth submitting an upstream issue and/or adding a `depends_on` for above Yosemite.

**Comment by ilovezfs** [comment]
Unfortunately, it builds just fine in Xcode itself, so the problem is either with the formula or brew.

**Comment by ilovezfs** [comment]
@mikemcquaid yup you were right. It's an upstream issue. In particular, a packaging problem. They forgot to run xcodebuild clean before shipping.

@zmwangx This fixes it:
```
diff --git a/Formula/unar.rb b/Formula/unar.rb
index d485529..9640e41 100644
--- a/Formula/unar.rb
+++ b/Formula/unar.rb
@@ -15,13 +15,9 @@ class Unar < Formula
 
   depends_on :xcode => :build
 
-  fails_with :clang do
-    build 600
-    cause "xcodebuild fails with errors"
-  end
-
   def install
     # Build XADMaster.framework, unar and lsar
+    xcodebuild "-project", "./XADMaster/XADMaster.xcodeproj", "-alltargets", "-configuration", "Release", "clean"
     xcodebuild "-project", "./XADMaster/XADMaster.xcodeproj", "-target", "XADMaster", "SYMROOT=../", "-configuration", "Release"
     xcodebuild "-project", "./XADMaster/XADMaster.xcodeproj", "-target", "unar", "SYMROOT=../", "-configuration", "Release"
     xcodebuild "-project", "./XADMaster/XADMaster.xcodeproj", "-target", "lsar", "SYMROOT=../", "-configuration", "Release"
```

**Comment by DomT4** [comment]
Not this formula and Mavericks again 😓. The last release was just as problematic to get through the CI happily.

**Comment by ilovezfs** [comment]
@DomT4 Yep, I'd checked the prior release and it was equally borked. hehe

**Comment by zmwangx** [comment]
@ilovezfs Applied your patch. Hopefully it will pass this time.

**Comment by ilovezfs** [comment]
@zmwangx excellent, thanks

**Comment by mikemcquaid** [comment]
Thanks again @zmwangx!

**Pull request closed without merging**
