### PR TITLE
ceylon 1.3.3

### PR DESCRIPTION
**Pull request by FroMage**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Hi, I'm one of the Ceylon maintainers. I haven't built the formula locally because I'm not running OSX, but I don't see why it would fail. Thanks.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@FroMage I'm getting 404:
```
Josephs-MacBook-Pro:~ joe$ curl -IL https://ceylon-lang.org/download/dist/1_3_3
HTTP/1.1 404 Not Found
Date: Mon, 21 Aug 2017 14:01:25 GMT
Server: Apache/2.2.15 (Red Hat)
Last-Modified: Mon, 21 Aug 2017 11:08:08 GMT
ETag: "190d51d-13aa-557417e5bf600"
Accept-Ranges: bytes
Content-Length: 5034
Strict-Transport-Security: max-age=31536000
Connection: close
Content-Type: text/html; charset=UTF-8
```

**Comment by FroMage** [comment]
> but I don't see why it would fail

Yeah, famous last words. Sorry to have wasted your time, we're still deploying this part of the website. I'll comment when that has propagated.

**Comment by FroMage** [comment]
OK it's up. Sorry again, that was really lame.

**Comment by FroMage** [comment]
Mmm, how can we restart the tests?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by JCount** [comment]
@FroMage 🎉 Thank you for opening the PR for the version update, it makes the lives of the maintainers here much easier.  😄

**Comment by FroMage** [comment]
Thanks!

**Pull request closed without merging**
