### PR TITLE
treefrog 1.28.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
00:50:37 ==> brew install --verbose --build-bottle treefrog
00:50:46 ==> FAILED
00:50:46 /usr/bin/sandbox-exec -f /private/tmp/homebrew20200311-64623-12rlkmt.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/treefrog.rb --build-bottle --verbose
00:50:46 ==> Downloading https://github.com/treefrogframework/treefrog-framework/archive/v1.28.0.tar.gz
00:50:46 Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/7706f938e84e28983b3d2a9d1135a11470e985d3366c41479e2ab1c3d12be33e--treefrog-framework-1.28.0.tar.gz
00:50:46 ==> Verifying 7706f938e84e28983b3d2a9d1135a11470e985d3366c41479e2ab1c3d12be33e--treefrog-framework-1.28.0.tar.gz checksum
00:50:46 tar xof /Users/brew/Library/Caches/Homebrew/downloads/7706f938e84e28983b3d2a9d1135a11470e985d3366c41479e2ab1c3d12be33e--treefrog-framework-1.28.0.tar.gz -C /private/tmp/d20200311-64624-1qz1rlk
00:50:46 cp -pR /private/tmp/d20200311-64624-1qz1rlk/treefrog-framework-1.28.0/. /private/tmp/treefrog-20200311-64624-fr29ln/treefrog-framework-1.28.0
00:50:46 chmod -Rf +w /private/tmp/d20200311-64624-1qz1rlk
00:50:46 ==> ./configure --prefix=/usr/local/Cellar/treefrog/1.28.0
00:50:46 cmake: command not found
```

**Comment by chenrui333** [comment]
```
02:00:27 In file included from /usr/local/Cellar/qt/5.14.1/lib/QtCore.framework/Headers/qmath.h:55:
02:00:27 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'isless' in the global namespace
02:00:27 using ::isless;
02:00:27       ~~^
02:00:27 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:327:9: error: no member named 'islessequal' in the global namespace
02:00:27 using ::islessequal;
02:00:27       ~~^
02:00:27 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:328:9: error: no member named 'islessgreater' in the global namespace
02:00:27 using ::islessgreater;
02:00:27       ~~^
02:00:27 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
02:00:27 using ::isunordered;
02:00:27       ~~^
02:00:27 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:330:9: error: no member named 'isunordered' in the global namespace
02:00:27 using ::isunordered;
02:00:27       ~~^
02:00:27 198 warnings and 13 errors generated.
02:00:27 make[1]: *** [.obj/applicationcontroller.o] Error 1
02:00:27 make[1]: *** Waiting for unfinished jobs....
02:00:27 22 warnings and 13 errors generated.
02:00:27 make[1]: *** [.obj/moc_applicationcontroller.o] Error 1
02:00:27 make: *** [sub-controllers-make_first-ordered] Error 2
02:00:27 Error: treefrog: failed
```

**Comment by Bo98** [comment]
Might be Qt related. I'll experiment with this a bit.

**Comment by chenrui333** [comment]
> Might be Qt related. I'll experiment with this a bit.

Any feedback on this PR?

**Comment by Bo98** [comment]
I've made some tweaks in `brew` which might help here. Try rebase and give it another go.

**Comment by chenrui333** [comment]
let's see how it goes.

**Comment by SMillerDev** [comment]
Cmake not found

**Comment by Bo98** [comment]
This is from it building its own Mongo driver.

Pass `--enable-shared-mongoc` to `configure` and depend on `mongo-c-driver`.

**Pull request closed without merging**
