### PR TITLE
openttd 1.10.2

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Should we replace a formula with a cask (since we already have it https://github.com/Homebrew/homebrew-cask/blob/master/Casks/openttd.rb)?

**Comment by SMillerDev** [comment]
If it's an open source CLI tool we should just keep the formula

**Comment by bayandin** [comment]
> If it's an open source CLI tool we should just keep the formula

It's a game (with UI), I'm not sure if it even has a CLI part: https://www.openttd.org/

**Comment by SMillerDev** [comment]
The test is a CLI call

**Comment by EricFromCanada** [comment]
It does have several CLI flags that can set options before launching the GUI. 
```
openttd -h
OpenTTD 1.10.1


Command line options:
  -v drv              = Set video driver (see below)
  -s drv              = Set sound driver (see below) (param bufsize,hz)
  -m drv              = Set music driver (see below)
  -b drv              = Set the blitter to use (see below)
  -r res              = Set resolution (for instance 800x600)
  -h                  = Display this help text
  -t year             = Set starting year
  -d [[fac=]lvl[,...]]= Debug mode
  -e                  = Start Editor
  -g [savegame]       = Start new/save game immediately
  -G seed             = Set random seed
  -n [ip:port#company]= Join network game
  -p password         = Password to join server
  -P password         = Password to join company
  -D [ip][:port]      = Start dedicated server
  -l ip[:port]        = Redirect DEBUG()
  -f                  = Fork into the background (dedicated only)
  -I graphics_set     = Force the graphics set (see below)
  -S sounds_set       = Force the sounds set (see below)
  -M music_set        = Force the music set (see below)
  -c config_file      = Use 'config_file' instead of 'openttd.cfg'
  -x                  = Do not automatically save to config file on exit
  -q savegame         = Write some information about the savegame and exit

...
```

**Review by bayandin — APPROVED** [review]
Fair enough, thanks folks!

**Pull request closed without merging**
