### PR TITLE
+ Formula/crystal@0.35.1

### PR DESCRIPTION
**Pull request by thoran**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks for your PR, @thoran. Does this meet the requirements for versioned formulae in the docs [1]?

[1] https://docs.brew.sh/Versions#acceptable-versioned-formulae

**Comment by thoran** [comment]
> Thanks for your PR, @thoran. Does this meet the requirements for versioned formulae in the docs [1]?
> 
> [1] https://docs.brew.sh/Versions#acceptable-versioned-formulae

This formula is identical to the latest of the most recent minor version except for the name change. I wanted this because I updated my version to 0.36 and it is incompatible with 0.35(.1) and couldn't easily downgrade and have meantime installed and am using asdf for crystal 0.35.1. I've had a go at answering all concerns below...

* Versioned software should build on all Homebrew’s supported versions of macOS.
By virtue of the being the old formula that should be the case.

* Versioned formulae should differ in major/minor (not patch) versions from the current stable release. This is because patch versions indicate bug or security updates, and we want to ensure you apply security updates.
Tick.

* Unstable versions (alpha, beta, development versions) are not acceptable for versioned (or unversioned) formulae.
Tick.

* Upstream should have a release branch for each formula version, and release security updates for each version when necessary. For example, PHP 7.0 was not a supported version but PHP 7.2 was in January 2020. By contrast, most software projects are structured to only release security updates for their latest versions, so their earlier versions are not eligible for versioning.
Tick.

* Versioned formulae should share a codebase with the main formula. If the project is split into a different repository, we recommend creating a new formula (formula2 rather than formula@2 or formula@1).
By virtue of the being the old formula that is the case.

* Formulae that depend on versioned formulae must not depend on the same formulae at two different versions twice in their recursive dependencies. For example, if you depend on openssl@1.0 and foo, and foo depends on openssl then you must instead use openssl.
Tick.

* Versioned formulae should only be linkable at the same time as their non-versioned counterpart if the upstream project provides support for it, e.g. using suffixed binaries. If this is not possible, use keg_only :versioned_formula to allow users to have multiple versions installed at once.
I don't if anyone wants multiple versions installed. Maybe?

* A keg_only :versioned_formula should not post_install anything in the HOMEBREW_PREFIX that conflicts with or duplicates the main counterpart (or other versioned formulae). For example, a node@6 formula should not install its npm into HOMEBREW_PREFIX like the node formula does.
It isn't, so not sure if this is relevant.

* Versioned formulae submitted should be expected to be used by a large number of people. If this ceases to be the case, they will be removed. We will aim not to remove those in the top 3,000 install_on_request formulae.
I have no idea how many people want this.

* Versioned formulae should not have resources that require security updates. For example, a node@6 formula should not have an npm resource but instead rely on the npm provided by the upstream tarball.
By virtue of the being the old formula that should be the case.

* Versioned formulae should be as similar as possible and sensible compared to the main formulae. Creating or updating a versioned formula should be a chance to ask questions of the main formula and vice versa, e.g. can some unused or useless options be removed or made default?
By virtue of the being the old formula that is the case.

* No more than five versions of a formula (including the main one) will be supported at any given time, regardless of usage.
There's only one presently.

* When removing formulae that violate this, we will aim to do so based on usage and support status rather than age.
OK.

**Comment by carlocab** [comment]
> * Upstream should have a release branch for each formula version, and release security updates for each version when necessary. For example, PHP 7.0 was not a supported version but PHP 7.2 was in January 2020. By contrast, most software projects are structured to only release security updates for their latest versions, so their earlier versions are not eligible for versioning.
>   Tick.

Are you sure? I can't actually find a release branch for 0.35.x at https://github.com/crystal-lang/crystal. I also get the impression that there will not be any further 0.35.x updates. If that were true, then that would make this not acceptable as a versioned formula.

**Comment by gromgit** [comment]
> Upstream should have a release branch for each formula version, and release security updates for each version when necessary. For example, PHP 7.0 was not a supported version but PHP 7.2 was in January 2020. By contrast, most software projects are structured to only release security updates for their latest versions, so their earlier versions are not eligible for versioning.
> Tick.

Untick:
* There's no 0.35 branch.
* Crystal has never publicly committed to maintaining earlier versions, and in fact seems to be adopt the "yesterday's version is history, never to be revisited" philosophy that's typical of the vast majority of open-source projects. See projects like [PHP](https://www.php.net/supported-versions.php) and [PostgreSQL](https://www.postgresql.org/support/versioning/) for what Homebrew expects from "versioning support from upstream".

I recommend extracting the version you want in your own tap instead:
```
brew tap-new thoran/personal
brew extract --version=0.35.1 crystal thoran/personal
brew install thoran/personal/crystal@0.35.1
```

**Pull request closed without merging**
