### PR TITLE
postgresql@16: support extension formulae

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Another attempt at trying to get extensions working on other PostgreSQL formulae.

This time, keg directory structure is mostly unchanged other than `datadir` using `#{share}/postgresql` rather than `#{share}/postgresql@16` for PostgreSQL 16, with a note to simplify some directory structure in PostgreSQL 17.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by p-linnane** [comment]
@cho-m is there anything else needed here?

**Comment by cho-m** [comment]
> @cho-m is there anything else needed here?

I may hold off until `postgresql@17` and only forward apply changes to reduce impact. May switch to beta testing until Sept/Oct release.

Mainly since I haven't sufficiently tested user scenarios and use cases.

**Comment by 9999years** [comment]
I've worked out (independently) the correct `./configure` and `make` and `make install-world` args for this here, maybe we can integrate them: https://github.com/MercuryTechnologies/homebrew-tap/blob/0d611b7c9b3d261a855011a9bf7d8d3d11faa37b/Formula/postgresql%4016.rb

**Comment by cho-m** [comment]
Copied over existing work to #181862 to figure out something for `postgresql@17`.

**Pull request closed without merging**
