### PR TITLE
qt: fix for arm

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
I suspected this was all we needed reading https://bugreports.qt.io/browse/QTBUG-85279

Maybe someone with a DTK can further work on this to fix this major blocker in https://github.com/Homebrew/brew/issues/7857

**Comment by Tibrim** [comment]
@SMillerDev, thought I'd take a stab at this one, but I'm new to homebrew development.

Got homebrew and homebred-core cloned and added your patch to qt.rb, but get the following:

```bash
brew install --build-from-source qt   
Warning: You are running macOS on a arm64 CPU architecture.
We do not provide support for this (yet).
Reinstall Homebrew under Rosetta 2 until we support it.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.

==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
######################################################################## 100.0%
==> Downloading https://codereview.qt-project.org/gitweb?p=qt/qt3d.git;a=patch;h=b456a7d47a36dc3429a5e7bac7665b1
==> Downloading from https://login.qt.io/login
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: e47071f5feb6f24958b3670d83071502fe87243456b29fdc731c6eba677d9a59
  Actual: 04ad191514574c278414f2372190065cf2d02d9554f7e781996df87cd4269b17
 Archive: /Users/***/Library/Caches/Homebrew/downloads/774933b2edc2b03911f16fa69ce84d09bb00b50ac9004cfc61999fca37713e25--login
To retry an incomplete download, remove the file above.
```

Happy to help if you can point me in the right direction to get started.

**Comment by SMillerDev** [comment]
Check the urls. The patch is redirecting you to a login page. You need to make sure that doesn't happen.

If there is no way to prevent that for qt git you can submit it to https://github.com/Homebrew/formula-patches.

**Comment by Tibrim** [comment]
Yes, that was it.  I was able to find a new anonymous http url from that site, but it looks like the diff is only available either base64 encoded or in a ZIP.  Looking at the docs, I'm not seeing anyway to have patch do some post processing on that diff file before it attempts to apply it.

I'll look into getting it submitted to https://github.com/Homebrew/formula-patches.

Since the comment for that patch says its Linux specific, I commented it out to see if the install would get any further and it did, but does eventually fail during compilation.  Will continue to dig into this.

**Comment by dtrodrigues** [comment]
The AVX2 patch is merged into 5.15.2, but the overall qt download situation needs to be looked into: https://github.com/Homebrew/homebrew-core/pull/65287

**Comment by aumuell** [comment]
I don't think that Qt 5.15.2 is completely ready for Apple Silicon yet:
- An entry in the discussion for the [5.15.2 release announcement](https://www.qt.io/blog/qt-5.15.2-released) reads that there is no official support yet: "@Gabureanu: [...] Qt 5.15.2 does not provide official support to the ARM based Macs. Schedule for fully supporting ARM based Macs is not yet decided. We'll inform when this is known."
- QWebEngine does still not build: https://bugreports.qt.io/browse/QTBUG-85537, and the 5.15.2 changelog says "The Chromium version has been updated to 83.0.4103.122", but to my knowledge 87 is the first version of Chrome to support Apple Silicon.
- Qt's internal assimp library does not build because of an incompatibility with the included minizip

So I cobbled s.th. together that builds Qt on arm64, but without assimp and without the WebEngine module: [qt.rb](https://gist.github.com/aumuell/e7110ac31919e8e5d4f0932fc243ac04). It does not include any patches, as the ones from 5.15.1 did not apply. BTW, 5.15.1 would build as well.

For me, this is already quite useful as I do not depend on the missing features. And I imagine that there are many Qt applications that do not rely on the WebEngine. Perhaps Homebrew could leave out WebEngine on arm64 for now?

**Pull request closed without merging**
