### PR TITLE
OpenJDK (Java version) dependency should be a caveat

### PR DESCRIPTION
**Pull request by brunoborges**
It is not always the case that a JDK will be installed through Homebrew. In fact, in many cases these days, Java developers tend to need more than one JDK major version installed. I came to this problem when trying to build and run a Maven project that required Java 8, on a fresh Mac Book device.

I installed JDK 8 and had it configured properly in my `PATH`, and `JAVA_HOME`. Then I proceeded installing Maven with `brew install maven`, hoping that it was going to only install Maven. While it is true that using `--ignore-dependencies` would have saved me from this problem, I only realized the issue later.

Maven formulas, and in fact many Java-based tools published on Homebrew, have a hard dependency on the `openjdk` package. This may suffice in the general case, but often tools should run with a particular Java version that matches with whatever Java project the developer is working on. More importantly, tools should use whatever JDK is already available in the system, configured however the user wanted.

Finally, there are a multitude of JDKs available in the market, with many different versions and features. While they are all compatible, there will be nuances between them, especially when it comes to support, licensing, and compliance. The `openjdk` package is installing the Oracle OpenJDK GPL distribution - published from jdk.java.net. While this is fine technically speaking, it may not comply with users' requirements and needs, and it may be hiding an implementation detail from the developer that does matter for non-technical reasons.

This PR is a proposal on how certain tools, starting with `Maven`, should depend on Java. The dependency should be on a major version (minimum requirement), not on a specific OpenJDK distribution+version.

### CODE REVIEW

**Comment by p-linnane** [comment]
This will not work. We require the specific dependency because we build and distribute binaries (bottles). The formulae will not build with this proposed change.

**Comment by brunoborges** [comment]
As far as I understand, Java packages are not being built, they are being downloaded (binaries) from their respective origins. For example, Maven binaries are downloaded from Apache.

The test indeed requires a JDK to run, but then, `openjdk` should be a dependency for running the test, not for shipping the software.

**Comment by p-linnane** [comment]
If we move forward with this it would be better to have `depends_on "openjdk" => :test` than outright removing it.

**Comment by brunoborges** [comment]
> If we move forward with this it would be better to have `depends_on "openjdk" => :test` than outright removing it.

I did not see this as an option. Good to know!

**Comment by SMillerDev** [comment]
But this means that if you do `brew install maven` on a new system followed by `mvn` you'll get errors. I don't think this is the right fix.

**Comment by reitermarkus** [comment]
We already let you override `JAVA_HOME` at runtime by using `Language::Java.overridable_java_home_env` in the `maven` formula.

So the only “problem” here is that we always install `openjdk`?

**Comment by brunoborges** [comment]
There are two problems: 

1. It always installs `openjdk` even if there is already a JDK installed in the system.
2. It forces the use of JAVA_HOME, meaning that `maven` won't run after installation if JAVA_HONE is not set in the system to the JDK the user wants to use.

JAVA_HOME is no longer necessary for a variety of tools. Maven itself works fine if the JAVA_HOME is not set, as long as <jdk>/bin is in PATH.

Here's the scenario:

* User installs JDK 11 from vendor X. This is an LTS release.
* `java` is available in `PATH` and the JDK works fine
* `JAVA_HOME` is not set
* User installs Maven with Homebrew
* Homebrew installs `openjdk` (version 19 as of today) from Oracle jdk.java.net. This is *not* an LTS release
* Maven now only runs with `openjdk` 19 unless user is conscious and changes its system configuration
* Certain projects _may not_ work properly due to changes between JDK 11 and JDK 19, not to mention being from different vendors

In the scenario above, if the user ignored the `openjdk` dependency while installing Maven, `mvn` from Homebrew would still not work because its launcher script **requires** `JAVA_HOME` to be set.

**Comment by SMillerDev** [comment]
> It always installs openjdk even if there is already a JDK installed in the system.

The alternative is "it is never OpenJDK even if none are installed", which is a much bigger problem

> It forces the use of JAVA_HOME, meaning that maven won't run after installation if `JAVA_HOME` is not set in the system to the JDK the user wants to use.

It is my understanding this is the standard across at least macOS and Linux. Is it not?

**Comment by brunoborges** [comment]
> It is my understanding this is the standard across at least macOS and Linux. Is it not?

There are two angles on why it is not apples to apples:

1. Mac usage as a development environment is much larger than Linux. So, installing Maven through APT/YUM is very likely to be way less common than installing Maven through Homebrew.
2. And while it is true that this is the case for Linux distributions, the main difference is that the JDK that gets installed in a Linux box as a dependency for Maven is the one **built** by the Linux distribution maintainers. Brew OTOH doesn't build its own JDK. Instead it consumes a 3rd party.

**Comment by SMillerDev** [comment]
> Brew OTOH doesn't build its own JDK. Instead it consumes a 3rd party.

Everything in Homebrew/core is build from source unless it is a cross-platform binary: https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

**Comment by brunoborges** [comment]
> Everything in Homebrew/core is build from source unless it is a cross-platform binary: https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

Great to know Homebrew tries its best, but I am talking specifically about Java tools and the JDK, which, to the best of my knowledge, are not built from source by Homebrew.

And I am looking at the source of the Maven and OpenJDK formulas. All these formulas do are download binaries from apache.org (Maven) and jdk.java.net (Oracle OpenJDK).

> EDIT:
> 
> > Mac usage as a development environment is much larger than Linux. So, installing Maven through APT/YUM is very likely to be way less common than installing Maven through Homebrew.
> 
> I'm not sure what popularity of the platform has to do with the standards people use to set a default Java.

And I am telling you that it is standard practice for a Java tool to use whatever JDK is already installed and configured in a system. Homebrew is installing brute force yet another JDK, with a different major version, and from a 3rd party vendor.

Linux distributions, again, do built Maven and the JDK from source, and some even have LTS versions and different default major versions, like Canonical for Ubuntu, not always pointing to the _latest_ major version.

**Comment by SMillerDev** [comment]
> Great to know Homebrew tries its best, but I am talking specifically about Java tools and the JDK, which, to the best of my knowledge, are not built from source by Homebrew.

And to the best of my knowledge we most definitely compile the JDK from source. See https://github.com/Homebrew/homebrew-core/blob/7c1be156cf812205a93711a1cdeb46ffedba5f77/Formula/openjdk.rb for example.

**Comment by brunoborges** [comment]
> > Great to know Homebrew tries its best, but I am talking specifically about Java tools and the JDK, which, to the best of my knowledge, are not built from source by Homebrew.
> 
> And to the best of my knowledge we most definitely compile the JDK from source. See https://github.com/Homebrew/homebrew-core/blob/7c1be156cf812205a93711a1cdeb46ffedba5f77/Formula/openjdk.rb for example.

My apologies. Missed that. For some reason I really thought it was not the case and was assuming it.

Yet, whether Homebrew does build the JDK from source or not,.it doesn't address the issue I'm raising here.

**Comment by SMillerDev** [comment]
> Yet, whether Homebrew does build the JDK from source or not,.it doesn't address the issue I'm raising here.

It is my understanding that any package manager will install it's own Java version if a package needs Java. It is then up to the user to select what JDK they want to use by means of `JAVA_HOME` as a standard.

There simply isn't an alternative, at the very least within Homebrew, for installing dependencies when a package needs them.

**Comment by reitermarkus** [comment]
> Here's the scenario:
> 
> * User installs JDK 11 from vendor X. This is an LTS release.
> * `java` is available in `PATH` and the JDK works fine
> * `JAVA_HOME` is not set
> * User installs Maven with Homebrew
> * Homebrew installs `openjdk` (version 19 as of today) from Oracle jdk.java.net. This is _not_ an LTS release
> * Maven now only runs with `openjdk` 19 unless user is conscious and changes its system configuration
> * Certain projects _may not_ work properly due to changes between JDK 11 and JDK 19, not to mention being from different vendors
> 

Here's my scenario:

- Install Maven with Homebrew
- Install and set up a Java version manager, e.g. `brew install jenv`
- Maven now runs with a project-specific Java version, without impacting other projects with different requirements 

That is also how every other programming language does it.

**Comment by brunoborges** [comment]
Yes, I think this conversation has been helpful for me to understand the nuances of "what a developer just wants to get done" versus developers who are more conscious about which JDK they want to use.

I played with installing different OpenJDK versions (`openjdk` formula), and noticed that any specific version is not automatically configured system-wide. User gets a caveat warning about this, and instructions on how to proceed.

I am coming to terms that it is the way it is, and that is OK.

**Comment by brunoborges** [comment]
Now to the last bit: the `mvn` script that is generated by Homebrew comes with a logic that requires either `openjdk` to be present, or that `JAVA_HOME` is set.

But there is a third option: `openjdk` is **not** installed (`--ignore-dependencies` was used) and `JAVA_HOME` is **not** set, but the user **did install a JDK** outside of Homebrew, meaning that `java` is available and working, in `PATH`.

Therefore, I'd like to suggest that the shell script for Maven changes to something like this:

```bash
#!/bin/bash
if [ ! -z $JAVA_HOME ]; then
  export JAVA_HOME="/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home"
fi

exec "/opt/homebrew/Cellar/maven/3.9.0/libexec/bin/mvn"  "$@"
```

Right now, this is how the shell script ends up being:

```bash
#!/bin/bash
JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home}" exec "/opt/homebrew/Cellar/maven/3.9.0/libexec/bin/mvn"  "$@"
```

The above script breaks an environment with a valid JDK installed (which may as well been installed _through Homebrew_) that just doesn't happen to be `openjdk` from Homebrew, nor there is a `JAVA_HOME` configured.

**Comment by brunoborges** [comment]
Ok, so the last bit that may be worth discussing is whether Maven, and other Java tools, should first rely on the JDK that is installed system-wide, and only fallback to the OpenJDK provided by Homebrew if there is no JDK installed.

Currently, the shell script for launching Maven (and similar tools) goes as follows:

```bash
#!/bin/bash
JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home}" exec "/opt/homebrew/Cellar/maven/3.9.0/libexec/bin/mvn"  "$@"
```

This creates a problem in systems where:

1. Another JDK is already installed (including those available through Homebrew) and it is the one developers want to use.
2. `JAVA_HOME` is not set, but `java` is reachable because the JDK got installed under `/Library/Java/JavaVirtualMachines` and Mac OS's own Java launcher (`/usr/bin/java`) brings the installed JDK forward.

If the user did ignore the dependency because they consciously know there is already a JDK installed, and working properly, `mvn` would still fail because it expects `JAVA_HOME` or that `openjdk` got installed (which it did not in case of --ignored-dependencies).

Therefore, I'd like to propose the following launcher for Java tools, starting with Maven:

```bash
#!/bin/bash

# If JAVA_HOME is not set and there is no JDK already installed, use Homebrew's dependency as fallback
if [ -z "${JAVA_HOME}" ]; then

  # Check if there is a JDK installed in the system
  jdkcount=$(find /Library/Java/JavaVirtualMachines/ -name java | wc -l)

  # If there is not, use the JDK from Homebrew installed as a dependency
  if [ $jdkcount -eq 0 ]; then
    export JAVA_HOME="/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home"
  fi
fi

# Maven will take care of the rest

exec "/opt/homebrew/Cellar/maven/3.9.0/libexec/bin/mvn"  "$@"
```

cc @reitermarkus @SMillerDev @gdams @p-linnane

**Comment by SMillerDev** [comment]
That’s a bunch of added complexity to avoid what, as far as I know, is the standard way to pick a Java install.

**Comment by brunoborges** [comment]
In comparison, here's Ubuntu's:

```bash
brborges@MSPC-BRBORGES:~$ java -version
-bash: /usr/bin/java: No such file or directory
brborges@MSPC-BRBORGES:~$ sudo apt install default-jdk
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
[...]
Setting up openjdk-11-jdk:amd64 (11.0.18+10-0ubuntu1~22.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jconsole to provide /usr/bin/jconsole (jconsole) in auto mode
Setting up default-jdk (2:1.11-72build2) ...
Scanning processes...
Scanning processor microcode...
Scanning linux images...

Failed to retrieve available kernel versions.

Failed to check for processor microcode upgrades.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
brborges@MSPC-BRBORGES:~$ java -version
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
brborges@MSPC-BRBORGES:~$
```

**Comment by brunoborges** [comment]
So, if the idea is to be as close as possible to what a Linux distribution does, then Homebrew should be configuring the `openjdk` package as the one installed JDK in the environment. Otherwise, the not-so-complex addition is deemed necessary in my opinion.

Not to mention that once `maven` is installed, and the same applies to many other Java-based tools, their execs are available in `PATH`. It feels odd that the JDK is not. And if a JDK is available already, it feels odd that Maven (and other Java-based tools) are using a different JDK (the one from Homebrew), unless `JAVA_HOME` is manually configured by the developer, which again, is not always the case anymore.

**Comment by reitermarkus** [comment]
The key difference is that `apt` requires `sudo`. If you want to use the Homebrew `openjdk` as the system default, you need to follow the caveat and link it to `/Library/Java/JavaVirtualMachines`, which requires `sudo`.

Also, Homebrew does not have a concept of “alternatives”, so I would classify being able to choose your system JDK as an implementation detail of `apt`.

**Comment by brunoborges** [comment]
Alright, I think we got to a point that I agree the current model makes sense, and the proposed change would only address an edge case.

**Pull request closed without merging**
