### PR TITLE
biber: test with texlive

### LINKED ISSUE #172769: biber 2.20 is incompatible with texlive 2024's biblatex
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
> brew config
HOMEBREW_VERSION: 4.3.1-63-gf1a7d97
ORIGIN: https://github.com/Homebrew/brew
HEAD: f1a7d971f2e5d04097d7a360aa1f9a910ccc20f3
wLast commit: 69 minutes ago
Core tap HEAD: f1e6445bf32504e0e3a50169a2ee7f8e7ccba76a
Core tap last commit: 4 days ago
Core tap JSON: 24 May 20:32 UTC
Core cask tap JSON: 24 May 20:32 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
 Clang: 15.0.0 build 1500
Git: 2.45.1 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
dCLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
> brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Biber is a LaTeX bibliography tool, and heavily relies on compatibility with the biblatex LaTeX package. biblatex is packaged as part of TeXlive and thus only updated once a year. The update to Biber 2.20 (#166841) that was merged recently is incompatible with biblatex that is part of TeXlive 2024, thus made biber inoperable. 

This issue was previously reported in #121738 and #95856 but those issues are stale and were closed.

### What happened (include all command output)?

```
INFO - This is Biber 2.20
INFO - Logfile is 'test.blg'
INFO - Reading 'test.bcf'
ERROR - Error: Found biblatex control file version 3.10, expected version 3.11.
This means that your biber (2.20) and biblatex (3.19) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
INFO - ERRORS: 1
```

### What did you expect to happen?

My bibliography to compile

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install texlive biber
cat > test.tex <<EOF
\begin{filecontents}{\jobname.bib}
@book{Labov1972,
    Address = {Philadelphia},
    Author = {William Labov},
    Publisher = {University of Pennsylvania Press},
    Title = {Sociolinguistic Patterns},
    Year = {1972}}

@book{Chomsky1957,
    Address = {The Hague},
    Author = {Noam Chomsky},
    Publisher = {Mouton},
    Title = {Syntactic Structures},
    Year = {1957}}
}
\end{filecontents}

\documentclass{article}
\usepackage[style=authoryear]{biblatex}
\addbibresource{\jobname.bib}
\begin{document}
Some famous linguists wrote a couple of books \autocite{Labov1972,Chomsky1957}.
\printbibliography
\end{document}
EOF
pdflatex test
biber test
```

### PR DESCRIPTION
**Pull request by nwhetsell**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This PR tests `biber` with `texlive` (see https://github.com/Homebrew/homebrew-core/issues/172769#issuecomment-2135829547). The test is currently failing because biber 2.20 isn’t compatible with the version of BibLaTeX installed with the `texlive` formula. To confirm that the test passes with biber 2.19:

```sh
brew install nwhetsell/biber/biber@2.19
brew test biber@2.19
```

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> /home/linuxbrew/.linuxbrew/Cellar/biber/2.20/bin/biber test
  INFO - This is Biber 2.20
  INFO - Logfile is 'test.blg'
  INFO - Reading 'test.bcf'
  ERROR - Error: Found biblatex control file version 3.10, expected version 3.11.
  This means that your biber (2.20) and biblatex (3.19) versions are incompatible.
  See compat matrix in biblatex or biber PDF documentation.
```

**Comment by SMillerDev** [comment]
@nwhetsell is there a way to patch support for a newer version into texlive that you know of?

**Comment by Cerebus** [comment]
I feel like the biber formula should roll back to 2.19, *then* work this PR.

**Comment by nwhetsell** [comment]
Applying this patch to the `texlive` formula gets the `biber` test to pass (at least locally):

```diff
diff --git a/Formula/t/texlive.rb b/Formula/t/texlive.rb
index 7df957dcb9c..22f124fffdb 100644
--- a/Formula/t/texlive.rb
+++ b/Formula/t/texlive.rb
@@ -89,6 +89,16 @@ class Texlive < Formula
 
   fails_with gcc: "5"
 
+  # biber 2.20 requires BibLaTeX 3.20, but TeX Live 2024 ships BibLaTeX 3.19
+  # (https://github.com/Homebrew/homebrew-core/issues/172769). Install BibLaTeX 3.20
+  # so that biber is functional. This resource and the update of BibLaTeX can be
+  # removed when TeX Live 2025 is released. The string biblatex@3.20 should also
+  # be removed from the list of tex_resources in this formula's install method.
+  resource "biblatex@3.20" do
+    url "https://github.com/plk/biblatex/archive/refs/tags/v3.20.tar.gz"
+    sha256 "f936ca60463f47d14ca165226f89388db39080caf49e62fbd36b9787b596b238"
+  end
+
   resource "texlive-extra" do
     url "https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2024/texlive-20240312-extra.tar.xz"
     mirror "https://ftp.tu-chemnitz.de/pub/tug/historic/systems/texlive/2024/texlive-20240312-extra.tar.xz"
@@ -347,7 +357,7 @@ class Texlive < Formula
     ENV["PERL_MM_USE_DEFAULT"] = "1"
     ENV["OPENSSL_PREFIX"] = Formula["openssl@3"].opt_prefix
 
-    tex_resources = %w[texlive-extra install-tl texlive-texmf]
+    tex_resources = %w[biblatex@3.20 texlive-extra install-tl texlive-texmf]
 
     resources.each do |r|
       next if tex_resources.include? r.name
@@ -436,6 +446,16 @@ class Texlive < Formula
     system "make", "install"
     system "make", "texlinks"
 
+    # This can be removed when TeX Live 2025 is released.
+    resource("biblatex@3.20").stage do
+      inreplace "obuild/build.sh",
+                "declare DATE=$(date '+%Y/%m/%d')",
+                # Date from https://github.com/plk/biblatex/releases/tag/v3.20
+                "declare DATE='2024/03/21'"
+
+      system "obuild/build.sh", "install", "3.20", share/"texmf-dist"
+    end
+
     # Create tlmgr config file.  This file limits the actions that the user
     # can perform in 'system' mode, which would write to the cellar.  'tlmgr' should
     # be used with --usermode whenever possible.
```

I’m not sure if I should add this change to this PR or open a new one.

**Comment by SMillerDev** [comment]
> I’m not sure if I should add this change to this PR or open a new one.

Let's add it here

**Comment by ywwry66** [comment]
Will upgrading biblatex potentially cause other incompatibility issues?

**Comment by nwhetsell** [comment]
@ywwry66 I think it’s safe to say that upgrading anything has the potential to cause incompatibility issues, but I don’t see anything at https://github.com/plk/biblatex/issues that indicates BibLaTeX 3.20 won’t work with TeX Live 2024.

**Review by carlocab — APPROVED** [review]
Nice work, @nwhetsell!

**Comment by nwhetsell** [comment]
It looks like the [macOS 14-x86_64 job](https://github.com/Homebrew/homebrew-core/actions/runs/9348394290/job/25727582061?pr=173159) has stalled.

**Comment by carlocab** [comment]
> It looks like the [macOS 14-x86_64 job](https://github.com/Homebrew/homebrew-core/actions/runs/9348394290/job/25727582061?pr=173159) has stalled.

Yup. I'e cancelled it. Will restart it when GitHub catches up with the cancellation.

**Comment by nwhetsell** [comment]
It doesn’t look like a log is available for the [“Linux (deps)” job](https://github.com/Homebrew/homebrew-core/actions/runs/9348394290/job/25798537119?pr=173159); I’m not sure what’s causing that to fail.

**Comment by nwhetsell** [comment]
Would it be possible to re-run the [Linux (deps)](https://github.com/Homebrew/homebrew-core/actions/runs/9348394290/job/25798537119?pr=173159) check, or to a view a log of it?

**Comment by nwhetsell** [comment]
From the [summary](https://github.com/Homebrew/homebrew-core/actions/runs/9348394290?pr=173159), it looks like the failing check isn’t running at all:

> This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.

(I’m probably missing something, but I can’t tell if this check is needed. Running `brew uses --eval-all biber` seems to indicate that there are no core formulae that depend on `biber`.)

**Review by SMillerDev — APPROVED** [review]

**Comment by nwhetsell** [comment]
It looks like https://ftp.math.utah.edu was down: https://github.com/Homebrew/homebrew-core/actions/runs/9924689454/job/27423779856#step:4:40:

```
==> brew audit --formula texlive --online --git --skip-style
==> FAILED
Full audit --formula texlive --online --git --skip-style output
  texlive
    * Stable: The source URL https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2024/texlive-20240312-source.tar.xz is not reachable
    * Stable resource "texlive-extra": The source URL https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2024/texlive-20240312-extra.tar.xz is not reachable
    * Stable resource "install-tl": The source URL https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2024/install-tl-unx.tar.gz is not reachable
    * Stable resource "texlive-texmf": The source URL https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2024/texlive-20240312-texmf.tar.xz is not reachable
    * HEAD resource "texlive-extra": The source URL https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2024/texlive-20240312-extra.tar.xz is not reachable
    * HEAD resource "install-tl": The source URL https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2024/install-tl-unx.tar.gz is not reachable
    * HEAD resource "texlive-texmf": The source URL https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2024/texlive-20240312-texmf.tar.xz is not reachable
```

Hopefully this is an intermittent issue.

**Pull request merged**
