### PR TITLE
qt: build with -proprietary-codecs by default

### PR DESCRIPTION
**Pull request by Lanny**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Added option to build Qt with proppritary codecs.

### CODE REVIEW

**Comment by fxcoudert** [comment]
From [Qt WebEngine doc](https://doc.qt.io/qt-5/qtwebengine-features.html):

> Qt WebEngine supports the MPEG-4 Part 14 (MP4) file format only if the required proprietary audio and video codecs, such as H.264 and MPEG layer-3 (MP3), have been enabled. Proprietary codecs can be enabled by passing the following option when configuring Qt: `-proprietary-codecs`
>
> Warning: When distributing proprietary codec libraries, you must acquire licenses for them.

I'm not sure we really want one more option for Qt…

**Comment by ilovezfs** [comment]
@RyanJenkins what are you planning to do with this option?

**Comment by ilovezfs** [comment]
@RyanJenkins thanks for this PR! However, we're not planning on adding any new options to the `qt` formula at this time because they trigger lengthy source builds that are prone to failure. You might want to consider hosting a version of the qt formula with this option enabled [in your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap).

**Comment by The-Compiler** [comment]
FWIW I know a handful of people wanting this option for qutebrowser alone, I'm sure that there are other users which would find it useful as well. Can you elaborate on "because they trigger lengthy source builds that are prone to failure"? Do you check all combinations of options on CI?

**Comment by ilovezfs** [comment]
>Do you check all combinations of options on CI?

Nope. We only build the default configuration and the resulting build becomes the binary bottle we distribute.

**Comment by The-Compiler** [comment]
I don't follow then - if it's only people using those options with a manual build, surely this is less error-prone than everyone editing their Formulas by hand (which is what's currently happening)?

**Comment by ilovezfs** [comment]
@The-Compiler the difference is that if it's an option in our formula, then we will attempt to support users to overcome the inevitable build failures they hit when passing the option. If the users are editing the formula by hand, then they're on their own in terms of getting any support from us when the build fails.

**Comment by ilovezfs** [comment]
Let's make this the default.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
> Let's make this the default.

> Warning: When distributing proprietary codec libraries, you must acquire licenses for them.

Are we allowed to, legally?

**Comment by scpeters** [comment]
I think this doesn't add proprietary codecs to the qt bottle but rather allows them to be found if they are already installed on the system.

**Comment by DomT4** [comment]
Okay, that makes sense.

Does this impact the redistributability _(unsure this is an actual word but we'll roll with it)_ of `.app` bundles generated with `macdeployqt`? Are the non-free libraries pulled into that process?

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @RyanJenkins! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
