### PR TITLE
boost 1.84

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Shall I close https://github.com/Homebrew/homebrew-core/pull/158705 then?

**Comment by iMichka** [comment]
Sorry, I missed #158705, my bad :(. Your's did not have the "long build" label, and as I did not see boost 1.84 in the long builds, I did not check for it in the other pull requests. I can push my changes to your pull request if you want, or we can close your's, as you wish.

**Comment by SMillerDev** [comment]
The python failure makes no sense since it seems to be using C++14 on our side.

**Comment by iMichka** [comment]
I have a bunch of patches ready, will push as soon as I made significant progress, as not to pollute the long build queue too early.

**Review by SMillerDev — APPROVED** [review]

**Comment by iMichka** [comment]
`fastnetmon` test failure is probably transient, there is a 15 sleep in that test, that probably needs to be extended for long builds ...

I'm going to merge this. I'm not sure why the `dspdfviewer` bottle is not found in 2 reverse deps tests (maybe a cache issue), I'll keep an extra eye open if anything is missing regarding bottles at the end

**Comment by iMichka** [comment]
> @iMichka Doesn't the build failing for `fastnetmon` on `12-x86_64` and `13-x86_64` not only the dependencies testing means it'll need some bottle rebuild after merge, though?

It's all good, no bottles were lost. Only `dspdfviewer` which I have added in #161046

**Pull request merged**
