### PR TITLE
vgmstream: update/secure url

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by vszakats** [comment]
This looks unhealthy:
```
==> Downloading https://gitlab.kode54.net/kode54/vgmstream/repository/archive.tar.bz2?ref=r1040
Already downloaded: /Users/brew/Library/Caches/Homebrew/vgmstream-r1040.bz2
==> Verifying vgmstream-r1040.bz2 checksum
Error: No such file or directory - test
```

**Comment by ilovezfs** [comment]
What you have will cause
```
Patch: https://github.com/Homebrew/homebrew-core/pull/10898.patch
==> Applying patch
Applying: vgmstream: update/secure url
Applying: use tarball
Applying: remove version (audit didn't complain, but anyway)
==> Patch closes issue #10898
Error: invalid attribute for formula 'vgmstream': version (nil)
```

**Comment by vszakats** [comment]
I've found some formulae that get away without it (`flake8`, `jerasure`, `gf-complete`), but I'll restore it.

**Comment by ilovezfs** [comment]
I think the problem is that their tag starts with a letter and brew is getting confused.

**Comment by vszakats** [comment]
Oh sure, got it!

**Comment by ilovezfs** [comment]
We can cheat by using the .tar or the .zip :)

**Comment by vszakats** [comment]
I'll respect the green checkmark and stop here :)

**Comment by ilovezfs** [comment]
:laughing:

**Comment by vszakats** [comment]
I just saw you made the change and _hence_ the checkmark, cheers then! :)

**Comment by ilovezfs** [comment]
Thanks @vszakats

**Pull request closed without merging**
