### PR TITLE
grype syft: update `ldflags`

### PR DESCRIPTION
**Pull request by kzantow**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This PR updates the Syft and Grype formulae to have the correct `ldflags`, including the commit SHA that necessitated changing to use the repository checkout.

### CODE REVIEW

**Comment by p-linnane** [comment]
You will need one commit per formula in this format: `grype: update ldflags` and `syft: update ldflags` or something to that effect. The formula name needs to be first.

**Comment by kzantow** [comment]
Thanks, @p-linnane; I've updated the commits

**Review by chenrui333 — CHANGES_REQUESTED** [review]
we dont do commit sha anymore, those are not useful for homebrew

**Comment by chenrui333** [comment]
@kzantow thanks for your PR. I dont think we need sha (as homebrew mostly doing release binary and track down the release tag).

I am gonna close this for now.

**Comment by kzantow** [comment]
Hi @chenrui333 the problem we have is not all the `ldflags` are being set correctly, so if you run `syft version` you will get this output:
```
$ syft version
Application:     syft
Version:         0.91.0
BuildDate:       2023-09-20T18:38:37Z
GitCommit:       Homebrew
GitDescription:  [not provided]
Platform:        darwin/amd64
GoVersion:       go1.21.1
Compiler:        gc
```
You can see the `GitCommit` is clearly not being set properly and the `GitDescription` is not being set at all. This PR corrects the issue in a manner similar to the [docker-buildx formula](https://github.com/Homebrew/homebrew-core/blob/e497d00dfab5d6dc660fe42a9ea120eca73fd130/Formula/d/docker-buildx.rb#L26). Why close this?

**Pull request closed without merging**
