### PR TITLE
open-mesh 11.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  /usr/bin/env tar --extract --no-same-owner --file /Users/brew/Library/Caches/Homebrew/downloads/8de1d6171eb02b9ba1dbed7f3651f7615bdd9fe74564ee9b9a2edc960434a9eb--OpenMesh-11.0.0.tar.bz2 --directory /private/tmp/homebrew-unpack20240515-4738-c7w8f4
  tar: Error opening archive: Unrecognized archive format
```

**Comment by chenrui333** [comment]
cc @Homebrew/core  for thoughts.

**Comment by carlocab** [comment]
```
❯ curl -OL https://www.graphics.rwth-aachen.de/media/openmesh_static/Releases/11.0/OpenMesh-11.0.0.tar.bz2
[snip]
❯ file OpenMesh-11.0.0.tar.bz2
OpenMesh-11.0.0.tar.bz2: HTML document text, Unicode text, UTF-8 text, with very long lines (14297)
```
Bad URL. Have you checked that upstream didn't upload to a different link? Otherwise, it's an upstream bug.

**Comment by chenrui333** [comment]
hmm, gonna email upstream about the file corruption issue.

**Comment by chenrui333** [comment]
wait for the upstream response on this (I cannot open an issue on their gitlab repo), closing it for now

**Pull request closed without merging**
