### PR TITLE
ruff 0.0.225

### PR DESCRIPTION
**Pull request by messense**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
==> cargo install --no-default-features --locked --root /opt/homebrew/Cellar/ruff/0.0.225 --path .
error: no packages found with binaries or examples
```

**Comment by messense** [comment]
Fixed, the `ruff` cli binary was moved to `ruff_cli` subdirectory: https://github.com/charliermarsh/ruff/tree/main/ruff_cli

**Comment by messense** [comment]
Seems like the x86_64 macOS runners are too slow?

**Comment by SMillerDev** [comment]
It seems that way, but I think something else is going on since it's unlikely they are 18x slower than ARM.

**Comment by SMillerDev** [comment]
Especially since Linux worked fine in 11 minutes

**Comment by messense** [comment]
Yeah, the build logs are too sparse, doesn't help much. Could you trigger a re-run failed jobs to see if it's a temporary issue or not?

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
