### PR TITLE
octant 0.14.0

### PR DESCRIPTION
**Pull request by GuessWhoSamFoo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
==> /usr/local/Cellar/octant/0.14.0/bin/octant --kubeconfig /private/tmp/octant-test-20200717-57053-1awxlu5/config 2>&1
Killing child processes...
Error: octant: failed
An exception occurred within a child process:
  Timeout::Error: execution expired
```

**Comment by claui** [comment]
Running `brew test octant` locally spawns a browser window asking for stuff.

grafik

The test appears to wait for user input so that would explain the timeout on CI.

**Comment by wwitzel3** [comment]
Octant no longer fails when it cannot find a valid kubeconfig. It instead prompts the user for one.

This is the offending line in the current formula https://github.com/Homebrew/homebrew-core/blob/6a8f5692ae05d70f347ce194d9cd892370712239/Formula/octant.rb#L51

**Comment by GuessWhoSamFoo** [comment]
Updated assert statements and made sure the browser doesn't open during brew test. Thanks for the callout @claui !

**Review by claui — APPROVED** [review]

**Comment by claui** [comment]
Thanks @GuessWhoSamFoo! 🍻

**Pull request closed without merging**
