### PR TITLE
php@7.0: import from homebrew/php

### PR DESCRIPTION
**Pull request by ikari7789**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Formula is _literally_ copy + paste from PHP 7.1 (minus the name/URLs/checksums).

### CODE REVIEW

**Comment by ilovezfs** [comment]
This was intentionally not migrated. Why do you think this is still needed when 7.1 and 7.2 are available, active support for 7.0 has already ended upstream, and security support expires in a few months?

**Comment by ikari7789** [comment]
@ilovezfs Same can be said for php@5.6. Just because support is ending doesn't mean that there aren't still a lot of people using it.

**Comment by ilovezfs** [comment]
We wanted to keep at least one from the 5.x series so that's not the same.

**Comment by ikari7789** [comment]
The basis for wanting to have a PHP 7.0 formula is to be able to help in migrating code to newer versions. Namely, there are syntax differences between 7.0 and 7.1.

http://php.net/manual/en/migration71.incompatible.php

If you run composer with PHP 7.1, it will grab packages for 7.1 and write them in the composer.lock. There's no way to have composer back-track the version, even if the minimum supported version is actually PHP 7.0.

While not under active support, it is still receiving security updates. PHP isn't following "semantic" versioning in the most precise manner, and each version, 5.6, 7.0, 7.1, 7.2 can really be considered a major release on it's own.

I'm not trying to push for support of dead software (for which this isn't even), but in this particular case, I feel that the inclusion of 7.0 would be appreciated by more than just myself.

**Comment by ikari7789** [comment]
As for the error from Jenkins, it seems to apply to both 7.1 and 7.2 as well. Should a PR be made to remove icu4c from those as well?

**Comment by ilovezfs** [comment]
No that audit is new-formula only and goes away once something is merged. It's often bogus.

**Comment by Neodork** [comment]
This design choice has effectively deprecated the development of a lot of PHP 7.0 based products. As valet-plus user switching on the fly to 7.0 is now impossible. I agree that developers should be switching to PHP 7.1 as soon as possible however for a lot of products this is not done within 30 days. Meaning that no more local development can be done using the brew PHP 7.0 version. Brew now forces a developer to upgrade 7.1.

**Comment by SMillerDev** [comment]
@Neodork I'd say the end of active support has deprecated development of PHP 7.0 based products. The 5.6 releases are a whole different beast then 7.0 though, so that version was chosen to maintain longer (not just by us but also by the PHP devs themselves).

**Comment by ikari7789** [comment]
@SMillerDev deprecated yes, but not finished. If anything I feel support should be maintained through at least the security window. 5.6 is well into the security phase (and done with active development). I could understand not keeping 5.3, 5.4, and 5.5, but 7.0 is an odd exclusion, especially considering that I basically only requires that the download link requires changing from PHP 7.1.

**Comment by rquadling** [comment]
As there has been a new release of PHP 7.0.29 - http://php.net/ChangeLog-7.php#7.0.29 - continued support would seem sort of required.

It feels strange for a packaging/distribution tool to take it upon itself to act as arbitrator as to what developers and users are allowed to use.

If this formula is not being ported to homebrew-core and homebrew-php is dead, then homebrew is now useless in support for PHP 7.0. 

So. What can we do to get homebrew working for PHP 7.0?

An alternative question is what is the negative of allowing homebrew to supply PHP 7.0 whilst PHP itself is still getting releases. According to http://php.net/supported-versions.php we have another 7 months of support to go before it is a dead version.

And only 8 months for PHP 5.6

Please reinstate this formula.

**Comment by ilovezfs** [comment]
OK.

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @ikari7789! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
