### PR TITLE
Add pack formula

### PR DESCRIPTION
**Pull request by lucperkins**
This is a second attempt to add a formula for the `pack` tool (information [here](https://buildpacks.io)

### CODE REVIEW

**Review by SMillerDev — COMMENTED** [review]
thanks for the review, couple of comments still.

**Review by mistydemeo — CHANGES_REQUESTED** [review]
Looks like the binary is built incorrectly, which is why the test is failing. It's not executable because it's not a Mach-O executable; I'm seeing:

```
file /usr/local/Cellar/pack/0.0.9/bin/pack
/usr/local/Cellar/pack/0.0.9/bin/pack: current ar archive
```

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by mistydemeo** [comment]
Looks like the test is failing; does it require Docker to run?

Thanks for making these changes! I think the name `pack` is too generic, and likely to cause confusion with other things called `pack`. How about `buildpacks` or `buildpacks-pack`?

**Comment by lucperkins** [comment]
@mistydemeo No, there's no Docker dependency.

Good call on the name change. I switched it to `buildpacks-pack` per your suggestion.

**Pull request closed without merging**
