### PR TITLE
docfx 2.23.1 (new formula)

### PR DESCRIPTION
**Pull request by cglong**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by ilovezfs** [comment]
I made two little tweaks but :+1:

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks for the new formula @cglong! :sparkler:

**Comment by cglong** [comment]
Thanks @ilovefs! :smile: I agree, your edits look a lot nicer. For future reference, when *do* we need to use `.mkpath`? Existing formulae and the documentation seem to use it somewhat inconsistently 😕

**Comment by ilovezfs** [comment]
>when do we need to use .mkpath

In this case it's not needed because `.write` does it: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/pathname.rb#L147

Similarly, `.install` does, too: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/pathname.rb#L103

Some cases where you do need to use `.mkpath` include the following:

- There's a broken Makefile that assumes its target directories are going to exist and we haven't been able to coax upstream into fixing the Makefile yet (e.g. https://github.com/Homebrew/homebrew-core/blob/master/Formula/vmdktool.rb#L17-L31)

- You're creating a directory for your own purposes somewhere in the `buildpath` (e.g. in Go formulae like here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/caddy.rb#L22-L23

- You need to make sure in `post_install` following bottle pouring that a directory in `var` exists (e.g. https://github.com/Homebrew/homebrew-core/blob/master/Formula/mariadb.rb#L132)

**Comment by cglong** [comment]
Thanks for the detailed explanation @ilovezfs! That makes total sense 😸

**Pull request merged**
