### PR TITLE
elasticsearch, kibana 6.8.8

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
```
error kibana@6.8.8: The engine "node" is incompatible with this module. Expected version "10.19.0". Got "10.20.1"
```

Seriously?

**Comment by chrmoritz** [comment]
There is a reason, why we used to ship the exact requested node LTS version as a request.

If you want to continue to use `node@10` for it, you might be better done with removing the `engines.node` field from the `package.json`, because it's checked in multiple places by both `yarn` and their own build scripts.

https://github.com/elastic/kibana/blob/v6.8.8/package.json#L430

**Comment by SMillerDev** [comment]
Why aren't we shipping 7.x?

**Comment by chrmoritz** [comment]
Because:

* it's a complicated update and we still need to find someone, who wants to do it
* not all `beats` are migrated yet to allow a OSS only build, so we would need to remove some of them, because these old 6.x.x `beats` aren't compatible with the 7.x.x stack

**Comment by Bo98** [comment]
> because it's checked in multiple places by both `yarn`

I fully expected their documented way to deal with it (`ignore-engines`) to work. Apparently not.

**Comment by Bo98** [comment]
Oh it did - I just misread the error.

**Comment by Bo98** [comment]
I'll deal with `beats` this weekend.

**Pull request closed without merging**
