### PR TITLE
qt 5.15.0 pyside 5.15.0

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
There're 2 fails: 
* `brew linkage --test pyside`: `pyside` requires a version bump, but probably we'd better wait for the corresponding `pyside` release (currently it's 5.14.2.1)
* `brew test --verbose qwtpolar`: https://github.com/Homebrew/homebrew-core/pull/55323/checks?check_run_id=710913076#step:6:14799
```
2020-05-27T07:42:30.9820500Z In file included from main.cpp:1:
2020-05-27T07:42:30.9820620Z In file included from /usr/local/Cellar/qt/5.15.0/lib/QtWidgets.framework/Headers/qapplication.h:44:
2020-05-27T07:42:30.9821030Z In file included from /usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qcoreapplication.h:46:
2020-05-27T07:42:30.9821170Z In file included from /usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qobject.h:49:
2020-05-27T07:42:30.9821280Z In file included from /usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qlist.h:47:
2020-05-27T07:42:30.9821410Z In file included from /usr/local/Cellar/qt/5.15.0/lib/QtCore.framework/Headers/qhashfunctions.h:47:
2020-05-27T07:42:30.9821910Z In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/numeric:148:
2020-05-27T07:42:30.9822680Z /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:325:9: error: no member named 'isless' in the global namespace
2020-05-27T07:42:30.9822820Z using ::isless;
2020-05-27T07:42:30.9822920Z       ~~^
2020-05-27T07:42:30.9823550Z /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'islessequal' in the global namespace
2020-05-27T07:42:30.9823780Z using ::islessequal;
2020-05-27T07:42:30.9824000Z       ~~^
2020-05-27T07:42:30.9825220Z /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:327:9: error: no member named 'islessgreater' in the global namespace
2020-05-27T07:42:30.9825910Z using ::islessgreater;
2020-05-27T07:42:30.9826240Z       ~~^
2020-05-27T07:42:30.9827480Z /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:328:9: error: no member named 'isunordered' in the global namespace
2020-05-27T07:42:30.9827730Z using ::isunordered;
2020-05-27T07:42:30.9827890Z       ~~^
2020-05-27T07:42:30.9829290Z /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
2020-05-27T07:42:30.9829560Z using ::isunordered;
2020-05-27T07:42:30.9831300Z       ~~^
2020-05-27T07:42:30.9831530Z 177 warnings and 13 errors generated.
2020-05-27T07:42:30.9831710Z make[1]: *** [obj/main.o] Error 1
2020-05-27T07:42:30.9832600Z make: *** [sub-spectrogram-make_first] Error 2
2020-05-27T07:42:30.9833510Z [31mError:[0m qwtpolar: failed
2020-05-27T07:42:30.9833690Z An exception occurred within a child process:
2020-05-27T07:42:30.9833880Z   BuildError: Failed executing: make
```

**Comment by Bo98** [comment]
qwtpolar might need a `depends_on :xcode => :build`.

`qmake` is known to not work well with the CLT.

**Comment by bayandin** [comment]
> qwtpolar might need a `depends_on :xcode => :build`.
> 
> `qmake` is known to not work well with the CLT.

Do you mean `depends_on :xcode => :test`? Or we need to rebuild `qwtpolar` with `depends_on :xcode => :build`?
Because `qwtpolar` runs `qmake` in test block.

**Comment by Bo98** [comment]
The bounds on `:xcode` requirements aren't followed closely so anything works really.

I just assumed the build was broken too (it also uses `qmake`) - but maybe we're lucky and it isn't.

**Comment by bayandin** [comment]
Since `brew test --verbose qwtpolar` failure is not introduced by these changes I would proceed and merge this PR.

**Pull request closed without merging**
