### PR TITLE
asdf 0.9.0

### PR DESCRIPTION
**Pull request by unitof**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by sshishov** [comment]
After the upgrade, ASDF is not working as `ASDF_DIR` location is incorrect

**Comment by emiliadecaudin** [comment]
Can corroborate @sshishov's issue. Fixed temporarily by replaced instances of `lib/commands` with `libexec/lib/commands` in the `libexec/bin/asdf`.

**Comment by unitof** [comment]
Appears to be working on M1 Mac after fresh reinstall. `ASDF_DIR=/opt/homebrew/Cellar/asdf/0.9.0/libexec`.

@sshishov & @emiliadecaudin, are you on Apple Silicon or Intel Macs?

**Comment by emiliadecaudin** [comment]
@unitof I'm on Intel. Looks like the issue is with the plugin we are using to load asdf: https://github.com/ohmyzsh/ohmyzsh/pull/10481

**Comment by carlocab** [comment]
> Appears to be working on M1 Mac after fresh reinstall. `ASDF_DIR=/opt/homebrew/Cellar/asdf/0.9.0/libexec`.

This should be `ASDF_DIR=/opt/homebrew/opt/asdf/libexec`. Please avoid using Cellar paths -- these could change at any time.

**Pull request closed without merging**
