### PR TITLE
kibana 6.8.0

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by zbeekman** [comment]
Audit failure due to out of date aliases:
```
Error: 2 problems in 1 formula detected
kibana:
  * Formula has other versions so create a versioned alias:
      cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases
      ln -s ../Formula/kibana.rb kibana@6.8
  * Formula has invalid versioned aliases:
      kibana@6.7
```

Please update the aliases. Thanks!

**Comment by chenrui333** [comment]
updating it now.

**Comment by chenrui333** [comment]
Should good now!

**Pull request closed without merging**
