### PR TITLE
snort 2.9.14.1

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
@timesflying please rebase to resolve the conflict and retrigger the build

**Comment by timesflying** [comment]
i dare thinking of : SUCCESS?

**Comment by SMillerDev** [comment]
You made a merge commit. Can you rebase instead?

**Comment by timesflying** [comment]
not a clue, sorry.

**Comment by chenrui333** [comment]
@timesflying Do you mind submitting a brand new PR on this upgrade? Thanks!

**Comment by chenrui333** [comment]
meanwhile, I am also testing the PR build locally as well.

**Comment by chenrui333** [comment]
passed install and test locally.

```
/Library/Taps/homebrew/homebrew-core/Formula/snort.rb --verbose
==> Caveats
For snort to be functional, you need to update the permissions for /dev/bpf*
so that they can be read by non-root users.  This can be done manually using:
    sudo chmod o+r /dev/bpf*
or you could create a startup item to do this for you.
==> Summary
🍺  /usr/local/Cellar/snort/2.9.14.1: 286 files, 8MB, built in 2 minutes 3 seconds
Removing: /Users/ruichen/Library/Caches/Homebrew/snort--2.9.12.tar.gz... (6.2MB)
==> Caveats
==> libpcap
libpcap is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have libpcap first in your PATH run:
  echo 'export PATH="/usr/local/opt/libpcap/bin:$PATH"' >> ~/.bash_profile

For compilers to find libpcap you may need to set:
  export LDFLAGS="-L/usr/local/opt/libpcap/lib"
  export CPPFLAGS="-I/usr/local/opt/libpcap/include"

For pkg-config to find libpcap you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/libpcap/lib/pkgconfig"

==> snort
For snort to be functional, you need to update the permissions for /dev/bpf*
so that they can be read by non-root users.  This can be done manually using:
    sudo chmod o+r /dev/bpf*
or you could create a startup item to do this for you.
```

**Comment by chenrui333** [comment]
Also the latest version seems `2.9.15`

**Comment by timesflying** [comment]
Have done that. Same as usual, works fine on my machine though.

**Comment by SMillerDev** [comment]
You didn't change your PR with it though.

**Comment by timesflying** [comment]
??
Opened a brand new PR with snort 2.9.15.0, as requested I thought.

**Comment by SMillerDev** [comment]
I just saw it, the idea was to update this one though. So instead I'll close this.

**Pull request closed without merging**
