### PR TITLE
git-branchless 0.4.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
Looks like `openssl` dependency wasn't needed to build. However I'm not sure if the tool then doesn't use it for pull/fetch/push commands as the test doesn't test this, how to be sure? If it's still required I guess however it's safe to upgrade to `openssl@3`.

**Comment by SMillerDev** [comment]
Since it's rust it should probably be a linux only dependency

**Comment by Porkepix** [comment]
> Since it's rust it should probably be a linux only dependency

Isn't there a way to test it to be sure it's required and not add unneeded dependencies?

**Comment by bayandin** [comment]
> > Since it's rust it should probably be a linux only dependency
> 
> Isn't there a way to test it to be sure it's required and not add unneeded dependencies?

Not really, even unlinked dependency can be used in a runtime

**Review by bayandin — APPROVED** [review]

**Pull request closed without merging**
