### PR TITLE
add libglade dependency to pygtk

### PR DESCRIPTION
**Pull request by blogabe**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Why is libglade necessary/useful?

**Comment by blogabe** [comment]
Formula I host on my personal tap that requires pygtk with libglade.  Rather than host my formula and host another version of pygtk that has the libglade dependency, I'm hoping we can add libglade to the master formula on core.

This is one of the ramifications of removing options from formulae.  I'm not relitigating it as maintainers have made clear this isn't coming back, but downstream impact on personal taps is that our dependencies now need to be duplicated and kept in sync as well not just the main formula we're hosting as well.

Thank you for your consideration.

**Comment by fxcoudert** [comment]
It probably makes sense to provide the full functionality (and the dependencies are already so numerous…).

Let's ask @tschoonj for an expert opinion, however.

**Comment by tschoonj** [comment]
I am ok with this but... I would not want to depend on a project like pygtk that was last updated in 2011, that has to be built against a particular dependency like libglade that was last updated in 2009.

Just my two cents.

**Comment by blogabe** [comment]
Thank you @fxcoudert and @tschoonj

**Pull request closed without merging**
