### PR TITLE
hashcat 5.1.0

### PR DESCRIPTION
**Pull request by weinshel**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Upgrade to hashcat 5.1.0.

Last time I tried to submit an upgrade to hashcat there were some weird CI failures, but things are seeming less flakey on my local machine with this update so hopefully it will work now.

### CODE REVIEW

**Comment by weinshel** [comment]
Hm, I'm not able to reproduce the test failure on my own machine running Mojave, and it's only failing on the Mojave CI but not the others, so not sure what the cause it.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
And it's passing locally for me…

**Comment by leonklingele** [comment]
Why was this failing? Jenkins has cleaned up already..
Test passes on 10.11.6 and 10.12.6.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by Habbie** [comment]
Maybe removing `2>/dev/null` will provide some insights?

**Comment by leonklingele** [comment]
Please reopen.

**Comment by leonklingele** [comment]
@fxcoudert can you please trigger a rebuild?

**Comment by zbeekman** [comment]
@BrewTestBot test this please

**Comment by zbeekman** [comment]
[Looks like a legit test failure](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/40554/version=mojave/testReport/junit/brew-test-bot/mojave/test_hashcat/) on mojave.

```
==> ./hashcat -m 500 -a 0 --force --quiet --potfile-disable --optimized-kernel-enable example500.hash example.dict 2>/dev/null
Error: hashcat: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<255>.
```

**Comment by zbeekman** [comment]
> Maybe removing `2>/dev/null` will provide some insights?

Yes, removing this on [L71](https://github.com/Homebrew/homebrew-core/pull/36348/files#diff-167d97a33c7b0b09c47aa6582d40b374L71) would add more info.

**Pull request closed without merging**
