### PR TITLE
dcd/dfix/dfmt change github user

### PR DESCRIPTION
**Pull request by John-Colvin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

@Hackerpilot's dfmt, dfix & dcd repos have been moved to the official @dlang-community organisation.

The github redirects would probably work forever, but might as well have it right.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@John-Colvin Thanks! It would be cool to have an audit that detects these.

**Comment by ilovezfs** [comment]
@John-Colvin oops ... stumbled into a bug. It looks like dfix doesn't build: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4075/version=sierra/console

**Comment by ilovezfs** [comment]
@John-Colvin looks like we can just blow that directory away, I think: https://github.com/dlang-community/libdparse/commit/1e811d2b5da79ae44dd79b68d1379f67d1250cb9

**Comment by John-Colvin** [comment]
Done. Have listed an [issue](https://github.com/dlang-community/dfix/issues/45) so hopefully can clear it up in the future.

**Comment by ilovezfs** [comment]
@John-Colvin perfect. Thank you! It'll need one more tweak :)
```
iMac-TMP:homebrew-core joe$ brew audit dfix
dfix:
  * C: 19: col 5: Favor modifier `if` usage when having a single-line body. Another good alternative is the usage of control flow `&&`/`||`.
Error: 1 problem in 1 formula
```

**Comment by ilovezfs** [comment]
Thanks for the PR @John-Colvin!

**Pull request merged**
