### PR TITLE
readline 8.2.10

### PR DESCRIPTION
**Pull request by miccal**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
`  configure: error: Could not detect PostgreSQL version from pg_config.`

**Comment by Bo98** [comment]
citus and pg_cron do not look like they need revision bumps for readline - readline generally keeps ABI compatibility.

They're maybe broken for different reasons however.

**Comment by chenrui333** [comment]
> citus and pg_cron do not look like they need revision bumps for readline - readline generally keeps ABI compatibility.
> 
> They're maybe broken for different reasons however.

yeah, sounds about right.

**Comment by p-linnane** [comment]
Kicking off another run now that the above has been addressed

**Review by p-linnane — APPROVED** [review]

**Review by fxcoudert — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
