### PR TITLE
chisel-tunnel 1.9.1 (new formula)

### PR DESCRIPTION
**Pull request by Ishaanahuja7**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Will add conflicts_with pr with formula chisel after this has merged

### CODE REVIEW

**Comment by Ishaanahuja7** [comment]
@SMillerDev Solved by using curl, thanks! Please review

**Review by chenrui333 — DISMISSED** [review]
lgtm, thanks!

**Comment by Ishaanahuja7** [comment]
Please trigger a merge @chenrui333

**Review by fxcoudert — DISMISSED** [review]

**Comment by Ishaanahuja7** [comment]
Whats up with the above comments? Do I need to create another PR for this to merge or something. This hasn't happened before. @chenrui333 @fxcoudert

**Comment by Ishaanahuja7** [comment]
Looks like now I need to give edit access as well. I just did. @BrewTestBot Trigger the merge again. @chenrui333 @fxcoudert

**Comment by fxcoudert** [comment]
There was an issue in the workflow (it hung), let's try it again.

**Review by fxcoudert — APPROVED** [review]

**Review by fxcoudert — APPROVED** [review]

**Pull request merged**
