### PR TITLE
convox 20190509115116

### PR DESCRIPTION
**Pull request by chenrui333**
I did pay attention to this weird release name :)

### CODE REVIEW

**Comment by lembacon** [comment]
@Homebrew/core Do we want to keep adding `HEAD` in these version bump PRs?

**Comment by MikeMcQuaid** [comment]
@lembacon If the user (@chengr28 in this case) can confirm they've personally 1) tested it and 2) needed it then I'd be 👍 otherwise 👎.

**Comment by chenrui333** [comment]
@MikeMcQuaid I think you are referring me?

Yeah, it works.

**Comment by MikeMcQuaid** [comment]
@chenrui333 You'd need to `brew install --HEAD convox`. Do you personally use/need that?

**Comment by chenrui333** [comment]
I actually test it when I am in the branch, `chenrui333:convox-20190509115116`, so I dont think I need that `--HEAD`

**Comment by chenrui333** [comment]
```
git checkout convox-20190509115116
brew install convox
brew test convox
```

**Comment by chenrui333** [comment]
i just removed `HEAD` line as I did not actually use it.

**Pull request closed without merging**
