### PR TITLE
xmrig 6.18.1

### PR DESCRIPTION
**Pull request by JacksonChen666**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  /usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libuv.a(libuv_la-threadpool.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIE
  /usr/bin/ld: failed to set dynamic section sizes: bad value
```

**Comment by JacksonChen666** [comment]
?

**Comment by chenrui333** [comment]
relates to relates to https://github.com/Homebrew/homebrew-core/pull/116656

**Comment by danielnachun** [comment]
For this failure we actually need to rebottle `libuv` so that it is build with `-fPIE`.

**Comment by chenrui333** [comment]
[libuv was rebottled successfully,](https://github.com/Homebrew/homebrew-core/commit/2b6e47ed8be) gonna rebase this PR to the latest amster.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @JacksonChen666!

**Pull request closed without merging**
