### PR TITLE
vcpkg 2024.04.23

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  CMake Error at CMakeLists.txt:196 (cmrc_add_resource_library):
    Unknown CMake command "cmrc_add_resource_library".
```

**Comment by chenrui333** [comment]
- https://github.com/microsoft/vcpkg/releases

**Comment by fxcoudert** [comment]
Super weird. There was a 2024-04-26 release for a couple of hours, but now it's gone!

**Comment by chenrui333** [comment]
they did not complete the release (ie did not generate the github release notes, that might be why, I suspect that they would re-tag the stuff)

**Comment by chenrui333** [comment]
> Super weird. There was a 2024-04-26 release for a couple of hours, but now it's gone!

image

Actually I can see it

**Pull request closed without merging**
