### PR TITLE
libpq 9.6.7

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
Re the test:
```
==> /usr/bin/clang libpq.c -L/usr/local/Cellar/libpq/9.6.7/lib -I/usr/local/Cellar/libpq/9.6.7/include -lpq -o libpqtest
libpq.c:17:15: warning: implicitly declaring library function 'exit' with type 'void (int) __attribute__((noreturn))' [-Wimplicit-function-declaration]
              exit(0);
              ^
libpq.c:17:15: note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'
1 warning generated.
==> ./libpqtest
```

Not a big deal, just annoying & easy to resolve.

**Comment by ilovezfs** [comment]
why didn't we move to 10.x?

**Comment by DomT4** [comment]
No idea. I presumed it was a desire to have a very stable `libpq` formula, given we've kept this up for a while & nobody had said anything.

**Comment by ilovezfs** [comment]
Not intentional but I guess it's fine either way.

**Comment by DomT4** [comment]
I can bump it again if you like.

**Pull request closed without merging**
