### PR TITLE
plantuml 1.2019.3

### PR DESCRIPTION
**Pull request by MindTooth**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by MindTooth** [comment]
Searched for `error` and only found `jasper` to complain.

**Comment by tschoonj** [comment]
I am observing the exact same issue in #37909

**Comment by MindTooth** [comment]
Works just fine locally.  So I suspect the build bot of some kind.  I see your change got merged. 👍

**Comment by tschoonj** [comment]
Can you rebase your branch against origin/master and force push? Perhaps my rebuild of `jasper` fixed the problem for you as well...

**Comment by MindTooth** [comment]
You are the man!  Worked like a charm. :D

**Comment by fxcoudert** [comment]
Thanks @MindTooth !

**Pull request merged**
