### PR TITLE
ansible-lint 5.0.4

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> /opt/homebrew/Cellar/ansible-lint/5.0.4/bin/ansible-lint /private/tmp/ansible-lint-test-20210318-68711-if6dc2/playbook.yml
ERROR    FATAL: Ansible CLI (2.10.6) and python module (2.10.7) versions do not match. This indicates a broken execution environment.
Error: ansible-lint: failed
```

Probably needs a version bump to `ansible` too?

**Comment by carlocab** [comment]
I don't think the revision bump will work. I think `ansible` needs to be bumped to 3.1.0, with its `ansible-base` resource updated.

**Comment by chenrui333** [comment]
cool

**Comment by carlocab** [comment]
Cherry-picked into #73630.

**Pull request closed without merging**
