### PR TITLE
metricbeat 6.2.1

### PR DESCRIPTION
**Pull request by tylerjl**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> make
go build -i
go build github.com/elastic/beats/vendor/github.com/shirou/gopsutil/disk: invalid flag in #cgo LDFLAGS: -mmacosx-version-min=10.10
make: *** [metricbeat] Error 1
```

**Comment by tylerjl** [comment]
Thanks @fxcoudert - the root cause here is that metricbeat [doesn't build on go 1.9.4](https://github.com/elastic/beats/pull/6326). Is there a way to pin `depends_on "go" => :build` in the formula to 1.9.2, or alternatively, any prior art regarding respecting a file like `.go-version` at build time to fetch a specific version? Beats ship those files by default and would help avoid these failures in the future.

**Comment by ilovezfs** [comment]
Nope. It must build with the latest go or we'll need to remove it from Homwbrew.

**Comment by tylerjl** [comment]
The [aforementioned PR](https://github.com/elastic/beats/pull/6326) should get metricbeat into a state that it'll compile with the latest version of go. How do you feel about just closing this one out, and we can update metricbeat when the next release comes out with go 1.9.4 supported?

**Comment by ilovezfs** [comment]
Can that not be applied as a patch?

**Comment by tylerjl** [comment]
I'll take a look at applying it as a patch one the PR has been finalized and merged ⚡️

**Comment by ilovezfs** [comment]
@tylerjl OK thanks. We'll close this out for now then. Let me know if/when you want it re-opened.

**Comment by tylerjl** [comment]
@ilovezfs my branch now has an inline patch which works for me when building the formula from source under golang 1.9.4, there's some comments in there as well indicating when the intermediate patch can be removed once a version supporting 1.9.4 is released.

**Comment by ilovezfs** [comment]
@tylerjl cool. I've reopened this if you want to push new commits.

**Comment by tylerjl** [comment]
Looks like the latest revision with the patch builds cleanly, any other changes needed?

**Review by ilovezfs — APPROVED** [review]

**Comment by commitay** [comment]
Thanks @tylerjl!

**Pull request closed without merging**
