### PR TITLE
evince 3.24.0

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
any thoughts on why this fails to install? I don't understand why there would be trouble writing to `/usr/local/share/mime`

**Comment by fxcoudert** [comment]
sandbox issue? Is `/usr/local/share/mime` in the whitelist?

**Comment by tschoonj** [comment]
@MikeMcQuaid @ilovezfs Any thoughts on this?

**Comment by MikeMcQuaid** [comment]
It should allow writing there: https://github.com/Homebrew/brew/blob/08a22d013e9ba44aa7c4ed4d08bb2fd6aebf7c05/Library/Homebrew/cmd/postinstall.rb#L41-L43. Maybe `/usr/local/share` or `/usr/local/share/mime` need to exist already?

**Comment by tschoonj** [comment]
Hmmm, they should exist already as they are created and populated by `shared-mime-info`

**Comment by ilovezfs** [comment]
This should fix it
```
iMac-TMP:homebrew-core joe$ git diff -- Formula/shared-mime-info.rb 
diff --git a/Formula/shared-mime-info.rb b/Formula/shared-mime-info.rb
index 68da590826..d03fc454c5 100644
--- a/Formula/shared-mime-info.rb
+++ b/Formula/shared-mime-info.rb
@@ -36,9 +36,14 @@ class SharedMimeInfo < Formula
       system "./configure", *args
     end
     system "make", "install"
+    pkgshare.install share/"mime/packages"
+    rmdir share/"mime"
   end
 
   def post_install
+    ln_sf HOMEBREW_PREFIX/"share/mime", share/"mime"
+    (HOMEBREW_PREFIX/"share/mime/packages").mkpath
+    cp (pkgshare/"packages").children, HOMEBREW_PREFIX/"share/mime/packages"
     system bin/"update-mime-database", HOMEBREW_PREFIX/"share/mime"
   end
 ```

**Pull request closed without merging**
