### PR TITLE
poppler 0.73.0

### PR DESCRIPTION
**Pull request by jeroen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Upstream has renamed some cmake variables, see [release notes](https://poppler.freedesktop.org/)

### CODE REVIEW

**Comment by jeroen** [comment]
Hmm it looks like reverse dependency pdftoedn is using some deprecated api's 🤦

**Comment by SMillerDev** [comment]
https://github.com/edporras/pdftoedn/issues/5 is the upstream issue for that.

**Comment by edporras** [comment]
I have released (pdftoedn-0.36.4)[https://github.com/edporras/pdftoedn/archive/v0.36.4.tar.gz] (sha256: `4714f2525a41574ad8601b5d68d82975615a52475088fa9f02e83ecb7a68b363`) and submitted a (PR to resolve pdftoipe)[https://github.com/otfried/ipe-tools/pull/34]

**Comment by jeroen** [comment]
OK thank you! I have updated this PR.

**Comment by fxcoudert** [comment]
Thanks @jeroen for the pull request!

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
