### PR TITLE
github/workflows: bottle with `--only-json-tab`

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Depends on https://github.com/Homebrew/homebrew-test-bot/pull/597

Build all our (new) bottles excluding the tab (which is uploaded and
downloaded from GitHub Packages instead).

This will enable a few things:
- bottles that can be (more) reproducible (as we embed a timestamp without this which means they can't be reproducible more than a  second apart)
- bottles between macOS versions (and perhaps even Linux) that have identical checksums and can be deduplicated by only uploading a single bottle (as GitHub Packages will not store multiple bottles with the same `sha256`)
- bottles identical between macOS and Linux can be migrated to use `all: $SHA256` (already in a Homebrew/brew tag) to share a single bottle for all platforms.
- remove all `bottle :unneeded` and bottle everything
- reduce (perhaps remove) our need for `brew mirror` as in favour of relying on bottles rather than building from source in more cases

Note to @iMichka: you'll definitely want to ensure these flags are passed through and added to all relevenat linuxbrew-core locations on merge. CC me on that PR if you need help with that.

### CODE REVIEW

**Comment by Bo98** [comment]
> * reduce (perhaps remove) our need for `brew mirror` as in favour of relying on bottles rather than building from source in more cases

This’ll require binary relocation to be implemented before we can fully achieve this.

**Comment by MikeMcQuaid** [comment]
> This’ll require binary relocation to be implemented before we can fully achieve this.

@Bo98 I disagree. We already don't support building from source so I don't think it's worth our time implementing a full `brew mirror` replacement on GitHub Packages. I'm open to someone disagreeing and building this, though.

**Comment by Bo98** [comment]
> We already don't support building from source

It's easy to say this, but ultimately we test that flow in CI a fair bit. For example, Go PRs (intentionally) will trigger a build from source test of dependents.

**Comment by MikeMcQuaid** [comment]
> It's easy to say this, but ultimately we test that flow in CI a fair bit. For example, Go PRs (intentionally) will trigger a build from source test of dependents.

Yeh, and in that case: we don't want to have to rely on us manually uploading a mirror either. The main use-case for these mirrors is "URLs that break when they are built from source" which isn't the majority use-case for Homebrew and, in our case, warrants finding a new mirror regardless.

**Comment by carlocab** [comment]
Reliable mirrors would still be good to have, even if we're not considering users building things from source. We rebuild formulae on CI for many different reasons, for example.

**Comment by SMillerDev** [comment]
Yeah, something like unstable upstream hosts still hurt us without a mirror.

**Comment by sjackman** [comment]
Could you report a list of information that is currently stored in `INSTALL_RECEIPT.json` that is not stored in `sh.brew.tab`? I'm just curious what information we're dropping.

**Comment by Bo98** [comment]
Probably [this](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/tab.rb#L321-L344) minus [this](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/tab.rb#L346-L360).

**Comment by sjackman** [comment]
```diff
--- INSTALL_RECEIPT.json	2021-04-12 14:42:10.000000000 -0700
+++ sh.brew.tab	2021-04-12 14:42:09.000000000 -0700
@@ -1,17 +1,8 @@
-aliases
 arch
-built_as_bottle
 built_on
 changed_files
 compiler
 homebrew_version
-installed_as_dependency
-installed_on_request
-poured_from_bottle
 runtime_dependencies
-source
 source_modified_time
 stdlib
-time
-unused_options
-used_options
```

**Comment by carlocab** [comment]
```
==> brew install --only-dependencies ./cdogs-sdl--0.11.1.arm64_big_sur.bottle.tar.gz
==> FAILED
Error: This bottle does not contain the file INSTALL_RECEIPT.json: /Users/brew/actions-runner-x86_64/_work/homebrew-core/homebrew-core/bottles/cdogs-sdl--0.11.1.arm64_big_sur.bottle.tar.gz
```
https://github.com/Homebrew/homebrew-core/pull/75097/checks?check_run_id=2333270172#step:7:46

**Comment by MikeMcQuaid** [comment]
Reverted in 76096f7374. Working on a fix but this will require a new tag to distribute these bottles.

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/brew/pull/11131 will fix this (but it'll require a new tag to revert my revert)

**Pull request merged**
