### PR TITLE
pipx 0.14.0.0

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by zbeekman** [comment]
@AlJohri Any thoughts here?

**Comment by zbeekman** [comment]
```
==> /usr/local/Cellar/pipx/0.13.1.1/bin/pipx --help
Traceback (most recent call last):
  File "/usr/local/Cellar/pipx/0.13.1.1/libexec/bin/pipx", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'userpath' distribution was not found and is required by pipx
Error: pipx: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.
```

**Comment by chenrui333** [comment]
Seems like dep missing.
`pkg_resources.DistributionNotFound: The 'userpath' distribution was not found and is required by pipx`

**Comment by zbeekman** [comment]
@chenrui333 original PR author for pipx, @AlJohri, said they would submit a formula for [userpath](https://github.com/ofek/userpath), but then never did. It looks like they've now decided to make it mandatory, for better or worse.

I think userpath could be a nice addition to homebrew, so we may need a formula for it to continue supporting pipx.

**Comment by zbeekman** [comment]
Alternatively, it appears to be a python package so it may be possible to just vendor it with pipx. (This may defeat the point of their desire to use it though...)

**Comment by AlJohri** [comment]
Yeah this is blocked from merging until this userpath issue is resolved. I will update this issue when that is complete. cc @ofek @jaraco @cs01

**Comment by jaraco** [comment]
There may be other ways to unblock this change:

- include 'userpath' in the pipx homebrew install until it becomes its own recipe
- build/install pipx using pip so that the executable isn't reliant on `pkg_resources` so bypasses the dependency check on invocation (as it is an optional dependency for the command-line).

**Comment by jaraco** [comment]
Are there any Homebrew formulas that use pip to install packages? If not, that's probably something that Homebrew should supply sooner than later as `setup.py install` is being deprecated (and doesn't support installation of newer PEP 517 style packages). I realize that's a broader concern outside the scope of this ticket. I'd be happy to consult on supporting that change.

**Comment by AlJohri** [comment]
@jaraco there's no issue with creating the formula. I've pretty much finished it here: https://github.com/ofek/userpath/issues/4

Just need to resolve the issues with userpath itself: https://github.com/ofek/userpath/pull/6

**Comment by zbeekman** [comment]
> Are there any Homebrew formulas that use pip to install packages?

Sure, I think docker-compose.rb is an OK example: `brew cat docker-compose`

We used to require pip packages be vendored, but no longer, so long as the appropriate flags are passed to `pip` (i.e., don't install binaries, etc.)

**Comment by ofek** [comment]
FYI ofek/userpath#6 is now merged and released on PyPI as version `1.2.0` 😄

**Comment by AlJohri** [comment]
@chenrui333 I found a bunch of issues using pipx through a virtualenv- any reason you changed that part of the formula?

I think the next step is creating the `userpath` homebrew formula (https://github.com/ofek/userpath/issues/4) and then making pipx `depends_on: "userpath"`.

Is that still the case @ofek?

**Comment by chenrui333** [comment]
I think I did the virtualenv installation per the discussion in this thread, I can revert the change on that part. Let me know which way works.

**Comment by ofek** [comment]
@AlJohri Yes, would you like to make the PR?

**Comment by AlJohri** [comment]
@chenrui333 yes, I found issues when putting it in a virtualenv: https://github.com/pipxproject/pipx/issues/60

can you revert that?

@ofek yes, let me submit the userpath formula now. I have not gotten a chance to test the latest changes but I trust it all works. 👍

**Comment by chenrui333** [comment]
@AlJohri, @ofek I have reverted my changes to the original PR. :)

**Comment by pcr910303** [comment]
Any updates on this? Is it still pending due to the userpath formula?

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by jonchang** [comment]
I just pushed up a new commit to try to get this merged.

* dropping the virtualenv stuff for a manual python install (c.f. https://github.com/pipxproject/pipx/issues/60)
* only linking the `pipx` binary since that was causing weird conflicts w/ other formulae

**Pull request closed without merging**
