### PR TITLE
loki 2.1.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Are these two formulae built from the same tarball? Why are they separate formulae?

**Comment by chenrui333** [comment]
yeah, multiple tools from the same artifact.

**Comment by chenrui333** [comment]
same deal like elastic `beats`.

**Comment by chenrui333** [comment]
```
==> Testing logcli
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201226-99154-1vwo5jv.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/logcli.rb --verbose
Error: logcli: failed
An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/local/etc/loki-local-config.yaml
```

**Comment by chenrui333** [comment]
passed the test in my local, I will file logcli separately to see if it works.

**Pull request closed without merging**
