### PR TITLE
yarn 0.21.1

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
This was marked as release on GitHub when I bumped it, but is now no longer. Close it?

**Comment by ilovezfs** [comment]
Yes. This is the second time they've done this.

**Comment by neutric** [comment]
🙄

**Comment by Daniel15** [comment]
> Yes. This is the second time they've done this.

Sorry about that, it looks like a race condition in the Yarn build scripts. I filed a task to look into it: https://github.com/yarnpkg/yarn/issues/2799

**Comment by ilovezfs** [comment]
@Daniel15 thanks for looking into it. In general, it might help to designate pre-release stuff with a "beta" or "rc" label just to avoid such confusions.

**Comment by Daniel15** [comment]
I think there's a reason why we didn't do that, I can't remember though. @bestander may know as he set up the RC release process.

**Pull request closed without merging**
