### PR TITLE
switch to HTTPS for SVN access on sf.net #1

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by DomT4** [comment]
Isn't this going to have the same issues as always? That at least everyone not running Sierra (and possibly even Sierra users) can't access these `svn` checkouts securely? Or did they finally fix the incredibly annoying certificate errors?

**Comment by vszakats** [comment]
Fair question. I'll bring alive my El Cap machine for a test.

**Comment by ilovezfs** [comment]
@DomT4 we're considering that a non-bug bug. It deliberately skips the svn tests everywhere except Sierra now.

**Comment by ilovezfs** [comment]
@DomT4 https://github.com/Homebrew/brew/pull/2262

**Comment by vszakats** [comment]
(Still needs manual confirmation of the cert on El Capitan when using `/usr/bin/svn`.)

**Comment by DomT4** [comment]
> we're considering that a non-bug bug. It deliberately skips the svn tests everywhere except Sierra now.

Yes, I know, I saw the commit at the time. I use a forked Homebrew so I check pretty much everything 😅. But I still think you'll have the situation at least on early versions of Sierra or everything including and before El Cap where users cannot execute `brew fetch` on these secure SVN URLs for at least SF, which has always been problematic in the past.

**Comment by vszakats** [comment]
To address pre-Sierra cases, the protocol could automatically be downgraded on these systems along with a screen warning, if the current user prompt may be a blocker.

**Comment by ilovezfs** [comment]
@DomT4 that sounds like a `brew fetch bug` if it fails instead of prompting :)

**Comment by DomT4** [comment]
> @DomT4 that sounds like a brew fetch bug if it fails instead of prompting :)

It prompts you to accept the certificate IIRC, but Mike has always been (understandably, IMO) firm on Homebrew not requiring interactivity once a command has been issued. Maybe that's changed, but simply seems like a way to break automatic `brew fetch` executions on things like Travis, scripting, etc.

**Comment by DomT4** [comment]
El Cap CI on the other PR confirms issues FWIW:
```
==> brew install --build-bottle --verbose spim
==> FAILED
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170310-89304-j02f3n.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/spim.rb --build-bottle --verbose
==> Cloning https://svn.code.sf.net/p/spimsimulator/code
==> Checking out 681
svn checkout https://svn.code.sf.net/p/spimsimulator/code /Users/brew/Library/Caches/Homebrew/spim--svn -r 681
svn: E170013: Unable to connect to a repository at URL 'https://svn.code.sf.net/p/spimsimulator/code'
svn: E230001: Server SSL certificate verification failed: issuer is not trusted
Error: Failed to download resource "spim"
Failure while executing: svn checkout https://svn.code.sf.net/p/spimsimulator/code /Users/brew/Library/Caches/Homebrew/spim--svn -r 681
```

Several of those.

**Comment by vszakats** [comment]
Worst case, I can downgrade everything to HTTP://, so that it looks organised and they can be bumped to TLS in the future with a simple s&r. Or, I can add `MacOS.version` branching to fall back to HTTP:// on pre-Sierra (though I may need advise on the preferred style for that).

**Comment by ilovezfs** [comment]
I think the cert only has to be accepted once. So we could just accept it on the CI boxes.

**Comment by ilovezfs** [comment]
@DomT4 

>To address pre-Sierra cases, the protocol could automatically be downgraded on these systems along with a screen warning, if the current user prompt may be a blocker.

perhaps you'd be interested in working on adding that to the subversion download strategy? :innocent:

**Comment by DomT4** [comment]
> perhaps you'd be interested in working on adding that to the subversion download strategy? 😇

Heh, I'm going to have to politely decline. I tried the opposite thing last month and didn't get anywhere 😸 https://github.com/Homebrew/brew/pull/1962

**Comment by ilovezfs** [comment]
Another option would be to pass `--trust-server-cert --non-interactive` on < Sierra.

**Comment by vszakats** [comment]
Sierra clean.

**Comment by ilovezfs** [comment]
>Sierra clean.

Sounds like a cologne.

**Comment by ilovezfs** [comment]
The head URLs are fine because they only go through audit not fetch.

I think until someone addresses this in Homebrew/brew, we should branch the stable URLs so that they don't fail CI.

An exception is is exult since it's now on GitHub: https://github.com/exult/exult/releases switching it over.

**Comment by vszakats** [comment]
Okay, moving stable URL updates to a separate PR.

**Comment by ilovezfs** [comment]
>Okay, moving stable URL updates to a separate PR.

yup that makes sense

**Comment by ilovezfs** [comment]
Let's also remove `highlight` from the PR since steps mentioned here have not been followed yet to my knowledge: https://github.com/Homebrew/homebrew-core/issues/10486#issuecomment-284225257

**Comment by ilovezfs** [comment]
Fine to update highlight's head url though if you want

**Comment by vszakats** [comment]
Okay, removed anything but the head URL update from `hightlight`.

**Comment by ilovezfs** [comment]
Thanks @vszakats. Shipped!

**Pull request merged**
