### PR TITLE
PHP switch back to pcre

### LINKED ISSUE #36031: PHP segfaults and impossible to use XDebug when using pcre2
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Since the commit of  #35660 PHP segfaults in some situations and XDebug 2.7 isn't working anymore!

There're already related issues:
- #35491
- https://github.com/bobthecow/psysh/issues/540

When I switch back to "pcre" instead of "pcre2", everything is working again!

### PR DESCRIPTION
**Pull request by mkalkbrenner**
fixes #36031

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Reading the docs again carefully, this change wouldn't have any effect: http://php.net/manual/en/pcre.installation.php it'd use the provided pcre either way since there's no `--with-pcre` specified.

**Comment by javian** [comment]
@SMillerDev looks right. Perhaps it would be possible to remove the dependency completely or use `--with-external-pcre` as the option is called to use the external library.

**Comment by SMillerDev** [comment]
Seems good to me, @mkalkbrenner could you edit this PR to remove the PCRE dependency completely then?

**Review by SMillerDev — CHANGES_REQUESTED** [review]
See previous comment

**Comment by javian** [comment]
I took the liberty of editing the formula, lets see how it pans out.

**Comment by mkalkbrenner** [comment]
Sorry, I don't know exactly if there's something left to do for me to fullfill your request as the PR already just removes the dependency.

**Comment by javian** [comment]
@mkalkbrenner I think we are good go as far as removing the dependency but I was wondering if we should add a test for what you discovered so that we don't run in to the same issue again. Would that be possible?

**Comment by javian** [comment]
Can you rebase the pr please since there's a new php version out ?

**Comment by mkalkbrenner** [comment]
fixed by #36975

**Pull request closed without merging**
