### PR TITLE
dmd 2.101.2

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by Porkepix** [comment]
Resources could probably make use of the livecheck update too; however while I know it can get a specific livecheck rules, can it inherit of the main livecheck edit directly into resources without having to provide specific livecheck which would be duplicates?

**Comment by chenrui333** [comment]
> Resources could probably make use of the livecheck update too; however while I know it can get a specific livecheck rules, can it inherit of the main livecheck edit directly into resources without having to provide specific livecheck which would be duplicates?

I dont think it is fully implemented yet, cc @nandahkrishna

**Comment by Porkepix** [comment]
> > Resources could probably make use of the livecheck update too; however while I know it can get a specific livecheck rules, can it inherit of the main livecheck edit directly into resources without having to provide specific livecheck which would be duplicates?
> 
> I dont think it is fully implemented yet, cc @nandahkrishna

I thought I saw some PRs editing the livecheck on resources, though?

**Comment by nandahkrishna** [comment]
> can it inherit of the main livecheck edit directly into resources without having to provide specific livecheck which would be duplicates?

While it is possible to do this, I plan to add a strategy to make this easier. I'll create a follow-up PR for this formula and a few others too once the strategy has been implemented in Homebrew/brew.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
