### PR TITLE
pytorch 2.0.1 torchvision 0.15.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
only failed on 13-arm

```
    /tmp/pytorch-20230521-17010-1orpcas/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:16:8: error: unknown token in expression
          ".intel_syntax noprefix\t\n"
           ^
    <inline asm>:2:18: note: instantiated into assembly here
            mov [rbp - 48], %r14
                            ^
    /tmp/pytorch-20230521-17010-1orpcas/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:188:8: error: unknown token in expression
          ".intel_syntax noprefix\t\n"
           ^
    <inline asm>:2:18: note: instantiated into assembly here
            mov [rbp - 48], %r14
                            ^
    /tmp/pytorch-20230521-17010-1orpcas/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:386:8: error: unknown token in expression
          ".intel_syntax noprefix\t\n"
           ^
    <inline asm>:2:18: note: instantiated into assembly here
            mov [rbp - 48], %r14
                            ^
    /tmp/pytorch-20230521-17010-1orpcas/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:548:8: error: unknown token in expression
          ".intel_syntax noprefix\t\n"
           ^
    <inline asm>:2:18: note: instantiated into assembly here
            mov [rbp - 48], %r14
                            ^
    /tmp/pytorch-20230521-17010-1orpcas/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:729:8: error: unknown token in expression
          ".intel_syntax noprefix\t\n"
           ^
    <inline asm>:2:18: note: instantiated into assembly here
            mov [rbp - 48], %r14
                            ^
    /tmp/pytorch-20230521-17010-1orpcas/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:929:8: error: unknown token in expression
          ".intel_syntax noprefix\t\n"
           ^
    <inline asm>:2:18: note: instantiated into assembly here
            mov [rbp - 48], %r14
                            ^
    6 errors generated.
```

**Comment by chenrui333** [comment]
Good to be merged now 🍻

**Comment by carlocab** [comment]
Still needs upstream report -- Intel Ventura failed.

**Review by carlocab — APPROVED** [review]
Let's move this along, but can someone please report the `pytorch` build failure on macOS 13-x86_64 upstream?

**Review by carlocab — APPROVED** [review]

**Pull request merged**
