### PR TITLE
swift 6.0.1

### PR DESCRIPTION
**Pull request by Bo98**
Created by `brew update-swift`. 🚀

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by SMillerDev** [comment]
```
2024-09-17T16:54:51.6742030Z /tmp/swift-20240917-9833-635xgc/swift-testing/Sources/Testing/ABI/EntryPoints/EntryPoint.swift:37:72: error: reference to static property 'arguments' is not concurrency-safe because it involves shared mutable state
2024-09-17T16:54:51.6742930Z  35 | #endif
2024-09-17T16:54:51.6743080Z  36 | 
2024-09-17T16:54:51.6743320Z  37 |     let args = try args ?? parseCommandLineArguments(from: CommandLine.arguments)
2024-09-17T16:54:51.6743770Z     |                                                                        `- error: reference to static property 'arguments' is not concurrency-safe because it involves shared mutable state
2024-09-17T16:54:51.6743850Z  38 |     // Configure the test runner.
2024-09-17T16:54:51.6744040Z  39 |     var configuration = try configurationForEntryPoint(from: args)
2024-09-17T16:54:51.6744050Z 
2024-09-17T16:54:51.6744200Z Swift.CommandLine:4:23: note: static property declared here
2024-09-17T16:54:51.6744300Z 2 |     public static var argc: Int32 { get }
2024-09-17T16:54:51.6744560Z 3 |     public static var unsafeArgv: UnsafeMutablePointer<UnsafeMutablePointer<Int8>?> { get }
2024-09-17T16:54:51.6744670Z 4 |     public static var arguments: [String]
2024-09-17T16:54:51.6744830Z   |                       `- note: static property declared here
2024-09-17T16:54:51.6744890Z 5 | }
2024-09-17T16:54:51.6744980Z ninja: build stopped: subcommand failed.
2024-09-17T16:54:51.6744990Z 
```

**Review by p-linnane — APPROVED** [review]

**Comment by cho-m** [comment]
/home/linuxbrew/.linuxbrew/Cellar/swift/6.0.1/libexec/bin/swift-build: error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory

**Comment by cho-m** [comment]
Sequoia failed on `swift-testing-macros`, but if everything else passes then may want to merge and then follow up:
```
error: compile command failed due to signal 5 (use -v to see invocation)
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/homebrew/Cellar/swift/6.0.1/Swift-6.0.xctoolchain/usr/bin/swift-frontend -frontend -c /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/ConditionMacro.swift -primary-file /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/SourceLocationMacro.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/SuiteDeclarationMacro.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/Additions/DeclGroupSyntaxAdditions.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/Additions/EditorPlaceholderExprSyntaxAdditions.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/Additions/FunctionDeclSyntaxAdditions.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/Additions/MacroExpansionContextAdditions.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/Additions/TokenSyntaxAdditions.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/Additions/TriviaPieceAdditions.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/Additions/TypeSyntaxProtocolAdditions.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/Additions/VersionTupleSyntaxAdditions.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/Additions/WithAttributesSyntaxAdditions.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/Argument.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/AttributeDiscovery.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/AvailabilityGuards.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/CommentParsing.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/ConditionArgumentParsing.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/CRC32.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/DiagnosticMessage.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/DiagnosticMessage+Diagnosing.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/SourceCodeCapturing.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/Support/SourceLocationGeneration.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/TagMacro.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/TestDeclarationMacro.swift /tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/TestingMacrosMain.swift -emit-reference-dependencies-path CMakeFiles/TestingMacros.dir/SourceLocationMacro.swift.o.swiftdeps -target arm64-apple-macosx15 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk -I /tmp/swift-20241008-10264-ollfwb/build/swift-macosx-arm64/lib/swift/host -module-link-name TestingMacros -O -D SWT_TARGET_OS_APPLE -D TestingMacros_EXPORTS -define-availability "_mangledTypeNameAPI:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0" -define-availability "_backtraceAsyncAPI:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0" -define-availability "_clockAPI:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0" -define-availability "_regexAPI:macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0" -define-availability "_swiftVersionAPI:macOS 13.0, iOS 16.0, tvOS 16.0, watchOS 9.0" -define-availability "_distantFuture:macOS 99.0, iOS 99.0, watchOS 99.0, tvOS 99.0, visionOS 99.0" -require-explicit-sendable -enable-experimental-feature AccessLevelOnImport -enable-upcoming-feature ExistentialAny -enable-upcoming-feature InternalImportsByDefault -disable-implicit-string-processing-module-import -disable-implicit-backtracing-module-import -empty-abi-descriptor -resource-dir /opt/homebrew/Cellar/swift/6.0.1/Swift-6.0.xctoolchain/usr/lib/swift -module-name TestingMacros -plugin-path /opt/homebrew/Cellar/swift/6.0.1/Swift-6.0.xctoolchain/usr/lib/swift/host/plugins -plugin-path /opt/homebrew/Cellar/swift/6.0.1/Swift-6.0.xctoolchain/usr/local/lib/swift/host/plugins -target-sdk-version 15.0 -target-sdk-name macosx15.0 -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin/swift-plugin-server -enable-default-cmo -parse-as-library -num-threads 4 -o CMakeFiles/TestingMacros.dir/SourceLocationMacro.swift.o
1.	Swift version 6.0.1 (swift-6.0.1-RELEASE)
2.	Compiling with effective version 5.10
3.	While evaluating request IRGenRequest(IR Generation for file "/tmp/swift-20241008-10264-ollfwb/swift-testing/Sources/TestingMacros/SourceLocationMacro.swift")
4.	While emitting IR SIL function "@$s13TestingMacros19SourceLocationMacroV019CompilerSwiftSyntaxB00E0AadEP10formatModeAD06FormatJ0OvgZTW".
 for getter for formatMode (in module 'SwiftSyntaxMacros')
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000103c85f24 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000103c86308 SignalHandler(int) + 188
2  libsystem_platform.dylib 0x000000018758c184 _sigtramp + 56
3  swift-frontend           0x0000000100bd1130 (anonymous namespace)::IRGenSILFunction::visitSILBasicBlock(swift::SILBasicBlock*) + 34860
4  swift-frontend           0x0000000100bc7bac swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 7312
5  swift-frontend           0x0000000100ada020 swift::irgen::IRGenerator::emitLazyDefinitions() + 1292
6  swift-frontend           0x0000000100b8bdc4 swift::IRGenRequest::evaluate(swift::Evaluator&, swift::IRGenDescriptor) const + 2308
```

**Comment by Bo98** [comment]
Yeah 6.0.1 was supposed to fix Sequoia but didn't seem to. I'll probably follow up with 6.0.2.

**Review by cho-m — APPROVED** [review]

**Comment by Bo98** [comment]
Pretty convinced now that macOS 15 issue is an upstream problem. We'll see if a fix lands in 6.0.x or if I'll have to hunt around for 6.1 backports.

Linux build should be green now after applying https://github.com/swiftlang/swift-foundation/commit/a3c2f108592da51bb645dd50feaac7d88e61df31 from 6.0.2.

**Review by cho-m — APPROVED** [review]

**Pull request merged**
