### PR TITLE
Use download mirror compatible with macOS `curl` & update livecheck blocks for Xiph.org software

### PR DESCRIPTION
**Pull request by vladimyr**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This is just a batch update adding download mirrors and altering livecheck blocks in order to ensure:
1. they are compatible with macOS `curl` (ie. do not require TLSv1.3)
2. they all use the same URL pattern https://ftp.osuosl.org/pub/xiph/releases/{{product}}/?C=M&O=D where `?C=M&O=D` part ensures that the latest version gets listed first.

### CODE REVIEW

**Comment by nandahkrishna** [comment]
The consistency seems desirable and I briefly checked the `livecheck` output with `HOMEBREW_FORCE_BREWED_CURL=1`. However, the changes would break the `livecheck` blocks for `libshout` and `speex` when not using Homebrew `curl` (they currently work with macOS `curl` because the `ftp.osuosl.org` URLs do not require TLSv1.3 support).

**Comment by vladimyr** [comment]
> and I briefly checked the `livecheck` output with `HOMEBREW_FORCE_BREWED_CURL=1`.

Ah, I completely forgot about that one, thanks for reminding me! 👍 

> However, the changes would break the `livecheck` blocks for `libshout` and `speex` when not using Homebrew `curl` (they currently work with macOS `curl` because the `ftp.osuosl.org` URLs do not require TLSv1.3 support).

Which basically means I went in the completely wrong direction. Ok so let's redo this by converting everything to https://ftp.osuosl.org/pub/xiph/releases/ in order to ensure macOS `curl` could reach it.

**Comment by vladimyr** [comment]
@nandahkrishna Ok, I now altered all formulas to use ftp.osuosl.org/pub/xiph/releases as tarball download and livecheck URL. This should enable doing both `brew fetch -s` and `brew livecheck` when using macOS `curl`.

**Review by nandahkrishna — APPROVED** [review]
I've verified with macOS `curl` that I'm able to `brew fetch --build-from-source` all these formulae. The mirror URL is used because the original stable URL doesn't work with macOS `curl` (due to the lack of TLSv1.3 support). This is good to have, for those who need to use `brew install -s`.

`livecheck` now works (with macOS `curl`) for formulae which earlier didn't thanks to the `url` change and the addition of `livecheck` blocks for some formulae. The blocks are consistent too, which is a plus.

Overall, I'm in favour of merging this PR. Thanks very much, @vladimyr! 🍻

**Pull request closed without merging**
