### PR TITLE
gobject-introspection: do not require brew python

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Reverts #11538.

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @tschoonj @fxcoudert 

Closes https://github.com/Homebrew/homebrew-core/issues/11536.

**Comment by JCount** [comment]
Note, this still requires brewed python.

**Comment by JCount** [comment]
Note that this still depends upon brewed python.

**Comment by ilovezfs** [comment]
fixed.

**Comment by tschoonj** [comment]
Hmmm... is there already a fix to strip those universal arch build flags from the Python config output?

**Comment by ilovezfs** [comment]
Nope, but since this passes CI, I'm still not sure I've understood the problem.

**Comment by tdsmith** [comment]
AIUI the extra arch flags won't be a problem in Homebrew because superenv strips them but they can cause trouble if you're building things outside of Homebrew using Homebrew-installed stuff. Is that right?

**Comment by ilovezfs** [comment]
If the only reason for the dependency is things outside of Homebrew, I think we should remove it.

**Comment by tschoonj** [comment]
IIRC the problems that forced me to use the brewed python occurred when trying to port an existing to formula to the meson build system, not while building something outside of Homebrew.

**Comment by ilovezfs** [comment]
@tschoonj if you can recall which one that is, I'll take a look.

**Comment by tschoonj** [comment]
Try graphene

**Comment by ilovezfs** [comment]
@tschoonj thanks

**Comment by ilovezfs** [comment]
`graphene` builds fine with system python plus `meson` if we use `ENV.refurbish_args`. (The current `graphene` formula is already effectively doing that because it uses `make`, which causes brew to apply `ENV.refurbish_args` automatically, whereas using `meson` does not.)

**Comment by tschoonj** [comment]
Is there a fix now ensuring that `meson` based formulas use `ENV.refurbish_args`?

**Comment by ilovezfs** [comment]
Nope. We only do that for make. PRs welcome.

**Comment by tschoonj** [comment]
Any pointers on where to find the relevant code? I am finding a reference in `formula.rb` but that only appears to kick in for python commands...

**Comment by brion** [comment]
This causes g-ir-scanner to always fail when compiling anything using glib.h, as in https://gitlab.gnome.org/GNOME/librsvg/issues/212. I would tend to recommend restoring the use of a brew-installed python2.

**Pull request closed without merging**
