### PR TITLE
FIX: init db with C locale and UTF-8

### PR DESCRIPTION
**Pull request by SamSaffron**
Without this fix fulltext on the db behaves strange due to:

https://stackoverflow.com/a/24541592

### CODE REVIEW

**Comment by zbeekman** [comment]
Syntax errors and you clearly didn't try to run this locally first. Closing. Feel free to resubmit and follow the PR template.

**Comment by SamSaffron** [comment]
@zbeekman fair enough I had one extra  comma there at the end I will ask someone from my team to follow this up and run this on local. 

It generated regular support requests for us at Discourse.

**Review by zbeekman — DISMISSED** [review]

**Comment by SamSaffron** [comment]
@zbeekman  thank you! I applied the change.

**Comment by zbeekman** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
This might have more wide-ranging affects, including collation and case conversion operations on text data in that database. Maybe a review of that and some testing is in order before flipping the switch on this? Since we don't know the use cases of all Homebrew users here, it's probably worth considering all its ramifications.

**Comment by zbeekman** [comment]
@Homebrew/maintainers Thoughts on this?

**Comment by MikeMcQuaid** [comment]
I'd like to see a bunch more people request this before we change the default. A lot of people will assume the previous default here.

**Comment by claui** [comment]
@apjanke While your point is valid, this change isn’t ever going to touch an existing database, or is it?

@MikeMcQuaid This change is going to align collation behaviour with user expectations. If we want to stick with creating the database cluster on the user’s behalf, this PR would be the _Right Thing_ to do for 99.9% of users.

Everyone else can be reasonably expected to be well aware of their specific use case, and is free to re-create the database cluster themselves.

I’d love for at least one more maintainer to chime in though – just in case I’m missing something really obvious here!

**Comment by sjackman** [comment]
Here's an article on this topic in favour of using `initdb --locale=C`.
https://justatheory.com/2004/08/postgres-always-use-c-locale/

**Comment by claui** [comment]
Thanks @sjackman, good to know!

**Comment by MikeMcQuaid** [comment]
> This change is going to align collation behaviour with user expectations. If we want to stick with creating the database cluster on the user’s behalf, this PR would be the _Right Thing_ to do for 99.9% of users.

@claui Do you/have you used PostgreSQL for "real" projects? If so: I 100% defer to you here.

**Comment by SamSaffron** [comment]
We do manage about 2000 or so Discourse sites including this one https://discourse.brew.sh/ :smile_cat:  

We use Postgres and have been using it ever since we started the project, the way PG requires you init with C locale is a huge curve ball for contributors who get confused that they created a UTF-8 site yet for some reason full text does not work right. Debian / Ubuntu default to this Arch mentions this in the sample initdb command. 

I agree though 100% you got to be prudent here.

**Comment by MikeMcQuaid** [comment]
@SamSaffron lol! Works for me then!

**Review by MikeMcQuaid — APPROVED** [review]

**Review by claui — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @SamSaffron!

**Comment by SamSaffron** [comment]
Hi Mike, Thank you! I always enjoy using Homebrew on the Mac and thing you and the Homebrew team do a fantastic job. If any issues arise due to this patch please @mention me and I will do my best to help out.

**Comment by MikeMcQuaid** [comment]
Will do @SamSaffron! Thanks again for the PR and for (our) Discourse!

**Pull request merged**
