### PR TITLE
Leptonica 1.73

### PR DESCRIPTION
**Pull request by edporras**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Note: I bumped revisions of `jbig2enc` and `tesseract` as they both depend on `leptonica`. Not sure if this is required though.

### CODE REVIEW

**Comment by DomT4** [comment]
Unless the `leptonica` update is breaking in some manner, such as incompatible changes or `.dylib` versioning bumps, you should be fine without the `revision` bumps for the `depends_on` formulae.

**Comment by edporras** [comment]
Thank you for the clarification. Should I do a new pull request from a different branch with only the `leptonica` change?

**Comment by DomT4** [comment]
Feel free to just force push over this branch if you wish to. CI knows to check the PR again when changes are pushed.

**Comment by edporras** [comment]
Done. Thanks.

**Comment by DomT4** [comment]
Sigh. It turned out despite the upstream update only being a seemingly minor update from `72` to `73` the dependents did indeed need revision bumps. That's frustrating. My apologies. If you wouldn't mind putting them back with the commit format:

```
jbig2enc: revision for leptonica
```
And so on, that'd be appreciated.

**Comment by edporras** [comment]
Haha. No problem. Let me try that now.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/bd4a96bf1ab89948bd3e2a45c1cdffa5b38407f6, https://github.com/Homebrew/homebrew-core/commit/194609bbc988d384f4039da34c8973cc1a373ec3 & https://github.com/Homebrew/homebrew-core/commit/a11ac74e36f5d8fef8aca55de1850497662d4899. Thank you for your contributions to Homebrew @edporras; we appreciate it! :smiley_cat:

**Pull request closed without merging**
