### PR TITLE
mono 5.16.0.220

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by javian** [comment]
Failing with
```
22:19:24 ==> Verifying e628a601102e1ac431559f0f4f3faec98db071781ff23618a9e7ebac84814726--petstore.json checksum
22:19:24 ==> /usr/local/Cellar/autorest/0.17.3/bin/autorest -n test -i petstore.json
22:19:24 Cannot open assembly '/usr/local/Cellar/autorest/0.17.3/libexec/AutoRest.exe': No such file or directory.
22:19:24 Error: autorest: failed
22:19:24 An exception occurred within a child process:
22:19:24   Test::Unit::AssertionFailedError: <0> expected but was
22:19:24 <2>.
```
the autorest formula on Mojave

**Comment by gep13** [comment]
@igas @javian is there something that can be done to get this fixed?  Thanks

**Comment by igas** [comment]
@gep13 we need to rewrite `autorest` to npm version. Because current `autorest` does not compile with new `mono`.

**Comment by gep13** [comment]
@igas thank you for the information!

**Comment by igas** [comment]
:tada: It's 🍏 !

**Pull request closed without merging**
