### PR TITLE
cartridge-cli 2.7.0

### PR DESCRIPTION
**Pull request by dokshina**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Could you please also remove from the formula:
``` ruby
    # Remove this when upstream ships a go.sum
    system "go", "mod", "download"
```

This shouldn't be required anymore

**Comment by dokshina** [comment]
Yes, of course.

**Comment by bayandin** [comment]
Let's try to build it for Apple Silicon as well. As I can see, all the previous attempts fails were related to the lack of `go.mod`. Hope this time it'll be ok

**Comment by Bo98** [comment]
The `gopsutil` version used is too old to build on Apple Silicon for now. I think they added support in 2.20.9.

**Review by dawidd6 — APPROVED** [review]

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Thanks, @dokshina.

**Pull request closed without merging**
