### PR TITLE
docker 1.13.0

### PR DESCRIPTION
**Pull request by ushuz**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Comment by msabramo** [comment]
How does one, as a contributor, update the bottles for a formula? Or is that something that happens automatically on the backend?

**Comment by ushuz** [comment]
@msabramo Contributors don't need to update the bottles. Bottles are built and updated by Homebrew bot.

**Comment by ziru** [comment]
When will this PR get merged?

**Comment by nijikon** [comment]
Sorry for the delay.

**Pull request closed without merging**
