### PR TITLE
media-info 24.01

### PR DESCRIPTION
**Pull request by owine**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by bevanjkay — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
image

**Comment by p-linnane** [comment]
I've brought this attestation upload failure to @woodruffw's attention. He is working with GitHub to see what happened.

**Comment by woodruffw** [comment]
For tracking: I'm currently talking with both GitHub and the Sigstore team to further root-cause here.

**Comment by woodruffw** [comment]
GitHub and Sigstore have both concluded their investigations here. To summarize the fixes applied:

1. `generate-build-provenance` now signs each artifact serially, not in parallel. This wasn't the true underlying cause, but it aggravated the cause. No action is required in the Homebrew repos, since the change was made to `main` and has been propagated already.
2. Sigstore's public load balancer now sets a consistent `keepalive` with the underlying service. This was the true underlying cause. 

This was the only 502 observed on `homebrew-core`. However, after deploying fix (2) above Sigstore has stopped observing 502s from other clients as well, suggesting that the fix is correct.

In terms of changes on `homebrew-core`:

* @Bo98 pointed out that we can make these failures less burdensome by moving the attestation step ahead of the bottle upload step. This should be a straightforward change.
* Unless there's a way to re-upload or re-use the current bottles, I think this PR unfortunately requires a rebuild bump. That should then generate the attestations as expected.

**Comment by p-linnane** [comment]
One solution would be to delete the uploaded bottles and rerun the publish job. I'm not sure how that would work with the existing attestations that were uploaded though.

**Comment by woodruffw** [comment]
> One solution would be to delete the uploaded bottles and rerun the publish job. I'm not sure how that would work with the existing attestations that were uploaded though.

That _should_ be fine -- I believe multiple attestations can be created for the same input file.

**Pull request merged**
