### PR TITLE
libnghttp2 nghttp2 1.55.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by bayandin** [comment]
A revision bump for `julia` is required

**Comment by chenrui333** [comment]
```
  ==> Testing julia
  ==> /opt/homebrew/Cellar/julia/1.9.2_1/bin/julia --startup-file=no --history-file=no --project=/private/tmp/julia-test-20230713-52239-1p6bp28 --procs 4 --print '2 + 2'
  ┌ Error: Error during initialization of module CHOLMOD
  │   exception =
  │    could not load library "libcholmod"
  │    dlopen(libcholmod.dylib, 0x0001): Symbol not found: _SuiteSparse_config
  │      Referenced from: <1DC9B85F-B249-3AD2-B9EF-0F2E3ED0432D> /opt/homebrew/Cellar/julia/1.9.2_1/lib/julia/libcholmod.3.0.14.dylib
  │      Expected in:     <63D05396-DC33-3876-B81B-342B52DFE3F7> /opt/homebrew/Cellar/suite-sparse/7.0.1/lib/libsuitesparseconfig.7.0.1.dylib
  │    Stacktrace:
  │     [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
  │       @ Base.Libc.Libdl ./libdl.jl:117
  │     [2] dlopen (repeats 2 times)
  │       @ ./libdl.jl:116 [inlined]
  │     [3] __init__()
  │       @ SparseArrays.CHOLMOD /opt/homebrew/Cellar/julia/1.9.2_1/share/julia/stdlib/v1.9/SparseArrays/src/solvers/cholmod.jl:173
```

**Comment by p-linnane** [comment]
`julia` has been having test failures across PR's for a bit.

cc @fxcoudert

**Comment by carlocab** [comment]
Revision bump won't help here.

**Review by carlocab — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
