### PR TITLE
elektra 0.9.13

### PR DESCRIPTION
**Pull request by mpranj**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  Plugin did not pass all checks:
  See description below:
  The symbol "commit" has the same value as another symbol!
```

**Comment by mpranj** [comment]
Thanks for reporting the error.

We'll have to look into it, sorry for the inconvenience.

**Comment by chenrui333** [comment]
#125863

**Comment by chenrui333** [comment]
np, thanks @mpranj for fixing it!

**Pull request closed without merging**
