### PR TITLE
pybind11 2.10.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by henryiii** [comment]
Can we go ahead and add 3.11?

**Comment by henryiii** [comment]
Just add:

```ruby
depends_on "python@3.11" => [:build, :test]
```

I've been trying but I can't audit formulas since I've updated to macOS 13 and Apple hasn't released the matching Xcode brew is requiring.

**Comment by henryiii** [comment]
(I can actually do it, but want an okay from @chenrui333 first)

**Comment by chenrui333** [comment]
> (I can actually do it here, but want an okay from @chenrui333 first)

good point

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
