### PR TITLE
semgrep 0.116.0

### PR DESCRIPTION
**Pull request by brendongo**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Review by iMichka — DISMISSED** [review]
Can you update the resources? You can use `brew update-python-resources` to do so.

**Comment by cho-m** [comment]
It looks https://github.com/Homebrew/homebrew-core/commit/e24d779ff96b66d8185a12de95d6bb6e36910f1a forgot to add `package_name`, which is needed since `semgrep` uses GitHub URL.

To restore auto-updated Python resources, mapping is needed:
```diff
--- a/pypi_formula_mappings.json
+++ b/pypi_formula_mappings.json
@@ -449,6 +449,7 @@
     "exclude_packages": ["six"]
   },
   "semgrep": {
+    "package_name": "semgrep",
     "exclude_packages": ["jsonschema", "attrs", "pyrsistent", "typing-extensions"]
   },
   "sgr": {
```

**Comment by bmahe** [comment]
I also run the update-python-resources command. However it did not seem to find anything to change.

```bash
bruno@brunos-MacBook-Pro homebrew-core % brew update-python-resources --package-name semgrep  semgrep
==> Retrieving PyPI dependencies for "semgrep"...
==> Getting PyPI info for "attrs==21.4.0"
==> Getting PyPI info for "boltons==21.0.0"
==> Getting PyPI info for "bracex==2.3.post1"
==> Getting PyPI info for "certifi==2022.9.24"
==> Getting PyPI info for "charset-normalizer==2.1.1"
==> Getting PyPI info for "click==8.1.3"
==> Getting PyPI info for "click-option-group==0.5.3"
==> Getting PyPI info for "colorama==0.4.5"
==> Getting PyPI info for "defusedxml==0.7.1"
==> Getting PyPI info for "face==20.1.1"
==> Getting PyPI info for "glom==22.1.0"
==> Getting PyPI info for "idna==3.4"
==> Getting PyPI info for "jsonschema==4.16.0"
==> Getting PyPI info for "packaging==21.3"
==> Getting PyPI info for "peewee==3.15.3"
==> Getting PyPI info for "pyparsing==3.0.9"
==> Getting PyPI info for "pyrsistent==0.18.1"
==> Getting PyPI info for "python-lsp-jsonrpc==1.0.0"
==> Getting PyPI info for "requests==2.28.1"
==> Getting PyPI info for "ruamel-yaml==0.17.21"
==> Getting PyPI info for "ruamel-yaml-clib==0.2.6"
==> Excluding "semgrep==0.116.0"
==> Getting PyPI info for "tomli==2.0.1"
==> Getting PyPI info for "tqdm==4.64.1"
==> Getting PyPI info for "typing-extensions==4.4.0"
==> Getting PyPI info for "ujson==5.5.0"
==> Getting PyPI info for "urllib3==1.26.12"
==> Getting PyPI info for "wcmatch==8.4.1"
==> Updating resource blocks
```

```bash
bruno@brunos-MacBook-Pro homebrew-core % git status                                                  
On branch bump-semgrep-0.116.0
Your branch is up to date with 'origin/bump-semgrep-0.116.0'.

nothing to commit, working tree clean
```

**Review by carlocab — APPROVED** [review]
Thanks!

**Comment by cho-m** [comment]
That doesn't look right. For example, the current formula has `certifi-2022.9.14` but the output of command shows `certifi==2022.9.24`.

I tried locally and the diff is:
```diff
diff --git a/Formula/semgrep.rb b/Formula/semgrep.rb
index 89052d1b0b7..034a05722d2 100644
--- a/Formula/semgrep.rb
+++ b/Formula/semgrep.rb
@@ -51,8 +51,8 @@ class Semgrep < Formula
   end
 
   resource "certifi" do
-    url "https://files.pythonhosted.org/packages/ca/48/88ec470f8b68319b6782ca3a0570789886ad5ca24c1af2f3771699135baa/certifi-2022.9.14.tar.gz"
-    sha256 "36973885b9542e6bd01dea287b2b4b3b21236307c56324fcc3f1160f2d655ed5"
+    url "https://files.pythonhosted.org/packages/cb/a4/7de7cd59e429bd0ee6521ba58a75adaec136d32f91a761b28a11d8088d44/certifi-2022.9.24.tar.gz"
+    sha256 "0d9c601124e5a6ba9712dbc60d9c53c21e34f5f641fe83002317394311bdce14"
   end
 
   resource "charset-normalizer" do
@@ -101,8 +101,8 @@ class Semgrep < Formula
   end
 
   resource "peewee" do
-    url "https://files.pythonhosted.org/packages/00/e2/636151cde2cb3fe479a06c3940352c69b51b858b0a56a1b08729244207a9/peewee-3.15.2.tar.gz"
-    sha256 "94d8eb7fc2b8d97d6216382bf5961239645dc9e2473b0e732eb6c79c920c4768"
+    url "https://files.pythonhosted.org/packages/b7/4a/ba48c5a99a86cad44f89766dfa9937efe18f8d61d8fb55d0cd9073d2b40c/peewee-3.15.3.tar.gz"
+    sha256 "cc934286d0c0842203abe66a3c6583d1463371e633b03d6da054d0f74e70706f"
   end
 
   resource "pyparsing" do
@@ -151,8 +151,8 @@ class Semgrep < Formula
   end
 
   resource "wcmatch" do
-    url "https://files.pythonhosted.org/packages/95/b3/597b79292584de5b790146871e50cf3cb3bf37cf845232a20123fc784ef2/wcmatch-8.4.tar.gz"
-    sha256 "ba4fc5558f8946bf1ffc7034b05b814d825d694112499c86035e0e4d398b6a67"
+    url "https://files.pythonhosted.org/packages/b7/94/5dd083fc972655f6689587c3af705aabc8b8e781bacdf22d6d2282fe6142/wcmatch-8.4.1.tar.gz"
+    sha256 "b1f042a899ea4c458b7321da1b5e3331e3e0ec781583434de1301946ceadb943"
   end
 
   def install
```

**Comment by bmahe** [comment]
@cho-m can you show me which command you used?
It's my first time dealing with brew, so I am probably doing something wrong somewhere.

Updating the command I run from `brew update-python-resources --package-name semgrep  semgrep` to `brew update-python-resources --verbose -d --package-name semgrep ./Formula/semgrep.rb`, I do get a diff, but it also includes more changes than what you got:

```diff
diff --git a/Formula/semgrep.rb b/Formula/semgrep.rb
index 89052d1b0b7..fe37ab2c208 100644
--- a/Formula/semgrep.rb
+++ b/Formula/semgrep.rb
@@ -40,6 +40,11 @@ class Semgrep < Formula
 
   fails_with gcc: "5"
 
+  resource "attrs" do
+    url "https://files.pythonhosted.org/packages/d7/77/ebb15fc26d0f815839ecd897b919ed6d85c050feeb83e100e020df9153d2/attrs-21.4.0.tar.gz"
+    sha256 "626ba8234211db98e869df76230a137c4c40a12d72445c45d5f5b716f076e2fd"
+  end
+
   resource "boltons" do
     url "https://files.pythonhosted.org/packages/ad/1f/6c0608d86e0fc77c982a2923ece80eef85f091f2332fc13cbce41d70d502/boltons-21.0.0.tar.gz"
     sha256 "65e70a79a731a7fe6e98592ecfb5ccf2115873d01dbc576079874629e5c90f13"
@@ -51,8 +56,8 @@ class Semgrep < Formula
   end
 
   resource "certifi" do
-    url "https://files.pythonhosted.org/packages/ca/48/88ec470f8b68319b6782ca3a0570789886ad5ca24c1af2f3771699135baa/certifi-2022.9.14.tar.gz"
-    sha256 "36973885b9542e6bd01dea287b2b4b3b21236307c56324fcc3f1160f2d655ed5"
+    url "https://files.pythonhosted.org/packages/cb/a4/7de7cd59e429bd0ee6521ba58a75adaec136d32f91a761b28a11d8088d44/certifi-2022.9.24.tar.gz"
+    sha256 "0d9c601124e5a6ba9712dbc60d9c53c21e34f5f641fe83002317394311bdce14"
   end
 
   resource "charset-normalizer" do
@@ -95,14 +100,19 @@ class Semgrep < Formula
     sha256 "814f528e8dead7d329833b91c5faa87d60bf71824cd12a7530b5526063d02cb4"
   end
 
+  resource "jsonschema" do
+    url "https://files.pythonhosted.org/packages/cf/54/8923ba38b5145f2359d57e5516715392491d674c83f446cd4cd133eeb4d6/jsonschema-4.16.0.tar.gz"
+    sha256 "165059f076eff6971bae5b742fc029a7b4ef3f9bcf04c14e4776a7605de14b23"
+  end
+
   resource "packaging" do
     url "https://files.pythonhosted.org/packages/df/9e/d1a7217f69310c1db8fdf8ab396229f55a699ce34a203691794c5d1cad0c/packaging-21.3.tar.gz"
     sha256 "dd47c42927d89ab911e606518907cc2d3a1f38bbd026385970643f9c5b8ecfeb"
   end
 
   resource "peewee" do
-    url "https://files.pythonhosted.org/packages/00/e2/636151cde2cb3fe479a06c3940352c69b51b858b0a56a1b08729244207a9/peewee-3.15.2.tar.gz"
-    sha256 "94d8eb7fc2b8d97d6216382bf5961239645dc9e2473b0e732eb6c79c920c4768"
+    url "https://files.pythonhosted.org/packages/b7/4a/ba48c5a99a86cad44f89766dfa9937efe18f8d61d8fb55d0cd9073d2b40c/peewee-3.15.3.tar.gz"
+    sha256 "cc934286d0c0842203abe66a3c6583d1463371e633b03d6da054d0f74e70706f"
   end
 
   resource "pyparsing" do
@@ -110,6 +120,11 @@ class Semgrep < Formula
     sha256 "2b020ecf7d21b687f219b71ecad3631f644a47f01403fa1d1036b0c6416d70fb"
   end
 
+  resource "pyrsistent" do
+    url "https://files.pythonhosted.org/packages/42/ac/455fdc7294acc4d4154b904e80d964cc9aae75b087bbf486be04df9f2abd/pyrsistent-0.18.1.tar.gz"
+    sha256 "d4d61f8b993a7255ba714df3aca52700f8125289f84f704cf80916517c46eb96"
+  end
+
   resource "python-lsp-jsonrpc" do
     url "https://files.pythonhosted.org/packages/99/45/1c2a272950679af529f7360af6ee567ef266f282e451be926329e8d50d84/python-lsp-jsonrpc-1.0.0.tar.gz"
     sha256 "7bec170733db628d3506ea3a5288ff76aa33c70215ed223abdb0d95e957660bd"
@@ -140,6 +155,11 @@ class Semgrep < Formula
     sha256 "5f4f682a004951c1b450bc753c710e9280c5746ce6ffedee253ddbcbf54cf1e4"
   end
 
+  resource "typing-extensions" do
+    url "https://files.pythonhosted.org/packages/e3/a7/8f4e456ef0adac43f452efc2d0e4b242ab831297f1bac60ac815d37eb9cf/typing_extensions-4.4.0.tar.gz"
+    sha256 "1511434bb92bf8dd198c12b1cc812e800d4181cfcb867674e0f8279cc93087aa"
+  end
+
   resource "ujson" do
     url "https://files.pythonhosted.org/packages/6e/4a/03ddad85a10dd52e209993a14afa0cb0dc5c348e4647329f1c53856ad9e6/ujson-5.5.0.tar.gz"
     sha256 "b25077a971c7da47bd6846a912a747f6963776d90720c88603b1b55d81790780"
@@ -151,8 +171,8 @@ class Semgrep < Formula
   end
 
   resource "wcmatch" do
-    url "https://files.pythonhosted.org/packages/95/b3/597b79292584de5b790146871e50cf3cb3bf37cf845232a20123fc784ef2/wcmatch-8.4.tar.gz"
-    sha256 "ba4fc5558f8946bf1ffc7034b05b814d825d694112499c86035e0e4d398b6a67"
+    url "https://files.pythonhosted.org/packages/b7/94/5dd083fc972655f6689587c3af705aabc8b8e781bacdf22d6d2282fe6142/wcmatch-8.4.1.tar.gz"
+    sha256 "b1f042a899ea4c458b7321da1b5e3331e3e0ec781583434de1301946ceadb943"
   end
 

```

**Comment by carlocab** [comment]
Just do
```
brew update-python-resources semgrep
```
The extra flags (in particular, `--package-name`) ignores the content of `pypi_formula_mappings.json`, which is why you get extra updates (which we don't need).

Cherry-picked this onto #112605 with the needed changes. Thanks for your work here!

**Comment by bmahe** [comment]
Got it!
Thank you so much!

**Pull request closed without merging**
