### PR TITLE
gromacs 2021.2

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
-- Could not convert sample image, ImageMagick convert can not be used. A possible way to fix it can be found here: https://alexvanderbist.com/2018/fixing-imagick-error-unauthorized
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE pygments) (Required is at least version "1.6.1")
CMake Error at api/nblib/CMakeLists.txt:79 (add_dependencies):
  Cannot add target-level dependencies to non-existent target "tests".
```

**Comment by fxcoudert** [comment]
We had the same issue with the current version, while testing gcc 11 at https://github.com/Homebrew/homebrew-core/pull/74843

I've opened a thread on upstream support: https://gromacs.bioexcel.eu/t/compilation-failure-for-gromacs-2021-1-and-2021-2-with-cmake-3-20-2/2129

**Comment by cho-m** [comment]
I think ImageMagick and Sphinx are for building documentation. Shouldn't be related to actual failure.

The problem is described in following lines:
```make
CMake Error at api/nblib/CMakeLists.txt:79 (add_dependencies):
  Cannot add target-level dependencies to non-existent target "tests".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.
```

Trying some variation of `cmake` arguments, I see issue happens using `-DBUILD_TESTING=OFF`.

This may end up not creating the `tests` target, which then breaks the `add_dependencies` later on.

**Comment by cho-m** [comment]
Possible patch to move any usage of `tests` into `BUILD_TESTING` section.
```diff
diff --git a/api/nblib/CMakeLists.txt b/api/nblib/CMakeLists.txt
index a2ce06596e..0882de73eb 100644
--- a/api/nblib/CMakeLists.txt
+++ b/api/nblib/CMakeLists.txt
@@ -69,21 +69,21 @@ if (BUILD_TESTING)
         set(UNITTEST_TARGET_OPTIONS EXCLUDE_FROM_ALL)
     endif()
     include(${TESTUTILS_DIR}/TestMacros.cmake)
-endif()
 
-add_custom_target(nblib-tests
-        COMMENT "Target to build all nblib tests including samples"
-        )
-# Ensure that "make tests" builds all nblib tests so the top-level
-# "make check" will work.
-add_dependencies(tests nblib-tests)
-
-# this allows all nblib tests to be run with "make check-nblib"
-add_custom_target(check-nblib
-        COMMAND ${CMAKE_CTEST_COMMAND} --output-on-failure -R NbLib
-        COMMENT "Running nblib tests"
-        USES_TERMINAL VERBATIM)
-add_dependencies(check-nblib nblib-tests)
+    add_custom_target(nblib-tests
+            COMMENT "Target to build all nblib tests including samples"
+            )
+    # Ensure that "make tests" builds all nblib tests so the top-level
+    # "make check" will work.
+    add_dependencies(tests nblib-tests)
+
+    # this allows all nblib tests to be run with "make check-nblib"
+    add_custom_target(check-nblib
+            COMMAND ${CMAKE_CTEST_COMMAND} --output-on-failure -R NbLib
+            COMMENT "Running nblib tests"
+            USES_TERMINAL VERBATIM)
+    add_dependencies(check-nblib nblib-tests)
+endif()
 
 set(NBLIB_MAJOR 0)
 set(NBLIB_MINOR 1)
```

---

Without patch, build fails for me on macOS 11.3
With patch, build works:
```console
❯ brew install --build-from-source gromacs
==> Installing gromacs
==> Patching
==> cmake .. -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11
==> make install
==> Caveats
GMXRC and other scripts installed to:
  /opt/homebrew/share/gromacs

zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/homebrew/Cellar/gromacs/2021.2: 614 files, 48MB, built in 1 minute 50 seconds
```

**Comment by carlocab** [comment]
@cho-m Maybe this will work too:
```diff
diff --git a/Formula/gromacs.rb b/Formula/gromacs.rb
index bee430a62ac..08d1e46bdeb 100644
--- a/Formula/gromacs.rb
+++ b/Formula/gromacs.rb
@@ -35,7 +35,7 @@ class Gromacs < Formula
                                                              "/usr/bin/ld"
 
     gcc_major_ver = Formula["gcc"].any_installed_version.major
-    args = std_cmake_args + %W[
+    args = std_cmake_args.reject { |s| s["BUILD_TESTING"] } + %W[
       -DCMAKE_C_COMPILER=gcc-#{gcc_major_ver}
       -DCMAKE_CXX_COMPILER=g++-#{gcc_major_ver}
     ]
```
Also looks to me like this formula is evading the shims by setting `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER`. I'd have thought that not specifying an absolute path there would still respect the shims, but given the log that appears to not be the case:
```
-- Check for working C compiler: /opt/homebrew/bin/gcc-10 - skipped
```
https://github.com/Homebrew/homebrew-core/pull/76819/checks?check_run_id=2538701533#step:7:60

**Comment by fxcoudert** [comment]
Upstream patch: https://gitlab.com/gromacs/gromacs/-/merge_requests/1494

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
