### PR TITLE
libswiften: needed to rebuild bottles with updated dependencies

### PR DESCRIPTION
**Pull request by vitalyster**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Is there a test that could be made that would fail if any of the dependencies were missing? To make sure the formula doesn't pass the test on the next boost update.

**Comment by vitalyster** [comment]
Please point me to some example formula with c++ test and I will try to adapt

**Comment by vitalyster** [comment]
@SMillerDev please review

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @vitalyster

**Pull request closed without merging**
