### PR TITLE
remind 03.03.08

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by branchvincent** [comment]
```
==> brew audit remind --online --git --skip-style
==> FAILED
remind:
  * HEAD: The URL https://dianne.skoll.ca/projects/remind/git/Remind.git is not a valid git URL
```

**Comment by chenrui333** [comment]
interesting, 😅

**Comment by branchvincent** [comment]
seems like it was moved to https://git.skoll.ca/Skollsoft-Public/Remind

**Comment by chenrui333** [comment]
```
remind:
  * HEAD: The source URL https://git.skoll.ca/Skollsoft-Public/Remind is not reachable
```

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
