### PR TITLE
llvm 5.0.0

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks @alex! Shipped :)

**Comment by alex** [comment]
Thanks for helping with the cleanup!

**Comment by ilovezfs** [comment]
@alex You're welcome!

**Comment by ilovezfs** [comment]
- [ ] [crystal-icr: revision for crystal-lang](https://github.com/Homebrew/homebrew-core/pull/17817)
- [ ] [creduce: depend on llvm@4](https://github.com/Homebrew/homebrew-core/pull/17818)
- [ ] [ldc: depend on llvm@4](https://github.com/Homebrew/homebrew-core/pull/17819)

**Pull request closed without merging**
