### PR TITLE
bandwhich 0.7.0 (new formula)

### PR DESCRIPTION
**Pull request by smorimoto**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by imbsky** [comment]
The current test is just to print out the version, but I think that's enough because it's a tool like MTR that's hard to test. If another test is required, I will add the proposed test.

**Comment by SMillerDev** [comment]
Please keep the description to just the tool usage and do improve the test.

**Comment by kontrafiktion** [comment]
Perhap swait until https://github.com/imsnif/bandwhich/issues/51 is solved?

**Comment by imbsky** [comment]
Yes, In the meantime, we will improve the description and test.

**Comment by imbsky** [comment]
bandwhich addressed an upstream bug and bumped to 0.7.0. So I updated this PR.
I understand, but MTR's fomula just prints the version. I think that's probably enough for this tool. or do you have any ideas?

**Comment by imbsky** [comment]
The software itself should be tested upstream, and the data output from this tool varies with the environment, making it difficult to test.

**Comment by SMillerDev** [comment]
While the data might differ between environments I'd imagine that there are some things standard in the output. If that's not the case, maybe you can make it fail reliably. Version checks just aren't enough to check if the install is correct and successful.

**Comment by imbsky** [comment]
I replaced with a new test that fail reliably. What do you think?

**Comment by SMillerDev** [comment]
I think you forgot to compare the output to something.

**Comment by imbsky** [comment]
I made some changes. There should be no problem with this. (I hope)

**Comment by SMillerDev** [comment]
Looks good to me, just waiting for CI. Thanks @imbsky! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by imbsky** [comment]
I'm always surprised by the polite reviews of the brew team. Thank you, too!

**Comment by imbsky** [comment]
Yay! The test passed!

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @imbsky!!

**Comment by imbsky** [comment]
👍

**Pull request closed without merging**
