### PR TITLE
wget 1.21

### PR DESCRIPTION
**Pull request by J-M0**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
utime.c:279:38: error: use of undeclared identifier 'errno'
      if (stat (name, &buf) == -1 && errno != EOVERFLOW)
                                     ^
utime.c:279:47: error: use of undeclared identifier 'EOVERFLOW'
      if (stat (name, &buf) == -1 && errno != EOVERFLOW)
                                              ^
2 errors generated.
make[3]: *** [utime.o] Error 1
```

**Comment by fxcoudert** [comment]
I've reported the issue by email to the wget list, it will appear at: https://lists.gnu.org/archive/html/bug-wget/2021-01/threads.html

There is a patch for gnulib (`lib` subdirectory in wget) at https://git.savannah.gnu.org/cgit/gnulib.git/commit/?id=6a76832db224ac5671599ce332717f985a2addc7

**Comment by darnir** [comment]
Thanks for the bug report. I've fixed the issue on the master branch. A new release tarball will be made in a week. Until then you could patch the sources manually for fixing the build

**Comment by fxcoudert** [comment]
@darnir thanks, I think we'll just wait for the point release

**Comment by chenrui333** [comment]
Thanks @darnir, adding patch into this PR (passed the build in my local).

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
