### PR TITLE
cling: make keg_only

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

https://github.com/Homebrew/homebrew-core/pull/18124#issuecomment-348055170

### CODE REVIEW

**Comment by ilovezfs** [comment]
Probably not the right solution because the keg only instructions still discuss how to make it first in your PATH and force linking is still possible too.  If the conflicting files are required at run time then maybe we should install them in libexec and use wrapper scripts if the paths cannot be specified in configure. so believe @GauthamGoli said he will look into this. Hence, closing.

**Comment by DomT4** [comment]
I'm happy with any solution, honestly. Just didn't want to leave it too long as, from experience, with the amount Homebrew turns over on a daily basis, if you say you'll do something & then don't fairly soon it gets drowned.

**Comment by DomT4** [comment]
It's surprising we don't audit check new formulae against `/usr/bin` to some extent 🙈.

**Comment by ilovezfs** [comment]
I'm pretty :-1: on any new audits that apply only to new formulae as they just create confusion.

**Comment by DomT4** [comment]
Yeah, wasn't something I was rushing to implement, just a note of surprise that it wasn't a thing already.

**Comment by ilovezfs** [comment]
>I'm happy with any solution, honestly. Just didn't want to leave it too long as, from experience, with the amount Homebrew turns over on a daily basis, if you say you'll do something & then don't fairly soon it gets drowned.

In terms of process, if a maintainer says they'll do something, please ping them again rather than doing it for them.

**Comment by DomT4** [comment]
FYI, there's no public indication that he is a maintainer. He isn't listed in the README on `brew`, his label here is `Contributor` and he isn't listed on his profile as a member of the Homebrew organisation.

**Comment by ilovezfs** [comment]
Ah, OK. Thanks for the heads up. Not sure what's up with that.

**Comment by DomT4** [comment]
No worries. I wasn't intentionally stepping on toes. As you've noticed I've very much dipped in & out of Homebrew since leaving, so unless something is prominently displayed I'm not always prone to noticing and/or remembering it, for better or worse 😰.

**Comment by ilovezfs** [comment]
>Yeah, wasn't something I was rushing to implement, just a note of surprise that it wasn't a thing already.

Maybe a white list so it's not new-formula-only?

**Comment by DomT4** [comment]
Whitelists in Rubocop are proving to be something of a grim education for me 😓. Are there many known cases of formulae that shadow the system & aren't `keg_only`? The most obvious I can think of is `vim`.

**Comment by ilovezfs** [comment]
nano, emacs, ruby, maybe others

**Comment by DomT4** [comment]
Ah, of course, forgot about `ruby` somehow _(probably because I switched over to `rbenv` a while ago)_. Can add `python` to that list as well then I guess. Alright, I guess I'll invest a little more time in working out Rubocop whitelists since I need to do so anyway to finish off https://github.com/Homebrew/brew/pull/3401.

**Comment by ilovezfs** [comment]
I think there's some kind of whitelisting for the patch urls?

**Comment by ilovezfs** [comment]
also I think wine with respect to the universal checks

**Comment by saagarjha** [comment]
Personally, I feel like `cling` is different than other formulae such as `vim`, `nano`, `ruby`, etc. since people installing these already have a copy of them on their system already–thus, it's pretty obvious that they're probably trying to update them. `cling` overriding `clang` is non-obvious (at least, it was to me; it looks like it should be a self-contained binary) and it's not upgrading anything, so I don't think it should be lumped in and get this treatment.

**Comment by ilovezfs** [comment]
@saagarjha I suggest you re-read what I said https://github.com/Homebrew/homebrew-core/pull/21178#issuecomment-348062061

**Comment by ilovezfs** [comment]
@DomT4 @saagarjha this is now fixed via https://github.com/Homebrew/homebrew-core/pull/21501.

**Pull request closed without merging**
