### PR TITLE
git-sizer 1.0.0 (new formula)

### PR DESCRIPTION
**Pull request by nrlquaker**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
We're going to decline for now:

```
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
  * https://github.com/github/git-sizer/releases/download/v1.0.0/git-sizer-1.0.0-darwin-amd64.zip looks like a binary package, not a source archive. Official taps are source-only.
```

**Comment by yefim** [comment]
@fxcoudert it has over 100 stars now. Can we get this re-opened?

**Comment by hansott** [comment]
This would be cool.

**Comment by nrlquaker** [comment]
It has more than 300 stars now.

**Comment by fxcoudert** [comment]
Congrats on the 300 stars in 20 hours :)

Yes, the second point still needs to be addressed: homebrew core formulas needs to build from source.

**Comment by nrlquaker** [comment]
Updated formula to build from source. Should I open new PR or this can be reopened?

**Comment by Maxooo** [comment]
And nearly 800 stars now ! Good job guys ! Now, it deserves its place in the brew packages repository

**Comment by ilovezfs** [comment]
@Maxooo fyi it was already merged.

**Comment by Maxooo** [comment]
Thank you for the information @ilovezfs

**Pull request closed without merging**
