### PR TITLE
logtalk 3.13.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by pmoura** [comment]
@ilovezfs Thanks for updating the Logtalk formula.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@pmoura you're welcome!

**Pull request closed without merging**
