### PR TITLE
ice 3.7.5

### PR DESCRIPTION
**Pull request by externl**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> brew audit ice --online --git --skip-style
==> FAILED
ice:
  * A top-level "man" directory was found
    Homebrew requires that man pages live under share.
    This can often be fixed by passing "--mandir=#{man}" to configure.
Error: 1 problem in 1 formula detected
```

**Comment by externl** [comment]
I'll look into fixing this error. 

The `--online --git --skip-style` flags should probably be mentioned in the PR checklist :)

**Comment by carlocab** [comment]
>I'll look into fixing this error.

Thanks. Let me know if you have trouble with it.

>The` --online --git --skip-style` flags should probably be mentioned in the PR checklist :)

You can always open a PR. This is the relevant file, I think:

https://github.com/Homebrew/homebrew-core/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by externl** [comment]
The man dir seems to be in the right location
```
❯ find /usr/local/Cellar -name man | grep -A 5 -B 5 ice
/usr/local/Cellar/perl/5.32.1/share/man
/usr/local/Cellar/wimlib/1.13.3_1/share/man
/usr/local/Cellar/readline/8.1/share/man
/usr/local/Cellar/graphicsmagick/1.3.36/share/man
/usr/local/Cellar/hunspell/1.7.0_2/share/man
/usr/local/Cellar/ice/3.7.5/share/man
/usr/local/Cellar/lz4/1.9.3/share/man
/usr/local/Cellar/awscli/2.1.21/libexec/man
/usr/local/Cellar/libarchive/3.5.1_1/share/man
/usr/local/Cellar/webp/1.1.0/share/man
/usr/local/Cellar/sqlite/3.34.0/share/man
```

Am I missing something?

**Comment by carlocab** [comment]
Interesting. What does
```
ls -la $(brew --cellar ice)/3.7.5
```
show?

**Comment by externl** [comment]
> Interesting. What does
> 
> ```
> ls -la $(brew --cellar ice)/3.7.5
> ```
> 
> show?

❯ ls -la (brew --cellar ice)/3.7.5
total 56
drwxr-xr-x  12 joe  admin    384 Jan 26 14:31 ./
drwxr-xr-x   3 joe  admin     96 Jan 26 14:07 ../
drwxr-xr-x   3 joe  admin     96 Jan 22 09:52 .brew/
-rw-r--r--   1 joe  admin    857 Jan 26 14:31 INSTALL_RECEIPT.json
-rw-r--r--   1 joe  admin  18093 Jan 22 09:52 LICENSE
-rw-r--r--   1 joe  admin   3916 Jan 22 09:52 README.md
drwxr-xr-x  24 joe  admin    768 Jan 22 09:52 bin/
drwxr-xr-x  12 joe  admin    384 Jan 22 09:52 include/
drwxr-xr-x  50 joe  admin   1600 Jan 22 09:52 lib/
drwxr-xr-x   3 joe  admin     96 Jan 22 09:52 libexec/
drwxr-xr-x   5 joe  admin    160 Jan 22 09:52 sdk/
drwxr-xr-x   4 joe  admin    128 Jan 22 09:52 share/

**Comment by carlocab** [comment]
Weird. Let's wait for CI to finish. That will let us take a closer look at the bottles to see what went wrong.

**Comment by carlocab** [comment]
The 10.14 runner succeeded, so it seems like the misplaced manpages only happen on ARM. Very weird.

**Comment by externl** [comment]
> The 10.14 runner succeeded, so it seems like the misplaced manpages only happen on ARM. Very weird.

Ok, I know what the issue is. It's because brew is installing outside of `/usr/local` on ARM

**Comment by carlocab** [comment]
Nice! So I guess we need need to specify an argument like `"installmandir=#{man}"` or something, to make sure it doesn't misplace the manpages on ARM.

**Comment by externl** [comment]
> Nice! So I guess we need need to specify an argument like `"install_mandir=#{man}"` or something, to make sure it doesn't misplace the manpages on ARM.

I just added `USR_DIR_INSTALL=yes`, which tells make to install it to the correct spot.

**Review by carlocab — APPROVED** [review]
Thanks, @externl!

**Pull request closed without merging**
