### PR TITLE
erg 0.6.16 (new formula)

### PR DESCRIPTION
**Pull request by henryhchchc**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
  ==> /home/linuxbrew/.linuxbrew/Cellar/erg/0.6.14/bin/erg /tmp/erg-test-20230621-16889-1uoy50l/test.er
  Traceback (most recent call last):
    File "/tmp/erg-test-20230621-16889-1uoy50l/test.er", line -1, in <module>
  ModuleNotFoundError: No module named '_erg_std_prelude'
```

**Comment by henryhchchc** [comment]
> ```
>   ==> /home/linuxbrew/.linuxbrew/Cellar/erg/0.6.14/bin/erg /tmp/erg-test-20230621-16889-1uoy50l/test.er
>   Traceback (most recent call last):
>     File "/tmp/erg-test-20230621-16889-1uoy50l/test.er", line -1, in <module>
>   ModuleNotFoundError: No module named '_erg_std_prelude'
> ```

I successfully reproduced this on a Linux machine. However I have no idea why this happens. It works well on macOS.

**Comment by chenrui333** [comment]
we can just log an upstream issue to see if anyone can help with the linux build. And just build the bottles for macos for now.

**Comment by chenrui333** [comment]
not just linux build, macos build has some issue as well

```
==> /opt/homebrew/Cellar/erg/0.6.14/bin/erg /private/tmp/erg-test-20230716-8695-1k2j46w/test.er
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/erg_common/python_util.rs:682:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: erg: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected: 0
  Actual: 101
```

**Comment by chenrui333** [comment]
Should be good now.

**Review by fxcoudert — APPROVED** [review]

**Pull request merged**
