### PR TITLE
python@3.9 3.9.3

### PR DESCRIPTION
**Pull request by jdmartin**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks for your PR, @jdmartin. You can update `setuptools` to 54.2.0.

**Comment by jdmartin** [comment]
Thanks, @carlocab!  Sorry that I didn't update that before bumping... now that I have, what would be the best way to make the alteration here?  (Sorry, I'm a bit of a git noob.)  Should I edit the Formula/python@3.9.rb attached to this PR, close it and bump again, or something else?

**Comment by carlocab** [comment]
You can just amend the commit in this PR with `git commit --amend` and `git push --force`.

**Comment by jdmartin** [comment]
Thanks, again!  Should be all set now. :)

**Comment by carlocab** [comment]
We actually prefer PRs to have only one commit per formula file modified. I cleaned that up for you.

**Comment by jdmartin** [comment]
Oh! I'm sorry.  Thanks for taking care of it.  I'll be more careful in the future. 😀

**Comment by carlocab** [comment]
CI issues. Have to restart the CI run, sadly.

**Comment by jdmartin** [comment]
Hmm... looks like 3.9.3 may be broken.  A 3.9.4 hotfix has been released today: https://pythoninsider.blogspot.com/2021/04/python-394-hotfix-is-now-available.html

**Comment by jdmartin** [comment]
As this is a broken release, and the python.org site has removed it [see here](https://www.python.org/downloads/), I'm going to close and open a 3.9.4 PR.  🤞

**Pull request closed without merging**
