### PR TITLE
gtk+3 3.22.14

### PR DESCRIPTION
**Pull request by tschoonj**
DO NOT MERGE
Broken (again)...

### CODE REVIEW

**Comment by tschoonj** [comment]
@ilovezfs if you or anyone else has access to a non-retina Mac, I would be grateful if this could be tested and confirm that everything looks properly

**Comment by bfontaine** [comment]
I’ve a non-retina Mac (MacBook Air mid '13), here’s a screenshot of `gtk3-widget-factory` after installing the formula from this PR:

screenshot

**Comment by tschoonj** [comment]
Thanks!

Feel free to merge this one in then

**Comment by bfontaine** [comment]
Thank you for merging it @tschoonj, I was sleeping when you posted your comment :smiley:

**Pull request closed without merging**
