### PR TITLE
kubernetes-cli 1.5.5

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Why have a `kubernetes-cli@1.6` alias if the latest version is 1.5?

**Comment by neutric** [comment]
Because `devel` is on 1.6 (and the CI checks told me so).

**Comment by fxcoudert** [comment]
Either the audit is wrong, or that's horrible user interface. If we add this symlink, `brew install kubernetes-cli@1.6` will actually install `kubernetes-cli-1.5.4` (and not the `devel` version).

Regardless of the audit, I think we shouldn't install versioned aliases for `devel` versions.

**Comment by MikeMcQuaid** [comment]
We should only add aliases based on stable versions, yeh. The `audit` can likely be improved.

**Comment by neutric** [comment]
I removed the `kubernetes-cli@1.6` alias.

**Comment by MikeMcQuaid** [comment]
@neutric Thanks and apologies for confusion.

**Comment by neutric** [comment]
@MikeMcQuaid Absolutely no problem. I hesitated for a second but was in a rush and figured that this case is not that uncommon and audit thus did the right thing. Thanks for being on top of things, @fxcoudert!

**Comment by neutric** [comment]
@MikeMcQuaid Should I open an issue for that? Or are you faster adding a check to `audit` that would not emit a warning concerning the missing alias when issued with `--devel` (if that is even a proper solution) than I would be putting this into understandable words?

**Comment by MikeMcQuaid** [comment]
@neutric Ideally try a PR otherwise I'll take a look when I get a chance.

**Comment by neutric** [comment]
Alright!

**Pull request closed without merging**
