### PR TITLE
radare2 4.1.1

### PR DESCRIPTION
**Pull request by jacob-greenfield**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Created with `brew bump-formula-pr` (manually uploaded because the GitHub API wasn't working for some reason).

Note:
* For some reason, tarballs are no longer distributed on the build site (hence the switch to the GitHub release archive).
* There is an official [prebuilt `pkg` installer](https://radare.mikelloc.com/list) but no bare binaries (you could extract from the `pkg` in theory I guess but I can't think of a good reason for using the `pkg` rather than the default bottle).

### CODE REVIEW

**Comment by Coder-256** [comment]
All 3 builds failed on `brew doctor`:

```
        Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/lib/libfuseprivate.0.dylib
  /usr/local/lib/libfuseprivate.dylib
```

I am completely and utterly clueless on the cause behind this or how I would even begin debugging this. Every other test passed. My best guess is that this problem is somehow completely unrelated to this PR and maybe somehow this just exposes a latent bug (or maybe there was an unrelated recent change that broke something?). AFAICT the only time this PR is accessed before the failure is simply pulling the changes, so I can't imagine how that causes these symlinks to break.

**Comment by Coder-256** [comment]
Definitely related to Homebrew/homebrew-test-bot#301 but I'm not sure how

**Comment by bayandin** [comment]
Thanks @Coder-256!
Could you please update the formula to version 4.1.1

**Comment by Coder-256** [comment]
@bayandin Done 👍

**Comment by bayandin** [comment]
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @Coder-256!

**Pull request closed without merging**
