### PR TITLE
git 2.19.2

### PR DESCRIPTION
**Pull request by koraktor**

### CODE REVIEW

**Comment by lembacon** [comment]
Both `html` and `man` resources also need updating.

**Comment by koraktor** [comment]
Oops, sorry. Looks I‘m a bit out of practice.

Fixed.

**Comment by lembacon** [comment]
Testing failure on Mojave,

```
10:11:58 ==> make test
10:11:58 ./t-git-credential-netrc.sh
10:11:58 ok 1 - set up test repository
10:11:58 # run 1: git-credential-netrc (perl /private/tmp/git-20181122-73360-zmgt22/git-2.19.2/t/../contrib/credential/netrc/test.pl)
10:11:58 1..1
10:11:58 # test_external test git-credential-netrc failed: perl /private/tmp/git-20181122-73360-zmgt22/git-2.19.2/t/../contrib/credential/netrc/test.pl
10:11:58 make: *** [test] Error 1
```

**Comment by koraktor** [comment]
@lembacon I can’t reproduce this on my machine.

And the output doesn’t really tell us what the problem is. 😕

**Comment by leonklingele** [comment]
Can this be resolved please? :)

@BrewTestBot test this again!

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
The test on Mojave is now fixed. 😅

**Comment by lembacon** [comment]
Thanks @koraktor!

**Pull request closed without merging**
