### PR TITLE
dvc 2.10.1

### LINKED ISSUE #7569: OpenSSH private key encryption requires bcrypt with KDF support
# Bug Report
DescriptionRunning dvc push returns an error after upgrading to dvc version 2.9.5.:

ERROR: unexpected error - OpenSSH private key encryption requires bcrypt with KDF support 

## Reproduce

    mkdir test
    cd test
    git init .
    dvc init
    dvc remote add storage ssh://host:/storage
    dvc remote default storage
    echo hi > test.txt
    dvc add test.txt
    dvc push test.txt

## Expected

I expect the file to be pushed to the remote storage.

## Environment information

macOS Monterey version 12.3.1 running on MacBook Pro M1
DVC installed via Homebrew Homebrew 3.4.6-36-g6745bb2

## Output of dvc doctor:

DVC version: 2.9.5 (brew)
---------------------------------
Platform: Python 3.9.12 on macOS-12.3.1-x86_64-i386-64bit
Supports:
	azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.7.1),
	gdrive (pydrive2 = 1.10.0),
	gs (gcsfs = 2022.1.0),
	hdfs (fsspec = 2022.1.0, pyarrow = 4.0.1),
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.1.0, boto3 = 1.20.24),
	ssh (sshfs = 2021.11.2),
	webdav (webdav4 = 0.9.4),
	webdavs (webdav4 = 0.9.4)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: ssh
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc (subdir), git

### PR DESCRIPTION
**Pull request by pmrowla**
Created with brew bump-formula-pr.

---

This also includes a manual update to `pypi_formula_mappings.json` (added new `bcrypt` extra package)

will close https://github.com/iterative/dvc/issues/7569

### CODE REVIEW

**Comment by SMillerDev** [comment]
> This also includes a manual update to pypi_formula_mappings.json (added new bcrypt extra package)

Do they have an install target that would include this?

**Comment by pmrowla** [comment]
> Do they have an install target that would include this?

Yes, the extra was left out of prior DVC brew releases by mistake (see https://github.com/iterative/dvc/issues/7569)

**Comment by cho-m** [comment]
I would recommend replacing some `extra_packages` with corresponding `pip` [extras_require](https://github.com/iterative/dvc/blob/main/setup.cfg#L78) feature name, which Homebrew supports via `package_name`. This would avoid having to hardcode and manually modify those dependencies.

One option would be to use `all` and add `pyarrow` to exclude:
```json
  "dvc": {
    "package_name": "dvc[all]",
    "extra_packages": ["...TODO..."],
    "exclude_packages": ["protobuf", "pyarrow", "six", "tabulate"]
  }
```

Another option would be to list features out like:
```json
  "dvc": {
    "package_name": "dvc[azure,gdrive,gs,oss,s3,ssh,webdav]",
    "extra_packages": ["...TODO..."],
    "exclude_packages": ["protobuf", "six", "tabulate"]
  }
```

This will help pick up new dependencies like the missing `ossfs`.

Ideally, there shouldn't be any `extra_packages`, but can add `oss2` to avoid picking older `oss2` that needs `aliyun-python-sdk-core-v3`.

**Comment by pmrowla** [comment]
> I would recommend replacing some `extra_packages` with corresponding `pip` [extras_require](https://github.com/iterative/dvc/blob/main/setup.cfg#L78) feature name, which Homebrew supports via `package_name`. This would avoid having to hardcode and manually modify those dependencies.

👍

Thanks, specifying `dvc[all]` this way looks like what we want, we just weren't aware that it actually supported pip extras in this way

**Comment by pmrowla** [comment]
PR has been updated to use `package_name: dvc[all]`.

One thing to note is that this still requires passing an additional `jmespath<1.0` into pipgrip in order for it to resolve DVC's dependencies properly (see https://github.com/Homebrew/brew/pull/13147 and the other linked issues there)

**Review by chenrui333 — APPROVED** [review]

**Comment by cho-m** [comment]
> One thing to note is that this still requires passing an additional `jmespath<1.0` into pipgrip in order for it to resolve DVC's dependencies properly (see [Homebrew/brew#13147](https://github.com/Homebrew/brew/pull/13147) and the other linked issues there)

I wonder if it would be worth enhancing `extra_packages` to support `>` and `<` constraints (I think it only supports unversioned and exact version `==` right now).

It looks like `oss2` v2.14+ no longer uses `aliyun-python-sdk-core-v3` (https://github.com/aliyun/aliyun-oss-python-sdk/commit/7c1a93ab6578d67fc91686eeaa0fb71d7a7802cd). Assuming rest of dependency tree is okay, then doing `oss2>=2.14.0` should avoid problematic packages.

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
