### PR TITLE
clang-format 15.0.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by Porkepix** [comment]
While having the exact same version numbers, the resource wasn't updated, is it normal?

**Comment by H-G-Hristov** [comment]
Is this dead?

**Comment by carlocab** [comment]
Looks like it, yes. Please open a pull request if you need this formula to be updated. The `install` method will need updating, though. See also #110369.

**Comment by H-G-Hristov** [comment]
@carlocab What's wrong with the `install`? I'm see the error but I don't get what's actually wrong.

**Pull request closed without merging**
