### PR TITLE
nvc 1.6.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ** Error: unit STD.STANDARD not found in library STD
```

**Comment by carlocab** [comment]
Let's try to get more verbose output here.

**Comment by cho-m** [comment]
> Let's try to get more verbose output here.

Would probably need to enable verbosity via `make V=1`.

---

Anyways, if I were to guess, I think it looks like a parallelization issue where NVC library is being built before STD library is ready.

As workaround, can try `ENV.deparallelize`.

**Comment by SMillerDev** [comment]
> configure: error: Could not detect the LLVM libraries. Make sure that llvm-config is on your path or specified by --with-llvm.

**Comment by carlocab** [comment]
> configure: error: Could not detect the LLVM libraries. Make sure that llvm-config is on your path or specified by --with-llvm.

https://github.com/Homebrew/homebrew-core/blob/37a53acb2212aa6de0e0e4ecc578a6a6f845c798/Formula/nvc.rb#L36

🤷

**Comment by cho-m** [comment]
Seems to be catch-all error message in M4, which would also happen when LLVM library test code failed to compile (https://github.com/nickg/nvc/blob/master/m4/ax_llvm_c.m4).

Here I would guess issue is `gcc-5`.
`llvm` itself has dependency on `gcc` for Linux, so may need to propagate that.

Also need to change configure option that is forcing `/usr/bin/clang`. This isn't the cause for failure, but it may cause an error later on during `make`.

**Comment by cho-m** [comment]
Looks like Linux built, but need to get rid of shim
```
  /home/linuxbrew/.linuxbrew/Cellar/nvc/1.6.0/bin/nvc
   --> match '/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/ld' at offset 0xd4440
  Warning: String '/home/linuxbrew/.linuxbrew/Homebrew' still exists in these files:
```

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
