### PR TITLE
Re-add maven 3.8.1 as a distinct version because 3.8.2 is broken/buggy...

### PR DESCRIPTION
**Pull request by fredcooke**
...and no 3.6 versions are available her (which are also all fine AFAIK).

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

I didn't check the commit one because I strongly believe that prose should dominate and illegibly short messages based on 80 char wide terminals without modern support are an anti pattern. However if forced at virtual gun point, I'll comply.

I didn't check the others as I didn't do them, but the file is lifted from the most recent version in history with:

```
cd Formula
git checkout 225b9036c0db7c4439de7ee540a07baa481dc2ae -- maven.rb
cp maven.rb maven@3.8.1.rb 
git checkout HEAD -- maven.rb
git add maven@3.8.1.rb
git commit -m ""
```

And thus it can be verified with:

```
cd Formula
git checkout 225b9036c0db7c4439de7ee540a07baa481dc2ae -- maven.rb
diff maven.rb maven@3.8.1.rb 
``` 

And clean up with `git reset --hard HEAD` once happy. 

I think 3.6 should be there, too, and can add it to the same PR or do a new one for that if that's acceptable

I know why it's not present - the popularity statistics, but they don't tell the whole story, a lot of big orgs are running horribly out dated versions of tools like this and it's important to support the last few recent versions in case of bugs like this one in 3.8.2. Hopefully 3.8.3 comes along with a fix soon. :-)

### CODE REVIEW

**Comment by SMillerDev** [comment]
We'll happily take patches if they're upstreamed but our rules explicitly forbid this: https://docs.brew.sh/Versions

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by fredcooke** [comment]
Thanks @SMillerDev - Yeah, I'd read that, which is what I was talking about in the body of the PR, however 3.8.2 is "maven.rb" and is *broken* unfortunately. As in Maven 3.8.2 is buggy - maybe it solves some issues that other devs have and doesn't break for them, but it breaks for us on hundreds of projects in many orgs. If you can help me figure out how to refer to a historic version in https://github.com/Branchout/homebrew-branchout rather than the default current version then that's the best solution rather than a custom tap IMO. The recipe exists in the history of homebrew-core but isn't available any more. 

Re this: 

```
Versioned formulae should differ in major/minor (not patch) versions from the current stable release. This is because patch versions indicate bug or security updates, and we want to ensure you apply security updates.
```

In this case the policy is forcing an unusable tool onto a subset of users with a specific project structure and is not serving the community well. But if I can assume that 3.6 IS eligible because it's a minor version difference not a patch, the latest 3.6 does work for us and would be great to have in homebrew-core :-)  

Pretty please? :-D

**Comment by fredcooke** [comment]
I'm surprised that 3.5 had more popularity than 3.6 did, check out the version history here:

Screenshot-2021-09-30-No-003-Selection

I was the first in our company to jump up to 3.8.1 and I was happy to find that it broke nothing :-) Sadly 3.8.2 is not in that same boat...

**Comment by SMillerDev** [comment]
Really your issues with maven should be reported to the maven developers. There's not much homebrew can do to fix this compared to the people who wrote the software.

**Comment by fredcooke** [comment]
@SMillerDev absolutely, but can you accept a properly set up 3.6 version of this PR? Happy to close this one either way as it's not going to get merged, but I'd love to be able to have a working stack right now for our Mac users (dozens of the fashion following buggers, ha ha) and 3.6 would provide that just nicely :-)

**Comment by fredcooke** [comment]
What I mean to point out is that existing non-broken versions exist (3.8.1 and most if not all 3.6 versions) whereas waiting for a fix from the Maven team could take some time meaning nasty manual workarounds for dozens of people in the mean time. There will always be bad versions of software and although Brew is superior to fink and ports (veteran here) this is a bit of a limitation IMO and artificially imposed.

**Comment by SMillerDev** [comment]
> but can you accept a properly set up 3.6 version of this PR?

If upstream will support that version, definitely.

> There will always be bad versions of software and although Brew is superior to fink and ports (veteran here) this is a bit of a limitation IMO and artificially imposed.

That's why a patch, even if it isn't accepted yet upstream, would be the best solution.

**Comment by fredcooke** [comment]
Thanks boss, #86192 still needs some work (just figuring that out) but this one can, sadly, close. Appreciate your help and great attitude.

**Pull request closed without merging**
