### PR TITLE
qt5: enable all options

### PR DESCRIPTION
**Pull request by ilovezfs**
intended to test #8502, and not necessarily intended to be merged

CC @MikeMcQuaid @DomT4

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Good idea to test. If this fails I'd probably like us to remove this option and not re-add it.

**Comment by DomT4** [comment]
Seems to have built okay on CI at least.

**Comment by ilovezfs** [comment]
So it looks like #8502 may actually be about the `--with-examples` option: https://github.com/Homebrew/homebrew-core/issues/8502#issuecomment-270740472

**Comment by ilovezfs** [comment]
Looks like `--with-examples` is also fine except for minor audit whining:
```
==> brew audit qt5 --online
==> FAILED
Error: 1 problem in 1 formula
qt5:
  * The installation was broken.
    Broken dylib links found:
      libgruesensor.1.dylib

```

**Comment by ilovezfs** [comment]
OK, let's try all options enabled. :spaghetti:

**Comment by ilovezfs** [comment]
Build with all options enabled was also fine. Poor qt5 and it's falsely accused, much maligned and scapegoated options. :goat:

**Comment by DomT4** [comment]
Possibly the first time a breakage wasn't explicitly the `qt5` formula's fault 😉.

**Pull request closed without merging**
