### PR TITLE
grpc: uses zlib from macos, install .so files on linux

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by dawidd6 — DISMISSED** [review]

**Comment by iMichka** [comment]
On Big Sur:

> 2020-12-23T01:26:27.3374580Z /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -Dgpr_EXPORTS -I/tmp/grpc-20201223-89359-1yzmh3j/include -I/tmp/grpc-20201223-89359-1yzmh3j -I/tmp/grpc-20201223-89359-1yzmh3j/third_party/address_sorting/include -I/tmp/grpc-20201223-89359-1yzmh3j/src/core/ext/upb-generated -I/tmp/grpc-20201223-89359-1yzmh3j/src/core/ext/upbdefs-generated -I/tmp/grpc-20201223-89359-1yzmh3j/third_party/upb -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -fPIC -std=c++17 -o CMakeFiles/gpr.dir/src/core/lib/profiling/basic_timers.cc.o -c /tmp/grpc-20201223-89359-1yzmh3j/src/core/lib/profiling/basic_timers.cc
2020-12-23T01:26:27.3379270Z make[2]: *** No rule to make target `/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/CoreFoundation.framework', needed by `libgpr.13.0.0.dylib'.  Stop.
2020-12-23T01:26:27.3380620Z make[2]: *** Waiting for unfinished jobs....

**Comment by carlocab** [comment]
Was able to fix this locally. Rebuilding all the formulae it depends on works. At least one of them has the versioned Big Sur SDK path baked in. You can skip rebuilding `openssl`; it's not that.

I did try being smarter about which of the dependencies to rebuild, but that didn't work, so I just rebuilt all of them except for `openssl`.

**Comment by carlocab** [comment]
This _might_ be related to https://github.com/Homebrew/brew/issues/10127; not sure. @Bo98

**Comment by iMichka** [comment]
Rev-bumping `abseil` worked.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Good to know. 

I first tried bumping `protobuf` since the error log looked related to a `zlib` dependency, and `protobuf` was the only one that had linkage with `zlib`. But then rebuilding `grpc` lead to a different error complaining about not being able to find the `CoreFoundation` `framework` which... looked like all of the dependencies. So I ran out of patience and just rebuilt all of them. 😅

**Pull request closed without merging**
