### PR TITLE
jHiccup 2.0.8

### PR DESCRIPTION
**Pull request by queengooborg**

### CODE REVIEW

**Review by ilovezfs — APPROVED** [review]

**Comment by vinyldarkscratch** [comment]
```
==> Downloading https://www.azul.com/files/jHiccup-2.0.8-dist.zip
Already downloaded: /Users/brew/Library/Caches/Homebrew/jhiccup-2.0.8.zip
==> Verifying jhiccup-2.0.8.zip checksum
unzip -qq /Users/brew/Library/Caches/Homebrew/jhiccup-2.0.8.zip
Error: No such file or directory - target
```

Seems the test bot still thinks the filename is "jhiccup-2.0.8" and not "jHiccup-2.0.8-dist"?

**Comment by vinyldarkscratch** [comment]
My revision bump didn't work...ah well, I tried!

**Comment by ilovezfs** [comment]
This one probably requires a full formula rewrite. I'd just close this out for now.

**Comment by vinyldarkscratch** [comment]
Just in case, I'll hold onto the branch.  :wink:

**Comment by ilovezfs** [comment]
yeah feel free to try to get it working locally. I think they've rearranged things a bit

**Pull request closed without merging**
