### PR TITLE
crystal-lang: use head of shard resource for head

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @monouser7dig

### CODE REVIEW

**Comment by monouser7dig** [comment]
thanks! 
looks good to me, 
if you are uncertain if it actually works this way _(although you probably know best)_ I can check your branch on a serrate system later 

otherwise I would just report after the merge

**Comment by ilovezfs** [comment]
@monouser7dig looks like build fails:
```
==> Checking out branch master
==> /private/tmp/crystal-lang-20171004-42284-lx4ezs/bin/crystal build -o /private/tmp/crystal-lang-20
Last 15 lines from /Users/joe/Library/Logs/Homebrew/crystal-lang/02.crystal:

      read_mapping(pull) do
      ^~~~~~~~~~~~

in src/spec.cr:73: instantiating 'read_mapping(YAML::PullParser)'

      read_mapping(pull) do
      ^~~~~~~~~~~~

in src/spec.cr:117: undefined method 'line_number' for YAML::PullParser

            raise YAML::ParseException.new("unknown attribute: #{ key }", pull.line_number, pull.column_number)
                                                                               ^~~~~~~~~~~

Rerun with --error-trace to show a complete error trace.

READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
crystal-lang: use head of shard resource for head https://github.com/Homebrew/homebrew-core/pull/18968
```

**Comment by monouser7dig** [comment]
this could very well be another issue because they currently merge a YAML and Time lib remake and some things broke in the spec 

another option would be to just give it a day and see how it evolves and if the issue is actually with the formula

**Comment by ilovezfs** [comment]
@monouser7dig I'm going to assume this doesn't make anything _worse_ and merge it so you can you mess around.

**Comment by monouser7dig** [comment]
`install` and `build-from-source` work as before so it does not seem to make anything worse

**Pull request merged**
