### PR TITLE
avrdude: add config.guess/config.sub workaround.

### PR DESCRIPTION
**Pull request by mahiuchun**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Makes it buildable on ARM.

### CODE REVIEW

**Comment by carlocab** [comment]
You probably need a `depends_on "automake" if Hardware::CPU.arm?`.

```
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /usr/local/opt/automake/share/automake-1.16/config.guess
```

**Comment by mahiuchun** [comment]
Ah, I did not realize `depends_on "automake" => :build` was in the head block. The config files update/workaround is not architecture dependent by itself.

**Review by fxcoudert — APPROVED** [review]

**Comment by carlocab** [comment]
Merging this without bottles then will dispatch the bottle separately. Thanks @mahiuchun!

**Comment by fxcoudert** [comment]
I'll let you merge @carlocab but I don't think we want to preserve old bottles at all cost. There is a positive side effect in rebuilding bottles with more recent toolchains than what was originally used.

**Comment by carlocab** [comment]
@fxcoudert I agree. However, for this particular formula, I think preserving the old bottles doesn't hurt. If there are concrete benefits to newer bottles, then I think the appropriate thing to do would be a revision bump so that the users that we do support are able to benefit from them.

**Pull request merged**
