### PR TITLE
fix: disable bottle for luit 20180628

### PR DESCRIPTION
**Pull request by alswl**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

```
luit:
  * Formulae should not use `bottle :disabled`
Error: 1 problem in 1 formula detected
```

If luit build on Jenkins server, it will failed on my macOS.

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Library and client of what? Can you explain a bit more? We haven't had a bug report about this.

**Comment by alswl** [comment]
@fxcoudert I'm not sure. If build from Jenkins server, when luit runs, run command `/usr/local/bin/luit -encoding GBK ls`, it will throw `cannot open /usr/X11/lib/X11/fonts/encodings/encodings.dir`.

If build on my macOS, it runs successful.

**Comment by fxcoudert** [comment]
@alswl this is not the right fix for the issue. Maybe running `configure` with `--without-x` would be.

**Comment by alswl** [comment]
@fxcoudert Jenkins build with fail:

```
==> /usr/local/Cellar/luit/20180628/bin/luit -encoding GBK ls
Couldn't set terminal to raw
Error: luit: failed
Failed executing:
/usr/local/Homebrew/Library/Homebrew/formula.rb:1921:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1858:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1858:in `system'
```

Any suggestion?

**Comment by alswl** [comment]
On my macOS:

```
brew reinstall --build-from-source luit
==> Reinstalling luit
==> Downloading https://invisible-mirror.net/archives/luit/luit-20180628.tgz
Already downloaded: /Users/jingchao.djc/Library/Caches/Homebrew/downloads/4ab271ce6194b9a2f89a0bfa1b49722cf4934de97de5609761dc0efca8f0ddce--luit-20180628.tgz
==> ./configure --prefix=/usr/local/Cellar/luit/20180628 --without-x
==> make install
==> Not running post_install as we're building a bottle
You can run it manually using `brew postinstall luit`
🍺  /usr/local/Cellar/luit/20180628: 4 files, 90.9KB, built in 14 seconds
```

**Comment by fxcoudert** [comment]
The error is in `brew test`. Can you find a test that would reproduce your issue, yet not need a terminal to run?

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @alswl for the pull request. Please next time do not touch the bottle block, it is automatically handled :)

**Comment by alswl** [comment]
@fxcoudert luit install from homebrew is still failed:

```
➜  homebrew-core git:(master) brew reinstall luit
==> Reinstalling luit
==> Downloading https://homebrew.bintray.com/bottles/luit-20180628.mojave.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring luit-20180628.mojave.bottle.1.tar.gz
🍺  /usr/local/Cellar/luit/20180628: 4 files, 91.1KB
➜  homebrew-core git:(master) /usr/local/bin/luit -x -encoding GBK ls
cannot open /usr/X11/lib/X11/fonts/encodings/encodings.dir
```

Maybe disable bottle and install from source is the only way to use it.
like `Formula/cryptopp.rb` or `Formula/leafnode.rb`.

**Comment by alswl** [comment]
> @BrewTestBot test this please

Sorry, I always test on my mac, but it still failed on Jenkins Server, I cannot reproduce it.

**Pull request closed without merging**
