### PR TITLE
gpm 1.4.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
Not sure this formula shouldn't just be using `depends_on "go"` and the test is a bit of a mess, but otherwise 👍 .

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed.

**Comment by ilovezfs** [comment]
@DomT4 :ship:?

**Comment by DomT4** [comment]
Seems reasonable to me 👍.

**Pull request closed without merging**
