### PR TITLE
arcade-learning-environment 0.9.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
there is some issue of producing the binary.

**Comment by chenrui333** [comment]
need to sort it out in the upstream first.

**Comment by branchvincent** [comment]
The `ale-import-roms` script was removed in https://github.com/Farama-Foundation/Arcade-Learning-Environment/pull/516, so I've installed the roms to match the PyPI wheel

**Review by bevanjkay — APPROVED** [review]

**Comment by chenrui333** [comment]
Nice catch, thanks @branchvincent!

**Pull request merged**
