### PR TITLE
Convox CLI needs packr as a preprocessor to embed templates

### PR DESCRIPTION
**Pull request by ddollar**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
This is looking good. The only question is: should we package it as a separate formula, so others can use it as standalone tool?

**Comment by ddollar** [comment]
Not sure about the answer to that but if it would be possible to merge this soon the `convox` CLI is currently broken for Homebrew users.

**Comment by fxcoudert** [comment]
> `convox` CLI is currently broken for Homebrew users

So that means it builds without `packr` with no error (sad), but also our test for it is poor, since it passed. How could we improve the test? (and then I believe we're done here)

**Comment by ddollar** [comment]
`packr` takes local files (templates) in this case and bundles them into the executable so that it can be standalone. Without running the `packr` pre-processor those files will be searched for on disk (and not exist next to the homebrew binary)

There isn't really a robust way to test this without running the Convox install process which requires a working Kubernetes cluster or AWS account.

**Comment by fxcoudert** [comment]
OK, merging

**Comment by ddollar** [comment]
Thank you!

**Pull request closed without merging**
