### PR TITLE
various: deprecate archived repos

### PR DESCRIPTION
**Pull request by SMillerDev**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
as caught in https://github.com/Homebrew/homebrew-core/actions/runs/5009520841/jobs/8978559774

### CODE REVIEW

**Comment by carlocab** [comment]
See also: #125554, profanity-im/profanity#1798

**Comment by SMillerDev** [comment]
Adding result of https://github.com/Homebrew/homebrew-core/actions/runs/5035124354/jobs/9030425438

**Comment by SMillerDev** [comment]
Filed https://bugs.ghostscript.com/show_bug.cgi?id=706736, in the meantime we can let mupdf use it's vendored copy.

**Comment by SMillerDev** [comment]
Split gumbo into: https://github.com/Homebrew/homebrew-core/pull/133411

**Comment by SMillerDev** [comment]
```
    error in textract setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
        extract-msg<=0.29.*
                   ~~~~~~^
```

Damned textract

**Pull request closed without merging**
