### PR TITLE
sshuttle 0.78.1

### PR DESCRIPTION
**Pull request by ilovezfs**
use new virtualenv feature
use multi-argument form of `system` in the test

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 don't we bottle all of these now?

**Comment by DomT4** [comment]
Apparently Python stuff doesn't use system development tools that require Xcode/CLT installed, so they are fine to not bottle, but my preference is _heavily_ towards bottling. I prefer to not expose users to any sort of build process, however tiny, where possible.

**Comment by ilovezfs** [comment]
@DomT4 yeah I'm very skeptical of bottle unneededs generally. They seem to also expose users to 404 issues unnecessarily even when they're "appropriate."

**Comment by ilovezfs** [comment]
@DomT4 :ship:?

**Comment by DomT4** [comment]
Bit weird the syntax is still `virtualenv_install_with_resources` even when there's no resources, but 👍.

**Comment by ilovezfs** [comment]
@DomT4 I think it should just be `virtualenv_install` and if you don't know that means resources too, if there are any, then it's a learning opportunity. CC @tdsmith

**Comment by ilovezfs** [comment]
@DomT4 alternatively we could introduce new pedantry and have two versions, `virtualenv_install_with_resources` and `virtualenv_install` and raise if the first is used when there are no resources, but that seems tedious without an obvious benefit other than precision for the sake of precision.

**Pull request closed without merging**
