### PR TITLE
git-annex 7.20190819

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
23:04:27 ==> brew install --only-dependencies --verbose --build-bottle git-annex
23:06:32 FATAL: command execution failed
23:06:32 java.io.EOFException
23:06:32 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2681)

image

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
```
==> Verifying bottles published on Bintray
Verifying bottle: git-annex-7.20190819.mojave.bottle.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 998bdaab335a14297b1c67ace50bdfbe94058fdae1284e10bf123b948eea2939
  Actual: 947b290d4f2ed7a8938bcf2064d80c3fc392a84a4897b7e317d5ef3a8d86f854
```

Conflicts. Manually deleting the bottle and trying rebuilding…

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
