### PR TITLE
fastqc: check test failure

### PR DESCRIPTION
**Pull request by iMichka**
Just testing to see if the ARM test failure is reproducible. I've seen this one fail in multiple long build runs lately.

### CODE REVIEW

**Comment by p-linnane** [comment]
According to the homepage this is `GPL-3.0-or-later`. I'll open a separate PR for that.

**Comment by p-linnane** [comment]
https://github.com/Homebrew/homebrew-core/pull/159568

**Comment by iMichka** [comment]
```
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/bin/bundle clean
  ==> Testing fastqc
  ==> /opt/homebrew/Cellar/fastqc/0.12.1_1/bin/fastqc test.fasta
  Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
  Started analysis of test.fasta
  null
  Analysis complete for test.fasta
  #
  # A fatal error has been detected by the Java Runtime Environment:
  #
  #  SIGILL (0x4) at pc=0x000000010103afc8, pid=7292, tid=26627
  #
  # JRE version: OpenJDK Runtime Environment Homebrew (21.0.1) (build 21.0.1)
  # Java VM: OpenJDK 64-Bit Server VM Homebrew (21.0.1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
  # Problematic frame:
  # C  [libawt.dylib+0x2efc8]  fillAAPgram+0x3e0
  #
  # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
  #
  # An error report file with more information is saved as:
  # /private/tmp/fastqc-test-20240110-7282-yiawo/hs_err_pid7292.log
  #
  # If you would like to submit a bug report, please visit:
  #   https://github.com/Homebrew/homebrew-core/issues
  Error: test failed
  # The crash happened outside the Java Virtual Machine in native code.
  # See problematic frame for where to report the bug.
  #
  Error: fastqc: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected: 0
    Actual: nil
```

**Comment by cho-m** [comment]
I think this is another Sonoma issue with JDK. Though not the same as #150824 as the test bypasses the GUI and runs in a headless CLI mode.

**Comment by iMichka** [comment]
Might be due to one of the .jar files having an issue?
The project comes with precompiled .jar files: [cisd-jhdf5.jar](https://github.com/s-andrews/FastQC/blob/master/cisd-jhdf5.jar), [htsjdk.jar](https://github.com/s-andrews/FastQC/blob/master/htsjdk.jar), [jbzip2-0.9.jar](https://github.com/s-andrews/FastQC/blob/master/jbzip2-0.9.jar).

I tried to rebuild `https://code.google.com/archive/p/jbzip2/source/default/source` from source, but it does not provide a build script, only a .jardesc file that can be compiled by eclipse ...

This is not going to be easy if we want to re-package this properly ...

**Comment by cho-m** [comment]
> Might be due to one of the .jar files having an issue? The project comes with precompiled .jar files: [cisd-jhdf5.jar](https://github.com/s-andrews/FastQC/blob/master/cisd-jhdf5.jar), [htsjdk.jar](https://github.com/s-andrews/FastQC/blob/master/htsjdk.jar), [jbzip2-0.9.jar](https://github.com/s-andrews/FastQC/blob/master/jbzip2-0.9.jar).

I still think JDK is issue.

If you have Sonoma ARM machine, you can install Ventura ARM `openjdk` bottle and the issue goes away.
- Sonoma ARM `openjdk`:
    ```console
    ❯ brew install fastqc
    ==> Downloading https://ghcr.io/v2/homebrew/core/fastqc/manifests/0.12.1
    Already downloaded: /Users/cho-m/Library/Caches/Homebrew/downloads/78a690e5bcf55e9471e64f0a3933ab1be89b76fb24589c81b063a1bf7c462250--fastqc-0.12.1.bottle_manifest.json
    ==> Fetching fastqc
    ==> Downloading https://ghcr.io/v2/homebrew/core/fastqc/blobs/sha256:98115fa6cc5acc2f8ac59e42843802c5e4d1484be2b030edbea
    Already downloaded: /Users/cho-m/Library/Caches/Homebrew/downloads/3e280a0409af33df1ca8bb81079d0f48ea22bbc6033709a285996ffb5c3ad88a--fastqc--0.12.1.all.bottle.tar.gz
    ==> Pouring fastqc--0.12.1.all.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/fastqc/0.12.1: 260 files, 12.0MB
    ==> Running `brew cleanup fastqc`...
    Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
    Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
    
    ❯ brew test -v fastqc
    ==> Testing fastqc
    ==> /opt/homebrew/Cellar/fastqc/0.12.1/bin/fastqc test.fasta
    Picked up _JAVA_OPTIONS: -Duser.home=/Users/cho-m/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
    Started analysis of test.fasta
    null
    Analysis complete for test.fasta
    #
    # A fatal error has been detected by the Java Runtime Environment:
    #
    #  SIGILL (0x4) at pc=0x0000000105da6fc8, pid=93595, tid=28675
    #
    # JRE version: OpenJDK Runtime Environment Homebrew (21.0.1) (build 21.0.1)
    # Java VM: OpenJDK 64-Bit Server VM Homebrew (21.0.1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
    # Problematic frame:
    # C  [libawt.dylib+0x2efc8]  fillAAPgram+0x3e0
    #
    # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
    #
    # An error report file with more information is saved as:
    # /private/tmp/fastqc-test-20240123-93587-gas164/hs_err_pid93595.log
    [1.447s][warning][os] Loading hsdis library failed
    #
    # If you would like to submit a bug report, please visit:
    #   https://github.com/Homebrew/homebrew-core/issues
    # The crash happened outside the Java Virtual Machine in native code.
    # See problematic frame for where to report the bug.
    #
    Error: fastqc: failed
    An exception occurred within a child process:
      Minitest::Assertion: Expected: 0
      Actual: nil
    ...
    ```
- Ventura ARM `openjdk`
    ```console
    ❯ brew edit openjdk
    <removed Sonoma ARM bottle>
    
    ❯ brew reinstall openjdk
    ==> Downloading https://ghcr.io/v2/homebrew/core/openjdk/manifests/21.0.1
    ################################################################################################################# 100.0%
    ==> Fetching openjdk
    ==> Downloading https://ghcr.io/v2/homebrew/core/openjdk/blobs/sha256:b0223e230b1086a6dab7c00472fac8ef67f799bf570a8f1b38
    ################################################################################################################# 100.0%
    ==> Reinstalling openjdk
    ==> Pouring openjdk--21.0.1.arm64_ventura.bottle.tar.gz
    🍺  /opt/homebrew/Cellar/openjdk/21.0.1: 600 files, 331MB
    ==> Running `brew cleanup openjdk`...
    Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
    Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
    
    ❯ brew test -v fastqc
    /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/bin/bundle clean
    ==> Testing fastqc
    ==> /opt/homebrew/Cellar/fastqc/0.12.1/bin/fastqc test.fasta
    Picked up _JAVA_OPTIONS: -Duser.home=/Users/cho-m/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
    Started analysis of test.fasta
    ```

**Comment by cho-m** [comment]
Also, most of JAR is bytecode which is cross-platform and doesn't need to be built from source.

Only `cisd-jhdf5.jar` has a couple native libs but they aren't used on ARM as there are no compatible variants:
```
native/nativedata/amd64-Linux/libnativedata.so
native/nativedata/amd64-Windows/nativedata.dll
native/nativedata/i386-Linux/libnativedata.so
native/nativedata/i386-Mac OS X/libnativedata.jnilib
native/nativedata/x86-Windows/nativedata.dll
native/nativedata/x86_64-Mac OS X/libnativedata.jnilib
native/unix/amd64-Linux/libunix.so
native/unix/i386-Linux/libunix.so
native/unix/i386-Mac OS X/libunix.jnilib
native/unix/x86_64-Mac OS X/libunix.jnilib
```

**Comment by chenrui333** [comment]
> I still think JDK is issue.

yeah, I feel the same, I can see the same test failure in my local sonoma arm machine as well.

**Comment by cho-m** [comment]
Rebuilding OpenJDK with newer SDK also fixed issue, so probably part of fixes included with macOS 14.2 / Xcode 15.1 (?).

I expect this to be fixed by #160093 (assuming fixes are in Xcode 15.1. I am on newer version so cannot backtest).

**Comment by cho-m** [comment]
Confirmed new SDK fixed issue in #161010 - https://github.com/Homebrew/homebrew-core/actions/runs/7679591014/job/20930693320#step:3:47

**Pull request closed without merging**
