### PR TITLE
mpv 0.29.0

### PR DESCRIPTION
**Pull request by ilovezfs**
depend on python at build time instead of python@2

Reverts https://github.com/Homebrew/homebrew-core/commit/b314a662626e0a7fd61fb8f2a5e12fbbb04651e6

### CODE REVIEW

**Comment by Akemi** [comment]
just another heads-up and sry for the trouble. hopefully https://github.com/mpv-player/mpv/pull/6004 fixes the testing problem? if yes, i believe we will try to get a new fixed version (0.29.1) out as fast as possible. there was at least one other build problem on windows cross-compiling that also needs fixing.

**Comment by JCount** [comment]
@Akemi it looks like your PR fixes the testing issue on Homebrew's CI. 🎉 Thanks for the rapid work towards fixing it.

Do you think we should just wait for a `0.29.1` bugfix release, or might it take long enough that we may want to just release this patched version as an interim fix?

**Comment by Akemi** [comment]
great that this fixes it.

personally i think we waited so long for a 0.29 that waiting a bit longer for 0.29.1 wouldn't be too bad. though i probably need to change that PR slightly. i will ask tomorrow if we can give a more specific ETA for 0.29.1 and will let you know.

**Comment by Akemi** [comment]
i fixed up the PR and this is most likely the final version. even so i tested it in a VM it would be nice if you could test it again too.

we hope to release 0.29.1 within a few days.

**Comment by JCount** [comment]
@Akemi The updated PR passes the CI as well, thanks. It sounds like it would be worth just waiting for a proper `0.29.1` release.

**Comment by ilovezfs** [comment]
@Noctem good point. updated.

**Pull request closed without merging**
