### PR TITLE
traefik 1.7.12

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
seems v8 compilation issue
```
17:25:16   clang++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/private/tmp/traefik-20190529-4359-mevzru/.brew_home/.node-gyp/12.3.1/include/node -I/private/tmp/traefik-20190529-4359-mevzru/.brew_home/.node-gyp/12.3.1/src -I/private/tmp/traefik-20190529-4359-mevzru/.brew_home/.node-gyp/12.3.1/deps/uv/include -I/private/tmp/traefik-20190529-4359-mevzru/.brew_home/.node-gyp/12.3.1/deps/v8/include -I../../nan -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -std=c++11 -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
17:25:16   clang++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/private/tmp/traefik-20190529-4359-mevzru/.brew_home/.node-gyp/12.3.1/include/node -I/private/tmp/traefik-20190529-4359-mevzru/.brew_home/.node-gyp/12.3.1/src -I/private/tmp/traefik-20190529-4359-mevzru/.brew_home/.node-gyp/12.3.1/deps/uv/include -I/private/tmp/traefik-20190529-4359-mevzru/.brew_home/.node-gyp/12.3.1/deps/v8/include -I../../nan -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -std=c++11 -MMD -MF ./Release/.deps/Release/obj.target/binding/src/create_string.o.d.raw   -c -o Release/obj.target/binding/src/create_string.o ../src/create_string.cpp
17:25:16   clang++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/private/tmp/traefik-20190529-4359-mevzru/.brew_home/.node-gyp/12.3.1/include/node -I/private/tmp/traefik-20190529-4359-mevzru/.brew_home/.node-gyp/12.3.1/src -I/private/tmp/traefik-20190529-4359-mevzru/.brew_home/.node-gyp/12.3.1/deps/uv/include -I/private/tmp/traefik-20190529-4359-mevzru/.brew_home/.node-gyp/12.3.1/deps/v8/include -I../../nan -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -std=c++11 -MMD -MF ./Release/.deps/Release/obj.target/binding/src/custom_function_bridge.o.d.raw   -c -o Release/obj.target/binding/src/custom_function_bridge.o ../src/custom_function_bridge.cpp
17:25:16 In file included from ../src/custom_function_bridge.cpp:1:
17:25:16 In file included from ../../nan/nan.h:203:
17:25:16 In file included from ../../nan/nan_new.h:189:
17:25:16 ../../nan/nan_implementation_12_inl.h:103:42: error: no viable conversion from 'v8::Isolate *' to 'Local<v8::Context>'
17:25:16   return scope.Escape(v8::Function::New( isolate
```

**Comment by chenrui333** [comment]
```
23:47:57 chmod -Rf +w /private/tmp/d20190530-19845-egu9ld
23:47:57 ==> yarn install
23:47:57 yarn install v1.16.0
23:47:57 [1/4] Resolving packages...
23:47:57 [2/4] Fetching packages...
23:47:57 error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "12.3.1"
23:47:57 error Found incompatible module.
23:47:57 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
23:47:57 
23:47:57 ==> Formula
23:47:57 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/traefik.rb
```

**Comment by djerfy** [comment]
Hi @chenrui333,

Before `yarn install` command add `yarn upgrade`:
```ruby
  cd "src/github.com/containous/traefik" do
      cd "webui" do
        system "yarn", "upgrade"
        system "yarn", "install"
        system "yarn", "run", "build"
      end
      system "go", "generate"
      system "go", "build", "-o", bin/"traefik", "./cmd/traefik"
      prefix.install_metafiles
    end
```

**Comment by chenrui333** [comment]
@djerfy Perfect, thanks for help, push the change now.

**Pull request closed without merging**
