### PR TITLE
gsettings-desktop-schemas 46.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
cc @cho-m (this formula looks like not autobumpable)

**Comment by cho-m** [comment]
> cc @cho-m (this formula looks like not autobumpable)

My PR https://github.com/Homebrew/brew/pull/16904 isn't merged yet which should handle GNOME URLs.

I'm going to wait until tomorrow to give enough time (24+ hours and weekday). Will merge then if no review change requests and still open.

**Comment by chenrui333** [comment]
Sounds good, thanks!

**Comment by fxcoudert** [comment]
Once more unto the breach, dear friends, once more…

**Review by p-linnane — APPROVED** [review]

**Review by fxcoudert — APPROVED** [review]

**Pull request merged**
