### PR TITLE
libgosu 0.11.3.1

### PR DESCRIPTION
**Pull request by pmer**

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
I noticed this tag was created, but it's not designated as the latest release. That is still 0.11.3. Upstream will need to designate the latest release as 0.11.3.1 before we merge this.

See https://github.com/gosu/gosu/releases/latest

**Comment by ilovezfs** [comment]
I've asked upstream what's up here https://github.com/gosu/gosu/issues/396

**Comment by jlnr** [comment]
0.11.3.1 is a Ruby-only hotfix release. On the C++ side, nothing has changed, and a formula update is not necessary.

I will update gosu's release list to clear that up too. Sorry for the confusion.

**Comment by ilovezfs** [comment]
Thanks for the clarification @jlnr

**Comment by ilovezfs** [comment]
@pmer thanks for this PR nonetheless.

**Pull request closed without merging**
