### PR TITLE
tunnel 0.5.13

### PR DESCRIPTION
**Pull request by vishr**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you squash your commits and rebase them on top of master?

**Comment by chenrui333** [comment]
@vishr, it would be better not use the master branch when you file a PR. Therefore you would have less trouble dealing with the upstream master branch conflict. :)

**Comment by chenrui333** [comment]
Your old commit history contained a release commit (v0.5.12). While i was trying to rebase your commit history, I did accidentally close it. 

I ended up creating a new PR for this effort, https://github.com/Homebrew/homebrew-core/pull/46982

It would be create in the future you can have something like `tunnel-0.5.13` as PR branch.

**Comment by chenrui333** [comment]
We do have convenient command for filing the PR like something below:

```
brew bump-formula-pr tunnel \
--url=https://github.com/labstack/tunnel-client/archive/v0.5.13.tar.gz \
--sha256=7b70b4728f90811c9bee7523af52458015bac65e22c6cee5be66122711bd1451
```

And there is community github action that you can use as well, 
https://github.com/mislav/bump-homebrew-formula-action

**Comment by vishr** [comment]
> We do have convenient command for filing the PR like something below:
> 
> ```
> brew bump-formula-pr tunnel \
> --url=https://github.com/labstack/tunnel-client/archive/v0.5.13.tar.gz \
> --sha256=7b70b4728f90811c9bee7523af52458015bac65e22c6cee5be66122711bd1451
> ```
> 
> And there is community github action that you can use as well,
> https://github.com/mislav/bump-homebrew-formula-action

Sure. I am getting error dealing with `bump-formula-pr` lately and I will check out github action.

**Comment by chenrui333** [comment]
I guess, that might be because your master branch is not quite clean?

**Comment by chenrui333** [comment]
but certainly let me know if you run into this issue again. Happy to help!

**Comment by chenrui333** [comment]
That github action is used by `ruby-build`, for example like this, `https://github.com/Homebrew/homebrew-core/pull/46619`

**Comment by vishr** [comment]
> but certainly let me know if you run into this issue again. Happy to help!

Thank you!

**Pull request closed without merging**
