### PR TITLE
minizip2 2.10.4

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Build error:
```
The formula built, but is not symlinked into /usr/local
Could not symlink lib/libzstd.a
Target /usr/local/lib/libzstd.a
is a symlink belonging to zstd. You can unlink it:
  brew unlink zstd
```
It seems to conflict with `zstd`, but also `depends_on "zstd"`? Not really sure how to fix this.

**Comment by nmoinvaz** [comment]
It appears to be looking for the libzstd.a in the source directory, but I have changed some things, I can easily change that particular part back.

**Comment by carlocab** [comment]
Thanks for looking at it.

I'm not sure that's the problem. The problem is that it's found a `libzstd.a` in the install directory, which it wants to symlink into `/usr/local/lib`. However, it can't do that, because there is already a `/usr/local/lib/libzstd.a` (from zstd) so it doesn't know what to do.

**Comment by carlocab** [comment]
Is the `libzstd.a` just a duplicate of the library that comes with zstd?

If it is I can just delete it and I think the build will proceed just fine.

**Comment by nmoinvaz** [comment]
If it can't find libzstd on the machine it will clone the zstd repository and build it, so it is the build zstd library.

**Comment by carlocab** [comment]
Ah, I see. Ok. I'll have to look at helping it find the existing zstd library then. Any tips on this would be appreciated, but I imagine I'll figure it out eventually.

**Comment by nmoinvaz** [comment]
It might be possible to add the BINARY_DIR to the FetchContent_Declare calls in the CMakeLists.txt. It looks like Homebrew is just looking for the file in a particular directory when it goes to package it up.

**Comment by carlocab** [comment]
It looks like you have cmake set up to use pkg-config to look for libraries. I'll make pkg-config available to the build environment and see if that helps.

**Comment by carlocab** [comment]
Ok, the `zstd` problem was fixed in the last test run. But it seems to have failed the test. I'm guessing that's because it's also rolled its own untested lzma library.

I've provided a tested lzma library as a dependency, so that should hopefully fix things.

Thanks again for the assist, @nmoinvaz.

**Comment by carlocab** [comment]
@chenrui333 build failure should be fixed now.

**Comment by nmoinvaz** [comment]
I agree, it only does that when it does not find the the library installed on the system. It can also be disabled through `-DZSTD_FORCE_FETCH=OFF` but it is on by default.

**Comment by carlocab** [comment]
It seems to be off by default here:

https://github.com/nmoinvaz/minizip/blob/318e848843667f982f81dbcb72334e415ba482a5/CMakeLists.txt#L34

It even looks like it does the opposite of what the name suggests (though the description does match). It's also not documented.

This behaviour has prevented two version bumps here at Homebrew: https://github.com/Homebrew/homebrew-core/pull/64762, https://github.com/Homebrew/homebrew-core/pull/63653

It would be useful for package managers like Homebrew if there were an option to turn off all fetching behaviour. If this option were the default, even better.

Apologies for the litany of complaints: I don't have a lot of experience with your fork of minizip but it seems like you've done great work with it. Just thought the feedback could be useful for when you think of things to improve.

**Review by chenrui333 — APPROVED** [review]
nice work!

**Comment by nmoinvaz** [comment]
@carlocab if you can create an issue in minizip project then when I am working on it again next I can take a look. Thanks.

**Pull request closed without merging**
