### PR TITLE
postgresql@9.4 9.4.25

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
13:29:06 Data page checksums are disabled.
13:29:06 
13:29:06 creating directory /private/tmp/postgresql@9.4-test-20191114-40939-18n1phd/test ... ok
13:29:06 creating subdirectories ... ok
13:29:06 selecting default max_connections ... 10
13:29:06 selecting default shared_buffers ... 400kB
13:29:06 selecting default timezone ... Europe/London
13:29:06 selecting dynamic shared memory implementation ... posix
13:29:06 creating configuration files ... ok
13:29:06 creating template1 database in /private/tmp/postgresql@9.4-test-20191114-40939-18n1phd/test/base/1 ... FATAL:  could not create shared memory segment: No space left on device
13:29:06 DETAIL:  Failed system call was shmget(key=5432003, size=56, 03600).
13:29:06 HINT:  This error does *not* mean that you have run out of disk space.  It occurs either if all available shared memory IDs have been taken, in which case you need to raise the SHMMNI parameter in your kernel, or because the system's overall limit for shared memory has been reached.
13:29:06 	The PostgreSQL documentation contains more information about shared memory configuration.
13:29:06 child process exited with exit code 1

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by Bo98** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
Thanks @Bo98!!

**Pull request closed without merging**
