### PR TITLE
WIP: switch emscripten backend to llvm

### PR DESCRIPTION
**Pull request by igas**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by igas** [comment]
@kripken I kicked off, but not sure I understand the whole build process. resource blocks is just download them. later we put them to the paths under workdir (emscripten-core/emscripten) https://github.com/Homebrew/homebrew-core/blob/ef7aa9b36cc3b47eab9576996dae2b56c61ffe2f/Formula/emscripten.rb#L82-L83. From here I'm not really sure how it's built as I'm not familiar with either python to understand built script or cmake :(

If there are approximate list of shell commands I can translate it to brew.

**Comment by chrmoritz** [comment]
Something you are definitely missing here is the `recursedeps = [ 'v8' ]` at the end of the `DEPS` file, which means that you would need to also include all the deps from `v8`'s `DEPS` file for that specific commit (basically at least the stuff we have in the `v8` formula too relative to the `v8` dir).

But I'm not sure if all these deps are actually required at runtime or if it might be possible to just use a normal dep on our homebrew formula form them, instead of building them from source with a `resource`.

**Comment by kripken** [comment]
Correct @chrmoritz, fastcomp is only needed for the old backend. Yes, in general you just need builds of llvm and binaryen. And also there is a dependency on node.js and python. (Optionally Java for closure compiler too.)

I wonder, btw, if it's possible to wrap around the emsdk for this? Getting the latest emsdk and running
```
emsdk install $VERSION-upstream
emsdk activate $VERSION-upstream
```
will get everything from our build infrastructure, and store it in under that directory. Then you can just use llvm, binaryen, emcc, etc. from there. That seems simple, and also those builds are what is constantly tested by us, and we have full mac, linux etc. support. Is brew wrapping around the emsdk like that an option?

**Comment by chrmoritz** [comment]
> I wonder, btw, if it's possible to wrap around the emsdk for this? Getting the latest emsdk and running

I think this wouldn't be possible in homebrew, because it installs precompiled binaries, which isn't acceptable for a core formula.

@igas I've also tried to make it working and here is my progress so far: https://github.com/chrmoritz/homebrew-core/commit/7cff243566dc423bdaabe5d9c03f7e9a640ef3bd. Not sure what `llvm` args are actuall needed because we only need the `host;WebAssembly` targets and these are more or less copied from the normal `llvm` formula so far.

**Comment by igas** [comment]
@chrmoritz I'm happy for you to take over this as it's not my area of expertise at all 😅  closest thing to the compiled languages I worked with was erlang ^_^

**Comment by chrmoritz** [comment]
I'm not so familiar with all the `llvm` stuff either. Especially I don't know the reasoning behind all these cmake arguments in the `llvm` formula. That's why the args used in [my attempt](https://github.com/chrmoritz/homebrew-core/commit/7cff243566dc423bdaabe5d9c03f7e9a640ef3bd) were more or less a mix between the ones [used in upstream's `build.py`](https://github.com/WebAssembly/waterfall/blob/master/src/build.py#L802-L817) and striped down version of the one we have in our formula (we need only 2 targets: `host;WebAssembly` here).

But except figuring out the best args passed to `llvm`'s cmake and actually carefully testing this, it should already somehow work that way.

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by openingnow** [comment]
Is this PR still active? I want to make a commit solving https://github.com/Homebrew/homebrew-core/issues/47869 but it looks like handling formula will make conflict.

**Comment by openingnow** [comment]
> I think this wouldn't be possible in homebrew, because it installs precompiled binaries, which isn't acceptable for a core formula.

What about providing emsdk formula instead emscripten and then make user to install emscripten, like [haskell-stack](https://github.com/Homebrew/homebrew-core/blob/master/Formula/haskell-stack.rb) do?

**Comment by chrmoritz** [comment]
> What about providing emsdk formula instead emscripten and then make user to install emscripten, like [haskell-stack](https://github.com/Homebrew/homebrew-core/blob/master/Formula/haskell-stack.rb) do?

Why not building a minimal `llvm` and `binaryen` from source in the formula for their specific revisions corresponding to the `emscripten` release. I mean the current version of the formula is also building `fastcomp` from source, so we could do the same thing for the new dependencies.

If you want you could take over where I stopped in https://github.com/chrmoritz/homebrew-core/commit/7cff243566dc423bdaabe5d9c03f7e9a640ef3bd (but you will still have to improve the args passed to `llvm` a bit I think).

**Pull request closed without merging**
