### PR TITLE
pre-commit 2.1.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> FAILED
Testing pre-commit
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200225-37593-l07ju1.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb --verbose
==> git init
Initialized empty Git repository in /private/tmp/pre-commit-test-20200225-37594-3e9at4/.git/
==> /usr/local/Cellar/pre-commit/2.1.1/bin/pre-commit install
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/2.1.1/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/pre-commit/2.1.1/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/pre-commit/2.1.1/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (PyYAML 3.13b1 (/usr/local/Cellar/pre-commit/2.1.1/libexec/lib/python3.8/site-packages), Requirement.parse('pyyaml>=5.1'), {'pre-commit'})

During handling of the above exception, another exception occurred:
```

**Comment by chenrui333** [comment]
previous attempt, https://github.com/Homebrew/homebrew-core/pull/50407

**Comment by chenrui333** [comment]
```
==> brew test pre-commit --verbose
==> FAILED
Testing pre-commit
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200225-14554-zyjvkn.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb --verbose
==> git init
Initialized empty Git repository in /private/tmp/pre-commit-test-20200225-14555-n0xkhs/.git/
==> /usr/local/Cellar/pre-commit/2.1.1/bin/pre-commit install
pre-commit installed at .git/hooks/pre-commit
==> git add f
==> /usr/local/Homebrew/Library/Homebrew/shims/scm/git commit -m test
env: python3.8: No such file or directory
Error: pre-commit: failed
Failed executing:
```

**Comment by samford** [comment]
This worked for me when I installed it from source and tested it locally (macOS 10.15.3). I wonder what the problem is with `python@3.8` here on CI.

**Comment by chenrui333** [comment]
Give another try (did not make any change).

It works for my Catalina machine.

**Comment by chenrui333** [comment]
<details>
<summary>Test failure</summary>

```
00:11:27 ==> brew test pre-commit --verbose
00:11:32 ==> FAILED
00:11:32 Testing pre-commit
00:11:32 /usr/bin/sandbox-exec -f /private/tmp/homebrew20200308-3590-ghrt7o.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pre-commit.rb --verbose
00:11:32 ==> git init
00:11:32 Initialized empty Git repository in /private/tmp/pre-commit-test-20200308-3591-18u4tdn/.git/
00:11:32 ==> /usr/local/Cellar/pre-commit/2.1.1/bin/pre-commit install
00:11:32 pre-commit installed at .git/hooks/pre-commit
00:11:32 ==> git add f
00:11:32 ==> /usr/local/Homebrew/Library/Homebrew/shims/scm/git commit -m test
00:11:32 env: python3.8: No such file or directory
00:11:32 Error: pre-commit: failed
00:11:32 Failed executing:
16:22:25 <7>.
```

</details>

**Comment by chenrui333** [comment]
Looks like there is no python@3.8 installed on Mojave and HighSierra?

**Comment by SMillerDev** [comment]
Not unless a formula depends on it.

**Comment by Bo98** [comment]
When invoked, pre-commit writes a git hook script. This script has `/usr/bin/env python3.8` which doesn't work because python@3.8 is keg only.

Arguably, it's always been wrong since this formula was migrated to `python@3.8`, except before it used `/usr/bin/env python` which probably picked up system Python 2.

The line can be found [here](https://github.com/pre-commit/pre-commit/blob/v2.1.1/pre_commit/commands/install_uninstall.py#L73). I don't see any way to change that beyond an `inreplace` to make it point to `Formula["python@3.8"].opt_bin/"python3"`.

Giving inreplacing is now what we're going to be doing more often for shebangs (ableit wrapped behind a new `Language::Python.rewrite_python_shebang`), that's probably what we should do here.

**Comment by chenrui333** [comment]
> env: python3.7: No such file or directory

**Comment by Bo98** [comment]
Should be good now.

**Pull request closed without merging**
