### PR TITLE
python: fix enable optimizations when build

### PR DESCRIPTION
**Pull request by jnozsc**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

idea:  https://redd.it/6i8dn7
stackoverflow topic: https://stackoverflow.com/questions/41405728/

### CODE REVIEW

**Comment by jnozsc** [comment]
Aborted by user ilovezfs ???

**Comment by ilovezfs** [comment]
Yes this will timeout on CI since it will likely increase python and python3 build times each by like 30 minutes, plus the time for the reverse dependency tests.

**Comment by ilovezfs** [comment]
It looks like this isn't actually kicking in. Running `brew install python -dvs`

```
checking for --enable-optimizations... no
```

Are you seeing "yes"?

**Comment by jnozsc** [comment]
when I run 
```
brew install --build-from-source python -dvs
```
, I get 
```
for --enable-optimizations... no
```

but I get
```
for --with-lto... yes
```


after the installation, I run 
```
import sysconfig
a = sysconfig.get_config_vars()
for k in a.keys():
    print k, a[k]
```

i get 

```
CONFIG_ARGS '--prefix=/usr/local/opt/python' '--enable-ipv6' '--datarootdir=/usr/local/opt/python/share' '--datadir=/usr/local/opt/python/share' '--enable-framework=/usr/local/opt/python/Frameworks' '--without-ensurepip' '--with-lto' '--enable-optimizations' '--without-gcc' 'MACOSX_DEPLOYMENT_TARGET=10.13' 'CC=clang' 'PKG_CONFIG_PATH=/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13'
```

it seems at least `'--with-lto'` works?

there are some conversational topic in python's issue tracker
https://bugs.python.org/issue29243

it seems `-enable-optimizations.` stilling being unstable, but  `'--with-lto'`  should work well.

**Comment by jnozsc** [comment]
this PR builder tests forever, I get your point. I choose to close this PR.

**Pull request closed without merging**
