### PR TITLE
duck 8.1.1

### PR DESCRIPTION
**Pull request by dkocher**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

The built artifact fails to launch with a stacktrace 

```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x18bb259b8 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x18bb5915c pthread_kill + 288
2   libsystem_c.dylib             	       0x18ba96314 abort + 164
3   libjvm.dylib                  	       0x106ed002c os::abort(bool, void*, void const*) + 56
4   libjvm.dylib                  	       0x10710e168 VMError::report_and_die(int, char const*, char const*, char*, Thread*, unsigned char*, void*, void*, char const*, int, unsigned long) + 2684
5   libjvm.dylib                  	       0x10710d6e0 VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*, char const*, ...) + 72
6   libjvm.dylib                  	       0x10710e2b0 VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*) + 36
7   libjvm.dylib                  	       0x106febbe0 JVM_handle_bsd_signal + 420
8   libsystem_platform.dylib      	       0x18bb704e4 _sigtramp + 56
9   libjimage.dylib               	       0x104395c14 ZipDecompressor::decompress_resource(unsigned char*, unsigned char*, ResourceHeader*, ImageStrings const*) + 40
10  libjimage.dylib               	       0x104395b9c ImageDecompressor::decompress_resource(unsigned char*, unsigned char*, unsigned long long, ImageStrings const*, Endian*) + 292
11  libjimage.dylib               	       0x1043967dc ImageFileReader::get_resource(ImageLocation&, unsigned char*) const + 256
12  libjimage.dylib               	       0x10439763c ImageFileReader::get_resource(unsigned int, unsigned char*) const + 132
13  libjimage.dylib               	       0x1043977f4 JIMAGE_GetResource + 20
14  libjvm.dylib                  	       0x106960e9c ClassPathImageEntry::open_stream_for_loader(JavaThread*, char const*, ClassLoaderData*) + 276
15  libjvm.dylib                  	       0x106963de8 ClassLoader::load_class(Symbol*, bool, JavaThread*) + 284
16  libjvm.dylib                  	       0x10706f6f0 SystemDictionary::load_instance_class_impl(Symbol*, Handle, JavaThread*) + 720
17  libjvm.dylib                  	       0x10706dfdc SystemDictionary::load_instance_class(unsigned int, Symbol*, Handle, JavaThread*) + 48
18  libjvm.dylib                  	       0x10706d6e8 SystemDictionary::resolve_instance_class_or_null(Symbol*, Handle, Handle, JavaThread*) + 1244
19  libjvm.dylib                  	       0x10706ccd4 SystemDictionary::resolve_or_fail(Symbol*, Handle, Handle, bool, JavaThread*) + 128
20  libjvm.dylib                  	       0x10710a5b8 vmClasses::resolve_all(JavaThread*) + 344
21  libjvm.dylib                  	       0x1070703a0 SystemDictionary::initialize(JavaThread*) + 204
22  libjvm.dylib                  	       0x1070ca1d8 Universe::genesis(JavaThread*) + 168
23  libjvm.dylib                  	       0x1070ccddc universe2_init() + 36
24  libjvm.dylib                  	       0x106b53484 init_globals() + 88
25  libjvm.dylib                  	       0x1070a3760 Threads::create_vm(JavaVMInitArgs*, bool*) + 940
26  libjvm.dylib                  	       0x106bee888 JNI_CreateJavaVM + 120
27  libjli.dylib                  	       0x1043acaa8 JavaMain + 260
28  libjli.dylib                  	       0x1043af958 __JVMInit_block_invoke + 80
29  Foundation                    	       0x18cadc600 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
30  Foundation                    	       0x18cadc4a8 -[NSBlockOperation main] + 104
31  Foundation                    	       0x18cadc438 __NSOPERATION_IS_INVOKING_MAIN__ + 24
32  Foundation                    	       0x18cadb67c -[NSOperation start] + 804
33  Foundation                    	       0x18cb1caa4 __NSThreadPerformPerform + 212
34  CoreFoundation                	       0x18bc24bbc __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
35  CoreFoundation                	       0x18bc24b08 __CFRunLoopDoSource0 + 208
36  CoreFoundation                	       0x18bc247f4 __CFRunLoopDoSources0 + 268
37  CoreFoundation                	       0x18bc23168 __CFRunLoopRun + 820
38  CoreFoundation                	       0x18bc22694 CFRunLoopRunSpecific + 600
39  libjli.dylib                  	       0x1043aefec CreateExecutionEnvironment + 400
40  libjli.dylib                  	       0x1043ab1fc JLI_Launch + 1184
41  duck                          	       0x104187940 launch + 2284
42  duck                          	       0x104186f9c main + 68
43  dyld                          	       0x1044410f4 start + 520
```

I suspect a code signing issue. The crash is inside the runtime environment we are bundling which has been updated to a build of OpenJDK 17. 

*Note*: Running `duck` from the build output prior installing with Homebrew does not crash. I tested this by removing the `libexec.install` phase and keeping the built source using `--keep-tmp`.

```
 /private/tmp/duck-20211128-99304-1gschx9/cli/osx/target/duck.bundle/Contents/MacOS/duck 
Missing required option: [--upload Upload file or folder recursively, -d Download file or folder. Denote a folder with a trailing '/', --copy Copy between servers, -l List files in remote folder, -L Long list format with modification date and permission mask, -D Delete, -c Make directory, --synchronize Synchronize folders, --edit Edit file in external editor, --purge Invalidate file in CDN, -V Show version number and quit., -h Print this help]
Try 'duck --help' for more options.
```

Any educated guesses what might be wrong are welcome. Replacing the ad-hoc code signature on the installed bundle did not seem to make a difference.

### CODE REVIEW

**Comment by carlocab** [comment]
@fxcoudert and @Bo98 might know something about codesigning weirdness here.

**Comment by fxcoudert** [comment]
> I suspect a code signing issue

What makes you think that? The stack trace does not look like a signature issue.

```
6   libjvm.dylib                  	       0x10710e2b0 VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*) + 36
7   libjvm.dylib                  	       0x106febbe0 JVM_handle_bsd_signal + 420
8   libsystem_platform.dylib      	       0x18bb704e4 _sigtramp + 56
9   libjimage.dylib               	       0x104395c14 ZipDecompressor::decompress_resource(unsigned char*, unsigned char*, ResourceHeader*, ImageStrings const*) + 40
10  libjimage.dylib               	       0x104395b9c ImageDecompressor::decompress_resource(unsigned char*, unsigned char*, unsigned long long, ImageStrings const*, Endian*) + 292
11  libjimage.dylib               	       0x1043967dc ImageFileReader::get_resource(ImageLocation&, unsigned char*) const + 256
12  libjimage.dylib               	       0x10439763c ImageFileReader::get_resource(unsigned int, unsigned char*) const + 132
13  libjimage.dylib               	       0x1043977f4 JIMAGE_GetResource + 20
```

Looks like `ZipDecompressor` is emitting an error or signal that isn't handled, and leads to failure. Maybe it's not finding the underlying zlib function? https://github.com/openjdk/jdk17/blob/master/src/java.base/share/native/libjimage/imageDecompressor.cpp

**Comment by carlocab** [comment]
Agreed re the stacktrace, but not sure why the binary works inside the build tree. Misrelocation would've been my guess, but that shouldn't affect being able to find system Zlib.

**Comment by Bo98** [comment]
Just to take one step back here, is it even using Homebrew's OpenJDK?

```
  duck:
    * Unexpected universal binaries were found.
      The offending files are:
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/Frameworks/libcore.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/Frameworks/librococoa.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/MacOS/duck
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libattach.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libdt_socket.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libextnet.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libfontmanager.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libfreetype.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libinstrument.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libj2gss.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libj2pcsc.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libj2pkcs11.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libjaas.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libjava.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libjavajpeg.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libjawt.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libjdwp.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libjimage.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libjli.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libjsig.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libjsound.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/liblcms.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libmanagement.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libmanagement_agent.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libmanagement_ext.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libmlib_image.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libnet.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libnio.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libosx.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libosxapp.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libosxkrb5.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libosxsecurity.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libosxui.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libprefs.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/librmi.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libsaproc.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libsplashscreen.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libsyslookup.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libverify.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/libzip.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/server/libjsig.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/Home/lib/server/libjvm.dylib
        /usr/local/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns/Runtime.jre/Contents/MacOS/libjli.dylib
  Error: 1 problem in 1 formula detected
```

Ignoring the copying of dylibs for a moment (not ideal since we already have OpenJDK as a runtime dependency but I understand this is sometimes necessary), we don't ship universal libraries for OpenJDK so is this some prebuilt OpenJDK from elsewhere?

**Comment by dkocher** [comment]
The embedded runtime is a custom build of OpenJDK that has both arm64 and x86_64 slices. One could drop this and use the Homebrew installed instead. I have verified this works by symlinking.

```
silverbullet:PlugIns dkocher$ pwd
/opt/homebrew/Cellar/duck/8.1.0.36410/libexec/Contents/PlugIns
silverbullet:PlugIns dkocher$ ll
total 0
drwxr-xr-x  3 dkocher  admin   96 Nov 29 21:15 ./
drwxr-xr-x  7 dkocher  admin  224 Nov 29 21:12 ../
lrwxr-xr-x  1 dkocher  admin   50 Nov 29 21:15 Runtime.jre@ -> ../../../../../openjdk/17.0.1/libexec/openjdk.jdk/
```

**Comment by dkocher** [comment]
I would still be interested in the cause of the error as we see this with our [custom tap that installs from the binary release](https://github.com/iterate-ch/homebrew-cyberduck/blob/master/duck.rb) as well.

**Comment by Bo98** [comment]
What I'm getting at is do we see the same crash with Homebrew's OpenJDK as well?

**Comment by dkocher** [comment]
> What I'm getting at is do we see the same crash with Homebrew's OpenJDK as well?

No, it does not crash.

**Comment by dkocher** [comment]
@Bo98 Kind ping for review.

**Comment by Bo98** [comment]
This looks much better - thanks! Glad we're building more things from source here!

> I would still be interested in the cause of the error as we see this with our [custom tap that installs from the binary release](https://github.com/iterate-ch/homebrew-cyberduck/blob/master/duck.rb) as well.

This is possibly a bug with the prebuilt you were using. A starting point might be to identify how that JDK was built and how it differs from the way we build it.

**Review by Bo98 — APPROVED** [review]

**Comment by dkocher** [comment]
It looks like no ARM bottle has been built despite cfc6a1085dba57e47ce8deb5b287352b7b7c0c31. Is there anything left to do from my side?

```
silverbullet:~ dkocher$ brew install duck
Error: duck: no bottle available!
```

**Comment by carlocab** [comment]
The ARM build succeeded, but the test failed so the bottle wasn't published. See https://github.com/Homebrew/homebrew-core/runs/4488613446?check_suite_focus=true#step:6:39.

If the failure isn't spurious we can fix the test and that should get a bottle published.

**Comment by dkocher** [comment]
> The ARM build succeeded, but the test failed so the bottle wasn't published. See https://github.com/Homebrew/homebrew-core/runs/4488613446?check_suite_focus=true#step:6:39.
> 
> If the failure isn't spurious we can fix the test and that should get a bottle published.

Thanks for the fast reply. I cannot seem to reproduce this locally

```
🍺  /opt/homebrew/Cellar/duck/8.1.1.36550: 838 files, 64.8MB, built in 1 minute 35 seconds
==> Running `brew cleanup duck`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
silverbullet:Formula dkocher$ brew test duck
==> Testing duck
==> /opt/homebrew/Cellar/duck/8.1.1.36550/bin/duck --download https://ftp.gnu.org/gnu/wget/wget-1.19.4.tar.gz /private/tmp/duck-test-20211217-44750-8syj66/test
silverbullet:Formula dkocher$ arch
arm64
```

**Pull request closed without merging**
