### PR TITLE
appscale-tools 3.8.1

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks may require updates.

Previous attempt: https://github.com/Homebrew/homebrew-core/pull/67230

### CODE REVIEW

**Comment by carlocab** [comment]
```
pkg_resources.DistributionNotFound: The 'keyrings.alt<3.2,>=3.1' distribution was not found and is required by appscale-agents
```

**Comment by bayandin** [comment]
> ```
> pkg_resources.DistributionNotFound: The 'keyrings.alt<3.2,>=3.1' distribution was not found and is required by appscale-agents
> ```

That is interesting.

In fails with exactly the same error as before, but it works on my Mojave installation
```
$ brew config
HOMEBREW_VERSION: 3.0.4-18-g3e69c2b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3e69c2b77b53d0e3a16eaa4aedb7cf72002eed78
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f0654b1b4474bb8c23373d1c882b939c7ca2847a
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dual-core 64-bit kabylake
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
```

**Comment by bayandin** [comment]
Even more interesting.
If we install `setuptools` first, then the test fails with the same error on all macOS versions (not only on Mojave as it was before).
So, I guess, let's try to install it last

**Comment by bayandin** [comment]
I run out of ideas for now.

What I've found. `keyrings.alt` doesn't exist in 10.14 bottles, along with some other packages:

```
$ diff <(ls -1a ./appscale-tools-10.14/3.8.1/libexec/vendor/lib/python2.7/site-packages/) <(ls -1a ./appscale-tools-10.15/3.8.1/libexec/vendor/lib/python2.7/site-packages/)
8d7
< UNKNOWN-0.0.0-py2.7.egg-info
71a71,72
> configparser-4.0.2-py2.7.egg-info
> configparser.py
73a75
> dateutil
96a99,102
> keyring
> keyring-18.0.1-py2.7.egg-info
> keyrings
> keyrings.alt-3.1.1-py2.7.egg-info
116a123
> python_dateutil-2.8.1-py2.7.egg-info
```

Logs for installing keyring/keyrings.alt:
```
2021-03-04 00:03:48 +0000

python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor
--install-scripts=/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/bin
--single-version-externally-managed
--record=installed.txt

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
running install
running build
running install_egg_info
running egg_info
creating UNKNOWN.egg-info
writing UNKNOWN.egg-info/PKG-INFO
writing top-level names to UNKNOWN.egg-info/top_level.txt
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
warning: manifest_maker: standard file '-c' not found

reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
removing '/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info' (and everything under it)
Copying UNKNOWN.egg-info to /usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info
running install_scripts
writing list of installed files to 'installed.txt'
```

for configparser:
```
2021-03-04 00:03:22 +0000

python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor
--install-scripts=/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/bin
--single-version-externally-managed
--record=installed.txt

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/backports
copying src/backports/__init__.py -> build/lib/backports
creating build/lib/backports/configparser
copying src/backports/configparser/__init__.py -> build/lib/backports/configparser
copying src/backports/configparser/helpers.py -> build/lib/backports/configparser
running install_lib
creating /usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/backports
copying build/lib/backports/__init__.py -> /usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/backports
creating /usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/backports/configparser
copying build/lib/backports/configparser/__init__.py -> /usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/backports/configparser
copying build/lib/backports/configparser/helpers.py -> /usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/backports/configparser
byte-compiling /usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/backports/__init__.py to __init__.pyc
byte-compiling /usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/backports/configparser/__init__.py to __init__.pyc
byte-compiling /usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/backports/configparser/helpers.py to helpers.pyc
running install_egg_info
running egg_info
creating src/UNKNOWN.egg-info
writing src/UNKNOWN.egg-info/PKG-INFO
writing top-level names to src/UNKNOWN.egg-info/top_level.txt
writing dependency_links to src/UNKNOWN.egg-info/dependency_links.txt
writing manifest file 'src/UNKNOWN.egg-info/SOURCES.txt'
warning: manifest_maker: standard file '-c' not found

reading manifest file 'src/UNKNOWN.egg-info/SOURCES.txt'
writing manifest file 'src/UNKNOWN.egg-info/SOURCES.txt'
Copying src/UNKNOWN.egg-info to /usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info
running install_scripts
writing list of installed files to 'installed.txt'
```

for `dateutil`:
```
2021-03-04 00:03:59 +0000

python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor
--install-scripts=/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/bin
--single-version-externally-managed
--record=installed.txt

setup.py:20: UserWarning: python_requires requires setuptools version > 24.3
  UserWarning)
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
running install
running build
running install_egg_info
running egg_info
creating UNKNOWN.egg-info
writing UNKNOWN.egg-info/PKG-INFO
writing top-level names to UNKNOWN.egg-info/top_level.txt
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
warning: manifest_maker: standard file '-c' not found

reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
removing '/usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info' (and everything under it)
Copying UNKNOWN.egg-info to /usr/local/Cellar/appscale-tools/3.8.1/libexec/vendor/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg-info
running install_scripts
writing list of installed files to 'installed.txt'
```


Warning `Unknown distribution option: 'use_scm_version'` appears only for these missing packages, maybe it worth to check it

**Pull request closed without merging**
