### PR TITLE
neovim 0.9.4

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Review by p-linnane — CHANGES_REQUESTED** [review]
Please check the resources. Looks like a few have updated versions.

**Comment by clason** [comment]
Which ones? The treesitter parsers are not bumped for 0.9.4.

**Comment by SMillerDev** [comment]
How about mpack?

**Comment by clason** [comment]
Oh, I forgot you insist on not using the vendored mpack (which is vendored already in 0.9.x). Fine.

**Review by SMillerDev — APPROVED** [review]
Thanks @clason  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by bpb** [comment]
Neovim is pretty broken on Sonoma without this update being available.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
