### PR TITLE
Added devcontainer configuration

### PR DESCRIPTION
**Pull request by okineadev**
This configuration is based on the configuration from https://github.com/Homebrew/brew - https://github.com/Homebrew/brew/tree/master/.devcontainer

### CODE REVIEW

**Review by issyl0 — COMMENTED** [review]
Personally I'm 👎 on this without a clearly articulated need from >1 person for a devcontainer in this repo.

**Comment by p-linnane** [comment]
This repo is already tapped in the devcontainer in `brew`. I don't see a need to maintain a separate one.

**Comment by carlocab** [comment]
A devcontainer here would make this easier:

Screenshot 2024-05-12 at 11 33 27 PM

**Comment by chenrui333** [comment]
honestly, you dont need this, you just need setup action and tmate (more easy to manage)

see, some examples in here, https://github.com/chenrui333/github-action-test/blob/main/.github/workflows/brew-debug.yml

**Comment by okineadev** [comment]
What are you talking about??

I've added a `devcontainer.json` to get this project up and running with **brew pre-installed** so you can **quickly** add a formula and **test** it!

Also to edit documentation with linter and get error/warning hints or when editing bash scripts (`on-create-command.sh`)

I hope now it became clear why this **PR**

**Comment by okineadev** [comment]
> This repo is already tapped in the devcontainer in `brew`. I don't see a need to maintain a separate one.

Alternatively, we can add a `.vscode/extensions.json` file with recommended extensions to work with this repository

**Comment by chenrui333** [comment]
you should be able to test anything in your local as well as recommended ways using something like this, https://github.com/chenrui333/github-action-test/blob/main/.github/workflows/brew-debug.yml.

**Pull request closed without merging**
