### PR TITLE
openssl@1.1 1.1.0g

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
:confetti_ball:

**Comment by alex** [comment]
powerdns failing, but no clue if it's related to this.

**Comment by ilovezfs** [comment]
@alex not related. It's just a bug introduced by 2df84736f94.

**Comment by alex** [comment]
thanks!

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by alex** [comment]
And we're green!

**Comment by ilovezfs** [comment]
Yup just waiting on https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/12128/downstreambuildview/

**Comment by ilovezfs** [comment]
Thanks again @alex! :lock:

**Comment by alex** [comment]
Thank you!

**Comment by reaperhulk** [comment]
Awesomely quick, ❤️ homebrew

**Pull request closed without merging**
