### PR TITLE
monero: depend on readline and use vendored unbound

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

use tag instead of tarball so that the submodules are fetched
remove unbound dependency

CC @jtgrassie

### CODE REVIEW

**Comment by jtgrassie** [comment]
Any way you can not hard-code the release tag and search for the latest tagged release instead? It would save editing this file every 6 months. 

Other changes look ok.

**Comment by ilovezfs** [comment]
>Any way you can not hard-code the release tag and search for the latest tagged release instead? It would save editing this file every 6 months.

No, for security, we have to use either source tarball + sha256 of the tarball or tag + Git commit of the tag. That means that if the tarball or the tag is altered, the build will fail and we can contact upstream to find out if there was a breach.

**Comment by jtgrassie** [comment]
> or tag + Git commit of the tag

That's what I'm suggesting except get the latest release tag without hardcoding `v0.12.0.0`. E.g. something like `git fetch --tags && git tag | sed 's/v0\.//g' | sort -n | tail -1` to get the most recent tag.

**Comment by ilovezfs** [comment]
That wouldn't be able to detect a change in the tag's commit if the tag gets force pushed.

**Comment by ilovezfs** [comment]
Then `brew info` would not know what version `monero` is unless `monero` were already installed unless we separately hard coded the version string. Also, it would still end up using whatever Git commit was currently associated with the lastest in the upstream repository regardless of whether it had been altered (i.e. if v0.12.0.0 is pointing to something other than c29890c2c03f7f24aa4970b3ebbfe2dbb95b24eb) but for security the install must fail if you retag v0.12.0.0 until we find out what happened.

**Comment by ilovezfs** [comment]
@jtgrassie I've opened https://github.com/monero-project/monero/issues/3822 regarding the unbound thing.

**Pull request closed without merging**
