### PR TITLE
mongodb 4.0.4

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> install (30 days)
Index | Name (with options)                                  |  Count |  Percent
-----:|------------------------------------------------------|-------:|--------:
1     | mongodb                                              | 51,895 |   99.97%
2     | mongodb --with-sasl                                  |      8 |    0.02%
3     | MongoDB                                              |      3 |    0.01%
4     | mongodb --with-boost                                 |      1 |    0.00%
5     | mongodb --with-boost --with-sasl                     |      1 |    0.00%
Total |                                                      | 51,908 |  100.00%
```

Do we use this opportunity to kill all options? They're really never used

**Comment by javian** [comment]
@fxcoudert sounds like a plan - the website is also mongodb.com

**Comment by fxcoudert** [comment]
At some point we'll also have to migrate this to Python 3…

**Comment by jorgegarciadev** [comment]
I don't know if this is the right place to ask this or I should open a new issue but... Seems that the mongo shell included in this formula doesn't support SSL Could a flag be included to install it with SSL support?

**Comment by SMillerDev** [comment]
It should support SSL through OpenSSL since that's still in the requirements. If this is not the case can you make a pull request that enables SSL by default? Homebrew is trying to get rid of options since they're never tested.

**Pull request closed without merging**
