### PR TITLE
rawtoaces: revision bump for libraw

### PR DESCRIPTION
**Pull request by niheaven**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
I guess this was because a dependency was updated? If that's the case, could you try and add a test here that would fail in that particular case?

**Comment by niheaven** [comment]
I only use libraw and follow @Moisan's request (https://github.com/Homebrew/homebrew-core/pull/35997#issuecomment-454234533) to add a revision bump here... Maybe I'll test if it would fail with the current bottle and latest build of libraw later.

**Comment by SMillerDev** [comment]
right, I didn't see that pull request yet. Usually revision bumps are done in the same branch in a new commit to keep it in the same pull request, otherwise the test bot goes crazy. Could you close this PR and add the commit to the other one you made?

**Comment by fxcoudert** [comment]
Closing here, as the revision bump should happen in the other PR.

**Pull request closed without merging**
