### PR TITLE
openjdk@8 1.8.0+275

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jonchang** [comment]
Well, the openjdk mercurial server is down, so hopefully we didn't cause that.

**Comment by fxcoudert** [comment]
```
curl: (22) The requested URL returned error: 502 Bad Gateway
Error: Failed to download resource "openjdk@8--corba"
Download failed: https://hg.openjdk.java.net/jdk8u/jdk8u/corba/archive/jdk8u275-ga.tar.bz2
```

**Comment by jonchang** [comment]
Using the Redhat site for tarballs of versioned checkouts. It's linked from their mailing list so it's probably OK. https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-November/012965.html

**Comment by jonchang** [comment]
sdk 11 ref: https://github.com/apple/openjdk/commit/9eaae342d122cc15c90fef45f6bb9bc6543a0f5b

**Comment by fxcoudert** [comment]
```
Making signal interposition lib...
Making SA debugger back-end...
/private/tmp/openjdk@8-20201116-78585-ifmtn7/jdk8u275-ga/hotspot/agent/src/os/bsd/MacosxDebuggerLocal.m:27:9: fatal error: 'JavaNativeFoundation/JavaNativeFoundation.h' file not found
#import <JavaNativeFoundation/JavaNativeFoundation.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[6]: *** [libsaproc.dylib] Error 1
```

**Comment by jonchang** [comment]
Yeah some parts of the Java build system are picking up the 11 SDK. Haven't tracked them all down yet.

**Comment by jonchang** [comment]
Need to fix tests for:

brew test --retry --verbose couchdb-lucene
brew test --retry --verbose voldemort

**Pull request closed without merging**
