### PR TITLE
fish: fix build path

### LINKED ISSUE #10139: Upgraded to version 3.6.4 and now all my configuration is broken
version: `fish, version 3.6.4`
uname: `Darwin amirraminfar-macbookpro.roam.internal 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64`

I recently updated via `brew upgrade` from `3.6.1` to `3.6.4`. In the process, I can't figure out what happened but all my fishshell is broken. My `PATH` is reset. Commands like `psub` do not work.  I have a custom location for homebrew at `/Users/amirraminfar/homebrew/bin`. 

When creating a new tab,  I see a terminal which looks like this: 
Screenshot 2023-12-05 at 1 07 44 PM

```
cat /etc/shells
# List of acceptable shells for chpass(1).
# Ftpd will not allow users to connect who are not using
# one of these shells.

/bin/bash
/bin/csh
/bin/dash
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh
/usr/local/bin/fish
/Users/amirraminfar/homebrew/bin/fish
```

Fish is in my `shells` file.  and `echo $SHELL` prints `/Users/amirraminfar/homebrew/bin/fish`. 

But I am clueless to why everything seems broken. `starship` seems to not load. I get multiple errors.  When I do `set --export PATH /Users/amirraminfar/homebrew/bin $PATH` I can at least get some of my binary files back. 

I have tried doing `brew rm fish` and `install` again. No luck. It feels like none of my configuration files are being loaded.

Is there a way to investigate what might actually be broken?

### PR DESCRIPTION
**Pull request by razvanazamfirei**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This hopefully fixes https://github.com/fish-shell/fish-shell/issues/10139

### CODE REVIEW

**Comment by cho-m** [comment]
We need to use `HOMEBREW_PREFIX` paths so that `fish` can work with other formulae.

`fish` bottle should have only been installed if using standard prefix:
https://github.com/Homebrew/homebrew-core/blob/c9a7acd4734c086ce285bfb01a7809acad8f3589/Formula/f/fish.rb#L13

May need additional info on how the installation was done in case `brew` somehow bypassed this constraint.

**Comment by razvanazamfirei** [comment]
Closing this. I had a similar issue, albeit with the official prefix. It was a `$PATH`/ `$fish_function_path` configuration issue that surfaced with the update.

**Comment by SteffenDE** [comment]
> `fish` bottle should have only been installed if using standard prefix:
> May need additional info on how the installation/upgrade was done in case `brew` somehow bypassed this constraint.

Seems like this happened to me. I have a non-default brew prefix and after updating fish it installed the bottled version which breaks. After reinstalling using `brew reinstall -s fish`, fish works again.

**Comment by Bo98** [comment]
Looks like `pour_bottle?` might not be supported in the API. Will get this fixed.

**Pull request closed without merging**
