### PR TITLE
imath 3.1.7

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Review by carlocab — DISMISSED** [review]

**Comment by ZhongRuoyu** [comment]
https://github.com/Homebrew/homebrew-core/pull/118902

```
Error: You are trying to merge a pull request that conflicts with a long running build in:
{
  "Homebrew/homebrew-core/pull/118902": [
    "Formula/ctl.rb",
    "Formula/gdal.rb",
    "Formula/gmic.rb",
    "Formula/imagemagick.rb"
  ]
}
```

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
time="2023-03-02T19:42:21Z" level=fatal msg="writing blob: Patch \"[https://ghcr.io/v2/homebrew/core/ctl/blobs/upload/0a5af6b4-5c68-406c-ba1e-e156219049b4\](https://ghcr.io/v2/homebrew/core/ctl/blobs/upload/0a5af6b4-5c68-406c-ba1e-e156219049b4/)": EOF"
Error: Failure while executing; `/usr/bin/env /usr/bin/skopeo copy --all oci:ctl--1.5.2_9 docker://ghcr.io/homebrew/core/ctl:1.5.2_9 --dest-creds=brewtestbot:******` exited with 1. Here's the output:
```

**Comment by chenrui333** [comment]
https://www.githubstatus.com/incidents/qfby3shb6r3w

**Comment by chenrui333** [comment]
same `bazarr` test failure

**Comment by chenrui333** [comment]
need some help merging this PR.

**Comment by chenrui333** [comment]
cc @Homebrew/core @Homebrew/tsc

**Comment by fxcoudert** [comment]
```
Error: docker://ghcr.io/homebrew/core/opencv:4.7.0_2 already exists!
```

Published [3 days ago](https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Fopencv). We need a better mechanism to make sure things don't break mid-published.

For now, how about skipping one revision?

**Comment by carlocab** [comment]
Are the bottles built here the same as the ones on GH packages?

**Comment by SMillerDev** [comment]
> For now, how about skipping one revision?

I think the audit wil complain about that 😢

**Comment by MikeMcQuaid** [comment]
> I think the audit wil complain about that 😢

We can ignore that if we need to as a one-off. We need to not get into the habit of such things, though.

Let's discuss the more general stuff in https://github.com/Homebrew/homebrew-test-bot/issues/880.

**Review by carlocab — APPROVED** [review]
Let's move this along.

**Pull request merged**
