### PR TITLE
libvirt 8.0.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
  ERROR: Unhandled python exception
  
      This is a Meson bug and should be reported!
```

**Comment by dawidd6** [comment]
`FICLONE` is not defined on Linux. This commit might be responsible for the error: 
https://gitlab.com/libvirt/libvirt/-/commit/59d21d2c2e7bc24f848cdc750b0151087e94bafe

**Comment by iMichka** [comment]
Might need newer linux headers. I'll add a new formula for that: #95177

**Comment by iMichka** [comment]
Got the Linux build green.

macOS is failing with:
```
2022-02-16T20:31:25.6364990Z Traceback (most recent call last):
2022-02-16T20:31:25.6366000Z   File "/usr/local/Cellar/meson/0.61.2/libexec/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 146, in run
2022-02-16T20:31:25.6366280Z     return options.run_func(options)
2022-02-16T20:31:25.6366950Z   File "/usr/local/Cellar/meson/0.61.2/libexec/lib/python3.10/site-packages/mesonbuild/minstall.py", line 811, in run
2022-02-16T20:31:25.6367080Z     installer.do_install(datafilename)
2022-02-16T20:31:25.6367520Z   File "/usr/local/Cellar/meson/0.61.2/libexec/lib/python3.10/site-packages/mesonbuild/minstall.py", line 588, in do_install
2022-02-16T20:31:25.6367680Z     self.install_headers(d, dm, destdir, fullprefix)
2022-02-16T20:31:25.6368120Z   File "/usr/local/Cellar/meson/0.61.2/libexec/lib/python3.10/site-packages/mesonbuild/minstall.py", line 673, in install_headers
2022-02-16T20:31:25.6368300Z     if self.do_copyfile(fullfilename, outfilename, makedirs=(dm, outdir)):
2022-02-16T20:31:25.6368990Z   File "/usr/local/Cellar/meson/0.61.2/libexec/lib/python3.10/site-packages/mesonbuild/minstall.py", line 446, in do_copyfile
2022-02-16T20:31:25.6369190Z     dirmaker.makedirs(outdir, exist_ok=True)
2022-02-16T20:31:25.6369650Z   File "/usr/local/Cellar/meson/0.61.2/libexec/lib/python3.10/site-packages/mesonbuild/minstall.py", line 112, in makedirs
2022-02-16T20:31:25.6369790Z     self.makedirs_impl(path, exist_ok=exist_ok)
2022-02-16T20:31:25.6370210Z   File "/usr/local/Cellar/meson/0.61.2/libexec/lib/python3.10/site-packages/mesonbuild/minstall.py", line 345, in makedirs
2022-02-16T20:31:25.6370320Z     os.makedirs(*args, **kwargs)
2022-02-16T20:31:25.6370550Z   File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 225, in makedirs
2022-02-16T20:31:25.6370650Z     mkdir(name, mode)
2022-02-16T20:31:25.6371020Z PermissionError: [Errno 1] Operation not permitted: '/usr/local/Cellar/yajl/2.1.0/include/libvirt'
```

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
