### PR TITLE
snort: add license

### PR DESCRIPTION
**Pull request by chenrui333**
relates to #59340

---

> This program is free software; you can redistribute it and/or modify
> it under the terms of the GNU General Public License as published by
> the Free Software Foundation; either version 2 of the License, or
> (at your option) any later version.

In the `COPYING` file of the artifact.

cc @Rylan12 @dawidd6

### CODE REVIEW

**Comment by chenrui333** [comment]
maybe we need to have our own mirror, but the mirror in the formula does work though.

```
==> Installing 'bundler' gem
Error: 1 problem in 1 formula detected
snort:
  * Stable: The URL https://www.snort.org/downloads/snort/snort-2.9.16.tar.gz is not reachable (HTTP status code 404)
```

aside from that, the `CI-syntax` seems not get picked up.

**Comment by SeekingMeaning** [comment]
Have to add `CI-syntax-only` label when you create the PR

**Comment by chenrui333** [comment]
> Have to add `CI-syntax-only` label when you're creating the PR

make sense.

**Comment by Rylan12** [comment]
Doesn't this indicate the opposite?

```
SNORT is an open source project that is governed exclusively by the GPL V2
and any third party desiring to use, modify or distribute SNORT must do so by
strictly following the terms and conditions of GPL V2. Anyone using, modifying
or distributing SNORT does not have the option to chose to use, modify or
distribute SNORT under any revised or new version of the GPL, including
without limitation, the GNU General Public License Version 3.

For ease of reference, the comparable notice that is used with SNORT
(contained in the 'README' file) is as follows:

"This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License Version 2 as published by the Free
Software Foundation. You may not use, modify or distribute this program under
any other version of the GNU General Public License."
```

I think what you're seeing is the explanation of what the options were for the authors when choosing a license (the options being `GPL-2.0-only` or `GPL-2.0-or-later`) but the rest of the `COPYING` file indicates that they went with `GPL-2.0-only`.

**Comment by chenrui333** [comment]
>  but the rest of the COPYING file indicates that they went with GPL-2.0-only.

What does it mean? Based on readings, I think it is still `GPL-2.0-or-later`. We need another person to do the double. I am going to drop them a email to ask about this.

**Comment by chenrui333** [comment]
> Doesn't this indicate the opposite?
> 
> ```
> SNORT is an open source project that is governed exclusively by the GPL V2
> and any third party desiring to use, modify or distribute SNORT must do so by
> strictly following the terms and conditions of GPL V2. Anyone using, modifying
> or distributing SNORT does not have the option to chose to use, modify or
> distribute SNORT under any revised or new version of the GPL, including
> without limitation, the GNU General Public License Version 3.
> 
> For ease of reference, the comparable notice that is used with SNORT
> (contained in the 'README' file) is as follows:
> 
> "This program is free software; you can redistribute it and/or modify it under
> the terms of the GNU General Public License Version 2 as published by the Free
> Software Foundation. You may not use, modify or distribute this program under
> any other version of the GNU General Public License."
> ```
> 
> I think what you're seeing is the explanation of what the options were for the authors when choosing a license (the options being `GPL-2.0-only` or `GPL-2.0-or-later`) but the rest of the `COPYING` file indicates that they went with `GPL-2.0-only`.

I think this is the similar situation with the other PR that how I interpreted the `-or-later` reference.

**Comment by gromgit** [comment]
I agree with @Rylan12: The passage he quoted clearly states that strict GPL 2.0 applies.

The current confusion seems to stem from the preamble to that passage, which says that GPL 2.0 (not the licensor) allows _the user_ to apply the terms of 2.0 or any later GPL version to the software if:
1. no GPL version was specified, or
1. the licensor (i.e. the Snort folks) explicitly states "or later"

Clearly, neither condition is met in this case, and the subsequent passage takes the option away from the user regardless.

**Comment by chenrui333** [comment]
I think you guys are right, correcting my license change now.

**Review by Rylan12 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @Rylan12!!

**Pull request merged**
