### PR TITLE
qt 5.15.1 pyside 5.15.1

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
See https://github.com/Homebrew/homebrew-core/issues/58225#issuecomment-662699868 for a discussion regarding the licence.

I have confirmed that the `patch do` block is still required, as the changes are not included in the source files.

**Comment by miccal** [comment]
Oh bother, the second mirror was not picked up -- fixing now.

**Comment by miccal** [comment]
The only failure for the first run was a linkage for `pyside`.

I have now added a license for `qt`, and revision-bumped and added license for `pyside`.

**Comment by miccal** [comment]
`pyside` now updated to 5.15.1.

**Comment by miccal** [comment]
All done 😎

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
