### PR TITLE
revisions for tuntap removal

### PR DESCRIPTION
**Pull request by ilovezfs**
See discussion in https://github.com/Homebrew/homebrew-core/pull/3101

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @AnastasiaSulyagina @DomT4 @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
👍 but let's hold off merging this until we figured out why the migration didn't happen on these.

**Comment by DomT4** [comment]
Migration didn't happen? I thought the point of this PR was largely that we can't claim to actually have tested these formulae using Mavericks/An updated `tuntap` now, so keeping bottles around was disingenuous, per the conversation in https://github.com/Homebrew/homebrew-core/pull/3101. Particularly since CI will keep attempting to pour previously built bottles but now has no way of testing them.

Am I missing a puzzle piece about the migration here?

**Comment by ilovezfs** [comment]
@DomT4 well I'd think in general we'd want these revisions to be part of the PR moving something from homebrew/pqr caskroom/xyz, no?

**Comment by DomT4** [comment]
Sure, in general, except we've already killed off `tuntap` so we'd be waiting forever here?

**Comment by ilovezfs** [comment]
@DomT4 Right. I think @MikeMcQuaid just wants to clarify exactly what the procedure here is. For example, should this PR be recursive? It's missing anything that uses one of these formulae but didn't declare a tuntap dependency explicitly.

Also it should be mandatory to have CI support fulfillment of Cask dependencies and requirements that are satisfied by a default in Cask. For formulae where that's not actually possible at this time,  I think any of them that have a non-optional dependency on something in Cask that cannot be installed no longer belong in homebrew/core, just as we do not support any formulae with non-optional x11 requirements or non-optional cross-tap dependencies in homebrew/core.

So I'm not convinced this PR is even correct.  I think these formulae (as well as any that have a non-optional dependency on them recursively) need to be moved to the boneyard, to a homebrew/cask-dependent-limbo, or to caskroom/xyz tap unless their tuntap requirement can be reasonably made optional without compromising the usefulness of the software or until we find a way to install the tuntap cask during CI.

**Comment by DomT4** [comment]
> Also it should be mandatory to have CI support fulfillment of Cask dependencies and requirements that are satisfied by a default in Cask. 

At least in `tuntap`'s case this requires root privileges to install, which is frankly dangerous to make programmatic on boxes which aren't disposable & are used for build after build after build. The user our CI runs on is deliberately privilege-limited to somewhat curtail that issue.

At least in `fuse` we've been using Travis to handle this problem, with the understanding whilst we can't build bottles for the formulae they can be completely built & tested by Travis CI. It also doesn't matter about executing `sudo` programatically there because if we accidentally trash the box, not a big deal due to how Travis is set up.

We could keep a `tuntap` permanently installed on the boxes like we do an up-to-date Java or X11, but Mike has previously made objection noises when people have suggested as much; I can understand where Mike is coming from on the objection.

> I think any of them that have a non-optional dependency on something in Cask that cannot be installed no longer belong in homebrew/core, just as we do not support any formulae with non-optional x11 requirements 

I somewhat agree, but if someone suggest a `homebrew/tuntap` tap & doesn't want to volunteer to maintain it forever themselves I'm going to throw them in a dungeon at this point. Our tap structure has mostly allowed maintainers to cherry pick the work they want to do, which is fine, but severely degrades UX.

**Comment by ilovezfs** [comment]
>We could keep a tuntap permanently installed on the boxes like we do an up-to-date Java or X11, but Mike has previously made objection noises when people have suggested as much; I can understand where Mike is coming from on the objection.

I would pitch a rather unpleasant fit if we did that as it's a totally unacceptable idea unless it were a separate physical box or it was a vm, container, etc.

**Comment by ilovezfs** [comment]
>I somewhat agree, but if someone suggest a homebrew/tuntap tap & doesn't want to volunteer to maintain it forever themselves I'm going to throw them in a dungeon at this point.

I agree. I think these all belong in the boneyard. If someone is able to get any or all of them admitted into a cask at some later date, that's lovely but not our concern.

**Comment by DomT4** [comment]
> I think these all belong in the boneyard.

Well, `openvpn` doesn't actually use `:tuntap` on Yosemite or above, which soon will be all of Homebrew's bottled Mac versions 😉.

**Comment by ilovezfs** [comment]
By these all, I mean whichever fit the criteria described above. For openvpn setting a minimum 10.10 requirement is fine.

**Comment by ilovezfs** [comment]
@MikeMcQuaid @DomT4 PR refreshed.

**Comment by ilovezfs** [comment]
@MikeMcQuaid reading over https://github.com/caskroom/homebrew-cask/issues/15603 and https://github.com/Homebrew/homebrew-core/pull/2075 it seems reverse dependencies have just not been discussed at all.

For instance, graphviz is currently slated for cask (according to the table), and has the following first-order reverse dependencies: bokken, eralchemy, fobis, ford, gammaray, gprof2dot, makefile2graph, plantuml, simgrid, xdot, homebrew/php/mondrian, homebrew/science/pnapi. But whether or not any/all/none of them are compatible with the Cask version has not entered the conversation.

**Comment by DomT4** [comment]
@ilovezfs We've (Well, I've) already shot down `graphviz` becoming a Cask only in https://github.com/Homebrew/homebrew-core/issues/2260 for pretty much that reason. I'm sure it's perfectly possible to develop against the upstream `.pkg` but I think doing so for us is asking for chaos given we'd never know if something needed rebuilding for compatibility, etc.

**Comment by ilovezfs** [comment]
@DomT4 I see. I suppose the table should be updated? It still says
```
graphviz.rb 	cask 	GUI
```

**Comment by DomT4** [comment]
The discussion has become kind of fragmented so I'm not sure what is getting updated where at this point, but aye, ideally.

**Comment by AnastasiaSulyagina** [comment]
I haven't seen #2260 till now. Will update

**Comment by DomT4** [comment]
Thanks @AnastasiaSulyagina.

**Comment by ilovezfs** [comment]
@MikeMcQuaid any thoughts on shipping this?

**Comment by MikeMcQuaid** [comment]
@ilovezfs Seems fine. Ideally we'll figure out a way to autoinstall casks in these cases but I think we're probably a bit off that point now.

**Comment by kim0** [comment]
Hi folks, 

As a user of some of the VPN apps that are being now moved into "boneyard" .. Can someone explain what is going on? Why this sudden move, and can I help get those VPN utils back?

Thanks

**Comment by ilovezfs** [comment]
@kim0 you can `brew tap homebrew/boneyard`.

**Comment by MikeMcQuaid** [comment]
@kim0 In short: we can no longer build tuntap from source and use it on modern versions of OS X so it doesn't make sense to keep around formulae that are unbuildable and untestable.

**Pull request closed without merging**
