### PR TITLE
libplist 2.3.0

### PR DESCRIPTION
**Pull request by TheRealKeto**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Looking through all previous pull requests, I've managed to solve all issues relating to `libplist` and its newest verison. `libirecovery` is not handled here, as I believe it should be handled in a new pull request (which was actually resolved by a  [closed PR](https://github.com/Homebrew/homebrew-core/pull/130966), [can it be reopened?](https://github.com/Homebrew/homebrew-core/pull/130886)). 

Should it be handled here instead, please let me know.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
brew linkage --test ideviceinstaller
brew test --retry --verbose ideviceinstaller
```

**Comment by TheRealKeto** [comment]
@chenrui333 Updated missed packages. Some CI jobs were skipped, not sure why.

**Comment by TheRealKeto** [comment]
@p-linnane Mind reviewing this?

**Review by p-linnane — COMMENTED** [review]
Any references to `--disable-dependency-tracking` or `--prefix=#{prefix}` should be removed and replaced with `*std_configure_args`.

Additionally, don't we still want to run `./configure` even when building from `HEAD`?

**Comment by TheRealKeto** [comment]
> Additionally, don't we still want to run ./configure even when building from HEAD?

`./autogen.sh` automatically runs `./configure` once it generates all files. This is only applicable to libimobiledevice projects, as evident by [this line example](https://github.com/libimobiledevice/libplist/blob/master/autogen.sh#L24-L26).

**Comment by p-linnane** [comment]
`--disable-silent-rules` is not part of `*std_configure_args`, so that will need to be added back where necessary. Once that and the style issue are addresses this should be good to merge.

**Review by p-linnane — APPROVED** [review]
Thanks for all the great work here!

**Comment by TheRealKeto** [comment]
The bot seemed to have ran into issues. Should I resolve the merge conflicts manually?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@TheRealKeto, thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/issues/139929

**Pull request merged**
