### PR TITLE
ruby@2.7 2.7.4

### PR DESCRIPTION
**Pull request by swrobel**
Created with `brew bump-formula-pr`.

includes rubygems 3.2.22

### CODE REVIEW

**Comment by carlocab** [comment]
Can we update `rubygems` to 3.2.22?

**Comment by swrobel** [comment]
> Can we update `rubygems` to 3.2.22?

Done!

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @swrobel!

**Comment by swrobel** [comment]
@carlocab any idea why it's using rubygems 3.2.21 even though I thought I properly included 3.2.22?

```
$ gem -v
3.2.21

$ which gem
/usr/local/Cellar/ruby@2.7/2.7.4/bin/gem

$ ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin20]

$ which ruby
/usr/local/Cellar/ruby@2.7/2.7.4/bin/ruby
```

**Pull request closed without merging**
