### PR TITLE
deno 1.25.0

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by cho-m** [comment]
`[v8 0.49.0] thread 'main' panicked at 'Path doesn't exist: "/private/tmp/deno-20220825-7243-1k3tgc0/deno/target/release/gn_out/../../../../../../../Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/v8-0.49.0/v8/tools/builtins-pgo/x64.profile"', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/v8-0.49.0/build.rs:713:5`

**Comment by carlocab** [comment]
Getting rid of the `..`s that path should be
```
/Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/v8-0.49.0/v8/tools/builtins-pgo/x64.profile
```
Not sure why that file's gone missing. Usually errors like this are due to some type of race condition, but we've already deparallelised the build, so...

**Comment by cho-m** [comment]
May be due to upstream not packaging those files inside `v8` crate, but their build script currently expects them to be available.

If the `rusty_v8` repo CI gets code via git when building librusty and then `deno` repo CI uses it, then I think upstream CI would not catch issue of missing files in crate.

---

https://github.com/denoland/v8/tree/1f7df8c39451f3d53e9acef4b7b0476cf4f5eb66/tools/builtins-pgo

**Comment by branchvincent** [comment]
@aslilac sorry to ping you, but since you've been helpful is there a chance you could look into this?

**Comment by aslilac** [comment]
sure!

**Comment by branchvincent** [comment]
I've patched the `v8` crate with the missing path from https://github.com/denoland/v8/tree/1f7df8c39451f3d53e9acef4b7b0476cf4f5eb66/tools/builtins-pgo

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
