### PR TITLE
duo_unix 1.11.5

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
I wasn't sure about the license so I checked what debian does. This is [quite a lot of licenses](https://metadata.ftp-master.debian.org/changelogs//main/d/duo-unix/duo-unix_1.11.3-1_copyright).

**Comment by SMillerDev** [comment]
I'd say `:cannot_represent`

**Comment by chenrui333** [comment]
The project is with `GPL-2+ with OpenSSL exception` along with many third party licenses. 

> Files: *
Copyright: 2010 Duo Security
License: GPL-2+ with OpenSSL exception

**Comment by chenrui333** [comment]
relates to `https://github.com/spdx/license-list-XML/issues/1356` (regarding openssl exception)

**Comment by chenrui333** [comment]
maybe we can pick up the license update in the next PR?

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
