### PR TITLE
maven: provide head location

### PR DESCRIPTION
**Pull request by mthmulders**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This pull request provides the HEAD version of Maven. It does so by inspecting Jenkins, our build server, and fetching the built package from the last succesful build.

There's a couple of things I'm unsure of, and where I'm seeking your advice:

* the formula has some audit errors (they were there before I started), I'm not sure if/how I could resolve them
* I'm not really happy with the code block. I had to do a lot of reformatting before it fitted into 10 lines, but ideally I'd write it a bit more verbose so it would be more clear. I don't know how to extract those methods out of the `Formula` class, though.
* In general, I'm not sure it's supposed to be done this way.

Any help or guidance would be appreciated!

### CODE REVIEW

**Comment by SMillerDev** [comment]
Yeah, this is basically a custom implementation of the `devel` block that used to exist. `HEAD` is really just meant to be for specifying a repo to pull from and I'd be against this addition.

**Comment by mthmulders** [comment]
> `HEAD` is really just meant to be for specifying a repo to pull from and I'd be against this addition.

Is there an alternative to achieve this? E.g. without checking out [the source code of Maven](https://github.com/apache/maven) and having the user do a full build (which requires Maven itself, by the way)?

**Comment by SMillerDev** [comment]
> Is there an alternative to achieve this? E.g. without checking out [the source code of Maven](https://github.com/apache/maven) and having the user do a full build (which requires Maven itself, by the way)?

No, that's not the kind of configuration homebrew supports. But you can keep nightly versions in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by mthmulders** [comment]
> But you can keep nightly versions in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

Funny, I started this day by thinking I needed a tap (I actually [started working on it already](github.com/mthmulders/homebrew-maven-snapshot/)) until I found out about `head`, and figured that'd be the nicer approach.

If I understand you correctly, the idea of such a tap would be to update it after each successful build, by pointing the `maven-snapshot` formula to the latest built packages? So our Jenkins build should push a change to the tap?

**Comment by SMillerDev** [comment]
Yeah, for taps you have full control over the behavior so you can make it automatically update if you want.

**Comment by mthmulders** [comment]
Thanks for the suggestions, I will (re-)explore that route.

**Pull request closed without merging**
