### PR TITLE
folly fizz wangle watchman 2021.07.20.00

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Continuation of #80732

### CODE REVIEW

**Comment by cho-m** [comment]
Exact same build failure on `watchman` for the last few attempts:
```make
/tmp/watchman-20210721-66877-1t2kvqe/watchman-2021.07.20.00/watchman/watchman_string.h:114:16: error: no member named 'data' in 'watchman_pending_fs'
      : s_(str.data()), e_(str.data() + str.size()) {}
           ~~~ ^
```

I am curious if upstream has CI running for these releases to see if it actually has been passing. The upstream releases used to include a macOS zip, but now only have a Linux zip.

**Comment by carlocab** [comment]
We can try to skip watchman, but I'm wary of trying to upgrade `folly` to a version where I know `watchman` won't build. We've already done that, but I'm not sure that's a sign that we can/should do it again. (Think of crossing the street without looking both ways...)

**Comment by carlocab** [comment]
We really need to be able to rebuild `watchman` unfortunately:
```
==> /opt/homebrew/Cellar/watchman/2021.06.07.00/bin/watchman -v
dyld: Symbol not found: __ZN5folly15SharedMutexImplILb0EvNSt3__16atomicELb0ELb0ELb0EE10ReadHolderD2Ev
  Referenced from: /opt/homebrew/Cellar/watchman/2021.06.07.00/bin/watchman
  Expected in: /opt/homebrew/opt/folly/lib/libfolly.0.58.0-dev.dylib
 in /opt/homebrew/Cellar/watchman/2021.06.07.00/bin/watchman
```

**Comment by cho-m** [comment]
I guess either need to fix up `watchman` or temporarily lock in `folly` dependency to older version, which successfully built

**Comment by carlocab** [comment]
We could try to fix it. No response from upstream on the issue I opened though (facebook/watchman#930), so we may have to dig into the code a bit for this.

**Pull request closed without merging**
