### PR TITLE
Updated the CGAL formula to version 4.10

### PR DESCRIPTION
**Pull request by the-null-void**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by the-null-void** [comment]
The audit fails with the message:
  * Dependency boost should not use option c++11
  * Dependency gmp should not use option c++11
Are these new requirements?  The previous formula used the cxx11 option.  The formulae for both boost and gmp still seem to have that option.

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/pull/14053.

Unfortunately this cannot be merged until https://github.com/Oslandia/SFCGAL/issues/142 is resolved.

Thanks for the PR nonetheless.

>Are these new requirements? The previous formula used the cxx11 option. The formulae for both boost and gmp still seem to have that option.

Yes. https://github.com/Homebrew/brew/pull/2482

**Comment by the-null-void** [comment]
Ah, thanks.  I must have missed that existing issue.

**Comment by ilovezfs** [comment]
@the-null-void yeah, I closed my PR a while ago because it doesn't look like the sfcgal compatibility is coming any time soon, but I've pinged upstream again: https://github.com/Oslandia/SFCGAL/issues/142#issuecomment-313845159

**Pull request closed without merging**
