### PR TITLE
Bulk import from homebrew/versions (6/7)

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Import formulae from homebrew/versions. Those that fail to build will likely be killed.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@MikeMcQuaid shouldn't it be ruby@1.8 and ruby@1.9?

**Comment by ilovezfs** [comment]
and I guess redis@1.3 not redis@1.310?

**Comment by ilovezfs** [comment]
or even redis@1?

**Comment by MikeMcQuaid** [comment]
Fixed Ruby. Rebar is happening in https://github.com/Homebrew/homebrew-core/pull/10815 and Redis in https://github.com/Homebrew/homebrew-core/pull/10559

**Pull request closed without merging**
