### PR TITLE
elixir-ls 0.14.5

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>Hotfix release fixing mix crash</pre>
</details>

### CODE REVIEW

**Comment by leonqadirie** [comment]
There is [0.14.2](https://github.com/elixir-lsp/elixir-ls/releases/tag/v0.14.2) out now.
Not sure about the test failure, though.

**Comment by chenrui333** [comment]
Still the same test failure:

```
  {"jsonrpc":"2.0","method":"window/logMessage","params":{"message":"Could not find Hex, which is needed to build dependency false","type":4}}Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] Content-Length: 408

```

**Comment by chenrui333** [comment]
relates to https://github.com/elixir-lsp/elixir-ls/commit/7f7ba8ac7ad518945f7622369d13c16f48568b30

**Comment by chenrui333** [comment]
Should be good now.

**Review by SMillerDev — DISMISSED** [review]

**Pull request merged**
