### PR TITLE
alluxio 2.0.1

### PR DESCRIPTION
**Pull request by apc999**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> /usr/local/Cellar/alluxio/2.0.1/bin/alluxio version
Error: Alluxio requires Java 8, currently Java 12.0.1 found.
```

**Comment by fxcoudert** [comment]
@apc999 can you check what are the requirements on Java version?

**Comment by equal-l2** [comment]
Relevant issue: https://github.com/Alluxio/alluxio/issues/9856

**Comment by fxcoudert** [comment]
Closing due to lack of activity

**Pull request closed without merging**
