### PR TITLE
mpv, ffmpeg: add some removed options as dependencies

### PR DESCRIPTION
**Pull request by deus0ww**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Based on what? Why those options and not others?

**Comment by deus0ww** [comment]
I'm ok with adding all the previous options as hard dependencies if that's what it takes to un-!@#$ my build.

**Comment by fxcoudert** [comment]
Please give context.

**Comment by SMillerDev** [comment]
Dependencies shouldn't be added to "un-!@#$ my build" but because there's a distinct advantage to all homebrew users weighed against the implications of pulling in extra dependencies imho.

**Comment by deus0ww** [comment]
Context: I'm using MPV and FFmpeg on my HTPC. Why these options are important:

FFmpeg:
 - AOM - I need AV1 support (for files or youtube-dl)
 - soxr - Higher quality audio sample rate conversion
 - rubberband - Higher quality audio speed change (this one is less important than the rest)

MPV:
 - uchardet - Support for non-UTF-8 international subtitles (like Thai, which I use).
 - libarchive - So I can open files in archives without extracting

**Comment by fxcoudert** [comment]
From what I can see, `libarchive`, `uchardet`, `libsoxr` and `aom` have low disk cost. `rubberband` has recursive dependencies, though.

**Comment by deus0ww** [comment]
Can I get a verdict on this? I'm not asking for when but if the PR will be accepted. In the short-term, I'll create a tap. However, if there's no interest at all, I might as well start looking for more permanent alternative solutions now.

**Comment by SMillerDev** [comment]
Can you squash everything into one commit, `ffmpeg: add libarchive, uchardet, libsoxr and aom as dependencies`

**Comment by deus0ww** [comment]
This is my first time doing a squash. Is the result what you're looking for?

**Comment by deus0ww** [comment]
Thank you. My git skill is sorely lacking.

**Comment by zmwangx** [comment]
Please add back `fdk-aac`. AAC is one of the (two) most widely audio codecs and fdk-aac was the de facto standard of AAC encoding with FFmpeg for years (see https://trac.ffmpeg.org/wiki/Encode/AAC, also search for AAC on https://ffmpeg.org/index.html#news). FFmpeg's builtin AAC encoder only moved out of experimental stage in December 2015, and fdk-aac is still the go-to for HE-AAC. Removing fdk-aac breaks a hell lot of encoding/transcoding scripts.

**Comment by zmwangx** [comment]
By the way, I'm toying with the idea to start a separate org to host more advanced formulae and keep options alive. If there are similar-minded past maintainer / power users out there, feel free to ping me (email's on my profile).

**Comment by mlindner** [comment]
fxcoudert Please don't remove options from mpv. Your previous commit here is BAD! https://github.com/Homebrew/homebrew-core/commit/1fdd9b152760e9d743964dd955c1ae816a3ca191

Please don't remove working options just to suit your personal fantasies.

**Comment by mlindner** [comment]
This pull request doesn't go far enough. Please revert all the changes in https://github.com/Homebrew/homebrew-core/commit/1fdd9b152760e9d743964dd955c1ae816a3ca191 as well please.

**Comment by SMillerDev** [comment]
@mlindner please read the code of conduct. This isn't the issue for this and #31510 has the explanation you are looking for.

**Comment by mlindner** [comment]
@SMillerDev That's not a satisfactory answer. Homebrew has been making many bad decisions like this of late.

**Comment by mlindner** [comment]
@MikeMcQuaid Made an unfortunate decision.

**Comment by SMillerDev** [comment]
You're more than welcome to maintain your own tap where you can decide what the direction is. Please stop hijacking threads because you have a complaint though.

**Comment by mlindner** [comment]
@SMillerDev Bifurcating the entire community is a great response. /s If I maintain a tap then I am now off of mainline. I don't want to maintain a tap, I just want compiler flags to be able to be passed through.

**Comment by deus0ww** [comment]
@mlindner Read #31510 and various other threads about the options removal.  You will come to realize that it's pointless to try to reverse this.  In the short-term, I've created a tap here: https://github.com/deus0ww/homebrew-tap.  You're welcome to use it.  Note that 'HEAD' for mpv and libass are pointing to my forks.

**Comment by MikeMcQuaid** [comment]
> Please add back `fdk-aac`

This should definitely not be added back (see also: `openssl`). From the formula before this was removed: 

```ruby
# These librares are GPL-incompatible, and require ffmpeg be built with
# the "--enable-nonfree" flag, which produces unredistributable libraries
args << "--enable-nonfree" if build.with?("fdk-aac") || build.with?("openssl")
```

We cannot legally distribute bottles with FDK AAC so we will not do so.

**Comment by zmwangx** [comment]
> > Please add back `fdk-aac`
> 
> This should definitely not be added back (see also: `openssl`). From the formula before this was removed:
> 
> ```ruby
> # These librares are GPL-incompatible, and require ffmpeg be built with
> # the "--enable-nonfree" flag, which produces unredistributable libraries
> args << "--enable-nonfree" if build.with?("fdk-aac") || build.with?("openssl")
> ```
> 
> We cannot legally distribute bottles with FDK AAC so we will not do so.

Yes, I realized that soon after posting the comment, but forgot to edit it. Which is why options need to be kept alive, somewhere.

**Comment by JuPlutonic** [comment]
About openssl. We need something to handle (e.g. in **mpv**) https-addresses/SSL protocol.
I recommend to put in dependencies gnutls *GNU Transport Layer Security (TLS) Library*.
But it up to you...
**PS**  New ffmpeg sources uses coremedia corevideo corefoundation libraries - bad for Linuxbrew..,
            smth bad with --enable-videotoolbox.
**on mpv** In linuxbrew we use 1) meson and ninja to make binaries from sources
2) llibnfs and libupnp, do Mac users need them to play mpd remotely? idk.

**Comment by MikeMcQuaid** [comment]
> I recommend to put in dependencies **gnutls** _GNU Transport Layer Security (TLS) Library_.
> But it up to you...

If we can do this without `--enable-nonfree` it seems like a good idea. Could you submit a pull request @JuPlutonic?

**Comment by retokromer** [comment]
>PPS Fraunhofer?! Remembered epopee with their MP3 codec licence

I don’t guess that Fraunhofer is a problem. Today the FFmpeg’s own AAC encoder is excellent. More problematic is OpenSSL, because – to my knowledge – it’s widely used.

**Comment by JuPlutonic** [comment]
> > I recommend to put in dependencies **gnutls** _GNU Transport Layer Security (TLS) Library_.
> > But it up to you...
> 
> If we can do this without `--enable-nonfree` it seems like a good idea. Could you submit a pull request @JuPlutonic?

Yes, #36650

**Comment by deus0ww** [comment]
Are there reasons why #36663 and #36730 got merged and this one did not? I should note that  #36730, which includes dep to rubberband, ballooned the dependencies tree way more than this PR.

**Comment by SMillerDev** [comment]
conflicts and failing tests would be the main reason I assume.

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by deus0ww** [comment]
@SMillerDev It doesn't help that ffmpeg.rb keeps getting changed from other PR's and the revolving conflicts on github doesn't appear to be working without causing build failure.

**Comment by MikeMcQuaid** [comment]
Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @deus0ww!

Sorry for the delay! This reproduced an issue with our CI system that I had to fix before this could be merged (https://github.com/Homebrew/homebrew-test-bot/issues/231). I also wanted to help resolve the merge conflicts for you and split your commits to one-per-formula (our preferred approach).

**Comment by deus0ww** [comment]
No problem and thank you for merging this.  Sorry about the mess with git (I'm sure some of the blame is with me and not just that bug with the CI... my git-fu is weak).

**Comment by MikeMcQuaid** [comment]
@deus0ww You're very welcome! ❤️

**Pull request closed without merging**
