### PR TITLE
freeswitch: fix for Xcode 14.3

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This should allow us to build this on Ventura after #118902.

### CODE REVIEW

**Comment by Bo98** [comment]
Can you paste the error in this PR for future reference?

**Comment by carlocab** [comment]
For reference, complete logs: [freeswitch.tar.gz](https://github.com/Homebrew/homebrew-core/files/11322720/freeswitch.tar.gz)

**Comment by Bo98** [comment]
asprintf.c defines `_XOPEN_SOURCE`. I'm not sure how it worked on previous Xcodes to be honest.

We could try `-D_DARWIN_C_SOURCE` here too.

**Comment by Bo98** [comment]
I'm guessing something evaluated `sys/cdefs.h` earlier but now doesn't. Include orders change all the time.

**Review by p-linnane — APPROVED** [review]

**Comment by carlocab** [comment]
Reported upstream at signalwire/freeswitch#2064.

**Pull request merged**
