### PR TITLE
kibana 6.5.0

### PR DESCRIPTION
**Pull request by DPattee**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chrmoritz** [comment]
```
==> yarn build --oss --release --skip-os-packages --skip-archives
yarn run v1.12.3
$ node scripts/build --all-platforms --oss --release --skip-os-packages --skip-archives
Error: ENOENT: no such file or directory, open '/private/tmp/kibana-20181119-89730-1q91iyp/x-pack/tsconfig.json'
```
Looks like they have unfortunately broken the OSS only build for `kibana` now.

BTW: This PR would need an Alias update too.

**Comment by DPattee** [comment]
Hmm, I added the alias after brew audit mentioned it during the first run, I'll take a look

**Comment by DPattee** [comment]
Whoops, I didn't expect a new build to be auto started here when I saved my changed to my branch...

**Review by Moisan — APPROVED** [review]

**Comment by Moisan** [comment]
Thank you @DPattee and @chrmoritz!

**Pull request closed without merging**
