### PR TITLE
haproxy 1.9.4

### PR DESCRIPTION
**Pull request by tommyang**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Build failure on all three macOS versions:

```
src/ssl_sock.c:337:1: error: argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and section separated by a comma
__decl_rwlock(ssl_ctx_lru_rwlock);
^
include/common/hathreads.h:189:2: note: expanded from macro '__decl_rwlock'
        INITCALL1(STG_LOCK, ha_rwlock_init, &(lock))
        ^
include/common/initcall.h:90:2: note: expanded from macro 'INITCALL1'
        _DECLARE_INITCALL(stage, __LINE__, function, arg1, 0, 0)
        ^
include/common/initcall.h:78:2: note: expanded from macro '_DECLARE_INITCALL'
        __DECLARE_INITCALL(__VA_ARGS__)
        ^
include/common/initcall.h:65:42: note: expanded from macro '__DECLARE_INITCALL'
            __attribute__((__used__,__section__("init_"#stg))) =   \
                                                ^
```

**Comment by tommyang** [comment]
Reported haproxy/haproxy#42

**Comment by javian** [comment]
There's a patch available now for this https://github.com/haproxy/haproxy/commit/9efa7b8ba8885ae796de62e079d4fd0ae259c11c

**Comment by fxcoudert** [comment]
Thanks @tommyang

**Pull request closed without merging**
