### PR TITLE
homeassistant-cli 0.5.0 (new formula)

### PR DESCRIPTION
**Pull request by michaelwoods**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Added a formula for [hass-cli](https://github.com/home-assistant/home-assistant-cli) (homeassistant-cli) which is a command line utility/client for [Home Assistant](https://home-assistant.io).

It is typically installed via a simple `pip3 install homeassistant-cli`. I generated the list of dependencies with `homebrew-pypi-poet`. I acknowledge that the `--version` test is "bad", however none of the operations are available without a server and configuring authentication.

### CODE REVIEW

**Comment by SMillerDev** [comment]
For the test, can we make the command fail in a reliable matter instead? "no server available" in the output or something similar?

**Comment by maxandersen** [comment]
what is it that the test is supposed to test ?  is it to verify all dependencies installed or similar ? not really any good way to test that without a server.

you can pass a broken url like: `hass-cli -x --server bad://url info` and with the -x output you get stacktrace that at some point should have the line: 
```requests.exceptions.InvalidSchema: No connection adapters were found for 'bad://url/api/discovery_info'```

but not sure that is a better test than it can dump its version info.

**Comment by SMillerDev** [comment]
Quite often a version check wouldn't fail if versioned dependencies are wrong. If we could check for more in depth usage of the program we can better spot failing dependencies.

**Comment by michaelwoods** [comment]
I updated the name of the formula at the request of the maintainer and changed out the `--version` test to running two commands that output shell completion scripts.

I experimented with matching exceptions but it started to get messy with the return code of 1 and requiring stderr redirects.

**Comment by javian** [comment]
So you would need a homeassistant server to run the test ? Wouldn't you want to add that formula as well while you are at it ? =)

**Comment by michaelwoods** [comment]
It wouldn't be all that hard but I highly doubt there would be many users installing the HA server with homebrew. I think the OSX server install base is very low and most use Hass.io, Linux on a Raspberry Pi or docker images to run their server. Their release frequency would also put a burden on maintaining the server formula.

In looking for a comparable formula test, `go-jira` performs similar tests (verifies template outputs) and does not contact a live server.

**Comment by smkelly** [comment]
Is this going to be accepted? It'd be great to have it available via Homebrew.

**Comment by fxcoudert** [comment]
Thanks @michaelwoods for contributing this formula to Homebrew!

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
