### PR TITLE
svtplay-dl: update resources

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

depend on python for Mavericks and below
have test verify an m3u8 url is printed

CC @spaam

### CODE REVIEW

**Comment by spaam** [comment]
it worked great in high sierra.

**Comment by ilovezfs** [comment]
@spaam meaning you tested these changes?

**Comment by spaam** [comment]
@ilovezfs that is correct.

**Comment by ilovezfs** [comment]
Awesome! Thanks for testing. I tried this on El Capitan (OS X 10.11) and Mountain Lion (OS X 10.8). So I think we're good.

**Comment by ilovezfs** [comment]
Shipped.

**Pull request closed without merging**
