### PR TITLE
Secure URLs (LiveCheck ones mostly)

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by nandahkrishna** [comment]
@vszakats I just happened to see this PR, and this breaks quite a few livecheckables:
```
Error: a52dec: redirection forbidden: https://liba52.sourceforge.io/downloads.html -> http://liba52.sourceforge.net/downloads.html
Error: abook: redirection forbidden: https://abook.sourceforge.io/ -> http://abook.sourceforge.net/
Error: bbftp-client: redirection forbidden: https://software.in2p3.fr/bbftp/download.html -> http://software.in2p3.fr/bbftp/download.html
Error: bcrypt: redirection forbidden: https://bcrypt.sourceforge.io/ -> http://bcrypt.sourceforge.net/
Error: bsdiff: redirection forbidden: https://www.daemonology.net/bsdiff -> http://www.daemonology.net/bsdiff/
Error: fortune: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired)
Error: gl2ps: redirection forbidden: https://geuz.org/gl2ps/src/ -> http://geuz.org/gl2ps/src/
Error: i2util: 403 Forbidden
Error: mhonarc: Unable to get versions
Error: owamp: 403 Forbidden
Error: ren: Unable to get versions
Error: ragel: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired)
```

Some of these livecheck URLs have comments near them indicating why we're not using the secure (HTTPS) URL, while in other cases such as SourceForge, we require the `.net` URLs, as livecheck doesn't allow URLs that redirect.

I'll probably open up a PR soon to fix these for now, we'll make sure we change them to HTTPS once those URLs are working.

CC @samford

**Comment by vszakats** [comment]
@nandahkrishna Why is redirection forbidden for livechecks? One would expect it to work like any other Formula URL and just redirect, or refuse when `HOMEBREW_NO_INSECURE_REDIRECT=1`. Having different behaviour and rules for URLs in difference conext isn't ideal, especially when one can silently leak onto another usage such as `homepage`. It'd be also useful to verify the livecheck URL in the `audit` phase, to catch these as part of the normal PR process. Also would be useful a way to use `user_agent: :fake` as in Casks, where we're machine parsing pages meant for browsers.

`fortune`: works for me (tested with macOS Catalina system curl).
`monharc`: the updated URL was in a comment unrelated to livecheck. Can livecheck use such URLs?
`ren`: Upgraded the homepage. If livecheck fails on this same URL, a fake user agent (e.g. `Mozilla/5.0`) fixes it. Is there a way to specify one?
`ragel`: works from me (using macOS Catalina system curl).

I'll revert for `i2util`, `owamp` to avoid these web server config/security bugs, by going insecure.

**Comment by nandahkrishna** [comment]
> Why is redirection forbidden for livechecks?

Unfortunately, I'm not aware why, so I'll have to defer to someone who knows more about livecheck for this one.

> It'd be also useful to verify the livecheck URL in the audit phase, to catch these as part of the normal PR process.

Certainly, thanks for the suggestion. I'm working on the PR currently, should be ready soon. We weren't able to account for it during GSoC with the other migration work going on, but long overdue, haha.

> Also would be useful a way to use user_agent: :fake as in Casks, where we're machine parsing pages meant for browsers/humans.

I'll take a look at this thanks.

> `fortune`: works for me (tested with macOS Catalina system curl).
> `ragel`: works from me (using macOS Catalina system curl).

Strangely for me (macOS Catalina system `curl`):
```
➜ curl https://www.ibiblio.org/pub/linux/games/amusements/fortune/
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
➜ curl https://www.colm.net/open-source/ragel/
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
Am I doing something wrong here, or is it possible that the outputs differ?

> fake user agent ... Is there a way to specify one?

Currently not, but I'll take note of your suggestion and work on it 👍🏼

> `monharc`: the updated URL was in a comment unrelated to livecheck. Can livecheck use such URLs?

Haha, no. I forgot to remove that from the output (which should've included failures arising from livecheck changes only), my mistake!

> I'll revert for i2util, owamp to avoid these web server config/security bugs, by going insecure.

Thank you! I'll try to answer your other questions too as soon as possible, and get the audit ready.

**Comment by vszakats** [comment]
Hm, flaky server certificates?

(IPv4 also works)
```
$ curl -v https://www.ibiblio.org/pub/linux/games/amusements/fortune/ -I
*   Trying 2610:28:3090:3000:0:bad:cafe:23...
* TCP_NODELAY set
* Connected to www.ibiblio.org (2610:28:3090:3000:0:bad:cafe:23) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; postalCode=27514; ST=NC; L=Chapel HIll; street=153A Country Club Road; O=University of North Carolina at Chapel Hill; OU=ibiblio; CN=www.ibiblio.org
*  start date: Oct 13 00:00:00 2017 GMT
*  expire date: Oct 12 23:59:59 2020 GMT
*  subjectAltName: host "www.ibiblio.org" matched cert's "www.ibiblio.org"
*  issuer: C=US; ST=MI; L=Ann Arbor; O=Internet2; OU=InCommon; CN=InCommon RSA Server CA
*  SSL certificate verify ok.
> HEAD /pub/linux/games/amusements/fortune/ HTTP/1.1
> Host: www.ibiblio.org
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
```

```
$ curl -v -4 -I https://www.colm.net/open-source/ragel/   
*   Trying 192.155.89.46...
* TCP_NODELAY set
* Connected to www.colm.net (192.155.89.46) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL; CN=www.colm.net
*  start date: Dec  8 00:00:00 2019 GMT
*  expire date: Dec  7 23:59:59 2021 GMT
*  subjectAltName: host "www.colm.net" matched cert's "www.colm.net"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=Sectigo Limited; CN=Sectigo RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
> HEAD /open-source/ragel/ HTTP/1.1
> Host: www.colm.net
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
```

**Comment by nandahkrishna** [comment]
Sure.

```
➜ curl -v https://www.ibiblio.org/pub/linux/games/amusements/fortune/
*   Trying 152.19.134.40...
* TCP_NODELAY set
* Connected to www.ibiblio.org (152.19.134.40) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, certificate expired (557):
* SSL certificate problem: certificate has expired
* Closing connection 0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

```
➜ curl -v https://www.colm.net/open-source/ragel/                    
*   Trying 192.155.89.46...
* TCP_NODELAY set
* Connected to www.colm.net (192.155.89.46) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, certificate expired (557):
* SSL certificate problem: certificate has expired
* Closing connection 0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by samford** [comment]
> Why is redirection forbidden for livechecks?

This isn't something that we're actively doing in livecheck and is simply the built-in behavior for `open-uri` where HTTPS to HTTP redirects are forbidden. This doesn't affect `brew audit`'s URL checking, for example, because it's using `curl` (via `utils/curl.rb`) instead of `open-uri`.

We have two ways of dealing with this issue:

* **Handle the `open-uri` redirection error, so we follow the HTTPS -> HTTP redirect.** I've worked on a couple different implementations of this locally but I haven't created a PR because I was unsure of if we wanted to be doing this.
* **Switch to using `curl` in livecheck instead of `open-uri`.** We would just need to make this change in the `PageMatch` and `Xorg` strategies and it seems relatively simple on the surface.

Considering that there's a desire to be able to modify the user agent, I think using `utils/curl.rb` is the way to go and this would bring livecheck more in line with other similar parts of Homebrew. I'll test this out and report back with findings.

Though I like to avoid redirections when it's appropriate, I specifically asked about the HTTPS -> HTTP SourceForge URLs in the past and Mike's view was that it's better to use an HTTPS URL that redirects instead of the HTTP URL it resolves to. The idea is that maybe one day the HTTPS URL won't redirect and we would already be using it. This may be a preference that we have to enforce in the `livecheck` URLs as well, if/when livecheck can follow insecure redirections. At the very least, it would largely avoid the issue that we're dealing with in this PR (and also allow us to use`url` symbols in some cases).

> refuse when `HOMEBREW_NO_INSECURE_REDIRECT=1`

This seems to be primarily used in `DownloadStrategy`, so we would need to mimic that behavior in livecheck. If we allow insecure redirects, I would definitely want to support this environment variable.

> Also would be useful a way to use `user_agent: :fake` as in Casks

If we switch over to using `curl`, then this would just require us to mimic how this is handled in the `cask` files. It doesn't look exceedingly complicated and it's something that I've thought about adding as well.

---

> It'd be also useful to verify the livecheck URL in the `audit` phase

We previously had a CI check in the homebrew-livecheck repository but we haven't implemented one in homebrew-core yet. The homebrew-core context is more complicated than homebrew-livecheck, so there are naturally more factors to consider.

We discussed possible ways of approaching this during GSoC and the ideas were either an audit or as part of test-bot. Mike was in favor of doing this in test-bot and that was where we last left it. There's still more to discuss but we haven't gotten around to it yet, as we only finished GSoC a week ago. Dawid asked me about this yesterday, so I think we may as well discuss the details of this. I still have to finish the documentation I started in Homebrew/brew before I work on livecheck in earnest again, so I can't implement the check myself right now but Dawid said he may get to it if he has time (though no promises). I'll open an issue in Homebrew/brew sometime today, so we can discuss the details in the open and mark it as "help wanted".

**Comment by SMillerDev** [comment]
> Switch to using curl in livecheck instead of open-uri. We would just need to make this change in the PageMatch and Xorg strategies and it seems relatively simple on the surface.

AFAIK most of Homebrew uses curl so that would have my preference for sure.

**Comment by vszakats** [comment]
Thanks @samford for your response, it's all looking good to me.

Regarding SF URLs, I can confirm the HTTPS entry point was the agreed way to access these. I've reached out to the pages above, and the thinking is indeed that this will eventually be enabled by admins or one day by SF. SF at the moment features a banner for logged-in users, promoting the settings.

**Comment by vszakats** [comment]
@nandahkrishna The issue seems to be the (not so) recently (on 2020-05-30) [expired](https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020) USERTrust certificate combined with certain TLS client library trying to find the clean certificate chain – but failing, due to bugs.

<https://dev.ssllabs.com/ssltest/analyze.html?d=www.ibiblio.org&s=152.19.134.40>
<https://dev.ssllabs.com/ssltest/analyze.html?d=www.colm.net>

Something these hosts should/could fix.

**Comment by vszakats** [comment]
`bsdiff`: It's a redirection bug on the server, when redirecting to the same URL, but with an ending dash. Will commit a fix to append the dash, to avoid triggering that redirect.

**Comment by nandahkrishna** [comment]
Thank you @vszakats!

**Comment by vszakats** [comment]
`gl2ps` no longer redirects to HTTP. Thanks to the author for the quick update on this.

**Comment by samford** [comment]
I'm pretty much finished reworking the `PageMatch` strategy's fetching behavior to use `curl` instead of `open-uri` at this point. It was a bit more complicated than it appeared on the surface but the general idea was fine.

With the `curl` setup, we can easily follow redirections using the `--location` option. For example, `a52dec` will simply follow the redirection and return the proper result instead of giving a `redirection forbidden` error.

I've also set things up so that livecheck surfaces the resolved URL (if any) in the debug and verbose JSON output. This will allow us to easily determine which URLs in checks are redirecting, so we can keep an eye on them and make changes where possible. In the process, I found that a couple of our strategies were generating URLs that redirected because the server wanted a trailing forward slash, so I'll be creating a PR to fix those.

I'm doing some testing and I'll work on creating PRs for the changes (in Homebrew/brew) once it's all ready.

**Comment by vszakats** [comment]
Files hosted on `ibiblio.org` should be fine now. Thanks to them for the fix.

**Comment by tarheelcoxn** [comment]
Glad to help! Thanks for the heads-up!

**Pull request merged**
