### PR TITLE
gdal: replace uchar with u_char

### LINKED ISSUE #7811: Osx 10.12.1 GDAL build failure
`brew install gdal --with-postgresql --with-opencl --with-java --with-armadillo --with-complete`

`libtool: compile:  clang++ -c -I/private/tmp/gdal-20161213-14237-1mrfcpq/gdal-1.11.5/port -I/private/tmp/gdal-20161213-14237-1mrfcpq/gdal-1.11.5/gcore -I/private/tmp/gdal-20161213-14237-1mrfcpq/gdal-1.11.5/alg -I/private/tmp/gdal-20161213-14237-1mrfcpq/gdal-1.11.5/ogr -I/private/tmp/gdal-20161213-14237-1mrfcpq/gdal-1.11.5/ogr/ogrsf_frmts -DOGR_ENABLED -I/usr/local/Cellar/gdal/1.11.5_1/include -I/private/tmp/gdal-20161213-14237-1mrfcpq/gdal-1.11.5/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.3.3.1_5/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -Idegrib18/degrib -DHAVE_JASPER -arch x86_64 -I/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/include/darwin -DHAVE_SSE_AT_COMPILE_TIME -Wall degrib18/degrib/inventory.cpp  -fno-common -DPIC -o ../o/.libs/inventory.o
jpeg2000_vsil_io.cpp:209:32: error: use of undeclared identifier 'uchar'; did you mean 'char'?
                        stream->bufbase_ = JAS_CAST(uchar *, buf);
                                                    ^~~~~
                                                    char
/usr/local/include/jasper/jas_types.h:117:4: note: expanded from macro 'JAS_CAST'
        ((t) (e))
          ^
jpeg2000_vsil_io.cpp:209:21: error: assigning to 'unsigned char *' from incompatible type 'char *'
                        stream->bufbase_ = JAS_CAST(uchar *, buf);
                                         ^ ~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.`

### Bug reports:

`brew config`
HOMEBREW_VERSION: 1.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0f529dae1043639058130092cf35e68d18907cb8
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 09ae1897d3bc0e1e573aba6ef607151c386fc5b1
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.3/bin/ruby
Java: 1.8.0_112
macOS: 10.12.1-x86_64
Xcode: 8.1
CLT: 8.1.0.0.1.1476494586
X11: 2.7.11 => /opt/X11

`brew gist-logs gdal`
https://gist.github.com/f45259c0adbb35796b703b8baaf30695

### PR DESCRIPTION
**Pull request by ilovezfs**
Fixes #7811.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Cheers @ilovezfs!

**Comment by ilovezfs** [comment]
hadn't merged this because it needs to be reported upstream ....

**Comment by MikeMcQuaid** [comment]
@ilovezfs Apologies for that. Was hasty on it because I saw the "Fixes" and jumped the gun. Shall I revert?

**Comment by ilovezfs** [comment]
@MikeMcQuaid nope it's a fairly common porting issue. I'll try to get this reported ASAP.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Thanks 🙇

**Pull request closed without merging**
