### PR TITLE
dvc 1.11.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dtrodrigues** [comment]
I don't think this formula actually uses any of the explicitly downloaded resources -- it does a pip install without `--no-deps` and fetches the dependencies again dynamically.

**Comment by chenrui333** [comment]
good call out, do you mind filing a ticket in the upstream repo?

**Comment by dtrodrigues** [comment]
It's not an upstream issue necessarily - it's the way this formula is written. We're also letting it install a couple pre-built wheels which we generally don't allow. Based on the linked issues in the comments, it seems like it'll take a bit of effort to re-work this to be more along the lines of other python formulae.

**Comment by efiop** [comment]
I see that oss's dependency pycryptodome fails. oss is a rather less popular extra for dvc package, so we could just skip it if we really have to. To do that we need to just remove `oss` from https://github.com/Homebrew/homebrew-core/blob/160b47aa1c5a6ca88c91b007110f77b6a5b7f068/Formula/dvc.rb#L317 if this is MacOS 11.0 that we are installing on. @chenrui333 would you be able to remove `oss` from that line? I'm happy to send a PR for your fork or create a new PR instead of this one, please let me know.

Regarding the resources, they were added by someone else. Indeed, the formula is written with some workarounds for problems in our dependencies and it is not trivial to rework it right now :slightly_frowning_face: I'm sure we'll revisit it in the future though.

**Comment by efiop** [comment]
Guys, could we close this so I could submit 1.11.3?

**Pull request closed without merging**
