### PR TITLE
cmake 3.16.0

### PR DESCRIPTION
**Pull request by jamiesnape**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jamiesnape** [comment]
Not sure I see anything failing in CI that is directly related to CMake.

**Comment by Bo98** [comment]
Looking through the Mojave and High Sierra logs, there's just some test failures that we already know about. In fact some of them have since been fixed - I'm trying to bring the number of failures down as much as I can.

Though the Catalina build was cancelled so I don't know about that.

**Comment by fxcoudert** [comment]
@chenrui333 if you abort a build please comment on the PR why, so we know if we can safely restart it or not

**Comment by chenrui333** [comment]
Sorry, I think it is safe to restart. I only abort the catalina build which seems hanging and takes too long. But the console log information seems sufficient enough.

**Comment by chenrui333** [comment]
I will go ahead cross posting the info:

on catalina

13:22:15 ==> brew test --verbose abyss
13:22:20 ==> FAILED
13:22:20 Testing abyss
13:22:20 /usr/bin/sandbox-exec -f /private/tmp/homebrew20191126-82817-x3l262.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/abyss.rb --verbose
13:22:20 ==> Downloading http://www.bcgsc.ca/platform/bioinfo/software/abyss/releases/1.3.4/test-data.tar.gz
13:22:20 ==> Downloading from https://www.bcgsc.ca/platform/bioinfo/software/abyss/releases/1.3.4/test-data.tar.gz
13:22:20 /usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.1.16-139-g96e0686\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.1\)\ curl/7.64.1 --fail --silent --location --remote-time --continue-at 0 --output /Users/brew/Library/Caches/Homebrew/downloads/8006732cdc492b5b7fb3eedd76552920a061850c0be3d95e8ee3d92ade4a756a--test-data.tar.gz.incomplete https://www.bcgsc.ca/platform/bioinfo/software/abyss/releases/1.3.4/test-data.tar.gz
13:22:20 curl: (22) The requested URL returned error: 404 Not Found
13:22:20 Error: abyss: failed
13:22:20 An exception occurred within a child process:
13:22:20   DownloadError: Failed to download resource "abyss--testdata"
13:22:20 Download failed: http://www.bcgsc.ca/platform/bioinfo/software/abyss/releases/1.3.4/test-data.tar.gz
13:22:20 

13:32:34 ==> brew test --verbose alure
13:37:38 ==> FAILED
13:37:38 Testing alure
13:37:38 /usr/bin/sandbox-exec -f /private/tmp/homebrew20191126-96805-1pecvip.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/alure.rb --verbose
13:37:38 ==> /usr/local/Cellar/alure/1.2/bin/alureplay /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/test.wav
13:37:38 Killing child processes...

15:14:53 ==> brew test --verbose dromeaudio
15:14:59 ==> FAILED
15:14:59 Testing dromeaudio
15:14:59 /usr/bin/sandbox-exec -f /private/tmp/homebrew20191126-81935-1arw79d.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/dromeaudio.rb --verbose
15:14:59 ==> /usr/local/Cellar/dromeaudio/0.3.0/bin/DromeAudioPlayer /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/test.mp3
15:14:59 DromeAudio Exception: AudioDriverOSX::AudioDriverOSX(): AudioUnitSetProperty (for StreamFormat) failed
15:14:59 Audio driver initialization failed
15:14:59 Error: dromeaudio: failed

20:31:08 ==> brew linkage --test octomap
20:31:10 ==> FAILED
20:31:10 Missing libraries:
20:31:10   /tmp/octomap-20191011-97874-zwpaix/octomap-1.9.0/octomap/lib/liboctomath.1.9.dylib

20:57:17 ==> brew install --only-dependencies osquery
20:58:06 ==> FAILED
20:58:06 ==> Installing dependencies for osquery: augeas, rocksdb, afflib, libewf, sleuthkit, ssdeep and yara
20:58:06 ==> Installing osquery dependency: augeas

**Comment by chenrui333** [comment]
on mojave

19:26:08 ==> brew linkage --test octomap
19:26:10 ==> FAILED
19:26:10 Missing libraries:
19:26:10   /tmp/octomap-20180822-74275-1lz3o12/octomap-1.9.0/octomap/lib/liboctomath.1.9.dylib

19:48:54 ==> brew install --only-dependencies osquery
19:49:36 ==> FAILED
19:49:36 ==> Installing dependencies for osquery: augeas, rocksdb, afflib, libewf, sleuthkit, ssdeep and yara
19:49:36 ==> Installing osquery dependency: augeas
...
19:49:36 ==> Pouring sleuthkit-4.6.7.mojave.bottle.tar.gz
19:49:36 Error: The `brew link` step did not complete successfully
19:49:36 The formula built, but is not symlinked into /usr/local
19:49:36 Could not symlink bin/icat
19:49:36 Target /usr/local/bin/icat
19:49:36 is a symlink belonging to libusbmuxd. You can unlink it:
19:49:36   brew unlink libusbmuxd

21:57:14 ==> brew test --verbose vit
21:57:19 ==> FAILED
21:57:19 Testing vit
21:57:19 /usr/bin/sandbox-exec -f /private/tmp/homebrew20191127-73034-169nsyy.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vit.rb --verbose
21:57:19 Error: vit: failed

**Comment by chenrui333** [comment]
On highsierra

19:45:49 ==> brew install --only-dependencies osquery
19:46:31 ==> FAILED
19:46:31 ==> Installing dependencies for osquery: augeas, rocksdb, afflib, libewf, sleuthkit, ssdeep and yara
19:46:31 ==> Installing osquery dependency: augeas
...
19:46:31 ==> Pouring sleuthkit-4.6.7.high_sierra.bottle.tar.gz
19:46:31 Error: The `brew link` step did not complete successfully
19:46:31 The formula built, but is not symlinked into /usr/local
19:46:31 Could not symlink bin/icat
19:46:31 Target /usr/local/bin/icat
19:46:31 is a symlink belonging to libusbmuxd. You can unlink it:
19:46:31   brew unlink libusbmuxd

**Comment by Bo98** [comment]
* abyss: fixed in #47076
* alure: known test failure - audio related
* aom: upstream TLS certificate issue causing test failures, seemingly intermittent (probably a single bad server among a few behind a load balancer)
* dromeaudio: known test failure - audio related
* octomap: noted in #46728 - waiting for response from upstream
* sleuthkit conflict with libusbmuxd: fixed in #47230
* vit: fixed in #47238

I think I've fixed enough to get this merged. `alure` and `dromeaudio` tests work locally if that's a concern. `aom` is a dice roll but did pass on High Sierra and Catalina last time. `octomap` is an upstream issue and existed before this pull request.

@BrewTestBot test this please

**Comment by Bo98** [comment]
Yikes, it ate all the disk space. I'll deal with that this evening.

**Comment by mrks** [comment]
Anything one can do to help with this?

**Comment by Bo98** [comment]
@BrewTestBot test this please

**Comment by wolkykim** [comment]
Thanks for the work on this. Hope this update gets released out soon.

**Comment by henryiii** [comment]
3.16.1 is now out.

**Comment by wolkykim** [comment]
@Bo98 where are we on this? Can this go out soon?

**Comment by Bo98** [comment]
Unfortunately builds since the initial one suffered from disk space issues which prevented progress, and I've been too busy with work for the last week to spend much time on Homebrew - but that should be out of the way come this weekend.

My recommendation is to attempt 3.16.1 and ping me in it. Builds of CMake take several hours anyway. If it fails with disk space issues, I'll see what I can do to get it through.

**Comment by wolkykim** [comment]
Thanks for the info.

**Comment by mrks** [comment]
@Bo98 Seems to have happened again :/

**Comment by fxcoudert** [comment]
Conflicting (but was otherwise in good shape). I've launched another testing cycle in https://github.com/Homebrew/homebrew-core/pull/47912

**Pull request closed without merging**
