### PR TITLE
root 6.26.00

### PR DESCRIPTION
**Pull request by henryiii**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by henryiii** [comment]
Could go `python@3.9` -> `python@3.10` as well if this passes. When is the default going to change?

**Comment by carlocab** [comment]
> Could go `python@3.9` -> `python@3.10` as well if this passes. When is the default going to change?

When the migration from 3.9 to 3.10 has been done for most formulae, probably. The `tap_syntax` job will likely complain about the mixed version dependency with `tbb` still on `python@3.9` if you switch this to `python@3.10`, though.

Also, this should help fix your test failure:
```patch
diff --git a/Formula/root.rb b/Formula/root.rb
index 9a790899b81..6472481eeaa 100644
--- a/Formula/root.rb
+++ b/Formula/root.rb
@@ -55,7 +55,7 @@ class Root < Formula
   skip_clean "bin"
 
   def install
-    ENV.append "LDFLAGS", "-Wl,-rpath,#{lib}/root" if OS.linux?
+    ENV.append "LDFLAGS", "-Wl,-rpath,#{lib}/root"
 
     inreplace "cmake/modules/SearchInstalledSoftware.cmake" do |s|
       # Enforce secure downloads of vendored dependencies. These are
```

**Comment by henryiii** [comment]
Hmmm,

```
Error: PR requires the CI-long-timeout label but it is not set!
Error: If the longer timeout is not required, remove the "long build" label.
Error: Otherwise, add the "CI-long-timeout" label.
Error: No more than 2 PRs at a time may use "CI-long-timeout".
```

**Comment by cho-m** [comment]
Probably need to disable default Linux GCC-5 as it probably lacks necessary C++17 features:
```
  In file included from <module-includes>:2:
  /tmp/root-20220303-39057-zkjpuz/root-6.26.00/builddir/include/ROOT/RStringView.hxx:25:10: fatal error: 'string_view' file not found
  #include <string_view>
           ^~~~~~~~~~~~~
```

Either disable GCC 5.x specifically:
```rb
fails_with gcc: "5"
```

Or disable GCC <= 6.x (or whatever versions that don't work)
```rb
fails_with :gcc do
  version "6"
  cause "needs C++17 string_view"
end
```

**Comment by henryiii** [comment]
What about toggling C++ 17 with 14 for older GCCs? C++11 support is gone, but 14 is still supported (though a few newer portions of ROOT are removed).

**Comment by henryiii** [comment]
ROOT team thinks 5.1 is required now, but that's in C++14 mode. Is there a way to detect the version in a such a way that we can pick 14 or 17?

**Comment by cho-m** [comment]
How was the build with the original C++ standard logic:
```rb
    cxx_version = (MacOS.version < :mojave) ? 14 : 17
    args << "-DCMAKE_CXX_STANDARD=#{cxx_version}"
```

Linux is always "true" and had previously chosen C++14.

**Comment by henryiii** [comment]
There are probably other things that break with older versions - if not tested, it probably doesn't work. But I've restored the original comparison for now. Would rather make it a gcc version comparison, though. :)

**Comment by cho-m** [comment]
One thing is that GCC 11+ is currently guaranteed to exist during build & run-time due to
```rb
depends_on "gcc" # for gfortran
```

Which is why it is possible to blindly enable C++17 and disable GCC-5 on Linux. In this case, it will use already installed Homebrew GCC-11 to build and link to corresponding libraries.

If these is any useful advantage of preferring C++17 over C++14 on Linux, then may as well do this as there is no dependency cost.

---

Not sure if there is any example of checking the particular `ENV.cc` version. In general, Homebrew only guarantees support for the particular compiler used to build bottles.

On Linux, this defaults to `gcc-5` for now and `gcc-7` is planned for future. And typically we use Homebrew's latest `gcc` if default doesn't work.

**Comment by cho-m** [comment]
Linux failure:
```
==> brew test --verbose root
==> FAILED
Full test root output
  ==> Testing root
  ==> /home/linuxbrew/.linuxbrew/Cellar/root/6.26.00/bin/root -b -l -q -e gSystem->LoadAllLibraries(); 0
   *** Break *** segmentation violation
   Generating stack trace...
  Error: root: failed
```

**Comment by henryiii** [comment]
That happened both for C++14 and for new GCC C++17. I'll see if I can reproduce this in docker later today.

**Comment by carlocab** [comment]
You can download the Linux bottle from the CI run to save you having to build it from source first.

**Comment by henryiii** [comment]
Similar issue seems to show up here: https://github.com/Homebrew/homebrew-core/pull/96175. If you enable debugging, you can get that error from linuxbrew.

```
Failure value returned from cantFail wrapped call
UNREACHABLE executed at /tmp/root-20220307-21626-1nv4an0/root-6.26.00/interpreter/llvm/src/include/llvm/Support/Error.h:731!
```

It's looking for a symbol (`GetExecutablePath`) to find its own path, but that's failing from the install dir, returning "" which fails the cantFail. (Seems to be fine from the build dir). Probably will continue debugging with the ROOT team tomorrow.

**Comment by carlocab** [comment]
> Similar issue seems to show up here: #96175.

Did you mean to link a different issue/PR?

**Comment by henryiii** [comment]
Oops, yes, copied the wrong one, fixed. 😳

**Comment by chrisburr** [comment]
This has been isolated to a bug where directories with a leading dot (i.e. `.linuxbrew`) are not being handled correctly (https://github.com/root-project/root/pull/10073). There will be a patch release soon.

**Comment by henryiii** [comment]
Ahh, that also explains the pcm warnings I was seeing. We can apply patches here that are accepted upstream, too. Though this one is bad enough that I’m guessing there will be a push for a rapid patch release.

**Comment by henryiii** [comment]
What's the proper procedure for adding a patch?

```
Use a commit hash URL rather than patch-diff: https://patch-diff.githubusercontent.com/raw/root-project/root/pull/10073.patch
```

**Comment by cho-m** [comment]
You will want to use the commit itself. From PR, you can find the actual merge, which is https://github.com/root-project/root/commit/efc67e432206771fe934ad7763529cf3621696a1

For GitHub patches, you can append `.patch?full_index=1` to URL. Try grepping other Homebrew formulae and there should be a bunch of examples.

**Comment by henryiii** [comment]
Thanks! I did grep but saw stuff from `Homebrew/formula-patches`. It was a two-commit merge so I had to add two patches.

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request closed without merging**
