### PR TITLE
taylor 0.1.3

### PR DESCRIPTION
**Pull request by thelvis4**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

 Update taylor to version 0.1.3

### CODE REVIEW

**Comment by DomT4** [comment]
Test is failing on execution, which is a bit strange. Locally I see this at the end of the build, which may be the issue:

```
Touch build/Release/Taylor.app
    cd /tmp/taylor-20160526-30222-1w5ft2l/Taylor-0.1.3
    /usr/bin/touch -c /tmp/taylor-20160526-30222-1w5ft2l/Taylor-0.1.3/build/Release/Taylor.app

RegisterWithLaunchServices build/Release/Taylor.app
    cd /tmp/taylor-20160526-30222-1w5ft2l/Taylor-0.1.3
    builtin-lsRegisterURL /tmp/taylor-20160526-30222-1w5ft2l/Taylor-0.1.3/build/Release/Taylor.app

** BUILD SUCCEEDED **

ditto "/private/tmp/taylor-20160526-30222-1w5ft2l/Taylor-0.1.3/.brew_home/tmp/Build/Products/Release/Taylor.app/Contents/MacOS/Taylor" "/usr/local/Cellar/taylor/0.1.3/bin/taylor"
ditto: can't get real path for source '/private/tmp/taylor-20160526-30222-1w5ft2l/Taylor-0.1.3/.brew_home/tmp/Build/Products/Release/Taylor.app/Contents/MacOS/Taylor'
make: *** [install] Error 1
```

**Comment by thelvis4** [comment]
Hmmm...
It saves the build in 
`/tmp/taylor-20160526-30222-1w5ft2l/Taylor-0.1.3/build/Release/Taylor.app` 
and tries to load it from
`/private/tmp/taylor-20160526-30222-1w5ft2l/Taylor-0.1.3/.brew_home/tmp/Build/Products/Release/Taylor.app/Contents/MacOS/Taylor`

Somehow it adds `/private` prefix and uses `.brew_home/tmp/Build/Products/Release/Taylor.app` instead of `build/Release/Taylor.app`

The command is:
`ditto "$(BUILD_DESTINATION)/$(PACKAGE_NAME)/Contents/MacOS/Taylor" "$(PREFIX)/bin/taylor"`
It seems like `BUILD_DESTINATION` and `PACKAGE_NAME ` is changed while executing.

Any ideas why might this happen?
BTW, I can install the formula locally without any problems.

**Comment by MikeMcQuaid** [comment]
> BTW, I can install the formula locally without any problems.

Can you run `brew test taylor` locally?

**Comment by thelvis4** [comment]
```
Testing taylor
==> Using the sandbox
==> /usr/local/Cellar/taylor/0.1.3/bin/taylor -p /tmp/taylor-test-20160526-17268-18dvreq
Last 15 lines from /Users/thelvis/Library/Logs/Homebrew/taylor/01.taylor:
2016-05-26 15:48:21 +0300

/usr/local/Cellar/taylor/0.1.3/bin/taylor
-p
/tmp/taylor-test-20160526-17268-18dvreq

Error: taylor: failed
Failed executing: /usr/local/Cellar/taylor/0.1.3/bin/taylor -p /tmp/taylor-test-20160526-17268-18dvreq
/usr/local/Library/Homebrew/formula.rb:1493:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1430:in `open'
/usr/local/Library/Homebrew/formula.rb:1430:in `system'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/taylor.rb:30:in `block in <class:Taylor>'
/usr/local/Library/Homebrew/formula.rb:1335:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1329:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by thelvis4** [comment]
Not sure, but I guess when I run `brew test taylor`, it doesn't create temporary folder that want's to use as sandbox.
I put `system "ls -a", testpath` in `test do` and returned:
```
ls -a
/tmp/taylor-test-20160526-17648-1huwllq

Error: taylor: failed
Failed executing: ls -a /tmp/taylor-test-20160526-17648-1huwllq
```

**Comment by MikeMcQuaid** [comment]
@thelvis4 That's not the bug here or every formula test would be failing 😉

**Comment by UniqMartin** [comment]
> I put `system "ls -a", testpath` in `test do` and returned:

You'd need to make this `system "ls", "-a", testpath` or `system "ls -a #{testpath}"`. Otherwise it will try to execute a binary names `ls -a` which is unlikely to exist (and is certainly not what you want).

**Comment by dunn** [comment]
Looks like we should be using `-f` instead of `-p`? https://github.com/yopeso/Taylor/#available-options

**Comment by thelvis4** [comment]
This is the path to project **folder**, not file.

**Comment by dunn** [comment]
Right, my mistake.

**Comment by UniqMartin** [comment]
@thelvis4 The `taylor` binary is trying to access `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/sourcekitd.framework/Versions/A/sourcekitd` in some way that is blocked by our sandbox (you should be able to reproduce locally with `brew test --sandbox taylor`).

I suspect this is a similar problem to Homebrew/legacy-homebrew#50211 and as far as I'm aware, we don't have a solution for that yet. Given these circumstances, it would be okay to weaken the test and instead make it something like:

```ruby
assert_match version.to_s, shell_output("#{bin}/taylor --version")
```

Though if you have a chance, please have a closer look at the linked PR and see if something can be done about that in the `taylor` project and whether we can fix that on our end without weakening the protection of our sandbox.

@jpsim If you have a chance, can you have a look and comment on whether the above is still correct and if there have been any new developments regarding the sandbox issue. Thanks!

**Comment by thelvis4** [comment]
@UniqMartin `taylor` uses `SourceKitten` internally, and yeah, it's actually the same problem. 
By reading [the thread](https://github.com/Homebrew/legacy-homebrew/pull/50211), I can conclude that the only sollution now is to weaken the test.

**Comment by thelvis4** [comment]
The tests passed. I think we can merge this.
@UniqMartin Thanks or your involvement and for the tips! 🍻

**Comment by UniqMartin** [comment]
I wasn't aware and didn't realize that this uses SourceKitten internally. 😳 Certainly explains the behavior. It would be great to figure out the sandbox issue and find a better solution, but for now that's the best we can do … I'm glad I was able to help.

Merged in 38096527369ea24e95c246ab59bc2ac4e093e5dc. Thank you for this contribution to Homebrew, @thelvis4! :tada:

**Comment by jpsim** [comment]
Glad you all sorted this out. What's odd is that SwiftLint is built on SourceKitten too and isn't affected by this (e.g. has a "real" test): https://github.com/Homebrew/homebrew-core/blob/master/Formula/swiftlint.rb

**Pull request closed without merging**
