### PR TITLE
uwsgi 2.0.13.1

### PR DESCRIPTION
**Pull request by dholm**
Depends on #3258.

### CODE REVIEW

**Comment by ilovezfs** [comment]
I'm not eager to add more options to this formula. Also, I'm not thrilled with adding more untestable `:tuntap` even if it's optional.

**Comment by DomT4** [comment]
Agree it'd be nice to limit the options a little until we see more demand for them. The _only_ options our analytics know about being used are `--with-python` and `--with-python --with-python3`. That's it, out of all the options included before today.

**Comment by apjanke** [comment]
While we want to limit options, these plugins could be added unconditionally for the ones that don't introduce new dependencies, right? (e.g. greenlet, stackless, coro, libffi)

What do folks think about changing that big `plugins = ["airbrake", "alarm_curl", ` to be one item per line, for more readable diffs? I can see that this PR added (and maybe removed) some items there and re-wrapped them, but I can't tell what changed without running my fingers along the lines and comparing them item by item.

**Comment by ilovezfs** [comment]
I wonder if there's an "all plugins" option to avoid the crazy.

**Comment by ilovezfs** [comment]
I guess we couldn't do that anyway because of `:tuntap`. Yeah one per line sounds fine.

**Comment by DomT4** [comment]
Yeah, still worth keeping the array non-empty but:
```ruby
plugins = %w[
  airbrake
  alarm_curl
  alarm_speech
  asyncio
  cache
]
```
And so on is a lot more readable.

**Comment by dholm** [comment]
Will fix the array and options.

I don't think there is an all plugin option, the annoying thing is that if you try to build a plugin that is unsupported the entire build fails. :(

**Comment by dholm** [comment]
@apjanke `greenlet` and `stackless` require Python modules to be installed separately.  The same goes for `coro` except that it's a Perl module.

**Comment by apjanke** [comment]
I like the new formatting a lot better. Can't remember why the last build failed, so...

@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
Install is failing: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6671/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_uwsgi/

**Comment by MikeMcQuaid** [comment]
Closing due to no response.

**Pull request closed without merging**
