### PR TITLE
cbonsai 1.3.1 (new formula)

### PR DESCRIPTION
**Pull request by osalbahr**
Adds [cbonsai](https://gitlab.com/jallbrit/cbonsai).

Re-attempts PR #130784, PR #130819.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by osalbahr** [comment]
I have verified that the formula works on the [homebrew/brew image](https://hub.docker.com/r/homebrew/brew) (`podman run -it homebrew/brew`) so hopefully it works on all Linux distributions.

**Comment by osalbahr** [comment]
Is there a way to have the remaining tests run despite the first error? I wonder if it’s a macOS version or architecture issue.

**Comment by osalbahr** [comment]
Thx for rerunning. Since it’s failing in all macOS I’ll see if it’s a GNU gcc vs Apple clang issue.

**Comment by osalbahr** [comment]
Using gcc-13 doesn't fix it, it just gives a slightly different error:

```c
/private/tmp/cbonsai-20230628-8764-1d5rnga/cbonsai-v1.3.1 $ gcc-13 -Wall -Wextra -Wshadow -Wpointer-arith -Wcast-qual -pedantic     cbonsai.c  -lncursesw -ltinfo -lpanelw -o cbonsai
cbonsai.c: In function 'printstdscr':
cbonsai.c:711:25: error: unknown type name 'cchar_t'; did you mean 'wchar_t'?
  711 |                         cchar_t c;
      |                         ^~~~~~~
      |                         wchar_t
cbonsai.c:712:25: warning: implicit declaration of function 'mvwin_wch'; did you mean 'mvwinsch'? [-Wimplicit-function-declaration]
  712 |                         mvwin_wch(stdscr, y, x, &c);
      |                         ^~~~~~~~~
      |                         mvwinsch
cbonsai.c:718:25: warning: implicit declaration of function 'getcchar'; did you mean 'getwchar'? [-Wimplicit-function-declaration]
  718 |                         getcchar(&c, wch, &attrs, &color_pair, 0);
      |                         ^~~~~~~~
      |                         getwchar
/private/tmp/cbonsai-20230628-8764-1d5rnga/cbonsai-v1.3.1 $ clang -Wall -Wextra -Wshadow -Wpointer-arith -Wcast-qual -pedantic     cbonsai.c  -lncursesw -ltinfo -lpanelw -o cbonsai
cbonsai.c:711:4: error: unknown type name 'cchar_t'; did you mean 'wchar_t'?
                        cchar_t c;
                        ^~~~~~~
                        wchar_t
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_wchar_t.h:34:26: note: 'wchar_t' declared here
typedef __darwin_wchar_t wchar_t;
                         ^
cbonsai.c:712:4: error: call to undeclared function 'mvwin_wch'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                        mvwin_wch(stdscr, y, x, &c);
                        ^
cbonsai.c:718:4: error: call to undeclared function 'getcchar'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                        getcchar(&c, wch, &attrs, &color_pair, 0);
                        ^
cbonsai.c:731:43: warning: format specifies type 'short' but the argument has type 'int' [-Wformat]
                        else if (fg >= 8) printf("\033[9%him", fg - 8);
                                                        ~~~    ^~~~~~
                                                        %i
1 warning and 3 errors generated.
/private/tmp/cbonsai-20230628-8764-1d5rnga/cbonsai-v1.3.1 $```

**Comment by osalbahr** [comment]
It looks like the issue was that `[panelw.pc` does not exist on macOS's `ncurses` but does exist on Homebrew's `ncurses`](https://gitlab.com/jallbrit/cbonsai/-/issues/10). Directly using the latter simplifies things. For some reason, I remember seeing a style error earlier to change `depends_on "ncurses"` to `uses_from_macos "ncurses"`.

**Comment by osalbahr** [comment]
Ok, the error message appeared again:
```console
==> FAILED
Full audit cbonsai --online --new-formula output
  cbonsai
    * Dependency 'ncurses' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.
```
https://github.com/Homebrew/homebrew-core/actions/runs/5406950925/jobs/9824439319

How can I force using brew's ncurses due to the missing package?

**Comment by osalbahr** [comment]
[CI / Linux (pull_request)](https://github.com/Homebrew/homebrew-core/actions/runs/5406950925/jobs/9824438956?pr=135198) failed due to:
```console
Run Homebrew/actions/setup-homebrew@master
/usr/bin/docker exec  703ff0778e59d025717d5fb570bc6f08d6a9066eec44e8355c3db883570e91c2 sh -c "cat /etc/*release | grep ^ID"
/usr/bin/bash /__w/_actions/Homebrew/actions/master/setup-homebrew/main.sh true false 
Set up ACL.
Reset branch 'master'
branch 'master' set up to track 'origin/master'.
Your branch is up to date with 'origin/master'.
remote: fatal: object 9b3c00be5172fefe29fd90e4bcbfa59f002126dd cannot be read        
remote: aborting due to possible repository corruption on the remote side.
fatal: protocol error: bad pack header
remote: fatal: object 9b3c00be5172fefe29fd90e4bcbfa59f002126dd cannot be read        
remote: aborting due to possible repository corruption on the remote side.
fatal: protocol error: bad pack header
remote: fatal: object 9b3c00be5172fefe29fd90e4bcbfa59f002126dd cannot be read        
remote: aborting due to possible repository corruption on the remote side.
fatal: protocol error: bad pack header
remote: fatal: object 0b612831480a377332904cda6a0e8eaa02739f82 cannot be read        
remote: aborting due to possible repository corruption on the remote side.
fatal: protocol error: bad pack header
remote: fatal: object 0b612831480a377332904cda6a0e8eaa02739f82 cannot be read        
remote: aborting due to possible repository corruption on the remote side.
fatal: protocol error: bad pack header
Error: The process '/usr/bin/bash' failed with exit code 128
```

I think this is unrelated to the formula. The tests pass in the hombrew/brew image.

**Comment by osalbahr** [comment]
The [CI error](https://github.com/Homebrew/homebrew-core/actions/runs/5406950925) is now "Canceling since a higher priority waiting request for 'tests-refs/pull/135198/merge' exists". Is there something I can do from my end?

**Comment by osalbahr** [comment]
Maybe the failure is related to the GitHub situation and is now semi-resolved?

**Comment by osalbahr** [comment]
Hi @p-linnane,

In [macOS 11-arm64](https://github.com/Homebrew/homebrew-core/actions/runs/5480296878/jobs/9983366350#logs) (and the other macOS *) I still get:
```console
==> brew audit cbonsai --online --new-formula
==> FAILED
Full audit cbonsai --online --new-formula output
  cbonsai
    * Dependency 'ncurses' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.
  Error: 1 problem in 1 formula detected.
  ```

What should I do?

**Comment by p-linnane** [comment]
@osalbahr We can ignore that audit. I've squashed the commits and will merge this once the builds are finished.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
