### PR TITLE
bartycrouch 4.15.1

### PR DESCRIPTION
**Pull request by Jeehut**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  Error: An exception occurred within a child process:
    Errno::ENOENT: No such file or directory @ rb_file_s_stat - /opt/homebrew/Cellar/bartycrouch/4.15.1/lib/lib_InternalSwiftSyntaxParser.dylib
```

**Comment by Jeehut** [comment]
@chenrui333 This is a follow-up on the failed release https://github.com/Homebrew/homebrew-core/pull/131567.

I've merged https://github.com/FlineDev/BartyCrouch/pull/280 from @alexdeem who tried to fix exactly that kind of error, but it seems it didn't help much.

**Comment by alexdeem** [comment]
@Jeehut I've raised https://github.com/Homebrew/homebrew-core/pull/133224 which resolves this problem :)

**Comment by Jeehut** [comment]
@alexdeem Awesome, thank you very much! ❤️

**Pull request closed without merging**
