### PR TITLE
postgresql 11.1

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Looks like pgroonga might need a version update since its a few versions behind and fails the test.

**Comment by fxcoudert** [comment]
- `pgrouting` test failure reported upstream: https://github.com/pgRouting/pgrouting/issues/1164

**Comment by fxcoudert** [comment]
The `pgrouting` failure is because `postgis` needs a revision bump too.

**Comment by fxcoudert** [comment]
This version was merged in #34784

**Pull request closed without merging**
