### PR TITLE
taylor: use 10.11 bottle on 10.12.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

A better alternative to https://github.com/Homebrew/homebrew-core/pull/6656.

### CODE REVIEW

**Comment by ilovezfs** [comment]
:(

**Comment by MikeMcQuaid** [comment]
@ilovezfs Yeh, need to figure it out.

**Comment by ilovezfs** [comment]
I don't think 

`"        or_later_arg = "-G    sha256 ['\"][a-f0-9]*['\"] => :\w+_or_later$"`

Is being evaluated

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/homebrew-test-bot/pull/22

**Comment by MikeMcQuaid** [comment]
Sierra logs confirm that this is being run as expected there: https://bot.brew.sh/job/Homebrew%20Core/10846/version=any_sierra/console

**Pull request merged**
