### PR TITLE
bazel 0.16.0

### PR DESCRIPTION
**Pull request by JCount**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by keith** [comment]
@JCount looks like there's an issue here

**Comment by JCount** [comment]
Yup, I am looking at it in a VM.

**Comment by keith** [comment]
Did you figure out the root cause @JCount ? Any way I can help?

**Comment by JCount** [comment]
@keith I'd welcome any ideas about the build failure on `10.11`. Is it a fundamental issue that means we should just set `10.12` as the minimum platform, and then just merge this PR?

(essentially anything useful is welcome in this PR 😉)

**Comment by philwo** [comment]
The failure looks like some minor problem that we could probably fix (but from the error messages I'm not sure what causes it yet).

I'll setup a couple of Mac Pros for Bazel's CI with 10.11 and 10.12 and will see that we can get this fixed and then also continuously test Bazel on older versions of macOS.

**Comment by keith** [comment]
Installing this formula directly now actually results in an error for me on 10.13.5:

```
ERROR: /private/tmp/bazel_gyrSHUHd/out/external/bazel_tools/third_party/zlib/BUILD:15:1: undeclared inclusion(s) in rule '@bazel_tools//third_party/zlib:zlib':
this rule is missing dependency declarations for the following files included by 'external/bazel_tools/third_party/zlib/compress.c':
```

**Comment by philwo** [comment]
@buchgr is working on a fix - basically we have to do three things:

1) Add a patch to Bazel to workaround a compatibility issue with newer JDKs. (This will result in Bazel 0.16.1)
2) Add a dependency on unzip / zip for this formula to workaround a too old version of these tools in macOS 10.11. (This resulted in the original build error seen here.)
3) Slightly change the formular to build a version of Bazel without an embedded Azul Zulu OpenJDK (to conform with Homebrew's policy of not shipping binaries that haven't been built from source by the formula). For this, we also have to bump the Java requirement of this formular to Java 9 or higher, as Bazel can no longer (easily) run with Java 8.

**Comment by JCount** [comment]
@philwo Thanks for the update.

**Pull request closed without merging**
