### PR TITLE
orc 0.4.32

### PR DESCRIPTION
**Pull request by issyl0**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
- The majority of the source code and the collective work is subject
to the following license: `BSD-2-Clause`
- The source code implementing the Mersenne Twister algorithm is
subject to the following license: `BSD-3-Clause`

**Comment by issyl0** [comment]
How did you find that, @chenrui333? The only reference to "license" I could find in the repo was [the COPYING file](https://cgit.freedesktop.org/gstreamer/orc/tree/COPYING), which doesn't specifically name one.

**Comment by issyl0** [comment]
@SMillerDev pointed me to [the licensee gem](https://licensee.github.io/licensee/) which reports:

```
License:        NOASSERTION
Matched files:  COPYING
COPYING:
  Content hash:  ed4d8768c099ef9dae066db4b07031a78107a317
  License:       NOASSERTION
  Closest non-matching licenses:
    BSD-3-Clause-Clear similarity:  58.65%
    BSD-4-Clause similarity:        57.14%
    BSD-3-Clause similarity:        56.30%
```

**Comment by chenrui333** [comment]
yeah, that COPYING file, I did bit translation of the terms to the SPDX identifier.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
