### PR TITLE
julia 1.10.1

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `if [ -e "failed to open library: dlopen(libcholmod_cuda.dylib, 0x0001): tried: '/opt/homebrew/Cellar/julia/1.10.0/lib/julia/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/curl/lib/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/mbedtls@2/lib/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/openblas/lib/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/gcc/lib/gcc/current/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/lib/libcholmod_cuda.dylib' (no such file), '/usr/lib/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/Cellar/julia/1.10.0/lib/julia/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/curl/lib/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/mbedtls@2/lib/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/openblas/lib/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/gcc/lib/gcc/current/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/lib/libcholmod_cuda.dylib' (no such file), '/usr/lib/libcholmod_cuda.dylib' (no such file), 'libcholmod_cuda.dylib' (no such file), '/usr/local/lib/libcholmod_cuda.dylib' (no such file), '/usr/lib/libcholmod_cuda.dylib' (no such file), '/private/tmp/julia-20231226-5974-wdndkm/julia-1.10.0/base/libcholmod_cuda.dylib' (no such file)" ]; then REALPATH=failed to open library: dlopen(libcholmod_cuda.dylib, 0x0001): tried: '/opt/homebrew/Cellar/julia/1.10.0/lib/julia/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/curl/lib/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/mbedtls@2/lib/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/openblas/lib/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/gcc/lib/gcc/current/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/lib/libcholmod_cuda.dylib' (no such file), '/usr/lib/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/Cellar/julia/1.10.0/lib/julia/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/curl/lib/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/mbedtls@2/lib/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/openblas/lib/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/opt/gcc/lib/gcc/current/libcholmod_cuda.dylib' (no such file), '/opt/homebrew/lib/libcholmod_cuda.dylib' (no such file), '/usr/lib/libcholmod_cuda.dylib' (no such file), 'libcholmod_cuda.dylib' (no such file), '/usr/local/lib/libcholmod_cuda.dylib' (no such file), '/usr/lib/libcholmod_cuda.dylib' (no such file), '/private/tmp/julia-20231226-5974-wdndkm/julia-1.10.0/base/libcholmod_cuda.dylib' (no such file); REALPATH_wd="`pwd`" && REALPATH_=`readlink -n ${REALPATH} || true` && if [ -n "${REALPATH_}" ]; then REALPATH_wd=`dirname "${REALPATH}"`; REALPATH="${REALPATH_}"; fi && if [ -z "`echo ${REALPATH} | grep '^/'`" ]; then REALPATH=${REALPATH_wd}/${REALPATH}; fi && REALPATH_=`otool -D ${REALPATH} | tail -n +2 | sed -e 's/^@.*$//'` && if [ -n "${REALPATH_}" ]; then REALPATH_wd=`dirname "${REALPATH}"`; REALPATH=${REALPATH_}; if [ -z "`echo ${REALPATH} | grep '^/'`" ]; then REALPATH=${REALPATH_wd}/${REALPATH}; fi; fi && [ -e "$REALPATH" ] && rm -f "/private/tmp/julia-20231226-5974-wdndkm/julia-1.10.0/usr/lib/julia/libcholmod_cuda.dylib" && echo ln -sf "$REALPATH" "/private/tmp/julia-20231226-5974-wdndkm/julia-1.10.0/usr/lib/julia/libcholmod_cuda.dylib" && ln -sf "$REALPATH" "/private/tmp/julia-20231226-5974-wdndkm/julia-1.10.0/usr/lib/julia/libcholmod_cuda.dylib"; else if [ "" != "ALLOW_FAILURE" ]; then echo "System library symlink failure: Unable to locate libcholmod_cuda.dylib on your system!" >&2; false; fi; fi'
make[1]: *** [/private/tmp/julia-20231226-5974-wdndkm/julia-1.10.0/usr/lib/julia/libcholmod_cuda.dylib] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by pthariensflame** [comment]
@chenrui333 Ready now!

**Comment by pthariensflame** [comment]
Seems like it just timed out?

**Comment by chenrui333** [comment]
there are some rpath issues :)

**Comment by pthariensflame** [comment]
> there are some rpath issues :)

How do I find those?  The CI logs tell me nothing, and just say that one runner was cancelled.

**Comment by chenrui333** [comment]
it is in the PR review

image

**Comment by pthariensflame** [comment]
Someone mark this as “in progress”, please?

**Comment by pthariensflame** [comment]
I've given up on making modern SuiteSparse work with Julia 1.10, since there was another break at 7.3 and the Julia project *really* seems to not want to permit up-patching compatibility, reserving all the libraries that depends on SuiteSparse after 7.3 for Julia 1.11 and onward.

**Comment by pthariensflame** [comment]
@chenrui333 This should be ready for another attempt at merging.

**Comment by pthariensflame** [comment]
Any news?

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
