### PR TITLE
git-test 1.0.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed.

**Comment by DomT4** [comment]
`share.install "test.sh"`

Mind moving that to `pkgshare`? Not you who introduced the problem, but that's awfully generically named to end up in the top-level `share` directory.

**Comment by ilovezfs** [comment]
@DomT4 fixed

**Pull request closed without merging**
