### PR TITLE
zsh 5.4.2

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

---

### CODE REVIEW

**Comment by zmwangx** [comment]
Not announced yet.

**Comment by fxcoudert** [comment]
@zmwangx this will need to be rebased again master

**Comment by KamilKopaczyk** [comment]
zsh 5.4.2 has been released 25 days ago.
Can we push this PR through somehow? Maybe i could open another pull request with exact same changes?

**Comment by zmwangx** [comment]
@KamilKopaczyk http://zsh.sourceforge.net/Arc/source.html and http://www.zsh.org/mla/zsh-announce/ may disagree with you.

**Comment by zmwangx** [comment]
Maybe I should ask on the mailing list, though.

**Comment by ilovezfs** [comment]
>Maybe I should ask on the mailing list, though.

yeah that sounds like a good idea. seems to have been a while.

**Comment by zmwangx** [comment]
http://www.zsh.org/mla/workers/2017/msg01403.html

(Forgot to fill the text. Shame.)

**Comment by ilovezfs** [comment]
thanks :)

**Comment by zmwangx** [comment]
It is considered released. http://www.zsh.org/mla/workers/2017/msg01404.html

**Comment by KamilKopaczyk** [comment]
Great! Thanks for clarification and quick response :)

**Comment by zmwangx** [comment]
No problem. @ilovezfs So currently the bot doesn't build 10.13 bottles by default? https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/9227/

**Comment by ilovezfs** [comment]
@zmwangx it's a little busy https://jenkins.brew.sh/job/Homebrew%20High%20Sierra%20Testing/

**Comment by zmwangx** [comment]
Yeah, makes sense.

**Comment by ilovezfs** [comment]
:zzz:

**Comment by fxcoudert** [comment]
@zmwangx High Sierra bottle currently being built, will be merged shortly

**Pull request closed without merging**
