### PR TITLE
peru 1.2.0

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by zbeekman** [comment]
@BrewTestBot test this please

**Comment by zbeekman** [comment]
😅 I think I fixed my mistake...

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by chenrui333** [comment]
> 😅 I think I fixed my mistake...

Good to hear! Sorry for the trouble though.

**Pull request closed without merging**
