### PR TITLE
coq 8.9.0

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by javian** [comment]
```
15:49:29 ==> ./configure -prefix /usr/local/Cellar/coq/8.9.0 -mandir /usr/local/Cellar/coq/8.9.0/share/man -emacslib /usr/local/Cellar/coq/8.9.0/share/emacs/site-lisp/coq -coqdocdir /usr/local/Cellar/coq/8.9.0/share/coq/latex -coqide no -with-doc no
15:49:29 ./configure.ml: unknown option '-emacslib'.
```

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by JasonGross** [comment]
There is an entry in `CHANGES.md `:
> Removed the Emacs modes distributed with Coq. You are advised to use Proof-General (and optionally Company-Coq) instead. If your use case is not covered by these alternative Emacs modes, please open an issue. We can help set up external maintenance as part of Proof-General, or independently as part of coq-community.

Perhaps it would have been more clear for the CHANGES entry to also mention `-emacslib `, but as this option only applies to the emacs mode, it there is nothing for it to do inn versions 8.9 and later.

**Comment by Moisan** [comment]
@JasonGross : oops, thank you for pointing that out, I'll close the upstream issue.

**Comment by javian** [comment]
@brewtestbot test this please

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by mistydemeo** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
