### PR TITLE
Upgrade to mono 5.2.0.215, fsharp 4.1.25 and add msbuild d15.3

### PR DESCRIPTION
**Pull request by manchoz**
Upgrade mono and fsharp to latest stable/release and add msbuild.

[MSbuild](//github.com/mono/msbuild) is now needed in order to build [newest](https://github.com/fsharp/fsharp/commit/7975efc3989888603a6169238ac0fa4671c2fceb) fsharp releases. 

- mono 5.2.0.215
- fsharp 4.1.25
- msbuild d15.3

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Can you compare and contrast your PR to https://github.com/Homebrew/homebrew-core/pull/17378 please?

**Comment by manchoz** [comment]
Hi @ilovezfs,
this fixes build failure (due to missing openssl libraries for old dotnet cli -- see https://github.com/dotnet/cli/issues/1161) and use "official" method to install the app.

**Comment by baronfel** [comment]
@ilovezfs I'd recommend this PR, because msbuild isn't really an optional dependency anymore for F# or the greater .Net ecosystem overall since mono 5.0+ moved over to it wholesale.

These two PRs just get us into an actually-workable state without having to install the mono binary distribution package, which bundles a built msbuild executable.

**Comment by ilovezfs** [comment]
Would `msbuild` be of use elsewhere perhaps as a formula with a `make install` provided by upstream? The resource block for msbuild in this PR and the resource block for msbuild in #17378 are both pretty far outside the range of acceptable gymnastics as currently written.

**Comment by manchoz** [comment]
@ilovezfs AFAIK `msbuild` is replacing `xbuild` as standard building tool (also) in mono. It is provided as a separate package in official `mono` distributions for GNU/Linux too, so it would not so strange to provide it as separate formula in `brew`.

I have already wrote a `msbuild` formula for debugging purpose while looking for a solution for `msbuild` in mono formula. I could PR it after few changes. I'm worried that we still need a small patch for fixing missing reference to `openssl` libraries for old `dotnet` used in building, but I've currently embedded it in DATA section.

@baronfel, thank you for the endorsement!

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by manchoz** [comment]
Ping @ilovezfs. Do you thing we can merge this?

I was wondering that moving to a separate `msbuild` formula would request also to move to a separate `fsharp` formula. We need `mono` to build `msbuild` and we need `msbuild` to build `fsharp`. If we move `msbuild` out we will not be able to build `mono` and `fsharp` in the same formula anymore. Let me know.

**Comment by ilovezfs** [comment]
A separate fsharp formula would be OK.

The main issue is not about splitting them up. It's that the procedure for installing `msbuild` needs to be something like
```
./configure --prefix=somewhere
make
make install
```
not the jumping jacks for some very strange handling of the openssl dependency.

**Comment by ilovezfs** [comment]
Going to pass on this PR because the resource block involves patching that needs to be fixed upstream rather than in the formula but thanks nonetheless @manchoz

**Comment by manchoz** [comment]
Yes (even for a separate formula for `msbuild`) in the simplest solution I was able to get, we still need to patch one of the downloaded dyld with `install_name_tool` in order to fix wrong references to `openssl` libraries (one-line `inreplace` in one of the shell scripts).
This solution could be also applied in current bundled formula: would be acceptable enough?
Let me know, so I would push a PR for mono 5.2.0 SR4 (5.2.0.224).

**Comment by dsyme** [comment]
@ilovezfs Can we make another attempt to get F# and Mono updated?  F# is now at 4.1.32.

**Pull request closed without merging**
