### PR TITLE
docker-compose 1.7.0

### PR DESCRIPTION
**Pull request by marksteve**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by arnested** [comment]
Duplicate of #312 (and #312 has passing test cases).

**Comment by marksteve** [comment]
Test failures were caused by a failure in `git checkout` though. My issue with #312 is that it uses latest versions of the dependencies even though they are pinned in `requirements.txt`. Other than that, I'm ok with #312 being merged.

**Comment by arnested** [comment]
Ah. Sorry, @marksteve.

**Comment by marksteve** [comment]
No worries! I just want the latest version of compose in brew since it has `exec` w/c I've wanted ever since.

**Comment by tdsmith** [comment]
> My issue with #312 is that it uses latest versions of the dependencies even though they are pinned in requirements.txt

Is there one that you're concerned about?

**Comment by tdsmith** [comment]
(#312 should give you the same result as `pip install docker-compose`, which I think is what we should shoot for.)

**Comment by marksteve** [comment]
@tdsmith My bad! I just checked setup.py and it has different requirements from requirements.txt w/c is the only place I looked at. Please go ahead and merge #312 :D

**Pull request closed without merging**
