### PR TITLE
ghc 9.4.7

### PR DESCRIPTION
**Pull request by Bo98**
Also switch to LLVM 14 as we will probably won't be able to LLVM 12 and earlier on Sonoma.

### CODE REVIEW

**Comment by Bo98** [comment]
9.6.x is apparently nearly finished, but this PR is here if necessary.

**Comment by plajjan** [comment]
Why close? Isn't this complementary to 9.6 ? :)

I would appreciate merging 9.4.7 since I have a dependency on it (the current 9.4.4 is just a tad too old).

**Comment by fxcoudert** [comment]
Current situation: LLVM 12 is incompatible with macOS Sonoma headers (see https://github.com/Homebrew/homebrew-core/pull/149310#issuecomment-1744457460). Therefore, we have no current way to build `ghc` on macOS Sonoma.

This update and the switch to LLVM 14 would be a good way forward. Requires https://github.com/Homebrew/homebrew-core/pull/149332 to be merged first.

**Comment by fxcoudert** [comment]
```
  ===> Command failed with error code: 2
  /private/tmp/ghc-20231004-5664-gs64m4/ghc-9.4.7/docs/users_guide/9.4.5-notes.rst:47: WARNING: Bullet list ends without a blank line; unexpected unindent.
  /private/tmp/ghc-20231004-5664-gs64m4/ghc-9.4.7/docs/users_guide/9.4.5-notes.rst:67: ERROR: Unexpected indentation.
  /private/tmp/ghc-20231004-5664-gs64m4/ghc-9.4.7/docs/users_guide/9.4.5-notes.rst:88: ERROR: Unknown interpreted text role "ghc-ticet".
```

**Comment by Bo98** [comment]
It's large, but also quite contained so I think it'll apply. Giving it a shot now.

**Comment by iMichka** [comment]
Closing in favour of #141617, I am almost done with ghc 9.6.2. and @9.4, I was waiting for a long timeout slot since 2 days to try it again, but there is so much activity right now that I never got an opportunity.

**Comment by fxcoudert** [comment]
I'm happy if you want to preempt and test your run instead, but I'd rather leave it open for now, as a fallback. And also, we may want to provide this versioned formula, anyway.

**Comment by plajjan** [comment]
@iMichka I'm using stack and there is no stackage.org release for either 9.4.4 (9.4.5 is oldest 9.4 and brew is on 9.4.4) nor 9.6.2. I think this is rather unfortunate. Closing this in favor of 9.6.2 does not enable using stack in brew formulas for GHC 9.4 or newer. I'm stuck on 9.2.8.  Can't 9.4.7 be complementary to 9.6.2? Or is the plan to remove 9.4 completely once 9.6 is in?

**Comment by fxcoudert** [comment]
The pull request for 9.6.2 also contains 9.4.7

**Comment by plajjan** [comment]
@fxcoudert ah, got ya. Cool, thanks! :)

**Pull request closed without merging**
