### PR TITLE
grpc 1.40.0

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
`sysdig` fails to build on Linux with
```
/home/linuxbrew/.linuxbrew/bin/ld: ../libsinsp/libsinsp.a(cri.grpc.pb.cc.o): undefined reference to symbol '_ZN4absl12lts_202103245MutexD1Ev'
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libabsl_synchronization.so.2103.0.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
userspace/sysdig/CMakeFiles/csysdig.dir/build.make:136: recipe for target 'userspace/sysdig/csysdig' failed
make[2]: *** [userspace/sysdig/csysdig] Error 1
```
CC @Homebrew/linux

**Comment by iMichka** [comment]
Might have to do with the linker flags. Maybe the order? The missing symbol comes from `abseil`:

```
[ 99%] Linking CXX executable sysdig
cd /tmp/sysdig-20210915-64838-1rj5rj8/sysdig-0.27.1/build/userspace/sysdig && /home/linuxbrew/.linuxbrew/Cellar/cmake/3.21.2/bin/cmake -E cmake_link_script CMakeFiles/sysdig.dir/link.txt --verbose=1
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-5  -Wall -ggdb   -std=c++0x -O3 -fno-strict-aliasing -DNDEBUG -rdynamic CMakeFiles/sysdig.dir/fields_info.cpp.o CMakeFiles/sysdig.dir/sysdig.cpp.o -o sysdig  ../libsinsp/libsinsp.a ../libscap/libscap.a -lelf -lz -lcurl -ljsoncpp -ltbb -lcares -lgrpc++_unsecure -lgrpc_unsecure -lprotobuf -lcares -lgrpc++_unsecure -lgrpc_unsecure -lprotobuf -ljq -Wl,-Bstatic -lb64 -Wl,-Bdynamic -lrt -lanl -lssl -lcrypto -Wl,-Bstatic -lluajit -Wl,-Bdynamic -ldl -lpthread
[100%] Linking CXX executable csysdig
cd /tmp/sysdig-20210915-64838-1rj5rj8/sysdig-0.27.1/build/userspace/sysdig && /home/linuxbrew/.linuxbrew/Cellar/cmake/3.21.2/bin/cmake -E cmake_link_script CMakeFiles/csysdig.dir/link.txt --verbose=1
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-5  -Wall -ggdb   -std=c++0x -O3 -fno-strict-aliasing -DNDEBUG -rdynamic CMakeFiles/csysdig.dir/fields_info.cpp.o CMakeFiles/csysdig.dir/csysdig.cpp.o -o csysdig  ../libsinsp/libsinsp.a -lncurses -lform ../libscap/libscap.a -lelf -lz -lcurl -ljsoncpp -ltbb -lcares -lgrpc++_unsecure -lgrpc_unsecure -lprotobuf -lcares -lgrpc++_unsecure -lgrpc_unsecure -lprotobuf -ljq -Wl,-Bstatic -lb64 -Wl,-Bdynamic -lrt -lanl -lssl -lcrypto -Wl,-Bstatic -lluajit -Wl,-Bdynamic -ldl -lpthread
/home/linuxbrew/.linuxbrew/bin/ld: ../libsinsp/libsinsp.a(cri.grpc.pb.cc.o): undefined reference to symbol '_ZN4absl12lts_202103245MutexD1Ev'
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libabsl_synchronization.so.2103.0.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by carlocab** [comment]
Let's see if building with `gcc` helps.

**Comment by carlocab** [comment]
> It's possibly related to the fact that the `abseil` libraries use `$ORIGIN/../lib:/home/linuxbrew/.linuxbrew/Cellar/abseil/20210324.2/lib:/home/linuxbrew/.linuxbrew/lib` as their RPATH, and probably need `/home/linuxbrew/.linuxbrew/opt/abseil/lib` as well.

Why does it need the opt path too? Don't
```
/home/linuxbrew/.linuxbrew/opt/abseil/lib
```
and
```
/home/linuxbrew/.linuxbrew/Cellar/abseil/20210324.2/lib
```
point to the same place?

**Review by carlocab — APPROVED** [review]
Merging this so that users can `brew extract --version=1.40.0 grpc` if they need to, plus there might be additional issues with `1.41.0`.

**Pull request closed without merging**
