### PR TITLE
youtube-dl 2017.03.26

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
  |\_/|
 / @ @ \
( > º < )
 `>>x<<´
 /  O  \
```

**Comment by zmwangx** [comment]
```
                                                                                
                                      ...                                       
         ,:c, ...      ';,..         .;:,.                                      
        ...;c,,cl'    ..lxo',.       ,c::'                                      
        .cloclcoolc,.  .'ld,,l'.      c;'                                       
         ::,;l;,l:.,l;...,l,;ld:,.    c;,                                       
         ;:cdOo;l:  ,dl'..;c,;:lc:.   c:,                                       
         ',,''.,l:...lk:'..;l',:l;c.  c:,                                       
         .,....:oc;::xkc,',;:coddcc;  l;,                                       
         .;'..,ldl,. lxc,;coocc:;:;:. c;,                                       
         .:;:::ll   .xd:,,::,,cc:;;::.o:,                                       
          cdxxool  .odl,''''','',;:c;.oc,             .                         
           .',,'  .loc,''',,;;:;::cc:cdl:        ..,co,          ....           
                  ,:;;;,,':;;;,'..,'codddolcccllooodo,,'.....,,'''''.',,.       
               .::;,;,,;:;'...   ..:odddddl;::::::::c:...  ..,;ccc:;,...'.      
               clc;dxl:.        .';,oddoc,:ooo;:clooo,.      ..:xkkxoc;..,.     
               olccdl'.         .,,:;cc:cooooc:ool:lo,.        .;.;xkdcl;',     
         ..'.. cdcod;...       .,,';:ccccclll,oooccll;.        .,.,xko::c;.     
        '',lllclddxl;....     .':c:looolllol;clooolc;,..      .':xkdc,,:c'      
        'lox;;ldxkxl;.........';:c:coddoolllooolccc:;;,.......;:ldc::clc.       
         .cdc  .;c:,...',,''.',:ldoc:::::::;;::lc:,''.......,:ccccool;.         
          .''...........'''',:ldxoc:;;;;;;;:ldkkxc;,''''''';;:ccldo,            
       ...',;;;,,,,,;;;;;;,,':dkkkxdollllodkOO000Ol;'''''.....':ol....          
        ;;',,,lol;..':;.          ..:xdodx,..;kKKK0o;''''... ..''',,,,;.        
        .:;'. .loxolodxxl.           clcll     .:ldo:',,;;::::ccc;cccl'         
          :;,.  ....',,'             .l::            .,ooo:clll:;.:cc.          
          .:;'                        c:,          .;loo;.  ,odd::ll.           
           .:;,.                      cc;          lllo,      ':;lo:,.          
            ;c::;.';l,                c:,          looo:     .,.;c              
             .,;clcoxxl               c;,          ,kkx:     ::;c'              
                 ..,;,,.              :;,           ';.      ':,,:.             
                                      ::;                    .:ldx.             
                                      :;,                      .,.              
                                      ...                                       
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
     .                       ;c.       ,c'                                      
     'c'..                  .loo.     .cll;                                     
       'c...                ,oddo.    'cloo;                                    
         .c' ....           ;lodd:....;clodd'.,,,''''..                         
           .c:.  ;,...      ;clcc;,;co::clodl .loc;,'',;;,.                     
             .cco.  .c;;.  .llc;,cxkoc:;:lodd. ':lool:,'',:c'                   
               .lo:;:  .'lcool;;xkox:'c;:clod...c;;cllllcccclc.                 
                 .oOl;..'  ldlcolloxd:;c;;cll..,ol;,,;:cccllllo:.               
                   .oddl'. ;xdoc  .'';::,. ....,dxxolc::cloollloo;.             
                     ,oc;'..'cdl                coodxkOOkkxddololll,            
                    ',..       ...;cc,.         .colccclooooolcllcccc,          
                  .,'.         .lXMk,KK;          ,lol:;,,,,;:cooolcclc.        
                 ',..          .OMMMMMMl            .:odxxxkkOOkoclolloo'       
               .,,..             ck00x;               ..lxkxdxkxdl:cloodl.      
              .,'..                                     'lc:lxdll:;;;cddd,      
             .,..                                    ...';:lxxlclc:;;;cdd;      
           .,'..                                   ....,;:codolccllc:::ldc      
          .;'..                                  ..........'ldlcclolcccldd.     
         ,c;.             .........           ....,;,........cdlccodolllod.     
       .:lc:;.     ............................';cc:,.........,lolcclooooo.     
       :loocc:'.   .........................',:looc;'...........'dkxlcclol.     
      .ooKNKocc:,.........'',,,,,,,',,,,,;:cloddoc;'.............lkddxxxd,      
      .ooxOxlllllc:,..',,;:cclcccccc::;;;;lxxxdoc;,'............'c::coooc.      
       ;ooooooolooooooccllc;..             lxdol:;,'............',;clcodc.      
        .:ooooooddxxkOx:.                  'dxdlc:;,''......,;;::;'.  .::.      
           .';clddoc,.                      lxdolcc:;,''.....           .'      
                                            .oddollc:;;'..                      
                                              ';::;,..                          
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                            .....',,;;;,,,;:.   
                                                       ...',,,,,;:cc:;,''':dk,  
                                                   ..',,''',;;;::c::;,...,cdOc  
                                               ..:ldkO0KK0dcc;;,''''.....,lxO:  
                                            ..;oxdddxOKXNWXddl,.......  .;dOk.  
                                         ...;dkooxOKXNWWMMWdll..       ':ok0l   
                                       ....ld0xOKXNWWMMMMMKl:;.      ..;ck0O.   
                                    .''.',;od0XNNWWMMMMMN0xx:.    ...,:ldkO'    
                                  ..',,;:ccdkxkKXNWNNXKOkxl.   ...',;cldkk,     
                               .lk;..';ll;oodxxxO00OOkdc,.  ....',;:loxOx.      
                           .'lk00:',:cllodolc::;;;,'..   ....',,;:lodkOl        
              .clcc::::cldkOO0K0c:clooooooool;,'....  ....'',;:clodxOk'         
            .lxxkkkkkkOOOOO00XXdloodddooolcc::;''......'',,;:clodxOOc           
          .lxxxkkkkkkOOOO000XN0xdddddoolcc:;,'.'....',,;;:cllodkO0o.            
        .ldxxxxxxxkkkkOO00KXNKkxdddoolc:;,'''',;:c:;;::cllodxkO0o.              
      .;llloloooodddxxkOO0KNKkdooolcc:;,'',:oxolooddxxdodxkO0Ol.                
     ':;::c::cccllloodxkk0NXkolcc:;;,,;:ldxkkxddxxxkkO00OO0k;                   
    ,,,,,;;;;;;::::.  .'.okOl:;;;;;:cokOddkkkkkkOOOO00KKk:.                     
  .'.....''''',,,'  .c0KkKXd;;;:coxOKXO:ck00000000KKKx:.                        
  .                 ,O0O00XW0xxOKXNNXkxOKKKKKKKKKK0d.                           
                 .....ckOkxd0NNNNNN0xkKXXXXXKK00Ok,                             
              ...      .,:okKNNXKOd;dKXKK00OOOOOO:                              
            .'..         ;0XNXKxdo. :OOOOOOOOOOOk.                              
       ..  ,'..        :0KKKxc,,.  ,xkOOOOOOOOOOk.                              
        .,,,'...     .dKKOl... .:dkOOOOOOOOOOOOOk'                              
        ',....      .O0o,...   .loxkkOOOOOOOOOkd;.                              
      .::'....    .cd;....     .:ldxkkOOOOOOxc.                                 
      .;.''.......,...'.        ;loxkkOOOkl'                                    
      :,';;,'.,::,....          ;codxkxc'                                       
     .;'';,';'.  ..            .;clc,.                                          
     '.                        ...                                              
                                                                                
                                                                                
```

**Comment by ilovezfs** [comment]
They are beautiful!

**Comment by retokromer** [comment]
Remembers me the «telex art».

**Pull request merged**
