### PR TITLE
gh 0.11.0

### PR DESCRIPTION
**Pull request by mislav**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by vilmibm** [comment]
:wave: hiya, I'm on the `gh` team. I'm not sure how to address the build failures here so please let me know how/if I can help!

**Comment by SMillerDev** [comment]
Can you confirm this also happens locally? I suspect the makefile tries to do git operations and that's what's failing (as the working directory is just the unzipped archive)

**Comment by Bo98** [comment]
Looks like a change in the Makefile in 0.11 means that the `LDFLAGS` in the formula needs to now be `GO_LDFLAGS`.

**Comment by mislav** [comment]
@Bo98 Nice catch; thank you!

Core: CI is passing; please re-review!

**Comment by SMillerDev** [comment]
Could you squash your commits @mislav

**Comment by mislav** [comment]
Done!

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
Thanks @mislav  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by Bo98** [comment]
Merged now. Thanks!

**Comment by mislav** [comment]
Note that "[bottle publish failed](https://github.com/Homebrew/homebrew-core/runs/889730923?check_suite_focus=true)"— I'm not sure what that means

**Comment by SMillerDev** [comment]
The bot had an issue but Bo ran the merge manually.

**Comment by Bo98** [comment]
Yeah, it's just the internet not being perfect:

```
 curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.bintray.com:443 
```

I ran the publish commands locally instead so all's good.

**Pull request closed without merging**
