### PR TITLE
ruby: avoid conflict with already installed bundler

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @DomT4

### CODE REVIEW

**Comment by DomT4** [comment]
Seems reasonable to me.

**Comment by ilovezfs** [comment]
Strange that `system ruby, "setup.rb", "--prefix=#{buildpath}/vendor_gem"` has a side effect in the Cellar but I guess that's how gem works …

Maybe there's another option to pass along with --prefix to prevent that?

**Comment by ilovezfs** [comment]
And now we're back to breaking wpscan. I may just revert the gem upgrade to 2.7.3

**Comment by DomT4** [comment]
I'm back at home later today, I can take a poke around once I'm there, if this isn't super super urgent.

**Comment by ilovezfs** [comment]
Yeah, no worries. I'll just revert gem.

**Pull request closed without merging**
