### PR TITLE
arangodb 3.8.1

### PR DESCRIPTION
**Pull request by KVS85**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by bayandin** [comment]
```
/tmp/arangodb-20210903-15856-1szm2z1/ArangoDB-3.8.1/arangod/Graph/ConstantWeightShortestPathFinder.h:52:18: error: exception specification of explicitly defaulted move assignment operator does not match the calculated one
    PathSnippet& operator=(PathSnippet&& other) noexcept = default;
                 ^
1 error generated.
```

**Comment by KVS85** [comment]
@bayandin can you please review now.

**Review by bayandin — DISMISSED** [review]
Looks good, thanks @KVS85!

**Comment by carlocab** [comment]
Replaced by #84803.

**Pull request closed without merging**
