### PR TITLE
SDL_image: exactly link with libpng and other recommended libraries

### PR DESCRIPTION
**Pull request by s172262**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

I'm sorry that this is re-open #281.

### CODE REVIEW

**Comment by dunn** [comment]
`ocamlsdl` might need its revision bumped: http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1158/version=mavericks/testReport/junit/brew-test-bot/mavericks/linkage___test_ocamlsdl/

**Comment by ilovezfs** [comment]
Why do these need to be hard dependencies?

**Comment by illume** [comment]
The imageio loader in sdl_image breaks a lot of apps.

**Comment by MikeMcQuaid** [comment]
Closing due to unanswered questions.

**Pull request closed without merging**
