### PR TITLE
oh-my-posh 14.22.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by iMichka — DISMISSED** [review]

**Comment by p-linnane** [comment]
Bottles were uploaded, but the job failed to push the commit and label the PR.

cc @carlocab

**Comment by ZhongRuoyu** [comment]
Let me try out what I learned in https://github.com/Homebrew/homebrew-core/pull/126969#issuecomment-1489058995.

**Comment by ZhongRuoyu** [comment]
Oh, actually, the bottle commit has been pushed to this PR branch already. It's just that the label wasn't added.

**Comment by p-linnane** [comment]
@ZhongRuoyu Can you :+1: this again?

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
This is the second time I saw `gh` fail adding a PR tag. The first was in #126740. I once said in https://github.com/Homebrew/homebrew-core/pull/126740#issuecomment-1484229847 that we may consider adding a retry mechanism "if we see this one more time". But, uh, I'm a bit unsure, and reluctant -- this is not the only `gh` invocation, so should we do that to all? I think it'd be super weird to retry things everywhere just because of some potential issue on GitHub's side. (If there's an outage, retries probably wouldn't work either.) So, in my opinion, unless it occurs frequent enough to be annoying, we should probably leave this as it is, treat this as any other GitHub Actions failures we encounter from time to time, and manually retry in case this happens again.

**Comment by carlocab** [comment]
It might be useful to add a `shell-retry` action that retries a shell command (or shell script) to Homebrew/actions a few times after failure. That could simplify the waiting step in the workflow too.

**Pull request merged**
