### PR TITLE
sonar 6.0

### PR DESCRIPTION
**Pull request by Godin**
Also fix Java version - Java 1.8 is required starting from SonarQube 5.6.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
CC @xu-cheng for thoughts on the failure here; could it be updated to state which file has that linkage?

**Comment by DomT4** [comment]
I ignored this the other day; I think it's an upstream packaging problem which isn't actionable by us, although potentially should be reported upstream. I'll hunt through the upstream download in a bit & try to find where the link is coming from.

**Comment by Godin** [comment]
@DomT4 if by upstream here you mean SonarQube, then my best guess that this link might come from its usage of Java Service Wrapper. I could check this deeper tomorrow.

**Comment by Godin** [comment]
I confirm that broken link comes from Java Service Wrapper:
```
$ otool -L -arch ppc64 sonarqube-6.0/bin/macosx-universal-64/wrapper
sonarqube-6.0/bin/macosx-universal-64/wrapper:
	/usr/lib/libgcc_s_ppc64.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)

$ otool -L -arch ppc64 sonarqube-6.0/bin/macosx-universal-64/lib/libwrapper.jnilib
sonarqube-6.0/bin/macosx-universal-64/lib/libwrapper.jnilib:
	/usr/lib/libgcc_s_ppc64.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)
```

Not sure that we (SonarQube) can fix this in short/mid term, because we use Java Service Wrapper provided only as a binary distribution - https://github.com/sonatype/jsw-binaries , and it doesn't receive any updates/changes due to the change of JSW license - this is the last version, which is compatible with LGPL.

However given that those files are in universal binary formal and contain multiple versions for different architectures:
```
$ otool -L -arch x86_64 sonarqube-6.0/bin/macosx-universal-64/lib/libwrapper.jnilib
sonarqube-6.0/bin/macosx-universal-64/lib/libwrapper.jnilib:
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)

$ otool -L -arch x86_64 sonarqube-6.0/bin/macosx-universal-64/wrapper
sonarqube-6.0/bin/macosx-universal-64/wrapper:
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)
```
don't think that this creates any problem - PPC arch never will be selected for Mac OS X >= Lion.

**Comment by MikeMcQuaid** [comment]
> I'll hunt through the upstream download in a bit & try to find where the link is coming from.

Bonus points if you can fix the warning to make that obvious 😉

**Comment by Godin** [comment]
@MikeMcQuaid well, I quickly looked on how this check implemented in brew, so might try, but can't promise 😉

**Comment by MikeMcQuaid** [comment]
@Godin Sorry, that was directed at @DomT4 but you're welcome to do so too!

**Comment by Godin** [comment]
@MikeMcQuaid FWIW I think that this goes down to
https://github.com/Homebrew/brew/blob/29bfc4caa3f7dde97ad4fd62d7da0adededbeede/Library/Homebrew/vendor/macho/macho/fat_file.rb#L159
called from (my naive and just visual backtrace) :
https://github.com/Homebrew/brew/blob/29bfc4caa3f7dde97ad4fd62d7da0adededbeede/Library/Homebrew/os/mac/ruby_mach.rb#L55
https://github.com/Homebrew/brew/blob/91a47a9ed6d85c1bf8f507cdfef4462a07f61831/Library/Homebrew/os/mac/linkage_checker.rb#L26
maybe the first one might simply use
https://github.com/Homebrew/brew/blob/29bfc4caa3f7dde97ad4fd62d7da0adededbeede/Library/Homebrew/vendor/macho/macho/fat_file.rb#L184
instead.

And at this point I'm wondering if relaxation of this warning blocker for this PR ?

**Comment by MikeMcQuaid** [comment]
@Godin Not a blocker, thanks for digging in!

**Comment by UniqMartin** [comment]
Sorry for the late input; I just found this. Assuming you don't actually support PPC64 with the rest of your code, I think the best solution to avoid the audit failure would be to remove the PPC64-specific Mach-O slice from the fat (universal) binaries by using `lipo(1)`. Ideally, this would be already done by upstream if my assessment is correct. We could also do this in the formula, but that would mean it would lose its `bottle :unneeded` status and this would be a pity.

**Comment by MikeMcQuaid** [comment]
@UniqMartin If it's `cellar :any` I think it's fine to lose.

**Comment by Godin** [comment]
@MikeMcQuaid thank you for merge!

@UniqMartin You are right - PPC64 part can be removed. How come I forgot about `lipo`?
I doubt that it was done in https://github.com/sonatype/jsw-binaries , which is used by SQ, because it already uses its latest release - https://github.com/SonarSource/sonarqube/blob/6.0/sonar-application/pom.xml#L127
It might be tricky to promote such change up to sonatype/jsw-binaries since it is probably not maintained having latest release 6 years ago.
But I could try to do this change in SonarQube. This seems more correct than change in formula.

**Comment by MikeMcQuaid** [comment]
> But I could try to do this change in SonarQube. This seems more correct than change in formula.

hqdefault

**Comment by Godin** [comment]
For the record - ticket on SQ side: https://jira.sonarsource.com/browse/SONAR-7959

**Pull request merged**
