### PR TITLE
llnode 2.0.0

### LINKED ISSUE #31617: llnode fails to build on 10.14
```
==> make plugin
node scripts/configure.js
Build dir is: /private/tmp/llnode-20180831-94315-j3e66y/llnode-1.7.1
Using lldb executable lldb

Looking for llvm-config...
No llvm-config found

Reading lldb version...
Deduced lldb version from Xcode version: Xcode 10.0 -> lldb 3.9
Installing llnode for lldb, lldb version 3.9

Looking for headers for lldb 3.9...
Could not find the headers, will download them later

Looking for shared libraries for lldb 3.9...
Could not find the shared libraries 
llnode will be linked to the LLDB shared framework from the Xcode installation

Skip cloning lldb headers because /private/tmp/llnode-20180831-94315-j3e66y/llnode-1.7.1/lldb-3.9 exists
Writing config.gypi:
{
  "variables": {
    "lldb_include_dir%": "/private/tmp/llnode-20180831-94315-j3e66y/llnode-1.7.1/lldb-3.9/include"
  }
}
Writing llnode.sh shortcut to /private/tmp/llnode-20180831-94315-j3e66y/llnode-1.7.1/llnode.sh
```

```
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
  CXX(target) Release/obj.target/plugin/src/llnode.o
  CXX(target) Release/obj.target/plugin/src/llv8.o
  CXX(target) Release/obj.target/plugin/src/llv8-constants.o
  CXX(target) Release/obj.target/plugin/src/llscan.o
  SOLINK(target) Release/plugin.dylib
ld: framework not found LLDB
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Release/plugin.dylib] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/10.9.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/Cellar/node/10.9.0/bin/node" "/usr/local/opt/node/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/llnode-20180831-94315-j3e66y/llnode-1.7.1
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
make: *** [plugin] Error 1
```

### PR DESCRIPTION
**Pull request by chrmoritz**
Created with `brew bump-formula-pr`.

Fixes #31617.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Don't we need to have a newer version of lldb for `DevelopmentTools.clang_build_version >= 1000`?

**Comment by chrmoritz** [comment]
Yeah likely. Can you tell me the correct revision to use for `>= 1000`? If I understand #22892 correctly, it was more or less a good guess last time.

**Comment by fxcoudert** [comment]
`release_60` seems like a reasonable guess…

**Comment by fxcoudert** [comment]
I think we should also modify `target = if DevelopmentTools.clang_build_version >= 900`

**Comment by chrmoritz** [comment]
> I think we should also modify `target = if DevelopmentTools.clang_build_version >= 900`

Nope, the [upstream target for XCode 8.3+](https://github.com/nodejs/llnode/blob/master/scripts/darwin.js#L72-L73) is still `lldb-3.9`.

**Pull request closed without merging**
