### PR TITLE
glances: add all the optional plugins

### LINKED ISSUE #35800: "glances" is missing optional functionality
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- "brew gist-logs glances" said: "Error: No logs."
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

The "glances" tool has some optional functionality that is only enabled if the user installs some optional third-party Python packages.  For example:
```
$ pip install docker         # for Docker support
$ pip install netifaces   # for IP support
```
I'm not sure what all the other packages are.  I installed "wifi" to get wifi support, and the glances log file stopped complaining that it was missing, but I see nothing new in the display.

Could the glances formula include these optional packages to enable Docker and IP support (and whatever other ones make sense)?  Thanks.

/cc @lembacon

### PR DESCRIPTION
**Pull request by apjanke**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes #35800.

glances looks like it would be more useful with all its optional plugins. Shall we add them?

Increases the keg size from 7.5 MB to 70 MB. Seems reasonable; disk is cheap.

One downside: it slows down `glances` startup by a couple seconds.

### CODE REVIEW

**Review by fxcoudert — APPROVED** [review]

**Comment by nedbat** [comment]
You left out the one I really wanted: docker.  The glances authors believed it was Linux only, but it is not. It works on Mac.

**Comment by apjanke** [comment]
Can you give me an example of how to use the glances Docker plugin so I can test it out?

**Comment by apjanke** [comment]
Okay, I tested it locally using the Docker tutorial and it does seem to work fine.

Here you go: #35907.

**Comment by nedbat** [comment]
You run some containers with docker.  Then run glances, you should have a new panel that shows the containers running.

For example:  `docker run redis`  will download the redis container, and run it.  Then when I run glances, I see:
image

**Comment by apjanke** [comment]
Gotcha. I see the same thing when testing locally on macOS 10.13.6.

**Comment by apjanke** [comment]
I put in an upstream PR to change the "Linux-only" labeling: https://github.com/nicolargo/glances/pull/1390.

**Comment by nedbat** [comment]
Amazing! Thanks :)

**Pull request closed without merging**
