### PR TITLE
dnsviz 0.11.0

### PR DESCRIPTION
**Pull request by cdeccio**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by bevanjkay — APPROVED** [review]

**Comment by cdeccio** [comment]
One dependency changed between 0.10.0 and 0.11.0, hence the extra commit _after_ running `brew bump-formula-pr --version 0.11.0 dnsviz`.

**Comment by bevanjkay** [comment]
Thank you @cdeccio - I am trying with our `cryptography` formula, and have also adjusted the `pypi_formula_mappings` file so the `brew update-python-resources` doesn't re-add M2Crypto.

**Comment by cdeccio** [comment]
Thanks so much, @bevanjkay !

**Comment by bevanjkay** [comment]
@cdeccio I just tested the install locally on MacOS 15 - and when running `brew test` the first command resulted in a panic and full system crash. This seems consistent with what is happening on CI.

**Comment by cdeccio** [comment]
> @cdeccio I just tested the install locally on MacOS 15 - and when running `brew test` the first command resulted in a panic and full system crash. This seems consistent with what is happening on CI.

Whoops, I see now that 1) cryptography is its own package in brew, as opposed to being a python package, so I needed to use `depends_on` instead of `resource` and 2) I should have tested better (it took me a minute to figure out how to test it with the new (to me) system 😅 ).  I think I've figured it out now... except that I'd like to test using pytest, and I'm not sure how to include a `resource` that is for testing only.  Do I not worry about the fact that it's really just for testing and just install it anyway, as a vanilla `resource`?   Or is there a way to mark it for testing only?

**Comment by cdeccio** [comment]
@bevanjkay 

> @cdeccio I just tested the install locally on MacOS 15 - and when running `brew test` the first command resulted in a panic and full system crash. 

I misunderstood and thought you were just using strong words to suggest that the test failed.  I see now that by "full system crash", you mean that it crashed MacOS -- completely.  I just reproduced it here too with MacOS 14.  I have no idea what would cause MacOS to crash like that, especially considering it did not crash with the old formula or test.  The only thing that has really changed since the last time (July 2024) is that cryptography has replaced M2Crypto.  Could be that dependencies have changed in the mean time too.

I don't have an answer for this yet.  Obviously, it would be nice to know what is causing this fundamentally.  But I might just mess with the tests to see if I can find tests that work without crashing the system.  So weird.

**Comment by cdeccio** [comment]
I updated the tests.  It looks like they didn't crash the system!  Oh, and they also passed 😅   Hopefully that's good enough to get this merged now.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
