### PR TITLE
mesa-glu (new formula)

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
- What is the difference between any_of: and all_of: for licences?
- This package was called glu in homebrew-xorg, I renamed it to libglu because this is probably more correct, and is also what debian does.

**Comment by chenrui333** [comment]
> What is the difference between any_of: and all_of: for licences?

it would be usually dual-licensed situation, `all_of:` would be applicable when there are many license declarations in the repo.

cc @fxcoudert @Rylan12

**Comment by fxcoudert** [comment]
In this specific case, it's `all_of:` because you need to comply with all the individual licenses listed. `any_of:` is for dual-licensed, when the licensor gives you several options to choose from.

**Comment by iMichka** [comment]
Then it's `all_of`.

@gromgit proposed to call this `mesalib-glu`, I named it `libglu`. Thoughts?

**Comment by jonchang** [comment]
| Library |         Homebrew | MacPorts |                       Debian | Fedora      |
|---------|-----------------:|---------:|-----------------------------:|-------------|
| libGL   |             mesa |     mesa |     libgl (source: libglvnd) | mesa-libgl  |
| libGLw  |      mesalib-glw |      glw |         libglw (source: glw) | mesa-libglw |
| libGLU  | libglu (this PR) |   libglu | libglu-mesa (source: libglu) | mesa-libglu |

I checked other package managers for their `libgl*` situation and this is what I came up with. Note that Debian actually does something interesting where the provide NVIDIA's vendor neutral graphics dispatch library, which then calls into mesa or whatever you want to provide your openGL bindings. I think we want to avoid that route since it sounds really complicated.

Personally I kinda like just calling the formula mesa-libgl* (and then maybe having an alias from e.g. libgl to mesa-libgl?)

**Comment by carlocab** [comment]
I quite like the Fedora approach to naming them, where the libraries are called `mesa-libgl*`. I think the prefix `mesa-` is useful because it clearly identifies them as the mesa implementation of the aforementioned libraries.

That said, I'm also happy for `libg*` to be aliased to `mesa-libg*` in the absence of alternative `libg*` providers. (Though that instance would raise the issue of how the `libg*` alias should resolve.)

I also like the Debian approach, but that assumes that there's someone around who can implement and maintain it for Homebrew. This approach would also avoid the issue of figuring out how to resolve aliases, but at this point, that is a purely hypothetical problem.

**Comment by gromgit** [comment]
My thoughts:
* The Mesa docs seem to indicate that it's the overarching project, with GLU and GLw its subcomponents.
* All of them are pure-library deliverables, so adding `lib` to the canonical names seems redundant.
* No core formula currently specifies `depends_on "mesalib-glw"`.
* Reworking `libGLU`-dependent formulae will happen anyway.
* Canonical names should give users a clear sense of what project they're looking at, since that's what they'll get when they `brew info <alias>`.

So I'm in favor of `mesa`, `mesa-glu`, `mesa-glw` as the canonical names, with aliases `libgl`, `libglu`, `libglw` if desired. This seems to result in zero additional work (outside aliasing and renaming the abovementioned formulae) and core disruption.

**Comment by sjackman** [comment]
The upstream Git repo is called https://cgit.freedesktop.org/mesa/glu/, so based on that `mesa-glu` seems like a good name, as suggested by @gromgit. https://github.com/Homebrew/homebrew-core/pull/64308#issuecomment-724401095

**Comment by maxim-belkin** [comment]
How about `mesa-gl`, `mesa-glu`, and `mesa-glw`, plus a `mesa` ~> `mesa-gl` alias, plus other aliases as necessary.

**Comment by carlocab** [comment]
I don't have a strong opinion regarding redundancy in the names, but I do want to say that redundancy can sometimes be a good thing. However, I think that a good naming scheme should at least satisfy two criteria:

1. it is clear that these are the mesa implementations of the libraries; and,
2. a user can find them by doing `brew search libgl`.

`mesa-gl`, etc plus suitable aliases would satisfy this, so it sounds like a good solution to me.

**Comment by iMichka** [comment]
I went for `mesa-glu`. I like how the fedora people made it consistent.
I also added a `libglu` alias.

**Comment by jonchang** [comment]
> So I'm in favor of mesa, mesa-glu, mesa-glw as the canonical names

Thinking about it more, I like this, especially since the Mesa formula ships not only libgl but a bunch of stuff too. Agnostic on the aliases, we can add them later if someone requests.

**Pull request closed without merging**
