### PR TITLE
rtags 2.8

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@vladshablinsky do you mind taking a look at this? It looks like the test has broken on us again :(

**Comment by vladshablinsky** [comment]
😕
Will take a look later today. Should be a different reason now.

**Comment by ilovezfs** [comment]
thanks!

**Comment by vladshablinsky** [comment]
I think I'm not able to fix it right now. I have no idea why it fails now. The same things worked for us several weeks ago. :| Seem like there is no related issues upstream.

When I try to run `rc -c cmake -c src/foo.c` I get `couldn't find process for pid 68347` in `rdm`'s  logs. Maybe this fact can help fixing it, but for now I don't know the fix.

```
➜ vlad:Homebrew$ rdm             rb_in_name ✗
Running with 4 jobs, using args: -ferror-limit=50 -Wall -fspell-checking -Wno-unknown-warning-option
Includepaths: -isystem /usr/local/Cellar/llvm/3.9.0/lib/clang/3.9.0/include/
couldn't find process for pid 68347
```

**Comment by ilovezfs** [comment]
@vladshablinsky OK, no problem. Thanks for taking a look.

**Comment by ilovezfs** [comment]
@vladshablinsky upstream fixed it today in https://github.com/Andersbakken/rtags/commit/cddf96a

**Pull request closed without merging**
