### PR TITLE
dump1090-mutability: deprecate

### PR DESCRIPTION
**Pull request by p-linnane**
Last release on 2021-01-26.

### CODE REVIEW

**Comment by alebcay** [comment]
Apart from not having a release in a while, is there an explicit statement of end of support for this? We do have a lot of "old" software that hasn't been updated in a while ([El Capitan bottles, anyone?](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-core+sha256+el_capitan%3A&type=code)) but I don't think we have a precedent of deprecating only due to age.

It also looks like the build process is relatively simple and does not involve any patches/workarounds that pose a maintenance burden, although maybe I'm missing something here (if such factors exist, perhaps they should be mentioned in the deprecation comment too).

**Comment by p-linnane** [comment]
I'm running through `homebrew-core` trying to fix formulae that aren't returning version information. I based this "last release" date off of the timestamp on the files in the archive, but it might be even older. 

See also https://github.com/Homebrew/homebrew-core/pull/130366 & https://github.com/Homebrew/homebrew-core/pull/130365, etc.

**Comment by carlocab** [comment]
> I don't think we have a precedent of deprecating only due to age.

I think the issue is that we lack a clear policy about deprecations. I've seen a number of formulae that have been deprecated merely due to age. We should probably clarify our policy here. CC @Homebrew/core

Personally: for some formulae (e.g. those written in relatively portable C, or shell scripts), age alone probably shouldn't be enough of a reason to deprecate. If it still builds as-is and has no outstanding CVEs, then we should probably avoid deprecation.

> It also looks like the build process is relatively simple and does not involve any patches/workarounds that pose a maintenance burden, although maybe I'm missing something here (if such factors exist, perhaps they should be mentioned in the deprecation comment too).

Agreed.

**Comment by p-linnane** [comment]
I'm of the opinion that if it's not actively supported we should deprecate it. It's unlikely that these lesser used formulae (this has 225 installs over the last year), will have any kind of security review that would uncover CVE's. I may be in the minority here, but let's see what others think.

**Comment by samford** [comment]
I agree with what Caleb and Carlo already mentioned.

I may be misremembering but I believe Mike tends to favor the view that we shouldn't deprecate a formula simply due to age if there aren't other meaningful issues (e.g., build failures), so I usually try to adhere to that. Some of the ones that you'll encounter haven't had a release in 10+ years and we will probably continue to keep those formulae around (and simply add a `#skip` `livecheck` block), so 2021 still feels fairly recent.

**Comment by Bo98** [comment]
Yeah don't agree with age as a metric. Some formulae can reach a point where further updates aren't necessarily required. If GNU's `hello` wasn't updated in 20 years I wouldn't see any issue with it.

Excluding extraordinary scenarios, I would generally agree with deprecations if:
- Upstream state it is no longer supported (`devtodo` satisfies this)
- It is clear that there are some form of somewhat-major outstanding issue (build failure, security issue, bugs that have resulted users to use an alternative package, or use of deprecated dependencies) and it appears that the upstream has been abandoned maintenance.

`dbxml` is still advertised upstream and there's no indication that development has ceased (though the same could be said by the Java Edition, which has been replaced by KVLocal), however it requires a patch to build on modern compilers so I understand arguments of abandonment. There's an additional bug that we haven't patched where it can return incorrect results, which Oracle posted about on their forums but didn't issue a new release (https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/development/libraries/dbxml/incorrect-optimization.patch). So I don't really have that much issue deprecating that one as it appears to be on us to patch for issues. And, in general, the Berkeley DB stuff is very much something I'd like to depend on as little as possible (we already are forced to ship an older version for legal reasons).

As for this formula (`dump1090-mutability`), it points to an Ubuntu package which to me already raises alarms. It is very rare that Ubuntu themselves are the maintainers behind a particular software and indeed the original source is actually https://github.com/mutability/dump1090, which indicates it has been deprecated and replaced by `dump1090-fa`, which we don't yet offer.

**Comment by p-linnane** [comment]
General consensus seems to be that age should not be a reason on it's own for deprecation. Thank you to everyone for contributing your thoughts. These formulae that are old and cannot be live checked will be skipped instead of deprecated.

Are we ok with deprecating this formula based off of @Bo98's comment?

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
I agree that age shouldn't be the sole reason. I'm ok with deprecating this formula, but I removed it from the merge queue to see if there's a different opinion.

**Comment by MikeMcQuaid** [comment]
> I may be misremembering but I believe Mike tends to favor the view that we shouldn't deprecate a formula simply due to age if there aren't other meaningful issues (e.g., build failures), so I usually try to adhere to that.

Yes, I strongly agree. We should avoid deprecating/disabling/removing formulae that are used and have no issues.

If they continue to compile on newer macOS versions/compilers/etc. without modification by us or others and they continue to be used by a reasonable number of people: we should not remove them.

As a principle behind the principle: Homebrew's primary goal is to be useful to people. If you're stuck on a decision: ask yourself whether it makes Homebrew more or less useful. To me, deprecation on a formulae that's used (https://formulae.brew.sh/analytics/install-on-request/365d/), we're not getting support issues about and there are no outstanding CVEs makes Homebrew less useful, not more. 

> however it requires a patch to build on modern compilers so I understand arguments of abandonment.

I'm not going to attempt to block this change specifically if more agree it should be removed rather than added but, given the above, I think the time for a debate like this is when a new patch is added/needed rather than looking at an existing formula with a patch and going "oh, let's deprecate it".

I was cautiously 👍🏻 on this until I spelled out my own reasoning above and, yeh, I don't think Homebrew is made better for having this deprecated.

I could be talked into the idea that deprecation is a good idea for formulae like this if we e.g. have a list of "deprecated but will never be disabled/removed until it actually breaks" formulae where, please correct me if I'm wrong, my understanding is that deprecation effectively starts a timer that will result in an inevitable disabling and removing until upstream becomes active again.

**Comment by Bo98** [comment]
> I'm not going to attempt to block this change specifically if more agree it should be removed rather than added but, given the above, I think the time for a debate like this is when a new patch is added/needed rather than looking at an existing formula with a patch and going "oh, let's deprecate it".

It's more a piece of evidence of being unmaintained rather than a reason itself. Particularly since we've been quite vocal against applying patches that upstream haven't adopted.

In this particular case, there's a patch to fix a significant bug that we're not applying that other package managers have.

Why has no one complained? Turns out it's been installed 20 times in the last year, and that probably includes CI.

**Comment by MikeMcQuaid** [comment]
> It's more a piece of evidence of being unmaintained rather than a reason itself.

Ok cool 👍🏻 

> Particularly since we've been quite vocal against applying patches that upstream haven't adopted.

I agree with this but: we have (intentionally) set a much higher bar for "adding new patches" than "removing existing working patches" or "removing existing working formulae with patches".


> But yes, nothing should be deprecated _because_ it contains a patch - more because of complications from it

Agree 👍🏻 

> Why has no one complained? Turns out it's been installed 20 times in the last year, and that probably includes CI.

Yeh, the install counts here are low enough that I'm not going to object at all if it's removed. I'm still very slightly leaning towards "leave it as-is" but I'm not involved enough in day-to-day homebrew-core work to feel comfortable making the call either way (beyond spelling out principles above).

I would say it feels like this conversation would do well being summarised in our documentation somewhere for future cases like this and do have a consistent process between formulae/maintainers.

**Comment by MikeMcQuaid** [comment]
> Are we interested in un-deprecating the other recently deprecated formulae?

I think it's worth considering based on above criteria 👍🏻

**Comment by p-linnane** [comment]
> > Are we interested in un-deprecating the other recently deprecated formulae?
> 
> I think it's worth considering based on above criteria 👍🏻

https://github.com/Homebrew/homebrew-core/pull/130469

**Pull request closed without merging**
