### PR TITLE
commitizen: add shell completions

### PR DESCRIPTION
**Pull request by singingwolfboy**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  brew: command not found: {"SHELL"=>"bash"}
  Error: Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /home/linuxbrew/.linuxbrew/opt/python-argcomplete/bin/register-python-argcomplete cz --shell bash` exited with 127. Here's the output:
```

**Comment by singingwolfboy** [comment]
I really don't understand why this is failing; I'm just calling `generate_completions_from_executable()`, which comes from Homebrew itself. [It works fine with the `pipx` formula.](https://github.com/Homebrew/homebrew-core/pull/150303) Any idea what the problem is, and how I can fix it?

**Comment by SMillerDev** [comment]
@Homebrew/brew it seems that the command is incorrectly escaping the environment variable that precedes it. Any ideas?

**Comment by MikeMcQuaid** [comment]
> @Homebrew/brew it seems that the command is incorrectly escaping the environment variable that precedes it. Any ideas?

@SMillerDev Sorry: which command/environment variable?

**Comment by SMillerDev** [comment]
```console
  Error: Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /opt/homebrew/opt/python-argcomplete/bin/register-python-argcomplete cz --shell=bash` exited with 127. Here's the output:
```
In the error. It is my understanding that the object before the command is actually an environment variable, and shouldn't be part of the command.

**Comment by Bo98** [comment]
> It is my understanding that the object before the command is actually an environment variable, and shouldn't be part of the command.

I think that's just a cosmetic issue with the error output.

I think the issue is `register-python-argcomplete` might have a shebang of a specific Python at runtime (probably 3.12) but the formula has no runtime dependencies: https://github.com/Homebrew/homebrew-core/blob/432ae83daa58863275c492c46e43050532bd7fff/Formula/p/python-argcomplete.rb.

`generate_completions_from_executable("python3.11", register_argcomplete, "cz", ...` probably works

**Comment by singingwolfboy** [comment]
> `generate_completions_from_executable("python3.11", register_argcomplete, "cz", ...` probably works

That appears to work! Seems like there's a bug with the error output. Unfortunately, I'm not sure how to fix that bug...

**Comment by Bo98** [comment]
It's sort of correct really. `exited with 127` is returned by the shell when it can't find the executable, which in the case of text executables means the shebang. Nothing gets output to stdout in those scenarios (and stderr is not supported unless you do `HOMEBREW_STDERR=1` though not sure if anything gets output there either or not).

Cosmetically, the error output should probably format the env hash as `SHELL=bash` instead of a Ruby hash, but that's about it.

**Review by Bo98 — APPROVED** [review]

**Pull request merged**
