### PR TITLE
wdc.rb new-formula

### PR DESCRIPTION
**Pull request by designerror**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by zmwangx** [comment]
Why are you opening a new PR?

**Comment by designerror** [comment]
because for too long we have to wait for the check from @mistydemeo.

**Comment by designerror** [comment]
https://github.com/Homebrew/homebrew-core/issues?utf8=✓&q=mentions%3Amistydemeo%20

**Comment by zmwangx** [comment]
That doesn't justify a new PR. We will merge when we think it's good, not when there's no "request changes" left.

**Comment by designerror** [comment]
I was hoping that You help the development of open-source.

**Comment by zmwangx** [comment]
I don't see why helping the development of open source means we need to play by your rules in our project, unfortunately.

**Comment by designerror** [comment]
then I'll wait.

**Comment by designerror** [comment]
@zmwangx, my apologies.

**Comment by zmwangx** [comment]
It's okay.

**Pull request closed without merging**
