### PR TITLE
maven-completion 20200420

### PR DESCRIPTION
**Pull request by mvitz**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
https://github.com/juven/maven-bash-completion/issues/79 needs to be fixed before this can be merged.

**Comment by mvitz** [comment]
Thanks for thee feedback. I will try to get the mentioned issue fixed.

**Comment by mvitz** [comment]
@SMillerDev They've created a tag `20200420` and I updated my PR with the tag.

**Comment by SMillerDev** [comment]
`brew style` is failing on ci.

**Comment by mvitz** [comment]
Sorry, my failure. I fixed and force pushed a fixed version.

**Comment by chenrui333** [comment]
@mvitz Thanks for your contribution to Homebrew! :tada: 🥇

**Pull request merged**
