### PR TITLE
cfn-lint 0.19.1 (new formula)

### PR DESCRIPTION
**Pull request by Shane4STER**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Shane4STER** [comment]
Updated test to actually verify small template rather than test help

**Comment by Shane4STER** [comment]
Fix errors introduced in 32bf0a9 causing audit to fail.

**Comment by Shane4STER** [comment]
@fxcoudert Sorry to tag you directly, is there anyway to bump this for review? or should it be closed and reopened?

**Comment by fxcoudert** [comment]
It's OK, merging. Thanks @Shane4STER

**Pull request closed without merging**
