### PR TITLE
snescom: delete

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

0 installs in the last 30 days, patch is 404, and last release in 2014.

### CODE REVIEW

**Comment by clobber** [comment]
Just as an FYI and probably not a reason to keep the formula:

I was curious and noticed that protomouse change their GitHub account name to @vrcsix, so the patch now lives at https://gist.githubusercontent.com/vrcsix/31335db2fe5c11978faf/raw/f0671999314e87c0487035e4f80f92a67a0c4d06/snescom-disasm-missing-cstdlib.diff

Very annoying thing that happens with GitHub gist's when people change their account names. I wonder if gist patches that are used within brew formulas should probably be filed under 'anonymous' so at least they can't be lost if someone changes their GitHub name.

**Comment by vrcsix** [comment]
Oops! Apologies for breaking this.

**Comment by kattrali** [comment]
I don't know when @vrcsix changed their username, but I installed this formula in the last couple months and just noticed its been deleted. Does a formula need to be installed regularly (and show up in metrics) to remain in the repository?

**Comment by deekthesqueak** [comment]
Using the renamed patch works for me. Does it need to be resubmitted?

**Pull request merged**
