### PR TITLE
Todolist 0.3.0

### PR DESCRIPTION
**Pull request by gammons**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
Do the resources need updating at all? Is there any plan to start vendoring those upstream in future, out of curiosity?

**Comment by gammons** [comment]
Hi Dominyk,

The change to the actual `todolist` binary was [very minor](https://github.com/gammons/todolist/compare/0.2.0...0.3.0).  The bigger change was what `todolist web` would serve.  

I'm happy to look into vendoring resources.  I looked at the homebrew docs but couldn't find specifics on how to do that.  If you could point me in the right direction I'd really appreciate it.

**Comment by DomT4** [comment]
> I'm happy to look into vendoring resources. I looked at the homebrew docs but couldn't find specifics on how to do that. If you could point me in the right direction I'd really appreciate it.

It's not a Homebrew thing as such, but rather a dependency system Golang have been trying to nudge developers of Go projects into, and because it makes packaging easier & more consistent for everyone we've been trying to ask as well. Very much not mandatory, but it's a nice system for stability.

The Golang [wiki](https://github.com/golang/go/wiki/PackageManagementTools) goes into a fair chunk of detail. [Govendor](https://github.com/kardianos/govendor) is nice & simple. [gvt](https://github.com/FiloSottile/gvt) is even simpler than `govendor`.

**Comment by apjanke** [comment]
Any objection to merging this as is, and switching to vendored resources in a different PR?

**Comment by DomT4** [comment]
Interested still if the resources need a bump. If they don't need a bump, sure 👍.

The way `go get` (still) works on non-vendored projects is to just `go get` the tip of the master branch _(in 99.9% of cases)_ of the dependencies, so it's nice to try & keep up with that so the experience of `brew` and outside `brew` for the same tool remains similar.

Saves upstream devs some work trying to chase up why one behaves differently from the other in bug reports, sometimes.

**Comment by gammons** [comment]
Hi @domt4, @apjanke,
 
The resources do not need to be bumped.  I'll definitely look into vendoring my resources for the next release.

**Comment by apjanke** [comment]
Merged! Thank you for your contribution.

**Pull request closed without merging**
