### PR TITLE
mu: fix url 404

### PR DESCRIPTION
**Pull request by rnkn**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The old GitHub archive url resolved to 404. This seems right.

### CODE REVIEW

**Comment by nijikon** [comment]
@ilovezfs should we bump revision?

**Comment by ilovezfs** [comment]
@nijikon yes

**Comment by rnkn** [comment]
Are revisions incremented with every formula change, or just to those for the same formula version? (e.g. would version 0.9.16 -> 0.9.17 trigger a bump?)

**Comment by ilovezfs** [comment]
Only if the version stays the same but we want to force an upgrade. In this case, there's no way to be sure the old tarball and new tarball are exactly the same (unless someone has a copy of the old one lying around with the right checksum) since it's 404ing, so forcing the upgrade will make sure 0.9.16 only means one thing.

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Pull request closed without merging**
