### PR TITLE
bash 4.4-beta2 (devel)

### PR DESCRIPTION
**Pull request by zgracem**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Hi! This is my first Homebrew pull request; I hope I did everything properly. (I removed the two babylon.network mirrors because I couldn't get the domains to resolve.)

### CODE REVIEW

**Comment by ilovezfs** [comment]
Here are some fresh mirrors to replace the ones that died:

https://mirror.clarkson.edu/gnu/bash/bash-4.4-beta2.tar.gz
https://fr.mirror.babylon.network/gnu/bash/bash-4.4-beta2.tar.gz
https://mirror1.unicorncloud.org/gnu/bash/bash-4.4-beta2.tar.gz
https://gnu.cu.be/bash/bash-4.4-beta2.tar.gz
https://nl.mirror.babylon.network/gnu/bash/bash-4.4-beta2.tar.gz
https://www.localmsp.org/gnu/bash/bash-4.4-beta2.tar.gz

Bonus points for updating the mirrors in the stable block too so they match :)

**Comment by DomT4** [comment]
We're not exactly running a mirrors deficit here 😄. Not hugely fussed about adding more mirrors, but removing any dead ones from stable is ❤️ if you wouldn't mind.

**Comment by ilovezfs** [comment]
@DomT4 it's for the sake of the patches in stable. The reason the patches had ended up vendor was due to issues with the mirrors being unreliable is this is intended to prevent that from ever being an issue again. But it may be that the mirror system is now far more reliable and this can be pared all the way down to the nub with just the standard 2 or the standard 2 plus Berkeley.

**Comment by DomT4** [comment]
Generally adding the two GNU URL types, `ftpmirror` and `ftp.gnu.org`, and then adding Berkeley & `mirrorservice` is bulletproof. If all of those are down the internet is probably broken 😄.

I'm mostly worried about when we add the check that mirrors are still functional the formulae that have lots of mirrors are going to pop big in the audit.

**Comment by ilovezfs** [comment]
Im concerned that check will be a problem. Sometimes the mirrors take a few days to be updated so removing them because they don't have the latest version will be a mistake unless it's done asynchronously with a lag of several days at least.

**Comment by ilovezfs** [comment]
If the mirror itself is dead that's another story :)

**Comment by DomT4** [comment]
Theoretically, and I'm not promising anything here, we could check if the _previous version_ hadn't yet appeared on the mirror. If that was the case, 99.9% of the time that mirror is 💀.

**Comment by ilovezfs** [comment]
I think I'd just check for the mirror itself being dead before worrying about anything fancier but not having the current version or the previous is definitely bad. I'm just not sure it's worth the extra work since the mirror server itself 404ing is almost always the problem.

**Comment by DomT4** [comment]
Not a bad idea. Remember this discussion when I file the `brew` PR at some undetermined future date, likely within the next 2 weeks unless Mike or you beat me to it 😃.

**Comment by ilovezfs** [comment]
@cryptostrophe there are two more of the same in the patch block :)

**Comment by cryptostrophe** [comment]
Oops! Thanks for the catch.

**Comment by ilovezfs** [comment]
@cryptostrophe thanks for putting up with us!

**Comment by ilovezfs** [comment]
@cryptostrophe Merged! Thank you for your contribution to Homebrew! :tada:

**Pull request closed without merging**
