### PR TITLE
sslyze 5.1.3

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
```
  ar: creating archive ../../libcrypto.a
  ar: ../libcrypto.a: Inappropriate file type or format
  make[1]: *** [../libcrypto.a] Error 1
  make[1]: *** Waiting for unfinished jobs....
```
https://github.com/Homebrew/homebrew-core/actions/runs/4583995451/jobs/8095232754?pr=127283#step:7:1724

It's building its own OpenSSL and Zlib 🙃

**Comment by ZhongRuoyu** [comment]
> It's building its own OpenSSL and Zlib 🙃

Maybe, always has been 🔫. At least since #119734; it has the earliest `sslyze` build logs that's still available. (Related: https://github.com/nabla-c0d3/nassl/issues/64.)

I couldn't reproduce the failure locally (on Intel Ventura), though.

**Comment by carlocab** [comment]
> > It's building its own OpenSSL and Zlib 🙃
> 
> Maybe, always has been 🔫. At least since #119734; it has the earliest `sslyze` build logs that's still available. (Related: [nabla-c0d3/nassl#64](https://github.com/nabla-c0d3/nassl/issues/64).)

Yea, that explains needing a custom built OpenSSL, but not quite the need for its own Zlib.

**Comment by ZhongRuoyu** [comment]
... and now the build succeeded :o

> Yea, that explains needing a custom built OpenSSL, but not quite the need for its own Zlib.

I asked upstream about this in #109. I don't see any customizable configurations in the source so some hacking might be needed.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
