### PR TITLE
numpy 1.19.0

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]
💯

**Comment by chenrui333** [comment]
only `csound` test failed on catalina

```
brew test --verbose csound
```

**Review by dawidd6 — APPROVED** [review]

**Comment by dtrodrigues** [comment]
It looks like csound test that's failing is known to be flaky - https://github.com/Homebrew/homebrew-core/pull/54364#issuecomment-626316365 https://github.com/Homebrew/homebrew-core/pull/54208#issuecomment-623849810

**Review by chenrui333 — APPROVED** [review]
sounds good!

**Comment by chenrui333** [comment]
Thanks @dtrodrigues!!

**Pull request closed without merging**
