### PR TITLE
haskell-stack 2.5.1.1

### PR DESCRIPTION
**Pull request by fishtreesugar**
Created with `brew bump-formula-pr`.

#62939

### CODE REVIEW

**Comment by carlocab** [comment]
Switching the URL to hackage broke `livecheck`, unfortunately. Is there any reason we shouldn't continue using the GitHub URL?

**Comment by fishtreesugar** [comment]
10.15 and 10.14 failed when version livechecking, but 2.5.1.1 is a [Hackage-only release](https://hackage.haskell.org/package/stack-2.5.1.1/changelog) 😭 
/sparkle

**Comment by carlocab** [comment]
Yes, and 11.0 won't build because presumable it needs ghc 8.10.3. What's the loss in sticking to 2.5.1? Will using 2.5.1.1 fix any build failures?

**Comment by fishtreesugar** [comment]
@carlocab  I think we can just pick #62939

**Comment by carlocab** [comment]
Yes, it appears to be equivalent, as it includes the patch reported in the changelog for 2.5.1.1.

**Pull request closed without merging**
