### PR TITLE
node 18.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
localtunnel test needs to be updated per nodejs API update, raise [an issue](https://github.com/localtunnel/localtunnel/issues/490) in the upstream.

**Comment by ath0mas** [comment]
npm version should be `8.6.0`, not `8.7.0`

see https://nodejs.org/en/download/current/
> Latest Current Version: 18.0.0 (includes npm 8.6.0)

https://nodejs.org/en/download/releases/
> Node.js 18.0.0 |   | 2022-04-18 | 10.1.124.8 | 8.6.0 | 108

**Review by bayandin — DISMISSED** [review]

**Comment by bayandin** [comment]
The only failure is `localtunel` (and it has been fixed in #99649). I believe we're good to merge this PR

**Comment by ath0mas** [comment]
Sorry but again why npm v8.7.0 instead of correct v8.6.0?

**Comment by chenrui333** [comment]
> Sorry but again why npm v8.7.0 instead of correct v8.6.0?

agree, we should use 8.6.0, let me fix it.

**Pull request closed without merging**
