### PR TITLE
openblas 0.3.15

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
I removed the `NO_AVX512` flag, because OpenBLAS should be able to detect it at runtime. Ref. #50252 The build failed when that variable was removed in that PR, which explains why it hadn't been removed before. It's probably worth checking whether the build will succeed without it now.

**Comment by carlocab** [comment]
On ARM:
```
Error: 1 failed step!
brew test --retry --verbose libbi
```
Looks like a mismatched `perl` error.

**Comment by carlocab** [comment]
> It's probably worth checking whether the build will succeed without it now.

Nope, still no dice. Should probably report this upstream.

**Comment by carlocab** [comment]
Ok, so everything works on Catalina and Big Sur. Doesn't build on Mojave. That's annoying.

**Comment by carlocab** [comment]
Trying to build with `clang` doesn't work.

**Comment by ywwry66** [comment]
`clang` should work if you add `depends_on "libomp"`. It just built on my machine.

**Comment by carlocab** [comment]
Oh, hey, running it again worked. Weird.

**Pull request closed without merging**
