### PR TITLE
jhipster 4.5.6

### PR DESCRIPTION
**Pull request by jdubois**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks for the upgrade @jdubois! :sparkle:

**Comment by jdubois** [comment]
Thanks ! It took a couple of PRs but now it's easy to do!

**Comment by ilovezfs** [comment]
@jdubois hehe. But I still see you're using `jdubois:master` instead of a branch. Tsk tsk.

**Comment by ilovezfs** [comment]
@jdubois have you discovered https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb yet?

**Comment by jdubois** [comment]
I saw it but didn't dare to use it.
Currently I have a simple script that wget the binary and calculates the sha. And I don't want to install the formula on my Mac, I have a dev setup which is quite complex, I'm afraid to break it.

**Comment by ilovezfs** [comment]
Ah, OK. You don't actually need the formula installed to use bump-formula-pr, and it will calculate the sha256 for you if you only specify the URL.

**Pull request closed without merging**
