### PR TITLE
operator-sdk 0.5.0 (new formula)

### PR DESCRIPTION
**Pull request by cblecker**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Add a new formula for the operator-sdk tool.

### CODE REVIEW

**Comment by cblecker** [comment]
Looks like CI is green. Please let me know if anything else is required on my part :)

**Comment by SMillerDev** [comment]
All dependencies should either be vendored in the formula or be a formula themselves. No downloading is allowed in the install block.
In addition to that, is the coreos project really the owner of this? Or is the homepage just an explanation of operator?

**Comment by cblecker** [comment]
@SMillerDev There are a number of formulas (such as kubernetes-helm) that code their dependencies via something like glide/dep, and then download at build time.. so that's not a hard and fast rule.

However, it looks like this isn't needed in this case. While the install directions suggest you should run `make dep`, it appears that all needed dependencies are in the repo's vendor folder. I've removed this step to simplify the formula.

Yes, the CoreOS site is the official site -- it's listed as such on the repo's homepage: https://github.com/operator-framework/operator-sdk

**Comment by SMillerDev** [comment]
While it might not be checked well all the time it's actually one of the rules in https://docs.brew.sh/Acceptable-Formulae

**Comment by cblecker** [comment]
CI is green after changes :)

**Comment by cblecker** [comment]
@SMillerDev are there any other changes required, or does this now meet the requirements to merge? Thank you!

**Comment by fxcoudert** [comment]
Thanks @cblecker

**Pull request closed without merging**
