### PR TITLE
openssl@1.1 1.1.0d

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alex** [comment]
I don't understand the test failure here, looks like maybe a lib that depends on openssl@1.1 has a broken build?

**Comment by DomT4** [comment]
Apparently `fdroidserver` is missing some dependencies. I would gently hazard a guess that at some point in went through part of a larger PR and scooped up some deps it usually wouldn't have access to.

You can either bump the revision without changing the deps and see if it solves the problem or you can add:

```ruby
depends_on "libtiff"
depends_on "webp"
```
to the formula, whilst bumping the revision number.

**Comment by alex** [comment]
@DomT4 attempting with the modified deps, let's see if that works

**Comment by alex** [comment]
Good call, that fixed it.

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Pull request closed without merging**
