### PR TITLE
discodex: audit fixes

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by nijikon** [comment]
🍼

**Comment by nijikon** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Welp, It's doing remote code fetching in `make`:
```
Pulling lager from {git,"https://github.com/basho/lager.git",{tag,"2.0.3"}}
Cloning into 'lager'...
Pulling folsomite from {git,"https://github.com/discoproject/folsomite",
                            {branch,"master"}}
Cloning into 'folsomite'...
Pulling plists from {git,"https://github.com/discoproject/plists",
                         {branch,"master"}}
Cloning into 'plists'...
Pulling mochiweb from {git,"https://github.com/mochi/mochiweb.git",
                           {tag,"v2.9.2"}}
Cloning into 'mochiweb'...
WARN:  Expected /private/tmp/disco20160411-65021-psbmwp/disco-0.5.4/master/deps/goldrush to be an app dir (containing ebin/*.app), but no .app found.
==> lager (get-deps)
WARN:  Expected /private/tmp/disco20160411-65021-psbmwp/disco-0.5.4/master/deps/goldrush to be an app dir (containing ebin/*.app), but no .app found.
Pulling goldrush from {git,"git://github.com/DeadZen/goldrush.git",
                           {tag,"0.1.6"}}
```

There's no tagged release upstream, no upstream commits in years, @apjanke filed an Issue three years ago asking for [a tag with no reply](https://github.com/discoproject/discodex/issues/1) and there have been no bottled downloads in 365 days.

Maybe this is worth just boneyarding.

**Comment by nijikon** [comment]
I thought about it :)

**Comment by nijikon** [comment]
Al in favor of removing this 👍

**Comment by DomT4** [comment]
Feel free to change the PR to do that :)

**Comment by mikemcquaid** [comment]
:+1: to boneyard

**Comment by apjanke** [comment]
Yeah, boneyard.

**Comment by apjanke** [comment]
PR for boneyarding:
https://github.com/Homebrew/homebrew-core/pull/270
https://github.com/Homebrew/homebrew-boneyard/pull/105

**Pull request closed without merging**
