### PR TITLE
wesnoth 1.14.5

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by equal-l2** [comment]
- You need to pass a flag to SCons for OpenSSL.
See https://github.com/Homebrew/homebrew-core/pull/27641/files#diff-12e33cd67affabaa584635f3944b6a22R34.

- You don't need `sdl2_net` anymore since wesnoth now uses Boost.asio instead.

**Comment by equal-l2** [comment]
More notes:
- Wesnoth now uses `sdl2` and the family. Please migrate the `sdl` dependencies.

- You need `pkg-config` on build since SCons requires it for finding OpenSSL.
(https://github.com/Homebrew/homebrew-core/pull/27641/files#diff-12e33cd67affabaa584635f3944b6a22R14)

- You don't need `libpng` anymore since wesnoth now uses `sdl2_image` for handling PNG.
(There's still the indirect dependency on `libpng` since `sdl2_image` uses `libpng`, though)

**Comment by Moisan** [comment]
`/bin/sh: pkg-config: command not found`

But `pkg-config` is in the build dependencies...

**Comment by SMillerDev** [comment]
@BrewTestBot Test this please!

**Comment by equal-l2** [comment]
It builds now, but the test fails.

**Comment by SMillerDev** [comment]
@BrewTestBot Test this please!

**Comment by igas** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
Giving up on this one.

**Pull request closed without merging**
