### PR TITLE
artifactory: improve test

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---
- Useless use of pattern;
- <s>`pipe_output` can be `shell_output` because nothing's piped.</s>

### CODE REVIEW

**Comment by zmwangx** [comment]
Forgot `pipe_output` optionally asserts exit status while `shell_output` asserts it. Guess we'll keep `pipe_output` here.

**Comment by DomT4** [comment]
If the exit code is predictable you can always tell `shell_output` to just expect that every time.

**Comment by zmwangx** [comment]
> If the exit code is predictable

Sometimes upstreams do massage the exit code for `--help`, `--version`, no argument specified and stuff. It's not very important.

**Comment by DomT4** [comment]
Indeed. Was only noting it in case you really wanted to ditch the `pipe_output`.

**Pull request closed without merging**
