### PR TITLE
protobuf 3.20.1

### PR DESCRIPTION
**Pull request by owine**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
protobuf changed the version scheme, here is [the doc](https://developers.google.com/protocol-buffers/docs/news/2022-05-06) for it

> Versioning
We changed our versioning scheme to enable more-nimble updates to language-specific parts of Protocol Buffers. In the new scheme, each language has its own major version that can be incremented independently of other languages, as covered later in this topic with the Python release. The minor and patch versions, however, will remain coupled. This allows us to introduce breaking changes into some languages without requiring a bump of the major version in languages that do not experience a breaking change.
> 
> The first instance of this new versioning scheme is the new version of the Python API, 4.21.0, which follows the preceding version, 3.20.1. Other language APIs will be released as 3.21.0.

it might be good shipping this release before bumping to `21.1`

**Comment by owine** [comment]
Sorry, all - I have taken this one as far as I am capable. I would appreciate an assist in keeping this one moving or I can close in favor of another attempt.

**Comment by SMillerDev** [comment]
Closing in favor of https://github.com/Homebrew/homebrew-core/pull/105712

**Comment by carlocab** [comment]
@owine, don't delete your branch yet. It seems like we might still want this update, as https://github.com/Homebrew/homebrew-core/pull/105712 is blocked.

**Comment by pitrou** [comment]
@cho-m For the record, the ABI issue should be fixed in protobuf 21.3: https://github.com/protocolbuffers/protobuf/pull/10273

**Comment by carlocab** [comment]
Thanks for the fix @pitrou!

**Pull request closed without merging**
