### PR TITLE
imagesnap 0.2.8

### PR DESCRIPTION
**Pull request by morusn**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
release is not marked as `latest release` yet
image

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
looks like still not marked as `latest release` yet

**Comment by rharder** [comment]
I'm the developer for imagesnap. I'm submitting a formula update for v0.2.10.  This pull can be closed.

**Comment by Rylan12** [comment]
Superseded by #73076

**Pull request closed without merging**
