### PR TITLE
rpm 4.19.1.1

### PR DESCRIPTION
**Pull request by bakkot**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bakkot** [comment]
This hopefully fixes https://github.com/orgs/Homebrew/discussions/4806 https://github.com/orgs/Homebrew/discussions/4826 etc

**Comment by bakkot** [comment]
hm, never mind, I don't think this actually worked :(

**Comment by chenrui333** [comment]
@bakkot why can't we go with this PR? what is the issue?

**Comment by bakkot** [comment]
@chenrui333 It didn't actually make it work on MacOS, when I tried it locally.

**Comment by chenrui333** [comment]
#163520

**Pull request closed without merging**
