### PR TITLE
cartridge-cli 2.6.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Let's check it on Apple Silicon

**Comment by bayandin** [comment]
Fails on arm:

```
==> mage build
Error determining list of magefiles: failed to list non-mage gofiles: exit status 1: go: docker.io/go-docker@v1.0.0: missing go.sum entry; try 'go mod download docker.io/go-docker' to add it
```

I looks like the error caused by go1.16 ([from 1.16 changelog](https://tip.golang.org/doc/go1.16#go-command)):
> Build commands like go build and go test no longer modify go.mod and go.sum by default. Instead, they report an error if a module requirement or checksum needs to be added or updated (as if the -mod=readonly flag were used). Module requirements and sums may be adjusted with go mod tidy or go get.

Should be reported upstream, I believe

**Comment by carlocab** [comment]
>go build and go test no longer modify go.mod and go.sum by default

Wait, they used to (/still, for go1.15) do this? Doesn't this make builds non-reproducible?

**Comment by bayandin** [comment]
> > go build and go test no longer modify go.mod and go.sum by default
> 
> Wait, they used to (/still, for go1.15) do this? Doesn't this make builds non-reproducible?

They have `go.mod`, but don't have `go.sum` 🤷

**Comment by carlocab** [comment]
Oh, I was just thinking of all the other go-based formula. If `go build` actually modifies `go.mod` and `go.sum` by default, then I think that might mean the dependencies aren't necessarily pinned?

That said, it's also going to be changed in go1.16, so even if the dependencies are not currently pinned, they will be soon. So there's probably no point in doing anything about them now.

**Review by carlocab — APPROVED** [review]
No bottle for ARM shouldn't block this, I think.

**Pull request closed without merging**
