### PR TITLE
nailgun 0.9.3

### PR DESCRIPTION
**Pull request by mistydemeo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Refs #23452.

Facebook, the new maintainers, haven't published 0.9.3 to Maven; this switches to a source build for stable the same way it does for the head build.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> /usr/local/Cellar/nailgun/0.9.3/bin/ng --nailgun-port 8765 ng-version
NailGun server version 0.9.3-SNAPSHOT
com.martiansoftware.nailgun.builtins.NGAlias: 0/0
com.martiansoftware.nailgun.builtins.NGClasspath: 0/0
com.martiansoftware.nailgun.builtins.NGServerStats: 0/0
com.martiansoftware.nailgun.builtins.NGStop: 1/1
com.martiansoftware.nailgun.builtins.NGVersion: 1/0
NGServer shut down.
Feb 06, 2018 11:14:57 AM com.martiansoftware.nailgun.NGInputStream lambda$new$1
WARNING: Nailgun client read future raised an exception
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.net.SocketException: Connection reset
    at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
    at com.martiansoftware.nailgun.NGInputStream.lambda$new$1(NGInputStream.java:130)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.util.concurrent.ExecutionException: java.net.SocketException: Connection reset
    at com.martiansoftware.nailgun.NGInputStream.lambda$new$0(NGInputStream.java:126)
    ... 4 more
Caused by: java.net.SocketException: Connection reset
    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:210)
    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
    at java.base/java.net.SocketInputStream.read(SocketInputStream.java:224)
    at java.base/java.io.DataInputStream.readInt(DataInputStream.java:392)
    at com.martiansoftware.nailgun.NGInputStream.readChunk(NGInputStream.java:260)
    at com.martiansoftware.nailgun.NGInputStream.lambda$new$0(NGInputStream.java:119)
    ... 4 more

Exception in thread "NGSession 1: 127.0.0.1: ng-version" recv: Undefined error: 0
iMac-TMP:~ joe$ 
```

**Comment by mistydemeo** [comment]
Looks like it passed in CI. What version of Java does it have?

**Comment by ilovezfs** [comment]
The `test do` ends in `true` so that's not surprising, I don't think.

CI has both 8 and 9 installed as do I.

**Comment by ilovezfs** [comment]
```
iMac-TMP:~ joe$ brew test nailgun 
Testing nailgun
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/joe/Library/Caches/Homebrew/java_cache
NGServer 0.9.3-SNAPSHOT started on all addresses, port 8765.
==> /usr/local/Cellar/nailgun/0.9.3/bin/ng --nailgun-port 8765 ng-version
com.martiansoftware.nailgun.builtins.NGAlias: 0/0
com.martiansoftware.nailgun.builtins.NGClasspath: 0/0
com.martiansoftware.nailgun.builtins.NGServerStats: 0/0
com.martiansoftware.nailgun.builtins.NGStop: 1/1
com.martiansoftware.nailgun.builtins.NGVersion: 1/0
NGServer shut down.
Feb 06, 2018 2:06:03 PM com.martiansoftware.nailgun.NGSession run
INFO: NGSession shutting down
recv: Undefined error: 0
iMac-TMP:~ joe$ echo $?
0
iMac-TMP:~ joe$ brew test -vd nailgun
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nailgun.rb
Testing nailgun
/usr/bin/sandbox-exec -f /tmp/homebrew20180206-22533-rwaeo9.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nailgun.rb -vd
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nailgun.rb
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/joe/Library/Caches/Homebrew/java_cache
NGServer 0.9.3-SNAPSHOT started on all addresses, port 8765.
==> /usr/local/Cellar/nailgun/0.9.3/bin/ng --nailgun-port 8765 ng-version
NailGun server version 0.9.3-SNAPSHOT
com.martiansoftware.nailgun.builtins.NGAlias: 0/0
com.martiansoftware.nailgun.builtins.NGClasspath: 0/0
com.martiansoftware.nailgun.builtins.NGServerStats: 0/0
com.martiansoftware.nailgun.builtins.NGStop: 1/1
com.martiansoftware.nailgun.builtins.NGVersion: 1/0
NGServer shut down.
Feb 06, 2018 2:06:17 PM com.martiansoftware.nailgun.NGInputStream lambda$new$1
WARNING: Nailgun client read future raised an exception
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.net.SocketException: Socket closed
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.martiansoftware.nailgun.NGInputStream.lambda$new$1(NGInputStream.java:130)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.net.SocketException: Socket closed
	at com.martiansoftware.nailgun.NGInputStream.lambda$new$0(NGInputStream.java:126)
	... 4 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:189)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at com.martiansoftware.nailgun.NGInputStream.readChunk(NGInputStream.java:260)
	at com.martiansoftware.nailgun.NGInputStream.lambda$new$0(NGInputStream.java:119)
	... 4 more

recv: Undefined error: 0
iMac-TMP:~ joe$ echo $?
0
iMac-TMP:~ joe$ 
```

**Comment by mistydemeo** [comment]
The output is noisy, but is actually does appear to work. When I try it manually, `ng-server` does print a bunch of garbage like that:

```
Feb 06, 2018 4:06:03 PM com.martiansoftware.nailgun.NGSession run
INFO: NGSession shutting down
Feb 06, 2018 4:06:12 PM com.martiansoftware.nailgun.NGInputStream lambda$new$1
WARNING: Nailgun client read future raised an exception
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.net.SocketException: Socket closed
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.martiansoftware.nailgun.NGInputStream.lambda$new$1(NGInputStream.java:130)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.net.SocketException: Socket closed
	at com.martiansoftware.nailgun.NGInputStream.lambda$null$0(NGInputStream.java:126)
	... 4 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:223)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at com.martiansoftware.nailgun.NGInputStream.readChunk(NGInputStream.java:260)
	at com.martiansoftware.nailgun.NGInputStream.lambda$null$0(NGInputStream.java:119)
	... 4 more
```

Nonetheless, nailgun client calls are successful:

```
$ ng --nailgun-port 8765 ng-version
NailGun server version 0.9.3-SNAPSHOT
```

Consequently, I think this is okay. That's also supported by this text on their issue tracker: https://github.com/facebook/nailgun/issues/112#issuecomment-357222580

> Unfortunately this is the way how server shutdown is currently designed - it just interrupts a listener thread by setting its flag to 'interrupted' and catching InterruptedException afterwards. I have plans to refactor it and implement a graceful shutdown.

> I think that fixing this at its root would be awesome -- users are confused when they see this stack trace, and they think something's acting up when it's not.

While the author indicated they thought it was fixed in 0.9.3, I guess it's still happening. Nonetheless, it turns out it's not a sign it's broken - it seems to still be working, just noisily.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
I commented that it's still happening on that issue.

**Comment by ilovezfs** [comment]
:rocket:

**Pull request closed without merging**
