### PR TITLE
libxml2: fix catalog usage

### PR DESCRIPTION
**Pull request by stsp**
Pass --sysconfdir for libxml2 to allow it to locate /etc/xml/catalog. Otherwise it looks into Cellar/libxml2/.../etc which doesn't exist.

To work around that problem, xmlto was patched to allow downloading xmls from internet, as the local catalog wasn't working. That fails if the internet access is disabled.
So drop the no longer needed patch, as with libxml2 fix, catalog works locally.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]
Looks reasonable to me. Thanks!

**Comment by stsp** [comment]
@carlocab I don't think the failure is
related to this patch.
Please help, I won't get that solved.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
we can followup failures separately

```
brew linkage --test libmp3splt
brew install metashell
brew test --retry --verbose mp3splt
brew test --retry --verbose mps-youtube
brew install --only-dependencies openai-whisper
brew link pytorch
brew install pmix
brew test --retry --verbose rpm
brew test --retry --verbose vunnel
```

**Comment by chenrui333** [comment]
@stsp thanks for your first PR to homebrew-core! 🎉

**Comment by stsp** [comment]
> we can followup failures separately

What needs to be done to get that
somehow "fixed" or disabled?
I suspect #154109 will also suffer.

**Pull request merged**
