### PR TITLE
tap_migrations.json: hdf5 is in homebrew-science

### PR DESCRIPTION
**Pull request by eleonore88**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
That has been true since 2013. But thanks for the PR nonetheless.

**Comment by iMichka** [comment]
@ilovezfs, I made that PR together with @eleonore88. Here a little bit of context:

> brew untap homebrew/homebrew-science
> brew install hdf5
Error: No available formula with the name "hdf5" 
==> Searching for a previously deleted formula...
hdf5 was deleted from homebrew/core in commit 7538fef0b1:
  Remove formulae moved to homebrew-science

> To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show 7538fef0b1^:Formula/hdf5.rb

> If you still use this formula consider creating your own tap:
  http://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html

Not the most useful error message. If you do not know that hdf5 is in homebrew-science, you end up needing to google a little bit to find the real location of that formula. As there seem to have been a migration at one point, this PR seemed to be most logical thing to do.

On the other side I know that we want to eventually move hdf5 back to core :)

**Comment by ilovezfs** [comment]
I'm reluctant to fill tap_migrations.json up with ancient migrations that occurred before there was such a thing as the tap_migrations.json file. As you can see, https://github.com/Homebrew/homebrew-core/commit/7538fef0b1e8788c73fb8c4c58145393212aedcb actually moved 16 formulae.

**Comment by iMichka** [comment]
> I'm reluctant to fill tap_migrations.json up with ancient migrations that occurred before there was such a thing as the tap_migrations.json file

Because the file would grow too much, or because of unknown side-effects/bugs?

> 16 formulae

We can update the PR and select the ones that still make sense. I also see that the actual hdf@4 migration is wrong, it should be hdf4. On the other side I see also some potential formula that could be migrate back to core.

My point is that the error message you get is really not helpful for people new to homebrew. Of course we will not be able to have all the migrated formulae in here, especially if that bookkeeping didn't exist 3-4 years ago, but at least we will fix it for the one which were really migrated.

**Comment by ilovezfs** [comment]
If the messaging bothers you, I suggest a PR to Homebrew/brew to improve it, but I don't think we should actively be backfilling these based on what amounts to ancient history at this point.

**Comment by iMichka** [comment]
Don't know how I could improve the messaging.

I see that the commit message fro the migration commit is displayed in the actual error message, but it is somewhat lost in the longer message, and it also tells to consider creating your own tap or to revive the old formula. Which is obviously not the first thing you should do.

I would have expected this:
> Error: No available formula with the name "hdf5" 
You can access it again by running:
  brew tap homebrew/science

But to get this I would need to have access to the list of formulae in science, without checking out science. So not sure how that would work.

On the other side, if you think that cleaning up the migration list by hand would take too long (and it will), I could try to write a script which would look to all the migrations between legacy-core and core to homebrew-science. We have the git history so this should be doable. This solves the problem for science only, but could be used for other taps if needed. Not sure in which of both strategies I should invest some time though.

**Comment by ilovezfs** [comment]
I don't think this used to require an entry in the tap migrations file to work properly for formulae in taps regardless of where they might have been in the Paleolithic era. CC @zmwangx @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
`brew install` will show search result output on a missing formula which will find it so I'm not sure I get your point @iMichka.

**Comment by zmwangx** [comment]
The point is `hdf5` was technically migrated to homebrew/science eons ago, but it's not in tap_migrations.json, so the message from the history search is not helpful.

We might be able to probably set an arbitrary cutoff time (`git log --since=...`) to the history search. Will improve the speed too.

**Comment by ilovezfs** [comment]
There's also the fact that if the `brew search` returned a result in science, then the formula is not really deleted, so the message for deleted formulae isn't actually applicable.

**Comment by MikeMcQuaid** [comment]
```
Error: No available formula with the name "hdf5" 
==> Searching for a previously deleted formula...
hdf5 was deleted from homebrew/core in commit 7538fef0b1:
  Remove formulae moved to homebrew-science

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show 7538fef0b1^:Formula/hdf5.rb

If you still use this formula consider creating your own tap:
  http://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html
```

**Comment by MikeMcQuaid** [comment]
> deleted from homebrew/core

is the key wording to me. "Searching for a previously deleted formula..." could be changed to "Searching for a previously deleted or migrated formula..." but the end result is kinda the same.

**Comment by MikeMcQuaid** [comment]
I guess the regression could be considered that if it's found as previously deleted we don't hit the API for a search result. In this case I do feel the commit message makes it pretty clear, though.

**Comment by ilovezfs** [comment]
@iMichka I guess if you want to spend the time to "correct the historical record," I'm fine with that.

**Comment by ilovezfs** [comment]
@eleonore88 thanks for the pull request!

I went with

`tap_migrations: add old migration of hdf5 to science`

for the commit message.

**Comment by eleonore88** [comment]
Thanks !

**Comment by iMichka** [comment]
> I guess if you want to spend the time to "correct the historical record," I'm fine with that.

I'll have a look if I can come up with a script that gets me the list of missing migrations automatically, and make a new PR. Thanks for all your comments.

**Comment by ilovezfs** [comment]
@iMichka here you go:
```
iMac-TMP:~ joe$ git clone https://github.com/Homebrew/homebrew-science
iMac-TMP:~ joe$ cd homebrew-science
iMac-TMP:homebrew-science joe$ ls *.rb | xargs -n1 -I % basename % .rb | while read f; do brew install $f 2>&1 | grep 'was deleted'; sleep 3; done
abyss was deleted from homebrew/core in commit f7e96b7:
adol-c was deleted from homebrew/core in commit 53406d2:
alembic was deleted from homebrew/core in commit 7538fef:
ann was deleted from homebrew/core in commit 53406d2:
armadillo was deleted from homebrew/core in commit 53406d2:
arow++ was deleted from homebrew/core in commit f7e96b7:
bact was deleted from homebrew/core in commit 53406d2:
bali-phy was deleted from homebrew/core in commit 53406d2:
bamtools was deleted from homebrew/core in commit f7e96b7:
bedtools was deleted from homebrew/core in commit 53406d2:
blast was deleted from homebrew/core in commit f7e96b7:
bowtie was deleted from homebrew/core in commit f7e96b7:
bwa was deleted from homebrew/core in commit f7e96b7:
cd-hit was deleted from homebrew/core in commit f7e96b7:
cdo was deleted from homebrew/core in commit 7538fef:
clustal-omega was deleted from homebrew/core in commit f7e96b7:
clustal-w was deleted from homebrew/core in commit f7e96b7:
cminpack was deleted from homebrew/core in commit 53406d2:
colpack was deleted from homebrew/core in commit 53406d2:
cufflinks was deleted from homebrew/core in commit f7e96b7:
dadadodo was deleted from homebrew/core in commit f7e96b7:
emboss was deleted from homebrew/core in commit f7e96b7:
exonerate was deleted from homebrew/core in commit 7538fef:
fann was deleted from homebrew/core in commit c5113a5:
fastx_toolkit was deleted from homebrew/core in commit f7e96b7:
field3d was deleted from homebrew/core in commit 7538fef:
flann was deleted from homebrew/core in commit 53406d2:
glpk was deleted from homebrew/core in commit 53406d2:
gmap-gsnap was deleted from homebrew/core in commit f7e96b7:
gmt was deleted from homebrew/core in commit 7538fef:
h5utils was deleted from homebrew/core in commit 7538fef:
hmmer was deleted from homebrew/core in commit f7e96b7:
igraph was deleted from homebrew/core in commit a8c48b9:
insighttoolkit was deleted from homebrew/core in commit 53406d2:
libmatio was deleted from homebrew/core in commit 7538fef:
mafft was deleted from homebrew/core in commit 53406d2:
mallet was deleted from homebrew/core in commit 53406d2:
mathgl was deleted from homebrew/core in commit 53406d2:
mathomatic was deleted from homebrew/core in commit 53406d2:
maxima was deleted from homebrew/core in commit 53406d2:
mcl was deleted from homebrew/core in commit 53406d2:
metis was deleted from homebrew/core in commit 53406d2:
mira was deleted from homebrew/core in commit f7e96b7:
moab was deleted from homebrew/core in commit 7538fef:
mpsolve was deleted from homebrew/core in commit 53406d2:
mrfast was deleted from homebrew/core in commit f7e96b7:
muscle was deleted from homebrew/core in commit f7e96b7:
nauty was deleted from homebrew/core in commit 53406d2:
ncview was deleted from homebrew/core in commit 7538fef:
netcdf was deleted from homebrew/core in commit 7538fef:
openimageio was deleted from homebrew/core in commit 53406d2:
openmeeg was deleted from homebrew/core in commit 7538fef:
paml was deleted from homebrew/core in commit f7e96b7:
parmetis was deleted from homebrew/core in commit 53406d2:
phyml was deleted from homebrew/core in commit f7e96b7:
plink was deleted from homebrew/core in commit f7e96b7:
pnapi was deleted from homebrew/core in commit 7538fef:
primer3 was deleted from homebrew/core in commit f7e96b7:
prodigal was deleted from homebrew/core in commit f7e96b7:
prooftree was deleted from homebrew/core in commit ee7405d:
qhull was deleted from homebrew/core in commit 53406d2:
quicktree was deleted from homebrew/core in commit f7e96b7:
r was deleted from homebrew/core in commit 7538fef:
radx was deleted from homebrew/core in commit 53406d2:
root was deleted from homebrew/core in commit 7538fef:
samtools was deleted from homebrew/core in commit f7e96b7:
scotch was deleted from homebrew/core in commit 53406d2:
sga was deleted from homebrew/core in commit f7e96b7:
shogun was deleted from homebrew/core in commit ef07ff3:
suite-sparse was deleted from homebrew/core in commit 53406d2:
symphony was deleted from homebrew/core in commit 53406d2:
tophat was deleted from homebrew/core in commit f7e96b7:
triangle was deleted from homebrew/core in commit 53406d2:
unafold was deleted from homebrew/core in commit 53406d2:
vcftools was deleted from homebrew/core in commit 53406d2:
velvet was deleted from homebrew/core in commit f7e96b7:
vips was deleted from homebrew/core in commit 53406d2:
vtk was deleted from homebrew/core in commit 53406d2:
wxmaxima was deleted from homebrew/core in commit c5113a5:
```

**Comment by ilovezfs** [comment]
Note that the current size of the tap_migration.json file is only 67 entries and this will add another 79 entries, so I'm still not exactly thrilled with this idea.

**Comment by iMichka** [comment]
Thanks. 79 more looks reasonable. We are not talking about thousands of formulae. Maybe there will be around 5 or 10 migrating back to core at one point.

I would prefer to have the list correctly filled out instead of having an arbitrary cutoff date. Else there is not real point to have the migration list, because we could also just drop it and let the users find out by themselves where formulae are ...

**Comment by ilovezfs** [comment]
It more than doubles the list, and this is the first I've heard anyone bring this up at all.

**Comment by iMichka** [comment]
Conclusion here, just in case somebody stumbles over this: we are migrating the important formulae to core, and not touching the migration list :)

**Pull request merged**
