### PR TITLE
zeek: migrate to python@3.11

### PR DESCRIPTION
**Pull request by ryenus**
Update formula **zeek** to use python@3.11 instead of python@3.10

see the related pr https://github.com/Homebrew/homebrew-core/pull/114154

### CODE REVIEW

**Comment by danielnachun** [comment]
Python 3.11 support should be available with the 5.1 release: https://github.com/zeek/zeek/issues/2654.  If this is not imminent we may want to close this PR until it's available.

**Comment by iMichka** [comment]
We should definitively update the formula to version 5.1.1 first.

**Comment by cho-m** [comment]
The last time we tried to update, `zeek` didn't work with our copy of `caf` and needed its own copy.

However, the only formula that uses `caf` is `zeek`, so it may not actually matter that much given it isn't as bad as formulae that bundle other packages.

**Comment by cho-m** [comment]
Superseded by #119717

**Pull request closed without merging**
