### PR TITLE
Update gauge formula to use zip installers

### PR DESCRIPTION
**Pull request by bugdiver**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by commitay** [comment]
https://docs.brew.sh/Acceptable-Formulae
> Our policy is that formulae in the core tap (homebrew/core) must be open-source and either built from source or produce cross-platform binaries (e.g. Java).

**Comment by sriv** [comment]
hi @commitay - this formulae is for an open source project: https://github.com/getgauge/gauge

And we do have cross-platform binaries (we build it using golang's cross compile toolchain).

The change in the formulae is because we need to sign the binaries. If there is any better way to get brew to sign the formulae, we would be happy to build from source.

cheers.

**Comment by commitay** [comment]
> And we do have cross-platform binaries (we build it using golang's cross compile toolchain).

`gauge-0.9.7-darwin.x86_64.zip` isn't a cross-platform binary.

> we need to sign the binaries

This would probably need to be migrated to [Cask](https://github.com/caskroom/homebrew-cask)

cc @ilovezfs

**Comment by sriv** [comment]
> gauge-0.9.7-darwin.x86_64.zip isn't a cross-platform binary.

Fair enough. 

> This would probably need to be migrated to Cask

From what I've seen cask apps get installed in `Applications`, whereas this is a CLI utility and we would like to be in `/usr/local/bin`. Would cask be apt for this? 

Another option could be that we start maintaining a separate tap. Perhaps that isn't ideal, would really appreciate some advice. 

cheers.

**Comment by ilovezfs** [comment]
Why do the binaries need signing?

**Comment by BugDiver** [comment]
@ilovezfs  sometime `gauge` needs to run as `daemon`, and it also open ports for `TCP` connections. OSX firewall doesn't allow it to accept connections by default.

The attached screenshot shows the error which occurs if binaries are not signed

screen shot 2018-03-15 at 4 21 39 pm

**Comment by ilovezfs** [comment]
That's not a sufficient reason for us to move this to Cask or a third-party tap. There's plenty of stuff in Homebrew/homebrew-core just like that.

**Comment by sriv** [comment]
@ilovezfs - I am a bit confused. Are you saying that it is ok for this prompt to come up? Or are you suggesting that there are other formulae which have solved this without having to sign the binary? If it's the latter, if you could point to a sample, that would be super helpful.

**Comment by ilovezfs** [comment]
The former.

**Comment by sriv** [comment]
Normally, I'd live with the popup. Since we bring it up as a daemon, via another application, the popup gets hidden, and can be quite annoying, especially in a multiple monitor setup.

But we respect your policies and decision. Thanks for all the good work.

**Comment by zabil** [comment]
> The former.

Along with annoyances, sometimes it blocks our port without showing the popup, and that breaks functionality in our app. How we package must not create a bad experience for the end user.

We are big fans of homebrew and hope, in the future, there'll be a way to sign binaries. Cheers.

**Comment by ilovezfs** [comment]
@zabil @sriv FYI the approach in xctool https://github.com/Homebrew/homebrew-core/pull/6736 or chisel https://github.com/Homebrew/homebrew-core/pull/22450 will probably work.

**Comment by BugDiver** [comment]
> FYI the approach in xctool #6736 or chisel #22450 will probably work.

@ilovezfs Thanks for the good work to find it but the ad-hoc signing of binaries is not actually solving the issue.

**Comment by MikeMcQuaid** [comment]
> Would cask be apt for this?

If you only wish to distribute binaries to end-users: yes.

> Another option could be that we start maintaining a separate tap.

You can do this without our permission but we would still want to keep this formula here because it works as-is.

> OSX firewall doesn't allow it to accept connections by default.

That's not quite right. The macOS firewall (which isn't enabled by default) doesn't allow connections from other machines unless you click "Allow". If you wish to only use it throw `localhost` (as I do using `nginx` at work daily) then you can click "Deny" and it works fine. Additionally, if you bind only to local ports it's possible to make the dialog not be shown at all.

> Since we bring it up as a daemon, via another application, the popup gets hidden, and can be quite annoying, especially in a multiple monitor setup.

This happens with `nginx` and many more popular packages than this and we don't hear complaints from users.

> But we respect your policies and decision. Thanks for all the good work.

This appears to be contradicted by this post to Hacker News: https://news.ycombinator.com/item?id=16616485. You're welcome to not respect our decisions but saying one thing here and another thing elsewhere is disingenuous, rude and makes us less likely to want to help you.

> How we package must not create a bad experience for the end user.

To be clear: you do not package it and we do. We welcome input but ultimately deciding what produces the best experience for Homebrew end-users is on the Homebrew maintainers and not you.

**Comment by zabil** [comment]
> This appears to be contradicted by this post to Hacker News:

@MikeMcQuaid didn't mean to come across as rude was only looking for a solution. I've added a comment to say it's not your fault.

https://news.ycombinator.com/item?id=16624970

Cheers and thanks agains.

**Comment by zabil** [comment]
> This happens with nginx and many more popular packages than this and we don't hear complaints from users.

Unfortunately we struggle a lot to debug this problem when things don't work for our users. We'll try the options and if they don't work ok with keeping the older packages here. 

We can point our users to the custom tap.

**Comment by zabil** [comment]
> If you wish to only use it throw localhost

Thanks for the tip, setting our connections to use `localhost` worked. The popup doesn't come anymore. 

We'd still like to sign our binaries and for this, we'll maintain a separate binary installer.

**Pull request closed without merging**
