### PR TITLE
minisat 2.2.1 (new formula)

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This fails the audit because the GitHub repo is a fork, but the original repo is unmaintained.

### CODE REVIEW

**Review by Moisan — DISMISSED** [review]
I know a bit the field of SAT solvers and I think you're right to point to the fork. I'll approve the PR but if test-bot refuses to merge, I'll poke other maintainers to find the proper way to merge this.

**Comment by carlocab** [comment]
Thanks, @Moisan.

**Comment by carlocab** [comment]
I think this just needs rebasing against master (hopefully).

**Comment by carlocab** [comment]
Let's try this again...

**Comment by carlocab** [comment]
🎉

**Pull request closed without merging**
