### PR TITLE
libtorch 1.7.1 + torchvision 0.8.2

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by carlocab** [comment]
Looks like torchvision needs a revision bump:
```
==> brew linkage --test torchvision
==> FAILED
Broken dependencies:
  /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/Python (python@3.9)
```
This also explains the later test failure. (This is the only failure on 10.14.)

If someone wants to add a commit to this PR doing that, please go ahead. My Mac is currently unusable from trying to build Rust. @chenrui333

**Comment by carlocab** [comment]
Sorted it out. Thanks for the help anyway, @chenrui333!

**Comment by carlocab** [comment]
Oh, I see the problem. `torchvision` needs a version bump: https://github.com/pytorch/vision/releases. 

I'll get to that.

**Comment by carlocab** [comment]
Still the same error after the version bump. How annoying.

**Comment by carlocab** [comment]
Upstream report: https://github.com/pytorch/vision/issues/3157

**Comment by carlocab** [comment]
Ok, I can't reproduce this error locally. Could this be a CI problem?

**Comment by gromgit** [comment]
This:
```
==> brew linkage --test torchvision
==> FAILED
Broken dependencies:
  /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/Python (python@3.9)
```
probably means that `python@3.9` should be a general dependency in `torchvision`, not just a build one.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
