### PR TITLE
ffmpeg 4.4

### PR DESCRIPTION
**Pull request by crunchtime-ali**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
`qcli` needs a revision bump.

**Comment by crunchtime-ali** [comment]
There are at least 80k output lines (thats where I stopped scrolling)  in this format:

```
I0409 06:39:24.787717 450792896 caffe.cpp:313] Batch 8, prob = 0.00103213
I0409 06:39:24.787729 450792896 caffe.cpp:313] Batch 8, prob = 0.000963325
I0409 06:39:24.787741 450792896 caffe.cpp:313] Batch 8, prob = 0.00100085
```

Is this really helpful?

**Comment by carlocab** [comment]
Yea, that's from `caffe`. It's been having some testing issues which I think is just a problem on CI. I tested in locally on Big Sur (after the `sqlite` update), but it would be good if someone could check on Catalina whether it's not broken there.

The Mojave errors are from misplaced bottles in the move to GitHub packages.

**Comment by crunchtime-ali** [comment]
@carlocab I built it using `brew reinstall --build-from-source --verbose ffmpeg && brew test ffmpeg` on 10.15.7. It finished without any issues.

Will re-triggering the CI build help or where do we go from here?

**Comment by carlocab** [comment]
Yea, `ffmpeg` is fine. It's more stuff that depends (indirectly) on `ffmpeg`. Still, re-running CI against the latest master might help. Let's see.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
