### PR TITLE
kubernetes-cli 1.20.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
build failure only on 10.15

```
==> hack/generate-docs.sh
WARNING: hack/generate-docs.sh is an alias for hack/update-generated-docs.sh
and will be removed in a future version.
+++ [1208 20:55:37] Building go targets for darwin/amd64:
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
# k8s.io/kubernetes/pkg/apis/autoscaling/v2beta1
pkg/apis/autoscaling/v2beta1/zz_generated.conversion.go:319:6: Convert_v2beta1_HorizontalPodAutoscaler_To_autoscaling_HorizontalPodAutoscaler redeclared in this block
	previous declaration at pkg/apis/autoscaling/v2beta1/conversion.go:311:195
pkg/apis/autoscaling/v2beta1/zz_generated.conversion.go:335:6: Convert_autoscaling_HorizontalPodAutoscaler_To_v2beta1_HorizontalPodAutoscaler redeclared in this block
	previous declaration at pkg/apis/autoscaling/v2beta1/conversion.go:285:195
!!! [1208 20:58:04] Call tree:
!!! [1208 20:58:04]  1: /private/tmp/kubernetes-cli-20201208-96166-1mehcym/hack/lib/golang.sh:719 kube::golang::build_some_binaries(...)
!!! [1208 20:58:04]  2: /private/tmp/kubernetes-cli-20201208-96166-1mehcym/hack/lib/golang.sh:863 kube::golang::build_binaries_for_platform(...)
!!! [1208 20:58:04]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make: *** [all] Error 1
```

**Comment by chenrui333** [comment]
failed on 11.0 this time

**Comment by chenrui333** [comment]
```
==> make WHAT=cmd/kubectl
+++ [1209 03:55:43] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
+++ [1209 03:55:43] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
+++ [1209 03:55:43] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
+++ [1209 03:55:43] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
+++ [1209 03:55:43] Building go targets for darwin/amd64:
    ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
+++ [1209 03:55:43] Building go targets for darwin/amd64:
    ./vendor/github.com/go-bindata/go-bindata/go-bindata
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12b9fd5]
```

**Comment by chenrui333** [comment]
failed on 10.14 this time
```
==> make WHAT=cmd/kubectl
+++ [1212 04:07:45] Building go targets for darwin/amd64:
+++ [1212 04:07:45] Building go targets for darwin/amd64:
    ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
+++ [1212 04:07:45] Building go targets for darwin/amd64:
    ./vendor/github.com/go-bindata/go-bindata/go-bindata
    ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
+++ [1212 04:07:45] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
+++ [1212 04:07:45] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
+++ [1212 04:07:45] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
ln: /private/tmp/kubernetes-cli-20201212-97483-4ycdk9/_output/bin/amd64: File exists
!!! [1212 04:07:55] Call tree:
!!! [1212 04:07:55]  1: hack/make-rules/build.sh:28 kube::golang::place_bins(...)
make[1]: *** [_output/bin/conversion-gen] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [generated_files] Error 2
```

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
