### PR TITLE
teleport 13.2.2

### PR DESCRIPTION
**Pull request by krehel**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
https://github.com/gravitational/teleport/releases

**Comment by krehel** [comment]
@chenrui333 - I suspect this will be coming soon.  I updated `homebrew-cask` earlier with the `v13.2.2` binaries.

**Comment by SMillerDev** [comment]
We really shouldn't if it's not released yet.

**Comment by chenrui333** [comment]
> @chenrui333 - I suspect this will be coming soon. I updated `homebrew-cask` earlier with the `v13.2.2` binaries for both `tsh` and `teleport-connect`.

yeah, let's wait a bit, ideally, we'd like to bump when there is an official release notes out.

**Comment by SMillerDev** [comment]
Cask should probably also update the livecheck to avoid pre-releases

**Comment by krehel** [comment]
> Cask should probably also update the livecheck to avoid pre-releases

The version pulled by Cask is from upstream download page which does not have this marked as a pre-release.  And the one-line install command on their download page references using `v13.2.2` along with install packages for multiple OS.  I don't think it was errant to update `cask`.

https://goteleport.com/download/

GitHub also has a version `13.2.2` with tags.  Not sure why this hasn't been bumped to `Releases`.  I'm guessing something is out of sync here.  But understand why we would hold this back until listed as a `Release`.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
