### PR TITLE
werf 1.2.195

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

relates to https://github.com/werf/werf/pull/5201

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
new linux build issue

```
  # github.com/containers/buildah
  /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/containers/buildah@v1.26.1/run_linux.go:2910:15: lockfile.Locked undefined (type lockfile.Locker has no field or method Locked)
```

**Comment by chenrui333** [comment]
> new linux build issue
> 
> ```
>   # github.com/containers/buildah
>   /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/github.com/containers/buildah@v1.26.1/run_linux.go:2910:15: lockfile.Locked undefined (type lockfile.Locker has no field or method Locked)
> ```

- relates to https://github.com/containers/storage/pull/1399

**Comment by chenrui333** [comment]
Closing for now.

**Comment by chenrui333** [comment]
`github.com/containers/buildah` upgrade for werf is not a straight upgrade.

**Pull request closed without merging**
