### PR TITLE
jupyter-completion (new formula)

### PR DESCRIPTION
**Pull request by kiendang**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Can we install completions as part of Jupyter, instead?

**Comment by kiendang** [comment]
Yes we can do that. But I think a separate formula would still be useful for those who don't install jupyter through brew. I think a lot of people would do `pip install jupyter` instead which doesn't come with completion.

I was thinking of adding completion to the Jupyter formula and keeping this as a separate formula with `conflicts_with "jupyter"` like what is done with [docker](https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker.rb) and [docker-completion](https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker-completion.rb). You don't need to `brew install docker-completion` if you `brew install docker`, but you do if you `brew cask install docker`.

**Comment by fxcoudert** [comment]
A pull request to install completions as part of Homebrew would be welcome! Let's make our package as complete as possible.

Regarding the need for a separate formula, I'm not very enthusiastic. If so, for every formula we'd need to install a separate "completion" formula, which would double our time. People who install Jupyter through other means should report the lack of completion files to that vendor, so it gets fixed there.

**Comment by kiendang** [comment]
Fair enough 👍

**Pull request closed without merging**
