### PR TITLE
mailcatcher 0.9.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.
<details>
  <summary>release notes</summary>
  <pre>## What's Changed
* Remove flexie library by @matthhan in https://github.com/sj26/mailcatcher/pull/505
* Correct the path for attachments by CID by @duncan3dc in https://github.com/sj26/mailcatcher/pull/504
* Support Ruby 3.1 by @sj26 in https://github.com/sj26/mailcatcher/pull/509
* Update Dockerfile to v0.8.1 by @ohbarye in https://github.com/sj26/mailcatcher/pull/493
* Switch from Skinny to Faye Websocket by @sj26 in https://github.com/sj26/mailcatcher/pull/510
* Update thin version by @mockdeep in https://github.com/sj26/mailcatcher/pull/530
* Add Ruby 3.2 to CI by @petergoldstein in https://github.com/sj26/mailcatcher/pull/536

## New Contributors
* @matthhan made their first contribution in https://github.com/sj26/mailcatcher/pull/505
* @duncan3dc made their first contribution in https://github.com/sj26/mailcatcher/pull/504
* @mockdeep made their first contribution in https://github.com/sj26/mailcatcher/pull/530
* @petergoldstein made their first contribution in https://github.com/sj26/mailcatcher/pull/536

**Full Changelog**: https://github.com/sj26/mailcatcher/compare/v0.8.2...v0.9.0</pre>
</details>

### CODE REVIEW

**Comment by Porkepix** [comment]
Compatible with latest ruby. Resources needs update though, but I'm not sure how you proceed to update Ruby or Perl resources, how to find the information nor if this can be automated, as it's done for python's ones.

**Comment by chenrui333** [comment]
> Compatible with latest ruby. Resources needs update though, but I'm not sure how you proceed to update Ruby or Perl resources, how to find the information nor if this can be automated, as it's done for python's ones.

I dont think we have any tools for ruby yet, but for perl, it would be https://github.com/branchvincent/homebrew-tap/blob/main/cmd/update-perl-resources.rb

**Comment by chenrui333** [comment]
```
      The offending files are:
        libexec/gems/sqlite3-1.6.3/ext/sqlite3/tmp/arm64-apple-darwin20.6.0/ports/sqlite3/3.42.0/sqlite-autoconf-3420000/config.log
```

**Comment by chenrui333** [comment]
raised an ask on the [sqlite gem](https://github.com/sparklemotion/sqlite3-ruby/issues/393) side

**Review by branchv — APPROVED** [review]

**Pull request merged**
