### PR TITLE
sourcekitten 0.21.0

### PR DESCRIPTION
**Pull request by jpsim**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by commitay** [comment]
Same `libxml2` issue as https://github.com/Homebrew/homebrew-core/pull/26487

```
swift build --disable-sandbox --configuration release -Xswiftc -static-stdlib
rm -rf "/private/tmp/sourcekitten-20180423-80961-fm8xlt/SourceKitten.dst"
swift package clean
Compile CYaml src/scanner.c
Compile CYaml src/writer.c
Compile CYaml src/reader.c
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2/module.modulemap:1:8: error: redefinition of module 'libxml2'
module libxml2 [system] [extern_c] {
       ^
/usr/include/libxml2/module.modulemap:1:8: note: previously defined here
module libxml2 [system] [extern_c] {
       ^
1 error generated.
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2/module.modulemap:1:8: error: redefinition of module 'libxml2'
module libxml2 [system] [extern_c] {
       ^
/usr/include/libxml2/module.modulemap:1:8: note: previously defined here
module libxml2 [system] [extern_c] {
       ^
1 error generated.
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2/module.modulemap:1:8: error: redefinition of module 'libxml2'
module libxml2 [system] [extern_c] {
       ^
/usr/include/libxml2/module.modulemap:1:8: note: previously defined here
module libxml2 [system] [extern_c] {
       ^
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /private/tmp/sourcekitten-20180423-80961-fm8xlt/.build/release.yaml main output:
```

**Comment by jpsim** [comment]
Doesn't look like this is related to my PR. Can an admin trigger a rebuild if this is believed to be a spurious infra failure?

**Comment by commitay** [comment]
It isn't related to this PR and a rebuild will also fail. 

It needs to be fixed in https://github.com/Homebrew/brew

**Comment by ilovezfs** [comment]
Yes @commitay is working on https://github.com/Homebrew/brew/pull/4147

**Comment by mistydemeo** [comment]
I can no longer repro this problem as of Xcode 9.4.

**Comment by yonaskolb** [comment]
This is still present in Xcode 9.4. See workarounds here https://github.com/Homebrew/brew/pull/4147

**Comment by ilovezfs** [comment]
Thanks again @jpsim!

**Comment by jpsim** [comment]
Thanks for patching & merging!

**Pull request closed without merging**
