### PR TITLE
sqlite 3.32.1, dbhash 3.32.1, sqldiff 3.32.1, sqlite-analyzer 3.32.1

### PR DESCRIPTION
**Pull request by samford**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by samford** [comment]
## `brew test-bot --only-formulae` failures

* On High Sierra (10.13):
```
Error: 11 failed steps!
brew test --verbose agda
brew test --verbose alure
brew test --verbose bnfc
brew test --verbose curaengine
brew test --verbose dromeaudio
brew test --verbose h2o
brew test --verbose nanomsg
brew test --verbose nng
brew linkage --test nvc
brew test --verbose openvdb
brew install percona-server
```

* On Mojave 10.14: Same as 10.13 but with the addition of `stubby`.
```
brew test --verbose stubby
```

* On Catalina (10.15): Same as 10.13 with the addition of `game-music-emu`, `thefuck`, and `ungit`.

```
brew test --verbose game-music-emu
brew test --verbose thefuck
brew test --verbose ungit
```

### agda
<details>
<summary>Output</summary>

```
==> brew test --verbose agda
==> FAILED
Testing agda
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200524-86679-axekgd.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/agda.rb --verbose
==> /usr/local/Cellar/agda/2.6.1/bin/agda /private/tmp/agda-test-20200524-86680-g45c0/SimpleTest.agda
Checking SimpleTest (/private/tmp/agda-test-20200524-86680-g45c0/SimpleTest.agda).
==> /usr/local/Cellar/agda/2.6.1/bin/agda -i /usr/local/Cellar/agda/2.6.1/lib/agda/src /private/tmp/agda-test-20200524-86680-g45c0/StdlibTest.agda
Checking StdlibTest (/private/tmp/agda-test-20200524-86680-g45c0/StdlibTest.agda).
==> /usr/local/Cellar/agda/2.6.1/bin/agda --js /private/tmp/agda-test-20200524-86680-g45c0/SimpleTest.agda
Compiling Agda.Primitive in /usr/local/Cellar/agda/2.6.1/share/x86_64-osx-ghc-8.10.1/Agda-2.6.1/lib/prim/Agda/Primitive.agdai to /private/tmp/agda-test-20200524-86680-g45c0/./jAgda.Agda.Primitive.js
Compiling SimpleTest in /private/tmp/agda-test-20200524-86680-g45c0/SimpleTest.agdai to /private/tmp/agda-test-20200524-86680-g45c0/./jAgda.SimpleTest.js
Error: agda: failed
An exception occurred within a child process:
  MethodDeprecatedError: Calling Language::Haskell::Cabal.cabal_sandbox is deprecated! There is no replacement.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/agda.rb:149
```
</details>

### alure
<details>
<summary>Output</summary>

```
==> brew test --verbose alure
==> FAILED
Testing alure
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200524-91830-xeu6p3.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/alure.rb --verbose
==> /usr/local/Cellar/alure/1.2_1/bin/alureplay /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/test.wav
Killing child processes...
Error: alure: failed
An exception occurred within a child process:
  Timeout::Error: execution expired
```
</details>

### bnfc
<details>
<summary>Output</summary>

```
==> brew test --verbose bnfc
==> FAILED
Testing bnfc
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200524-65013-1kitqov.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bnfc.rb --verbose
==> /usr/local/Cellar/bnfc/2.8.3/bin/bnfc -m -o. --c /private/tmp/bnfc-test-20200524-65014-f7qlxi/calc.cf
8 rules accepted

writing new file ./Absyn.h
writing new file ./Absyn.c
writing new file ./calc.l
writing new file ./calc.y
writing new file ./Parser.h
writing new file ./Skeleton.h
writing new file ./Skeleton.c
writing new file ./Printer.h
writing new file ./Printer.c
writing new file ./Test.c
writing new file ./Makefile
==> make CC=/usr/bin/clang CCFLAGS=-Os -w -pipe -march=nehalem -mmacosx-version-min=10.14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
/usr/bin/clang -Os -w -pipe -march=nehalem -mmacosx-version-min=10.14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -c Absyn.c
flex -Pcalc -oLexer.c calc.l
bison -t -pcalc calc.y -o Parser.c
/usr/bin/clang -Os -w -pipe -march=nehalem -mmacosx-version-min=10.14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -c Printer.c
/usr/bin/clang -Os -w -pipe -march=nehalem -mmacosx-version-min=10.14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -c Test.c
/usr/bin/clang -Os -w -pipe -march=nehalem -mmacosx-version-min=10.14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -c Parser.c
/usr/bin/clang -Os -w -pipe -march=nehalem -mmacosx-version-min=10.14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -c Lexer.c
Linking Testcalc...
/usr/bin/clang -Os -w -pipe -march=nehalem -mmacosx-version-min=10.14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk Absyn.o Lexer.o Parser.o Printer.o Test.o -o Testcalc
==> ./Testcalc /private/tmp/bnfc-test-20200524-65014-f7qlxi/test.calc
==> /usr/local/Cellar/bnfc/2.8.3/bin/bnfc -m -o. --cpp /private/tmp/bnfc-test-20200524-65014-f7qlxi/calc.cf
8 rules accepted

writing new file ./Absyn.H
writing new file ./Absyn.C
writing new file ./calc.l
writing new file ./calc.y
writing new file ./Parser.H
writing new file ./Skeleton.H
writing new file ./Skeleton.C
writing new file ./Printer.H
writing new file ./Printer.C
writing new file ./Test.C
writing new file ./Makefile
==> make CC=/usr/bin/clang++ CCFLAGS=-Os -w -pipe -march=nehalem -mmacosx-version-min=10.14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
/usr/bin/clang++ -Os -w -pipe -march=nehalem -mmacosx-version-min=10.14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -c Absyn.C
flex -oLexer.C calc.l
bison calc.y -o Parser.C
/usr/bin/clang++ -Os -w -pipe -march=nehalem -mmacosx-version-min=10.14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -c Printer.C
/usr/bin/clang++ -Os -w -pipe -march=nehalem -mmacosx-version-min=10.14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -c Test.C
/usr/bin/clang++ -Os -w -pipe -march=nehalem -mmacosx-version-min=10.14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -c Parser.C
/usr/bin/clang++ -Os -w -pipe -march=nehalem -mmacosx-version-min=10.14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -c Lexer.C
Linking Testcalc...
/usr/bin/clang++ -Os -w -pipe -march=nehalem -mmacosx-version-min=10.14 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk Absyn.o Lexer.o Parser.o Printer.o Test.o -o Testcalc
==> ./Testcalc /private/tmp/bnfc-test-20200524-65014-f7qlxi/test.calc
Error: bnfc: failed
An exception occurred within a child process:
  MethodDeprecatedError: Calling Language::Haskell::Cabal.cabal_sandbox is deprecated! There is no replacement.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bnfc.rb:88
```
</details>

### curaengine
<details>
<summary>Output</summary>

```
Testing curaengine
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200524-50858-ptlmci.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/curaengine.rb --verbose
==> Downloading https://raw.githubusercontent.com/Ultimaker/Cura/master/resources/definitions/fdmextruder.def.json
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.2.17-96-g2e801c3\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --fail --silent --retry 3 --location --remote-time --continue-at 0 --output /Users/brew/Library/Caches/Homebrew/downloads/b78cfc8196149e1010092de60a4129f41ce9db5fec64b276a19eaa9c0cfa3acf--fdmextruder.def.json.incomplete https://raw.githubusercontent.com/Ultimaker/Cura/master/resources/definitions/fdmextruder.def.json
cp -p /Users/brew/Library/Caches/Homebrew/downloads/b78cfc8196149e1010092de60a4129f41ce9db5fec64b276a19eaa9c0cfa3acf--fdmextruder.def.json /private/tmp/curaengine--fdmextruder_defaults-20200524-50859-1uorjzc/fdmextruder.def.json
==> Verifying b78cfc8196149e1010092de60a4129f41ce9db5fec64b276a19eaa9c0cfa3acf--fdmextruder.def.json checksum
==> Downloading https://raw.githubusercontent.com/Ultimaker/Cura/master/resources/definitions/fdmprinter.def.json
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.2.17-96-g2e801c3\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --fail --silent --retry 3 --location --remote-time --continue-at 0 --output /Users/brew/Library/Caches/Homebrew/downloads/7b892c41f22fcc50c26807b05e0f3fff94a7e514cf9eb49c1282ecc6f8721119--fdmprinter.def.json.incomplete https://raw.githubusercontent.com/Ultimaker/Cura/master/resources/definitions/fdmprinter.def.json
==> Verifying 7b892c41f22fcc50c26807b05e0f3fff94a7e514cf9eb49c1282ecc6f8721119--fdmprinter.def.json checksum
Error: curaengine: failed
An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: e16ffd9f6412dc7160485f3452041ac1d56ba786d8cf65a009bdfc4be526d070
  Actual: fa0916a38e67299a3a5637246ade56b493b71e56dde421c27851fea935380466
 Archive: /Users/brew/Library/Caches/Homebrew/downloads/7b892c41f22fcc50c26807b05e0f3fff94a7e514cf9eb49c1282ecc6f8721119--fdmprinter.def.json
To retry an incomplete download, remove the file above.
```
</details>

### dromeaudio
<details>
<summary>Output</summary>

```
==> brew test --verbose dromeaudio
==> FAILED
Testing dromeaudio
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200524-85230-rd10bn.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/dromeaudio.rb --verbose
==> /usr/local/Cellar/dromeaudio/0.3.0/bin/DromeAudioPlayer /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/test.mp3
DromeAudio Exception: AudioDriverOSX::AudioDriverOSX(): AudioUnitSetProperty (for StreamFormat) failed
Audio driver initialization failed
Error: dromeaudio: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/dromeaudio/0.3.0/bin/DromeAudioPlayer
```
</details>

### game-music-emu
<details>
<summary>Output</summary>

```
==> brew test --verbose game-music-emu
==> FAILED
3793
Testing game-music-emu
3794
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200524-85496-c9uf22.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/game-music-emu.rb --verbose
3795
==> /usr/bin/clang test.c -I/usr/local/Cellar/game-music-emu/0.6.3/include -L/usr/local/Cellar/game-music-emu/0.6.3/lib -lgme -o test -Os -w -pipe -march=nehalem -mmacosx-version-min=10.15 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
3796
==> ./test
3797
dyld: Library not loaded: @rpath/libclang_rt.ubsan_osx_dynamic.dylib
3798
  Referenced from: /usr/local/opt/game-music-emu/lib/libgme.0.dylib
3799
  Reason: image not found
3800
Error: game-music-emu: failed
3801
An exception occurred within a child process:
3802
  BuildError: Failed executing: ./test
```
</details>

### h2o
<details>
<summary>Output</summary>

```
==> FAILED
Testing h2o
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200524-59784-sitj33.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/h2o.rb --verbose
[INFO] raised RLIMIT_NOFILE to 10240
h2o server (pid:59792) is ready to serve requests
==> curl localhost:57135
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   177  100   177    0     0  22334      0 --:--:-- --:--:-- --:--:-- 25285
Killing child processes...
received SIGTERM, gracefully shutting down
Error: h2o: failed
An exception occurred within a child process:
  Timeout::Error: execution expired

```
</details>

### nanomsg
<details>
<summary>Output</summary>

```
==> brew test --verbose nanomsg
==> FAILED
Testing nanomsg
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200524-97371-l05d95.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nanomsg.rb --verbose
==> /usr/local/Cellar/nanomsg/1.1.5/bin/nanocat --req --connect tcp://127.0.0.1:59589 --format ascii --data brew
brew
Killing child processes...
Error: nanomsg: failed
An exception occurred within a child process:
  Timeout::Error: execution expired
```
</details>

### nng
<details>
<summary>Output</summary>

```
==> brew test --verbose nng
==> FAILED
Testing nng
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200524-12493-z0lrr.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nng.rb --verbose
==> /usr/local/Cellar/nng/1.3.0/bin/nngcat --req --connect tcp://127.0.0.1:59757 --format ascii --data brew
brewKilling child processes...
Error: nng: failed
An exception occurred within a child process:
  Timeout::Error: execution expired
```
</details>

### nvc
<details>
<summary>Output</summary>

```
==> brew linkage --test nvc
==> FAILED
Broken dependencies:
  /usr/local/opt/llvm/lib/libc++.1.dylib (llvm)
```
</details>

### openvdb
<details>
<summary>Output</summary>

```
==> brew test --verbose openvdb
==> FAILED
Testing openvdb
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200524-50945-hkel77.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openvdb.rb --verbose
==> Downloading https://nexus.aswf.io/content/repositories/releases/io/aswf/openvdb/models/cube.vdb/1.0.0/cube.vdb-1.0.0.zip
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.2.17-96-g2e801c3\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --fail --silent --retry 3 --location --remote-time --continue-at 0 --output /Users/brew/Library/Caches/Homebrew/downloads/d856c5b3e869d4324409affae83d00b5054395e6c03b5a3e75467fca5138a698--cube.vdb-1.0.0.zip.incomplete https://nexus.aswf.io/content/repositories/releases/io/aswf/openvdb/models/cube.vdb/1.0.0/cube.vdb-1.0.0.zip
curl: (6) Could not resolve host: nexus.aswf.io
Error: openvdb: failed
An exception occurred within a child process:
  DownloadError: Failed to download resource "openvdb--test_file"
Download failed: https://nexus.aswf.io/content/repositories/releases/io/aswf/openvdb/models/cube.vdb/1.0.0/cube.vdb-1.0.0.zip
```
</details>

### percona-server
<details>
<summary>Output</summary>

```
==> brew install percona-server
==> FAILED
==> Downloading https://homebrew.bintray.com/bottles/percona-server-8.0.19-10.mojave.bottle.tar.gz
Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/4b0e00c446d4682dda66b092890045070001bad59c6f109fe1174dd6069b436a--percona-server-8.0.19-10.mojave.bottle.tar.gz
==> Pouring percona-server-8.0.19-10.mojave.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink lib/libprotobuf-lite.dylib
Target /usr/local/lib/libprotobuf-lite.dylib

is a symlink belonging to protobuf. You can unlink it:
  brew unlink protobuf

To force the link and overwrite all conflicting files:
  brew link --overwrite percona-server

To list all files that would be deleted:
  brew link --overwrite --dry-run percona-server

Possible conflicting files are:
/usr/local/lib/libprotobuf-lite.dylib -> /usr/local/Cellar/protobuf/3.12.1/lib/libprotobuf-lite.dylib
/usr/local/lib/libprotobuf.dylib -> /usr/local/Cellar/protobuf/3.12.1/lib/libprotobuf.dylib
==> Caveats
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation
MySQL is configured to only allow connections from localhost by default
To connect run:
    mysql -uroot

To have launchd start percona-server now and restart at login:
  brew services start percona-server
Or, if you don't want/need a background service you can just run:
  mysql.server start
==> Summary
/usr/local/Cellar/percona-server/8.0.19-10: 307 files, 294.5MB
```
</details>

### stubby
<details>
<summary>Output</summary>

```
==> brew test --verbose stubby
==> FAILED
Testing stubby
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200524-32822-1e52u3z.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/stubby.rb --verbose
==> /usr/local/Cellar/stubby/0.3.0/bin/stubby -i -C stubby_test.yml
[14:27:41.334729] STUBBY: Stubby version: Stubby 0.3.0
[14:27:41.348600] STUBBY: Read config from file stubby_test.yml
Result: Config file syntax is valid.
[14:27:41.363360] STUBBY: Stubby version: Stubby 0.3.0
[14:27:41.369072] STUBBY: Read config from file /private/tmp/stubby-test-20200524-32823-5c0k7n/stubby_test.yml
[14:27:41.370444] STUBBY: DNSSEC Validation is OFF
[14:27:41.370485] STUBBY: Transport list is:
[14:27:41.370489] STUBBY:   - TLS
[14:27:41.370492] STUBBY:   - UDP
[14:27:41.370495] STUBBY:   - TCP
[14:27:41.370499] STUBBY: Privacy Usage Profile is Opportunistic
[14:27:41.370502] STUBBY: (NOTE a Strict Profile only applies when TLS is the ONLY transport!!)
[14:27:41.370505] STUBBY: Starting DAEMON....
==> dig @127.0.0.1 -p 5553 getdnsapi.net
Error: stubby: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </status:\ NOERROR/> was expected to be =~
<"\n" +
"; <<>> DiG 9.16.3 <<>> @127.0.0.1 -p 5553 getdnsapi.net\n" +
"; (1 server found)\n" +
";; global options: +cmd\n" +
";; Got answer:\n" +
";; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 4873\n" +
";; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n" +
";; WARNING: recursion requested but not available\n" +
"\n" +
";; QUESTION SECTION:\n" +
";getdnsapi.net.\t\t\tIN\tA\n" +
"\n" +
";; Query time: 8 msec\n" +
";; SERVER: 127.0.0.1#5553(127.0.0.1)\n" +
";; WHEN: Sun May 24 15:27:48 BST 2020\n" +
";; MSG SIZE  rcvd: 31\n" +
"\n">.
```
</details>

### thefuck
<details>
<summary>Output</summary>

```
==> brew test --verbose thefuck
==> FAILED
12011
Testing thefuck
12012
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200525-28663-1uaphrg.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/thefuck.rb --verbose
12013
==> /usr/local/Cellar/thefuck/3.30/bin/thefuck --version 2>&1
12014
==> /usr/local/Cellar/thefuck/3.30/bin/thefuck --alias
12015
==> /usr/local/Cellar/thefuck/3.30/bin/thefuck git branchh
12016
No fucks given
12017

12018
Error: thefuck: failed
12019
An exception occurred within a child process:
12020
  Test::Unit::AssertionFailedError: <0> expected but was
12021
<1>.
```
</details>

### ungit
<details>
<summary>Output</summary>

```
==> brew test --verbose ungit
12428
==> FAILED
12429
Testing ungit
12430
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200525-57611-f4cnrg.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ungit.rb --verbose
12431
==> curl -s 127.0.0.1:52773/
12432

12433
==> ps -o pid,ppid
12434
Error: ungit: failed
12435
An exception occurred within a child process:
12436
  Test::Unit::AssertionFailedError: <0> expected but was
12437
<7>.
```
</details>

**Comment by samford** [comment]
I've done my due diligence with the CI failures and none of them seem related to this `sqlite` update.

I don't imagine there's any benefit in kicking off another CI run and this is probably good to merge but it would be good for another maintainer to check my work.

**Comment by SMillerDev** [comment]
The deprecations should probably be addressed ASAP.

> Timeout::Error: execution expired

Usually means that we're waiting for a test that isn't killed properly. You can remove the TERM statements nowadays because brew will kill them in a more consistent way at the end of the test.

**Comment by SMillerDev** [comment]
percona-server probably needs a "conflicts-with" for protobuf based on the output.

**Comment by samford** [comment]
> The deprecations should probably be addressed ASAP.

Looking through related formulae using `cabal_sandbox` (in the install and test), it would be better for someone else to handle these changes. I don't know the first thing about Haskell and I don't have the time to do a deep dive at this moment.

> Usually means that we're waiting for a test that isn't killed properly. You can remove the TERM statements nowadays because brew will kill them in a more consistent way at the end of the test.

Gotcha, I'll create PRs to remove the relevant bits from the tests for `h2o`, `nanomsg`, `nng`, `stubby`, and `ungit`.

`alure` and `thefuck` don't have a `Process.kill`/`Process.wait` in the test, so I'm not sure how those would be fixed.

> percona-server probably needs a "conflicts-with" for protobuf based on the output.

Any preferences on the text for `conflicts_with` here? Something like `both install libprotobuf(-lite) libraries.`?

---

Past that, do you think this PR should be blocked on these unrelated failures?

**Comment by SMillerDev** [comment]
> Looking through related formulae using cabal_sandbox (in the install and test), it would be better for someone else to handle these changes.

There is an issue open for this from @Bo98 

> Any preferences on the text for conflicts_with here? Something like both install libprotobuf(-lite) libraries.?

Sounds fine

> Past that, do you think this PR should be blocked on these unrelated failures?

I think if CI fails something must be done to make sure that doesn't happen again. Especially with test failures I'm a bit hasitant to just dismiss them.

**Comment by SMillerDev** [comment]
Alureplay's homepage has a link to a

**Comment by samford** [comment]
> Alureplay's homepage has a link to a git repo which in turn has reference to a github repo. So I made an issue to ask if this is an official successor.

Does this have any impact on the test timeout? The test works fine for me locally and all it does is play a .wav file: `system bin/"alureplay", test_fixtures("test.wav")`, so I'm not sure how we would resolve the timeout on CI.

> For dromeaudio I think it's time to mark it as disabled. If we can't get it to perform it's main function....

I commented on #55292 with some additional information and that may or may not impact the decision here.

---

Outside of these two, the only other one that isn't being resolved in another PR is `thefuck`. This test fine for me locally, so I'll have to open a PR to debug it on CI (like we did for `ungit`).

**Comment by samford** [comment]
Welp, sqlite 3.32.1 was apparently released in the interim time, so I'm going to update this PR and see what happens on CI this time around.

**Comment by samford** [comment]
The failures in this latest run will either be fixed in another PR (`agda`, `bnfc`) or are related to unreliable tests that can fail due to certain circumstances (timouts in `alure` and `libsoundio`, upstream website unreliability in `yafc`). Unless there are specific ways to fix the tests for the latter three formulae, I think we should just go ahead and merge this instead of holding it up further.

---

CI failures across all macOS versions:

```
brew test --verbose agda
brew test --verbose alure
brew test --verbose bnfc
```

Additional failure for 10.13:

```
brew test --verbose libsoundio
```

Additional failure for 10.15:

```
brew test --verbose yafc
```

---

The `agda`, `alure` and `bnfc` failures are the same ones we encountered before, so they're expected. `agda` and `bnfc` will be fixed in the Cabal issue (#55253) and I'm not sure how we would fix the `alure` test timeout other than not playing an audio file.

### libsoundio

`Timeout::Error: execution expired`

<details>
<summary>Output</summary>

```
==> brew test --verbose libsoundio
==> FAILED
Testing libsoundio
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200530-37825-6qsthf.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libsoundio.rb --verbose
==> /usr/bin/clang -L/usr/local/Cellar/libsoundio/2.0.0/lib -lsoundio test.c -o test
==> ./test
Killing child processes...
Error: libsoundio: failed
An exception occurred within a child process:
  Timeout::Error: execution expired
```
</details>


### yafc

This just happened to fail due to the upstream Speedtest server.

<details>
<summary>Output</summary>

```
==> brew test --verbose yafc
==> FAILED
Testing yafc
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200530-47645-1aa89k8.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yafc.rb --verbose
==> /usr/local/Cellar/yafc/1.3.7_4/bin/yafc -W /private/tmp/yafc-test-20200530-47646-siie7g -a ftp://speedtest.tele2.net/
Looking up speedtest.tele2.net... 
                                  
Connecting to speedtest.tele2.net at port 21...
Connected to speedtest.tele2.net ([90.130.70.73]:21).
(vsFTPd 3.0.3)
logging in anonymously...
Tired of waiting for reply, timeout after 42 seconds
Error: yafc: failed
An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /private/tmp/yafc-test-20200530-47646-siie7g/512KB.zip
```
</details>

**Comment by Bo98** [comment]
> I think we should just go ahead and merge this instead of holding it up further.

:+1: considering these are known failures.

**Pull request closed without merging**
