### PR TITLE
python: Fix building from sources

### PR DESCRIPTION
**Pull request by Kentzo**
New process absolutely requires custom venv for docs.

See https://devguide.python.org/documenting/#using-make-make-bat

### CODE REVIEW

**Comment by ilovezfs** [comment]
Sorry it's not clear to me what this is fixing. We're not seeing any problems building this on our CI. Can you please elaborate on what the goal here is?

**Comment by Kentzo** [comment]
@ilovezfs Did I answer the question?

**Review by ilovezfs — CHANGES_REQUESTED** [review]
Yes. I believe that means we should remove the `sphinx-doc` dependency from the formula since the `make venv` is handling that.

**Comment by ilovezfs** [comment]
@Kentzo Thanks for the PR. I managed to get it to continue to support offline installations with https://github.com/Homebrew/homebrew-core/pull/28825 and https://github.com/Homebrew/homebrew-core/pull/28824. Please let us know if you have any trouble with that.

**Pull request closed without merging**
