### PR TITLE
libmill 1.14

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
Seems kind of weird this needs the autotools _and_ `cmake`.

**Comment by apjanke** [comment]
cmake looks unneeded; builds and tests fine without it.

**Comment by ilovezfs** [comment]
Travis seems to run both: https://github.com/sustrik/libmill/blob/master/.travis.yml#L32-L42

**Comment by DomT4** [comment]
It looks like they're intentionally supporting two different build systems. No idea which one we should be using.

**Comment by ilovezfs** [comment]
Looks like the more actively maintained one is Autotools. The Makefile that CMake generated doesn't even seem to have an install target.

**Pull request closed without merging**
