### PR TITLE
pdns 3.4.9

### PR DESCRIPTION
**Pull request by justinclift**
Also adjusted to use Homebrew OpenSSL instead of system provided
one, and added a basic test clause to verify installation

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Test failing: http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1958/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_pdns/

**Comment by justinclift** [comment]
Weird, it passed here.  I'll just remove it.

**Comment by mikemcquaid** [comment]
Let's see if we can't get it working instead.

**Comment by justinclift** [comment]
I don't have the time, sorry.

**Comment by mikemcquaid** [comment]
Please re-add the test to let another contributor try to fix it up, thanks.

**Comment by justinclift** [comment]
Done.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/84edcf8c746fddebdbe4410cf69a993dbd5506fe. Thank you for your contribution to Homebrew @justinclift; we appreciate it! :smiley_cat:

**Pull request closed without merging**
