### PR TITLE
tor: bump for openssl 1.0.2k

### PR DESCRIPTION
**Pull request by tdsmith**

### CODE REVIEW

**Comment by rakkesh** [comment]
Is the revision update required? `tor` seems to be running fine without recompiling from source.

**Comment by MikeMcQuaid** [comment]
Given this is dynamically linked I'm not sure I understand either?

**Comment by tdsmith** [comment]
I asked Dom last night; it (used to?) prints a warning banner if the
compile time version is different from the runtime version but I think it's
just cosmetic.

**Comment by DomT4** [comment]
At least for `devel`, which I pretty much always run with `tor` so can't advise on stable, the warning is no longer present so I guess upstream scrapped it or at least tightened it up to allow for updates across the same OpenSSL branch that _should_ be compatible. Presuming the warning is gone on stable too I'd presume this is alright to stop bothering with.

However, `stunnel` is still whingy:

```
[.] stunnel 5.39 on x86_64-apple-darwin16.3.0 platform
[.] Compiled with OpenSSL 1.0.2j  26 Sep 2016
[.] Running  with OpenSSL 1.0.2k  26 Jan 2017
[.] Update OpenSSL shared libraries or rebuild stunnel
[.] Threading:PTHREAD Sockets:POLL,IPv6 TLS:ENGINE,FIPS,OCSP,PSK,SNI
[ ] errno: (*__error())
```

And apparently `libevent` still has some Sierra issues despite the patch, at least in the way `tor` is using it:

```
Jan 27 20:56:19.906 [warn] Warning from libevent: kq_init: detected broken kqueue; not using.: Invalid argument
```

**Comment by tdsmith** [comment]
I assume neither other package is tor-related and therefore not actionable here? I'll close this; thanks!

**Comment by DomT4** [comment]
`stunnel` bump in https://github.com/Homebrew/homebrew-core/pull/9352, and there's a `libevent` PR from someone else in https://github.com/Homebrew/homebrew-core/pull/9344 that maybe hopefully fixes the remaining Sierra issues there.

**Pull request closed without merging**
