### PR TITLE
i2pd 2.45.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
```
  ==> Testing i2pd
  ==> /opt/homebrew/Cellar/i2pd/2.45.0/bin/i2pd --datadir=/private/tmp/i2pd-test-20230103-98089-18ecam0 --pidfile=/private/tmp/i2pd-test-20230103-98089-18ecam0/i2pd.pid --daemon
  libc++abi: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
  Error: i2pd: failed
  An exception occurred within a child process:
    BuildError: Failed executing: /opt/homebrew/Cellar/i2pd/2.45.0/bin/i2pd --datadir=/private/tmp/i2pd-test-20230103-98089-18ecam0 --pidfile=/private/tmp/i2pd-test-20230103-98089-18ecam0/i2pd.pid --daemon
```

**Comment by p-linnane** [comment]
@r4sas Would you mind taking a look at this test failure?

**Comment by p-linnane** [comment]
Opened an issue upstream: https://github.com/PurpleI2P/i2pd/issues/1836

**Comment by r4sas** [comment]
We need someone who can take full backtrace. No one in our team have Apple M1 devices.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
