### PR TITLE
grafana 6.7.1

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
only test failed on mojave build

```
==> brew test grafana --verbose
==> FAILED
Testing grafana
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200328-77000-uoygl4.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/grafana.rb --verbose
==> /usr/local/Cellar/grafana/6.7.1/bin/grafana-server -v
Version 6.7.1 (commit: unknown-dev, branch: master)
Error: grafana: failed
An exception occurred within a child process:
  Timeout::Error: execution expired
```

**Comment by chenrui333** [comment]
Give it another run.
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Timed out, @BrewTestBot test this please

**Comment by Bo98** [comment]
Well it worked, but I can't say it's a very good test if it took 3 attempts...

Maybe we just need to increase the timeout on line 119?

**Comment by chenrui333** [comment]
rebased to the latest master for the latest github action flow

@Bo98 agree, if it times out again, we should increase the time out setting.

Also there is a new release out with v6.7.2

**Pull request closed without merging**
