### PR TITLE
neovim: remove python@2 dependency

### PR DESCRIPTION
**Pull request by methane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
We'll need a regression test to verify it works with Python 3. See the `test do` blocks in `vim` and `macvim` for examples.

**Comment by methane** [comment]
@ilovezfs Actually speaking, this formula doesn't enable Python support for neovim.

Neovim use very different approach for Python/Ruby support.  It executes external process
and communicate with it via RPC.

See also: neovim/homebrew-neovim#18

**Comment by ilovezfs** [comment]
@methane that issue in the neovim tracker is pretty old. The support should be vendored into the formula rather than using a caveat.

**Comment by methane** [comment]
@ilovezfs Hmm, can I `pip3 install neovim` directly instead of creating virtualenv (like aws-shell)?
User may want to use other libraries they installed via `pip3 install` from neovim.

**Comment by ilovezfs** [comment]
@methane the user should can set PYTHONPATH if they want to do that. See comment here: https://github.com/Homebrew/homebrew-core/pull/21370#issuecomment-349637739

If that approach is unacceptable we can use old style like in https://github.com/Homebrew/homebrew-core/blob/master/Formula/snakemake.rb#L72-L86

**Comment by methane** [comment]
I'm not brew expert and I don't know what's the best way to vendor support.
But please note that neovim formula doesn't provide out-of-the-box Python support from start
and `depends_on "python@2"` was added without Python support.

Unlike vim/macvim, neovim doesn't require rebuild itself for adding Python/Ruby support.
If I want Python 3 support, I can add it by `pip3 install neovim`.  If I want Ruby support, I can add it by `gem install neovim`.

So, my question is: Is it mandatory that out-of-the-box Python support?.
Anyway, current `depends_on "python@2"` is totally useless.

**Comment by ilovezfs** [comment]
@javian do you know why the original formula had
```
  depends_on :python if MacOS.version <= :snow_leopard 
```

**Comment by javian** [comment]
No I don't. This is the commit that added it where there's basically no further info https://github.com/neovim/homebrew-neovim/commit/ee2609c3da949c407cb0c788ee2b96b27b4eb47a

**Comment by javian** [comment]
Just note that neovim has the `:CheckHealth` command similar to `brew doctor` which will inform the user of the stuff and more that is in this caveat. This is also noted as the first line in the faq https://github.com/neovim/neovim/wiki/FAQ

```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    python2 not found in search path or not executable.
    /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
    python2.6 not found in search path or not executable.
    /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - ERROR: Python provider error
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.5
  - INFO: python3-neovim version: 0.2.4
  - OK: Latest python3-neovim is installed: 0.2.4

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
  - WARNING: Missing "neovim" gem.
    - ADVICE:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

## Node provider (optional)
  - INFO: Node: v9.11.1
  - INFO: Host: /usr/local/bin/neovim-node-host
  - OK: Latest "neovim" npm is installed: 3.5.2
```

**Comment by methane** [comment]
Should I remove caveats?

**Comment by methane** [comment]
What I can do?
I completely graduated Python 2 and I don't want to install Python 2 only for unused dependency....

**Comment by commitay** [comment]
Yes, please remove the caveats as they aren't Homebrew specific.

**Review by fxcoudert — APPROVED** [review]
Looks good as it is, remove the unnecessary dep.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @methane and sorry for the delay!

**Pull request merged**
