### PR TITLE
wine: bump dependencies

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by fxcoudert — DISMISSED** [review]
Please also update `mono` to 4.7.0 (http://dl.winehq.org/wine/wine-mono/4.7.0/), `freetype` to 2.8, `libgphoto2` to 2.5.13. And why are the `sane-backends` mirrors commented out?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by yurikoles** [comment]
sup?

**Comment by ilovezfs** [comment]
It's chugging away on CI :)

**Comment by fxcoudert** [comment]
`libtiff 4.0.8` is out

**Comment by yurikoles** [comment]
>`libtiff 4.0.8` is out
we have it in formulae already :)

**Comment by ilovezfs** [comment]
@yurikoles that's because I added it after fx pointed that out.

**Review by fxcoudert — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks for the pull request @yurikoles

**Comment by yurikoles** [comment]
@ilovezfs you are welcome

**Pull request closed without merging**
