### PR TITLE
mupdf mupdf-tools pymupdf 1.24.2

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
pymupdf only failed to build on linux

**Comment by chenrui333** [comment]
```
/home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: cannot find -lmupdf: No such file or directory
collect2: error: ld returned 1 exit status
```

**Comment by baskerville** [comment]
Support for `.cbr` was added in 1.24.0 via *libarchive*.

**Comment by chenrui333** [comment]
## linux 

```
brew install --verbose --build-bottle pymupdf
brew install --build-from-source pymupdf
brew install --only-dependencies --verbose --build-bottle enex2notion
brew install --verbose --build-bottle enex2notion
```

**Comment by chenrui333** [comment]
gonna kick off new efforts with 1.24.5

**Pull request closed without merging**
