### PR TITLE
llnode: don't unconditionally call Xcode version

### LINKED ISSUE #20052: I've been trying to install man and mysql using brew and it's been throwing the following error:
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [Yes ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ Yes] Ran `brew update` and retried your prior step?
- [Yes ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [Yes ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [Yes ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why) 
  I'm trying to install man and mysql
- What happened (include command output)
taj.palecanda:~ $ brew install mvn31
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 4614, done.
remote: Compressing objects: 100% (4398/4398), done.
remote: Total 4614 (delta 34), reused 310 (delta 8), pack-reused 0
Receiving objects: 100% (4614/4614), 3.83 MiB | 2.96 MiB/s, done.
Resolving deltas: 100% (34/34), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/imagesnap.rb
undefined method `>=' for nil:NilClass
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llnode.rb
undefined method `>=' for nil:NilClass
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core
taj.palecanda:~ $ 

- What you expected to happen
   install the software
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Might fix #20052.

### CODE REVIEW

**Comment by ilovezfs** [comment]
May be better to check clang_build_version instead

**Comment by DomT4** [comment]
Sure, done.

**Comment by ilovezfs** [comment]
🎃

**Comment by DomT4** [comment]
Thanks ILZ ❤️

**Pull request merged**
