### PR TITLE
readline: drop universal

### PR DESCRIPTION
**Pull request by fxcoudert**
Former wine dependency.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by tdsmith** [comment]
Please remember to pull and publish the new bottle when you bump the revision. (Should the revision have been bumped, here?)

**Comment by ilovezfs** [comment]
>Should the revision have been bumped, here?

Yes, because it was ENV.universal_binary (i.e., always building universal), so the bottle contents are a tad different now :)

**Comment by tdsmith** [comment]
Gotcha, thanks.

**Comment by fxcoudert** [comment]
@tdsmith thanks for catching that… forgot this one was non optional universal

**Pull request merged**
