### PR TITLE
dynare 4.6.3

### PR DESCRIPTION
**Pull request by carlocab**
Follow up to #65956.

### CODE REVIEW

**Comment by carlocab** [comment]
Ok, I solved the missing package issue from  #65956. The test is now failing for some other reason...

**Comment by carlocab** [comment]
Tried compiling locally. It spat out this warning:
```
Warning: dynare dependency gmp was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
```
It doesn't look like this is what's causing the test failure, but it might be worth fixing still. If I can sort out this test failure.

**Comment by carlocab** [comment]
Sigh. Thanks, Big Sur.

**Comment by carlocab** [comment]
https://forum.dynare.org/t/pre-processing-failed-with-source-build-on-big-sur/17311

**Review by fxcoudert — APPROVED** [review]
Unclear why we would need to force static libgcc, but…

**Comment by carlocab** [comment]
Same, but it was the only idea I had after looking at their build docs.

**Pull request closed without merging**
