### PR TITLE
ghc@8.2 8.2.2 (new formula)

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
`ghc@8.0` was created because we had formulas that did not build with the later version. Here it appears all haskell formulas that built with 8.2 also build with 8.4, so can we skip the versioned formula?

I think there is no real user demand for ghc versioned formulas, with `ghc@8.0` having 35 installs a month compared to ghc's 3057.

**Comment by ilovezfs** [comment]
I don'tt want to unnecessarily downgrade the ghc version of things that have already moved to 8.2. The focus should be on the last 3 stragglers using 8.0 and getting them on 8.2 or 8.4 so we can remove 8.0.

**Comment by ilovezfs** [comment]
I don't want to unnecessarily downgrade the ghc version of things that have already moved to 8.2. The focus should be on the last 3 stragglers using 8.0 and getting them on 8.2 or 8.4 so we can remove 8.0.

**Comment by ilovezfs** [comment]
Sorry I thought you were suggesting moving them to 8.0 not 8.4 What makes you think they build with 8.4? So far everything I have tried fails to build with 8.4.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
