### PR TITLE
kde: livecheck update

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

- followup #153729

### CODE REVIEW

**Review by samford — CHANGES_REQUESTED** [review]
The `#formula` and `#cask` methods are only intended to be used when there's a clear parent/child (or primary/ancillary, general/specific) relationship between formulae/casks (e.g., `boost-bcp`, `boost-mpi`, `boost-python3` are more specific formulae that use the check for the `boost` formula). We don't use formula/cask references when there's a sibling relationship or there isn't a clear primary formula/cask.

In this case, `extra-cmake-modules` is simply one of many frameworks in this directory, so these formulae all have equal standing. I understand the desire to ease the maintenance burden and automatically align these checks but using a `#formula` reference here isn't appropriate.

These should be updated to use the same `livecheck` block as `extra-cmake-modules` instead:

```ruby
  livecheck do
    url "https://download.kde.org/stable/frameworks/"
    regex(%r{href=.*?v?(\d+(?:\.\d+)+)/?["' >]}i)
  end
```

**Comment by chenrui333** [comment]
I see, I thought `formula` approach can be applied to the synced formulae, let me update it then.

**Comment by samford** [comment]
> I see, I thought `formula` approach can be applied to the synced formulae, let me update it then.

There's often a correlation between synced formulae and use of a `livecheck` block reference but not always. The criteria for using `#formula`/`#cask` is stricter than the criteria for syncing formula versions. [A bit of history: `livecheck` block references preceded `synced_versions_formulae.json` and the livecheck references were used to initially seed that file.]

There are a number of formulae that share a version (and sometimes the same `stable` URL) but shouldn't use `#formula` because there isn't a primary/secondary relationship (e.g., the `*beat` formulae, the `avro-*` formulae, `buildifier`/`buildozer`, etc.). Some of those are in `synced_versions_formulae.json` but it's not appropriate to use a `livecheck` block reference because they don't meet the previously-described criteria.

**Review by samford — APPROVED** [review]

**Comment by chenrui333** [comment]
yeah, make sense, i dont have particular preferences, mostly use it for connivence as they are livecheck against the same url.

**Comment by samford** [comment]
> yeah, make sense, i dont have particular preferences, mostly use it for connivence as they are livecheck against the same url.

Please remember the primary/secondary requirement for `livecheck` block references going forward.

I implemented `livecheck` block references to save us effort where appropriate but using them when there's not a primary/secondary relationship can lead to unexpected behavior (as described above). Tracking down those types of issues is considerably harder than manually maintaining duplicate `livecheck` blocks (as in this PR), so we should only be using `#formula` when there's a clear primary/secondary relationship (not equal formulae).

I'll see about creating a brew PR to add an explanation about this requirement to the livecheck docs, as this is an oversight on my part.

**Pull request merged**
