### PR TITLE
capstone 3.0.5

### PR DESCRIPTION
**Pull request by aquynh**
Update for newly released Capstone v3.0.5

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@aquynh why the close?

**Comment by aquynh** [comment]
Because i am not sure how to fix the issue, when verification was not
passed. Waiting for brew experts to submit a better update.

**Comment by ilovezfs** [comment]
The install method currently has
```
    if build.head?
      ENV["PREFIX"] = prefix
    else
      # Capstone's Make script ignores the prefix env and was installing
      # in /usr/local directly. So just inreplace the prefix for less pain.
      # https://github.com/aquynh/capstone/issues/228
      inreplace "make.sh", "export PREFIX=/usr/local", "export PREFIX=#{prefix}"
    end
```
I assume this just needs to be updated to be
```
    ENV["PREFIX"] = prefix
```

**Comment by aquynh** [comment]
thanks a lot, but looks like this still fails on High Sierra?

**Comment by ilovezfs** [comment]
just a CI blip

**Comment by aquynh** [comment]
so that is just false positive, nice!

**Comment by ilovezfs** [comment]
Thanks for the upgrade, @aquynh! Shipped.

**Comment by aquynh** [comment]
@ilovezfs: you are amazing, my gratitude!

**Comment by ilovezfs** [comment]
@aquynh thanks for the kind words. You're welcome!

**Pull request closed without merging**
