### PR TITLE
openmotif: upstream Linux fix

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can this be patched upstream?

**Comment by cho-m** [comment]
Ubuntu/Debian has been using a patch since 2011: 
https://bugs.launchpad.net/ubuntu/+source/openmotif/+bug/705294

While Fedora/Arch have been disabling demos: 
https://src.fedoraproject.org/rpms/motif/blob/rawhide/f/motif-2.3.4-no_demos.patch

**Comment by danielnachun** [comment]
I'm not sure we can really consider this patch or the one for `prover9` to really be bug fixes of the formulae themselves.  The reason both of those patches are needed is because Ubuntu 16.04 LTS links with `--ld-no-add-needed`, and this makes the order of the linker flags matter.  

However, Ubuntu changed this in 18.04 LTS and as far as I know most distros have never used that option either, probably because it breaks so many build systems.  If add a comment explaining why we need this right now and that it should be removed with Ubuntu 18.04 LTS, would that be sufficient?

**Comment by danielnachun** [comment]
I added a comment explaining why we shouldn't need this patch after switching to Ubuntu 18.04 LTS.

**Pull request merged**
