### PR TITLE
qt 5.10.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 could I convince you to take a look at the #fail ?

**Comment by scpeters** [comment]
I filed an issue upstream; hopefully that wasn't premature:

* https://bugreports.qt.io/browse/QTBUG-65075

**Comment by ilovezfs** [comment]
@scpeters thank you :heart:

**Comment by ilovezfs** [comment]
@jakepetroules any idea what went wrong here?

**Comment by DomT4** [comment]
```
qwebview_darwin.mm:261:24: error: 'loadFileURL:allowingReadAccessToURL:' is only available on macOS 10.11 or newer [-Werror,-Wunguarded-availability]
            [wkWebView loadFileURL:url.toNSURL()
                       ^~~~~~~~~~~~~~~~~~~~~~~~~
```
Well, that's a weird one. I'll take a look locally but I'm not seeing any massive differences on this chunk of code _in isolation_ compared to the current version we ship or anything.

**Comment by ilovezfs** [comment]
It's very weird since it's not a problem in the 10.11 build. So maybe some kind of #ifdef macros that only apply to 10.12 & 10.13

**Comment by jakepetroules** [comment]
> @jakepetroules any idea what went wrong here?

Yes. It's a regression from 5.9.1. It affects both 5.9.2+ and 5.10.x. I've just posted a fix which applies cleanly to both 5.9 and 5.10 branches; the latter will get it once the downmerge happens. Cherry-pick here: https://codereview.qt-project.org/#/c/213993/

**Comment by ilovezfs** [comment]
@jakepetroules awesome. Out of interest, how did it escape the notice of your CI? Maybe you're building with Xcode 8 currently?

**Comment by jakepetroules** [comment]
Yes, we haven't yet updated it to Xcode 9, so that's why it slipped past.

**Comment by DomT4** [comment]
When you test Qt builds locally. My poor CPU 🤣:

screen shot 2017-12-08 at 22 17 39

**Comment by ilovezfs** [comment]
That's how your CPU builds :muscle:!

**Comment by RandomDSdevel** [comment]
You have my sympathies, @DomT4!  I suppose it could be _worse_, though…  (_Glares at his old clunker of a machine._)

**Comment by ilovezfs** [comment]
- [ ] audacious https://jenkins.brew.sh/job/Homebrew%20Testing/361/
- [ ] cockatrice https://jenkins.brew.sh/job/Homebrew%20Testing/362/
- [ ] codequery https://jenkins.brew.sh/job/Homebrew%20Testing/363/
- [ ] color-code https://jenkins.brew.sh/job/Homebrew%20Testing/364/
- [ ] djview4 https://jenkins.brew.sh/job/Homebrew%20Testing/365/
- [ ] dspdfviewer https://jenkins.brew.sh/job/Homebrew%20Testing/366/
- [ ] gammaray https://jenkins.brew.sh/job/Homebrew%20Testing/367/
- [ ] gearboy https://jenkins.brew.sh/job/Homebrew%20Testing/368/
- [ ] gearsystem https://jenkins.brew.sh/job/Homebrew%20Testing/369/
- [ ] liblastfm https://jenkins.brew.sh/job/Homebrew%20Testing/370/
- [ ] mgba https://jenkins.brew.sh/job/Homebrew%20Testing/371/
- [ ] pc6001vx https://jenkins.brew.sh/job/Homebrew%20Testing/372/
- [ ] pushpin https://jenkins.brew.sh/job/Homebrew%20Testing/373/
- [ ] pyqt https://jenkins.brew.sh/job/Homebrew%20Testing/374/
- [ ] qbs https://jenkins.brew.sh/job/Homebrew%20Testing/375/
- [ ] qca https://jenkins.brew.sh/job/Homebrew%20Testing/376/
- [ ] qcachegrind https://jenkins.brew.sh/job/Homebrew%20Testing/377/
- [ ] qcli https://jenkins.brew.sh/job/Homebrew%20Testing/378/
- [ ] qjackctl https://jenkins.brew.sh/job/Homebrew%20Testing/379/
- [ ] qjson https://jenkins.brew.sh/job/Homebrew%20Testing/380/
- [ ] qmmp https://jenkins.brew.sh/job/Homebrew%20Testing/381/
- [ ] qscintilla2 https://jenkins.brew.sh/job/Homebrew%20Testing/382/
- [ ] qtads https://jenkins.brew.sh/job/Homebrew%20Testing/383/
- [ ] quazip https://jenkins.brew.sh/job/Homebrew%20Testing/384/
- [ ] qwt https://jenkins.brew.sh/job/Homebrew%20Testing/385/
- [ ] qwtpolar https://jenkins.brew.sh/job/Homebrew%20Testing/386/
- [ ] qxmpp https://jenkins.brew.sh/job/Homebrew%20Testing/387/
- [ ] tarsnap-gui https://jenkins.brew.sh/job/Homebrew%20Testing/388/
- [ ] treefrog https://jenkins.brew.sh/job/Homebrew%20Testing/389/
- [ ] zurl https://jenkins.brew.sh/job/Homebrew%20Testing/390/

**Comment by DomT4** [comment]
> (Glares at his old clunker of a machine.)

Heh, been there. My prior MacBook to this one was significantly less powerful & compiling things from source felt like I was subjecting the machine to some kind of physical torment 😅.

Thanks for handling this update @ilovezfs ❤️.

**Pull request closed without merging**
