### PR TITLE
godep 79

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by woodruffw** [comment]
:thinking: 

```
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:	Current Directory: /private/tmp/godep-test-20170202-30124-k3jswo
godep: [WARNING]:	$GOPATH: /private/tmp/godep-test-20170202-30124-k3jswo
godep: Dep (go.googlesource.com/tools) restored, but was unable to load it with error:
```

**Comment by ilovezfs** [comment]
It's a bug due to https://github.com/tools/godep/commit/f15f6db5da33a4ac48be83e20b9dd838e14f117b

**Comment by ilovezfs** [comment]
Reported here: https://github.com/tools/godep/issues/535

**Comment by ilovezfs** [comment]
This should not be merged with the revision bumps. However, the changes in 79 have the potential to break previously working Godeps files so let's make sure that doesn't affect anything in brew first, and then this can be rebuilt without the revision bumps.

**Pull request closed without merging**
