### PR TITLE
hadolint 1.17.3

### PR DESCRIPTION
**Pull request by shigemk2**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
06:51:57 [__8] rejecting: ShellCheck:setup.base-4.12.0.0,
06:51:57 ShellCheck:setup.base-4.11.1.0, ShellCheck:setup.base-4.11.0.0,
06:51:57 ShellCheck:setup.base-4.10.1.0, ShellCheck:setup.base-4.10.0.0,
06:51:57 ShellCheck:setup.base-4.9.1.0, ShellCheck:setup.base-4.9.0.0,
06:51:57 ShellCheck:setup.base-4.8.2.0, ShellCheck:setup.base-4.8.1.0,
06:51:57 ShellCheck:setup.base-4.8.0.0, ShellCheck:setup.base-4.7.0.2,
06:51:57 ShellCheck:setup.base-4.7.0.1, ShellCheck:setup.base-4.7.0.0,
06:51:57 ShellCheck:setup.base-4.6.0.1, ShellCheck:setup.base-4.6.0.0,
06:51:57 ShellCheck:setup.base-4.5.1.0, ShellCheck:setup.base-4.5.0.0,
06:51:57 ShellCheck:setup.base-4.4.1.0, ShellCheck:setup.base-4.4.0.0,
06:51:57 ShellCheck:setup.base-4.3.1.0, ShellCheck:setup.base-4.3.0.0,
06:51:57 ShellCheck:setup.base-4.2.0.2, ShellCheck:setup.base-4.2.0.1,
06:51:57 ShellCheck:setup.base-4.2.0.0, ShellCheck:setup.base-4.1.0.0,
06:51:57 ShellCheck:setup.base-4.0.0.0, ShellCheck:setup.base-3.0.3.2,
06:51:57 ShellCheck:setup.base-3.0.3.1 (constraint from non-upgradeable package
06:51:57 requires installed instance)
06:51:57 [__8] fail (backjumping, conflict set: ShellCheck, base,
06:51:57 ShellCheck:setup.Cabal, ShellCheck:setup.base)
06:51:57 After searching the rest of the dependency tree exhaustively, these were the
06:51:57 goals I've had most trouble fulfilling: ShellCheck:setup.array,
06:51:57 ShellCheck:setup.deepseq, ShellCheck:setup.time, ShellCheck:setup.Cabal,
06:51:57 ShellCheck:setup.base, ShellCheck:setup.unix, ShellCheck, hadolint, base
06:51:57 Try running with --minimize-conflict-set to improve the error message.
06:51:57 Note: when using a sandbox, all packages are required to have consistent
06:51:57 dependencies. Try reinstalling/unregistering the offending packages or
06:51:57 recreating the sandbox.

**Comment by chenrui333** [comment]
looks like the issue stays the same?

**Comment by shigemk2** [comment]
I am still suffering from the same error.

**Comment by Bo98** [comment]
Haskell errors are a bit cryptic.

Looks like what's happening is that hadolint does not support cabal-install 3.0 that Homebrew ships.

**Comment by chenrui333** [comment]
Let's give another try.

**Comment by chenrui333** [comment]
same error as above:

18:42:35 [__8] fail (backjumping, conflict set: ShellCheck, base,
18:42:35 ShellCheck:setup.Cabal, ShellCheck:setup.base)
18:42:35 After searching the rest of the dependency tree exhaustively, these were the
18:42:35 goals I've had most trouble fulfilling: ShellCheck:setup.array,
18:42:35 ShellCheck:setup.deepseq, ShellCheck:setup.time, ShellCheck:setup.Cabal,
18:42:35 ShellCheck:setup.base, ShellCheck:setup.unix, ShellCheck, hadolint, base
18:42:35 Try running with --minimize-conflict-set to improve the error message.
18:42:35 Note: when using a sandbox, all packages are required to have consistent
18:42:35 dependencies. Try reinstalling/unregistering the offending packages or
18:42:35 recreating the sandbox.

**Comment by chenrui333** [comment]
Closing in favor of #48554

**Pull request closed without merging**
