### PR TITLE
ruby 2.7.0

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Test failure:

```
==> /usr/local/lib/ruby/gems/2.7.0/bin/bundle install --binstubs=/private/tmp/ruby-test-20191228-49116-nd4uwv/bin
/usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
	from /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
	from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:23:in `<main>'
```

and many others…

**Comment by bayandin** [comment]
I have no idea what's going on, so any suggestions are welcome

**Comment by fxcoudert** [comment]
poke @mistydemeo who is our Ruby expert :)

**Comment by chdiza** [comment]
Shouldn't the `readline` dependency be removed too?

The new features list in the announcement says that `irb` now uses a pure ruby implementation of multiline editing.

**Comment by tkosaka1976** [comment]
Does anyone help us?
We are waiting for the version up to 2.7.

**Comment by SMillerDev** [comment]
>  We are waiting for the version up to 2.7.
You don't have to wait for it, you can just help fix this pull request

**Comment by mistydemeo** [comment]
> poke @mistydemeo who is our Ruby expert :)

Looks like it's not finding the preinstalled Bundler. Looking in `/usr/local/Cellar/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.2`, we seem to have ended up with Bundler's `exe` binstubs but not the gem itself, which would explain something. As to *why*, I'm not sure...

**Comment by mistydemeo** [comment]
Actually, that's not true. The bundled Bundler's source code is a part of Ruby's tree in `/usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/bundler`, and only the binstubs are in the gem directory.

**Comment by indirect** [comment]
That's pretty odd. IIRC we didn't change how Bundler is included with Ruby as a default gem between 2.6 and 2.7. Is there an easy way to locally reproduce this so myself or maybe @deivid-rodriguez could take a look?

**Comment by mistydemeo** [comment]
Yes, if you use Homebrew then `brew install https://github.com/Homebrew/homebrew-core/raw/caac2af313ea378de6ef07dc30c680bdc77fef46/Formula/ruby.rb` (or `brew upgrade https://github.com/Homebrew/homebrew-core/raw/caac2af313ea378de6ef07dc30c680bdc77fef46/Formula/ruby.rb`) will install the Ruby 2.7.0 formula from this PR so you can give it a try. Thanks for giving it a look!

**Comment by indirect** [comment]
I uh... huh. It seems like it works as intended on my machine?

```
❯ export PATH="/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/2.7.0/bin:$PATH"
❯ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
❯ gem -v
3.1.2
❯ bundle -v
Bundler version 2.1.4
❯ cd src/indirect/homebrew-test
❯ bundle install
Using bundler 2.1.4
Using rack 2.2.1
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

The environments look totally normal/correct to me, too:

```
❯ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.2
  - RUBY VERSION: 2.7.0 (2019-12-25 patchlevel 0) [x86_64-darwin19]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.7.0
  - USER INSTALLATION DIRECTORY: /Users/andre/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /usr/local/opt/ruby/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/lib/ruby/gems/2.7.0/bin
  - SPEC CACHE DIRECTORY: /Users/andre/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/Cellar/ruby/2.7.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-19
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.7.0
     - /Users/andre/.gem/ruby/2.7.0
     - /usr/local/Cellar/ruby/2.7.0/lib/ruby/gems/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/opt/ruby/bin
     - /usr/local/lib/ruby/gems/2.7.0/bin
     - /Users/andre/.cargo/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/andre/.bin

❯ bundle env
## Environment
Bundler       2.1.4
  Platforms   ruby, x86_64-darwin-19
Ruby          2.7.0p0 (2019-12-25 revision 647ee6f091eafcce70ffb75ddf7e121e192ab217) [x86_64-darwin19]
  Full Path   /usr/local/opt/ruby/bin/ruby
  Config Dir  /usr/local/Cellar/ruby/2.7.0/etc
RubyGems      3.1.2
  Gem Home    /usr/local/lib/ruby/gems/2.7.0
  Gem Path    /Users/andre/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/Cellar/ruby/2.7.0/lib/ruby/gems/2.7.0
  User Home   /Users/andre
  User Path   /Users/andre/.gem/ruby/2.7.0
  Bin Dir     /usr/local/lib/ruby/gems/2.7.0/bin
Tools         
  Git         2.24.0
  RVM         not installed
  rbenv       not installed
  chruby      
Gem.ruby      /usr/local/opt/ruby/bin/ruby
bundle #!     /usr/local/Cellar/ruby/2.7.0/bin/ruby

## Bundler Build Metadata
Built At          2020-01-05
Git SHA           32a4159325
Released Version  true
```

Any suggestions for how I could go about getting access to a machine where this issue reproduces?

**Comment by indirect** [comment]
Oh no. It was completely my fault 🤦‍♂ My `.gemrc` has a user-install directory, and I had bundler installed in it! I can reproduce now that I have uninstalled that copy of Bundler. 😬

**Comment by indirect** [comment]
Okay, got it: the reason Bundler is gone is because the formula deletes it manually. Delete these lines to make it work:

https://github.com/Homebrew/homebrew-core/blob/caac2af313ea378de6ef07dc30c680bdc77fef46/Formula/ruby.rb#L104-L111

Turns out we did change something between Ruby 2.6 and Ruby 2.7: we started installing Bundler in the normal place you would expect the gem files to live. That means the Homebrew formula's "clever workaround" of deleting any installed Bundler versions... now also deletes the Bundler that ships with Ruby. If you don't do that, you should be fine. 😅

**Comment by deivid-rodriguez** [comment]
I'm later here, but thanks for investigating this @indirect :)

**Comment by bayandin** [comment]
Thanks for the help @indirect

> Okay, got it: the reason Bundler is gone is because the formula deletes it manually. Delete these lines to make it work:
> 
> https://github.com/Homebrew/homebrew-core/blob/caac2af313ea378de6ef07dc30c680bdc77fef46/Formula/ruby.rb#L104-L111

I've applied these changes, but it seems it still doesn't work:

```
==> /usr/local/lib/ruby/gems/2.7.0/bin/bundle install --binstubs=/private/tmp/ruby-test-20200210-83546-1yosc1v/bin
/usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
	from /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
	from /usr/local/lib/ruby/gems/2.7.0/bin/bundle:23:in `<main>'
Error: ruby: failed
```

**Comment by indirect** [comment]
What command are you running to get that output? For me, formula in this PR raised an error on `bundle -v`, and uninstalling then deleting those lines and reinstalling fixed it so that `bundle -v` (and other bundler commands) started to work.

**Comment by bayandin** [comment]
> What command are you running to get that output? For me, formula in this PR raised an error on `bundle -v`, and uninstalling then deleting those lines and reinstalling fixed it so that `bundle -v` (and other bundler commands) started to work.

I've updated the PR with suggested changes and on CI command `/usr/local/lib/ruby/gems/2.7.0/bin/bundle install --binstubs=/private/tmp/ruby-test-20200210-83546-1yosc1v/bin` fails. 
Locally (with suggested changes) `/usr/local/lib/ruby/gems/2.7.0/bin/bundle -v` fails with the same error

**Comment by indirect** [comment]
Are you seeing the same thing happen with IRB? I might have successfully reproduced the issue, but it now seems like _all_ default gems in Ruby 2.7 are broken by Homebrew, not just Bundler.

```
$ irb
Traceback (most recent call last):
	2: from /usr/local/opt/ruby/bin/irb:23:in `<main>'
	1: from /usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
/usr/local/Cellar/ruby/2.7.0/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem irb (>= 0.a) with executable irb (Gem::GemNotFoundException)
```

**Comment by indirect** [comment]
Ahhh, okay, that was the lead I needed to find the issue. In the formula, Homebrew installs a monkeypatch to overwrite `Gem::BasicSpecification.default_specifications_dir`. That has been deprecated and replaced by `Gem.default_specifications_dir`:

```
irb(main):001:0> Gem::BasicSpecification.default_specifications_dir
NOTE: Gem::BasicSpecification.default_specifications_dir is deprecated; use Gem.default_specifications_dir instead. It will be removed on or after 2020-02-01.
```

After updating the formula to use the new location, `irb` and `bundle` seem to be working for me again. Here's the formula I used that seems to work: https://gist.github.com/indirect/3cb3b06227935a801db8fcf85c715079

**Comment by mistydemeo** [comment]
Good catch, thank you! Here's a more minimal version of that which still upgrades our Rubygems install while ensuring everything works:

```patch
From d53b8bce85c8167d90cb4f4758c2c2817cc11f23 Mon Sep 17 00:00:00 2001
From: Misty De Meo <mistydemeo@gmail.com>
Date: Sat, 15 Feb 2020 11:04:53 -0800
Subject: [PATCH] ruby: fix operating_system for new API

Co-authored-by: Andre Arko <andre@arko.net>
---
 Formula/ruby.rb | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/Formula/ruby.rb b/Formula/ruby.rb
index 40db3c1cdb..c2420cdbc5 100644
--- a/Formula/ruby.rb
+++ b/Formula/ruby.rb
@@ -130,6 +130,7 @@ class Ruby < Formula
         alias :old_default_path :default_path
         alias :old_default_bindir :default_bindir
         alias :old_ruby :ruby
+        alias :old_default_specifications_dir :default_specifications_dir
       end
 
       def self.default_dir
@@ -186,10 +187,9 @@ class Ruby < Formula
       end
 
       # https://github.com/Homebrew/homebrew-core/issues/40872#issuecomment-542092547
-      class BasicSpecification
-        def self.default_specifications_dir
-          File.join(Gem.old_default_dir, "specifications", "default")
-        end
+      # https://github.com/Homebrew/homebrew-core/pull/48329#issuecomment-584418161
+      def self.default_specifications_dir
+        File.join(Gem.old_default_dir, "specifications", "default")
       end
     end
   EOS
-- 
2.25.0

```

**Comment by mistydemeo** [comment]
Shipped in #50294.

**Pull request closed without merging**
