### PR TITLE
sql2pb 1.0.2 (new formula)

### PR DESCRIPTION
**Pull request by Mikaelemmmm**
sql2pb
Generates a protobuf file from your mysql database

### CODE REVIEW

**Comment by Mikaelemmmm** [comment]
image
Do these conditions have to be met?

**Comment by SMillerDev** [comment]
Yes, that's why we audit for them

**Comment by SMillerDev** [comment]
Hi, this seems like a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by Mikaelemmmm** [comment]
> Hi, this seems like a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.
> 
> Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

Okay, I understand, I'll submit pr when the conditions are met later.
However, I have a question, I have to submit pr to another tool goctl, currently using the tap form, I haven't figured out the version number relationship yet, so I haven't submitted pr yet.
What I want to ask is, the latest version of our goctl is 1.3.5, if I submit this version to your repository, and then I release the new version 1.3.6, you will automatically synchronize the new version? What else do I need to do?

Translated with www.DeepL.com/Translator (free version)

**Comment by Mikaelemmmm** [comment]
> Hi, this seems like a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.
> 
> Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

Okay, I understand, I'll submit pr when the conditions are met later.
However, I have a question, I have to submit pr to another tool goctl, currently using the tap form, I haven't figured out the version number relationship yet, so I haven't submitted pr yet.
What I want to ask is, the latest version of our goctl is 1.3.5, if I submit this version to your repository, and then I release the new version 1.3.6, you will automatically synchronize the new version? What else do I need to do?

**Pull request closed without merging**
