### PR TITLE
sslyze 2.1.4

### PR DESCRIPTION
**Pull request by Gillingham**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
20:05:07 copying build/lib.macosx-10.14-x86_64-3.7/nassl/_nassl.cpython-37m-darwin.so -> nassl
20:05:07 Error: An exception occurred within a child process:
20:05:07   NameError: undefined local variable or method `nassl_path' for #<Formulary::FormulaNamespace098ec6c15fc5e5e9932692d8bd47a06e::Sslyze:0x00007feb4a120808>
20:05:07

**Comment by chenrui333** [comment]
@Gillingham Thanks for making efforts to get the PR build passed, can you squash the commits into one single commit (commit msg format as `sslyze  2.1.4`)?

**Comment by Gillingham** [comment]
No idea if I squashed that correctly with the merge that it prompted me to do immediately following.

**Comment by Bo98** [comment]
Thanks for this. Apologies for the wait. We're currently building Python 3.8 (see #45337) and we'll revisit this pull request once that's finished.

**Comment by iMichka** [comment]
Superseded by #47993. We needed to make the update to Python 3 quickly and could not wait, as the `pyhton@2` formula will be removed at the end of the year. Sorry for this PR but we had to act quick.

**Pull request closed without merging**
