### PR TITLE
libcerf 2.1

### PR DESCRIPTION
**Pull request by yurikoles**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by yurikoles** [comment]
Big Sur and Catalina are timed out, while others are green. Could you please set `CI-long-timeout`?

**Comment by yurikoles** [comment]
All tests are green now, please review.

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
@yurikoles, thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by cho-m** [comment]
Need a rebase due to #99291
```
Error: Bottles are for litani 1.23.0_1 but formula is version 1.24.0_1!
```

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
