### PR TITLE
mesa 19.2.3

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please.

**Comment by SMillerDev** [comment]
Thanks @yurikoles

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Error on Catalina and Mojave (Xcode 11):

```
../src/util/u_queue.c:176:7: error: implicit declaration of function 'timespec_get' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      timespec_get(&ts, TIME_UTC);
      ^
```

**Comment by yurikoles** [comment]
It seems that we need to backport [9d3fc737](https://gitlab.freedesktop.org/mesa/mesa/commit/9d3fc737afcb98e3882b4d54c9d093980cfb4874
)

**Comment by yurikoles** [comment]
Upstream issue: https://gitlab.freedesktop.org/mesa/mesa/issues/1020

**Comment by chenrui333** [comment]
Thanks @yurikoles !!

**Comment by yurikoles** [comment]
@chenrui333 this commit is already in 19.2.0 and after it there was some refactor around it for BSD systems and others with same issue. I'm sorry for confusing you. I had raised discussion in upstream ticket, see discussion in link above.

**Comment by yurikoles** [comment]
We can introduce a hack in this snippet:
```
foreach f : ['strtof', 'mkostemp', 'posix_memalign', 'timespec_get', 'memfd_create', 'random_r']
  if cc.has_function(f)
    pre_args += '-DHAVE_@0@'.format(f.to_upper())
  endif
endforeach
```
It seems that meson reports that compiler has this feature, just in another file, e.g. this check is incorrect.

**Comment by yurikoles** [comment]
@fxcoudert could we end up providing High Sierra bottle for Mojave and Catalina?

**Comment by fxcoudert** [comment]
> could we end up providing High Sierra bottle for Mojave and Catalina?

No

**Comment by chenrui333** [comment]
Just FYI, there is a new release of v19.2.3

**Comment by yurikoles** [comment]
removing mesa

**Pull request closed without merging**
