### PR TITLE
q 1.7.1

### PR DESCRIPTION
**Pull request by harelba**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by harelba** [comment]
Hi - I've tried first with `brew bump-formula-pr`, and it ran for a while, but then got stuck for ~30 minutes. Running the command again issued an error that the new 1.7.1 already exists, but looking at the file on master didn't reflect it. 

This is a manual PR i've created which perform the same change to 1.7.1.

**Comment by ilovezfs** [comment]
what's the output of `brew config`

**Comment by harelba** [comment]
```
HOMEBREW_VERSION: 1.3.8-10-g1ff628e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1ff628e20f828a0b1e7093b5f3235d77bd30e488
Last commit: 25 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e241a49d759d2cbe0b304c4b6bd73fb04d165877
Core tap last commit: 33 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.6 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /Users/harelbenattia/.pyenv/shims/python => /Users/harelbenattia/.pyenv/versions/2.7.13/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_151
macOS: 10.13.1-x86_64
Xcode: 9.1
CLT: 9.0.1.0.1.1506734476
X11: N/A
```

**Comment by ilovezfs** [comment]
thanks. and what's the output of `hub --version` and

```
cd $(brew --repo homebrew/core)
hub fork
```

**Comment by harelba** [comment]
Interesting. `hub fork` requests a github username. This is probably what got everything stuck, waiting for my input. The actual "github.com username:" string was not displayed on the screen in the original run, though. 

```
$ hub --version
git version 2.13.6 (Apple Git-96)
hub version 2.2.9

19:17 $ git status
On branch q-1.7.1
nothing to commit, working tree clean

$ hub fork
github.com username: ^C
```

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L339-L342

Can you try again? I'm wondering if your brew was just outdated.

```
brew bump-formula-pr --url="https://github.com/vim/vim/archive/v8.0.1300.tar.gz" vim
```

**Comment by ilovezfs** [comment]
1333 not 1300, sorry

**Comment by ilovezfs** [comment]
(of course if you already configured hub now it's too late to test …)

**Comment by harelba** [comment]
haven't configured hub yet, so i did the test you suggested - 

Getting an `Error: You need to configure hub`

**Comment by ilovezfs** [comment]
OK, good. So I think this is fixed in master and your brew was outdated.

**Comment by harelba** [comment]
great. thanks!

Is there a need for me to recreate the PR using brew, or is this PR good enough?

**Comment by ilovezfs** [comment]
This is fine as is. However, https://github.com/harelba/q/releases/latest needs to be updated.

**Comment by harelba** [comment]
awesome, thanks for pointing it out - i'll issue a release there. A quick question - Is it needed even though the formula uses a url/sha256 combination, and not a tag?

**Comment by ilovezfs** [comment]
Yep. If you have any explicit releases, then they need to be done consistently so that the latest tag == latest release. If the explicit releases are not going to be done consistently, then they should all be removed so that https://github.com/harelba/q/releases/latest just redirects to the list of tags.

**Comment by ilovezfs** [comment]
i.e. you should either make 1.7.1 an explicit release or you should delete both 1.5.0 and 1.6.3 (deleting the releases does not delete the underlying tags).

**Comment by harelba** [comment]
I've added the 1.7.1 release.

thanks.

**Comment by ilovezfs** [comment]
Thanks for the upgrade @harelba! :rocket:

**Comment by ilovezfs** [comment]
@harelba by the way you may want to automate the creation of the explicit releases with the GitHub API https://developer.github.com/v3/repos/releases/#create-a-release

**Pull request merged**
