### PR TITLE
nodeenv 1.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
use new virtualenv feature

### CODE REVIEW

**Comment by zmwangx** [comment]
Regarding the test: why prepend to `PATH` and hoping there's a `node` in the prepended directory (may not be true, in which case the formula is broken but there might be another `node` on `PATH` masking the issue), when we can use the absolute path to said `node`?

**Comment by ilovezfs** [comment]
because this is fine as-is?

**Comment by ilovezfs** [comment]
@DomT4 you wrote the test in 93d74a07 so feel free to answer

**Comment by zmwangx** [comment]
It may be fine on the CI, but for a developer testing this on a dev machine it'll most likely catch nothing even when the formula breaks. What about

```rb
node_in_env = testpath/"env-0.10.40-prebuilt/bin/node"
(testpath/"test.js").write "console.log('hello');"
assert_equal "hello", shell_output("#{node_in_env} test.js").chomp
assert_equal "v0.10.40", shell_output("#{node_in_env} -v").chomp
```

**Comment by zmwangx** [comment]
> it'll most likely catch nothing even when the formula breaks

Oh, actually no, the chance of said developer happen to be running 0.10.40 is quite slim... So whatever.

**Comment by ilovezfs** [comment]
As I've mentioned before, I really only care about what happens on test-bot with respect to test blocks.

**Comment by zmwangx** [comment]
Sure.

**Comment by DomT4** [comment]
Prepending is more in line with how the software actually behaves at run, which is what I was trying to emulate. As you point out, it's not a perfect solution.

I'd be amazed if anyone is running `0.10.40` now though, it's not even the latest 0.10.x series release, let alone any of the newer branches.

**Comment by zmwangx** [comment]
By the way, I do care about running locally because having to throw random commits at CI trying to find out why the test works locally but fails on the CI is not fun.

**Comment by zmwangx** [comment]
> I'd be amazed if anyone is running 0.10.40 now though, it's not even the latest 0.10.x series release, let alone any of the newer branches.

Yeah, see https://github.com/Homebrew/homebrew-core/pull/4672#issuecomment-246080794 where I realized and stepped down.

**Comment by ilovezfs** [comment]
>By the way, I do care about running locally because having to throw random commits at CI trying to find out why the test works locally but fails on the CI is not fun.

This is why you should learn to run test-bot locally.

**Comment by ilovezfs** [comment]
In any case, I'm happy to modify this test to be however @DomT4 would like it to be current since it's "his" test.

**Comment by zmwangx** [comment]
The ops repo doesn't talk about how to set up though... So no, I'll continue to throw commits at bot.brew.sh 😉

**Comment by DomT4** [comment]
I don't mind either way here.

If there's a desire to change it, the theoretical reasons for changing it are valid enough, but in reality if anyone runs into a real world issue with this test by now I'll at least consider eating a hat.

**Comment by ilovezfs** [comment]
@zmwangx that's because there's nothing to explain. You run `brew test-bot foo` starting from an empty brew installation in a new macOS user without any local profile modifications.

**Comment by zmwangx** [comment]
Let's just keep as is.

**Comment by zmwangx** [comment]
> You run brew test-bot foo starting from an empty brew installation in a new macOS user without any local profile modifications.

Oh forgive me, I was thinking about setting up full fledged continuous integration...

**Comment by ilovezfs** [comment]
>Oh forgive me, I was thinking about setting up full fledged continuous integration...

Ah yeah, that would require significantly more explanation and documentation, or at least an extensive poking around at the settings on Jenkins.

**Comment by ilovezfs** [comment]
>I'll at least consider eating a hat.

@DomT4 I hear they pair well with crow meat and humble pie.

**Comment by DomT4** [comment]
@ilovezfs We need to find you some better restaurants I fear 😄.

**Pull request closed without merging**
