### PR TITLE
openvino 2024.4.0

### PR DESCRIPTION
**Pull request by artanokhov**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by artanokhov** [comment]
Please add tags required for long-build, as we have in previous PR
https://github.com/Homebrew/homebrew-core/pull/179077/

**Review by chenrui333 — APPROVED** [review]
Thanks!

**Comment by SMillerDev** [comment]
This looks like a problem in @Homebrew/brew 
```
  Error: An exception occurred within a child process:
    RuntimeError: `sig` not present for method `generic_std_cmake_args` on #<Formula opencv (stable) /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/o/opencv.rb> but you're trying to run it anyways. This should only be executed if you used `alias_method` to grab a handle to a method after `sig`ing it, but that clearly isn't what you are doing. Maybe look to see if an exception was thrown in your `sig` lambda or somehow else your `sig` wasn't actually applied to the method.
```

**Comment by carlocab** [comment]
Think this is Homebrew/brew#18305. CC @dduugg

**Comment by MikeMcQuaid** [comment]
Should be fixed by https://github.com/Homebrew/brew/pull/18364

**Comment by artanokhov** [comment]
Currently observing issue with downloading OpenCV manifest
```
==> Downloading https://ghcr.io/v2/homebrew/core/opencv/manifests/4.10.0_7
curl: (56) The requested URL returned error: 404
```

**Pull request merged**
