### PR TITLE
kubeless 0.5.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> brew test kubeless --verbose
==> FAILED
Testing kubeless
/usr/bin/sandbox-exec -f /tmp/homebrew20180329-30483-v80spz.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubeless.rb --verbose
==> /usr/local/Cellar/kubeless/0.5.0/bin/kubeless function deploy --from-file test.py --runtime python2.7 --handler test.foo test
time="2018-03-29T17:52:07+01:00" level=fatal msg="Error while fetching config location: couldn't get version/kind; json parse error: invalid character 'O' looking for beginning of value"
Error: kubeless: failed
Failed executing: /usr/local/Cellar/kubeless/0.5.0/bin/kubeless function deploy --from-file test.py --runtime python2.7 --handler test.foo test
/usr/local/Homebrew/Library/Homebrew/formula.rb:1790:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1728:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1728:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubeless.rb:100:in `block in <class:Kubeless>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1634:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:558:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1633:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:835:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1632:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1626:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by andresmgot** [comment]
thanks for reporting @ilovezfs I will send a PR for fixing that

**Comment by ilovezfs** [comment]
Thanks @andresmgot! I will close this out then.

**Comment by ilovezfs** [comment]
superseded by https://github.com/Homebrew/homebrew-core/pull/26056

**Pull request closed without merging**
