### PR TITLE
conan: switch back to pypi

### PR DESCRIPTION
**Pull request by chenrui333**
Switch back to pypi (relates to #66182)

Redo #65836

### CODE REVIEW

**Review by samford — CHANGES_REQUESTED** [review]
Is there a specific reason why the stable source for `conan` was changed from PyPI to GitHub in #66182?

If not, then it seems like we should go back to using an archive from PyPI, in which case the `livecheck` block will return to checking the `stable` URL using the `Pypi` strategy. The change in the `stable` URL from PyPI to GitHub is why this stopped working as expected.

If `stable` continues to be an archive from GitHub, then this should use `strategy :github_latest` (a regex isn't needed).

**Comment by chenrui333** [comment]
Sounds about right, just updated. :)

**Comment by samford** [comment]
I'm still curious about the `stable` switch from PyPI to GitHub. It was specifically modified to use PyPI in #65836.

cc: @dtrodrigues

**Comment by chenrui333** [comment]
I see what you saying, yeah. 

I think it is my issue of using wrong source, switching back to pypi.

**Comment by samford** [comment]
I modified this to update the `resource` blocks while we're at it.

**Comment by dtrodrigues** [comment]
In #65836 I was switching to the PyPI url to allow for the automated resource bumps and also had the livecheck block switch to use the stable PyPI url.

**Review by samford — APPROVED** [review]
I built this from source locally and everything tested fine 👍

**Pull request closed without merging**
