### PR TITLE
wireshark 3.6.7

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter) (Required
    is at least version "3.4")
```

**Review by SMillerDev — APPROVED** [review]

**Comment by Porkepix** [comment]
Was it not possible to use `3.10` directly, as the normal formula still points out to `3.9`, or is it not recommended for builds dependencies?

**Comment by carlocab** [comment]
Installing a formula is a pretty expensive operation (with expensive knock-on effects for CI) that would be good to avoid if possible.

The build doesn't seem too picky about the Python interpreter, and has no effects at runtime, so there's really no good reason to incur the expense of using a Homebrew-built Python when the one that's shipped by Apple will do.

**Comment by Porkepix** [comment]
Owwww, my bad, didn't even noticed it was a `uses_from_macos` and not a `depends_on`…

**Pull request closed without merging**
