### PR TITLE
frotz: fix sha256 checksum

### PR DESCRIPTION
**Pull request by jcgraybill**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by jcgraybill** [comment]
From the CI test failure:
```
Full audit frotz --online --git --skip-style output
  frotz:
    * stable sha256 changed without the url/version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
```

Upstream issue created: https://gitlab.com/DavidGriffith/frotz/-/issues/272

**Comment by chenrui333** [comment]
Thanks @jcgraybill!

**Comment by jcgraybill** [comment]
See discussion with maintainer @DavidGriffith at https://github.com/Homebrew/homebrew-core/issues/127318

**Comment by jcgraybill** [comment]
Following up - @cho-m it looks like the new checksum is stable. Are there any other questions I can answer before this is ready to be merged? TY!

```
% curl https://gitlab.com/DavidGriffith/frotz/-/archive/2.54/frotz-2.54.tar.bz2 | shasum -a 256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  345k    0  345k    0     0   408k      0 --:--:-- --:--:-- --:--:--  409k
756d7e11370c9c8e61573e350e2a5071e77fd2781be74c107bd432f817f3abc7  -
```

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@jcgraybill thanks for the efforts on this.

**Pull request merged**
