### PR TITLE
terraform 0.13.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by dtrodrigues — APPROVED** [review]

**Comment by kusold** [comment]
This should have included a `terraform@0.12` formula. `0.13` has some changes that many companies aren't ready to deal with in the short term.

**Comment by kusold** [comment]
This should have included a `terraform@0.12` formula. `0.13` has some changes that many companies aren't ready to deal with in the short term.

**Comment by chenrui333** [comment]
> This should have included a `terraform@0.12` formula. `0.13` has some changes that many companies aren't ready to deal with in the short term.

Good call. I will do that.

**Comment by chenrui333** [comment]
Filed a PR, #59443

**Comment by Porkepix** [comment]
This is strange, the PR appear as closed while commit went to master, and `0.13` is now in the repository, how is that so?
I think both should have arrived in the same time, as pointed out by @kusold. User will now have to resort to manually-downloaded binary until the other PR is merged.

**Comment by kusold** [comment]
@Porkepix homebrew utilizes some automation for merging PRs: https://github.com/Homebrew/homebrew-core/actions/runs/202961161 (See @BrewTestBot's activity on this PR )

We've been directing users to use `tfenv` to download the correct terraform version. TBH we probably should have been using this all along to keep everyone in sync.

**Comment by chenrui333** [comment]
Forgot to cross post in here, `brew install terraform@0.12` should be available now. 🎉

**Comment by kusold** [comment]
Thank you @chenrui333. We appreciate all of your work.

**Pull request closed without merging**
