### PR TITLE
ruby: update HEAD

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

```
==> brew audit ruby --online
==> FAILED
Error: 1 problem in 1 formula detected
ruby:
  * HEAD: The URL https://svn.ruby-lang.org/repos/ruby/trunk/ is not a valid svn URL
```

The CI was complaining.

### CODE REVIEW

**Comment by DomT4** [comment]
I think it's potentially worth seeing if we can fix the audit rather than thwacking these individually; this kind of thing pops up on CI fairly frequently, and I'm assuming not all of those will have convenient GitHub mirrors.

**Comment by lembacon** [comment]
But this case might be slightly different, the development of Ruby has been moved to GitHub for a while, they probably shut down the svn repository recently.

**Comment by DomT4** [comment]
The last SVN change was 4 hours ago, so it still seems plenty active.

No objection to moving this one because they officially list it as an alternative `HEAD` location on the website, but think more broadly we need to deal with the source of the problem here, which is `audit` red-flagging "bad links" incorrectly.

**Comment by lembacon** [comment]
That's fair enough. 👍

**Comment by lembacon** [comment]
```
15:41:39 ==> brew test ruby --verbose
15:41:54 ==> FAILED
15:41:54 Testing ruby
15:41:54 /usr/bin/sandbox-exec -f /private/tmp/homebrew20180902-79786-pzq1sk.sb /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib:/Library/Ruby/Gems/2.3.0/gems/power_assert-0.2.6/lib:/Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib:/Library/Ruby/Site/2.3.0:/Library/Ruby/Site/2.3.0/x86_64-darwin17:/Library/Ruby/Site/2.3.0/universal-darwin17:/Library/Ruby/Site:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17:/usr/local/Homebrew/Library/Homebrew/cask/lib:/usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ruby.rb --verbose
15:41:54 ==> /usr/local/Cellar/ruby/2.5.1/bin/ruby -e 'puts :hello'
15:41:54 ==> /usr/local/Cellar/ruby/2.5.1/bin/gem install json
15:41:54 Building native extensions. This could take a while...
15:41:54 Successfully installed json-2.1.0
15:41:54 Parsing documentation for json-2.1.0
15:41:54 Installing ri documentation for json-2.1.0
15:41:54 Done installing documentation for json after 1 seconds
15:41:54 1 gem installed
15:41:54 ==> /usr/local/bin/bundle install --binstubs=/private/tmp/ruby-test-20180902-79787-wzbv8j/bin
15:41:54 Fetching gem metadata from https://rubygems.org/.
15:41:54 Resolving dependencies...
15:41:54 Using bundler 1.16.1
15:41:54 Fetching gemoji 3.0.0
15:41:54 Bundler::GemspecError: Could not read gem at
15:41:54 /private/tmp/ruby-test-20180902-79787-wzbv8j/cache/gemoji-3.0.0.gem. It may be
15:41:54 corrupted.
15:41:54 An error occurred while installing gemoji (3.0.0), and Bundler cannot continue.
15:41:54 Make sure that `gem install gemoji -v '3.0.0'` succeeds before bundling.
15:41:54 
15:41:54 In Gemfile:
15:41:54   gemoji
15:41:54 Error: ruby: failed
15:41:54 Failed executing: /usr/local/bin/bundle install --binstubs=/private/tmp/ruby-test-20180902-79787-wzbv8j/bin
15:41:54 /usr/local/Homebrew/Library/Homebrew/formula.rb:1879:in `block in system'
15:41:54 /usr/local/Homebrew/Library/Homebrew/formula.rb:1817:in `open'
15:41:54 /usr/local/Homebrew/Library/Homebrew/formula.rb:1817:in `system'
15:41:54 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ruby.rb:202:in `block in <class:Ruby>'
15:41:54 /usr/local/Homebrew/Library/Homebrew/formula.rb:1694:in `block (3 levels) in run_test'
15:41:54 /usr/local/Homebrew/Library/Homebrew/utils.rb:520:in `with_env'
15:41:54 /usr/local/Homebrew/Library/Homebrew/formula.rb:1693:in `block (2 levels) in run_test'
15:41:54 /usr/local/Homebrew/Library/Homebrew/formula.rb:861:in `with_logging'
15:41:54 /usr/local/Homebrew/Library/Homebrew/formula.rb:1692:in `block in run_test'
15:41:54 /usr/local/Homebrew/Library/Homebrew/formula.rb:1929:in `block in mktemp'
15:41:54 /usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
15:41:54 /usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
15:41:54 /usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
15:41:54 /usr/local/Homebrew/Library/Homebrew/formula.rb:1928:in `mktemp'
15:41:54 /usr/local/Homebrew/Library/Homebrew/formula.rb:1686:in `run_test'
15:41:54 /usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
15:41:54 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
15:41:54 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
15:41:54 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
15:41:54 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
15:41:54 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
15:41:54 /usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

This now happens on El Capitan, Sierra, High Sierra as well as Mojave, so this is apparently not a Mojave-specific issue. 🙃 cc @fxcoudert

**Comment by fxcoudert** [comment]
Given the test failure is not Mojave-specific, I've now merged a Mojave bottle https://github.com/Homebrew/homebrew-core/commit/79a10be00f5c9b37f8cd210263400a3cacd81a7a

**Comment by lembacon** [comment]
> No objection to moving this one because they officially list it as an alternative HEAD location on the website, but think more broadly we need to deal with the source of the problem here, which is audit red-flagging "bad links" incorrectly.

So I'm also merging this one for now. 😉

**Pull request closed without merging**
