### PR TITLE
knot-resolver: fix cannot be started by `brew services restart knot-r…

### PR DESCRIPTION
**Pull request by camachat**
knot-resolver: fix cannot be started by `brew services restart knot-resolver`.

### CODE REVIEW

**Comment by vcunat** [comment]
Sounds OK from _theoretical_ point of view.  Note that it will newly create `/var/kresd/tty/$PID` control socket.

**Comment by crystalneth** [comment]
Running knot as a service is I would think the primary use case. Is there an alternative without that side effect?

**Comment by camachat** [comment]
> Running knot as a service is I would think the primary use case. Is there an alternative without that side effect?
Looks OK for me, only root can access thru unix socket file.
`
user ~> ls -l /usr/local/var/kresd/tty/93300 
srwxr-xr-x  1 root  admin  0 Jan 14 19:00 /usr/local/var/kresd/tty/93300
user ~> nc -U /usr/local/var/kresd/tty/93300
user ~> sudo nc -U /usr/local/var/kresd/tty/93300
> cache.count()
37108

> 
`

**Comment by vcunat** [comment]
We (upstream) consider it an intentional side-effect.  If you don't want stdin, you get this means of controlling kresd without restarting it (one that's even a bit more flexible than stdin).

**Comment by fxcoudert** [comment]
Thanks @camachat for the issue report and the pull request!

**Pull request merged**
