### PR TITLE
xonsh 0.12.6

### PR DESCRIPTION
**Pull request by PythonCoderAS**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Still seems to be broken with same error as #103952:
```
Errno::ENOENT: No such file or directory - /opt/homebrew/Cellar/xonsh/0.12.6/bin/xonsh
```

**Comment by PythonCoderAS** [comment]
I am utterly confused by this. If I directly download the tar.gz and then install that directly via pip it works perfectly fine.

**Comment by PythonCoderAS** [comment]
AHA I HAVE THE PROBLEM! Setuptools is outdated and _needs_ to be upgraded in order to recognize `pyproject.toml` as a valid source of metadata. I have no idea where the venv gets it's setuptools from (any venvs I manually create on 3.9 are updated, any venvs I manually create on 3.10 are not).

**Comment by cho-m** [comment]
`setuptools` is part of `python*` formulae. Next update is #103101

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @PythonCoderAS!

**Pull request closed without merging**
