### PR TITLE
go 1.15.2

### PR DESCRIPTION
**Pull request by qinxin0720**

### CODE REVIEW

**Comment by mojotx** [comment]
Looks like the regression testing is taking an extraordinarily long time. 

There were some issues with the [pull request for Go 1.15.1](Homebrew/homebrew-core/pull/60495)...possibly related?

**Comment by SeekingMeaning** [comment]
> Looks like the regression testing is taking an extraordinarily long time.

Yes, that is expected. We try to test dependents of a formulae when updating (`go` has a lot!)

> There were some issues with the [pull request for Go 1.15.1](https://github.com/Homebrew/homebrew-core/pull/60495)...possibly related?

Ideally, we should fix all failures before merging, but if a few are known issues with previous updates, then we can skip those

**Comment by chenrui333** [comment]
Besides minukube (which is raised in [here](https://github.com/Homebrew/homebrew-core/issues/60746)), all are the known issues. Proceeding with a merge.

**Comment by chenrui333** [comment]
minikube fix PR #61071

**Pull request closed without merging**
