### PR TITLE
yubico-piv-tool 1.4.2

### PR DESCRIPTION
**Pull request by realdimas**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by nijikon** [comment]
@BrewTestBot test this please

**Comment by nijikon** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
Third time's a charm! Merged as 0bc85959d4157698cb4e9ca97d1dd151e3990e4a, thanks!

**Pull request closed without merging**
