### PR TITLE
gradle@4 4.10.3 (New Formula)  

### PR DESCRIPTION
**Pull request by RandomDSdevel**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Needed for #32864, as OpenJFX doesn't build with Gradle v5.x yet.

### CODE REVIEW

**Comment by equal-l2** [comment]
Hello, how's it going?
This PR blocks #32864, right?

**Comment by RandomDSdevel** [comment]
@equal-l2:  

> Hello, how's it going?
>
> ⋮

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;See below.  

> ⋮
>
> This PR blocks #32864, right?

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If I don't have to drop back to Gradle v4.8.x to resolve the build issues I asked @SMillerDev for advice fixing in [my reply in that PR's discussion thread](https://github.com/Homebrew/homebrew-core/pull/32864#issuecomment-447330513), then, yes, that's correct.

**Comment by equal-l2** [comment]
@RandomDSdevel 
I should have noticed SMillerDev didn't reply yet.
Sorry for rushing!

**Comment by RandomDSdevel** [comment]
@equal-l2:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;That's all right.  I expect things will pick up repository-wide after the holidays, in any case.

**Comment by RandomDSdevel** [comment]
@fxcoudert:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;See https://github.com/Homebrew/homebrew-core/pull/32864#issuecomment-451253484.

**Pull request closed without merging**
