### PR TITLE
nativefier 42.0.0

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dtrodrigues** [comment]
https://github.com/jiahaog/nativefier/commit/9dc0bed95c6c812ba99a4e59d90f30d0b3d68e36
```
Also, bumping npm version to something far away from current Electron version.

Rationale for the nonsensical major version bump: around Nativefier 8.x,
versions of Nativefier and Electron aligned, by release schedule coincidence.
Since Nativefier has little breaking changes, it was great: as Electron
releases are breaking, Nativefier had no breaking changes, I bumped our
major version on new major Electron, and everything was good.

Except *now*, as I have a breaking change, which would bump Nativefier to
12.x, being annoyingly confusing since we'd still default to Electron 11 :-/ .

-> To keep respecting semver and reduce confusion, bumping Nativefier
   version to something far ahead of Electron versions. No it doesn't
   matter, version number are meaningless anyway (well, outside of
   semver, whose respect is precisely the point here).
```

**Comment by dtrodrigues** [comment]
```
==> /usr/local/Cellar/nativefier/42.0.0/bin/nativefier --version
Invalid argument passed: /usr/local/Cellar/node/15.3.0/bin/node .
Nativefier supports short options (like "-n") and long options (like "--name"), all lowercase. Run "nativefier --help" for help.
Aborting
```

See https://github.com/jiahaog/nativefier/issues/1083

**Comment by ronjouch** [comment]
Hi there, Nativefier maintainer here. I just published 42.0.1, which should fix the regression in 42.0.0. It's not visible yet in npm's web interface, but it's available, `npm install` did resolve to `nativefier@42.0.1` Thanks for the heads up.

@fxcoudert out of curiosity, why the [:confused: reaction to the version number change](https://github.com/Homebrew/homebrew-core/pull/66363#issuecomment-739555860)? Is it breaking anything?

**Comment by dtrodrigues** [comment]
Thanks @ronjouch, I've opened https://github.com/Homebrew/homebrew-core/pull/66381

**Pull request closed without merging**
