### PR TITLE
apache-arrow, apache-arrow-glib 12.0.1

### PR DESCRIPTION
**Pull request by raulcd**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by raulcd** [comment]
@carlocab @chenrui333 can you help me adding the:  `long build`, `CI-long-timeout` labels?
Thanks!

**Comment by carlocab** [comment]
Should be good now. Please rebase. Thanks!

Incidentally: are you sure your `revision` bumps are necessary?

**Comment by carlocab** [comment]
Based on local testing (on Linux): I don't think your `revision` bumps are needed.

**Comment by carlocab** [comment]
We might be able to use a newer `protobuf`/`grpc` in #133623.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
