### PR TITLE
libgroove: migrate to boneyard

### PR DESCRIPTION
**Pull request by DomT4**
Created with `brew boneyard-formula-pr` because Upstream unresponsive to reported issues for 6+ months.

### CODE REVIEW

**Comment by DomT4** [comment]
See:

https://github.com/Homebrew/homebrew-core/pull/8595
https://github.com/Homebrew/homebrew-core/pull/5180
https://github.com/Homebrew/homebrew-core/issues/6408
https://github.com/andrewrk/libgroove/issues/129

Upstream hasn't pushed a commit for a year now, and there's no upstream response to the issue Alex filed 6 months ago. This can't keep blocking things being updated forever.

**Comment by DomT4** [comment]
Jenkins threw an unrelated tantrum.

**Comment by fxcoudert** [comment]
Boneyard sounds reasonable

**Comment by ilovezfs** [comment]
did anyone try to fix it

**Comment by DomT4** [comment]
Upstream made some changes around their custom shim in 2015 but haven't cut a release with that in yet, which I haven't tested locally, but it's also not up-to-date on `ffmpeg` or `chromaprint` compatibility even at the tip of the master branch upstream. Kind of a case of "Does Homebrew want to become the new upstream? 🎉" sadly.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/10758

**Comment by DomT4** [comment]
It seems absolutely certain to break at some point given upstream's lack of activity, but if you're happy to support it from the `brew` side of things for at least the foreseeable feel free to close this.

**Comment by ilovezfs** [comment]
@DomT4 can you elaborate on the ffmpeg/chromaprint thing?

**Comment by DomT4** [comment]
Was working off upstream issues:

https://github.com/andrewrk/libgroove/issues/131
https://github.com/andrewrk/libgroove/issues/130

And [this commit](https://github.com/andrewrk/libgroove/commit/aed5104a92089e9b56ac5a47935980f9f07f72b5) which hasn't made it into a release yet.

**Comment by ilovezfs** [comment]
ok, let's kill it.

**Pull request merged**
