### PR TITLE
dive: add livecheck

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
upstream release build failed, https://github.com/wagoodman/dive/actions/runs/5465690573

**Review by chenrui333 — APPROVED** [review]

**Comment by abitrolly** [comment]
@chenrui333 will that also release `0.11.0`?

By the way, why this PR is needed when livecheck works without it?

```shell
$ brew bump dive
...
==> dive
Current formula version:  0.10.0
Latest livecheck version: 0.11.0
Latest Repology version:  0.10.1
```

**Comment by chenrui333** [comment]
@abitrolly it is needed whenever there is a failure release in the upstream and we might have re-tagging risk. Let me know if that makes sense, thanks!

**Comment by chenrui333** [comment]
@abitrolly you can also see the related issue, https://github.com/wagoodman/dive/issues/456, thanks for checking on this PR.

**Comment by abitrolly** [comment]
> @abitrolly it is needed whenever there is a failure release in the upstream and we might have re-tagging risk. Let me know if that makes sense, thanks!

Not sure I get how it works. `dive` 0.10.1 got tagged, but upstream release failed. What is re-tagging risk here?

**Comment by p-linnane** [comment]
Let's just close this and bump to v0.11.0 since the release process is fixed.

**Comment by p-linnane** [comment]
https://github.com/Homebrew/homebrew-core/pull/136077

**Comment by chenrui333** [comment]
> > @abitrolly it is needed whenever there is a failure release in the upstream and we might have re-tagging risk. Let me know if that makes sense, thanks!
> 
> @chenrui333 not sure I get how it works. `dive` 0.10.1 got tagged, but upstream release failed. What is the re-tagging risk here? What happens if upstream get re-tagged?

this is the preventive measure that I am seeking across the board.

Instead of filing the upstream issues and get them fixed, we dont have to run into such thing in the first place (by adding the livecheck to ignore the unreleased tags), let me know if that makes better sense now.

**Comment by abitrolly** [comment]
> instead of filing the upstream issues to report report about the release process issue, and get them fixed, I can just avoid running into it in the first place (by adding the livecheck to ignore the unreleased tags)

@chenrui333 that makes sense. But why `brew dump dive` can not ignore unreleased tags automatically?

**Pull request closed without merging**
