### PR TITLE
cantata 2.4.2 (new formula)

### PR DESCRIPTION
**Pull request by kmontag**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

As discussed in Homebrew/discussions#1370 and CDrummond/cantata#1671, the Cantata maintainer is no longer providing precompiled binaries for Cantata releases. Therefore, the `cantata` cask (https://formulae.brew.sh/cask/cantata) cannot be updated beyond `v2.3.2`, which was released in August 2018.

This adds a core formula to supercede the cask distribution. The formula builds a `.app` bundle, and the user is informed via caveats that they may wish to link it to their system directory. A symlink to the `cantata` binary is also exposed directly in the formula's `bin/` directory.

~A patch is applied to fix the application's theming on MacOS. This change has also been merged into Cantata master (CDrummond/cantata#1692), but not yet included in a release.~

#3331 provides some precedent for this sort of migration. As with `gedit`, I imagine we'd also want to sunset the `cantata` cask if this PR is accepted.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Thanks for your PR, @kmontag. A few comments.

**Comment by carlocab** [comment]
> ~A patch is applied to fix the application's theming on MacOS. This change has also been merged into Cantata master ([CDrummond/cantata#1692](https://github.com/CDrummond/cantata/pull/1692)), but not yet included in a release.~

Can we ask if they're willing to cut a new release with this patch, or, at least, when the next release that includes this might be made?

**Comment by Marcool04** [comment]
> I suppose if the `.dmg` builds are automated and included in releases, we could keep this as a cask. (I've never worked with Github CI, but I guess it should be fairly easy to translate this formula into a CI workflow...famous last words.)

Not too hard indeed 😁: https://github.com/Marcool04/cantata/blob/github-actions/.github/workflows/github-actions.yml
(not sure it's 100% correct, but it builds and the dmg produced is fine on my machine)

Well done @kmontag for getting this formula submitted! I really wanted to and just don't have enough ruby experience nor time on my hands to get it to build. Kudos to you!

**Comment by kmontag** [comment]
Oh, that's great @Marcool04! So I guess this means `2.5.0` should have a `.dmg` attached to the release? In that case maybe it's best to close this and keep Cantata as a cask. We can re-open if the release gets significantly delayed or something. What do you think @carlocab?

**Comment by Marcool04** [comment]
> Oh, that's great @Marcool04! So I guess [this](https://github.com/CDrummond/cantata/pull/1747) means `2.5.0` should have a `.dmg` attached to the release? In that case maybe it's best to close this and keep Cantata as a cask. We can re-open if the release gets significantly delayed or something. What do you think @carlocab?

I do hope so… if all goes well it should (took me a few tries to get it to work on my branch, so there could well be some more ironing out to do).

> Sounds good to me. Thanks for your work here, @kmontag, @Marcool04!

Quite welcome!

**Pull request closed without merging**
