### PR TITLE
docbook-xsl: introduce stack usage patch and URL rewrites

### PR DESCRIPTION
**Pull request by pthariensflame**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See [this page](http://www.linuxfromscratch.org/blfs/view/9.1/pst/docbook-xsl.html).

### CODE REVIEW

**Comment by Bo98** [comment]
I don't know what this fixes, but it doesn't look like it will fix the gtk-doc situation.

Seems like that patch is for some issue that isn't even 1.79.2 specific.

**Comment by pthariensflame** [comment]
@Bo98 I've added more to this.  It should be more likely to fix `gtk-doc` _et al._; I guess we'll see.

**Comment by pthariensflame** [comment]
Waiting on Homebrew/homebrew-test-bot#345 to test this properly.

**Comment by Bo98** [comment]
We should also test upgrading existing installations. I feel some of this stuff may need to be moved to `postinstall` as I don't think `etc` files are overwritten.

We should probably also be using `opt_prefix` if possible (this should be tested in case symlinks don't work) as we won't be able to delete the old entries properly while just relying on `prefix`, albeit it's perhaps too late now to cover existing 1.79.1 installations.

**Comment by pthariensflame** [comment]
It _is_ in `postinstall` already.

**Comment by Bo98** [comment]
Sorry, I think I was looking at two pull request so at once!

I’d still be tempted to give opt_prefix a shot as the `--del` is currently pretty useless IMO.

**Comment by Bo98** [comment]
Also what was the `touch "log"` lines for?

**Comment by pthariensflame** [comment]
The `touch "log"` lines are there because 1.79.2 no longer supplied empty log files like 1.79.1 did, and I figured it would be more in line with stability to remake them on installation than to fail to install them at all.

**Comment by pthariensflame** [comment]
Local testing has confirmed that the `#{etc}` vs. `#{opt_etc}` thing doesn't seem to make a difference.  Notably, two entirely different formulas see the same `#{etc}` during `postinstall`: `docbook` and `docbook-xsl`.

**Comment by Bo98** [comment]
I'm talking about `opt_prefix` over `prefix` - not `opt_etc` which I don't even think is a thing.

**Comment by iMichka** [comment]
I am OK to keep the patch, looks like it fixes something for someone.

The change looks good overall, glad we are making steps forward to a solution. I confirm that this fixes gtk-doc.

The only remaining question is if we could use `opt_prefix` instead of `prefix`.

**Comment by pthariensflame** [comment]
Oh, I see what you're talking about.  Okay; I'll update it to use `opt_prefix`.  :)

**Comment by pthariensflame** [comment]
@Bo98 @iMichka Done!

**Comment by iMichka** [comment]
- [ ]   `fceux`

> scons RELEASE=1 GTK=0 GTK3=1 LOGO=0
Last 150 lines from /Users/brew/Jenkins/workspace/core/logs/fceux/01.scons:
2020-03-25 06:16:05 +0000
scons
RELEASE=1
GTK=0
GTK3=1
LOGO=0
scons: Reading SConscript files ...
  File "/private/tmp/fceux-20200325-62170-nifb3s/fceux-2.2.3/SConstruct", line 72
    print "platform: ", env['PLATFORM']
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("platform: ", env['PLATFORM'])?

- [ ]   `gitg`

> FAILED: libgitg/5cbadd7@@gitg-1.0@sha/gitg-platform-support-osx.c.o 
clang -Ilibgitg/5cbadd7@@gitg-1.0@sha -Ilibgitg -I../libgitg -I. -I../ -Icontrib/ide -I../contrib/ide -I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/Cellar/pcre/8.44/include -I/usr/local/Cellar/glib/2.64.1/include -I/usr/local/Cellar/glib/2.64.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.64.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libgee/0.20.3/include/gee-0.8 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/Cellar/glib/2.64.1/include/gio-unix-2.0 -I/usr/local/Cellar/pixman/0.38.4/include/pixman-1 -I/usr/local/Cellar/cairo/1.16.0_2/include/cairo -I/usr/local/Cellar/gdk-pixbuf/2.40.0/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/fribidi/1.0.9/include/fribidi -I/usr/local/Cellar/graphite2/1.3.13/include -I/usr/local/Cellar/harfbuzz/2.6.4/include/harfbuzz -I/usr/local/Cellar/pango/1.44.7/include/pango-1.0 -I/usr/local/Cellar/atk/2.34.1/include/atk-1.0 -I/usr/local/Cellar/libepoxy/1.5.4/include -I/usr/local/Cellar/gtk+3/3.24.14/include/gtk-3.0 -I/usr/local/Cellar/libgit2/0.28.4/include -I/usr/local/Cellar/libgit2-glib/0.28.0.1/include/libgit2-glib-1.0 -I/usr/local/Cellar/libdazzle/3.36.0/include/libdazzle-1.0 -I/usr/local/Cellar/gsettings-desktop-schemas/3.36.0/include/gsettings-desktop-schemas -I/usr/local/Cellar/gtksourceview3/3.24.11_2/include/gtksourceview-3.0 -I/usr/include/libxml2 -I/usr/local/Cellar/libsecret/0.20.2/include/libsecret-1 -I/usr/local/Cellar/sqlite/3.31.1/include -I/usr/local/Cellar/libpsl/0.21.0_2/include -I/usr/local/Cellar/libsoup/2.70.0/include/libsoup-2.4 -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -O2 -g -DHAVE_CONFIG_H '-DG_LOG_DOMAIN="gitg"' -DGIT_SSH=1 -Werror=format=2 -Werror=implicit-function-declaration -Werror=init-self -Werror=missing-include-dirs -Werror=missing-prototypes -Werror=pointer-arith -Werror=return-type -Wmissing-declarations -Wnested-externs -Wstrict-prototypes -Wuninitialized '-DDATADIR="/usr/local/Cellar/gitg/3.32.1_1/share"' '-DLIBDIR="/usr/local/Cellar/gitg/3.32.1_1/lib"' '-DGETTEXT_PACKAGE="gitg"' -xobjective-c -MD -MQ 'libgitg/5cbadd7@@gitg-1.0@sha/gitg-platform-support-osx.c.o' -MF 'libgitg/5cbadd7@@gitg-1.0@sha/gitg-platform-support-osx.c.o.d' -o 'libgitg/5cbadd7@@gitg-1.0@sha/gitg-platform-support-osx.c.o' -c ../libgitg/gitg-platform-support-osx.c
../libgitg/gitg-platform-support-osx.c:51:3: error: unknown type name 'NSString'; did you mean 'GString'?
                NSString *dataUrl = [NSString stringWithUTF8String:g_file_get_uri (file)];
                ^~~~~~~~
                GString
/usr/local/Cellar/glib/2.64.1/include/glib-2.0/glib/gstring.h:39:33: note: 'GString' declared here
typedef struct _GString         GString;
                                ^
../libgitg/gitg-platform-support-osx.c:51:24: error: use of undeclared identifier 'NSString'
                NSString *dataUrl = [NSString stringWithUTF8String:g_file_get_uri (file)];
                                     ^
../libgitg/gitg-platform-support-osx.c:52:3: error: use of undeclared identifier 'NSURLRequest'
                NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:dataUrl]];
                ^
../libgitg/gitg-platform-support-osx.c:52:17: error: use of undeclared identifier 'request'
                NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:dataUrl]];
                              ^
../libgitg/gitg-platform-support-osx.c:52:28: error: use of undeclared identifier 'NSURLRequest'
                NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:dataUrl]];
                                         ^
../libgitg/gitg-platform-support-osx.c:53:3: error: use of undeclared identifier 'NSOperationQueue'
                NSOperationQueue *queue = [[NSOperationQueue alloc] init];
                ^
../libgitg/gitg-platform-support-osx.c:53:21: error: use of undeclared identifier 'queue'
                NSOperationQueue *queue = [[NSOperationQueue alloc] init];
                                  ^
../libgitg/gitg-platform-support-osx.c:53:31: error: use of undeclared identifier 'NSOperationQueue'
                NSOperationQueue *queue = [[NSOperationQueue alloc] init];
                                            ^
../libgitg/gitg-platform-support-osx.c:57:4: error: use of undeclared identifier 'NSURLConnection'
                [NSURLConnection sendAsynchronousRequest:request queue:queue completionHandler:^(NSURLResponse *response, NSData *data, NSError *error) {
                 ^
../libgitg/gitg-platform-support-osx.c:102:2: error: use of undeclared identifier 'NSCursor'
        NSCursor *cursor;
        ^
../libgitg/gitg-platform-support-osx.c:102:12: error: use of undeclared identifier 'cursor'
        NSCursor *cursor;
                  ^
../libgitg/gitg-platform-support-osx.c:103:2: error: use of undeclared identifier 'NSImage'
        NSImage *image;
        ^
../libgitg/gitg-platform-support-osx.c:103:11: error: use of undeclared identifier 'image'
        NSImage *image;
                 ^
../libgitg/gitg-platform-support-osx.c:104:2: error: use of undeclared identifier 'NSBitmapImageRep'
        NSBitmapImageRep *image_rep;
        ^
../libgitg/gitg-platform-support-osx.c:104:20: error: use of undeclared identifier 'image_rep'
        NSBitmapImageRep *image_rep;
                          ^
../libgitg/gitg-platform-support-osx.c:106:2: error: use of undeclared identifier 'NSSize'
        NSSize size;
        ^
../libgitg/gitg-platform-support-osx.c:107:2: error: use of undeclared identifier 'NSPoint'
        NSPoint hotspot;
        ^
../libgitg/gitg-platform-support-osx.c:117:4: error: use of undeclared identifier 'cursor'
                        cursor = [NSCursor pointingHandCursor];
                        ^
../libgitg/gitg-platform-support-osx.c:117:14: error: use of undeclared identifier 'NSCursor'
                        cursor = [NSCursor pointingHandCursor];
                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

- [ ]   `opensc`

> checking for readline in -lreadline... yes
checking readline/readline.h usability... yes
checking readline/readline.h presence... yes
checking for readline/readline.h... yes
checking for libcrypto >= 0.9.8... yes
configure: WARNING: libeac not found by pkg-config
checking eac/eac.h usability... no
checking eac/eac.h presence... no
checking for eac/eac.h... no
configure: WARNING: OpenPACE headers not found
checking for EAC_CTX_init_pace... configure: WARNING: Cannot link against libeac
Package libeac was not found in the pkg-config search path.
Perhaps you should add the directory containing `libeac.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libeac' found
configure: WARNING: use --enable-cvcdir=DIR
Package libeac was not found in the pkg-config search path.
Perhaps you should add the directory containing `libeac.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libeac' found
Package libeac was not found in the pkg-config search path.
Perhaps you should add the directory containing `libeac.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libeac' found
configure: WARNING: use --enable-x509dir=DIR
checking winscard.h usability... no
checking winscard.h presence... no
checking for winscard.h... no
configure: error: winscard.h is required for pcsc

- [ ]   `pytouhou`

> ==> python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/pytouhou/634_5/libexec --install-scripts=/usr/local/Cellar/pytouhou/634_5/libexec/bin --single-version-externally-managed --record=installed.txt
Last 150 lines from /Users/brew/Jenkins/workspace/core/logs/pytouhou/02.python3:
2020-03-25 11:14:18 +0000
python3
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/pytouhou/634_5/libexec
--install-scripts=/usr/local/Cellar/pytouhou/634_5/libexec/bin
--single-version-externally-managed
--record=installed.txt
Package glfw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glfw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glfw3' found

**Comment by iMichka** [comment]
These errors seem unrelated. When the build is done, I propose to merge this as-is with the new docbook-xsl bottle, and work on these issues separately.

**Comment by Bo98** [comment]
I agree.

* fceux is because it is incompatible with Python 3, which `scons` now uses.
* gitg is a pre-existing failure that existed before docbook-xsl was updated. Upstream claim it is a docbook-xsl problem but it 100% is not.
* opensc happens on High Sierra only. Not docbook-sdk related, but will need investigating at some point.
* pytouhou probably needs `depends_on "glfw"`, though I don't know what changed to have made that work before. Either way, unlikely to be related to docbook-xsl.

**Comment by iMichka** [comment]
- [ ] `efl` on Catalina 

> CC       lib/elementary/libelementary_la-elc_ctxpopup.lo
  CC       lib/elementary/libelementary_la-elc_fileselector.lo
  CC       lib/elementary/libelementary_la-elc_fileselector_button.lo
  CC       lib/elementary/libelementary_la-elc_fileselector_entry.lo
  CC       lib/elementary/libelementary_la-elc_hoversel.lo
lib/ecore_cocoa/ecore_cocoa_app.m:48:5: error: use of undeclared identifier '_mainMenu'
   [_mainMenu update];
    ^
lib/ecore_cocoa/ecore_cocoa_app.m:79:4: error: use of undeclared identifier '_running'
   _running = 1;
   ^
2 errors generated.
make[3]: *** [lib/ecore_cocoa/libecore_cocoa_la-ecore_cocoa_app.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [install-recursive] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

Also unrelated

**Comment by Bo98** [comment]
Also pre-existing.

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Thanks @pthariensflame !

**Comment by chenrui333** [comment]
Thanks @pthariensflame !!

**Comment by iMichka** [comment]
There is a patch for fceux, I asked for a release: https://github.com/TASVideos/fceux/pull/75
I made another comment on https://gitlab.gnome.org/GNOME/gitg/-/issues/277 for gitg.
I opened a PR for pytouhou : https://github.com/Homebrew/homebrew-core/pull/52128

The rest can stay as-is until somebody has time to fix this.

**Pull request closed without merging**
