### PR TITLE
xmake: revision for ARM

### PR DESCRIPTION
**Pull request by fxcoudert**
Trying to bottle on ARM

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
compile:
    plat:		macosx
    arch:		x86_64
    host:		macosx
```

then

```
make[3]: *** [tbox/src/tbox/platform/file.o] Error 1
475
make[3]: *** Waiting for unfinished jobs....
476
make[2]: *** [DEP_PROS_tbox_all] Error 2
477
: note: 'stat' declared here
478
int     stat(const char *, struct stat *) __DARWIN_INODE64(stat);
479
        ^
480
```

**Comment by waruqi** [comment]
try `make BUILD_ARCH=arm64`

A better solution is to modify the makefile to automatically detect the macos/arm environment.

https://github.com/xmake-io/xmake/blob/f8d0f8e608bb58e4a1dfeadf7d9068a8d6b471ae/core/makefile#L171

**Comment by waruqi** [comment]
I have supported apple m1, and it works for me.

you can switch url to `https://github.com/xmake-io/xmake/releases/download/v2.3.9/xmake-v2.3.9.m1.tar.gz` 
and modify shasum to 25a8fc39c6859854d26cec918eca94e16427d76870a9f29f4b302f7d300674a2 and try it again.

**Comment by SMillerDev** [comment]
Wouldn't that break it for Intel?

**Comment by waruqi** [comment]
> Wouldn't that break it for Intel?

No, fully compatible

**Comment by SMillerDev** [comment]
> No, fully compatible

The m1 in the name there is really confusing then. Why not just make a `v2.3.10` or `v2.3.9.1`?

**Comment by fxcoudert** [comment]
Is it necessary to pass `BUILD_ARCH=arm64`?

**Comment by waruqi** [comment]
> > No, fully compatible
> 
> The m1 in the name there is really confusing then. Why not just make a `v2.3.10` or `v2.3.9.1`?

This is just a temporary version.

soon, I will release 2.5.1, and then I will open a new pr to update it.

**Comment by waruqi** [comment]
> Is it necessary to pass `BUILD_ARCH=arm64`?

No need, just execute make.

**Comment by fxcoudert** [comment]
`tbox` is the only formula we have depending on `xmake`, so let's try to build an ARM bottle for it at the same time

**Pull request closed without merging**
