### PR TITLE
apm-server 6.0.1

### PR DESCRIPTION
**Pull request by tylerjl**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@tylerjl it appears this release doesn't actually exist (yet?).

**Comment by tylerjl** [comment]
Thanks @ilovezfs, I'm working with upstream to get the repo appropriately tagged, I'll report back when it's ready to re-test. 👍

**Comment by ilovezfs** [comment]
I've updated the checksum.

**Comment by ilovezfs** [comment]
Thanks @tylerjl! Shipped.

**Pull request closed without merging**
