### PR TITLE
distcc: migrate to python@3.11

### PR DESCRIPTION
**Pull request by ryenus**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
This pull request updates distcc to use python@3.11 instead of python@3.10, see the related pull request https://github.com/Homebrew/homebrew-core/pull/114154

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  The following error occurred while trying to add or remove files in the
  installation directory:
  
      [Errno 1] Operation not permitted: '/opt/homebrew/lib/python3.11/site-packages/test-easy-install-26243.write-test'
```

**Comment by cho-m** [comment]
Added a new test that uses Python code, but looks like it is timing out on Linux. Will need to try locally to figure out why.

**Comment by chenrui333** [comment]
gonna re-queue the build and how it works this time.

**Comment by chenrui333** [comment]
pretty weird, cannot reproduce it.

**Comment by chenrui333** [comment]
cc @Homebrew/linux

**Comment by iMichka** [comment]
Odd. Can't reproduce either. Might be a race condition?

**Comment by chenrui333** [comment]
so let's comment out that test for linux runner then.

**Review by iMichka — APPROVED** [review]

**Pull request closed without merging**
