### PR TITLE
expect: use brewed tcl-tk

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

From `license.terms`:

```
Design and implementation of this program was paid for by U.S. tax
dollars.  Therefore it is public domain.  However, the author and NIST
would appreciate credit if this program or parts of it are used.
```

See also #72714, #72450, #67378.

### CODE REVIEW

**Comment by carlocab** [comment]
Huh, ARM failure:
```
checking build system type... configure: error: /bin/sh tclconfig/config.sub -apple-darwin20.3.0 failed
configure: WARNING: cache variable ac_cv_build contains a newline
```

**Comment by Bo98** [comment]
Probably an old, outdated `config.guess/sub`

**Comment by carlocab** [comment]
As a configure flag, you mean? Is there a portable way to set that? Or just make it conditional on ARM?

**Comment by Bo98** [comment]
Actually we depend on `automake` so just replace `config.guess` and `config.sub` with the ones from `#{Formula["automake"].opt_prefix}/share/automake-#{Formula["automake"].version.major_minor}`

**Comment by carlocab** [comment]
Tried that; didn't work. Or did I do it incorrectly?

**Comment by Bo98** [comment]
They're in the `tclconfig` subdirectory.

**Comment by carlocab** [comment]
Whoops; of course they are

**Pull request closed without merging**
