### PR TITLE
{helm@2, landscaper}: deprecate

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

relates to #59698

### CODE REVIEW

**Comment by SMillerDev** [comment]
Deprecations are not CI only, they could pull the rug out from other formula.

**Comment by claui** [comment]
Haven’t looked at the CI failures yet but 👍 on deprecating both formulae:
`landscaper` has a very low usage count, plus it’s [no longer maintained](https://github.com/Eneco/landscaper/tree/b9f9be234333161cd004637234f7ea04dfc64c91). While `helm@2` has significant numbers of downloads, anyone is free to use latest stable. Deprecating `helm@2` feels kind of justified if it causes us trouble.

**Comment by chenrui333** [comment]
`helm@2` is just not buildable, but still useable though (that is why you see a sizable downloads). 

`landscaper` has a replacement called, `helmfile`.

**Comment by chenrui333** [comment]
> Haven’t looked at the CI failures yet but 👍 on deprecating both formulae:

CI failures are actually expected since it was constantly failed with each golang version bump.

**Comment by claui** [comment]
@chenrui333 Looks like you’re correct.

**Review by claui — APPROVED** [review]
I agree with what @SMillerDev wrote.
But since CI has already returned green for all dependent formulae, I’m 👍 on merging as-is.

**Comment by chenrui333** [comment]
@SMillerDev how should we proceed on this?

**Comment by chenrui333** [comment]
I go ahead merging these changes as they are (should be no disruption)

**Comment by chenrui333** [comment]
Looks like they just released a new revision for helm@2 and it is buildable now (#61270)

**Pull request merged**
