### PR TITLE
gem-completion 20170723

### PR DESCRIPTION
**Pull request by igas**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @igas but it's not a stable release, so we'll pass.

**Comment by igas** [comment]
Hi @fxcoudert, 

I know, but I think we should decide what do we do here. There are few formulas lake this that never had tags but in brew. I think we should either update them in this case or drop them.

What do you think?

**Comment by igas** [comment]
Examples:

https://github.com/Homebrew/homebrew-core/pull/34459
https://github.com/Homebrew/homebrew-core/pull/34489

**Comment by fxcoudert** [comment]
They show some use, so I'm all for letting them live… but no updates unless upstream tags a release. If people are motivated to have the latest, they will lobby for a release :)

**Pull request closed without merging**
