### PR TITLE
emacs 25.1-rc2 (devel)

### PR DESCRIPTION
**Pull request by cacology**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
A duplicate of https://github.com/Homebrew/homebrew-core/pull/4132 (just).

**Comment by MikeMcQuaid** [comment]
er, other way around 😉

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by ilovezfs** [comment]
@MikeMcQuaid That url doesn't resolve which is why I'd changed it ...

**Comment by MikeMcQuaid** [comment]
https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6635/version=el_capitan/testReport/brew-test-bot/el_capitan/fetch___devel_emacs/ seems to work ok?

**Comment by ilovezfs** [comment]
screen shot 2016-08-22 at 3 58 18 am

Looks like it's an SSL problem:
```
Josephs-MacBook-Pro:~ joe$ wget  http://alpha.gnu.org/gnu/emacs/pretest/emacs-25.1-rc2.tar.xz
URL transformed to HTTPS due to an HSTS policy
--2016-08-22 04:00:00--  https://alpha.gnu.org/gnu/emacs/pretest/emacs-25.1-rc2.tar.xz
Resolving alpha.gnu.org... 208.118.235.21, 2001:4830:134:3::c
Connecting to alpha.gnu.org|208.118.235.21|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-08-22 04:00:01 ERROR 404: Not Found.

Josephs-MacBook-Pro:~ joe$ curl -OL http://alpha.gnu.org/gnu/emacs/pretest/emacs-25.1-rc2.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40.3M  100 40.3M    0     0  3512k      0  0:00:11  0:00:11 --:--:-- 4315k
Josephs-MacBook-Pro:~ joe$ sha256 emacs-25.1-rc2.tar.xz 
SHA256(emacs-25.1-rc2.tar.xz)= 5bd45f03bdff90f9d7add7224917fc828ed89716e952b3db8eb98242b7dfcec1
Josephs-MacBook-Pro:~ joe$ rm emacs-25.1-rc2.tar.xz 
Josephs-MacBook-Pro:~ joe$ curl -OL https://alpha.gnu.org/gnu/emacs/pretest/emacs-25.1-rc2.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   328  100   328    0     0    750      0 --:--:-- --:--:-- --:--:--   953
Josephs-MacBook-Pro:~ joe$ cat emacs-25.1-rc2.tar.xz 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /gnu/emacs/pretest/emacs-25.1-rc2.tar.xz was not found on this server.</p>
<hr>
<address>Apache/2.4.7 (Trisquel_GNU/Linux) Server at alpha.gnu.org Port 443</address>
</body></html>
Josephs-MacBook-Pro:~ joe$
```

**Pull request merged**
