### PR TITLE
pango: Update the SHA-256 of the patch

### PR DESCRIPTION
**Pull request by sjackman**
Is gitlab.gnome.org having a SHApocalypse?

```
==> Downloading https://gitlab.gnome.org/tschoonj/pango/commit/60df2b006e5d4553a
Downloaded to: /Users/sjackman/Library/Caches/Homebrew/pango--patch--d5ece753cf393ef507dd2b0415721b4381159da5e2f40793c6d85741b1b163bc.patch
SHA256: a31188c253b3b57b134d1fee1bfaa7d45c55986aa76165a1ebacd184f2b16439
Warning: Patch reports different SHA256: d5ece753cf393ef507dd2b0415721b4381159da5e2f40793c6d85741b1b163bc
```

### CODE REVIEW

**Review by DomT4 — DISMISSED** [review]
Going to need some kind of confirmation here, although I suspect that confirmation may well indeed be "Yes, we upgraded git server-side". 

Edit - _I meant to leave this as a neutral comment rather than a request for change but Chrome on Mojave has some rendering issues which make such things difficult_ 🙃.

**Comment by sjackman** [comment]
Does anyone happen to have a cached copy of the previous patch with SHA-256 of `d5ece753cf393ef507dd2b0415721b4381159da5e2f40793c6d85741b1b163bc`?

**Comment by sjackman** [comment]
The SHA-1 of the commit in the URL hasn't changed.
https://gitlab.gnome.org/tschoonj/pango/commit/60df2b006e5d4553abc7bb5fe9a99539c91b0022.patch

**Comment by sjackman** [comment]
I'm afraid that I don't have the time to follow up with upstream myself. For whomever is interested, here's links the upstream's bugtrackers:
https://gitlab.gnome.org/GNOME/pango/issues
https://bugzilla.gnome.org/show_bug.cgi?id=787867

**Comment by DomT4** [comment]
Retrieved the prior patch from the El Capitan VM, which was _fun_, and confirmed upstream updated their `git` version from 2.17.1 to 2.18.0, which broke the hash. To prevent this happening again I've (well, technically you've) moved the patch over to our `formula-patches` repo.

**Comment by sjackman** [comment]
No worries at all. Thanks for resolving this issue, Dominyk!

**Pull request closed without merging**
