### PR TITLE
less 563

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
checking for working terminal libraries... Cannot find terminal libraries - configure failed
```

**Comment by sharris40** [comment]
As usual, this is caused by Xcode 12 no longer allowing implicit function declarations. In `configure.ac`, all the `AC_TRY_LINK` commands from lines 55-173 try to link against functions without declaring them, which is no longer allowed.

**Comment by chenrui333** [comment]
@sharris40 are you aware of any workarounds of solving this issue?

**Comment by carlocab** [comment]
Use Homebrew `clang` to build it. See https://github.com/carlocab/homebrew-personal/blob/main/Formula/less%40563.rb

I should mention that I don't know Ruby, and I'm not familiar with the `brew` codebase, so the way I've done things may not be idiomatic. However, it did build for me.

**Comment by carlocab** [comment]
By the way, the `llvm` `LDFLAGS` don't be necessary to build. The formula in my tap works fine after removal of those flags.

**Comment by carlocab** [comment]
Apologies for the spam, but I thought it'd be useful for you to know that I've updated the formula in my tap into a form that I think is suitable (with minor modification) for homebrew/core: https://github.com/carlocab/homebrew-personal/blob/main/Formula/less-ncurses.rb

You can just replace the `depends_on "ncurses"` with `uses_from_macos "ncurses"` and `pcre2` with `pcre`.

However, I think it would be useful if Homebrew less was linked to Homebrew ncurses: this will improve compatibility with some other Homebrew software that use the newer ncurses (e.g. zsh, tmux). After all, users already have a built-in `less` that is linked against the old ncurses, so I think there's not much value added to a Homebrew version of less unless it also used the much newer ncurses library.

**Pull request closed without merging**
