### PR TITLE
python@3.12 python-gdbm@3.12 python-tk@3.12 3.12.4

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by utkonos** [comment]
Can this be merged?

**Comment by timsutton** [comment]
While the CI output can look like it's stuck:

image

I made that same assumption this morning and cancelled the runs, only to find that after cancelling the logs got finally populated and were viewable. So I think we probably just need to give this enough time (like 14+ hours) to run its course on all the dependent tests.

**Comment by timsutton** [comment]
The two failing tests here (`bazarr` and `gorilla-cli`) are fixed in the master branch. I didn't want to rebase this PR and interrupt the current jobs or Linux queue given the long CI loop here.

**Review by bevanjkay — APPROVED** [review]

**Comment by branchvincent** [comment]
Can't see linux logs for some reason, but the two main failing tests were fixed and only others are isolated to a specific runner and seem like flakes

**Pull request merged**
