### PR TITLE
generate-json-schema 2.3.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
Version hardcoded in the test smh https://bot.brew.sh/job/Homebrew Core Pull Requests/8369/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_generate_json_schema/

**Comment by MikeMcQuaid** [comment]
@ilovezfs If you set this PR to allow maintainers to edit I'll happily change https://github.com/Homebrew/homebrew-core/pull/5300/files#diff-98c1d858e7d90c7adf86ffd532a56186R48 for you 😉

**Comment by ilovezfs** [comment]
pretty sure this is still sitting here because that wasn't the only problem ;)

**Comment by MikeMcQuaid** [comment]
@ilovezfs Would be good to fix that problem and figure out the other(s) 😉

**Comment by ilovezfs** [comment]
Indeed. There are lots of things that would be good.

**Comment by ilovezfs** [comment]
Fixed. :green_apple:

**Comment by MikeMcQuaid** [comment]
Hooray! 🚢 able?

**Comment by ilovezfs** [comment]
Yes, though I'd not be surprised if that test breaks every time.

**Comment by MikeMcQuaid** [comment]
Maybe worth just checking `Welcome to Generate Schema #{version}` and the exit code. Could even just use `system` now, too, if the mentioned bug is fixed.

**Comment by ilovezfs** [comment]
```
if (args[0]) {
  stream = fs.createReadStream(args[0])
  stream.on('close', function () {
    process.exit(1)
  })
}
```
So system fails due to the ridiculous exit code.

**Comment by MikeMcQuaid** [comment]
Ok. Does `pipe_output` help? If not, I think just doing a simpler string match is probably more sane if we can't really check the exit code.

**Comment by ilovezfs** [comment]
Maybe just
```
    assert_match "schema.org", pipe_output("#{bin}/generate-schema", input, 0)
```

**Comment by MikeMcQuaid** [comment]
@ilovezfs 👍

**Pull request closed without merging**
