### PR TITLE
ugrep 2.5.2

### PR DESCRIPTION
**Pull request by pete-woods**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by issyl0 — DISMISSED** [review]
Thanks!

**Comment by genivia-inc** [comment]
It seems that this latest commit is hanging on incomplete tests for some time now. Looking forward to see this move forward.

**Comment by SMillerDev** [comment]
No checks even started. @pete-woods could you rebase to trigger a new CI run?

**Comment by pete-woods** [comment]
> No checks even started. @pete-woods could you rebase to trigger a new CI run?

Done!

**Review by SMillerDev — APPROVED** [review]
Thanks @pete-woods  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
