### PR TITLE
libressl 2.4.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
We've moved onto tracking the stable rather than unstable branch, so this PR is wrong 😉.

**Comment by ilovezfs** [comment]
Um, ok …
Well, at least I know the code in https://github.com/Homebrew/brew/pull/318 works.

**Comment by DomT4** [comment]
😄. I'll chuck a note in the formula because I'm sure this'll happen a few times. The versioning scheme isn't massively clear.

**Comment by ilovezfs** [comment]
@DomT4 Even better fix `brew livecheck` so it doesn't report this as an update available ;)

**Pull request closed without merging**
