### PR TITLE
amazon-ecs-cli 0.3.1

### PR DESCRIPTION
**Pull request by ilovezfs**
- remove unnecessary Language::Go.stage_deps
- run make test
- clean up the formula

### CODE REVIEW

**Comment by DomT4** [comment]
Not sure what's going on with this formula.

I can't see a `vendor` or `godep` folder upstream, but this formula has no `go_resource`s but does have `Language::Go.stage_deps resources, buildpath/"src"` and the consequent `require`.

**Comment by ilovezfs** [comment]
It has always been that way apparently: https://github.com/Homebrew/legacy-homebrew/pull/45053

@DomT4 I wonder if we should make this an error not a warning: 
```
Warning: tried to stage empty resources array
```
When is that ever acceptable?

**Comment by DomT4** [comment]
It should probably be a hard `raise` when `HOMEBREW_DEVELOPER` is set & a warning (as currently) otherwise.

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed.

**Comment by DomT4** [comment]
Yeah, the vendoring system is there, I just missed it because it's nested. There's a new new version out, above this one, but that aside 👍.

**Pull request closed without merging**
