### PR TITLE
vault 0.11.4

### PR DESCRIPTION
**Pull request by igas**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by igas** [comment]
Hi @fxcoudert, what should I do? Should I keep this MR and wait for `safe` to update compatibility with new vault version?

**Comment by igas** [comment]
I bumped safe in this PR https://github.com/Homebrew/homebrew-core/pull/32688
I'll rebase when it'll be merged

**Comment by fxcoudert** [comment]
@igas safe is herded. But this formula does not depend on safe…

PS: only 1.38% of installs use the `--with-dynamic` option, can we remove it please? See #31510 for rationale

**Comment by igas** [comment]
@fxcoudert yeah, it's the other way around, I think safe failed with the new version of vault if I read CI log correctly. I rebased and pushed. Please also check diff if I understood you correctly about flag.

**Comment by fxcoudert** [comment]
The flag change is OK.
But the `safe` test still fails:

```
!! Unable to generate a new root token: token length / one-time password length mismatch (24/16)
shutting down the Vault...
Error: safe: failed
```

**Comment by DrStrangepork** [comment]
What is the status of this upgrade?

**Comment by igas** [comment]
Hi @DrStrangepork,

I think vault update is ok, but test on `safe` package fails, unfortunately, I don't know much about it, I tried to update its version but it did not help.

**Comment by igas** [comment]
Hi @hakamadare, could you please assist with `safe` formula test related to vault update?

**Comment by DrStrangepork** [comment]
Where is `safe` coming into play here? I don't see it in the code

**Comment by igas** [comment]
@DrStrangepork it's a dependency that starts to fail with the upgrade. Check out Jenkins output.

**Comment by DrStrangepork** [comment]
It doesn't appear that the Jenkins job is online anymore. All I see is a 404

HTTP ERROR 404
Problem accessing /job/Homebrew%20Core%20Pull%20Requests/31546/. Reason:

    Not Found

**Comment by fxcoudert** [comment]
@DrStrangepork when vault is update to this latest version, we test `safe` (because it depends on `vault`, so we want to make sure it still runs). After the `vault` update, our `safe` test fails with the error message here: 
https://github.com/Homebrew/homebrew-core/pull/32650#issuecomment-426915750

@BrewTestBot test this please (will recreate a Jenkins output)

**Comment by DrStrangepork** [comment]
It is specifically the `length mismatch (24/16)` that concerns me, as I have run into this problem as well as of Vault 0.11.\*. Makes me think that either `safe` doesn't work nicely with 0.11.\* or the test hasn't been updated to match updates to safe or Vault. I can't confirm those suspicions right or wrong, because I can't see the Jenkins output nor do I see where the `safe` test is actually occurring. I'd like to help with this, because I use Vault every day.

**Comment by commitay** [comment]
@fxcoudert as `vault` is reasonably popular I'm inclined to ship this anyway. IIRC `vault` often has breaking changes in minor/patch versions.

```
install events in the last 30 days
================================================================================
1 | vault                                                      | 3,777 |  98.10%
2 | vault --with-dynamic                                       |    60 |   1.56%
3 | vault --HEAD                                               |    13 |   0.34%
================================================================================
Total                                                          | 3,850 |    100%
================================================================================

install events in the last 30 days
================================================================================
1 | safe                                                          | 55 | 100.00%
================================================================================
```

**Comment by fxcoudert** [comment]
Let's just make sure an issue is opened with safe's upstream: https://github.com/starkandwayne/safe/issues so they are aware

**Comment by DrStrangepork** [comment]
FWIW, I have a good suspicion that Hashicorp is going to announce Vault 1.0 at HashiConf this week, and that should put an end to the breaking changes in minor/patch versions issue.

**Comment by DrStrangepork** [comment]
https://github.com/starkandwayne/safe/releases/tag/v0.9.7
The Improvements and Backend Changes sections sound like potential causes for the issues here.

**Comment by jhunt** [comment]
If we remove the `safe` formula in #33268, the upgrade to Vault 0.11.3 can proceed.

**Comment by igas** [comment]
Looks like @DrStrangepork was right and we have vault 1.0 beta now. I'll bump this MR to 0.11.4 meanwhile.

**Comment by igas** [comment]
@commitay should I add `1.0.0-beta1` as a `devel`? If so could you please point out for an example, because I could not find any in https://github.com/Homebrew/homebrew-core.

**Comment by commitay** [comment]
No, we recently removed devel specs from `homebrew/core`. https://github.com/Homebrew/brew/pull/5086

**Comment by igas** [comment]
safe 0.9.8 and vault 0.11.4 same issue https://github.com/starkandwayne/safe/issues/171

**Comment by fxcoudert** [comment]
> as vault is reasonably popular I'm inclined to ship this anyway

Agreed. `vault` has many more users than `safe`, so let's not delay this.

**Pull request closed without merging**
