### PR TITLE
qt: add devel 5.12.0-beta2

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Why is the pc-files patch not needed for devel? If it has been reverted in upstream, can you give a link please?

**Comment by yurikoles** [comment]
https://github.com/Homebrew/formula-patches/pull/254

**Comment by yurikoles** [comment]
@fxcoudert could you please promote or merge my new pc files patch for qt-5.12?

**Comment by fxcoudert** [comment]
@yurikoles merged

**Comment by fxcoudert** [comment]
@yurikoles then I don't understand how you came up with the patch at 
https://github.com/Homebrew/formula-patches/pull/254 if it was already applied?

**Comment by yurikoles** [comment]
@fxcoudert it was merged after beta1, besides commit date.

**Pull request merged**
