### PR TITLE
docker-cloud 1.0.8

### PR DESCRIPTION
**Pull request by mkjaer**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Review by fxcoudert — DISMISSED** [review]
Update all resources, and in particular `python-dockercloud`:

```
pkg_resources.DistributionNotFound: The 'python-dockercloud<2,>=1.0.11' distribution was not found and is required by docker-cloud
```

**Comment by mkjaer** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@mkjaer thanks for the update @mkjaer :tada:

**Pull request closed without merging**
