### PR TITLE
cryfs 0.10.3

### PR DESCRIPTION
**Pull request by smessmer**

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks for your PR, @smessmer. This formula is deprecated since it uses mac/osxfuse:

https://github.com/Homebrew/homebrew-core/blob/d21879ed8a30af9ecc6430ffb4b0ea99d65fdfbf/Formula/cryfs.rb#L25-L28

We no longer have mac/osxfuse installed in CI. This means that bottles for this formula were not built, and merging this will make it quite hard for users to install the existing bottles.

**Comment by smessmer** [comment]
ok. What's the recommended way to install software that depends on osxfuse through brew?

**Comment by SMillerDev** [comment]
> ok. What's the recommended way to install software that depends on osxfuse through brew? Install osxfuse first manually, and then the formula without the dependency?

Maintain a personal tap with the software with the osxfuse dependency, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by carlocab** [comment]
This formula has now been disabled.

**Pull request closed without merging**
