### PR TITLE
apache-pulsar 2.9.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by zbentley** [comment]
@SMillerDev @chenrui333 could you explain why this change was made? I was under the impression that the highest supported version of Pulsar is currently 2.8.1; I thought the 2.9* family are pre-release and still under development. The main Apache Pulsar website only references 2.8.1 and below for download.

**Comment by SMillerDev** [comment]
Because if there is a download from the official location I don't have a reason to doubt if upstream wants this released or not. https://archive.apache.org/dist/pulsar/ also doesn't mention that it's a pre-release.

Basically, it was too much effort to find out it was a pre-release.

> The main Apache Pulsar website only references 2.8.1 and below for download.

Upstream websites lacking behind is pretty common and unfortunately not a great indicator for pre-releases.

---

If you feel this should be reverted you can always make a pull request though

**Comment by zbentley** [comment]
> If you feel this should be reverted you can always make a pull request though

Thanks, I'll check with upstream and submit a PR if those versions are not ready. If that turns out to be the case, is there a way to flag a given formula/version as "don't upgrade this, even if there are semver-higher numbers available in the containing folder"?

**Comment by zbentley** [comment]
Update on above: per https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1640023614409600, those releases are intended/stable. This PR does not need to be reverted.

**Pull request closed without merging**
