### PR TITLE
protobuf-swift 2.4.4

### PR DESCRIPTION
**Pull request by alexeyxo**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by ilovezfs** [comment]
@alexeyxo I'm a little confused by the test here. Isn't `protoc` a `protobuf` formula binary, not what's installed by `protobuf-swift`?

**Comment by alexeyxo** [comment]
"protobuf-swift" it's a plugin for protoc, like a ```protobuf-c``` and etc.  After Install ```protoc``` has a support generate code for swift language.

**Comment by ilovezfs** [comment]
@alexeyxo Would it be possible to compile the run the output Test.proto.swift to make sure it works, or if not, perhaps just verify the output file matches some substring we expect to be in it?

**Comment by alexeyxo** [comment]
For compile output file needed swift compiler and runtime library. If ```protoc``` can compile ```*.proto``` with ```--swift_out``` flag, then plugin work fine.

**Comment by ilovezfs** [comment]
@alexeyxo OK, if you're happy, I'm happy.

**Comment by ilovezfs** [comment]
@alexeyxo Thanks for keeping your software up to date on Homebrew! :100: We really appreciate upstreams that are proactive.

**Pull request closed without merging**
