### PR TITLE
wangle 2021.02.22.00

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Rylan12** [comment]
@dtrodrigues does this need to be done in sync with `folly` and `fizz`? I often see them updated together, so I'm just not sure. If so, it's probably a good idea to add an audit or (at least) a comment indicating as such.

**Comment by chenrui333** [comment]
yeah, all three can be updated at the same time.

**Comment by dtrodrigues** [comment]
They don't always need to be updated at the same time, but occasionally rely on features from the latest version of other ones in the set.

**Comment by dtrodrigues** [comment]
Since folly isn't building on 10.14, trying just wangle and fizz to see if they work for this week's release.

**Comment by dtrodrigues** [comment]
And fizz now is failing to build since it requires changes only in the version of folly, so it's not. We're back to just building wangle like you did in the first place :)

**Review by dtrodrigues — APPROVED** [review]

**Pull request closed without merging**
