### PR TITLE
gitleaks 2.0.0

### PR DESCRIPTION
**Pull request by zricethezav**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
I thought it has been upgraded in https://github.com/Homebrew/homebrew-core/pull/39581 ?

**Comment by zricethezav** [comment]
@chenrui333 closed that PR due to git difficulties

**Comment by chenrui333** [comment]
Ah, I see. My bad.

**Comment by fxcoudert** [comment]
This does not apply cleanly. Please include a single commit on top of current, clean master.

**Pull request closed without merging**
