### PR TITLE
cargo-edit: fix test

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
> Error: No available formula or cask with the name "cmake".

???

**Comment by SMillerDev** [comment]
Why does github say it timed out after 72 hours? :confused:

**Comment by carlocab** [comment]
Time dilation?

**Comment by SMillerDev** [comment]
Christopher Nolan messing with our CI?

**Comment by carlocab** [comment]
Ghosts?

**Review by carlocab — APPROVED** [review]

**Pull request merged**
