### PR TITLE
ncdu 2.2.2

### PR DESCRIPTION
**Pull request by owine**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
bottle failure on 11

```
  ==> Bottling ncdu--2.2.2.big_sur.bottle.tar.gz...
  Error: Failed changing install name in /usr/local/Cellar/ncdu/2.2.2/bin/ncdu
    from /usr/local/opt/ncurses/lib/libncursesw.6.dylib
      to @@HOMEBREW_PREFIX@@/opt/ncurses/lib/libncursesw.6.dylib
  Error: Updated load commands do not fit in the header of /usr/local/Cellar/ncdu/2.2.2/bin/ncdu. /usr/local/Cellar/ncdu/2.2.2/bin/ncdu needs to be relinked, possibly 
```

**Comment by carlocab** [comment]
Needs `-headerpad_max_install_names`. Might be something similar to what we do in `zig`. Likely a patch that needs to be upstreamed.

**Comment by SMillerDev** [comment]
That seems to have fixed it

**Comment by carlocab** [comment]
Yes. Except I can't access my account at https://code.blicky.net/yorhel/ncdu/, and I'm not getting the password reset email.

I'll send Yorhel an email later, unless someone else wants to open a PR.

**Comment by p-linnane** [comment]
`12` got stuck launching. Rerunning.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
