### PR TITLE
harfbuzz 2.6.7

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
I am not sure what happened here and in my PR's for ImageMagick -- did I do something wrong?

**Comment by issyl0** [comment]
This PR looks fine! 💪 I've re-queued the checks as we were doing some CI maintenance earlier.

**Comment by miccal** [comment]
Thank you @issyl0.

**Comment by miccal** [comment]
Same error as in https://github.com/Homebrew/homebrew-core/pull/55731, which I thought may be fixed by https://github.com/Homebrew/homebrew-core/pull/55912.

**Comment by SMillerDev** [comment]
Could you rebase?

**Comment by miccal** [comment]
`genometools` test still fails.

**Comment by miccal** [comment]
@SMillerDev I have given `genometools` a revision bump which has fixed its failing test. The error now is:
```
==> FAILED
Error: 1 problem in 1 formula detected
harfbuzz:
  * The URL https://wiki.freedesktop.org/www/Software/HarfBuzz/ is not reachable
```
and I notice form this page that:

> IMPORTANT: 2020-06-05: We have moved to github.com/harfbuzz/harfbuzz. For latest releases, filing bug reports, etc, please go there. This page is kept for historical content that will eventually be ported to the Github space.

Would you like me to change the `homepage` for `harfbuzz` from `https://wiki.freedesktop.org/www/Software/HarfBuzz/` to `https://github.com/harfbuzz/harfbuzz`?

**Comment by SMillerDev** [comment]
Sounds good to me

**Comment by miccal** [comment]
@SMillerDev done, thank you.

**Review by chenrui333 — APPROVED** [review]
💯

**Comment by chenrui333** [comment]
Thanks @miccal!!

**Pull request closed without merging**
