### PR TITLE
octave: fix opengl-partial-update bug

### LINKED ISSUE #170616: Octave 9.1.0 opengl bug interacting with qt6-6.7.0
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
I do not use homebrew.  This is an attempt at getting an upstream patch in to fix crashes for homebrew users.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I can't seem to get your system to accept my patch.  Here is my best go at it.  In the following code block the patch to octave.rc should (I hope) download a patch from savannah.gnu.org and apply it to your source tree prior to build.  This should fix the bug with octave 9.1.0 interacting with qt6-6.7.0.

```
diff --git a/Formula/o/octave.rb b/Formula/o/octave.rb
index 60f8aea563d..c11a87df330 100644
--- a/Formula/o/octave.rb
+++ b/Formula/o/octave.rb
@@ -81,6 +81,12 @@ class Octave < Formula
 
   fails_with gcc: "5"
 
+  # Fix opengl-partial-update bug causing crashes on figure() and plot().
+  patch do
+    url "https://file.savannah.gnu.org/file/bug65605-qt6-opengl-partial-update.patch?file_id=55978"
+    sha256 "4f258a90dcb6b5d7f1af466dfc2b2fd6413968070ab224e4b368d355ec257ca9"
+  end
+
   def install
     # Default configuration passes all linker flags to mkoctfile, to be
     # inserted into every oct/mex build. This is unnecessary and can cause
```

### What happened (include all command output)?

I got a report from a homebrew user in the octave mailing lists saying his build crashes.

### What did you expect to happen?

Opening octave and running figure() will cause a crash.  With this patch applied a figure window will open instead.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
No instructions here.  Just trying to help out.
```

### PR DESCRIPTION
**Pull request by chrisjohgorman**
Please test this.  I don't have a homebrew system and this is my first wack at ruby code.  I copied the patch command from ocaml@4.rb, updated the sha256sum and linked in the patch from savannah.gnu.org.

Hope this helps.

Chris

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

fixes https://github.com/Homebrew/homebrew-core/issues/170616

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
src/octave-svgconvert.cc:42:10: fatal error: 'QApplication' file not found
```

Seems like it fails to build now

**Comment by chrisjohgorman** [comment]
Not sure here.  I only touch libgui/graphics/GLCanvas.cc with the patch.  I don't know why this isn't building.  Does it build without the upstream patch form Markus?

**Comment by chrisjohgorman** [comment]
Could this be due to the fact that I didn't update the revision 2 to revision 3?

**Comment by carlocab** [comment]
> Not sure here. I only touch libgui/graphics/GLCanvas.cc with the patch. I don't know why this isn't building. Does it build without the upstream patch form Markus?

It should build, but let's see...

**Comment by carlocab** [comment]
Build failure and OpenGL bug will be fixed in #170657.

Thanks @chrisjohgorman!

**Comment by chrisjohgorman** [comment]
Hi Carlo,

Thank you for taking this over and committing it.

All the best,

Chris

**Comment by carlocab** [comment]
No problem. Thanks for taking the time to trying to get this fixed!

**Comment by chrisjohgorman** [comment]
Glad to help.  All the best.

**Comment by chrisjohgorman** [comment]
Sorry for the extra email.  But I thought you might like to know that I
have a report of figure() and plot() working now with octave from homebrew.

Take care,

Chris

**Pull request closed without merging**
