### PR TITLE
kops 1.24.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
>   fatal: not a git repository (or any of the parent directories): .git

**Comment by cho-m** [comment]
The failure happens later in `cp`:
```
  cp /private/tmp/kops-20220708-87591-v9s6tc/kops-1.24.0/src/k8s.io/kops/.build/dist/darwin/arm64/kops* 
  usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
         cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
```

It looks like Makefile is now trying to install into `GOBIN` which is probably not set by default https://github.com/kubernetes/kops/blob/v1.24.0/Makefile#L94
```
	cp ${DIST}/$(shell go env GOOS)/$(shell go env GOARCH)/kops* $(shell go env GOBIN)
```

**Comment by mostafahussein** [comment]
Hello,
Are you going to fix this? or can i try and fix it and then submit a PR for it?
Thank you

**Comment by chenrui333** [comment]
#106882

**Pull request closed without merging**
