### PR TITLE
svt-av1: fix sha256

### PR DESCRIPTION
**Pull request by sizlo**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@sizlo can you also raise an upstream issue to confirm this checksum change behavior? Thanks!

**Comment by sizlo** [comment]
> @sizlo can you also raise an upstream issue to confirm this checksum change behavior? Thanks!

Upstream issue raised here
https://gitlab.com/AOMediaCodec/SVT-AV1/-/issues/2136

**Comment by cho-m** [comment]
Most likely related to https://gitlab.com/AOMediaCodec/SVT-AV1/-/merge_requests/2135#note_1696774281 but can wait for upstream confirmation.

**Comment by mbologna** [comment]
Confirmed upstream: https://gitlab.com/AOMediaCodec/SVT-AV1/-/issues/2136#note_1700787871

**Review by SMillerDev — APPROVED** [review]

**Comment by sizlo** [comment]
Do we need to fix the CI failures about opening an upstream issue before this PR can be merged, or can someone manually merge in the current state?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> Do we need to fix the CI failures about opening an upstream issue before this PR can be merged, or can someone manually merge in the current state?

yeah, we can just merge as it is per the upstream confirmation. As for the CI failure, it is just a audit failure wrt the checksum mismatch

**Comment by chenrui333** [comment]
@sizlo thanks for your first contribution to homebrew-core!

**Pull request merged**
