### PR TITLE
Use Ubuntu 22.04 to build bottles

### PR DESCRIPTION
**Pull request by sjackman**
Use Ubuntu 22.04 rather than Ubuntu 16.04 to build bottles. This PR needs to be merged after merging PR https://github.com/Homebrew/brew/pull/13733 and tagging Homebrew 3.6.0.

- https://github.com/Homebrew/brew/pull/13733
- https://github.com/Homebrew/brew/issues/13619

-----

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Comment by danielnachun** [comment]
Should we add the changes to swap the symlinks to `$HOMEBREW_PREFIX/lib` from `gcc@5` to `gcc@11` here too?  Or is that better in a separate PR?

**Review by MikeMcQuaid — DISMISSED** [review]

**Comment by sjackman** [comment]
> Should we add the changes to swap the symlinks to `$HOMEBREW_PREFIX/lib` from `gcc@5` to `gcc@11` here too?  Or is that better in a separate PR?

Similarly to how we bumped the brewed Glibc version before building bottles with that Glibc version, perhaps we can also bump the preferred brewed GCC version before building bottles with that GCC version. (https://github.com/Homebrew/brew/issues/13619#issuecomment-1226044992)

I'd like to have a stable release of Homebrew that migrates our users to `glibc` 2.35 and `gcc@11` before we move our bottling infrastructure to Ubuntu 22.04. (https://github.com/Homebrew/brew/issues/13619#issuecomment-1226395765).

I've those two commits to their own PR
- https://github.com/Homebrew/homebrew-core/pull/108816

**Comment by carlocab** [comment]
I think once the `ubuntu22.04` image is available we can test a build by adding a formula to this PR. This can be done before the tag goes out.

**Comment by carlocab** [comment]
> CI is failing 😭

I think that's because there is no `ghcr.io/homebrew/ubuntu22.04:master` yet.

**Comment by MikeMcQuaid** [comment]
> I think that's because there is no `ghcr.io/homebrew/ubuntu22.04:master` yet.

Yeh. I'd suggest we do that before switching everything over and definitely before tagging.

**Comment by sjackman** [comment]
>> I think that's because there is no `ghcr.io/homebrew/ubuntu22.04:master` yet.

> Yeh. I'd suggest we do that before switching everything over and definitely before tagging.

See https://github.com/Homebrew/brew/pull/13733#issuecomment-1237203226

> - [ ] Merge PR https://github.com/Homebrew/brew/pull/13733
> - [ ] Rerun and merge PR https://github.com/Homebrew/homebrew-core/pull/108590

**Comment by MikeMcQuaid** [comment]
@sjackman it's finding the container here now but still failing to run so: holding off tagging until this PR is green.

https://github.com/Homebrew/homebrew-core/runs/8209428299?check_suite_focus=true#step:3:22

> we can test a build by adding a formula to this PR

This would be good to do here, too.

**Comment by carlocab** [comment]
I think it's `ubuntu22.04`. As in, GitHub's `ubuntu22.04`.

**Comment by carlocab** [comment]
Yea, the contents of `/proc/1/cgroup` are no longer what we expect it to be on `ubuntu-22.04`. They still are on `ubuntu-latest`. That will need fixing at https://github.com/Homebrew/actions/blob/3db14755156ae235e90a898e546323186322a02c/setup-homebrew/main.sh#L50

**Review by MikeMcQuaid — DISMISSED** [review]
Working now but would be good to push a bottle test commit in here.

**Comment by carlocab** [comment]
In the Homebrew `ubuntu22.04` container:
```
linuxbrew@9d1860ec5ecd:/tmp/colima$ brew install ./hello--2.12.1.x86_64_linux.bottle.1.tar.gz
==> Pouring hello--2.12.1.x86_64_linux.bottle.1.tar.gz
Warning: "/home/linuxbrew/.linuxbrew/bin" is not in your PATH.
You can amend this by altering your ~/.profile file.
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/hello/2.12.1: 55 files, 658.9KB
```
Not sure if that's something we want to fix.

Will report back how `brew test hello` works shortly -- testing `16.04` simultaneously and I'm waiting for it to install `glibc` and `gcc@11`.

**Comment by carlocab** [comment]
Yea, the bottle seems to work.

**Review by carlocab — DISMISSED** [review]

**Review by SMillerDev — APPROVED** [review]

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by sjackman** [comment]
```console
$ brew install newrelic-cli
…
$ jq '{compiler} + (.built_on | {glibc_version})' ~/.linuxbrew/opt/newrelic-cli/INSTALL_RECEIPT.json      
{
  "compiler": "gcc-11",
  "glibc_version": "2.35"
}
```
👏 🥳 🚀

**Pull request merged**
