### PR TITLE
gobject-introspection 1.58.2

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
I agree that gtk should handle this case more gracefully but since this is very recent behaviour, and exclusively on High Sierra, I do wonder what configuration setting change on the corresponding build bot is responsible for these failures...

Anyway, this one is ready to merge in.

**Comment by tschoonj** [comment]
@Homebrew/maintainers Given the discussion in Homebrew/brew#5391... Could anyone with some understanding of Gerrit have a look at why these tests are failing on the High Sierra build machine?

Thanks!

**Comment by sjackman** [comment]
My best guess is that XQuartz needs to be installed, or the X server needs to be started.

**Comment by tschoonj** [comment]
I don't think that will work. This build of `gtk3` uses the Quartz backend exclusively and does not link against XQuartz' X11 libraries or use the X server in any way.

**Comment by tschoonj** [comment]
The new gtk+3 build has somehow resolved the High Sierra problems... ready to merge!

**Pull request closed without merging**
