### PR TITLE
fmt 10.0.0

### PR DESCRIPTION
**Pull request by FtZPetruska**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by FtZPetruska** [comment]
Rebased on master to include the spdlog patch needed for fmt 10.0.0 support (#130746)

**Comment by carlocab** [comment]
Other build failures need to be reported upstream and/or patched.

**Comment by FtZPetruska** [comment]
Here's an update:
- arrayfire: sort of confused by this one, build passes on master, but not on this PR. But the failure only happen at the end of a successful install:
  <details>
  <summary>Error log</summary>

  ```
  ==> Temporary files retained at:
  /tmp/arrayfire-20230513-27616-1a6wyk9
  Error: An exception occurred within a child process:
    NoMethodError: undefined method `header' for nil:NilClass
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/elftools-1.2.0/lib/elftools/dynamic.rb:115:in `str_offset'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/elftools-1.2.0/lib/elftools/dynamic.rb:174:in `call'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/elftools-1.2.0/lib/elftools/dynamic.rb:174:in `name'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/patcher.rb:214:in `map'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/patcher.rb:214:in `needed_'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/patcher.rb:67:in `needed'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:158:in `needed_libraries_using_patchelf_rb'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:153:in `needed_libraries'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:130:in `initialize'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:180:in `new'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:180:in `metadata'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:189:in `dynamically_linked_libraries'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:63:in `block in detect_cxx_stdlibs'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:59:in `each'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:59:in `detect_cxx_stdlibs'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:198:in `detect_stdlibs'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:179:in `block (3 levels) in install'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:498:in `with_env'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1335:in `block in brew'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2742:in `block (2 levels) in stage'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:498:in `with_env'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2741:in `block in stage'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:128:in `block (2 levels) in unpack'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/download_strategy.rb:118:in `chdir'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/download_strategy.rb:118:in `chdir'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/download_strategy.rb:105:in `stage'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:124:in `block in unpack'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:75:in `run'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:228:in `stage_resource'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:123:in `unpack'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:97:in `stage'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2721:in `stage'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1328:in `brew'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:133:in `block in install'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:498:in `with_env'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:128:in `install'
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:229:in `<main>'
  ```

  </details>
- bear, upstream patch already available https://github.com/Homebrew/homebrew-core/pull/130921
- cherrytree, patch submitted upstream https://github.com/giuspen/cherrytree/pull/2274, https://github.com/Homebrew/homebrew-core/pull/130923
- clip, upstream already has a fix that applies to v0.7 https://github.com/Homebrew/homebrew-core/pull/130922
- easyrpg-player, issue reported upstream https://github.com/EasyRPG/Player/issues/3002
- mkvtoolnix, upstream patch already available https://github.com/Homebrew/homebrew-core/pull/130928
- mdp, SSL error
- vcpkg, patch submitted upstream https://github.com/microsoft/vcpkg-tool/pull/1063
- watchman, issue reported upstream https://github.com/facebook/watchman/issues/1140

**Comment by FtZPetruska** [comment]
Rebased on master to include the fixes for:
- bear
- cherrytree
- clip
- easyrpg-player
- mkvtoolnix

And fix the merge conflicts with clip.

**Comment by carlocab** [comment]
Outstanding failures are `arrayfire` (Linux-only), `vcpkg`, `watchman`, and `cryfs` (needs `revision` bump).

It looks like you have a patch for `vcpkg`, so I guess that leaves `arrayfire` and `watchman`. Will look into what's going on with `arrayfire`.

**Comment by FtZPetruska** [comment]
> It looks like you have a patch for `vcpkg`

Regarding how to add this patch, since it removes compatibility with fmt 9.x, should it be added to this PR directly? As making it a standalone PR is guaranteed to break in CI.

> Will look into what's going on with arrayfire.

Thank you, I greatly appreciate your help!

For reference, I already tried to apply this upstream patch https://github.com/arrayfire/arrayfire/commit/e9432c2788ab6a4bbe4af036224d4572c15c1e77 as it mentioned adding formatters, but it did not seem to fix the issue. Then again, the error itself is quite obscure to me.

**Comment by carlocab** [comment]
Here's a backtrace for `arrayfire`:
```
Error: An exception occurred within a child process:
  NoMethodError: undefined method `header' for nil:NilClass
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/elftools-1.2.0/lib/elftools/dynamic.rb:115:in `str_offset'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/elftools-1.2.0/lib/elftools/dynamic.rb:174:in `call'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/elftools-1.2.0/lib/elftools/dynamic.rb:174:in `name'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/patcher.rb:214:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/patcher.rb:214:in `needed_'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/patcher.rb:67:in `needed'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:158:in `needed_libraries_using_patchelf_rb'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:153:in `needed_libraries'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:130:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:180:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:180:in `metadata'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:189:in `dynamically_linked_libraries'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:63:in `block in detect_cxx_stdlibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:59:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:59:in `detect_cxx_stdlibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:198:in `detect_stdlibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:179:in `block (3 levels) in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:498:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1342:in `block in brew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2739:in `block (2 levels) in stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:498:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2738:in `block in stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:128:in `block (2 levels) in unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/download_strategy.rb:118:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/download_strategy.rb:118:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/download_strategy.rb:105:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:124:in `block in unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:75:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:228:in `stage_resource'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:123:in `unpack'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:97:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2718:in `stage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1335:in `brew'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:133:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:498:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:128:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:229:in `<main>'
```
Interestingly, it fails only after updating to `fmt` 10. Building from current `master` (1b6e82a81da1fbd31b51b109d0bc89c3f7334f0a) works fine.

It looks like a problem with `patchelf.rb`, which is a little above my pay grade. CC @Bo98 @Homebrew/linux for ideas.

**Comment by carlocab** [comment]
> > It looks like you have a patch for `vcpkg`
> 
> Regarding how to add this patch, since it removes compatibility with fmt 9.x, should it be added to this PR directly? As making it a standalone PR is guaranteed to break in CI.

Yes, feel free to add it directly here. I also suggest ignoring the `arrayfire` failure on Linux for now, as I don't think it's worth blocking this update for it. That should leave only `watchman` that needs fixing (assuming `cryfs` doesn't also need a patch).

**Comment by FtZPetruska** [comment]
Bumped the revision on `cryfs` and added an explicit dependency on `fmt` as it links to it (previously pulled transitively by `spdlog`).

Added the patch on `vcpkg`.

I'll see if I have time tomorrow to start figuring out a patch for `watchman`.

**Comment by carlocab** [comment]
`mpd` still failed, unfortunately.

**Comment by FtZPetruska** [comment]
> `mpd` still failed, unfortunately.
> 
> Related: [MusicPlayerDaemon/MPD#1807](https://github.com/MusicPlayerDaemon/MPD/issues/1807)

Ah, I had only seen the initial post when I made the MPD PR the other day, and had wrongly assumed this patch (https://github.com/MusicPlayerDaemon/MPD/commit/f869593ac8913e52c711e974257bd6dc0d5dbf26) would be enough to fix the fmt 10 issues on the latest release.

**Comment by FtZPetruska** [comment]
Since I could not find any roadmap or up-to-date milestones, I opened an issue about their plans for the next release.(https://github.com/MusicPlayerDaemon/MPD/issues/1813)

Upstream seems to be working towards v0.24, so it may take a while, as such I also offered to provide a patch adding fmt 10 support for the v0.23.x branch.

**Comment by FtZPetruska** [comment]
Changed up the build commands for `fmt` in the latest rebase to only use `cmake` commands instead of invoking `make` and not run the `clean` target.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Thanks for your work here, @FtZPetruska!

**Comment by chenrui333** [comment]
@FtZPetruska Great work! 💯

**Pull request merged**
