### PR TITLE
c-ares: use CMake

### PR DESCRIPTION
**Pull request by kou**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CMake based build installs CMake related files such as c-ares-config.cmake too.

### CODE REVIEW

**Comment by kou** [comment]
There are "Incompatible library version: XXX requires version 7.0.0 or later, but libcares.2.dylib provides version 2.0.0" dyld failures only on macOS 10.13:

```text
brew test --retry --verbose curl-openssl
brew test --retry --verbose fb-client
brew test --retry --verbose grpc
brew test --retry --verbose libexosip
brew test --retry --verbose nghttp2
brew install php
brew install php@7.2
brew install php@7.3
brew test --retry --verbose shadowsocks-libev
brew test --retry --verbose termshark
brew test --retry --verbose wireshark
```

Can we rebuild them by bumping revision of them?

**Comment by SMillerDev** [comment]
Yes, you can use https://docs.brew.sh/Manpage#bump-revision-options-formula-formula-

**Comment by kou** [comment]
Thanks. I didn't know the convenience `bump-revision` command.
I've bumped revisions of them.

**Comment by SMillerDev** [comment]
Please keep one commit per formula (as the revision command will do)

**Comment by kou** [comment]
OK. Done.

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
I will make some semantic changes for the commits now. One sec

**Comment by kou** [comment]
Thanks. Sorry for missing `for c-ares` in commit messages.

All checks have passed. Can we merge this?

**Review by SMillerDev — DISMISSED** [review]
Thanks @kou  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by SMillerDev** [comment]
@Homebrew/core  can someone check this? I don't have much time right now

**Comment by dawidd6** [comment]
@SMillerDev done, seems like GitHub has some troubles with transfers (?) recently.

**Pull request closed without merging**
