### PR TITLE
openssl@1.1 1.1.0e

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alex** [comment]
```
==> brew fetch --retry fdroidserver
==> brew install fdroidserver
==> brew linkage --test fdroidserver
==> FAILED
Missing libraries:
  /usr/local/opt/little-cms2/lib/liblcms2.2.dylib
==> brew test --verbose fdroidserver
```

Don't really understand what that's about, or how to fix?

**Comment by ilovezfs** [comment]
@alex looks like some undesirable opportunistic linkage that snuck in.

**Comment by alex** [comment]
@ilovezfs meaning `depend_on "little-cms2"` should be added to the fdroidserver formula?

**Comment by ilovezfs** [comment]
@alex we could solve it that way, but the right answer is to figure out how to block it from ever linking against it in the first place.

**Comment by ilovezfs** [comment]
```
/usr/local/opt/little-cms2/lib/liblcms2.2.dylib
  libexec/lib/python3.6/site-packages/PIL/_imagingcms.cpython-36m-darwin.so
```

It's pillow that's doing it.

**Comment by ilovezfs** [comment]
@alex this will take care of it for now: https://github.com/Homebrew/homebrew-core/pull/10035

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by alex** [comment]
thanks

**Comment by ilovezfs** [comment]
Shipped! Thanks for the PR :closed_lock_with_key:

**Pull request closed without merging**
