### PR TITLE
openldap 2.4.45

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
I'm really not eager to resume the transition to openssl@1.1. `wget` is a special case.

**Comment by DomT4** [comment]
I mean, with respect, we're going to have to do it at some point. 1.0.2 may be the LTS branch but 1.1.x is just a _better_ OpenSSL, not least because it isn't saddled with the extremely-questionable SSLv3 & `zlib` compression, but also because it's the only place you will get _new_ features for over the next year+.

Frankly, the OpenSSL transition isn't going to get _easier_ as time goes on; we use OpenSSL so widely & in so many projects that haven't seen an update for years that's unlikely to change. At some point we start letting the oldest, slowest, least active projects hold back Homebrew from more routinely shipping a more secure, feature-rich OpenSSL.

You seem to have deleted your comment before [my comment here](https://github.com/Homebrew/homebrew-core/pull/14000#issuecomment-304563589) on the `wget` PR (❓) but you did [literally create & link to this list](https://gist.github.com/ilovezfs/2158e097790a7c7907f0b5ff4245eed3) of things that could be bumped to `openssl@1.1` without messing with the dependency situation.

Obviously here that's not quite the case, but I checked `brew.sh/analytics` and found no popular trace of anyone using the `openldap` option with `apr-util`.

**Comment by ilovezfs** [comment]
>You seem to have deleted your comment before my comment here on the wget PR (:question:) but you did literally create & link to this list of things that could be bumped to openssl@1.1 without messing with the dependency situation.

Yeah, Tim had been interested in such a list so I made one. I did not mean for it to trigger a bunch of PRs. I still think this needs to be done in one shot, not one at a time. I'm willing to make occasional exceptions when a user requests it for a very good reason (cf. wget and ldns), but I don't think we should be doing these one at a time just because this or that happens to build.

**Comment by DomT4** [comment]
> I did not mean for it to trigger a bunch of PRs. 

It hasn't, really. Every PR I've filed on this to date has been caused by the need to version bump. I think what you're asking in terms of doing everything at once is basically impossible unless you intend to remove 100+ formulae from Homebrew permanently. These special exceptions are going to build up and build up and create a confusing picture as to when it's desired.

`curl` for example, presumably will want to be a special exception once TLSv1.3 lands, which means all the `curl` dependencies will need to also be special exceptions, as well as anything that links to `curl` because we don't enforce the vanilla installation on people if they have an option-used version installed locally and the dependency simply says `depends_on "curl"`.

I really think we're making a mistake deliberately mainstreaming an `openssl` formula which we have said many times should lose SSLv3 & compression but nobody wants to revision bump 350 formulae to do it.

This choice isn't going to become less painful in time I fear. Given 1.0.2 is only LTS until 2019 we have two & a half years until this becomes urgent very quickly, at which point you will _have_ to transition or kill stuff because 1.0.2 is about to slide into being unsupported.

I appreciate things are a bit _"two and a half years & you're concerned now?"_ but it has been around two & a half years since I removed SSLv2 from Homebrew's `openssl` and we've gone from 50 formulae using our `openssl` to ~350+. It would've been so much easier to remove SSLv3 at that point in time but we punted and now we're stuck with it likely forever on the `openssl` formula.

**Comment by ilovezfs** [comment]
Please recast these as simple version bump PRs. I'm really not interested in debating openssl* at this point.

**Comment by DomT4** [comment]
As you wish, but don't glare at me if 2019 swings around & things pan out as I expect they will.

**Comment by DomT4** [comment]
A belated apology, my tone was overly harsh. It's a subject I foresee pain on for Homebrew and I guess I haven't shaken off that protective instinct over the project even after all this time. I shouldn't have snapped at you about it, despite our difference in opinion.

**Pull request closed without merging**
