### PR TITLE
bandwhich 0.12.0

### PR DESCRIPTION
**Pull request by smorimoto**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
Thanks @imbsky!!

**Comment by imbsky** [comment]
✌️

**Comment by chenrui333** [comment]
CI hiccup on the merge.

@BrewTestBot test this please

**Comment by imbsky** [comment]
Oh the test passed 👏

**Pull request closed without merging**
