### PR TITLE
glibc@2.13: disable.

### PR DESCRIPTION
**Pull request by carlocab**
We don't use this for anything anymore.

### CODE REVIEW

**Comment by danielnachun** [comment]
We have to move this to the portable-ruby repo before we can disable it here, or it will break that workflow.  @Bo98 should we keep the same name?

**Comment by Bo98** [comment]
> should we keep the same name?

Possibly, yeah. I don't think `portable-glibc` would be an accurate name.

**Comment by danielnachun** [comment]
> > should we keep the same name?
> 
> Possibly, yeah. I don't think `portable-glibc` would be an accurate name, nor will it necessarily be subclassing `PortableFormula`.

Okay that's what I was thinking too.  I will move the formula over to `portable-ruby` and we can get it merged there first before disabling/deprecating here.

**Comment by danielnachun** [comment]
Are we okay with disabling this immediately or should we follow the standard 3 month deprecation period?  I don't feel strongly either way.

**Comment by Bo98** [comment]
> Are we okay with disabling this immediately or should we follow the standard 3 month deprecation period? I don't feel strongly either way.

I'd go for outright removal.

**Pull request closed without merging**
