### PR TITLE
proof-general 4.5

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==>/opt/homebrew/Cellar/proof-general/4.5/bin/proofgeneral --help
  Failed to execute: /opt/homebrew/Cellar/proof-general/4.5/bin/proofgeneral
  Error: proof-general: failed
  An exception occurred within a child process:
    BuildError: Failed executing: /opt/homebrew/Cellar/proof-general/4.5/bin/proofgeneral --help
```

**Comment by chenrui333** [comment]
the license should be actually GPL 3+ per [this commit](https://github.com/ProofGeneral/PG/commit/6c9c995507a0fb8be55491655557b40b4729e399).

- Also relates to https://github.com/ProofGeneral/PG/issues/198

**Comment by chenrui333** [comment]
As the release is not being finalized yet, we can merge this later.

**Comment by chenrui333** [comment]
```
$ tree /opt/homebrew/Cellar/proof-general/4.4_2/bin/
/opt/homebrew/Cellar/proof-general/4.4_2/bin/
├── coqtags
├── isartags
├── legotags
└── proofgeneral

$ tree /opt/homebrew/Cellar/proof-general/4.5/bin/
/opt/homebrew/Cellar/proof-general/4.5/bin/
└── coqtags
```

**Review by SMillerDev — APPROVED** [review]

**Comment by Porkepix** [comment]
> the license should be actually GPL 3+ per [this commit](https://github.com/ProofGeneral/PG/commit/6c9c995507a0fb8be55491655557b40b4729e399).
> 
>     * Also relates to [License of the package - consider move to GPL-3+ ProofGeneral/PG#198](https://github.com/ProofGeneral/PG/issues/198)

Well, that's the audit step on the first CI run which reported it should be `GPL-3.0` which it seems to have read from the repo.

**Pull request closed without merging**
