### PR TITLE
various formulae: remove golang requirement

### PR DESCRIPTION
**Pull request by eirinikos**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

These commits address the `brew audit` warning:
`require "language/go" is unnecessary unless using `go_resource`s`.

### CODE REVIEW

**Comment by DomT4** [comment]
Interestingly, I thought `fabio` should have died on installation here with:
```
Error: tried to stage empty Language::Go resources array
Error: Kernel.exit
```
But it didn't. Hmm.

**Comment by eirinikos** [comment]
> Interestingly, I thought `fabio` should have died on installation here with:
> 

> ```
> Error: tried to stage empty Language::Go resources array
> Error: Kernel.exit
> ```

> But it didn't. Hmm.
> 
> It does locally, and `brew tests` yesterday affirmed this was working as expected, so a touch confused here.

Hmm. Is it an option to remove `Language::Go.stage_deps resources, buildpath/"src"` from the `install` method?

If I understand correctly, then it looks like there are no `resource`s defined for `fabio`, so if that's correct, does `stage_deps` serve any purpose here? (I'm a little out of my depth here, so please feel free to let me know if I'm missing anything.)

**Comment by DomT4** [comment]
> Hmm. Is it an option to remove Language::Go.stage_deps resources, buildpath/"src" from the install method?

Yeah, this is more or less what the `odie` in [this commit](https://github.com/Homebrew/brew/commit/373d927e372825e13c0e9b32d556282580c42c27) was supposed to achieve, forcing formulae that went through CI to kill the line if it wasn't actually necessary. For some reason, in this PR, it didn't `odie` despite it staging no resources & behaving as expected locally by well, dying.

I'm just a little puzzled why that wasn't triggered here.

**Comment by DomT4** [comment]
Figured it out. I was being stupid & forgot for CI we do [this](https://github.com/Homebrew/brew/blob/f6dad377b63946d403df7ed755fb14426a33df31/Library/Homebrew/dev-cmd/test-bot.rb#L578-L584). We've buried away so many different bits of code it's far too easy to forget which bits still exist & which bits we've refactored out of existence.

If you rebase this against an up-to-date master we'll be good to ship. Thanks for the patience here.

**Comment by eirinikos** [comment]
Sure thing, thanks the explanations and the closer look!

**Comment by DomT4** [comment]
Merged. Thank you Andrea, appreciate the help killing off the unnecessary Go module requires! 🙇

**Pull request closed without merging**
