### PR TITLE
dip 1.3.5 (new formula)

### PR DESCRIPTION
**Pull request by amancevice**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Adds a formula for the `dip` CLI -- a tool for using docker-compose to make & distribute CLIs

### CODE REVIEW

**Comment by fxcoudert** [comment]
Hi @amancevice, thanks for suggesting this formula. For new, self-submitted software with few users, we cannot include it in homebrew core. We recommend that you maintain it in a personal tap: https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md

**Comment by amancevice** [comment]
There are dozens of us! DOZENS!

Thanks, @fxcoudert will do.

**Comment by amancevice** [comment]
@fxcoudert, is there any documentation on getting Travis to build your bottles on multiple macOS/OSX versions like the official repo?

**Comment by fxcoudert** [comment]
@amancevice our documentation is here: https://github.com/Homebrew/brew/blob/master/docs/Bottles.md

Basically:
- `brew install --build-bottle`
- `brew bottle`
- use a custom `root_url` to reflect where you host your bottles

**Comment by amancevice** [comment]
Thanks, @fxcoudert. I figured out that much, but I was more wondering about how to get bottles for multiple OS version (el_capitan, sierra, yosemite, etc) -- I only have the one machine so I can only make a single bottle. This might be more of a question for Travis, but I thought there might be some docs on it somewhere.

**Pull request closed without merging**
