### PR TITLE
yarn: bring back 0.17.10 as stable and move 0.18.0 to devel as this i…

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

…s a pre-release

### CODE REVIEW

**Comment by nijikon** [comment]
As reported in #7534

**Comment by mgol** [comment]
👍

**Comment by mgol** [comment]
Looks good! 👍

**Comment by MikeMcQuaid** [comment]
Fine with me but perhaps worth adding an `audit` check or at least a comment to catch this in future?

**Comment by mgol** [comment]
The build failed because of:

> stable version should not decrease (from 0.18.0 to 0.17.10)

Is downgrading possible?

**Pull request closed without merging**
