### PR TITLE
semgrep: drop GCC dependency

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
It looks like this is failing due to a race condition, but it's already deparallelized.  Not sure how to fix this just yet.

**Comment by carlocab** [comment]
I don't think this is a race. Races are non-deterministic, but we see the same error every time.

**Comment by danielnachun** [comment]
I think the runners had not all finished when I wrote that above, but it is indeed the same error on all platforms.  Moreover it is in one of the Python resources (`jsonschema`).  I will update the resources and see if that fixes the failure, as `jsonschema` has been updated among others.

**Comment by iMichka** [comment]
Looks similar to the error we had with the `poetry` build. I bumped the resources, let's see how this goes.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
