### PR TITLE
adding libglade dependency to pygtk

### PR DESCRIPTION
**Pull request by blogabe**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by blogabe** [comment]
Hi maintainers, the test failed, but I don't believe it has anything to do with the change I've introduced.  I'm simply adding a dependency.

**Comment by SMillerDev** [comment]
The test that failed is the build.

**Comment by fxcoudert** [comment]
```
pango.c:3822:34: error: no member named 'find_shaper' in 'struct _PangoFontClass'
    if (PANGO_FONT_CLASS(klass)->find_shaper)
        ~~~~~~~~~~~~~~~~~~~~~~~  ^
pango.c:3823:40: error: no member named 'find_shaper' in 'struct _PangoFontClass'
        ret = PANGO_FONT_CLASS(klass)->find_shaper(PANGO_FONT(self->obj), lang, ch);
              ~~~~~~~~~~~~~~~~~~~~~~~  ^
pango.c:8650:55: error: use of undeclared identifier 'PANGO_TYPE_FONTSET_SIMPLE'
    pygobject_register_class(d, "PangoFontsetSimple", PANGO_TYPE_FONTSET_SIMPLE, &PyPangoFontsetSimple_Type, Py_BuildValue("(O)", &PyPangoFontset_Type));
                                                      ^
```

**Comment by blogabe** [comment]
Hi, yes, I can see that, but that build error - I don't believe anyway - has anything to do with the dependency I'm adding.  The build fails without my addition on my Catalina machine, but not on my High Sierra machine.

**Comment by blogabe** [comment]
Cool.  I'm all for that.  I'm unsure how to fix the build and appreciate any direction to resolve this.

**Pull request closed without merging**
