### PR TITLE
haskell-stack 2.5.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Failed to build casa-types-0.0.1.
Build log (
/private/tmp/haskell-stack-20201015-9666-1lguhm9/stack-2.5.1/.brew_home/.cabal/logs/ghc-8.10.1/cs-typs-0.0.1-8d139765.log
):
Configuring library for casa-types-0.0.1..
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-L/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries' [-Wunused-command-line-argument]
Preprocessing library for casa-types-0.0.1..
Building library for casa-types-0.0.1..
[1 of 2] Compiling Casa.Types       ( src/Casa/Types.hs, dist/build/Casa/Types.o, dist/build/Casa/Types.dyn_o )

src/Casa/Types.hs:52:14: error:
    • Couldn't match expected type ‘Either String ByteString’
                  with actual type ‘(ByteString, ByteString)’
    • In the pattern: (result, wrong)
      In a case alternative:
          (result, wrong) | S.null wrong -> pure result
      In a stmt of a 'do' block:
        case Hex.decode (T.encodeUtf8 bytes) of
          (result, wrong) | S.null wrong -> pure result
          _ -> fail "Invalid hex key."
   |
52 |              (result, wrong) | S.null wrong -> pure result
   |              ^^^^^^^^^^^^^^^
cabal: Failed to build casa-types-0.0.1 (which is required by stack-2.5.1).
See the build log above for details.
```

**Comment by chenrui333** [comment]
reported in here, https://gitlab.haskell.org/ghc/ghc/-/issues/18754

**Comment by chenrui333** [comment]
https://hackage.haskell.org/package/casa-types-0.0.2 fixed the build issue.

**Comment by chenrui333** [comment]
```
[ 54 of 109] Compiling Stack.Storage.User ( src/Stack/Storage/User.hs, dist/build/Stack/Storage/User.o, dist/build/Stack/Storage/User.dyn_o )

src/Stack/Storage/User.hs:53:1: error:
    Generating Persistent entities now requires the DataKinds language extension. Please enable it by copy/pasting this line to the top of your file:

{-# LANGUAGE DataKinds #-}
   |
53 | share [ mkPersist sqlSettings
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Failed to build stack-2.5.1. See the build log above for details.
```

**Comment by SeekingMeaning** [comment]
```
[ 40 of 109] Compiling Stack.Constants  ( src/Stack/Constants.hs, dist/build/Stack/Constants.o, dist/build/Stack/Constants.dyn_o )
<command line>: can't load framework: Cocoa (not found)
cabal: Failed to build stack-2.5.1.1. See the build log above for details.
```

Possibly related: https://gitlab.haskell.org/ghc/ghc/-/issues/18446, fixed in GHC 8.10.3

**Comment by chenrui333** [comment]
let's revisit the change later.

**Comment by carlocab** [comment]
ghc 8.10.3 https://github.com/Homebrew/homebrew-core/pull/67284

**Pull request closed without merging**
