### PR TITLE
docfx 2.62.1

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
I filed an issue for the artifact problem, https://github.com/dotnet/docfx/issues/8345

**Comment by chenrui333** [comment]
need to switch to use `dotnet@6` to build the artifact.

**Comment by iMichka** [comment]
Wait; the install block just downloads a precompiled exe and we just execute it with mono, right? So it looks like there is more work to do to get this building from source, or am I wrong?

**Comment by cho-m** [comment]
Switching to `dotnet@6` (this version) or `dotnet` (2.61.0) will require a full rewrite of install block similar to `gitversion`, `archi-steam-farm`, `jackett`, etc.

Upstream workflow example: https://github.com/dotnet/docfx/blob/main/.github/workflows/release.yml#L39

Note that we don't want to use exact upstream publish command as it is self-contained (i.e. bundles .NET runtime).

---

On side note, all our `mono`-based formulae use upstream's pre-built EXEs.

**Comment by chenrui333** [comment]
The build should be good now, but the test has some issue (could not figure it out why)

**Comment by iMichka** [comment]
Glad you could move this forward, had no time to look into it.

> Config file docfx.json does not exist!

Looks like a file is missing. But maybe we can call it a day and just look for that string in the test output.

**Comment by iMichka** [comment]
I think I found it, I removed the `"--NoUpdates"` flag from the script rewrite line.

**Comment by iMichka** [comment]
Ping @chenrui333

**Review by SMillerDev — DISMISSED** [review]

**Pull request closed without merging**
