### PR TITLE
swi-prolog: use ARPREFIX to locate libarchive

### LINKED ISSUE #19140: SWI-Prolog development installation fails
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? --> https://gist.github.com/zephyrfalcon/969a9f4c43c1572276d0050a56115019
- [n/a] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I am trying to install the development version of SWI-Prolog (package `swi-prolog`). This used to work in the past, but since a month or two (not exactly sure) it fails. The stable version does install properly. Previously installed development versions also still work. I saw that a new version (7.7.1) was available, and decided to try it, but the same problem still occurs.

- What happened (include command output)

This is my current situation:

```
hans@vulpix ~/temp % brew info swi-prolog
swi-prolog: stable 7.4.2 (bottled), devel 7.7.1, HEAD
ISO/Edinburgh-style Prolog interpreter
http://www.swi-prolog.org/
/usr/local/Cellar/swi-prolog/7.4.2 (791 files, 18.9MB)
  Poured from bottle on 2017-09-30 at 08:01:28
/usr/local/Cellar/swi-prolog/7.5.6 (1,795 files, 29.5MB)
  Built from source on 2017-06-18 at 11:30:11 with: --with-libarchive --with-xpce --with-jpl
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/swi-prolog.rb
==> Dependencies
Build: pkg-config ✔
Required: readline ✔, gmp ✔, openssl ✔
Optional: libarchive ✔
[...]
```

Then, when upgrading, this happens:

```
hans@vulpix ~/temp % brew upgrade swi-prolog --devel --with-libarchive --with-xpce
==> Upgrading 1 outdated package, with result:
swi-prolog 7.7.1
==> Upgrading swi-prolog --with-jpl --with-xpce --with-libarchive
==> Downloading http://www.swi-prolog.org/download/devel/src/swipl-7.7.1.tar.gz
Already downloaded: /Users/hans/Library/Caches/Homebrew/swi-prolog-7.7.1.tar.gz
Error: No such file or directory @ rb_sysopen - packages/archive/configure.in
```

(I looked at the source of SWI-Prolog 7.7.1, and the file `packages/archive/configure.in` does exist. I don't see any glaring differences here with previous versions either.)

- What you expected to happen

I expected version 7.7.1 to be installed. :)

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install swi-prolog --devel --with-xpce --with-libarchive
# or, if already installed:
brew upgrade swi-prolog --devel --with-xpce --with-libarchive
```

(For the record, I am reluctant to completely delete all the existing Prolog versions and do a fresh install, in case none of the installs work. I am working on a few projects that use Prolog and need to have at least the stable version around...)

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes #19140.

CC @DomT4

### CODE REVIEW

**Comment by ilovezfs** [comment]
Fixes https://github.com/Homebrew/homebrew-core/issues/19140.

**Comment by DomT4** [comment]
More than fine with me at least until they get the silly which `configure` script should be patched semi-harmonised.

**Comment by ilovezfs** [comment]
@DomT4 actually it looks like there's an envvar `ARPREFIX` it understands so maybe we should just do that.

**Comment by DomT4** [comment]
That would definitely be simpler. I'm essentially down for any option that doesn't involve patching three slightly different files for three different builds.

**Comment by ilovezfs** [comment]
@DomT4 updated.

**Comment by DomT4** [comment]
Looks like the code that was there had stuck around for a while, at least since this was migrated from X11 last year. The `ENV` is a lot cleaner than the `inreplace`, nice find 👍.

**Comment by ilovezfs** [comment]
@DomT4 while I have your attention, the indefinite article audit for `desc` is toast (as in it stopped working at some point), if you want something to do.

**Comment by DomT4** [comment]
I think it might be more borked than that. I saw someone offer up a _very_ long `desc` the other night and locally I can set `a2ps`'s `desc` to:

```ruby
desc "An Any-to-PostScript filter asjagasgasjagasgasjagasgasjagasgasjagasgasjagasgasjagasgasjagasgasjagasgasjagasgasjagasgasjagasgasjagasgasjagasgasjagasgasjagasg"
```
And run `brew audit --new-formula a2ps` and it cares not even a bit. I have to go right back to https://github.com/Homebrew/brew/commit/febc1085984e3d7fa23ee4c18d11e087afe20cbe before it complains about both the `An` and the length. Everything after https://github.com/Homebrew/brew/commit/a693ca332efcc56e0d7dbb3f43952226225ccf75 is broken for me, although of course that may not have been the actual breakage point.

**Comment by ilovezfs** [comment]
@DomT4 

```
iMac-TMP:Homebrew joe$ git bisect bad
9eb51db400261545822c8c03c2e9d587d70e8ad0 is the first bad commit
commit 9eb51db400261545822c8c03c2e9d587d70e8ad0
Author: Mike McQuaid <mike@mikemcquaid.com>
Date:   Sun Sep 24 19:10:57 2017 +0100

    Rubocop 0.50 and target 2.3.

:040000 040000 7e98e5993eeca9eb1960aa7e6fbe5b1eca726b5b 38ad8af98332b43176282241df9c5a866ae258b1 M    Library
```
:(

**Comment by DomT4** [comment]
Huh, yup. If I change the Rubocop version line back to:
```ruby
HOMEBREW_RUBOCOP_VERSION = "0.49.1"
```
we get back to expected functionality. Interesting.

**Comment by ilovezfs** [comment]
@DomT4 Can you comment with that on https://github.com/Homebrew/brew/issues/3286 please?

**Pull request merged**
