### PR TITLE
awscli 2.0.44

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by Rylan12 — APPROVED** [review]

**Comment by xeron** [comment]
Not sure if this PR is the reason but I'm getting:

```
Upgrading awscli 2.0.43 -> 2.0.44
...
Given no hashes to check 145 links for project ...: discarding no candidates
```

during `awscli` installation.

**Comment by chenrui333** [comment]
> Not sure if this PR is the reason but I'm getting:
> 
> ```
> Upgrading awscli 2.0.43 -> 2.0.44
> ...
> Given no hashes to check 145 links for project ...: discarding no candidates
> ```
> 
> during `awscli` installation.
> 
> And after some updates / cleanup and reinstalling python I'm getting:
> 
> ```
> ==> Downloading https://files.pythonhosted.org/packages/11/74/2c151a13ef41ab9fb43b3c4ff9e788e0496ed7923b2078d42cab30622bdf/virtualenv-16.7.4.tar.gz
> ######################################################################## 100.0%
> ==> Downloading https://github.com/aws/aws-cli/archive/2.0.44.tar.gz
> ==> Downloading from https://codeload.github.com/aws/aws-cli/tar.gz/2.0.44
> ######################################################################## 100.0%
> ==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/awscli--homebrew-virtualenv-20200901-61786-1x4hyqs/target --install-scripts=/private/tmp/awscli--homebrew-virtualenv-20200901-61786-1x4hyqs/target/bin --single-version-externally-managed --record=installed.txt
> ==> python3 -s /private/tmp/awscli--homebrew-virtualenv-20200901-61786-1x4hyqs/target/bin/virtualenv -p python3 /opt/brew/Cellar/awscli/2.0.44/libexec
> Last 15 lines from /Users/ilarionov/Library/Logs/Homebrew/awscli/02.python3:
> New python executable in /opt/brew/Cellar/awscli/2.0.44/libexec/bin/python3.8
> Also creating executable in /opt/brew/Cellar/awscli/2.0.44/libexec/bin/python
> Traceback (most recent call last):
>   File "/private/tmp/awscli--homebrew-virtualenv-20200901-61786-1x4hyqs/target/lib/python3.8/site-packages/virtualenv.py", line 2632, in <module>
>     main()
>   File "/private/tmp/awscli--homebrew-virtualenv-20200901-61786-1x4hyqs/target/lib/python3.8/site-packages/virtualenv.py", line 860, in main
>     create_environment(
>   File "/private/tmp/awscli--homebrew-virtualenv-20200901-61786-1x4hyqs/target/lib/python3.8/site-packages/virtualenv.py", line 1159, in create_environment
>     install_distutils(home_dir)
>   File "/private/tmp/awscli--homebrew-virtualenv-20200901-61786-1x4hyqs/target/lib/python3.8/site-packages/virtualenv.py", line 1784, in install_distutils
>     distutils_path = change_prefix(distutils.__path__[0], home_dir)
>   File "/private/tmp/awscli--homebrew-virtualenv-20200901-61786-1x4hyqs/target/lib/python3.8/site-packages/virtualenv.py", line 1267, in change_prefix
>     assert False, "Filename {} does not start with any of these prefixes: {}".format(filename, prefixes)
> AssertionError: Filename /opt/brew/lib/python3.8/site-packages/setuptools/_distutils does not start with any of these prefixes: ['/private/tmp/awscli-20200901-61786-16h5kum/aws-cli-2.0.44/.brew_home/Library/Python/3.8/lib/python/site-packages', '/private/tmp/awscli-20200901-61786-16h5kum/aws-cli-2.0.44/.brew_home/.local/lib/python/3.8/site-packages', '/private/tmp/awscli-20200901-61786-16h5kum/aws-cli-2.0.44/.brew_home/Library/Python/3.8/site-packages', '/opt/brew/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/Extras/lib/python', '/opt/brew/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8', '/opt/brew/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8', '/Library/Python/3.8/site-packages']
> Running virtualenv with interpreter /opt/brew/opt/python@3.8/bin/python3
> 
> Do not report this issue to Homebrew/brew or Homebrew/core!
> ```

here is my upgrade output:

```
$ brew upgrade awscli
==> Upgrading 1 outdated package:
awscli 2.0.40 -> 2.0.44
==> Upgrading awscli 2.0.40 -> 2.0.44
==> Downloading https://homebrew.bintray.com/bottles/awscli-2.0.44.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/b610a107875dac44a9a3a5c45569228dfb0c51769af74e69ac3aec57ac1c8c70?response-content-disposition=attachment%3Bfilename%3D%22awscli-2.0.44.mojave.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvYjYxMGExMDc4NzVkYWM0NGE5YTNhNWM0NTU2OTIyOGRmYjBjNTE3NjlhZjc0ZTY5YWMzYWVjNTdhYzFjOGM3MD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmF3c2NsaS0yLjAuNDQubW9qYXZlLmJvdHRsZS50YXIuZ3olMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1OTg5OTkzMzB9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=jJzw7QE91w~xrYPicmVTGP4nW0MLyOmXKKmhBZZtaLVALGR1YpvJDDXxogeMHPhIx3DVxq~jlsL5xlxoWxNlgVzKAL9sTnNO57XIg~60SrFESo6t0UEC1H~vrN4EjvTmDpeiXTIOmtX-wfPPCuTk~rt4wydWiSaxhcfT6~BY1LP8jNNmLql20ZIf2Oza~DtiYvisjP3VpQfFpENP0LobBs9l8LcDWBh57PWF3LPaxRhkqWlHxLdIVQ81Ts7bexLSmGyEgDtD3BK1WN1KwAhqLKEEbDugjOqQ6qVcRX11jHIH5tHS8RrD2I3zLIuNpQSOlDrD5GJtmnxkMKgMdjQY~g__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.4.16-46-g2b4f364\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --fail --retry 3 --location --remote-time --continue-at 0 --output /Users/rchen/Library/Caches/Homebrew/downloads/39893f5a3f4acd6820d8485b92b1d34756ed213b06dde6c6b8049f3ba51e3759--awscli-2.0.44.mojave.bottle.tar.gz.incomplete https://d29vzk4ow07wi7.cloudfront.net/b610a107875dac44a9a3a5c45569228dfb0c51769af74e69ac3aec57ac1c8c70\?response-content-disposition=attachment\%3Bfilename\%3D\%22awscli-2.0.44.mojave.bottle.tar.gz\%22\&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvYjYxMGExMDc4NzVkYWM0NGE5YTNhNWM0NTU2OTIyOGRmYjBjNTE3NjlhZjc0ZTY5YWMzYWVjNTdhYzFjOGM3MD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmF3c2NsaS0yLjAuNDQubW9qYXZlLmJvdHRsZS50YXIuZ3olMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1OTg5OTkzMzB9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19\&Signature=jJzw7QE91w\~xrYPicmVTGP4nW0MLyOmXKKmhBZZtaLVALGR1YpvJDDXxogeMHPhIx3DVxq\~jlsL5xlxoWxNlgVzKAL9sTnNO57XIg\~60SrFESo6t0UEC1H\~vrN4EjvTmDpeiXTIOmtX-wfPPCuTk\~rt4wydWiSaxhcfT6\~BY1LP8jNNmLql20ZIf2Oza\~DtiYvisjP3VpQfFpENP0LobBs9l8LcDWBh57PWF3LPaxRhkqWlHxLdIVQ81Ts7bexLSmGyEgDtD3BK1WN1KwAhqLKEEbDugjOqQ6qVcRX11jHIH5tHS8RrD2I3zLIuNpQSOlDrD5GJtmnxkMKgMdjQY\~g__\&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.5M  100 21.5M    0     0  3521k      0  0:00:06  0:00:06 --:--:-- 3276k
==> Verifying 39893f5a3f4acd6820d8485b92b1d34756ed213b06dde6c6b8049f3ba51e3759--awscli-2.0.44.mojave.bottle.tar.gz checksum
rm /usr/local/bin/aws
rm /usr/local/bin/aws_completer
rm /usr/local/bin/aws_legacy_completer
rm /usr/local/etc/bash_completion.d/aws_bash_completer
rm /usr/local/share/awscli
rm /usr/local/share/zsh/site-functions/_aws
rm /usr/local/share/zsh/site-functions/aws_zsh_completer.sh
==> Pouring awscli-2.0.44.mojave.bottle.tar.gz
tar xof /Users/rchen/Library/Caches/Homebrew/downloads/39893f5a3f4acd6820d8485b92b1d34756ed213b06dde6c6b8049f3ba51e3759--awscli-2.0.44.mojave.bottle.tar.gz -C /var/folders/tx/r379rh796575t4m9_40r8b940000gp/T/d20200901-65748-14kc69z
cp -pR /var/folders/tx/r379rh796575t4m9_40r8b940000gp/T/d20200901-65748-14kc69z/awscli/. /usr/local/Cellar/awscli
chmod -Rf +w /var/folders/tx/r379rh796575t4m9_40r8b940000gp/T/d20200901-65748-14kc69z
==> Finishing up
ln -s ../../Cellar/awscli/2.0.44/etc/bash_completion.d/aws_bash_completer aws_bash_completer
ln -s ../Cellar/awscli/2.0.44/bin/aws aws
ln -s ../Cellar/awscli/2.0.44/bin/aws_completer aws_completer
ln -s ../Cellar/awscli/2.0.44/bin/aws_legacy_completer aws_legacy_completer
ln -s ../Cellar/awscli/2.0.44/share/awscli awscli
ln -s ../../../Cellar/awscli/2.0.44/share/zsh/site-functions/_aws _aws
ln -s ../../../Cellar/awscli/2.0.44/share/zsh/site-functions/aws_zsh_completer.sh aws_zsh_completer.sh
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200901-65869-8kjbg2.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/awscli.rb
NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.
fgrep: /usr/local/Cellar/awscli/2.0.44/libexec/include/python3.8: Is a directory
fgrep: /usr/local/Cellar/awscli/2.0.44/libexec/lib/python3.8/lib-dynload: Is a directory
fgrep: /usr/local/Cellar/awscli/2.0.44/libexec/lib/python3.8/encodings: Is a directory
fgrep: /usr/local/Cellar/awscli/2.0.44/libexec/lib/python3.8/config-3.8-darwin: Is a directory
fgrep: /usr/local/Cellar/awscli/2.0.44/libexec/lib/python3.8/importlib: Is a directory
fgrep: /usr/local/Cellar/awscli/2.0.44/libexec/lib/python3.8/collections: Is a directory
==> Caveats
The "examples" directory has been installed to:
  /usr/local/share/awscli/examples

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/awscli/2.0.44: 11,809 files, 83.9MB
Removing: /usr/local/Cellar/awscli/2.0.40... (11,783 files, 85.8MB)
```

@xeron do you want to give `brew reinstall awscli` a shot?

**Comment by xeron** [comment]
Yeah I tried it. also tried remove / cleanup of `awscli` and installing `2.0.43` but it doesn't work either…

I recentyl updated to cataline, which could be the problem. Looks like `awscli` formula update is not related.

```
python3
-s
/private/tmp/awscli--homebrew-virtualenv-20200901-80133-7m29sg/target/bin/virtualenv
-p
python3
/opt/brew/Cellar/awscli/2.0.44/libexec

Already using interpreter /opt/brew/opt/python@3.8/bin/python3.8
Using base prefix '/opt/brew/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8'
New python executable in /opt/brew/Cellar/awscli/2.0.44/libexec/bin/python3.8
Also creating executable in /opt/brew/Cellar/awscli/2.0.44/libexec/bin/python
Traceback (most recent call last):
  File "/private/tmp/awscli--homebrew-virtualenv-20200901-80133-7m29sg/target/lib/python3.8/site-packages/virtualenv.py", line 2632, in <module>
    main()
  File "/private/tmp/awscli--homebrew-virtualenv-20200901-80133-7m29sg/target/lib/python3.8/site-packages/virtualenv.py", line 860, in main
    create_environment(
  File "/private/tmp/awscli--homebrew-virtualenv-20200901-80133-7m29sg/target/lib/python3.8/site-packages/virtualenv.py", line 1159, in create_environment
    install_distutils(home_dir)
  File "/private/tmp/awscli--homebrew-virtualenv-20200901-80133-7m29sg/target/lib/python3.8/site-packages/virtualenv.py", line 1784, in install_distutils
    distutils_path = change_prefix(distutils.__path__[0], home_dir)
  File "/private/tmp/awscli--homebrew-virtualenv-20200901-80133-7m29sg/target/lib/python3.8/site-packages/virtualenv.py", line 1267, in change_prefix
    assert False, "Filename {} does not start with any of these prefixes: {}".format(filename, prefixes)
AssertionError: Filename /opt/brew/lib/python3.8/site-packages/setuptools/_distutils does not start with any of these prefixes: ['/private/tmp/awscli-20200901-80133-1glzj3y/aws-cli-2.0.44/.brew_home/Library/Python/3.8/lib/python/site-packages', '/private/tmp/awscli-20200901-80133-1glzj3y/aws-cli-2.0.44/.brew_home/.local/lib/python/3.8/site-packages', '/private/tmp/awscli-20200901-80133-1glzj3y/aws-cli-2.0.44/.brew_home/Library/Python/3.8/site-packages', '/opt/brew/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/Extras/lib/python', '/opt/brew/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8', '/opt/brew/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8', '/Library/Python/3.8/site-packages']
Running virtualenv with interpreter /opt/brew/opt/python@3.8/bin/python3

HOMEBREW_VERSION: 2.4.16-59-gcbc3448
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: cbc3448634aebf0fa14dec799a138e01f6df687b
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f652c981aa448202aae4d6c493e1d2c9110414a6
Core tap last commit: 4 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/brew
HOMEBREW_REPOSITORY: /opt/brew
HOMEBREW_CELLAR: /opt/brew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.GhHVBPyLiA/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 12.0 build 1200
Git: 2.28.0 => /opt/brew/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.8, 1.8.0_265
macOS: 10.15.6-x86_64
CLT: 12.0.0.0.1.1597368733
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /opt/brew/opt/openssl@1.1:/opt/brew/opt/readline:/opt/brew/opt/sqlite:/opt/brew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /opt/brew/opt/python@3.8/Frameworks
PKG_CONFIG_PATH: /opt/brew/opt/openssl@1.1/lib/pkgconfig:/opt/brew/opt/readline/lib/pkgconfig:/opt/brew/opt/sqlite/lib/pkgconfig:/opt/brew/opt/xz/lib/pkgconfig:/opt/brew/opt/python@3.8/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/brew/Library/Homebrew/os/mac/pkgconfig/10.15
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
ACLOCAL_PATH: /opt/brew/share/aclocal
PATH: /opt/brew/Library/Homebrew/shims/mac/super:/opt/brew/opt/gdbm/bin:/opt/brew/opt/openssl@1.1/bin:/opt/brew/opt/sqlite/bin:/opt/brew/opt/xz/bin:/opt/brew/opt/python@3.8/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by xeron** [comment]
Also your log is from bottle… mine is from source sure to `/opt/brew` prefix.

**Pull request closed without merging**
