### PR TITLE
imagemagick 6.9.5-2

### PR DESCRIPTION
**Pull request by zmwangx**

### CODE REVIEW

**Comment by RandomDSdevel** [comment]
@zmwangx:  Hmm, looks like the bottle build errored out on us.  From what I see in [the top-level CI console output](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4766/console), the [Mavericks build](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4766/version=mavericks/console) succeeded but, strangely enough, both the [Yosemite build](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4766/version=yosemite/console) and the [El Capitan](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4766/version=el_capitan/console) one crashed.  Scrutinizing the 10.11.5 build console output I linked previously further reveals that the problem reared its ugly head when ImageMagick's configure phase was trying to look for a little something called libltdl, which, upon further research, appears to be part of libtool.  I wonder what in the blazes could be going on here…

**Comment by zmwangx** [comment]
See #2932. I haven't looked into the issue, but my local build is fine.

**Comment by RandomDSdevel** [comment]
Ah, whoops:  since I wasn't expecting that bug to persist for builds of later versions of ImageMagick, I overlooked it.  Thanks for pointing me back to it, @zmwangx!

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/0f16c1c3a18ee5eeceda06a33765f1ddea19bb4c. Thanks again @zmwangx, and appreciate the patience whilst I ran around the Homebrew repos screaming _"Why is everything broken, what did we do"_ until I spotted & fixed it, heh.

**Pull request closed without merging**
