### PR TITLE
gauge 1.3.2

### PR DESCRIPTION
**Pull request by gaugebot**
Please cc getgauge/core for any issue.

### CODE REVIEW

**Comment by dawidd6** [comment]
CC @getgauge/core

**Comment by sriv** [comment]
The plugin being used in this test i.e. `html-report` also needs to be on darwin/arm64 it seems. I need to verify why this is the case here, since it should in theory fallback to x86_64 which should run under rosetta.

FWIW, the `html-report` plugin has been ported to darwin/arm64, I'll include it in the repository and that should help here.

> Also please fix your bumping script as the above CC does not work.
Strange, the team exists and the visibility is set to `Visible`. In any case I'll let the script tag a few key individuals instead.

Question - is there a way to retrigger the checks in this PR? Or do I need to submit a new one?

**Comment by dawidd6** [comment]
Any maintainer can retrigger tests manually. Or you can just rebase and force push the branch.

**Comment by sriv** [comment]
The plugin repository for gauge has now been updated to include `darwin/arm64` build for `html-report`. If someone can retrigger the build, it can help verify.

The PR is raised by a bot, so unfortunately I cannot force push any commits to this.

**Review by dawidd6 — APPROVED** [review]

**Pull request closed without merging**
