### PR TITLE
bmake 20210808

### PR DESCRIPTION
**Pull request by stevej098**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
followed all steps in https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

11635	 cd $(brew --repository homebrew/core)
11636	 pwd
11638	 git remote add stevej098 https://github.com/stevej098/homebrew-core.git
11641	 git checkout master
11642	 brew update
11643	 git checkout -b bmake-20210808 origin/master
11649	 export EDITOR=/usr/bin/vim
11650	 brew edit bmake
11651	 echo https://www.crufty.net/ftp/pub/sjg/bmake-20210808.tar.gz | pbcopy
11653	 (cd ~/src; sha2 -256 bmake.tar.gz; ) # get SHA-256, copy to paste buffer
11654	 fg
11655	 brew tests
11657	 brew install --build-from-source bmake
11658	 brew test bmake
11688	 brew audit --strict --online bmake
11691	 brew audit --strict --online bmake
11692	 ls -l /usr/local/bin/bmake
11693	 git add bmake 20210808
11695	 git add Formula/bmake.rb 
11697	 git commit
11721	 gh auth login -w
11722	 git push --set-upstream stevej098 bmake-20210808

### CODE REVIEW

**Comment by Bo98** [comment]
On Big Sur only:

```
--- /private/tmp/bmake-20210914-81442-ah39wn/bmake/unit-tests/shell-ksh.exp	2020-10-10 17:41:47.000000000 +0100
+++ shell-ksh.out	2021-09-14 11:27:12.000000000 +0100
@@ -1,4 +1,6 @@
 : normal
-: always
-: ignore errors
-exit status 0
+*** Signal 11 (continuing)
+
+Stop.
+make: stopped in unit-tests
+exit status 1
Failed tests: shell-ksh
```

**Comment by stevej098** [comment]
I have Mojave.

Am I supposed to understand the output?
or know how to fix this without access to the System Under Test?

> On 14 Sep 2021, at 20:42, Bo Anderson ***@***.***> wrote:
> 
> 
> On Big Sur only:
> 
> --- /private/tmp/bmake-20210914-81442-ah39wn/bmake/unit-tests/shell-ksh.exp	2020-10-10 17:41:47.000000000 +0100
> +++ shell-ksh.out	2021-09-14 11:27:12.000000000 +0100
> @@ -1,4 +1,6 @@
>  : normal
> -: always
> -: ignore errors
> -exit status 0
> +*** Signal 11 (continuing)
> +
> +Stop.
> +make: stopped in unit-tests
> +exit status 1
> Failed tests: shell-ksh
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

--
Steve Jenkin, IT Systems and Design 
0412 786 915 (+61 412 786 915)
PO Box 38, Kippax ACT 2615, AUSTRALIA

***@***.***
http://members.tip.net.au/~sjenkin

**Comment by stevej098** [comment]
You've got a problem with process.
As an organisation, by adding this formula you undertook a number of commitments.
There must be a clear and identified 'owner' of each and every package and a commitment to deal with 'upstream' over time as changes are made.

You added 'bmake' and then walked away, turning your back on maintenance. This is not professional behaviour.
Do you think that Debian, Ubuntu and Fedora operate that way with their very large package systems? NO.
That you can't see that you've undertaken those commitments underlines the issue with your process.

Apparently I'm not the first person to attempt to update bmake to the current version - and that people have noticed multiple failed pull requests and sat on their hands. You're not even interested in investigating _multiple_ occurrences of failures.

As a First Time contrib, I've been treated appallingly: no help, no explanations, no shepherding through the process  - NO mentoring.
I very diligently and assiduously followed your noxious & noisome Update instructions, hidden away in a secret place (see above for commands run) - and NOTHING in them said there'd be this bullshit afterwards.

I proceeded in good faith and you're acting like a bunch of jerks.

you've automatically closed the pull request and left me swinging in the breeze.
I'm not the owner of this code, I'm not the 'upstream', I'm just a user trying to help the community by fixing a tiny corner.

Where the hell are the CI logs?
There NO clues for newbies / 1st time contrib.
What went wrong? NO IDEA and nobody

How do I get access to a Big Sur test environment to actually troubleshoot?
Your answer: Screw You, there's no access for you!

This isn't what I do as a Day Job - it's a very hard slog as a 1st time contrib grinding through your byzantine and complex system.

This isn't how quality or Professional open source projects are run.

I've attempted to be a good member of the community and your behaviour isn't just abhorrent, it's downright nasty.

**Comment by iMichka** [comment]
https://github.com/Homebrew/.github/blob/HEAD/CODE_OF_CONDUCT.md#code-of-conduct

I am going to leave the ugly message you wrote so everyone can see it.

I just woke up and I am reviewing pull request during breakfast, on my free time, and you already ruined my day.

You'll be blocked from the Homebrew org from now on, based on the above.

**Pull request closed without merging**
