### PR TITLE
nuclei 2.9.2

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
```
  ==> /opt/homebrew/Cellar/nuclei/2.9.2/bin/nuclei -target google.com -t test.yaml
  [ERR] failed to create config directory at /Users/brew/.config/nuclei got: mkdir /Users/brew/.config/nuclei: operation not permitted
  [ERR] failed to write config file at /Users/brew/.config/nuclei/.templates-config.json got: [:RUNTIME] could not create nuclei config directory at /Users/brew/.config/nuclei <- mkdir /Users/brew/.config/nuclei: operation not permitted
```

Hmm... this is a bit problematic. [The logic](https://github.com/projectdiscovery/nuclei/blob/v2.9.2/v2/pkg/catalog/config/nucleiconfig.go#L271-L277) is to always create the config directory on startup.

```go
func init() {
	ConfigDir := getDefaultConfigDir()
	if !fileutil.FolderExists(ConfigDir) {
		if err := fileutil.CreateFolder(ConfigDir); err != nil {
			gologger.Error().Msgf("failed to create config directory at %v got: %s", ConfigDir, err)
		}
	}
	// ...
}
```

`getDefaultConfigDir`'s implementation [uses Go's `os/user` package](https://github.com/projectdiscovery/utils/blob/main/folder/folderutil.go#L143-L150) to retrieve the home directory. The latter does not seem to respect our sandbox settings.

**Comment by chenrui333** [comment]
maybe filing an upstream issue about this?

**Comment by ZhongRuoyu** [comment]
- https://github.com/projectdiscovery/nuclei/issues/3576

**Comment by ZhongRuoyu** [comment]
Closing this for now since upstream will fix this in the next release.

**Comment by p-linnane** [comment]
https://github.com/Homebrew/homebrew-core/pull/130138

**Pull request closed without merging**
