### PR TITLE
molecule 2.15.0

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
This should fix #28635 and I assume the bottles will be created by the Brew Test Bot.

### CODE REVIEW

**Comment by marcelmetz** [comment]
Thanks for taking a look into this.  It seems like your update is unable to locate the dependency binaries like `flake8` or even the python `molecule` module itself.

I tried to initialise a new default test by invoking

```
molecule init scenario -r test-role -s default -d docker
```

which works fine, however the utilities and modules mentioned above cannot be located.  For example when invoking `molecule lint` this results in:

```
$ molecule lint
--> Validating schema <redacted>/test-role/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── default
    └── lint
    
--> Scenario: 'default'
--> Action: 'lint'
--> Executing Yamllint on files found in <redacted>/test-role/...
Lint completed successfully.
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 10, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/molecule/2.15.0/libexec/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/molecule/2.15.0/libexec/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/molecule/2.15.0/libexec/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/molecule/2.15.0/libexec/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/molecule/2.15.0/libexec/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/molecule/2.15.0/libexec/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/molecule/2.15.0/libexec/lib/python2.7/site-packages/molecule/command/lint.py", line 106, in lint
    base.execute_subcommand(scenario.config, action)
  File "/usr/local/Cellar/molecule/2.15.0/libexec/lib/python2.7/site-packages/molecule/command/base.py", line 100, in execute_subcommand
    return command(config).execute()
  File "/usr/local/Cellar/molecule/2.15.0/libexec/lib/python2.7/site-packages/molecule/command/lint.py", line 81, in execute
    l.execute()
  File "/usr/local/Cellar/molecule/2.15.0/libexec/lib/python2.7/site-packages/molecule/verifier/lint/flake8.py", line 119, in execute
    self.bake()
  File "/usr/local/Cellar/molecule/2.15.0/libexec/lib/python2.7/site-packages/molecule/verifier/lint/flake8.py", line 100, in bake
    self._flake8_command = sh.flake8.bake(
  File "/usr/local/Cellar/molecule/2.15.0/libexec/lib/python2.7/site-packages/sh.py", line 3349, in __getattr__
    return self.__env[name]
  File "/usr/local/Cellar/molecule/2.15.0/libexec/lib/python2.7/site-packages/sh.py", line 3226, in __getitem__
    raise CommandNotFound(k)
sh.CommandNotFound: flake8
```

A similar error occurs when calling `molecule check`:

```
$ molecule lint
--> Validating schema <redacted>/test-role/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── default
    ├── destroy
    ├── dependency
    ├── create
    ├── prepare
    ├── converge
    ├── check
    └── destroy
    
--> Scenario: 'default'
--> Action: 'destroy'
    
    PLAY [Destroy] *****************************************************************
    
    TASK [Destroy molecule instance(s)] ********************************************
    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named molecule
    fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1   
    
ERROR: 
```

Is there a way to set the PATH for the molecule installation accordingly?  For my understanding none of the topics in `docs/Python-for-Formula-Authors.md` covers this case and I have yet to find another related document for in-formula dependency search path setup.

**Comment by marcelmetz** [comment]
Still waiting for feedback.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@dhoppeIT @marcelmetz the current test seems fine to me. Can you state what is currently wrong with the PR as it is?

**Comment by marcelmetz** [comment]
@fxcoudert  The formula tests don't invoke any basic functionality of molecule itself aside from initializing a test environment.  Please see my previous post for a step by step case where most functionality isn't working.

- molecule invokes third party applications (e.g. flake8, yamllint, ...) when running tests.  The molecule formula installs that software into the keg(?), but molecule searches it in the regular `PATH`, which may or may not contain the correct third party tools installed by unrelated homebrew invocations.
- molecule uses a python module called `molecule` when testing ansible roles.  It uses the `ansible` application that is found within the `PATH`, whose keg has not this `molecule` python module in its PYTHONPATH`.  The molecule formula also installs a matching `ansible` binary into the molecule keg, but doesn't use it.

**Comment by fxcoudert** [comment]
@marcelmetz test aside, is the resulting installation working for a "normal" user? The test was already somewhat limited, from what I understand.

**Comment by marcelmetz** [comment]
@fxcoudert No, the installation based from this PR does not work for a "normal" user for any regular feature it should cover.

**Comment by marcelmetz** [comment]
Also to clarify: molecule is an application to "unit" test ansible roles.  So when talking about "running (ansible|molecule) tests"  I meant that the molecule installation doesn't work as it should.

The "formula tests" are the smoke tests written within the molecule.py formula to ensure that the formula is working as expected.

**Comment by fxcoudert** [comment]
Thanks for the clarification.

**Comment by claui** [comment]
Bumping @marcelmetz’s [question](https://github.com/Homebrew/homebrew-core/pull/29280#issuecomment-401800531) for visibility:

> Is there a way to set the PATH for the molecule installation accordingly? For my understanding none of the topics in `docs/Python-for-Formula-Authors.md` covers this case and I have yet to find another related document for in-formula dependency search path setup.

**Pull request closed without merging**
