### PR TITLE
apache-pulsar 3.0.0

### PR DESCRIPTION
**Pull request by austek**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by austek** [comment]
Pulsar cli arguments seem to have changed since 2.10.3
In v2.10.3
standalone was using `bin/"pulsar", "standalone", "--zookeeper-dir", "#{testpath}/zk", " --bookkeeper-dir", "#{testpath}/bk"`
for tests `#{bin}/pulsar initialize-cluster-metadata -c a -cs localhost -uw localhost -zk localhost`

However, in v3.0.0 `standalone` doesn't have `--zookeeper-dir` option anymore and is not starting a zookeeper. As a result `initialize-cluster-metadata` fails

**Comment by austek** [comment]
I'm still stuck, raised a discussion on apache pulsar but responses yet https://github.com/apache/pulsar/discussions/20633. Anyways, I don't think the problem is with Pulsar.

I've managed to get the zookeeper to start running with standalone. I've increased the sleep to `1500` to locally test while running the `brew test apache-pulsar`, I can use the command in the formula, `pulsar initialize-cluster-metadata -c a -cs localhost -uw localhost -zk localhost` manually and it completes successfully, however the same command is not working within the test itself?

**Comment by MikeMcQuaid** [comment]
Have removed `help wanted` and/or `in progress` from this PR as there's been no progress in a few months. Maintainers: please don't add these labels as the stalebot is performing a useful service in continuing to bump these PRs and closing them if there's no activity after those bumps. Thanks ❤️

**Comment by chenrui333** [comment]
I am gonna close this PR for now, for whoever watching this, feel free to open a new one. :)

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/198589

**Pull request closed without merging**
