### PR TITLE
openjdk: test build with `llvm@17`

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Let's test whether this builds with `llvm@17` to help track down the
build failure with Apple Clang 16.

### CODE REVIEW

**Comment by carlocab** [comment]
Seems to succeed: https://github.com/Homebrew/homebrew-core/actions/runs/10886892015/job/30208111641?pr=190817#step:3:38

CC @Bo98

**Comment by Bo98** [comment]
Current theory is an optimisation bug. Seems to not happen with `slowdebug` which I think uses `-O0`. Not sure which `-O` level triggers it.

**Comment by carlocab** [comment]
Ok, will add `-Os` to `cflags` and `cxxflags` next to see

**Comment by cho-m** [comment]
May be related root cause for OpenJDK 11 and 17, though for those a JVM crash happens during build. From local attempt, need to go down to `-O1` to avoid.

**Comment by Bo98** [comment]
Yeah seems to be `-O2`. Trying to pin it down further to a specific optimisation pass or what bit of code is failing but haven't gotten anywhere yet.

**Comment by Bo98** [comment]
With that said, if it's crashing in OpenJDK 17 it might be easier to debug properly there.

**Pull request closed without merging**
