### PR TITLE
libinfinity 0.7.1

### PR DESCRIPTION
**Pull request by alebcay**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
```
test.c:1:10: fatal error: 'libinfinity/common/inf-init.h' file not found
#include <libinfinity/common/inf-init.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by fxcoudert** [comment]
```
configure: error: Package requirements (libinfinity-0.6 libinftext-0.6 libinfgtk3-0.6 libinftextgtk3-0.6) were not met:

No package 'libinfinity-0.6' found
No package 'libinftext-0.6' found
No package 'libinfgtk3-0.6' found
No package 'libinftextgtk3-0.6' found
```

**Comment by alebcay** [comment]
Looks like `gobby` expects and will only accept `libinfinity-0.6`, not 0.7. Would it be better to patch `gobby` until its next release or just leave `libinfinity` at 0.6?

**Comment by fxcoudert** [comment]
They seem tightly integrated, so I'd say do nothing for now :)

**Pull request closed without merging**
