### PR TITLE
exiv2 0.28.1

### PR DESCRIPTION
**Pull request by samford**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This updates `exiv2` to the latest version, 0.28.1. 0.28.0 introduced `brotli` and `inih` dependencies and it was necessary to add them to the formula for the build to work. [It's possible to use `-DEXIV2_ENABLE_BROTLI=OFF` to avoid the `brotli` dependency but I've opted to simply add it as a dependency.]

Upstream appears to have switched from publishing `-Source` tarballs in favor of simply using autogenerated GitHub tag archives. This change broke the existing `livecheck` block, so I've updated it to check the Git tags instead.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  CMake Error at /opt/homebrew/Cellar/cmake/3.27.7/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find Brotli (missing: BROTLIDEC_LIBRARY BROTLICOMMON_LIBRARY
    BROTLI_INCLUDE_DIR)
```

**Comment by samford** [comment]
> ```
>   CMake Error at /opt/homebrew/Cellar/cmake/3.27.7/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>     Could NOT find Brotli (missing: BROTLIDEC_LIBRARY BROTLICOMMON_LIBRARY
>     BROTLI_INCLUDE_DIR)
> ```

Ah, it built fine locally because I have `brotli` installed. We can either add `depends_on "brotli"` or use `-DEXIV2_ENABLE_BROTLI=OFF` to disable the `brotli` support. That said, I've pushed a commit to add `brotli` as a dependency.

**Comment by chenrui333** [comment]
make sense :)

**Comment by samford** [comment]
Looks like `siril` may be the only issue at this point. I'm tinkering with 1.2.0, to see if we can get that to build and if it resolves the issue here.

**Comment by samford** [comment]
This will still fail with `siril` 1.2.0 but it can be fixed by applying [an upstream patch](https://gitweb.gentoo.org/repo/gentoo.git/plain/sci-astronomy/siril/files/siril-1.2-exiv2-0.28.patch?id=002882203ad6a2b08ce035a18b95844a9f4b85d0) (I found this in nixpkgs). I'll rebase/update this after the `siril` PR is finished and merged.

**Comment by samford** [comment]
`geeqie` build failure on Linux:

```
FAILED: src/gq-marshal.h 
  /home/linuxbrew/.linuxbrew/Cellar/glib/2.78.1/bin/glib-genmarshal --prefix gq_marshal --output src/gq-marshal.h --header ../src/gq-marshal.list --pragma-once
  /usr/bin/env: ‘python3’: No such file or directory
```

**Comment by chenrui333** [comment]
> `geeqie` build failure on Linux:
> 
> ```
> FAILED: src/gq-marshal.h 
>   /home/linuxbrew/.linuxbrew/Cellar/glib/2.78.1/bin/glib-genmarshal --prefix gq_marshal --output src/gq-marshal.h --header ../src/gq-marshal.list --pragma-once
>   /usr/bin/env: ‘python3’: No such file or directory
> ```

uses_from_macos "python" => :build should be good enough

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
