### PR TITLE
 ipython,  ipython@5,  jupyter, urh: depend on zeromq

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

IMO, leaving it as-is by explicitly enforcing `pyzmq` using its bundled `zeromq` might be better than introducing `zeromq` as a new dependency. 🤔️ However, @ilovezfs, if you prefer the latter, we can always change it. 🧐

### CODE REVIEW

**Comment by ilovezfs** [comment]
Yes this is fine.

**Comment by fxcoudert** [comment]
Let's use this opportunity to make it a proper dependency. No point in having it duplicated through 4 formulas.

**Comment by lembacon** [comment]
@fxcoudert Updated.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @lembacon for the pull request!

**Pull request closed without merging**
