### PR TITLE
axel 2.17.5

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
==> ./autogen.sh
Failed to execute: ./autogen.sh
```

**Comment by jonchang** [comment]
Looks like they changed their build system a bit: https://github.com/axel-download-accelerator/axel#building-from-source

Needs `autoreconf -fvi` probably

**Comment by chenrui333** [comment]
Checking on this now.

**Comment by chenrui333** [comment]
Updating the build step to see if it works.

**Comment by chenrui333** [comment]
11:15:50 usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
11:15:50             [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
11:15:50 /bin/sh: txt2man: command not found
11:15:50 make[1]: *** [doc/axel.1] Error 1
11:15:50 make[1]: *** Waiting for unfinished jobs....
11:15:50 make: *** [install-recursive] Error 1
11:15:50 
11:15:50 ==> Formula
11:15:50 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/axel.rb

**Comment by jonchang** [comment]
I think we will need to open a pull request to upstream to fix the build for macOS, or create a formula for txt2man. One workaround for now is to do `system "make", "axel"` then `bin.install "axel"` but I don't really like that.

**Comment by chenrui333** [comment]
@jonchang I will try this first:
```
    system "make", "axel"
    bin.install "axel"
```

**Comment by chenrui333** [comment]
```
00:14:15 config.status: creating po/Makefile
00:14:15 ==> make axel
00:14:15   CC       src/axel.o
00:14:15   CC       src/conf.o
00:14:15   CC       src/conn.o
00:14:15   CC       src/ftp.o
00:14:15   CC       src/http.o
00:14:15   CC       src/search.o
00:14:15   CC       src/ssl.o
00:14:15   CC       src/tcp.o
00:14:15   CC       src/text.o
00:14:15   CCLD     axel
00:14:15 Error: Empty installation
00:14:15 
00:14:15 ==> brew audit axel --online
```

**Comment by chenrui333** [comment]
Refresh the version to the latest, `v2.17.6`

**Comment by chenrui333** [comment]
```
22:49:51 ==> brew pull --clean https://github.com/Homebrew/homebrew-core/pull/42540
22:50:04 ==> FAILED
22:50:04 fatal: ref HEAD is not a symbolic ref
22:50:04 Warning: axel has a bottle: do you need to update it with --bottle?
22:50:04 Warning: makepkg has a bottle: do you need to update it with --bottle?
22:50:04 Warning: mfterm has a bottle: do you need to update it with --bottle?
22:50:04 Warning: miniserve has a bottle: do you need to update it with --bottle?
22:50:04 Warning: mit-scheme has a bottle: do you need to update it with --bottle?
22:50:04 Warning: monetdb has a bottle: do you need to update it with --bottle?
22:50:04 Warning: mongoose has a bottle: do you need to update it with --bottle?
22:50:04 Warning: monit has a bottle: do you need to update it with --bottle?
22:50:04 Warning: monitoring-plugins has a bottle: do you need to update it with --bottle?
22:50:04 Warning: mupdf has a bottle: do you need to update it with --bottle?
22:50:04 Warning: mysql-cluster has a bottle: do you need to update it with --bottle?
22:50:04 Warning: mysql has a bottle: do you need to update it with --bottle?
22:50:04 Warning: mysql@5.5 has a bottle: do you need to update it with --bottle?
22:50:04 Warning: mysql@5.6 has a bottle: do you need to update it with --bottle?
22:50:04 Warning: mysql@5.7 has a bottle: do you need to update it with --bottle?
22:50:04 Warning: netlify-cli has a bottle: do you need to update it with --bottle?
22:50:04 Warning: sphinx has a bottle: do you need to update it with --bottle?
22:50:04 ==> Fast-forwarding to the merge commit
22:50:04 fatal: Not possible to fast-forward, aborting.
22:50:04 Error: Failure while executing; `git merge --quiet --ff-only --no-edit FETCH_HEAD` exited with 128.
22:50:04 Homebrew/brew 2.1.11 (Merge pull request #6400 from lembacon/virtualenv-16.7.4)
```

**Comment by chenrui333** [comment]
yeah, I forgot why did I do that, but I will update my commits later.

**Comment by chenrui333** [comment]
Closing the PR now as there is no progress made.

**Comment by chenrui333** [comment]
opened a new PR after the release, https://github.com/Homebrew/homebrew-core/pull/46271

**Pull request closed without merging**
