### PR TITLE
Secure URL(s)

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by vszakats** [comment]
`mupen64plus` fails to build on Sierra (unrelated to this update). Splitting it off to a separate PR.

**Comment by vszakats** [comment]
`mupen64plus` and `serialosc` have Sierra build issues, both unrelated to changing the homepage or the checksum-verified source archive.

**Comment by ilovezfs** [comment]
@vszakats serialosc: https://github.com/Homebrew/homebrew-core/pull/17190

**Comment by ilovezfs** [comment]
@vszakats hmm seems brew audit cannot detect libconfig. Do you know what the problem is?

**Comment by vszakats** [comment]
That's great, thank you @ilovezfs.

**Comment by ilovezfs** [comment]
Is it because the content differs?
```
Apache Server at www.hyperrealm.com Port 80
```
vs
```
Apache Server at www.hyperrealm.com Port 443
```
at the bottom of the page

**Comment by ilovezfs** [comment]
Audit is also blind to https://hg.nginx.org/nginx/ probably because of the `:using => :hg`

**Comment by ilovezfs** [comment]
Hmm … audit notices http://accellera.org/images/downloads/standards/systemc/systemc-2.3.1.tgz but does not notice http://accellera.org.

**Comment by vszakats** [comment]
In `libconfig` the content returned via HTTPS is slightly different (and there is no ETag.) The difference is because the port number is being returned in the page footer.

**Comment by vszakats** [comment]
For `accellera.org`, my tools show:
```
https://accellera.org/ [OK] [Matching content (after normalization)]
```
It means the content is identical after removing protocol designators (`http://`, `https://`, etc) from the content.

**Comment by ilovezfs** [comment]
>It means the content is identical after cleaning it from protocol designators (http://, https://, etc).

That sounds like something audit --online could/should be doing, too. CC @MikeMcQuaid

**Comment by ilovezfs** [comment]
Thanks @vszakats!

**Comment by MikeMcQuaid** [comment]
> That sounds like something audit --online could/should be doing, too. CC @MikeMcQuaid

@ilovezfs Agreed. @vszakats Would you be interested in trying to make any of these additions to the audit now it's implemented? We'll be happy to help.

**Comment by vszakats** [comment]
@MikeMcQuaid:
Here's a (likely embarrassing) attempt:
```diff
diff --git a/Library/Homebrew/dev-cmd/audit.rb b/Library/Homebrew/dev-cmd/audit.rb
index 2c9336481..4fadae1a4 100644
--- a/Library/Homebrew/dev-cmd/audit.rb
+++ b/Library/Homebrew/dev-cmd/audit.rb
@@ -201,7 +201,7 @@ class FormulaAuditor
     @specs = %w[stable devel head].map { |s| formula.send(s) }.compact
   end
 
-  def self.check_http_content(url, name, user_agents: [:default])
+  def self.check_http_content(type, url, name, user_agents: [:default])
     return unless url.start_with? "http"
 
     details = nil
@@ -236,8 +236,31 @@ class FormulaAuditor
       details[:content_length] == secure_details[:content_length]
     file_match = details[:file_hash] == secure_details[:file_hash]
 
-    return if !etag_match && !content_length_match && !file_match
-    "The URL #{url} could use HTTPS rather than HTTP"
+    if etag_match || content_length_match || file_match
+      return "The URL #{url} could use HTTPS rather than HTTP"
+    end
+
+    if type == "homepage"
+
+      details[:file] = details[:file].gsub(/https?:\\?\/\\?\//, '/')
+      secure_details[:file] = secure_details[:file].gsub(/https?:\\?\/\\?\//, '/')
+
+      # Same content after normalization
+      if details[:file] == secure_details[:file]
+        return "The URL #{url} could use HTTPS rather than HTTP"
+      end
+
+      # Same size, different content after normalization
+      # (typical causes: Generated ID, Timestamp, Unix time)
+      if details[:file].length == secure_details[:file].length
+        return "The URL #{url} could use HTTPS rather than HTTP"
+      end
+
+      lenratio = (100 * secure_details[:file].length / details[:file].length).to_i
+      if lenratio >= 90 && lenratio <= 120
+        return "The URL #{url} may be able to use HTTPS rather than HTTP. Please verify it in a browser."
+      end
+    end
   end
 
   def self.http_content_headers_and_checksum(url, hash_needed: false, user_agent: :default)
@@ -260,6 +283,7 @@ class FormulaAuditor
       etag: headers[%r{ETag: ([wW]\/)?"(([^"]|\\")*)"}, 2],
       content_length: headers[/Content-Length: (\d+)/, 1],
       file_hash: output_hash,
+      file: output,
     }
   end
 
@@ -564,7 +588,8 @@ class FormulaAuditor
     return unless @online
 
     return unless DevelopmentTools.curl_handles_most_https_homepages?
-    if http_content_problem = FormulaAuditor.check_http_content(homepage,
+    if http_content_problem = FormulaAuditor.check_http_content("homepage",
+                                               homepage,
                                                formula.name,
                                                user_agents: [:browser, :default])
       problem http_content_problem
@@ -1219,7 +1244,8 @@ class ResourceAuditor
         # A `brew mirror`'ed URL is usually not yet reachable at the time of
         # pull request.
         next if url =~ %r{^https://dl.bintray.com/homebrew/mirror/}
-        if http_content_problem = FormulaAuditor.check_http_content(url, name)
+        if http_content_problem = FormulaAuditor.check_http_content("url",
+                                                                    url, name)
           problem http_content_problem
         end
       elsif strategy <= GitDownloadStrategy
```

Mercurial HTTPS URLs aren't a special case, so it'd be enough to let them run through the regular homepage check logic.

**Comment by MikeMcQuaid** [comment]
@vszakats Not embarrassing at all, that looks like a good start. Could you open a pull request? It's much easier to discuss code that way. Thanks!

**Comment by vszakats** [comment]
Opened https://github.com/Homebrew/brew/pull/3096 with the above patch as a start.

**Pull request merged**
