### PR TITLE
Buku 1.9

### PR DESCRIPTION
**Pull request by zmwangx**
https://github.com/jarun/Buku/releases/tag/1.9

### CODE REVIEW

**Comment by DomT4** [comment]
Test is failing:
```
==> /usr/local/Cellar/buku/1.9/bin/buku -a https://github.com/Homebrew/homebrew
Traceback (most recent call last):
  File "/usr/local/Cellar/buku/1.9/bin/buku", line 1160, in <module>
    if encrypt == True:
NameError: name 'encrypt' is not defined
Error: buku: failed
```

**Comment by zmwangx** [comment]
Weird, works locally. I'll take a look a bit later.

**Comment by zmwangx** [comment]
Oops, I was testing on master branch... Yeah indeed it's broken. Sorry about that.

**Comment by zmwangx** [comment]
Upstream issue. I've notified the maintainer. My bad on forgetting to test before submitting.

**Comment by DomT4** [comment]
No worries, these things happen. Thanks for letting upstream know!

**Comment by zmwangx** [comment]
Fixed and retagged. Formula updated accordingly.

**Comment by chulito1** [comment]
Remove tag or follower

**Comment by DomT4** [comment]
@zmwangx Nice, that _was_ a quick fix.

@chulito1 Sorry, I don't understand what you're asking?

**Comment by zmwangx** [comment]
Because it's a trivial fix 😉

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/155e19e8a1c7bc759c8225a3b6bf372b82f82fb3. Thanks again @zmwangx! 😺

**Pull request closed without merging**
