### PR TITLE
edencommon fb303 fbthrift fizz folly mvfst proxygen wangle watchman 2024.01.15.00

### PR DESCRIPTION
**Pull request by timsutton**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
* applies the proxygen patch from [this upstream issue](https://github.com/facebook/proxygen/issues/479#issuecomment-1899292578) to get `proxygen` build + test working again. See https://github.com/Homebrew/homebrew-core/pull/159369 for discussion in last week's versions.
* updates `folly` test since Folly now [assumes C++17 as a minimum](https://github.com/facebook/folly/commit/a8318792992593989f0a87fe3ce53b99f947c6c9)

### CODE REVIEW

**Comment by lnicco** [comment]
Thanks @timsutton for all the help reproducing the issue. 
This commit should fix it
https://github.com/facebook/proxygen/commit/343ffcbba4f97ddc2a31570b429ac71ea59f670e 

Please let us know in case it doesn't

**Comment by timsutton** [comment]
Seeing this in the Linux job:
```
Download action repository 'actions/download-artifact@v3' (SHA:9bc31d5ccc31df68ecc42ccf4149144866c47d8a)
Getting action download info
Error: Bad request - github-early-access/generate-build-provenance@main is not allowed to be used in Homebrew/homebrew-core. Actions in this workflow must be: within a repository owned by Homebrew, created by GitHub, or matching the following: Vampire/setup-wsl@*, codecov/codecov-action@*, google-github-actions/setup-gcloud@*, peter-evans/*, reitermarkus/*, ruby/setup-ruby@*, dessant/lock-threads@*, google-github-actions/auth@*, google-github-actions/get-gke-credentials@*, algolia/algoliasearch-crawler-github-actions@*.
```

**Comment by timsutton** [comment]
@p-linnane or @SMillerDev if you have a moment to review 🙏

**Review by p-linnane — APPROVED** [review]
Amazing work @timsutton! Thank you so much for resolving this long standing `proxygen` issue!

**Pull request merged**
