### PR TITLE
ccache: rework forumula to build without build options

### PR DESCRIPTION
**Pull request by Git-Jiro**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
This PR should fix ccache related issues related to: https://github.com/Homebrew/homebrew-core/issues/13133

@ilovezfs This solution works with ccache --HEAD as well.

### CODE REVIEW

**Comment by Git-Jiro** [comment]
I just noticed, maybe this solution would work as well here: https://github.com/Homebrew/homebrew-core/pull/6402

**Comment by Git-Jiro** [comment]
Yes, this solution seem to apply here as well: https://github.com/Homebrew/homebrew-core/pull/6402

**Comment by ilovezfs** [comment]
@Git-Jiro yeah the question is whether asciidoc built --with-docbook-xsl is actually itself any different from asciidoc built without the option, or if the only difference is the extra dependency itself. I've been suspecting for some time it may be the latter, in which case this would be the correct solution, and we could probably remove the option from asciidoc too.

**Comment by Git-Jiro** [comment]
In case of ccache (and makepkg) both solutions seem to be viable.

**Comment by apjanke** [comment]
I believe the only difference for `asciidoc --with-docbook-xsl` is the dependency. I installed it locally from source using both the default options and `--with-docbook-xsl`, and the only difference in the installed files is in brew's own `INSTALL_RECEIPT`.

```
[~/tmp/asciidoc-with-xsl]
$ diff -r default with-docbook-xsl
diff -r default/asciidoc/8.6.9_1/INSTALL_RECEIPT.json with-docbook-xsl/asciidoc/8.6.9_1/INSTALL_RECEIPT.json
1c1
< {"homebrew_version":"1.3.5-26-gcf34901","used_options":[],"unused_options":["--with-docbook-xsl"],"built_as_bottle":false,"poured_from_bottle":false,"installed_as_dependency":false,"installed_on_request":true,"changed_files":null,"time":1508277128,"source_modified_time":1383773580,"HEAD":"cf349018d5cc508ddd2bd0797df47688b9f7346b","stdlib":null,"compiler":"clang","aliases":[],"runtime_dependencies":[{"full_name":"docbook","version":"5.0"}],"source":{"path":"/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/asciidoc.rb","tap":"homebrew/core","spec":"stable","versions":{"stable":"8.6.9","devel":null,"head":"HEAD","version_scheme":0}}}
\ No newline at end of file
---
> {"homebrew_version":"1.3.5-26-gcf34901","used_options":["--with-docbook-xsl"],"unused_options":[],"built_as_bottle":false,"poured_from_bottle":false,"installed_as_dependency":false,"installed_on_request":true,"changed_files":null,"time":1508277006,"source_modified_time":1383773580,"HEAD":"cf349018d5cc508ddd2bd0797df47688b9f7346b","stdlib":null,"compiler":"clang","aliases":[],"runtime_dependencies":[{"full_name":"docbook","version":"5.0"},{"full_name":"docbook-xsl","version":"1.79.1"}],"source":{"path":"/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/asciidoc.rb","tap":"homebrew/core","spec":"stable","versions":{"stable":"8.6.9","devel":null,"head":"HEAD","version_scheme":0}}}
\ No newline at end of file
[✘ ~/tmp/asciidoc-with-xsl]
$
```

**Comment by Git-Jiro** [comment]
@apjanke @ilovezfs that sounds like the "with-docbook-xsl" option of asciidoc was unnecessary in the first place?

**Comment by JCount** [comment]
@Git-Jiro Thank you for the PR!! 😄

**Pull request merged**
