### PR TITLE
erlang: remove fop as a build dep

### LINKED ISSUE #61770: Erlang: `fop` dependency was added for supporting chunked docs but doesn't appear to be required.
# Bug report

In a previous release of Erlang it appears `fop` was added as a dependency so that Erlang is able to support chunked docs.

See:  http://blog.erlang.org/OTP-23-Highlights/ -- specifically:
> The ordinary doc build is extended with the generation of .chunk files for all OTP modules. You can run make docs DOC_TARGETS=chunks to build only the EEP 48 chunks. Running just make docs without setting the DOC_TARGETS variable will build all formats (html, man, pdf, chunks).

I would like to open a PR to remove `fop` as a dependency, but wanted to discuss via an issue first just in case my assumptions are wrong.

Assuming no one has an issue with this I will open a PR and link it to the ticket.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Remove the `fop` dependency from Erlang. This should speed up the builds as it removes openjdk as an upstream dependency of Erlang.

## What happened (include command output)

I have tested this out locally and as far as I can tell removing the dependency on `fop` works find with otp 23.1

## Step-by-step reproduction instructions (by running `brew install` commands)

- brew edit erlang
- (remove fop dependency)
- brew install erlang
- run `erl` and then ` h(lists,sort,2).` 

you should then see the chunked doc for lists, sort,2.

### PR DESCRIPTION
**Pull request by idyll**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
- [ ] Updated tests to include test for changes...
-----

Fixes #61770

### CODE REVIEW

**Comment by chenrui333** [comment]
heads up, created a new PR for the latest release, #61951

**Comment by iMichka** [comment]
@idyll can you please rebase this on master?

**Comment by idyll** [comment]
I've rebased it @iMichka

**Comment by iMichka** [comment]
@SMillerDev @idyll Do you think a test is still needed? Not sure how important this documentation is. In general we do not focus that much on documentation building in homebrew, as the documentation is best provided directly by upstream on their webpage.

**Comment by idyll** [comment]
@iMichka no. FOP was added in mistake. This just pulls it out.

**Comment by idyll** [comment]
I should note that this PR is what is needed for Erlang to compile on Apple Silicon. Once this is merged Erlang + Elixir are happy on Apple Silicon.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
