### PR TITLE
xarexec 18.07.12 (new formula)

### PR DESCRIPTION
**Pull request by get9**
Introduces Facebook's new [XAR](https://code.fb.com/data-infrastructure/xars-a-more-efficient-open-source-system-for-self-contained-executables/) self-contained executable packaging format. This formula builds and packages the C++ runtime program necessary to mount, extract, and unmount XAR archives.

- [ x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by get9** [comment]
Note that this depends on #28771 before this formula will install properly..

**Comment by ilovezfs** [comment]
The name is going to be overly generic. There are competing packages already distributed as `xar`:
https://repology.org/metapackage/xar/versions

e.g. Apple's is packaged as `xar` by Gentoo
https://github.com/gentoo/gentoo/blob/master/app-arch/xar/xar-1.8-r1.ebuild

We'll need something more specific like facebook-xar or similar

**Comment by get9** [comment]
Seems like CI kinda died, not sure how to kick it off again. Audit returns clean locally though.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@get9 it prints
```
iMac-TMP:~ joe$ xarexec_fuse --help
Usage: xarexec [-m|-n] /path/to/file.xar
Options: 
     -m: mount and print mountpoint, do not execute payload
     -n: print the mountpoint but don't mount
iMac-TMP:~ joe$ 
```
So it seems there is no `--help` option.

Also, why is it saying `xarexec` if the executable is named `xarexec_fuse`?

And note that it crashes if `/mnt/xarfuse` doesn't exist.

```
iMac-TMP:you-get joe$ xarexec_fuse ./dist/you-get.xar 
FATAL /tmp/xarexec-20180719-10714-t6esq9/xar-18.07.12/xar/XarExecFuse.cpp:382: Unable to find suitabe 01777 mount root. Try: mkdir /mnt/xarfuse && chmod 01777 /mnt/xarfuse
Abort trap: 6
iMac-TMP:you-get joe$ 
```
```

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff92be5f06 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff9d6684ec pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff9a51b6df abort + 129
3   xarexec_fuse                  	0x000000010f6d53d0 tools::xar::detail::LogFatal::~LogFatal() + 160
4   xarexec_fuse                  	0x000000010f6d5493 tools::xar::detail::LogFatal::~LogFatal() + 9
5   xarexec_fuse                  	0x000000010f6d108b main + 8881
6   libdyld.dylib                 	0x00007fff9e3365ad start + 1
```

**Comment by ilovezfs** [comment]
>Unable to find suitabe 01777 mount root.

and note spelling of "suitable"

**Pull request closed without merging**
