### PR TITLE
lnav 0.11.1

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
They moved from `pcre` to `pcre2`, however some things are not clear  in this formula for me:
- `re2c` is a dependency only for `head`;
- `ncurses`, `wireshark`, `bz2`, `zlib` are missing from dependencies.

All those dependencies are marked as needed here: https://github.com/tstack/lnav/blob/1faa95df94ee53011ac10ead2814ab62a7ee5509/README#L18-L31 and are not new dependencies either (already needed on previous version bump, as opposed to `pcre2` that is new).

**Review by fxcoudert — APPROVED** [review]

**Comment by Porkepix** [comment]
@fxcoudert Are those dependencies I talk about above not needed?

**Comment by SMillerDev** [comment]
Seeing that it works, I would assume not

**Comment by tstack** [comment]
> some things are not clear in this formula for me:
>
> * re2c is a dependency only for head;

The `re2c` command is only used in development builds.  The output of it is checked into the source tree to reduce dependencies when building from source.

> * ncurses, wireshark, bz2, zlib are missing from dependencies.

I think the `ncurses`, `bz2`, and `zlib` libraries are picked up from the system.  The wireshark dependency is only on the `tshark` command and that is detected at runtime, if it's available.

**Comment by Porkepix** [comment]
> I think the `ncurses`, `bz2`, and `zlib` libraries are picked up from the system. The wireshark dependency is only on the `tshark` command and that is detected at runtime, if it's available.

So, should the tool be considered as incomplete without Wireshark support? Should it be added?

**Comment by tstack** [comment]
> So, should the tool be considered as incomplete without Wireshark support? Should it be added?

No, it's an optional dependency really.  The `tshark` command is used by lnav to process pcap files, which the vast majority of folks are not going to be working with.

**Pull request closed without merging**
