### PR TITLE
Add versioned aliases for formulae.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
This will be checked by `brew audit` when https://github.com/Homebrew/brew/pull/1850 is merged so let's get this ready to ship at the same time.

### CODE REVIEW

**Comment by ilovezfs** [comment]
tomcat@8.0 is a formula

**Comment by DomT4** [comment]
`openssl@1.0` is potentially confusing. There's two branches that could be, 1.0.1 which is deprecated and no longer has security updates applied but is still living in `homebrew/versions`, and 1.0.2 which is LTS & supported until 2019 (IIRC).

**Comment by ilovezfs** [comment]
@DomT4 I assume the rememdy is to delete https://github.com/Homebrew/homebrew-versions/blob/master/openssl101.rb ?

**Comment by DomT4** [comment]
@ilovezfs Whatever the decision made about the versioned name you wish to use here for `openssl`, yes, that `openssl101` formula should've died at the start of the year really.

**Comment by MikeMcQuaid** [comment]
> tomcat@8.0 is a formula

Yeh, that was added to test that https://github.com/Homebrew/brew/pull/1850 goes 💥 on this.

**Comment by ilovezfs** [comment]
>Yeh, that was added to test that Homebrew/brew#1850 goes :boom: on this.

Hehe ... and you thought I wasn't paying attention!

**Comment by MikeMcQuaid** [comment]
> Hehe ... and you thought I wasn't paying attention!

@ilovezfs If anything you pay too much attention 😉

**Comment by ilovezfs** [comment]
@DomT4 I've removed openssl101: https://github.com/Homebrew/homebrew-versions/pull/1528

**Review by ilovezfs — APPROVED** [review]
assuming tomcat@8.0 is removed

**Comment by DomT4** [comment]
Thanks @ilovezfs ❤️

**Comment by MikeMcQuaid** [comment]
Confirmed CI failure: 

> Error: Broken alias: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/tomcat@8.0

**Comment by ilovezfs** [comment]
hurray!

**Pull request merged**
