### PR TITLE
consul-backinator: update to v1.3

### PR DESCRIPTION
**Pull request by aaronhurt**
Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Update to latest release.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks for the upgrade @leprechau!

Note that commit subjects are standardized for version upgrades as follows:
```
==> Applying patch
Applying: consul-backinator: update to v1.3
==> Patch closes issue #5748
Warning: Nonstandard bump subject: consul-backinator: update to v1.3
Warning: Subject should be: consul-backinator 1.3
```

**Comment by leprechau** [comment]
Alright, thank you.  I'll remember that for future reference.

**Pull request closed without merging**
