### PR TITLE
node 10.2.0

### PR DESCRIPTION
**Pull request by dio-az**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@chrmoritz any ideas?

**Comment by chrmoritz** [comment]
```
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  /usr/bin/clang++ '-DNODE_GYP_MODULE_NAME=bufferutil' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/tmp/node-test-20180524-59556-1tu9kmv/.node-gyp/10.2.0/include/node -I/tmp/node-test-20180524-59556-1tu9kmv/.node-gyp/10.2.0/src -I/tmp/node-test-20180524-59556-1tu9kmv/.node-gyp/10.2.0/deps/uv/include -I/tmp/node-test-20180524-59556-1tu9kmv/.node-gyp/10.2.0/deps/v8/include -I../../nan  -Os -gdwarf-2 -mmacosx-version-min=10.8 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/bufferutil/src/bufferutil.o.d.raw -F/usr/local/Frameworks -Os -w -pipe -march=native -Xclang -target-feature -Xclang -aes -mmacosx-version-min=10.11 -c -o Release/obj.target/bufferutil/src/bufferutil.o ../src/bufferutil.cc
In file included from ../src/bufferutil.cc:7:
In file included from ../../nan/nan.h:51:
/tmp/node-test-20180524-59556-1tu9kmv/.node-gyp/10.2.0/include/node/node.h:53:10: fatal error: 'core.h' file not found
#include "core.h"  // NOLINT(build/include_order)
         ^
1 error generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
```

It's caused by https://github.com/nodejs/node/issues/20921, which should be fixed in the upcoming 10.2.1 release.

**Comment by ilovezfs** [comment]
Thanks for finding that @chrmoritz

**Comment by chrmoritz** [comment]
A fix for it landed upstream in https://github.com/nodejs/node/commit/3f4caec1d1e6f2c75d2339db21920dc349986682. A new 10.2.1 release should follow shortly.

**Comment by diogoazevedos** [comment]
Fixed in #28247

**Pull request closed without merging**
