### PR TITLE
publish-commit-bottles: autosquash PR branches

### PR DESCRIPTION
**Pull request by carlocab**
Another attempt at #126463.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
> That would give us more flexibility if `gh` is limited and we want to be able to use the force with lease option.

I'd rather we relied more heavily on `gh` rather than the other way around. We already maintain IMO too much boilerplate code that `gh` can do for us more simply.

**Review by MikeMcQuaid — APPROVED** [review]
Seems fine. As I've said before: I'd really like to try and get much more of this custom logic out of the workflow files. They are essentially untested/untestable as-is.

**Comment by carlocab** [comment]
Homebrew/actions#340

**Comment by MikeMcQuaid** [comment]
@carlocab The `gh` testing probably pushed this actual PR to `master`. Another reason I want to see this workflow get default sooner rather than later to stop this being possible 😅

**Comment by carlocab** [comment]
I thought that too. I looked for a workflow run for it, but couldn't find it. But, fine, let's try to get this in shape to 🚢

**Comment by MikeMcQuaid** [comment]
@carlocab my guess is something like this did it: https://github.com/Homebrew/homebrew-core/actions/runs/4534120757/jobs/7987877819#step:12:46

**Comment by carlocab** [comment]
> @carlocab my guess is something like this did it: https://github.com/Homebrew/homebrew-core/actions/runs/4534120757/jobs/7987877819#step:12:46

That would be a surprise to me, because previously you couldn't do `brew pr-publish` PRs that change workflow files 🤷

**Comment by carlocab** [comment]
Success: https://github.com/Homebrew/homebrew-core/actions/runs/4534453300/jobs/7988647577

**Pull request merged**
