### PR TITLE
kitchen-sync 0.54

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍. Test is a bit weird, but I presume it's doing something useful.

**Comment by ilovezfs** [comment]
How does this sound
```
    output = shell_output("#{bin}/ks --from a://b/ --to c://d/")
    assert_match "Finished Kitchen Syncing", output
```

```
iMac-TMP:~ joe$ brew test -v kitchen-sync
Testing kitchen-sync
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160816-77002-d5qh6q.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/kitchen-sync.rb -v
==> /usr/local/Cellar/kitchen-sync/0.54/bin/ks --from a://b/ --to c://d/
Couldn't exec /usr/local/Cellar/kitchen-sync/0.54/bin/ks_a: No such file or directory
Couldn't exec /usr/local/Cellar/kitchen-sync/0.54/bin/ks_c: No such file or directory
iMac-TMP:~ joe$ 
```

**Comment by DomT4** [comment]
What's with the `No such file or directory` messages there?

**Comment by ilovezfs** [comment]
the test is nonsense of course :)
```
  --from url                 The URL of the database to copy data from.  
                             Required.

  --to url                   The URL of the database to copy data to.  
                             Required.
```

**Comment by DomT4** [comment]
Ah, I see. I'd possibly `2>&1` it so the output doesn't confuse people (_cough_ me _cough_), but either way, seems an improvement.

**Comment by ilovezfs** [comment]
Yeah that seems reasonable. I'm against wasting brain cycles if it can be avoided. The hilarious part is that that test exits zero, whereas the usage message exits 1 even if you pass --help or --version :see_no_evil:

**Comment by DomT4** [comment]
> The hilarious part is that that test exits zero, whereas the usage message exits 1 even if you pass --help or --version

Oh dear.

👍 on this PR.

**Pull request closed without merging**
