### PR TITLE
namazu: Add upstream patch to fix search error due to memory corruption

### PR DESCRIPTION
**Pull request by weisslj**
See http://cvs.namazu.org/Development/namazu/nmz/search.c?r1=1.116&r2=1.117&view=patch

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why not just use the URL for the patch data?

**Comment by weisslj** [comment]
Any update?

**Comment by weisslj** [comment]
What is missing to get this merged?

**Comment by SMillerDev** [comment]
@ilovezfs?

**Comment by fxcoudert** [comment]
Thanks @weisslj for the suggestion.

Upstream should issue a new release, rather than us considering patching issues one at a time. We typically only consider patches for issues that prevent build or render the software completely unusable. Please encourage namazu to make a new release!

**Comment by weisslj** [comment]
@fxcoudert: Thanks for the explanation!

**Comment by weisslj** [comment]
@fxcoudert I contacted upstream: Namazu is preparing the next stable release 2.0.22 since 2013, but it cannot be released just now, and a long time is still needed for the preparation:

- 2.0.22 pre1 release Sat, 19 Jan 2013
         :
- 2.0.22 pre7 release Fri, 13 Jan 2017

The error mentioned can be considered critical because of the memory corruption (although I do not know if it counts as security issue). Can the patch be included considering this information?

**Pull request closed without merging**
