### PR TITLE
node 18.1.0

### PR DESCRIPTION
**Pull request by bevanjkay**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by derrabus** [comment]
npm needs to be bumped to 8.8.0, see nodejs/node#42886

**Comment by bevanjkay** [comment]
Thanks @branchvincent  - sorry I thought the PR hadn't gone through due to a duplicate.

**Comment by derrabus** [comment]
> Error: PR requires the CI-long-timeout label but it is not set!
> Error: If the longer timeout is not required, remove the "long build" label.
> Error: Otherwise, add the "CI-long-timeout" label.
> Error: No more than 2 PRs at a time may use "CI-long-timeout".

Can you please add the `CI-long-timeout` label, @branchvincent?

**Comment by bevanjkay** [comment]
@derrabus There is only a limited amount of long-timeout slots available, so CI cannot be restarted at the moment.
Here's the full run with the failures from the original tests - https://github.com/Homebrew/homebrew-core/actions/runs/2266546607

**Comment by bevanjkay** [comment]
Seems to have been tracked upstream 

https://github.com/nodejs/node/pull/42701#issuecomment-1120736485

**Comment by bevanjkay** [comment]
The test for emscripten will pass with the flag `--no-experimental-fetch` - https://github.com/emscripten-core/emscripten/issues/16913

**Comment by bevanjkay** [comment]
#101576 update should fix `bash-language-server`

**Comment by bevanjkay** [comment]
@branchvincent Do we usually fix the tests in a separate PR? I think this should be green now.

**Comment by faradaytrs** [comment]
Could we merge this?

**Comment by derrabus** [comment]
node 18.2.0 has been released, bumping NPM to 8.9.0: https://github.com/nodejs/node/releases/tag/v18.2.0

**Comment by chenrui333** [comment]
maybe let's merge this one and fix the failures and then start 18.2.0 journey.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
only `bash-language-server` failed on all builds, I will do a merge and follow up to see if that is reproducible.

**Pull request closed without merging**
