### PR TITLE
diffstat 1.63

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
16:59:26 ==> brew install --verbose --build-bottle diffstat
17:00:45 ==> FAILED
17:00:45 /usr/bin/sandbox-exec -f /private/tmp/homebrew20191203-88336-151fdoc.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/diffstat.rb --build-bottle --verbose
17:00:45 ==> Downloading https://invisible-mirror.net/archives/diffstat/diffstat-1.63.tgz
17:00:45 Error: An exception occurred within a child process:
17:00:45   ChecksumMismatchError: SHA256 mismatch
17:00:45 Expected: 8b437d545d2c95b2a0e3f43274112891ad1867fb3e746f0753438b4794e9f35d
17:00:45   Actual: 7eddd53401b99b90bac3f7ebf23dd583d7d99c6106e67a4f1161b7a20110dc6f
17:00:45  Archive: /Users/brew/Library/Caches/Homebrew/downloads/a3968beeb901957f424a144673986ef4083e726b0201a2f2040ab675ce03b9e2--diffstat-1.63.tgz
17:00:45 To retry an incomplete download, remove the file above.

**Comment by alebcay** [comment]
For whatever reason, the URL yields a different file for me when downloaded via Firefox vs `wget`/`curl`.

**Comment by chenrui333** [comment]
Mine is below:
$ shasum -a 256 diffstat-1.63.tar
7eddd53401b99b90bac3f7ebf23dd583d7d99c6106e67a4f1161b7a20110dc6f  diffstat-1.63.tar

**Comment by chenrui333** [comment]
Could that be the artifact change in the upstream?

**Comment by alebcay** [comment]
With browser download (Firefox 71.0), I'm seeing
```
8b437d545d2c95b2a0e3f43274112891ad1867fb3e746f0753438b4794e9f35d  diffstat-1.63.tgz
```

With `wget`, I'm seeing
```
7eddd53401b99b90bac3f7ebf23dd583d7d99c6106e67a4f1161b7a20110dc6f  diffstat-1.63.tgz
```

With `curl`, I'm seeing
```
7eddd53401b99b90bac3f7ebf23dd583d7d99c6106e67a4f1161b7a20110dc6f  diffstat-1.63.tgz
```

**Pull request closed without merging**
