### PR TITLE
ansible 2.3.2.0

### PR DESCRIPTION
**Pull request by msvab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
The resource blocks should be updated too.

**Comment by PikachuEXE** [comment]
@ilovezfs all resource blocks?

**Comment by ilovezfs** [comment]
@PikachuEXE for example, see https://github.com/Homebrew/homebrew-core/pull/14172/files.

**Comment by msvab** [comment]
Updated

**Comment by ilovezfs** [comment]
```
Error Message

failed: brew style ansible

Stacktrace

        == /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ansible.rb ==
W: 43:  5: end at 43, 4 is not aligned with resource "pbr" do at 40, 2.

1 file inspected, 1 offense detected
```

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @msvab!

**Pull request closed without merging**
