### PR TITLE
arkade 0.9.7

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Can you disable the "allow maintainers to edit pull request" option here? I want to test my fall back PR.

**Comment by carlocab** [comment]
> It seems I can only untick "Allow edits and access to secrets by maintainers" on this page.

Yup, that's exactly what's needed. Thanks!

**Comment by carlocab** [comment]
Nope; doesn't work 😢

This needs to be merged with `--warn-on-upload-failure`.

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
Oops, still can't push. Can you enable pushing to your branch now here?

**Comment by ZhongRuoyu** [comment]
Okay! Re-enabled.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
