### PR TITLE
fceux 2.6.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by branchvincent** [comment]
website hasn't been updated yet: https://fceux.com/web/home.html

**Comment by chenrui333** [comment]
the website has the version, https://fceux.com/web/version.html, but just not announce it yet.

**Comment by carlocab** [comment]
Released here: https://github.com/TASEmulators/fceux/releases

Seems good enough to me.

**Review by carlocab — APPROVED** [review]

**Review by branchv — APPROVED** [review]
works for me

**Pull request closed without merging**
