### PR TITLE
pyside 6.4.2

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  pyside:
    * Files were found with references to the Homebrew shims directory.
      The offending files are:
        bin/shiboken6
```

**Comment by p-linnane** [comment]
Successfully built with `python@3.11`. Just need some help with the Linux audit failure.

**Review by iMichka — APPROVED** [review]

**Comment by p-linnane** [comment]
Thank you @danielnachun!

**Comment by danielnachun** [comment]
FYI `pyside` is still broken on Linux, but that's because of a test failure, not an audit failure.  For some reason the test binaries for both `pyside@2` and `pyside` segfault.  I've looked at the test binary and core dump in GDB for both and it seems uninformative so far.  I'm adding `pyside` and `pyside@2` (and `coin3d` which depends on pyside@2` to our list of unbottled formulae on Linux until we can figure out what is wrong with them, as the test program is extremely simple and the problem is likely buried deeply in `pyside`/`pyside@2`.

**Pull request closed without merging**
