### PR TITLE
open-scene-graph: avoid opportunistic linkage

### PR DESCRIPTION
**Pull request by apjanke**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Addresses #16531.

Avoids opportunistic linkage.

### CODE REVIEW

**Comment by ilovezfs** [comment]
We've generally standardized on all caps `=ON` and `=OFF`

**Comment by apjanke** [comment]
Updated.

**Comment by ilovezfs** [comment]
Thanks @apjanke! :rocket:

**Comment by apjanke** [comment]
:+1:

**Pull request merged**
