### PR TITLE
imagemagick@6: fix audit

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`brew bottle` bug?

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> brew bottle bug?

I think it's never going to be quite perfect because it's a crude regex rewriting Ruby. If it can be fixed, great, but it doesn't seem high priority. Thanks for the fix, though ⚡️

**Comment by zmwangx** [comment]
> I think it's never going to be quite perfect

No big deal.

**Comment by ilovezfs** [comment]
I've seen this happen in science a lot when they use comments at the top.

**Comment by zmwangx** [comment]
Expanding the regexp to allow comments should help a lot:

```diff
diff --git a/Library/Homebrew/dev-cmd/bottle.rb b/Library/Homebrew/dev-cmd/bottle.rb
index 9618cf4121..b867328828 100644
--- a/Library/Homebrew/dev-cmd/bottle.rb
+++ b/Library/Homebrew/dev-cmd/bottle.rb
@@ -435,6 +435,7 @@ module Homebrew
             else
               string = s.sub!(
                 /(
+                  (\ {2}\#.*\n)*                                                 # comments
                   \ {2}(                                                         # two spaces at the beginning
                     (url|head)\ ['"][\S\ ]+['"]                                  # url or head with a string
                     (
```

**Comment by zmwangx** [comment]
Opened https://github.com/Homebrew/brew/pull/1868 with this trivial change.

**Comment by MikeMcQuaid** [comment]
Thanks again @zmwangx!

**Pull request merged**
