### PR TITLE
harfbuzz 8.2.1

### PR DESCRIPTION
**Pull request by chiefmikey**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
sorry this pr has to wait a bit.

**Comment by fxcoudert** [comment]
```
Warning: 3 failed steps ignored!
brew test --retry --verbose beast
brew linkage --cached --test --strict pyside
brew linkage --cached --test --strict wxmaxima
Error: 2 failed steps!
brew test --retry --verbose solr@8.11
brew test --retry --verbose trino
```

Failures are consistent across macOS versions, and appear unrelated (all java-related). Unless someone objects, I intend to merge this.

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
```
    * Binaries built for a non-native architecture were installed into vercel-cli's prefix.
      The offending files are:
        /opt/homebrew/Cellar/vercel-cli/32.3.1/libexec/lib/node_modules/vercel/node_modules/fsevents/fsevents.node	(x86_64)
```

LOL

**Comment by ZhongRuoyu** [comment]
`solr@8.11` and `trino` are pre-existing (and hence unrelated).

There's also an `ammonite-repl` failure on Linux, which is kinda concerning. It first surfaced in the `openjdk` 21 PR, but presumably we should already have addressed it by switching to `openjdk@17` in #144278.

Anyway, I don't think that's related to `harfbuzz` either.

**Pull request merged**
