### PR TITLE
cql 0.6.0

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by fxcoudert** [comment]
Test failure:

```
==> /usr/local/Cellar/cql/0.6.0/bin/cql generate -config /private/tmp/cql-test-20190515-11202-lhy8p5/confgen -no-password config
flag provided but not defined: -config
usage: cql generate [common params] [-source template_file] [-miner] [-private existing_private_key] [dest_path]
Run 'cql help generate' for details.
Error: cql: failed
```

**Comment by chenrui333** [comment]
Cool! Checking now.

**Comment by chenrui333** [comment]
@fxcoudert should be fixed now, I have install and test locally.

**Comment by fxcoudert** [comment]
@chenrui333 thanks, but please mind the commit messages, so that they match the formula name

**Comment by chenrui333** [comment]
yeah, you are right!

**Comment by chenrui333** [comment]
I updated the PR to remind me what I would do in the future.

**Pull request closed without merging**
