### PR TITLE
apache-arrow-glib apache-arrow 12.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
/tmp/vineyard-20230501-64018-1c9lxjq/v6d-0.14.3/modules/basic/ds/arrow.cc:335:30: error: variable type 'memory::VineyardMemoryPool' is an abstract class
    memory::VineyardMemoryPool pool(client);
                               ^
  /opt/homebrew/include/arrow/memory_pool.h:141:19: note: unimplemented pure virtual method 'total_bytes_allocated' in 'VineyardMemoryPool'
    virtual int64_t total_bytes_allocated() const = 0;
                    ^
  /opt/homebrew/include/arrow/memory_pool.h:144:19: note: unimplemented pure virtual method 'num_allocations' in 'VineyardMemoryPool'
    virtual int64_t num_allocations() const = 0;
                    ^
  /tmp/vineyard-20230[501](https://github.com/Homebrew/homebrew-core/actions/runs/4857452242/jobs/8658026410?pr=129859#step:8:502)-64018-1c9lxjq/v6d-0.14.3/modules/basic/ds/arrow.cc:456:30: error: variable type 'memory::VineyardMemoryPool' is an abstract class
    memory::VineyardMemoryPool pool(client);
                               ^
  /tmp/vineyard-20230501-64018-1c9lxjq/v6d-0.14.3/modules/basic/ds/arrow.cc:526:30: error: variable type 'memory::VineyardMemoryPool' is an abstract class
    memory::VineyardMemoryPool pool(client);
                               ^
  /tmp/vineyard-20230501-64018-1c9lxjq/v6d-0.14.3/modules/basic/ds/arrow.cc:595:30: error: variable type 'memory::VineyardMemoryPool' is an abstract class
    memory::VineyardMemoryPool pool(client);
                               ^
  /tmp/vineyard-20230501-64018-1c9lxjq/v6d-0.14.3/modules/basic/ds/arrow.cc:647:30: error: variable type 'memory::VineyardMemoryPool' is an abstract class
    memory::VineyardMemoryPool pool(client);
                               ^
```

**Review by raulcd — COMMENTED** [review]
Thanks for the PR.
We also have to remove `PLASMA` and enable `ACERO`, as discussed on the Mailing list from: https://lists.apache.org/thread/2stklo8dgpgn4dkq2lmvy4483jqcxzgx
```diff
$ git diff
diff --git a/Formula/apache-arrow.rb b/Formula/apache-arrow.rb
index f0d3868..520448b 100644
--- a/Formula/apache-arrow.rb
+++ b/Formula/apache-arrow.rb
@@ -46,6 +46,7 @@ class ApacheArrow < Formula
 
     args = %W[
       -DCMAKE_INSTALL_RPATH=#{rpath}
+      -DARROW_ACERO=ON
       -DARROW_COMPUTE=ON
       -DARROW_CSV=ON
       -DARROW_DATASET=ON
@@ -57,7 +58,6 @@ class ApacheArrow < Formula
       -DARROW_JSON=ON
       -DARROW_ORC=ON
       -DARROW_PARQUET=ON
-      -DARROW_PLASMA=ON
       -DARROW_PROTOBUF_USE_SHARED=ON
       -DARROW_S3=ON
       -DARROW_WITH_BZ2=ON
```

**Comment by raulcd** [comment]
It does seem vineyard hasn't implemented the changes on their `VineyardMemoryPool` to support arrow 12.0.0:
https://github.com/v6d-io/v6d/blob/a4af21dd23df131415a89d22e4f66987cb1a8f2e/modules/basic/ds/arrow_shim/memory_pool.h#L33
Should we pin arrow 11.0.0 on vineyard?
```
depends_on "apache-arrow@11.0.0"
```
This is the PR that included those on arrow: https://github.com/apache/arrow/pull/33731
And the current issue on vineyard as pointed above:
```
   /tmp/vineyard-20230503-55118-14bq3js/v6d-0.14.3/modules/basic/ds/arrow.cc:335:30: error: variable type 'memory::VineyardMemoryPool' is an abstract class
    memory::VineyardMemoryPool pool(client);
                               ^
  /opt/homebrew/include/arrow/memory_pool.h:141:19: note: unimplemented pure virtual method 'total_bytes_allocated' in 'VineyardMemoryPool'
    virtual int64_t total_bytes_allocated() const = 0;
                    ^
  /opt/homebrew/include/arrow/memory_pool.h:144:19: note: unimplemented pure virtual method 'num_allocations' in 'VineyardMemoryPool'
    virtual int64_t num_allocations() const = 0;
                    ^
  /tmp/vineyard-20230503-55118-14bq3js/v6d-0.14.3/modules/basic/ds/arrow.cc:456:30: error: variable type 'memory::VineyardMemoryPool' is an abstract class
    memory::VineyardMemoryPool pool(client);
                               ^
  /tmp/vineyard-20230503-55118-14bq3js/v6d-0.14.3/modules/basic/ds/arrow.cc:526:30: error: variable type 'memory::VineyardMemoryPool' is an abstract class
    memory::VineyardMemoryPool pool(client);
                               ^
  /tmp/vineyard-20230503-55118-14bq3js/v6d-0.14.3/modules/basic/ds/arrow.cc:595:30: error: variable type 'memory::VineyardMemoryPool' is an abstract class
    memory::VineyardMemoryPool pool(client);
                               ^
  /tmp/vineyard-20230503-55118-14bq3js/v6d-0.14.3/modules/basic/ds/arrow.cc:647:30: error: variable type 'memory::VineyardMemoryPool' is an abstract class
    memory::VineyardMemoryPool pool(client);
                               ^
```
cc @kou

**Comment by SMillerDev** [comment]
> Should we pin arrow 11.0.0 on vineyard?

Is that version gonna be supported long term?

**Comment by kou** [comment]
> Is that version gonna be supported long term?

Unfortunately, no...

**Comment by kou** [comment]
How about backporting https://github.com/v6d-io/v6d/pull/1359 ?

**Comment by kou** [comment]
0.14.4 may be released soon: https://github.com/v6d-io/v6d/commit/9bc031aee212bbdb9c9cd20d9b64a9ad8589d2d1

**Comment by sighingnow** [comment]
> 0.14.4 may be released soon: [v6d-io/v6d@9bc031a](https://github.com/v6d-io/v6d/commit/9bc031aee212bbdb9c9cd20d9b64a9ad8589d2d1)

I have submit a pull request to bump up the version: https://github.com/Homebrew/homebrew-core/pull/130424

**Comment by sighingnow** [comment]
I'm working on the vineyard failure. Sorry for the break.

**Comment by carlocab** [comment]
```
  In file included from /tmp/vineyard-20230507-94520-18we7kx/v6d-0.14.4/modules/basic/ds/arrow_shim/concatenate.cc:59:
  /opt/homebrew/include/arrow/visit_type_inline.h:54:34: error: no matching member function for call to 'Visit'
      ARROW_GENERATE_FOR_ALL_TYPES(TYPE_VISIT_INLINE);
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
  /opt/homebrew/include/arrow/visitor_generate.h:66:3: note: expanded from macro 'ARROW_GENERATE_FOR_ALL_TYPES'
    ACTION(RunEndEncoded);                        \
    ^~~~~~~~~~~~~~~~~~~~~
  /opt/homebrew/include/arrow/visit_type_inline.h:29:21: note: expanded from macro 'TYPE_VISIT_INLINE'
      return visitor->Visit(internal::checked_cast<const TYPE_CLASS##Type&>(type), \
             ~~~~~~~~~^~~~~
  /tmp/vineyard-20230507-94520-18we7kx/v6d-0.14.4/modules/basic/ds/arrow_shim/concatenate.cc:247:19: note: in instantiation of function template specialization 'arrow::VisitTypeInline<vineyard::arrow_shim::(anonymous namespace)::ConcatenateImpl>' requested here
      RETURN_NOT_OK(VisitTypeInline(*out_->type, this));
                    ^
  /tmp/vineyard-20230507-94520-18we7kx/v6d-0.14.4/modules/basic/ds/arrow_shim/concatenate.cc:252:10: note: candidate function not viable: no known conversion from 'const arrow::RunEndEncodedType' to 'const arrow::NullType' for 1st argument
    Status Visit(const NullType&) { return Status::OK(); }
           ^
  /tmp/vineyard-20230507-94520-18we7kx/v6d-0.14.4/modules/basic/ds/arrow_shim/concatenate.cc:254:10: note: candidate function not viable: no known conversion from 'const arrow::RunEndEncodedType' to 'const arrow::BooleanType' for 1st argument
    Status Visit(const BooleanType&) {
           ^
  /tmp/vineyard-20230507-94520-18we7kx/v6d-0.14.4/modules/basic/ds/arrow_shim/concatenate.cc:258:10: note: candidate function not viable: no known conversion from 'const arrow::RunEndEncodedType' to 'const arrow::FixedWidthType' for 1st argument
    Status Visit(const FixedWidthType& fixed) {
           ^
  /tmp/vineyard-20230507-94520-18we7kx/v6d-0.14.4/modules/basic/ds/arrow_shim/concatenate.cc:265:10: note: candidate function not viable: no known conversion from 'const arrow::RunEndEncodedType' to 'const arrow::BinaryType' for 1st argument
    Status Visit(const BinaryType&) {
           ^
  /tmp/vineyard-20230507-94520-18we7kx/v6d-0.14.4/modules/basic/ds/arrow_shim/concatenate.cc:275:10: note: candidate function not viable: no known conversion from 'const arrow::RunEndEncodedType' to 'const arrow::LargeBinaryType' for 1st argument
    Status Visit(const LargeBinaryType&) {
           ^
  /tmp/vineyard-20230507-94520-18we7kx/v6d-0.14.4/modules/basic/ds/arrow_shim/concatenate.cc:285:10: note: candidate function not viable: no known conversion from 'const arrow::RunEndEncodedType' to 'const arrow::ListType' for 1st argument
    Status Visit(const ListType&) {
           ^
  /tmp/vineyard-20230507-94520-18we7kx/v6d-0.14.4/modules/basic/ds/arrow_shim/concatenate.cc:295:10: note: candidate function not viable: no known conversion from 'const arrow::RunEndEncodedType' to 'const arrow::LargeListType' for 1st argument
    Status Visit(const LargeListType&) {
           ^
  /tmp/vineyard-20230507-94520-18we7kx/v6d-0.14.4/modules/basic/ds/arrow_shim/concatenate.cc:305:10: note: candidate function not viable: no known conversion from 'const arrow::RunEndEncodedType' to 'const arrow::FixedSizeListType' for 1st argument
    Status Visit(const FixedSizeListType& fixed_size_list) {
           ^
  /tmp/vineyard-20230507-94520-18we7kx/v6d-0.14.4/modules/basic/ds/arrow_shim/concatenate.cc:312:10: note: candidate function not viable: no known conversion from 'const arrow::RunEndEncodedType' to 'const arrow::StructType' for 1st argument
    Status Visit(const StructType& s) {
           ^
  /tmp/vineyard-20230507-94520-18we7kx/v6d-0.14.4/modules/basic/ds/arrow_shim/concatenate.cc:391:10: note: candidate function not viable: no known conversion from 'const arrow::RunEndEncodedType' to 'const arrow::DictionaryType' for 1st argument
    Status Visit(const DictionaryType& d) {
           ^
  /tmp/vineyard-20230507-94520-18we7kx/v6d-0.14.4/modules/basic/ds/arrow_shim/concatenate.cc:419:10: note: candidate function not viable: no known conversion from 'const arrow::RunEndEncodedType' to 'const arrow::UnionType' for 1st argument
    Status Visit(const UnionType& u) {
           ^
  /tmp/vineyard-20230507-94520-18we7kx/v6d-0.14.4/modules/basic/ds/arrow_shim/concatenate.cc:509:10: note: candidate function not viable: no known conversion from 'const arrow::RunEndEncodedType' to 'const arrow::ExtensionType' for 1st argument
    Status Visit(const ExtensionType& e) {
           ^
  1 error generated.
  make[2]: *** [modules/basic/CMakeFiles/vineyard_basic.dir/ds/arrow_shim/concatenate.cc.o] Error 1
  make[1]: *** [modules/basic/CMakeFiles/vineyard_basic.dir/all] Error 2
```
https://github.com/Homebrew/homebrew-core/actions/runs/4910846169/jobs/8768426022?pr=129859#step:3:502

**Comment by sighingnow** [comment]
I have published a quick bugfix release. Could someone help me to cherry-pick https://github.com/Homebrew/homebrew-core/pull/130429 to this pull request?

**Comment by raulcd** [comment]
I am not sure why the jobs were cancelled. Could it be timeout after 45 minutes? I recall we usually add the `long-ci-build` labels when adding new versions.

**Review by fxcoudert — APPROVED** [review]

**Pull request merged**
