### PR TITLE
lsyncd: xnu headers for 10.13

### PR DESCRIPTION
**Pull request by fxcoudert**

### CODE REVIEW

**Comment by DomT4** [comment]
Might want to chuck in `10.13.1` here as well. First beta has already landed 😸.

**Comment by fxcoudert** [comment]
Apple only publishes them after release: https://opensource.apple.com

**Comment by DomT4** [comment]
Yeah, I'm aware. Historically we've just chucked the last known version on until more information becomes available. It's less ugly than the formula simply starting to blow up the day people upgrade to 10.13.1, whether now or when it drops stable.

**Comment by ilovezfs** [comment]
What he said

**Pull request merged**
