### PR TITLE
crystal: align with linux

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
```
2020-12-12T14:50:57.7591300Z [34m==>[0m [1mmake deps[0m
2020-12-12T14:50:57.7592760Z Makefile:57: *** Could not locate llvm-config, make sure it is installed and in your PATH, or set LLVM_CONFIG.  Stop.
2020-12-12T14:50:57.7593470Z 
2020-12-12T14:50:57.7594380Z [34m==>[0m [1mFormula[0m
2020-12-12T14:50:57.7595800Z Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/crystal.rb
```

**Comment by dawidd6** [comment]
https://github.com/Homebrew/homebrew-core/pull/65221

**Comment by SeekingMeaning** [comment]
Needs llvm@9, maybe add that change here instead?

**Comment by SeekingMeaning** [comment]
Tests succeeded after CI requeue

**Review by dawidd6 — APPROVED** [review]

**Comment by mitchblank** [comment]
Now that this is merged can somebody try rebottling `oq` and `crystal-icr` which may be OK now on big sur?

**Pull request closed without merging**
