### PR TITLE
diffoscope: switch to hosted patch

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
👍 but was this even submitted upstream?

**Comment by zmwangx** [comment]
@MikeMcQuaid It's on upstream cgit so it is submitted upstream. Also, the patch reads

```diff
From 261be7c7bd911092d6703f2f9e370818055b9b9e Mon Sep 17 00:00:00 2001
From: Mike McQuaid <mike@mikemcquaid.com>
Date: Wed, 2 Dec 2015 13:16:36 +0200
Subject: Support older versions of GNU diff.
```

so you know it better than me...

**Comment by MikeMcQuaid** [comment]
@zmwangx LOL. Naughty past-@MikeMcQuaid.

**Comment by MikeMcQuaid** [comment]
Thanks for cleaning up my mess!

**Comment by zmwangx** [comment]
No problem, shipped.

**Pull request closed without merging**
