### PR TITLE
python{,@2}: setuptools 40.2.0

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
I aborted the build because we're into _"just a ridiculous amount of CI time"_ territory and the other CI is being eaten by the `boost` build going on at the same time. You can pull this one as-is without needing another CI run though; it got more than far enough to generate new `python` bottles and show these changes aren't introducing new problems.

**Comment by DomT4** [comment]
Scrub that; the El Cap CI apparently had a complete meltdown and hasn't handled the build artefacts properly. I loathe CI with a passion sometimes 🙃🙃🙃 . One of us can whack this back on the queue later for the benefit of supporting El Cap with bottles for another month or so, but let's try and wait till the `boost` PR is through CI at least.

**Comment by lembacon** [comment]
I've just triggered a rebuild for this, so we can have bottles for El Capitan. 🙃

**Comment by lembacon** [comment]
I think I should update resources for one python per pull request next time. So we could simply abort the CI once the python formula itself has been successfully built. 🙃

**Comment by DomT4** [comment]
Aye, probably not a bad idea 👍.

**Pull request closed without merging**
