### PR TITLE
mesos: install "six" resource in libexec/"protobuf"

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This prevents "ImportError: No module named six" when Homebrew's Python
is first in the PATH.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
The Sierra failure occurs locally as well, but only when Mesos is built from source, and the problem occurs with and without this PR, so it may be due to an incompatibility with the latest Xcode.

**Comment by ilovezfs** [comment]
@bbannier do you happen to know whether upstream is aware of this crash on macOS 10.12.5 Sierra building with Xcode 8.3.2?

It looks like it's a segmentation fault in _scheduler.so https://gist.github.com/ilovezfs/033f58185b81a79c471f81bf75a8c944

**Comment by bbannier** [comment]
@ilovezfs: I couldn't find a related issue in our [issue tracker](https://issues.apache.org/jira/issues/). Looking at both the CI failure here and the gist you posted above I see that this Mesos Python module pulls in some protobuf-3.X while Mesos built with a bundle protobuf (which is 2.6.1 currently). I am not sure protobuf has ABI compatibility across such a wide range of versions and would be surprised if this wasn't related to these crashes. Note that Mesos can be built with an unbundled protobuf, see the `--with-protobuf` option.

**Comment by ilovezfs** [comment]
@bbannier that wouldn't explain why it passed on El Capitan and Yosemite though, would it?

**Comment by ilovezfs** [comment]
@bbannier I've reported it here: https://issues.apache.org/jira/browse/MESOS-7583

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@bbannier interestingly, the failure does not occur if I use Xcode 9 beta 3 (neither on 10.12 nor 10.13)

**Pull request closed without merging**
