### PR TITLE
sourcery 2.1.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
rebased and updated sha

**Comment by chenrui333** [comment]
`error: 'sourcery-2.1.0': package 'sourcery-2.1.0' is using Swift tools version 5.8.0 but the installed version is 5.7.1`

**Comment by chenrui333** [comment]
- linux support, https://github.com/krzysztofzablocki/Sourcery/pull/1188

**Comment by p-linnane** [comment]
Linux failed:

```
  swift build --disable-sandbox -c release --build-path build/
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/swift: line 15: /home/linuxbrew/.linuxbrew/opt/swift/bin/swift: No such file or directory
  rake aborted!
  Command failed with status (127): [swift build --disable-sandbox -c release -...]
```

**Comment by chenrui333** [comment]
> Linux failed:
> 
> ```
>   swift build --disable-sandbox -c release --build-path build/
>   /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/swift: line 15: /home/linuxbrew/.linuxbrew/opt/swift/bin/swift: No such file or directory
>   rake aborted!
>   Command failed with status (127): [swift build --disable-sandbox -c release -...]
> ```

somehow missed it 😅

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
