### PR TITLE
hbase 2.3.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dawidd6** [comment]
```
Error: An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
/usr/local/Cellar/hbase/2.3.0/libexec/conf/hbase-env.sh:
  expected replacement of /^export HBASE_OPTS=.*/ with "export HBASE_OPTS=\"-Djava.net.preferIPv4Stack=true -XX:+UseConcMarkSweepGC\""
```

**Comment by jonchang** [comment]
Looks like we'll have to set that environment variable some other way:

https://github.com/apache/hbase/commit/ce57437012a345fe30ff5c11563395ff0e4d3ff3#diff-fc144dcf35c3d4c3dc13e61c8010019a

**Comment by SeekingMeaning** [comment]
Unless anyone has objections, we should probably `brew pr-pull` (considering how CI is behaving lately)

**Comment by SMillerDev** [comment]
Should be pulled regardless to squash the commits

**Comment by SeekingMeaning** [comment]
Right. I'll go ahead ahead and merge this

**Comment by SeekingMeaning** [comment]
https://github.com/Homebrew/homebrew-core/commit/e220e129887f87d9e425d9a8f0882c2d30bcbc82

**Pull request closed without merging**
