### PR TITLE
SDL, SDL_mixer wav file crash fixes.

### PR DESCRIPTION
**Pull request by illume**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

These issues are fixed in hg but don't have a release in the SDL 1.2 series.
- https://bugzilla.libsdl.org/show_bug.cgi?id=1673 https://github.com/pygame/pygame/issues/459
- https://bugzilla.libsdl.org/show_bug.cgi?id=1418 https://github.com/pygame/pygame/issues/406

### CODE REVIEW

**Comment by fxcoudert** [comment]
While it is sad that SDL is not releasing new versions with these fixes, we will not accept patches for them in Homebrew: we do not want to become _de facto_ maintainers of old, unmaintained software. We only include patches without which the software would not build, or be totally unusable.

The addition of the test, however, is a very good idea!

**Comment by fxcoudert** [comment]
I've pushed the test in https://github.com/Homebrew/homebrew-core/commit/2b9d86c744d856ec8d7423aceb4b2a8c041ec4b9
Thanks @illume!

**Comment by illume** [comment]
Lots of people can't use it to load wav files which is the point of it. Pretty ridiculous decision to reject security fixes. Please remove the test I wrote. I don't want it included.

Have a nice day! And thanks!

**Comment by fxcoudert** [comment]
- Re. “security fix”: nothing in your report indicates that this is a security issue.
- We have had no report from users about this issue.
- The proper fix is for SDL to make a new release, or for software relying on SDL to move to another, actively maintained platform.

**Pull request closed without merging**
