### PR TITLE
giflib 5.2.1

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Upstream still has not gotten their build system in working order for us with this release, but at least someone was gracious enough to contribute a patch so we can head off to the races with this one. @fxcoudert initiated discussion upstream at https://sourceforge.net/p/giflib/bugs/133/.

### CODE REVIEW

**Comment by alebcay** [comment]
`mapserver` build failure is already happening in current master (probably not caused by this update). Will need to resolve that failure before this can be merged.

**Comment by SMillerDev** [comment]
```
tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:6701:66: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:CompositingFilter_filter_set", , &arg2)) SWIG_fail;
                                                                 ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:7475:59: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:clusterObj_region_set", , &arg2)) SWIG_fail;
                                                          ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:7529:65: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:clusterObj_updateFromString", , &arg2)) SWIG_fail;
                                                                ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:7626:57: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:clusterObj_setGroup", , &arg2)) SWIG_fail;
                                                        ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:7723:58: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:clusterObj_setFilter", , &arg2)) SWIG_fail;
                                                         ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:7938:62: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:outputFormatObj_name_set", , &arg2)) SWIG_fail;
                                                             ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:7991:66: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:outputFormatObj_mimetype_set", , &arg2)) SWIG_fail;
                                                                 ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:8044:64: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:outputFormatObj_driver_set", , &arg2)) SWIG_fail;
                                                               ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:8097:67: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:outputFormatObj_extension_set", , &arg2)) SWIG_fail;
                                                                  ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:8412:58: error: expected expression
  if (!PyArg_ParseTuple(args, "O|z:new_outputFormatObj", , &arg2)) SWIG_fail;
                                                         ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:9190:66: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:queryMapObj_updateFromString", , &arg2)) SWIG_fail;
                                                                 ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:9382:52: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:webObj_log_set", , &arg2)) SWIG_fail;
                                                   ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:9435:58: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:webObj_imagepath_set", , &arg2)) SWIG_fail;
                                                         ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:9488:57: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:webObj_imageurl_set", , &arg2)) SWIG_fail;
                                                        ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:9541:57: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:webObj_temppath_set", , &arg2)) SWIG_fail;
                                                        ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:9617:57: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:webObj_template_set", , &arg2)) SWIG_fail;
                                                        ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:9670:55: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:webObj_header_set", , &arg2)) SWIG_fail;
                                                      ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:9723:55: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:webObj_footer_set", , &arg2)) SWIG_fail;
                                                      ^
/tmp/mapserver-20190629-64163-189e4q9/mapserver-7.2.2/build/mapscript/python/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c:9776:54: error: expected expression
  if (!PyArg_ParseTuple(args, "Oz:webObj_empty_set", , &arg2)) SWIG_fail;
                                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
[ 99%] Built target mapserv
[ 99%] Built target shp2img
20 errors generated.
make[2]: *** [mapscript/python/CMakeFiles/_pythonmapscript.dir/CMakeFiles/_pythonmapscript.dir/mapscriptPYTHON_wrap.c.o] Error 1
make[1]: *** [mapscript/python/CMakeFiles/_pythonmapscript.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by iMichka** [comment]
@alebcay This needs to be rebased.

**Comment by Moisan** [comment]
I think the quick fix for `mapserver` without having to wait on #41884 is to change the `swig` dependency to `swig@3`.

**Comment by Moisan** [comment]
`pgrouting` test is failing and the installation of `postgresql` as a dependency of `mapnik` also fails.

**Comment by fxcoudert** [comment]
I think this is good to merge (`pgrouting` is a common test failure, sadly… unrelated)

**Comment by fxcoudert** [comment]
Thank you @alebcay and @Moisan for your work on this!

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by alebcay** [comment]
```
==> brew test --verbose caffe
==> FAILED
Testing caffe
/usr/bin/sandbox-exec -f /private/tmp/homebrew20191114-41826-69nbna.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/caffe.rb --verbose
==> Downloading http://dl.caffe.berkeleyvision.org/bvlc_reference_caffenet.caffemodel
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.1.16-67-g1b92638\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15\)\ curl/7.64.1 --fail --silent --location --remote-time --continue-at 0 --output /Users/brew/Library/Caches/Homebrew/downloads/b8b2cb12fb8cbc38d1eb301e02486c100e5e7868c1914cd22b3db1e030b806e7--bvlc_reference_caffenet.caffemodel.incomplete http://dl.caffe.berkeleyvision.org/bvlc_reference_caffenet.caffemodel
curl: (7) Failed to connect to dl.caffe.berkeleyvision.org port 80: Operation timed out
Error: caffe: failed
An exception occurred within a child process:
  DownloadError: Failed to download resource "caffe--test_model_weights"
Download failed: http://dl.caffe.berkeleyvision.org/bvlc_reference_caffenet.caffemodel
```

The model is no longer available at the given URL. `dl.caffe.berkeleyvision.org` times out, but `caffe.berkeleyvision.org` is still reachable.

Apart from this error, there's just the usual `shmget`-related stuff for `mapnik` and `pgrouting`.

**Comment by fxcoudert** [comment]
Honestly, this being waiting since June, I suggest we merge as-is, and another PR be opened to deal with the preexisting `caffe` failure.

**Comment by SMillerDev** [comment]
I'm fine with that too.

**Pull request closed without merging**
