### PR TITLE
mdns-repeater 1.10 (new formula)

### PR DESCRIPTION
**Pull request by bsiegel**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by ilovezfs** [comment]
The patches would need to be accepted upstream for us to accept this.

**Comment by bsiegel** [comment]
> The patches would need to be accepted upstream for us to accept this.

The project appears to have been last updated in 2012, what is your suggestion? I suppose I could fork it and take over maintenance, but I wasn't really planning on that.

**Comment by ilovezfs** [comment]
>I suppose I could fork it and take over maintenance

I'd suggest starting out by forking it, apply these patches in the fork, and then create a clean formula without patching in your own tap and see how that goes for a while.

**Comment by ilovezfs** [comment]
>The project appears to have been last updated in 2012

That doesn't necessarily mean upstream is gone. You might be surprised. I'd definitely open an issue or PR, etc. and see if you get a response.

**Comment by MikeMcQuaid** [comment]
Passing on this for now, sorry!

**Pull request closed without merging**
