### PR TITLE
tektoncd-cli: update checksum

### PR DESCRIPTION
**Pull request by piyush-garg**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
Any explanation why the hash changed?

**Comment by carlocab** [comment]
```
==> brew audit tektoncd-cli --online --git --skip-style
==> FAILED
tektoncd-cli:
  * stable sha256 changed without the url/version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
Error: 1 problem in 1 formula detected
```

**Comment by piyush-garg** [comment]
I downloaded the source tar and did

```
sha256sum cli-0.17.2.tar.gz 
44444e0ebf02934e500c0806b53cea4269deeaa2a4b04e05d6a74e7bc169ca5d  cli-0.17.2.tar.gz
```

And I raised the PR with this sha, not sure about the reason why it is changed?

**Comment by SMillerDev** [comment]
> And I raised the PR with this sha, not sure about the reason why it is changed?

You need to make an issue upstream to make sure this isn't a compromised tarbal.

**Comment by carlocab** [comment]
Did you re-tag 0.17.2?

**Comment by piyush-garg** [comment]
I did not retag, but tag was moved from pre-release to release

**Comment by nandahkrishna** [comment]
I noticed that it was a pre-release (and it was also picked up by the audit) in #75053, but it was marked as the latest in just a short while (a few minutes, I think). Apologies if I was wrong in approving that PR.

**Comment by SMillerDev** [comment]
If only the GitHub status changed the hash wouldn't change. If it was actually retagged to mark it as a release that would explain the issue.

**Comment by nandahkrishna** [comment]
Shouldn't that have cause CI to fail during `brew fetch --retry tektoncd-cli --build-bottle --force`? (I re-ran CI after the release was marked.)

**Comment by SMillerDev** [comment]
> Shouldn't that have caused CI to fail during brew fetch --retry tektoncd-cli --build-bottle --force? (I re-ran CI after the release was marked.)

Yeah, that would have broken. That means it must have been retagged.

**Comment by piyush-garg** [comment]
> > Shouldn't that have caused CI to fail during brew fetch --retry tektoncd-cli --build-bottle --force? (I re-ran CI after the release was marked.)
> 
> Yeah, that would have broken. That means it must have been retagged.

I did not do retag, release job was run only once

**Comment by nandahkrishna** [comment]
Closing this PR in favour of #76019. Thanks anyway, @piyush-garg.

**Pull request closed without merging**
