### PR TITLE
pick 4.0.0

### PR DESCRIPTION
**Pull request by Bo98**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
Anyone have any idea of a way to test this? It seems to me that it's entirely interactive.

**Comment by SMillerDev** [comment]
Run it and see if it still runs seconds later?

**Comment by alebcay** [comment]
[Some formulae use `expect` to test interactive situations](https://github.com/Homebrew/homebrew-core/blob/635d927391cc14ef73aa272db5d6332dfd63cf1f/Formula/minisign.rb#L46), I don't know if it might be of help in this case.

**Comment by chenrui333** [comment]
Besides expect, pipe_shell is also good for interactive test.

**Pull request closed without merging**
