### PR TITLE
hapi-fhir-cli: Fix incorrect source for test resource

### PR DESCRIPTION
**Pull request by johngrimes**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
If we need to update this every time, we should probably just install it in `pkgshare` to decrease the maintenance burden when upgrading. See e.g. arpack, clblast, hwloc, etc.

**Comment by ilovezfs** [comment]
ping

**Comment by johngrimes** [comment]
I'm just trying to figure out exactly how to implement what you've asked for.

This is just a JAR distribution (not built from source), and the test resource comes from the corresponding tagged source on GitHub. I'm not sure how using `pkgshare` would prevent maintainers from having to update both the main `url` and the `url` within the `test_resource`.

Is there a way of just interpolating the formula version into the `url` string of the `test_resource`, would this achieve the same result? I guess the maintainer would still need to check that the test resource is still located in the same place within source control.

**Comment by johngrimes** [comment]
¯\_(ツ)_/¯

**Pull request closed without merging**
