### PR TITLE
gifski 1.4.3

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
  cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
  cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)
```
Looks like they picked up an LLVM dependency. Let's see if we just need it for the build.

**Comment by chenrui333** [comment]
refreshed the PR and let's see how it goes.

**Comment by chenrui333** [comment]
<details>
<summary>build failure</summary>

```
   Compiling ffmpeg-sys-next v4.3.5
error[E0004]: non-exhaustive patterns: `AV_PIX_FMT_X2RGB10LE` and `AV_PIX_FMT_X2RGB10BE` not covered
   --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/ffmpeg-next-4.3.8/src/util/format/pixel.rs:407:15
    |
407 |         match value {
    |               ^^^^^ patterns `AV_PIX_FMT_X2RGB10LE` and `AV_PIX_FMT_X2RGB10BE` not covered
    |
   ::: /private/tmp/gifski-20210612-77510-8se56m/gifski-1.4.3/target/release/build/ffmpeg-sys-next-21a5cbfe3ca12f11/out/bindings.rs:3:318650
    |
3   | ..."] AV_PIX_FMT_X2RGB10LE = 196 , # [doc = "< packed RGB 10:10:10, 30bpp, (msb)2X 10R 10G 10B(lsb), big-endian, X=unused/undefined"] AV_PIX_FMT_X2RGB10BE = ...
    |       -------------------- not covered                                                                                                -------------------- not covered
    |
    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
    = note: the matched value is of type `sys::AVPixelFormat`

error[E0004]: non-exhaustive patterns: `AV_FRAME_DATA_SEI_UNREGISTERED` and `AV_FRAME_DATA_FILM_GRAIN_PARAMS` not covered
  --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/ffmpeg-next-4.3.8/src/util/frame/side_data.rs:60:15
   |
60 |         match value {
   |               ^^^^^ patterns `AV_FRAME_DATA_SEI_UNREGISTERED` and `AV_FRAME_DATA_FILM_GRAIN_PARAMS` not covered
   |
  ::: /private/tmp/gifski-20210612-77510-8se56m/gifski-1.4.3/target/release/build/ffmpeg-sys-next-21a5cbfe3ca12f11/out/bindings.rs:3:366182
   |
3  | ..."] AV_FRAME_DATA_SEI_UNREGISTERED = 22 , # [doc = " Film grain parameters for a frame, described by AVFilmGrainParams."] # [doc = " Must be present for every frame which should have film grain applied."] AV_FRAME_DATA_FILM_GRAIN_PARAMS = ...
   |       ------------------------------ not covered                                                                                                                                                               ------------------------------- not covered
   |
   = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
   = note: the matched value is of type `sys::AVFrameSideDataType`

error[E0004]: non-exhaustive patterns: `AV_CODEC_ID_PGX`, `AV_CODEC_ID_AVS3`, `AV_CODEC_ID_MSP2` and 11 more not covered
   --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/ffmpeg-next-4.3.8/src/codec/id.rs:586:15
    |
586 |         match value {
    |               ^^^^^ patterns `AV_CODEC_ID_PGX`, `AV_CODEC_ID_AVS3`, `AV_CODEC_ID_MSP2` and 11 more not covered
    |
    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
    = note: the matched value is of type `sys::AVCodecID`

error[E0004]: non-exhaustive patterns: `AV_PKT_DATA_S12M_TIMECODE` not covered
  --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/ffmpeg-next-4.3.8/src/codec/packet/side_data.rs:55:15
   |
55 |         match value {
   |               ^^^^^ pattern `AV_PKT_DATA_S12M_TIMECODE` not covered
   |
  ::: /private/tmp/gifski-20210612-77510-8se56m/gifski-1.4.3/target/release/build/ffmpeg-sys-next-21a5cbfe3ca12f11/out/bindings.rs:3:482968
   |
3  | ... # [doc = " function in libavutil/timecode.h."] AV_PKT_DATA_S12M_TIMECODE = 30 , # [doc = " The number of side data types."] # [doc = ...
   |                                                    ------------------------- not covered
   |
   = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
   = note: the matched value is of type `sys::AVPacketSideDataType`

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0004`.
error: could not compile `ffmpeg-next`
```

</details>

**Comment by chenrui333** [comment]
#82961

**Pull request closed without merging**
