### PR TITLE
mumps 5.1.1 (migrated from homebrew-science)

### PR DESCRIPTION
**Pull request by jslee02**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

TODO
- [x] Change mumps to be MPI-less by default (comment: https://github.com/Homebrew/homebrew-core/pull/23645#discussion_r165912674)
-----

This PR is a revive of https://github.com/Homebrew/homebrew-core/pull/20505.

Depends on #22361 and #22362

### CODE REVIEW

**Comment by jslee02** [comment]
`brew audit --strict mumps.rb` says `:fortran is deprecated. Usage should be "gcc"`, but I'm not sure if removing `depends_on :fortran` is the right way to fix this issue.

**Comment by jslee02** [comment]
This PR is not ready to review. Let me reopen once it's ready.

**Comment by jslee02** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
- parmetis and scotch already have PRs of their own.
- Let's make this formula optionless.
- Squash all commits into a single one

**Comment by jslee02** [comment]
Closing in favor of #23884

**Pull request closed without merging**
