### PR TITLE
sdcc 4.0.0

### PR DESCRIPTION
**Pull request by HoangDuong**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can you check the hash of the new file and update that too?

**Comment by chenrui333** [comment]
../../bin/sdcc -I../../device/include -I../../device/include/mcs51 --model-huge --nostdinc --std-c11 -c printfl.c -o huge/printfl.rel
../../bin/sdcc -I../../device/include -I../../device/include/mcs51 --model-huge --nostdinc --std-c11 -c bpx.c -o huge/bpx.rel
/Applications/Xcode.app/Contents/Developer/usr/bin/make port-specific-objects
if [ -f huge/Makefile ]; then \
	  /Applications/Xcode.app/Contents/Developer/usr/bin/make -C huge PORT=huge; \
	fi
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../mcs51 all
../../../bin/sdar -rcD ../build/huge/mcs51.lib crtstart.rel crtxinit.rel crtxclear.rel crtclear.rel crtpagesfr.rel crtbank.rel crtcall.rel crtxstack.rel crtxpush.rel crtxpushr0.rel crtxpop.rel crtxpopr0.rel gptr_cmp.rel
cp ../mcs51/*.rel .
touch dummy.rel
/Applications/Xcode.app/Contents/Developer/usr/bin/make build/huge/libfloat.lib build/huge/libint.lib build/huge/liblong.lib build/huge/liblonglong.lib build/huge/libsdcc.lib
../../bin/sdar -rcD build/huge/libfloat.lib huge/_atof.rel huge/_schar2fs.rel huge/_sint2fs.rel huge/_slong2fs.rel huge/_uchar2fs.rel huge/_uint2fs.rel huge/_ulong2fs.rel huge/_fs2schar.rel huge/_fs2sint.rel huge/_fs2slong.rel huge/_fs2uchar.rel huge/_fs2uint.rel huge/_fs2ulong.rel huge/_fsadd.rel huge/_fsdiv.rel huge/_fsmul.rel huge/_fssub.rel huge/_fseq.rel huge/_fslt.rel huge/_fsneq.rel huge/fabsf.rel huge/frexpf.rel huge/ldexpf.rel huge/expf.rel huge/powf.rel huge/sincosf.rel huge/sinf.rel huge/cosf.rel huge/logf.rel huge/log10f.rel huge/sqrtf.rel huge/tancotf.rel huge/tanf.rel huge/cotf.rel huge/asincosf.rel huge/asinf.rel huge/acosf.rel huge/atanf.rel huge/atan2f.rel huge/sincoshf.rel huge/sinhf.rel huge/coshf.rel huge/tanhf.rel huge/floorf.rel huge/ceilf.rel huge/modff.rel huge/errno.rel huge/isinf.rel huge/isnan.rel huge/_fscmp.rel huge/_fsget1arg.rel huge/_fsget2args.rel huge/_fsnormalize.rel huge/_fsreturnval.rel huge/_fsrshift.rel huge/_fsswapargs.rel huge/_logexpf.rel
../../bin/sdar -rcD build/huge/libint.lib huge/_divsint.rel huge/_divuint.rel huge/_modsint.rel huge/_moduint.rel huge/_mulint.rel
../../bin/sdar -rcD build/huge/liblong.lib huge/_divslong.rel huge/_modslong.rel huge/_modulong.rel huge/_divulong.rel huge/_mullong.rel
../../bin/sdar -rcD build/huge/liblonglong.lib huge/_rrulonglong.rel huge/_rrslonglong.rel huge/_rlulonglong.rel huge/_rlslonglong.rel huge/_mullonglong.rel huge/_divslonglong.rel huge/_divulonglong.rel huge/_modslonglong.rel huge/_modulonglong.rel
../../bin/sdar -rcD build/huge/libsdcc.lib huge/isalnum.rel huge/isalpha.rel huge/isblank.rel huge/iscntrl.rel huge/isdigit.rel huge/isgraph.rel huge/islower.rel huge/isprint.rel huge/ispunct.rel huge/isspace.rel huge/isupper.rel huge/isxdigit.rel huge/tolower.rel huge/toupper.rel huge/atoi.rel huge/atol.rel huge/atoll.rel huge/strtol.rel huge/strtoul.rel huge/bsearch.rel huge/qsort.rel huge/abs.rel huge/labs.rel huge/rand.rel huge/_strcat.rel huge/_strchr.rel huge/_strcspn.rel huge/strdup.rel huge/strndup.rel huge/_strncat.rel huge/_strncmp.rel huge/strxfrm.rel huge/_strncpy.rel huge/_strpbrk.rel huge/_strrchr.rel huge/_strspn.rel huge/_strstr.rel huge/_strtok.rel huge/memccpy.rel huge/_memchr.rel huge/_memcmp.rel huge/_memset.rel huge/aligned_alloc.rel huge/calloc.rel huge/malloc.rel huge/realloc.rel huge/free.rel huge/mblen.rel huge/mbtowc.rel huge/wctomb.rel huge/mbstowcs.rel huge/wcstombs.rel huge/mbrtoc16.rel huge/c16rtomb.rel huge/mbrtoc32.rel huge/c32rtomb.rel huge/mbstoc16s.rel huge/c16stombs.rel huge/wcscmp.rel huge/wcslen.rel huge/btowc.rel huge/wctob.rel huge/mbsinit.rel huge/mbrlen.rel huge/mbrtowc.rel huge/wcrtomb.rel huge/printf_large.rel huge/puts.rel huge/gets.rel huge/__assert.rel huge/time.rel huge/_autobaud.rel huge/_bp.rel huge/_decdptr.rel huge/_gptrget.rel huge/_gptrgetc.rel huge/_gptrput.rel huge/_ser.rel huge/_setjmp.rel huge/serial.rel huge/_itoa.rel huge/_ltoa.rel huge/_spx.rel huge/_startup.rel huge/_strcmp.rel huge/_strlen.rel huge/__memcpy.rel huge/memcpy.rel huge/_memmove.rel huge/_strcpy.rel huge/_heap.rel huge/sprintf.rel huge/vprintf.rel huge/printf_fast.rel huge/printf_fast_f.rel huge/printf_tiny.rel huge/printfl.rel huge/bpx.rel
/Applications/Xcode.app/Contents/Developer/usr/bin/make clean_intermediate
rm -f build/huge/*.lst build/huge/*.sym
make[1]: *** [all] Error 2
make: *** [sdcc-device-lib] Error 2

**Comment by HoangDuong** [comment]
How can i check hash ?? sorry i am dummy on homebrew and git, please guide me.

**Comment by SMillerDev** [comment]
You need to download the new file and check the [sha256 checksum](https://www.dyclassroom.com/howto-mac/how-to-verify-checksum-on-a-mac-md5-sha1-sha256-etc). And then you need to specify that checksum in the `sha256` field in the formula

**Comment by HoangDuong** [comment]
> You need to download the new file and check the [sha256 checksum](https://www.dyclassroom.com/howto-mac/how-to-verify-checksum-on-a-mac-md5-sha1-sha256-etc). And then you need to specify that checksum in the `sha256` field in the formula

i delete old version of sddc and uninstall old version of sdcc in my PC, then flowing each step:

`brew edit sdcc`

then i change dowload link by: https://excellmedia.dl.sourceforge.net/project/sdcc/sdcc-macos-amd64/4.0.0/sdcc-4.0.0-x86_64-apple-macosx.tar.bz2

then run command and get SHA256: 
`brew fetch sdcc --build-from-source`

`==> Downloading https://excellmedia.dl.sourceforge.net/project/sdcc/sdcc-macos-amd64/4.0.0/sdcc-4.0.0-x86_64-apple-macosx.tar.bz2
######################################################################## 100.0%
Downloaded to: /Users/duonghuuhoang/Library/Caches/Homebrew/downloads/f5c15375b3599ecc6c971266cbb273e624787e93b5efb9d7794a854aabbee9ef--sdcc-4.0.0-x86_64-apple-macosx.tar.bz2
SHA256: 84056a0d0a144e5e41ccc30dd1ca172e8a48ff0c964724d5a4fe32283bebecb1
Warning: Formula reports different SHA256: 489180806fc20a3911ba4cf5ccaf1875b68910d7aed3f401bbd0695b0bef4e10`

using SHA256: 84056a0d0a144e5e41ccc30dd1ca172e8a48ff0c964724d5a4fe32283bebecb1 then paste to sdcc.rb file and run command

`brew install -vsd --git sdcc`

Output from terminal: 
`/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sdcc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/icu4c.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gputils.rb
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200206-24836-6vo78c.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sdcc.rb --git --verbose --debug
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sdcc.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/icu4c.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gputils.rb
==> Downloading https://excellmedia.dl.sourceforge.net/project/sdcc/sdcc-macos-amd64/4.0.0/sdcc-4.0.0-x86_64-apple-macosx.tar.bz2
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.5-19-g2555e43\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head --request GET https://excellmedia.dl.sourceforge.net/project/sdcc/sdcc-macos-amd64/4.0.0/sdcc-4.0.0-x86_64-apple-macosx.tar.bz2
Already downloaded: /Users/duonghuuhoang/Library/Caches/Homebrew/downloads/f5c15375b3599ecc6c971266cbb273e624787e93b5efb9d7794a854aabbee9ef--sdcc-4.0.0-x86_64-apple-macosx.tar.bz2
tar xof /Users/duonghuuhoang/Library/Caches/Homebrew/downloads/f5c15375b3599ecc6c971266cbb273e624787e93b5efb9d7794a854aabbee9ef--sdcc-4.0.0-x86_64-apple-macosx.tar.bz2 -C /private/tmp/d20200206-24837-sigatz
cp -pR /private/tmp/d20200206-24837-sigatz/sdcc-4.0.0/. /private/tmp/sdcc-20200206-24837-1gb9ncd/sdcc-4.0.0
Initialized empty Git repository in /private/tmp/sdcc-20200206-24837-1gb9ncd/sdcc-4.0.0/.git/
==> ./configure --prefix=/usr/local/Cellar/sdcc/4.0.0
Last 15 lines from /Users/duonghuuhoang/Library/Logs/Homebrew/sdcc/01.configure:
2020-02-06 09:10:27 +0700

./configure
--prefix=/usr/local/Cellar/sdcc/4.0.0

/usr/bin/curl --version
/usr/libexec/java_home --xml --failfast
/usr/libexec/java_home --xml --failfast
/usr/local/Homebrew/Library/Homebrew/debrew.rb:13:in `raise'
BuildError: Failed executing: ./configure --prefix=/usr/local/Cellar/sdcc/4.0.0
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action:
`
if i chose 'shell', i dont know what command to run.
when i chose raise, output show: Error: sdcc 4.0.0 did not build
`Choose an action: raise   
==> Kept temporary files
Temporary files retained at /private/tmp/sdcc-20200206-27374-1ck37sa

==> Formula
Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sdcc.rb
==> Configuration
HOMEBREW_VERSION: 2.2.5-19-g2555e43
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2555e43a6dcfa6357f7bcf3e1341e36c97b885ee
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b5ce2d4f171f4ac2260e57bd51a8b3e1769c8b36
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1000
Git: 2.25.0 => /usr/local/bin/git
/usr/bin/curl --version
Curl: 7.54.0 => /usr/bin/curl
/usr/libexec/java_home --xml --failfast
/usr/libexec/java_home --xml --failfast
Java: 13.0.1, 1.8.0_152
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/icu4c:/usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/icu4c/bin:/usr/local/opt/gputils/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: sdcc 4.0.0 did not build
Logs:
     /Users/duonghuuhoang/Library/Logs/Homebrew/sdcc/00.options.out
     /Users/duonghuuhoang/Library/Logs/Homebrew/sdcc/01.configure.cc
     /Users/duonghuuhoang/Library/Logs/Homebrew/sdcc/02.make.cc
     /Users/duonghuuhoang/Library/Logs/Homebrew/sdcc/config.log
     /Users/duonghuuhoang/Library/Logs/Homebrew/sdcc/01.configure
     /Users/duonghuuhoang/Library/Logs/Homebrew/sdcc/02.make
READ THIS: https://docs.brew.sh/Troubleshooting

/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.5-19-g2555e43\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location https://api.github.com/search/issues\?q=sdcc\+state\%3Aopen\+repo\%3AHomebrew\%2Fhomebrew-core\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --header Authorization:\ token\ ****** --dump-header /private/tmp/github_api_headers20200206-26676-6atsqo
These open issues may also help:
sdcc 4.0.0 https://github.com/Homebrew/homebrew-core/pull/49768`

please guide me to next step.

**Comment by SMillerDev** [comment]
You'll need to fix the build of 4.0. This problem is specific to the software, I can't really help you with it. I don't know the build process either.

**Comment by HoangDuong** [comment]
i can build success on my PC

```
sdcc --version
SDCC : mcs51/z80/z180/r2k/r3ka/gbz80/tlcs90/ez80_z80/ds390/pic16/pic14/TININative/ds400/hc08/s08/stm8/pdk13/pdk14/pdk15 4.0.0 #11528 (Mac OS X x86_64)
```
but when i execute cmd:
`brew install -vsd --git sdcc`
or
`brew install --verbose --debug sdcc`

i always received:
```
BuildError: Failed executing: make all
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 
```

**Pull request closed without merging**
