### PR TITLE
* FontForge: Install Python3 bindings instead of Python2

### PR DESCRIPTION
**Pull request by earboxer**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
> After testing, if you think it is needed to force the corresponding bottles to be rebuilt and redistributed, add a line of the form revision 1 to the formula, or add 1 to the revision number already present.

I think I'm right in adding `revision 1` here, as the existing bottles have python2 bindings.
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See https://discourse.brew.sh/t/python-2-eol-2020/4647/11

### CODE REVIEW

**Comment by SMillerDev** [comment]
You have an audit failure.

Other than that, is python actually a runtime dependency here? Otherwise it might be possible to mark it just as build/test dependency.

**Comment by fxcoudert** [comment]
It looks like `mftrace` is unhappy… possibly it should be made to depend on `python` (i.e. use Python 3)?

**Comment by earboxer** [comment]
@fxcoudert Thanks for figuring that out. I was wondering what that was about.

**Comment by earboxer** [comment]
If/when this pull request goes through, installing fontforge will no longer have python2 bindings.

FontForge's Ubuntu install still comes with python2 bindings. [One user suggested](https://github.com/fontforge/fontforge/issues/1731#issuecomment-184453360) they create a `python3-fontforge` package. There exist some PPA's that are built like this.

The reason I mention this is because `brew install fontforge` **won't** be identical to `apt install fontforge`. (And I know this is fine: brew tends to be cutting edge while others are more stable).

What I'm leading up to is: 

Should we have a separate `fontforge@python2` for the people who depend on it? (See also `boost-python*.rb` formulas for some precedent for this...)

**Comment by SMillerDev** [comment]
With the end of python 2 closing in fast I'm not sure if adding a package for it is the best course of. We can always do that if someone makes a pull request for it.

**Comment by fxcoudert** [comment]
Thank you @earboxer for your contribution to Homebrew

**Pull request closed without merging**
