### PR TITLE
kde-ki18n 5.71.0 (new formula)

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by yurikoles** [comment]
@alebcay could you please review this.

I had spent half of my day trying to develop sample app with ki18n, but I ended up installing autotests to `pkgshare` and testing it on demand.

**Comment by alebcay** [comment]
Generally looks good. The only change I would advise is to rename the formula as just `ki18n`. Unlike ECM, I feel like the `k` prefix makes it pretty clear that it's KDE-related (i.e. it's not named just `i18n`). In retrospect I probably should've suggested this for `kde-threadweaver` as well, but that can be a change for down the road if it's important enough.

Going to leave the PR here for some more eyes to look over, though.

**Comment by yurikoles** [comment]
https://github.com/Homebrew/homebrew-core/pull/55120#issuecomment-632688209
> > I think the naming is pretty ambiguous and should include KDE, @Homebrew/core what do others think?
> 
> Agreed 👍

@alebcay, let's follow original agreement.

**Comment by SMillerDev** [comment]
Yeah, I'd like to keep KDE in the name. Though I wouldn't be opposed to adding an alias.

**Comment by yurikoles** [comment]
@SMillerDev I had added an alias. Could you please accept it?

**Review by SMillerDev — APPROVED** [review]
Thanks @yurikoles ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by yurikoles** [comment]
Thanks, @SMillerDev!

I really appreciate your code review of this project!

**Pull request closed without merging**
