### PR TITLE
vera++: fix build for Linux

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

https://github.com/Homebrew/homebrew-core/runs/3259356874?check_suite_focus=true
```
-- Could NOT find Tclsh (missing: TCL_TCLSH) 
-- Could NOT find TCL (missing: TCL_LIBRARY TCL_INCLUDE_PATH) 
-- Could NOT find TCLTK (missing: TCL_LIBRARY TCL_INCLUDE_PATH TK_LIBRARY TK_INCLUDE_PATH) 
-- Could NOT find TK (missing: TK_LIBRARY TK_INCLUDE_PATH) 
CMake Error at src/CMakeLists.txt:5 (message):
  TCL was not found.
```

### CODE REVIEW

**Comment by jonchang** [comment]
I've managed to get this to work, but not sure if it'll work on Linux due to a lack of an available Python 2.

**Comment by jonchang** [comment]
I've split off the macOS fixes to https://github.com/Homebrew/homebrew-core/pull/82933

**Comment by cho-m** [comment]
@jonchang Sure. Thanks for taking a look.
I'll wait for that PR and then give it another try to force build system to pick Python 3.
If nothing works, I will just add `depends_on :macos` for Python 2.

**Comment by cho-m** [comment]
I just disabled Python 2 bindings on Linux. I think this should be fine for now as we don't really support Python 2.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
