### PR TITLE
cpl: patch incorrect -flat_namespace usage

### PR DESCRIPTION
**Pull request by carlocab**
This is needed for bottling on Monterey.

### CODE REVIEW

**Comment by carlocab** [comment]
Adding `no ARM bottle` as a reminder not to dispatch an ARM Monterey bottle (`fftw` has no ARM bottle for Monterey).

**Comment by SMillerDev** [comment]
Still flat

**Comment by SMillerDev** [comment]
Livecheck failure... It's not going great here

**Comment by iMichka** [comment]
Might have been transient network issue, I re-triggered a build.

**Comment by SMillerDev** [comment]
Doesn't seem transient, although it does only exist on macOS

**Comment by carlocab** [comment]
I don't think livecheck failures should block bottling on ARM. If we really don't like the failures, we could just get rid of the `livecheck` block.

**Comment by SMillerDev** [comment]
It's odd since it works for me locally.

**Comment by carlocab** [comment]
Well even more reason to not nix the `livecheck` block...

**Review by iMichka — APPROVED** [review]

**Comment by carlocab** [comment]
@iMichka please remember to check the commit format before using `--no-autosquash`.

**Comment by iMichka** [comment]
Oups my bad, I saw the label and the wrong commit message, and then approved and forgot about it. Sorry :(

**Pull request closed without merging**
