### PR TITLE
tomcat 8.5.28

### PR DESCRIPTION
**Pull request by marcokrikke**
Upgraded Tomcat 8.0.43 to 8.5.28 after defaulting to Tomcat 9 in Homebrew/homebrew-core#23870.
Also renamed formula to tomcat@8.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
We already have 3 versions of tomcat (6, 7, and 8.0), and we probably don't want to add yet another. If tomcat 8.5 is actively maintained, it may make sense to move the 8.0 version to be named `tomcat@8` and correspond to the latest 8 update (8.5.27), to bring it in line with the others.

**Comment by marcokrikke** [comment]
Apache indeed mentions that:

> Tomcat 8.5 is thought as a replacement for Tomcat 8.0. [1]

Happy to provide a PR to upgrade `Tomcat@8.0` to 8.5.27 and rename that formula to `tomcat@8`.

[1] https://tomcat.apache.org/whichversion.html

**Comment by fxcoudert** [comment]
> Happy to provide a PR to upgrade tomcat@8.0 to 8.5.27 and rename that formula to tomcat@8.

Great, thanks

**Comment by marcokrikke** [comment]
@fxcoudert I've changed this PR:

* Upgraded `tomcat@8.0` to 8.5.28 (newest version)
* Renamed `tomcat@8.0` to `tomcat@8`
* Added `bottle :unneeded` and `keg_only :versioned_formula`, as with `tomcat@7`
* Added plist part, as with `tomcat`. Not sure if this is required.
* Tested with `brew install --build-from-source tomcat@8`
* Tested with `brew audit --strict tomcat@8`

**Comment by fxcoudert** [comment]
Thanks @marcokrikke for the pull request!

**Pull request merged**
