### PR TITLE
chronograf 1.3.6.1 + cleanup

### PR DESCRIPTION
**Pull request by chrmoritz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR updates `chronograf` to the latest version according to [their download page](https://portal.influxdata.com/downloads) and fixes some general issues with the formula (see [line comments](https://github.com/chrmoritz/homebrew-core/commit/d1b3b28ad533face582a540ab5d41e246aecfbb7)).

### CODE REVIEW

**Comment by ilovezfs** [comment]
latest version is still 1.3.3.4 according to https://github.com/influxdata/chronograf/releases/latest

**Comment by chrmoritz** [comment]
@ilovezfs: Looks like 1.3.4.0 is now marked as the latest version on github releases (and a new 1.3.5.0 tag was created).

**Comment by chrmoritz** [comment]
I've updated this PR to the newly released version 1.3.5.0 (which is now also marked on Github releases as latest). Please take another look.

**Comment by chrmoritz** [comment]
@ilovezfs Changed this PR to use `language/node` for setting the $PATH to npm using `setup_npm_environment` instead of directly calling `ENV.prepend_path` to be more rebust against future node formula changes (for more information see also #16074 fixing such a issue).

**Comment by chrmoritz** [comment]
updates this PR to the latest chronograf 1.3.6.0 release

**Comment by chrmoritz** [comment]
@ilovezfs updated to chronograf 1.3.6.1. PTAL

**Comment by dunn** [comment]
Merged as 07528832ded80a5b1ed2b9a143d9ee435b3d74a6.

**Pull request closed without merging**
