### PR TITLE
go formulae: add completions

### PR DESCRIPTION
**Pull request by max-ae**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This PR adds completions for `go`-based formulae using the `cobra` framework and offering completions generation.

### CODE REVIEW

**Comment by max-ae** [comment]
Since there are failures I could not yet reproduce locally, plus the need for `long build`, should this be split into individual PRs instead?

**Comment by SMillerDev** [comment]
That seems better, yes. You can also just split out the errors and the long builds.

**Comment by max-ae** [comment]
> That seems better, yes. You can also just split out the errors and the long builds.

I'll just split this into individual PRs, should be easier if more failures arise.

**Comment by max-ae** [comment]
I have made the required changes to the remaining formulae so that they should pass now in one go. As the overall number decreased, I think this might work now without the `long-build` label 😄

**Comment by max-ae** [comment]
All remaining commits have been split off into individual PRs.

**Pull request closed without merging**
