### PR TITLE
openssl@1.1 1.1.1j

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
On ARM:
```
Error: 3 failed steps!
brew test --retry --verbose emscripten
brew test --retry --verbose howdoi
brew test --retry --verbose yle-dl
```
I think these are pre-existing (at least, `emscripten` is).

**Comment by bayandin** [comment]
- `yle-dl` test fixed in https://github.com/Homebrew/homebrew-core/pull/71404
- `howdoi` just doesn't work. There's a recent upstream issue https://github.com/gleitz/howdoi/issues/331

**Comment by bayandin** [comment]
- `emscripten` test should be fixed after https://github.com/Homebrew/homebrew-core/pull/71400 (https://github.com/nodejs/node/issues/37061)

**Comment by carlocab** [comment]
This version fixes [three CVEs](https://www.openssl.org/news/cl111.txt). Judging from the last few releases, this is above par. (Of course, this doesn't account for magnitude/severity.)

**Comment by carlocab** [comment]
Mojave:

```
Error: 8 failed steps!
brew test --retry --verbose gallery-dl
brew test --retry --verbose howdoi
brew test --retry --verbose hyperkit
brew test --retry --verbose opencascade
brew test --retry --verbose swift
brew test --retry --verbose treefrog
brew test --retry --verbose wasm-pack
brew test --retry --verbose yle-dl
```

**Review by carlocab — APPROVED** [review]
Merging for security fixes.

**Pull request closed without merging**
