### PR TITLE
schema-evolution-manager (sem) 0.9.40 (new formula)

### PR DESCRIPTION
**Pull request by gheine**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by commitay** [comment]
@gheine Please squash this down to one commit.

**Comment by gheine** [comment]
@commitay done

**Comment by gheine** [comment]
@commitay @fxcoudert could this be merged please?

**Comment by ilovezfs** [comment]
I am wondering if we should call this `schema-evolution-manager` not `sem`.

**Comment by gheine** [comment]
All the commands are `sem-*` (sem-add, sem-apply, sem-init, etc.)

**Comment by ilovezfs** [comment]
@gheine Let's call the formula itself `schema-evolution-manager` and have an alias for it in the Aliases directory named `sem`, so people can still `brew install sem` if they want.

**Comment by ilovezfs** [comment]
@gheine ping

**Comment by gheine** [comment]
@ilovezfs done

**Comment by ilovezfs** [comment]
Thanks for the 🆕 formula @gheine! Shipped.

**Pull request merged**
