### PR TITLE
mysql: add caveat explaining update process 8.3-9.0

### LINKED ISSUE #180063: Homebrew MySQL `brew upgrade` broke mysql - MacOS Sonoma 14.5
From time-to-time I run `brew upgrade` just to keep my stuff up-to-date.  Yesterday I noticed the it upgraded mysql from 8.xx to 9.0.1.  After the upgrade mysql was, for me, completely broken.  It appears that I was given a fresh install and none of my logins worked (existing schema gone.).  I've uninstalled and reinstalled mysql a couple of times with no luck.  I can restored the databases but it would have been nice to have had everything preserved.

I also have no idea why a clean/fresh install of mysql (as me) would try to start as root.

Here's what I now get:

**% brew uninstall mysql**
Uninstalling /opt/homebrew/Cellar/mysql/9.0.1... (324 files, 310.3MB)
==> Autoremoving 1 unneeded formula:
protobuf@21
Uninstalling /opt/homebrew/Cellar/protobuf@21/21.12... (288 files, 19.6MB)

**% brew install mysql**
==> Downloading https://formulae.brew.sh/api/formula.jws.json
################################################################################################################################################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
################################################################################################################################################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/mysql/manifests/9.0.1
Already downloaded: /Users/bquimby1/Library/Caches/Homebrew/downloads/f10a7045f58ec039e1ed95b8f166e6bd49ef4b8067a155a649bbd51839c8237d--mysql-9.0.1.bottle_manifest.json
==> Fetching dependencies for mysql: protobuf@21
==> Downloading https://ghcr.io/v2/homebrew/core/protobuf/21/manifests/21.12-2
################################################################################################################################################################################################## 100.0%
==> Fetching protobuf@21
==> Downloading https://ghcr.io/v2/homebrew/core/protobuf/21/blobs/sha256:bc82f299ae0fffa1e5b4e93ec3dd39f0330bb06a8dfdebbb953479de3b25eb00
################################################################################################################################################################################################## 100.0%
==> Fetching mysql
==> Downloading https://ghcr.io/v2/homebrew/core/mysql/blobs/sha256:809ff45d66016c434d3eca504cd4f9b251101134bcf48e53c332de6ee12c1007
Already downloaded: /Users/bquimby1/Library/Caches/Homebrew/downloads/162c46701f0ede64d836dafc5baf20fd3caf8c19a31c21584c3a0ea91c291d4e--mysql--9.0.1.arm64_sonoma.bottle.tar.gz
==> Installing dependencies for mysql: protobuf@21
==> Installing mysql dependency: protobuf@21
==> Downloading https://ghcr.io/v2/homebrew/core/protobuf/21/manifests/21.12-2
Already downloaded: /Users/bquimby1/Library/Caches/Homebrew/downloads/583342af32dcbdcd8cfa8359e446e22f36310246bf95602d6813748f1af52728--protobuf@21-21.12-2.bottle_manifest.json
==> Pouring protobuf@21--21.12.arm64_sonoma.bottle.2.tar.gz
🍺  /opt/homebrew/Cellar/protobuf@21/21.12: 289 files, 19.8MB
==> Installing mysql
==> Pouring mysql--9.0.1.arm64_sonoma.bottle.tar.gz
==> Caveats
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -u root

To restart mysql after an upgrade:
  brew services restart mysql
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/mysql/bin/mysqld_safe --datadir\=/opt/homebrew/var/mysql
==> Summary
🍺  /opt/homebrew/Cellar/mysql/9.0.1: 324 files, 310.3MB
==> Running `brew cleanup mysql`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Caveats
==> mysql
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -u root

To restart mysql after an upgrade:
  brew services restart mysql
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/mysql/bin/mysqld_safe --datadir\=/opt/homebrew/var/mysql

% **brew doctor**
Your system is ready to brew.

% **brew services restart mysql**
Stopping `mysql`... (might take a while)
==> Successfully stopped `mysql` (label: homebrew.mxcl.mysql)
==> Successfully started `mysql` (label: homebrew.mxcl.mysql)

% **brew services**
Name          Status  User     File
httpd         started bquimby1 ~/Library/LaunchAgents/homebrew.mxcl.httpd.plist
**_mysql         stopped root     ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist_**
php           started bquimby1 ~/Library/LaunchAgents/homebrew.mxcl.php.plist
php@8.1       none             
postgresql@14 started bquimby1 ~/Library/LaunchAgents/homebrew.mxcl.postgresql@14.plist
unbound       none          

% mysql -u root
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

### PR DESCRIPTION
**Pull request by SMillerDev**
Fixes https://github.com/Homebrew/homebrew-core/issues/180063

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by MikeMcQuaid — COMMENTED** [review]
Looks good! Some wording and style suggestion.

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by carlocab** [comment]
> @carlocab should the bottles not be updated with the new caveat?

I thought caveats came from the API, and not read from the bottles?

**Comment by MikeMcQuaid** [comment]
Thanks @SMillerDev!

**Comment by trungtaxp** [comment]
I don't have mariadb, percona-server but now I brew upgrade and it's like this. I installed mysql@8.4 but it didn't work.
brew info mysql    
==> mysql: stable 9.0.1 (bottled)
Open source relational database management system
https://dev.mysql.com/doc/refman/9.0/en/
Conflicts with:
  mariadb (because mysql, mariadb, and percona install the same binaries)
  percona-server (because mysql, mariadb, and percona install the same binaries)
Installed
/opt/homebrew/Cellar/mysql/9.0.1 (324 files, 310.3MB)
  Poured from bottle using the formulae.brew.sh API on 2024-08-09 at 14:38:18
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/m/mysql.rb
License: GPL-2.0-only with Universal-FOSS-exception-1.0
==> Dependencies
Build: bison ✔, cmake ✔, pkg-config ✔
Required: icu4c ✔, libfido2 ✔, lz4 ✔, openssl@3 ✔, protobuf@21 ✔, zlib ✔, zstd ✔
==> Caveats
Upgrading from MySQL <8.4 to MySQL >9.0 requires running MySQL 8.4 first:
 - brew services stop mysql
 - brew install mysql@8.4
 - brew services start mysql@8.4
 - brew services stop mysql@8.4
 - brew services start mysql

We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -u root

To start mysql now and restart at login:
  brew services start mysql
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/mysql/bin/mysqld_safe --datadir\=/opt/homebrew/var/mysql
==> Analytics
install: 36,757 (30 days), 102,772 (90 days), 493,872 (365 days)
install-on-request: 36,723 (30 days), 102,653 (90 days), 492,319 (365 days)
build-error: 744 (30 days)

**Pull request merged**
