### PR TITLE
nuclei 2.5.5

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
I've sent upstream an email. It's probably a retag but I went through the security email, as asked by upstream in their issue template.

**Comment by chenrui333** [comment]
@iMichka just FYI, nuclei made a new release `v2.5.5`.

**Comment by iMichka** [comment]
Yes, upstream responded and told me that they had to retag, and it already created confusion for some other users. They made a new release anyway, so I'll just update here.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
🚀

**Pull request closed without merging**
