### PR TITLE
janet 1.11.1

### PR DESCRIPTION
**Pull request by corasaurus-hex**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by dtrodrigues — DISMISSED** [review]
Thanks so much for your contribution to Homebrew @nate!

**Comment by nate** [comment]
That error doesn't seem like it's caused by janet, but some kind of action config?

**Comment by dawidd6** [comment]
Yep, fix here: https://github.com/Homebrew/brew/pull/8085

**Comment by nate** [comment]
Awesome, thanks @dawidd6!

**Comment by issyl0** [comment]
Let's try this again!

**Comment by issyl0** [comment]
Thanks for your patience, @nate! 👍

**Pull request closed without merging**
