### PR TITLE
Update ffmpeg to 4.2.1

### PR DESCRIPTION
**Pull request by danielbair**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
https://github.com/Homebrew/homebrew-core/pull/42827 is stuck.
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This fixes the build issue in mpv.rb https://github.com/Homebrew/homebrew-core/pull/42827#issuecomment-521474699

And fixes the issue with ffmpeg.rb https://github.com/Homebrew/homebrew-core/pull/42827#issuecomment-518442457

### CODE REVIEW

**Comment by SMillerDev** [comment]
That mpv archive isn't a release. And I don't think it's the best way to go.

**Comment by retokromer** [comment]
@SMillerDev Do you have any hint on how we could disconnect `mpv` from `ffmpeg`?

**Comment by danielbair** [comment]
Considering that the tagged release 0.29.1 of mpv cannot be built on macos 10.14.x and that there exists a 'brew cask install mpv' and that the mpv developers do not support tagged releases anymore but only operate from master, and that homebrew maintainer policy regarding tagged releases and the mpv developer policy are in conflict, it only seems reasonable to completely delete this formula.

**Comment by jonchang** [comment]
In that case, would you mind adding something to [tap_migrations.json](https://github.com/Homebrew/homebrew-core/blob/master/tap_migrations.json) as well for `mpv`? Thanks!

**Comment by danielbair** [comment]
Sure, done.

**Comment by jonchang** [comment]
Looks like `mps-youtube` depends on `mpv` and will need to be updated or removed. Looking at the README of mps-youtube I'm not sure that the dependency is even necessary.

**Comment by danielbair** [comment]
Removed mpv dep as mpv is not required. See https://github.com/mps-youtube/mps-youtube#macos-x

**Comment by fxcoudert** [comment]
> Mpsyt requires a player to use as a backend, with either mpv or mplayer supported. Mpv is the recommended option

**Comment by danielbair** [comment]
> > Mpsyt requires a player to use as a backend, with either mpv or mplayer supported. Mpv is the recommended option

@fxcoudert does this help...

```
  def caveats
    <<~EOS
    Install the optional mpv app with Homebrew Cask:
      brew cask install mpv
    EOS
  end
```

**Comment by jonchang** [comment]
Ok, looks like this is almost ready. Please squash this pull request to one commit per formula [per our commit message style](https://docs.brew.sh/Formula-Cookbook#commit) and force push.

**Comment by jonchang** [comment]
Thanks @danielbair. This will be merged soon. Also, we don't get notifications for force-pushes, so if you do so, please comment in the pull request so we know to check it out!

**Comment by danielbair** [comment]
> Thanks @danielbair. This will be merged soon. Also, we don't get notifications for force-pushes, so if you do so, please comment in the pull request so we know to check it out!

Ah, got it! I should just wait politely. Now I know.

**Pull request closed without merging**
