### PR TITLE
sqlite 3.31.1, dbhash 3.31.1, sqldiff 3.31.1, sqlite-analyzer 3.31.1

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
On catalina, failed
- anime-downloader
- mps-youtube
- streamlink

On Mojave, failed
- anime-downloader
- mps-youtube
- streamlink
- euler-py

On highsierra, failed
- anime-downloader
- buku
- dynare
- libzdb
- mps-youtube
- pgrouting
- streamlink

**Comment by chenrui333** [comment]
anime-downloader is raised in here, https://github.com/Homebrew/homebrew-core/issues/49339

**Comment by fxcoudert** [comment]
`mps-youtube` is not related, it needs an update of its `youtube_dl` resource to the latest version

**Comment by chmaynard** [comment]
What's going on? SQLite is a vital tool and 3.31 is an important release. I don't understand why this PR hasn't been merged yet.

**Comment by alebcay** [comment]
[`sqlite` 3.31.1 is now available](https://sqlite.org/releaselog/3_31_1.html).

--

> @chenrui333 What's going on? SQLite is a vital tool and 3.31 is an important release. I don't understand why this PR hasn't been merged yet.

> On catalina, failed [...] On Mojave, failed [...] On highsierra, failed

This has not been merged because certain packages that depend on `sqlite` have been broken by this update, and we will not ship half-working stuff, which would simply result in more issues for us to deal with.

**Comment by chmaynard** [comment]
@alebcay Understood, sorry for the noise. The author of SQLite sent out this announcement.

SQLite version 3.31.1 is now available on the website.

Version 3.31.1 is a patch against version 3.31.0 that reverts the
layout of an internal data structure to use a format that is largely
compatible with historical versions of SQLite.  This shouldn't make
any difference to applications that use SQLite.  However, there exists
at least one popular application that does depend on the
implementation details of one specific internal data structure.  When
those details changed in version 3.31.0, that application broke.
SQLite version 3.31.1 attempts to change the internal data structure
yet again so that the 3rd-party application will continue to work,
without fixes, using version 3.31.1.

All developers are admonished to *not* make any assumptions about the
internal organization of data structures inside of SQLite.  If some
detail of the implementation is not part of the public API then it is
subject to change without notice in future releases.  If you write
your application such that it depends on some random internal
implementation detail of SQLite and that detail changes in subsequent
release of SQLite, then it is on your own head.  Just because we have
backed out an internal change this one time does not mean we will ever
do so again.

Or, if you really, really must play games with internal SQLite data
structures, then at the very least please statically link your
application against SQLite, rather than use a shared-library version
of SQLite that is part of the system.  That way your application won't
break when the system version of SQLite is upgraded.

-- 
D. Richard Hipp
drh@sqlite.org

**Comment by chenrui333** [comment]
@chmaynard Sorry for the delay, I will add the patch release into this PR. 

@alebcay, I think we can for the merge with knowing the `anime-downloader` test failed.

**Comment by chenrui333** [comment]
Forced update the PR for the latest release and rebased to the current master.

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
rebased to the latest master (with several test PRs merged)

**Comment by chenrui333** [comment]
Only gitless formula has test issue. I think it is OK to do the merge.

**Comment by chenrui333** [comment]
@chmaynard sorry for the wait, the sqlite 3.31.1 has been shipped. 

Thanks @samford for fixing so many tests! You rock!

**Pull request closed without merging**
