### PR TITLE
duck 6.2.10

### PR DESCRIPTION
**Pull request by dkocher**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@dkocher this is failing due to incompatibility with Java 9.

**Comment by ilovezfs** [comment]
@dkocher also, with Java 8, the test block fails:
```
==> Summary
🍺  /usr/local/Cellar/duck/6.2.10.26754: 839 files, 168.9MB, built in 11 minutes 25 seconds
iMac-TMP:~ joe$ brew test -vd duck
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/duck.rb
Testing duck
/usr/bin/sandbox-exec -f /tmp/homebrew20171027-60103-ozjzxj.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/duck.rb -vd
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/duck.rb
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libmagic.rb
==> /usr/local/Cellar/duck/6.2.10.26754/bin/duck --download ftp://ftp.astron.com/pub/file/file-5.32.tar.gz /tmp/duck-test-20171027-60104-g8i7i8/test
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/joe/Library/Caches/Homebrew/java_cache
Missing protocol in URI ftp://ftp.astron.com/pub/file/file-5.32.tar.gz
Try 'duck --help' for more options.

/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: /usr/local/Cellar/duck/6.2.10.26754/bin/duck --download ftp://ftp.astron.com/pub/file/file-5.32.tar.gz /tmp/duck-test-20171027-60104-g8i7i8/test
```

**Comment by ilovezfs** [comment]
Requiring Java 8 currently means this cannot be bottled.

**Comment by dkocher** [comment]
We will have to wait for the next release then which can fix the build issue with Java 9.

**Comment by ilovezfs** [comment]
@dkocher a fix cannot be applied as a patch?

**Comment by dkocher** [comment]
You could apply https://github.com/iterate-ch/cyberduck/commit/612a973d119e95452799c9040da3ec0ce43c676d

**Comment by ilovezfs** [comment]
@dkocher done!

**Comment by ilovezfs** [comment]
Thanks again, @dkocher! Shipped. :duck:

**Pull request closed without merging**
