### PR TITLE
icu4c 64.2

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
I killed the testing, since it was an endless series of `node` failures, all identical:

```
09:20:42 ==> node /private/tmp/node-20190328-6879-nki74n/node-v11.12.0/npm_bootstrap/bin/npm-cli.js install -ddd --global --prefix=/usr/local/Cellar/node/11.12.0_1/libexec /Users/brew/Library/Caches/Homebrew/downloads/b493007b7de25271b0e25e4781bef6f3ffa882e80ff5b213bfdf23430b6533f0--npm-6.7.0.tgz
09:20:42 Last 150 lines from /Users/brew/Jenkins/workspace/core/logs/node/03.node:
09:20:42 2019-03-28 09:20:32 +0000
09:20:42 
09:20:42 node
09:20:42 /private/tmp/node-20190328-6879-nki74n/node-v11.12.0/npm_bootstrap/bin/npm-cli.js
09:20:42 install
09:20:42 -ddd
09:20:42 --global
09:20:42 --prefix=/usr/local/Cellar/node/11.12.0_1/libexec
09:20:42 /Users/brew/Library/Caches/Homebrew/downloads/b493007b7de25271b0e25e4781bef6f3ffa882e80ff5b213bfdf23430b6533f0--npm-6.7.0.tgz
09:20:42 
09:20:42 Error: Cannot convert name to ASCII
09:20:42     at Url.parse (url.js:381:23)
09:20:42     at Object.urlParse [as parse] (url.js:145:13)
09:20:42     at Object.validateUrl [as validate] (/private/tmp/node-20190328-6879-nki74n/node-v11.12.0/npm_bootstrap/node_modules/nopt/lib/nopt.js:172:13)
09:20:42     at validate (/private/tmp/node-20190328-6879-nki74n/node-v11.12.0/npm_bootstrap/node_modules/nopt/lib/nopt.js:221:24)
09:20:42     at validate (/private/tmp/node-20190328-6879-nki74n/node-v11.12.0/npm_bootstrap/node_modules/nopt/lib/nopt.js:187:11)
09:20:42     at /private/tmp/node-20190328-6879-nki74n/node-v11.12.0/npm_bootstrap/node_modules/nopt/lib/nopt.js:104:12
09:20:42     at Array.map (<anonymous>)
09:20:42     at /private/tmp/node-20190328-6879-nki74n/node-v11.12.0/npm_bootstrap/node_modules/nopt/lib/nopt.js:70:15
09:20:42     at Array.forEach (<anonymous>)
09:20:42     at Function.clean (/private/tmp/node-20190328-6879-nki74n/node-v11.12.0/npm_bootstrap/node_modules/nopt/lib/nopt.js:58:21)
09:20:42 /private/tmp/node-20190328-6879-nki74n/node-v11.12.0/npm_bootstrap/lib/npm.js:59
09:20:42       throw new Error('npm.load() required')
09:20:42       ^
09:20:42 
09:20:42 Error: npm.load() required
09:20:42     at Object.get (/private/tmp/node-20190328-6879-nki74n/node-v11.12.0/npm_bootstrap/lib/npm.js:59:13)
09:20:42     at process.errorHandler (/private/tmp/node-20190328-6879-nki74n/node-v11.12.0/npm_bootstrap/lib/utils/error-handler.js:205:32)
09:20:42     at process.emit (events.js:197:13)
09:20:42     at process._fatalException (internal/process/execution.js:123:25)
```

**Comment by SMillerDev** [comment]
rebased on the latest master to avoid the conflicts and hopefully resolve the node error.

**Comment by SMillerDev** [comment]
Rebased again, @lembacon @fxcoudert any word on a fix for the node failure?

**Comment by fxcoudert** [comment]
@SMillerDev I have no idea, was it reported? discussed with upstream?
@lembacon seemed to say there is 64.2 release coming, and we should wait for this

**Comment by lembacon** [comment]
icu4c 64.2 is now released, updating…

**Comment by fxcoudert** [comment]
Missing revisions: `libpqxx php php@7.1 php@7.2 postgresql@10`

**Comment by fxcoudert** [comment]
Merging. `mimic` needs to be investigated:

```
==> Downloading https://github.com/MycroftAI/mimic/archive/1.2.0.2.tar.gz
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 6adcc9911b09d6e9513add41ad9dfc0893ece277f556419869520a0f0708c102
  Actual: 619f3864d8ff599c1fa47424b7d87059236fcd51db3c0c311eb3635c80174b5a
 Archive: /Users/brew/Library/Caches/Homebrew/downloads/c0d849d10b6f889cbabb38753036afe3204e31c2ce807d17334b6998848188a5--mimic1-1.2.0.2.tar.gz
To retry an incomplete download, remove the file above.
```

**Pull request closed without merging**
