### PR TITLE
dart-sass: 1.23.7 (new formula)

### PR DESCRIPTION
**Pull request by JarryShaw**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Following discussion in Homebrew/homebrew-core#43388, this formula is directly copied from SASS's official Tap (`sass/sass/sass`).

For node implementation, please refer to #47439 
For dart formula, please refer to #47442

### CODE REVIEW

**Comment by SMillerDev** [comment]
This seems like a very odd formula, depending on a separate tap and doing weird things for 64-bit systems. What did you base this on?

**Comment by JarryShaw** [comment]
This is the official formula of SASS (Dart implementation), copied directly from [`sass/sass/sass`](https://github.com/sass/Homebrew-sass/tree/master/sass.rb).

**Comment by SMillerDev** [comment]
You might want to rework it to be in line with the homebrew-core guidelines

**Comment by JarryShaw** [comment]
Will wait until `dart` itself is in the homebrew-core :)

**Comment by fxcoudert** [comment]
dart formula was rejected in current state, so closing this for now

**Pull request closed without merging**
