### PR TITLE
ranger: fix homepage

### PR DESCRIPTION
**Pull request by MindTooth**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
-----

New homepage for ranger.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @MindTooth! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by MindTooth** [comment]
@ilovezfs https://github.com/Homebrew/homebrew-core/commits?author=MindTooth ;)

**Comment by ilovezfs** [comment]
@MindTooth hmm https://github.com/Homebrew/homebrew-core/pulls/MindTooth

**Comment by MindTooth** [comment]
Wanted a holiday from GitHub, but could not stay away 🎉

**Comment by ilovezfs** [comment]
right but your old PRs don't show in the closed list ...

**Comment by MindTooth** [comment]
Guess they got removed when I deleted my account.

**Comment by ilovezfs** [comment]
ah I see. so it's some email matching magic maybe

**Comment by MindTooth** [comment]
But thank you for the welcome anyway ;)  Appreciated.

**Comment by ilovezfs** [comment]
No problem! :)

**Pull request merged**
