### PR TITLE
kakoune: add HEAD

### PR DESCRIPTION
**Pull request by John-Colvin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Always nice to have the option to skip to the latest master when you want to.

### CODE REVIEW

**Comment by DomT4** [comment]
Same comments as in https://github.com/Homebrew/homebrew-core/pull/28622, I'm afraid. We'd like to a consistent record of releases from upstream before we re-add `HEAD` here, to prevent `HEAD` becoming the default method of installation for this formula.

**Comment by John-Colvin** [comment]
Sometimes it's better to be out of date, sometimes it's better to track master. Why can't the user be trusted to make the call?

**Comment by DomT4** [comment]
Because many of those users then file issues against core telling us `HEAD` builds are broken and we have to either outright close those or go chasing a moving target to try and work out why it has broken 🙃.

I'm not against adding `HEAD` again here in future, but analytics currently shows more installs from `HEAD` than from stable, and `HEAD` becoming the de facto default isn't something we support or wish to encourage.

**Comment by John-Colvin** [comment]
Seems like that's a net loss for users.

What is the support promise that HEAD makes? I want to know for the packages I regularly commit to.

**Comment by DomT4** [comment]
> Seems like that's a net loss for users

More of a net gain if it allows us to instead invest that time on doing things like preparing core for Mojave, handling updates, reviewing PRs, etc. At the end of the day we're a fairly small team with finite time and we have to make not entirely delightful choices on where/how to save ourselves time. I appreciate that's frustrating for you here but I disagree we'd be better investing that time supporting `HEAD` more than we do.

> What is the support promise that HEAD makes?

As with all formulae if people file issues regarding build failures we will try to identify if those failures are driven by Homebrew or a universal issue, and either encourage people to report build failures upstream, or rather often end up doing it ourselves.

We don't technically support trying to resolve `HEAD` failures because you can go from working to broken to working again in the space of a few hours, but nonetheless we end up doing so rather than simply closing issues with a blunt _"This isn't supported"_ message.

**Comment by John-Colvin** [comment]
Ok, I understand the rationale. I wish there was a way to add an "unsupported HEAD", which would never take any core developers time away (no reason to be afraid of blunt issue closing when it's written in the issue template not to file it!) but would occasionally be useful to users.

P.S. When I said it was a net loss to users, I wasn't imaging you would be adding lots of extra `HEAD`s and actively - in effect - supporting them, I thought you could just let them break because they're not supposed to be supported.

**Pull request closed without merging**
