### PR TITLE
i2p 0.9.25

### PR DESCRIPTION
**Pull request by benmezger**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
### Description

The version of i2p in homebrew is a bit behind the current stable version. Here is a new formula with the new version available at https://geti2p.net/en/

### CODE REVIEW

**Comment by ephexeve** [comment]
Jenkins is returning the following error:

```
==> git checkout origin/master
==> brew pull --clean https://github.com/Homebrew/homebrew-core/pull/788
==> brew --env
==> brew config
==> brew tests
==> brew tests --no-compat
==> brew readall --aliases
==> brew uses i2p
==> brew fetch --retry i2p --force
==> brew uninstall --force i2p
==> brew install --verbose i2p
==> brew audit i2p
==> brew test i2p --verbose
==> git checkout master -f
Slave went offline during the build
ERROR: Connection was broken: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2335)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2804)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:802)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

Build step 'Execute shell' marked build as failure
ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for Homebrew Core Pull Requests/version=mavericks #1265
ERROR: Step ‘Archive the artifacts’ failed: no workspace for Homebrew Core Pull Requests/version=mavericks #1265
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Finished: FAILURE```

A quick Google tells me this is a Jenkins issue and not mine, could anyone confirm that?
From this [1] Stackoverflow answer, apparently it's a Java version issue. Could anyone give me some hints here?

[1] - http://stackoverflow.com/a/18201464

**Comment by apjanke** [comment]
Yeah, that looks like an intermittent Jenkins failure.

@BrewTestBot test this please

**Comment by DomT4** [comment]
It's not intermittent really; something about this formula test breaks the internet connection on Jenkins pretty much every time. I've asked for it to be rewritten before and that probably still needs to be done.

**Comment by apjanke** [comment]
That is weird. And yep, the rerun failed too. Closing this out as broken.

@ephexeve if you can figure out how to fix this, please re-submit it on the new [`homebrew/core` repo](https://github.com/homebrew/homebrew-core). Or if you can't figure it out, submit it as an issue there and we'll see if someone can fix it. We really can't merge this as long as the CI run is breaking.

**Comment by DomT4** [comment]
@apjanke This _is_ the `homebrew/core` repo 😜.

**Comment by apjanke** [comment]
Oops! Sorry, this got mixed in with all the notifications from my legacy-homebrew cleanup run. Reopening. I'll take a stab at it myself if nobody else can figure it out soon.

Sorry!

**Comment by apjanke** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
The test will break on CI, as it always does. Have been asking people to rewrite it for about 3 months now 🙈.

**Comment by MikeMcQuaid** [comment]
Thanks @DomT4. Closing this out until test is rewritten.

**Comment by DomT4** [comment]
I'd be tempted to just revert it to a version test until we can work out why it breaks the VM connection temporarily.

**Pull request closed without merging**
