### PR TITLE
hashcat 5.1.0

### PR DESCRIPTION
**Pull request by leonklingele**
Updates https://github.com/Homebrew/homebrew-core/pull/36348

### CODE REVIEW

**Comment by leonklingele** [comment]
I don't have a machine with Mojave available so I'll debug this with Homebrew CI.

**Comment by leonklingele** [comment]
Test failure of 5.1.0 on Mojave:

```
[..]
==> ./hashcat -m 500 -a 0 --force --quiet --potfile-disable example500.hash example.dict
==> ./hashcat -m 500 -a 1 --force --quiet --potfile-disable example500.hash dict1.txt dict2.txt
�[31mclBuildProgram(): CL_BUILD_PROGRAM_FAILURE�[0m

Error: hashcat: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<255>.
[..]
```

Unfortunately, there seems to be no easy fix except skipping the test on Mojave. The Mojave build machine only has a single OpenCL device available (CPU) (which fails to run the test / crashes / whatever) so we can't use a different device (using `-d`).

Even when rebuilding the previous version (4.2.1), the test fails (see https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/41612/version=mojave/console) indicating that some kind of driver or other piece of software has changed on the build machine.

Other options tested so far which didn't fix the issue:

- `--markov-disable`
- `--opencl-vector-width=2`

**Comment by leonklingele** [comment]
@MikeMcQuaid any idea on what to do about the Mojave build?

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
> any idea on what to do about the Mojave build?

No, sorry. You'll need to figure out why the test is failing there and fix it. Do you have access to a Mojave machine?

**Comment by leonklingele** [comment]
Something is fishy with the Mojave build machine. The previous version (v4.2.1) fails to build now but succeeded a few months ago in https://github.com/Homebrew/homebrew-core/pull/30899. Please see my other comments in this thread.

**Comment by MikeMcQuaid** [comment]
@leonklingele That doesn't provide enough information to debug or do anything about this, sorry. Mojave and Xcode have both been upgraded in that time so it's unclear to me at this time that this is an issue with our build machine rather than this software building on Mojave.

**Comment by alexcruice** [comment]
I may be able to shed some light on this. I have a machine running macOS Mojave 10.14.6 (18G87).

I don't know why it fails so often when executed via `brew test hashcat`, but when running with the `--debug` flag and dropping into the shell at the failure the test command in question
```
./hashcat -m 500 -a 0 --force --quiet --potfile-disable example500.hash example.dict
```
can execute successfully and crack the target `$1$uOM6WNc4$r3ZGeSB11q6UUSILqek3J1:hash234`. However, it does sometimes fail.

When running the test command without the `--quiet` flag this is the difference in output between a successful crack and keyspace exhaustion.
_success_
```
$1$uOM6WNc4$r3ZGeSB11q6UUSILqek3J1:hash234

Session..........: hashcat
Status...........: Cracked
Hash.Type........: md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)
Hash.Target......: $1$uOM6WNc4$r3ZGeSB11q6UUSILqek3J1
Time.Started.....: Wed Aug 14 08:35:49 2019 (1 sec)
Time.Estimated...: Wed Aug 14 08:35:50 2019 (0 secs)
Guess.Base.......: File (example.dict)
Guess.Queue......: 1/1 (100.00%)
Speed.#2.........:    88348 H/s (5.82ms) @ Accel:64 Loops:31 Thr:8 Vec:1
Speed.#3.........:    12750 H/s (9.04ms) @ Accel:64 Loops:31 Thr:32 Vec:1
Speed.#*.........:   101.1 kH/s
Recovered........: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.........: 94208/128416 (73.36%)
Rejected.........: 0/94208 (0.00%)
Restore.Point....: 49152/128416 (38.28%)
Restore.Sub.#2...: Salt:0 Amplifier:0-1 Iteration:93-124
Restore.Sub.#3...: Salt:0 Amplifier:0-1 Iteration:992-1000
Candidates.#2....: nc6f81 -> support
Candidates.#3....: h0n07u7u -> igela1
```

_failure_
```
Approaching final keyspace - workload adjusted.

Session..........: hashcat
Status...........: Exhausted
Hash.Type........: md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)
Hash.Target......: $1$uOM6WNc4$r3ZGeSB11q6UUSILqek3J1
Time.Started.....: Wed Aug 14 08:33:23 2019 (1 sec)
Time.Estimated...: Wed Aug 14 08:33:24 2019 (0 secs)
Guess.Base.......: File (example.dict)
Guess.Queue......: 1/1 (100.00%)
Speed.#2.........:    76882 H/s (4.44ms) @ Accel:64 Loops:31 Thr:8 Vec:1
Speed.#3.........:    14481 H/s (6.22ms) @ Accel:64 Loops:31 Thr:32 Vec:1
Speed.#*.........:    91363 H/s
Recovered........: 0/1 (0.00%) Digests, 0/1 (0.00%) Salts
Progress.........: 128416/128416 (100.00%)
Rejected.........: 0/128416 (0.00%)
Restore.Point....: 127494/128416 (99.28%)
Restore.Sub.#2...: Salt:0 Amplifier:0-1 Iteration:992-1000
Restore.Sub.#3...: Salt:0 Amplifier:0-1 Iteration:992-1000
Candidates.#2....: waller -> zeni12
Candidates.#3....: zenica75 -> zzzzzzzzzzz
```

**Comment by alexcruice** [comment]
There's a closed issue on hashcat for macOS sometimes failing to crack, https://github.com/hashcat/hashcat/issues/1350. The failure is likely related to the random device selection. I have three OpenCL devices on my machine.
```
$ hashcat -I
hashcat (v5.1.0) starting...

OpenCL Info:

Platform ID #1
  Vendor  : Apple
  Name    : Apple
  Version : OpenCL 1.2 (Jun 23 2019 21:50:55)

  Device ID #1
    Type           : CPU
    Vendor ID      : 4
    Vendor         : Intel
    Name           : Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Version        : OpenCL 1.2
    Processor(s)   : 8
    Clock          : 2800
    Memory         : 4096/16384 MB allocatable
    OpenCL Version : OpenCL C 1.2
    Driver Version : 1.1

  Device ID #2
    Type           : GPU
    Vendor ID      : 4
    Vendor         : Intel
    Name           : Iris Pro
    Version        : OpenCL 1.2
    Processor(s)   : 40
    Clock          : 1300
    Memory         : 384/1536 MB allocatable
    OpenCL Version : OpenCL C 1.2
    Driver Version : 1.2(Jul  2 2019 21:50:21)

  Device ID #3
    Type           : GPU
    Vendor ID      : 32
    Vendor         : NVIDIA
    Name           : GeForce GT 750M
    Version        : OpenCL 1.2
    Processor(s)   : 2
    Clock          : 810
    Memory         : 512/2048 MB allocatable
    OpenCL Version : OpenCL C 1.2
    Driver Version : 12.0.24 355.11.10.50.10.103
```

When running the test command specifically on the Intel Iris Pro, it always fails.
```
./hashcat -m 500 -d 2 -a 0 --force --quiet --potfile-disable example500.hash example.dict
```

The test commands could be amended to include the `--opencl-device-types=1` flag to instruct it to use only CPU devices - but do all of the Homebrew build machines have OpenCL drivers installed for their CPUs (confident for macOS, not so sure for Linux)?

This leaves us in a bit of a pickle. What does it mean to successfully test hashcat when the hardware isn't reliable and CPU OpenCL drivers may not be installed? Could all the custom test activity be reduced to a simple `hashcat --benchmark -m 0` (this passes on the Intel Iris Pro `hashcat --benchmark -m 0 -d 2`)?

**Comment by alexcruice** [comment]
https://github.com/alexcruice/homebrew-core/commit/a6fcb4fca8ccc696442314eb8fae4d94d7814d4f

**Comment by jonchang** [comment]
> This leaves us in a bit of a pickle. What does it mean to successfully test hashcat when the hardware isn't reliable and CPU OpenCL drivers may not be installed? Could all the custom test activity be reduced to a simple `hashcat --benchmark -m 0` (this passes on the Intel Iris Pro `hashcat --benchmark -m 0 -d 2`)?

This sounds like a better solution than our current test.

**Comment by leonklingele** [comment]
Isn't that just fixing tests to make them pass somehow? I'd prefer to fix the bug in hashcat and keep the tests as-is.
Anyhow, I've updated this PR so you can decide.

**Pull request closed without merging**
