### PR TITLE
ghq: Add head

### PR DESCRIPTION
**Pull request by superbrothers**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR adds head target to `ghq` formula. I tested the formula as follows:
```
$ brew install ./Formula/ghq.rb --HEAD
==> Cloning https://github.com/motemen/ghq.git
Cloning into '/Users/ksuda/Library/Caches/Homebrew/ghq--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> make build
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/ghq/HEAD-787ce65: 7 files, 8.2MB, built in 7 seconds
```

### CODE REVIEW

**Comment by SMillerDev** [comment]
If the upstream tag doesn't build anymore they should be encouraged to tag a new release instead of working around it really.

**Comment by jonchang** [comment]
[This patch](https://github.com/motemen/ghq/commit/38ac89e60e60182b5870108f9753c9fe8d00e4a6.patch) seems to be sufficient to get it to build on go 1.13.

**Comment by superbrothers** [comment]
I got it. If the new upstream tag is created and the formula is updated, I'll rebase this PR.

**Comment by SMillerDev** [comment]
@superbrothers did that ever happen?

**Comment by superbrothers** [comment]
No, the upstream has no releases these past few months.

**Comment by superbrothers** [comment]
@SMillerDev ghq released v0.12.7, so I created a PR that bumps the version. #46304

**Comment by superbrothers** [comment]
@fxcoudert Why was this PR closed? I still want head target as before.

**Comment by fxcoudert** [comment]
I misunderstood you, then:

> It's a source repository's problem, so I'd like to add head

Reopening

**Comment by superbrothers** [comment]
@fxcoudert Thanks. I've rebased this PR on top of master.

**Pull request merged**
