### PR TITLE
colordiff 1.0.19

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by issyl0** [comment]
The patch needs removing.

**Comment by chenrui333** [comment]
```
==> make INSTALL_DIR=/usr/local/Cellar/colordiff/1.0.19/bin ETC_DIR=/usr/local/etc MAN_DIR=/usr/local/Cellar/colordiff/1.0.19/share/man/man1 install
install -d /usr/local/Cellar/colordiff/1.0.19/bin
sed -e "s%/etc%/usr/local/etc%g" colordiff.pl > \
	  /usr/local/Cellar/colordiff/1.0.19/bin/colordiff
chmod +x /usr/local/Cellar/colordiff/1.0.19/bin/colordiff
if [ ! -f /usr/local/Cellar/colordiff/1.0.19/bin/cdiff ] ; then \
	  install cdiff.sh /usr/local/Cellar/colordiff/1.0.19/bin/cdiff; \
	fi
install -Dm 644 colordiff.1 /usr/local/Cellar/colordiff/1.0.19/share/man/man1/colordiff.1
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
```

**Comment by Bo98** [comment]
Looks like it needs `ginstall`. See `sha1dc` as an example.

**Comment by issyl0** [comment]
Thanks Bo. Those changes seem to work locally for me.

**Comment by issyl0** [comment]
Pesky `brew style`...

**Pull request closed without merging**
