### PR TITLE
node 9.2.1, node@6 6.12.2, node@4 4.8.7, node@8 8.9.3 (new formula)

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

npm 5.6.0

Also, npm updates to 5.6.0 for node@6 and node@4.

### CODE REVIEW

**Comment by chrmoritz** [comment]
Shouldn't there be a new `node@8` formula too, given that it is in LTS.

**Comment by ilovezfs** [comment]
@chrmoritz added

**Review by DomT4 — APPROVED** [review]
Thanks for picking all these up @ilovezfs! ❤️

**Comment by ilovezfs** [comment]
@chrmoritz looks like joplin is going splat.
```
Error Message

failed: brew test --verbose joplin

Stacktrace

        Testing joplin
/usr/bin/sandbox-exec -f /tmp/homebrew20171208-6074-1qfbp0u.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/joplin.rb --verbose
==> /usr/local/Cellar/joplin/0.10.79/bin/joplin config editor subl
module.js:544
    throw err;
    ^

Error: Cannot find module '/usr/local/Cellar/joplin/0.10.79/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/binding/node-v59-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/Cellar/joplin/0.10.79/libexec/lib/node_modules/joplin/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
Error: joplin: failed
Failed executing: /usr/local/Cellar/joplin/0.10.79/bin/joplin config editor subl
/usr/local/Homebrew/Library/Homebrew/formula.rb:1796:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1734:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1734:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/joplin.rb:23:in `block in <class:Joplin>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1640:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1639:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:834:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1638:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1632:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by ilovezfs** [comment]
Going to assume that will be fixed ASAP. CC @laurent22

**Comment by ilovezfs** [comment]
:nine: :eight: :six: :four:

**Comment by laurent22** [comment]
Do I need to change something? I see the issue mentioned Node 9, which I haven't tested with.

**Comment by ilovezfs** [comment]
@laurent22 probably since joplin in homebrew/core is now :face_with_thermometer:

**Comment by chrmoritz** [comment]
@ilovezfs I think `joplin` just needs a revision bump, because it ships with a native addon `node-sqlite3` which was build against our node8 version, which isn't abi compatible with node9.

**Comment by ilovezfs** [comment]
thx https://github.com/Homebrew/homebrew-core/pull/21486

**Comment by chrmoritz** [comment]
The error basically say that it's looking for the binary for node9 (NODE_MODULE_VERSION 59), but couldn't find it, because there is only one for node8 (NODE_MODULE_VERSION 57) available.
Welcome in the bright new world, where we have to care about node based formulas shipping native addons.

**Pull request closed without merging**
