### PR TITLE
nebula: add HEAD build

### PR DESCRIPTION
**Pull request by jasikpark**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by jasikpark** [comment]
not sure how to test that `brew install --HEAD nebula` actually works..

**Comment by jasikpark** [comment]
```
homebrew-core on  add-head-version-for-nebula took 5s 
❯ brew install --HEAD Formula/nebula.rb
Error: Failed to load cask: Formula/nebula.rb
Cask 'nebula' is unreadable: wrong constant name #<Class:0x0000000159dca0a0>
Warning: Treating Formula/nebula.rb as a formula.
==> Fetching nebula
==> Downloading https://github.com/slackhq/nebula
Already downloaded: /Users/calebjasik-defined/Library/Caches/Homebrew/downloads/c3d412033fa50818cf0a23e3d303d199e7fc2c7fda16ce89a3c666488a571c62--nebula
Warning: Cannot verify integrity of 'c3d412033fa50818cf0a23e3d303d199e7fc2c7fda16ce89a3c666488a571c62--nebula'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "d7808d837435daefe82dca8a48fa11b0f5cf4a98597141a1aa11f836c3e713cb"
==> make service
Last 15 lines from /Users/calebjasik-defined/Library/Logs/Homebrew/nebula/01.make:
2023-05-16 17:19:42 +0000

make
service

make: *** No rule to make target `service'.  Stop.

Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!

nebula's formula was built from an unstable upstream --HEAD.
This build failure is expected behaviour.
Do not create issues about this on Homebrew's GitHub repositories.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

homebrew-core on  add-head-version-for-nebula took 5s 
❯ 
```

**Comment by carlocab** [comment]
> not sure how to test that `brew install --HEAD nebula` actually works..

Have you tried doing `brew install --HEAD nebula` after checking out your PR branch?

**Comment by jasikpark** [comment]
> > not sure how to test that `brew install --HEAD nebula` actually works..
> 
> Have you tried doing `brew install --HEAD nebula` after checking out your PR branch?

well, isn't https://github.com/Homebrew/homebrew-core/pull/131113#issuecomment-1550071327 the same thing?

**Comment by jasikpark** [comment]
I use a separate homebrew clone from my macos homebrew setup

**Comment by carlocab** [comment]
> > > not sure how to test that `brew install --HEAD nebula` actually works..
> > 
> > 
> > Have you tried doing `brew install --HEAD nebula` after checking out your PR branch?
> 
> well, isn't [#131113 (comment)](https://github.com/Homebrew/homebrew-core/pull/131113#issuecomment-1550071327) the same thing?

It is not. Apply your changes to `$(brew --repo homebrew/core)/Formula/nebula.rb` then try `brew install --HEAD nebula` again.

**Comment by jasikpark** [comment]
image
```
homebrew-core on  add-head-version-for-nebula 
❯ code $(brew --repo homebrew/core)/Formula/nebula.rb

homebrew-core on  add-head-version-for-nebula 
❯ brew install --HEAD nebula
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################## 100.0%
Error: No head is defined for nebula

homebrew-core on  add-head-version-for-nebula took 3s 
❯ 
```

hmm it doesn't seem to have worked... - homebrew didn't pick up that change

**Comment by carlocab** [comment]
Ah, yes, sorry, try:
```
HOMEBREW_NO_INSTALL_FROM_API=1 brew install --HEAD nebula
```

**Comment by jasikpark** [comment]
```
~
❯ HOMEBREW_NO_INSTALL_FROM_API=1 brew install --HEAD nebula
==> Fetching dependencies for nebula: go
==> Fetching go
==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.19.5
Already downloaded: /Users/calebjasik-defined/Library/Caches/Homebrew/downloads/857fbe3c407bb637fd015fca96c14aa18b2e08fe1ed3d7dc1f2e43cca3aaf723--go-1.19.5.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/go/blobs/sha256:9e45e8c058b38e85608717871c18e8a4236f7
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:9e45e8c058b38e856
############################################################################################### 100.0%
==> Fetching nebula
==> Downloading https://github.com/slackhq/nebula
Already downloaded: /Users/calebjasik-defined/Library/Caches/Homebrew/downloads/c3d412033fa50818cf0a23e3d303d199e7fc2c7fda16ce89a3c666488a571c62--nebula
Warning: Cannot verify integrity of 'c3d412033fa50818cf0a23e3d303d199e7fc2c7fda16ce89a3c666488a571c62--nebula'.
No checksum was provided.
For your reference, the checksum is:
  sha256 "d7808d837435daefe82dca8a48fa11b0f5cf4a98597141a1aa11f836c3e713cb"
==> Installing dependencies for nebula: go
==> Installing nebula dependency: go
==> Pouring go--1.19.5.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/go/1.19.5: 12,458 files, 629.5MB
==> Installing nebula --HEAD
==> make service
Last 15 lines from /Users/calebjasik-defined/Library/Logs/Homebrew/nebula/01.make:
2023-05-17 15:47:10 +0000

make
service

make: *** No rule to make target `service'.  Stop.

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
nebula 1.7.0 https://github.com/Homebrew/homebrew-core/pull/131206
nebula: add HEAD version https://github.com/Homebrew/homebrew-core/pull/131113
nebula's formula was built from an unstable upstream --HEAD.
This build failure is expected behaviour.
Do not create issues about this on Homebrew's GitHub repositories.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

**Comment by jasikpark** [comment]
Fixed the fact that I was curling an html page instead of cloning a git repo 😓 

```
homebrew-core on  add-head-version-for-nebula [!] took 5s 
❯ HOMEBREW_NO_INSTALL_FROM_API=1 brew install --HEAD nebula
==> Fetching nebula
==> Cloning https://github.com/slackhq/nebula.git
Updating /Users/calebjasik-defined/Library/Caches/Homebrew/nebula--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 7ae3cd2 v1.7.0 (#870)
==> make service
Last 15 lines from /Users/calebjasik-defined/Library/Logs/Homebrew/nebula/01.make:
2023-05-17 16:36:10 +0000

make
service

go build -trimpath -ldflags "-X main.Build=HEAD-7ae3cd2" -o ./nebula "./cmd/nebula-service"
go: downloading github.com/kardianos/service v1.2.2
cert/cert.go:5:2: package crypto/ecdh is not in GOROOT (/opt/homebrew/Cellar/go/1.19.5/libexec/src/crypto/ecdh)
make[1]: *** [bin] Error 1
make: *** [service] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
nebula 1.7.0 https://github.com/Homebrew/homebrew-core/pull/131206
nebula: add HEAD version https://github.com/Homebrew/homebrew-core/pull/131113
nebula's formula was built from an unstable upstream --HEAD.
This build failure is expected behaviour.
Do not create issues about this on Homebrew's GitHub repositories.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

Now just have some weird dep problems that don't exist in the "build from 1.6.1 source" case..

**Comment by jasikpark** [comment]
```
calebjasik-defined@Calebs-MacBook-Pro-2 nebula-20230517-94863-13fkzcd % go mod tidy
go: go.mod file indicates go 1.20, but maximum version supported by tidy is 1.19
```

heh??

**Comment by jasikpark** [comment]
image

**Comment by chenrui333** [comment]
build and test out fine with the HEAD build, good for the merge.

**Review by chenrui333 — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
