### PR TITLE
x86_64-elf cross-toolchain

### PR DESCRIPTION
**Pull request by MRNIU**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
This was discussed previously: https://github.com/Homebrew/homebrew-core/pull/34666 and https://github.com/Homebrew/homebrew-core/pull/36001

The question is: could we make a multilib (or multitarget) x86/x86_64-elf binutils and gcc?

**Comment by MRNIU** [comment]
Now we can use x86_64-elf- for both 32bit and 64 bit, also other targets provided.
Maybe we should replace i386-elf with x86_64-elf toolchain.

**Comment by MRNIU** [comment]
Is there anyone here?

**Comment by fxcoudert** [comment]
Can you please instead update the `i386-elf-binutils` formula (and `i386-elf-gcc`) so they become multilib/multitarget?

**Comment by MRNIU** [comment]
I'd love to but I can't, which i386-elf with "--enable-targets=all" and "--enable-multilib" can only be forward compatible, without the ability of 64 bits, so we can not just update.

2019年11月6日 下午7:27，FX Coudert <notifications@github.com<mailto:notifications@github.com>> 写道：


Can you please instead update the i386-elf-binutils formula (and i386-elf-gcc) so they become multilib/multitarget?

**Comment by MRNIU** [comment]
I'd love to but I can't, which i386-elf with "--enable-targets=all" and "--enable-multilib" can only be forward compatible, without the ability of 64 bits, so we can not just update.

**Comment by MRNIU** [comment]
@fxcoudert 
It's been a long time.

**Comment by fxcoudert** [comment]
> i386-elf with "--enable-targets=all" and "--enable-multilib" can only be forward compatible, without the ability of 64 bits

It should definitely be possible to update the i386-elf toolchain to do 64-bit. Please do that.

**Comment by MRNIU** [comment]
@fxcoudert 
Here we go.
https://github.com/Homebrew/homebrew-core/pull/47935
Thank you.

**Pull request closed without merging**
