### PR TITLE
Various: support non-brew Mono where possible.

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Essentially does [this](https://github.com/Homebrew/brew/pull/2626) for everything except one formula without mandating the addition of yet another special requirement. These could be `[:run, :recommended]` but `:run` hasn't yet found a comfortable use really so sticking with the more vanilla `:recommended`.

### CODE REVIEW

**Comment by DomT4** [comment]
Yeah, let's ignore that I completely missed the `fetch` warning that the `sha256` was wrong locally. Didn't forget to change that before `fetch`ing, nope, not at all.

**Comment by ilovezfs** [comment]
Not really eager to add options.

**Comment by DomT4** [comment]
I appreciate that. This is consistent though, in the past we've had requests to facilitate using a non-brew `mono` and due to almost everything being effectively `:run` when it comes to `mono` deps we've been happy to provide that:

screen shot 2017-05-21 at 16 42 49

That just wasn't consistently enforced as widely as it could've been, which this PR resolves. I don't have a strong feeling either way on `mono` stuff but it is nice when things are consistent.

**Review by fxcoudert — APPROVED** [review]

**Comment by ilovezfs** [comment]
Nonetheless, going to pass on this for now.

**Comment by DomT4** [comment]
As you wish. There's a version bump buried in here you'll want to pick up yourself, I suspect.

**Comment by DomT4** [comment]
Also likely the fix for the `test` in one not using the full path 🤷‍♂️

**Pull request closed without merging**
