### PR TITLE
libupnp 1.12.0 & delete djmount, gmediaserver

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
<details>
<summary>build failure log</summary>

clang -DHAVE_CONFIG_H -I. -I. -I..  -I../lib -I../lib   -Wall -I.. -pthread -I/usr/local/Cellar/libupnp/1.12.0/include/upnp  -g -O2 -c webserver.c
upnp.c:216:57: error: incomplete definition of type 'struct Upnp_Subscription_Request'
    say(3, _("Event device UDN: %s\n"), quotearg(request->UDN));
                                                 ~~~~~~~^
upnp.c:208:36: note: forward declaration of 'struct Upnp_Subscription_Request'
handle_subscription_request(struct Upnp_Subscription_Request *request)
                                   ^
upnp.c:217:57: error: incomplete definition of type 'struct Upnp_Subscription_Request'
    say(3, _("Event service ID: %s\n"), quotearg(request->ServiceId));
                                                 ~~~~~~~^
upnp.c:208:36: note: forward declaration of 'struct Upnp_Subscription_Request'
handle_subscription_request(struct Upnp_Subscription_Request *request)
                                   ^
upnp.c:218:58: clang -DHAVE_CONFIG_H -I. -I. -I..  -I../lib -I../lib   -Wall -I.. -pthread -I/usr/local/Cellar/libupnp/1.12.0/include/upnp  -g -O2 -c webclient.c
error: incomplete definition of type 'struct Upnp_Subscription_Request'
webserver.c:95:6: error    say(3, _("Event request SID: %s\n"), quotearg(request->Sid));
                                                  ~~~~~~~^
upnp.c:208:36: note: forward declaration of 'struct Upnp_Subscription_Request'
handle_subscription_request(struct Upnp_Subscription_Request *request)
                                   ^
upnp.c:220:23: : incomplete definition of type 'struct File_Info'
        info->file_length = CONTENTDIRECTORY_DESC_LEN;
        ~~~~^
webserver.c:error: incomplete definition of type 'struct Upnp_Subscription_Request'
    if (strcmp(request->UDN, device_udn) != 0) {
               ~~~~~~~^
upnp.c:208:36: note: forward declaration of 'struct Upnp_Subscription_Request'
handle_subscription_request(struct Upnp_Subscription_Request *request)
                                   ^
upnp.c:221:96: error: incomplete definition of type 'struct Upnp_Subscription_Request'
        say(1, _("Discarding event - event device UDN (%s) not recognized\n"), quotearg(request->UDN));
                                                                                        ~~~~~~~^
upnp.c:208:36: note: forward declaration of 'struct Upnp_Subscription_Request'
87handle_subscription_request(struct Upnp_Subscription_Request *request)
                                   ^
:upnp.c:224:40: error: incomplete definition of type 'struct Upnp_Subscription_Request'
49    if ((service = find_service(request->ServiceId)) == NULL) {
                                ~~~~~~~^
upnp.c:208:36: note: forward declaration of 'struct Upnp_Subscription_Request'
handle_subscription_request(struct Upnp_Subscription_Request *request)
                                   ^
upnp.c:225:90: error: incomplete definition of type 'struct Upnp_Subscription_Request'
:         say(1, _("Discarding event - service ID (%s) not recognized\n"), quotearg(request->ServiceId));
                                                                                  ~~~~~~~^
upnp.c:208:36: note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
webserver.c:96:6: error: incomplete definition of type 'struct File_Info'
        info->last_modified = 0;
        ~~~~^
webserver.c:87:49: note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
webserver.c:97:6: error: incomplete definition of type 'struct File_Info'
        info->is_directory = 0;
        ~~~~^
webserver.c:87:49: note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
webserver.c:98:6: error: incomplete definition of type 'struct File_Info'
        info->is_readable = 1;
        ~~~~^
webserver.c:87:49: note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
webserver.c:99:6: error: incomplete definition of type 'struct File_Info'
        info->content_type = ixmlCloneDOMString("text/xml");
        ~~~~^
webserver.c:87:49note: forward declaration of 'struct Upnp_Subscription_Request'
:handle_subscription_request(struct Upnp_Subscription_Request *request)
                                   ^
 note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
upnp.c:246:53: error: incomplete definition of type 'struct Upnp_Subscription_Request'
        res = UpnpAcceptSubscription(device, request->UDN, request->ServiceId,
                                             ~~~~~~~^
upnp.c:208:36: note: forward declaration of 'struct Upnp_Subscription_Request'
handle_subscription_request(struct Upnp_Subscription_Request *request)
                                   ^
upnp.c:246:67: error: incomplete definition of type 'struct Upnp_Subscription_Request'
        res = UpnpAcceptSubscription(device, request->UDN, request->ServiceId,
                                                           ~~~~~~~^
upnp.c:208:36: note: forward declaration of 'struct Upnp_Subscription_Request'
handle_subscription_request(struct Upnp_Subscription_Request *request)
                                   ^
webserver.c:103:6: error: incomplete definition of type 'struct File_Info'
        info->file_length = CONNECTIONMANAGER_DESC_LEN;
        ~~~~^
webserver.c:87:49: note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)upnp.c:248:61
                                                ^
webserver.c:104:6: error: incomplete definition of type 'struct File_Info'
        info->last_modified = 0;
        ~~~~^
webserver.c:87:49: note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
webserver.c:105:6: error: incomplete definition of type 'struct File_Info'
        info->is_directory = 0;
        ~~~~^
webserver.c:87:49: note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
webserver.c:106:6: error: incomplete definition of type 'struct File_Info'
        info->is_readable = 1;
        ~~~~^
webserver.c:87:49: note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
webserver.c:107:6: error: incomplete definition of type 'struct File_Info'
        info->content_type = ixmlCloneDOMString("text/xml");
        ~~~~^
webserver.c:87:49: note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
webserver.c:117:13: error: incomplete definition of type 'struct File_Info'
: error: incomplete definition of type 'struct Upnp_Subscription_Request'
                                     variable_count, request->Sid);
                                                     ~~~~~~~^
upnp.c:208:36:        info->is_readable = 1;
        ~~~~^ note: forward declaration of 'struct Upnp_Subscription_Request'
handle_subscription_request(struct Upnp_Subscription_Request *request)
                                   ^
upnp.c:265:57: error: incomplete definition of type 'struct Upnp_State_Var_Request'

webserver.c:87:49: note: forward declaration of 'struct File_Info'
    say(3, _("Event device UDN: %s\n"), quotearg(request->DevUDN));webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
webserver.c:118:13: error: incomplete definition of type 'struct File_Info'

                                                 ~~~~~~~^
upnp.c:259:31: note: forward declaration of 'struct Upnp_State_Var_Request'
        info->is_directory = 0;
        ~~~~^
handle_get_var_request(struct Upnp_State_Var_Request *request)
                              ^
webserver.c:87:49: note: forward declaration of 'struct File_Info'
clang -DHAVE_CONFIG_H -I. -I. -I..  -I../lib -I../lib   -Wall -I.. -pthread -I/usr/local/Cellar/libupnp/1.12.0/include/upnp  -g -O2 -c main.c
webserver_get_info(const char *filename, struct File_Info *info)
upnp.c                                                ^:266:57: error: incomplete definition of type 'struct Upnp_State_Var_Request'

webserver.c:120:10: error: incomplete definition of type 'struct File_Info'
            info->file_length = detail->data.file.size;
            ~~~~^
webserver.c:87:49: note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
webserver.c:122:10: error    say(3, _("Event service ID: %s\n"), quotearg(request->ServiceID));
                                                 ~~~~~~~^
upnp.c:259:31: note: forward declaration of 'struct Upnp_State_Var_Request'
: handle_get_var_request(struct Upnp_State_Var_Request *request)
                              ^
incomplete definition of type 'struct File_Info'upnp.c:267:60: error: 
            info->file_length = -1;
            ~~~~^
webserver.c:incomplete definition of type 'struct Upnp_State_Var_Request'
87:    say(3, _("Event variable name: %s\n"), quotearg(request->StateVarName));
49: note: forward declaration of 'struct File_Info'
                                                    ~~~~~~~^webserver_get_info(const char *filename, struct File_Info *info)

upnp.c:                                                ^
webserver.c259:31:123:13: error: incomplete definition of type 'struct File_Info'
:        info->last_modified = detail->data.file.mtime;
        ~~~~^ note: forward declaration of 'struct Upnp_State_Var_Request'

handle_get_var_request(struct Upnp_State_Var_Request *request)
                              ^webserver.c:87:49:
 noteupnp.c:268:78: error: incomplete definition of type 'struct Upnp_State_Var_Request'
: forward declaration of 'struct File_Info'    say(3, _("Event source: %s\n"), inet_ntoa(((struct sockaddr_in *)&request->CtrlPtIPAddr)->sin_addr));
                                                                      ~~~~~~~^
upnp.c:259:31: note: 
forward declaration of 'struct Upnp_State_Var_Request'webserver_get_info(const char *filename, struct File_Info *info)
                                                ^

webserver.c:handle_get_var_request(struct Upnp_State_Var_Request *request)
                              ^
124upnp.c::27013: error: incomplete definition of type 'struct File_Info':23: error: incomplete definition of type 'struct Upnp_State_Var_Request'
    if (strcmp(request->DevUDN, device_udn) != 0) {
               ~~~~~~~^
upnp.c:259:31: note: forward declaration of 'struct Upnp_State_Var_Request'
handle_get_var_request(struct Upnp_State_Var_Request *request)
                              ^
upnp.c:271:96: error: incomplete definition of type 'struct Upnp_State_Var_Request'
        info->content_type = ixmlCloneDOMString(detail->data.file.mime_type);
        ~~~~^
webserver.c:87:49: note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
webserver.c:125:43: error: incomplete definition of type 'struct File_Info'
        say(4, _("  Readable: %s\n"), info->is_readable ? _("Yes") : _("No"));
                                      ~~~~^
webserver.c:87:49: note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
webserver.c:126:44: error: incomplete definition of type 'struct File_Info'
        say(4, _("  Directory: %s\n"), info->is_readable ? _("Yes") : _("No"));
                                       ~~~~^
webserver.c:87:49: note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
webserver.c:127:65: error: 
        say(1, _("Discarding event - event device UDN (%s) not recognized\n"), quotearg(request->DevUDN));
                                                                                        ~~~~~~~^
upnp.c:259:31: note: forward declaration of 'struct Upnp_State_Var_Request'
handle_get_var_request(struct Upnp_State_Var_Request *request)
                              ^
upnp.c:272:23: error: incomplete definition of type 'struct Upnp_State_Var_Request'
        strcpy(request->ErrStr, _("Unrecognized device"));
               ~~~~~~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/secure/_string.h:84:27: note: incomplete definition of type 'struct File_Info'
        say(4, _("  File Length: %" PRIi64 "\n"), (int64_t) info->file_length);
                                                            ~~~~^
webserver.c:87:49: note: forward declaration of 'struct File_Info'
webserver_get_info(const char *filename, struct File_Info *info)
                                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
expanded from macro 'strcpy'
                __builtin___strcpy_chk (dest, __VA_ARGS__, __darwin_obsz (dest))
                                        ^~~~
upnp.c:259:31: note: forward declaration of 'struct Upnp_State_Var_Request'
handle_get_var_request(struct Upnp_State_Var_Request *request)
                              ^
upnp.c:272:23: error: incomplete definition of type 'struct Upnp_State_Var_Request'
        strcpy(request->ErrStr, _("Unrecognized device"));
               ~~~~~~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/secure/_string.h:84:61: note: expanded from macro 'strcpy'
                __builtin___strcpy_chk (dest, __VA_ARGS__, __darwin_obsz (dest))
                                                                          ^~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/secure/_common.h:39:54: note: expanded from macro '__darwin_obsz'
#define __darwin_obsz(object) __builtin_object_size (object, _USE_FORTIFY_LEVEL > 1 ? 1 : 0)
                                                     ^~~~~~
upnp.c:259:31: note: forward declaration of 'struct Upnp_State_Var_Request'
handle_get_var_request(struct Upnp_State_Var_Request *request)
                              ^
upnp.c:273:16: error: incomplete definition of type 'struct Upnp_State_Var_Request'
        request->CurrentVal = NULL;
20 errors generated.
        ~~~~~~~^
upnp.c:259:31: note: forward declaration of 'struct Upnp_State_Var_Request'
handle_get_var_request(struct Upnp_State_Var_Request *request)
                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
make[4]: *** [webserver.o] Error 1
make[4]: *** Waiting for unfinished jobs....
20 errors generated.
make[4]: *** [upnp.o] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
</details>

**Comment by Bo98** [comment]
djmount's configure script is outdated and looks for `-lthreadutil` which no longer exists and was never meant for public consumption. I suppose it's easily patchable but given it's not been updated since 2006, YMMV.

gmediaserver is simply not compatible with the latest libupnp. Similarly, it has not been updated since 2007.

We'll either need to create a versioned formula or drop those formulae.

**Comment by Bo98** [comment]
Just so we know what we're dealing with, install counts over the last month:
* gmediaserver: 1
* djmount: 0

**Comment by SMillerDev** [comment]
Let's just drop it.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
