### PR TITLE
argocd-autopilot 0.3.3

### PR DESCRIPTION
**Pull request by roi-codefresh**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by iMichka — CHANGES_REQUESTED** [review]
This is not marked as an official release at https://github.com/argoproj-labs/argocd-autopilot/releases. Let's wait until this is done.

**Review by Qasim1234567890 — COMMENTED** [review]
Tu

**Comment by noam-codefresh** [comment]
we messed up v0.3.3 release a bit. re-releasing as v0.3.4 in a few minutes.

**Comment by noam-codefresh** [comment]
created updated pr in https://github.com/Homebrew/homebrew-core/pull/99550
please close the current one, sorry for the mess

**Comment by chenrui333** [comment]
@noam-codefresh no worries at all, also feel free to automate the process with `dawidd6/action-homebrew-bump-formula` or `mislav/bump-homebrew-formula-action`. Thanks!

**Pull request closed without merging**
