### PR TITLE
gauge 0.9.2

### PR DESCRIPTION
**Pull request by nehashri**
Created with `brew bump-formula-pr`.

---

Created by a bot. Please cc `@getgauge/core` on issues

### CODE REVIEW

**Comment by ilovezfs** [comment]
Should the `gauge_screenshot` resource block be updated, too?

**Comment by nehashri** [comment]
@ilovezfs `gauge_screenshot` need not be updated

**Comment by ilovezfs** [comment]
@nehashri regardless of whether it "needs" to be updated, we like to keep the resources in the formulae up to date unless it actually break something. Please update it to the current version.

@sriv the formula is failing to build because something has changed in gauge that no longer lets it build successfully from the source archive tarball. Maybe you know what the specific problem is? The source archive tarball used to work.

**Comment by nehashri** [comment]
@ilovezfs the latest version of gauge-screenshot version is compatible with development version of gauge. Hence, it need not be updated.
For the build failures, it seems to work properly for me. Is there any specific error that has occurred? More information on the failure would be helpful.

**Comment by ilovezfs** [comment]
>@ilovezfs the latest version of gauge-screenshot version is compatible with development version of gauge. Hence, it need not be updated.

Does that mean that updating the gauge-screenshot resource will break gauge?

The failure is shown here: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8234/version=sierra/console

**Comment by nehashri** [comment]
@ilovezfs gauge-screenshot may break with released version of gauge. Hence I had not updated it.
Also I have found the problem with gauge installation. There are a few changes which do not work well with source installations. Hence, I will be closing this PR and raise another one after we fix the bug in gauge.

**Pull request closed without merging**
