### PR TITLE
stout 1.3.2

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
```
==> go build -o /usr/local/Cellar/stout/1.3.2/bin/stout -v github.com/eagerio/stout/src
src/github.com/eagerio/stout/src/utils.go:15:2: cannot find package "github.com/sspencer/go-ini" in any of:
	/private/tmp/stout-20180811-59272-136jq43/Stout-1.3.2/src/github.com/eagerio/stout/vendor/github.com/sspencer/go-ini (vendor tree)
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/sspencer/go-ini (from $GOROOT)
	/private/tmp/stout-20180811-59272-136jq43/Stout-1.3.2/src/github.com/sspencer/go-ini (from $GOPATH)
```

**Comment by fxcoudert** [comment]
Previous attempt also failed: https://github.com/Homebrew/homebrew-core/pull/25818
Issue reported, not fixed: https://github.com/cloudflare/Stout/issues/52
Not sure if this is actively maintained, look at the github issues…

**Comment by lembacon** [comment]
Should have checked there are no any other previous attempts on this beforehand though, my bad 🤦🏻‍♂️.

**Pull request closed without merging**
