### PR TITLE
ruby-build 20200727

### PR DESCRIPTION
**Pull request by mislav**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by eregon** [comment]
Shouldn't this be updated?
`master` still seems to be `v20200722`: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ruby-build.rb

**Comment by eregon** [comment]
i.e., it fixes https://github.com/rbenv/ruby-build/releases/tag/v20200727

**Comment by Bo98** [comment]
I suspect the CI failure here was just because the branch wasn't based of the latest master. I've opened #58908.

**Comment by eregon** [comment]
Thank you!

**Comment by mislav** [comment]
I've accidentally prematurely closed this PR. Thanks @Bo98 for the rescue! ❤️

**Pull request closed without merging**
