### PR TITLE
gradle: update alias and add gradle@5

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Does anything in homebrew require gradle@5 and will upstream keep providing support?

**Comment by SeekingMeaning** [comment]
Hmm good question. I'll have to check on that.

Checklist:

- [ ] elasticsearch
- [ ] gdub
- [ ] groovyserv
- [ ] jadx
- [ ] pdftk-java
- [ ] smali
- [ ] spotbugs
- [ ] voldemort

**Comment by chenrui333** [comment]
technically, gssh is still using gradle@5 (5.2.1), but it got covered by the gradle wrapper.

**Comment by SMillerDev** [comment]
Yeah, we shouldn't use the wrapper

**Pull request closed without merging**
