### PR TITLE
qxmpp 1.3.0

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
Errors such as these in Catalina:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:319:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/math.h:749:12: note: 'finite' declared here
extern int finite(double)
           ^
```
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:320:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:321:9: error: no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:323:9: error: no member named 'isgreater' in the global namespace; did you mean 'qGreater'?
using ::isgreater;
      ~~^
```

**Comment by Bo98** [comment]
It's a Qt dependent so might need `depends_on :xcode => :build`. Qt is really awkward with SDKs.

**Comment by alebcay** [comment]
Still same errors in Catalina.

**Comment by Bo98** [comment]
Ah, that'll be because `std_cmake_args` didn't correctly check for `depends_on :xcode`. I've fixed this now in Homebrew/brew#7301 so try it again.

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Comment by Bo98** [comment]
I don't know how this formula ever worked. I don't know how it can possibly work on Mojave but not Catalina. It passes in the Xcode SDK from start to finish and suddenly pulls out the CLT SDK out of thin air and breaks everything.

I'll try reproduce the issue locally. Hopefully not another Xcode 11.4 breakage.

**Comment by Bo98** [comment]
Completely misread it - it is a test failure now rather than a build failure. https://github.com/Homebrew/brew/pull/7426 should fix it. Can you try rebase on master?

**Comment by alebcay** [comment]
Not sure if the `depends_on :xcode => :build` can be removed.

**Comment by Bo98** [comment]
I reckon it is still needed - the changes made in brew should make no difference for formulae that don't depend on Xcode. But feel free to try it out.

**Comment by Bo98** [comment]
Yeah, it needs Xcode to build. Doesn't seem to support the CLT SDK.

**Comment by chenrui333** [comment]
There is new release https://github.com/qxmpp-project/qxmpp/releases/tag/v1.3.0 (published 19 days ago)

**Comment by alebcay** [comment]
Looks like it's still needed. Adding it back now.

**Review by Bo98 — APPROVED** [review]

**Pull request closed without merging**
