### PR TITLE
txr 246

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
build error:

```
LINK opt/txr.o opt/lex.yy.o opt/y.tab.o opt/match.o opt/lib.o opt/regex.o opt/gc.o opt/unwind.o opt/stream.o opt/arith.o opt/hash.o opt/utf8.o opt/filter.o opt/eval.o opt/parser.o opt/rand.o opt/combi.o opt/sysif.o opt/args.o opt/lisplib.o opt/cadr.o opt/struct.o opt/itypes.o opt/buf.o opt/jmp.o opt/protsym.o opt/ffi.o opt/strudel.o opt/vm.o opt/chksum.o opt/chksums/sha256.o opt/chksums/crc32.o opt/chksums/md5.o opt/tree.o opt/time.o opt/mpi/mpi.o opt/debug.o opt/syslog.o opt/glob.o opt/ftw.o opt/signal.o opt/socket.o opt/termios.o opt/linenoise/linenoise.o -> txr
Undefined symbols for architecture x86_64:
  "_args_get_list", referenced from:
      _uw_invoke_catch in unwind.o
  "_do_generic_funcall", referenced from:
      _generic_funcall in lib.o
  "_eq", referenced from:
      _remq in lib.o
      _init in lib.o
      _seq_iter_ops in lib.o
      _char_set_obj_ops in regex.o
      _regex_obj_ops in regex.o
      _cont_ops in unwind.o
      _null_ops in stream.o
      ...
     (maybe you meant: _eq_s, _eql_based_k , _eq_based_k , _hash_equal , _hash_eql , _make_eq_hash , _eql_s , _equal , _equal_hash , _equal_based_k , _cobj_equal_handle_op , _str_eq , _eql , _eql_f , _cobj_eq_hash_op , _filter_equal , _eq_f , _equal_f , _equal_s )
  "_neq", referenced from:
      _keepq in lib.o
      _eval_init in eval.o
     (maybe you meant: _test_neq_set_indent_mode)
  "_neql", referenced from:
      _keepql in lib.o
      _eval_init in eval.o
  "_nequal", referenced from:
      _keepqual in lib.o
      _eval_init in eval.o
  "_null", referenced from:
      _init in lib.o
     (maybe you meant: _null_string, _null_list , _null_f , _nullify , _null_s , _nullify_s , _make_null_stream )
  "_rlcp", referenced from:
      _eval_init in eval.o
     (maybe you meant: _rlcp_tree)
  "_type", referenced from:
      _lazy_struct_init in struct.o
     (maybe you meant: _ffi_type_operator_p, _ffi_type_compile , _static_slot_type_reg , _struct_type_p , _struct_type_name , _ffi_type_s , _type_s , _struct_type_s , _ffi_type_p , _make_struct_type , _struct_type , _static_slot_types , _cptr_type , _cptr_typed , _sock_type , _type_error_s , _find_struct_type , _get_special_slot_by_type , _ffi_typedef , _typeof , _carray_type , _slot_types , _typep , _slot_type_reg , _type_mismatch )
  "_uw_block_return", referenced from:
      _uw_pop_block.cold.2 in unwind.o
      _op_return in eval.o
      _op_return_from in eval.o
      _return_star in eval.o
      _vm_retsr in vm.o
      _vm_retrs in vm.o
      _vm_retrr in vm.o
      ...
     (maybe you meant: _uw_block_return_proto)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: failing command:
clang -O2 -fno-stack-protector -nopie -fno-pie -iquote . -std=c99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200112 -D_GNU_SOURCE -D_DARWIN_C_SOURCE -Wall -Wextra -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=strict-prototypes -Werror=old-style-definition -g -o txr opt/txr.o opt/lex.yy.o opt/y.tab.o opt/match.o opt/lib.o opt/regex.o opt/gc.o opt/unwind.o opt/stream.o opt/arith.o opt/hash.o opt/utf8.o opt/filter.o opt/eval.o opt/parser.o opt/rand.o opt/combi.o opt/sysif.o opt/args.o opt/lisplib.o opt/cadr.o opt/struct.o opt/itypes.o opt/buf.o opt/jmp.o opt/protsym.o opt/ffi.o opt/strudel.o opt/vm.o opt/chksum.o opt/chksums/sha256.o opt/chksums/crc32.o opt/chksums/md5.o opt/tree.o opt/time.o opt/mpi/mpi.o opt/debug.o opt/syslog.o opt/glob.o opt/ftw.o opt/signal.o opt/socket.o opt/termios.o opt/linenoise/linenoise.o  -lm   
```

**Comment by chenrui333** [comment]
revisit later.

**Comment by chenrui333** [comment]
build from source failed for txr 244 as well

```
ffi.c:374:5: error: implicit declaration of function 'ffi_closure_free' [-Werror,-Wimplicit-function-declaration]
    ffi_closure_free(tfcl->clo);
    ^
ffi.c:374:5: note: did you mean 'ffi_closure_struct'?
ffi.c:351:32: note: 'ffi_closure_struct' declared here
static struct txr_ffi_closure *ffi_closure_struct(val obj)
                               ^
ffi.c:4739:12: error: implicit declaration of function 'ffi_prep_cif_var' [-Werror,-Wimplicit-function-declaration]
    ffis = ffi_prep_cif_var(&tfcd->cif, FFI_DEFAULT_ABI, nf, nt,
           ^
ffi.c:4739:12: note: did you mean 'ffi_prep_cif'?
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/ffi/ffi.h:312:1: note: 'ffi_prep_cif' declared here
ffi_prep_cif(
^
ffi.c:4963:23: error: implicit declaration of function 'ffi_closure_alloc' [-Werror,-Wimplicit-function-declaration]
                      ffi_closure_alloc(sizeof *tfcl->clo,
                      ^
ffi.c:4970:15: error: implicit declaration of function 'ffi_prep_closure_loc' [-Werror,-Wimplicit-function-declaration]
  if ((ffis = ffi_prep_closure_loc(tfcl->clo, &tfcd->cif,
              ^
ffi.c:4970:15: note: did you mean 'ffi_prep_closure'?
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/ffi/ffi.h:269:1: note: 'ffi_prep_closure' declared here
ffi_prep_closure(
^
4 errors generated.
make: failing command:
clang -MMD -MT opt/ffi.o -O2 -fno-stack-protector -nopie -fno-pie -iquote . -ansi -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200112 -D_GNU_SOURCE -D_DARWIN_C_SOURCE -Wall -Wextra -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=strict-prototypes -g -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/ffi -c -o opt/ffi.o ffi.c
make: *** [opt/ffi.o] Error 1
```

**Comment by gromgit** [comment]
It seems to be an issue with function inlining. `configure` autodetects `inline` in macOS, but `static inline` in Linux, and forcing the latter:
```
system "./configure", "--prefix=#{prefix}", "--inline=static inline"
```
builds and tests OK on everything from Mojave to Big Sur (Intel).

**Comment by chenrui333** [comment]
> system "./configure", "--prefix=#{prefix}", "--inline=static inline"

works for me, thanks!

**Comment by gromgit** [comment]
The ARM build failure is more tricky, as it seems to involve assembly code (`jmp.S`) that's conditionally generated based on C compiler defines. I don't have an M1 box, so someone else will have to advise on which `#define`s are applicable to M1 assembly language, and whether any of the ARM-based snippets in `jmp.S` are correct for M1 under macOS.

**Pull request closed without merging**
