### PR TITLE
handbrake: fix build on High Sierra

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
handbrake: fix build on High Sierra

### CODE REVIEW

**Comment by fxcoudert** [comment]
I tried to report the issue upstream, but couldn't pinpoint it as well as you did: https://github.com/HandBrake/HandBrake/issues/872

Can you update them, so it gets properly fixed?

**Comment by ilovezfs** [comment]
@fxcoudert someone needs to test what happens when the CLT is not installed before we can report anything really useful to upstream.

**Comment by ilovezfs** [comment]
@fxcoudert also it's not clear yet whether it's 10.13 only or Xcode 9.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Actually the problem is https://github.com/Homebrew/brew/pull/2883 (specifically https://github.com/Homebrew/brew/commit/890788af65f4b9c42b4eb7246771d96512f48260) and it's been broken since July. See https://github.com/Homebrew/homebrew-core/pull/18795.

**Comment by ilovezfs** [comment]
The issue in `brew` is now fixed: https://github.com/Homebrew/brew/pull/3252.

**Comment by JCount** [comment]
Good work, @ilovezfs!

**Comment by JCount** [comment]
Fixed by https://github.com/Homebrew/brew/pull/3252.

**Pull request closed without merging**
