### PR TITLE
ocaml 4.10.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

previous effort, #52742

cc @tchajed @Moisan

### CODE REVIEW

**Comment by chenrui333** [comment]
```
 Error: 6 failed steps!
 brew install --build-from-source comby
 brew test --verbose lablgtk
 brew install --build-from-source ott
 brew install --build-from-source unison
 brew install --build-from-source infer
 brew install --verbose --build-bottle ocamlsdl
```

**Comment by chenrui333** [comment]
for infer,

```
 [34m==>[0m [1mopam pin add ppx_tools 5.3+4.08.0 --locked[0m
 Last 150 lines from /Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/logs/infer/05.opam:
 2020-07-03 21:51:38 +0100
 
 opam
 pin
 add
 ppx_tools
 5.3+4.08.0
 --locked
 
 ppx_tools is now pinned to version 5.3+4.08.0
 
 The following dependencies couldn't be met:
   - ppx_tools → ocaml < 4.10
       base of this switch (use `--unlock-base' to force)
 
 [NOTE] Pinning command successful, but your installed packages may be out of sync.
 'opam pin add ppx_tools 5.3+4.08.0 --locked' failed.
 
 [31mREAD THIS:[0m [4mhttps://docs.brew.sh/Troubleshooting[24m
 
```

**Comment by chenrui333** [comment]
for ocamlsdl

```
 Configure finished, type 'make' to build.
 [34m==>[0m [1mmake[0m
 /Applications/Xcode.app/Contents/Developer/usr/bin/make -C src all
 ocamlc.opt  sdl.mli
 ocamlc.opt  sdlcdrom.mli
 ocamlc.opt  sdltimer.mli
 ocamlc.opt  sdljoystick.mli
 ocamlc.opt  sdlkey.mli
 ocamlc.opt  sdlmouse.mli
 ocamlc.opt  sdlvideo.mli
 ocamlc.opt  sdlmixer.mli
 ocamlc.opt -ccopt "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -D_THREAD_SAFE -g -O " sdl_stub.c
 ocamlc.opt -ccopt "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -D_THREAD_SAFE -g -O " sdlcdrom_stub.c
 ocamlc.opt -ccopt "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -D_THREAD_SAFE -g -O " sdltimer_stub.c
 ocamlc.opt -ccopt "-I/usr/local/include/SDL -D_GNU_SOURCE=1 -D_THREAD_SAFE -g -O " sdljoystick_stub.c
 File "sdlmixer.mli", line 1:
 Error: Invalid import of Sdl, compiled with -unsafe-string.
        This compiler has been configured in strict safe-string mode (-force-safe-string)
 make[1]: *** [sdlmixer.cmi] Error 2
 make[1]: *** Waiting for unfinished jobs....
 make: *** [all] Error 2
```

**Comment by chenrui333** [comment]
for `lablgtk`

```
 Testing lablgtk
 /usr/bin/sandbox-exec -f /private/tmp/homebrew20200703-77660-1grzzhd.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lablgtk.rb --verbose
 [34m==>[0m [1mocamlc -I /usr/local/opt/lablgtk/lib/ocaml/lablgtk2 lablgtk.cma gtkInit.cmo test.ml -o test -cclib -latk-1.0 -cclib -lcairo -cclib -lgdk-quartz-2.0 -cclib -lgdk_pixbuf-2.0 -cclib -lgio-2.0 -cclib -lglib-2.0 -cclib -lgobject-2.0 -cclib -lgtk-quartz-2.0 -cclib -lgtksourceview-2.0 -cclib -lintl -cclib -lpango-1.0 -cclib -lpangocairo-1.0[0m
 File "test.ml", line 1:
 Error: /usr/local/opt/lablgtk/lib/ocaml/lablgtk2/gtkMain.cmi
        is not a compiled interface for this version of OCaml.
 It seems to be for an older version of OCaml.
 [31mError:[0m lablgtk: failed
```

**Comment by Bo98** [comment]
Infer cannot use OCaml 4.10 until 1.0 releases, which should be "soon".

**Comment by Bo98** [comment]
See #51255, which was originally a 4.10 PR.

**Comment by tchajed** [comment]
ott is failing only because the sha256 sum is wrong; fixed in #57408 

I tried installing it with opam using OCaml 4.10.0 and that worked.

**Comment by alebcay** [comment]
`ocaml` 4.11.0 is now available.

**Comment by chenrui333** [comment]
> `ocaml` 4.11.0 is now available.

yeah, let's do incremental bump.

**Comment by chenrui333** [comment]
across OSX builds
```
brew install --build-from-source infer
brew install --verbose --build-bottle ocamlsdl
brew install --verbose --build-bottle unison
```

**Comment by chenrui333** [comment]
This a shorten list than ocaml 4.09.0, proceeding with a merge.

**Comment by chenrui333** [comment]
merging the PR.

**Pull request closed without merging**
