### PR TITLE
python 3.7.0

### PR DESCRIPTION
**Pull request by sashkab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by sashkab** [comment]
I think bumping revisions for failed packages should fix most of the errors detected in CI. Correct me if I'm wrong.

**Comment by oudingfan** [comment]
can't wait to update to python 3.7

**Comment by lithammer** [comment]
Out of curiosity, will 3.6 be available as `python@3.6` or would I need to use [pyenv](https://github.com/pyenv/pyenv/) for that?

**Comment by ilovezfs** [comment]
There is no plan to add a python@3.6 at this time. See discussion on https://github.com/Homebrew/homebrew-core/pull/10239

**Comment by ilovezfs** [comment]
let's hold off on pushing more commits here for now

**Comment by ilovezfs** [comment]
So far, I have fixes locally for

- [ ] diffoscope
- [ ] flintrock
- [ ] ipython
- [ ] juju-wait
- [ ] ocrmypdf
- [ ] pytouhou

**Comment by ilovezfs** [comment]
The `root` build failure is
```
/tmp/root-20180628-17694-yteyfj/root-6.14.00/bindings/pyroot/src/PyRootType.cxx:103:22: error: cannot initialize a variable of type 'char *' with an rvalue of type 'const char *'
               char* cppname = PyROOT_PyUnicode_AsString(pycppname);
                     ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
so probably can be fixed with a cast or just `const char* cppname` but I haven't tested.

Same issue for `opencv`.

**Comment by ilovezfs** [comment]
vim@7.4 needs https://github.com/vim/vim/commit/16d7eced1a08565a9837db8067c7b9db5ed68854

**Comment by ilovezfs** [comment]
also have local fixes for opencv and root.

Feel free to push more commits. CI has calmed down

**Comment by sashkab** [comment]
@ilovezfs how do you want to handle this PR? There are a lot of changes in many formulas, so not sure if I want to start resolving merge conflicts, or wait for you to push your local changes?

**Comment by ilovezfs** [comment]
@sashkab hopefully it'll be OK now except for https://github.com/conjure-up/conjure-up/issues/1484. We shall see.

**Comment by ilovezfs** [comment]
Thanks for the PR @sashkab! Shipped.

**Pull request closed without merging**
