### PR TITLE
xonsh 0.9.13

### PR DESCRIPTION
**Pull request by samueldg**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Resource `prompt_toolkit` needs to be updated too.

**Comment by samueldg** [comment]
@Moisan I rebased on master, then also added the latest version of `prompt_toolkit` I found on PyPI: 2.0.10: https://pypi.org/project/prompt_toolkit/2.0.10/#files with the corresponding sha.

I wasn't too sure about how to update this since it isn't picked up by `bump-formula-pr`, but I did some digging and found #33072, then superseded by #33987, who solved the same issue.
Let me know if the change is ok.

Also, I'm not sure that rebase was a good thing, since a bunch of unrelated changes are showing up in the CI: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/50270/

**Comment by Moisan** [comment]
You did the right thing! I wouldn't worry about the commits in the CI. You only need to squash your commits into one with the original commit message `xonsh 0.9.13` and then `git push --force`. We'll be good to merge it after.

**Comment by samueldg** [comment]
@Moisan: Done! Thanks for you help 👍

**Comment by chenrui333** [comment]
Thanks @samueldg @Moisan!!

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
