### PR TITLE
nettle: fix Xcode/CLT 10+ build

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Unless this has been merged upstream, I don't think we want to making formula changes for 10.14.

**Comment by DomT4** [comment]
I thought we already had in multiple places? `fontconfig`, `node`, etc? `node` in particular got some pretty heavy patching for a while. An alternative would be to simply not run `make check` against Xcode 10 I guess.

I can file it upstream if Misty doesn't have an objection, but I can't promise an especially quick response given we've been carrying the existing `inreplace` around for the last 30 months lol.

**Comment by DomT4** [comment]
> The node patches are from upstream, no?

Could well have been, to be fair. I suspect they were folded in pretty quickly because of how active `node` is as a project.

> what does the etc. refer to

The reality that I haven't had the time lately to check every commit & may well have missed something 😸.

I'd prefer we go for some resolution here, whether it's the minor `inreplace` or selectively disabling `make check`, because `nettle` is a recursive dependency of some pretty major formulae, including both `gnutls` and `gnupg`, and the former of which not being able to build automatically blocks the building of another ~40 formulae.

**Comment by DomT4** [comment]
`brew uses nettle --recursive --include-build | wc -l` returns 98, which is a pretty chunky number.

**Comment by ilovezfs** [comment]
>selectively disabling make check

If we're not yet confident that the change should actually be reported and merged upstream, then I'd favor this.

**Comment by ilovezfs** [comment]
FWIW, my guess is that this one is upstreamable. If there's a new symbol, there's a new symbol. I don't see why we'd expect it to disappear in a later Xcode 10 beta.

**Comment by DomT4** [comment]
Alright, I've filed it upstream. I'll stick a link here once the mailing list archive catches up.

**Comment by mistydemeo** [comment]
> It looks potentially like the feature can be disabled by passing `-mno-stack-probe` which we could do in our shim (I think?), but I guess we don't want to go down that path.

That option doesn't appear to have made it into the patch that's in Xcode 10:

```
clang: error: unknown argument: '-mno-stack-probe'
```

The comment on the LLVM review indicates that there's a different patch which will be upstreamed later: https://reviews.llvm.org/D40864#1100905

**Comment by DomT4** [comment]
> That option doesn't appear to have made it into the patch that's in Xcode 10

Looks like it might have changed slightly from the version submitted to LLVM upstream. `clang -cc1 --help` returns this argument which looks like the same thing:
```
-mno-stack-arg-probe    Disable stack probes which are enabled by default
```

**Comment by mistydemeo** [comment]
> `-mno-stack-arg-probe    Disable stack probes which are enabled by default`

Sounds right. 👍 With luck we shouldn't need to disable it though.

**Comment by DomT4** [comment]
Could we append that to `CFLAGS` individually here as a workaround temporarily or would that get stripped by the shim? I'm assuming Joe might find that more palatable than patching something upstream might not be willing to take yet, but I'll let him chime in on that.

**Comment by ilovezfs** [comment]
What is `make check` complaining about? Is it that the symbol is being exported and shouldn't be?

**Comment by ilovezfs** [comment]
Let's just scope the `inreplace` for now and make sure the upstream issue url is in there. Is it needed for Xcode 10 + macOS 10.13 too?
```
if DevelopmentTools.clang_build_version >= 1000
```

**Comment by DomT4** [comment]
> Is it needed for Xcode 10 + macOS 10.13 too?

Haven't checked this but seems extremely likely. Update pushed.

**Comment by ilovezfs** [comment]
Early 🐦 gets the worm

**Comment by DomT4** [comment]
Merged upstream FYI: https://git.lysator.liu.se/nettle/nettle/commit/f3e2607fce0c6da41eb1d9ee89b9535d4abec7be

**Pull request merged**
