### PR TITLE
workflows/triage: force ARM for new formulae

### PR DESCRIPTION
**Pull request by carlocab**
This makes @BrewTestBot add the CI-force-arm label to all new formula PRs.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@carlocab It feels like this would be better addressed in `brew test-bot` instead? Thoughts?

**Review by MikeMcQuaid — CHANGES_REQUESTED** [review]
Let's try and do this in `brew-test-bot`?

**Comment by carlocab** [comment]
Sure, yes. I'll have a look at `test-bot`.

**Comment by carlocab** [comment]
Opened https://github.com/Homebrew/homebrew-test-bot/issues/562.

**Pull request closed without merging**
