### PR TITLE
urh 2.8.8

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by dtrodrigues — COMMENTED** [review]
urh removed the dependency on `pyzmq` in https://github.com/jopohl/urh/releases/tag/v2.8.5 with commit https://github.com/jopohl/urh/commit/7e150293980fd9c5360d51da81cf51f1f67cac8a#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by Moisan** [comment]
That looks good, thank you for the precision. Could you squash all those commits in one while keeping the original commit message (`urh 2.8.8`)? Then you should be ready to merge.

**Comment by dtrodrigues** [comment]
@Moisan done!

**Review by Moisan — APPROVED** [review]
Thank you @dtrodrigues !

**Review by chenrui333 — APPROVED** [review]
💯 :shipit:

**Pull request closed without merging**
