### PR TITLE
poppler 21.01.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
brew linkage --test gdal
brew test --retry --verbose gdal
brew test --retry --verbose gmt
brew test --retry --verbose gmt@5
brew test --retry --verbose mapserver
brew test --retry --verbose pdal
brew linkage --test pdftoipe
brew test --retry --verbose pdftoipe
brew test --retry --verbose points2grid
brew test --retry --verbose simple-tiles

**Comment by carlocab** [comment]
Just give `gdal` and `pdftoipe` revision bumps, that should surely resolve some of the other test failures.

**Comment by carlocab** [comment]
If you haven't checked, I also looked up the resource block. Doesn't need updating, I think.

**Comment by carlocab** [comment]
Are you sure that all of these need revision bumps? The last `poppler` bump didn't need as many: https://github.com/Homebrew/homebrew-core/pull/66369

Users tend to complain when they get unexpected upgrades, so I'd like to keep the revision bumping to only the formulae where we know they're needed.

**Comment by chenrui333** [comment]
> Are you sure that all of these need revision bumps? The last `poppler` bump didn't need as many: #66369
> 
> Users tend to complain when they get unexpected upgrades, so I'd like to keep the revision bumping to only the formulae where we know they're needed.

This one did have those revision bumps. So basically I did the revision bumps into two categories:
- runtime dependencies, which need `poppler`
- runtime dependencies, which need `gdal` (which actually failed earlier)

**Comment by carlocab** [comment]
CI failed quickly on ARM for some reason. Going to try to restart it.

**Comment by chenrui333** [comment]
```
brew install --verbose --build-bottle mapnik
brew test --verbose nuxeo
brew audit pdfpc --online --git --skip-style
```

**Comment by chenrui333** [comment]
mapnik build pass last time, #65895

**Comment by chenrui333** [comment]
pdfpc has license update recently (switched to GPLv3+), https://github.com/pdfpc/pdfpc/pull/567

**Comment by chenrui333** [comment]
nuxeo test passed in my local. :(

**Comment by carlocab** [comment]
```
==> brew audit pdfpc --online --git --skip-style
==> FAILED
pdfpc:
  * Formula license ["GPL-2.0-or-later"] does not match GitHub license ["GPL-3.0"].
Error: 1 problem in 1 formula detected
```

**Comment by carlocab** [comment]
ARM:
```
Error: 1 failed steps!
brew test --verbose nuxeo
```
Big Sur, Catalina, Mojave:
```
Error: 3 failed steps!
brew install --verbose --build-bottle mapnik
brew test --verbose nuxeo
brew audit pdfpc --online --git --skip-style
```

**Comment by carlocab** [comment]
nuxeo:
```
==> FAILED
==> Testing nuxeo
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210103-2106-1qmsk3x.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nuxeo.rb --verbose
==> /usr/local/Cellar/nuxeo/10.10_1/libexec/bin/nuxeoctl config -q --get nuxeo.conf
Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.
ERROR: Nuxeo requires Java 1.8+ (detected )

Error: nuxeo: failed
```

<details><summary>mapnik compiler errors</summary>
<p>

```
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:54:12: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
    : std::conditional_t<Trait::value, conjunction<Traits...>, Trait>
      ~~~~~^~~~~~~~~~~~~
           conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:429:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:68:12: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
    : std::conditional_t<Trait::value, Trait, disjunction<Traits...>>
      ~~~~~^~~~~~~~~~~~~
           conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:429:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:95:18: error: no template named 'remove_cv_t' in namespace 'std'; did you mean simply 'remove_cv_t'?
    using type = std::remove_cv_t<std::remove_reference_t<T>>;
                 ^~~~~~~~~~~~~~~~
                 remove_cv_t
/usr/local/opt/boost/include/boost/type_traits/remove_cv.hpp:39:23: note: 'remove_cv_t' declared here
   template <class T> using remove_cv_t = typename remove_cv<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:95:35: error: no template named 'remove_reference_t' in namespace 'std'; did you mean simply 'remove_reference_t'?
    using type = std::remove_cv_t<std::remove_reference_t<T>>;
                                  ^~~~~~~~~~~~~~~~~~~~~~~
                                  remove_reference_t
/usr/local/opt/boost/include/boost/type_traits/remove_reference.hpp:53:23: note: 'remove_reference_t' declared here
   template <class T> using remove_reference_t = typename remove_reference<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:105:18: error: no template named 'remove_const_t' in namespace 'std'; did you mean simply 'remove_const_t'?
    using type = std::remove_const_t<std::remove_reference_t<T>>;
                 ^~~~~~~~~~~~~~~~~~~
                 remove_const_t
/usr/local/opt/boost/include/boost/type_traits/remove_const.hpp:33:23: note: 'remove_const_t' declared here
   template <class T> using remove_const_t = typename remove_const<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:105:38: error: no template named 'remove_reference_t' in namespace 'std'; did you mean simply 'remove_reference_t'?
    using type = std::remove_const_t<std::remove_reference_t<T>>;
                                     ^~~~~~~~~~~~~~~~~~~~~~~
                                     remove_reference_t
/usr/local/opt/boost/include/boost/type_traits/remove_reference.hpp:53:23: note: 'remove_reference_t' declared here
   template <class T> using remove_reference_t = typename remove_reference<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:115:18: error: no template named 'remove_const_t' in namespace 'std'; did you mean simply 'remove_const_t'?
    using type = std::remove_const_t
                 ^~~~~~~~~~~~~~~~~~~
                 remove_const_t
/usr/local/opt/boost/include/boost/type_traits/remove_const.hpp:33:23: note: 'remove_const_t' declared here
   template <class T> using remove_const_t = typename remove_const<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:117:13: error: no template named 'remove_pointer_t' in namespace 'std'; did you mean simply 'remove_pointer_t'?
            std::remove_pointer_t<std::remove_reference_t<T>>
            ^~~~~~~~~~~~~~~~~~~~~
            remove_pointer_t
/usr/local/opt/boost/include/boost/type_traits/remove_pointer.hpp:78:23: note: 'remove_pointer_t' declared here
   template <class T> using remove_pointer_t = typename remove_pointer<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:117:35: error: no template named 'remove_reference_t' in namespace 'std'; did you mean simply 'remove_reference_t'?
            std::remove_pointer_t<std::remove_reference_t<T>>
                                  ^~~~~~~~~~~~~~~~~~~~~~~
                                  remove_reference_t
/usr/local/opt/boost/include/boost/type_traits/remove_reference.hpp:53:23: note: 'remove_reference_t' declared here
   template <class T> using remove_reference_t = typename remove_reference<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:129:23: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
    using type = std::conditional_t
                 ~~~~~^~~~~~~~~~~~~
                      conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:429:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:131:39: error: no template named 'remove_reference_t' in namespace 'std'; did you mean simply 'remove_reference_t'?
                        std::is_const<std::remove_reference_t<From>>::value,
                                      ^~~~~~~~~~~~~~~~~~~~~~~
                                      remove_reference_t
/usr/local/opt/boost/include/boost/type_traits/remove_reference.hpp:53:23: note: 'remove_reference_t' declared here
   template <class T> using remove_reference_t = typename remove_reference<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:132:25: error: no template named 'add_const_t' in namespace 'std'; did you mean simply 'add_const_t'?
                        std::add_const_t<To>,
                        ^~~~~~~~~~~~~~~~
                        add_const_t
/usr/local/opt/boost/include/boost/type_traits/add_const.hpp:46:23: note: 'add_const_t' declared here
   template <class T> using add_const_t = typename add_const<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:166:18: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
    typedef std::conditional_t
            ~~~~~^~~~~~~~~~~~~
                 conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:429:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:38:
In file included from /usr/local/opt/boost/include/boost/geometry.hpp:17:
In file included from /usr/local/opt/boost/include/boost/geometry/geometry.hpp:34:
In file included from /usr/local/opt/boost/include/boost/geometry/core/closure.hpp:24:
/usr/local/opt/boost/include/boost/geometry/core/ring_type.hpp:96:18: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
    typedef std::conditional_t
            ~~~~~^~~~~~~~~~~~~
                 conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:429:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:38:
In file included from /usr/local/opt/boost/include/boost/geometry.hpp:17:
In file included from /usr/local/opt/boost/include/boost/geometry/geometry.hpp:34:
In file included from /usr/local/opt/boost/include/boost/geometry/core/closure.hpp:24:
/usr/local/opt/boost/include/boost/geometry/core/ring_type.hpp:111:18: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
            std::conditional_t
            ~~~~~^~~~~~~~~~~~~
                 conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:429:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:38:
In file included from /usr/local/opt/boost/include/boost/geometry.hpp:17:
In file included from /usr/local/opt/boost/include/boost/geometry/geometry.hpp:34:
In file included from /usr/local/opt/boost/include/boost/geometry/core/closure.hpp:24:
/usr/local/opt/boost/include/boost/geometry/core/ring_type.hpp:127:18: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
            std::conditional_t
            ~~~~~^~~~~~~~~~~~~
                 conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:429:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:38:
In file included from /usr/local/opt/boost/include/boost/geometry.hpp:17:
In file included from /usr/local/opt/boost/include/boost/geometry/geometry.hpp:35:
/usr/local/opt/boost/include/boost/geometry/core/coordinate_dimension.hpp:101:23: error: constexpr function's return type 'void' is not a literal type
constexpr inline void assert_dimension()
                      ^
/usr/local/opt/boost/include/boost/geometry/core/coordinate_dimension.hpp:111:23: error: constexpr function's return type 'void' is not a literal type
constexpr inline void assert_dimension_less_equal()
                      ^
/usr/local/opt/boost/include/boost/geometry/core/coordinate_dimension.hpp:117:23: error: constexpr function's return type 'void' is not a literal type
constexpr inline void assert_dimension_greater_equal()
                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

</p>
</details>

mapnik also complains about the patch ending unexpectedly. Not sure if that's related.

**Comment by chenrui333** [comment]
Will do another push once upstream provides the boost 1.75 compatible change for mapnik.

**Comment by carlocab** [comment]
mapnik is not compatible with boost 1.75? That didn't show up in CI at the version bump though. Strange. I wonder if mapnik's test is insufficient.

**Comment by chenrui333** [comment]
> mapnik is not compatible with boost 1.75? That didn't show up in CI at the version bump though. Strange. I wonder if mapnik's test is insufficient.

not compatible during the build time, if we rebuild when we did boost 1.75, we should be able to find it out.

**Comment by carlocab** [comment]
mapnik: https://github.com/Homebrew/homebrew-core/pull/68359

**Comment by carlocab** [comment]
mapnik should be fixed now. You can try again.

**Comment by chenrui333** [comment]
let me do the rebase.

**Comment by carlocab** [comment]
Wait, why have you given `nuxeo` a revision bump? `nuxeo` is `bottle :unneeded`, so a revision bump does nothing.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
The only error is `nuxeo`. I am merging, except for the `nuxeo` revision bump, as I think it is not necessary. Let's just open a new PR if I'm mistaken.

**Pull request closed without merging**
