### PR TITLE
mobile-shell 1.2.6

### PR DESCRIPTION
**Pull request by ilovezfs**
verified new version still builds with protobuf 3

### CODE REVIEW

**Comment by DomT4** [comment]
👍

**Comment by ilovezfs** [comment]
no news item yet https://mosh.mit.edu/#getting

**Comment by DomT4** [comment]
Interesting. @cgull - Is this release considered the new stable yet?

**Comment by ilovezfs** [comment]
It's now been shipped.

**Comment by cgull** [comment]
Sorry, I didn't see this email in an auto-created folder. Yes, it's official now, it took us an extra day or two to get OS X packages built and relnotes written.

For the `test` method, you could now do `mosh --local 127.0.0.1 true` or `mosh --local ::1 true`.  Those will start a session without using `ssh` and test much more functionality.

**Comment by ilovezfs** [comment]
@cgull https://github.com/Homebrew/homebrew-core/pull/3880

**Pull request closed without merging**
