### PR TITLE
protobuf 3.0.0

### PR DESCRIPTION
**Pull request by jeroen**
Protobuf 3.0.0 is now final. Perhaps it should become the default at some point. I'll make that a seperate PR (once this one is merged).

### CODE REVIEW

**Comment by jeroenooms** [comment]
👍🍺

**Comment by DomT4** [comment]
I'm not sure this is necessarily a great idea, because it means anyone on devel won't be shunted across to stable until at least the next 3.x release once we actually get the 3.x release merged stable, which admittedly could be a wee while yet.

**Comment by jeroenooms** [comment]
Not sure I understand. So you prefer to make 3.0.0 stable straight away?

**Comment by MikeMcQuaid** [comment]
> Not sure I understand. So you prefer to make 3.0.0 stable straight away?

Yes.

**Comment by jeroenooms** [comment]
OK I have updated the PR accordingly.

**Comment by DomT4** [comment]
Of course, we now have the problems from https://github.com/Homebrew/homebrew-core/pull/3415 to deal with 🙈.

**Comment by ilovezfs** [comment]
@DomT4 zbackup:
```
iMac-TMP:homebrew-core joe$ brew test -v zbackup
Testing zbackup
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160814-46673-1edmb47.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/zbackup.rb -v
==> /usr/local/Cellar/zbackup/1.4.4_1/bin/zbackup --non-encrypted init .
==> echo test | /usr/local/Cellar/zbackup/1.4.4_1/bin/zbackup --non-encrypted backup backups/test.bak
Loading index...
Index loaded.
Using up to 8 thread(s) for compression
iMac-TMP:homebrew-core joe$ brew linkage zbackup
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/lzo/lib/liblzo2.2.dylib (lzo)
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)
  /usr/local/opt/protobuf/lib/libprotobuf.10.dylib (protobuf)
  /usr/local/opt/xz/lib/liblzma.5.dylib (xz)
iMac-TMP:homebrew-core joe$ mdutil -t /usr/local/opt/protobuf/lib/libprotobuf.10.dylib
/usr/local/Cellar/protobuf/3.0.0/lib/libprotobuf.10.dylib
```

It was just a collision between the CHECK macro in protobuf and the CHECK macro in zbackup, so find/replace CHECK->ZCHECK fixes it.

Were there more problems besides that?

**Comment by ilovezfs** [comment]
what's the status here?

**Comment by apjanke** [comment]
Think we should close this in favor of #3415, which does the same thing but includes the required dependent revision bumps and the original discussion.

**Comment by DomT4** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-core/pull/4145. Thanks for the submission nonetheless @jeroenooms! ❤️

**Comment by jeroenooms** [comment]
@DomT4  @MikeMcQuaid Is there any way we can reconsider this original PR to upgrade at least the `devel` build to 3.0.0-release? We are now a month down the line and homebrew users still cannot use 3.0.0 because it is not ready for `stable` but we are not upgrading the `devel` branch either.

I personally think it is a much more undesirable situation that protobuf 3.0.0 is stuck on beta while a stable was released on July 27.

**Comment by ilovezfs** [comment]
@jeroenooms https://github.com/Homebrew/homebrew-core/pull/4145 should be merged soon.

**Comment by ilovezfs** [comment]
@jeroenooms #4145 has shipped.

**Pull request closed without merging**
