### PR TITLE
netpbm 10.73.07

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

@ilovezfs This was bumped accidentally(?) from stable to advanced in the past, but there are some issues with both current stable/advanced that would encourage a bump to the latest release on either branch. Are you happy staying on `advanced` or do you want a `version_scheme` bump here and a drop back down to stable?

### CODE REVIEW

**Comment by ilovezfs** [comment]
It looks like it was a deliberate decision here: https://github.com/Homebrew/legacy-homebrew/pull/15762

But if those reasons are now out the window, it sounds like we should go back to stable or super stable without a reason not to.

**Comment by DomT4** [comment]
Cool, I'll push the `version_scheme` method shortly then, presuming `stable` builds now.

**Comment by DomT4** [comment]
Looks like that worked fine 🎉

**Comment by ilovezfs** [comment]
@DomT4 should the basename of the url not be "stable"?

**Comment by DomT4** [comment]
Oops! 😓. That's what I get for trying to get something done in a spare 10 minutes. Will fix.

**Comment by ilovezfs** [comment]
Hehe no problem.

**Comment by DomT4** [comment]
Stupid error fixed 🙈

**Comment by woodruffw** [comment]
:tada:

**Pull request closed without merging**
