### PR TITLE
makensis: fix PREFIX_DOC

### PR DESCRIPTION
**Pull request by idleberg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Running `makensis -HDRINFO` will list the compiler flags the binary has been built with. Among these are several file locations, including the path for the documentation:

```
NSISDIR=/usr/local/share/nsis
PREFIX_CONF=/usr/local/etc
PREFIX_DATA=/usr/local/share/nsis
PREFIX_DOC=/usr/local/share/doc/nsis
```

Unfortunately, the path in `PREFIX_DOC` does not exist after installation. This PR fixes that. While it works, I'm not 100% sure I used the preferred variable.

### CODE REVIEW

**Comment by dunn** [comment]
@brewtestbot test this please

**Comment by ilovezfs** [comment]
We prefer to use `#{doc}` for the location of documentation. That translates into `/usr/local/Cellar/makensis/3.02.1/share/doc/makensis` as opposed to `/usr/local/Cellar/makensis/3.02.1/share/nsis/Docs`

**Comment by idleberg** [comment]
> We prefer to use #{doc} for the location of documentation.

What do you suggest? The PR does not change the location of the documentation, but makes sure the location in use is stored in the flags. I can move the documentation itself as well, if that's what you're asking.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks @idleberg! Shipped.

**Pull request closed without merging**
