### PR TITLE
gcc@7: split args for macOS and Linux

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
I think we want to merge this with bottles. Judging from the log, it looks like the Mojave bottle was built when the CLT on the Mojave runner was broken (we had the Catalina SDK installed instead), and hasn't been rebuilt since that was fixed.

That would explain this: https://github.com/Homebrew/discussions/discussions/1256

**Comment by iMichka** [comment]
I'm fine with that. Should I revision-bump it?

**Comment by carlocab** [comment]
Not sure. We haven't seen a complaint about it until now so I suspect it's not really needed. Still, I guess it doesn't hurt.

**Comment by iMichka** [comment]
I bumped the revision.

Regarding the license, I'll do a separate PR for all the gcc versions later.

**Comment by carlocab** [comment]
Ok. May as well rev-bump all the `gcc` PRs you have open that still build on our current runners. That's gcc 6, 8, and 9, I think.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
