### PR TITLE
Delete carthage.rb

### PR DESCRIPTION
**Pull request by nawafuyfc**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jdhealy** [comment]
Why is this proposed for deletion?

**Comment by DavidBrunow** [comment]
Carthage is a good thing and I would like to be able to install it through Homebrew if I am so inclined.

**Comment by alebcay** [comment]
Hi @nawafuyfc - could you please provide some reasoning behind this PR for deleting `carthage`?

**Comment by chenrui333** [comment]
Closing the PR as the intention is not well communicated.

**Comment by chenrui333** [comment]
honestly, I think @nawafuyfc might be a spam account.

**Comment by claui** [comment]
This PR has a [famous precedent](https://en.wikipedia.org/wiki/Carthago_delenda_est).

**Pull request closed without merging**
