### PR TITLE
keptn 0.8.7

### PR DESCRIPTION
**Pull request by orf**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
==> /opt/homebrew/Cellar/keptn/0.8.7/bin/keptn version 2>&1
Killing child processes...
Error: keptn: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /Warning:\ could\ not\ open\ KUBECONFIG\ file/ to match "Warning: could not parse KUBECONFIG file: Cannot find file /private/tmp/keptn-test-20210803-44214-1lt3ovb/.kube/config".
```

**Comment by solidnerd** [comment]
Hey @orf, 

can you add the following into the binary test section:

```ruby
 # keptn.rb
  ...
  test do
    shell_output("#{bin}/keptn set config kubeContextCheck false") 
    run_output = shell_output("#{bin}/keptn version 2>&1")
    assert_match "\nKeptn CLI version:", run_output
    ...
```

**Comment by chenrui333** [comment]
Thanks @solidnerd, give it another shot now.

**Comment by chenrui333** [comment]
#84682

**Pull request closed without merging**
