### PR TITLE
ldns: migrate to python@3.10

### PR DESCRIPTION
**Pull request by anandb-ripencc**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by anandb-ripencc** [comment]
I don't understand why the tap_syntax check has failed...

**Comment by SMillerDev** [comment]
```
   freeswitch:
    * freeswitch contains conflicting version recursive dependencies:
        python@3.9, python@3.10
```

**Comment by anandb-ripencc** [comment]
@SMillerDev ok, but that's for someone else to fix, right? I didn't touch anything other than the ldns formula.

**Comment by SMillerDev** [comment]
The freeswitch formula depends on ldns so you introduced the python 3.10 dependency in the tree.

**Comment by anandb-ripencc** [comment]
Ah, thanks for the explanation. Freeswitch appears to have a lot of dependencies, which in turn depend on python 3.9. I don't think I can fix it. So I will just close this PR for now.

**Comment by iMichka** [comment]
Yes, the more complex dependency tree changes like that are better handled by maintainers. Or if someone wants to spend a lot of time on this, we can help them working on this.

**Pull request closed without merging**
