### PR TITLE
mysql@5.6&5.7: fix C++20 complier loads VERSION

### PR DESCRIPTION
**Pull request by lungothrin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
This should be patched upstream, have you tried submitting this there?

**Comment by lungothrin** [comment]
mysql 8.x already fixed this issue, but it appears they have no plan to backport this fix to 5.6/5.7

**Comment by carlocab** [comment]
Are there patches we can backport for these versions, rather than doing `inreplace`s in the formula?

**Comment by cho-m** [comment]
The v8.0 commit was https://github.com/mysql/mysql-server/commit/51675ddb41661163c23e802a3e5eedb1344ce023, which should be simple to backport.
The `inreplace`s appear to be replicating the commit.

**Comment by nandahkrishna** [comment]
Resolved in #78850 (backported the patch). Thanks, @lungothrin.

**Pull request closed without merging**
