### PR TITLE
rust 1.14.0

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
also llvm appears to be broken, though breakage apparently is preexisting and wasn't caught on the prior release: https://gist.github.com/ilovezfs/1eb14b90948d2079bb6e5abdaeac6a5f

**Comment by ilovezfs** [comment]
CC @alexcrichton any ideas on the CI breakage https://bot.brew.sh/job/Homebrew%20Core/13572/version=sierra/console and/or the `--with-llvm` breakage https://gist.github.com/ilovezfs/1eb14b90948d2079bb6e5abdaeac6a5f ?

**Comment by yurikoles** [comment]
It doesn't build. I tried same changes myself, it fails with message CARG_CFG not found.

**Comment by alexcrichton** [comment]
@ilovezfs I think the CI breakage is relevant here:

```
configure: error: needed, but unable to find any of: CFG_CARGO cargo
```

To build Cargo you'll need a previous version of Cargo installed somewhere to build with. For example the previously packaged Cargo should work ok to build the next Cargo.

For the latter it looks like LLVM was linked against libffi and Rust didn't detect that. I think that may be a case where we don't detect that library should be linked (or a bug in llvm-config, I forget). I'd recommend not compiling against the system LLVM, however, as using the upstream version is guaranteed to have the most bugfixes.

**Comment by ilovezfs** [comment]
@alexcrichton cool. Thanks for the help. Note that the LLVM is the upstream LLVM, specifically the homebrew llvm formula (https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm.rb):
https://github.com/alex/homebrew-core/blob/c4217951cac69bdd25a1a3bb40206ce804b1cde9/Formula/rust.rb#L56

**Comment by nijikon** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Closing in favor of #8708 but thanks for the PR nonetheless.

**Pull request closed without merging**
