### PR TITLE
node-build 4.9.1

### PR DESCRIPTION
**Pull request by jasonkarns**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by tommeier** [comment]
did this get reverted? current master is now showing 4.9.0 again https://github.com/Homebrew/homebrew-core/blob/master/Formula/node-build.rb

**Comment by tommeier** [comment]
and fresh upgrades of `brew update && brew upgrade node-build` are once again maxxing out at 4.9.0 - but _were_ 4.9.1 yesterday

**Comment by SeekingMeaning** [comment]
Ah, it was reverted in d7058fbf4b257a139a7f436989db808c52237944 when licenses were being added to formulae in batch

**Comment by Bo98** [comment]
Fixed now. Sorry about that.

91357eebe4

**Pull request merged**
