### PR TITLE
mockolo 1.8.2

### PR DESCRIPTION
**Pull request by sidepelican**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sidepelican** [comment]
mockolo 1.8.2 cannot build with Xcode 14.3 because it doesn't have `lib_InternalSwiftSyntaxParser.dylib` in toolchains.
I want to use Xcode 14.2 on macOS13 but I'm not familiar with brew so I'm not sure how to do it.

**Comment by chenrui333** [comment]
There is no need to manipulate the ventural bottle checksum, we can trigger the merge for the success ones, but is there any issue tracking the support of xcode 14.3?

**Comment by sidepelican** [comment]
mockolo 1.8.2 uses [SwiftSyntax](https://github.com/apple/swift-syntax) 0.50700.1 and it depends to _InternalSwiftSyntaxParser (in swift toolchains) in compile time.

Swift toolchains and SwiftSyntax are released in heavily close sync.
Xcode14.3 has Swift5.8 and its syntax parser is dramatically changed.
The new Swift does not have _InternalSwiftSyntaxParser and also, Swift 5.8 toolchains does not contain `lib_InternalSwiftSyntaxParser.dylib`.

I am planning to release new mockolo that uses the new SwiftSyntax 508.0.0 (it no longer dependes to _InternalSwiftSyntaxParser).
but before releasing it, I have considered to release current unreleased commits on master bransh of mockolo.

So I have no idea to build SwiftSyntax 0.50700.1 on Xcode14.3.

**Comment by carlocab** [comment]
@Bo98, thoughts here?

**Comment by Bo98** [comment]
SwiftSyntax has always been strict.

SwiftSyntax 0.50700.0 can only be used with Xcode 14.0-14.2
SwiftSyntax 0.50600.0 can only be used with Xcode 13.3-13.4.1
SwiftSyntax 0.50500.0 can only be used with Xcode 13.0-13.2.1

The new system in SwiftSyntax 508.0.0 however solves this. SwiftSyntax 508.0.0 can built under older Xcode as well (not sure how far, but 14.0 seems to work fine) and won't suddenly break with newer Xcode.

**Review by carlocab — APPROVED** [review]

**Comment by sidepelican** [comment]
Thank you everyone!

**Pull request merged**
