### PR TITLE
percona-server 5.7.18-14

### PR DESCRIPTION
**Pull request by teslamint**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
One of our `inreplace` patches no longer applies:
```
Error: inreplace failed
/usr/local/Cellar/percona-server/5.7.18-14/support-files/mysql.server:
  expected replacement of /pidof/ with "pgrep"
```
Did you test this locally?

**Comment by teslamint** [comment]
My bad. Fixed.

**Comment by ilovezfs** [comment]
There's a problem with the test as it got stuck on all three CI nodes until I just canceled the builds manually.

**Review by ilovezfs — CHANGES_REQUESTED** [review]
This cannot be merged until the test doesn't hang on CI.

**Comment by dunn** [comment]
```
==> /usr/local/Cellar/percona-server/5.7.18-14/bin/mysql --verbose --port=3307 --user=root --execute=source /tmp/percona-server-test-20170609-33436-zjmats/mysql_test.sql
ERROR 1006 (HY000) at line 1 in file: '/tmp/percona-server-test-20170609-33436-zjmats/mysql_test.sql': Can't create database 'mysql_test' (errno: 178976778)
--------------
CREATE DATABASE `mysql_test`
--------------

**Comment by dunn** [comment]
Thanks so much, especially for the test!

**Pull request closed without merging**
