### PR TITLE
dotnet 5.0.100

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
```
error : Unable to load the service index for source https://dotnet.myget.org/F/nuget-build/api/v3/index.json.
error :   Response status code does not indicate success: 404 (Feed does not exist.).
```

**Comment by bayandin** [comment]
> ```
> error : Unable to load the service index for source https://dotnet.myget.org/F/nuget-build/api/v3/index.json.
> error :   Response status code does not indicate success: 404 (Feed does not exist.).
> ```

https://github.com/dotnet/source-build/issues/1971

**Comment by SeekingMeaning** [comment]
```
  tar: Error opening archive: Failed to open '/private/tmp/dotnet-20210114-8594-cs48xl/artifacts/obj/x64/Release/blob-feed/assets/dotnet-runtime-5.0.0-osx.10.14-x64.tar.gz'
/private/tmp/dotnet-20210114-8594-cs48xl/repos/runtime.proj(18,5): error MSB3073: The command "tar -xvf /private/tmp/dotnet-20210114-8594-cs48xl/artifacts/obj/x64/Release/blob-feed/assets/dotnet-runtime-5.0.0-osx.10.14-x64.tar.gz -C /private/tmp/dotnet-20210114-8594-cs48xl/.dotnet/" exited with code 1.
  'known-good' failed during build.

Build FAILED.
```

**Comment by carlocab** [comment]
One last failure:
```
==> brew test --retry --verbose gitversion
==> FAILED
==> Testing gitversion
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210114-46182-19xd7fz.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gitversion.rb --verbose --retry
==> git init
Initialized empty Git repository in /private/tmp/gitversion-test-20210114-46183-vmjk8c/.git/
==> git config user.name Test
==> git config user.email test@example.com
==> git add test.txt
==> git commit -q --message='Test'
==> /usr/local/Cellar/gitversion/5.6.3/bin/gitversion -output json
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.0 at [/usr/local/Cellar/dotnet/5.0.100/libexec/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

**Comment by SeekingMeaning** [comment]
```
==> brew audit gitversion --online --git --skip-style
==> FAILED
Error: curl failed!
curl: (7) Failed to connect to api.github.com port 443: Operation timed out
```

**Comment by SeekingMeaning** [comment]
Added `CI-force-arm` to see what would happen; all other runners succeeded, so merging

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
