### PR TITLE
awscli: replace ld workaround with lightweight alternative

### PR DESCRIPTION
**Pull request by cho-m**
~~Also add `groff` as dependency on Ventura for Homebrew/homebrew-core#105682~~ Was merged in #114038

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
Looks like Xcode 14.1 fails,
```
    ld: fatal warning(s) induced error (-fatal_warnings)
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Bo98** [comment]
I'm going to guess this is going to be the `-undefined dynamic_lookup may not work with chained fixups` warning.

I wonder if we need `-no_fixup_chains` everywhere that uses Python now, assuming the warning is alerting to us something alarming on a wider scale than just this project (`-fatal_warnings`  is not that common).

**Comment by p-linnane** [comment]
@fxcoudert Related to Ventura bottling failure.

**Comment by cho-m** [comment]
> I'm going to guess this is going to be the `-undefined dynamic_lookup may not work with chained fixups` warning.
> 
> I wonder if we need `-no_fixup_chains` everywhere that uses Python now, assuming the warning is alerting to us something alarming on a wider scale than just this project (`-fatal_warnings` itself is not that common).
> 
> [python/cpython#97524](https://github.com/python/cpython/issues/97524)

Looks like `-Wl,-no_fixup_chains` does get build to pass. We could use this workaround for now if we want to avoid `llvm` workaround that may bypass some Homebrew `ld` logic.

--- 

`groff` change was merged in #114038 so rebased and dropped here.

**Review by branchv — APPROVED** [review]

**Pull request closed without merging**
