### PR TITLE
Camel-K v1.1.0

### PR DESCRIPTION
**Pull request by ipolyzos**
Upgrade kamel formula to v1.1.0 as releases of today

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Below you can find the logs for _build from source_  and _audit_ runs.

**brew --build-from-source**
```
==> Cloning https://github.com/apache/camel-k.git
Updating /Users/ipolyzos/Library/Caches/Homebrew/kamel--git
==> Checking out tag v1.1.0
HEAD is now at 29d581a4 Release 1.1.0
HEAD is now at 29d581a4 Release 1.1.0
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

==> make
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/kamel/1.1.0: 8 files, 53.9MB, built in 1 minute 8 seconds
```

**brew test**
```
Testing kamel
==> /usr/local/Cellar/kamel/1.1.0/bin/kamel 2>&1
==> echo $(/usr/local/Cellar/kamel/1.1.0/bin/kamel help 2>&1)
==> echo $(/usr/local/Cellar/kamel/1.1.0/bin/kamel get 2>&1)
==> echo $(/usr/local/Cellar/kamel/1.1.0/bin/kamel version 2>&1)
==> echo $(/usr/local/Cellar/kamel/1.1.0/bin/kamel run 2>&1)
==> echo $(/usr/local/Cellar/kamel/1.1.0/bin/kamel run None.java 2>&1)
==> echo $(/usr/local/Cellar/kamel/1.1.0/bin/kamel reset 2>&1)
==> echo $(/usr/local/Cellar/kamel/1.1.0/bin/kamel rebuild 2>&1)
==> echo $(/usr/local/Cellar/kamel/1.1.0/bin/kamel reset 2>&1)
```

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
Is this the latest stable release? https://github.com/apache/camel-k/releases says 1.0.1 is latest

**Comment by ipolyzos** [comment]
> Is this the latest stable release? https://github.com/apache/camel-k/releases says 1.0.1 is latest

the v1.1.0 is the to be relased and currently under vote please see [camel-k/branches](https://github.com/apache/camel-k/branches) for more.

**Comment by SeekingMeaning** [comment]
> Camel K 1.1.0 is now released.

**Comment by SeekingMeaning** [comment]
Thanks again for your contribution to Homebrew/core, @ipolyzos! 🌟

**Pull request closed without merging**
