### PR TITLE
python and python3: add --with-sphinx-doc option for building HTML docs

### PR DESCRIPTION
**Pull request by zmwangx**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Having offline HTML docs is good for air travel, crappy hotel Wi-Fi or other situations where docs.python.org is not accessible or very slow.

### CODE REVIEW

**Comment by DomT4** [comment]
It's a small concern that using `sphinx-doc` for `python` introduces a circular dependency on OS X 10.6 because `sphinx-doc` needs Python 2.7 & the most common way to satisfy that Python 2.7 requirement will be our `python`.

That said, frankly I'm not sure we've got any 10.6 users left at this point. Any thoughts on this PR in general @tdsmith?

**Comment by zmwangx** [comment]
Right, I wasn't thinking about 10.6... Maybe something like

```ruby
if MacOS.version > :snow_leopard
  option "with-sphinx-doc", "Build HTML documentation"
  depends_on "sphinx-doc" => [:build, :optional]
end
```

for `python.rb`? It looks horrible though and I've never seen anything like this in core.

**Comment by DomT4** [comment]
Personally I'd just like to completely stop supporting 10.6 for `homebrew/core`, but that's my opinion. Let's see what Tim has to say.

**Comment by zmwangx** [comment]
This proposed changed is optional rather than recommended (because the uncompressed docsets are pretty huge — 34M for Python 2.7.12 and 41M for Python 3.5.2), so I'd assume it doesn't have to await a heavy-handed decision like dropping support for 10.6 completely even if the option doesn't work on 10.6, right?

Of course there might be other concerns.

**Comment by tdsmith** [comment]
lgtm

**Comment by DomT4** [comment]
> Of course there might be other concerns.

Yeah, this isn't the primary driver of my problems with 10.6. It's more driven by us being basically unable to fix most problems that come up without significant user help, which isn't always forthcoming, and there's an unreasonable number of blobs in formulae for 10.6/10.7 to support what is less than 0.2% of Homebrew's entire userbase.

Still, not strictly relevant to this PR itself.

**Comment by zmwangx** [comment]
I meant to say there might be other concerns about this PR itself... But points taken 😺. I'm not bothered at all by dropping support for 10.6 simply because I'm not in that demographic...

**Comment by MikeMcQuaid** [comment]
Lets try and support 10.6 if we can and it's no extra grief.

**Comment by zmwangx** [comment]
So any thoughts on

```ruby
if MacOS.version > :snow_leopard
  option "with-sphinx-doc", "Build HTML documentation"
  depends_on "sphinx-doc" => [:build, :optional]
end
```

proposed above?

**Comment by MikeMcQuaid** [comment]
Looks good 👍

**Comment by DomT4** [comment]
You'll need to tweak the `if build.with? "sphinx-doc"` install blob in `python` as well. Something like:
```ruby
if MacOS.version > :snow_leopard && build.with?("sphinx-doc")
```
Seems fine.

**Comment by zmwangx** [comment]
I made the change (with a comment on why), but I'm not sure where to place the block.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/259d62b76f1eda2e63d7c88651689e3629da93df & https://github.com/Homebrew/homebrew-core/commit/1e8c627cc584add11e0266253b2429bfb5419bcc. Thanks @zmwangx!

**Pull request closed without merging**
