### PR TITLE
Bulk import from homebrew/versions (1/7)

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Import formulae from homebrew/versions. Those that fail to build will likely be killed.

### CODE REVIEW

**Comment by neutric** [comment]
Did some easy fixes before leaving, hope you don't mind.

**Comment by MikeMcQuaid** [comment]
@neutric Saving me work? How dare you? 😉 :trollface:

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@MikeMcQuaid `drush` itself was moved to homebrew/php in Homebrew/legacy-homebrew#31726 so not sure `drush@5` belongs in core.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Moved to https://github.com/Homebrew/homebrew-php/pull/4036

**Comment by ilovezfs** [comment]
poifect.

**Comment by MikeMcQuaid** [comment]
Thanks for the help here @neutric, @ilovezfs!

**Pull request closed without merging**
