### PR TITLE
openh264: chmod dylib only on mac

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
The `.so` file does not need this?

**Comment by iMichka** [comment]
No one complained until now. The question should rather probably be: why does upstream does not handle this and why is this needed on Mac?

**Comment by SMillerDev** [comment]
Does anything complain if you just drop the line completely?

**Comment by iMichka** [comment]
Let's try it. It was added because a brew complained about this in 2014: https://github.com/Homebrew/legacy-homebrew/pull/34703

**Comment by iMichka** [comment]
Looks like it was not needed at all.

**Review by SMillerDev — APPROVED** [review]
Thanks @iMichka  ! Without your contributions it'd be impossible to keep homebrew going. You can feel good knowing that you've made the world a lot better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
