### PR TITLE
ttfautohint 1.8.1

### PR DESCRIPTION
**Pull request by lemzwerg**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by lemzwerg** [comment]
I don't understand the failure message:
```
failed: brew linkage --test pdf2htmlex
```
Please advise.

**Comment by lemzwerg** [comment]
Looking again at the issue, this can only be a bug in homebrew itself (or its setup on Jenkins), since ttfautohint has no connection to pdf2htmlex whatsoever.

**Comment by ilovezfs** [comment]
>since ttfautohint has no connection to pdf2htmlex whatsoever.

That is not the case:
```
$ grep ttf $(brew formula pdf2htmlex)
  depends_on "ttfautohint"
$ brew uses ttfautohint | grep pdf
pdf2htmlex
```

> this can only be a bug in homebrew

Yes, I broke it in #12226.

**Comment by lemzwerg** [comment]
Hehe, yes :-)  However, this can't be deduced from anything jenkins is emitting...

I've opened issue https://github.com/Homebrew/homebrew-core/issues/22331

**Comment by ilovezfs** [comment]
>However, this can't be deduced from anything jenkins is emitting

Then how did I deduce it?

**Comment by lemzwerg** [comment]
Well, I don't use homebrew at all!  I'm just innocently updating a formula as a courtesy to users, so it didn't hit me immediately that there are tests for reverse dependencies also...

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks @lemzwerg! Shipped.

**Pull request closed without merging**
