### PR TITLE
gcc: enable jit support

### PR DESCRIPTION
**Pull request by d12frosted**
Hello,

It would be super nice to have `gcc` compiled with `jit` support. I am not sure about implications for other users, but from what I've read around, should be safe. Would be glad for any feedback.

-----

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

```
λ brew audit --strict Formula/gcc.rb
gcc:
  * Formula has other versions so create an alias named gcc@10.2.
Error: 1 problem in 1 formula detected
```

Not sure what to do about it. And doesn't seem to be related to my changes.

-----

### CODE REVIEW

**Comment by d12frosted** [comment]
Oh my, I did the change, but my I/C told me that I can't push. Sorry.

**Comment by d12frosted** [comment]
Both 10.13 and 10.14 failures are related to other packages. `gcc` was built successfully. Should I re-trigger CI?

**Comment by d12frosted** [comment]
Rebased on to of the latest master.

**Comment by d12frosted** [comment]
I see that at some point of time there was an option to enable `jit` support, but it [was removed][1] for being not popular. At the same time I see a comment saying that it actually has a performance cost (not sure if it's about formula installation time or gcc itself). Would love to hear what others think.

  [1]: https://github.com/Homebrew/homebrew-core/pull/34865/files#

**Comment by seagle0128** [comment]
> I see that at some point of time there was an option to enable `jit` support, but it [was removed](https://github.com/Homebrew/homebrew-core/pull/34865/files#) for being not popular. At the same time I see a comment saying that it actually has a performance cost (not sure if it's about formula installation time or gcc itself). Would love to hear what others think.

Not all options are popular. `jit` option is critical for emacs-native-comp, and many people need it. We just need to leave the option there while not removing it.

**Comment by SMillerDev** [comment]
It was removed almost 2 years ago, when we removed options in formulae.

**Comment by seagle0128** [comment]
> It was removed almost 2 years ago, when we removed options in formulae.

That's why many guys had to download and compile gcc themselves 😢 @d12frosted raised this issue finally.
What's the impact of keeping jit option?

**Comment by kaz-yos** [comment]
I just went through the jit hack for Emacs 28 native-comp branch. It would be nice to have it without tinkering with the formula file!

**Comment by seanfarley** [comment]
Yeah, I've been playing with the jit library as well for another project and this would indeed be nice!

**Comment by parsoj** [comment]
I second (or fifth?) this! - gcc-compiled emacs is going to bring in alot of new people looking to be able to use jit functionality in gcc. 
If it wasn't a popular feature before, it sure is now :)

**Comment by jonchang** [comment]
I believe setting `--enable-host-shared`, which is required for the jit option, slows down the compiler, which is why it wasn't a default when we had options and isn't a default now. How do other package managers address this situation? Does e.g. Debian build GCC with `--enable-host-shared` for all its GCC source packages?

**Comment by seagle0128** [comment]
> I believe setting `--enable-host-shared`, which is required for the jit option, slows down the compiler, which is why it wasn't a default when we had options and isn't a default now. How do other package managers address this situation? Does e.g. Debian build GCC with `--enable-host-shared` for all its GCC source packages?

I don't think the request is make the option `--enable-host-shared` as default, while just add the option.

**Comment by SMillerDev** [comment]
> I don't think the request is make the option --enable-host-shared as default, while just add the option.

That is the pull request content though. And we're not bringing options back to homebrew-core. They keep breaking builds which takes way too much time from maintainers.

**Comment by seanfarley** [comment]
In practice, this slow down is almost never noticed. But the solution, from the gcc devs themselves, is to build it with both:

> The configure-time option --enable-host-shared is needed when building the jit in order to get position-independent code. This will slow down the regular compiler by a few percent. Hence when packaging gcc with libgccjit, please configure and build twice:
>
> once without --enable-host-shared for most languages, and
> once with --enable-host-shared for the jit

https://gcc.gnu.org/onlinedocs/gcc-10.2.0/jit/internals/index.html

It seems updating the formula to do that would satisfy both the slow down concerns while also including libgccjit.

**Comment by jonchang** [comment]
> > once without --enable-host-shared for most languages, and
> > once with --enable-host-shared for the jit
> 
> https://gcc.gnu.org/onlinedocs/gcc-10.2.0/jit/internals/index.html
> 
> It seems updating the formula to do that would satisfy both the slow down concerns while also including libgccjit.

Ok, this pull request should be updated to follow that recommendation. Let's see how it looks once it runs through CI.

**Comment by d12frosted** [comment]
I will update it. Thanks everyone for comments and suggestions. I will need a second wave soon 😸

**Comment by d12frosted** [comment]
I've updated the formula, but now it doesn't build. Unfortunately, it takes an hour to get to the failure. The second configure + make fails. Seems like I need to pass less arguments to the second run 🤔 

```
==> ../configure --build=x86_64-apple-darwin19 --prefix=/usr/local/Cellar/gcc/10.2.0_1 --libdir=/usr/local/Cellar/gcc/10.2.0_1/lib/gcc/10 --disable-nls --enable-checking=release --enable-languages=jit --program-suffix=-10 --with-gmp=/usr/local/opt/gmp -
==> make BOOT_LDFLAGS=-Wl,-headerpad_max_install_names
Last 15 lines from /Users/d12frosted/Library/Logs/Homebrew/gcc/04.make:
TARGET_CPU_DEFAULT="" \
	HEADERS="config/i386/i386-protos.h config/darwin-protos.h tm-preds.h" DEFINES="" \
	/bin/sh ../../gcc/mkconfig.sh tm_p.h
TARGET_CPU_DEFAULT="" \
	HEADERS="auto-host.h ansidecl.h" DEFINES="" \
	/bin/sh ../../gcc/mkconfig.sh bconfig.h
make[3]: *** No rule to make target `../build-x86_64-apple-darwin19/libiberty/pic/libiberty.a', needed by `build/genmodes'.  Stop.
make[3]: *** Waiting for unfinished jobs....
config.h is unchanged
tm_p.h is unchanged
bconfig.h is unchanged
tm.h is unchanged
make[2]: *** [all-stage1-gcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	27: from /usr/local/Homebrew/Library/Homebrew/build.rb:229:in `<main>'
	26: from /usr/local/Homebrew/Library/Homebrew/build.rb:140:in `install'
	25: from /usr/local/Homebrew/Library/Homebrew/utils.rb:492:in `with_env'
	24: from /usr/local/Homebrew/Library/Homebrew/build.rb:145:in `block in install'
	23: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1192:in `brew'
	22: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2161:in `stage'
	21: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	20: from /usr/local/Homebrew/Library/Homebrew/resource.rb:86:in `stage'
	19: from /usr/local/Homebrew/Library/Homebrew/resource.rb:111:in `unpack'
	18: from /usr/local/Homebrew/Library/Homebrew/resource.rb:201:in `mktemp'
	17: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
	16: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
	15: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
	14: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `block in unpack'
	13: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2181:in `block in stage'
	12: from /usr/local/Homebrew/Library/Homebrew/utils.rb:492:in `with_env'
	11: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2182:in `block (2 levels) in stage'
	10: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1199:in `block in brew'
	9: from /usr/local/Homebrew/Library/Homebrew/build.rb:177:in `block (2 levels) in install'
	8: from /Users/d12frosted/Developer/homebrew-core/Formula/gcc.rb:107:in `install'
	7: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2095:in `mkdir'
	6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
	4: from /Users/d12frosted/Developer/homebrew-core/Formula/gcc.rb:114:in `block in install'
	3: from /Users/d12frosted/Developer/homebrew-core/Formula/gcc.rb:90:in `make'
	2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1975:in `system'
	1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1975:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2037:in `block in system': Failed executing: make BOOT_LDFLAGS=-Wl,-headerpad_max_install_names (BuildError)
	5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:142:in `<main>'
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:154:in `rescue in <main>'
	3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:439:in `dump'
	2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:385:in `issues'
	1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:389:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:313:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)
```

**Comment by jonchang** [comment]
It looks like you're re-using the build directory which I assume would cause problems. The official packaging recommendation uses [two separate build directories](https://gcc.gnu.org/onlinedocs/gcc-10.2.0/jit/internals/index.html#packaging-notes). The formula definition should probably do the same.

Instead of creating a new function in the formula class, I suggest you set up the common arguments , then in a `mkdir "build-jit" do` and `mkdir "build-standard" do` blocks run `configure` and `make` like in the documentation. The diff should be fairly minimal.

**Comment by d12frosted** [comment]
You are right. I have fixed that and now it builds. Though instead of 100 minutes it now takes 197 minutes to build! Maybe I did something wrong?

**Comment by gromgit** [comment]
> Though instead of 100 minutes it now takes 197 minutes to build! Maybe I did something wrong?

That's to be expected, since using the same build dir for both builds would make the second round reuse most of the object files from the first, thus greatly speeding it up at the cost of correctness. (I assume you didn't do a `make clean` in between?)

**Comment by d12frosted** [comment]
No, there is no `make clean`, but as suggested by @jonchang, I am using separate build dirs, otherwise it [doesn't work][1]. 

  [1]: https://github.com/Homebrew/homebrew-core/pull/59134#issuecomment-682608322

**Comment by jonchang** [comment]
CC @fxcoudert @Bo98 for thoughts on adding another ~90-100 minutes on gcc build time for libgccjit? The difference in bottle size seems negligible, but the extra build time might be an issue.

I'll probably take the patch in https://github.com/Homebrew/homebrew-core/pull/60338 instead of this one since we try to avoid defining extra functions if possible, given the temptations outlined in https://discourse.brew.sh/t/calling-one-formulas-methods-in-another/8382.

If someone could reproduce and fix the snakemake test that would be great (in a separate pull request).

**Comment by SMillerDev** [comment]
GCC isn't used much in macOS building so I'm not too worried about it. But maybe we should ask @Homebrew/linux as well

**Comment by fxcoudert** [comment]
I don't have an objection in theory, if it builds without patching (it used to require patching for macOS). But I'm not too much in favour either, given that we have to build twice, bringing a 4-hour build to CI and to users who can't use bottles.

**Comment by iMichka** [comment]
Not too many concerns from @Homebrew/linux, but could we maybe introduce a new gcc-jit formula instead? The increased build times are not that appealing.

**Comment by seagle0128** [comment]
> Not too many concerns from @Homebrew/linux, but could we maybe introduce a new gcc-jit formula instead? The increased build times are not that appealing.

I vote it. A new gcc-git formula is a good idea.

**Comment by seanfarley** [comment]
> > Not too many concerns from @Homebrew/linux, but could we maybe introduce a new gcc-jit formula instead? The increased build times are not that appealing.
> 
> I vote it. A new gcc-git formula is a good idea.

For what it's worth, this is how debian packages gcc-jit as well (as a separate pacakge).

**Comment by d12frosted** [comment]
Ok, will prepare a separate package then.

**Comment by SMillerDev** [comment]
Already done in https://github.com/Homebrew/homebrew-core/pull/60338

**Comment by jonchang** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/99e5d3335b2477a02d32645e797d638b5a7d0d34

**Pull request closed without merging**
