### PR TITLE
swift 4.2

### PR DESCRIPTION
**Pull request by fxcoudert**
Swift 4.2 was released, but the tarballs for other sources (swift-clang, etc.) have not been pushed yet.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Fails to build on Mojave with:

```
/tmp/swift-20180919-16866-gccsnl/swift/stdlib/public/runtime/ObjCRuntimeGetImageNameFromClass.cpp:259:25: error: no matching constructor for initialization of '(anonymous namespace)::patch_t'
  patchLazyPointers(mh, patch_t("_class_getImageName",
                        ^       ~~~~~~~~~~~~~~~~~~~~~~
/tmp/swift-20180919-16866-gccsnl/swift/stdlib/public/runtime/ObjCRuntimeGetImageNameFromClass.cpp:108:5: note: candidate template ignored: could not match 'const T *' against 'const char *(*)(Class _Nullable)' (aka 'const char *(*)(objc_class * _Nullable)')
    patch_t(const char *newName, const T *newFn)
    ^
/tmp/swift-20180919-16866-gccsnl/swift/stdlib/public/runtime/ObjCRuntimeGetImageNameFromClass.cpp:103:10: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
  struct patch_t {
         ^
/tmp/swift-20180919-16866-gccsnl/swift/stdlib/public/runtime/ObjCRuntimeGetImageNameFromClass.cpp:103:10: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
1 error generated.
```

**Comment by fxcoudert** [comment]
One more bug… this is endless:

```
15:24:46 In file included from /tmp/swift-20180919-53325-1wrv3rt/swift/stdlib/public/stubs/SwiftNativeNSXXXBaseARC.m:12:
15:24:46 In file included from /tmp/swift-20180919-53325-1wrv3rt/swift/include/swift/Runtime/Config.h:21:
15:24:46 /tmp/swift-20180919-53325-1wrv3rt/llvm/include/llvm/Support/Compiler.h:20:10: fatal error: 'new' file not found
15:24:46 #include <new>
15:24:46          ^~~~~
15:24:46 1 error generated.
```

**Comment by fxcoudert** [comment]
Lack of release tarballs reported at https://bugs.swift.org/browse/SR-8859

**Comment by fxcoudert** [comment]
Compilation bug reported at https://bugs.swift.org/browse/SR-8860

**Comment by fxcoudert** [comment]
```
CMake Error at stdlib/public/core/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/tmp/swift-20181101-47303-hu8kms/build/swift-macosx-x86_64/./lib/swift/iphoneos/armv7/Swift.swiftmodule".
Call Stack (most recent call first):
  stdlib/public/cmake_install.cmake:40 (include)
  stdlib/cmake_install.cmake:37 (include)
  cmake_install.cmake:41 (include)
```

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Thanks @fxcoudert! 👍

**Pull request closed without merging**
