### PR TITLE
vapoursynth, vapoursynth-imwri, vapoursynth-ocr, vapoursynth-sub 52

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Removed explicit `macos` version dependency in `vapoursynth` because we check for it anyways in `zimg`, which is where the actual `macos` version dependency is. Updated licenses based on the following license headers:
- For `vapoursynth`, in most of the `src/core` tree:
```
/*
* Copyright (c) 2012-2016 Fredrik Mellbin
*
* This file is part of VapourSynth.
*
* VapourSynth is free software; you can redistribute it and/or
* modify it under the terms of the GNU Lesser General Public
* License as published by the Free Software Foundation; either
* version 2.1 of the License, or (at your option) any later version.
*
* VapourSynth is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* Lesser General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with VapourSynth; if not, write to the Free Software
* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
*/
```

- For `vapoursynth-imwri`, in `src/filters/imwri`, the same above header is present
- For `vapoursynth-ocr`, in `src/filters/ocr`, the following header is present:
```
/*
 * Tesseract-based OCR filter
 *
 * Copyright (c) 2014, Martin Herkt <lachs0r@srsfckn.biz>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
 * REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
 * INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
 * LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
 * OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THIS SOFTWARE.
 */
```
- For `vapoursynth-sub`, in `src/filters/subtext`, there are multiple files but only one file (`text.c`) contains a license header. The license header that is present is:
```
/*
 * AssVapour
 *
 * Copyright (c) 2012, Martin Herkt <lachs0r@srsfckn.biz>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
 * REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
 * INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
 * LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
 * OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THIS SOFTWARE.
 */
```

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
==> brew audit vapoursynth-ocr --online --git --skip-style
==> FAILED
Error: 1 problem in 1 formula detected
vapoursynth-ocr:
  * Formula license ["ISC"] does not match GitHub license ["LGPL-2.1"].

==> brew audit vapoursynth-sub --online --git --skip-style
==> FAILED
Error: 1 problem in 1 formula detected
vapoursynth-sub:
  * Formula license ["ISC"] does not match GitHub license ["LGPL-2.1"].
```

**Comment by chenrui333** [comment]
Looks like that is intentional, cc @Homebrew/core

**Comment by fxcoudert** [comment]
Please hold this a couple of hours for the completion of testing of https://github.com/Homebrew/homebrew-core/pull/62560

**Comment by fxcoudert** [comment]
More progress to be done on #62560, feel free to merge this in the meantime.

**Comment by fxcoudert** [comment]
Putting on hold again, resuming testing of #62560 (fingers crossed!)

**Comment by fxcoudert** [comment]
Rebased after the python 3.9 migration was merged.

**Comment by fxcoudert** [comment]
```
vapoursynth-sub:
  * Formula license ["ISC"] does not match GitHub license ["LGPL-2.1"].
```

This is by design, since the part of the repository we're using is not the same as the main licence. poke @MikeMcQuaid for guidance on how this is supposed to be handled

**Comment by MikeMcQuaid** [comment]
@Rylan12 may be a better ask than me.

**Comment by Rylan12** [comment]
We can add these to the [`PERMITTED_FORMULA_LICENSE_MISMATCHES`](https://github.com/Homebrew/brew/blob/c8fcd050c7b85e2b48f7b1b2c5465980b8705679/Library/Homebrew/dev-cmd/audit.rb#L376-L379) allowlist. It looks like that list takes both a formula name and version. I'm not sure what the rationale for that is. I would think that if the license doesn't match for one version it would be expected to not match for later versions as well.

**Comment by Rylan12** [comment]
I'm currently working on a fix for the license audit but it shouldn't hold this back if needed for Big Sur bottles. You'll just need to ignore the audit failure.

**Pull request closed without merging**
