### PR TITLE
apache-arrow apache-arrow-glib 18.0.0

### PR DESCRIPTION
**Pull request by kou**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by kou** [comment]
Sorry for forgetting update the PR title...

Hmm. It seems that we need to pyarrow version in dvc. Let's try it.

**Comment by carlocab** [comment]
I wonder if it makes more sense to build `pyarrow` with `apache-arrow` so that we won't need to rev bump `dvc` on version updates (well, probably not).

**Comment by kou** [comment]
Or we may be able to create `Formula/p/pyarrow.rb` and `dvc` depends on it.

**Comment by carlocab** [comment]
I suppose the `pyarrow` sources are distributed separately from the `apache-arrow` tarball?

**Comment by kou** [comment]
Right.
But the `apache-arrow` tarball includes the `pyarrow` sources.

**Review by chenrui333 — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
Thanks!

**Comment by kou** [comment]
> If that's the case it seems simpler to build `pyarrow` along with `apache-arrow`. Is there any reason why we're not already doing that?

It means that https://github.com/Homebrew/homebrew-core/blob/master/Formula/a/apache-arrow.rb installs PyArrow too, right?

If we use the approach, `apache-arrow` may have needless dependencies for Apache Arrow C++ users (dependencies only for PyArrow). Is it acceptable?

FYI: We have a separated formula for Apache Arrow GLib, https://github.com/Homebrew/homebrew-core/blob/master/Formula/a/apache-arrow-glib.rb , because Apache Arrow GLib has additional GLib dependency. (apache-arrow-${version}.tar.gz also includes Apache Arrow GLib sources.)

**Pull request merged**
