### PR TITLE
abyss 2.2.4

### PR DESCRIPTION
**Pull request by jwong-1**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@jowong4 Thanks for the PR, it would be good that if you can update the commit message to the format as `abyss 2.2.4` and force update this PR. thanks!

**Comment by chenrui333** [comment]
In case you don't know, there is convenient brew command to do the version upgrade `brew bump-formula-pr`: 

```
brew bump-formula-pr abyss \
--url=https://github.com/bcgsc/abyss/releases/download/2.2.4/abyss-2.2.4.tar.gz \
--sha256=f064a8c5ad152a37963d9001df6c89d744370f7ec5a387307747c4647360a47c
```

Cheers!

**Comment by jowong4** [comment]
@chenrui333 Updated the commit message.

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
Thanks @jowong4!

**Comment by jonchang** [comment]
Audit failed with a 404 url. Try updating it to https://www.bcgsc.ca/resources/software/abyss

**Pull request closed without merging**
