### PR TITLE
Rename interactive-rebase-tool to git-interactive-rebase-tool

### PR DESCRIPTION
**Pull request by glensc**
1. I find it illogical to find it under the name `interactive-rebase-tool`
2. upstream name is git-interactive-rebase-tool: https://github.com/MitMaro/git-interactive-rebase-tool
3. pretty much everyone uses git-interactive-rebase-tool: https://github.com/MitMaro/git-interactive-rebase-tool/blob/1.2.1/readme/install.md

Originally added in https://github.com/Homebrew/homebrew-core/pull/34926, but can't find any discussion regarding name there.

### CODE REVIEW

**Comment by bayandin** [comment]
Formula class should be renamed as well:

```ruby
class InteractiveRebaseTool < Formula
```

**Comment by bayandin** [comment]
And commit message should be like `git-interactive-rebase-tool: renamed from interactive-rebase-tool`

**Comment by glensc** [comment]
@bayandin thanx! fixed already.

**Comment by Bo98** [comment]
I'd probably use `formula_renames.json` instead of aliases.

**Comment by glensc** [comment]
@Bo98 I have no idea what's the difference or their purpose :)

but as it should keep working under the old name for some time to have seamless migration path.

**Comment by bayandin** [comment]
> but as it should keep working under the old name for some time to have seamless migration path.

And `formula_renames.json` will do exactly what you ask (you could try it locally first)

**Comment by glensc** [comment]
@bayandin is there a reason why I should not use the aliases?

**Comment by SMillerDev** [comment]
Alias is meant as something like java/openjdk where people might know it under both names. This is a rename since it shouldn't be using the current name.

**Comment by glensc** [comment]
but using formula renames, I can install with both names?

I think there should be some transition period while removing the old name to install with.

doesn't seem that with formula renames can use old name:

```
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula (git-interactive-rebase-tool)↑★] ➔ brew info git-interactive-rebase-tool
git-interactive-rebase-tool: stable 1.2.1 (bottled)
Native sequence editor for Git interactive rebase
https://gitrebasetool.mitmaro.ca/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-interactive-rebase-tool.rb
==> Dependencies
Build: rust ✘

[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula (git-interactive-rebase-tool)↑★] ➔ brew info interactive-rebase-tool
Error: No available formula with the name "homebrew/core/git-interactive-rebase-tool.rb"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula (git-interactive-rebase-tool)↑★] ➔

➔ brew install interactive-rebase-tool
Error: No available formula with the name "homebrew/core/git-interactive-rebase-tool.rb"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
```

**Comment by glensc** [comment]
also, the CI fails thinking this is new formula, do i remove the bottle block then?

```
==> FAILED
Error: 1 problem in 1 formula detected
git-interactive-rebase-tool:
  * New formulae in homebrew/core should not have a `bottle do` block
```

- https://github.com/Homebrew/homebrew-core/actions/runs/105376049
- https://github.com/Homebrew/homebrew-core/runs/677064048?check_suite_focus=true

**Comment by SMillerDev** [comment]
> but using formula renames, I can install with both names?

Yes, renames is a signinfier that something is now renamed while alias is a signifier that there's other names someone might know a formula under indefinitely..

**Comment by glensc** [comment]
I'm confused if with formula renames can use both names (old and new), why my tests to use old name have failed?
-  https://github.com/Homebrew/homebrew-core/pull/53532#issuecomment-629043153

**Comment by bayandin** [comment]
> why my tests to use old name have failed?

It's hard to say really since PR still has uses an alias instead of rename. 
For me `formula_renames.json` works perfectly:

```
$ brew info git-interactive-rebase-tool
git-interactive-rebase-tool: stable 1.2.1 (bottled)
Native sequence editor for Git interactive rebase
https://gitrebasetool.mitmaro.ca/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-interactive-rebase-tool.rb
==> Dependencies
Build: rust ✔

$ brew info interactive-rebase-tool
git-interactive-rebase-tool: stable 1.2.1 (bottled)
Native sequence editor for Git interactive rebase
https://gitrebasetool.mitmaro.ca/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-interactive-rebase-tool.rb
==> Dependencies
Build: rust ✔

$ brew install interactive-rebase-tool
==> Downloading https://homebrew.bintray.com/bottles/git-interactive-rebase-tool-1.2.1.catalina.bottle.tar.gz
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "git-interactive-rebase-tool"
Download failed: https://homebrew.bintray.com/bottles/git-interactive-rebase-tool-1.2.1.catalina.bottle.tar.gz
```

**Comment by glensc** [comment]
@bayandin I didn't push the commit, because it did not work form

```
➔ g show
commit 3a9f3a7044955cacbf5de28c76a66d9116eda267 (HEAD -> git-interactive-rebase-tool)
Author: Elan Ruusamäe <glen@pld-linux.org>
Date:   Fri May 15 08:53:26 2020 +0300

    git-interactive-rebase-tool: use formula_renames

diff --git a/Aliases/interactive-rebase-tool b/Aliases/interactive-rebase-tool
deleted file mode 120000
index ebacfdaf361..00000000000
--- a/Aliases/interactive-rebase-tool
+++ /dev/null
@@ -1 +0,0 @@
-../Formula/git-interactive-rebase-tool.rb
\ No newline at end of file
diff --git a/formula_renames.json b/formula_renames.json
index 4a8bf583836..b89d9b8d827 100644
--- a/formula_renames.json
+++ b/formula_renames.json
@@ -57,6 +57,7 @@
   "httpd24": "httpd",
   "i386-elf-binutils": "x86_64-elf-binutils",
   "i386-elf-gcc": "x86_64-elf-gcc",
+  "interactive-rebase-tool": "git-interactive-rebase-tool.rb",
   "juju2": "juju",
   "juju@2.0": "juju",
   "jupyter": "jupyterlab",
```

**Comment by glensc** [comment]
oh, I notice my mistake. removed `.rb` extension

**Comment by glensc** [comment]
still no reply on my question:
- https://github.com/Homebrew/homebrew-core/pull/53532#issuecomment-629076964

so I'll drop the bottle block then!

**Comment by bayandin** [comment]
> so I'll drop the bottle block then!

Yep, that's good, thanks @glensc!

**Pull request closed without merging**
