### PR TITLE
xz: drop universal

### PR DESCRIPTION
**Pull request by fxcoudert**

### CODE REVIEW

**Comment by greensky01** [comment]
@fxcoudert any reason to drop universal support?

I need build rubygems  nokogiri on Mac, and it requires universal xz.

**Comment by chdiza** [comment]
> I need build rubygems nokogiri on Mac, and it requires universal xz.

I don't think this is true.  I have built nokogiri repeatedly for over year and I don't have a universal `xz`.

**Comment by MikeMcQuaid** [comment]
@greensky01 macOS has been 64-bit only since 10.6 so universal usage in Homebrew is deprecated.

**Comment by JeanMertz** [comment]
FYI: [the docs of Nokogiri](http://www.nokogiri.org/tutorials/installing_nokogiri.html#mac_os_x) mention using `--universal`. I realise this is theirs to fix, but, I did have to do `brew unlink xz`, install Nokogiri, and link xz afterwards, for Nokogiri to work with the Homebrew installed xz.

This is 10.13 public beta, so that might be the reason, just thought I would share this tidbit of information here, for whomever this is useful.

**Pull request merged**
