### PR TITLE
meson: add patch to produce properly versioned dylibs and gobject-introspection data

### PR DESCRIPTION
**Pull request by tschoonj**
Long story as to why can be read at: https://github.com/mesonbuild/meson/pull/2577
Note: this patch will not be merged in anytime soon as it breaks meson's testsuite, and I am waiting for help to fix this...

When this one is merged in, I will start updating formulas that switched to meson, as well as add some new ones...

### CODE REVIEW

**Comment by tschoonj** [comment]
@ilovezfs Assuming you don't mind the `libepoxy` warning, this is ready to merge.

**Comment by tschoonj** [comment]
I am thinking that perhaps meson should become keg-only now, as it becomes hard to use it with this patch for development purposes. Perhaps adding a caveat, asking people to install it with pip3, if necessary? Something like is done in the Cython formula.

**Comment by tschoonj** [comment]
Assuming you are developing some software project with meson, you wouldn't be able to run the compiled executables anymore before installing them (actually the shared libraries in the project must be installed). Also, `ninja test` will fail for the same reason.

**Comment by ilovezfs** [comment]
And what happens if we don't patch meson?

**Comment by tschoonj** [comment]
Then we cannot build any of the GNOME projects containing that use meson 😄

**Comment by ilovezfs** [comment]
Does it not work to do two stage installs, first building without the bindings, installing, and then building with the bindings, and installing?

**Comment by tschoonj** [comment]
You would still need the patch. As I explain in https://github.com/mesonbuild/meson/pull/2577, meson is putting the wrong path to the dylib into the typelib files.

Also the patch adds versioning information to the dylibs, which is currently not done...

**Comment by ilovezfs** [comment]
How do you feel about using a separate `meson-internal` keg-only formula?

**Comment by tschoonj** [comment]
sure, I could live with that. Is there a precedent for that?

**Comment by ilovezfs** [comment]
Not that I know of, though the ghc @ formulae that are "for our own purposes" aren't conceptually much different from that.

**Comment by tschoonj** [comment]
Ok, will look into that. Thanks for the suggestion

**Comment by tschoonj** [comment]
@ilovezfs If you can live with the audit warnings, than this one is ready to merge...

**Comment by ilovezfs** [comment]
What's the status of the `gom` patch?

**Comment by tschoonj** [comment]
I removed all bits that assumed `pygobject3` is present.

They were redundant anyway as we `reinplace` the install location of the override files.

**Comment by ilovezfs** [comment]
🍪

**Comment by tschoonj** [comment]
Obliged! Feel free to reopen #25428. There shouldn't be any rev bumps necessary now.

**Pull request closed without merging**
