### PR TITLE
qt@5: revision bump for re2

### PR DESCRIPTION
**Pull request by iMichka**
See #117089

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
some runner issue
image

**Review by SMillerDev — DISMISSED** [review]

**Comment by iMichka** [comment]
> Error: docker://ghcr.io/homebrew/core/qt/5:5.15.7_1 already exists!

That's odd. It was created 8 days ago. Not sure where / how this happened.

**Comment by fxcoudert** [comment]
In the old Jenkins times, we had ways to unpublish bottles that had been published by mistake. Not sure what is the standard way of dealing with this now… skip a revision number?

**Comment by chenrui333** [comment]
Also for the test-bot, it might also be good to check if the bottle has been published or not.

**Comment by cho-m** [comment]
> > Error: docker://ghcr.io/homebrew/core/qt/5:5.15.7_1 already exists!
> 
> That's odd. It was created 8 days ago. Not sure where / how this happened.

Probably `icu4c` failed upload attempt

**Comment by cho-m** [comment]
As long as we are okay with it, we can delete previous upload:
Screenshot 2022-12-29 at 11 05 38 AM

**Comment by SMillerDev** [comment]
> As long as we are okay with it, we can delete previous upload:

I think that's best.

**Comment by iMichka** [comment]
Done. I deleted the previous upload.

**Comment by chenrui333** [comment]
🎉

**Pull request closed without merging**
