### PR TITLE
glib: install both static and shared libs

### PR DESCRIPTION
**Pull request by realnc**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
What's the use-case for this? It's an LGPL library so installing static libraries seems generally like a bad idea as it'll be very easy to accidentally violate the license.

**Comment by realnc** [comment]
> What's the use-case for this? It's an LGPL library so installing static libraries seems generally like a bad idea as it'll be very easy to accidentally violate the license.

The use case is to link against it statically when it's impossible not to. For example when creating a plugin (a single dylib file) that is supposed to be loaded in a third-party host application.

Also, it's very difficult to do static linking by mistake. I have to jump through weird hoops to achieve this:

https://github.com/realnc/dosbox-core/blob/libretro/.github/workflows/main.yml#L121

Also, I don't think the Homebrew project should be responsible for policing and enforcing licensing issues :-P

**Comment by MikeMcQuaid** [comment]
> For example when creating a plugin (a single dylib file) that is supposed to be loaded in a third-party host application.

Unless that third-party host application is open source and distributes Glib sources: this is a LGPL violation.

> Also, it's very difficult to do static linking by mistake.

I disagree.

> Also, I don't think the Homebrew project should be responsible for policing and enforcing licensing issues :-P

We should do what's best for our users as a whole. It's up to the maintainers to figure out what that is.

If we get more requests for this we'll consider it but passing for now. I'd suggest you fork this formula for your own static version.

**Comment by realnc** [comment]
> Unless that third-party host application is open source and distributes Glib sources: this is a LGPL violation.

It is open source. It's GPL. But even if it wasn't, how would that violate the LGPL? The host application links dynamically against the `.dylib` plugin. Why would it be different compared to linking against the glib `.dylib` file instead? It's the same thing. So please explain :-/

And why do open source people like myself have to pay a penalty here? We should be able to benefit from our application being open source. Now we're being inconvenienced for the sake of proprietary software.

**Comment by MikeMcQuaid** [comment]
> And why do open source people like myself have to pay a penalty here?

You don't. We don't make changes to formulae for all users unless we suspect they are needed by a decent percentage of them. I'm unconvinced that applies in this case (yet).

In this case: Homebrew binaries/libraries are explicitly not suitable for distribution in other applications because of how they are built.

**Comment by sjackman** [comment]
Arguments in favour:
- Debian includes the static library `libglib-2.0.a` in their package. Debian are generally quite strict on license issues. https://packages.debian.org/sid/amd64/libglib2.0-dev/filelist
- Most packages distribute both dynamic and static libraries (AFAIK)

Arguments against:
- The upstream maintainers do not install the static library by default.

@realnc Is it possible for a plugin to be dynamically linked? I would think so myself. Are you trying to distribute a binary of the plugin? If so, have you considered distributing your binary plugin package using a third-party Homebrew tap? Homebrew works on macOS, Linux, and Windows 10 (using WSL). Happy to chat about this more if you're interested.

**Comment by realnc** [comment]
> Is it possible for a plugin to be dynamically linked?

No. It should be a single `.dylib` file and not require any external dependencies.

Anyway, MikeMcQuaid said that Homebrew is not that kind of package manager, even though I've been using it as such for a long time now. But I will finally need to switch to something like Conan or vcpkg, since they are made to support my use case (meaning easily installing dependencies of libraries I need to compile distributable builds of my software.)

**Comment by MikeMcQuaid** [comment]
> MikeMcQuaid said that Homebrew is not that kind of package manager,

I said that Homebrew doesn't change things just because a single user asks for them. If you'd rather use something else: that's up to you but it ends this conversation.

**Pull request closed without merging**
