### PR TITLE
hmmer 3.2.1

### PR DESCRIPTION
**Pull request by tseemann**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> /usr/local/Cellar/hmmer/3.2.1/bin/hmmstat /usr/local/Cellar/hmmer/3.2.1/share/doc/hmmer/tutorial/minifam

Error: File existence/permissions problem in trying to open HMM file /usr/local/Cellar/hmmer/3.2.1/share/doc/hmmer/tutorial/minifam.
HMM file /usr/local/Cellar/hmmer/3.2.1/share/doc/hmmer/tutorial/minifam not found (nor an .h3m binary of it)

Error: hmmer: failed
```

**Comment by tseemann** [comment]
Thank you @fxcoudert - i accidently tested the old version locally. They've renamed `minifam` to `Pkinase.hmm`.

**Comment by sjackman** [comment]
Oddly, this updated PR didn't get properly transfer to BrewTestBot.
See https://github.com/BrewTestBot/homebrew-core/blob/pr-32804/Formula/hmmer.rb#L22
@tseemann Please run `git commit --amend && git push --force` to rebuild the bottle.

**Comment by tseemann** [comment]
Ok, rebased, amended and pushed.

**Comment by sjackman** [comment]
Merged. Thanks, Torsten!

**Pull request closed without merging**
