### PR TITLE
frpc: 0.24.1 (new formula).

### PR DESCRIPTION
**Pull request by xykong**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Could you add a more meaningful test? Version checks very rarely show issues with dependencies.

**Comment by xykong** [comment]
frpc is the client of frp (https://github.com/fatedier/frp)
Without frps running, I can't run comprehensive functional testing.
But I add more test case for checking return code and return message.
Hope this helps. @SMillerDev

**Comment by sunznx** [comment]
want this, please - -

**Comment by xykong** [comment]
remove useless ENV["XC_OS"] = "darwin"
remove duplicated url from desc.

on commit d79a264

**Comment by xykong** [comment]
Same modify as the server script.  https://github.com/Homebrew/homebrew-core/pull/37160

more minor improvements

    1. modify desc to more clearer
    2. remove unnecessary ENV["XC_ARCH"] = "amd64"
    3. modify tag to latest version v0.26.0

Please review again, thanks. @SMillerDev

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
