### PR TITLE
navi 0.5.0

### PR DESCRIPTION
**Pull request by denisidoro**
Related: https://github.com/denisidoro/navi

### CODE REVIEW

**Comment by djerfy** [comment]
Hi @denisidoro can you update the title with `(new formula)` and run a `brew audit --strict navi`

**Comment by equal-l2** [comment]
```
navi:
  * C: 1: col 1: A `test do` test block should be added
  * C: 2: col 9: Description shouldn't start with an indefinite article, i.e. "An"
  * C: 6: col 1: Trailing whitespace detected.
  * C: 13: col 1: Extra empty line detected at class body end.
  * C: 14: col 4: Final newline missing.
  * File should end with a newline
Error: 6 problems in 1 formula detected
```

**Comment by denisidoro** [comment]
I'll add the necessary changes later this week. Thanks for the responses

**Comment by SMillerDev** [comment]
Hi, this seems like a nice software, but not notable enough for us to package in Homebrew for now. This is not a decision on the merits of the software, but we cannot distribute every single piece of software and have to draw a line on “notability” somewhere. Of course, we would be happy to reconsider in the future.

Please consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by Amorymeltzer** [comment]
FWIW @SMillerDev the repo is at ~140 forks, ~45 watchers, and ~3200 stars.

**Pull request closed without merging**
