### PR TITLE
cairomm 1.16 cairomm 1.14.2 (newformula)

### PR DESCRIPTION
**Pull request by tschoonj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Closes #65090

### CODE REVIEW

**Comment by chenrui333** [comment]
just curious, why dont we just upgrade to the latest 1.16.0 per [NEWS](https://github.com/freedesktop/cairomm/blob/master/NEWS)?

**Comment by tschoonj** [comment]
1.16 breaks API and is not supported by the current gtkmm3 release.

But you're right, this formula should have the latest stable release: I will do so, and also create a cairomm@1.14 formula.

**Comment by tschoonj** [comment]
@chenrui333 are you fine with this PR?

**Review by SMillerDev — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@tschoonj, lgtm!

**Pull request closed without merging**
