### PR TITLE
gtk+3 3.24.18

### PR DESCRIPTION
**Pull request by tschoonj**
By the way: my 3.24.17 PR #52561 was closed but apparently the commit never made it into master...

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
> By the way: my 3.24.17 PR #52561 was closed but apparently the commit never made it into master...

https://github.com/Homebrew/homebrew-core/blob/master/Formula/gtk%2B3.rb#L4 ?

**Comment by tschoonj** [comment]
Ignore my remark, my brain went offline apparently when I wrote that...

**Comment by Bo98** [comment]
blergh

**Comment by Bo98** [comment]
@tschoonj Can you try rebase onto master and see if that fixes it?

**Comment by tschoonj** [comment]
Done!

**Comment by Bo98** [comment]
ffs

**Comment by tschoonj** [comment]
Need another rebase?

**Comment by Bo98** [comment]
Maybe nuking the branch and recreating might work. It seems to be cursed.

I will need to look into why it happens. Something's funky about GitHub's API.

Basically it says that the CI run doesn't exist:

```
Error: No matching workflow run found for these criteria!
  Commit SHA:   972c5d52be8dd4933ad29774861c8bd12666b9c8
  Branch ref:   gtk+-3.24.18
  Pull request: 52817
  Workflow:     tests.yml
```

**Comment by tschoonj** [comment]
Closing in favour of #53106

**Pull request closed without merging**
