### PR TITLE
libtool 2.4.7

### PR DESCRIPTION
**Pull request by joh-klein**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
The patch doesn't apply correctly anymore. I guess we could try to drop it

```
==> Applying dynamic_lookup-11.patch
  patch -g 0 -f -p0 -i /private/tmp/libtool--patch-20220317-4[41](https://github.com/Homebrew/homebrew-core/runs/5583809315?check_suite_focus=true#step:6:41)36-lfng68/dynamic_lookup-11.patch
  patching file m4/libtool.m4
  Hunk #1 FAILED at 1067.
  1 out of 1 hunk FAILED -- saving rejects to file m4/libtool.m4.rej
  patching file configure
  Hunk #1 FAILED at 8[48](https://github.com/Homebrew/homebrew-core/runs/5583809315?check_suite_focus=true#step:6:48)0.
  1 out of 1 hunk FAILED -- saving rejects to file configure.rej
  patching file libltdl/configure
  Hunk #1 FAILED at 7366.
  1 out of 1 hunk FAILED -- saving rejects to file libltdl/configure.rej
```

**Comment by carlocab** [comment]
I haven't checked the tarball, but my understanding based on discussion from the Libtool dev mailing list is that this release should include a version of the patch.

**Comment by Bo98** [comment]
Yes, that's correct.

**Comment by SMillerDev** [comment]
Linux failure are the usual suspects, I think this is mergable.

**Review by SMillerDev — APPROVED** [review]

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
