### PR TITLE
txr 241

### PR DESCRIPTION
**Pull request by zachauten**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
You'll need to remove the `disable!` if you want to test this.

**Comment by SMillerDev** [comment]
Why was it disabled?

**Comment by gromgit** [comment]
https://github.com/Homebrew/homebrew-core/pull/53941#issuecomment-667662893:
> Upstream git repo and tarball leads to a parked domain, so let's disable this formula.

It seems like that's been resolved.

**Comment by Bo98** [comment]
Good to know they fixed the build error in 241.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
