### PR TITLE
youtube-dl 2017.03.20

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zmwangx** [comment]
> All three bottles end up identical

That's true for any pure Python wheel. There's not much to compile, sure, but the end result is still very different from source form, and I don't think there's any guideline that says we only make bottles when there's heavy compilation involved.

**Comment by fxcoudert** [comment]
Bottles are described in our doc as _“pre-built binary package”_. It also says _“Only formulae where the upstream URL breaks or moves frequently, require compile or have a reasonable amount of patches/resources should be bottled”_.

Making `youtube-dl` bottleless would not increase the user install time (going from 2 to 5 seconds on my system), and would make merging easier for maintainers (which happens _often_ given that `youtube-dl` is releases an update pretty much every day).

**Comment by fxcoudert** [comment]
@ilovezfs @MikeMcQuaid @JCount @bfontaine what's your opinion on the matter?

**Comment by MikeMcQuaid** [comment]
We need them because we use `make` and broadly want bottles to be usable in the slightly mad configuration where you don't have Xcode or the CLT installed.

**Comment by zmwangx** [comment]
youtube-dl clearly falls into "require compile" so I'm not sure why that quote is an argument against bottling.

As for merging, I personally preferred `brew pull` over clicking the merge button since it's safer (checks malformed title and such), and bottling or not doesn't make a huge difference for `brew pull`. YMMV.

**Comment by bfontaine** [comment]
> youtube-dl clearly falls into "require compile"

Well it does require `make` but [it doesn’t compile anything](https://github.com/rg3/youtube-dl/blob/master/Makefile per se)

**Comment by zmwangx** [comment]
> Well it does require make but it doesn’t compile anything per se

Depending on your definition of compilation.

```make
youtube-dl: youtube_dl/*.py youtube_dl/*/*.py
	zip --quiet youtube-dl youtube_dl/*.py youtube_dl/*/*.py
	zip --quiet --junk-paths youtube-dl youtube_dl/__main__.py
	echo '#!$(PYTHON)' > youtube-dl
	cat youtube-dl.zip >> youtube-dl
	rm youtube-dl.zip
	chmod a+x youtube-dl
```

But I forgot the fact that the zipped package is already provided in the tarballs we download. So yeah, when we download the release tarballs we're not really compiling anything other than `CONTRIBUTING.md` and `docs/supportedsites.md`.

**Comment by zmwangx** [comment]
Basically, we can bypass the make step and it still works for stable releases.

```diff
diff --git a/Formula/youtube-dl.rb b/Formula/youtube-dl.rb
index 7a3fb28d54..058447c605 100644
--- a/Formula/youtube-dl.rb
+++ b/Formula/youtube-dl.rb
@@ -22,7 +22,7 @@ class YoutubeDl < Formula
   depends_on "rtmpdump" => :optional
 
   def install
-    system "make", "PREFIX=#{prefix}"
+    system "make", "PREFIX=#{prefix}" if build.head?
     bin.install "youtube-dl"
     man1.install "youtube-dl.1"
     bash_completion.install "youtube-dl.bash-completion"
```

**Comment by ilovezfs** [comment]
what is make step doing

**Comment by zmwangx** [comment]
Zipping up source files into an executable bundle, etc. The make step has already been run when making the release tarball though, so running it again only checks the timestamps (and for whatever reason makes CONTRIBUTING.md and docs/supportedsites.md which we disgard).

**Comment by ilovezfs** [comment]
can we just kill the HEAD spec

**Comment by zmwangx** [comment]
Sure, I don't care 😑

**Comment by ilovezfs** [comment]
hm so how does this interact with rtmpdump option

**Comment by zmwangx** [comment]
Nothing. `rtmpdump` is just an external executable optionally called by `youtube-dl`, like `ffmpeg` or `avconv`.

```
brew install youtube-dl --with-rtmpdump
```

is equivalent to

```
brew install youtube-dl rtmpdump
```

Frankly I'm surprised there's such an option.

**Comment by ilovezfs** [comment]
I'm indifferent about keeping HEAD but :+1: to bottle unneeded here for stable.

**Comment by zmwangx** [comment]
#11284.

**Pull request closed without merging**
