### PR TITLE
glm 0.9.9.6

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
[Upstream issue](https://github.com/g-truc/glm/issues/947).

**Comment by chenrui333** [comment]
@Moisan Looks like the upstream issue got resolved.

**Comment by fxcoudert** [comment]
Probably means we will be able to ship the next version

**Comment by alebcay** [comment]
Version 0.9.9.7 has been released, looks like things still aren't working.
```
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/glm/0.9.9.7 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
GLM: Clang - AppleClang compiler
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_C_FLAGS_RELEASE


-- Build files have been written to: /tmp/glm-20200111-4686-lp6h0z/glm/build
==> make install
make: *** No rule to make target `install'.  Stop.
```

**Pull request closed without merging**
