### PR TITLE
imagemagick 7.0.4-2

### PR DESCRIPTION
**Pull request by equal-l2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
This will actually be quite a bit of work: https://github.com/Homebrew/homebrew-core/issues/1828

**Comment by equal-l2** [comment]
@ilovezfs 
Sorry, I didn't look in issues.

**Comment by ilovezfs** [comment]
@equal-l2 no need to apologize. Just wanted to make sure you realize what you're getting yourself into here hehe

**Comment by ilovezfs** [comment]
So you'll need to revision bump autotrace, blockhash, dmtx-utils, pstoedit, synfig, and zbar. Based on #1828, that will be sufficient for autotrace and pstoedit but not the others.

**Comment by ilovezfs** [comment]
Closing in favor of #8746.

@equal-l2 thanks for the PR nonetheless.

**Pull request closed without merging**
