### PR TITLE
peco: fix `glide install` permissions error

### LINKED ISSUE #4412: peco 0.4.2 upgrade fails during glide install
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

When running the command `brew upgrade peco`, I get a failure from inside the `install` method of the formula:

```
$ brew upgrade peco
==> Upgrading 1 outdated package, with result:
peco 0.4.2
==> Upgrading peco
==> Using the sandbox
==> Downloading https://github.com/peco/peco/archive/v0.4.2.tar.gz
Already downloaded: /opt/boxen/cache/homebrew/peco-0.4.2.tar.gz
==> glide install
Last 15 lines from /Users/rk/Library/Logs/Homebrew/peco/01.glide:
2016-09-01 09:17:43 -0400

glide
install

[INFO] 	Downloading dependencies. Please wait...
[ERROR]	Cache directory unavailable: mkdir /Users/rk/.glide: operation not permitted

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues
```

I apologize, when I ran `brew gist-logs peco`, I got an error message (likely unrelated to this issue):

```
$ brew gist-logs peco
Error: Your HOMEBREW_GITHUB_API_TOKEN does not have sufficient scope!
Scopes it has: ["repo", "user"]
Create a new personal access token: https://github.com/settings/tokens
and then set the new HOMEBREW_GITHUB_API_TOKEN as the authentication method instead.
Error: {
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/gists/#create-a-gist"
}
```

Looking at the documentation for glide, this suggests to me that `glide install` is running into a permissions problem; perhaps work around it by setting `$GLIDE_HOME` to a temp dir or something?

### PR DESCRIPTION
**Pull request by hakamadare**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Fixes #4412.  #4413 also fixes the same problem; I would have no objection to that fix being merged instead of this one.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@hakamadare do you mind updating this to just set `ENV["GLIDE_HOME"] = buildpath/"glide_home"`? I'd like to merge your PR instead of mine since you did the research to find the fix!

**Comment by ilovezfs** [comment]
@hakamadare just a ping on this. Have you had a chance to update this?

**Comment by ilovezfs** [comment]
I'll go ahead and merge my PR but many thanks for bringing this problem to our attention.

**Comment by hakamadare** [comment]
d'oh, sorry, totally missed this!  no worries, i'm just glad it's fixed :)

**Comment by ilovezfs** [comment]
@hakamadare no problem at all! I figured it was something like that. Thanks again for the PR!!!

**Pull request closed without merging**
