### PR TITLE
istioctl 1.10.0

### PR DESCRIPTION
**Pull request by LukasAuerbeck**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
I think this needs https://github.com/istio/istio/pull/32792

**Comment by LukasAuerbeck** [comment]
> I think this needs [istio/istio#32792](https://github.com/istio/istio/pull/32792)

Yes it seems so. I am not that familiar with homebrew so I am unsure how such situations get handled. Would it be ok to change the build for release 1.9.5 to the branch https://github.com/istio/istio/commits/release-1.9.5-patch to make updating possible, and switching it back to the normal builds based on tags when the next version gets released?

**Comment by SMillerDev** [comment]
> Would it be ok to change the build for release 1.9.5 to the branch https://github.com/istio/istio/commits/release-1.9.5-patch to make updating possible

No, releases need to be tagged versions, but we can apply a patch if upstream merged it already.

**Comment by cho-m** [comment]
@LukasAuerbeck You can see how other formula make use of the `patch do ... end` block.

The patch you want is probably:
https://github.com/istio/istio/commit/98a6168b48fd02c2e3d7cc819067d50044004ba5.patch?full_index=1

You will need to calculate the sha256sum of the patch and may want to add a comment to remove patch.

**Comment by LukasAuerbeck** [comment]
Alright, thanks for the help. I will try to look into this later today and update the PR!

**Comment by LukasAuerbeck** [comment]
I updated the PR and rebased it to the master, however, there still seems to be an issue with the ARM build.

Since I don't have an ARM cpu I can't easily look at the generated .env file which apparently has wrong spacing. A local build produces the following content for me:

```
TARGET_OUT_LINUX=/private/tmp/istioctl-20210514-29143-1tw6hvg/out/linux_amd64
TARGET_OUT=/private/tmp/istioctl-20210514-29143-1tw6hvg/out/darwin_amd64
TIMEZONE=Europe/Vienna
LOCAL_OS=Darwin
TARGET_OS=darwin
LOCAL_ARCH=x86_64
TARGET_ARCH=amd64
BUILD_WITH_CONTAINER=0
```

To further debug this I think access to the generated .env file is necessary, is there a way to upload this file as an artifact of the arm build?

**Comment by cho-m** [comment]
I don't think `istioctl` currently supports Apple Silicon (ARM).
The commit for support is only available in 1.10.x (rc/alpha) tags: https://github.com/istio/istio/commit/ee0abcc8ed470d967e16b35c251a8abb01e9f4df

For Homebrew, there previously wasn't an ARM bottle, but the bottles got collapsed into an `all` section (https://github.com/Homebrew/homebrew-core/commit/ba9c2f3df0ab31674fe057ea40ec3fdd3d1ad93b) during 1.9.4 update.

**Comment by SMillerDev** [comment]
can you add `depends_on arch: :x86_64` then?

**Comment by LukasAuerbeck** [comment]
I added the depends_on for the arch as suggested and rebased the branch to the master, everything builds now! Thanks for the suggestions and help on this PR :)

**Comment by chenrui333** [comment]
Now with istioctl 1.10.0 release, let's give it another spin.

**Comment by cho-m** [comment]
It looks like upstream didn't change shell script so Makefile still errors
https://github.com/istio/istio/blob/1.10.0/common/scripts/setup_env.sh#L28

We could try forcing the build by doing something like:
`ENV["TARGET_ARCH"] = "arm64" if Hardware::CPU.arm?`

The `dirpath = darwin_arm64` will need to be used for cd output directory.

---

I was able to build/test locally, but can't confirm if it is fully functional:
```console
❯ brew install istioctl --build-from-source
==> Cloning https://github.com/istio/istio.git
Updating /Users/cho-m/Library/Caches/Homebrew/istioctl--git
==> Checking out tag 1.10.0
HEAD is now at d26cba7e34 Fix local address for ipv6 probes (#32877)
HEAD is now at d26cba7e34 Fix local address for ipv6 probes (#32877)
==> make gen-charts istioctl istioctl.completion
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/homebrew/Cellar/istioctl/1.10.0: 7 files, 94.4MB, built in 21 seconds

❯ brew test istioctl
==> Testing istioctl
==> /opt/homebrew/Cellar/istioctl/1.10.0/bin/istioctl version --remote=false

❯ uname -m
arm64
```

**Comment by cho-m** [comment]
Some updates:
1. removed deprecated target `gen-charts`:
    ```make
    # Keep dummy target since some build pipelines depend on this
    gen-charts:
	    @echo "This target is no longer required and will be removed in the future"
    ```
2. add logic to support missing condition for `$(uname -m) == "arm64"` in https://github.com/istio/istio/blob/1.10.0/common/scripts/setup_env.sh#L28

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
