### PR TITLE
openimageio 2.2.10

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by carlocab** [comment]
Ok, just one error:
```
==> brew audit openimageio --online --git --skip-style
==> FAILED
Error: 1 problem in 1 formula detected
openimageio:
  * python modules have explicit framework links
    These python extension modules were linked directly to a Python
    framework binary. They should be linked with -undefined dynamic_lookup
    instead of -lpython or -framework Python.
      /usr/local/opt/openimageio/lib/python3.9/site-packages/OpenImageIO.so
```
I'll have to look into how to fix this.

**Comment by carlocab** [comment]
Ok. My last commit didn't fix the audit failure, but it didn't break things either, which is good. I've got another idea to try when the other CI nodes finish. I want to check that my last commit didn't break anything on those versions too.

**Comment by carlocab** [comment]
Right, I'm out of ideas here. Any suggestions, anyone?

**Comment by carlocab** [comment]
@jonchang -- I was thinking you might know how to fix this. If you have a minute, please take a look.

**Comment by jonchang** [comment]
It's getting late here, but I'll take a deeper look tomorrow. The python undefined dynamic lookup I think was solved over a year ago in cmake upstream, so all that really needs to happen is that app maintainers need to use the new(ish) FindPython cmake scripts.

**Comment by jonchang** [comment]
You can see Seeker's similar pull request to gnuradio which also had this issue for a while with cmake for comparison: https://github.com/gnuradio/gnuradio/pull/3674/files

**Comment by carlocab** [comment]
@SeekingMeaning do you know what's going on here? I tried to replicate what you did in your PR for gnuradio, but audit is still failing...

**Comment by SeekingMeaning** [comment]
Looking at [`src/cmake/pythonutils.cmake`](https://github.com/OpenImageIO/oiio/blob/master/src/cmake/pythonutils.cmake) and [`src/python/CMakeLists.txt`](https://github.com/OpenImageIO/oiio/blob/master/src/python/CMakeLists.txt), it looks like `-undefined dynamic_lookup` is being added to an OpenImageIO library, but not `Python::Python` directly (I'm not sure, though)

See also: gnuradio's [`cmake/Modules/GrPython.cmake`](https://github.com/gnuradio/gnuradio/blob/master/cmake/Modules/GrPython.cmake) (use ⌘F for `Python::Python`)

**Comment by chenrui333** [comment]
FYI, openimageio 2.2.10 is out.

**Comment by carlocab** [comment]
I don't think it'll help tbh, but I'll give it a try; thanks.

**Comment by carlocab** [comment]
Upstream issue filed: https://github.com/OpenImageIO/oiio/issues/2806

**Review by chenrui333 — APPROVED** [review]
🚀

**Pull request closed without merging**
