### PR TITLE
web100clt: switch to `openssl@3`

### PR DESCRIPTION
**Pull request by chenrui333**
See #134251.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  configure: error: in `/tmp/web100clt-20230624-3214-qjrf5n/ndt-3.7.0.2':
  configure: error: I2util required to build NDT
```

**Comment by chenrui333** [comment]
rerun

**Comment by p-linnane** [comment]
From the homepage:

>IMPORTANT NOTICE
NDT is no longer supported because the Web100 patches to the Linux kernel will not work on modern kernels (3.x and later). A follow-on project called [Web10G](https://www.web10g.org/) was never completed. This documentation remains available for historical purposes only.

**Comment by Bo98** [comment]
```
configure:4087: gcc-11 -o conftest -pedantic -Wall -fno-strict-aliasing -std=gnu99 -DNDEBUG -O2 -DEXPERIMENTAL_ENABLED -DDATABASE_ENABLED   -pedantic -Wall -fno-strict-aliasing -std=gnu99 -DNDEBUG -O2 -DEXPERIMENTAL_ENABLED -DDATABASE_ENABLED   conftest.c -lI2util   >&5
/usr/bin/ld: /home/linuxbrew/.linuxbrew/lib/libI2util.a(addr.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
configure:4094: $? = 1
```

PIE is now the default. Looks like i2util needs recompiling, or if we don't want to do that then we could supply `-no-pie` here as a workaround for that.

**Comment by Bo98** [comment]
It's already deprecated.

Though if it's easy enough to hack in order to have one less OpenSSL 1.1 dependent it's probably worth it.

**Comment by p-linnane** [comment]
> It's already deprecated.

How did I miss that 🤦‍♂️

**Comment by chenrui333** [comment]
Build is good now. cc @Homebrew/core

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
