### PR TITLE
Fix sqoop by exposing hadoop's libexec files

### PR DESCRIPTION
**Pull request by apjanke**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Addresses #28760.
Depends on https://github.com/Homebrew/brew/pull/4470.

`brew test sqoop` is [currently failing](https://gist.github.com/ilovezfs/42eb68ded89dc0f12879550c715354cd) because sqoop cannot find hadoop's `hadoop-config.sh`. That `hadoop-config.sh` is in hadoop's `libexec`. But because we're stuffing all of hadoop into `libexec`, it ends up in `libexec/libexec`.

Current behavior:

```
$ /usr/local/Cellar/sqoop/1.4.6_1/libexec/bin/sqoop version
Warning: /usr/local/Cellar/sqoop/1.4.6_1/libexec/bin/../../hcatalog does not exist! HCatalog jobs will fail.
Please set $HCAT_HOME to the root of your HCatalog installation.
Warning: /usr/local/Cellar/sqoop/1.4.6_1/libexec/bin/../../accumulo does not exist! Accumulo imports will fail.
Please set $ACCUMULO_HOME to the root of your Accumulo installation.
Warning: /usr/local/Cellar/sqoop/1.4.6_1/libexec/bin/../../zookeeper does not exist! Accumulo imports will fail.
Please set $ZOOKEEPER_HOME to the root of your Zookeeper installation.
ERROR: Cannot execute /usr/local/libexec/hadoop-config.sh.
$ brew test sqoop                                                                                                                          master
Testing sqoop
==> /usr/local/Cellar/sqoop/1.4.6/bin/sqoop version
Error: sqoop: failed
<0> expected but was
<1>.
```

This PR re-exposes Hadoop's libexec scripts by write_exec_script'ing them back into the top libexec dir. It then points sqoop at Hadoop's `opt_prefix` so sqoop can find hadoop's config scripts.

This also sets HCAT_HOME and ZOOKEEPER_HOME in the sqoop wrapper script to fix some warnings it's currently issuing.

New behavior:

```
$ sqoop version                                                                                                                         fix-sqoop
Warning: /usr/local/Cellar/sqoop/1.4.6_1/libexec/bin/../../accumulo does not exist! Accumulo imports will fail.
Please set $ACCUMULO_HOME to the root of your Accumulo installation.
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula]
$ echo $?                                                                                                                               fix-sqoop
0
$ brew test sqoop                                                                                                                       fix-sqoop
Testing sqoop
==> /usr/local/Cellar/sqoop/1.4.6_1/bin/sqoop version
[/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula]
$
```

### CODE REVIEW

**Comment by DomT4** [comment]
Leave it alone bot.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Do we need to wait on https://github.com/Homebrew/brew/pull/4512 here @apjanke?

**Comment by DomT4** [comment]
Alright. I'm open to the permissions being fixed in-formula temporarily if that's an option & easier on you than waiting for the brew PR to reach completion, but whichever way works for you is the way we'll go.

**Comment by apjanke** [comment]
Yeah, fixing this in-formula will take less time than getting tests for Homebrew/brew#4512 written. Hold on...

**Comment by apjanke** [comment]
I've changed this PR to do the fix in-formula in `hadoop`. This PR no longer depends on Homebrew/brew#4512 and can be evaluated for merging now.

**Comment by DomT4** [comment]
Thanks @apjanke. Entirely content trusting you on Java stuff so, 🚢'd.

**Pull request closed without merging**
