### PR TITLE
appium 1.17.0

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Duplicate of #51751

That's kinda annoying that GitHub doesn't show merge conflicts for such cases.. 
@chenrui333 you've raised a GitHub issue once regarding the similar problem, is there any outcome?

**Comment by Bo98** [comment]
Probably a case of git being "too smart". You won't get merge conflicts if you merge this locally. GitHub just matches what git does.

e.g.

```
$ brew pull 51766
==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-core/pull/51766.patch
######################################################################## 100.0%
==> Applying patch
Applying: appium 1.17.0
Using index info to reconstruct a base tree...
M	Formula/appium.rb
Falling back to patching base and 3-way merge...
Auto-merging Formula/appium.rb
No changes -- Patch already applied.
==> Patch closes issue #51766
==> Patch changed:
```

**Comment by bayandin** [comment]
Wow, also just noticed when I did `brew pull --bottle 51766 51757` the wrong pull request id was added to the comment

**Comment by Bo98** [comment]
`brew pull` possibly doesn't correctly detect that no patch was applied and just carries on and modifies the last commit with the close issue line.

**Comment by chenrui333** [comment]
> That's kinda annoying that GitHub doesn't show merge conflicts for such cases..
> @chenrui333 you've raised a GitHub issue once regarding the similar problem, is there any outcome?

Have not heard about anything from Github side.

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/51134#issuecomment-595294299
> Ticket ID: 590093

**Comment by chenrui333** [comment]
> `brew pull` possibly doesn't correctly detect that no patch was applied and just carries on and modifies the last commit with the close issue line.

this issue seems only emerge most recently, I feel like it is mostly on Github side.

**Pull request closed without merging**
