### PR TITLE
ibex 2.3.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Needed to apply upstream fix for ibex-team/ibex-lib#204.

### CODE REVIEW

**Comment by DomT4** [comment]
One of the tests is 💀.

**Comment by ilovezfs** [comment]
Yeah, it's a regression. Not sure what the exact cause is yet, but seems to be some crazy exception that can be ignored but isn't.

**Comment by ilovezfs** [comment]
Reported upstream: https://github.com/ibex-team/ibex-lib/issues/204

**Comment by ilovezfs** [comment]
@DomT4 or would it be preferable to apply the patch itself? Either way is fine with me.

**Comment by DomT4** [comment]
The `inreplace` is minor enough that I think that's fine, personally. Feel free to patch if you're happier doing so though.

**Pull request closed without merging**
