### PR TITLE
libuninameslist 20230523

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ZhongRuoyu — COMMENTED** [review]
This is a pre-release: https://github.com/fontforge/libuninameslist/releases/tag/20230523

**Comment by osalbahr** [comment]
> This is a pre-release: https://github.com/fontforge/libuninameslist/releases/tag/20230523

True. Could it be that `brew bump --open-pr` is using the Repology version without looking at `livecheck`?

```console
% brew bump libuninameslist
==> libuninameslist
Current formula version:  20221022
Latest livecheck version: 20221022
Latest Repology version:  20230523
Open pull requests:       libuninameslist 20230523 (https://github.com/Homebrew/homebrew-core/pull/138604)
Closed pull requests:     none
```

**Comment by ZhongRuoyu** [comment]
Might be https://github.com/Homebrew/brew/issues/15825#issuecomment-1666346862

**Comment by osalbahr** [comment]
> Might be [Homebrew/brew#15825 (comment)](https://github.com/Homebrew/brew/issues/15825#issuecomment-1666346862)

Maybe. That error message only appears with casks, though.

**Pull request closed without merging**
