### PR TITLE
rust 1.51.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by carlocab** [comment]
Killing the tests as they will probably need to be restarted anyway when https://github.com/Homebrew/brew/pull/10934 is merged.

**Comment by bayandin** [comment]
Failures on Apple Silicon:
```
Error: 71 failed steps!
brew install --build-from-source amp
brew install --build-from-source asuka
brew test --retry --verbose aws-google-auth
brew install --build-from-source bandwhich
brew install --build-from-source boringtun
brew install --build-from-source --only-dependencies caffe
brew install --build-from-source caffe
brew install --build-from-source cargo-instruments
brew test --retry --verbose chromaprint
brew install --build-from-source chronograf
brew install --build-from-source click
brew install --build-from-source dartsim
brew install --build-from-source --only-dependencies dog
brew install --build-from-source dog
brew install --build-from-source dprint
brew install --build-from-source --only-dependencies efl
brew install --build-from-source efl
brew install --build-from-source fblog
brew test --retry --verbose ffmpegthumbnailer
brew install --build-from-source ffsend
brew test --retry --verbose fnm
brew install --build-from-source gifski
brew install --build-from-source git-trim
brew install --build-from-source --only-dependencies gitg
brew install --build-from-source gitg
brew install --build-from-source gjs
brew install --build-from-source gleam
brew install --build-from-source --only-dependencies gnuradio
brew install --build-from-source gnuradio
brew install --build-from-source grin
brew install --build-from-source grin-wallet
brew test --retry --verbose ktmpl
brew test --retry --verbose libgit2-glib
brew test --retry --verbose mat2
brew install --build-from-source miniserve
brew install --build-from-source --only-dependencies mlpack
brew install --build-from-source mlpack
brew test --retry --verbose mlt
brew install --build-from-source mpv
brew install --build-from-source openalpr
brew test --retry --verbose openimageio
brew install --build-from-source --only-dependencies pandoc-plot
brew install --build-from-source pandoc-plot
brew install --build-from-source pdfpc
brew install --build-from-source --only-dependencies pushpin
brew install --build-from-source pushpin
brew install --build-from-source --only-dependencies qmmp
brew install --build-from-source qmmp
brew install --build-from-source rbspy
brew install --build-from-source ripgrep-all
brew install --build-from-source rm-improved
brew install --build-from-source rustscan
brew test --retry --verbose saltwater
brew install --build-from-source shadowenv
brew install --build-from-source silicon
brew install --build-from-source siril
brew install --build-from-source sniffglue
brew install --build-from-source sonic
brew install --build-from-source spotifyd
brew install --build-from-source ssh-permit-a38
brew install --build-from-source --only-dependencies synfig
brew install --build-from-source synfig
brew install --build-from-source vice
brew install --build-from-source volta
brew install --build-from-source wagyu
brew install --build-from-source wapm
brew install --build-from-source wasm-pack
brew install --build-from-source --only-dependencies xboard
brew install --build-from-source xboard
brew test --retry --verbose xdot
brew install --build-from-source zim
```

**Comment by carlocab** [comment]
Most of the ARM failures don't have bottles. The ones that do are
```
aws-google-auth
cargo-instruments
chronograf
gifski
gleam
miniserve
mpv
siril
sniffglue
```

**Comment by carlocab** [comment]
Big Sur:

```
Error: 15 failed steps!
brew test --retry --verbose asuka
brew test --retry --verbose asuka
brew test --retry --verbose aws-google-auth
brew install --build-from-source chronograf
brew install --build-from-source dartsim
brew install --build-from-source gifski
brew install --build-from-source gleam
brew test --retry --verbose ktmpl
brew install --build-from-source miniserve
brew install --build-from-source pdfpc
brew install --build-from-source siril
brew install --build-from-source sniffglue
brew install --build-from-source vice
brew test --retry --verbose wasm-pack
brew test --retry --verbose wasm-pack
```

Catalina:

```
Error: 14 failed steps!
brew test --retry --verbose aws-google-auth
brew test --retry --verbose aws-google-auth
brew install --build-from-source chronograf
brew install --build-from-source dartsim
brew install --build-from-source gifski
brew install --build-from-source gleam
brew test --retry --verbose ktmpl
brew install --build-from-source miniserve
brew install --build-from-source pdfpc
brew install --build-from-source siril
brew install --build-from-source sniffglue
brew install --build-from-source vice
brew test --retry --verbose wasm-pack
brew test --retry --verbose wasm-pack
```

Mojave:

```
Error: 12 failed steps!
brew install --build-from-source chronograf
brew install --build-from-source dartsim
brew install --build-from-source gifski
brew install --build-from-source gleam
brew test --retry --verbose ktmpl
brew install --build-from-source miniserve
brew install --build-from-source pdfpc
brew install --build-from-source siril
brew install --build-from-source sniffglue
brew install --build-from-source vice
brew test --retry --verbose wasm-pack
brew test --retry --verbose wasm-pack
```

We can ignore `vice`. That's from a `vice` dependency being unlinked earlier in the CI run but not being re-linked for the `vice` build.

**Comment by Moisan** [comment]
`miniserve` has been updated to 0.12.1 since the last CI run. I can build it successfully with rust 1.51.0 locally.

**Comment by Moisan** [comment]
Gleam has been updated #74039 and upstream changelog includes
> The Gleam compiler has been updated to compile with the new Rust v1.51.0.

**Comment by Moisan** [comment]
`chronograf` currently doesn't build on master. Its only dependency on `rust` is trough `influxdb` which builds correctly with rust 1.51.0 .

**Comment by carlocab** [comment]
`chronograf` may need to be switched to `influxdb@1`.

**Comment by Bo98** [comment]
`chronograf` will be fixed in the next version: https://github.com/influxdata/chronograf/commit/6532c639762813aa33c048eaa8ba985102ac047c. Not Rust related.

**Comment by Moisan** [comment]
> chronograf may need to be switched to influxdb@1

I tried locally and it leads to the same error.

**Comment by carlocab** [comment]
I guess the only ones that still look suspicious (without double-checking the logs...) are `gifski`, `sniffglue`, `dartsim`, and `pdfpc`. I think the rest also failed in the Rust 1.50 bump.

**Comment by Bo98** [comment]
`gifski` has an open PR. I'll have a look at what's going wrong but it seems to not build on arm64 correctly.

`sniffglue` requires this patch: https://github.com/kpcyrd/sniffglue/commit/e2244ab2616272faa8ebce18308e146f275250c4.patch?full_index=1

`dartsim` actually broke from the CMake 3.20 update, which is a rare thing to see.

`pdfpc` broke with Vala 0.51.1.

**Comment by carlocab** [comment]
Actually, I just realised `cargo-instruments` and `siril` are unexpected. I think they're unrelated based on the logs though.

**Review by carlocab — APPROVED** [review]
Looks like all the failures are unrelated to this version bump. Merging.

**Comment by Bo98** [comment]
`sniffglue` isn't, but can be fixed after merge.

**Comment by carlocab** [comment]
Oops. OK, will open a PR for `sniffglue`.

**Pull request closed without merging**
