### PR TITLE
opensearch 1.2.2

### PR DESCRIPTION
**Pull request by DVMVCGCG**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dblock** [comment]
1. This should be at least superseded with OpenSearch 1.2.2 which is about to be released and includes log4j 2.16.

2. This formulae downloads the source, builds and runs OpenSearch-min, which is _not_ the release of OpenSearch. It should be rewritten to get the distribution .tar.gz from https://opensearch.org/. Those binaries include all the plugins, are signed and tested. We don't officially have a MacOS distribution yet, but in the meantime a Linux distribution can be used with some minor changes post-extraction, which I still think would be a lot better than building from source. 

Coming from https://github.com/opensearch-project/opensearch-build/issues/38

**Comment by DVMVCGCG** [comment]
@dblock what you suggest makes sense. Is there another formulae you know of that downloads a binary distribution that could be used as an example? I've never written a formulae before, so any pointers would be appreciated.

**Comment by dblock** [comment]
> @dblock what you suggest makes sense. Is there another formulae you know of that downloads a binary distribution that could be used as an example? I've never written a formulae before, so any pointers would be appreciated.

Me neither ;) For opensearch it's [pretty straightforward to get started](https://opensearch.org/docs/latest/opensearch/install/tar/) though.

**Comment by chenrui333** [comment]
Can we update opensearch to 1.2.2 per this PR?

**Comment by bayandin** [comment]
> 2\. This formulae downloads the source, builds and runs OpenSearch-min, which is _not_ the release of OpenSearch. It should be rewritten to get the distribution .tar.gz from https://opensearch.org/. Those binaries include all the plugins, are signed and tested. We don't officially have a MacOS distribution yet unfortunately, but in the meantime a Linux distribution can probably be used with some minor changes post-extraction, which I still think would be a lot better than building from source.

We don't allow such things in homebrew core. The formula should be built from the source. 
If you'd like to make a full build, please create a PR with suggested changes.

**Comment by dblock** [comment]
> > 2. This formulae downloads the source, builds and runs OpenSearch-min, which is _not_ the release of OpenSearch. It should be rewritten to get the distribution .tar.gz from https://opensearch.org/. Those binaries include all the plugins, are signed and tested. We don't officially have a MacOS distribution yet unfortunately, but in the meantime a Linux distribution can probably be used with some minor changes post-extraction, which I still think would be a lot better than building from source.
> 
> We don't allow such things in homebrew core. The formula should be built from the source. If you'd like to make a full build, please create a PR with suggested changes.

I see that looking at other formula, thanks. Is it written up somewhere? (I’m new here, apologies).

What’s the guidance for dependencies? This build downloads the kitchen sink from maven for example. Those are binary dependencies, not built from source.

**Comment by bayandin** [comment]
> I see that looking at other formula, thanks. Is it written up somewhere? (I’m new here, apologies).

Something like this https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae?

> What’s the guidance for dependencies? This build downloads the kitchen sink from maven for example. Those are binary dependencies, not built from source.

It's ok to use maven / npm / go modules / whatever else that freezes the exact version of source code dependencies with their checksums (ok, maybe "whatever" is a too broad term, but you get the idea).

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
