### PR TITLE
v2ray 4.35.1

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
>`resource` blocks may require updates.

Do you know how to check this?

**Comment by bayandin** [comment]
> > `resource` blocks may require updates.
> 
> Do you know how to check this?

It looks like we can drop resources and copy these files from [`release/config` ](https://github.com/v2fly/v2ray-core/tree/v4.35.1/release/config)

**Comment by Loyalsoldier** [comment]
I'm one of the maintainers of V2Ray's `geoip.dat` and `geosite.dat`. Is there any way in Homebrew to auto-update the resource block?

**Comment by bayandin** [comment]
> I'm one of the maintainers of V2Ray's `geoip.dat` and `geosite.dat`. Is there any way in Homebrew to auto-update the resource block?

Nope, it should be done manually unless these files added to the repo.
We can add a comment suggesting using the latest version for these resources when we update the formula tho.

Is there any problem with using files from `release/config`?

**Comment by Loyalsoldier** [comment]
> > I'm one of the maintainers of V2Ray's `geoip.dat` and `geosite.dat`. Is there any way in Homebrew to auto-update the resource block?
> 
> Nope, it should be done manually unless these files added to the repo.
> We can add a comment suggesting using the latest version for these resources when we update the formula tho.
> 
> Is there any problem with using files from `release/config`?

Then I think the better solution is to use files from `release/config`.

**Review by Loyalsoldier — CHANGES_REQUESTED** [review]
Could please also add a new testing rule for `geosite.dat` in `routing` like this:

```
{
  "ip": [
    "geoip:private"
  ],
  "outboundTag": "direct",
  "type": "field"
},
{
  "domains": [
    "geosite:private"
  ],
  "outboundTag": "direct",
  "type": "field"
}
```

**Comment by bayandin** [comment]
> Could please also add a new testing rule for `geosite.dat` in `routing`

Done

**Review by bayandin — APPROVED** [review]

**Pull request closed without merging**
