### PR TITLE
resty 3.0

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Follow up on #18857 cleaning up the formula :)

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks @AdrieanKhisbe! :triumph:

**Comment by AdrieanKhisbe** [comment]
You're welcome @ilovezfs ☺

**Comment by AdrieanKhisbe** [comment]
I got the following warning error while installing:

```
-> brew install resty
==> Downloading https://homebrew.bintray.com/bottles/resty-3.0.el_capitan.bottle.tar.gz
Already downloaded: /Users/abecchis/Library/Caches/Homebrew/resty-3.0.el_capitan.bottle.tar.gz
Error: SHA256 mismatch
Expected: 6bcc3e0e5c27ef7a59cdee22e495e5474458af91c7e481f938c3dbd48553d72c
Actual: 435854dd9bc54f09e46f3f895fc0801ce90a30b23b8d9f109f361f89666fcfe1
Archive: /Users/abecchis/Library/Caches/Homebrew/resty-3.0.el_capitan.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/micha/resty/archive/v3.0.tar.gz
Already downloaded: /Users/abecchis/Library/Caches/Homebrew/resty-3.0.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/JSON-2.94.tar.gz
Already downloaded: /Users/abecchis/Library/Caches/Homebrew/resty--JSON-2.94.tar.gz
==> perl Makefile.PL INSTALL_BASE=/usr/local/Cellar/resty/3.0/libexec
==> make
==> make install
==> Caveats
To activate the resty, add the following at the end of your ~/.zshrc:
source /usr/local/opt/resty/share/resty/resty
==> Summary
🍺  /usr/local/Cellar/resty/3.0: 20 files, 309.6KB, built in 3 seconds
```

@ilovezfs Shouldn't I have update the bottle hashed too?

**Comment by AdrieanKhisbe** [comment]
@ilovezfs Forget what I said. Everything just works fine now. I might have update brew before the bot updated the bottle

**Comment by ilovezfs** [comment]
@AdrieanKhisbe it's possible you were still on your branch?

**Comment by AdrieanKhisbe** [comment]
mmmm. now that you mention it 😉 

anyway, sorry for the false alarm 😕

**Comment by ilovezfs** [comment]
No worries :)

**Pull request closed without merging**
