### PR TITLE
Remove gnome-common

### PR DESCRIPTION
**Pull request by fxcoudert**
All those are HEAD builds, can we somehow get CI to test them?

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
CC @tschoonj to OK this.

**Comment by MikeMcQuaid** [comment]
Sorry, misclicked with the close.

**Comment by tschoonj** [comment]
good for me assuming all head builds pass....

**Comment by ilovezfs** [comment]
>All those are HEAD builds, can we somehow get CI to test them?

They'll need to be tested manually.

**Comment by fxcoudert** [comment]
Local head builds:
- `libgsf` and `goffice` pass
- `libgxps` is a preexisting failure (no `autopen.sh` file in git tree). Removing head.
- `gupnp` fails, not because of `gnome-common` but because it wants `gssdp-1.2 >= 1.1.0` (which as far as I know is not a released version, so we don't have it)
- `libgit2-glib` fails in `autogen.sh` missing `GNOME_COMPILE_WARNINGS`
- `osm-gps-map` fails in `autogen.sh` saying `You need to install gnome-common from the GNOME SVN`

**Comment by fxcoudert** [comment]
I suggest removing head from `gupnp`, `libgit2-glib` and `ism-gps-map`. @ilovezfs @tschoonj @MikeMcQuaid ?

**Comment by ilovezfs** [comment]
If there are head specs that fail without gnome-common, it doesn't really make sense to me to remove it.

**Comment by ilovezfs** [comment]
e.g. with gnome-common still there:
```
==> Summary
🍺  /usr/local/Cellar/libgit2-glib/HEAD-995b33c_1: 88 files, 1.4MB, built in 22 seconds
```

**Comment by tschoonj** [comment]
This [link](https://wiki.gnome.org/Projects/GnomeCommon/Migration) gives some background on why `gnome-common` should not be used anymore. I am totally fine with removing HEAD from those projects that still require it.

**Comment by tschoonj** [comment]
Alternatively how about using a resource for `gnome-common` for those packages whose HEAD still needs it?

**Comment by ilovezfs** [comment]
Removing gupnp head here: https://github.com/Homebrew/homebrew-core/pull/16202

@tschoonj the main one I care about is libgit2-glib since we're always having to test whether HEAD works yet with the new libgit2.

**Comment by rwhogg** [comment]
@fxcoudert would you please change the name of this PR if you don't mind? It seems somewhat misleading since the `gnome-common` formula was not deleted as part of it.

**Pull request merged**
