### PR TITLE
apache-zeppelin: fix depends_on :java

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by tingletech** [comment]
this broke zeppelin for me :(

```
% brew install apache-zeppelin  
apache-zeppelin: Java 1.7 is required to install this formula.
Install AdoptOpenJDK 8 with Homebrew Cask:
  brew cask install homebrew/cask-versions/adoptopenjdk8
Error: An unsatisfied requirement failed this build.
```

last month, zeppelin worked fine with java 1.8

**Comment by cdeil** [comment]
I wanted to try out `apache-zeppelin` (on latest macOS Catalina), and indeed it's broken in homebrew at the moment:
```
% brew install apache-zeppelin
apache-zeppelin: Java 1.7 is required to install this formula.
Install AdoptOpenJDK 8 with Homebrew Cask:
  brew cask install homebrew/cask-versions/adoptopenjdk8
Error: An unsatisfied requirement failed this build.


% brew cask install homebrew/cask-versions/adoptopenjdk8
Warning: Cask 'adoptopenjdk8' is already installed.

To re-install adoptopenjdk8, run:
  brew cask reinstall adoptopenjdk8
```

@reitermarkus @fxcoudert @tingletech - Would it be helpful to file an issue for this?

**Comment by tingletech** [comment]
I just downloaded the version directly from apache

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by reitermarkus** [comment]
According to https://zeppelin.apache.org/docs/0.8.2/quickstart/install.html 1.7 is the officially supported version. There is only a single JDK 1.7 cask left, `zulu7`, so this certainly isn't ideal.

**Comment by tingletech** [comment]
well, it works with java 1.8 -- and their Dockerfile uses java 1.8 https://hub.docker.com/r/apache/zeppelin/dockerfile -- I think the docs must be out-of-date

**Pull request merged**
