### PR TITLE
operator-sdk 1.20.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Related PR #100353, so same comment should hold on how to improve test.

**Review by canniffamber — COMMENTED** [review]
``

**Review by canniffamber — COMMENTED** [review]
L

**Review by canniffamber — COMMENTED** [review]
L

**Review by canniffamber — COMMENTED** [review]
L

**Review by canniffamber — COMMENTED** [review]
M

**Review by SMillerDev — DISMISSED** [review]

**Comment by cho-m** [comment]
Update got merged in #100602. `go` downgrade and test enhancement are being handled  in #100353

**Pull request closed without merging**
