### PR TITLE
ffmpeg 4.0, mpv 0.28.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
CC @zmwangx

**Review by ilovezfs — COMMENTED** [review]
Not announced yet.

https://www.ffmpeg.org/

**Comment by zmwangx** [comment]
I think It shouldn't be remotely as disruptive as 3.0, but we'll see.

**Comment by retokromer** [comment]
@ilovezfs FYI: It’s announced now.

**Comment by zshbleaker** [comment]
Noticed version 4.0 is not updated yet and came here to check if there's a PR. Wish it could be merged soon. 

@zmwangx As a alumnus of NSFZ 2012, 久仰大名😄

**Comment by ilovezfs** [comment]
@zmwangx there are build failures for gifski, mgba, opencv@2, openimageio, and qcli.

**Comment by ilovezfs** [comment]
gifski reported here https://github.com/meh/rust-ffmpeg/issues/112

**Comment by ilovezfs** [comment]
mgba is already fixed, so we can update it https://github.com/Homebrew/homebrew-core/pull/26914

**Comment by ilovezfs** [comment]
openimageio reported here https://github.com/OpenImageIO/oiio/issues/1923

**Comment by ilovezfs** [comment]
qcli was fixed in HEAD (https://github.com/bavc/qctools/commit/e83d7ad54a594358f6337c7a214bb700ae1bb9c9) but there's no release with the fix yet.

I've requested a release in https://github.com/bavc/qctools/issues/538.
However, there's an unrelated build failure on OS X 10.11 https://github.com/bavc/qctools/issues/539

**Comment by ilovezfs** [comment]
Expecting qcli to be the sole failure, which isn't sufficient reason to block this upgrade or to add a versioned ffmpeg@3 formula.

**Comment by ilovezfs** [comment]
also bumping mpv to 0.28.2 as long as we're here

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by scpeters** [comment]
Sorry I didn't notice this before it got merged (need to add this to my email filters). I have compilation errors in some formulae in a 3rd-party tap. If there was an `ffmpeg@3` formula, I'd try using that now, but since there's not, I'll just try to fix the compilation errors when I get a chance tomorrow.

**Pull request closed without merging**
