### PR TITLE
flac 1.4.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
#106925 also rev-bumps `faust`.

**Comment by danielnachun** [comment]
This is failing on Linux because `libsndfile` needs `python@3.10` to build.  The other failures seem to happen because they depend on `libsndfile`.

**Comment by carlocab** [comment]
> This is failing on Linux because `libsndfile` needs `python@3.10` to build.

How were we able to build it before now?

**Comment by danielnachun** [comment]
> > This is failing on Linux because `libsndfile` needs `python@3.10` to build.
> 
> How were we able to build it before now?

That is puzzling me now.  My best guess is that something in its dependency tree used to bring in Python 3 but no longer does.  I've confirmed in local testing that this is not because of it opportunistically picking up Python, and it does not provide an option to disable Python either.

**Comment by carlocab** [comment]
Needs the self-hosted Linux runner. Restarting, as I want to try to get this in before the maintenance window tomorrow.

**Review by carlocab — APPROVED** [review]

**Comment by danielnachun** [comment]
Assuming there are no serious issues on Intel macOS, there are only two failures on Linux that will need to be fixed in follow up PRs after this has been merged:
-`csfml` - the test failure here is weird - it's a C program complaining about C++ ABI problems.  I can't reproduce this locally right now and will have to look after this is merged.
-`mp3fs` - will need a revision bump

**Comment by danielnachun** [comment]
Actually the problem with `csfml` is that `sfml` needs to be rebuilt with Ubuntu 22.04 so it is built with GCC 11.  Simply rebuilding `sfml` was enough to fix `csfml` locally, so I'll open a revision bump for that now.

**Pull request closed without merging**
