### PR TITLE
chapel 1.15.0

### PR DESCRIPTION
**Pull request by awallace-cray**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by awallace-cray** [comment]
The official release date for Chapel 1.15.0 is April 6, 2017. 
I ran this a day early, in case of problems. 
But, promote it as soon as you like. 
Thanks!

**Comment by neutric** [comment]
Thanks so much @awallace-cray! I think we can wait the one day for it to be official. :)

**Comment by awallace-cray** [comment]
It's official! (thanks!)

**Comment by awallace-cray** [comment]
Hi @neutric, Chapel 1.15.0 is official and the announcements are going out.  Please promote this formula update at your next opportunity. Thanks again!

**Comment by neutric** [comment]
Done! Thanks for the update and the poke, @awallace-cray :D

**Pull request closed without merging**
