### PR TITLE
conan 0.28.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
```
==> brew install --build-bottle --verbose conan
Error: SHA256 mismatch
Expected: 278044fc06231c7ca60027406fcd6670401f2248f34c75dbf8ea73fc706093ac
Actual: eadf4cb64ec89ae32944fe8092b07cc502e88a6b68a509d495557f37907fa739
Archive: /home/linuxbrew/.cache/Homebrew/conan-0.28.0.tar.gz
To retry an incomplete download, remove the file above.
==> FAILED
```

Sigh ...

**Comment by iMichka** [comment]
Reported: https://github.com/conan-io/conan/issues/1955

**Comment by ilovezfs** [comment]
They messed up the version number.
```
Josephs-MacBook-Pro:conan joe$ diff old/conan-0.28.0/conans/__init__.py new/conan-0.28.0/conans/__init__.py 
20c20
< __version__ = '0.29.0-dev'
---
> __version__ = '0.28.0'
```

**Comment by iMichka** [comment]
Then they should have released a 0.28.1 instead of retagging ...

**Comment by ilovezfs** [comment]
Indeed.

**Pull request closed without merging**
