### PR TITLE
dbt 0.8.3

### PR DESCRIPTION
**Pull request by cmcarthur**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@cmcarthur is this not able to use cryptography 1.9?

**Comment by cmcarthur** [comment]
@ilovezfs unfortunately, we still have deps on libraries that require older crypto. we have an issue for it.

**Comment by drewbanin** [comment]
@cmcarthur any update here?

**Comment by cmcarthur** [comment]
cc @ilovezfs

**Comment by ilovezfs** [comment]
Thanks @cmcarthur!

**Pull request closed without merging**
