### PR TITLE
ldc 1.0.1-alpha1

### PR DESCRIPTION
**Pull request by ilovezfs**
CC @JohanEngelen

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by JohanEngelen** [comment]
Thanks.
I patched LLVM 1.0.0 so that it builds with LLVM3.9, there are some stupid test failures to be fixed and then we can do a subrelease 1.0.1.

**Comment by ilovezfs** [comment]
I assume you mean you patched ldc 1.0.0

>stupid test failures to be fixed and then we can do a subrelease 1.0.1.

Take your time, but if the test failures are bogus, I'd probably defer their fixes to 1.0.2

**Comment by JohanEngelen** [comment]
The failures were fixed in the commit hash that you chose here :-)  excellent

@klickverbot @redstar Let's release 1.0.1 ?

**Pull request closed without merging**
