### PR TITLE
ocrmypdf 7.3.0

### PR DESCRIPTION
**Pull request by KarlAmort**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Resource blocks need to be updated. The test fail due to the `pikepdf` version used.

**Comment by Moisan** [comment]
brew style is failing

**Review by fxcoudert — DISMISSED** [review]

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
Thank you @MatthiasWinkelmann for you effort on this PR. Closing in favor of #35138 .

**Pull request closed without merging**
