### PR TITLE
ruby-build 20180424

### PR DESCRIPTION
**Pull request by hsbt**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by commitay** [comment]
`20180329` is tagged as latest.

**Comment by hsbt** [comment]
What? I've been tagged v20180424. ( https://github.com/rbenv/ruby-build/releases/tag/v20180424 )

**Comment by ilovezfs** [comment]
@hsbt https://github.com/rbenv/ruby-build/releases/latest

An explicit GitHub release is needed.

**Comment by hsbt** [comment]
done.

**Comment by ilovezfs** [comment]
Thanks @hsbt

**Pull request merged**
