### PR TITLE
ndpi 4.6 ntopng 5.6

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  src/Flow.cpp:612:33: error: no member named 'alpn' in 'ndpi_flow_struct::(unnamed struct at /opt/homebrew/Cellar/ndpi/4.6/include/ndpi/ndpi_typedefs.h:1421:5)'
           && (ndpiFlow->protos.tls_quic.alpn != NULL))
               ~~~~~~~~~~~~~~~~~~~~~~~~~ ^
  src/Flow.cpp:613:60: error: no member named 'alpn' in 'ndpi_flow_struct::(unnamed struct at /opt/homebrew/Cellar/ndpi/4.6/include/ndpi/ndpi_typedefs.h:1421:5)'
          protos.tls.client_alpn = strdup(ndpiFlow->protos.tls_quic.alpn);
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~ ^
  src/Flow.cpp:704:14: error: no matching function for call to 'ndpi_detection_process_packet'
    proto_id = ndpi_detection_process_packet(iface->get_ndpi_struct(), ndpiFlow,
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /opt/homebrew/Cellar/ndpi/4.6/include/ndpi/ndpi_api.h:323:17: note: candidate function not viable: requires 6 arguments, but 5 were provided
    ndpi_protocol ndpi_detection_process_packet(struct ndpi_detection_module_struct *ndpi_struct,
                  ^
  src/Flow.cpp:777:13: error: no member named 'check_extra_packets' in 'ndpi_flow_struct'
    ndpiFlow->check_extra_packets = 1, ndpiFlow->max_extra_packets_to_check = 10;
    ~~~~~~~~  ^
  src/Flow.cpp:779:14: error: no matching function for call to 'ndpi_detection_process_packet'
    proto_id = ndpi_detection_process_packet(iface->get_ndpi_struct(), ndpiFlow,
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /opt/homebrew/Cellar/ndpi/4.6/include/ndpi/ndpi_api.h:323:17: note: candidate function not viable: requires 6 arguments, but 5 were provided
    ndpi_protocol ndpi_detection_process_packet(struct ndpi_detection_module_struct *ndpi_struct,
                  ^
  6 errors generated.
  make: *** [src/Flow.o] Error 1
```

**Comment by p-linnane** [comment]
`ntopng` wants to build `ndpi` itself:
```
checking for nDPI source... not found
  Could not find nDPI
  Please do cd ..; git clone https://github.com/ntop/nDPI.git; cd nDPI; ./autogen.sh; make; cd ../ntopng
  and try again
```

**Comment by chenrui333** [comment]
this is the root cause, https://github.com/ntop/ntopng/commit/92f812cfbcaf592c09538be7cedfaaf5a5c7bd60 (not sure why need the source), gonna try the revert in my local.

**Comment by chenrui333** [comment]
patch to remove the source dependency

```diff
diff --git a/configure.ac.in b/configure.ac.in
index 89068da..697750b 100644
--- a/configure.ac.in
+++ b/configure.ac.in
@@ -242,11 +242,14 @@ if test -d /usr/local/include/ndpi ; then :
    echo "WARNING: /usr/local/include/ndpi is present and might lead to compile errors"
 fi

-NDPI_INC=`echo $NDPI_CFLAGS | sed -e "s/[ ]*$//"`
-NDPI_LIB=
-NDPI_LIB_DEP=
-
-AC_MSG_CHECKING(for nDPI source)
+PKG_CHECK_MODULES([NDPI], [libndpi >= 2.0], [
+   NDPI_INC=`echo $NDPI_CFLAGS | sed -e "s/[ ]*$//"`
+   # Use static libndpi library as building against the dynamic library fails
+   NDPI_LIB="-Wl,-Bstatic $NDPI_LIBS -Wl,-Bdynamic"
+   #NDPI_LIB="$NDPI_LIBS"
+   NDPI_LIB_DEP=
+   ], [
+      AC_MSG_CHECKING(for nDPI source)
       if test -d "./nDPI" ; then :
          NDPI_HOME=./nDPI
       elif test -d "../nDPI" ; then :
@@ -254,7 +257,6 @@ AC_MSG_CHECKING(for nDPI source)
       elif test -d "$HOME/nDPI" ; then :
          NDPI_HOME=$HOME/nDPI
       fi
-
       if test ! -z "$NDPI_HOME" ; then :
          AC_MSG_RESULT(found in $NDPI_HOME)
          NDPI_LIB=$NDPI_HOME/src/lib/libndpi.a
@@ -271,7 +273,7 @@ AC_MSG_CHECKING(for nDPI source)
       else
          AC_MSG_RESULT(not found)
       fi
-
+   ])
```

**Comment by chenrui333** [comment]
per [this change](https://github.com/ntop/ntopng/commit/8d31f218212d47eb7816e49076c746d9e769a2a7), it needs [PF_RING](https://repology.org/project/pf-ring-userland/versions)

**Comment by aparcar** [comment]
Can we please still have this?

**Pull request closed without merging**
