### PR TITLE
opencascade: fix missing fontconfig dependency

### PR DESCRIPTION
**Pull request by Meakk**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Meakk** [comment]
Required for #90575  

@SMillerDev

**Comment by iMichka** [comment]
Linux build fails with:
```
2021-12-14T10:11:35.8581330Z In file included from /tmp/opencascade-20211214-14760-1cgb4h3/occt-V7_6_0/include/opencascade/OpenGl_GlFunctions.hxx:1:0,
2021-12-14T10:11:35.8582739Z                  from /tmp/opencascade-20211214-14760-1cgb4h3/occt-V7_6_0/src/OpenGl/OpenGl_GlCore11Fwd.hxx:19,
2021-12-14T10:11:35.8584081Z                  from /tmp/opencascade-20211214-14760-1cgb4h3/occt-V7_6_0/include/opencascade/OpenGl_GlCore11Fwd.hxx:1,
2021-12-14T10:11:35.8585412Z                  from /tmp/opencascade-20211214-14760-1cgb4h3/occt-V7_6_0/src/OpenGl/OpenGl_GlCore11.hxx:19,
2021-12-14T10:11:35.8586711Z                  from /tmp/opencascade-20211214-14760-1cgb4h3/occt-V7_6_0/include/opencascade/OpenGl_GlCore11.hxx:1,
2021-12-14T10:11:35.8588012Z                  from /tmp/opencascade-20211214-14760-1cgb4h3/occt-V7_6_0/src/OpenGl/OpenGl_Context.hxx:44,
2021-12-14T10:11:35.8589397Z                  from /tmp/opencascade-20211214-14760-1cgb4h3/occt-V7_6_0/include/opencascade/OpenGl_Context.hxx:1,
2021-12-14T10:11:35.8590682Z                  from /tmp/opencascade-20211214-14760-1cgb4h3/occt-V7_6_0/src/OpenGl/OpenGl_Aspects.cxx:15:
2021-12-14T10:11:35.8592108Z /tmp/opencascade-20211214-14760-1cgb4h3/occt-V7_6_0/src/OpenGl/OpenGl_GlFunctions.hxx:65:21: fatal error: GL/gl.h: No such file or directory
2021-12-14T10:11:35.8593005Z compilation terminated.
2021-12-14T10:11:35.8594149Z src/TKOpenGl/CMakeFiles/TKOpenGl.dir/build.make:78: recipe for target 'src/TKOpenGl/CMakeFiles/TKOpenGl.dir/__/OpenGl/OpenGl_Aspects.cxx.o' failed
2021-12-14T10:11:35.8595276Z make[2]: *** [src/TKOpenGl/CMakeFiles/TKOpenGl.dir/__/OpenGl/OpenGl_Aspects.cxx.o] Error 1
2021-12-14T10:11:35.8596547Z make[2]: Leaving directory '/tmp/opencascade-20211214-14760-1cgb4h3/occt-V7_6_0'
2021-12-14T10:11:35.8597667Z CMakeFiles/Makefile2:1808: recipe for target 'src/TKOpenGl/CMakeFiles/TKOpenGl.dir/all' failed
2021-12-14T10:11:35.8598479Z make[1]: *** [src/TKOpenGl/CMakeFiles/TKOpenGl.dir/all] Error 2
2021-12-14T10:11:35.8599064Z make[1]: *** Waiting for unfinished jobs....
```

I think this needs `mesa` on Linux. Can you add this in a `on_linux` block?

**Comment by Meakk** [comment]
@iMichka I have added, but a lot of workflows have been canceled because of the 1-hour timeout.

**Comment by SMillerDev** [comment]
The test seems to be failing on Linux, it's not clear to me why.
```
==> /home/linuxbrew/.linuxbrew/Cellar/opencascade/7.6.0/bin/DRAWEXE -c "pload ALL"
this isn't a Tk application
Error: opencascade: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected: "1"
  Actual: ""
```

**Comment by Meakk** [comment]
I suspect the test is calling an executable requiring an X server. How are run the tests? Inside a Docker container?

**Comment by SMillerDev** [comment]
Yes, they are run in docker

**Review by carlocab — DISMISSED** [review]
Thanks!

**Comment by Meakk** [comment]
I have modified the code to run the process using the `-b` option in order to run it in batch mode where a running X server is not required.  
In this case, an additional message is displayed: "DRAW is running in batch mode", so I discarded this first line and test only the second line which is "1" as expected.

**Comment by iMichka** [comment]
I retriggered the CI.

**Comment by Meakk** [comment]
Looks like all the tests are passing. Can we move forward?

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
