### PR TITLE
ansible-lint 6.14.1

### PR DESCRIPTION
**Pull request by ssbarnea**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ModuleNotFoundError: No module named 'ansible_compat'
```

**Comment by ssbarnea** [comment]
@dawidd6 Yep, I can. Leave it up to me to find a fix. Thanks for mentioning me.

**Comment by chenrui333** [comment]
#125220

**Comment by chenrui333** [comment]
@ssbarnea I think we can close this PR in favor of the other one?

**Pull request closed without merging**
