### PR TITLE
pipenv 2021.11.5.post0

### PR DESCRIPTION
**Pull request by FlickerSoul**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dtrodrigues** [comment]
```
Resolving dependencies...
✘ Locking Failed! 

  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2021.11.5.post0/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 25
    path_options = [name, f"{name}.py"]
                                     ^
SyntaxError: invalid syntax
```

Looks to be caused by https://github.com/pypa/pipenv/issues/4831

**Comment by carlocab** [comment]
We probably want to wait for a version where that's fixed then.

**Comment by dtrodrigues** [comment]
Thanks for the PR @FlickerSoul but we'll wait for the next release

**Comment by FlickerSoul** [comment]
Thank you guys!

**Pull request closed without merging**
