### PR TITLE
goaccess 1.0.2

### PR DESCRIPTION
**Pull request by ilovezfs**
- stable spec also needs Autotools now
- remove glib and pkg-config dependencies
- enable utf8 support
- update the test

### CODE REVIEW

**Comment by ilovezfs** [comment]
So just how much do we all hate this approach?

**Comment by UniqMartin** [comment]
It's not technically patching, but the `open_memstream` workaround feels pretty invasive and I wonder whether there's a better and cleaner solution for that …

**Comment by ilovezfs** [comment]
Upstream is aware of the issue per the issue report link above, and is deciding how to proceed, but in the meantime this seemed like the most straightforward workaround to me. Also, this worked equally well: http://piumarta.com/software/memstream

**Comment by ilovezfs** [comment]
For what it's worth, the breaking commit https://github.com/allinurl/goaccess/commit/487ef906f8a7c7a7bff807c252c60c4fe2f537ca did not `git revert` cleanly. But maybe you have another idea?

**Comment by UniqMartin** [comment]
If the currently available version doesn't have any issues, how about just waiting a little bit longer until upstream has had a fair chance to ponder this a bit more and maybe even come up with an official fix?

**Comment by ilovezfs** [comment]
@UniqMartin we could do that, but upstream seemed to be happy with the PR in the interim ...

**Comment by ilovezfs** [comment]
Time wasted, I guess. Moving on.

**Comment by UniqMartin** [comment]
:+1: Thanks for your patience and letting upstream fix this and create a new release.

**Comment by ilovezfs** [comment]
@UniqMartin https://github.com/allinurl/goaccess/issues/422#issuecomment-225333338, and following :)

It's nice to have upstreams that care about their software.

**Comment by UniqMartin** [comment]
:tada:

> It's nice to have upstreams that care about their software.

Indeed. That reads a lot like a constructive and respectful conversation. :)

**Pull request closed without merging**
