### PR TITLE
immortal 0.16.0

### PR DESCRIPTION
**Pull request by nbari**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@nbari Can I convince you to start using the Go vendor directory and/or one of the Go vendor systems (`dep`, `glide`, `govendor`, `godep`, etc.), so that we can remove these resource blocks?

**Comment by nbari** [comment]
@ilovezfs  I can give a try, but could this one please be as it is?

**Comment by ilovezfs** [comment]
Thanks! :heart:

>could this one please be as it is?

No problem.

**Comment by ilovezfs** [comment]
Thanks for the upgrade @nbari!

**Comment by nbari** [comment]
@ilovezfs I would like to try submitting a new formula but in this time giving a try to go `dep` but are there any guidelines or examples you could please provide so that I could implement it.

thanks in advance

**Comment by ilovezfs** [comment]
@nbari Awesome! Sure, here are two:

https://github.com/pressly/goose/pull/51
https://github.com/pilosa/pilosa/pull/744

**Pull request closed without merging**
