### PR TITLE
Update kompose to version 0.3.0 (from 0.2.0)

### PR DESCRIPTION
**Pull request by MPV**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by MPV** [comment]
I tried `brew bump-formula-pr` but without success:
```
$ brew bump-formula-pr --strict kompose --url=https://github.com/kubernetes-incubator/kompose/archive/v0.3.0.tar.gz --sha256=047e5367856f07338515eea43fb213e08fdde79333250e4cc85251e80251c928
Updated Homebrew from a381b59 to 29f431e.
Updated 1 tap (caskroom/cask).
==> replace "https://github.com/kubernetes-incubator/kompose/archive/v0.2.0.tar.gz" with "https://github.com/kubernetes-incubato
==> replace "a6be3935ff666b75ad06f389a5c23184c3c83659ae25135ab7c2c3d37b22d92d" with "047e5367856f07338515eea43fb213e08fdde793332
==> Installing or updating 'rubocop' gem
Fetching: rainbow-2.2.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed rainbow-2.2.1
Fetching: ast-2.3.0.gem (100%)
Successfully installed ast-2.3.0
Fetching: parser-2.4.0.0.gem (100%)
Successfully installed parser-2.4.0.0
Fetching: powerpack-0.1.1.gem (100%)
Successfully installed powerpack-0.1.1
Fetching: ruby-progressbar-1.8.1.gem (100%)
Successfully installed ruby-progressbar-1.8.1
Fetching: unicode-display_width-1.1.3.gem (100%)
Successfully installed unicode-display_width-1.1.3
Fetching: rubocop-0.47.1.gem (100%)
Successfully installed rubocop-0.47.1
7 gems installed
M	Formula/kompose.rb
Switched to a new branch 'kompose-0.3.0'
[kompose-0.3.0 b5af2f2] kompose 0.3.0
 1 file changed, 2 insertions(+), 2 deletions(-)
github.com username: MPV
github.com password for MPV (never stored):
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Counting objects: 84525, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (30242/30242), done.
Writing objects: 100% (84525/84525), 28.34 MiB | 5.48 MiB/s, done.
Total 84525 (delta 60087), reused 78568 (delta 54134)
remote: Resolving deltas: 100% (60087/60087), done.
To git@github.com:MPV/homebrew-core.git
 * [new branch]      kompose-0.3.0 -> kompose-0.3.0
Branch kompose-0.3.0 set up to track remote branch kompose-0.3.0 from MPV.
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
Error: Failure while executing: hub pull-request --browse -m kompose\ 0.3.0

Created\ with\ `brew\ bump-formula-pr`.
```

**Comment by MPV** [comment]
RuboCop doesn't pass, but I can't tell why:
```
$ brew audit --strict kompose
==> Installing or updating 'rubocop' gem
Fetching: parser-2.4.0.0.gem (100%)
Successfully installed parser-2.4.0.0
Fetching: unicode-display_width-1.1.3.gem (100%)
Successfully installed unicode-display_width-1.1.3
Fetching: rubocop-0.47.1.gem (100%)
Successfully installed rubocop-0.47.1
3 gems installed
Error: Error while running RuboCop
```

**Comment by MPV** [comment]
RuboCop doesn't pass, but I can't tell why:
```
$ brew audit --strict kompose
==> Installing or updating 'rubocop' gem
Fetching: parser-2.4.0.0.gem (100%)
Successfully installed parser-2.4.0.0
Fetching: unicode-display_width-1.1.3.gem (100%)
Successfully installed unicode-display_width-1.1.3
Fetching: rubocop-0.47.1.gem (100%)
Successfully installed rubocop-0.47.1
3 gems installed
Error: Error while running RuboCop
```

**Comment by fxcoudert** [comment]
Audit seems to pass on the build bot, so… thanks for contributing to Homebrew!

**Comment by MPV** [comment]
@fxcoudert Seems it doesn't work as a "bottle" install, but maybe that's not an issue?

```
$ brew update
Updated Homebrew from 29f431e to bd444dd.
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
kompose
```
```
$ brew install kompose
==> Downloading https://homebrew.bintray.com/bottles/kompose-0.3.0.sierra.bottle.tar.gz
######################################################################## 100,0%
Error: SHA256 mismatch
Expected: f9ff134a40769ed9d390a2571bc16c49940c7cef071bd54d80a97424524887df
Actual: 1f9c9222f6bfa1971afbde27a1d79e64431caf5394cf5657065e30f272f21ef2
Archive: /Users/vs/Library/Caches/Homebrew/kompose-0.3.0.sierra.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
==> Using the sandbox
==> Downloading https://github.com/kubernetes-incubator/kompose/archive/v0.3.0.tar.gz
Already downloaded: /Users/vs/Library/Caches/Homebrew/kompose-0.3.0.tar.gz
==> make bin
🍺  /usr/local/Cellar/kompose/0.3.0: 6 files, 45MB, built in 37 seconds
```

**Comment by fxcoudert** [comment]
I don't know, the Sierra bottle works for me… maybe transient network issue?

**Pull request closed without merging**
