### PR TITLE
llvm 9.0

### PR DESCRIPTION
**Pull request by Noctem**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by equal-l2** [comment]
```
Error: 2 problems in 1 formula detected
llvm:
  * Formula has other versions so create a versioned alias:
      cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases
      ln -s ../Formula/llvm.rb llvm@9
  * Formula has invalid versioned aliases:
      llvm@8
```

**Review by fxcoudert — CHANGES_REQUESTED** [review]
- Based on usage statistics and our rules for versioned formulas, we should remove `llvm@3.9` and `llvm@5` (one commit per deleted formula, with commit message `llvm@5: delete`).
- Make the `swig` dependency unconditional (i.e. remove `if MacOS.version >= :lion`)
- Existing changes should be split into two commits:
  1. One commit that contains the changes to `llvm.rb` and the alias rename. Commit message should be `llvm 9.0.0`.
  2. One commit that contains the new `llvm@8` formula, with commit message `llvm@8 8.0.1 (new formula)`

**Review by fxcoudert — APPROVED** [review]

**Review by chenrui333 — APPROVED** [review]
👍

**Comment by fxcoudert** [comment]
Thank you @Noctem for your contribution to Homebrew!

**Comment by alexchandel** [comment]
The absence of LLD, or any option to build it, or any cask to acquire it now, still underscores how enduringly foolish #31510 was.

**Comment by soonho-tri** [comment]
> The absence of LLD

There is `/usr/local/opt/llvm/bin/lld`. What do we miss?

**Pull request closed without merging**
