### PR TITLE
ffmpeg: replace gnutls with openssl

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
Just noting that `gnutls` is still indirectly part of dependency tree due to `ffmpeg -> librist -> libmicrohttpd -> gnutls`.

**Comment by Bo98** [comment]
> Just noting that `gnutls` is still indirectly part of dependency tree due to `ffmpeg -> librist -> libmicrohttpd -> gnutls`.

`librist` is bit of a mess it looks like given it _also_ depends on `mbedtls`! Might need to investigate whether some of those optional dependencies are worth it.

**Comment by cho-m** [comment]
> `librist` is bit of a mess it looks like given it _also_ depends on `mbedtls`! 

Looks like `librist` defaults to `mbedtls` and other option is `gnutls`. It uses `libmicrohttpd` for prometheus metrics support. `libmicrohttpd` only has `gnutls` option for HTTPS support.

In case of modifying `ffmpeg`'s `librist` dependency, this has same consideration as `gnutls` where a user added `librist` support (https://github.com/Homebrew/homebrew-core/pull/88821) so any removal may need to be evaluated across our user base. This makes removing features difficult as we can't get analytics into feature usage.

**Comment by carlocab** [comment]
It would be good to understand feature-parity too. Most other package managers use GnuTLS with FFmpeg, but that's presumably largely because of GPL-related concerns. GPL is no longer a concern with OpenSSL 3, but it still seems to me that FFmpeg is still more thoroughly tested with FFmpeg than it is with OpenSSL.

**Comment by carlocab** [comment]
> Looks like `librist` defaults to `mbedtls` and other option is `gnutls`. It uses `libmicrohttpd` for prometheus metrics support. `libmicrohttpd` only has `gnutls` option for HTTPS support.

We could switch `librist` to using only `gnutls`, but everyone else still seems to link it to `mbedtls`.

**Comment by Bo98** [comment]
> > Looks like `librist` defaults to `mbedtls` and other option is `gnutls`. It uses `libmicrohttpd` for prometheus metrics support. `libmicrohttpd` only has `gnutls` option for HTTPS support.
> 
> We could switch `librist` to using only `gnutls`, but everyone else still seems to link it to `mbedtls`.

Only Debian actually links libmicrohttpd, and they have a separate `rist-tools` subpackage for it. Gentoo explicitly disable tools to avoid opportunistic libmicrohttpd usage.

**Pull request closed without merging**
