### PR TITLE
libdap 3.18.1

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by ilovezfs** [comment]
@nijikon I think this one doesn't need Autotools for non-HEAD anymore.

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/legacy-homebrew/pull/50631 for the prior version sans Autotools.

**Comment by nijikon** [comment]
@ilovezfs fixed 🚄

**Comment by ilovezfs** [comment]
:+1:

**Pull request closed without merging**
