### PR TITLE
fmt 9.0.0

### PR DESCRIPTION
**Pull request by owine**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by carlocab** [comment]
```
Error: 33 failed steps!
brew linkage --test bear
brew test --retry --verbose bear
brew linkage --test cherrytree
brew test --retry --verbose cherrytree
brew linkage --test clip
brew test --retry --verbose clip
brew linkage --test easyrpg-player
brew test --retry --verbose easyrpg-player
brew linkage --test fb303
brew test --retry --verbose fb303
brew linkage --test fbthrift
brew test --retry --verbose fbthrift
brew linkage --test fizz
brew test --retry --verbose fizz
brew linkage --test folly
brew test --retry --verbose folly
brew linkage --test gnuradio
brew test --retry --verbose gnuradio
brew linkage --test mkvtoolnix
brew test --retry --verbose mkvtoolnix
brew linkage --test mpd
brew test --retry --verbose mpd
brew linkage --test poac
brew test --retry --verbose poac
brew test --retry --verbose sophus
brew linkage --test spdlog
brew linkage --test vcpkg
brew test --retry --verbose vcpkg
brew linkage --test vowpal-wabbit
brew test --retry --verbose vowpal-wabbit
brew linkage --test wangle
brew linkage --test watchman
brew test --retry --verbose watchman
```

Let's start by rev bumping the `linkage` failures:
```
bear
cherrytree
clip
easyrpg-player
fb303
fbthrift
fizz
folly
gnuradio
mkvtoolnix
mpd
poac
spdlog
vcpkg
vowpal-wabbit
wangle
watchman
```

**Comment by owine** [comment]
`bear` needs an upstream fix

https://github.com/rizsotto/Bear/issues/471

**Comment by carlocab** [comment]
Upstream issue for `vcpkg`: https://github.com/microsoft/vcpkg/issues/25673

**Comment by carlocab** [comment]
`vowpal-wabbit` fixed in https://github.com/VowpalWabbit/vowpal_wabbit/pull/4059

**Comment by owine** [comment]
#106462 for `bear` with fix merged
#106463 for `vcpkg` but does not appear to have the fix merged

**Comment by carlocab** [comment]
Tried to apply the patch from https://github.com/gnuradio/gnuradio/pull/5935, but it failed, unfortunately.

**Comment by cho-m** [comment]
`gnuradio` now has open PR https://github.com/gnuradio/gnuradio/pull/6053

**Comment by carlocab** [comment]
I will probably cherry-pick #108112 onto here to save on rebuilds. I just need to test my `fbthrift` patch first.

**Comment by carlocab** [comment]
`mpd` might fail again with
```
  Undefined symbols for architecture arm64:
    "av_free(void*)", referenced from:
        AvioStream::~AvioStream() in libdecoder_plugins.a(FfmpegIo.cxx.o)
    "av_malloc(unsigned long)", referenced from:
        AvioStream::Open() in libdecoder_plugins.a(FfmpegIo.cxx.o)
```
https://github.com/Homebrew/homebrew-core/runs/7852851807?check_suite_focus=true#step:6:1515

**Comment by carlocab** [comment]
Actually, maybe that's the issue: it should be looking for `_av_free` and `_av_malloc`, **not** `av_free(void*)` and `av_malloc(unsigned long)`.

Maybe an `extern C` missing somewhere? Not sure why this didn't come up before, though.

**Comment by carlocab** [comment]
Ah. That's exactly the problem:

https://github.com/MusicPlayerDaemon/MPD/issues/1582
https://github.com/MusicPlayerDaemon/MPD/commit/59792cb0b801854ee41be72d33db9542735df754

**Review by carlocab — DISMISSED** [review]

**Review by carlocab — DISMISSED** [review]
Forgot to remove the revision bumps when cherry-picking the FB formulae.

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
All bottles built on Linux except for Watchman, which got killed by the timeout. I'll trigger that separately, since this has waited long enough.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
