### PR TITLE
libpng 1.6.24

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by DomT4** [comment]
@MikeMcQuaid Gentle nudge that you forgot to mirror this one. Done now.

**Comment by MikeMcQuaid** [comment]
@DomT4 oops, cheers. An audit or something would be 🆒.

**Comment by DomT4** [comment]
Checking `mirror`s aren't 404s generally is on my list. I'll try and squeak in a PR tonight if I can get the PR I've been working on (and frequently exasperated by) for the last couple days actually pushed for review this evening.

**Comment by MikeMcQuaid** [comment]
> Checking mirrors aren't 404s generally is on my list. I'll try and squeak in a PR tonight if I can get the PR I've been working on (and frequently exasperated by) for the last couple days actually pushed for review this evening.

@DomT4 👍. Would be enough to check that a `HEAD` isn't a 404, I think.

**Pull request closed without merging**
