### PR TITLE
alot 0.8.1

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by fxcoudert** [comment]
Let's move this formula to Python 3, it is apparently compatible: https://github.com/pazz/alot/blob/0.8.1/setup.py#L26

**Comment by chenrui333** [comment]
Sounds good, doing this now.

**Comment by chenrui333** [comment]
I will take a look at it tomorrow.

**Comment by chenrui333** [comment]
notmuch is the dependent formula.

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
```
19:09:32     writing manifest file 'pip-egg-info/alot.egg-info/SOURCES.txt'
19:09:32   Source in /private/tmp/pip-req-build-QQLOHp has version 0.8.1, which satisfies requirement alot==0.8.1 from file:///private/tmp/alot-20190529-15838-mxcwim/alot-0.8.1
19:09:32   Removed alot==0.8.1 from file:///private/tmp/alot-20190529-15838-mxcwim/alot-0.8.1 from build tracker '/private/tmp/pip-req-tracker-7tufWD'
19:09:32 Cleaning up...
19:09:32   Removing source in /private/tmp/pip-req-build-QQLOHp
19:09:32 Removed build tracker '/private/tmp/pip-req-tracker-7tufWD'
19:09:32 ERROR: alot requires Python '>=3.5' but the running Python is 2.7.16
19:09:32 Exception information:
19:09:32 Traceback (most recent call last):
19:09:32   File "/usr/local/Cellar/alot/0.8.1/libexec/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
19:09:32     status = self.run(options, args)
19:09:32   File "/usr/local/Cellar/alot/0.8.1/libexec/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 352, in run
19:09:32     resolver.resolve(requirement_set)
19:09:32   File "/usr/local/Cellar/alot/0.8.1/libexec/lib/python2.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
19:09:32     self._resolve_one(requirement_set, req)
19:09:32   File "/usr/local/Cellar/alot/0.8.1/libexec/lib/python2.7/site-packages/pip/_internal/resolve.py", line 299, in _resolve_one
19:09:32     check_dist_requires_python(dist)
19:09:32   File "/usr/local/Cellar/alot/0.8.1/libexec/lib/python2.7/site-packages/pip/_internal/utils/packaging.py", line 69, in check_dist_requires_python
19:09:32     '.'.join(map(str, sys.version_info[:3])),)
19:09:32 UnsupportedPythonVersion: alot requires Python '>=3.5' but the running Python is 2.7.16
19:09:32 
19:09:32 ==> Formula
19:09:32 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/alot.rb
```

**Comment by Moisan** [comment]
Superseded by #41159.

**Pull request closed without merging**
