### PR TITLE
ortp 5.2.23

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by p-linnane** [comment]
The only difference between this release and the last one is [this commit](https://gitlab.linphone.org/BC/public/ortp/-/commit/0ff695106cf59c258066308103d68809f1978554). This changed `-Wno-unused-parameter` to `-Wunused-parameter`, which is causing the build failure.

**Comment by danielnachun** [comment]
Let's try adding
```
cflags << "-Wno-error=unused-parameter" if OS.linux?
```
as the failure is from non-critical warning.

**Comment by SMillerDev** [comment]
```
  /tmp/ortp--bctoolbox-20230216-5833-6k5sjp/bctoolbox-5.2.22/src/crypto/mbedtls.c: In function ‘bctbx_ssl_set_mtu’:
  /tmp/ortp--bctoolbox-20230216-5833-6k5sjp/bctoolbox-5.2.22/src/crypto/mbedtls.c:1050:45: error: unused parameter ‘ssl_ctx’ [-Werror=unused-parameter]
   1050 | void bctbx_ssl_set_mtu(bctbx_ssl_context_t *ssl_ctx, uint16_t mtu) { }
        |                        ~~~~~~~~~~~~~~~~~~~~~^~~~~~~
```

**Comment by p-linnane** [comment]
@danielnachun Can you provide some additional guidance here? It looks like the resource needs `-Wno-error=unused-parameter` and `ortp` itself needs `-Wno-error=maybe-uninitialized`.

**Comment by danielnachun** [comment]
> @danielnachun Can you provide some additional guidance here? It looks like the resource needs `-Wno-error=unused-parameter` and `ortp` itself needs `-Wno-error=maybe-uninitialized`.

You are right, it should be for the resource.  I will test a local build of this now and push a fix if it works.

**Review by danielnachun — APPROVED** [review]
This is fixed now.

**Comment by p-linnane** [comment]
Thank you @danielnachun!

**Pull request closed without merging**
