### PR TITLE
getmail 5.16

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
`inreplace` needs updating.

**Comment by alebcay** [comment]
Looks like starting in this release, all of the shebangs have been converted from `#!/usr/bin/env python` to `#!/usr/bin/env python2`.

We could detect and replace all these shebangs (preferably with shebangs to a brewed Python, so that we can package on Linux as well). Of course, there's no guarantee at all that this will actually work (there's probably some good reason upstream decided to change all the shebangs to explicitly specify `python2` instead of just `python`).

Not sure how we should proceed here.

**Comment by carlocab** [comment]
Isn't `/usr/bin/python` Python2?

**Comment by SMillerDev** [comment]
It is for me on Monterey so I don't expect anything else on earlier OSes

**Comment by alebcay** [comment]
Yes, I misspoke. Edited earlier comment. So I could update the shebang replacement but of course CI will still fail on Linux since there's no Python 2 there. If that's fine (continue bottling/supporting only macOS on this one), we can move in that direction.

**Comment by SMillerDev** [comment]
With 32 installs in 30 days, I would say we at least deprecate it if we allow it to use the macOS system Py2

**Pull request closed without merging**
