### PR TITLE
waffle 1.6.1 (new formula)

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by yurikoles** [comment]
The patch is from my [upstream MR].(https://gitlab.freedesktop.org/mesa/waffle/-/merge_requests/72)

Fails to build examples, upstream [ticket](
https://gitlab.freedesktop.org/mesa/waffle/-/issues/57).
```
I/O error : I/O Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
```
Does sandbox forbids networking? Or this may because it tries to write some path outside of sandbox?

**Comment by SMillerDev** [comment]
Networking should be fine, writing outside is not.

**Comment by Bo98** [comment]
You likely need `depends_on "docbook-xsl" => :build"`

You may potentially also need `ENV["XML_CATALOG_FILES"] = etc/"xml/catalog"`.

**Comment by yurikoles** [comment]
Thanks, @Bo98, fixed.

**Comment by yurikoles** [comment]
Any news? [My MR](https://gitlab.freedesktop.org/mesa/waffle/-/merge_requests/72) will be merged soon.

**Comment by SMillerDev** [comment]
We need a release with the patch. New formulae should build without patches.

**Comment by yurikoles** [comment]
Fix was merged and was added to 1.6.2 milestone.

**Comment by chenrui333** [comment]
Added a comment to the patch and rebased to the latest master.

**Comment by SMillerDev** [comment]
We should wait for the next release and add the software without a need for the patch.

**Comment by chenrui333** [comment]
Mark PR with upstream issue while we are waiting for the new release.

**Comment by chenrui333** [comment]
Superseded by #71275

**Pull request closed without merging**
