### PR TITLE
condure 1.0.1 (new formula)

### PR DESCRIPTION
**Pull request by jkarneges**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jkarneges** [comment]
CI is giving the error "not notable enough". However, I hope an exception can be made. `condure` is an optional runtime dependency of `pushpin` (as of 1.30.0), and `pushpin` is in Homebrew.

**Comment by SMillerDev** [comment]
If it's optional I don't think we should make an exception.

**Comment by jkarneges** [comment]
Our plan is to eventually make it a required dependency. However, in the meantime it would be nice if it were easier for users to try it out rather than installing outside of Homebrew.

**Comment by SMillerDev** [comment]
You can provide it in a tap until it's notable enough.

**Pull request closed without merging**
