### PR TITLE
dolt 0.51.1

### PR DESCRIPTION
**Pull request by coffeegoddd**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by abitrolly** [comment]
@coffeegoddd these are not getting released. Why opening new PRs?

**Comment by chenrui333** [comment]
> @coffeegoddd these are not getting released. Why opening new PRs?

looks like it got released now?

**Review by chenrui333 — APPROVED** [review]

**Comment by abitrolly** [comment]
@chenrui333 nope. Still not doesn't not updated.
```
$ brew info dolt   
==> dolt: stable 0.41.4 (bottled)
```

**Comment by abitrolly** [comment]
@chenrui333 oh, well. Nevermind. My taps were on a different branch. Not sure why they were getting updates at all. Maybe I was rebasing for a patch. Anyway fixed now. Thanks for responding.
```
~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/core) checkout master                                                                                                              /5,5s
➜  ~ 
➜  ~ git -C $(brew --repo homebrew/core) checkout master
Switched to branch 'master'                                                                                                                                        /1,7s
➜  ~ brew doctor                                        
Your system is ready to brew.                                                                                                                                      /3,3s
➜  ~ brew update
Already up-to-date.                                                                                                                                                /1,0s
➜  ~ brew upgrade
==> Upgrading 25 outdated packages:
...
dolt 0.41.4 -> 0.51.1
```

**Pull request closed without merging**
