### PR TITLE
sqlpage 0.8.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by branchvincent** [comment]
Their release failed: https://github.com/lovasoa/SQLpage/actions/runs/5569953772/jobs/10173666747

**Comment by lovasoa** [comment]
For some reason, Github had decided to run the action with an old outdated version of the windows runner image:

image


I relaunched it and it works

**Comment by lovasoa** [comment]
The new gh action run finished successfully: https://github.com/lovasoa/SQLpage/releases/tag/v0.8.0

**Comment by chenrui333** [comment]
Thanks @lovasoa!

**Review by branchv — APPROVED** [review]

**Pull request merged**
