### PR TITLE
libwebsockets 3.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
CMake Error at CMakeLists.txt:488 (message):
  Sorry libev and libevent conflict with each others' namespace, you can only
  have one or the other
```

**Comment by ilovezfs** [comment]
Blocked on https://github.com/Homebrew/homebrew-core/pull/27504

**Comment by tsl0922** [comment]
ttyd is not ready for libwebsockets 3.0.0 too (https://github.com/tsl0922/ttyd/issues/86), as it has some breaking api changes.

**Comment by ilovezfs** [comment]
Thanks for the heads up @tsl0922!

**Pull request closed without merging**
