### PR TITLE
ghc-8.10.1

### PR DESCRIPTION
**Pull request by lukel97**
Extending https://github.com/Homebrew/homebrew-core/pull/52093 @fishtreesugar

### CODE REVIEW

**Comment by fishtreesugar** [comment]
Thanks!

**Comment by bubba** [comment]
I think we'll need to make a whitelist exception for ghc@8.8 here https://github.com/Homebrew/brew/blob/72f7ef3d02dce3eb9056493044fcc530d7a83d3f/Library/Homebrew/rubocops/urls.rb#L24-L44

**Comment by bubba** [comment]
Should the CI be taking this long?

**Comment by Bo98** [comment]
GHC pull requests usually take 16-19 hours to build the two GHC formulae and go through and test building every GHC dependent (49 formulae).

**Comment by bubba** [comment]
Holy smokes. Is there a way to run this on my machine? I’m not able to see the logs from GitHub Actions and I’m sure there’s bound to be some failures

**Comment by Bo98** [comment]
> Is there a way to run it locally?

If you have a lot of time to spare, I guess you can do `brew install -s ghc ghc@8.8 $(brew uses --recursive --include-build ghc)` but you might as well wait on the CI.

> I’m not able to see the logs from GitHub Actions

Logs can be seen when the CI run is complete.

**Comment by bubba** [comment]
@Bo98 I've wrangled down most of the failures. Two of the failures are auditing failures, from cmt and mighttpd2.
Cmt's failure is that it's using a pre-release release on GitHub, but it's been using same version since the formula was initially added in January. mighttpd2 is failing because the website is unreachable ([I've pinged the author](https://github.com/kazu-yamamoto/mighttpd/issues/1)).
I'm not sure if I'll be able to fix either of these within this PR, will it still be possible to merge this?

**Comment by bubba** [comment]
I think the cmt auditing failure should be the only one left now, ready for review

**Comment by bayandin** [comment]
A patch for `furmark` doesn't apply:
```
==> Downloading https://github.com/diku-dk/futhark/commit/b862de37f1e2cd7e7b561b723d01da9c8d248881.diff?full_index=1
cp -p /Users/brew/Library/Caches/Homebrew/downloads/cee2bef6ac248d41bfa19eb8ef82dafb906efcd6a2bbc29d40425920013a89ae--b862de37f1e2cd7e7b561b723d01da9c8d248881.diff /private/tmp/futhark--patch-20200505-11593-1yz0nx5/b862de37f1e2cd7e7b561b723d01da9c8d248881.diff
Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/cee2bef6ac248d41bfa19eb8ef82dafb906efcd6a2bbc29d40425920013a89ae--b862de37f1e2cd7e7b561b723d01da9c8d248881.diff
==> Verifying cee2bef6ac248d41bfa19eb8ef82dafb906efcd6a2bbc29d40425920013a89ae--b862de37f1e2cd7e7b561b723d01da9c8d248881.diff checksum
==> Patching
==> Applying b862de37f1e2cd7e7b561b723d01da9c8d248881.diff
patch -g 0 -f -p1 -i /private/tmp/futhark--patch-20200505-11593-1yz0nx5/b862de37f1e2cd7e7b561b723d01da9c8d248881.diff
patching file src/Futhark/Pass/ExtractKernels/Interchange.hs
Hunk #1 FAILED at 102.
1 out of 1 hunk FAILED -- saving rejects to file src/Futhark/Pass/ExtractKernels/Interchange.hs.rej
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/futhark--patch-20200505-11593-1yz0nx5/b862de37f1e2cd7e7b561b723d01da9c8d248881.diff` exited with 1.
```

**Comment by bubba** [comment]
@bayandin looks like futhark was updated on master to a version that includes the patch

**Comment by bayandin** [comment]
Looks good now.
There're only audit complains
```
brew audit --skip-style cmt --online
brew audit --skip-style mighttpd2 --online
```

**Comment by bubba** [comment]
@bayandin Yeah, and I think these are out of our control unfortunately (or at least, out of scope for ghc)

**Comment by SMillerDev** [comment]
Yeah, both are pre-existing issues. I say it's good to go!

**Comment by bayandin** [comment]
I'm merging it manually since it required to rearrange commits a bit.

Well done @bubba! Thanks a lot for your contribution 🎉

**Comment by bayandin** [comment]
It took about 5 hours just to upload all the bottles!
But everything is merged finally.

Thanks again @fishtreesugar, @bubba, and @Bo98!

**Pull request closed without merging**
