### PR TITLE
postgresql@9.4 9.4.16

### PR DESCRIPTION
**Pull request by commitay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by commitay** [comment]
fails on el cap, sierra 
```
configure: error: readline library not found
```

**Comment by apjanke** [comment]
Funny; I can reproduce this failure locally on Sierra from the version in `master`, *before* your PR.

```
$ brew install -s postgresql@9.4
==> Downloading https://ftp.postgresql.org/pub/source/v9.4.15/postgresql-9.4.15.tar.bz2
Already downloaded: /Users/janke/Library/Caches/Homebrew/postgresql@9.4-9.4.15.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/postgresql@9.4/9.4.15 --datadir=/usr/local/Cellar/postgresql@9.4/9.4.15/share/postgresql@9.4 --docdir=/usr/lo
Last 15 lines from /Users/janke/Library/Logs/Homebrew/postgresql@9.4/01.configure:
checking for library containing socket... no
checking for library containing shl_load... no
checking for library containing getopt_long... no
checking for library containing crypt... no
checking for library containing shm_open... no
checking for library containing shm_unlink... no
checking for library containing fdatasync... no
checking for library containing sched_yield... no
checking for library containing gethostbyname_r... no
checking for library containing shmget... no
checking for library containing readline... no
configure: error: readline library not found
If you have readline already installed, see config.log for details on the
failure.  It is possible the compiler isn't looking in the proper directory.
Use --without-readline to disable readline support.

READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
postgresql@9.4 9.4.16 https://github.com/Homebrew/homebrew-core/pull/23911
[✘ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on ⇄ master]
$
```

Same error with your PR change. I have a bunch of formulae installed on my machine, so maybe it's something to do with prior installation leftover state.

brew gist-logs, from my attempt to install from master: https://gist.github.com/f5e78cd5d70da1c92bc6876f1e955936

Breaks under Xcode 9.1 for me, too.

**Comment by commitay** [comment]
I can't reproduce any issues with the current formula either.

Using a clean sierra VM (CLT only).

**Comment by gma** [comment]
I'm getting this while trying to run `brew upgrade postgresql@9.4`.

I'm trying to upgrade it because of this:

```
% psql
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /usr/local/bin/psql
  Reason: image not found
Abort trap: 6
```

`libreadline.7.dylib` exists, and I was hoping upgrading Postgres would rebuild it, pointing it at v7, rather than v6. Is there anything you'd like me to try to help folk reproduce it, or ideas you'd like me to test?

**Pull request closed without merging**
