### PR TITLE
Go 1.13

### PR DESCRIPTION
**Pull request by leonklingele**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by laverya** [comment]
Well that's unfortunate
(The CI test failure)
```
...
time="2019-09-03T21:21:07+01:00" level=info msg="Created deploy/crds/app_v1alpha1_appservice_cr.yaml"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18e89e5]

goroutine 1 [running]:
k8s.io/gengo/parser.(*Builder).AddDirRecursive(0xc000022640, 0xc0000d51d0, 0x2c, 0x2, 0x2)
	pkg/mod/k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a/parser/parse.go:229 +0xb5
sigs.k8s.io/controller-tools/pkg/crd/generator.(*Generator).Do(0xc0006a5760, 0x0, 0x0)
	pkg/mod/sigs.k8s.io/controller-tools@v0.0.0-20190411181648-9d55346c2bde/pkg/crd/generator/generator.go:126 +0x3ac
github.com/operator-framework/operator-sdk/internal/pkg/scaffold.(*CRD).CustomRender(0xc000319e40, 0x2d14c00, 0x4024ca0, 0x73fc5f0, 0xc000319e40, 0x1)
	src/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/crd.go:102 +0x27e
github.com/operator-framework/operator-sdk/internal/pkg/scaffold.(*Scaffold).doRender(0xc0006a5cf8, 0xc0000d5140, 0x2c, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00028e720, 0x23, ...)
	src/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/scaffold.go:222 +0x16c
github.com/operator-framework/operator-sdk/internal/pkg/scaffold.(*Scaffold).doFile(0xc0006a5cf8, 0x2c9a520, 0xc000319e40, 0x0, 0x0)
	src/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/scaffold.go:192 +0x230
github.com/operator-framework/operator-sdk/internal/pkg/scaffold.(*Scaffold).Execute(0xc0006a5cf8, 0xc0006a5c68, 0xc0006a5c98, 0x6, 0x6, 0x0, 0x0)
	src/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/scaffold.go:157 +0x103
github.com/operator-framework/operator-sdk/cmd/operator-sdk/add.apiRun(0xc000442780, 0xc00027d6c0, 0x0, 0x2, 0x0, 0x0)
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/add/api.go:118 +0x542
github.com/spf13/cobra.(*Command).execute(0xc000442780, 0xc00027d680, 0x2, 0x2, 0xc000442780, 0xc00027d680)
	pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000442280, 0x2c9da20, 0xc00037e600, 0x0)
	pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	src/github.com/operator-framework/operator-sdk/cmd/operator-sdk/main.go:85 +0x50f
...
```

**Comment by theckman** [comment]
I did some digging on this. It looks like this issue is tracked in three GitHub issues on `operator-sdk`.

There is [#1853](https://github.com/operator-framework/operator-sdk/issues/1853) which was created and closed as a duplicate of [#1759](https://github.com/operator-framework/operator-sdk/issues/1759). On [#1759](https://github.com/operator-framework/operator-sdk/issues/1759) I found a mention that it should be fixed in https://github.com/operator-framework/operator-sdk/commit/abac23c897b898e6fecfb2c02fe318843ae9347f and a reference to [#1854 (comment)](https://github.com/operator-framework/operator-sdk/issues/1854#issuecomment-525132306) which explains it in more depth.

If I'm understanding this correctly, either need to

A. Set the `GOROOT`.
B. Push `operator-sdk` to release a new version with these fixes in it.

or

C. Both!

I hope this helps!

**Comment by PureWhiteWu** [comment]
Hi, is there still any problem? Quite looking forward to use go 1.13 now.

**Comment by theckman** [comment]
@PureWhiteWu you can always use `gimme` to get Go: https://github.com/travis-ci/gimme

**Comment by PureWhiteWu** [comment]
> @PureWhiteWu you can always use `gimme` to get Go: https://github.com/travis-ci/gimme

Thanks very much, but I'm used to `brew upgrade`😜

**Comment by SMillerDev** [comment]
>Hi, is there still any problem? Quite looking forward to use go 1.13 now.

@PureWhiteWu maintainer time is a problem. This pull request was opened only 11 hours ago. Someone will review and eventually merge it when they have time. If you don't think that's fast enough you could always make your own tap or help homebrew and at some point after offer to become a maintainer yourself.

**Comment by PureWhiteWu** [comment]
> > Hi, is there still any problem? Quite looking forward to use go 1.13 now.
> 
> @PureWhiteWu maintainer time is a problem. This pull request was opened only 11 hours ago. Someone will review and eventually merge it when they have time. If you don't think that's fast enough you could always make your own tap or help homebrew and at some point after offer to become a maintainer yourself.

I know, I was just asking if there's still any problem I may help to solve. I've already installed go 1.13 through `brew edit go` locally and just want it to be officially supported.

**Comment by leonklingele** [comment]
@theckman thanks for looking into this. I've updated the `operator-sdk` formula accordingly.
CI is green now.

**Comment by SMillerDev** [comment]
Thanks @leonklingele!

**Comment by jonchang** [comment]
Having trouble with bottles; rebased and force pushed.

**Comment by leaxoy** [comment]
CI passed, is time to merge this?

**Comment by fxcoudert** [comment]
Merging, thanks @leonklingele and everyone involved.

**Comment by barshow** [comment]
@jonchang @fxcoudert, seems like every time go is updated go@1.12 -> go@1.13 we loose the ability to install go@1.12, this has happened several times before, am I missing something?

**Comment by fxcoudert** [comment]
We have a PR for Go 1.12: https://github.com/Homebrew/homebrew-core/pull/43900

**Pull request closed without merging**
