### PR TITLE
wget: switch to OpenSSL 1.1.0

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alex** [comment]
@tdsmith as we discussed :-)

**Comment by ilovezfs** [comment]
What's the reason for this? I don't think this is a great idea because it means we won't be able to depend on wget for anything that uses openssl 1.0, which is the vast majority of openssl-using formulae.

**Comment by alex** [comment]
@ilovezfs `wget` does not expose a library, as far as I can tell, just a binary, so I don't think there's a linkage concern.

**Comment by ilovezfs** [comment]
There's an audit that prevents anything that depends on openssl 1.0 anywhere in its recursive dependency tree from also depending on openssl 1.1 anywhere in its recursive dependency tree.

**Comment by alex** [comment]
My reasoning is that I'm starting to review the programs I have, for which I'll want TLS 1.3 support, in preparation for OpenSSL adding support, and `wget` was on the list :-)

**Comment by alex** [comment]
(And indeed, Jenkins is unhappy on several packages which depend on `openssl`)

**Comment by ilovezfs** [comment]
Yup. Hence, closing for now until/unless we resume the openssl 1.1 migration.

**Comment by alex** [comment]
Ok. I don't know if this conversation is/was occuring anywhere besides #4543, but FWIW at this point Debian is largely migrated, so it may be time to resume that process.

**Comment by ilovezfs** [comment]
Debian's choices are their own.

**Comment by ilovezfs** [comment]
@alex if you want to make this change, the first step would be a PR adding an audit exemption for wget in https://github.com/Homebrew/brew.

**Comment by MikeMcQuaid** [comment]
I'm 👎 on adding an audit exemption for this because it seems silly to me for `brew install open-scene-graph` to install multiple versions of OpenSSL.

**Comment by ilovezfs** [comment]
@alex I guess you can skip that PR then ;)

**Comment by ilovezfs** [comment]
It looks like we can render `open-scene-graph` moot since the `wget` dependency is no longer needed: https://github.com/Homebrew/homebrew-core/pull/14012.

**Comment by alex** [comment]
Heh, I'm glad something useful came out of this.

**Comment by ilovezfs** [comment]
@alex with any luck you'll be able to re-open this shortly :)

**Comment by alex** [comment]
@ilovezfs probably not that quickly; `xplanetfx` (the other package which Jenkins was unhappy about) requires OpenSSL via Python, which I assume will be one the more challenging packages to migrate because of the vast number of things which depend on it.

**Comment by ilovezfs** [comment]
@alex https://github.com/Homebrew/homebrew-core/pull/14013

**Comment by ilovezfs** [comment]
To be extra safe, I think we need to kill the wget dependency in cherokee, gucharmap, libosinfo, and ntopng too. (Jenkins doesn't check `=> :build` but it could still cause the same problems, I think.)

**Comment by alex** [comment]
Hah, how'd you figure out that the dep was unused?

**Comment by ilovezfs** [comment]
By just trying to build without it!

**Comment by ilovezfs** [comment]
OK cherokee had a whole 11 installs in the last 30 days of which 0 were HEAD, which is where wget is, so I'll just remove that head spec.

**Comment by alex** [comment]
Since `wget` is something programs likely use by shelling out, is simply building without it sufficient?

**Comment by ilovezfs** [comment]
Until proven otherwise, yes.

**Comment by ilovezfs** [comment]
cherokee: https://github.com/Homebrew/homebrew-core/pull/14014

**Comment by ilovezfs** [comment]
libosinfo: https://github.com/Homebrew/homebrew-core/pull/14016

**Comment by ilovezfs** [comment]
@alex you should be safe to re-open this now.

**Comment by alex** [comment]
Cool, thanks!

Hmmm, I don't see the "restore branch" button I usually see after I delete a branch... really hoping I don't need to file a new PR...

**Comment by ilovezfs** [comment]
You can probably just push a branch with the same name to your fork.

**Comment by ilovezfs** [comment]
Oh it's competing with https://github.com/Homebrew/homebrew-core/pull/14015

**Comment by alex** [comment]
Oof. Nice debugging, that would not have occurred to me.

**Comment by DomT4** [comment]
> Debian's choices are their own.

It's probably also worth noting that a fair bit of Debian's migration involved moving things off of OpenSSL and onto GnuTLS, because then you can have GnuTLS & OpenSSL 1.1.x in the same tree without having potentially conflicting symbols. Debian kept a 1.0.2 for things that absolutely could not use 1.1.x or GnuTLS but I'm not sure how long they intend to sustain that.

I considered this kind of transition for Homebrew but I expected pushback given OpenSSL has pretty much always been the crypto library of choice on macOS _if_ you didn't or couldn't use the system's SecureTransport or CommonCrypto.

**Comment by alex** [comment]
That's interesting, I didn't realize the migration involved gnutls :-(

**Comment by DomT4** [comment]
I _believe_ so, but to be honest I lost track of the various threads of discussion/thought around the migration so I could be referencing an outdated source at this point. There was [so](https://www.mail-archive.com/tech@openbsd.org/msg36437.html) much [different](https://lists.debian.org/debian-devel/2016/11/msg00754.html) discussion & [so much](https://wiki.debian.org/OpenSSL-1.1) to track in terms of the transition, including a point where [curl was pushed to GnuTLS and then pushed back to OpenSSL 1.0.2](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844018#101).

At some point they jumped from it's nearly impossible to do to it's done. I'm still trying to piece together quite what happened & where from time to time 😓. Debian still have this list of [things](https://bugs.debian.org/cgi-bin/pkgreport.cgi?tag=openssl-1.1-trans;users=pkg-openssl-devel@lists.alioth.debian.org) that wouldn't build with 1.1.x, but again, unsure how current it has been kept.

**Comment by ilovezfs** [comment]
Any of [these](https://gist.github.com/ilovezfs/2158e097790a7c7907f0b5ff4245eed3) are probably safe to switch to 1.1 if they have compatibility.

**Comment by DomT4** [comment]
I know `openssh` doesn't at least, and I'd be mildly surprised if it ever did given some of the noises out of upstream. None of the `node`s have 1.1 support yet, although it's under consideration for the newest ones. I _think_ `john-jumbo` has support upstream but not in a release yet. `h2o` uses `libressl` upstream but has been merging in 1.1.x support recently & may now work fine. `openvpn` has been slowly adding support upstream but last time I checked they weren't quite there.

**Comment by alex** [comment]
@ilovezfs I don't appear to have permissions to reopen this :-)

**Comment by ilovezfs** [comment]
Magic! Behold the power!

**Review by MikeMcQuaid — APPROVED** [review]

**Review by ilovezfs — APPROVED** [review]
I've also bumped the revision.

**Comment by ilovezfs** [comment]
Lucky PR 14000! Thanks @alex 

:rocket: :closed_lock_with_key:

**Comment by alex** [comment]
Thank you, and everyone else who contributed to this! Working with homebrew is always an awesome experience!

**Pull request closed without merging**
