### PR TITLE
afflib 3.7.11

### PR DESCRIPTION
**Pull request by ilovezfs**
- fix inability to import pyaff.so by actually linking to libexpat and
  libcurl as required
- fix audit failure due to python module having explicit framework links
  by replacing -lpython with -undefined dynamic_lookup
- remove upstreamed patches
- use unbound "with-python" option unless we're on Snow Leopard or below
- use commas between arguments to `system` to avoid spawning a shell as
  prescribed by audit --strict
- use autoreconf -fiv not autoreconf -iv
- do not put spaces between dependency types

### CODE REVIEW

**Comment by ilovezfs** [comment]
Failure to link libexpat and libcurl reported here: https://github.com/sshock/AFFLIBv3/issues/17

**Comment by umireon** [comment]
PR created: sshock/AFFLIBv3#18

**Comment by ilovezfs** [comment]
@umireon I'm going to merge this, and then you can open a fresh PR applying your patch if you'd like.

**Comment by umireon** [comment]
@ilovezfs thanks 😄

**Comment by ilovezfs** [comment]
@umireon shipped!

**Comment by sshock** [comment]
PR merged: sshock/AFFLIBv3#18

Please try updating to afflib 3.7.13 now (should be able to remove "-L/usr/lib -lcurl -lexpat").

Note: Please do not use afflib 3.7.12; both 3.7.12 and 3.7.11 had incorrect versioning.

**Pull request closed without merging**
