### PR TITLE
Add curl formula with openssl 1.1.1

### PR DESCRIPTION
**Pull request by bolmaster2**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Thank you for the submission @bolmaster2 and welcome to the Homebrew community! (hej! =))
We are especially appreciative of first time submitters and will hope this will not be your last :heart: :rose: .

This change you are proposing is creative but will however take us down a rabbit hole and won't be manageable in the long term under the umbrella of this project. At one point in time I'm assuming we will move the default version of openssl to 1.1 but I'm not aware of any timeline for that project as I'm writing this. In the meantime I would be :-1: on adding this to the current repository.

An alternative would be to create your own [tap](https://docs.brew.sh/Taps) and put your own formulas there if you need to use it or check if someone else already has created what you need and use that.

**Comment by iMichka** [comment]
Agreeing with @javian here. If we start adding `openssl@1.1`, we need to add it almost everywhere. We can not mix two versions of `openssl` in the same dependency tree.

There are 415 formulae using `openssl`. The idea would be to replace everything and rebuild them one by one, and see what fails. Please do not open a pull request like that right now, as the build will probably run for more than 24 hours on our CI. We need to have a better picture of what is broken before we start trying to update.

I will close this pull request as this change will not be accepted as is. As you see, this is a bigger issue we will need to handle one day.

Is there any specific issue you where trying to solve with this change? Or was it just to try to update the dependency?

**Comment by bolmaster2** [comment]
Thanks for taking the time to explain, I understand it's problematic to update the default `openssl` to 1.1 because of all the dependencies. That's why I created this new formula for curl with `openssl@1.1` to keep it isolated. Even though I cheated with `nghttp2` and `libssh2` and added `openssl@1.1` directly to them. 

Yes, my use case is to make curl (with openssl) support tls 1.3. As support for tls 1.3 is not in openssl 1.0, this was my solution.

I'll create a tap for it then, thanks again!

**Comment by bolmaster2** [comment]
If someone wants to use `curl` with `openssl@1.1` right now I created a tap for it here: https://github.com/bolmaster2/homebrew-curl-openssl

Best case would of course be if the default openssl would be 1.1 as the maintainers say. And I think that should be happening soon as openssl 1.0.2 end of life is 31-Dec-2019.

**Comment by javian** [comment]
@bolmaster2 work has started on it as you see in the pull requests but as with most things it might be hard to tell when it will be completed.

**Comment by bolmaster2** [comment]
@javian Oh, I missed that. Sorry, I didn't mean to stress you. Let me know if I can help in any way. And keep up the great work, I love homebrew!

**Pull request closed without merging**
