### PR TITLE
vala 0.50.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@tschoonj, it looks like this is the latest stable release, but not LTS, let me know what is your take.

**Comment by jonchang** [comment]
Looks like `valabind` needs a resource bump.

**Comment by chenrui333** [comment]
yeah, that is right.

**Comment by tschoonj** [comment]
It is an LTS release, but I didn't upgrade to it before since `valabind` cannot handle the API changes. I opened an [issue](https://github.com/radare/valabind/issues/55) upstream, but no response yet. In fact the project seems to be mostly dead.

**Comment by chenrui333** [comment]
Got you. I will close this PR then.

**Comment by jonchang** [comment]
Should we disable valabind then?

**Comment by tschoonj** [comment]
I could certainly live with that.

**Comment by trufae** [comment]
Fixed in 1.7.2! https://github.com/radare/valabind/releases/tag/1.7.2

Thanks for the heads up! @tschoonj 

valabind is not dead. it just works and i dont have much time to spend on it, but ihave near plans to add support for V and improve the current backends.

**Comment by tschoonj** [comment]
Hi @trufae,

Many thanks for releasing the update! I have opened a PR (#63786) to bump the formula

**Comment by trufae** [comment]
Cool!

**Pull request closed without merging**
