### PR TITLE
Indentation style fixes

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by DomT4** [comment]
Is `; <<~EOS` being deprecated?

**Comment by ilovezfs** [comment]
>Is def blah; <<~EOS being deprecated?

Not necessarily, no. I'm just finding these two choices somewhat grim:
```
  def caveats; <<~EOS
    blah blah
    blah blah blah
    EOS
  end
```
or
```
  def caveats; <<~EOS
    blah blah
    blah blah blah
  EOS
  end
```

It no longer likes
```
  def caveats; <<~EOS
      blah blah
      blah blah blah
    EOS
  end
```

**Comment by DomT4** [comment]
```
  def caveats; <<~EOS
    blah blah
    blah blah blah
  EOS
  end
```
I can at least see the logic for that, in the sense that `EOS` is declared on the same line as `def` and consequently lines up with `def` being closed by `end`. Not that I have a strong objection to the changes you've made, to be honest.

**Comment by ilovezfs** [comment]
The
```
  EOS
  end
```
kind of hurts my eyes. When was the last time you saw `end` not preceded by something more indented?

**Comment by DomT4** [comment]
Yeah, I agree it's not completely ideal. We have been using that style fairly consistently, IIRC? There's plenty of [examples](https://github.com/Homebrew/homebrew-core/blob/30abddeed8f2b8d6e3d7b5ee313ddcd2c8ff1671/Formula/glassfish.rb#L19-L23) around.

I don't know. I agree there's not really a great option here. Maybe your existing changes are the best of a bad bunch.

**Comment by ilovezfs** [comment]
Merging as is for now. But just so it's recorded somewhere explicitly, this removed the semi-colon style thing on these:

abuse 
asciidoc
cc65
cdargs
docker-machine
elasticsearch
elasticsearch@2.4
fail2ban
jboss-as@5
ksh
logstash
mat
mecab-ipadic
mecab-jumandic
mecab-ko-dic
mecab-unidic-extended
mecab-unidic
minetest
minio
ooniprobe
openttd
pgbouncer
plod
solr
sshconfigfs
varnish
weechat

**Pull request merged**
