### PR TITLE
docker-credential-helper 0.7.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Continuing #111484

vet goals got removed in [this commit](https://github.com/docker/docker-credential-helpers/commit/9582eb666163c3678c6c1cc50d2280597bdd40b3)

### CODE REVIEW

**Comment by danielnachun** [comment]
The test failure now is because we are running without a display on Linux:
```
 Minitest::Assertion: Expected /Error\ from\ list\ function\ in\ secretservice_linux\.c/ to match "Cannot autolaunch D-Bus without X11 $DISPLAY\n".
```
We should probably skip that part of the test on Linux with a note indicating that we can reenable it if we ever have a way to test X applications in CI.

**Comment by cho-m** [comment]
> We should probably skip that part of the test on Linux with a note indicating that we can reenable it if we ever have a way to test X applications in CI.

We will have a way once #109215 is merged, but it does require installing a large dependency tree so would need to see how practical it is. There are a could examples in that PR of using `Xvfb` as fake display.

**Comment by danielnachun** [comment]
> > We should probably skip that part of the test on Linux with a note indicating that we can reenable it if we ever have a way to test X applications in CI.
> 
> We will have a way once #109215 is merged, but it does require installing a large dependency tree so would need to see how practical it is. There are a couple examples in that PR of using `Xvfb` as fake display.

I think we only need that tree for testing though, right?  If the user is running `docker-credential-helper` in a GUI, it will use whatever X server is available.

On a related note, can we invoke `docker-credential-secretservice` without using a GUI?  That would avoid the need for X in testing altogether.

**Comment by cho-m** [comment]
> I think we only need that tree for testing though, right? If the user is running `docker-credential-helper` in a GUI, it will use whatever X server is available.

Yes. More on the amount of overhead in CI if we end up installing/uninstall X11 dependencies. If it isn't too bad, we can add test dependency.
 
> On a related note, can we invoke `docker-credential-secretservice` without using a GUI? That would avoid the need for X in testing altogether.

Not sure. The X11 failure is happening when Glib tries to autolaunch a DBus https://gitlab.gnome.org/GNOME/glib/-/blob/2.74.0/gio/gdbusaddress.c#L1115

It may be possible to avoid autolaunch-ing DBus. I don't think our `dbus` even supports this as we build without X11 support.

**Comment by cho-m** [comment]
One option is to use `dbus-launch` to manually create D-Bus, but I think we need a backend like `gnome-keyring` to get a meaningful result.

e.g. w/o any backend:
```console
$ dbus-launch --exit-with-session docker-credential-secretservice list
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
```

e.g. using Ubuntu's `gnome-keyring` (I don't think we have an equivalent formula?)
```console
$ dbus-launch --exit-with-session docker-credential-secretservice list
{}
```

**Pull request closed without merging**
