### PR TITLE
ccheck 1.0.1 (new formula)

### PR DESCRIPTION
**Pull request by nerdlem**
Provide a formula to directly compile the ccheck tool for X.509
TLS certificate monitoring / review utility.

The formula compiles the upstream Go binary and dependencies as specified
via vendoring, in compliance with the automated audit as well as the advice
provided in the Formula Cookbook.

- [✔︎] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [✔︎] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [✔︎] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [✔︎] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [✔︎] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by LooTKinGz** [comment]
Repository

**Comment by nerdlem** [comment]
> Repository

I'm afraid I don't get it.

**Comment by SMillerDev** [comment]
> I'm afraid I don't get it.


Just spam, you can ignore it.

**Comment by chenrui333** [comment]
Thanks @nerdlem for your contribution!

**Comment by nerdlem** [comment]
My pleasure

**Comment by cixtor** [comment]
> _GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)_

Can one of the Homebrew maintainers explain what was the criteria to accept this formula? I have wanted to add some of my programs to Homebrew for a while but none of my repositories have the number of forks, watchers or stars to be accepted here. I am surprised [ccheck](https://github.com/nerdlem/ccheck) was accepted considering it has even less notoriety than, for example, [slackapi](https://github.com/cixtor/slackapi).

**Comment by chenrui333** [comment]
> Can one of the Homebrew maintainers explain what was the criteria to accept this formula? I have wanted to add some of my programs to Homebrew for a while but none of my repositories have the number of forks, watchers or stars to be accepted here. I am surprised ccheck was accepted considering it has even less notoriety than, for example, slackapi.

Sorry about your confusion, I did not do well with checking on the repo stats before I merged the PR (if you ask me again, I probably will encourage @nerdlem to do their personal tap).  
I just personally feel that is useful for my own work.

With that being said, the formula acceptance could be YMMV.

Thanks for your understanding, and let me know if you need any help with setting up your personal tap.

**Comment by cixtor** [comment]
Thank you for explaining. I already have my personal tap setup but I appreciate your offer.

I also find `ccheck` useful and also installed it just a couple of minutes ago when I saw it was added to the library; although the name of the binary is confusing considering Mono SDK also installs a tool called `cccheck` _(note the additional “c”)_.

However, regardless of usefulness, I think it is unfair to merge this formula considering how many other interesting tools exist on GitHub with low notoriety. Merging the formula sets a bad precedent for the project [Homebrew].

Fortunately, I am not one of those [crazy people in social media who loudly complain about minor stuff](https://github.com/microsoft/vscode/issues/87268). Hopefully no one else will notice and this will remain as a simple lesson to do better reviews in the future. Thank you for taking care of the Homebrew repository and let’s hope _ccheck_ becomes more popular to justify keeping the formula in the core library.

**Comment by nerdlem** [comment]
On 20 Mar 2020, at 17:44, chenrui wrote:
> I just personally feel that is useful for my own work.

Much appreciated!

**Comment by nerdlem** [comment]
On 20 Mar 2020, at 17:58, Yorman wrote:

> However, regardless of usefulness, I think it is unfair to merge this 
> formula considering how many other interesting tools exist on GitHub 
> with low notoriety. Merging the formula sets a bad precedent for the 
> project [Homebrew].

Isn't this perhaps an opportunity to visit the criteria? Perhaps 
"notoriety" is not an ideal threshold that tools need to meet in order 
to be accepted. I would be glad to donate some time to go over this if 
this can help in some way.

Best regards

-lem

**Comment by chenrui333** [comment]
@cixtor Thanks a lot for your understanding, much appreciated your support. We will definitely revisit this after we scale up our infrastructure and automate the process as much as we can and then we can definitely incorporate more formula into homebrew-core.

@erdlem The maintainability and popularity are the biggest concerns for including the formula (that is why that github stats was set), but no hard rules though.

**Comment by chenrui333** [comment]
@cixtor, thanks for that github issue, that was fun read.

TBH, we do have some hatred comment recently in our repo too, https://github.com/Homebrew/homebrew-core/issues/51268 (we removed python2 because it is EOL)

**Pull request closed without merging**
