### PR TITLE
yarn 0.15.0 (new formula)

### PR DESCRIPTION
**Pull request by AdamEdgett**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by eppsilon** [comment]
Duplicate of https://github.com/Homebrew/homebrew-core/pull/5821 ?

**Comment by cmckni3** [comment]
@AdamEdgett Can you move the version line above the URL line? Ideally, I think you should remove the call to `#version`. File aren't always named the same way.

**Comment by AdamEdgett** [comment]
@eppsilon aw yep thanks. Searching for yarn didn't turn up that PR as it's titled "yarnpkg" 🙂
@cmckni3 Agreed, this was a product of me misinterpreting an audit warning about the version number having redundant data from the URL

Closing as dupe of #5821

**Comment by cmckni3** [comment]
Looks like #5821 also fixes the issue I was having with 0.15.1 not having the node packages preinstalled. Likely because a new release hasn't been made.

I ended up installing `yarn` using npm

**Pull request closed without merging**
