### PR TITLE
node 12.13.0

### PR DESCRIPTION
**Pull request by metowolf**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chrmoritz** [comment]
`npm` should be upgraded to 6.12.0 here too following whats in the official release.

**Comment by dustinfarris** [comment]
Thanks for this.  npm 6.12.0 fixes a regression where npm could not install git-based dependencies.

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by chrmoritz** [comment]
Shouldn't this be superseded by #45725 now?

**Comment by SMillerDev** [comment]
Yes. yes it should.

**Pull request closed without merging**
