### PR TITLE
opencv: migrate from homebrew/science

### PR DESCRIPTION
**Pull request by fxcoudert**
See https://github.com/Homebrew/homebrew-core/issues/15619

### CODE REVIEW

**Comment by fxcoudert** [comment]
Based on analytics, choices made are:

- `--without-test`, `--without-opencl` are removed
- `eigen` and `openexr` move from recommended to mandatory
- `opengl` and `ximea` are built in (no dependencies)
- `quicktime`, `universal` and `cuda` are dropped
- `gstreamer`, `openni`, and `vtk` are removed

`python`, `java`, `ffmpeg`, `jasper` and `tbb` have significant usage and stay as options.

**Comment by ilovezfs** [comment]
See comment here https://github.com/Homebrew/homebrew-core/pull/15903#issuecomment-317180370

**Comment by ilovezfs** [comment]
There are two issues that should be closed or resolved before this is merged as well:

- [ ] https://github.com/Homebrew/homebrew-science/pull/2714
- [ ] https://github.com/Homebrew/homebrew-science/issues/3268

**Comment by fxcoudert** [comment]
https://github.com/Homebrew/homebrew-science/pull/2714 is a CUDA issue, and CUDA is now gone

**Comment by blech** [comment]
If anyone else lands here looking for the previous opencv formula to make local edits to attempt to re-enable a feature deemed "insignificant", here's the last homebrew/science version:

https://github.com/Homebrew/homebrew-science/blob/c0155357293ae35f1beaa5a0d727e65b5edeaa0a/opencv.rb

**Pull request closed without merging**
