### PR TITLE
fix two homepages

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

<https://www.cloog.org/> has no content.
<https://www.xvid.org/> has a mismatched certificate (for `*.xvid.com`).

### CODE REVIEW

**Comment by ilovezfs** [comment]
Of course this will cause
```
iMac-TMP:~ joe$ brew audit --strict --online cloog
cloog:
  * The URL http://www.cloog.org/ could use HTTPS rather than HTTP
Error: 1 problem in 1 formula
```
so we'll either have to hard code an exception for this one or get upstream to fix it – preferably the latter.

**Comment by vszakats** [comment]
@ilovezfs Went with a third option and used the page under the domain also used as `url`.

**Comment by ilovezfs** [comment]
thanks! would be nice to report the empty content thing to them regardless :)

**Comment by zmwangx** [comment]
Just shot them an email: https://groups.google.com/forum/#!topic/cloog-development/tiXZg_DlnZ0

**Comment by ilovezfs** [comment]
Thanks Zhi

**Comment by fxcoudert** [comment]
Thanks @vszakats and @zmwangx for your contribution!

**Pull request closed without merging**
