### PR TITLE
pypy 5.7.0

### PR DESCRIPTION
**Pull request by chuanconggao**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chuanconggao** [comment]
The build console output says it is aborted by @ilovezfs. Any thing went wrong? Is it timeout?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@chuanconggao can you please squash your commits together into one commit? this will trigger the testbot again

**Comment by JCount** [comment]
@BrewTestBot test this please

**Comment by JCount** [comment]
@chuanconggao Thank you for your contribution to Homebrew! 🎊

**Pull request closed without merging**
