### PR TITLE
cromwell 0.19.3

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
Already downloaded: /Users/brew/Library/Caches/Homebrew/cromwell-0.19.3.jar
==> Verifying cromwell-0.19.3.jar checksum
Error: No such file or directory - cromwell-0.19.3.jar
```
Well isn't that just fascinating?

**Comment by DomT4** [comment]
Happening because the upstream `.jar` is still `0.19` but we've got logic in the formula pointing to `cromwell-#{version}.jar`. I guess upstream only versions the `.jar` by major release or something?

**Comment by ilovezfs** [comment]
Looks like it could be a mistake because they've never done a point release. I'll ask.

**Comment by ilovezfs** [comment]
@DomT4 strange, upstream hasn't responded.

Any feelings about the current fix?

**Comment by DomT4** [comment]
It's not an entirely pretty fix, but it seems reasonable enough as far as our options go.

**Pull request closed without merging**
