### PR TITLE
curl 7.86.0

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by derrabus** [comment]
Not sure what to do about the Ubuntu failure.

**Comment by SMillerDev** [comment]
@carlocab should a rebuild of curlcpp fix this?

>  lto1: fatal error: bytecode stream in file ‘/home/linuxbrew/.linuxbrew/Cellar/curlcpp/2.1/lib/libcurlcpp.a’ generated with LTO version 11.2 instead of the expected 11.3

**Comment by carlocab** [comment]
Yes, it should. But, in addition to a rebuild, we should either:
- disable building with LTO on Linux
- build a shared library only (i.e. no static library, especially on Linux)

**Comment by carlocab** [comment]
You can rebase this PR now.

**Review by carlocab — APPROVED** [review]

**Comment by derrabus** [comment]
Now we see failures on Ubuntu because `qt` cannot be installed from a bottle.

**Comment by carlocab** [comment]
> Now we see failures on Ubuntu because `qt` cannot be installed from a bottle.

That's only some of the failures. The others I've seen before.

**Pull request closed without merging**
