### PR TITLE
vnstat 2.8

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
<details>
<summary>license header ref</summary>

```
/*
vnStat daemon - Copyright (C) 2008-2021 Teemu Toivola <tst@iki.fi>

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; version 2 dated June, 1991.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License along
   with this program; if not, write to the Free Software Foundation, Inc.,
   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/
```


</details>

**Comment by cho-m** [comment]
For Linux build, we should modify inreplace to avoid `s.gsub! "\"eth0\"", "\"en0\"", false`

`en` is BSD name, so it is used on macOS.
However, on Linux `eth` is more likely correct.

**Comment by carlocab** [comment]
Ping @chenrui333

**Comment by chenrui333** [comment]
I will check on this tomorrow.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
