### PR TITLE
epinio: fix version output

### LINKED ISSUE #2182: Homebrew client version is missing `v` in version string
Using `epinio` installed by `brew` shows this error:

```
Epinio server version (v1.7.1) doesn't match the client version (1.7.1)
```

Details

```console
$ brew install epinio
[...]
==> Fetching epinio
==> Downloading https://ghcr.io/v2/homebrew/core/epinio/manifests/1.7.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/epinio/blobs/sha256:8d1474f7f9b47570521502580304b3f00cb6ea4b21d4a0683c3a52e
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:8d1474f7f9b47570521502580304b3f00cb6ea4
######################################################################## 100.0%
==> Pouring epinio--1.7.1.monterey.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/epinio/1.7.1: 8 files, 75.4MB
==> Running `brew cleanup epinio`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

$ epinio login -u admin 'https://epinio.127.0.0.1.sslip.io'
[...]
⚠️  Epinio server version (v1.7.1) doesn't match the client version (1.7.1)

⚠️  Update the client manually or run `epinio client-sync`

✔️  Login successful

$ epinio client-sync

⚠️  Epinio server version (v1.7.1) doesn't match the client version (1.7.1)

⚠️  Update the client manually or run `epinio client-sync`
Downloading file https://github.com/epinio/epinio/releases/download/v1.7.1/epinio-darwin-x86_64
[...]
✔️  Updated epinio client to v1.7.1
```

The client installed via `epinio client-sync` does have a matching version string.

### PR DESCRIPTION
**Pull request by enrichman**
Fix: https://github.com/epinio/epinio/issues/2182

We are missing the `v` prefix in the version output during the build. This wasn't catched because our tap is using the version tag (with the `v`), and the test in the formula was not going to check for the right value.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @enrichman!

**Comment by enrichman** [comment]
> Thanks @enrichman! 

Thanks to you! Very responsive as always. 💪

**Comment by enrichman** [comment]
@chenrui333 how does it work? Will it be available from the next version? Or the build is going to be ready also for the current one?

**Comment by chenrui333** [comment]
> @chenrui333 how does it work? Will it be available from the next version? Or the build is going to be ready also for the current one?

if already upgraded to the latest version, then a `brew reinstall epinio` is needed.

**Pull request merged**
