### PR TITLE
curlie 1.6.7

### PR DESCRIPTION
**Pull request by zuisong**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
some build issue

```
package github.com/rs/curlie
	imports golang.org/x/sys/windows: build constraints exclude all Go files in /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sys@v0.0.0-20191026070338-33540a1f6037/windows
```

**Comment by dawidd6** [comment]
This clearly classifies for an upstream issue.

**Comment by dawidd6** [comment]
Fixed in https://github.com/rs/curlie/releases/tag/v1.6.4

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request closed without merging**
