### PR TITLE
dotnet@6: switch to `openssl@3`

### PR DESCRIPTION
**Pull request by mchoo7**
See https://github.com/Homebrew/homebrew-core/issues/134251.

### CODE REVIEW

**Comment by fel1x-developer** [comment]
CI-long-timeout needed.

**Comment by fel1x-developer** [comment]
Related:
https://github.com/Homebrew/homebrew-core/pull/95339
https://github.com/dotnet/source-build/issues/2795

Maybe this PR solved this issue: https://github.com/dotnet/runtime/pull/84591

**Comment by carlocab** [comment]
This is also needed to resolve a versioned dependency conflict for `dafny`.

**Comment by osalbahr** [comment]
What's the "CI-long-timeout label"?

**Comment by SMillerDev** [comment]
> What's the "CI-long-timeout label"? It seems to be for CI tests that expectedly take a lot of time?

It's a label to use a longer timeout setting for the few formulae that need more than 90 minutes to build

**Comment by bunnyc1986** [comment]
what's the status on this PR? I'd like to bump the version to v6.0.412.
ref: https://github.com/Homebrew/homebrew-core/pull/136842

**Pull request closed without merging**
