### PR TITLE
kubernetes-cli 1.3.0-alpha.5 (devel)

### PR DESCRIPTION
**Pull request by Jerzerak**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---
- Bump devel version from 1.3.0-alpha.4 to 1.3.0-alpha.5

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Install is failing: http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/2687/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install___devel_kubernetes_cli/

**Comment by DomT4** [comment]
🔔?

**Comment by DomT4** [comment]
```
k8s.io/kubernetes/cmd/kubectl
*
+++ [0613 14:43:50] Placing binaries
Error: No such file or directory - contrib/completions/bash/kubectl
```

**Comment by DomT4** [comment]
Replaced by https://github.com/Homebrew/homebrew-core/commit/0676761e917fd3ee4354aef98d43b45272b957c7.

**Pull request closed without merging**
