### PR TITLE
tile38 1.16.2

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by igas** [comment]
@BrewTestBot test this please

**Comment by scpeters** [comment]
This jenkins build had been running for over 14 hours at the `brew test tile38` stage. I ssh'd to the machine and manually killed the `tile38-server` processes and then the build completed successfully. I'll check if the `brew test tile38` hangs outside of CI.

**Comment by scpeters** [comment]
I can reproduce that `brew test tile38` leaks a `tile38-server` process in the background. The `brew test` invocation returns, but the process is still there. I'm guessing test-bot is waiting for that lingering process to terminate?

**Comment by igas** [comment]
I'll take a look. Thanks @scpeters

**Pull request closed without merging**
