### PR TITLE
pari: remove x11 dependency

### PR DESCRIPTION
**Pull request by ear**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Hello, I would like to make a plea with this PR: having access to an X11 server is of extremely marginal utility for PARI/GP. The whole software package can be used without it and since homebrew/homebrew-core doesn't support optional depdencies anymore it is better to implement a `caveat` than force a `depends_on` onto every single user.

This much is described in the first paragraph of the [PARI/GP homepage](https://pari.math.u-bordeaux.fr): the focus of the software is algebra and number theory. It provides a wealth of functions and operator to work with number fields, elliptic curves, modular forms, and other number-theoretic and algebraic objects. This is what the vast majority of PARI/GP users depend on it for.

It also provides a few [functions related to plotting](https://pari.math.u-bordeaux.fr/dochtml/html-stable/Plotting_functions) graphs and some graphical primitives. All of them are device-independent in the sense that the output device can be chosen by the user.

Now observe that the default for `plot()` is (a rather cute) textual output:

```
? plot(x=-5,5,exp(-abs(x/2))*sin(2*x))

 0.692608 |''''''''''''''''''''''''''''''''''x"''''''''''''''''''''''''''|
          |                                 _  "                         |
          |                                 :   _                        |
          |                                :    :                        |
          |                                x     :                       |
          |                                :     "                       |
          |               x""_            :                              |
          |              x    _           :       x                      |
          |             x                 x       :              ___     |
          |            x       _          :        :           x"   x_   |
          "x          _                   :        "          "       x_ |
          ``"x```````_``````````_````````:```````````````````"``````````x_
          |   "x   _x           :        :          "       x            |
          |     """              :       x                 x             |
          |                      x       :           "    x              |
          |                             :             "__x               |
          |                       _     :                                |
          |                       :     x                                |
          |                        :    :                                |
          |                        "   :                                 |
          |                         _  "                                 |
-0.692608 |.........................._x..................................|
          -5                                                             5
```

Furthermore it is very easy to produce PostScript and/or SVG output as follows:

```
? plotinit(0,300,300);
? s=plothexport("ps",x=-5,5,exp(-abs(x/2))*sin(2*x));
? write("/tmp/graph.ps",s);
```

Screenshot 2019-06-23 at 12 10 02

Lastly there is the option to have the software fork a process that creates an X11 window in which the results can be shown as well. Please note that none of the functionality is impeded by removing the `depends_on :x11` constraint.

It seems to me this is a perfect example for the use of the [`caveats`](https://docs.brew.sh/Formula-Cookbook#caveats) feature: the software works, but the user needs to perform extra steps to unveil this tiny last corner of functionality.

Furthermore the steps to take are straightforward now that [X11/XQuartz](https://github.com/Homebrew/brew/blob/6b2dbbc96f7d8aa12f9b8c9c60107c9cc58befc4/Library/Homebrew/os/mac/xquartz.rb) is part of the [official homebrew/homebrew-cask tap](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/xquartz.rb). A `brew cask install xquartz` will immediately allow access to the `plotdraw()` function.

Thank you for taking the time to read and review this proposal, it is appreciated!

### CODE REVIEW

**Comment by jonchang** [comment]
Looks like you'll need to pass an argument to `configure` or set some kind of environment variable to disable X11 support.

**Comment by ear** [comment]
> Looks like you'll need to pass an argument to `configure` or set some kind of environment variable to disable X11 support.

You're right: without an explicit `--graphic=…` option to `./Configure` it infers by itself that it has access to the `x11` libraries.

I'm gonna push `--graphic=ps` to test out if it builds correctly on all supported platforms but I have a question: would it be possible to list x11 as a build dependency only?

I.e. let the code be compiled with the default options, the binary is linked to X11 and everything else, but it will only actually display the graphics window if you actually have XQuartz installed. This would make the `caveat` proposed worth it in my opinion.

Otherwise I think the `caveat` must be gone or rewritten to also suggest you need to compile from sources with `--graphic=auto` after the cask install of XQuartz. Not sure what's best.

**Comment by ear** [comment]
I'm glad this works.

What would be the preferred option as per Homebrew standards?

1. Drop `depends_on :x11` and use `./Configure --graphic=ps`, no `caveats`.
2. Use `depends_on :x11 => :build' and use no `--graphic` option, add the proposed `caveats`.

The `caveats` should also mention that a build from source will fail unless X11 is installed. That might be a deal breaker for solution #2 but I want to learn more about Homebrew.

The Formula Cookbook [under `depends_on`](https://docs.brew.sh/Formula-Cookbook#specifying-other-formulae-as-dependencies) says:

> A Hash (e.g. =>) adds information to a dependency. Given a String or Symbol, the value can be one or more of the following values:
> 
>  * :build means that dependency is a build-time only dependency so it can be skipped when installing from a bottle or when listing missing dependencies using brew missing.
>  * :optional generates an implicit with-foo option for the formula. This means that, given depends_on "foo" => :optional, the user must pass --with-foo in order to use the dependency.
>
> [..]
>
> Note: `option`s are not allowed in Homebrew/homebrew-core as they are not tested by CI.

I don't understand if `option` refers to `:optional` in particular or if it refers to the the general notion of those optional hash values.

The most satisfactory way to go about it might also be something else I'm not thinking of at this moment!

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
