### PR TITLE
elm 0.18.0

### PR DESCRIPTION
**Pull request by ashleyconnor**
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

First PR for `homebrew`. If @ilovezfs could take a look I'd be grateful.

Main change here is adding `aeson-pretty` to the `cabal.config` as a version was fixed in the `elm-lang` project back in August (post `0.17.1` release). Wouldn't build on `macOS Sierra` without it.

One question I have:

There are a few bottle references in this package. Are they built by some CI or does the community need to compile and upload each target?

### CODE REVIEW

**Comment by woodruffw** [comment]
Looks like you're failing the audit:

```
        Error: 1 problem in 1 formula
elm:
  * File should end with a newline
```

Once that's fixed, the build should pass (assuming there are no other errors).

> There are a few bottle references in this package. Are they built by some CI or does the community need to compile and upload each target?

Our CI will handle that :smile:

**Comment by ashleyconnor** [comment]
That's funny because `brew audit --strict --online elm` was complaining about the newline.

I'll add it back in.

**Comment by woodruffw** [comment]
Strange. I'll look into that.

**Comment by ashleyconnor** [comment]
Error is:

```
elm:
  * C: 93: col 1: 1 trailing blank lines detected.
Error: 1 problem in 1 formula
```

I've added it in for the CI.

**Comment by ilovezfs** [comment]
File should end with a new line means the final '\n' was deleted.
```
bash-4.4$ curl -sL https://raw.githubusercontent.com/ashleyconnor/homebrew-core/12c09f0/Formula/elm.rb|cat -vet|tail -3
    assert File.exist?(out_path)$
  end$
end$
```
shows it's now correct.

I would like to see this version build successfully with 56-59 removed before this PR is merged. If we need to apply an upstream commit as a patch to make that happen, that'll be OK. A new release tag would be even better.
```
     # GHC 8 compat
     # Fixes "cabal: Could not resolve dependencies"
     # Reported 25 May 2016: https://github.com/elm-lang/elm-compiler/issues/1397
-    (buildpath/"cabal.config").write("allow-newer: base,time,transformers,HTTP\n")
+    (buildpath/"cabal.config").write("allow-newer: base,time,transformers,HTTP,aeson-pretty\n")
```

**Comment by woodruffw** [comment]
> I would like to see this version build successfully with 56-59 removed before this PR is merged.

Whew. I was about 30 seconds from merging this before you said that...

**Comment by ilovezfs** [comment]
hehe

**Comment by ilovezfs** [comment]
I've removed those lines. Let's see if/how this blows up.

**Comment by ilovezfs** [comment]
@ashleyconnor do you mind opening an issue upstream about this build failure? Thanks!

**Comment by ashleyconnor** [comment]
@ilovezfs - Done [https://github.com/elm-lang/elm-compiler/issues/1519](https://github.com/elm-lang/elm-compiler/issues/1519)

**Comment by ilovezfs** [comment]
Thanks @ashleyconnor

**Comment by ashleyconnor** [comment]
Evan replied in the upstream issue and we will have to wait for elm to officially support GHC 8 before these issues are made a priority.

I'm not sure how you guys want to proceed with this issue.

**Comment by ilovezfs** [comment]
@ashleyconnor I've commented on this issue: https://github.com/elm-lang/elm-compiler/issues/1519#issuecomment-260764302

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@ashleyconnor shipped! Thanks for this PR and your patience. I'm really happy with how it turned out.

**Comment by ashleyconnor** [comment]
@ilovezfs - Glad to have contributed.

**Pull request closed without merging**
