### PR TITLE
x86_64-linux-gnu-binutils 2.38 (new formula)

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This formula allows for cross-compiling to GNU/Linux on macOS.

### CODE REVIEW

**Comment by Gcenx** [comment]
With how gcc handles this it may be better to use `x86_64-unknown-linux-gnu`

**Comment by carlocab** [comment]
> With how gcc handles this it may be better to use `x86_64-unknown-linux-gnu`

This is true, but the other cross-toolchain formulae don't really follow this. Using `config.sub` provided by `automake`:

- `aarch64-elf` should be `aarch64-unknown-elf`
- `arm-linux-gnueabihf` should be `arm-unknown-linux-gnueabihf`
- `i686-elf` should be `i686-pc-elf`
- `x86_64-elf` should be `x86_64-pc-elf`

Incidentally, `config.sub` also gives `x86_64-pc-linux-gnu` for `x86_64-linux-gnu`.

**Comment by sjackman** [comment]
```console
$ brew unpack binutils
$ cd binutils-2.38
$ ./config.guess
x86_64-pc-linux-gnu
```
I'd suggest `x86_64-pc-linux-gnu`, but I'm also fine with `x86_64-linux-gnu`, and I dislike `x86_64-unknown-pc-linux-gnu`.

> Also, this formula is a bit useless on Linux (it's a duplicate of the `binutils` formula), so it might make sense to make it macOS-only.

I wouldn't make it macOS-only despite it being redundant. It's nice to be able to depend on the same packages and use the same build scripts on both macOS and Linux. Someone who has both packages installed likely knows what they're doing, and it does no harm.

**Comment by carlocab** [comment]
The target is usually of the form `cpu-vendor-kernel-os`, but our other cross-toolchain formulae typically omit the `vendor` part. Let's do the same here: `x86_64-linux-gnu`.

**Pull request closed without merging**
