### PR TITLE
gettext 0.22.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
`homebank` doesn't need a `revision` bump.

**Comment by carlocab** [comment]
`bindtextdomain` and `gettext` are private symbols for some reason. This looks like a `gettext` issue.

**Comment by carlocab** [comment]
Not super clear on what went wrong here, but it smells like an autotools problem. CC @fxcoudert and @Bo98 for thoughts.

**Comment by Bo98** [comment]
Yes, this should not need any revision bumps as the ABI version did not change. Something went wrong in the original build somewhere it seems.

**Comment by Bo98** [comment]
> `bindtextdomain` and `gettext` are private symbols for some reason. This looks like a `gettext` issue.

Potentially caused by https://github.com/autotools-mirror/gettext/commit/a80b9021019fe311b81771d67138496f512ef35a#diff-16e786cf1a43af13663bb3c26e360678aeb437ed167e3b60cf25a9e5fbcb5e22L37?

https://github.com/autotools-mirror/gettext/blob/aeb278579938aa386d902d2b4b73b3d144612784/gettext-runtime/intl/intl-compat.c#L50-L51

**Comment by fxcoudert** [comment]
I don't really know what is happening. Filed upstream: https://savannah.gnu.org/bugs/index.php?64323

**Comment by david718** [comment]
What's going on with this? If this PR isn't resolved, I won't be able to install gettext via arch64 homebrew on mac os 14.

**Comment by chenrui333** [comment]
> What's going on with this? If this PR isn't resolved, I won't be able to install gettext via arch64 homebrew on mac os 14.

there are some build issues with dependencies.

**Comment by ywwry66** [comment]
`gettext` 0.22.1 is out.

**Comment by fxcoudert** [comment]
> gettext 0.22.1 is out

And it fixes that bug.

**Comment by Bo98** [comment]
Try remove the revision bumps. They should not be needed if the bug is fixed - no ABI bumps occurred.

**Comment by Bo98** [comment]
The fix was accidentally omitted from the 0.22.1 archive and there's now a 0.22.2 where it is actually fixed.

**Review by Bo98 — APPROVED** [review]

**Pull request merged**
