### PR TITLE
wordgrinder 0.7.2 (new formula)

### PR DESCRIPTION
**Pull request by jalzur**
- [ yes] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [yes ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ yes] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ yes] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [yes ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I've been waiting for ak2k to finish his PR (https://github.com/Homebrew/homebrew-core/pull/41864) for months.  But he didn't finish it and now that PR is closed, so I'm fixing the last issues remaining from his PR and submitting it to finally have this new formula working.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @jalzur !

**Comment by jalzur** [comment]
Thanks to you @fxcoudert for taking care of it.

I've noticed that I'm not authorized to merge the PR.  Probably an admin should do that.

Do I need to do anything else?

**Comment by SMillerDev** [comment]
No, this is all. One of the maintainers needs to have time to wipe the Christmas dinner grease of their fingers, start the terminal and merge it. So it might be after Christmas.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
I can take care of this. Happy Christmas!! 🎄🎄

**Pull request closed without merging**
