### PR TITLE
curl + recursive dependen{cies,ts}: switch to `openssl@3`

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This will probably break a whole bunch of things, especially on Linux, but we may as well try to get this going.

### CODE REVIEW

**Comment by carlocab** [comment]
This PR is probably missing at least `node` and `lanraragi`, which are part of `nghttp2`'s dependency graph.

**Comment by carlocab** [comment]
Oops, nope. There's lots more. Presumably the tap-syntax job is picking up all the `uses_from_macos "curl"` instances that I was trying to ignore here.

**Comment by Bo98** [comment]
Our `tap_syntax` check only follows macOS dependency graph so we should maybe fix that first.

**Comment by Bo98** [comment]
> Presumably the tap-syntax job is picking up all the `uses_from_macos "curl"` instances

I'm surprised since we set `HOMEBREW_SIMULATE_MACOS_ON_LINUX`?

**Comment by carlocab** [comment]
> > Presumably the tap-syntax job is picking up all the `uses_from_macos "curl"` instances
> 
> I'm surprised since we set `HOMEBREW_SIMULATE_MACOS_ON_LINUX`?

Yea, that was a guess that turned out to be mistaken. I had thought `brew audit --strict foo` recurses through `foo`'s dependency graph, but it does not.

**Comment by Bo98** [comment]
Ideally we should get that audit checking on Linux first though before we migrate. https://github.com/Homebrew/brew/pull/12117 will help enable that but I imagine a lot of things will pop up.

Plus fixing the conflict that currently exists between `openssl@1.1` and `openssl@3` on Linux: #85812.

**Comment by chris-araman** [comment]
Is https://github.com/openssl/openssl/issues/16670 actually a blocker? Homebrew [requires](https://docs.brew.sh/Installation#macos-requirements) macOS 10.15 or later.

**Comment by lprimak** [comment]
Lots of people still use older macs including me. The above issue is resolved but not merged in yet

**Comment by Bo98** [comment]
Homebrew primarily supports 10.15 or higher but does "support" down to 10.10 best effort basis (see footnote 2) - that means we don't actively test it and it's up to users to send pull requests to fix things.

While we don't normally let older macOS issies block things here, in this scenario knowingly breaking older macOS by rendering curl unusable would end up crippling brew entirely for them since installing Homebrew's curl is _required_ on < 10.12.

**Comment by lprimak** [comment]
Thanks @Bo98

**Comment by cho-m** [comment]
Going to close this as quite outdated and probably easier to open new PRs. We should track OpenSSL 3 migration via #104784 or another issue where we can scope this better.

**Pull request closed without merging**
