### PR TITLE
apngasm 3.1.10

### PR DESCRIPTION
**Pull request by SMillerDev**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
ld: library not found for -lapngasm
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```
ld: library not found for -lstdc++fs
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by carlocab** [comment]
> ```
> ld: library not found for -lstdc++fs
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```

This sounds like the build getting confused and thinking it's running on Linux and/or compiling with an old GCC.

**Comment by carlocab** [comment]
We can probably fix the Linux build by building with a newer GCC. No idea about the macOS failures.

**Comment by Kagetsuki** [comment]
master should build on current OS-X/homebrew distributions now; but the header and linker path for ICU need to be diverted to the homebrew versions. I've added notes in the documentation to do:
```
export LDFLAGS="-L/usr/local/opt/icu4c/lib"
export CPPFLAGS="-I/usr/local/opt/icu4c/include"
```
before running cmake.

If there's a way in cmake to specifically detect homebrew based builds I could add that in?

**Comment by SMillerDev** [comment]
CMake already finds icu4c if you declare it as a dependency.

**Comment by Kagetsuki** [comment]
@SMillerDev Yes but it finds the system libraries first which are incompatible with the homebrew distributed boost. Also note I added icu4c in the homebrew install line in the README. I actually only figured this out because there were other projects reporting the same issue - I got the export lines above directly from an issue on a separate project here on GH. Basically you can add the search lines in CMake and it will find them but the build will fail when it tries to link libicudata because the Apple system versions are too different to the ones needed by the newer versions of boost distributed by homebrew.

**Comment by SMillerDev** [comment]
If the homebrew Formula depends on something it will put those dependencies in the search path before the system ones.

**Comment by Kagetsuki** [comment]
From my tests it didn't seem to be doing that. I'll try re-adding the icu4c search and will report back with results - it's totally possible [highly likely] I didn't add the find correctly and just assumed the above kludge was needed and ran with it.

**Comment by SMillerDev** [comment]
Just to be clear, it'll only do that if you build it with brew

**Comment by Kagetsuki** [comment]
@SMillerDev I've tried as many methods as I can find and there's problems with all of them. If I'm specifically looking for homebrew libraries without using find package I can make it work but that's definitely not the right way to do it. The "official" method using find_package and searching for components of ICU 
```
find_package(ICU COMPONENTS data REQUIRED)

include_directories(${ICU_INCLUDE_DIRS})

target_link_libraries(${APNGASM_DYNAMIC_LIB_TARGET} ${ICU_LIBRARIES})
target_link_libraries(${APNGASM_STATIC_LIB_TARGET} ${ICU_LIBRARIES})
```
fails on both a clean OS-X install and on the CI instance: https://github.com/Kagetsuki/apngasm/runs/4416693500?check_suite_focus=true

If you can point me to a way to do this without breaking non-homebrew builds it would be much appreciated.

**Comment by SMillerDev** [comment]
That one works if you change your github actions to use

```
      - name: "run cmake ubuntu"
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cmake ../apngasm
      - name: "run cmake macOS"
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          export ICU_ROOT=$(brew --prefix icu4c)
          cmake ../apngasm
```

**Comment by Kagetsuki** [comment]
Right, but that's specifying the ICU_ROOT which is basically the same thing I'm doing with the exports I posted above but at/before make time. If the ICU libraries are in a common path like they are on Linux and MSYS2 you don't need to find the packages - and if you specify the exports like I do above and in the README then you don't need to add the find package to CMake. If you're going to be adding exports in either case I'm not sure why the version with the extra find_package is preferable?

**Comment by SMillerDev** [comment]
Well, you require ICU. So CMake should know that you do.

Subsequently CMake might not be able to find ICU from brew on its own so you can tell it to look in somewhere specific with `ICU_ROOT`.

Sure you can add the include directory using `LDFLAGS` but then why use a build system at all?

**Comment by Kagetsuki** [comment]
Actually Boost requires it. We don't directly use ICU, which is sort of another reason I'd like to avoid including this. The issue here is that homebrew is defaulting to allow precidence to the system provided libraries which are incompatible with newer versions of Boost.

**Comment by Kagetsuki** [comment]
Don't get me wrong, if there's a few simple lines that won't break other builds I'll include them - but of you need to override environment variables either way I'd rather take the cleaner and less obtrusive route of not including the extra lines just for homebrew.

**Comment by carlocab** [comment]
You could query for a `brew` installation with something like `find_program(BREW brew /opt/homebrew /usr/local)` then use that to check for the value of `$(brew --prefix icu4c)`, which you can append to `CMAKE_PREFIX_PATH`.

**Comment by Kagetsuki** [comment]
Thanks for the hints but I'm afraid that adding the icu4c prefix to the CMAKE_PREFIX_PATH still results in link failure during make; even if I'm explicitly specifying the ICU libraries with target_link_libraries (as per how I stated here: https://github.com/Homebrew/homebrew-core/pull/88825#issuecomment-986002732) .

I'm sorry but I don't have a lot of free time to continue attributing to this and I don't really know what you specifically need me to do to make homebrew work. If you can add the exports I mentioned [here](https://github.com/Homebrew/homebrew-core/pull/88825#issuecomment-979766329) to your build directives before running `make` it should work. Otherwise, even though I'd really like to avoid adding dependencies (ICU) for dependencies (Boost) for only one build chain, if you'd care to adjust the cmake files and put in a pull request I'd be fine with looking at it and accepting it if it doesn't interfere with anything else.

**Comment by carlocab** [comment]
I see, that's fine, I think the documentation you mentioned in https://github.com/Homebrew/homebrew-core/pull/88825#issuecomment-979766329 should be sufficient for users building outside of Homebrew but using Homebrew-built ICU.

**Comment by Kagetsuki** [comment]
Just let me know if there's anything that needs to be done to build packages.

I wish I could have been a little more helpful here but I honestly am not completely sure how homebrew works or what's really needed and I'm a bit pressed for time at the moment.

As a side note, I was a little surprised when I found out libraries and headers weren't stored in shared locations, and also that Boost wouldn't have been built with hardcoded relative links to the icu4c libraries - but I now understand the reasoning behind this. I'm not going to disagree with this design (it does have its own benefits, espically considering how Apple has some system specific versions of libs) but honestly I'm also not very comfortable with adding a lot of extra cmake handling just to accomodate it.

Thanks everyone, especially @SMillerDev , for their effort and assistance here.

**Comment by porg** [comment]
In easy words (for non developers like me) will the updated apngasm be available in brew anytime soon?

**Comment by carlocab** [comment]
@porg likely not too long after apngasm has made a release with the build fixes that blocked this version. Or if someone wants to backport those fixes to 3.1.10, then we'd probably merge a PR that applies those fixes here.

**Comment by Kagetsuki** [comment]
All fixes noted here are in master and the 3.1.10 tag/release has been updated to the current master head. Unless Max decides to implement some of the suggested changes there won't be another update for a while - so again, if there's anything else you need me to do you need to let me know; but otherwise it should be ready for you to incorporate it.

**Pull request closed without merging**
