### PR TITLE
katago 1.8.2

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Review by nandahkrishna — APPROVED** [review]

**Comment by carlocab** [comment]
I wonder if we should be installing those resources. They're no longer being updated, and altogether they're pretty sizeable (~500 MB).

**Comment by nandahkrishna** [comment]
Their README points to a separate website where newer versions of these networks can be downloaded (https://d3dndmfyhecmj0.cloudfront.net/g170/neuralnets/index.html), so we could definitely consider removing these resources.

**Comment by carlocab** [comment]
Yea, I don't think these need to be packaged with the formula. Users who need them can just download them from that website.

**Comment by apetresc** [comment]
We had this debate originally when I introduced the formula. I strongly feel we should keep them in. The formula is useless to 99.999% of users without the network files. If we removed it, the first thing virtually every user would have to do is start reading through complicated release notes about the technical differences between the different network sizes/versions, just to arrive at the same conclusion as we have in the Formula. They would then need to download it and figure out how to configure katago to point to it.

The network should be considered as much a part of the formula as, say, BIOS images are for qemu. The program is completely useless without them unless you are one of the 0.0001% of users who are basically developing your own from scratch.

**Pull request closed without merging**
