### PR TITLE
Rename bigdata to blazegraph and update to 2.1.4

### PR DESCRIPTION
**Pull request by numbermaniac**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
First time I've ever even tried this....so I hope I got it right...
Fixes the first issue in #10839

I renamed it due to the change of official file name.

### CODE REVIEW

**Comment by neutric** [comment]
Try [formula_renames.json](https://github.com/Homebrew/homebrew-core/blob/master/formula_renames.json). Old name on the left, new name on the right.

**Comment by ilovezfs** [comment]
Looks like homepage may need an update too? Seems to redirect to the generic product page currently

**Comment by ilovezfs** [comment]
The symbolic link is corrupt. How did you create it?

**Comment by Numbermaniac** [comment]
@ilovezfs Using Github's online editor. Perhaps it doesn't work for symbolic links then...

**Comment by ilovezfs** [comment]
Interesting. I'm surprised it let you do that.

**Comment by Numbermaniac** [comment]
Looks like that fixed it @ilovezfs ! Thanks!

**Comment by ilovezfs** [comment]
you're welcome

**Comment by ilovezfs** [comment]
squashed to 1 commit

**Comment by ilovezfs** [comment]
Merged! Thanks for your help with https://github.com/Homebrew/homebrew-core/issues/10839.

**Pull request merged**
