### PR TITLE
balena-cli 12.22.0

### PR DESCRIPTION
**Pull request by pranasziaukas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
>    # balena-cli should only be updated every 10 releases on multiples of 10

**Comment by pranasziaukas** [comment]
How is this version not a multiple of 10?

**Comment by chenrui333** [comment]
@SMillerDev I think this is legit upgrade from 12.20.0 to 12.22.0.

**Comment by pranasziaukas** [comment]
As a reminder, there's throttling audit rule set [here](https://github.com/Homebrew/brew/blob/431b9c07427b0edf84c6721f48b8e46c51a782e5/Library/Homebrew/dev-cmd/audit.rb#L691).

**Pull request closed without merging**
