### PR TITLE
aqbanking 6.5.0 gwenhywfar 5.9.0

### PR DESCRIPTION
**Pull request by yurikoles**
- gwenhywfar 5.9.0
- aqbanking 6.5.0

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

There is some problems on home site, I removed `head` for `aqbanking`, url produces `403`.

### CODE REVIEW

**Comment by yurikoles** [comment]
`livecheck` works for me locally, so I'm force-pushing to trigger a rebuild.

**Comment by yurikoles** [comment]
```
➜  homebrew-core git:(bump-aqbanking-6.5.0-gwenhywfar-5.9.0) brew livecheck aqbanking    
aqbanking : 6.5.0 ==> 6.5.0
➜  homebrew-core git:(bump-aqbanking-6.5.0-gwenhywfar-5.9.0) brew livecheck gwenhywfar 
gwenhywfar : 5.9.0 ==> 5.9.0
```
¯\_(ツ)_/¯

**Comment by yurikoles** [comment]
Strange things happen with main site, a lot of pages report `403` for mostly a week. 

I think with may end up deprecating it.

**Comment by Bo98** [comment]
> There is some problems on home site, I removed `head` for `aqbanking`, url produces `403`.

Worthing noting that I cannot reproduce this issue. The git repos work fine for me.

**Comment by cho-m** [comment]
The livecheck failures remind me of `juman` #88309 where Linux CI would pass but macOS runners would fail with timeout.

Only similarity though is that they are both hosted outside USA.

If only livecheck fails, then we may just want to bypass it and merge since the download is successful and bottle is available.

**Comment by Bo98** [comment]
Yeah, livecheck isn't a blocker.

**Review by SMillerDev — APPROVED** [review]

**Comment by yurikoles** [comment]
It seems that due to failing checks, a manual merge is required.

**Pull request closed without merging**
