### PR TITLE
libtiff 4.5.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

continuing #118265

---

EDIT: Failures from previous run that should be fixed before next run:
- [ ] `libarchive` needs an upstream pkgconfig fix to unblock `libgxps` and `evince`
- [ ] `qt@5` (Linux)  - opportunistic linkage to `little-cms2`
- [x] `argyll-cms` (Linux)  - opportunistic linkage to `openssl@1.1` - #120289
- [x] `pike` (Linux)  - opportunistic linkage to `gdbm`, `sqlite`, `unixodbc` - #120310
- [ ] `root` - revision bump
- [x] `imlib2` (Linux)  - build is detecting `openjpeg` - #120098
- [x] `xplanet` (Linux) - doesn't build with C++11 or later standards. Some Linux distros have a patch. - #120097
- [x] `imagemagick` (Linux)  - opportunistic linkage to `djvulibre` - #120091
- [x] `imagemagick@6` (Linux)  - opportunistic linkage to `djvulibre` - #120091
- [x] `openimageio` opportunistic linkage to `dcmtk` - #120080

### CODE REVIEW

**Comment by chenrui333** [comment]
This seems a much bigger PR than I anticipated.

**Comment by chenrui333** [comment]
workflow run, https://github.com/Homebrew/homebrew-core/actions/runs/3784078239/jobs/6433105226

**Comment by fxcoudert** [comment]
libgxps fails with:

```
meson.build:145:0: ERROR: Dependency lookup for libarchive with method 'pkgconfig' failed: Could not generate cargs for libarchive:
  Package iconv was not found in the pkg-config search path.
  Perhaps you should add the directory containing `iconv.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'iconv', required by 'libarchive', not found
```

gegl fails with:

`Couldn't find include 'Babl-0.1.gir' (search path: '['/opt/homebrew/Cellar/gobject-introspection/1.74.0/share/gir-1.0', '/opt/homebrew/Cellar/gobject-introspection/1.74.0/share', 'gir-1.0', '/usr/local/share/gir-1.0', '/usr/share/gir-1.0', '/opt/homebrew/Cellar/gobject-introspection/1.74.0/share/gir-1.0', '/opt/homebrew/share/gir-1.0']')`

**Comment by cho-m** [comment]
`libarchive` needs an upstream fix. One PR got merged for Linux (https://github.com/libarchive/libarchive/pull/1825) but that doesn't help on macOS where system `libiconv` gets detected but `libiconv` doesn't ship a pkg-config file. The pkg-config lookup probably only works for particular msys2 package where they manually create a pkg-config file.

`babl` missing gir file was mentioned in #117590. I think it is missing due to how brew handles dependencies of build dependencies. So, pkg-config cannot find `glib`'s dependencies.

**Comment by cho-m** [comment]
`babl` fix #119675.

Checking if `libarchive` PR (https://github.com/libarchive/libarchive/pull/1813) can be re-opened. Otherwise, we may need to submit a new PR.

**Comment by cho-m** [comment]
Also seeing some opportunistic linkage, particularly on Linux. We should try to fix those beforehand (maybe in separate PRs) either by setting configure/cmake/etc arguments or making the dependency explicit.

**Comment by cho-m** [comment]
Failures/warnings impacting macOS and Linux:
- [ ] `libarchive` needs an upstream pkgconfig fix to unblock `libgxps` and `evince`
- [ ] `openimageio` opportunistic linkage to `dcmtk` - #120080
- [ ] `libpano` - revision bump
- [ ] `sane-backends` - revision bump

Failures/warnings impacting Linux:
- [ ] `exiftran` - revision bump
- [ ] `xplanet` - doesn't build with C++11 or later standards. Some Linux distros have a patch.
- [ ] `imlib2` - build is detecting `openjpeg`. either need to force disable feature or add dependency everywhere.
- [ ] `libgr` - need to rebuild `qhull` 
    ```
    ld: /home/linuxbrew/.linuxbrew/lib/libqhullstatic.a(global.c.o): relocation R_X86_64_32S against symbol `qh_qh' can not be used when making a shared object; recompile with -fPIC
    ```
- [ ] `argyll-cms` - opportunistic linkage to `openssl@1.1`
- [ ] `imagemagick` - opportunistic linkage to `djvulibre`
- [ ] `imagemagick@6` - opportunistic linkage to `djvulibre`
- [ ] `pike` - opportunistic linkage to `gdbm`, `sqlite`, `unixodbc`
- [ ] `qt@5` - opportunistic linkage to `little-cms2`

**Comment by cho-m** [comment]
Rebased, but not ready to run yet. Added checklist to first post to avoid getting hidden.

**Comment by fxcoudert** [comment]
`libgxps` cannot find `libarchive`.

**Comment by SMillerDev** [comment]
libarchive issue should be fixed now.

**Comment by carlocab** [comment]
`vtk` also needs a rebuild, should fix `opencv` test failure.

**Comment by SMillerDev** [comment]
Seems like the ARM failures at least are unrelated

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
Making a note of the Linux and macOS failures, but all the tests of related software are successful.

**Review by MikeMcQuaid — DISMISSED** [review]
I'm fine with landing this and landing fixes ASAP.

**Comment by fxcoudert** [comment]
```
Auto-merging Formula/gmic.rb
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:
    git commit --allow-empty
```

😢

**Comment by fxcoudert** [comment]
Rebased. Running this time without dependents.

**Comment by chenrui333** [comment]
would need another rebase after [ffmpeg 6.0 PR](https://github.com/Homebrew/homebrew-core/pull/124363)

**Comment by SMillerDev** [comment]
Let's hope this is the last run

**Comment by SMillerDev** [comment]
Rebased and bumped pike that failed everywhere, I think the other builds can be fixed after this run.

**Comment by p-linnane** [comment]
Rebased and rerunning due to `11-arm64` runners needing to be restarted.

**Comment by p-linnane** [comment]
Rebased and rerunning due to `11-arm64` runners needing to be restarted.

**Review by fxcoudert — APPROVED** [review]

**Comment by SMillerDev** [comment]
Seems to be https://bugreports.qt.io/browse/QTBUG-112906?jql=text%20~%20std::move%20ORDER%20BY%20created%20DESC

**Comment by carlocab** [comment]
> Seems to be https://bugreports.qt.io/browse/QTBUG-112906?jql=text%20~%20std::move%20ORDER%20BY%20created%20DESC

Yup, looks like it. Guess we're not able to build `qt@5` on Ventura at the moment.

**Review by carlocab — APPROVED** [review]
I'd rather merge this and deal with the consequences after. It's not going to get easier after a re-run.

**Comment by SMillerDev** [comment]
> Ventura users will automatically get a Monterey bottle if there are no Ventura ones anyway, so it should be painless for users

**Comment by carlocab** [comment]
Failures on Ventura are the same across ARM and Intel:
- djview4
- freeswitch
- itk
- matplotplusplus
- netpbm
- opencv
- poppler-qt5
- qt@5
- siril
- vtk
- xfig
Most of them seem to come from a failure to build one of `qt@5` or `netpbm`.

**Comment by carlocab** [comment]
> Needs https://invent.kde.org/qt/qt/qtlocation-mapboxgl/-/commit/5a07e1967dcc925d9def47accadae991436b9686 applied.

Thanks for tracking that down.

**Comment by carlocab** [comment]
Just realised that `formulae_detect` may choke on the number of bottles it needs to fetch here.

**Comment by carlocab** [comment]
Oh, nice. Guess not.

**Comment by carlocab** [comment]
On Linux:

`exiftran` failed to build with
```
  /home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: filter.o:(.bss+0x0): multiple definition of `debug'; fbi.o:(.bss+0x650): first defined here
    CC	  ida.o
  collect2: error: ld returned 1 exit status
  make: *** [mk/Compile.mk:83: fbi] Error 1
  make: *** Waiting for unfinished jobs....
```
https://github.com/Homebrew/homebrew-core/pull/118902/checks#step:9:894

`gegl` failed with
```
  ../operations/external/pdf-load.c:53:10: fatal error: poppler.h: No such file or directory
     53 | #include <poppler.h>
        |          ^~~~~~~~~~~
  compilation terminated.
```
https://github.com/Homebrew/homebrew-core/pull/118902/checks#step:9:2323

CC @Homebrew/linux

**Comment by iMichka** [comment]
Here are fixes for both issues: #129412, #129413

**Comment by fxcoudert** [comment]
Merging qt@5 without Ventura bottles is now blocking all PRs that include dependents of qt@5, like this: https://github.com/Homebrew/homebrew-core/pull/128954

**Comment by carlocab** [comment]
Missing bottle checklist, since it seems to be buried by GitHub: https://github.com/Homebrew/homebrew-core/pull/118902#issuecomment-1521700524

**Comment by fxcoudert** [comment]
I think we're done now

**Pull request merged**
