### PR TITLE
lumo 1.0.0 (new formula)

### PR DESCRIPTION
**Pull request by leppert**

### CODE REVIEW

**Comment by leppert** [comment]
I realize this has alpha in the name, but it's highly stable. I'll let @anmonteiro comment on his release naming if it's of concern to the brew community.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by leppert** [comment]
Closing this down until we get a proper 1.0.0 released due to the non-alpha url restriction. Will resubmit at that time.

**Comment by leppert** [comment]
Re-opening as Lumo is now at 1.0.0.

**Comment by leppert** [comment]
Re-opening as Lumo is now at 1.0.0. cc/ @anmonteiro

**Comment by woodruffw** [comment]
LGTM, could you squash this down to 1 commit? Thanks!

**Comment by leppert** [comment]
@woodruffw done!

**Comment by woodruffw** [comment]
Thanks! CI should be done soon; I'll merge then.

**Comment by woodruffw** [comment]
Thanks for contributing @leppert!

**Pull request closed without merging**
