### PR TITLE
git-standup 2.1.4

### PR DESCRIPTION
**Pull request by nicosomb**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
### Description

The project maintainer just released 2.0.0. 

I don't know what to do with this auto generated block: 

```
  bottle do
    cellar :any_skip_relocation
    sha256 "9ec910ead4b99bdcaa2649a01a207257d56ba6e8d51233b18220637f968eb6d2" => :el_capitan
    sha256 "a77681880f954d6e3337c582d589cb23b5b34e09a3d787737567278fbb33fc45" => :yosemite
    sha256 "87050e61def08fe7c2c4b521c5ddc607348987241a94efeb91cf699e84fe63e0" => :mavericks
  end
```

### CODE REVIEW

**Comment by mikemcquaid** [comment]
> I don't know what to do with this auto generated block:

Leave it as-is; it'll be updated when we pull.

**Comment by UniqMartin** [comment]
The test on our build bot fails because `git-standup` has made changes to the command line interface in 2.0.0. Please have a look at its documentation and adjust the test code accordingly. Thanks!

**Comment by apjanke** [comment]
Test failed on the test-bot. Looks like `git standup` expects to be running inside a tty.

```
failed: brew test git-standup --verbose

Stacktrace

        Testing git-standup
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160421-53397-1a8ngte.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/git-standup.rb --verbose
==> git init
Initialized empty Git repository in /private/tmp/git-standup-test-20160421-53398-1p2s6c7/.git/
==> git add /tmp/git-standup-test-20160421-53398-1p2s6c7/test
==> git commit --message test
[master (root-commit) 5d6713e] test
 1 file changed, 1 insertion(+)
 create mode 100644 test
==> git standup
tput: No value for $TERM and no -T specified
Error: git-standup: failed
Failed executing: git standup
/usr/local/Library/Homebrew/formula.rb:1492:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1429:in `open'
```

This is a bug that should be reported to upstream. But in the mean time, to get the test running, you can just hack it by putting `ENV["TERM"] = "xterm"` at the beginning of the `test do` block.

**Comment by mikemcquaid** [comment]
> But in the mean time, to get the test running, you can just hack it by putting ENV["TERM"] = "xterm" at the beginning of the test do block.

Yeh, this will do it 👍

**Comment by DomT4** [comment]
Failed again:
```
==> git init
Initialized empty Git repository in /private/tmp/git-standup-test-20160422-75960-4zq49i/.git/
==> git add /tmp/git-standup-test-20160422-75960-4zq49i/test
==> git commit --message test
[master (root-commit) 5ad2a27] test
 1 file changed, 1 insertion(+)
 create mode 100644 test
==> git standup
Error: git-standup: failed
Failed executing: git standup
```

**Comment by UniqMartin** [comment]
Merged in 0e481da1d8db35b2505235673a58305a0dc1c86b. Thank you for this contribution to Homebrew, @nicosomb! :tada:

**Pull request closed without merging**
