### PR TITLE
cocoapods 0.39.0 (new formula)

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
### Description

Taking an approach we haven't taken with Ruby things before. I think this matches what we do for Python and should allow more packaging of Ruby "apps" (if we want to do so).

### CODE REVIEW

**Comment by mikemcquaid** [comment]
CC @DomT4 for thoughts on this.

**Comment by DomT4** [comment]
Seems reasonable to me, but I'd possibly be tempted to make it `keg_only` given that it's currently more limited than the full `gem` installation and the latter is likely to be quite popular and may raise conflicts. That'd be consistent in particular with things like `sphinx-doc`.

Unsure on that though, feel free to override the concern there if you feel strongly.

**Comment by mikemcquaid** [comment]
CC @keith who may be interested in this.

**Comment by her** [comment]
This is fantastic 😍 great news 👏🏻

**Comment by mikemcquaid** [comment]
@DomT4 Thanks for the feedback. Think I'll ship this as-is for now and we'll see if we can't get it fully featured.

**Comment by DomT4** [comment]
Alright, let's see how it goes. I suspect if we can't get it fully-featured soon we may get whacked with requests to lock it away until we can but I'm happy to shut up till then 😃.

**Comment by mikemcquaid** [comment]
FWIW I asked a few users and none of them had used the commands that are currently not working.

**Pull request closed without merging**
