### PR TITLE
mmseqs2 8-fac81

### PR DESCRIPTION
**Pull request by milot-mirdita**
Hi all,

We have a new MMseqs2 release with some bigger changes. The test section had to be adapted slightly to check one of the user-facing formats, instead of the internal databases.

- [✓] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [✓] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [✓] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [✓] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [✓ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by milot-mirdita** [comment]
The build is failing on GCC on Mojave. Apple has introduced the `_Atomic` keyword in the 10.14 SDK recently. G++ does no seem to support this keyword and the compilation fails. We had a user already experience this [issue](https://github.com/soedinglab/MMseqs2/issues/182) in our own repository. My advice was the following very dirty hack:
```
cmake -DCMAKE_CXX_FLAGS="-D_Atomic=volatile" ..
```

I guess this would not be acceptable for the brew formula. Right?

I just saw that another Homebrew user seems to be facing the same challenge using the Homebrew GCC:
https://github.com/Homebrew/homebrew-core/issues/38607

Should I make a new issue and try to get GCC somehow fixed or should I apply some hack to the formula?

**Comment by SMillerDev** [comment]
You should always try to get upstream to fix things.

**Comment by milot-mirdita** [comment]
The issue seems to be [known](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89864) to upstream. 

Can we proceed with this hack instead?

**Comment by SMillerDev** [comment]
Preferably we'd use the patch upstream has instead of a hack.

**Comment by fxcoudert** [comment]
Yes, let's not go redefining keywords such as `_Atomic`. Upstream should include conditional compilation for such code.

**Comment by milot-mirdita** [comment]
The proposed [patch](https://gcc.gnu.org/ml/gcc-patches/2019-04/msg00162.html) from upstream is essentially the same, just more localized. I could wrap the two includes of the `sysctl.h` header in the MMseqs2 codebase in the same way through a `:patch` directive. Would that be better?

**Comment by milot-mirdita** [comment]
This workaround suggested in the upstream bug thread seems to work well (even with the unrelated `brew doctor` issue):
```
-DCMAKE_CXX_FLAGS=-D__APPLE_API_STRICT_CONFORMANCE
```

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by milot-mirdita** [comment]
The Mojave failure does not seem related to the formula. Can I do something about it? Should I rebase the commit ontop of master?

**Comment by zbeekman** [comment]
Only maintainers can trigger the testbot through comments or the Jenkins UI.

**Pull request closed without merging**
