### PR TITLE
ldc 1.23.0

### PR DESCRIPTION
**Pull request by hewison-chris**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Geod24** [comment]
@bayandin : Any suggestion how to move forward ? This is an LLVM bug :/

**Comment by bayandin** [comment]
> @bayandin : Any suggestion how to move forward ? This is an LLVM bug :/

We could try to switch formula to `llvm@9`, to see if it helps.

@Bo98 did you get a chance to have a look at libxml2 CMake changes you mentioned in https://discourse.brew.sh/t/llvm-config-10-0-1-advertise-libxml2-tbd-as-system-libs/8593/3 ?

**Comment by Geod24** [comment]
@bayandin : Thanks, looks like it did the trick!

**Review by bayandin — APPROVED** [review]
I've just added a reference to a llvm bug not to lose it.

Thanks @hewison-chris 🎉

**Comment by bcardiff** [comment]
FYI `llvm(@10)` should be usable now https://github.com/Homebrew/homebrew-core/pull/61005

**Comment by bayandin** [comment]
> FYI `llvm(@10)` should be usable now #61005

Thanks! 
I've created https://github.com/Homebrew/homebrew-core/pull/61117 to switch `ldc` back to `llvm`

**Pull request closed without merging**
