### PR TITLE
cargo-c: switch back to `uses_from_macos "curl"`

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

relates to:
- https://github.com/alexcrichton/curl-rust/issues/524 (should be resolved with curl-rust 0.4.67 rel)
- https://github.com/Homebrew/homebrew-core/pull/146547

### CODE REVIEW

**Comment by chenrui333** [comment]
yeah, only 13 does not link to sys curl

**Comment by chenrui333** [comment]
I just run a sys curl, seems working fine for me


```
bash-3.2$ cat cargo.toml
[package]
name = "curl_sys_checker"
version = "0.1.0"
edition = "2021"
bash-3.2$ cat src/main.rs
use std::io::{stdout, Write};

use curl::easy::Easy;

// Print a web page onto stdout
fn main() {
    let mut easy = Easy::new();
    easy.url("https://www.rust-lang.org/").unwrap();
    easy.write_function(|data| {
        stdout().write_all(data).unwrap();
        Ok(data.len())
    }).unwrap();
    easy.perform().unwrap();

    println!("{}", easy.response_code().unwrap());
}

bash-3.2$ otool -L target/debug/curl_sys_checker
target/debug/curl_sys_checker:
        /usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1336.61.1)
```

**Comment by Bo98** [comment]
It'll be things that use the `http2` feature. `curl-config --features` did not report HTTP2 prior to macOS 14.

Technically more a bug in `curl-config` because HTTP2 did exist since 10.13. Maybe we can make a shim workaround in `brew`.

Or an alternative if you want a quicker solution is to use `since: :sonoma` for now.

**Comment by chenrui333** [comment]
> It'll be things that use the `http2` feature. `curl-config --features` did not report HTTP2 prior to macOS 14.
> 
> Technically more a bug in `curl-config` because HTTP2 did exist since 10.13. Maybe we can make a shim workaround in `brew`.

yeah, I saw HTTP2 in `curl --version`, but did not run `curl-config` check

**Review by daeho-ro — APPROVED** [review]

**Pull request merged**
