### PR TITLE
oci-cli 3.3.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
ERROR: Some build dependencies for setuptools-rust>=0.11.4 from https://files.pythonhosted.org/packages/a1/00/56ed41e98bd83e8fd028e24144e20bef87cdec0110fd1729352fce33d36c/setuptools-rust-1.1.0.tar.gz#sha256=e8a65f7398028cb0e4e00730ee3d1e168bf9d4e3770a61fec815e8e7a24dcab1 conflict with the backend dependencies: setuptools_scm==6.0.1 is incompatible with setuptools_scm>=6.3.2.

**Comment by chenrui333** [comment]
- relates to pyca/cryptography#6671

**Comment by alex** [comment]
The latest setuptools-rust release hopefully ameliorates this issue.

**Comment by chenrui333** [comment]
@alex looks good now.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
