### PR TITLE
sane-backends 1.0.25

### PR DESCRIPTION
**Pull request by yurikoles**
Resubmission of previous old patch https://github.com/Homebrew/legacy-homebrew/pull/44655

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like we may need to work on the patch more here, given upstream have [rejected](https://lists.alioth.debian.org/pipermail/sane-devel/2015-October/034011.html) the existing one:

>  However, I don't think that your fix is the right way to go about fixing this. It is really something that configure should check for.

> Feel free to keep using this patch yourself but I will not commit it to Alioth's master.

I can't speak to how fair or unfair the judgement of your patch is by upstream, but since we try very hard not to carry patches forever we would prefer a solution that upstream hasn't shot down already.

**Comment by yurikoles** [comment]
@DomT4 in fact those issues was addressed in upstream's master, but they are introduced new one. So I have sent another patch, that is already merged. So we can now build master (HEAD) without patches.

**Comment by yurikoles** [comment]
I don't need it now, but I have question: could one formula contain different sets of patches for stable/devel/head?

**Comment by MikeMcQuaid** [comment]
> I don't need it now, but I have question: could one formula contain different sets of patches for stable/devel/head?

Yes, just put the `patch do` inside e.g. `stable do`/`devel do`.

**Pull request closed without merging**
