### PR TITLE
clarinet 1.6.1

### PR DESCRIPTION
**Pull request by CharlieC3**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  error: failed to run custom build command for `clarinet-cli v1.6.1 (/private/tmp/clarinet-20230516-5964-10wu75r/components/clarinet-cli)`
  
  Caused by:
    process didn't exit successfully: `/private/tmp/clarinet-20230516-5964-10wu75r/target/release/build/clarinet-cli-40fff9b77ef68bce/build-script-build` (signal: 5, SIGTRAP: trace/breakpoint trap)
    --- stdout
    cargo:rustc-env=TARGET=aarch64-apple-darwin
    cargo:rustc-env=PROFILE=release
    cargo:rustc-env=GIT_COMMIT_HASH=acd7a3affaf9f2beb57c11fca888840239c7baba
    cargo:rerun-if-env-changed=GIT_COMMIT_HASH
    cargo:rustc-env=TS_VERSION=4.3.0
    cargo:rerun-if-env-changed=TS_VERSION
  
    --- stderr
  
  
    #
    # Fatal error in , line 0
    # Check failed: RwxMemoryWriteScope::IsAllowed().
    #
    #
    #
    #FailureMessage Object: 0x16db95d98
    ==== C stack trace ===============================
  
        0   build-script-build                  0x00000001030f53c8 v8::base::debug::StackTrace::StackTrace() + 24
        1   build-script-build                  0x00000001030f93d8 v8::platform::(anonymous namespace)::PrintStackTrace() + 24
        2   build-script-build                  0x00000001030ed5e8 V8_Fatal(char const*, ...) + 268
        3   build-script-build                  0x00000001037a35f4 v8::internal::wasm::WasmCodeManager::MemoryProtectionKeysEnabled() const + 0
        4   build-script-build                  0x00000001037b5694 v8::internal::wasm::WasmEngine::InitializeOncePerProcess() + 44
        5   build-script-build                  0x000000010338d910 v8::internal::V8::Initialize() + 1576
        6   build-script-build                  0x0000000103154bcc v8::V8::Initialize(int) + 32
        7   build-script-build                  0x00000001030ce308 v8::V8::initialize::h04957d4b3c69f4ff + 376
        8   build-script-build                  0x0000000102e7d7f0 deno_core::runtime::v8_init::h74206d08410707b9 + 188
        9   build-script-build                  0x0000000102e7ed9c _ZN9deno_core7runtime9JsRuntime3new28_$u7b$$u7b$closure$u7d$$u7d$17h190320006bc33581E + 48
        10  build-script-build                  0x0000000102def27c _ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17h44111a2c3a700e27E + 128
        11  build-script-build                  0x0000000103ec1938 std::sys_common::once::queue::Once::call::had70297f6bfba27b + 724
        12  build-script-build                  0x0000000102def19c std::sync::once::Once::call_once::h5af791f9907be628 + 196
        13  build-script-build                  0x0000000102e7da68 deno_core::runtime::JsRuntime::new::h316fd18e2b9ed3e3 + 264
        14  build-script-build                  0x00000001022d199c build_script_build::create_runtime_snapshot::h4b074fc7e9b2234e + 1344
        15  build-script-build                  0x00000001022d1d10 build_script_build::build_snapshot::h2bc0f15fa5200ccc + 168
        16  build-script-build                  0x00000001022d2360 build_script_build::main::h54d3c1f0c4a69db6 + 832
        17  build-script-build                  0x0000000102292ed4 core::ops::function::FnOnce::call_once::he2327ed7db5d7c58 + 16
        18  build-script-build                  0x000000010226f704 std::sys_common::backtrace::__rust_begin_short_backtrace::ha0557242cdd31688 + 16
        19  build-script-build                  0x00000001022e31c8 _ZN3std2rt10lang_start28_$u7b$$u7b$closure$u7d$$u7d$17he1b3b247a9719ae4E + 20
        20  build-script-build                  0x0000000103e74d30 std::rt::lang_start_internal::hcf5249aa241f98ab + 60
        21  build-script-build                  0x00000001022e31a0 std::rt::lang_start::hb11d0c7b7fc5891e + 60
        22  build-script-build                  0x00000001022d23a0 main + 36
        23  dyld                                0x0000000106e1d08c start + 520
  warning: build failed, waiting for other jobs to finish...
  error: failed to compile `clarinet-cli v1.6.1 (/private/tmp/clarinet-20230516-5964-10wu75r/components/clarinet-cli)`, intermediate artifacts can be found at `/private/tmp/clarinet-20230516-5964-10wu75r/target`
```

**Comment by chenrui333** [comment]
Looks like the same error as before on monterey arm build

(for the record, we have a fellow maintainer who can just build/test fine in local with 1.6.0 release 🤔 )

**Comment by hugocaillard** [comment]
Same error as 1.6.0.
Will keep investigating. The error message is definitely not helping

> for the record, we have a fellow maintainer who can just build/test fine in local with 1.6.0 release 🤔 
On the same env? (macos 12 arm?)

**Comment by hugocaillard** [comment]
Hey @chenrui333 

I discovered that even the green jobs are actually failing with the same error (here on macos 13 ARM) https://github.com/Homebrew/homebrew-core/actions/runs/4996398604/jobs/8950248639?pr=131127#step:3:30

Also, when looking at past releases, the CI is completely different: https://github.com/Homebrew/homebrew-core/pull/126489/checks
Do you know what could cause this?

Thanks for your help

**Comment by hugocaillard** [comment]
I also tried to add macos 12 to our own CI, in the build works https://github.com/hirosystems/clarinet/pull/1016
But again, I'm not sure macos 12 is the actual issue (since the build also fails on other version even though the check is green).
I'm investigating again today

**Comment by chenrui333** [comment]
#131430

**Pull request closed without merging**
