### PR TITLE
tmux 2.2

### PR DESCRIPTION
**Pull request by chusiang**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---
1. Modify tmux v2.2 url.
2. Remove 2.1 path, bottle and pkgshare.install for local pass build.
3. I have not idea of bottle sha256.

This is my first PR, maybe someone can help me.

Thank you very much.

### CODE REVIEW

**Comment by chusiang** [comment]
I see the #240, I know you will wait v2.3.

I just need the tmux support to send  Hex Codes on my iTerm2 (Build 2.9.20160510).

**Comment by rakkesh** [comment]
How about `% brew install tmux --HEAD`?

**Comment by dunn** [comment]
Yeah, for your use-case either use the `HEAD` installation or modify your local copy of the formula.

**Comment by chusiang** [comment]
I have try it, is this?

1. generation HEAD file.

        $ brew reinstall tmux --HEAD
        ==> Reinstalling tmux
        ==> Cloning https://github.com/tmux/tmux.git
        Updating /Library/Caches/Homebrew/tmux--git
        ==> Checking out branch master
        ==> sh autogen.sh
        ==> ./configure --prefix=/usr/local/Cellar/tmux/HEAD --sysconfdir=/usr/local/etc
        ==> make install
        🍺  /usr/local/Cellar/tmux/HEAD: 7 files, 638.2K, built in 25 seconds

2. show INSTALL_RECEIPT.json and get **b8e5ff431d2d5a20ba35d8a3fc9371e1a5ef3991**.

        $ cat /usr/local/Cellar/tmux/HEAD/INSTALL_RECEIPT.json
        {"used_options":[],"unused_options":[],"built_as_bottle":false,"poured_from_bottle":false,"time":1463709791,"source_modified_time":1463124766,"HEAD":"b8e5ff431d2d5a20ba35d8a3fc9371e1a5ef3991","stdlib":null,"compiler":"clang","source":{"path":"/usr/local/Library/Taps/homebrew/homebrew-core/Formula/tmux.rb","tap":"homebrew/core","spec":"head"}}

3. so the bottle will be this ?

        class Tmux < Formula
          desc "Terminal multiplexer"
          homepage "https://tmux.github.io/"
        
          stable do
            url "https://github.com/tmux/tmux/releases/download/2.2/tmux-2.2.tar.gz"
            sha256 "bc28541b64f99929fe8e3ae7a02291263f3c97730781201824c0f05d7c8e19e4"
          end
        
          bottle do
            cellar :any
            sha256 "b8e5ff431d2d5a20ba35d8a3fc9371e1a5ef3991" => :el_capitan
          end
        
        ...

**Comment by dunn** [comment]
There aren't bottles for HEAD builds, since they're just the latest commit from the repository.  After you've run `brew install --HEAD tmux`, you've got the head build.

**Comment by chusiang** [comment]
Oh, I see.

If I use the `brew install --HEAD tmux` command, I can get the latest tmux from official repository, and I don't need to edit the `tmux.rb` file.

Thank you. 👍 

```
$ brew reinstall --HEAD tmux
==> Reinstalling tmux
==> Cloning https://github.com/tmux/tmux.git
Updating /Library/Caches/Homebrew/tmux--git
==> Checking out branch master
==> sh autogen.sh
==> ./configure --prefix=/usr/local/Cellar/tmux/HEAD --sysconfdir=/usr/local/etc
==> make install
==> Caveats
Example configuration has been installed to:
  /usr/local/opt/tmux/share/tmux
==> Summary
🍺  /usr/local/Cellar/tmux/HEAD: 8 files, 640.0K, built in 27 seconds

$ tmux -V
tmux 2.3

**Pull request closed without merging**
