### PR TITLE
llvm@3.9 3.9.1 (new formula)

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by ilovezfs** [comment]
@tmcdonell Let me know if you'd prefer I re-open https://github.com/Homebrew/homebrew-core/pull/9414.

**Comment by ilovezfs** [comment]
CC @@SeanTAllen

**Comment by ilovezfs** [comment]
CC @SeanTAllen

**Comment by tmcdonell** [comment]
I think it's worthwhile to try the keg_only plus `llvm-config-3.9` solution, since you should be able to automate that (and llvm drops a release every 6 months or so, which is a lot of work for you guys). Might as well see how it goes, and reopen #9414 if it doesn't work for people.

**Comment by ilovezfs** [comment]
I'm not sure if it's actually possible to install anything in /usr/local/bin when it's marked keg_only as I think that would be a sandbox violation, but most build systems should allow it to be specified via an environment variable (e.g. `LLVM_CONFIG` for `ponyc`) or a configure option (e.g. `--llvm-root` for `rust`).

**Comment by ilovezfs** [comment]
Actually, it looks like we have HOMEBREW/"bin" white-listed in `postinstall` so I can do that.

**Comment by ilovezfs** [comment]
It's also important to note, I think, that the main `llvm` formula is itself `keg_only :provided_by_osx` so having the versioned ones be `keg_only` too really shouldn't be that big of a deal.

**Comment by ilovezfs** [comment]
In the interest of getting this shipped, I'm going to punt on linking llvm-config-3.9 since it technically violates the idea of keg_only-ness but I'm open to reconsidering in a future PR, especially if we do the same for the main llvm formula as well.

**Comment by yiakwy** [comment]
This formula has problems to support libcxxabi, because the ruby formula does not contain the libcxxabi sources. Could you show me the minimum codes to support that. Here is a example from homebrew legacy but I don't know how to generate the hashcode. Look forward to your reply.

**Pull request closed without merging**
