### PR TITLE
qt 6.5.0

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by p-linnane** [comment]
```
  /tmp/qt-20230403-26203-1g4pjzj/qt-everywhere-src-6.5.0/qtbase/include/QtCore/../../src/corelib/global/qtversionchecks.h:18:10: fatal error: 'QtCore/qconfig.h' file not found
  #include <QtCore/qconfig.h>
           ^~~~~~~~~~~~~~~~~~
  1 error generated.
```

**Comment by fxcoudert** [comment]
Still that, opened an upstream issue: https://bugreports.qt.io/browse/QTBUG-113295

```
  /tmp/qt-20230403-26203-1g4pjzj/qt-everywhere-src-6.5.0/qtbase/include/QtCore/../../src/corelib/global/qtversionchecks.h:18:10: fatal error: 'QtCore/qconfig.h' file not found
  #include <QtCore/qconfig.h>
           ^~~~~~~~~~~~~~~~~~
  1 error generated.
```

**Comment by fxcoudert** [comment]
To work around the Intel issue, we might replace `cannonlake` by `skylake-avx512` in `qtbase/config.tests/x86intrin/CMakeLists.txt`

**Comment by fxcoudert** [comment]
Build finished on ARM this time, but:

```
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ apply2files - /opt/homebrew/Cellar/qt/6.5.0/bin/qt-cmake-private-install.cmake
```

apparently that file is not there anymore.

**Comment by fxcoudert** [comment]
OK now we have:
- a clean build on ARM (all macOS versions), and all tests passing
- still the build failure on macOS Intel: https://bugreports.qt.io/browse/QTBUG-113391
- Linux is ongoing

**Comment by fxcoudert** [comment]
The issue persists even without `-DQT_FEATURE_avx2=OFF`. At this point, my suspicion is that our compiler shim is messing with Qt's detection of x86 intrinsics. If that is the case, I am not sure how to fix it.

**Comment by p-linnane** [comment]
@carlocab Isn't this a scenario where we should be able to remove https://github.com/Homebrew/homebrew-core/labels/CI-long-timeout since only Linux is still running?

**Comment by fxcoudert** [comment]
To detect the availability of x86 intrinsics, Qt passes `-march=cannonlake` to the compiler, which our shims rewrites to `-march=nehalem`. The test code fails to compile (because it uses intrinsics not present on Nehalem), Qt thinks we cannot handle x86 intrinsics, and errors out. Not sure what is the best way forward.

**Comment by carlocab** [comment]
> @carlocab Isn't this a scenario where we should be able to remove https://github.com/Homebrew/homebrew-core/labels/CI-long-timeout since only Linux is still running?

Yes. Didn't work? 😞

> To detect the availability of x86 intrinsics, Qt passes `-march=cannonlake` to the compiler, which our shims rewrites to `-march=nehalem`. The test code fails to compile (because it uses intrinsics not present on Nehalem), Qt thinks we cannot handle x86 intrinsics, and errors out. Not sure what is the best way forward.

`ENV.runtime_cpu_detection` will prevent the compiler shims from refurbishing `-march` flags.

**Comment by fxcoudert** [comment]
I just found out myself about `ENV.runtime_cpu_detection` and I can confirm after a local build that it fixes the issue.

**Review by fxcoudert — APPROVED** [review]

**Review by fxcoudert — APPROVED** [review]

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
@p-linnane long timeout label [removal](https://github.com/Homebrew/homebrew-core/pull/127440#event-9225101138) seems [to work](https://github.com/Homebrew/homebrew-core/pull/127440#event-9225102938). (`macOS 11-x86_64 (deps)` is still running at the time of writing.)

Let me know if you still see issues with it.

**Comment by fxcoudert** [comment]
@carlocab well it removed the label now, even though the deps runs are on-going

**Comment by carlocab** [comment]
No, it removed the label hours ago when only Intel Big Sur was running. Dep tests seem to have been restarted though.

**Comment by fxcoudert** [comment]
Should it remove the label if dependencies have not been tested yet? Is that a bug or a feature?

**Comment by carlocab** [comment]
> Should it remove the label if dependencies have not been tested yet? Is that a bug or a feature?

Hmmm. Not sure. Maybe both. 🙃 Let me think about it.

**Comment by carlocab** [comment]
> Should it remove the label if dependencies have not been tested yet? Is that a bug or a feature?

Probably a bug. Handled in #131583.

**Pull request merged**
