### PR TITLE
Adds Skafos forumula for homebrew

### PR DESCRIPTION
**Pull request by wess**
- [ x ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ x ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ x ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ x ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks for the PR. However, Homebrew formulae are required to build from source. Feel free to open a new pull request when you have it building from source.

**Comment by wess** [comment]
can the tarball be the source code then, or does it have to clone a tag of the release?

**Comment by ilovezfs** [comment]
We use release tarballs where available such as https://github.com/arvidn/libtorrent/releases/download/libtorrent-1_1_6/libtorrent-rasterbar-1.1.6.tar.gz but otherwise use source archive tarballs like https://github.com/conan-io/conan/archive/1.0.2.tar.gz

**Comment by wess** [comment]
Does it have to be github hosted tho, and in a public repo?

**Comment by ilovezfs** [comment]
doesn't have to be on GitHub but it does need to be open source and there needs to be somewhere to report bugs

**Pull request closed without merging**
