### PR TITLE
virt-manager: fix for python 3.13

### PR DESCRIPTION
**Pull request by groulet**
virt-manager4.1.0 relies on module "pipes" which has been deprecated since version 3.11, and removed in version 3.13. This commit also keep everything in the venv "libexec" and install libvirt-python as a resource instead of a depedency.
Until a new relase of virt-manager 4.1.0 is available, the formula should keep using python@3.12

How to reproduce the issue:
- Open virt-manager 4.1.0 with python 3.13.
- Open "Show virtual hardware details" of a virtual machine
- Go to the tap "Boot options"
- A "ModuleNotFoundError" error will be raised with "No module named 'pipes'"

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by branchvincent** [comment]
Thanks for the fix!

Since replacing `pipes` is a one-line fix to use `shlex` instead, let's either add a patch for https://github.com/virt-manager/virt-manager/commit/bb1afaba29019605a240a57d6b3ca8eb36341d9b#diff-dc64ef981d8d3488f7a092c88d405f16908b36aff4d6db67e91ddd9b85bc91ff or add an `inreplace` ourselves

**Comment by groulet** [comment]
**Patch vs Python3.12**
A patch/inreplace would work for the pipes module. However, I did not check if something else is also broken (or will break) with python 3.13 (or > 3.13). Since virt-manager 4.1.0 was released in 2022 (it looks like a new release might be in the work https://github.com/virt-manager/virt-manager/discussions/712). Wouldn't keeping formula to python 3.12 safer until a new release of virt-manager?

**libvirt-python as a resource**
Do you agree with having libvirt-python as a **resource** instead of a **depends_on**?

**virt-manager app in libexec**
Do you agree with keeping virt-manager inside libexec? I did this change because building from source on my Mac (Apple M3 Mac OS Version 14.6.1 (23G93)) failed with the current formula (prefix.install would move libexec/"share" under prefix/"share/share"). However this change breaks CI :(. I used the command:
`HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source --verbose --debug foo`
I did not have time yet to test with the docker CI image


PS: This is the first time I do a pull request, would love to make it to the end :)

**Comment by groulet** [comment]
I made a change in order for the build to pass the CI. I was not expecting the bot to automatically pull from the branch, therefore my commits were not correctly formatted :(

**Comment by daeho-ro** [comment]
Thanks for the fix, @groulet ! Really appriciate.

Here is my personal opinion.
1. I'd like to apply patch because `virt-manager` also have a patch to use `python` 3.13 and so there is no reason to keep 3.12.
2. When the python resource is pre-built, then it is better to use as `depends_on`.
3. Agree with you, it should be fixed.

As of this, I have pushed new commit and I hope this will resolve all the problems.

**Comment by groulet** [comment]
@daeho-ro Thanks for the commit.

I'm still a bit puzzled about not declaring libvirt-python as a resource.  My understanding was that the modules (dependencies) of Python app should be declared as resource as per https://docs.brew.sh/Python-for-Formula-Authors#installing-applications ? But well, does it matter in the end? Unless a future release of libvirt-python becomes incompatible with virt-manager 4.1.0 there should be no difference.

Cheers!

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
