### PR TITLE
HTTPie 3.0.0

### PR DESCRIPTION
**Pull request by isidentical**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by iMichka — DISMISSED** [review]
Thanks for your first contribution.

Why is idna regressing from 3.3 to 3.2?

**Comment by isidentical** [comment]
Hey @iMichka! Thanks for the review. I've used httpie's own [dependency generator](https://github.com/httpie/httpie/blob/master/docs/packaging/brew/brew-deps.py) which used to pin `idna` to `3.2`. Did not notice brew already was upgraded. I now fixed it on a separate branch, and updated this PR. If you could re-review, that would appreciated.

**Comment by dtrodrigues** [comment]
@isidentical the process in https://github.com/httpie/httpie/blob/master/docs/packaging/brew/README.md looks to be out of date. At this point, all that's needed is `brew bump-formula-pr httpie --version=3.0.0` which will update the primary url as well as the resources if applicable.

**Review by dtrodrigues — APPROVED** [review]
Thanks @isidentical

**Comment by jakubroztocil** [comment]
Thanks, @dtrodrigues! We’ll switch to `brew bump-formula-pr` for future releases.

**Pull request closed without merging**
