### PR TITLE
php 7.2.4

### PR DESCRIPTION
**Pull request by metowolf**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by commitay** [comment]
Thanks @metowolf!

**Comment by SMillerDev** [comment]
This isn't officially released yet. Ifficially it's still a RC

**Comment by ilovezfs** [comment]
Reverted. It would be nice to have some kind of audit for this.

**Comment by metowolf** [comment]
Sorry about that. 
It tags v7.2.4 in http://git.php.net/ and  be public in php.net tomorrow.
I will fix my bots later.

**Comment by ilovezfs** [comment]
@metowolf no worries! Thanks for the PR nonetheless.

**Comment by SMillerDev** [comment]
> Reverted. It would be nice to have some kind of audit for this.

Agree, just wouldn't know where to even start with it

**Comment by ngocphamm** [comment]
Idiotic way can be build a script to visit https://secure.php.net/ChangeLog-7.php and parse out the version. If it's not there, it's not officially released yet (hopefully).

**Comment by SMillerDev** [comment]
https://secure.php.net/releases/feed.php might be easier to parse then.

**Pull request closed without merging**
