### PR TITLE
json-glib: replace meson-internal with meson

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

relates to #58943

### CODE REVIEW

**Comment by chenrui333** [comment]
license header ref:

```
/* json-array.c - JSON array implementation
 * 
 * This file is part of JSON-GLib
 * Copyright (C) 2007  OpenedHand Ltd.
 * Copyright (C) 2009  Intel Corp.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 *
 * Author:
 *   Emmanuele Bassi  <ebassi@linux.intel.com>
 */
```

**Comment by chenrui333** [comment]
test failed on 10.13

```
==> /usr/bin/clang test.c -o test -I/usr/local/opt/atk/include/atk-1.0 -I/usr/local/opt/cairo/include/cairo -I/usr/local/opt/cogl/include/cogl -I/usr/local/opt/fontconfig/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/gettext/include -I/usr/local/opt/glib/include/glib-2.0 -I/usr/local/opt/glib/lib/glib-2.0/include -I/usr/local/opt/harfbuzz/include/harfbuzz -I/usr/local/Cellar/clutter/1.26.4/include/clutter-1.0 -I/usr/local/opt/json-glib/include/json-glib-1.0 -I/usr/local/opt/libpng/include/libpng16 -I/usr/local/opt/pango/include/pango-1.0 -I/usr/local/opt/pixman/include/pixman-1 -D_REENTRANT -L/usr/local/opt/atk/lib -L/usr/local/opt/cairo/lib -L/usr/local/opt/cogl/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/glib/lib -L/usr/local/opt/json-glib/lib -L/usr/local/Cellar/clutter/1.26.4/lib -L/usr/local/opt/pango/lib -latk-1.0 -lcairo -lcairo-gobject -lclutter-1.0 -lcogl -lcogl-pango -lcogl-path -lgio-2.0 -lglib-2.0 -lgmodule-2.0 -lgobject-2.0 -lintl -ljson-glib-1.0 -lpango-1.0 -lpangocairo-1.0
==> ./test
dyld: Library not loaded: /usr/local/opt/json-glib/lib/libjson-glib-1.0.0.dylib
  Referenced from: /usr/local/opt/clutter/lib/libclutter-1.0.0.dylib
  Reason: Incompatible library version: libclutter-1.0.0.dylib requires version 401.0.0 or later, but libjson-glib-1.0.0.dylib provides version 0.0.0
Error: clutter: failed
An exception occurred within a child process:
  BuildError: Failed executing: ./test
```

**Comment by miccal** [comment]
@chenrui333 the links in [this PR](https://github.com/Homebrew/homebrew-core/pull/58676) from @Bo98 may help explain the 10.13 errors.

**Comment by Bo98** [comment]
Yes.

> `libjson-glib-1.0.0.dylib provides version 0.0.0`

This is a bug and should be fixed before migrating away from `meson-internal`. `meson-internal` is a workaround for this very bug.

**Comment by chenrui333** [comment]
@Bo98 also I think for Mesa to deprecate `meson-internal`, I found out `meson` is used the python formula vs `meson-internal` is actually using the builtin python, probably you can take a look at that PR as well.

**Comment by alebcay** [comment]
Upstream already has this fixed in `HEAD` with [this patch](https://gitlab.gnome.org/GNOME/json-glib/-/commit/f24bc0f561c4e966006b0ad5cb51f230a69617c1). We could try to backport it or just sit tight with `meson-internal` until the `json-glib` 1.6.x branch is released.

**Comment by chenrui333** [comment]
Close in favor of #60986

**Pull request closed without merging**
