### PR TITLE
gping gping-v1.3.0

### PR DESCRIPTION
**Pull request by orf**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by orf** [comment]
The `no Linux bottle` tag was added. Is there anything I can do to add support for Linux, or is this OK as it is?

**Review by nandahkrishna — COMMENTED** [review]
@orf, we should probably add this at the beginning of the `test` block:
```ruby
if OS.linux?
  # Test fails on CI: Input/output error @ io_fread - /dev/pts/0
  # Fixing it involves pty/ruby voodoo, which is not worth spending time on
  return if ENV["HOMEBREW_GITHUB_ACTIONS"]
end
```
(Similar formulae: `nnn`, `viddy`, `pianobar`)

**Comment by cho-m** [comment]
Alternatively, you may be able to replace `screenlog = r.read` with a line-by-line read and ignore the (expected) error:
```rb
screenlog = ""
begin
  r.each_line { |line| screenlog += line }
rescue Errno::EIO
  # GNU/Linux raises EIO when read is done on closed pty
end
```

I've used this (and some variations) to get Linux test to work in other formulae. The last iteration of `r.each_line` will still raise an EIO error, so need to capture it.

**Comment by orf** [comment]
> Alternatively, you may be able to replace `screenlog = r.read` with a line-by-line read and ignore the (expected) error:
> 
> ```ruby
> screenlog = ""
> begin
>   r.each_line { |line| screenlog += line }
> rescue Errno::EIO
>   # GNU/Linux raises EIO when read is done on closed pty
> end
> ```
> 
> I've used this (and some variations) to get Linux test to work in other formulae. The last iteration of `r.each_line` will still raise an EIO error, so need to capture it.

Thanks @cho-m! I've made these changes, let's see!

**Comment by cho-m** [comment]
So it got past that error, but now there is a different failure. Maybe missing a dependency to run `ping`?

`Minitest::Assertion: Expected /google\.com\ \(/ to match "\e[?1049h\e[?1000h\e[?1002h\e[?1003h\e[?1015h\e[?1006h\e[2Jthread '<unnamed>' panicked at 'Failed to run ping: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }', pinger/src/lib.rs:57:18\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\nError: receiving on a closed channel\n".`

**Comment by orf** [comment]
Thank you @cho-m, it's much appreciated ☺️. I've added the linux depends on 👍

**Comment by cho-m** [comment]
Ah. Sadly we may need to disable test for a different reason.

I just remembered that we don't set up sudo-less `ping` like most Linux distros and we don't allow using root during tests.

As side-effect, this also means Homebrew's Linux `gping` is probably going to also be forced to use sudo.

---

May need to look into this further as distros like Debian/Arch/etc. usually enable non-sudo ping.

Debian, for example:
```
    # If we have setcap installed, try setting cap_net_raw+ep,
    # which allows us to install our binaries without the setuid
    # bit.
    if command -v setcap > /dev/null; then
        if setcap cap_net_raw+ep $PROGRAM; then
            chmod u-s $PROGRAM
        else
            echo "Setcap failed on $PROGRAM, falling back to setuid" >&2
            chmod u+s $PROGRAM
        fi
    else
        echo "Setcap is not installed, falling back to setuid" >&2
        chmod u+s $PROGRAM
    fi
```

Arch:
```
  setcap cap_net_raw=ep usr/bin/ping  2>/dev/null || chmod +s usr/bin/ping 
```

**Comment by orf** [comment]
Ok @cho-m, I've reverted the linux changes for now so we can get this merged. I'm happy to re-add the changes if any docker changes are made in the future, or I can try and make them myself if you can point me to where I should make them?

**Comment by cho-m** [comment]
> Ok @cho-m, I've reverted the linux changes for now so we can get this merged. I'm happy to re-add the changes if any docker changes are made in the future, or I can try and make them myself if you can point me to where I should make them?

That's fine for now. We can merge this once CI is done.

I'll also take a look and maybe do a follow up PR for any Linux changes.

We may just end up using a basic help/version output test (or expect failure) on Linux since it looks like the formula may work fine after adding `iputils` dependency.

The docker changes would need to be done as part of CI workflow when starting Linux docker container to have permissions. Will need to confirm if possible via GitHub Ubuntu runner and if any security issues.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
