### PR TITLE
streamlink 1.3.0

### PR DESCRIPTION
**Pull request by 404NetworkError**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Updated version and Python resources.

### CODE REVIEW

**Comment by Bo98** [comment]
Thanks for this. We're currently building Python 3.8 (see #45337), which involves revision bumping almost all Python formulae, so we're going to wait on this until that's finished to avoid merge conflicts. I'll let you know when we're ready.

**Comment by maxnordlund** [comment]
This fixes a critical bug, without it you can't watch Twitch anymore, see https://github.com/streamlink/streamlink/issues/2680#issuecomment-557605851

Could we get this in before the 3.8 stuff, pretty please?

**Comment by Bo98** [comment]
The reason I said it was because if we merge this then the entire build process would need to start again.

You're in luck though as I think we might have to restart anyway since there's some changes that need making.

@BrewTestBot test this please

**Comment by Bo98** [comment]
Merged now.

**Comment by maxnordlund** [comment]
Thanks

**Pull request closed without merging**
