### PR TITLE
nginx 1.14.0

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by apeschel** [comment]
nginx 1.13 is the mainline (unstable) release line, but nginx 1.14 is the stable release line. Not sure why this recipe is tracking the unstable line, maybe it was an accident, but someone should probably speak to if it makes sense to switch this recipe from the mainline release line to the stable release line.

If this recipe is tracking the mainline for some intended purpose, this should actually be upgraded to nginx 1.15 when that is released.

Otherwise, this is a good change to get this recipe onto the more sane stable release line.

**Comment by apeschel** [comment]
Additionally, a comment should be added to this recipe explaining how nginx release versioning works, so the line isn't accidentally changed again.

**Comment by apeschel** [comment]
Having a `--mainline` option for this recipe could also be a good idea.

**Comment by apeschel** [comment]
I've created a duplciate PR that fixes (most) the issues in this PR. https://github.com/Homebrew/homebrew-core/pull/27093

**Comment by ilovezfs** [comment]
Using main line is intentional as it's the recommended upstream branch. "Stable" is an LTS branch not the recommended branch.

**Comment by ilovezfs** [comment]
I have reverted ecb604ddf03d4feb6c047ea8795d7e5ab30c55c4 and 85f85ddfd3d90edbb69bc8f2bf7874920e75a3ec

**Comment by ilovezfs** [comment]
Comment about using mainline only added in https://github.com/Homebrew/homebrew-core/pull/27111

**Pull request closed without merging**
