### PR TITLE
vroom 1.7.0

### PR DESCRIPTION
**Pull request by dtrodrigues**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dtrodrigues** [comment]
Reported upstream: https://github.com/VROOM-Project/vroom/issues/361 .

**Comment by jcoupey** [comment]
See https://github.com/VROOM-Project/vroom/issues/361#issuecomment-656002878 for context on why the test now fails.

Possible ways I see to fix this:
- changing the test to somehow temporarily filter out the `id` keys for the json content used in `assert_equal`
- committing a new `example_2_sol.json` file on the `release/v1.7` branch and pointing to this specific commit on homebrew for `v1.7.0`
- temporarily removing the formula test just for `v1.7.0` and adding the example update step to our upstream workflow to avoid this problem in the future

Let me know what you think?

**Comment by dtrodrigues** [comment]
@ankane @SMillerDev thoughts on the suggestions from @jcoupey?

**Comment by SMillerDev** [comment]
Why not just fix the example files and retag as 1.7.1?

**Comment by jcoupey** [comment]
It would feel strange to do a patch release for this, especially as nothing would change in the codebase (also not so long ago, the provided solution used in the formula test was not even versioned).

However if this helps on the homebrew side, we could push a dedicated tag like `v1.7.0-homebrew` after the example update?

**Comment by SMillerDev** [comment]
I mean, your documentation is currently broken. Isn't that a good enough reason to make a bug fix release?

**Comment by ankane** [comment]
fwiw, to temporarily fix the test, the last line can be replaced with:

```ruby
actual_routes = JSON.parse(output)["routes"]
actual_routes.first["steps"].each { |r| r.delete("id") } # temp fix, remove in 1.7.1
assert_equal expected_routes, actual_routes
```

**Comment by dtrodrigues** [comment]
Thanks @ankane, I've included and force-pushed your suggestion.

@jcoupey, I do agree with @SMillerDev that both the example json (`example_2_sol.json`) as well as the docs (https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#examples) not matching the output of the current tool should be enough reason to create a bug-fix release so that users of the tool aren't confused when their output doesn't match the documented example output.

**Comment by jcoupey** [comment]
Of course I see your point and the provided second example is definitely not complete (and will be fixed). On the other hand, the authoritative part of the documentation is the [step description](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#steps) in output, which is correct. The examples are only provided for convenience with the mention "a solution that looks like".

Some parts of the output depend on hardware/setting and in some cases of the underlying routing engine, hence the formula test only relying on a subpart of the output. Also so far we've never committed to providing reproducible solutions (see also https://github.com/VROOM-Project/vroom/issues/145 on this) so the test only actually works as expected because the input is a really tiny toy example.

The temporary fix suggested by @ankane looks like a good way to go forward with `v1.7.0` without a patch release. We'd only have to drop it when reaching `v1.8` while I'm making sure we have upstream checks to prevent this issue from poping up again.

**Comment by dtrodrigues** [comment]
High Sierra doesn't have full C++17 support, snippet below along with full build output beneath that:
```
2020-07-09T23:56:35.6931110Z clang++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDEBUG -c algorithms/local_search/operator.cpp -o algorithms/local_search/operator.o
2020-07-09T23:56:35.6931570Z In file included from algorithms/local_search/operator.cpp:10:
2020-07-09T23:56:35.6931970Z In file included from ./algorithms/local_search/operator.h:13:
2020-07-09T23:56:35.6933340Z ./structures/typedefs.h:36:34: error: In file included from no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6933760Z algorithms/local_search/local_search.cpp:12:
2020-07-09T23:56:35.6934030Z In file included from ./algorithms/local_search/local_search.h:13:
2020-07-09T23:56:35.6934710Z In file included from ./structures/vroom/raw_route.h:15:
2020-07-09T23:56:35.6936040Z ./structures/typedefs.h:36:34: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6940160Z using OptionalCoordinates = std::optional;
2020-07-09T23:56:35.6940590Z                             ~~~~~^
2020-07-09T23:56:35.6941530Z using OptionalCoordinates = std::optional;
2020-07-09T23:56:35.6942810Z                             ~~~~~^
```

<details>
  <summary>Full output</summary>
  <pre>
2020-07-09T23:56:35.6920200Z ==> make
2020-07-09T23:56:35.6921650Z clang++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDEBUG -c main.cpp -o main.o
2020-07-09T23:56:35.6923140Z clang++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDEBUG -c algorithms/kruskal.cpp -o algorithms/kruskal.o
2020-07-09T23:56:35.6926610Z clang++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDEBUG -c algorithms/munkres.cpp -o algorithms/munkres.o
2020-07-09T23:56:35.6928110Z clang++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDEBUG -c algorithms/heuristics/solomon.cpp -o algorithms/heuristics/solomon.o
2020-07-09T23:56:35.6929610Z clang++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDEBUG -c algorithms/local_search/local_search.cpp -o algorithms/local_search/local_search.o
2020-07-09T23:56:35.6931110Z clang++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDEBUG -c algorithms/local_search/operator.cpp -o algorithms/local_search/operator.o
2020-07-09T23:56:35.6931570Z In file included from algorithms/local_search/operator.cpp:10:
2020-07-09T23:56:35.6931970Z In file included from ./algorithms/local_search/operator.h:13:
2020-07-09T23:56:35.6933340Z ./structures/typedefs.h:36:34: error: In file included from no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6933760Z algorithms/local_search/local_search.cpp:12:
2020-07-09T23:56:35.6934030Z In file included from ./algorithms/local_search/local_search.h:13:
2020-07-09T23:56:35.6934710Z In file included from ./structures/vroom/raw_route.h:15:
2020-07-09T23:56:35.6936040Z ./structures/typedefs.h:36:34: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6940160Z using OptionalCoordinates = std::optional<Coordinates>;
2020-07-09T23:56:35.6940590Z                             ~~~~~^
2020-07-09T23:56:35.6941530Z using OptionalCoordinates = std::optional<Coordinates>;
2020-07-09T23:56:35.6942810Z                             ~~~~~^
2020-07-09T23:56:35.6943200Z In file included from algorithms/kruskal.cpp:14:
2020-07-09T23:56:35.6943470Z In file included from ./algorithms/kruskal.h:13:
2020-07-09T23:56:35.6943870Z In file included from ./structures/generic/undirected_graph.h:17:
2020-07-09T23:56:35.6944380Z In file included from ./structures/generic/edge.h:13:
2020-07-09T23:56:35.6945800Z ./structures/typedefs.h:36:34: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6946250Z using OptionalCoordinates = std::optional<Coordinates>;
2020-07-09T23:56:35.6946600Z                             ~~~~~^
2020-07-09T23:56:35.6946900Z In file included from algorithms/local_search/local_search.cpp:12:
2020-07-09T23:56:35.6947120Z In file included from ./algorithms/local_search/local_search.h:13:
2020-07-09T23:56:35.6947350Z In file included from ./structures/vroom/raw_route.h:16:
2020-07-09T23:56:35.6947570Z In file included from ./structures/vroom/input/input.h:19:
2020-07-09T23:56:35.6947730Z In file included from ./routing/wrapper.h:16:
2020-07-09T23:56:35.6948570Z ./structures/vroom/location.h:22:3: error: unknown type name 'OptionalCoordinates'
2020-07-09T23:56:35.6948840Z   OptionalCoordinates _coords;
2020-07-09T23:56:35.6949070Z   ^
2020-07-09T23:56:35.6949290Z In file included from algorithms/local_search/operator.cpp:10:
2020-07-09T23:56:35.6949510Z In file included from ./algorithms/local_search/operator.h:14:
2020-07-09T23:56:35.6949740Z In file included from ./structures/vroom/input/input.h:19:
2020-07-09T23:56:35.6949960Z In file included from ./routing/wrapper.h:16:
2020-07-09T23:56:35.6950670Z ./structures/vroom/location.h:22:3: error: unknown type name 'OptionalCoordinates'
2020-07-09T23:56:35.6950940Z   OptionalCoordinates _coords;
2020-07-09T23:56:35.6951150Z   ^
2020-07-09T23:56:35.6951370Z In file included from algorithms/munkres.cpp:15:
2020-07-09T23:56:35.6951590Z In file included from ./algorithms/munkres.h:15:
2020-07-09T23:56:35.6951800Z In file included from ./structures/generic/matrix.h:16:
2020-07-09T23:56:35.6952630Z ./structures/typedefs.h:36:34: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6952890Z using OptionalCoordinates = std::optional<Coordinates>;
2020-07-09T23:56:35.6953490Z                             ~~~~~^
2020-07-09T23:56:35.6953730Z In file included from algorithms/heuristics/solomon.cpp:14:
2020-07-09T23:56:35.6953950Z In file included from ./algorithms/heuristics/solomon.h:13:
2020-07-09T23:56:35.6954360Z In file included from ./structures/vroom/input/input.h:19:
2020-07-09T23:56:35.6954630Z In file included from ./routing/wrapper.h:15:
2020-07-09T23:56:35.6954840Z In file included from ./structures/generic/matrix.h:16:
2020-07-09T23:56:35.6955700Z ./structures/typedefs.h:36:34: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6956090Z using OptionalCoordinates = std::optional<Coordinates>;
2020-07-09T23:56:35.6956230Z                             ~~~~~^
2020-07-09T23:56:35.6956450Z In file included from algorithms/heuristics/solomon.cpp:14:
2020-07-09T23:56:35.6956680Z In file included from ./algorithms/heuristics/solomon.h:13:
2020-07-09T23:56:35.6956910Z In file included from ./structures/vroom/input/input.h:19:
2020-07-09T23:56:35.6957140Z In file included from ./routing/wrapper.h:16:
2020-07-09T23:56:35.6958330Z ./structures/vroom/location.h:22:3: error: unknown type name 'OptionalCoordinates'
2020-07-09T23:56:35.6958580Z   OptionalCoordinates _coords;
2020-07-09T23:56:35.6958790Z   ^
2020-07-09T23:56:35.6958920Z In file included from algorithms/local_search/local_search.cpp:12:
2020-07-09T23:56:35.6959150Z In file included from ./algorithms/local_search/local_search.h:13:
2020-07-09T23:56:35.6959360Z In file included from ./structures/vroom/raw_route.h:16:
2020-07-09T23:56:35.6959590Z In file included from ./structures/vroom/input/input.h:24:
2020-07-09T23:56:35.6960400Z ./structures/vroom/vehicle.h:23:8: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6960680Z   std::optional<Location> start;
2020-07-09T23:56:35.6961420Z   ~~~~~^
2020-07-09T23:56:35.6962260Z ./structures/vroom/vehicle.h:24:8: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6962540Z   std::optional<Location> end;
2020-07-09T23:56:35.6962670Z   ~~~~~^
2020-07-09T23:56:35.6962870Z In file included from algorithms/local_search/operator.cpp:10:
2020-07-09T23:56:35.6963100Z In file included from ./algorithms/local_search/operator.h:14:
2020-07-09T23:56:35.6963310Z In file included from ./structures/vroom/input/input.h:24:
2020-07-09T23:56:35.6964230Z ./structures/vroom/vehicle.h:23:8: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6964530Z   std::optional<Location> start;
2020-07-09T23:56:35.6964750Z   ~~~~~^
2020-07-09T23:56:35.6965580Z ./structures/vroom/vehicle.h:24:8: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6965750Z   std::optional<Location> end;
2020-07-09T23:56:35.6965960Z   ~~~~~^
2020-07-09T23:56:35.6966750Z ./structures/vroom/vehicle.h:31:22: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6967050Z           const std::optional<Location>& start,
2020-07-09T23:56:35.6967270Z                 ~~~~~^
2020-07-09T23:56:35.6968080Z ./structures/vroom/vehicle.h:32:22: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6968340Z           const std::optional<Location>& end,
2020-07-09T23:56:35.6968570Z                 ~~~~~^
2020-07-09T23:56:35.6969280Z ./structures/vroom/vehicle.h:31:22: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6969560Z           const std::optional<Location>& start,
2020-07-09T23:56:35.6969770Z                 ~~~~~^
2020-07-09T23:56:35.6970580Z ./structures/vroom/vehicle.h:32:22: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6970860Z           const std::optional<Location>& end,
2020-07-09T23:56:35.6971080Z                 ~~~~~^
2020-07-09T23:56:35.6971290Z In file included from algorithms/heuristics/solomon.cpp:14:
2020-07-09T23:56:35.6971530Z In file included from ./algorithms/heuristics/solomon.h:13:
2020-07-09T23:56:35.6971760Z In file included from ./structures/vroom/input/input.h:24:
2020-07-09T23:56:35.6973040Z ./structures/vroom/vehicle.h:23:8: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6973300Z   std::optional<Location> start;
2020-07-09T23:56:35.6973430Z   ~~~~~^
2020-07-09T23:56:35.6974340Z ./structures/vroom/vehicle.h:24:8: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6974630Z   std::optional<Location> end;
2020-07-09T23:56:35.6974840Z   ~~~~~^
2020-07-09T23:56:35.6975640Z ./structures/vroom/vehicle.h:31:22: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6975900Z           const std::optional<Location>& start,
2020-07-09T23:56:35.6976120Z                 ~~~~~^
2020-07-09T23:56:35.6976940Z ./structures/vroom/vehicle.h:32:22: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6977130Z           const std::optional<Location>& end,
2020-07-09T23:56:35.6977350Z                 ~~~~~^
2020-07-09T23:56:35.6977550Z 1 error generated.
2020-07-09T23:56:35.6977770Z make: *** [algorithms/kruskal.o] Error 1
2020-07-09T23:56:35.6977990Z make: *** Waiting for unfinished jobs....
2020-07-09T23:56:35.6978200Z 6 errors generated.
2020-07-09T23:56:35.6978410Z make: *** [algorithms/local_search/operator.o] Error 1
2020-07-09T23:56:35.6978540Z 1 error generated.
2020-07-09T23:56:35.6978760Z make: *** [algorithms/munkres.o] Error 1
2020-07-09T23:56:35.6978970Z In file included from main.cpp:19:
2020-07-09T23:56:35.6979180Z In file included from ./problems/vrp.h:13:
2020-07-09T23:56:35.6979410Z In file included from ./structures/vroom/solution/solution.h:15:
2020-07-09T23:56:35.6979620Z In file included from ./structures/vroom/job.h:15:
2020-07-09T23:56:35.6980450Z ./structures/typedefs.h:36:34: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6980720Z using OptionalCoordinates = std::optional<Coordinates>;
2020-07-09T23:56:35.6981280Z                             ~~~~~^
2020-07-09T23:56:35.6981510Z In file included from main.cpp:19:
2020-07-09T23:56:35.6981730Z In file included from ./problems/vrp.h:13:
2020-07-09T23:56:35.6981970Z In file included from ./structures/vroom/solution/solution.h:15:
2020-07-09T23:56:35.6982190Z In file included from ./structures/vroom/job.h:17:
2020-07-09T23:56:35.6983020Z ./structures/vroom/location.h:22:3: error: unknown type name 'OptionalCoordinates'
2020-07-09T23:56:35.6983270Z   OptionalCoordinates _coords;
2020-07-09T23:56:35.6983480Z   ^
2020-07-09T23:56:35.6983600Z In file included from main.cpp:22:
2020-07-09T23:56:35.6983810Z In file included from ./structures/vroom/input/input.h:24:
2020-07-09T23:56:35.6984760Z ./structures/vroom/vehicle.h:23:8: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6985060Z   std::optional<Location> start;
2020-07-09T23:56:35.6985270Z   ~~~~~^
2020-07-09T23:56:35.6986070Z ./structures/vroom/vehicle.h:24:8: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6986340Z   std::optional<Location> end;
2020-07-09T23:56:35.6986550Z   ~~~~~^
2020-07-09T23:56:35.6987260Z ./structures/vroom/vehicle.h:31:22: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6987550Z           const std::optional<Location>& start,
2020-07-09T23:56:35.6987760Z                 ~~~~~^
2020-07-09T23:56:35.6988550Z ./structures/vroom/vehicle.h:32:22: error: no template named 'optional' in namespace 'std'
2020-07-09T23:56:35.6988840Z           const std::optional<Location>& end,
2020-07-09T23:56:35.6989040Z                 ~~~~~^
2020-07-09T23:56:35.6989240Z 6 errors generated.
2020-07-09T23:56:35.6989450Z make: *** [algorithms/heuristics/solomon.o] Error 1
2020-07-09T23:56:35.6989590Z 6 errors generated.
2020-07-09T23:56:35.6989790Z make: *** [algorithms/local_search/local_search.o] Error 1
2020-07-09T23:56:35.6990010Z 6 errors generated.
2020-07-09T23:56:35.6990220Z make: *** [main.o] Error 1
2020-07-09T23:56:35.6990300Z
2020-07-09T23:56:35.6991050Z ==> Formula
2020-07-09T23:56:35.6991860Z Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vroom.rb
2020-07-09T23:56:35.6993080Z ==> Configuration
2020-07-09T23:56:35.6993340Z HOMEBREW_VERSION: 2.4.5
2020-07-09T23:56:35.6993590Z ORIGIN: https://github.com/Homebrew/brew
2020-07-09T23:56:35.6993830Z HEAD: 6d2c39579e22d0ee9baccdccdd8a12efb8b00304
2020-07-09T23:56:35.6994050Z Last commit: 8 hours ago
2020-07-09T23:56:35.6994980Z Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
2020-07-09T23:56:35.6995270Z Core tap HEAD: 7e819eb15749d1b25310784830c905b1b93c049a
2020-07-09T23:56:35.6995490Z Core tap last commit: 49 minutes ago
2020-07-09T23:56:35.6995720Z HOMEBREW_PREFIX: /usr/local
2020-07-09T23:56:35.6995930Z HOMEBREW_CACHE: /Users/brew/Library/Caches/Homebrew
2020-07-09T23:56:35.6996150Z HOMEBREW_COLOR: set
2020-07-09T23:56:35.6996370Z HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.SfTPm7vEfN/org.macosforge.xquartz:0
2020-07-09T23:56:35.6996620Z HOMEBREW_FAIL_LOG_LINES: 150
2020-07-09T23:56:35.6997320Z HOMEBREW_GIT_EMAIL: homebrew-test-bot@lists.sfconservancy.org
2020-07-09T23:56:35.6997590Z HOMEBREW_GIT_NAME: BrewTestBot
2020-07-09T23:56:35.6998370Z HOMEBREW_LOGS: /Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/logs
2020-07-09T23:56:35.6998640Z HOMEBREW_MAKE_JOBS: 6
2020-07-09T23:56:35.6998850Z HOMEBREW_NO_ANALYTICS: set
2020-07-09T23:56:35.6999060Z HOMEBREW_NO_AUTO_UPDATE: set
2020-07-09T23:56:35.6999270Z HOMEBREW_NO_EMOJI: set
2020-07-09T23:56:35.6999910Z CPU: hexa-core 64-bit penryn
2020-07-09T23:56:35.7000750Z Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
2020-07-09T23:56:35.7001020Z Clang: 10.0 build 1000
2020-07-09T23:56:35.7001240Z Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
2020-07-09T23:56:35.7001460Z Curl: 7.54.0 => /usr/bin/curl
2020-07-09T23:56:35.7001660Z Java: 14.0.1, 1.8.0_252
2020-07-09T23:56:35.7002850Z macOS: 10.13.6-x86_64
2020-07-09T23:56:35.7003080Z CLT: 10.1.0.0.1.1539992718
2020-07-09T23:56:35.7003210Z Xcode: 10.1
2020-07-09T23:56:35.7004350Z Error: vroom 1.7.0 did not build
2020-07-09T23:56:35.7004680Z XQuartz: 2.7.11 => /opt/X11
2020-07-09T23:56:35.7005560Z ==> ENV
2020-07-09T23:56:35.7005810Z HOMEBREW_CC: clang
2020-07-09T23:56:35.7006020Z HOMEBREW_CXX: clang++
2020-07-09T23:56:35.7006740Z MAKEFLAGS: -j6
2020-07-09T23:56:35.7006900Z CMAKE_PREFIX_PATH: /usr/local/opt/openssl@1.1:/usr/local
2020-07-09T23:56:35.7007140Z CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
2020-07-09T23:56:35.7007390Z CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
2020-07-09T23:56:35.7007620Z PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig
2020-07-09T23:56:35.7007860Z PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13
2020-07-09T23:56:35.7008090Z HOMEBREW_GIT: git
2020-07-09T23:56:35.7008290Z ACLOCAL_PATH: /usr/local/share/aclocal
2020-07-09T23:56:35.7009190Z PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/pkg-config/bin:/usr/local/opt/openssl@1.1/bin:/usr/bin:/bin:/usr/sbin:/sbin
2020-07-09T23:56:35.7009320Z
2020-07-09T23:56:35.7009520Z Logs:
2020-07-09T23:56:35.7010340Z      /Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/logs/vroom/01.make
2020-07-09T23:56:35.7011180Z      /Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/logs/vroom/00.options.out
2020-07-09T23:56:35.7012010Z      /Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/logs/vroom/01.make.cc
2020-07-09T23:56:35.7012860Z READ THIS: https://docs.brew.sh/Troubleshooting
2020-07-09T23:56:35.7013000Z
  </pre>
</details>

I've updated the formula to require macOS mojave or newer.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
🚀

**Pull request closed without merging**
