### PR TITLE
cadubi 1.3.1

### PR DESCRIPTION
**Pull request by matteocng**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Any chance you could add a `test do` block to this formula? Thanks!

**Comment by DomT4** [comment]
Could you chuck in a `man1.install "cadubi.1"` as well? Thanks!

**Comment by matteocng** [comment]
`assert_match version.to_s shell_output("#{bin}/cadubi -v")` doesn't work because cadubi [exits with 1](/statico/cadubi/blob/master/cadubi#L390). How should this be handled?

**Comment by mikemcquaid** [comment]
> matteocng commented 25 minutes ago
> assert_match version.to_s shell_output("#{bin}/cadubi -v") doesn't work because cadubi exits with 1. How should this be handled?

The second argument to `shell_output` allows you to specify the exit code e.g. `shell_output("#{bin}/cadubi -v", 1)`

**Comment by matteocng** [comment]
The [fix] (/statico/cadubi/commit//f079b6) for the Perl deprecation warnings that are causing the failure was merged into master, but the current, latest release doesn't include it. Should we apply the patch ourselves?

**Comment by mikemcquaid** [comment]
@matteocng Yep, sounds reasonable. Use a `patch do` with the URL as the commit URL with `.patch` appended.

**Comment by matteocng** [comment]
``assert_match version.to_s shell_output("#{bin}/cadubi -v", 1)``
Bot fails: "Unable to read terminal settings in GetControlChars".

``assert_match version.to_s, shell_output("script -q /dev/null #{bin}/cadubi -v", 1)``
El Capitan: '1' correctly detected. [Mavericks](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/784/version=mavericks/testReport/junit/brew-test-bot/mavericks/test_cadubi/) and [Yosemite](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/784/version=yosemite/testReport/junit/brew-test-bot/yosemite/test_cadubi/): fail, detecting a '0' error code (build #784).

I then copy-pasted the Ranger formula, which is also using "script -q", with a bogus added argument so that it would exit with '1':

``assert_match version.to_s, shell_output("script -q /dev/null ranger -c exitcodecheck", 0)``

[El Capitan](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/809/version=el_capitan/testReport/brew-test-bot/el_capitan/test_cadubi/): '1' correctly detected. [Mavericks](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/809/version=mavericks/testReport/brew-test-bot/mavericks/test_cadubi/) and [Yosemite](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/809/version=yosemite/testReport/brew-test-bot/yosemite/test_cadubi/): '0' detected (build #809).

I've made it work by always returning '0' and matching the whole version string for a bit more safety: no exact match done because cadubi appends `\x1b[0m` at the end of its output.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
