### PR TITLE
pyenv-pip-migrate: 20181205

### PR DESCRIPTION
**Pull request by samdoran**
Update to latest commit and following CalVer used in the current (and only) release. The project has not made a new release in quite some time and the current release contains bugs. There is an [open issue](https://github.com/pyenv/pyenv-pip-migrate/issues/6) asking for a new release. I figured using the latest commit on the stable branch would be an acceptable solution in the absence of on official release.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
We can't build formulae over untagged commits, unfortunately.

If the formulae doesn't work properly because of a lack of updates, that's probably a reason to deprecate it instead of using a commit that isn't part of a stable release.

**Comment by SMillerDev** [comment]
> I figured using the latest commit on the stable branch would be an acceptable solution in the absence of on official release.

No, this is against our requirements: https://docs.brew.sh/Acceptable-Formulae#stable-versions

**Comment by pfheatwole** [comment]
That plugin is not (to my knowledge) under active development, but I'm taking the lack of issues as evidence that HEAD is stable.

@samdoran Feel free to update your formula to https://github.com/pyenv/pyenv-pip-migrate/archive/v20181205.tar.gz

**Comment by chenrui333** [comment]
Thanks @pfheatwole!

**Review by chenrui333 — APPROVED** [review]

**Comment by samdoran** [comment]
@pfheatwole Somehow I overlooked there was a newer release available. Thank you for fixing that up.

**Pull request merged**
