### PR TITLE
kuto 0.3.6 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

```
kuto
  * GitHub repository too new (<30 days old)
```

### CODE REVIEW

**Comment by chenrui333** [comment]
just audit failure, should be good to go.

**Comment by SMillerDev** [comment]
Why should we add it if it fails the audit?

**Comment by chenrui333** [comment]
yeah, I can remove the audit failure, it only fails with the days notability.

**Comment by SMillerDev** [comment]
If we don't want to count that one it should be removed.

**Comment by chenrui333** [comment]
fair enough, I will reopen in couple of days.

**Comment by SMillerDev** [comment]
I'm not really against merging this, I think that rule and audit are already covert much better by the notability check. But if we're not going to respect the audit, let's just get rid of the rule.

**Pull request closed without merging**
