### PR TITLE
libomp 13.0.0

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Looks like this can't be built independently of LLVM anymore:
```
CMake Error at libomptarget/cmake/Modules/LibomptargetGetDependencies.cmake:29 (find_package):
  By not providing "FindLLVM.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LLVM", but
  CMake did not find one.

  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by carlocab** [comment]
This formula no longer builds on Linux without LLVM. I'm probably going to make this macOS-only. CC @Homebrew/linux

**Comment by Bo98** [comment]
That's going to break a lot of downstream projects. Let me check and see what has happened here.

**Comment by Bo98** [comment]
Ok caused by https://github.com/llvm/llvm-project/commit/f2f88f3e7a110b2d4d9da446e45f0dba040e62b2.

This is only an issue on Linux as `libomptarget` is only enabled on Linux.

It's possible it might only be using static parts of LLVM - in which case a `depends_on "llvm" => :build` will work. Worth seeing if that is the case or whether it will be using libLLVM.

**Comment by carlocab** [comment]
> That's going to break a lot of dependents. Let me check and see what has happened here.

Yep. I was thinking of just switching them to LLVM. But I guess seeing if we can just make LLVM a build dependency is worth a try.

**Comment by carlocab** [comment]
That didn't work, sadly:
```
CMake Error at libomptarget/src/CMakeLists.txt:28 (add_library):
  add_library cannot create target "omptarget" because an imported target
  with the same name already exists.


CMake Error at libomptarget/src/CMakeLists.txt:34 (target_compile_definitions):
  target_compile_definitions may only set INTERFACE properties on IMPORTED
  targets


CMake Error at libomptarget/src/CMakeLists.txt:35 (target_link_libraries):
  Cannot specify link libraries for target "omptarget" which is not built by
  this project.
```

**Comment by Bo98** [comment]
Could just disable it `-DOPENMP_ENABLE_LIBOMPTARGET=OFF` if it's not needed.

**Comment by carlocab** [comment]
Is that target not the `libomp` library file?

**Comment by Bo98** [comment]
No, `libomptarget` is a different library.

**Comment by carlocab** [comment]
Guess that worked. I hope no one was counting on `libomp` shipping `libomptarget`. If they were, they can always install `llvm`, I guess.

Thanks @Bo98!

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
