### PR TITLE
gnome-builder 3.32.0

### PR DESCRIPTION
**Pull request by alebcay**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by zbeekman** [comment]
failing patches

**Comment by zbeekman** [comment]
Someone needs to investigate whether the patch should be removed and how it should be updated.

IMO, the comment with that patch is insufficient, it should also detail upstream reports, and info about when it can be removed, how to update it.

**Comment by alebcay** [comment]
Looks like we need `webkit2gtk` (not yet a formula):

```
Dependency webkit2gtk-4.0 found: NO (tried pkgconfig and framework)
meson.build:268:0: ERROR: Dependency "webkit2gtk-4.0" not found, tried pkgconfig and framework
```

**Comment by tschoonj** [comment]
I think we are stuck with this particular release of `gnome-builder` now that `webkitgtk` has become a hard dependency.

We used to have a formula for `webkitgtk`, but it turned out to be a maintenance nightmare so it was moved to the boneyard.

**Pull request closed without merging**
