### PR TITLE
petsc: update to use hdf5-mpi

### PR DESCRIPTION
**Pull request by abhinavsns**
Petsc in general relies on openMPI, any other library is likely to use petsc and hdf5-mpi together.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by abhinavsns** [comment]
Hello! Checks have passed.

**Comment by abhinavsns** [comment]
Hi, Can anyone explain the issue here for not merging?

**Review by fxcoudert — CHANGES_REQUESTED** [review]
This calls for an increase of the `revision` to `revision 1`. Other than that, it makes sense and we should also do it for `petsc-complex` (to keep parity between the two).

**Comment by abhinavsns** [comment]
I accidentally synchronized the fork and the branch. Closing this one for cleaner version.

**Comment by abhinavsns** [comment]
Please see new PRs for petsc and petsc-complex. 
https://github.com/Homebrew/homebrew-core/pull/167477
https://github.com/Homebrew/homebrew-core/pull/167478

**Pull request closed without merging**
