### PR TITLE
gtk+3 3.22.28

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
Broken release:

````
dyld: lazy symbol binding failed: Symbol not found: _gdk_quartz_atom_to_pasteboard_type_libgtk_only
  Referenced from: /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
  Expected in: flat namespace

dyld: Symbol not found: _gdk_quartz_atom_to_pasteboard_type_libgtk_only
  Referenced from: /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
  Expected in: flat namespace

Abort trap: 6
````

**Comment by tschoonj** [comment]
Issue opened at https://gitlab.gnome.org/GNOME/gtk/issues/32

**Comment by tschoonj** [comment]
Interestingly, not a single test failed...

**Comment by ilovezfs** [comment]
🍨

**Pull request closed without merging**
