### PR TITLE
fakeroot 1.25.3

### PR DESCRIPTION
**Pull request by claui**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by claui** [comment]
Note: the upstream source tarball of the previous version, 1.24, has gone.

**Comment by SMillerDev** [comment]
What kind of feedback are you looking for?

**Comment by claui** [comment]
> What kind of feedback are you looking for?

@SMillerDev Sorry for not making that clear. I just need someone to approve the PR.

Could have self-approved but that’s not how we usually do it, right? Or is there an exception for `bump-formula-pr`-based PRs?

**Comment by SMillerDev** [comment]
You can't approve your own PRs. But CI is failing so I think that should be fixed first?

**Comment by claui** [comment]
> You can't approve your own PRs. But CI is failing so I think that should be fixed first?

Sorry, the audit failure used to be fake (it complained about the old upstream source tarball being gone).
Didn’t catch that there are more failures now.

**Comment by SMillerDev** [comment]
Rebased it to fix the syntax issues at least.

**Comment by SMillerDev** [comment]
The patches don't apply cleanly anymore unfortunately

**Comment by mitchblank** [comment]
> The patches don't apply cleanly anymore unfortunately

Specifically:
```
==> Applying 0001-Implement-openat-2-wrapper-which-handles-optional-ar.patch
patch -g 0 -f -p1 -i /private/tmp/fakeroot--patch-20201208-85637-bu17p1/0001-Implement-openat-2-wrapper-which-handles-optional-ar.patch
patching file libfakeroot.c
Hunk #1 succeeded at 2520 (offset 94 lines).
patching file wrapfunc.inp
Hunk #1 succeeded at 198 (offset 1 line).
cp -p /Users/brew/Library/Caches/Homebrew/downloads/446b9b9c92c24195ef463099617d6e92a00027a69e8ba4478a8a01b7d28e372b--0002-OS-X-10.10-introduced-id_t-int-in-gs-etpriority.patch /private/tmp/fakeroot--patch-20201208-85637-1qxiz2w/0002-OS-X-10.10-introduced-id_t-int-in-gs-etpriority.patch
==> Applying 0002-OS-X-10.10-introduced-id_t-int-in-gs-etpriority.patch
patch -g 0 -f -p1 -i /private/tmp/fakeroot--patch-20201208-85637-1qxiz2w/0002-OS-X-10.10-introduced-id_t-int-in-gs-etpriority.patch
patching file libfakeroot.c
Hunk #1 FAILED at 110.
Hunk #2 succeeded at 133 (offset 2 lines).
Hunk #3 succeeded at 1918 (offset 17 lines).
1 out of 3 hunks FAILED -- saving rejects to file libfakeroot.c.rej
patching file wrapfunc.inp
Hunk #1 succeeded at 146 with fuzz 2 (offset 1 line).
```

The debian bug they reference hasn't been marked as "fixed" or anything so it doesn't seem likely that the patches are completely unneeded now.  However they probably do need rebasing against the new upstream :-/

**Pull request closed without merging**
