### PR TITLE
logstash 7.10.1

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
Build from source?

**Review by Rylan12 — APPROVED** [review]

**Comment by fxcoudert** [comment]
This is wrong. This contains darwin-specific binaries in `logstash-7.10.1/jdk.app`. We should be able to install from actual sources.

**Comment by fxcoudert** [comment]
Please let's be very very conservative about bypassing audits, they are here for good reasons

**Comment by Rylan12** [comment]
@fxcoudert what's your proposed solution for this? There is no platform-independent source that we can use (unless I totally missed it). It's clear that the stable URL we are using isn't a binary URL as it does download a source archive. I think it's appropriate in this case to have the URL in the list.

**Pull request closed without merging**
