### PR TITLE
homebank 5.4.3

### PR DESCRIPTION
**Pull request by AAS**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by Rylan12 — DISMISSED** [review]

**Comment by Rylan12** [comment]
Thanks, @AAS!

**Comment by chenrui333** [comment]
oops. just about to update the license.

**Comment by chenrui333** [comment]
license header ref:

```
/*  HomeBank -- Free, easy, personal accounting for everyone.
 *  Copyright (C) 1995-2020 Maxime DOYEN
 *
 *  This file is part of HomeBank.
 *
 *  HomeBank is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  HomeBank is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
```

**Review by Rylan12 — APPROVED** [review]

**Comment by Rylan12** [comment]
No worries! Was going to open a separate PR but this works fine also!

**Pull request closed without merging**
