### PR TITLE
bash-snippets 1.17.1, install selected tools on one line

### PR DESCRIPTION
**Pull request by alexanderepstein**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alexanderepstein** [comment]
The install.sh can now handle running something like ```./install.sh --prefix=/file/path tool1 tool2 tool3 tool4``` I am not sure how to account for this in the formula.

**Comment by ilovezfs** [comment]
```
bash-3.2$ echo -n "--prefix=/foo/bar stocks weather"| sed -e 's/--prefix=\(.*\) .*/\1/'|grep -Eo "^[a-z/A-Z= -- .0-9]*"
/foo/bar stocks
```

**Comment by ilovezfs** [comment]
@alexanderepstein so for example

```
diff --git a/Formula/bash-snippets.rb b/Formula/bash-snippets.rb
index 4febb0c..18f1655 100644
--- a/Formula/bash-snippets.rb
+++ b/Formula/bash-snippets.rb
@@ -32,10 +32,12 @@ class BashSnippets < Formula
     if build.with? "all-tools"
       system "./install.sh", "--prefix=#{prefix}", "all"
     else
+      args = []
       %w[cheat cloudup crypt cryptocurrency currency geo movies newton qrify
          short siteciphers stocks taste todo weather ytview].each do |tool|
-        system "./install.sh", "--prefix=#{prefix}", tool if build.with? tool
+        args << tool if build.with? tool
       end
+      system "./install.sh", "--prefix=#{prefix}", *args
     end
   end
```
leads to
```
iMac-TMP:homebrew-core joe$ brew instal -dvs bash-snippets --with-stocks --with-weather --without-all-tools
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bash-snippets.rb
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170801-35762-1fgrza6.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bash-snippets.rb --verbose --debug --with-stocks --with-weather --without-all-tools
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bash-snippets.rb
==> Downloading https://github.com/alexanderepstein/Bash-Snippets/archive/v1.17.1.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/bash-snippets-1.17.1.tar.gz
==> Verifying bash-snippets-1.17.1.tar.gz checksum
tar xzf /Users/joe/Library/Caches/Homebrew/bash-snippets-1.17.1.tar.gz
==> ./install.sh --prefix=/usr/local/Cellar/bash-snippets/1.17.1 stocks weather
/usr/local/Cellar/bash-snippets/1.17.1 stocks
Installing stocks: Failure
Error copying file, try running install script as sudo
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: ./install.sh --prefix=/usr/local/Cellar/bash-snippets/1.17.1 stocks weather
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action:
```

**Comment by alexanderepstein** [comment]
Hopefully i fixed this by removing the spaces in the grep call so ```grep -Eo "^[a-z/A-Z= -- .0-9]*``` is now ```grep -Eo "^[a-z/A-Z=--.0-9]*```

**Comment by alexanderepstein** [comment]
If this doesn't work I should be able to replace the grep call entirely with ```cut -d " " -f 1```

**Comment by ilovezfs** [comment]
```
grep: invalid character range
```

**Comment by alexanderepstein** [comment]
Ah i was worried about that will just replace grep with cut.

**Comment by alexanderepstein** [comment]
Replaced grep with cut, should not get that error now.

**Review by ilovezfs — APPROVED** [review]

**Comment by alexanderepstein** [comment]
Want me to squash these commits?

**Comment by ilovezfs** [comment]
@alexanderepstein that would be great, and please add a note in the commit message about the change you've made to the installation method.

**Comment by alexanderepstein** [comment]
Let me know if that name works for you, can always change it.

**Comment by ilovezfs** [comment]
Thanks for the upgrade @alexanderepstein! Merged.

For future reference, the commit subject should just be `bash-snippets 1.17.1` regardless of what else is going on in the body of the commit message.

**Comment by alexanderepstein** [comment]
Ah I wasn't sure if you wanted the title to include something about the formula change, but now i get it. Thanks again for working with me to help optimize the formula

**Comment by ilovezfs** [comment]
You're welcome!

**Pull request merged**
