### PR TITLE
anttweakbar 1.16: update homepage url

### PR DESCRIPTION
**Pull request by VonUniGE**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Fails to compile on El Capitan and Yosemite:

```
g++ -c -O3 -Wall -fPIC -fno-strict-aliasing -D_MACOSX -ObjC++  -D__PLACEMENT_NEW_INLINE -I../include -I/usr/local/include -I/usr/X11R6/include -I/usr/include -o TwFonts.o TwFonts.cpp
In file included from TwColors.cpp:11:
In file included from ./TwPrecomp.h:65:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:80:
In file included from TwOpenGL.cpp:11:
In file included from ./TwPrecomp.h:65:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:80In file included from In file included from TwOpenGLCore.cpp:21/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:60:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Security.framework/Headers/SecItem.h:985:49: error: expected ';' after top level declarator
extern const CFStringRef kSecUseAuthenticationUI
                                                ^
:
```

**Comment by VonUniGE** [comment]
These build failures are not related to the proposed commit. Was it already the case with the current formula?

**Comment by VonUniGE** [comment]
Reading the documentation of **revision** (in the [source code](https://github.com/Homebrew/brew/blob/d6d681ca01f8acf6b8d5e66cc1ca67310e9b8913/Library/Homebrew/formula.rb#L1993)) 
```
# Used for creating new Homebrew versions of software without new upstream
# versions. For example, if we bump the major version of a library this
# {Formula} {.depends_on} then we may need to update the `revision` of this
# {Formula} to install a new version linked against the new library version.
# `0` if unset.
```
and this discussion https://github.com/Homebrew/brew/issues/38, I understand that it's not needed for a simple homepage update, so I remove it. If I understand well, the bottle build is then no more needed. The current build failures in El Capitan and Yosemite are probably caused by a change in the build environment.

Is it correct?

**Comment by ilovezfs** [comment]
@VonUniGE your reading is correct! PR merged :)

**Pull request merged**
