### PR TITLE
c*: Fix `Homebrew/NoFileutilsRmrf` RuboCop offenses

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

- Part of https://github.com/Homebrew/brew/pull/17705.
- Different approach from the previous massive PR - I'm splitting them up per-alphabet letter (ish) and letting CI do the full "no bottles" build. This is `c*`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by issyl0** [comment]
- `check_postgres`, `chapel` have some files we're trying to remove in `install` that don't exist.
- `ca-certificates` needs checking if `cert.pem` exists before trying to delete it in the postinstall.
- `cdktf` the test timed out, so let's try again or move it to its own PR.

**Comment by issyl0** [comment]
```
Error: 2 failed steps!
brew test --verbose cdktf
brew test --verbose couchdb-lucene
```

**Comment by issyl0** [comment]
Skipping the tests since they’re timeouts and not related to the changes (I don’t think). Adding the `CI-syntax-only` label.

**Comment by cho-m** [comment]
Cancelling current 14-x86_64 run as going on for 21 hours and logs appear to be stuck on `brew install ./cconv--0.6.3.sonoma.bottle.1.tar.gz`.

**Comment by issyl0** [comment]
I thought `ci-syntax-only` shouldn't do those things?

**Comment by cho-m** [comment]
> I thought `ci-syntax-only` shouldn't do those things?

Either run started before label or `setup_tests` job was not re-run after label (e.g. if using `Re-run failed jobs`).

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
