### PR TITLE
pulumi 1.2.0

### PR DESCRIPTION
**Pull request by pgavlin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by 0xCMP** [comment]
Was waiting for this to be merged and seems like the tests are broken because of a bad native gems unrelated to this PR

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
Thank you @pgavlin !

**Pull request closed without merging**
