### PR TITLE
lua-language-server 3.10.2

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by clason** [comment]
Version seems bad; will see if there's a quick fixup.

**Comment by clason** [comment]
@carlocab I guess I can make it write a logfile and check the contents. How would I do that in a formula?

**Comment by carlocab** [comment]
> I guess I can make it write a logfile and check the contents. How would I do that in a formula?

If you give me the shell script of what you want to do I can help you translate it.

> Or would it be enough to check for existence (much more robust against churn)?

Maybe. Or ideally, maybe check that the log doesn't contain references to `[Ee]rror`? (Or however the LSP specifies error logging, if any)

**Comment by clason** [comment]
Input is just `./bin/lua-language-server --logpath=.`; output would be `services.log` in the same directory, whose contents -- *mutatis mutandis* -- look like
```
[11:03:09.321][info] [#0:/Users/clason/build/lua-language-server/main.lua:68]: Lua Lsp startup, root: 	/Users/clason/build/lua-language-server
[11:03:09.321][info] [#0:/Users/clason/build/lua-language-server/main.lua:69]: ROOT:	/Users/clason/build/lua-language-server
[11:03:09.321][info] [#0:/Users/clason/build/lua-language-server/main.lua:70]: LOGPATH:	.
[11:03:09.321][info] [#0:/Users/clason/build/lua-language-server/main.lua:71]: METAPATH:	/Users/clason/build/lua-language-server/meta
[11:03:09.322][info] [#0:/Users/clason/build/lua-language-server/main.lua:72]: VERSION:	3.10.2
[11:03:09.346][info] [#0:script/proto/proto.lua:234]: Listen Mode: stdio
[11:03:09.346][info] [#0:script/service/service.lua:146]: 
========= Medical Examination Report =========
    --------------- Memory ---------------
        Total: 2.208 MB
        # 00 : 2.208 MB
        # 01 : 0.000 MB
        # 02 : 0.000 MB
        # 03 : 0.000 MB
        # 04 : 0.000 MB
    --------------- Coroutine ---------------
        Total:     0
        Running:   0
        Suspended: 0
        Normal:    0
        Dead:      0
    --------------- Cache ---------------
        Total: 1
        Dead:  0
    ---------------  RPC  ---------------
        Holdon:   0
        Waiting:  0
==============================================
```

**Comment by carlocab** [comment]
Could probably do something like
```ruby
test do
  pid = spawn bin/"lua-language-server", "--logpath=."
  sleep 5
  assert_predicate testpath/"services.log", :exist?
  refute_predicate testpath/"services.log", :empty?
ensure
  Process.kill "TERM", pid
end
```

**Comment by clason** [comment]
That worked! Looks much cleaner to me, too. Thank you!

**Review by carlocab — APPROVED** [review]

**Pull request merged**
