### PR TITLE
qt: fix linux test

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Trying to get Linux bottle restored. Probably okay to ignore macOS here and just do a separate bottle job for Linux only.

### CODE REVIEW

**Comment by cho-m** [comment]
Not sure if we need to do dependents tests on Linux or should just prioritize restoring bottle by merging and triggering bottle job (w/ self-hosted & extended timeout)

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
@cho-m I'm okay with a merge without bottles, and dispatching a separate bottle job on Linux

**Review by p-linnane — APPROVED** [review]

**Comment by fxcoudert** [comment]
Launched a bottle at https://github.com/Homebrew/homebrew-core/actions/runs/3726355193/jobs/6319748625

**Comment by cho-m** [comment]
> Launched a bottle at https://github.com/Homebrew/homebrew-core/actions/runs/3726355193/jobs/6319748625

@fxcoudert, I think that is running on GitHub runner which usually fails to build Qt.

We could just let `icu4c` PR build `qt` bottle as it has been rebased with this PR and has a revision bump. Only inconvenience is time for each run attempt (2~3 days), but that PR will occupy self-hosted runner anyways.

**Pull request merged**
