### PR TITLE
ironcli 0.0.22 (new formula)

### PR DESCRIPTION
**Pull request by rdallman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by apjanke** [comment]
Test is failing.

```
failed: brew test --verbose ironcli

Stacktrace

        Testing ironcli
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160403-25342-ktl9nk.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/ironcli.rb --verbose
==> /usr/local/Cellar/ironcli/0.0.22/bin/iron --version
Error: ironcli: failed
Expected /iron\ version\ 0\.0\.22\ \(HEAD\)/ to match "0.0.22\n".
```

Fails for me locally with the same error. Is the expected version correct?

And can we get rid of this "empty resources array" warning?

```
$ brew install ironcli
==> Using the sandbox
==> Downloading https://github.com/iron-io/ironcli/archive/0.0.22.tar.gz
==> Downloading from https://codeload.github.com/iron-io/ironcli/tar.gz/0.0.22
######################################################################## 100.0%
Warning: tried to stage empty resources array
==> go build -o iron
🍺  /usr/local/Cellar/ironcli/0.0.22: 2 files, 8.9M, built in 5 seconds
```

**Comment by rdallman** [comment]
> Fails for me locally with the same error. Is the expected version correct?
>
> And can we get rid of this "empty resources array" warning?

doh, sorry. fixed, thank you

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
