### PR TITLE
php@8.0 8.0.30

### PR DESCRIPTION
**Pull request by qiqizjl**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  /private/tmp/phpA8.0-20230804-68411-19gw1l/php-8.0.30/ext/openssl/openssl.c:1328:51: error: use of undeclared identifier 'RSA_SSLV23_PADDING'
          REGISTER_LONG_CONSTANT("OPENSSL_SSLV23_PADDING", RSA_SSLV23_PADDING, CONST_CS|CONST_PERSISTENT);
                                                           ^
  1 error generated.
```

**Comment by qiqizjl** [comment]
It seems that the dependent libraries are all openssl3. But PHP8.0 does not support OpenSSL3.0
. This doesn't seem to fix him. His corresponding dependency does not have the version of OpenSSL1.1.1

**Comment by qiqizjl** [comment]
> ```
>   /private/tmp/phpA8.0-20230804-68411-19gw1l/php-8.0.30/ext/openssl/openssl.c:1328:51: error: use of undeclared identifier 'RSA_SSLV23_PADDING'
>           REGISTER_LONG_CONSTANT("OPENSSL_SSLV23_PADDING", RSA_SSLV23_PADDING, CONST_CS|CONST_PERSISTENT);
>                                                            ^
>   1 error generated.
> ```

fxied

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @qiqizjl!

**Pull request merged**
