### PR TITLE
edencommon fb303 fbthrift fizz folly mvfst proxygen wangle watchman 2023.07.17.00

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
```
  CMake Error at CMakeLists.txt:106 (find_package):
    Could not find a package configuration file provided by "mvfst" with any of
    the following names:
  
      mvfstConfig.cmake
      mvfst-config.cmake
```

`fbthrift` now depends on [`mvfst`](https://github.com/facebookincubator/mvfst). The latter has no tagged releases, and is not available in core currently. I filed facebookincubator/mvfst#301 to ask `mvfst` maintainers to see if they are interested in providing weekly releases.

**Comment by carlocab** [comment]
`mvfst` is also an [optional dependency](https://github.com/facebook/proxygen/blob/d5aeea8770a1777051ee7f84496d7e07b4fd6226/CMakeLists.txt#L72-L74) of `proxygen`.

**Comment by carlocab** [comment]
`mvfst` also needs some fixes for new `fmt`. 🙃

**Comment by carlocab** [comment]
I'm thinking `quic::LocalErrorCode` needs a formatter specialisation?

**Comment by carlocab** [comment]
`fb303` fails with:
```
  CMake Error at /opt/homebrew/lib/cmake/fbthrift/FBThriftConfig.cmake:56 (find_package):
    Could not find a package configuration file provided by "mvfst" with any of
    the following names:
  
      mvfstConfig.cmake
      mvfst-config.cmake
  
    Add the installation prefix of "mvfst" to CMAKE_PREFIX_PATH or set
    "mvfst_DIR" to a directory containing one of the above files.  If "mvfst"
    provides a separate development package or SDK, be sure it has been
    installed.
  Call Stack (most recent call first):
    CMakeLists.txt:58 (find_package)
```

**Review by SMillerDev — APPROVED** [review]

**Review by carlocab — APPROVED** [review]

**Pull request merged**
