### PR TITLE
terraform 1.0.0

### PR DESCRIPTION
**Pull request by sc250024**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sc250024** [comment]
@chenrui333 I suppose we would want to keep the `terraform@0.15` alias? The `brew bump-formula-pr` automatically moved the alias. Not sure if that's correct or not.

**Review by chenrui333 — DISMISSED** [review]

**Review by chenrui333 — DISMISSED** [review]

**Comment by SMillerDev** [comment]
The terraform@0.15 should be a new PR and only if upstream actually intends to support this.

**Comment by chenrui333** [comment]
I will create a separate PR for 0.15 release train.

**Comment by chenrui333** [comment]
> The terraform@0.15 should be a new PR and only if upstream actually intends to support this.

Technically speaking, the 1.0.0 is just like a naming change (continuing release of 0.15.x), so things might diverge in the 1.x.x land, so I would vote for keeping `0.15.x`.

We have already talked about the versioned releases a lot in [terraform@0.14](https://github.com/Homebrew/homebrew-core/pull/75981) thread, folks love the versioned formulae and it helps their lives. From homebrew maintenance perspective, we can add deprecation notice to notify folks to move to the latest version.

**Comment by SMillerDev** [comment]
I do appreciate that people want this, and honestly I hate to be the person to say no here. But without assurance that upstream will publish fixes for security issues I can't, in good faith, support a merge of older versions. Especially seeing the nature of the tool.

As soon as that is addressed I'll (try to) be the first to accept it.

**Comment by sc250024** [comment]
@SMillerDev I was at HashiConf Europe today when they announced it. Seems like 1.0 will be the first truly stable version of Terraform that will have some semblance of LTS support. I think any of the `0.1X` versions at this point should be migrated, but people need time obviously. Up to you guys.

**Review by chenrui333 — DISMISSED** [review]

**Comment by SMillerDev** [comment]
For people who want the older versions: upstream has a tap with all historical versions for you to use. That's really the easiest way.

**Comment by sc250024** [comment]
Why was this closed?

**Comment by SMillerDev** [comment]
Because it was merged.

>  @BrewTestBot closed this in cf75e37 8 minutes ago

**Comment by sc250024** [comment]
Ah ok, thank you!

**Pull request closed without merging**
