### PR TITLE
hadolint 1.2.4

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by zemanlx** [comment]
@ilovezfs you are fast. I was trying to build new formula with [linuxbrew](http://linuxbrew.sh/) and I was succesful with the following https://github.com/Homebrew/homebrew-core/compare/master...zemanlx:hadolint-1.2.4
I had to add a constraint for ShellCheck as new version 0.4.7 is not compatible with the previous one.

**Comment by ilovezfs** [comment]
Reported https://github.com/hadolint/hadolint/issues/143

**Comment by ilovezfs** [comment]
Thanks @zemanlx. I've updated the PR with your workaround :)

**Comment by zemanlx** [comment]
@ilovezfs `hadolint` has been also moved under GitHub organisation `hadolint` so it is no longer
 
https://github.com/lukasmartinelli/hadolint
but 
https://github.com/hadolint/hadolint

How can we update it for next release?

**Pull request closed without merging**
