### PR TITLE
xonsh 0.12.5

### PR DESCRIPTION
**Pull request by PythonCoderAS**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
`/usr/local/Cellar/xonsh/0.12.5/bin` is not created and it looks like the installation is empty.

The upstream doc says something about a flag that needs to be added to the `pip install` step:
https://xon.sh/packages.html

`pip install 'xonsh[full]'`

**Comment by PythonCoderAS** [comment]
The flag is for extra features. The base executable should just work without them.

**Comment by PythonCoderAS** [comment]
Can tests be re-queued? I think it was a fluke.

**Comment by SMillerDev** [comment]
It was unlikely that an empty install is a fluke, but a re-run confirms it.

**Comment by PythonCoderAS** [comment]
Further investigation lead to this being installed via pip:

```$ ./pip list
Package        Version
-------------- -------
numpy          1.22.4
Pillow         9.1.1
pip            22.0.4
prompt-toolkit 3.0.29
protobuf       3.19.4
Pygments       2.12.0
pyperclip      1.8.2
setproctitle   1.2.3
setuptools     60.10.0
UNKNOWN        0.0.0
wcwidth        0.2.5
wheel          0.37.1
```

**Comment by SMillerDev** [comment]
So... not xonsh then?

**Comment by PythonCoderAS** [comment]
> So... not xonsh then?

My suspicions are that xonsh is the `unknown`. Looking through the `setup.py` of the tarball confirms it:

https://gist.github.com/PythonCoderAS/2e3e300ce9e50db39ca4308df5c587cc

**Comment by PythonCoderAS** [comment]
When installing from PyPi, xonsh uses wheels. Interesting to note, when running `pip install --verbose --upgrade --force --no-binary :all: xonsh`, pip is forced to downgrade.

https://gist.github.com/PythonCoderAS/483e95967756f3146e2feb52029ad470

**Comment by PythonCoderAS** [comment]
xonsh has an open issue: https://github.com/xonsh/xonsh/issues/4807

**Pull request closed without merging**
