### PR TITLE
cacli 1.2.29 (new formula)

### PR DESCRIPTION
**Pull request by bourdakos1**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
I see the project is using Go Modules.
It would be great if you could drop the GOPATH stuff.

This should be enough for `def install`:

```ruby
 cd "cacli" do
      project = "github.com/cloud-annotations/training/cacli"
      system "go", "build",
             "-ldflags", "-s -w -X #{project}/version.Version=#{version}",
             "-o", bin/"cacli"
  end
```

**Comment by bourdakos1** [comment]
Oh yes, thank you, that works :) 

updated `def install`

**Comment by SMillerDev** [comment]
Thanks @bourdakos1! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by bourdakos1** [comment]
Thank you!

**Pull request closed without merging**
