### PR TITLE
linkerd 0.8.6

### PR DESCRIPTION
**Pull request by apakulov**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
Test is failing on Sierra: https://bot.brew.sh/job/Homebrew%20Core/16201/

**Comment by ilovezfs** [comment]
Closing due to inactivity.

**Comment by ilovezfs** [comment]
@apakulov thanks for the PR nonetheless.

**Pull request closed without merging**
