### PR TITLE
mlkit 4.3.12

### PR DESCRIPTION
**Pull request by FranklinChen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
https://github.com/melsman/mlkit/releases/latest still points to 4.3.11

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Review by fxcoudert — APPROVED** [review]

**Comment by ilovezfs** [comment]
Sorry but I don't think we should ship this until it's clarified upstream. More often than not, when upstream has not designated something the latest release, and there's a newer tag, and I ask, they say it's intentionally not marked the latest release and not to ship it. That may or may not be the case here, but we need these releases treated consistently on GitHub to make sure we're not getting ahead of our skis. If they want us to just go by tags, not explicit releases, then the old explicit releases should be deleted.

Thanks nonetheless @FranklinChen

**Comment by ilovezfs** [comment]
The author has confirmed we can use 4.3.12: https://github.com/melsman/mlkit/issues/21#issuecomment-392310214

**Comment by ilovezfs** [comment]
Thanks for another contribution to Homebrew @FranklinChen!

**Pull request closed without merging**
