### PR TITLE
bcftools 1.13

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
clang -rdynamic -L/usr/local/opt/htslib/lib  -o bcftools main.o vcfindex.o tabix.o vcfstats.o vcfisec.o vcfmerge.o vcfquery.o vcffilter.o filter.o vcfsom.o vcfnorm.o vcfgtcheck.o vcfview.o vcfannotate.o vcfroh.o vcfconcat.o vcfcall.o mcall.o vcmp.o gvcf.o reheader.o convert.o vcfconvert.o tsv2vcf.o vcfcnv.o HMM.o consensus.o ploidy.o bin.o hclust.o version.o regidx.o smpl_ilist.o csq.o vcfbuf.o mpileup.o bam2bcf.o bam2bcf_indel.o bam_sample.o vcfsort.o cols.o extsort.o dist.o abuf.o ccall.o em.o prob1.o kmin.o str_finder.o polysomy.o peakfit.o vcfplugin.o -lhts -lm -lz   -lgsl -lcblas  -lpthread
Undefined symbols for architecture x86_64:
  "_hts_idx_nseq", referenced from:
      _vcf_index_stats in vcfindex.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bcftools] Error 1
```

**Comment by danielnachun** [comment]
It's possible this is happening for the same reason as https://github.com/Homebrew/homebrew-core/pull/81066#issuecomment-878802074.  The LDFLAGS would need to come after the `-o` output.

**Comment by cho-m** [comment]
I think `bcftools`, `htslib`, and `samtools` need to be updated at same time (e.g. #73404).

`bcftools` v1.13 bundles `htslib` v1.13. Since we use Homebrew's `htslib` as dependency, this may be an API difference.

**Comment by danielnachun** [comment]
That sounds more correct than what I wrote.  @chenrui333 should we close this and open a new PR where we update all 3 formulae?

**Comment by SMillerDev** [comment]
Bumping htslib in https://github.com/Homebrew/homebrew-core/pull/81295

**Pull request closed without merging**
