### PR TITLE
Make python@3.9 the main python

### PR DESCRIPTION
**Pull request by fxcoudert**
Here we go…

### CODE REVIEW

**Comment by fxcoudert** [comment]
Testing cannot proceed because:

```
python@3.9:
  * Versioned formulae in homebrew/core should use `keg_only :versioned_formula`
```

**Comment by fxcoudert** [comment]
With this PR the output of `python3-config --cflags --ldflags --embed` (for python@3.9) is:

```
-I/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -L/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin -lpython3.9 -lintl -ldl -framework CoreFoundation```

Without the PR, it is currently (also for python@3.9):

```
-I/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/include/python3.9 -I/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/include/python3.9 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -L/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin -lpython3.9 -ldl -framework CoreFoundation
```

I do not know where the extra `-lintl` flag comes from, but it is wrong. It triggers test failures for `pybind11` and `boost-python3`.

**Comment by fxcoudert** [comment]
Testing this locally on 10.15, I cannot reproduce the issue. During python 3.9.0 compilation, I get:

```
checking libintl.h usability... no
checking libintl.h presence... no
checking for libintl.h... no
```

and

```
checking for textdomain in -lintl... no
```

The resulting python installation does not have `-lintl` in the output of `python3-config --cflags --ldflags --embed`

**Comment by fxcoudert** [comment]
On 10.13, looking good:

```
brew test --retry --verbose freeling
brew install googletest
brew test --retry --verbose pcl
brew linkage --test urh
```

- Fixing `urh` in https://github.com/Homebrew/homebrew-core/pull/63484
- Fixing `freeling` in https://github.com/Homebrew/homebrew-core/pull/63485
- `googletest` conflicts with `nss`: fixing in https://github.com/Homebrew/homebrew-core/pull/63486
- `pcl` does not find Eigen3: it's preexisting issue, something apparently broke it since https://github.com/Homebrew/homebrew-core/pull/62572

**Review by MikeMcQuaid — COMMENTED** [review]
Makes sense to me 👍🏻

**Comment by fxcoudert** [comment]
There is not switch in Python's configure to allow it to disable libintl if found.
We could configure with `ac_cv_lib_intl_textdomain=no`, or split this into two pull requests (but that might introduce some audits failures, and the question of the switching of the symlinks is not clear).

**Pull request closed without merging**
