### PR TITLE
aws-elasticbeanstalk 3.7.8

### PR DESCRIPTION
**Pull request by hameedullah**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by ilovezfs** [comment]
The resource blocks actually need to be updated as well.
```
  resource "blessed" do
    url "https://files.pythonhosted.org/packages/0f/56/2ff802d1a91ea50f7597328d6048aa3995b329b284c05d464aa24d6d5635/blessed-1.9.5.tar.gz"
    sha256 "b93b5c7600814638c0913c8325608327a24e3731977d9a4f003ecf37b08ca6e5"
  end

  resource "botocore" do
    url "https://files.pythonhosted.org/packages/54/4c/b217d400ff096970242fddc67086bb72ffd3c40a7486d4ac9200538ea51d/botocore-1.4.51.tar.gz"
    sha256 "e6216bf77f23c49eaae9fff4ad3903af2fbff0de92d2d730d8ca83447be33ad9"
  end

  resource "cement" do
    url "https://files.pythonhosted.org/packages/70/60/608f0b8975f4ee7deaaaa7052210d095e0b96e7cd3becdeede9bd13674a1/cement-2.8.2.tar.gz"
    sha256 "8765ed052c061d74e4d0189addc33d268de544ca219b259d797741f725e422d2"
  end

  resource "colorama" do
    url "https://files.pythonhosted.org/packages/f0/d0/21c6449df0ca9da74859edc40208b3a57df9aca7323118c913e58d442030/colorama-0.3.7.tar.gz"
    sha256 "e043c8d32527607223652021ff648fbb394d5e19cba9f1a698670b338c9d782b"
  end

  resource "docker-py" do
    url "https://files.pythonhosted.org/packages/2c/f8/719f2b240e2b546a8ee779ac74e54754ccf2f17baad728e89188d70e0b5f/docker-py-1.7.2.tar.gz"
    sha256 "95b1d14c4ae49dfbb724332cda9c63fb67628b8bdee79c321f2d405cf7a8d04c"
  end

  resource "dockerpty" do
    url "https://files.pythonhosted.org/packages/8d/ee/e9ecce4c32204a6738e0a5d5883d3413794d7498fe8b06f44becc028d3ba/dockerpty-0.4.1.tar.gz"
    sha256 "69a9d69d573a0daa31bcd1c0774eeed5c15c295fe719c61aca550ed1393156ce"
  end

  resource "docopt" do
    url "https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz"
    sha256 "49b3a825280bd66b3aa83585ef59c4a8c82f2c8a522dbe754a8bc8d08c85c491"
  end

  resource "docutils" do
    url "https://files.pythonhosted.org/packages/37/38/ceda70135b9144d84884ae2fc5886c6baac4edea39550f28bcd144c1234d/docutils-0.12.tar.gz"
    sha256 "c7db717810ab6965f66c8cf0398a98c9d8df982da39b4cd7f162911eb89596fa"
  end

  resource "jmespath" do
    url "https://files.pythonhosted.org/packages/8f/d8/6e3e602a3e90c5e3961d3d159540df6b2ff32f5ab2ee8ee1d28235a425c1/jmespath-0.9.0.tar.gz"
    sha256 "08dfaa06d4397f283a01e57089f3360e3b52b5b9da91a70e1fd91e9f0cdd3d3d"
  end

  resource "pathspec" do
    url "https://files.pythonhosted.org/packages/14/9d/c9d790d373d6f6938d793e9c549b87ad8670b6fa7fc6176485e6ef11c1a4/pathspec-0.3.4.tar.gz"
    sha256 "7605ca5c26f554766afe1d177164a2275a85bb803b76eba3428f422972f66728"
  end

  resource "python-dateutil" do
    url "https://files.pythonhosted.org/packages/3e/f5/aad82824b369332a676a90a8c0d1e608b17e740bbb6aeeebca726f17b902/python-dateutil-2.5.3.tar.gz"
    sha256 "1408fdb07c6a1fa9997567ce3fcee6a337b39a503d80699e0f213de4aa4b32ed"
  end

  resource "PyYAML" do
    url "https://files.pythonhosted.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.12.tar.gz"
    sha256 "592766c6303207a20efc445587778322d7f73b161bd994f227adaa341ba212ab"
  end

  resource "requests" do
    url "https://files.pythonhosted.org/packages/f9/6d/07c44fb1ebe04d069459a189e7dab9e4abfe9432adcd4477367c25332748/requests-2.9.1.tar.gz"
    sha256 "c577815dd00f1394203fc44eb979724b098f88264a9ef898ee45b8e5e9cf587f"
  end

  resource "semantic_version" do
    url "https://files.pythonhosted.org/packages/8e/0e/33052dd97ab9d07dae8ddffcfb2740efe58c46d72efbc060cf6da250439f/semantic_version-2.5.0.tar.gz"
    sha256 "3baad35dcb074a49419539cea6a33b484706b6c2dd03f05b67763eba4c1bb65c"
  end

  resource "six" do
    url "https://files.pythonhosted.org/packages/b3/b2/238e2590826bfdd113244a40d9d3eb26918bd798fc187e2360a8367068db/six-1.10.0.tar.gz"
    sha256 "105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a"
  end

  resource "texttable" do
    url "https://files.pythonhosted.org/packages/f5/5e/47cbc50187ca719a39ce4838182c6126487ca62ddd299bc34cafb94260fe/texttable-0.8.4.tar.gz"
    sha256 "8587b61cb6c6022d0eb79e56e59825df4353f0f33099b4ae3bcfe8d41bd1702e"
  end

  resource "wcwidth" do
    url "https://files.pythonhosted.org/packages/55/11/e4a2bb08bb450fdbd42cc709dd40de4ed2c472cf0ccb9e64af22279c5495/wcwidth-0.1.7.tar.gz"
    sha256 "3df37372226d6e63e1b1e1eda15c594bca98a22d33a23832a90998faa96bc65e"
  end

  resource "websocket-client" do
    url "https://files.pythonhosted.org/packages/a3/1e/b717151e29a70e8f212edae9aebb7812a8cae8477b52d9fe990dcaec9bbd/websocket_client-0.37.0.tar.gz"
    sha256 "678b246d816b94018af5297e72915160e2feb042e0cde1a9397f502ac3a52f41"
  end
```
which I generated with https://github.com/tdsmith/homebrew-pypi-poet

**Comment by hameedullah** [comment]
Should I add these or should I re-run poet on my system and add those and resubmit PR?

**Comment by dunn** [comment]
> Should I add these or should I re-run poet on my system and add those and resubmit PR?

You can update your PR by force-pushing to the same branch.

**Comment by ilovezfs** [comment]
@hameedullah you should do both! I ran poet "for you" this time so you should be able to outright replace all of the resource blocks in the formula with what I pasted above. However, it would be great if you could also try running poet yourself so that you can see how I got those resource blocks and know how to do it yourself next time :)

**Comment by hameedullah** [comment]
Thank you guys.. I really appreciate you guiding me through this. I already did installed poet but wasn't sure about it, gonna update the PR ASAP with updated resource block.

**Comment by hameedullah** [comment]
@ilovezfs I have updated the PR.

**Comment by MikeMcQuaid** [comment]
Test is failing: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/7151/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_aws_elasticbeanstalk/

Install is failing on Mavericks: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/7151/version=mavericks/testReport/junit/brew-test-bot/mavericks/install_aws_elasticbeanstalk/

**Comment by ilovezfs** [comment]
Try adding
```
  resource "setuptools" do
    url "https://files.pythonhosted.org/packages/32/3c/e853a68b703f347f5ed86585c2dd2828a83252e1216c1201fa6f81270578/setuptools-26.1.1.tar.gz"
    sha256 "475ce28993d7cb75335942525b9fac79f7431a7f6e8a0079c0f2680641379481"
  end
```
as the first resource.

**Comment by hameedullah** [comment]
I found out that the output generated by poet is also missing backports.ssl_match_hostname so I have added that as well by running poet on that package explicitly and adding the resource clause.

**Comment by ilovezfs** [comment]
`poet --single` is good for that.

**Comment by ilovezfs** [comment]
@hameedullah would you also like to try converting this over to use the new virtualenv feature? Here's an example: https://github.com/Homebrew/homebrew-core/commit/355cc94c56fa806d4797e65c3b0ea9303261c999

**Comment by hameedullah** [comment]
@ilovezfs  I tried to convert to new virtualenv feature but I am getting failed 'brew link' at the end:

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/eb_completion.bash
Target /usr/local/bin/eb_completion.bash
already exists. You may want to remove it:
  rm '/usr/local/bin/eb_completion.bash'

To force the link and overwrite all conflicting files:
  brew link --overwrite aws-elasticbeanstalk

To list all files that would be deleted:
  brew link --overwrite --dry-run aws-elasticbeanstalk

Possible conflicting files are:
/usr/local/bin/eb_completion.bash
```

**Comment by tdsmith** [comment]
> I found out that the output generated by poet is also missing backports.ssl_match_hostname

Are you sure it's still required?

**Comment by hameedullah** [comment]
@tdsmith good point, I just tried it without back ports, I am able use eb command line just fine. So to be honest I am not sure if its still required or not.

**Comment by ilovezfs** [comment]
@hameedullah you should be able to do this:
```
diff --git a/Formula/aws-elasticbeanstalk.rb b/Formula/aws-elasticbeanstalk.rb
index 8ef5e3e..6be1c3c 100644
--- a/Formula/aws-elasticbeanstalk.rb
+++ b/Formula/aws-elasticbeanstalk.rb
@@ -1,4 +1,6 @@
 class AwsElasticbeanstalk < Formula
+  include Language::Python::Virtualenv
+
   desc "Client for Amazon Elastic Beanstalk web service"
   homepage "https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-reference-eb.html"
   url "https://pypi.python.org/packages/a0/90/b86fe16aaea41c69d265d1b872ca73d2bfc07de85489273a31ac712489de/awsebcli-3.7.8.tar.gz"
@@ -109,17 +111,8 @@ class AwsElasticbeanstalk < Formula
   end
 
   def install
-    ENV.prepend_create_path "PYTHONPATH", libexec+"lib/python2.7/site-packages"
-
-    resources.each do |r|
-      r.stage { system "python", *Language::Python.setup_install_args(libexec) }
-    end
-
-    system "python", *Language::Python.setup_install_args(libexec)
-
+    virtualenv_install_with_resources
     bash_completion.install libexec/"bin/eb_completion.bash"
-    bin.install Dir[libexec/"bin/{eb,jp}"]
-    bin.env_script_all_files(libexec+"bin", :PYTHONPATH => ENV["PYTHONPATH"])
   end
 
   test do
```

**Comment by ilovezfs** [comment]
@hameedullah also the audit failure is legit
```
==> FAILED
Error: 1 problem in 1 formula
aws-elasticbeanstalk:
  * File should end with a newline
```

```
bash-3.2$ cat -vet Formula/aws-elasticbeanstalk.rb |tail -5
$
  test do$
    system "#{bin}/eb", "--version"$
  end$
end$
bash-3.2$ brew pull https://github.com/Homebrew/homebrew-core/pull/4450 &>/dev/null
bash-3.2$ cat -vet Formula/aws-elasticbeanstalk.rb |tail -5
$
  test do$
    system "#{bin}/eb", "--version"$
  end$
endbash-3.2$
```
As you can see the final line is missing its `\n` which causes the final `end` to appear on the same line as `bash-3.2$`. You can usually fix this just by opening the file in a text editor and re-saving it.
```
/usr/bin/ex -cwq Formula/aws-elasticbeanstalk.rb
```

**Comment by hameedullah** [comment]
Yes sorry about the audit failure that I missed in a hurry of trying to remove backports. I have just updated the PR fixing that audit part, let me try to to implement new virtualenv feature and update the PR.

**Comment by hameedullah** [comment]
Also seems like backports.ssl_match_hostname is indeed still required: pkg_resources.DistributionNotFound: The 'backports.ssl_match_hostname' distribution was not found and is required by websocket-client

https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/7200/version=mavericks/testReport/brew-test-bot/mavericks/test_aws_elasticbeanstalk/

**Comment by hameedullah** [comment]
I have added backports.ssl_match_hostname resource block again, fixed the audit issue with line ending and have implemented the new virtualenv feature.

**Comment by ilovezfs** [comment]
@hameedullah excellent work on this PR :100: Thanks for doing the conversion to virtualenv too!

**Pull request closed without merging**
