### PR TITLE
corral 0.5.7

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Building ../mort -> /private/tmp/corral-20220227-9[76](https://github.com/Homebrew/homebrew-core/runs/5349499313?check_suite_focus=true#step:6:76)22-1rxc43l/corral-0.5.7/corral/mort
  Error:
  pony_test: couldn't locate this path
  Error:
  /private/tmp/corral-20220227-[97](https://github.com/Homebrew/homebrew-core/runs/5349499313?check_suite_focus=true#step:6:97)622-1rxc43l/corral-0.5.7/corral/logger/_test.pony:1:1: can't load package 'pony_test'
  use "pony_test"
  ^
  Error:
  /private/tmp/corral-20220227-97622-1rxc43l/corral-0.5.7/corral/cmd/script.pony:1:1: can't load package '../logger'
  use "../logger"
  ^
  Error:
  pony_test: couldn't locate this path
  Error:
  /private/tmp/corral-20220227-97622-1rxc43l/corral-0.5.7/corral/cmd/_test_cmd_update.pony:3:1: can't load package 'pony_test'
  use "pony_test"
  ^
  Error:
  pony_test: couldn't locate this path
  Error:
  /private/tmp/corral-20220227-97622-1rxc43l/corral-0.5.7/corral/cmd/_test.pony:1:1: can't load package 'pony_test'
  use "pony_test"
  ^
  Error:
  /private/tmp/corral-20220227-97622-1rxc43l/corral-0.5.7/corral/main.pony:2:1: can't load package 'cmd'
  use "cmd"
  ^
  make: *** [build/release/corral] Error 255
```

**Comment by Porkepix** [comment]
Considering this seems closely linked with ponyc and that it was updated with https://github.com/Homebrew/homebrew-core/pull/95936 might be worth doing a retry?

**Comment by Bo98** [comment]
Rebase on the latest master to pull that in.

**Comment by Porkepix** [comment]
Looks like it's closely linked with `ponyc` and tests are fixed with the rebase.

**Review by Bo98 — APPROVED** [review]

**Pull request closed without merging**
