### PR TITLE
egctl 1.1.0

### PR DESCRIPTION
**Pull request by branchv**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Autobump had an issue with the PR body being too large: https://github.com/Homebrew/homebrew-core/actions/runs/10105167166/job/27945251050#step:6:4309

### CODE REVIEW

**Review by zirain — COMMENTED** [review]
LGTM

**Review by iMichka — APPROVED** [review]

**Comment by zirain** [comment]
@branchvincent do you think is a good idea to put the release notes link instead of the content in the PR description?
```ruby
          if github_release_data.present?
            pre = "pre" if github_release_data["prerelease"].present?
            pr_message += <<~XML
              <details>
                <summary>#{pre}release notes</summary>
                <pre>#{github_release_data["body"]}</pre>
              </details>
            XML
          end
```

**Comment by branchvincent** [comment]
@zirain it's useful to see the release notes in the PR description without having to navigate to a different page (like dependabot does)

I think we should just make sure we truncate to a reasonable length to avoid the error here

**Comment by zirain** [comment]
what about replace with link when the body is too large?

**Comment by branchvincent** [comment]
To me, it's more useful to always see the release notes in the PR description and just truncate if needed. But perhaps other maintainers have a different opinion, feel free to open a PR to start a discussion

**Comment by zirain** [comment]
> To me, it's more useful to always see the release notes in the PR description and just truncate if needed. But perhaps other maintainers have a different opinion, feel free to open a PR to start a discussion

how about replace it with link when the body is too large(maximum is 65536 character)?

**Comment by branchvincent** [comment]
please open a PR if you want to discuss further

**Pull request merged**
