### PR TITLE
cpp-netlib 0.12: fix bad package, use Github

### PR DESCRIPTION
**Pull request by theopolis**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by theopolis** [comment]
The package hosted on `cpp-netlib.org` does not reflect the SHASUM from Github. Furthermore, it is breaking out tests with a segfault, https://github.com/facebook/osquery/issues/2033, we suspect the package was taken from master and not the `0.12-final` tag. Either way, it feels safer to use the exact tag from Github.

**Comment by theopolis** [comment]
Seems like the source of the issue is rather benign, the `cpp-netlib.org`-provided tarball bundles boost and ASIO within. That leads to several problems when building/linking inside brew, assuming a brew-controlled set of dependent libraries.

We definitely need this to land, otherwise anyone linking the current brew-provided cpp-netlib will run into similar ODR (and other oddities) issues.

**Comment by mikemcquaid** [comment]
> Either way, it feels safer to use the exact tag from Github.

In this case can you consider adding a `revision 1` line to make sure people are `brew upgrade`d to the right version? Thanks!

**Comment by theopolis** [comment]
Right, sorry for not bumping the `revision` originally!

**Comment by mikemcquaid** [comment]
@theopolis Sorry, can you add it outside the `bottle` block?

**Comment by theopolis** [comment]
Done! Mind real quick helping me understand the placement difference? :D

**Comment by tdsmith** [comment]
The bottles and the formulas each have a revision concept; the formula revision (but not the bottle revision) is used in version comparisons. We can push new bottles without increasing the formula version, or we can mark existing installations outdated by increasing the formula revision.

**Comment by theopolis** [comment]
Woot, thanks Tim

**Pull request closed without merging**
