### PR TITLE
dnsdist 1.3.3

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
You might need to play with `ENV["SDKROOT"] = MacOS.sdk_path if MacOS.version == :sierra` to get it building on Sierra.

**Comment by alebcay** [comment]
[That's already in the formula](https://github.com/Homebrew/homebrew-core/pull/37396/files#diff-246659b6956181f585f719092d6422e0L19), and the formula is on High Sierra right now, so I'll try making it `<= :high_sierra` and see if that fixes the High Sierra build.

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by zbeekman** [comment]
@BrewTestBot test this please

**Comment by zbeekman** [comment]
@BrewTestBot test this please

**Comment by Habbie** [comment]
@BrewTestBot test this please

**Comment by zbeekman** [comment]
@BrewTestBot test this please

**Comment by zbeekman** [comment]
high sierra C++ breakage:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/functional:720:29: note: '::std::greater' declared here
struct _LIBCPP_TEMPLATE_VIS greater : binary_function<_Tp, _Tp, bool>
                            ^
In file included from dns.cc:25:
In file included from ./dns.hh:28:
In file included from ./qtype.hh:27:
In file included from ./namespaces.hh:29:
In file included from /usr/local/include/boost/any.hpp:20:
In file included from /usr/local/include/boost/type_index.hpp:29:
In file included from /usr/local/include/boost/type_index/stl_type_index.hpp:47:
In file included from /usr/local/include/boost/container_hash/hash.hpp:21:
In file included from /usr/local/include/boost/container_hash/detail/hash_float.hpp:14:
In file included from /usr/local/include/boost/container_hash/detail/float_functions.hpp:14:
In file included from /usr/local/include/boost/config/no_tr1/cmath.hpp:21:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:320:7: error: no member named 'isgreaterequal' in the global namespace; did you mean '::std::greater_equal'?
using ::isgreaterequal;
      ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/functional:749:29: note: '::std::greater_equal' declared here
struct _LIBCPP_TEMPLATE_VIS greater_equal : binary_function<_Tp, _Tp, bool>
                            ^
In file included from dns.cc:25:
In file included from ./dns.hh:28:
In file included from ./qtype.hh:27:
In file included from ./namespaces.hh:29:
In file included from /usr/local/include/boost/any.hpp:20:
In file included from /usr/local/include/boost/type_index.hpp:29:
In file included from /usr/local/include/boost/type_index/stl_type_index.hpp:47:
In file included from /usr/local/include/boost/container_hash/hash.hpp:21:
In file included from /usr/local/include/boost/container_hash/detail/hash_float.hpp:14:
In file included from /usr/local/include/boost/container_hash/detail/float_functions.hpp:14:
In file included from /usr/local/include/boost/config/no_tr1/cmath.hpp:21:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:321:9: error: no member named 'isless' in the global namespace
using ::isless;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:322:9: error: no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:323:9: error: no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:324:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
13 errors generated.
```

**Pull request closed without merging**
