### PR TITLE
duck 6.3.4

### PR DESCRIPTION
**Pull request by dkocher**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
It seems there is already a 6.3.5

**Comment by dkocher** [comment]
The 6.3.5 was a hotfix only relevant for Windows.

**Comment by fxcoudert** [comment]
Thanks!

(Can you look at the script that generates this pull request, and adjust the commit message to the `duck 6.3.4` format please?)

**Comment by dkocher** [comment]
On 12 Jan 2018, at 09:34, FX Coudert <notifications@github.com> wrote:
> 
> Thanks!
> 
> (Can you look at the script that generates this pull request, and adjust the commit message to the duck 6.3.4 format please?)

Will do.

**Pull request closed without merging**
