### PR TITLE
terminal-notifier 1.8.0

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by julienXX** [comment]
@zmwangx thanks you're fast :) Let me know if you need some help, there were quite a few maybe breaking changes with this release.

**Comment by fxcoudert** [comment]
```
==> xcodebuild -project Terminal Notifier.xcodeproj -target terminal-notifier SYMROOT=build -verbose
Build settings from command line:
    SYMROOT = build

=== BUILD TARGET terminal-notifier OF PROJECT Terminal Notifier WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
No signing certificate "Mac Development" found:  No "Mac Development" signing certificate matching team ID "LF74623VJR" with a private key was found.

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by zmwangx** [comment]
Disabled codesign.

**Comment by fxcoudert** [comment]
Thanks @zmwangx for the pull request!

**Pull request closed without merging**
