### PR TITLE
boost@1.61: rename from boost

### PR DESCRIPTION
**Pull request by ilovezfs**

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Let's see what happens 💥 🔥

**Comment by ilovezfs** [comment]
@MikeMcQuaid thoughts on :boat:ing?

**Comment by MikeMcQuaid** [comment]
@ilovezfs Gonna look at this today but I reckon we do whatever in core is require to not rerevision this e.g. https://github.com/Homebrew/brew/pull/1192 first.

**Comment by ilovezfs** [comment]
@MikeMcQuaid Homebrew/brew#1192 isn't necessary if the first step in the procedure is creating boost@1.62 alongside boost, not renaming boost to boost@1.61.

**Comment by MikeMcQuaid** [comment]
@ilovezfs I need to write up the steps better but I think this PRs rename should include an alias which in turn allows a pointer to `opt/boost`.

**Comment by ilovezfs** [comment]
Boost versioning can wait until the version procedures are honed further.

**Pull request closed without merging**
