### PR TITLE
gfold 4.3.2 (new formula)

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by ZhongRuoyu — COMMENTED** [review]
Since [it's using `git2`](https://github.com/nickgerace/gfold/blob/main/crates/gfold/Cargo.toml#L20), it should depend on `libgit2` and `pkg-config` I think. (`pkg-config` is used by the `libgit2-sys` crate to find the brewed `libgit2`; see its [`build.rs`](https://github.com/rust-lang/git2-rs/blob/master/libgit2-sys/build.rs#L16).) Like what was done in #124647. Otherwise it's very likely that a vendored `libgit2` will be used.

**Comment by chenrui333** [comment]
> Since [it's using `git2`](https://github.com/nickgerace/gfold/blob/main/crates/gfold/Cargo.toml#L20), it should depend on `libgit2` and `pkg-config` I think. (`pkg-config` is used by the `libgit2-sys` crate to find the brewed `libgit2`; see its [`build.rs`](https://github.com/rust-lang/git2-rs/blob/master/libgit2-sys/build.rs#L16).) Like what was done in #124647. Otherwise it's very likely that a vendored `libgit2` will be used.

that is good call.

**Review by ZhongRuoyu — DISMISSED** [review]

**Comment by carlocab** [comment]
We should check for linkage with `libgit2`, since it's too easy for `cargo` to silently start using a vendored one. This is likely what happened with `cargo-outdated`.

**Comment by chenrui333** [comment]
> We should check for linkage with `libgit2` in the `test` block, since it's too easy for `cargo` to silently start using a vendored one. This is what happened with `cargo-outdated`: the bottles in [354fc29](https://github.com/Homebrew/homebrew-core/commit/354fc294d34180a4b5e237192376d78939581972) have linkage with `libgit2`, but the ones in [9907655](https://github.com/Homebrew/homebrew-core/commit/99076553b5ffd0ac9878365f3eab0094e3de309a) don't.
> 
> The problem is that cargo-outdated 0.11.1 uses libgit2-sys v0.13.2+1.4.2, which [allows any version of `libgit2` that is newer than `1.4.0`](https://github.com/rust-lang/git2-rs/blob/0443adb5388b2a529c042256e7716c36dc567220/libgit2-sys/build.rs#L17), but cargo-outdated 0.11.2 uses libgit2-sys v0.13.5+1.4.5, which [allows only `libgit2` 1.4.*](https://github.com/rust-lang/git2-rs/blob/8c97ea151a293dca2de6014b06d9322a4ffbbf73/libgit2-sys/build.rs#L18).

make sense 👍

**Comment by carlocab** [comment]
Let's wait for #124227 to merge this, since this will likely need a rebuild (or a `libgit2@1.5` dependency) after that.

**Comment by ZhongRuoyu** [comment]
[Oops](https://github.com/Homebrew/homebrew-core/actions/runs/4404124047/jobs/7713499056#step:7:94):

```
Minitest::Assertion: No linkage with libgit2! Cargo is likely using a vendored version.
```

**Comment by ZhongRuoyu** [comment]
> or a `libgit2@1.5` dependency

Yeah, even the `libgit2-sys` crate's master doesn't have support for `libgit2` v1.6.2 yet: https://github.com/rust-lang/git2-rs/blob/master/libgit2-sys/build.rs#L20

**Review by carlocab — APPROVED** [review]

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request closed without merging**
