### PR TITLE
ghidra 9.0

### PR DESCRIPTION
**Pull request by mrjefftang**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by ajd394** [comment]
Ghidra is not open source. Does that mean it has to be a cask?

https://github.com/NationalSecurityAgency/ghidra/wiki/Frequently-asked-questions#where-is-the-complete-ghidra-source-code

**Comment by mrjefftang** [comment]
Most of the source is included in the zip file available for Ghidra.  They're all tagged as -src.zip.

A few components have only been released as a binary.

**Comment by ajd394** [comment]
@mrjefftang 
I think that the "no binary" requirement is that the formula be able to be built from source. I also think the open source requirement suggest that all source required to build must be available. Can it be build from source with the source provided? 

I would like to see this tool get merged as much as you but it does not appear to meet the acceptable formula requirements. 

https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

**Comment by mrjefftang** [comment]
This project falls somewhere in between formula and cask. It doesn't fit 1 definition or the other since it doesn't build a ".app" for Casks.

From Acceptable-Formulae
>Our policy is that formulae in the core tap (homebrew/core) must be open-source with an OSI-approved license and either built from source or produce cross-platform binaries (e.g. Java, Mono). Binary-only formulae should go to homebrew/cask.

The app is open-source but not built from source but it does produce cross-platform binaries in the form of Java JARs. The source is in the master zip file, it just hasn't been uploaded as a git repo to GitHub which will change.  So it's going to be silly to convert this back to a formula down the line.

**Comment by Gaelan** [comment]
IIRC part of Ghidra is written in C++ that isn't open source yet. Maybe wait on that, cask for now?

**Comment by SMillerDev** [comment]
Casks don't require an app file but core does require every part to be open source. This will have to be a cask.

**Comment by ajd394** [comment]
i think the new release 9.0.2 now open sourced the whole thing

**Pull request closed without merging**
