### PR TITLE
secp256k1 1 (new formula)

### PR DESCRIPTION
**Pull request by dtebbs**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Does your submission pass `brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by alexreg** [comment]
Why was this closed, may I ask?

**Comment by dtebbs** [comment]
After adding it (mainly in order to make my own life easier), I later closed it because it wasn't clear to me there would be a need to install it.
On reflection, I can't see a reason not to keep it, even it goes unused.  Apps can statically linking against specific versions, or specifying version ranges if they want.

Thanks for prompting me to rethink.  I can't reopen (because I did a force push since creating it), but I'll create a new PR.

**Comment by alexreg** [comment]
Thanks, that sounds good. It might make creating a formula for the Bitcoin daemon easier in the future, besides other projects potentially.

**Comment by dtebbs** [comment]
@alexreg, fyi re the new request, it looks like it won't happen until there is a stable release tagged ... https://github.com/Homebrew/homebrew-core/pull/559#issuecomment-213767983

**Pull request closed without merging**
