### PR TITLE
baresip libre librem 2.11.0

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> make SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr install PREFIX=/opt/homebrew/Cellar/libre/2.11.0 RELEASE=1 V=1
  make: *** No rule to make target `install'.  Stop.
```

**Comment by p-linnane** [comment]
Looks like they overhauled the build process using `cmake`. This all worked locally for me including tests, so trying it here.

**Comment by chenrui333** [comment]
> baresip libre librem: add to synced_versions

They are not always in sync, it should be removed.

**Comment by p-linnane** [comment]
@chenrui333 Thanks for the heads up. I dropped that commit.

**Comment by p-linnane** [comment]
Needs to be rebased after https://github.com/Homebrew/homebrew-core/pull/120422 is merged.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
