### PR TITLE
faust 2.27.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
license header ref:

```
    FAUST compiler, Version 2.27.2
    Copyright (C) 2003-2019 GRAME, Centre National de Creation Musicale
    ---------------------------------------------------------------------
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

----------------------------------------------------------------------------
```

**Comment by chenrui333** [comment]
```
[ 97%] Built target staticlib
[ 98%] Building CXX object CMakeFiles/dynamiclib.dir/tmp/faust-20200923-3244-3x3taw/faust-2.27.2/compiler/generator/llvm/llvm_dsp_aux.cpp.o
[ 98%] Linking CXX executable ../bin/faust
ld: library not found for -llibxml2.tbd
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [../bin/faust] Error 1
make[3]: *** [CMakeFiles/faust.dir/all] Error 2
[ 98%] Building CXX object CMakeFiles/dynamiclib.dir/tmp/faust-20200923-3244-3x3taw/faust-2.27.2/compiler/generator/llvm/llvm_dynamic_dsp_aux.cpp.o
[ 98%] Linking CXX shared library ../lib/libfaust.dylib
ld: library not found for -llibxml2.tbd
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [../lib/libfaust.2.27.2.dylib] Error 1
make[3]: *** [CMakeFiles/dynamiclib.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2

```

**Comment by chenrui333** [comment]
relates to https://discourse.brew.sh/t/llvm-config-10-0-1-advertise-libxml2-tbd-as-system-libs/8593/2

**Comment by chenrui333** [comment]
only build failed on 10.14 and 10.15

**Comment by chohner** [comment]
Why was this closed?

**Pull request closed without merging**
