### PR TITLE
protobuf 3.6.1.1

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
(The Perl-related testing failure on Mojave should have been fixed by now, let's just try again. 😉)

**Comment by Moisan** [comment]
Thank you @igas !

**Comment by jd-a** [comment]
Is it still working with clang 7? I get an error now.

**Comment by kkdd** [comment]
protobuf 3.6.1.1 is [incompatible with python 3.7 for now](https://github.com/protocolbuffers/protobuf/pull/4862).
Don't upgrade it with ``` --with-python```.

**Pull request closed without merging**
