### PR TITLE
aflplusplus 2.60c (new formula)

### PR DESCRIPTION
**Pull request by devnexen**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
What the bot says and also, is automake a runtime dependency?

**Comment by devnexen** [comment]
> What the bot says and also, is automake a runtime dependency?
No autoconf is build time dependency my bad. But the patch is that such an issue ? it s only one line change otherwise make install fails.

**Comment by SMillerDev** [comment]
Yes, homebrew policy forbids it. We're just packaging things and it's up to upstream to develop it. Remeber when [debian accidentally patched away encryption](https://www.debian.org/security/2008/dsa-1571)? Homebrew won't have any of that. No patches

**Comment by devnexen** [comment]
Ok ... will try to push a change upstream then.

**Comment by fxcoudert** [comment]
Closing for now, we'll revisit for a later version once the patch is not needed anymore.

**Pull request closed without merging**
