### PR TITLE
boost 1.61.0

### PR DESCRIPTION
**Pull request by UniqMartin**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

This replaces #1200 while maintaining commit credit of the original contributor. The commits have been rebased (with minor adjustments) on top of an up-to-date `master`. After 1.5 months it's time to finally get this merged, at which point we'll also be able to resurrect `folly`.

### CODE REVIEW

**Comment by DomT4** [comment]
I'm pretty sure the test on `pdnsrec` for Mavericks is failing for the reasons I discussed with @ilovezfs earlier in https://github.com/Homebrew/homebrew-core/pull/2895 😄.

**Comment by ilovezfs** [comment]
Yeah that should be fixed but not by messing up the formulae ;)

**Comment by ilovezfs** [comment]
Incidentally it looks like `-static-libgcc` is the way to avoid perpetual matrimonial bliss with gcc.

**Comment by UniqMartin** [comment]
Does this look ready to merge? Should I give an advance warning to the science team so they can prepare for the inevitable breakage this will cause for them? Anybody else?

> I'm pretty sure the test on `pdnsrec` for Mavericks is failing for the reasons I discussed with @ilovezfs earlier in https://github.com/Homebrew/homebrew-core/pull/2895 😄.

Thanks for the heads up! This doesn't seem to be a rabbit hole I'm willing to explore right now.

> Incidentally it looks like `-static-libgcc` is the way to avoid perpetual matrimonial bliss with gcc.

It may work for `libgcc`, but IIRC static linking is definitely not an option for `libstdc++` as correct propagation of exceptions and a few other C++ features depend on `libstdc++` being dynamically linked, unless *all* of the program and its dependencies is statically linked. This doesn't sound like a viable solution in most cases …

**Comment by ilovezfs** [comment]
Correct, it's just static linking for libgcc for the reasons you stated.

**Comment by ilovezfs** [comment]
@UniqMartin regarding the PR, :+1:

**Comment by DomT4** [comment]
I don't have everything tapped, but my `brew uses boost` list is:

<details>
<summary>Clicky</summary>
```
apngasm
arabica
asio
avro-cpp
boost-python
bulk_extractor
cclive
cgal
collada-dom
cpp-netlib
cpprestsdk
cucumber-cpp
dspdfviewer
echoprint-codegen
exempi
freeling
gearman
gnuradio
gource
highlight
innoextract
json_spirit
kitchen-sync
ledger
liblas
libmongoclient
libopkele
libphonenumber
libpst
librcsc
librevenge
libswiften
libtorrent-rasterbar
luabind
mal4s
mapnik
mdds
metaproxy
mkvtoolnix
mstch
ncmpcpp
nghttp2
ompl
openvdb
osm2pgrouting
osm2pgsql
osquery
pcb2gcode
pdal
pdns
pdnsrec
pgrouting
pktanon
plustache
points2grid
povray
pyexiv2
quantlib
rcssserver
sdcc
sfcgal
shibboleth-sp
simgrid
simple-amqp-client
source-highlight
srecord
supersonic
synfig
thrift
uhd
upscaledb
vowpal-wabbit
xml-tooling-c
yaml-cpp
homebrew/fuse/encfs
homebrew/fuse/ori
homebrew/gui/inkscape
homebrew/versions/ledger26
homebrew/versions/libmongoclient-legacy
homebrew/versions/thrift090
homebrew/x11/scantailor
```
</details>

So potentially Fuse, GUI, Versions & X11 all may need a look at by someone, somewhen after this is merged.

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ brew uses --include-build --include-optional boost
apngasm                                            vimpc                                            
apt-cacher-ng                                      vowpal-wabbit                                    
arabica                                            writerperfect                                    
asio                                               xml-tooling-c                                    
aspcud                                             yaml-cpp                                         
assimp                                             homebrew/boneyard/cppdom                         
avro-cpp                                           homebrew/boneyard/cvc4                           
boost-python                                       homebrew/boneyard/flusspferd                     
bulk_extractor                                     homebrew/boneyard/folly                          
cclive                                             homebrew/boneyard/htqc                           
cgal                                               homebrew/boneyard/justniffer                     
collada-dom                                        homebrew/boneyard/pagan                          
cpp-netlib                                         homebrew/boneyard/soccerwindow2                  
cpprestsdk                                         homebrew/fuse/encfs                              
cputhrottle                                        homebrew/fuse/ori                                
cucumber-cpp                                       homebrew/games/arx-libertatis                    
curlpp                                             homebrew/games/bastet                            
dspdfviewer                                        homebrew/games/c10t                              
echoprint-codegen                                  homebrew/games/easyrpg-player                    
exempi                                             homebrew/games/fuego                             
freeling                                           homebrew/games/mapcrafter                        
gearman                                            homebrew/games/mkhexgrid                         
gnuradio                                           homebrew/games/mupen64plus                       
gource                                             homebrew/games/openclonk                         
highlight                                          homebrew/games/rlvm                              
hyperscan                                          homebrew/games/snescom                           
innoextract                                        homebrew/games/supertux                          
joshua                                             homebrew/games/wesnoth                           
json_spirit                                        homebrew/gui/inkscape                            
kitchen-sync                                       homebrew/python/vpython                          
ledger                                             homebrew/science/abyss                           
libcdr                                             homebrew/science/alembic                         
libetonyek                                         homebrew/science/alpscore                        
libfreehand                                        homebrew/science/amos                            
libftdi                                            homebrew/science/arrayfire                       
liblas                                             homebrew/science/augustus                        
libmongoclient                                     homebrew/science/bali-phy                        
libmspub                                           homebrew/science/beetl                           
libodfgen                                          homebrew/science/biobloomtools                   
libpagemaker                                       homebrew/science/bioformats-cpp                  
libphonenumber                                     homebrew/science/blaze-lib                       
libpst                                             homebrew/science/bless                           
librcsc                                            homebrew/science/boost-compute                   
librevenge                                         homebrew/science/ckon                            
libswiften                                         homebrew/science/clblas                          
libtorrent-rasterbar                               homebrew/science/clfft                           
libvisio                                           homebrew/science/cmdstan                         
libwps                                             homebrew/science/cppad                           
logstalgia                                         homebrew/science/cufflinks                       
luabind                                            homebrew/science/dealii                          
mal4s                                              homebrew/science/delly                           
mapnik                                             homebrew/science/dgtal                           
mdds                                               homebrew/science/diamond                         
metaproxy                                          homebrew/science/dssp                            
mkvtoolnix                                         homebrew/science/dynare                          
mongodb                                            homebrew/science/enblend-enfuse                  
monotone                                           homebrew/science/express                         
mpd                                                homebrew/science/field3d                         
mstch                                              homebrew/science/fwdpp                           
mysql-connector-c++                                homebrew/science/galsim                          
ncmpcpp                                            homebrew/science/graph-tool                      
nghttp2                                            homebrew/science/gtsam                           
ompl                                               homebrew/science/joinx                           
openvdb                                            homebrew/science/kat                             
osm2pgrouting                                      homebrew/science/libsequence                     
osm2pgsql                                          homebrew/science/lobstr                          
osquery                                            homebrew/science/madlib                          
pcb2gcode                                          homebrew/science/meraculous                      
pdal                                               homebrew/science/mira                            
pdns                                               homebrew/science/mlpack                          
pdnsrec                                            homebrew/science/mtl                             
pgrouting                                          homebrew/science/nixio                           
pktanon                                            homebrew/science/nxtrim                          
plustache                                          homebrew/science/openimageio                     
points2grid                                        homebrew/science/orocos-kdl                      
povray                                             homebrew/science/paraview                        
pyexiv2                                            homebrew/science/pcl                             
quantlib                                           homebrew/science/pulseview                       
rcssserver                                         homebrew/science/pykep                           
rethinkdb                                          homebrew/science/quake                           
sdcc                                               homebrew/science/rstudio-server                  
sfcgal                                             homebrew/science/sailfish                        
shibboleth-sp                                      homebrew/science/salmon                          
simgrid                                            homebrew/science/shark                           
simple-amqp-client                                 homebrew/science/statismo                        
snappystream                                       homebrew/science/tophat                          
soci                                               homebrew/science/trilinos                        
source-highlight                                   homebrew/science/vislcg3                         
srecord                                            homebrew/science/vtk                             
stuntman                                           homebrew/science/xylib                           
supersonic                                         homebrew/versions/ledger26                       
synfig                                             homebrew/versions/libmongoclient-legacy          
tcpflow                                            homebrew/versions/mongodb26                      
thrift                                             homebrew/versions/mongodb30                      
uhd                                                homebrew/versions/thrift090                      
upscaledb                                          homebrew/x11/scantailor                          
```

**Comment by ilovezfs** [comment]
@UniqMartin I believe @tdsmith requested a heads up for potentially breaking changes for science and some grace period to fix problems. I wonder if we should temporarily tap homebrew/science and re-run this PR through test-bot?

**Comment by UniqMartin** [comment]
> I wonder if we should temporarily tap homebrew/science and re-run this PR through test-bot?

Does that work? I haven't tried this before. And what do you think we should do with the outcome of such a test bot run? I think the only thing we'll learn is how many formulae will break, assuming they have tests that will disclose this. (But maybe that's exactly what you had in mind.)

**Comment by ilovezfs** [comment]
In science, I set Jenkins to do this:
```
GIT_WORK_TREE=/usr/local GIT_DIR=/usr/local/.git git reset --hard origin/master
brew update
brew tap homebrew/python
brew tap homebrew/x11
brew test-bot --ci-pr
```
and that's worked well to deal with CI issues caused by pervasive cross-tap deps in science. Locally, I've noticed that test-bot tests anything that's tapped for the `uses` part, so I assume it will work on Jenkins too.

>And what do you think we should do with the outcome of such a test bot run?

Well presumably we notify @tdsmith et. al of which ones fail and give them some time to fix it. Whether anyone will pay attention to that notification or do anything is beyond my powers of prediction. I'm just trying to heed this: https://github.com/Homebrew/homebrew-core/pull/3269#issuecomment-234789416.

**Comment by ilovezfs** [comment]
@UniqMartin This PR breaks the `libswiften` build: https://gist.github.com/86c78aac570f12777eca9a8e21985541

It builds locally without the PR, and it currently passes CI: https://github.com/Homebrew/homebrew-core/pull/3508.

` git://swift.im/swift.git` (HEAD, but not defined in the formula currently) suffers from the same problem.

**Comment by ilovezfs** [comment]
@UniqMartin this PR also breaks the pdnsrec build: https://gist.github.com/2887fd1a890eaa5da37f2f7a919f5446

**Comment by ilovezfs** [comment]
CC @Habbie pdnsrec is broken with boost 1.61.0

**Comment by DomT4** [comment]
> Locally, I've noticed that test-bot tests anything that's tapped for the uses part, so I assume it will work on Jenkins too.

We intentionally don't test cross-tap currently because we handle it awfully. Until that improves, I don't really want the load on the CI to be honest.

> This PR breaks the libswiften build:

Maybe we should just be revision bumping everything in `brew uses boost` for a new boost 😕 .

**Comment by tdsmith** [comment]
> Maybe we should just be revision bumping everything in brew uses boost for a new boost.

Emphatically: yes.

**Comment by ilovezfs** [comment]
It would be nice if CI found these failures instead of having to choose between running all of these builds locally, as I'm currently doing, or just "hoping for the best."

**Comment by MikeMcQuaid** [comment]
> Maybe we should just be revision bumping everything in brew uses boost for a new boost 😕 .

I don't agree with preemptively rebuilding everything if it's unnecessary.

> It would be nice if CI found these failures instead of having to choose between running all of these builds locally, as I'm currently doing, or just "hoping for the best."

CI used to rebuild everything from source rather than test the bottles in this case but it was hilariously slow for things like Boost with large numbers of reverse dependencies. I think what we have now is probably the best middle ground considering CI resources.

**Comment by ilovezfs** [comment]
>CI used to rebuild everything from source rather than test the bottles in this case but it was hilariously slow for things like Boost with large numbers of reverse dependencies

To what extent, though, was that because it was doing `brew uses --recursive` vs. `brew uses` which are radically different in the case of boost?

**Comment by MikeMcQuaid** [comment]
> To what extent, though, was that because it was doing brew uses --recursive vs. brew uses which are radically different in the case of boost?

Probably: "a bit" but still: building all dependents from source rather than downloading a bottle and running `brew test` will always be a lot slower. Perhaps in cases like Boost we want to suck it up but it's not something we want/can change as a universal default, unfortunately.

**Comment by ilovezfs** [comment]
Yeah, as universal default would be crazy talk. I'd like to see us peg all boost-dependent formulae to a specific version of boost rather than using CI meltdown as a workaround.

**Comment by MikeMcQuaid** [comment]
@ilovezfs I finally opened https://github.com/Homebrew/brew/issues/620 for this. The first step is the only blocker and the only code that needs written. Please take this as an invitation to beat me to an implementation 😆

**Comment by ilovezfs** [comment]
*ilovezfs looks for his magic wand.*

By the way, here's another casualty of the boost wars I found: https://github.com/Homebrew/homebrew-science/pull/3931

`gtsam` just built successfully locally with boost155, but fails with boost159, boost, and boost161 (this PR). Do you recall why there's no boost155 bottle for 10.11? boost155 just built fine for me locally on 10.11, so that seems like an artificial constraint.

At the moment, it seems like the right thing to do for `gtsam` is `depends_on "homebrew/versions/boost155"`, even though @DomT4 may shoot me.

**Comment by MikeMcQuaid** [comment]
> At the moment, it seems like the right thing to do for gtsam is depends_on "homebrew/versions/boost155", even though @DomT4 may shoot me.

That's 🆗 in homebrew/science for now 👍

**Comment by DomT4** [comment]
> Do you recall why there's no boost155 bottle for 10.11?

Because nobody loves Versions & nobody periodically sweeps through adding new bottles or ensuring the formulae there actually work 😄.

> gtsam just built successfully locally with boost155

IMO, being _6_ major releases behind `boost` in support smells like a cry to be boneyarded, but Science are welcome to do whatever they like with their formulae.

**Comment by ilovezfs** [comment]
https://collab.cc.gatech.edu/borg/gtsam/

"Boost 1.58: This came out after GTSAM 3.2.1, and is not supported. The latest development code does support Boost 1.58 on Linux/Mac. Windows support is coming soon."

So it's possible it can be patched.

**Comment by ilovezfs** [comment]
I think we should ship this PR as-is and worry about pdnsrec and libswiften afterwards with two new issues.

**Comment by MikeMcQuaid** [comment]
> I think we should ship this PR as-is and worry about pdnsrec and libswiften afterwards with two new issues.

👍

**Comment by DomT4** [comment]
Might as well. Hopefully this will be the last major Boost update we ship without having some kind of framework in place for handling the next one, whether that's a massive expansion of CI usage or versions handled in a way people won't leave out to develop gangrene.

**Comment by ilovezfs** [comment]
>massive expansion of CI usage

How are we doing with that $10,000,000 donation?

>versions handled in a way people won't leave out to develop gangrene

Frankly, I'd settle for a wee bit of gangrene after contemplating the scope of https://github.com/Homebrew/homebrew-core/pull/3090.

**Comment by ilovezfs** [comment]
:ship:'d

**Comment by DomT4** [comment]
> How are we doing with that $10,000,000 donation?

It keeps appearing in my dreams. Nothing real yet though, sadly.

> Frankly, I'd settle for a wee bit of gangrene after contemplating the scope of #3090.

https://github.com/Homebrew/homebrew-core/pull/971 is potentially going to be worse 😄.

**Comment by ilovezfs** [comment]
>#971 is potentially going to be worse

Yeah, let's just pretend that doesn't actually exist.

Just to create the PR cross-references for the broken-with-boost-1.61.0 formulae: 
pdnsrec: https://github.com/Homebrew/homebrew-core/pull/3526
libswiften: https://github.com/Homebrew/homebrew-core/pull/3527

**Comment by UniqMartin** [comment]
Thanks @ilovezfs for shipping this and everyone for the nice discussion during my absence. 😀

**Comment by ilovezfs** [comment]
@UniqMartin You're welcome. You can repay me by fixing #3527 hehe

**Comment by tdsmith** [comment]
On Tue, Aug 2, 2016, 01:54 Mike McQuaid <notifications@github.com> wrote:

> Maybe we should just be revision bumping everything in brew uses boost for
> a new boost 😕 .
>
> I don't agree with preemptively rebuilding everything if it's unnecessary.
>
Because Boost doesn't maintain ABI or API compatibility between releases,
without looking closely at each package and which libraries they use it's
difficult to know for sure which rev deps don't need rebuilt binaries.
Stuff that uses header only libraries doesn't need to be rebuilt but it may
no longer be possible to build them. ABI incompatibility can be subtle and
won't necessarily crash our test but can induce bugs anyway.

>

**Comment by UniqMartin** [comment]
> You can repay me by fixing #3527 hehe

I've put in on my list, but I can guarantee that I get to it in a reasonable time frame. Sorry!

> Because Boost doesn't maintain ABI or API compatibility between releases, […]

Agreed. The only safe thing to do is to rebuild everything that dynamically links to one of the Boost libraries. For the sake of completeness and to make sure from-source builds aren't broken, it would be good to try to rebuild everything that depends on Boost, even if it's only using a header-only Boost library. Because that's quite a burden for our CI, the only practical solution seems to be to keep multiple versions of Boost around until all formulae have been transitioned to a newer version. (One of the aims of #620 if I'm not misreading it.)

**Comment by DomT4** [comment]
> (One of the aims of #620 if I'm not misreading it.)

Wrong repo 😉. Looking for https://github.com/Homebrew/brew/issues/620.

To be honest, looking at the `uses` list if we haven't got a new versioning system in place by the next major Boost bump, I don't think putting everything through CI would be too evil. Looking at that list I'd guess ~3 hours per run, which isn't significantly worse than `qt5` bumps.

**Pull request closed without merging**
