### PR TITLE
swiftlint 0.28.0

### PR DESCRIPTION
**Pull request by jpsim**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Fails on Mojave:

```
==> SWIFTLINT_SWIFT_VERSION=3 /usr/local/Cellar/swiftlint/0.28.0/bin/swiftlint --no-cache
Linting Swift files at paths 
Linting 'Test.swift' (1/1)
Error: swiftlint: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<nil>.
```

**Comment by jpsim** [comment]
Any ideas what that means? Looking at the tests, there's nothing explicitly checking for `<0>`.

https://github.com/jpsim/homebrew-core/blob/swiftlint-0.28.0/Formula/swiftlint.rb#L23-L29

**Comment by jpsim** [comment]
Seems like this was also an issue in #32449 and #32405. In that first PR, it was mentioned that this was also an issue on `master`. I don't see anything else about that.

**Comment by jpsim** [comment]
@fxcoudert what can we do to get more information about this failure?

**Comment by jpsim** [comment]
Releasing 0.28.1 shortly.

**Comment by jpsim** [comment]
PR for 0.28.1: #34268

**Pull request closed without merging**
