### PR TITLE
Remove unmaintained mono package

### LINKED ISSUE #35848: Possible issue with mono formula
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ X] ran `brew update` and can still reproduce the problem?
- [X ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

There seems to be some kind of issue with the most recent 1 or 2 versions of the mono formula for brew. I use it with ckan, and when trying to start it gives a mono related error. An error that does not occur according to the discussion here (https://github.com/KSP-CKAN/CKAN/issues/2630 1) when installing mono directly without brew. Any idea how to fix this, since I’d prefer to use brew rather than dealing with miscellaneous package (.pkg) installers?

### PR DESCRIPTION
**Pull request by HebaruSan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Currently the mono package doesn't work. The libnative library seems to be missing, based on [Debian's investigation](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920531) and [fix for the same stack trace](https://salsa.debian.org/dotnet-team/mono/commit/fcb8084be66074f5315728c2783348fb4c1bb0aa). This means that users will use homebrew to install mono and [report bugs to other packages](https://github.com/KSP-CKAN/CKAN/issues/2630) that depend on mono. This was reported by users in #35848, but no one knows how to fix it.

This pull request removes this non-working recipe to stop causing problems for other packages that depend on it; users will have to find other, [working ways to install mono](https://www.mono-project.com/download/stable/#download-mac).

Fixes #35848.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Wouldn't it be better to help fix mono on homebrew instead? You're clearly invested in mono working properly for people. 

I checked for the issue debian had but that doesn't seem to be the case for homebrew. Maybe this could be reported upstream and we could get some help there? Since the formula does seem to follow the compilation guide.
```
[sean] ~> ls /usr/local/Cellar/mono/5.18.0.225/lib/ | grep native
libikvm-native.a
libikvm-native.dylib
libmono-system-native.0.dylib
libmono-system-native.a
libmono-system-native.dylib
```

**Comment by HebaruSan** [comment]
> Wouldn't it be better to help fix mono on homebrew instead?

Yes, I would like to do that, but I do not have a Mac. Sorry for resorting to drastic action, but that "stale" notification on the issue spooked me. If there's no process for finding a fix for a broken package, then just leaving it broken indefinitely is going to be a constant pain point for users and other teams.

**Comment by MikeMcQuaid** [comment]
It's not unmaintained: it has a limitation that doesn't stop it being useful to [thousands of installs in the last 30 days](https://formulae.brew.sh/formula/mono).

Note also https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/38040/version=mojave/testReport/junit/brew-test-bot/mojave/uses___include_build___include_optional___include_test_mono/: there's things that depend on it that will break if you remove it (and are clearly working without this).

**Comment by tsal** [comment]
None of this makes any sense - you have a broken package poisoning your ecosystem, and the response is "it's okay, we have a build that needs it to be broken".. what??

So the answer is - "don't use us for your package management" since that's the only way to get a working mono installation at the moment.

**Comment by SMillerDev** [comment]
The answer is "other things do work, we can't just remove a major package like this one because it doesn't work in some cases".
Another option of course is to help debug since none of the homebrew maintainers knows mono very well afaik. But of course just complaining against volunteers will get it fixed a lot faster.

**Pull request closed without merging**
