### PR TITLE
nghttp2 1.28.0

### PR DESCRIPTION
**Pull request by ilovezfs**
remove spdylay dependency as upstream has deprecated spdylay support

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like `spdylay` can/should be cut out here: https://github.com/nghttp2/nghttp2/commit/24d92b979d36ebe82b24c831265ea1352a1aa0ff.

**Comment by ilovezfs** [comment]
done.

**Comment by DomT4** [comment]
Thanks! Over time it seems likely the `spdylay` formula itself will fade into irrelevance given the protocol itself has been deprecated, but maybe someone out there is using it for something that isn't this.

**Comment by ilovezfs** [comment]
probably
```
Josephs-MacBook-Pro:~ joe$ brew formula-analytics --install-on-request spdylay
install_on_request events in the last 30 days for spdylay
===============================================================================
1 | spdylay                                                      | 55 |  98.21%
2 | spdylay --without-libevent                                   |  1 |   1.79%
===============================================================================
Total                                                            | 56 |    100%
===============================================================================
Josephs-MacBook-Pro:~ joe$ 
```

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ brew formula-analytics spdylay
install events in the last 30 days for spdylay
===============================================================================
1 | spdylay                                                   | 7,854 |  99.99%
2 | spdylay --without-libevent                                |     1 |   0.01%
===============================================================================
Total                                                         | 7,855 |    100%
===============================================================================
Josephs-MacBook-Pro:~ joe$ brew formula-analytics nghttp2
install events in the last 30 days for nghttp2
===============================================================================
 1 | nghttp2                                                 | 15,146 |  99.69%
 2 | nghttp2 --with-python3                                  |     16 |   0.11%
 3 | nghttp2 --with-examples --with-python3                  |     13 |   0.09%
 4 | nghttp2 --without-jemalloc                              |      5 |   0.03%
 5 | nghttp2 --HEAD --with-python3                           |      4 |   0.03%
 6 | nghttp2 --with-examples                                 |      3 |   0.02%
 7 | nghttp2 --without-apps                                  |      2 |   0.01%
 8 | nghttp2 --HEAD                                          |      1 |   0.01%
 9 | nghttp2 --with-examples --with-python3 --without-jemall |      1 |   0.01%
10 | nghttp2 --with-python3 --without-jemalloc               |      1 |   0.01%
11 | nghttp2 --without-apps --without-docs --without-jemallo |      1 |   0.01%
===============================================================================
Total                                                        | 15,193 |    100%
===============================================================================
Josephs-MacBook-Pro:~ joe$ 
```
So it will be interesting to see what the non-install-on-request events look like over the next month.

**Comment by DomT4** [comment]
Aye, I'd be amazed if that number doesn't tank. One to keep an eye on I guess.

**Pull request closed without merging**
