### PR TITLE
vulkan-validationlayers 1.3.250

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  /tmp/vulkan-validationlayers-20230505-7593-j0ooez/Vulkan-ValidationLayers-1.3.250/layers/gpu_validation/gpu_validation.cpp:1338:38: error: no member named 'kDebugInputBindlessMaxDescSets' in namespace 'spvtools'; did you mean 'kDebugInputBindlessInitOffset'?
          buffer_info.size = spvtools::kDebugInputBindlessMaxDescSets * 8; // 64 bit addresses
                             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                       kDebugInputBindlessInitOffset
```

**Comment by pthariensflame** [comment]
This needs a patch to `spirv-tools` akin to the patches to `spirv-headers`.

**Comment by chenrui333** [comment]
#131028

**Comment by chenrui333** [comment]
> This needs a patch to `spirv-tools` akin to the patches to `spirv-headers`.
> 
> Cherry-picking [this commit](https://github.com/KhronosGroup/SPIRV-Tools/commit/d4c0abdcad60325a2ab3c00a81847e2dbdc927a2) should be sufficient, I think.

Thanks for the pointer!

**Pull request closed without merging**
