### PR TITLE
mosquitto 1.6.11

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Rylan12** [comment]
Looks like it's dual-licensed under `EPL-1.0` or the Eclipse Distribution License (EDL) 1.0. The latter is not an SPDX license so I think we can just go with `EPL-1.0`

**Comment by chenrui333** [comment]
> EPL-1.0

Sounds good, I will add a comment about dual license situation, in case that is helpful.

**Review by Rylan12 — APPROVED** [review]

**Comment by Rylan12** [comment]
Do we need one commit?

**Comment by chenrui333** [comment]
I assume you mean squashing the commits, right? Sure, I will do that later, taking a long walk now. 😀

**Comment by Rylan12** [comment]
I'll take care of it. I just wanted to make sure it didn't merge automatically.

**Comment by chenrui333** [comment]
> I'll take care of it. I just wanted to make sure it didn't merge automatically.

Thanks!!

**Pull request closed without merging**
