### PR TITLE
chronograf 1.7.17

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
20:58:44 go-bindata -o swagger_gen.go -ignore go -nocompress -pkg server .
20:58:44 server/swagger.go:3: running "go-bindata": exec: "go-bindata": executable file not found in $PATH
20:58:44 make: *** [server/swagger_gen.go] Error 1

**Comment by issyl0** [comment]
Still the same kind of failure. It works locally:

```
$ brew test chronograf
Testing chronograf
INFO[0000] Running migration 59b0cda4fc7909ff84ee5c4f9cb4b655b6a26620
INFO[0000] Serving chronograf at http://[::]:8888        component=server
INFO[0000] Reporting usage stats                         component=usage freq=24h reporting_addr=https://usage.influxdata.com stats=os,arch,version,cluster_id,uptime   
==> curl -s 0.0.0.0:8888/chronograf/v1/
INFO[0000] Response: OK                                  component=server method=GET remote_addr=127.0.0.1:49942 response_time=225.86µs status=200
ERRO[0001] shutdown initiated
INFO[0001] Stopped serving chronograf at http://[::]:8888  component=server
```

How much `sleep`ing is Jenkins allowed? 😄 I'm hesitant to up it any more, but at this point it's trial and error.

**Comment by issyl0** [comment]
Hmm, `nomad` has `sleep 10` in its test, so I'm going to see if that works.

**Comment by issyl0** [comment]
Ten seconds did the trick. I'll squash all the commits together and then pull the bottles once CI is green again.

**Comment by chenrui333** [comment]
🎉 Nice job!!

**Comment by issyl0** [comment]
@alebcay You beat me by a couple of seconds. 🥇 Thanks! 😄

**Pull request closed without merging**
