### PR TITLE
appscale-tools 3.8.1

### PR DESCRIPTION
**Pull request by dawidd6**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Test failure

**Comment by fxcoudert** [comment]
```
pkg_resources.DistributionNotFound: The 'keyring<19.0.0,>=12.0.2' distribution was not found and is required by appscale-agents
```

Maybe pypi-poet can be used to do this more systematically?

**Comment by fxcoudert** [comment]
Still:

```
pkg_resources.DistributionNotFound: The 'keyring<19.0.0,>=12.0.2' distribution was not found and is required by appscale-agents
```

**Comment by fxcoudert** [comment]
```
pkg_resources.DistributionNotFound: The 'keyring<19.0.0,>=12.0.2' distribution was not found and is required by appscale-agents
```

How does this pass locally?

**Comment by dawidd6** [comment]
@fxcoudert it does not. I'm not on macOS and can't test it easily.

**Comment by fxcoudert** [comment]
```
pkg_resources.DistributionNotFound: The 'azure-mgmt-marketplaceordering' distribution was not found and is required by appscale-agents
```

**Comment by fxcoudert** [comment]
Back  to 

```
pkg_resources.DistributionNotFound: The 'keyring<19.0.0,>=12.0.2' distribution was not found and is required by appscale-agents
```

**Comment by dawidd6** [comment]
I must have not synced the branch on my laptop. Restored.

**Comment by fxcoudert** [comment]
```
pkg_resources.DistributionNotFound: The 'azure==2.0.0' distribution was not found and is required by appscale-agents
```

**Comment by SMillerDev** [comment]
```
pkg_resources.DistributionNotFound: The 'azure-servicebus~=0.21.1' distribution was not found and is required by azure
```

**Comment by SMillerDev** [comment]
```
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'azure-batch~=3.0.0' distribution was not found and is required by azure
```

**Comment by SMillerDev** [comment]
`pkg_resources.DistributionNotFound: The 'configparser>=3.5' distribution was not found and is required by entrypoints`

**Comment by chenrui333** [comment]
relates to #67230

**Pull request closed without merging**
