### PR TITLE
harfbuzz: make glib, cairo and gobject-introspection required

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by ilovezfs** [comment]
🍪

**Comment by khaledhosny** [comment]
Why require Cairo? It is only used for the `hb-view` command line utility, HarfBuzz library does not use it.

**Comment by tschoonj** [comment]
Seems like a rather light dependency to me. Most people will get harfbuzz on their systems as a dependency of pango, which depends in turn on Cairo.

**Comment by khaledhosny** [comment]
There are many other packages that depend on HarfBuzz and not Cairo, I last I checked Cairo was pulling with it a long tail of other dependencies.

**Comment by tschoonj** [comment]
There is only a handful of packages that depend on harfbuzz and not on Cairo. I really don't think that this is a big deal.

However, if you insist to bring the option back feel free to open a PR.

**Comment by MikeMcQuaid** [comment]
> However, if you insist to bring the option back feel free to open a PR.

Sorry to contradict @tschoonj but please don't add an option because it won't be accepted. We're trying to remove more options generally in Homebrew. If you still need an option: maintain the formula in your tap. Sorry!

**Pull request closed without merging**
