### PR TITLE
podofo 0.9.6

### PR DESCRIPTION
**Pull request by luzpaz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by luzpaz** [comment]
`gdal` has `podofo` as a dependency. Maybe merge this after #37823 is merged so no need to bump the `gdal` package ?

**Comment by luzpaz** [comment]
```
Missing libraries:
  /tmp/podofo-20190319-17460-1uuv2cr/podofo-0.9.6/build/src/libpodofo.0.9.6.dylib
podofo:
  * podofo has broken dynamic library links:
```

**Comment by fxcoudert** [comment]
- The `gdal` linkage audit and test passed, so it does not need revision.
- `podofo` linkage test is a known false positive.

**Comment by fxcoudert** [comment]
Merging, thanks @luzpaz

**Pull request closed without merging**
