### PR TITLE
ucon64 2.2.0

### PR DESCRIPTION
**Pull request by zachauten**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
clang ucon64.o ucon64_dat.o ucon64_misc.o ucon64_opts.o misc/chksum.o misc/file.o misc/getopt2.o misc/misc.o misc/property.o misc/string.o misc/term.o console/atari.o console/coleco.o console/console.o console/dc.o console/gb.o console/gba.o console/genesis.o console/jaguar.o console/lynx.o console/n64.o console/nds.o console/neogeo.o console/nes.o console/ngp.o console/pce.o console/psx.o console/sms.o console/snes.o console/swan.o console/vboy.o backup/backup.o backup/cc2.o backup/cmc.o backup/dex.o backup/doctor64.o backup/doctor64jr.o backup/f2a.o backup/fal.o backup/ffe.o backup/fig.o backup/gbx.o backup/gd.o backup/interceptor.o backup/lynxit.o backup/mccl.o backup/mcd.o backup/md-pro.o backup/mgd.o backup/mgh.o backup/msg.o backup/nfc.o backup/pce-pro.o backup/pl.o backup/psxpblib.o backup/quickdev16.o backup/sc.o backup/sflash.o backup/smc.o backup/smd.o backup/smsgg-pro.o backup/spsc.o backup/ssc.o backup/swc.o backup/tototek.o backup/ufo.o backup/ufosd.o backup/yoko.o backup/z64.o patch/aps.o patch/bsl.o patch/gg.o patch/ips.o patch/patch.o patch/ppf.o misc/getopt.o misc/archive.o misc/ioapi.o misc/map.o misc/unzip.o misc/parallel.o misc/dlopen.o -lz -o ucon64
Undefined symbols for architecture x86_64:
  "_sched_setscheduler", referenced from:
      _main in ucon64.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ucon64] Error 1

**Comment by mistydemeo** [comment]
Huh, I had no idea there was a new release.

`sched_setscheduler` looks to be a non-POSIX, Linux-only function: https://linux.die.net/man/2/sched_setscheduler

Looks like between 2.2.0 and trunk, they added a check for this. Here's the patch: https://sourceforge.net/p/ucon64/svn/2763/

**Comment by mistydemeo** [comment]
Here's that patch in as a git patch: https://github.com/mistydemeo/ucon64/commit/878e5b04404f721f60936b2066ae17b5dfce8921.patch?full_index=1

**Comment by zachauten** [comment]
@mistydemeo If the patch fixes the build, should I add it to Homebrew/formula-patches?

**Comment by mistydemeo** [comment]
@zachauten Seems reasonable. The repo I linked is my unofficial git mirror, so while I don't expect that link to break or change, it's not a bad idea to mirror the patch either.

**Comment by mistydemeo** [comment]
Backported that patch to 2.2.0; it needed some editing.

```patch
From b7c433d2567662b8b8ede74ff91f7b24a32450ad Mon Sep 17 00:00:00 2001
From: Misty De Meo <mistydemeo@gmail.com>
Date: Tue, 18 Feb 2020 19:06:24 -0800
Subject: [PATCH 1/2] ucon64: adapt upstream patch for 2.2.0

---
 Formula/ucon64.rb | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)

diff --git a/Formula/ucon64.rb b/Formula/ucon64.rb
index 20247310e0..0cc460d863 100644
--- a/Formula/ucon64.rb
+++ b/Formula/ucon64.rb
@@ -18,9 +18,12 @@ class Ucon64 < Formula
     sha256 "d74cb3ba11a4ef5d0f8d224325958ca1203b0d8bb4a7a79867e412d987f0b846"
   end
 
+  # Fixes an upstream issue which incorrectly attempts to use a Linux-only
+  # function on macOS. Should be in the next release.
+  # bb7bf52ec016092bf84b0a5eebb4295394288985993d4ab7a6b69a78c1c3ce77
   patch do
-    url "https://github.com/mistydemeo/ucon64/commit/878e5b04404f721f60936b2066ae17b5dfce8921.patch?full_index=1"
-    sha256 "168ae94e3e7e82b5b8f4c0424d16d9a5f74d3f21320bb38d35b2ca8fae1738f3"
+    url "https://github.com/Homebrew/formula-patches/raw/23a80b586dd35fdde1bf575c57a1b468631e644e/ucon64/sched_setscheduler.diff"
+    sha256 "bb7bf52ec016092bf84b0a5eebb4295394288985993d4ab7a6b69a78c1c3ce77"
   end
 
   def install
-- 
2.25.0

```

That then reveals a new formula issue, which is easily fixed:

```patch
From dc51c4bfb55e741e54f54a41e22698013971cecf Mon Sep 17 00:00:00 2001
From: Misty De Meo <mistydemeo@gmail.com>
Date: Tue, 18 Feb 2020 19:06:50 -0800
Subject: [PATCH 2/2] ucon64: libdiscmage now built with the correct name

---
 Formula/ucon64.rb | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/Formula/ucon64.rb b/Formula/ucon64.rb
index 0cc460d863..c70e065fea 100644
--- a/Formula/ucon64.rb
+++ b/Formula/ucon64.rb
@@ -42,7 +42,7 @@ class Ucon64 < Formula
                             "--prefix=#{prefix}"
       system "make"
       bin.install "ucon64"
-      libexec.install "libdiscmage/discmage.so" => "libdiscmage.dylib"
+      libexec.install "libdiscmage/discmage.dylib" => "libdiscmage.dylib"
     end
   end
 
-- 
2.25.0

```

**Pull request closed without merging**
