### PR TITLE
curaengine: migrate to Cask

### PR DESCRIPTION
**Pull request by AnastasiaSulyagina**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?

---

Deleting curaengine from homebrew-core as part of deduplication process . See context [here](https://github.com/caskroom/homebrew-cask/issues/15603). 

_Please note that this PR is created to continue case-by-case discussions from thread linked above and if decision is made not to remove the formula, PR will be closed._ 

cc @MikeMcQuaid

### CODE REVIEW

**Comment by apjanke** [comment]
:+1:

**Comment by DomT4** [comment]
👍

**Comment by MikeMcQuaid** [comment]
Thanks again @AnastasiaSulyagina :metal:

**Comment by DerekRoth** [comment]
Correct me if i'm wrong but aren't Cura and CuraEngine two different softwares ?
I'm trying to install CuraEngine in order to use it in RepetierHost on macOS but installing the Cura app does not help...

**Comment by MikeMcQuaid** [comment]
@DerekRoth You may be right. What does `find -name CuraEngine /Applications/Cura.app` output?

**Comment by DerekRoth** [comment]
`$ find /Applications/Cura.app/ -name CuraEngine
/Applications/Cura.app//Contents/MacOS/CuraEngine`

I think CuraEngine is a plugin used by Cura, that can be used by other programs.

**Pull request merged**
