### PR TITLE
azure-storage-cpp 5.1.1 (new formula)

### PR DESCRIPTION
**Pull request by mschmieder**
added azure-storage-cpp that enables communication with azure storages. This formula is dependend on newer versions of cpprestsdk > 2.10.5 and therefore will only build successfully if the the merge request for cpprestsdk 2.10.6 is accepted first

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
CMake Warning at CMakeLists.txt:33 (message):
  No GETTEXT_LIB_DIR specified, assuming: /usr/local/opt/gettext/lib


ERRORWe couldn't find your gettext lib directory (/usr/local/opt/gettext/lib). Please re-run cmake with -DGETTEXT_LIB_DIR=<your gettext lib dir>. This is usually where libintl.a and libintl.dylib reside.
-- Found OpenSSL: /usr/local/opt/openssl/lib/libcrypto.dylib (found suitable version "1.0.2p", minimum required is "1.0.0")  
CMake Error at cmake/Modules/FindUUID.cmake:101 (message):
  Could not find UUID
Call Stack (most recent call first):
  CMakeLists.txt:49 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/azure-storage-cpp-20181001-32765-1yrjhi3/azure-storage-cpp-5.1.1/CMakeFiles/CMakeOutput.log".
```

**Comment by fxcoudert** [comment]
```
/tmp/azure-storage-cpp-20181002-76811-10g4wvj/azure-storage-cpp-5.1.1/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h:370:20: error: no member named '_do_while' in namespace 'pplx::details'; did you mean 'Concurrency::details::_do_while'?
no member named '_do_while' in namespace 'pplx::details'; did you mean 'Concurrency::details::_do_while'?
            return pplx::details::_do_while([instance]() -> pplx::task<bool>
                   ^~~~~~~~~~~~~~~~~~~~~~~~
                   Concurrency::details::_do_while
/usr/local/include/cpprest/astreambuf.h:30:23: note: 'Concurrency::details::_do_while' declared here
        pplx::task<T> _do_while(F func)
                      ^
            return pplx::details::_do_while([instance]() -> pplx::task<bool>
                   ^~~~~~~~~~~~~~~~~~~~~~~~
                   Concurrency::details::_do_while
/usr/local/include/cpprest/astreambuf.h:30:23: note: 'Concurrency::details::_do_while' declared here
        pplx::task<T> _do_while(F func)
                      ^
```

Please test locally before pushing to our CI…

**Comment by mschmieder** [comment]
> ```
> /tmp/azure-storage-cpp-20181002-76811-10g4wvj/azure-storage-cpp-5.1.1/Microsoft.WindowsAzure.Storage/includes/wascore/executor.h:370:20: error: no member named '_do_while' in namespace 'pplx::details'; did you mean 'Concurrency::details::_do_while'?
> no member named '_do_while' in namespace 'pplx::details'; did you mean 'Concurrency::details::_do_while'?
>             return pplx::details::_do_while([instance]() -> pplx::task<bool>
>                    ^~~~~~~~~~~~~~~~~~~~~~~~
>                    Concurrency::details::_do_while
> /usr/local/include/cpprest/astreambuf.h:30:23: note: 'Concurrency::details::_do_while' declared here
>         pplx::task<T> _do_while(F func)
>                       ^
>             return pplx::details::_do_while([instance]() -> pplx::task<bool>
>                    ^~~~~~~~~~~~~~~~~~~~~~~~
>                    Concurrency::details::_do_while
> /usr/local/include/cpprest/astreambuf.h:30:23: note: 'Concurrency::details::_do_while' declared here
>         pplx::task<T> _do_while(F func)
>                       ^
> ```
> Please test locally before pushing to our CI…

This error is due to the fact that the newest `cpprestsdk 2.10.6` was not available for the CI. In order to have this pull request compile correctly, I merged in the `cpprestsdk 2.10.6` branch that was already successfully build by your CI.

**Comment by fxcoudert** [comment]
> I merged in the cpprestsdk 2.10.6 branch

Please undo that, it overwrote the published bottles.

**Comment by mschmieder** [comment]
> > I merged in the cpprestsdk 2.10.6 branch
> 
> Please undo that, it overwrote the published bottles.

Ok, commits have been reverted.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by mschmieder** [comment]
@fxcoudert 
Do you need me to do anything about the CI error?

```
==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-core/pull/32600.patch
==> Applying patch
Applying: cpprestsdk 2.10.6
Using index info to reconstruct a base tree...
M	Formula/cpprestsdk.rb
Falling back to patching base and 3-way merge...
Auto-merging Formula/cpprestsdk.rb
CONFLICT (content): Merge conflict in Formula/cpprestsdk.rb
error: Failed to merge in the changes.
Patch failed at 0001 cpprestsdk 2.10.6
Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Error: Patch failed to apply: aborted.
```

I'm not sure I understand where this is coming from. Do I need to merge the current `master` manually in there?

**Comment by fxcoudert** [comment]
@mschmieder please squash all commits into one, that ought to fix it

**Comment by mschmieder** [comment]
@fxcoudert 
I‘m not able to squash the commits somehow. I could close this pull request and create a new, clean one!?

**Pull request closed without merging**
