### PR TITLE
[WIP] caddy 1.0.0

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
work on it!

**Comment by chenrui333** [comment]
```
22:11:46 cp -pR /private/tmp/d20190514-70428-8c6898/caddy-1.0.0/. /private/tmp/caddy-20190514-70428-lx81y8/caddy-1.0.0
22:11:46 chmod -Rf +w /private/tmp/d20190514-70428-8c6898
22:11:46 ==> go build -ldflags -X github.com/mholt/caddy/caddy/caddymain.gitTag=1.0.0 -o /usr/local/Cellar/caddy/1.0.0/bin/caddy github.com/mholt/caddy/caddy
22:11:46 $GOPATH/go.mod exists but should not
```

**Review by leafac — APPROVED** [review]

**Comment by MindTooth** [comment]
I believe this is superseded by https://github.com/Homebrew/homebrew-core/pull/41879.

**Comment by SMillerDev** [comment]
Think so too, thanks

**Comment by chenrui333** [comment]
👍

**Pull request closed without merging**
