### PR TITLE
alluxio 2.2.1

### PR DESCRIPTION
**Pull request by zachauten**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by Moisan — DISMISSED** [review]

**Comment by Moisan** [comment]
Test fails with 
```
==> /usr/local/Cellar/alluxio/2.2.1/bin/alluxio version
Error: Alluxio requires Java 8, currently Java 14.0.1 found.
Error: alluxio: failed
```
You probably need to use java 1.8+ here.

**Comment by SMillerDev** [comment]
If it worked with openjdk before maybe 11 works?

**Comment by Moisan** [comment]
This seems to be a [known issue](https://github.com/Alluxio/alluxio/issues/9856) . Upstream only supports Java version 8.

**Comment by apc999** [comment]
@zachauten latest Alluxio 2.4.0 supports Java 11. I have created a PR to bump version on homebrew. FYI
https://github.com/Homebrew/homebrew-core/pull/63589/

**Pull request closed without merging**
