### PR TITLE
imap-backup 7.0.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Not (yet?) a GitHub Release.

**Comment by iMichka** [comment]
I got the confirmation from upstream that this is a pre-release.

**Comment by carlocab** [comment]
Actually, let's keep this open for a bit to try to block dupes.

**Comment by Porkepix** [comment]
> Actually, let's keep this open for a bit to try to block dupes.

Aren't dupes also checked against closed MR? I seemed to noticed that, generally (and I guess CI can be cancelled if it's the only goal).

**Comment by carlocab** [comment]
Yes, I don't mean to keep this open indefinitely. Just that we want to fix this so that `brew livecheck` returns the right version first.

**Comment by jonchang** [comment]
Superseded by #111305.

**Comment by Porkepix** [comment]
> Superseded by #111305.

I believe @carlocab wanted to have it opened as some sort of reminder so that the livecheck doesn't pickup prereleases.

**Comment by jonchang** [comment]
Shouldn't apply now that there's an official release. (We could also change the livecheck strategy to github_latest)

**Comment by Porkepix** [comment]
> Shouldn't apply now that there's an official release. (We could also change the livecheck strategy to github_latest)

But this'll still grab the next pre-releases currently, right?
Opened https://github.com/Homebrew/homebrew-core/pull/112179 with latest one detected by the livecheck, but it looks like it grabs a tag rather than the actual latest release.

**Comment by jonchang** [comment]
> But this'll still grab the next pre-releases currently, right?

Not if it uses the github_latest strategy.

**Pull request closed without merging**
