### PR TITLE
R: configure R with Objective C++ compiler

### LINKED ISSUE #92534: R: R is not configured with an Objective C++ compiler
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.3.9-122-g578286a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 578286a94701a2f9c013266e76f02a41079edbaf
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1f19d01143863068f0038ceb18ee62b4066f5629
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.x0kSysPZap/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
Rosetta 2: false


$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  proj@7

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/kevin/bin/tmux-config
  /Users/kevin/Library/r-miniconda-arm64/bin/python3.9-config
  /Users/kevin/Library/r-miniconda-arm64/bin/python3-config
  /Users/kevin/Library/r-miniconda-arm64/bin/ncursesw6-config
  /Users/kevin/Library/r-miniconda-arm64/bin/ncurses6-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Some R packages (e.g. [systemfonts](https://github.com/r-lib/systemfonts/issues/84)) require that R is configured with an Objective C++ compiler. However, R installations from Homebrew do not set this:

```
$ cat /opt/homebrew/opt/R/lib/R/etc/Makeconf | grep '^OBJCXX'
OBJCXX =
```

Compare with an "official" installation of R, e.g.

```
$ cat /Library/Frameworks/R.framework/Resources/etc/Makeconf | grep '^OBJCXX'
OBJCXX = clang++ -mmacosx-version-min=10.13
```

### What happened (include all command output)?

Installation of packages requiring an Objective C++ compiler can fail with Homebrew R. See https://github.com/r-lib/systemfonts/issues/84 for details.

### What did you expect to happen?

Installation of packages requiring an Objective C++ compiler should succeed without issue. In particular, the Homebrew installation of R should set:

```
OBJCXX = clang++
```

in the R installation's `etc/Makeconf` file.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install R
R -e 'install.packages("systemfonts", type = "source", repos = "https://cloud.r-project.org")'
# observe installation failure
```

### PR DESCRIPTION
**Pull request by kevinushey**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Closes #92534.

### CODE REVIEW

**Comment by kevinushey** [comment]
The real problem here is evidently that R's configure script fails to confirm that Objective C++ is supported:

```
$ brew install -s -v r
< ... >
checking whether the compiler supports GNU Objective C... yes
checking whether clang accepts -g... yes
checking whether $(CXX) can compile ObjC++... no
checking whether clang++ can compile ObjC++... no
< ... >
```

I'm not exactly sure why -- maybe Homebrew's `clang` shim is confusing R's configure script?

The simplest workaround here is to just update the installed Makeconf after installation.

**Comment by carlocab** [comment]
Can you check `config.log` in `~/Library/Logs/Homebrew/r` to see why `configure` thinks that `clang++` doesn't work as an Objective-C++ compiler?

**Comment by kevinushey** [comment]
Thanks for the hint! I see in `config.log`:

```
configure:9607: checking whether clang++ can compile ObjC++
running: clang++ -c conftest.mm -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/xz/include 
In file included from conftest.mm:2:
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/objc/Object.h:141:28: error: expected a type
- (id)forward: (SEL)sel : (marg_list)args;
                           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/objc/Object.h:142:29: error: expected a type
- (id)performv: (SEL)sel : (marg_list)args;
                            ^
2 errors generated.
configure:9637: result: no
configure:9646: checking whether clang++ can compile ObjC++
running: clang++ -c conftest.mm -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/xz/include 
In file included from conftest.mm:2:
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/objc/Object.h:141:28: error: expected a type
- (id)forward: (SEL)sel : (marg_list)args;
                           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/objc/Object.h:142:29: error: expected a type
- (id)performv: (SEL)sel : (marg_list)args;
                            ^
2 errors generated.
configure:9676: result: no
```

Compared to what I see in a successful configure invocation:

```
configure:9607: checking whether clang++ can compile ObjC++
running: clang++ -c conftest.mm -I/usr/local/include 
configure:9631: result: yes
```

The contents of `conftest.mm`:

```
#include <Foundation/Foundation.h>
#include <iostream>

@interface Greeter : NSObject
- (void) greet: (const char *)msg;
@end

@implementation Greeter
- (void) greet: (const char *)msg { std::cout << msg; }
@end

int
main ()
{
  std::cout << "Hello from C++\n";
  Greeter *obj = [Greeter new];
  [obj greet: "Hello from Objective-C\n"];
}
```

But that seems to succeed for me even with `brew sh`, which is surprising to me. That is, this runs without issue:

```
$ brew sh -c 'clang++ -c conftest.mm -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/xz/include'
```

Is there anything else I can try to poke at?

**Comment by kevinushey** [comment]
Whatever is going on, it seems like `marg_list` is normally defined made available by `clang++` when compiling Objective C++ files, but for some reason that's not true when called within R's configure script -- but _only_ when invoked through Homebrew; it seems to work fine in a regular shell.

And even with that, compilation of Objective C++ scripts appears to be fine within `brew sh`. So, it seems like there's some very strange interaction between Homebrew, R's configure script, and compilation of Objective C++ code.

Incredibly weird!

**Comment by carlocab** [comment]
Not really clear on what's happening. CC @Homebrew/core for ideas.

**Comment by kevinushey** [comment]
Okay, I can reproduce with the following:

```
#undef __OBJC2__
#include <objc/Object.h>
```

```
$ clang++ -c test.mm
In file included from test.mm:2:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/Object.h:141:28: error: expected a type
- (id)forward: (SEL)sel : (marg_list)args;
                           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/Object.h:142:29: error: expected a type
- (id)performv: (SEL)sel : (marg_list)args;
                            ^
2 errors generated.
```

And it looks like R 4.1.2 does include that `#undef` in their configure script:

```
cat << \EOF > conftest.mm
#undef __OBJC2__
#include <objc/Object.h>
#include <iostream>

@interface Greeter : Object
- (void) greet: (const char *)msg;
@end

@implementation Greeter
- (void) greet: (const char *)msg { std::cout << msg; }
@end

int
main ()
{
  std::cout << "Hello from C++\n";
  Greeter *obj = @<:@Greeter new@:>@;
  @<:@obj greet: "Hello from Objective-C\n"@:>@;
}
EOF
```

And that was fixed in the latest development versions of R, with:

https://github.com/wch/r-source/commit/f205003ac5f5d9736af6e7547978960f24cb979f

So, in sum:

1. This will be fixed in the next release of R;
2. As a workaround, Homebrew could manually set OBJCXX post-build as this patch does, or we could just leave it until the next version of R is released.

**Comment by MikeMcQuaid** [comment]
> 2\. As a workaround, Homebrew could manually set OBJCXX post-build as this patch does, or we could just leave it until the next version of R is released.

I'd say just wait 👍🏻

**Pull request closed without merging**
