### PR TITLE
swiftformat 0.36.0

### PR DESCRIPTION
**Pull request by nicklockwood**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
Thank you @nicklockwood ! 
Note that next time you can use `brew bump-formula-pr` to quickly bump a formula version.

**Comment by nicklockwood** [comment]
@Moisan doesn't work for me, unfortunately. When I run

    brew bump-formula-pr swiftformat --url https://github.com/nicklockwood/SwiftFormat/archive/0.36.0.tar.gz

I get

    Error: 0.36.0.tar.gz: /Users/nick/Library/Caches/Homebrew/Formula/0.36.0.tar.gz:1: Invalid char `\x1F' in expression

**Comment by igas** [comment]
@nicklockwood order matters, you need to do it like this:

```
brew bump-formula-pr --url https://github.com/nicklockwood/SwiftFormat/archive/0.36.0.tar.gz swiftformat
```

Depends on the shell you may need to put URL in quotes too.

**Comment by nicklockwood** [comment]
@Moisan thanks, I'll try that next time.

**Pull request closed without merging**
