### PR TITLE
caddy 2.2.0

### PR DESCRIPTION
**Pull request by lukasbestle**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Can it work with the latest go

**Comment by lukasbestle** [comment]
It does!

I wonder why the Go version had been pinned to 1.14 in the first place. Caddy is modern software that supports modern language versions...

Anyway, I have now unpinned the Go version again. And while I was at it, I also updated the `xcaddy` resource to the latest version.

**Comment by chenrui333** [comment]
> I wonder why the Go version had been pinned to 1.14 in the first place. Caddy is modern software that supports modern language versions...

It happened when we did the `go 1.15` upgrade, it did not work out last time, I believe.

**Comment by lukasbestle** [comment]
@chenrui333 Ah, makes sense. :)

**Review by dawidd6 — APPROVED** [review]

**Comment by francislavoie** [comment]
FYI older versions of Caddy did not build with Go 1.15 because of a bug in quic-go https://github.com/lucas-clemente/quic-go/issues/2614. It's best to pin to the latest known-good version of Go to avoid potential issues like that in the future.

Also, it seems like Caddy v2.2 in brew is broken, see https://caddy.community/t/caddy-v-panic-duplicate-metrics-collector-registration-attempted/9915 and https://github.com/Homebrew/homebrew-core/issues/61621

**Pull request closed without merging**
