### PR TITLE
qtads 3.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Per https://realnc.github.io/qtads/
> The current version is 3.0, released on 2020-02-15. The list of changes since 2.1.7 can be found on the GitHub release page.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
[34m==>[0m [1mbrew install --verbose --build-bottle qtads[0m
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200412-91998-5997tp.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qtads.rb --build-bottle --verbose
[34m==>[0m [1mDownloading https://downloads.sourceforge.net/project/qtads/v3.0.0/qtads-3.0.0-source.tar.xz[0m
Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/2fd1a7eea11aeb5d9fb1632003e28ef60bb199fe30ec77e8652c394d7f281a1f--qtads-3.0.0-source.tar.xz
[34m==>[0m [1mVerifying 2fd1a7eea11aeb5d9fb1632003e28ef60bb199fe30ec77e8652c394d7f281a1f--qtads-3.0.0-source.tar.xz checksum[0m
tar xof /Users/brew/Library/Caches/Homebrew/downloads/2fd1a7eea11aeb5d9fb1632003e28ef60bb199fe30ec77e8652c394d7f281a1f--qtads-3.0.0-source.tar.xz -C /private/tmp/d20200412-91999-p88h3o
cp -pR /private/tmp/d20200412-91999-p88h3o/qtads-3.0.0/. /private/tmp/qtads-20200412-91999-1s4375l/qtads-3.0.0
chmod -Rf +w /private/tmp/d20200412-91999-p88h3o
[31mError:[0m An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
qtads.pro:
  expected replacement of "INCLUDEPATH += src $$T2DIR $$T3DIR $$HTDIR" with "INCLUDEPATH += src $$T2DIR $$T3DIR $$HTDIR /usr/local/opt/sdl_sound/include/SDL"
```

**Comment by chenrui333** [comment]
```
[34m==>[0m [1mbrew install --verbose --build-bottle qtads[0m
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200413-48365-bgbbfb.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qtads.rb --build-bottle --verbose
[34m==>[0m [1mDownloading https://downloads.sourceforge.net/project/qtads/v3.0.0/qtads-3.0.0-source.tar.xz[0m
Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/2fd1a7eea11aeb5d9fb1632003e28ef60bb199fe30ec77e8652c394d7f281a1f--qtads-3.0.0-source.tar.xz
[34m==>[0m [1mVerifying 2fd1a7eea11aeb5d9fb1632003e28ef60bb199fe30ec77e8652c394d7f281a1f--qtads-3.0.0-source.tar.xz checksum[0m
tar xof /Users/brew/Library/Caches/Homebrew/downloads/2fd1a7eea11aeb5d9fb1632003e28ef60bb199fe30ec77e8652c394d7f281a1f--qtads-3.0.0-source.tar.xz -C /private/tmp/d20200413-48366-36qu7b
cp -pR /private/tmp/d20200413-48366-36qu7b/qtads-3.0.0/. /private/tmp/qtads-20200413-48366-1feppe2/qtads-3.0.0
chmod -Rf +w /private/tmp/d20200413-48366-36qu7b
[34m==>[0m [1mqmake DEFINES+=NO_STATIC_TEXTCODEC_PLUGINS[0m
Info: creating stash file /private/tmp/qtads-20200413-48366-1feppe2/qtads-3.0.0/.qmake.stash
Project ERROR: sndfile development package not found
```

**Comment by bayandin** [comment]
```
==> qmake DEFINES+=NO_STATIC_TEXTCODEC_PLUGINS
Info: creating stash file /private/tmp/qtads-20200413-97896-v0hlf/qtads-3.0.0/.qmake.stash
Project ERROR: libmpg123 development package not found
```

**Comment by bayandin** [comment]
```
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - share/man/man6/qtads.6
```
man was moved (from `share` to `desktop`)

And, the real question I wanted to ask, does this formula creates only `QTads.app`, if so I would suggest to move it to a cask

**Comment by Bo98** [comment]
> Does this formula creates only QTads.app, if so I would suggest to move it to a cask

Yeah, it seems so. The `qtads.6` and a bin script to start the app were the only other things in the bottle.

**Pull request closed without merging**
