### PR TITLE
brew-cask-completion: remove `bottle :unneeded`

### PR DESCRIPTION
**Pull request by Moisan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

See #75943.

### CODE REVIEW

**Comment by Moisan** [comment]
❯ sha256sum *.tar.gz
a058f8dd7fb25aa2ca8452d32f7d419b3b461b0f3b1dfe4f2f2e6d0e79b014ab  brew-cask-completion--2.1_1.arm64_big_sur.bottle.tar.gz
a5256bbd0456fc15083d843e7cc3778fd45dfd3562b14bf076e0a08bcc04948a  brew-cask-completion--2.1_1.big_sur.bottle.tar.gz
a5256bbd0456fc15083d843e7cc3778fd45dfd3562b14bf076e0a08bcc04948a  brew-cask-completion--2.1_1.catalina.bottle.tar.gz
a5256bbd0456fc15083d843e7cc3778fd45dfd3562b14bf076e0a08bcc04948a  brew-cask-completion--2.1_1.mojave.bottle.tar.gz

❌

**Comment by Moisan** [comment]
```
❯ diffoscope brew-cask-completion--2.1_1.arm64_big_sur.bottle.tar.gz brew-cask-completion--2.1_1.big_sur.bottle.tar.gz
--- brew-cask-completion--2.1_1.arm64_big_sur.bottle.tar.gz
+++ brew-cask-completion--2.1_1.big_sur.bottle.tar.gz
│   --- brew-cask-completion--2.1_1.arm64_big_sur.bottle.tar
├── +++ brew-cask-completion--2.1_1.big_sur.bottle.tar
│ ├── file list
│ │ @@ -2,8 +2,8 @@
│ │  drwxr-xr-x   0        0        0        0 2016-10-10 04:08:10.000000 brew-cask-completion/2.1_1/.brew/
│ │  -rw-r--r--   0        0        0      536 2016-10-10 04:08:10.000000 brew-cask-completion/2.1_1/.brew/brew-cask-completion.rb
│ │  -rw-r--r--   0        0        0     1238 2016-10-10 04:08:10.000000 brew-cask-completion/2.1_1/LICENSE
│ │  -rw-r--r--   0        0        0      868 2016-10-10 04:08:10.000000 brew-cask-completion/2.1_1/README.md
│ │  drwxr-xr-x   0        0        0        0 2016-10-10 04:08:10.000000 brew-cask-completion/2.1_1/share/
│ │  drwxr-xr-x   0        0        0        0 2016-10-10 04:08:10.000000 brew-cask-completion/2.1_1/share/fish/
│ │  drwxr-xr-x   0        0        0        0 2016-10-10 04:08:10.000000 brew-cask-completion/2.1_1/share/fish/vendor_completions.d/
│ │ --rw-r--r--   0        0        0     7419 2016-10-10 04:08:10.000000 brew-cask-completion/2.1_1/share/fish/vendor_completions.d/brew-cask.fish
│ │ +-rw-r--r--   0        0        0     7422 2016-10-10 04:08:10.000000 brew-cask-completion/2.1_1/share/fish/vendor_completions.d/brew-cask.fish
│ ├── brew-cask-completion/2.1_1/share/fish/vendor_completions.d/brew-cask.fish
│ │ @@ -19,15 +19,15 @@
│ │  end
│ │
│ │  function __fish_brew_cask_casks
│ │    find (brew --repository)/Library/Taps/caskroom/homebrew-cask/Casks -name "*.rb" -print | sed 's/.rb$//' | sed "s|^.*/||"
│ │  end
│ │
│ │  function __fish_brew_cask_caskroom
│ │ -  ls @@HOMEBREW_PREFIX@@-cask/Caskroom/
│ │ +  ls /opt/homebrew-cask/Caskroom/
│ │  end
│ │
│ │  function __fish_brew_cask_installed_casks
│ │    brew-cask list -1
│ │  end
│ │
│ │
│ │ @@ -149,14 +149,14 @@
│ │  # --internet_plugindir
│ │  complete -f -c brew-cask -n '__fish_brew_cask_needs_command' -l internet_plugindir -d 'Target location for Internet Plugin links'
│ │
│ │  # --screen_saverdir
│ │  complete -f -c brew-cask -n '__fish_brew_cask_needs_command' -l screen_saverdir -d 'Target location for Screen Saver links'
│ │
│ │  # --no-binaries
│ │ -complete -f -c brew-cask -n '__fish_brew_cask_needs_command' -l no-binaries -d 'Do not link ahelpera executables to /usr/local/bin'
│ │ +complete -f -c brew-cask -n '__fish_brew_cask_needs_command' -l no-binaries -d 'Do not link ahelpera executables to @@HOMEBREW_PREFIX@@/bin'
│ │
│ │  # --binarydir
│ │  complete -f -c brew-cask -n '__fish_brew_cask_needs_command' -l binarydir -d 'Target location for ahelpera executable links'
│ │
│ │  # --debug
│ │  complete -f -c brew-cask -n '__fish_brew_cask_needs_command' -l debug -d 'Output debugging information'
```

**Comment by carlocab** [comment]
That's awkward. We should probably tighten the replacement regex to rule out the match here.

**Comment by Moisan** [comment]
Yeah, I don't know how to handle that. And the latest release dates back from 2016.

**Comment by Moisan** [comment]
I'll close the PR for now unless someone finds a reason for `/opt/homebrew-cask`.

**Comment by nandahkrishna** [comment]
We might want to consider deprecating or disabling this formula. It requires the old [`brew-cask ls` command](https://github.com/xyb/homebrew-cask-completion/blob/4b3c5b6fe4d73c08ce9f07f22161e09c8577d7b8/homebrew-cask-completion.bash#L59) to work, to generate a list of all casks. It also has completions for the now-disabled/removed `alfred` subcommand.

> That said, not sure `/opt/homebrew-cask` is a thing.

I believe this might've been the Caskroom prefix from back then (as seen here https://github.com/Homebrew/homebrew-cask/issues/22663).

It's got 1800+ installs in the last 30 days though.

**Pull request closed without merging**
