### PR TITLE
petsc-complex petsc 3.21.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
ld: unknown option: -no_warn_duplicate_libraries
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by abhinavsns** [comment]
The new Xcode toolkit has a new linker and probably it is necessary to use LDFLAGS='-Wl, -ld_classic' for linking to work correctly.

**Comment by timsutton** [comment]
> The new Xcode toolkit has a new linker and probably it is necessary to use LDFLAGS='-Wl, -ld_classic' for linking to work correctly.

It complains about `ld: unknown option: -no_warn_duplicate_libraries`. It seems to fail only on the Ventura runners, but which are still on Xcode 15.2 according to CI. Perhaps we can try out [this commit](https://gitlab.com/petsc/petsc/-/commit/1799f4a2cd937edd8bf461d58977dd1134fe4888) or some variant of it.

**Comment by timsutton** [comment]
>Perhaps we can try out [this commit](https://gitlab.com/petsc/petsc/-/commit/1799f4a2cd937edd8bf461d58977dd1134fe4888) or some variant of it.

nvm, that commit is already in the latest tagged release.

**Comment by timsutton** [comment]
I can build this on Ventura and Sonoma Apple Silicon by just removing this line:
```
diff --git a/config/BuildSystem/config/setCompilers.py b/config/BuildSystem/config/setCompilers.py
index 58c9c43d4bb..61f3240889f 100644
--- a/config/BuildSystem/config/setCompilers.py
+++ b/config/BuildSystem/config/setCompilers.py
@@ -2463,8 +2463,6 @@ class Configure(config.base.Configure):
     if hasattr(self, 'FC'):
       languages.append('FC')
     ldTestFlags = ['-Wl,-bind_at_load', '-Wl,-commons,use_dylibs', '-Wl,-search_paths_first', '-Wl,-no_compact_unwind']
-    if self.LDFLAGS.find('-Wl,-ld_classic') < 0:
-      ldTestFlags.append('-Wl,-no_warn_duplicate_libraries')
     for language in languages:
       self.pushLanguage(language)
       for testFlag in ldTestFlags:
```

I can follow up with adding this to formula-patches and filing an upstream issue when I find a bit of time.

**Comment by chenrui333** [comment]
> -    if self.LDFLAGS.find('-Wl,-ld_classic') < 0:
> -      ldTestFlags.append('-Wl,-no_warn_duplicate_libraries')

that should also check the xcode version as well.

**Comment by cho-m** [comment]
> looks like they missed the xcode version check

Bit strange as it looks like `-no_warn_duplicate_libraries` was introduced in Xcode 15.0.

On side note, we are setting `-ld_classic` via `open-mpi`  due to https://github.com/Homebrew/homebrew-core/commit/f1b2b17efc6e3d5158423c5b952c0567c614830f (`-Wl,-ld_classic` gets stored in installed pkgconfig files and wrapper scripts)

I think issue is `LDFLAGS` detection isn't able to see specific `open-mpi` flags and it is causing the build to use both, i.e. `-Wl,-no_warn_duplicate_libraries ... -Wl,-ld_classic`.

This doesn't seem to be supported in Xcode 15.1 / 15.2.

**Pull request closed without merging**
