### PR TITLE
yq 4.9.3

### PR DESCRIPTION
**Pull request by mikefarah**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moulick** [comment]
hey @mikefarah , why closed this ?

**Comment by mikefarah** [comment]
I stuffed it up, it had conflicts. I need to fix my Brew up :)
________________________________

**Comment by mikefarah** [comment]
To clarify its my local brew set-up that's confused, the bump-pr command didn't work properly. Hopefully someone else bumps it, otherwise I'll look into it when I back from my trip on Monday
________________________________

**Comment by Moulick** [comment]
@mikefarah  I covered it in https://github.com/Homebrew/homebrew-core/pull/77788, enjoy your trip :)

**Comment by mikefarah** [comment]
Cheers mate!
________________________________

**Pull request closed without merging**
