### PR TITLE
bazel 6.1.2

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
[12-arm64](https://github.com/Homebrew/homebrew-core/actions/runs/4734802273/jobs/8406436103#step:8:11146):

```
  src/main/tools/process-wrapper-legacy.cc:80: "execvp(external/remote_java_tools_darwin/java_tools/ijar/ijar, ...)": Bad CPU type in executable
```

[11-arm64](https://github.com/Homebrew/homebrew-core/actions/runs/4734802273/jobs/8406436478#step:8:13858):

```
  java.lang.NoClassDefFoundError: java/util/Itytator
  	at com.google.turbine.binder.ClassPathBinder.bindJar(ClassPathBinder.java:138)
  	at com.google.turbine.binder.ClassPathBinder.bindClasspath(ClassPathBinder.java:67)
  	at com.google.turbine.main.Main.bootclasspath(Main.java:311)
  	at com.google.turbine.main.Main.compile(Main.java:141)
  	at com.google.turbine.main.Main.compile(Main.java:132)
  	at com.google.turbine.main.Main.main(Main.java:88)
  Caused by: java.lang.ClassNotFoundException: java.util.Itytator
  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  	... 6 more
```

**Comment by chenrui333** [comment]
maybe also report this into the upstream?

**Comment by ZhongRuoyu** [comment]
Will do, but let me try to have a look at it first.

**Comment by ZhongRuoyu** [comment]
The 12-arm64 failure seems related to https://github.com/bazelbuild/bazel/issues/13944.

**Comment by ZhongRuoyu** [comment]
I'll revisit this.

**Comment by chenrui333** [comment]
#130269

**Pull request closed without merging**
