### PR TITLE
mysql-client 8.0.18; create mysql-client@5.7; merge mysql-connector-c into mysql-client

### PR DESCRIPTION
**Pull request by Bo98**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Note that I have **not** yet tested all the formulae I have revision bumped. It is possible some will be incompatible with 8.0 and will require to depend on `mysql-client@5.7`.

### CODE REVIEW

**Comment by Bo98** [comment]
It would help if I wasn't an idiot: `ntopng: undefined method `revision' for #<SoftwareSpec:0x00007fee5bca8f68>`

**Comment by Bo98** [comment]
No compile errors? I'm suspicious.

**Comment by fxcoudert** [comment]
poke @commitay who introduced this formula, with its `Pinned at `5.7.*` comment: https://github.com/Homebrew/homebrew-core/pull/28085 & https://github.com/Homebrew/homebrew-core/pull/27210

**Comment by commitay** [comment]
When `mysql` was upgraded to 8.0 it couldn't be built on el capitan, which still had several months of support left at the time. As there was a dozen or so formulae with a `mysql` dep we made `mysql-client` rather than pinning all of them to the versioned `mysql@5.7` formula.

**Comment by fxcoudert** [comment]
OK so now we probably simply want to remove mysql-client, right?

**Comment by Bo98** [comment]
It comes to no surprise that mysql-client can be seen as MySQL without the server part. And indeed it is the same source code.
Equally, mysql-client can be seen as the Connector/C replacement - and indeed it recommended for people wanting to connect to MySQL servers as clients.

Although El Capitan may be the reason for pinning 5.7, I don't really see how that was the reason to have created mysql-client over using the already existing mysql@5.7 formula.

mysql-client vs mysql isn't actually too dissimilar to mariadb-connector-c vs mariadb, though they're developed slightly differently than the way MySQL do it. One advantage I see is that you can have mysql-client and mariadb-connector-c installed together without conflicts, but you cannot have mysql and mariadb installed together without forcing it.

Whatever path is chosen, I strongly encourage having the mysql-connector-c -> whatever rename, particular with the high install count. The mapping to mysql-client was natural because they became synonyms. The mapping to mysql server less so but it is just a superset of the client.

**Comment by fxcoudert** [comment]
@Homebrew/core what's your opinion?

**Review by chenrui333 — APPROVED** [review]
Lgtm

**Comment by SMillerDev** [comment]
Works for me. And after this all the bumped formula depend on "mysql-client"? Or still on the connector naming?

**Comment by Bo98** [comment]
There is no change the dependencies. The bumped formulae depended on mysql-client before. Nothing depended on mysql-connector-c, though there's some conflicts_with I should probably remove that I forgot about.

**Comment by SMillerDev** [comment]
Yeah, that would be great.

**Comment by Bo98** [comment]
The old CI job expired anyway so me doing that will get a fresh one again.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
