### PR TITLE
dar: build on Apple Silicon without `upx` compressed binary

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
I would suggest removing the dependency entirely and passing `--disable-upx`. It's been problematic on OS upgrades in the past, even as far as having discussions with Apple about it, and I doubt the benefits are very high (but feel free to compare).

**Review by carlocab — APPROVED** [review]

**Comment by cho-m** [comment]
Probably fine to remove.

The largest binary is `dar` at **414K** without `upx` and **129K** with. It does provide a 3.2x compression, but still within reason without `upx`.
 
Existing:
```console
❯ ls -lh /usr/local/Cellar/dar/2.7.4/bin
total 396K
-r-xr-xr-x 1 cho-m admin 129K Mar 13 08:22 dar
-r-xr-xr-x 1 cho-m admin  53K Mar 13 08:22 dar_cp
-r-xr-xr-x 1 cho-m admin  73K Mar 13 08:22 dar_manager
-r-xr-xr-x 1 cho-m admin  53K Mar 13 08:22 dar_slave
-r-xr-xr-x 1 cho-m admin  13K Mar 13 08:22 dar_split
-r-xr-xr-x 1 cho-m admin  57K Mar 13 08:22 dar_xform
```

Without `upx`:
```console
❯ ls -lh /usr/local/Cellar/dar/2.7.4/bin
total 1.3M
-r-xr-xr-x 1 cho-m admin 414K Apr  6 18:43 dar
-r-xr-xr-x 1 cho-m admin 177K Apr  6 18:43 dar_cp
-r-xr-xr-x 1 cho-m admin 238K Apr  6 18:43 dar_manager
-r-xr-xr-x 1 cho-m admin 177K Apr  6 18:43 dar_slave
-r-xr-xr-x 1 cho-m admin  50K Apr  6 18:43 dar_split
-r-xr-xr-x 1 cho-m admin 178K Apr  6 18:43 dar_xform
```

**Comment by carlocab** [comment]
3.2x is pretty significant though. I suggest leaving it in for now and deactivating it if we find need to. We can document this in a comment too so anyone trying to fix the formula will be able to do so easily.

**Review by SMillerDev — APPROVED** [review]

**Comment by Bo98** [comment]
I'd be very cautious about any arch conditionals though. We don't have a proper system for arch-specific dependencies, so I generally advise to avoid them. `if/unless Hardware::CPU.whatever?` trips up audits since you cannot get a dependency graph for non-host systems like we do with `on_macos` and `on_linux`.

We probably should have something for at least GHC, but we currently don't.

**Pull request closed without merging**
