### PR TITLE
terminalizer 0.7.2 (new formula)

### PR DESCRIPTION
**Pull request by curoky**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Your test is failing because `node@14` is keg-only. You need to wrap the executables in an env script.

**Comment by curoky** [comment]
https://github.com/faressoft/terminalizer/blob/fb079fc3e4a2a7e4939c65f9fe29c7fc96e1a73d/package.json#L50

Terminalizer depends on electron with version(^7.1.14), its version is too low to support darwin-arm64. Should we skip CI on arm64? @carlocab

**Comment by curoky** [comment]
Electron which Terminalizer depends on has pre-built binary in dist directory.

```
➜ l /home/linuxbrew/.linuxbrew/Cellar/terminalizer/0.7.2/libexec/lib/node_modules/terminalizer/node_modules/electron/dist/          
Permissions Size User   Date Modified Name
.rwxr-xr-x  5.6M curoky 21 Oct 20:33  chrome-sandbox*
.rw-r--r--  178k curoky 21 Oct 20:33  chrome_100_percent.pak
.rw-r--r--  317k curoky 21 Oct 20:33  chrome_200_percent.pak
.rwxr-xr-x  116M curoky 21 Oct 20:33  electron*
.rw-r--r--   10M curoky 21 Oct 20:33  icudtl.dat
.rwxr-xr-x  248k curoky 21 Oct 20:33  libEGL.so*
.rwxr-xr-x  3.0M curoky 21 Oct 20:33  libffmpeg.so*
.rwxr-xr-x  8.4M curoky 21 Oct 20:33  libGLESv2.so*
.rw-r--r--  1.1k curoky 21 Oct 20:33  LICENSE
.rw-r--r--  4.7M curoky 21 Oct 20:33  LICENSES.chromium.html
drwxr-xr-x     - curoky 21 Oct 20:33  locales/
.rw-r--r--   82k curoky 21 Oct 20:33  natives_blob.bin
drwxr-xr-x     - curoky 21 Oct 20:33  resources/
.rw-r--r--  8.6M curoky 21 Oct 20:33  resources.pak
.rw-r--r--  280k curoky 21 Oct 20:33  snapshot_blob.bin
drwxr-xr-x     - curoky 21 Oct 20:33  swiftshader/
.rw-r--r--  701k curoky 21 Oct 20:33  v8_context_snapshot.bin
.rw-r--r--     5 curoky 21 Oct 20:33  version
```

The prebuild binary electron depends on many dynamic libraries. We can't solve the problem just by adding depends_on in formula, because electron doesn't known where to find it.

```
➜ ldd electron                  
        linux-vdso.so.1 (0x00007ffed2d94000)
        libffmpeg.so => /home/linuxbrew/.linuxbrew/Cellar/terminalizer/0.7.2/libexec/lib/node_modules/terminalizer/node_modules/electron/dist/./libffmpeg.so (0x00007f76ae8cd000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f76ae8c3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f76ae8a1000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f76ae896000)
        libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f76ae83b000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f76ae703000)
        libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f76ae533000)
        libX11.so.6 => not found
        libX11-xcb.so.1 => not found
        libxcb.so.1 => not found
        libXcomposite.so.1 => not found
        libXcursor.so.1 => not found
        libXdamage.so.1 => not found
        libXext.so.6 => not found
        libXfixes.so.3 => not found
        libXi.so.6 => not found
        libXrender.so.1 => not found
        libXtst.so.6 => not found
        libnss3.so => not found
        libnssutil3.so => not found
        libsmime3.so => not found
        libnspr4.so => not found
        libgdk_pixbuf-2.0.so.0 => not found
        libgtk-3.so.0 => not found
        libgdk-3.so.0 => not found
        libpangocairo-1.0.so.0 => not found
        libpango-1.0.so.0 => not found
        libatk-1.0.so.0 => not found
        libcairo.so.2 => not found
        libdbus-1.so.3 => not found
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f76ae4fc000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f76ae4f3000)
        libXrandr.so.2 => not found
        libXss.so.1 => not found
        libasound.so.2 => not found
        libatk-bridge-2.0.so.0 => not found
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f76ae3a3000)
        libatspi.so.0 => not found
        libcups.so.2 => not found
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f76ae386000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f76ae19a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f76b5cbf000)
        libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007f76ae18e000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f76ae118000)
        libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f76ae112000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f76ae0f4000)
        libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f76ae097000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f76ae06b000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f76ae050000)
        libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007f76adffe000)
        libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f76adf65000)
```

Although we can force the search path with patchelf, we can't guarantee that the linked version will always be appropriate. Perhaps we need wait for electron formula.

**Comment by SMillerDev** [comment]
> Electron which Terminalizer depends on has pre-built binary in dist directory.

https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

**Pull request closed without merging**
