### PR TITLE
dolt 0.15.2 (new formula)

### PR DESCRIPTION
**Pull request by ankane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Version control for data

### CODE REVIEW

**Comment by chenrui333** [comment]
@ankane Thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by chenrui333** [comment]
Looks like there are some audit failures need to be addressed.

**Comment by ankane** [comment]
Thanks @chenrui333!

Re audit failures: it looks like it's internal to Homebrew?

```
==> brew audit dolt --online --new-formula
Error: undefined method `provided_by_macos?' for nil:NilClass
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:406:in `block (2 levels) in audit_deps'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:378:in `block in audit_deps'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:375:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:375:in `audit_deps'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1017:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1010:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:1010:in `audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:117:in `block in audit'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:110:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:110:in `audit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
==> FAILED
```

**Comment by MikeMcQuaid** [comment]
CI is green now.

**Comment by chenrui333** [comment]
🎉 Merging the PR!

**Comment by timsehn** [comment]
Thank you from the Dolt team!

**Pull request closed without merging**
