### PR TITLE
Add dynamic option for nomad

### PR DESCRIPTION
**Pull request by ProbablyRusty**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

- Add option “with-dynamic” to nomad, in order to optionally build with CGO_ENABLED
- This is a common use case for some VPN users on Mac OS X
- See:   https://github.com/Homebrew/homebrew-core/pull/7238

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
See https://github.com/Homebrew/homebrew-core/pull/7238#issuecomment-263052115

**Comment by consultantRR** [comment]
@MikeMcQuaid in light of https://github.com/Homebrew/homebrew-core/pull/7238 can we remove Do Not Merge on this as well?

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

For future reference the preferred commit message format is `nomad: add dynamic option.`. Please complete the issue template in future PRs where this format is detailed in the linked [Contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md). Thanks!

**Pull request closed without merging**
