### PR TITLE
neo4j@3 3.5.18 (new formula)

### PR DESCRIPTION
**Pull request by danielmcq**
Adding a 3.x version of neo4j. The reason for a 3.x version of neo4j is that the 4.x
versions are not 100% compatible with queries written for the 3.x versions. It is
convenient to be able to use homebrew to get one of the previous major versions.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Neo4j 3.5 will be EOL in a few months, see https://support.neo4j.com/hc/en-us/articles/4407792164755-Neo4j-3-5-EOL-End-of-Life-Extension

This might be a better fit for a tap: https://docs.brew.sh/Taps. Or we need to add a deprecation date.

**Comment by danielmcq** [comment]
I went with adding the deprecation to the formula.

**Comment by SMillerDev** [comment]
Since upstream planned to have it deprecated already I don't think we should add it here for a couple of months.

**Comment by danielmcq** [comment]
Closing until 2022-05-27.

**Comment by iMichka** [comment]
Just to be clear, we won't add it, even later.
I think the best solution for you is to create a tap, https://docs.brew.sh/Taps, which is pretty easy.

**Pull request closed without merging**
