### PR TITLE
cheat 3.0.1

### PR DESCRIPTION
**Pull request by chenrui333**
bump the version.

### CODE REVIEW

**Comment by dawidd6** [comment]
`cheat` has been rewritten in Go.

**Comment by chenrui333** [comment]
I see, I will update the formula accordingly then.

**Comment by chenrui333** [comment]
Have some local build issues
I will probably hold off they have some CI in place.

**Comment by dawidd6** [comment]
New release: https://github.com/cheat/cheat/releases/tag/3.0.1

Upstream is now using Go modules, so simple:
```ruby
system("go", "build", "-o", bin/"cheat", "./cmd/cheat")
```
should be sufficient.

**Comment by chenrui333** [comment]
@dawidd6 yeah, it did not quite work out for me, somehow.

**Pull request closed without merging**
