### PR TITLE
molten-vk 1.1.7

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by Porkepix** [comment]
Updated comments to make it more clear where to find SPIRV-Tools and SPIRV-Headers
revisions, this was quite confusing as I was looking for them in the Molten-VK repo.

**Comment by SMillerDev** [comment]
Linux fails to find python
```
==> ./build_info.py . -i build_info.h.tmpl -o build/include/glslang/build_info.h
/usr/bin/env: ‘python’: No such file or directory
```

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
> Linux fails to find python
> 
> ```
> ==> ./build_info.py . -i build_info.h.tmpl -o build/include/glslang/build_info.h
> /usr/bin/env: ‘python’: No such file or directory
> ```

I'd be pretty surprised if this worked on Linux. We'd probably at least have to package a macOS SDK

**Comment by SMillerDev** [comment]
Oh yeah, I hadn't realized that this was the macOS specific parts of Vulkan. We should add a `depends_on :macos` then.

**Pull request closed without merging**
