### PR TITLE
bison 3.7

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dtrodrigues** [comment]
Strange that `bump-formula-pr` didn't put the correct hash. Should be `sha256 "07b25fbf4de2f2c686e8bff50fdb69efda49b6f9f7377dad1884f9508a28592b"`

**Comment by alebcay** [comment]
I passed the checksum of the tarball from the mirror as the `--sha256` argument. Looks like the tarball on the main and mirror sites don't match.

```
❯ remotesum "https://ftp.gnu.org/gnu/bison/bison-3.7.tar.xz"
07b25fbf4de2f2c686e8bff50fdb69efda49b6f9f7377dad1884f9508a28592b

❯ remotesum "https://ftpmirror.gnu.org/bison/bison-3.7.tar.xz"
dd2943d2f8c69925d2c6248e82f232d5c75efca81b0b16d580773e2d890133b6
```

**Comment by alebcay** [comment]
Upon further investigation, this turns out to be a case of PEBCAK. I think GNU may have changed something in how their mirrors work (there's now a redirect in there somewhere), but it seems to have thrown off the checksum when I calculated it.

**Comment by dtrodrigues** [comment]
Yeah it looks like it redirects and some of the places it redirects to don't currently have the tar located there yet, eg https://mirror.clarkson.edu/gnu/bison/bison-3.7.tar.xz and https://mirror.clarkson.edu/gnu/bison/bison-3.7.tar.xz. 

You also don't need to manually supply the `sha256` since `bump-formula-pr` will do that for you. When I was testing it locally, `brew bump-formula-pr bison --url https://ftp.gnu.org/gnu/bison/bison-3.7.tar.xz` updated the `url`, `mirror`, and `sha256` correctly.

**Review by dtrodrigues — APPROVED** [review]

**Comment by xeron** [comment]
Too bad it doesn't even compile:
```
  CCLD     src/bison
Undefined symbols for architecture x86_64:
  "_ostream_printf", referenced from:
      _complains in bison-complain.o
  "_styled_ostream_set_hyperlink", referenced from:
      _complains in bison-complain.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/bison] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

HOMEBREW_VERSION: 2.4.8-105-g1b7c498
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 1b7c498d354a098572cfcf06e18d54ff25c4c0b8
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 371fa3ff9a4f247f46fc7fcd4730b45fd475b466
Core tap last commit: 35 minutes ago
HOMEBREW_PREFIX: /opt/brew
HOMEBREW_REPOSITORY: /opt/brew
HOMEBREW_CELLAR: /opt/brew/Cellar
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.8433AdmXug/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /opt/brew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 10.0 build 1001
Git: 2.27.0 => /opt/brew/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.6-zulu-11.37+17, 1.8.0_242-zulu-8.44.0.11
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /opt/brew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2:/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/brew/Library/Homebrew/os/mac/pkgconfig/10.14
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
ACLOCAL_PATH: /opt/brew/share/aclocal
PATH: /opt/brew/Library/Homebrew/shims/mac/super:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by xeron** [comment]
https://lists.gnu.org/archive/html/bug-bison/2020-07/msg00030.html

**Comment by alebcay** [comment]
Interesting that it built and bottled just fine yet is failing to build from source (verified locally that it will not build). Thanks for the mailing list thread though.

**Pull request closed without merging**
