### PR TITLE
harfbuzz 1.2.7

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@UniqMartin So this one requires like 500 other things to be bumped right?

**Comment by UniqMartin** [comment]
@ilovezfs No, the evil one is `icu4c`. `harfbuzz` just has a dependency on `icu4c` and by including it in its `pkg-config` files et al. it helps spreading this dependency. But bumping `harfbuzz` alone shouldn't be a hassle as far as I know.

**Comment by ilovezfs** [comment]
@UniqMartin OK, thanks for putting my mind at ease.

**Comment by DomT4** [comment]
Yeah, these are generally simple bumps. 👍.

**Pull request closed without merging**
