### PR TITLE
sqlite 3.34.0

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by miccal** [comment]
`dbhash` PR: https://github.com/Homebrew/homebrew-core/pull/66043
`sqldiff` PR: https://github.com/Homebrew/homebrew-core/pull/66024
`sqlite-analyzer` PR: https://github.com/Homebrew/homebrew-core/pull/66044

**Review by SMillerDev — APPROVED** [review]

**Comment by chenrui333** [comment]
11.0

```
Error: 31 failed steps!
brew test --retry --verbose asuka
brew test --retry --verbose augustus
brew test --retry --verbose cargo-edit
brew test --retry --verbose condure
brew test --retry --verbose corral
brew test --retry --verbose creduce
brew test --retry --verbose cython
brew test --retry --verbose glyr
brew test --retry --verbose gobject-introspection
brew test --retry --verbose hyperkit
brew test --retry --verbose innotop
brew linkage --test mapnik
brew install mariadb
brew install mariadb@10.1
brew install mariadb@10.2
brew install mariadb@10.3
brew install mariadb@10.4
brew test --retry --verbose mysql@5.6
brew test --retry --verbose mysql@5.7
brew test --retry --verbose networkit
brew test --retry --verbose odin
brew test --retry --verbose pcl
brew install percona-server
brew test --retry --verbose pipgrip
brew test --retry --verbose pony-stable
brew test --retry --verbose ponyc
brew test --retry --verbose pre-commit
brew install pypy
brew install pypy3
brew test --retry --verbose root
brew test --retry --verbose zurl
```

10.15

```
Error: 11 failed steps!
brew test --retry --verbose cargo-edit
brew linkage --test mapnik
brew install mariadb
brew install mariadb@10.1
brew install mariadb@10.2
brew install mariadb@10.3
brew install mariadb@10.4
brew test --retry --verbose mysql@5.6
brew test --retry --verbose mysql@5.7
brew test --retry --verbose pcl
brew install percona-server
```

10.14

```
Error: 11 failed steps!
brew test --retry --verbose cargo-edit
brew linkage --test mapnik
brew install mariadb
brew install mariadb@10.1
brew install mariadb@10.2
brew install mariadb@10.3
brew install mariadb@10.4
brew test --retry --verbose mysql@5.6
brew test --retry --verbose mysql@5.7
brew test --retry --verbose pcl
brew install percona-server
```

**Comment by miccal** [comment]
Thanks @chenrui333 -- the obvious place to start here would be woth the linkage error for `mapnik`, but there was an issue with this in my other PR of `poppler` [here](https://github.com/Homebrew/homebrew-core/pull/66042), so I am a bit unsure how to best move forward here.

**Comment by chenrui333** [comment]
let's go with the merge and fix the issues separately (like what we did before).

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
