### PR TITLE
Fix style for llvm@3.9 and ruby@2.3

### PR DESCRIPTION
**Pull request by maxim-belkin**
Before:
```sh
$ brew style *.rb
== llvm@3.9.rb ==
C: 82:  1: Extra blank line detected.
== ruby@2.3.rb ==
C: 25:  1: Extra blank line detected.

4091 files inspected, 2 offenses detected
```

After:
```sh
$ brew style llvm\@3.9.rb ruby\@2.3.rb 

2 files inspected, no offenses detected
```

### CODE REVIEW

**Comment by fxcoudert** [comment]
Can you make those two commits, with commit message `llvm@3.9: fix style` (and same for ruby)

**Comment by maxim-belkin** [comment]
sure...

**Comment by ilovezfs** [comment]
It is odd this was no caught by `brew audit --new-formula` for llvm@3.9. I thought we ran `brew style` for that. :bug:?

**Comment by ilovezfs** [comment]
Ah it's because it happened in the bottle block commit and `brew pull` doesn't re-check after applying that.

**Comment by maxim-belkin** [comment]
but then it means that code that adds bottle block does it wrong

**Comment by ilovezfs** [comment]
@maxim-belkin yup, there are definitely cases where it applies it incorrectly.

**Comment by ilovezfs** [comment]
_ilovezfs will try to remember to be more careful next time._

**Comment by fxcoudert** [comment]
Merged, thanks @maxim-belkin !

**Pull request merged**
