### PR TITLE
yt-dlp 2022.3.8.1

### PR DESCRIPTION
**Pull request by bevanjkay**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
```
File "/private/tmp/yt-dlp-20220308-98604-1sbju7t/yt-dlp-2022.3.8.1/setup.py", line 26, in <module>
        REQUIREMENTS = open('requirements.txt', encoding='utf-8').read().splitlines()
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    error: subprocess-exited-with-error
```

**Comment by bevanjkay** [comment]
Is this a bug upstream @cho-m 
https://github.com/yt-dlp/yt-dlp/commit/4390d5ec12349e5b5bba30af6b4e7f08678af41a#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7

**Comment by cho-m** [comment]
Yeah. The `setup.py` has reference to `requirements.txt` but PyPI source tarball is missing the file making it not possible to build.

**Comment by bevanjkay** [comment]
Superseded by #96537

**Comment by pukkandan** [comment]
Sorry about the headache. I didn't realize requirements.txt was not being packed in the tar

**Pull request closed without merging**
