### PR TITLE
kubescape: add "v' to version. (v2.0.149 instead of 2.0.149)

### PR DESCRIPTION
**Pull request by rotemamsa**
if there is some other proper way doing that- ill be happy to hear

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@rotemamsa what is the concern about the `kubescape version` output?

**Comment by cho-m** [comment]
Probably to solve armosec/kubescape#417. Looks like a version comparison is done on strings so official `v`-prefixed versions will always be "newer" than Homebrew's versions.

---

We would need a `revision 1` to provide update to all existing users.

Not sure if this is wanted for `head` build? I think version would be Git commit.

**Comment by rotemamsa** [comment]
@cho-m you mentioned the exact reason, we are sticking to Kubernetes versioning format and that is why we added the 'v' sign to our prev version.
its not effecting the content of the version, just version numbering

**Comment by chenrui333** [comment]
> We would need a `revision 1` to provide update to all existing users.

agree, we need `revision bump` for users.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
