### PR TITLE
Python 3.9 mass migration

### PR DESCRIPTION
**Pull request by fxcoudert**
Leaving out all independent formulas (see https://github.com/Homebrew/homebrew-core/issues/62201) is it doable to migrate all the rest in one huge PR?

### CODE REVIEW

**Comment by fxcoudert** [comment]
So, what did we learn from the first round? It ran for 53 hours, and built 35 bottles. But, most of that time is spent in a couple of formulas: `rust` takes 3 hours to build, and 6 more hours to test all its dependents; `node` is a couple of hours; `llvm` also. Also, it tried *many* times to rebuild `libxml2` from source, and kept failing.

## Failures

```
libxml2 fails to build with:

libxml.c:297:15: error: expected '(' after 'if'
    } else if PyUnicode_Check (ret) {
              ^
```

```
brew linkage --test gst-editing-services
==>FAILED
Broken dependencies:
  /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Python (python@3.8)
No broken library linkage detected
==>Testing gst-editing-services
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201009-83220-15xzthx.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gst-editing-services.rb --verbose --retry
/usr/local/Cellar/gst-editing-services/1.18.0/bin/ges-launch-1.0 --ges-version
dyld: Library not loaded: /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Python
  Referenced from: /usr/local/Cellar/gst-editing-services/1.18.0/lib/libges-1.0.0.dylib
  Reason: image not found
```

```
brew linkage --test gst-plugins-bad
==>FAILED
Broken dependencies:
  /usr/local/opt/srt/lib/libsrt.1.dylib (srt)
```

```
brew install --build-from-source findomain
==>FAILED
Downloading https://github.com/Edu4rdSHL/findomain/archive/2.1.4.tar.gz
Downloading from https://codeload.github.com/Findomain/Findomain/tar.gz/2.1.4
Error: SHA256 mismatch
Expected: e669e5297c3112ec4e256bef286028220dcb9d46cd8a31e6965cbbc3d2ae3199
  Actual: dd193f3b2d81b05769efbf2a2c7af7479395617204343c84fb5d7e1b0bec9d83
```

```
brew install --build-from-source mdbook
==>FAILED
Downloading https://github.com/rust-lang/mdBook/archive/v0.4.3.tar.gz
Downloading from https://codeload.github.com/rust-lang/mdBook/tar.gz/v0.4.3
Error: SHA256 mismatch
Expected: e1a60eb877a95c6cf8832cb158a8f09b2d641206fe853378905bcdb962902935
  Actual: 3a3c4da76ff47943dbd5d490567a3d283cf85889f16d4d96ae04328371c1a817
```

```
brew install --build-from-source spotifyd
==>FAILED
error: failed to run custom build command for `coreaudio-sys v0.2.3`
```

```
brew audit llvm --online --git --skip-style
==>FAILED
Error: 1 problem in 1 formula detected
llvm:
  * Packages have been installed for:
      Python 3.8
    but this formula depends on:
      Python 3.9
```

```
brew audit vapoursynth --online --git --skip-style
==>FAILED
Error: 1 problem in 1 formula detected
vapoursynth:
  * python modules have explicit framework links
    These python extension modules were linked directly to a Python
    framework binary. They should be linked with -undefined dynamic_lookup
    instead of -lpython or -framework Python.
      /usr/local/opt/vapoursynth/lib/python3.9/site-packages/vapoursynth.so
```

```
scipy fails with many errors:

scipy/sparse/linalg/dsolve/SuperLU/SRC/clacon2.c:175:5: error: implicit declaration of function 'ccopy_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
scipy/sparse/linalg/dsolve/SuperLU/SRC/dmach.c:62:9: error: implicitly declaring library function 'strncmp' with type 'int (const char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_cdrop_row.c:196:3: error: implicit declaration of function 'scopy_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_zdrop_row.c:196:3: error: implicit declaration of function 'dcopy_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
scipy/sparse/linalg/dsolve/SuperLU/SRC/smach.c:62:9: error: implicitly declaring library function 'strncmp' with type 'int (const char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
scipy/sparse/linalg/dsolve/SuperLU/SRC/zlacon2.c:175:5: error: implicit declaration of function 'zcopy_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
scipy/sparse/linalg/dsolve/SuperLU/SRC/slacon2.c:160:16: error: implicit declaration of function 'idamax_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
```

**Comment by fxcoudert** [comment]
10.13 tests are over in 37 hours, and the results are not so bad!

```
brew audit vapoursynth --online --git --skip-style
brew audit tbb --online --git --skip-style
brew test --retry --verbose bowtie2
brew install --verbose --build-bottle apache-arrow
brew audit gtk-doc --online --git --skip-style
brew test --retry --verbose gspell
brew test --verbose gdb
brew audit uhd --online --git --skip-style
brew install --verbose --build-bottle afflib
brew install --verbose --build-bottle borgbackup
brew audit cryptominisat --onlinea --git --skip-style
brew test --verbose dnsviz
brew install --build-from-source apache-arrow
brew install --only-dependencies --verbose --build-bottle dvc
brew install --verbose --build-bottle dvc
brew test --verbose eralchemy
brew install --verbose --build-bottle fail2ban
brew install --verbose --build-bottle fdroidserver
brew install --verbose --build-bottle filebeat
brew test --verbose gdbgui
brew test --verbose gnuradio
brew install --verbose --build-bottle lc0
brew test --verbose lensfun
brew audit libpqxx --online --git --skip-style
brew test --verbose mitmproxy
brew install --verbose --build-bottle mypy
brew install --verbose --build-bottle ola
brew install --verbose --build-bottle onnxruntime
brew install --verbose --build-bottle salt
brew test --verbose zim
```

**Comment by fxcoudert** [comment]
- [”mypy 0.790 doesn’t yet officially support the recently released Python 3.9”](https://mypy-lang.blogspot.com/2020/10/mypy-0790-released.html), but we can split that one off, it's independent
- `lc0` says `Dependency 'eigen3' not found and fallback is disabled`
-

**Comment by fxcoudert** [comment]
The most time-consuming formulas remaining in the PR are: `glib gobject-introspection pyqt protobuf bazel libtorch vtk@8.2 gdal vtk ansible emscripten gnuradio kibana libtensorflow libtensorflow@1 mame nest nwchem opencv opencv@3 semgrep wxpython`

Moving some of those away from this PR…

**Comment by fxcoudert** [comment]
CI fails silently after 16 hours, and provides no logs. Wonderful.

**Comment by fxcoudert** [comment]
Each worker has gone through 12 to 15 hours of testing, inside `brew test-bot --only-formulae`, but there are no logs from this step. It’s the second time now, so it seems it’s a systematic issue.

**Comment by fxcoudert** [comment]
10.13:

```
brew install --verbose --build-bottle fail2ban
brew fetch --retry graph-tool --build-bottle --force
brew test --retry --verbose bowtie2
brew test --verbose gnuradio
brew test --retry --verbose openslide
brew audit cryptominisat --online --git --skip-style
brew audit graph-tool --online --git --skip-style
brew audit gtk-doc --online --git --skip-style
brew audit libpqxx --online --git --skip-style
brew audit tbb --online --git --skip-style
brew audit uhd --online --git --skip-style
brew audit vapoursynth --online --git --skip-style
```

**Comment by fxcoudert** [comment]
- Moving `ldns openssh freeswitch` to their separate PR: https://github.com/Homebrew/homebrew-core/pull/63086
- Fixing `scipy` in https://github.com/Homebrew/homebrew-core/pull/63085

**Comment by fxcoudert** [comment]
`apache-arrow` fails to build from source, now that we have LLVM 11:

```
CMake Warning at cmake_modules/FindLLVMAlt.cmake:27 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "10".
```

It prefers LLVM 7 to 10. I've opened a PR upstream: https://github.com/apache/arrow/pull/8492

**Comment by fxcoudert** [comment]
`apache-arrow` was fixed by moving it to `llvm@9`. Retrying.

**Comment by jonchang** [comment]
https://github.com/Homebrew/brew/pull/8958 should be merged before this is done, but if for some reason it isn't hold off on merging this pull request until it is. Could be a real disaster otherwise 😅

**Comment by fxcoudert** [comment]
@jonchang well testing was restarted before the brew PR was written 😄 
Well I'll cancel the workflow, and restart it later.

**Comment by fxcoudert** [comment]
I've merged the boost, bazel, and glib updates. And now we're back to testing! 🤞

**Comment by fxcoudert** [comment]
Great. New style audits blocking all testing.

```
Formula/libxml2.rb:60:10: C: GitLab patches should end with .patch, not .diff:
  https://gitlab.gnome.org/nwellnhof/libxml2/-/commit/e4fb36841800038c289997432ca547c9bfef9db1.
    url "https://gitlab.gnome.org/nwellnhof/libxml2/-/commit/e4fb36841800038c289997432ca547c9bfef9db1.diff"
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Formula/mitmproxy.rb:197:10: C: GitHub patches should end with .patch, not .diff:
  https://github.com/mitmproxy/mitmproxy/commit/8e5e43de.diff?full_index=1
    url "https://github.com/mitmproxy/mitmproxy/commit/8e5e43de.diff?full_index=1"
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Be right back 😭

**Comment by dtrodrigues** [comment]
`redex` failure due to new boost:
```
libredex/Show.cpp:12:10: fatal error: 'boost/io/detail/quoted_manip.hpp' file not found
#include <boost/io/detail/quoted_manip.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
PR in https://github.com/Homebrew/homebrew-core/pull/63266

**Comment by fxcoudert** [comment]
Thanks @dtrodrigues 
I'm going to merge as-is, and we can deal with the test failures and redex build failure in a second time.

**Comment by fxcoudert** [comment]
10.15

```
brew audit vapoursynth --online --git --skip-style
brew audit gtk-doc --online --git --skip-style
brew audit uhd --online --git --skip-style
brew audit cryptominisat --online --git --skip-style
brew audit csound --online --git --skip-style
brew audit cxxtest --online --git --skip-style
brew audit dnsviz --online --git --skip-style
brew test --verbose gnuradio
brew audit mitmproxy --online --git --skip-style
brew audit mkvtomp4 --online --git --skip-style
brew install --verbose --build-bottle redex
```

10.14

```
brew audit vapoursynth --online --git --skip-style
brew audit gtk-doc --online --git --skip-style
brew audit uhd --online --git --skip-style
brew audit anime-downloader --online --git --skip-style
brew audit cmark-gfm --online --git --skip-style
brew audit cmark --online --git --skip-style
brew audit code-server --online --git --skip-style
brew audit cryptominisat --online --git --skip-style
brew audit csound --online --git --skip-style
brew audit gnuradio --online --git --skip-style
brew test --verbose gnuradio
brew audit gprof2dot --online --git --skip-style
brew audit rdiff-backup --online --git --skip-style
brew install --verbose --build-bottle redex
brew audit redex --online --git --skip-style
```

10.13

```
brew audit vapoursynth --online --git --skip-style
brew audit gtk-doc --online --git --skip-style
brew audit uhd --online --git --skip-style
brew audit cryptominisat --online --git --skip-style
brew audit genometools --online --git --skip-style
brew audit git-cola --online --git --skip-style
brew audit gitfs --online --git --skip-style
brew audit gitless --online --git --skip-style
brew test --verbose gnuradio
brew audit libproxy --online --git --skip-style
brew fetch --retry pytouhou --build-bottle --force
brew install --verbose --build-bottle pytouhou
brew install --verbose --build-bottle redex
```

**Comment by fxcoudert** [comment]
```
==> Checking remote file homebrew/bottles/gnuradio-3.8.2.0_3.catalina.bottle.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/2.5.6-112-g0d56c47\ \(Linux\;\ x86_64\ Ubuntu\ 18.04.5\ LTS\)\ curl/7.58.0 --header Accept-Language:\ en --retry 3 --fail --silent --head https://dl.bintray.com/homebrew/bottles/gnuradio-3.8.2.0_3.catalina.bottle.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/2.5.6-112-g0d56c47\ \(Linux\;\ x86_64\ Ubuntu\ 18.04.5\ LTS\)\ curl/7.58.0 --header Accept-Language:\ en --fail --progress-bar --silent --retry 3 --fail --silent --output /dev/null https://api.bintray.com/packages/homebrew/bottles/gnuradio
==> Uploading homebrew/bottles/gnuradio/3.8.2.0_3/gnuradio-3.8.2.0_3.catalina.bottle.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/2.5.6-112-g0d56c47\ \(Linux\;\ x86_64\ Ubuntu\ 18.04.5\ LTS\)\ curl/7.58.0 --header Accept-Language:\ en --fail --progress-bar --silent --retry 3 --fail --upload-file gnuradio--3.8.2.0_3.catalina.bottle.tar.gz --header X-Checksum-Sha2:\ 17573d65b40db37b8354c9ac75b59df89f91630fe89d154c487d50f8b841fb7d --user brewtestbot:****** https://api.bintray.com/content/homebrew/bottles/gnuradio/3.8.2.0_3/gnuradio-3.8.2.0_3.catalina.bottle.tar.gz
curl: Can't open 'gnuradio--3.8.2.0_3.catalina.bottle.tar.gz'!
curl: try 'curl --help' or 'curl --manual' for more information
Error: Failure while executing; `/usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/2.5.6-112-g0d56c47\ \(Linux\;\ x86_64\ Ubuntu\ 18.04.5\ LTS\)\ curl/7.58.0 --header Accept-Language:\ en --fail --progress-bar --silent --retry 3 --fail --upload-file gnuradio--3.8.2.0_3.catalina.bottle.tar.gz --header X-Checksum-Sha2:\ 17573d65b40db37b8354c9ac75b59df89f91630fe89d154c487d50f8b841fb7d --user brewtestbot:****** https://api.bintray.com/content/homebrew/bottles/gnuradio/3.8.2.0_3/gnuradio-3.8.2.0_3.catalina.bottle.tar.gz` exited with 26. Here's the output:
curl: Can't open 'gnuradio--3.8.2.0_3.catalina.bottle.tar.gz'!
curl: try 'curl --help' or 'curl --manual' for more information
```

I have no idea why this happens…

**Comment by jonchang** [comment]
GitHub Actions is having an outage.

**Comment by jonchang** [comment]
Couldn't figure out how to fix it in time so just did a manual merge overnight. 🥳

**Comment by fxcoudert** [comment]
Many thanks @jonchang !

**Pull request closed without merging**
