### PR TITLE
geckodriver: patch stable and add HEAD support

### PR DESCRIPTION
**Pull request by alyssais**
I needed to build HEAD because stable is broken with current Rust.

https://bugzilla.mozilla.org/show_bug.cgi?id=1441204

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by ilovezfs** [comment]
Ouch. Can the fix be backported?

**Comment by alyssais** [comment]
It _can_ be, but it’s not a small patch: https://gist.github.com/alyssais/572264b2820ac5572de5412e437f44af

(it also doesn’t apply cleanly and I had to manually resolve a good few conflicts)

**Comment by alyssais** [comment]
If we think it’s worth carrying that patch I’ll prepare the formula-patches PR.

**Comment by ilovezfs** [comment]
This is a pretty popular package so it is worth carrying the patch so that it can build from source but it would be good to request a new release as well.

**Comment by alyssais** [comment]
> would be good to request a new release as well.

Looks like that work is already in progress, but I've said we're looking forward to it: https://bugzilla.mozilla.org/show_bug.cgi?id=1441204#c1

**Comment by ilovezfs** [comment]
The merged patch url is
```
https://raw.githubusercontent.com/Homebrew/formula-patches/e89f1ad/geckodriver/bug-1435830.patch
```

Also, there should be a comment above the patch with
1. for which version the patch can be removed (e.g. `Remove for > 0.19.1`)
2. what build failure the patch fixes
3. the date of the corresponding upstream commit
4. a link to the upstream commit

**Comment by ilovezfs** [comment]
@alyssais any news here?

**Comment by ilovezfs** [comment]
Thanks @alyssais! Shipped.

**Pull request closed without merging**
