### PR TITLE
gdal 3.1.4

### PR DESCRIPTION
**Pull request by mjsteinbaugh**
Update GDAL from 3.1.3 to 3.1.4.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`brew install --build-from-source gdal` is returning this error:

```
❯ brew install --build-from-source gdal
==> Downloading https://download.osgeo.org/gdal/3.1.4/gdal-3.1.4.tar.xz
Already downloaded: /Users/mike/Library/Caches/Homebrew/downloads/22a59c91c3224ea68a1ab3b28b3731734c7062e38e7dd4993765a1c8413ad5cb--gdal-3.1.4.tar.xz
==> ./configure --prefix=/usr/local/Cellar/gdal/3.1.4 --mandir=/usr/local/Cellar/gdal/3.1.
==> make
==> make install
==> /usr/local/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --
Last 15 lines from /Users/mike/Library/Logs/Homebrew/gdal/04.python3:
--prefix=/usr/local/Cellar/gdal/3.1.4
--install-scripts=/usr/local/Cellar/gdal/3.1.4/bin
--single-version-externally-managed
--record=installed.txt

init_dgelsd failed init
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "setup.py", line 84, in <module>
    import numpy
  File "/usr/local/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned


READ THIS: https://docs.brew.sh/Troubleshooting
```

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
Looks like there's a fun NumPy issue popping up with Python 3.9.

This related issue looks relevant https://github.com/numpy/numpy/issues/15947

**Comment by fxcoudert** [comment]
Homebrew's `numpy` is linked against `openblas` so this should not happen.

**Comment by mjsteinbaugh** [comment]
@fxcoudert Argh yeah there's an issue with my Python config. I'll fix and retest. Thanks!

**Comment by mjsteinbaugh** [comment]
OK this works:

```sh
sudo rm -fr /usr/local/lib/python3.9/site-packages
brew reinstall python@3.9
brew reinstall numpy

brew install --build-from-source gdal
```

Should be safe to update.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
