### PR TITLE
Don't run CI on forks

### PR DESCRIPTION
**Pull request by dtrodrigues**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dtrodrigues** [comment]
Resolves https://github.com/Homebrew/homebrew-core/issues/55954

**Comment by MikeMcQuaid** [comment]
@Homebrew/linux thoughts on this? Is this also something we should do in the Docker images?

**Comment by dtrodrigues** [comment]
When pushing to a fork of linuxbrew-core, it only runs `brew style` on `homebrew/core` and not on the user repository: https://github.com/dtrodrigues/linuxbrew-core/runs/754534620?check_suite_focus=true , so this issue is avoided. The `sudo chmod -R g-w,o-w "$HOMEBREW_CORE_REPOSITORY"` there ensures the permissions are appropriate and since another repository is not tapped, `brew style` passes.

**Comment by sjackman** [comment]
Which ACL policies are set? What's the output of `getfacl $(brew --prefix)`? Is GitHub Actions setting funky ACL by default?

**Comment by dtrodrigues** [comment]
The acl policies are below. I `touch`ed a file in the  `brew --prefix` before clearing the ACL and even though the umask is `0022`, the file ended up with `666` permissions due to the ACL. I think Github Actions has the ACL set by default for certain directories.

```
getfacl $(brew --prefix)
touch $(brew --prefix)/testfile
ls -l $(brew --prefix)/testfile
....
sudo setfacl -b -R  $HOMEBREW_PREFIX
touch $(brew --prefix)/testfile2
ls -l $(brew --prefix)/testfile2


# file: home/linuxbrew/.linuxbrew
# owner: runneradmin
# group: runneradmin
user::rwx
group::rwx
other::rwx
default:user::rwx
default:user:runner:rwx
default:group::rwx
default:mask::rwx
default:other::rwx

-rw-rw-rw-+ 1 runner docker 0 Jun  9 22:01 /home/linuxbrew/.linuxbrew/testfile
-rw-r--r-- 1 runner docker 0 Jun  9 22:01 /home/linuxbrew/.linuxbrew/testfile2
```

**Comment by sjackman** [comment]
In a fork `dtrodrigues/homebrew-core`, the CI is tapping `dtrodrigues/core`, and I'm not really sure it should be doing that. Given that no other tap including my third party tap `brewsci/bio` is facing any issue with ACL, I can't help but think the root issue lies elsewhere.

**Comment by dtrodrigues** [comment]
The `brewsci/bio` tap doesn't include the offending https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/tests.yml in its GitHub actions (https://github.com/brewsci/homebrew-bio/tree/develop/.github/workflows).  This is also affecting https://github.com/issyl0/homebrew-core (https://github.com/issyl0/homebrew-core/runs/660849542?check_suite_focus=true).

**Comment by dtrodrigues** [comment]
Based on https://github.com/Homebrew/homebrew-test-bot/blob/1810d9720395e6134033978cc55c5ba163bd8e9c/lib/test_bot.rb#L33 , it seems like we're trying to running check on the current tap vs homebrew-core. Based on https://github.com/Homebrew/homebrew-test-bot/pull/353 , the `brew style` call was changed to run on the current tap. @MikeMcQuaid - can you confirm if the intention of this GitHub action is to test the syntax of the formulae in the current tap?

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid - can you confirm if the intention of this GitHub action is to test the syntax of the formulae in the current tap?

The intention is to check homebrew-core. It's not been made intentionally to work on forks so I have no idea if it does correctly or not. Not sure if that answers your question? Sorry if not!

**Comment by dtrodrigues** [comment]
Can the current PR, which will allow non-core forks to work with CI, be accepted (preferred option) or can a change be made to include `if: github.repository == 'Homebrew/homebrew-core'` before the tests to prevent CI from running on forks? With the current behavior, anybody forking the repository will have failed CI runs which is undesirable.

**Comment by MikeMcQuaid** [comment]
> can a change be made to include `if: github.repository == 'Homebrew/homebrew-core'` before the tests to prevent CI from running on forks?

Fine with me 👍

**Comment by dtrodrigues** [comment]
I've force-pushed a change to only run CI on `Homebrew/homebrew-core`.

**Comment by MikeMcQuaid** [comment]
Merged. Thanks again @dtrodrigues!

**Pull request merged**
