### PR TITLE
fastgron 0.4.8 (new formula)

### PR DESCRIPTION
**Pull request by adamritter**
Update fastgron.rb

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [-] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

```
$ brew audit --new fastgron
fastgron
  * GitHub repository too new (<30 days old)
```

### CODE REVIEW

**Comment by adamritter** [comment]
I see that there's a 30 day minimum wait period, so I guess I need to wait :)

**Comment by chenrui333** [comment]
> I see that there's a 30 day minimum wait period, so I guess I need to wait :)

yeah, that is what I just saw as well 😅

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@adamritter I have dropped you a PR to patch the version report issue, https://github.com/adamritter/fastgron/pull/3

**Comment by adamritter** [comment]
I released v0.4.8 with the version fix, sha256sum: ee028cbf47813f65f08c37a4746c88bd0e326928893815d98c08720e2e3980b1

**Comment by p-linnane** [comment]
@chenrui333 Why are we skipping the 30 day audit?

**Comment by chenrui333** [comment]
> @chenrui333 Why are we skipping the 30 day audit?

Honestly, I can go either way, I actually also skipped the 30 day audit with [rye](https://github.com/Homebrew/homebrew-core/pull/131401) as well.

**Comment by chenrui333** [comment]
I will put this into feedback phase then :)

**Comment by p-linnane** [comment]
I was just wondering if there was a certain reason, but I think it's fine too.

**Review by p-linnane — APPROVED** [review]

**Comment by chenrui333** [comment]
> I was just wondering if there was a certain reason, but I think it's fine too.

we are aligned, I think this is a good tool :)

**Pull request merged**
