### PR TITLE
pyqt: migrate to `python@3.13`, vtk 9.4.0

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Closes #198907

### CODE REVIEW

**Comment by cho-m** [comment]
Blocked by F3D. https://github.com/f3d-app/f3d/commit/d9fa161e99817028a16b9db371c0369d44b8022e doesn't apply and would be tricky to backport

**Comment by cho-m** [comment]
Going to work on getting Boost PR merged first

**Comment by cho-m** [comment]
`visp` failure. Not sure yet if issue is in `visp` or `pcl`.
```
  cd /tmp/visp-20241212-86864-ggjtsi/visp-3.6.0/modules/me && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -Dvisp_EXPORTS -I/tmp/visp-20241212-86864-ggjtsi/visp-3.6.0/include -I/opt/homebrew/opt/eigen/include/eigen3 -I/tmp/visp-20241212-86864-ggjtsi/visp-3.6.0/modules/tracker/me/include -I/tmp/visp-20241212-86864-ggjtsi/visp-3.6.0/modules/tracker/me/src -I/tmp/visp-20241212-86864-ggjtsi/visp-3.6.0/modules/me -I/tmp/visp-20241212-86864-ggjtsi/visp-3.6.0/modules/core/include -I/tmp/visp-20241212-86864-ggjtsi/visp-3.6.0/3rdparty/catch2 -I/opt/homebrew/Cellar/opencv/4.10.0_16/include/opencv4 -Wall -Wextra -Xclang -fopenmp -std=c++17 -fvisibility=hidden -fPIC -O3 -DNDEBUG -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -fPIC -MD -MT modules/me/CMakeFiles/visp_me.dir/src/moving-edges/vpMeTracker.cpp.o -MF CMakeFiles/visp_me.dir/src/moving-edges/vpMeTracker.cpp.o.d -o CMakeFiles/visp_me.dir/src/moving-edges/vpMeTracker.cpp.o -c /tmp/visp-20241212-86864-ggjtsi/visp-3.6.0/modules/tracker/me/src/moving-edges/vpMeTracker.cpp
  In file included from /tmp/visp-20241212-86864-ggjtsi/visp-3.6.0/modules/gui/src/pointcloud/vpPclViewer.cpp:43:
  In file included from /tmp/visp-20241212-86864-ggjtsi/visp-3.6.0/modules/gui/include/visp3/gui/vpPclViewer.h:49:
  In file included from /opt/homebrew/include/pcl-1.14/pcl/visualization/pcl_visualizer.h:48:
  In file included from /opt/homebrew/include/pcl-1.14/pcl/visualization/common/actor_map.h:40:
  /opt/homebrew/include/pcl-1.14/pcl/visualization/point_cloud_geometry_handlers.h:49:10: fatal error: 'vtkSmartPointer.h' file not found
     49 | #include <vtkSmartPointer.h>
        |          ^~~~~~~~~~~~~~~~~~~
  1 error generated.
  make[2]: *** [modules/gui/CMakeFiles/visp_gui.dir/src/pointcloud/vpPclViewer.cpp.o] Error 1
  make[1]: *** [modules/gui/CMakeFiles/visp_gui.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
```

**Comment by cho-m** [comment]
Need to rebase for another `opencv` revision bump.

Will do so after current run finishes to populate cache.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
