### PR TITLE
openkim-models 2024-02-20

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
notified the upstream about the CMakeLists.txt issue via https://openkim.org/contact

**Comment by ilia-nikiforov-umn** [comment]
> notified the upstream about the CMakeLists.txt issue via https://openkim.org/contact

Hi Rui,

The file was generated in error. We are not providing an `openkim-models` package at this time and are instead instructing users to install individual models, sorry! The PR can be closed.

**Comment by chenrui333** [comment]
> We are not providing an `openkim-models` package at this time and are instead instructing users to install individual models

@ilia-nikiforov-umn thanks for chiming in here, should we deprecate this openkim-models package instead (as the installation has changed)

**Comment by ellio167** [comment]
I'd say it's simplest to leave it as is for now.

Some work on our backend infrastructure resulted in the accidental creation of the new archive which lead to the creation of this PR.  The previously available version is still the official current version of this package.  So, I don't think there is any particular clear reason to deprecate it.

**Comment by cho-m** [comment]
Closing based on above discussion.

Tarball has been removed and livecheck is back to showing correct version:
```console
❯ brew livecheck openkim-models
openkim-models: 2021-08-11 ==> 2021-08-11
```

**Pull request closed without merging**
