### PR TITLE
lgtm 0.3.0 (new formula)

### PR DESCRIPTION
**Pull request by gozeloglu**
Signed-off-by: Gökhan Özeloğlu <gozeloglu@gmail.com>

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by chenrui333 — CHANGES_REQUESTED** [review]
please refer to the [CONTRIBUTING](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#to-add-a-new-formula-for-foo-version-234-from-url) about how to add a new formula.

**Comment by gozeloglu** [comment]
Hi @chenrui333. I've followed the steps but I got the following error in the second step.

```bash
$ brew install --build-from-source lgtm
==> Downloading https://github.com/gozeloglu/lgtm
##O=#  #                                                                      
Error: lgtm: SHA256 mismatch
Expected: 34542797b1e30695601fef0f530d4ef208d36985e323615c6c501a844a917932
  Actual: add2961c52977b5c4d14137dd0e94319184764fb26f31467414e8b12ebd74d61
    File: /Users/gokhan.ozeloglu/Library/Caches/Homebrew/downloads/78bbd716807e3b4ca64bbff8f70384a0e65e7a7a785d00cacfb5c31301e372d1--lgtm
To retry an incomplete download, remove the file above.
```

I removed the `/Users/gokhan.ozeloglu/Library/Caches/Homebrew/downloads/78bbd716807e3b4ca64bbff8f70384a0e65e7a7a785d00cacfb5c31301e372d1--lgtm` file but it didn't work. Am I missing something?

**Comment by SMillerDev** [comment]
> Am I missing something?

What is the hash of the file if you download it normally?

**Comment by gozeloglu** [comment]
I checked with the below command.

```
$ shasum -a 256 lgtm-mac.tar.gz
34542797b1e30695601fef0f530d4ef208d36985e323615c6c501a844a917932  lgtm-mac.tar.gz
```

**Comment by SMillerDev** [comment]
Then the tar you have is not the same one brew is downloading.

**Comment by gozeloglu** [comment]
Actually, I downloaded the tar from repository release and then run the above command.

**Pull request closed without merging**
