### PR TITLE
afl-fuzz 2.22b

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by alex** [comment]
Test failure appear to be because jenkins is broken?

**Comment by DomT4** [comment]
Either you or someone before you force pushed their PR, I'd guess. It can upset Jenkins if a build has already begun.

**Comment by alex** [comment]
👍 , I did not rebase.

**Comment by DomT4** [comment]
Probably another build that was in progress at the same time as this one then. It's a known issue upstream but doesn't seem to be any haste fixing it, so happens sometimes. Went green this build.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/98ac9baf967e1f127c739314cf41ebe9b71da987. Thank you @alex 🙇.

**Pull request closed without merging**
