### PR TITLE
opencv 4.9.0

### PR DESCRIPTION
**Pull request by timsutton**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.
<details>
  <summary>release notes</summary>
  <pre>OpenCV 4.9.0 has been released.

:hammer_and_wrench: Change log is [here](https://github.com/opencv/opencv/wiki/ChangeLog#version490).

```
d181481fdabf6c02b1b45a3b382a583c531bb4d6b0582d0fbbb686487f071218  opencv-4.9.0-android-sdk.zip
0fce577941eea0db27d2c37b7c46785db23de6520b725b8f0dca7c46b368b18c  opencv-4.9.0-ios-framework.zip
fefddff0623fbd5a6fa0cecb9bccd4b822478354e6c587ebb6e40ab09dacba51  opencv-4.9.0-windows.exe
1e71ceb6220c94bd917ee48b29284e43883e066a3c7129e27f5c2a4ffbab8275  opencv-4.9.0-docs.zip
```</pre>
</details>

### CODE REVIEW

**Comment by timsutton** [comment]
mxnet failing to fetch due to different sha from www.apache.org:
```
  ==> Fetching mxnet
  ==> Downloading https://www.apache.org/dyn/closer.lua?path=mxnet/1.9.1/apache-mxnet-src-1.9.1-incubating.tar.gz
  Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/bbc2b23eecad518920e42bb966a7e2f1ebead9c9266b4032a5e3dad22ad83e88--mxnet.html
  ==> Verifying checksum for 'bbc2b23eecad518920e42bb966a7e2f1ebead9c9266b4032a5e3dad22ad83e88--mxnet.html'
  Error: mxnet: SHA256 mismatch
  Expected: 11ea61328174d8c29b96f341977e03deb0bf4b0c37ace658f93e38d9eb8c9322
    Actual: e72608a2ea6b8757278c1f75ef69f3b80429c49e8e1b45afec27ac37c4f35335
      File: /Users/brew/Library/Caches/Homebrew/downloads/bbc2b23eecad518920e42bb966a7e2f1ebead9c9266b4032a5e3dad22ad83e88--mxnet.html
  To retry an incomplete download, remove the file above.
```

**Comment by chenrui333** [comment]
caffe commit should be dropped as well (that is already disabled)

**Comment by timsutton** [comment]
Would love a hand with re-kicking CI on this one, seeing:
```
Error: PR requires the CI-long-timeout label but it is not set!
Error: If the longer timeout is not required, remove the "long build" label.
Error: Otherwise, add the "CI-long-timeout" label.
Error: No more than 2 PRs at a time may use "CI-long-timeout".
```

**Comment by chenrui333** [comment]
mxnet commit can be also dropped as it is already deprecated.

**Comment by chenrui333** [comment]
looks like visp build failure is the real deal

**Comment by timsutton** [comment]
Agreed, I will make a point to file an issue upstream on `visp`

**Comment by timsutton** [comment]
@p-linnane Would you be able to re-add the `CI-long-timeout` label so we can run this one again?

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
