### PR TITLE
pfetch-rs 2.2.0 (new formula)

### PR DESCRIPTION
**Pull request by 21st-centuryman**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by 21st-centuryman** [comment]
I realized I am 3 days too early with this. is it ok to wait in the meantime or should I do a new PR in 3 days?

**Comment by chenrui333** [comment]
yeah, we can totally wait a bit.

**Comment by 21st-centuryman** [comment]
Do you guys need more on my end? I saw that the tests passed.

**Comment by SMillerDev** [comment]
Please don't add merge commits. Our CI can't run with those.

**Comment by 21st-centuryman** [comment]
oh alright i was unaware. Do you want me to create another pull request?

**Comment by SMillerDev** [comment]
You can just rebase and drop the merge commit.

**Comment by SMillerDev** [comment]
That just added a lot of commits so I rebased it again

**Review by MikeMcQuaid — DISMISSED** [review]

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@21st-centuryman, thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by 21st-centuryman** [comment]
@chenrui333 thank you for your help and kind words. Love the work you guys put in on Homebrew.

**Pull request closed without merging**
