### PR TITLE
mingw-w64 8.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> Testing mingw-w64
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201003-58806-12zbauj.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mingw-w64.rb --verbose
==> /usr/local/Cellar/mingw-w64/8.0.0/bin/i686-w64-mingw32-gcc -o test.exe hello.c
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /usr/local/Cellar/mingw-w64/8.0.0/bin/i686-w64-mingw32-gcc
  Reason: image not found
Error: mingw-w64: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/mingw-w64/8.0.0/bin/i686-w64-mingw32-gcc -o test.exe hello.c
```

**Comment by fxcoudert** [comment]
Updated GCC and binutils to the latest. We'll see if this is fixed:

```
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      toolchain-i686/libexec/gcc/i686-w64-mingw32/9.3.0/install-tools/fixincl
      toolchain-x86_64/libexec/gcc/x86_64-w64-mingw32/9.3.0/install-tools/fixincl
```

This is not an issue in practice, since `fixincl` is not supposed to be run by users (it's for GCC developers).

**Comment by fxcoudert** [comment]
Passing `--disable-nls` to avoid opportunistically linking to `libintl`, which happens on 10.13 because `texinfo` depends on `gettext` on that macOS version.

**Comment by fxcoudert** [comment]
Also passing `--disable-nls` to binutils

**Comment by fxcoudert** [comment]
Tests are stuck 😮

**Comment by fxcoudert** [comment]
The 10.15 CI was stuck in `brew bottle --verbose --json mingw-w64`.

**Comment by fxcoudert** [comment]
```
mingw-w64:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      toolchain-i686/libexec/gcc/i686-w64-mingw32/10.2.0/install-tools/fixincl
      toolchain-x86_64/libexec/gcc/x86_64-w64-mingw32/10.2.0/install-tools/fixincl
```

This is not a problem, since `fixincl` is not supposed to be run by end users.

**Pull request closed without merging**
