### PR TITLE
linkerd 2.6.0

### PR DESCRIPTION
**Pull request by jeffreyfriedman**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Thanks @jeffreyfriedman !!

**Comment by jeffreyfriedman** [comment]
@chenrui333 My pleasure!  Thanks for all of your hard work!

**Comment by jeffreyfriedman** [comment]
Build broke due to a versioning issue with a Linkerd dependency, I opened a bug report: https://github.com/linkerd/linkerd2/issues/3566

**Comment by chenrui333** [comment]
@jeffreyfriedman I think `go@1.12` would solve this upgrade issue. :)

**Comment by chenrui333** [comment]
The upstream repo does need to support go@1.13 on its own though.

**Comment by chenrui333** [comment]
The build looks good, merging the PR now.

**Pull request closed without merging**
