### PR TITLE
unbound 1.5.10

### PR DESCRIPTION
**Pull request by Habbie**
created with `brew bump-formula-pr`

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/45864a7b7ea747c98479c31214fd3bd6c465dd90. Thank you for another contribution to Homebrew @Habbie! 😺

**Comment by Habbie** [comment]
@DomT4 

```
==> Downloading https://homebrew.bintray.com/bottles/unbound-1.5.10.yosemite.bottle.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 0b641ab092cbd5aa02b33054f6f3fa27c76787bd17d7c4f1cd9dc7d798725a60
Actual: f873d5c0fac865009e8e49cd216ff0920c398327718cf47a1c667ae46f2cdb12
```

**Comment by Habbie** [comment]
There's no commit from BrewTestBot updating the bottles.

**Comment by Habbie** [comment]
False alarm - `bump-formula-pr` left `Homebrew/Library/Taps/homebrew/homebrew-core` in a bad state.

**Comment by Habbie** [comment]
(and `brew update` did not notice)

**Comment by MikeMcQuaid** [comment]
@Habbie It did notice but assumes you would rather handle those Git repositories yourself rather than us e.g. overwriting your work.

**Comment by Habbie** [comment]
@MikeMcQuaid right, but it does so silently it appears :)

**Pull request closed without merging**
