### PR TITLE
tkdiff 5.5.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> /opt/homebrew/Cellar/tkdiff/5.5.3/bin/tkdiff --help
  macOS 11 (1107) or later required, have instead 11 (1106) !
  /usr/bin/wish: line 2: 18183 Abort trap: 6           "$(dirname $0)/../../System/Library/Frameworks/Tk.framework/Versions/8.5/Resources/Wish.app/Contents/MacOS/Wish" "$@"
```

**Comment by chenrui333** [comment]
needs macOS 11+

**Comment by chenrui333** [comment]
Give it another run and see where we are.

**Comment by iMichka** [comment]
On 11-arm64: `macOS 11 (1107) or later required, have instead 11 (1106)`

**Pull request closed without merging**
