### PR TITLE
mx 5.292.5 (new formula)

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Baby steps towards GraalVM as a formula

### CODE REVIEW

**Comment by carlocab** [comment]
```
==> /opt/homebrew/Cellar/mx/5.292.5/bin/mx suites
unknown or unsupported architecture: os=darwin, machine=arm64
```

**Comment by SMillerDev** [comment]
I guess I'll have to pick a different project to test with

**Comment by SMillerDev** [comment]
It doesn't work with ARM on macOS apparently so I marked it as `depends_on arch: :x86_64`

**Comment by carlocab** [comment]
> It doesn't work with ARM on macOS apparently so I marked it as `depends_on arch: :x86_64`

Not a promising start for for GraalVM 😅

**Review by carlocab — APPROVED** [review]

**Comment by SMillerDev** [comment]
> Not a promising start for for GraalVM 😅

It's the future (of 2010)!

**Comment by carlocab** [comment]
Looks like this needs a `livecheck` blog:
```
❯ brew livecheck mx
mx : 5.292.5 ==> 8.8
```
This is a bit beyond my understanding of `livecheck`. @samford, if you've got the time to take a look.

**Pull request closed without merging**
