### PR TITLE
pgloader 3.5.2

### PR DESCRIPTION
**Pull request by eMerzh**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
the resource blocks will need to be updated too

**Comment by eMerzh** [comment]
aouch :( 
i've not lisp and not really sure how to use quicklisp-homebrew-roundup
but pgloader 3.5.1 is broken for me :(

**Comment by ilovezfs** [comment]
@eMerzh no worries. I'll take a look at doing it.

**Review by ilovezfs — APPROVED** [review]

**Comment by eMerzh** [comment]
many thanks for the help! ❤️

**Comment by ilovezfs** [comment]
You're welcome!

Thanks so much for your first contribution! Without people like you submitting PRs we couldn't run this project. You rock, @eMerzh!

**Pull request closed without merging**
