### PR TITLE
brook 20230401

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>## Documentation

https://txthinking.github.io/brook/

## CLI
- --log
- --tag
- --dialWithIP4
- --dialWithIP6
- --dialWithSocks5
- brook tproxy:
    - better and better on dual-stack network
    - --disableA
    - --disableAAAA
    - --bypassGeoIP
    - --redirectDNS
    - bugfix
    - cookbook: [Turn any Linux into a router with two Brook commands](https://www.txthinking.com/talks/articles/brook-linux-router-en.article)
    - cookbook: [使用 Brook 两条命令把任意 Linux 变成路由器](https://www.txthinking.com/talks/articles/brook-linux-router.article)
- brook quicserver
- brook quicclient
- brook dhcpserver
    - cookbook: [Turn any Linux into a router with two Brook commands](https://www.txthinking.com/talks/articles/brook-linux-router-en.article)
    - cookbook: [使用 Brook 两条命令把任意 Linux 变成路由器](https://www.txthinking.com/talks/articles/brook-linux-router.article)

## GUI

- OpenWRT:
    - better and better on dual-stack network
    - Rewrite UI, similar to other GUI clients
    - bugfix
    - cookbook: [Brook OpenWRT Router](https://www.txthinking.com/talks/articles/brook-openwrt-en.article)
    - cookbook: [Brook OpenWRT 路由器](https://www.txthinking.com/talks/articles/brook-openwrt.article)
- iOS / M1 Mac
    - Dark Mode
    - Shortcut
- Android
    - Dark Mode
    - Shortcut
- Linux
    - Dark Mode
    - Shortcut
- Intel Mac
    - Dark Mode
    - Shortcut
- Windows
    - Dark Mode
    - Shortcut
    - System Tray

</pre>
</details>

### CODE REVIEW

**Comment by chenrui333** [comment]
- relates to [brook link: remove redundant fields if not specified](https://github.com/txthinking/brook/commit/133d78bde32328374e5eda6740e90827d4645763)

**Review by carlocab — DISMISSED** [review]

**Comment by carlocab** [comment]
Testing the changes to the publish workflow here.

**Comment by carlocab** [comment]
Ah, I forgot about this. `brew pr-pull` expects a branch that doesn't contain the commits that update the formula:
```
==> Using 2 commits from #126083
Error: Failure while executing; `/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/shared/git -C /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core cherry-pick --ff --allow-empty 3dfa3c56e85fc8c07b9861e102f5b19a9cc0838e 8e086c7908913a1999a6627e22f5bb6b6bbd805c` exited with 0. Here's the output:
Auto-merging Formula/brook.rb
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty
```
https://github.com/Homebrew/homebrew-core/actions/runs/4461335852/jobs/7835095294#step:10:40

CC @MikeMcQuaid

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Homebrew/brew#15011

**Pull request closed without merging**
