### PR TITLE
heroku 7.0.30

### PR DESCRIPTION
**Pull request by epistrephein**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
I think we should consider throttling the releases to multiples of 10.

**Comment by epistrephein** [comment]
Yeah, really doesn't make sense trying to keep the pace with 6 releases a day.

**Comment by ilovezfs** [comment]
@epistrephein OK let's roll it back to 7.0.30 and add a comment like the one in aws-cli.
https://github.com/Homebrew/homebrew-core/blob/9f1a4e9982dc0cb74c31b44c4a54fe18b8e5dcaa/Formula/awscli.rb#L6

**Comment by ilovezfs** [comment]
Thanks again @epistrephein!

**Pull request closed without merging**
