### PR TITLE
pdal 1.3.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
😱 
```
/tmp/pdal-20160901-68066-1cxr8dp/PDAL-1.3.0/vendor/arbiter/arbiter.cpp:1361:25: error: return type 'basic_string<[3 * ...]>' must match previous return type 'const basic_string<[3 * ...]>' when lambda expression has unspecified explicit return type
                        return out + c;
                        ^

**Comment by ilovezfs** [comment]
probably deserves a `depends_on :macos => :yosemite` just for being ridiculous

**Comment by ilovezfs** [comment]
@dunn reported upstream https://github.com/PDAL/PDAL/issues/1300

**Comment by ilovezfs** [comment]
https://github.com/connormanning/arbiter/issues/7
https://github.com/PDAL/PDAL/issues/1300#issuecomment-244606540

**Comment by ilovezfs** [comment]
https://github.com/connormanning/arbiter/commit/6442564680212eb45fc5620f65d6ce32b42536c7

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
