### PR TITLE
qt: revision bump (icu4c 73.2)

### PR DESCRIPTION
**Pull request by carlocab**
See #133611.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by carlocab** [comment]
Ah, no wonder the build went suspiciously quickly. Some frameworks were not built: QtPdf, QtPdfWidgets, and QtWebEngine. Not sure what happened there. Mind having a look, @paperchalice?

**Comment by carlocab** [comment]
Ah, no, I see. `node` wasn't working on this branch, which is why some components were not built. Needs rebase.

**Comment by carlocab** [comment]
Is `av_stream_get_first_dts` in upstream FFmpeg?

**Comment by carlocab** [comment]
Ah, right. That's the function that FFmpeg made private. What are other package managers doing about FFmpeg and Qt6? How big is the patch required to expose the function only to QtWebEngine?

**Comment by carlocab** [comment]
Hmm, ok. Let me think about applying that patch.

By the way: can you think of an update to the `test` that checks that QtWebEngine was built? It seems inconvenient to wait for dependents to get tested before finding out that QtWebEngine went missing.

**Pull request merged**
