### PR TITLE
opencascade 7.7.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
Linux `opencascade` build failure:
```
/tmp/opencascade-20221113-19908-1gmwbky/occt-V7_7_0/src/ViewerTest/ViewerTest_CmdParser.cxx:53:80: error: ‘numeric_limits’ is not a member of ‘std’
     53 | const std::size_t ViewerTest_CmdParser::THE_UNNAMED_COMMAND_OPTION_KEY = (std::numeric_limits<std::size_t>::max)();
        |                                                                                ^~~~~~~~~~~~~~
```

**Comment by mistydemeo** [comment]
`std::numeric_limits` is defined by `<limits.h>`: https://en.cppreference.com/w/cpp/types/numeric_limits

Guessing it's pulled in transitively in some envionments but not others.

**Comment by cho-m** [comment]
Some related upstream issues:
https://tracker.dev.opencascade.org/view.php?id=33157
https://tracker.dev.opencascade.org/view.php?id=33200

The patch in one of them has unnecessary changes.

GitHub mirror has some simpler patches (https://github.com/Open-Cascade-SAS/OCCT/pulls) but those will get auto-closed since OpenCascade doesn't use GitHub for issues/patches.

**Comment by SMillerDev** [comment]
Could you suggest one of those pull requests as a patch upstream?

**Comment by chenrui333** [comment]
Thanks @ZhongRuoyu!! 🚀

**Review by p-linnane — APPROVED** [review]

**Pull request closed without merging**
