### PR TITLE
libdrm 2.4.103

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
/usr/bin/ld: cannot find -liconv
unix.o: In function `set_symlnk_attribs':
unix.c:(.text+0x187c): warning: lchmod is not implemented and will always fail
collect2: error: ld returned 1 exit status
Makefile:283: recipe for target 'unzip' failed
make[1]: *** [unzip] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/unzip-20201105-17846-16czrhz/unzip60'
unix/Makefile:875: recipe for target 'macosx' failed
make: *** [macosx] Error 2
```

**Comment by SeekingMeaning** [comment]
`-liconv` flag shouldn't be used on Linux when building `unzip`:

https://github.com/Homebrew/linuxbrew-core/blob/09fd76a/Formula/unzip.rb#L67

**Comment by iMichka** [comment]
Yes, that was me merging it despite the error. I was not really expecting people to upgrade linux-only formulae here before completing the merging of both repositories. Especially as no bottles are built; and not reverse dependencies are tested. So we may introduce breakages in linuxbrew-core, which is far from ideal.

We are in a transition period so not everything will go as smoothly as expected I guess :) 

I added https://github.com/Homebrew/brew/pull/8907 to brew, which will allow to backport to the linux change to the unzip formula.

We need to wait for a brew release, update the unzip formula, and then we can proceed here.

**Comment by MikeMcQuaid** [comment]
> We are in a transition period so not everything will go as smoothly as expected I guess :)

How long do you expect this period to be/take? I'm not sure about us preventing maintainers from bumping here indefinitely?

**Comment by iMichka** [comment]
I updated unzip to build on linux here #64514. 

Please rebase, this should build now.

**Comment by chenrui333** [comment]
@iMichka looks like the linux build is still failing.

**Comment by iMichka** [comment]
Can you rebase again? This needed a working openssl@1.1, and we fixed that build for linux not so long ago.

**Comment by SeekingMeaning** [comment]
Requires python linux changes https://github.com/Homebrew/homebrew-core/pull/66168

**Comment by SeekingMeaning** [comment]
Same error after re-queue:

```
curl: (7) Failed to connect to www.linuxfromscratch.org port 80: Connection timed out
Error: Failed to download resource "docbook-xsl--patch"
Download failed: http://www.linuxfromscratch.org/patches/blfs/9.1/docbook-xsl-nons-1.79.2-stack_fix-1.patch
```

**Comment by carlocab** [comment]
I think that’s what the following PR is for:

https://github.com/Homebrew/formula-patches/pull/331

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
