### PR TITLE
top-post 0.0.9 (new formula)

### PR DESCRIPTION
**Pull request by daschaa**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by daschaa** [comment]
Duplicate of [#98647](https://github.com/Homebrew/homebrew-core/pull/98647) - Reopened this to fulfill the commit style guide (own branch).

**Comment by daschaa** [comment]
@SMillerDev
`* GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)`

The checks fail because of the constraint, that the github repository has less than 30 stars. I thought this constraint is only for casks, isn't it?

**Comment by SMillerDev** [comment]
> The checks fail because of the constraint, that the github repository has less than 30 stars. I thought this constraint is only for casks, isn't it?

No, it's for all Homebrew software.

**Comment by daschaa** [comment]
> > The checks fail because of the constraint, that the github repository has less than 30 stars. I thought this constraint is only for casks, isn't it?
> 
> No, it's for all Homebrew software.

Ok then I will close this PR. Thanks for reviewing.

**Pull request closed without merging**
