### PR TITLE
gpgme: migrate to python@3.10

### PR DESCRIPTION
**Pull request by XuehaiPan**
Migrate formula `gpgme` to `python@3.10`.

### CODE REVIEW

**Comment by carlocab** [comment]
I think this will break `alot`, which does actually make use of the Python bindings provided here: https://alot.readthedocs.io/en/latest/installation.html

**Comment by carlocab** [comment]
Anyway, the Python bindings aren't being built because this only checks for:
- `python2.7` (found, but the Framework is poisoned so third-party apps cannot link to it)
- `python3.4`
- `python3.5`
- `python3.6`
- `python3.7`
- `python3.8`
- `python3.9`
- `pythonall`

Not sure why it doesn't check for `python` or `python3`, but there you go.

**Comment by carlocab** [comment]
Here's the relevant snippet from `configure.ac`. This is not fixed on `master`.
```sh
	if test "$found_py" = "1" -o "$found_py3" = "1"; then
	  # Reset everything, so that we can look for another Python.
          m4_foreach([mym4pythonver],
                     [[2.7],[3.4],[3.5],[3.6],[3.7],[3.8],[3.9],[all]],
           [unset PYTHON
	    unset PYTHON_VERSION
	    unset PYTHON_CPPFLAGS
	    unset PYTHON_LDFLAGS
	    unset PYTHON_SITE_PKG
	    unset PYTHON_EXTRA_LIBS
	    unset PYTHON_EXTRA_LDFLAGS
	    unset ac_cv_path_PYTHON
	    unset am_cv_pathless_PYTHON
	    unset am_cv_python_version
	    unset am_cv_python_platform
	    unset am_cv_python_pythondir
	    unset am_cv_python_pyexecdir
	    AM_PATH_PYTHON(mym4pythonver, [
		AX_PYTHON_DEVEL
		if test "$PYTHON_VERSION"; then
			PYTHONS="$(echo $PYTHONS $PYTHON)"
			PYTHON_VERSIONS="$(echo $PYTHON_VERSIONS $PYTHON_VERSION)"
		fi
	    ], :, m4_if([mym4pythonver],[all],[],[python]mym4pythonver))
           ])
	fi
```

**Comment by cho-m** [comment]
Here is link to open PR to allow building with Python 3.10: https://dev.gnupg.org/D546

**Review by carlocab — COMMENTED** [review]
This will break `alot`, so (at least) that will need migrating too.

**Pull request closed without merging**
