### PR TITLE
libgetdata: option tweaks

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DomT4** [comment]
No idea what `Rubocop` is whinging about here:
```
libgetdata:
  * C: 42: col 5: Favor modifier `if` usage when having a single-line body. Another good alternative is the usage of control flow `&&`/`||`.
```

Seems fine to me as-is.

**Comment by ilovezfs** [comment]
```
       args << "--disable-fortran" << "--disable-fortran95" if build.with? "gcc"
```
is <= 80 columns so it wants that

**Comment by DomT4** [comment]
Ah, that makes sense. Rubocop sure does spit out some deeply unclear messages.

**Comment by ilovezfs** [comment]
Does it actually make sense to be setting `      --with-perl-dir=#{lib}/perl5/site_perl` if we're not building `--with-perl`?

**Comment by DomT4** [comment]
Depends how much effort it's making to find out where it should be installing things. If it goes looking and finds the answer `/Library/Perl/5.18`, which is _technically_ the right place with the system perl, then yeah it's necessary. I'll check.

**Comment by ilovezfs** [comment]
I'd probably just require everything (gcc, perl, xz).

**Comment by ilovezfs** [comment]
even libzzip too

**Comment by DomT4** [comment]
`gcc` is a pretty fat default dependency, but I guess there's an argument that it's popular.

**Comment by ilovezfs** [comment]
Very few installs here so I think this is fine.

**Comment by DomT4** [comment]
The install location is fairly "sane" only passing `--with-perl` as a `configure` flag when building against the system, so that could be scoped to only when using Homebrew's `perl` if desired. Installs at:
```
#{lib}/perl/#{system_perl_version}/GetData.pm
```

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ brew formula-analytics libgetdata
install events in the last 30 days for libgetdata
=====================================================================================================
1 | libgetdata                                                                         |  8 |  72.73%
2 | libgetdata --with-fortran                                                          |  2 |  18.18%
3 | libgetdata --with-fortran --with-xz --with-libzzip                                 |  1 |   9.09%
=====================================================================================================
Total                                                                                  | 11 |    100%
=====================================================================================================

install_on_request events
=====================================================================================================
1 | libgetdata                                                                          | 7 |  87.50%
2 | libgetdata --with-fortran --with-xz --with-libzzip                                  | 1 |  12.50%
=====================================================================================================
Total                                                                                   | 8 |    100%
=====================================================================================================

Error: No BuildError data found!
```
So I'd be surprised if this ever comes up one way or the other.

**Comment by DomT4** [comment]
Yeah. Those numbers aren't exactly massive.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/commit/44a899c9aa97374a269660b0cc120c9e53cc28f7

**Pull request merged**
