### PR TITLE
libuv 1.32.0

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
```
Run-time dependency libh2o found: NO (tried pkgconfig, cmake and framework)
Looking for a fallback subproject for the dependency libh2o

|Executing subproject libh2o method meson 
|
|Project name: libh2o
|Project version: 0.13.5
|C compiler for the build machine: clang (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
|C compiler for the host machine: clang (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
|Run-time dependency libuv found: YES 1.32.0
|Run-time dependency zlib found: YES 1.2.11

subprojects/libh2o/meson.build:141:2: ERROR: C library 'crypto' not found

A full log can be found at /private/tmp/urbit-20190911-74810-1idfa73/build/meson-logs/meson-log.txt
ninja: Entering directory `build'
ninja: error: loading 'build.ninja': No such file or directory
```

**Comment by igas** [comment]
@lembacon do you think you can help here? I'm lost :(

**Comment by fxcoudert** [comment]
The `meson` expert around these parts is @tschoonj 🥇

**Comment by tschoonj** [comment]
The meson script is explicitly looking for `libcrypto` in `/usr/local/opt/openssl/lib`, which won't work with `openssl@1.1`:

https://github.com/urbit/h2o/blob/0ed9ac70757a16ec45f91b8a347850d9699c3fb1/meson.build#L140-L149

By the way `urbit` is at [0.8.2](https://github.com/urbit/urbit/releases/tag/v0.8.2), so you may want to try updating it

**Comment by igas** [comment]
@tschoonj is it possible to use ENV or some param in meson, so we can ask upstream to add it?

**Comment by tschoonj** [comment]
What upstream should be doing in the meson script is use `pkg-config` to find the openssl compilation and linker flags on macOS as well, just as they do on other platforms.

I see no reason why `openssl_dep = dependency('openssl', version: '>=1.0.0')` wouldn't have worked with Homebrew

**Comment by fxcoudert** [comment]
Closing due to lack of progress.

**Pull request closed without merging**
