### PR TITLE
percona-xtrabackup 8.0.33-28

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [ ] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
This PR should be merged into #136966 (some bug got fixed per mysql upgrade)

**Comment by cho-m** [comment]
Looks like upstream bug introduced with logic changes to detect `procps` v3 vs v4 (https://github.com/percona/percona-xtrabackup/commit/6038a7934cbd4e6c01389fdc9b8ffabf8c3e006a). `FIND_PROCPS()` should not be run on macOS.

**Comment by altmannmarcelo** [comment]
Hi @chenrui333 .
Can you explain why this happened?

**Comment by chenrui333** [comment]
gonna close it for now

**Pull request closed without merging**
