### PR TITLE
biber 2.17

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
```
 ==> /opt/homebrew/Cellar/biber/2.17/bin/biber --validate-control --convert-control test
  INFO - This is Biber 2.17
  INFO - Logfile is 'test.blg'
  INFO - 'test.bcf' validates against schema '/opt/homebrew/Cellar/biber/2.17/libexec/lib/perl5/Biber/bcf.rng'
  INFO - Converted BibLaTeX control file 'test.bcf' to 'test.bcf.html'
  INFO - Reading 'test.bcf'
  ERROR - Error: Found biblatex control file version 3.7, expected version 3.8.
  This means that your biber (2.17) and biblatex (3.15) versions are incompatible.
  See compat matrix in biblatex or biber PDF documentation.
  INFO - ERRORS: 1
```

**Comment by nandahkrishna** [comment]
Based on https://github.com/plk/biber/issues/380, the updated test file is `test-dev.bcf`. Tested locally and passes.

**Review by chenrui333 — APPROVED** [review]

**Comment by brooksdavis** [comment]
Merging this broken the ability to use texlive with biber. You get errors like:
```
ERROR - Error: Found biblatex control file version 3.7, expected version 3.8.
This means that your biber (2.17) and biblatex (3.16) versions are incompatible.
```

**Comment by jrtc27** [comment]
Specifically, the Biber homepage says:
> Biber 2.17 is now [released](http://sourceforge.net/project/platformdownload.php?group_id=228270). It should be used in conjunction with biblatex 3.17".

Biblatex 3.17 was released 8 days ago.

**Comment by carlocab** [comment]
Happy to review a PR that updates the test block to make sure biber works with the latest released version of biblatex.

**Comment by jrtc27** [comment]
The error was found by CI, which said:

> ERROR - Error: Found biblatex control file version 3.7, expected version 3.8.
[52](https://github.com/Homebrew/homebrew-core/runs/4950340607?check_suite_focus=true#step:6:52)
  This means that your biber (2.17) and biblatex (3.15) versions are incompatible.
[53](https://github.com/Homebrew/homebrew-core/runs/4950340607?check_suite_focus=true#step:6:53)
  See compat matrix in biblatex or biber PDF documentation.

This was masked by changing the test file to a -dev one that is produced by an updated biblatex. This CI failure should have been an indication that more attention was needed to verify compatibility, not just blindly update test files and hope for the best.

**Comment by nandahkrishna** [comment]
Apologies for the breakage here.

> Biblatex 3.17 was released 8 days ago.

The commit to update the test file was made after the Biblatex `3.17` tag was created, and this PR was merged about 8 hours after the tag's creation. The original `test.bcf` file for `biber` hadn't been updated since 2020, and based on the issue I'd linked to and the fact that Biblatex 3.17 had been released, I took a call to update the test file.

I'd be happy to help with a PR if there is a problem with this and there is a better way to verify compatibility.

**Pull request closed without merging**
