### PR TITLE
Build Python extensions by default

### PR DESCRIPTION
**Pull request by tdsmith**
Followup to #13794.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Should these get rev-bumped too?

**Comment by tdsmith** [comment]
Maybe? What's our philosophy on that lately?

**Comment by ilovezfs** [comment]
Typically, if it changes the bottle contents in a material way, and formula != {qt,ffmpeg,very popular formula} then rev bump, but I don't have a sense of how much this change impacts the bottle contents.

**Comment by tdsmith** [comment]
Works for me. I think adding the extensions sounds reasonably material.

**Pull request closed without merging**
