### PR TITLE
tika 1.22

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
17:32:20 ==> brew fetch --retry tika --force
17:32:45 ==> FAILED
17:32:45 ==> Downloading https://www.apache.org/dyn/closer.cgi?path=tika/tika-app-1.22.jar
17:32:45 ==> Downloading from http://apache.cs.utah.edu/tika/tika-app-1.22.jar
17:32:45 curl: (22) The requested URL returned error: 404 Not Found
17:32:45 Trying a mirror...
17:32:45 ==> Downloading https://www-eu.apache.org/dist/tika/tika-app-1.22.jar
17:32:45 Downloaded to: /Users/brew/Library/Caches/Homebrew/downloads/f7a2d39b3e4cc8773eed82c5fbb59b001dea7d5d97b0bb435a237185b0d161cf--tika-app-1.22.jar
17:32:45 SHA256: d7219709abc547136fa5fca17632a85fe1cd36dc08cb4031957e3c9a836543e2
17:32:45 Resource: server
17:32:45 ==> Downloading https://www.apache.org/dyn/closer.cgi?path=tika/tika-server-1.21.jar
17:32:45 ==> Downloading from http://apache.claz.org/tika/tika-server-1.21.jar
17:32:45 curl: (22) The requested URL returned error: 404 Not Found
17:32:45 Trying a mirror...
17:32:45 ==> Downloading https://www-eu.apache.org/dist/tika/tika-server-1.21.jar
17:32:45 curl: (22) The requested URL returned error: 404 Not Found
17:32:45 Trying a mirror...
17:32:45 ==> Downloading https://www-us.apache.org/dist/tika/tika-server-1.21.jar

**Comment by chenrui333** [comment]
image

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
image

**Comment by chenrui333** [comment]
I think it can be merged now. 😄

**Comment by chenrui333** [comment]
ping @lembacon

**Comment by EricFromCanada** [comment]
Bump `resource "server"` to 1.22 first?

**Comment by chenrui333** [comment]
@EricFromCanada Did not notice that, thanks for pointing out.

**Comment by chenrui333** [comment]
Updated.

**Comment by chenrui333** [comment]
ping @lembacon

**Pull request closed without merging**
