### PR TITLE
supertux 0.6.0

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by javian** [comment]
Latest build error
```
23:42:56 -- Installing: /usr/local/Cellar/supertux/0.6.0/MacOS/libpng.dylib
23:42:56 -- Installing: /usr/local/Cellar/supertux/0.6.0/MacOS/libz.dylib
23:42:56 -- Installing: /usr/local/Cellar/supertux/0.6.0/MacOS/libjpeg.dylib
23:42:56 /usr/local/Homebrew/Library/Homebrew/build.rb:206:in `rescue in <main>': undefined method `cmd' for #<Errno::ENOENT:0x00007fab05333f30> (NoMethodError)
23:42:56 	from /usr/local/Homebrew/Library/Homebrew/build.rb:183:in `<main>'
```

**Comment by fxcoudert** [comment]
So this means one of the `Remove unnecessary files` lines is failing, because the corresponding directory does not exist anymore. One needs to build locally and inspect what is present after the build.

**Comment by javian** [comment]
I smile introvertly seeing the version test fail ^^- 😏

**Comment by javian** [comment]
It looks a bit weird. When I locally run `supertux --version` I get
```
➜  Formula git:(master) supertux2 --version
supertux2 v0.6.0
```
but if I run the test locally I get
```
➜  Formula git:(master) brew test supertux
Testing supertux
==> /usr/local/Cellar/supertux/0.6.0/bin/supertux2 --version
[WARNING] /tmp/supertux-20181228-5178-xtmqkj/SuperTux-v0.6.0-Source/src/supertux/main.cpp:115 Error saving config: Couldn't open file 'config': 21
```
Not sure what's causing that at the moment but it might explain why ci fails.

**Pull request closed without merging**
