### PR TITLE
node 8.5.0

### PR DESCRIPTION
**Pull request by dio-az**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
The test failure with jsdoc3 is reproducible locally.

```
==> /usr/local/Cellar/jsdoc3/3.5.4/bin/jsdoc --verbose test.js
Parsing /private/tmp/jsdoc3-test-20170912-52234-1wi7mlz/test.js ...
Generating output files...
fs.js:1919
  binding.copyFile(src, dest, flags);
          ^

Error: EISDIR: illegal operation on a directory, copyfile '/usr/local/Cellar/jsdoc3/3.5.4/libexec/lib/node_modules/jsdoc/templates/default/static/fonts/OpenSans-Bold-webfont.eot' -> 'out/fonts'
    at Object.fs.copyFileSync (fs.js:1919:11)
    at /usr/local/Cellar/jsdoc3/3.5.4/libexec/lib/node_modules/jsdoc/templates/default/publish.js:516:12
    at Array.forEach (<anonymous>)
    at Object.exports.publish (/usr/local/Cellar/jsdoc3/3.5.4/libexec/lib/node_modules/jsdoc/templates/default/publish.js:512:17)
    at Object.module.exports.cli.generateDocs (/usr/local/Cellar/jsdoc3/3.5.4/libexec/lib/node_modules/jsdoc/cli.js:448:35)
    at Object.module.exports.cli.processParseResults (/usr/local/Cellar/jsdoc3/3.5.4/libexec/lib/node_modules/jsdoc/cli.js:399:20)
    at module.exports.cli.main (/usr/local/Cellar/jsdoc3/3.5.4/libexec/lib/node_modules/jsdoc/cli.js:240:14)
    at Object.module.exports.cli.runCommand (/usr/local/Cellar/jsdoc3/3.5.4/libexec/lib/node_modules/jsdoc/cli.js:189:5)
    at /usr/local/Cellar/jsdoc3/3.5.4/libexec/lib/node_modules/jsdoc/jsdoc.js:105:9
    at Object.<anonymous> (/usr/local/Cellar/jsdoc3/3.5.4/libexec/lib/node_modules/jsdoc/jsdoc.js:106:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
```

@chrmoritz any idea what's wrong with 8.5.0? This doesn't look promising lol

**Comment by shinnn** [comment]
> what's wrong with 8.5.0?

This is a bug of jsdoc3. https://github.com/jsdoc3/jsdoc/issues/1438 I'm not sure what is the best way to avoid the test failure without waiting for this bug to be fixed.

Though it's not ideal, there is one proposal from me; Downgrade [the dependency of `jsdoc3`](https://github.com/Homebrew/homebrew-core/blob/814f73407c97e2e272e2b1721cbed8d4ec9a603a/Formula/jsdoc3.rb#L17) from `node` to [`node@6`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/node@6.rb).

**Comment by ilovezfs** [comment]
We'll just wait for it to be fixed.

**Comment by shinnn** [comment]
I proposed https://github.com/Homebrew/homebrew-core/pull/18008#issuecomment-329073888 because jsdoc3/jsdoc repository is not so active recently. However,

>  just wait for it to be fixed

Yes, it's also a good, straightforward solution.

**Comment by ilovezfs** [comment]
@hegemonic any idea when this might be fixed? Thanks!

**Comment by ilovezfs** [comment]
Actually there aren't enough jsdoc3 installs to warrant holding this up (50 installs on request events in the last month), so I'm going to break jsdoc3 and ship this.

**Comment by ilovezfs** [comment]
Thanks @diogoazevedos! Shipped.

**Comment by ilovezfs** [comment]
`jsdoc3` fixed in https://github.com/Homebrew/homebrew-core/pull/18060.

**Pull request closed without merging**
