### PR TITLE
fasd: switch to maintained fork at 1.0.2

### PR DESCRIPTION
**Pull request by andrewferrier**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by SMillerDev — CHANGES_REQUESTED** [review]
Is this the official successor? Did any other packagers change to this source?

**Comment by andrewferrier** [comment]
Sorry, I should have explained in my original PR.

I'm not sure there is any direct measure of 'official' (the original maintainer has gone AWOL), but:

* This new fork has the most stars by far of any fork on GitHub (29 vs. the next nearest at 4) - as measured by https://techgaun.github.io/active-forks/index.html#https://github.com/clvv/fasd.

* The new fork was last pushed to 9 months ago, which is relatively recent considering the software is stable, and is one of only two repos that recent (again measured using the same tool).

* Arch Linux packages this fork: https://archlinux.org/packages/community/any/fasd/. 

Thanks.

**Comment by andrewferrier** [comment]
Any thoughts on merging this PR? The CI failure looks like a false alarm to me.

**Comment by mkaito** [comment]
Out of curiosity, if the author is AWOL, who archived the repo?

**Comment by andrewferrier** [comment]
@mkaito the simple answer is I don't know, I assume the original author did.

**Comment by jefftemplon** [comment]
I support this request - I use `fasd` regularly, and the last few months have been nervous about the messages from Homebrew that I should find a replacement.  There is no good replacement AFAICT.

**Comment by chenrui333** [comment]
> Sorry, I should have explained in my original PR.
> 
> I'm not sure there is any direct measure of 'official' (the original maintainer has gone AWOL), but:
> 
> * This new fork has the most stars by far of any fork on GitHub (29 vs. the next nearest at 4) - as measured by https://techgaun.github.io/active-forks/index.html#https://github.com/clvv/fasd.
> * The new fork was last pushed to 9 months ago, which is relatively recent considering the software is stable, and is one of only two repos that recent (again measured using the same tool).
> * Arch Linux packages this fork: https://archlinux.org/packages/community/any/fasd/.
> 
> Thanks.

yeah, we just need clvv's endorsement. Also I feel like he should create a `fasd` organization and move the code to a co-maintained mode.

This seems another maintained fork, https://github.com/infokiller/fasd

**Comment by chenrui333** [comment]
I can still see activities from clvv, maybe just need someone to nudge him to move the fasd to a org and recruit some maintainers (could be some big efforts)

**Comment by huyz** [comment]
I would not accept any fork until the fork's maintainer both approves and enables "Issues" for their fork.  Otherwise, it would be a waste of time.

**Comment by zoltan-nz** [comment]
Hi There. Do you think we can reactivate this initiative? The fork is actively maintained, while the original version was abandoned and archived.

**Comment by huyz** [comment]
@whjvenyl how do you feel about this proposal? I see that you've enabled the Issues page on your fork. But it doesn't look you're making new releases.

**Comment by gromgit** [comment]
Not a Homebrew maintainer, but unless the original author "blesses" a specific fork, the alternative is for someone to create a _new_ formula from whichever fork that the `fasd` community (however that's defined) generally accepts. You can't call it `fasd`, to forestall potential supply chain attacks on unsuspecting users, but you can call it `infokiller-fasd` or `clvv-fasd` etc. It'll still have to [meet homebrew/core requirements](https://docs.brew.sh/Acceptable-Formulae#requirements-for-homebrewcore), but at least it's a way forward.

**Pull request closed without merging**
