### PR TITLE
serverless 1.29.2 (new formula)

### PR DESCRIPTION
**Pull request by Ketouem**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Ketouem** [comment]
`head` clause removed

**Comment by Ketouem** [comment]
Any additional work to do on the PR?

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
```
Error: 1 problem in 1 formula
serverless:
  * C: 4: col 9: Description shouldn't have a leading space
```
_(That's an audit I added a few days ago, so it's nice to have confirmation it works in the wild, heh)_.

**Comment by Ketouem** [comment]
Happy to play the guinea pig 🐹 😉 @DomT4. I've updated the description and the version being pulled.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/7717b8c8c06884edd00ab7ff0f9981cc0857e18a. Thank you for your contribution to Homebrew @Ketouem; we appreciate it! :smiley_cat:

**Pull request closed without merging**
