### PR TITLE
mmseqs2 3-be8f6

### PR DESCRIPTION
**Pull request by milot-mirdita**
Hello again,
We have a new release of our software suite. I created most of the PR with bump-formula-pr and have run both the install and test step locally. Hope everything is okay.

- [✓] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [✓] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [✓] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [✓] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
The Git commit for the docs doesn't need to be bumped?

**Comment by milot-mirdita** [comment]
It does! Thanks, you know our project better than I do myself ^_^

**Comment by ilovezfs** [comment]
You're welcome! You'll also want to remove the pre-release attribute from 3-be8f6 so that https://github.com/soedinglab/MMseqs2/releases/latest is pointing at the right one.

**Review by ilovezfs — CHANGES_REQUESTED** [review]
wait on https://github.com/soedinglab/MMseqs2/releases/latest

**Comment by milot-mirdita** [comment]
Done. Thanks again!

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Shipped! Thanks for the upgrade @milot-mirdita

**Pull request closed without merging**
