### PR TITLE
mikutter 3.6.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> brew test mikutter --verbose
==> FAILED
Testing mikutter
/usr/bin/sandbox-exec -f /tmp/homebrew20171225-87724-1j9g1uf.sb /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mikutter.rb --verbose
==> /usr/local/Cellar/mikutter/3.6.0/bin/mikutter plugin_depends /tmp/mikutter-test-20171225-87725-z2utsv/.mikutter/plugin/test_plugin/test_plugin.rb
digraph mikutter_plugin {
  achievement -> gui;
  achievement -> activity;
  achievement -> uitranslator;
  activity -> gui;
  activity -> gtk;
  activity -> settings;
  activity -> uitranslator;
  activity -> skin;
  alsa -> sound;
  api_request_file_cache;
  aspectframe -> gtk;
  bitly;
  bugreport -> gtk;
  bugreport -> uitranslator;
  change_account -> settings;
  change_account -> uitranslator;
  change_account -> achievement;
  change_account -> world;
  command -> gui;
  command -> gtk;
  command -> uitranslator;
  command -> skin;
  console -> gui;
  console -> gtk;
  console -> uitranslator;
  console -> skin;
  core;
  direct_message -> gui;
  direct_message -> gtk;
  direct_message -> uitranslator;
  direct_message -> skin;
  direct_message -> twitter;
  display_requirements -> gui;
  display_requirements -> gtk;
  display_requirements -> uitranslator;
  display_requirements -> skin;
  extract -> gtk;
  extract -> settings;
  extract -> gui;
  extract -> uitranslator;
  extract -> skin;
  file_path;
  followingcontrol -> gtk;
  followingcontrol -> gui;
  followingcontrol -> user_detail_view;
  followingcontrol -> skin;
  followingcontrol -> twitter;
  gtk -> gui;
  gtk -> uitranslator;
  gui -> uitranslator;
  gui -> skin;
  guide -> achievement;
  home_timeline -> gui;
  home_timeline -> uitranslator;
  home_timeline -> skin;
  home_timeline -> twitter;
  image_file_cache -> gtk;
  intent;
  intent_selector -> gtk;
  intent_selector -> intent;
  intent_selector -> skin;
  libnotify;
  list -> change_account;
  list -> twitter;
  list_for_profile -> list;
  list_for_profile -> gtk;
  list_for_profile -> gui;
  list_for_profile -> uitranslator;
  list_for_profile -> skin;
  list_settings -> list;
  list_settings -> settings;
  list_settings -> gui;
  list_settings -> gtk;
  list_settings -> uitranslator;
  list_settings -> skin;
  mentions -> gui;
  mentions -> uitranslator;
  mentions -> skin;
  message_detail_view -> gui;
  message_detail_view -> gtk;
  message_detail_view -> intent;
  message_detail_view -> skin;
  message_detail_view -> twitter;
  message_favorite -> message_detail_view;
  message_favorite -> skin;
  message_favorite -> twitter;
  message_retweet -> message_detail_view;
  message_retweet -> skin;
  message_retweet -> twitter;
  notification -> settings;
  notification -> uitranslator;
  notify -> settings;
  notify -> uitranslator;
  openimg -> gtk;
  openimg -> uitranslator;
  openimg -> intent;
  openimg -> photo;
  openimg -> skin;
  photo -> uitranslator;
  photo_support -> openimg;
  proxy -> gtk;
  proxy -> settings;
  proxy -> uitranslator;
  quoted_message -> gtk;
  quoted_message -> gui;
  quoted_message -> command;
  quoted_message -> skin;
  ratelimit -> gui;
  ratelimit -> activity;
  ratelimit -> uitranslator;
  rest -> twitter;
  saved_search -> gui;
  saved_search -> change_account;
  saved_search -> uitranslator;
  saved_search -> skin;
  saved_search -> twitter;
  search -> gtk;
  search -> gui;
  search -> uitranslator;
  search -> skin;
  search -> twitter;
  set_input -> settings;
  set_input -> uitranslator;
  set_view -> settings;
  set_view -> uitranslator;
  settings -> gui;
  settings -> gtk;
  settings -> uitranslator;
  settings -> skin;
  shortcutkey -> gui;
  shortcutkey -> gtk;
  shortcutkey -> settings;
  shortcutkey -> uitranslator;
  shortcutkey -> skin;
  skin -> photo;
  skin_setting_gtk -> settings;
  skin_setting_gtk -> uitranslator;
  skin_setting_gtk -> gtk;
  skin_setting_gtk -> skin;
  smartthread -> gui;
  smartthread -> uitranslator;
  smartthread -> skin;
  sound -> settings;
  sound -> uitranslator;
  spell;
  streaming -> twitter;
  streaming_connection_status -> activity;
  streaming_connection_status -> uitranslator;
  tco;
  twitter -> world;
  twitter -> spell;
  uitranslator;
  user_detail_view -> gui;
  user_detail_view -> gtk;
  user_detail_view -> command;
  user_detail_view -> uitranslator;
  user_detail_view -> intent;
  user_detail_view -> skin;
  user_detail_view -> twitter;
  web -> uitranslator;
  world;
  test_plugin;
}
==> /usr/local/Cellar/mikutter/3.6.0/bin/mikutter --plugin=test_plugin --debug
notice: {MIKUTTER_DIR}/core/configloader.rb:49:in `boot': setting data not found
notice: {MIKUTTER_DIR}/core/miquire_plugin.rb:155:in `block in load': plugin loaded: {MIKUTTER_DIR}/core/plugin/core/core.rb
notice: {MIKUTTER_DIR}/core/miquire_plugin.rb:155:in `block in load': plugin loaded: /tmp/mikutter-test-20171225-87725-z2utsv/.mikutter/plugin/test_plugin/test_plugin.rb
notice: {MIKUTTER_DIR}/mikutter.rb:44:in `<main>': fire boot event
/usr/local/Cellar/mikutter/3.6.0/libexec/mikutter.rb:45:in `<main>': uninitialized constant Post (NameError)
Error: mikutter: failed
Failed executing: /usr/local/Cellar/mikutter/3.6.0/bin/mikutter --plugin=test_plugin --debug
/usr/local/Homebrew/Library/Homebrew/formula.rb:1797:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1735:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1735:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mikutter.rb:295:in `block in <class:Mikutter>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1641:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:548:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1640:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:834:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1639:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1633:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by ilovezfs** [comment]
@midchildan any idea what the problem is here?

**Comment by midchildan** [comment]
@ilovezfs The test I created for this formula is a bit of a hack, because mikutter is a GUI Twitter client and is hard to write a proper test. Mikutter is built on a plugin-based architecture, and most of its functionalities are provided as a set of standard plugins. I took advantage of this fact and disabled plugins that aren't essential to booting mikutter, so that I could exclude GUIs and Twitter-related stuff from running during the test. But code refactoring from 3.6 seems to block mikutter from booting if Twitter-related plugins aren't loaded. I'll see if I can work around this limitation. Apart from the tests, mikutter seems to be working fine though.

**Comment by ilovezfs** [comment]
@midchildan cool. I'll merge this as-is and look forward to a PR from you :)

**Pull request closed without merging**
