### PR TITLE
python@3 rename from python3, python@2 rename from python

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @MikeMcQuaid

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]

**Review by ilovezfs — COMMENTED** [review]
blocked on https://github.com/Homebrew/brew/pull/3613 and a new tag

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Review by ilovezfs — COMMENTED** [review]
Blocked on https://github.com/Homebrew/brew/pull/3618 and a new tag.

**Comment by ilovezfs** [comment]
Closing for now.

**Pull request closed without merging**
