### PR TITLE
haskell-stack 1.9.3.1

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
```
19:14:27 Populated index cache.
19:14:27 
19:14:27 Error: While constructing the build plan, the following exceptions were encountered:
19:14:27 
19:14:27 In the dependencies for stack-1.9.3.1:
19:14:27     rio-0.1.5.0 from stack configuration does not match >=0.1.9.2 && <0.2  (latest matching version
19:14:27                 is 0.1.9.2)
19:14:27 needed since stack is a build target.
19:14:27 
19:14:27 Some different approaches to resolving this:
19:14:27 
19:14:27   * Set 'allow-newer: true'
19:14:27     in /private/tmp/haskell-stack-20190519-38154-aowgn8/stack-1.9.3.1/.stack/config.yaml to ignore all version constraints and build anyway.
19:14:27 
19:14:27   * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some
19:14:27     working build configuration. This can be convenient when dealing with many complicated
19:14:27     constraint errors, but results may be unpredictable.
19:14:27 
19:14:27   * Recommended action: try adding the following to your extra-deps
19:14:27     in /private/tmp/haskell-stack-20190519-38154-aowgn8/stack-1.9.3.1/stack-lts-12.yaml:
19:14:27 
19:14:27 rio-0.1.9.2@sha256:d46a202ae0930b496fd17fd9041d051d45645ab28a2f8d30cf483f50ccb21eb3
19:14:27 
19:14:27 Plan construction failed.
19:14:27 
19:14:27 ==> Formula
19:14:27 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/haskell-stack.rb
19:14:27 ==> Configuration
```

**Comment by chenrui333** [comment]
Should be fixed by now.

**Comment by chenrui333** [comment]
waiting to be merged now.

**Comment by SMillerDev** [comment]
Thanks @chenrui333

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
```
22:20:32 ==> cabal v1-install --jobs=3 --max-backjumps=100000 happy
22:20:32 clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
22:20:32 clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
22:20:32 clang: warning: argument unused during compilation: '-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries' [-Wunused-command-line-argument]
22:20:32 Resolving dependencies...
22:20:32 Notice: installing into a sandbox located at
22:20:32 /private/tmp/haskell-stack-20190530-68506-6bu05s/stack-1.9.3.1/.cabal-sandbox
22:20:32 Downloading  happy-1.19.10
22:20:32 Downloaded   happy-1.19.10
22:20:32 Starting     happy-1.19.10
22:20:32 Building     happy-1.19.10
22:20:32 Completed    happy-1.19.10
22:20:32 ==> cabal v1-install --jobs=3 --max-backjumps=100000
22:20:32 clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
22:20:32 clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
22:20:32 clang: warning: argument unused during compilation: '-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries' [-Wunused-command-line-argument]
22:20:32 cabal: Error reading local package.
22:20:32 Couldn't find .cabal file in: .
22:20:32 
22:20:32 
22:20:32 ==> Formula
22:20:32 Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/haskell-stack.rb
```

somehow the build is failing now

**Comment by chenrui333** [comment]
Close in favor of https://github.com/Homebrew/homebrew-core/pull/40975

**Pull request closed without merging**
