### PR TITLE
citus 6.1.0

### PR DESCRIPTION
**Pull request by jasonmp85**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jasonmp85** [comment]
Rebased this. Anything blocking merge?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by jasonmp85** [comment]
Looks like the commit status is good…

**Comment by MikeMcQuaid** [comment]
Thanks again for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
