### PR TITLE
terraform-inventory: add dependencies for HEAD build

### PR DESCRIPTION
**Pull request by AndiDog**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)? – Has warnings "`go_resource`s are deprecated", but my fix does not change that.

-----

Add required dependencies for building with `brew install --HEAD`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
These dependencies should be added for head only, i.e. in a `head do … end` block. But if the software hasn't seen a release in many years, maybe it's better for us to drop it.

**Comment by AndiDog** [comment]
Added `head do ... end` block. I asked for a new release and also added another pull request to the project. If there's no activity, I would fork and take maintainership incl. homebrew support. Using it at my company and I think it's valuable for other users.

**Review by mistydemeo — DISMISSED** [review]
Mind updating this for the `brew audit` and `brew style` warnings?

```
C: 24:  5: Use 2 (not 4) spaces for indentation.
C: 29:  5: Use 2 (not 4) spaces for indentation.

C: 22: col 3: `head` (line 22) should be put before `depends_on` (line 20)
C: 22: col 3: `head` and `head do` should not be simultaneously present
```

**Comment by AndiDog** [comment]
audit/style offenses fixed

**Comment by fxcoudert** [comment]
Thanks @AndiDog for your contribution to Homebrew!

**Pull request merged**
