### PR TITLE
efl 1.23.2

### PR DESCRIPTION
**Pull request by fxcoudert**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
`efl` has changed its built system to `meson` and `ninja`. However after trying to build I get stuck with this error:
```
src/lib/eina/meson.build:264:2: ERROR: Dependency "libsystemd" not found, tried pkgconfig, cmake and framework
```
Could it be possible that it can now only be built on linux?

**Comment by Bo98** [comment]
Try `-Dsystemd=false`.

**Comment by Moisan** [comment]
The dependencies seem to be OK now. Current build error:
```
Installing /private/tmp/efl-20191123-85322-1so3v2z/efl-1.23.2/build/src/scripts/eo/eo_debug to /usr/local/Cellar/efl/1.23.2/bin
Installing /private/tmp/efl-20191123-85322-1so3v2z/efl-1.23.2/build/Efl_Config.h to /usr/local/Cellar/efl/1.23.2/include/efl-1
Installing /private/tmp/efl-20191123-85322-1so3v2z/efl-1.23.2/build/elm_intro.h to /usr/local/Cellar/efl/1.23.2/include/elementary-1
FAILED: meson-install 
/usr/local/Cellar/meson/0.52.0/libexec/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

**Comment by Bo98** [comment]
Relevant part:

```
(most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/minstall.py", line 521, in run
    installer.do_install(datafilename)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/minstall.py", line 346, in do_install
    self.install_data(d)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/minstall.py", line 375, in install_data
    d.dirmaker.makedirs(outdir, exist_ok=True)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/minstall.py", line 55, in makedirs
    os.makedirs(path, exist_ok=exist_ok)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 1] Operation not permitted: '/usr/local/Cellar/dbus/1.12.16/share/dbus-1/services'
```

Can we make it not do that?

**Comment by Bo98** [comment]
Just a heads up: the current version of EFL we ship does not compile on Xcode 11:

```
lib/ecore_cocoa/ecore_cocoa_app.m:48:5: error: use of undeclared identifier '_mainMenu'
   [_mainMenu update];
    ^
lib/ecore_cocoa/ecore_cocoa_app.m:79:4: error: use of undeclared identifier '_running'
   _running = 1;
   ^
2 errors generated.
```

Tried to revision bump it because the gif module was broken after giflib update but couldn't.

Not sure if the problem is fixed in this new version or not.

**Pull request closed without merging**
