### PR TITLE
git-review 1.28.0

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by zbeekman** [comment]
```
==> git init
Initialized empty Git repository in /private/tmp/git-review-test-20190525-74178-1pe5ud3/.git/
==> git remote add gerrit https://github.com/Homebrew/homebrew.github.io
==> git add foo
==> git commit -m test
hint: The '.git/hooks/commit-msg' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
[master (root-commit) 5d9346d] test
 Committer: Homebrew <brew@Mojave-2.local>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 1 file changed, 1 insertion(+)
 create mode 100644 foo
==> /usr/local/Cellar/git-review/1.28.0/bin/git-review --dry-run
Traceback (most recent call last):
  File "/usr/local/Cellar/git-review/1.28.0/libexec/bin/git-review", line 6, in <module>
    from git_review.cmd import main
  File "/usr/local/Cellar/git-review/1.28.0/libexec/lib/python3.7/site-packages/git_review/cmd.py", line 28, in <module>
    import six
ModuleNotFoundError: No module named 'six'
Error: git-review: failed
```

**Comment by chenrui333** [comment]
resume

**Comment by chenrui333** [comment]
Should be good now.

**Comment by chenrui333** [comment]
@fxcoudert this can be merged. 😄

**Pull request closed without merging**
