### PR TITLE
universal-ctags p6.0.20221218.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Needs a `depends_on "python@3.10"` although I'm not sure where it picks that dependency from.

**Comment by chenrui333** [comment]
build/test works fine in my local (13-arm)

**Comment by cho-m** [comment]
`docutils` scripts are currently broken. There is no guarantee which Python version is used in scripts so any formula that has a build-time dependency on `docutils` is also going to have issues. This is why Intel macOS & Linux need `python@3.11` but ARM macOS needs `python@3.10`.

On side note, we really should have a Python runtime dependency for `docutils`. Removing it has broken our original use-case and will make it harder to reproduce builds as build-time dependency on `docutils` usually means the formula needs to use one of the scripts (e.g. usually `rst2man` to generate manpages).

**Comment by cho-m** [comment]
Update merged in #118740

**Pull request closed without merging**
