### PR TITLE
rancher-cli 0.5.2

### PR DESCRIPTION
**Pull request by bfontaine**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
This has not been marked as the lastest release https://github.com/rancher/cli/releases

**Comment by bfontaine** [comment]
@ilovezfs Good catch; is it too late to revert?

**Comment by ilovezfs** [comment]
I would revert ASAP and open an issue asking them why that tag is sitting there alongside newer RCs.

**Comment by bfontaine** [comment]
Reverted, plus https://github.com/rancher/rancher/issues/8529.

**Comment by ilovezfs** [comment]
Thanks!

**Pull request closed without merging**
