### PR TITLE
libelf: remove libelf and dependents

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The libelf upstream is no longer available, and its apparent successor `elfutils` does not build on macOS. 

c.f. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813584, https://github.com/Homebrew/homebrew-core/issues/39870

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
Error: Missing formulae should not have dependents!
dwarfutils
```

**Comment by fxcoudert** [comment]
Given it's working, and it's actually widely used (1,469 installs last month), I'm reluctant to remove it like that.

**Comment by kousu** [comment]
Yeah, I don't want this removed. It is needed by arm-eabi-none-gcc, and they seem to be happy enough to use the older version. The successor is too new!

I did try to get the successor to build. After some futzing, I got this to compile:

```
$ git clone git://sourceware.org/git/elfutils.git
$ brew install autoconf automake argp-standalone gawk 
$ cd elfutils
$ autoreconf -i -f
$ ./configure CC=gcc-8 --disable-symbol-versioning --enable-maintainer-mode
```

I haven't yet gotten `make && make check` to work though: it wants error.h, byteswap.h, and endian.h, all of which are glibc extensions. And glibc is, I assume, a hard no for brew, so porting to elfutils is a non-starter, at least at this point, unless we patch it for darwin for them.

**Comment by kousu** [comment]
There's a mirror of libelf at https://github.com/WolfgangSt/libelf. It looks like this it's one below the same version that was removed: 0.8.12. I'm going to see if it builds and if I can use it for avrdude.

**Comment by kousu** [comment]
There's also https://sourceforge.net/p/elftoolchain/code/HEAD/tree/branches/release-branch-0.7/ which seems to be a drop-in compatible BSD-licensed replacement for libelf.

**Comment by vszakats** [comment]
This fixes the URL issues: https://github.com/Homebrew/homebrew-core/pull/39936

**Pull request closed without merging**
