### PR TITLE
upx 4.0.2

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
relates to https://github.com/upx/upx/issues/628

**Comment by carlocab** [comment]
Any chance you have the time to take a look at this, @Bo98? I think the test is failing because of our use of patchelf. The original test (without `--force-execve`) succeeds when built from source. After installing from a bottle, the test fails.

CC @Homebrew/linux

**Comment by Bo98** [comment]
I will take a look yes -  I have one patchelf change already locally that I'll test.

It might be just after the AGM.

**Comment by iredmail** [comment]
Dear all, any update?

Thanks for your great work. :)

**Comment by chenrui333** [comment]
ping @Bo98 :)

**Comment by gnought** [comment]
Might not relate to `--force-execve`. 
I tried on Apple Silicon macOS Ventura 13, it still returns failure for 
```
    system "#{bin}/upx", "-1", "./upx2"
```
UPX 4.0.2 still has an unresolved issue to compile macOS arm64 binaries, reported in https://github.com/upx/upx/issues/612 and https://github.com/upx/upx/issues/601

**Review by carlocab — APPROVED** [review]
Let's move this along.

CC @Homebrew/linux in case anyone's interested in fixing this test.

**Pull request closed without merging**
