### PR TITLE
envoy: fix build for Linux

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
```
[1,531 / 4,866] Compiling src/google/protobuf/repeated_field.cc; 2s processwrapper-sandbox ... (2 actions running)
INFO: From CcCmakeMakeRule bazel/foreign_cc/nghttp2/include:
rules_foreign_cc: Cleaning temp directories
INFO: From CcCmakeMakeRule bazel/foreign_cc/ares/include:
rules_foreign_cc: Cleaning temp directories
ERROR: /tmp/envoy-20210728-8806-1776cas/.brew_home/_bazel/198d9fb500d90bb37d44573bb4174b7e/external/boringssl/BUILD:162:11: Compiling src/crypto/curve25519/curve25519.c failed: (Exit 1): gcc-11 failed: error executing command 
  (cd /tmp/envoy-20210728-8806-1776cas/.brew_home/_bazel/198d9fb500d90bb37d44573bb4174b7e/sandbox/processwrapper-sandbox/1510/execroot/envoy && \
  exec env - \
    BAZEL_LINKLIBS=-l%:libstdc++.a \
    BAZEL_LINKOPTS=-lm \
    CC=gcc-11 \
    CXX=g++-11 \
    PATH=/home/linuxbrew/.linuxbrew/opt/python@3.9/libexec/bin:/home/linuxbrew/.linuxbrew/bin:/usr/bin:/bin \
    *** \
  /home/linuxbrew/.linuxbrew/bin/gcc-11 -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/k8-opt/bin/external/boringssl/_objs/crypto/curve25519.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/boringssl/_objs/crypto/curve25519.pic.o' -fPIC -gsplit-dwarf -iquote external/boringssl -iquote bazel-out/k8-opt/bin/external/boringssl -isystem external/boringssl/src/include -isystem bazel-out/k8-opt/bin/external/boringssl/src/include -fPIC -fexceptions -Wa,--noexecstack '-D_XOPEN_SOURCE=700' -Wall -Werror '-Wformat=2' -Wsign-compare -Wmissing-field-initializers -Wwrite-strings -Wshadow -fno-common '-std=c11' -Wmissing-prototypes -Wold-style-definition -Wstrict-prototypes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/boringssl/src/crypto/curve25519/curve25519.c -o bazel-out/k8-opt/bin/external/boringssl/_objs/crypto/curve25519.pic.o)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
external/boringssl/src/crypto/curve25519/curve25519.c:503:57: error: argument 2 of type 'const uint8_t[32]' {aka 'const unsigned char[32]'} with mismatched bound [-Werror=array-parameter=]
  503 | int x25519_ge_frombytes_vartime(ge_p3 *h, const uint8_t s[32]) {
      |                                           ~~~~~~~~~~~~~~^~~~~
In file included from external/boringssl/src/crypto/curve25519/curve25519.c:33:
external/boringssl/src/crypto/curve25519/internal.h:109:58: note: previously declared as 'const uint8_t *' {aka 'const unsigned char *'}
  109 | int x25519_ge_frombytes_vartime(ge_p3 *h, const uint8_t *s);
      |                                           ~~~~~~~~~~~~~~~^
external/boringssl/src/crypto/curve25519/curve25519.c:823:57: error: argument 2 of type 'const uint8_t *' {aka 'const unsigned char *'} declared as a pointer [-Werror=array-parameter=]
  823 | void x25519_ge_scalarmult_base(ge_p3 *h, const uint8_t *a) {
      |                                          ~~~~~~~~~~~~~~~^
In file included from external/boringssl/src/crypto/curve25519/curve25519.c:33:
external/boringssl/src/crypto/curve25519/internal.h:117:56: note: previously declared as an array 'const uint8_t[32]' {aka 'const unsigned char[32]'}
  117 | void x25519_ge_scalarmult_base(ge_p3 *h, const uint8_t a[32]);
      |                                          ~~~~~~~~~~~~~~^~~~~
cc1: all warnings being treated as errors
Target //source/exe:envoy-static failed to build
INFO: Elapsed time: 629.287s, Critical Path: 29.96s
INFO: 1646 processes: 131 internal, 1514 processwrapper-sandbox, 1 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by cho-m** [comment]
Also adding note that attempt with LLVM 12 failed - https://github.com/Homebrew/homebrew-core/commit/4d8c84bc5d5520fb2e5e9d5eeb8de22051d8e7e0
Upstream only runs CI build+tests on LLVM/Clang 10. They do officially list GCC support and do check CI build (no test) on GCC 9 (see: https://github.com/envoyproxy/envoy/tree/main/ci#build-image-base-and-compiler-versions).
```
[1,440 / 4,914] Compiling src/compiler/python_generator.cc [for host]; 4s processwrapper-sandbox ... (2 actions, 1 running)
INFO: From Generating C++ proto_library @com_google_googleapis//google/devtools/cloudtrace/v2:cloudtrace_proto:
google/devtools/cloudtrace/v2/trace.proto:19:1: warning: Import google/api/annotations.proto is unused.
google/devtools/cloudtrace/v2/tracing.proto:26:1: warning: Import google/protobuf/timestamp.proto is unused.
ERROR: /tmp/envoy-20210729-10250-1dlkcus/.brew_home/_bazel/9ea9a869639bb884de78ea3b634500d5/external/com_google_absl/absl/base/BUILD.bazel:66:11: output 'external/com_google_absl/absl/base/_objs/raw_logging_internal/raw_logging.dwo' was not created
ERROR: /tmp/envoy-20210729-10250-1dlkcus/.brew_home/_bazel/9ea9a869639bb884de78ea3b634500d5/external/com_google_absl/absl/base/BUILD.bazel:66:11: Compiling absl/base/internal/raw_logging.cc failed: not all outputs were created or valid
Target //source/exe:envoy-static failed to build
INFO: Elapsed time: 726.592s, Critical Path: 23.36s
INFO: 1515 processes: 247 internal, 1267 processwrapper-sandbox, 1 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

---

Currently trying `gcc@10`. Has been running for 4+ hours so either working or stuck.

**Comment by cho-m** [comment]
Finally built by using `gcc@9`.
Test failure due to Homebrew issue. Will add as test dependency with comment that Homebrew issue.
```
==> brew test --verbose envoy
==> FAILED
Error: test failed
==> Testing envoy
Error: envoy: failed
An exception occurred within a child process:
  CompilerSelectionError: envoy cannot be built with any available compilers.
Install Clang or run `brew install gcc`.
```

**Review by SMillerDev — APPROVED** [review]
Thanks @cho-m !

@Homebrew/linux could you take a look at the brew issue?

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
I'm fine as-is. @cho-m can you open an issue in Homebrew/brew with a link to this pull request, so that we keep track of it. Not saying that it will be fixed in the next days, but it's something we need to address whenever someone finds time to look into that.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Dispatched, https://github.com/Homebrew/homebrew-core/actions/runs/1083018391

**Comment by cho-m** [comment]
> @cho-m can you open an issue in Homebrew/brew with a link to this pull request, so that we keep track of it.

@iMichka Opened https://github.com/Homebrew/brew/issues/11795.
A similar failure happened in `dotnet` for `depends_on "llvm" => :build`.
And I think we saw the failure when `semgrep` was tested as dependent.

---

> Dispatched, https://github.com/Homebrew/homebrew-core/actions/runs/1083018391

@chenrui333 `envoy` takes 5 hours to build, so it hits the 1 hour timeout.
There is probably another way to upload the bottle, but I am not aware of steps.

**Comment by iMichka** [comment]
I dispatched a new build: https://github.com/Homebrew/homebrew-core/actions/runs/1083411661
You can change the timeout from 60 to 360 in the dispatch options.

And I think you can use "Linux" as build agent instead of "ubuntu-latest" to use the self-hosted runner if the build takes more than 360 minutes.

**Pull request merged**
