### PR TITLE
ansible 2.2.0.0

### PR DESCRIPTION
**Pull request by robotblake**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

* Upgraded Ansible
* Upgraded dependencies
* Removed httplib2 (not needed in >= 2.1)

### CODE REVIEW

**Comment by tdsmith** [comment]
Can you shorten line 19 to `depends_on :python`, please? Thanks!

cf #5042

**Comment by ilovezfs** [comment]
@robotblake ping

**Comment by robotblake** [comment]
Done.

**Comment by tdsmith** [comment]
Thanks for your pull request! :tada: Homebrew thrives because of contributions like this one.

**Pull request closed without merging**
