### PR TITLE
gawk 4.2.1

### PR DESCRIPTION
**Pull request by ilovezfs**
depend on gettext

### CODE REVIEW

**Comment by chdiza** [comment]
On my machine the `make check` fails.  I've reported upstream already.

**Comment by chdiza** [comment]
Upstream bug report is [here](http://lists.gnu.org/archive/html/bug-gawk/2018-02/msg00074.html).

I don't think we should add a dependcy on `gettext` solely to pass a test suite.  In that thread, the devs told me that the test failure can be ignored.  I've also asked them to change the tests so that `gettext` isn't required.

**Comment by ilovezfs** [comment]
@chdiza too late ;)

**Comment by ilovezfs** [comment]
@chdiza fyi the gettext dependency is also used by both [MacPorts](https://github.com/macports/macports-ports/blob/919f2ac06d3bbbcddd304a2ec5428b909c041f94/lang/gawk/Portfile#L26) and [Spack](https://github.com/spack/spack/blob/05fa3026551fd1fc7895ea5cfaed001c2bb1af55/var/spack/repos/builtin/packages/gawk/package.py#L47), and allows gawk to print its usage messages/errors/etc. in the user's local language. See https://www.gnu.org/software/gawk/manual/html_node/Gawk-I18N.html

Currently that includes the following translations:

/usr/local/Cellar/gawk/4.2.1/share/locale/ca/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/da/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/de/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/es/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/fi/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/fr/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/id/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/it/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/ja/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/ms/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/nl/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/pl/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/pt_BR/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/sv/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/vi/LC_MESSAGES/gawk.mo
/usr/local/Cellar/gawk/4.2.1/share/locale/zh_CN/LC_MESSAGES/gawk.mo

So I don't see any downside here given how small of a dependency gettext is.

**Pull request closed without merging**
