### PR TITLE
fortune: Don't install offensive quotes

### LINKED ISSUE #8811: fortune formulae violates Homebrew code of conduct
The version of fortune [installed by Homebrew](https://formulae.brew.sh/formula/fortune) is based on a distribution of the tool 'fortune-mod' which includes explicitly racist, homophobic, ethnically insensitive and other offensive content that directly conflicts with the [Homebrew's code of conduct](https://github.com/Homebrew/.github/blob/HEAD/CODE_OF_CONDUCT.md#code-of-conduct).  Please adjust this formulae so that content which violates the code of conduct is not installed by default on a user's machine.

## repro steps

(content warning, running these commands will potentially output offensive content)

```
> brew install fortune
> fortune -o racism
<... racist quote omitted from bug report ...>
> fortune -o hphobia
<... homophobic quote omitted from bug report ...>
> fortune -o ethnic
<... ethnically insensitive quote omitted from bug report ...>
```

You can investigate all of the offensive databases installed by Homebrew's fortune formulae in its /share/games/fortunes/off directory:

```
> ls /usr/local/Cellar/fortune/9708/share/games/fortunes/off
astrology          drugs              limerick           misogyny           racism             sex
astrology.dat      drugs.dat          limerick.dat       misogyny.dat       racism.dat         sex.dat
black-humor        ethnic             misandry           politics           religion           songs-poems
black-humor.dat    ethnic.dat         misandry.dat       politics.dat       religion.dat       songs-poems.dat
definitions        hphobia            miscellaneous      privates           riddles            vulgarity
definitions.dat    hphobia.dat        miscellaneous.dat  privates.dat       riddles.dat        vulgarity.dat
```

Quotes from these databases are sourced randomly when the '-o' (offensive) option is passed to the tool, and/or the database is specified by name as an argument to the tool.

## expected behavior

Installing Homebrew's fortune formulae should not add to a user's machine databases of content which violate the Homebrew project's code of conduct.

The fortune tool has a long history and discussion of handling offensive content chronicled in its [readme file](https://www.ibiblio.org/pub/linux/games/amusements/fortune/fortune-mod-9708.README). It appears the past maintainers attempted to isolate offensive content into explicit databases hidden behind opt in command line parameters, however this content is still distributed and loaded on Homebrew user's machines likely without their knowledge or consent. I would recommend that Homebrew patch the formulae to move these offensive databases outside of the officially distributed package entirely. If users would like to use fortune with content that violates this project's code of conduct they can publish and maintain a tap on their own servers, under their own code of conduct.

### PR DESCRIPTION
**Pull request by issyl0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

- These violate our Code of Conduct.
- Fixes https://github.com/Homebrew/brew/issues/8811.

### CODE REVIEW

**Comment by issyl0** [comment]
I tried to add a license, but I picked the wrong one (oops, I think I read the [wrong file](http://www.ibiblio.org/pub/linux/games/amusements/fortune/fortune-mod.lsm)), and then the one that it [actually is (BSD, for the modified download we ship)](http://www.ibiblio.org/pub/linux/games/amusements/fortune/fortune-mod.lsm) is not a recognized license identifier. So I gave up with setting a license for this _right now_. Either way, licenses aren't the most important thing with this PR!

**Review by SMillerDev — APPROVED** [review]
Thanks @issyl0  ! Without your contributions it'd be impossible to keep homebrew going. You can feel good knowing that you've made the world a lot better for homebrew users around the world! 👍 🎉

**Comment by Julian** [comment]
Is there not a way to restore these using the existing formula?

I can certainly agree installing them by default for folks who don't want them isn't the right behavior, and I know Homebrew doesn't really have options/arguments to formulas anymore, so does that basically mean to get these back you have to fork the formula?

**Comment by Rylan12** [comment]
@Julian yes, the best way to get this functionality is to host it in your own custom tap (as you've done).

I want to take a second to thank you for being so respectful about this. I opened this (hesitantly) expecting an angry comment berating us for making this choice... that's how these often go, unfortunately. Needless to say, I was pleasantly surprised! It can be draining having to handle stubborn commenters telling us we're doing things the wrong way and offering no help. Hearing positive feedback, even on a disappointing change, makes a big difference to us and is what makes being a maintainer worth it.

Thank you for your understanding and thanks for the kind words! ❤️

**Comment by Julian** [comment]
I specifically tried to be as understanding as I could, regardless of whether I agreed or not, knowing that'd be the case :) (that you may have been bracing for backlash, and that ultimately there can be nothing but good will intended here by making this kind of change, even if it means a few of us get some extra work if we insist).

So yeah thank *you* again!

**Pull request closed without merging**
