### PR TITLE
Bump to python@3.9 for awscli

### PR DESCRIPTION
**Pull request by jamesharr**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Bump to Python 3.9

### CODE REVIEW

**Comment by fxcoudert** [comment]
We need to migrate all formulas that have related depencies at the same time. This means: `conjure-up`, `iamy`, and `juju-wait` as well.

**Comment by jamesharr** [comment]
Bumped python version for conjure-up and juju-wait as well. iamy didn't depend on a python version.

Tests are pending.

**Comment by fxcoudert** [comment]
Almost ready:
- One commit per formula/file
- Each commit title of the format: `awscli: migrate to python@3.9`
- Bump the revision number for each formula

**Comment by jamesharr** [comment]
Everything is done but the last bullet point - I'm not sure how to bump the version of the formula itself. I didn't see anything in Formula/awscli.rb that indicates the version for the formula

**Comment by jonchang** [comment]
Add `revision 1`.

**Comment by jamesharr** [comment]
Pending tests completing, I think I have everything done.

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
