### PR TITLE
blazegraph 2.1.5

### PR DESCRIPTION
**Pull request by shwang53**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
previous effort, #40004

**Comment by Bo98** [comment]
It does not work with Java newer than Java 8. The "1.7+" requirement is allowing it to use OpenJDK 13.

However the issue appears to be fixed in the upcoming 2.1.6. A release candidate was recently released with a fix.

**Comment by chenrui333** [comment]
Good point, I will try with Java 8 for now.

**Comment by Bo98** [comment]
Still picks up OpenJDK 13:

> AdoptOpenJDK 13.0.2

**Comment by chenrui333** [comment]
<details>
<summary>Test failure</summary>

```
21:48:09 ==> brew test blazegraph --verbose
21:48:18 ==> FAILED
21:48:18 Testing blazegraph
21:48:18 /usr/bin/sandbox-exec -f /private/tmp/homebrew20200304-23203-1yubnbp.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/blazegraph.rb --verbose
21:48:18 Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
21:48:18 INFO: com.bigdata.util.config.LogUtil: Configure: jar:file:/usr/local/Cellar/blazegraph/2.1.5/libexec/blazegraph.jar!/log4j.properties
21:48:18 
21:48:18 BlazeGraph(TM) Graph Engine
21:48:18 
21:48:18                    Flexible
21:48:18                    Reliable
21:48:18                   Affordable
21:48:18       Web-Scale Computing for the Enterprise
21:48:18 
21:48:18 Copyright SYSTAP, LLC DBA Blazegraph 2006-2016.  All rights reserved.
21:48:18 
21:48:18 mojave
21:48:18 Wed Mar 04 02:48:13 GMT 2020
21:48:18 Mac OS X/10.14.6 x86_64
21:48:18 Mac OS X 10.14.6 x86_64 #CPU=6
21:48:18 AdoptOpenJDK 13.0.2
21:48:18 freeMemory=229440944
21:48:18 buildVersion=2.1.5
21:48:18 gitCommit=cb08991909034b5fba53c16f5c495e72ab011933
21:48:18 
21:48:18 Dependency         License                                                                 
21:48:18 ICU                http://source.icu-project.org/repos/icu/icu/trunk/license.html          
21:48:18 bigdata-ganglia    http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 blueprints-core    https://github.com/tinkerpop/blueprints/blob/master/LICENSE.txt         
21:48:18 colt               http://acs.lbl.gov/software/colt/license.html                           
21:48:18 commons-codec      http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 commons-fileupload http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 commons-io         http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 commons-logging    http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 dsiutils           http://www.gnu.org/licenses/lgpl-2.1.html                               
21:48:18 fastutil           http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 flot               http://www.opensource.org/licenses/mit-license.php                      
21:48:18 high-scale-lib     http://creativecommons.org/licenses/publicdomain                        
21:48:18 httpclient         http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 httpclient-cache   http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 httpcore           http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 httpmime           http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 jackson-core       http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 jetty              http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 jquery             https://github.com/jquery/jquery/blob/master/MIT-LICENSE.txt            
21:48:18 jsonld             https://raw.githubusercontent.com/jsonld-java/jsonld-java/master/LICENCE
21:48:18 log4j              http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 lucene             http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 nanohttp           http://elonen.iki.fi/code/nanohttpd/#license                            
21:48:18 rexster-core       https://github.com/tinkerpop/rexster/blob/master/LICENSE.txt            
21:48:18 river              http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 semargl            https://github.com/levkhomich/semargl/blob/master/LICENSE               
21:48:18 servlet-api        http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 sesame             http://www.openrdf.org/download.jsp                                     
21:48:18 slf4j              http://www.slf4j.org/license.html                                       
21:48:18 zookeeper          http://www.apache.org/licenses/LICENSE-2.0.html                         
21:48:18 
21:48:18 ERROR: Banner.java:160: Uncaught exception in thread
21:48:18 java.lang.NullPointerException
21:48:18 	at com.bigdata.rdf.sail.webapp.StandaloneNanoSparqlServer.main(StandaloneNanoSparqlServer.java:142)
21:48:18 Error: blazegraph: failed
21:48:18 An exception occurred within a child process:
21:48:18   Test::Unit::AssertionFailedError: <#<Pathname:/private/tmp/blazegraph-test-20200304-23204-mkwk4s/blazegraph.jnl>>.exist? is true value expected but was
21:48:18 <false>
21:48:18 /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:55:in `block in assert_block'
21:48:18 /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:1631:in `_wrap_assertion'
21:48:18 /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:53:in `assert_block'
21:48:18 /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:1392:in `block in assert_predicate'
21:48:18 /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:1636:in `_wrap_assertion'
21:48:18 /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/gems/2.6.0/gems/test-unit-3.2.9/lib/test/unit/assertions.rb:1383:in `assert_predicate'
21:48:18 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/blazegraph.rb:43:in `block in <class:Blazegraph>'
21:48:18 /usr/local/Homebrew/Library/Homebrew/formula.rb:1757:in `block (3 levels) in run_test'
21:48:18 /usr/local/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
21:48:18 /usr/local/Homebrew/Library/Homebrew/formula.rb:1756:in `block (2 levels) in run_test'
21:48:18 /usr/local/Homebrew/Library/Homebrew/formula.rb:865:in `with_logging'
21:48:18 /usr/local/Homebrew/Library/Homebrew/formula.rb:1755:in `block in run_test'
21:48:18 /usr/local/Homebrew/Library/Homebrew/formula.rb:2000:in `block in mktemp'
21:48:18 /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
21:48:18 /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
21:48:18 /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
21:48:18 /usr/local/Homebrew/Library/Homebrew/formula.rb:1999:in `mktemp'
21:48:18 /usr/local/Homebrew/Library/Homebrew/formula.rb:1749:in `run_test'
21:48:18 /usr/local/Homebrew/Library/Homebrew/test.rb:33:in `block in <main>'
21:48:18 /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
21:48:18 /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
21:48:18 /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
21:48:18 /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
21:48:18 /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
21:48:18 /usr/local/Homebrew/Library/Homebrew/test.rb:32:in `<main>'
```

</details>

**Comment by Bo98** [comment]
There is a 2.1.6 release candidate that fixes this, though it's been over a month since that was released so I don't know when a final version is coming.

**Comment by chenrui333** [comment]
Sounds like we should close this PR and wait for the next release?

**Comment by Bo98** [comment]
This affects the current version we ship so arguably we should fix it.

Try add `, java_version: "1.8"` to the end of the `write_jar_script` line.

Also add a comment to the `depends_on` to say that the 1.8 requirement can be lifted come 2.1.6 so that whoever updates it in the future will know.

**Comment by chenrui333** [comment]
Sounds good!

**Comment by chenrui333** [comment]
It does not really quite work.

**Comment by chenrui333** [comment]
Push out for visibility.

**Comment by chenrui333** [comment]
```
WARN : NanoSparqlServer.java:517: Starting NSS
WARN : WebAppContext.java:554: Failed startup of context o.e.j.w.WebAppContext@4b952a2d{/blazegraph,null,UNAVAILABLE}{jar:file:/usr/local/Cellar/blazegraph/2.1.5/libexec/blazegraph.jar!/war}
java.lang.IllegalStateException: Parent for temp dir not configured correctly: writeable=false
```

**Comment by Bo98** [comment]
Probably the sandbox. Try `ENV.prepend "_JAVA_OPTIONS", "-Djava.io.tmpdir=#{testpath}"` in the test block.

**Comment by chenrui333** [comment]
Works for me locally.

**Pull request merged**
