### PR TITLE
couchdb 3.2.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Does this not work with linux or ARM?

**Review by carlocab — COMMENTED** [review]
Not the latest release on the website.

**Comment by carlocab** [comment]
> Does this not work with linux or ARM?

```
❯ brew unbottled --tag=arm64_monterey couchdb
==> Populating dependency tree...
==> :arm64_monterey bottle status
couchdb: unbottled deps: spidermonkey
❯ brew unbottled --tag=arm64_big_sur couchdb
==> Populating dependency tree...
==> :arm64_big_sur bottle status
couchdb: unbottled deps: spidermonkey
❯ brew unbottled --tag=monterey couchdb
==> Populating dependency tree...
==> :monterey bottle status
couchdb: unbottled deps: spidermonkey
❯ brew unbottled --tag=x86_64_linux couchdb
==> Populating dependency tree...
==> :x86_64_linux bottle status
couchdb: requires macOS
```

**Review by SMillerDev — DISMISSED** [review]

**Comment by chenrui333** [comment]
Gonna update livecheck and revisit the PR later.

**Pull request closed without merging**
