### PR TITLE
opus 1.4

### PR DESCRIPTION
**Pull request by mxsrm**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by mxsrm** [comment]
So apparently some of the dependents fail and I have no idea how to fix that.

**Comment by alebcay** [comment]
Linkage audit for `gstreamer` is probably going to remain broken until https://github.com/Homebrew/homebrew-core/pull/132821 is merged.

**Comment by chenrui333** [comment]
only snapcast test failure on 13, LGTM with the merge.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
also failed on HEAD build as well, https://github.com/chenrui333/github-action-test/actions/runs/5207271231/jobs/9394659385

**Review by carlocab — APPROVED** [review]

**Pull request merged**
