### PR TITLE
macosvpn 1.0.1

### PR DESCRIPTION
**Pull request by tiiiecherle**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> xcodebuild SYMROOT=build
Build settings from command line:
    SYMROOT = build

Resolve Package Graph

Fetching https://github.com/jdhealy/PrettyColors.git

Fetching https://github.com/kareman/Moderator.git

xcodebuild: error: Could not resolve package dependencies:
  sandbox-exec: sandbox_apply_container: Operation not permitted
```

**Comment by chenrui333** [comment]
FYI, there is new release now
https://github.com/halo/macosvpn/releases/tag/1.0.1

**Comment by fxcoudert** [comment]
On high Sierra:

```
Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'macosvpn')
```

On Catalina and Mojave:

```
==> /usr/local/Cellar/macosvpn/1.0.1/bin/macosvpn version
Error: macosvpn: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <10> expected but was
<2>.
```

**Comment by halo** [comment]
@fxcoudert You're so fast, if I wouldn't know it better, I'd say you're a bot 😄

**Comment by fxcoudert** [comment]
Thank you @tiiiecherle for your contribution to Homebrew!

**Comment by tiiiecherle** [comment]
@fxcoudert Thank you all for this great project ;)

**Pull request closed without merging**
