### PR TITLE
update gnu-cobol

### PR DESCRIPTION
**Pull request by bastie**
stable release 2.2, also include informations for last version of release 2.0 and 1.1

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
This should be an upgrade to 2.2 without any of the 2.0/1.1 stuff.

**Comment by bastie** [comment]
It can be important to install previous version of a compiler or runtime! What is the best way with homebrew provide more than one version of GNU COBOL?

**Comment by ilovezfs** [comment]
@bastie our policy for versioned formulae is here: https://github.com/Homebrew/brew/blob/master/docs/Versions.md#acceptable-versioned-formulae

>formulae submitted should be expected to be used by a large number of people and still supported by their upstream projects.

Given there were only 140 installs of gnu-cobol in the last 30 days days, older versions won't meet the criterion "expected to be used by a large number of people" so they should be maintained in a third party tap: https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap

**Comment by ilovezfs** [comment]
@bastie feel free to open a fresh pull request when it's just a version upgrade to 2.2.

**Pull request closed without merging**
