### PR TITLE
fn 0.5.96

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
only failed on Catalina
```
==> brew test fn --verbose
==> FAILED
Testing fn
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200317-12383-14eery4.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fn.rb --verbose
==> /usr/local/Cellar/fn/0.5.95/bin/fn --version
==> /usr/local/Cellar/fn/0.5.95/bin/fn init --runtime go --name myfunc
Function boilerplate generated.
func.yaml created.
==> /usr/local/Cellar/fn/0.5.95/bin/fn create app myapp

Fn: Post "http://localhost:60718/v2/apps": net/http: HTTP/1.x transport connection broken: unexpected EOF

See 'fn <command> --help' for more information. Client version: 0.5.95

Error: fn: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.
```

**Comment by chenrui333** [comment]
tested on my catalina machine, working fine
```
$ brew test fn
Testing fn
==> /usr/local/Cellar/fn/0.5.95/bin/fn --version
==> /usr/local/Cellar/fn/0.5.95/bin/fn init --runtime go --name myfunc
==> /usr/local/Cellar/fn/0.5.95/bin/fn create app myapp
```

**Comment by chenrui333** [comment]
Let's see whether CI complains this time.

**Comment by bayandin** [comment]
On Catalina only:

```
==> /usr/local/Cellar/fn/0.5.95/bin/fn --version
==> /usr/local/Cellar/fn/0.5.95/bin/fn init --runtime go --name myfunc
Function boilerplate generated.
func.yaml created.
==> /usr/local/Cellar/fn/0.5.95/bin/fn create app myapp

Fn: read tcp [::1]:63309->[::1]:63306: read: connection reset by peer

See 'fn <command> --help' for more information. Client version: 0.5.95

Error: fn: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.
```

**Comment by chenrui333** [comment]
@bayandin does it work on your machine, it works on my Catalina machine though when I tested last time.

**Comment by bayandin** [comment]
> @bayandin does it work on your machine, it works on my Catalina machine though when I tested last time.

It works as well (on Catalina)

**Comment by chenrui333** [comment]
Let's give another try on the new release.

**Pull request closed without merging**
