### PR TITLE
workflows/publish-commit-bottles: cache gems

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Related: https://github.com/Homebrew/brew/pull/10201

### CODE REVIEW

**Comment by dawidd6** [comment]
No need for caching in automerge workflow. Apart from that, good to merge.

**Comment by SeekingMeaning** [comment]
`Warning: Event Validation Error: The event type workflow_dispatch is not supported. Only push, pull_request events are supported at this time.`

**Comment by dawidd6** [comment]
https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

Maybe we can try v2?

**Comment by SeekingMeaning** [comment]
I was just about to post the same link :stuck_out_tongue: Yes, let's try

**Comment by SeekingMeaning** [comment]
https://github.com/Homebrew/homebrew-core/runs/1639162068
`/bin/tar: ../../../../linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby: Cannot stat: No such file or directory`

**Comment by dawidd6** [comment]
Guess we need to go the vendoring route then...

**Comment by reitermarkus** [comment]
The problem is the same as described here I guess: https://github.com/actions/toolkit/pull/580

Try this? https://github.com/Homebrew/homebrew-cask/blob/master/.github/workflows/ci.yml#L86-L105

**Comment by SeekingMeaning** [comment]
https://github.com/Homebrew/homebrew-core/runs/1640407988#step:28:2

`Unable to reserve cache with key Linux-rubygems-1a4e9d7268b417fa907ef0d7c30c83685669ed85454de05ddd45f03ac95aa191, another job may be creating this cache.`

**Comment by SeekingMeaning** [comment]
https://github.com/Homebrew/homebrew-core/runs/1640476308#step:28:3

`Cache saved successfully`

**Comment by SeekingMeaning** [comment]
List of related commits to `workflows/publish-commit-bottles.yml` for future reference:

- 7d57baa77790e030e1d686c2fc413bd9c75e126c - cache gems
- 4c842d423d011b476174d2449dadcf03ac4f9f23 - use actions/cache@v2
- 6f1da46848e2523606c2fc0c8ca45acdef9a49c8 - add workaround for caching gems
- 1ea2bbc16aff387b9f155b7449243b0775efea8b - add workaround for caching gems (part 2)
- 3b1fd5add8f9d574359db54376d660bbcda98415 - start with new cache

**Comment by SeekingMeaning** [comment]
https://github.com/Homebrew/homebrew-core/runs/1640501478#step:5:12

`Cache restored from key: Linux-rubygems-v2-1a4e9d7268b417fa907ef0d7c30c83685669ed85454de05ddd45f03ac95aa191`

**Comment by dawidd6** [comment]
Great work. The speed is back!

**Pull request merged**
