### PR TITLE
yaegi 0.8.5

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> /usr/local/Cellar/yaegi/0.8.5/bin/yaegi
Error: yaegi: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </4/> was expected to be =~
<"">.
```

**Comment by alebcay** [comment]
Reproduced this issue with upstream's own binaries on macOS and Linux and could not find any documentation that this is intended behavior. Reported upstream at https://github.com/containous/yaegi/issues/636. In the meantime, a solution is  to invoke the CLI tool with a `pty` and pass the input in from there and then observe the result.

**Comment by alebcay** [comment]
Upstream noted that the previous behavior should work again soon, but explicitly specifying `println(...)` is probably good too (and also works with the existing version of `yaegi` as well).

**Comment by chenrui333** [comment]
Thanks @alebcay!!

**Pull request closed without merging**
