### PR TITLE
Add `uses_from_macos` to formulae, part 1 (a-j)

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

c.f. https://github.com/Homebrew/brew/issues/6150

Note that there are many instances in linuxbrew-core where `uses_from_macos` is (I believe) used improperly. For example, `uses_from_macos "python"` is incorrect because macOS does not provide a Python 3 installation. Something to think about for a follow up issue.

I'll open a pull request for part 2 once this is merged.

### CODE REVIEW

**Comment by fxcoudert** [comment]
- First question:

> `uses_from_macos "python@2"`

With macOS Catalina approaching, which contains both Python 2 and 3… what does this mean? Does it mean “uses Python 2 on all macOS versions, even when Python 3 is there?” Something else?

- Second question: I get this is currently a no-op, but is this actually checked / enforced on macOS? Because it could lead to divergences in formulas between the macOS and Linux version.

Imagine formula X has `uses_from_macos "ncurses"`, because it builds with macOS curses. When the next version ships, formula X requires wide-char curses, which macOS does not have. It may fail (and then we see it), or it might build in a degraded mode, without curses — and then we won't see it. And our comment that it depends on curses is not correct anymore.

**Comment by jonchang** [comment]
> > `uses_from_macos "python@2"`
> 
> With macOS Catalina approaching, which contains both Python 2 and 3… what does this mean? Does it mean “uses Python 2 on all macOS versions, even when Python 3 is there?” Something else?

It means, "use system Python 2 on all versions". 

> Second question: I get this is currently a no-op, but is this actually checked / enforced on macOS? Because it could lead to divergences in formulas between the macOS and Linux version.

Yes, I'll write an audit to check for linkages and that sort of thing.

> Imagine formula X has `uses_from_macos "ncurses"`, because it builds with macOS curses. When the next version ships, formula X requires wide-char curses, which macOS does not have. It may fail (and then we see it), or it might build in a degraded mode, without curses — and then we won't see it. And our comment that it depends on curses is not correct anymore.

Then it should be changed to `depends_on "ncurses"` meaning to use brewed `ncurses`.

**Comment by fxcoudert** [comment]
> Then it should be changed to depends_on "ncurses" meaning to use brewed ncurses.

But do we have checks that say “this is not actually used anymore”? If not, these lines will bitrot.

**Comment by jonchang** [comment]
> > Then it should be changed to depends_on "ncurses" meaning to use brewed ncurses.
> 
> But do we have checks that say “this is not actually used anymore”? If not, these lines will bitrot.

Yes, I'll write an audit to check for linkages and that sort of thing. Degraded functionality could be tested via `brew test` if the formula test is writtenw ell.

**Comment by jonchang** [comment]
Audit: https://github.com/Homebrew/brew/pull/6265

**Comment by fxcoudert** [comment]
Thanks @jonchang

**Review by fxcoudert — APPROVED** [review]

**Pull request merged**
