### PR TITLE
python@2 2.7.17

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@bayandin I removed this from the queue, please let Python 3 test run through before we start another one. We have to keep other PRs moving :)

**Comment by bayandin** [comment]
@fxcoudert sure, thanks!

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
20:34:13 ==> brew linkage --test ansible@1.9
20:34:14 ==> FAILED
20:34:14 Broken dependencies:
20:34:14   /usr/local/opt/gmp/lib/libgmp.10.dylib (gmp)
20:34:14 

20:34:57 ==> brew linkage --test ansible@2.0
20:34:59 ==> FAILED
20:34:59 Broken dependencies:
20:34:59   /usr/local/opt/gmp/lib/libgmp.10.dylib (gmp)

20:49:12 ==> brew linkage --test dxpy
20:49:14 ==> FAILED
20:49:14 Broken dependencies:
20:49:14   /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
20:49:14   /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)

21:08:44 ==> brew test --verbose gnome-latex
21:17:46 FATAL: command execution failed
21:17:46 java.nio.channels.ClosedChannelException

**Comment by fxcoudert** [comment]
Testing did not finish, however 😢

**Comment by bayandin** [comment]
Thank you guys, I've pushed fixed for failed formulas:

```bash
# failed before:
brew-test-bot.catalina.linkage --test dxpy
brew-test-bot.mojave.linkage --test ansible@1.9
brew-test-bot.mojave.linkage --test ansible@2.0
brew-test-bot.mojave.linkage --test dxpy
brew-test-bot.high_sierra.linkage --test ansible@1.9
brew-test-bot.high_sierra.linkage --test ansible@2.0
brew-test-bot.high_sierra.linkage --test dxpy
```

**Comment by bayandin** [comment]
It seems everything is ok now

**Review by chenrui333 — APPROVED** [review]

**Comment by fxcoudert** [comment]
Many thanks @bayandin

**Pull request closed without merging**
