### PR TITLE
libelf: fix build for arm.

### PR DESCRIPTION
**Pull request by mahiuchun**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
What's with the gettext dependency? Can we avoid that (and pass `--disable-nls` if needed)?

**Comment by carlocab** [comment]
I think it gets pulled in by the newer `config.{guess,sub}` scripts? I'm not sure if this makes any sense, but I've seen another formula that suddenly needed `gettext` at build time when using these newer scripts.

 I think `--disable-nls` only stops runtime linkage, which isn't what we're worried about here.

**Comment by carlocab** [comment]
Let's bottle this for ARM separately to preserve all the older bottles.

**Review by carlocab — APPROVED** [review]
Thanks, @mahiuchun.

**Comment by fxcoudert** [comment]
> I think it gets pulled in by the newer config.{guess,sub} scripts?

Nope, config.guess/sub definitely don't need gettext. @mahiuchun please explain why that is needed, it wasn't before

**Comment by carlocab** [comment]
Hmm, ok. I merged this too hastily then; apologies. The actions queue doesn't look too long, so I opened this to see if we can drop the dependency: #73105

**Comment by carlocab** [comment]
Looks like it isn't needed.

**Comment by mahiuchun** [comment]
I saw an error with `autopoint` during `autoreconf` which is solved by adding `gettext`.

Fwiw, I was also experimenting new upstream https://sourceware.org/elfutils/ so things could get mixed up.

**Pull request merged**
