### PR TITLE
activemq 5.16.3

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by branchvincent** [comment]
```
==> brew audit activemq --online --git --skip-style
==> FAILED
activemq:
  * Binaries built for a non-native architecture were installed into activemq's prefix.
    The offending files are:
      /opt/homebrew/Cellar/activemq/5.16.3/libexec/bin/macosx/libwrapper.jnilib	(universal)
      /opt/homebrew/Cellar/activemq/5.16.3/libexec/bin/macosx/wrapper	(universal)
Error: 1 problem in 1 formula detected
```

**Comment by carlocab** [comment]
We can probably delete both these files; they're unusable.
```
❯ file libwrapper.jnilib wrapper
libwrapper.jnilib: Mach-O universal binary with 2 architectures: [ppc:Mach-O bundle ppc] [i386:Mach-O bundle i386]
libwrapper.jnilib (for architecture ppc):       Mach-O bundle ppc
libwrapper.jnilib (for architecture i386):      Mach-O bundle i386
wrapper:           Mach-O universal binary with 3 architectures: [ppc_7400:Mach-O executable ppc_7400] [i386:Mach-O executable i386] [x86_64:Mach-O 64-bit executable x86_64]
wrapper (for architecture ppc7400):     Mach-O executable ppc_7400
wrapper (for architecture i386):        Mach-O executable i386
wrapper (for architecture x86_64):      Mach-O 64-bit executable x86_64
```

**Comment by carlocab** [comment]
On Intel:
```
==> FAILED
activemq:
  * Binaries built for a non-native architecture were installed into activemq's prefix.
    The offending files are:
      /usr/local/Cellar/activemq/5.16.3/libexec/bin/macosx/libwrapper.jnilib	(universal)
    Unexpected universal binaries were found.
    The offending files are:
      /usr/local/Cellar/activemq/5.16.3/libexec/bin/macosx/wrapper
Error: 1 problem in 1 formula detected
```

**Comment by alebcay** [comment]
Applied the changes as suggested for now. Ideally there would be a way to build the JNI library from source for Apple Silicon. Hopefully this doesn't break anything.

**Comment by carlocab** [comment]
> Applied the changes as suggested for now. Ideally there would be a way to build the JNI library from source for Apple Silicon. Hopefully this doesn't break anything.

Do you mean the `wrapper`? The JNI library isn't usable on Intel either.

**Comment by alebcay** [comment]
Both, really. I guess whatever functionality the JNI library provides just hasn't been available on macOS for a while.

**Review by SMillerDev — APPROVED** [review]

**Comment by carlocab** [comment]
We might be able to build the wrapper from source following the discussion at #88380.

**Pull request closed without merging**
