### PR TITLE
mpd 0.23.14

### PR DESCRIPTION
**Pull request by Sean-Der**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  /home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: src/decoder/plugins/libdecoder_plugins.a.p/Mpg123DecoderPlugin.cxx.o: in function `mpd_mpg123_open(mpg123_handle_struct*, char const*, AudioFormat&)':
  Mpg123DecoderPlugin.cxx:(.text._ZL15mpd_mpg123_openP20mpg123_handle_structPKcR11AudioFormat+0x22): undefined reference to `mpg123_open_64'
  /home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: src/decoder/plugins/libdecoder_plugins.a.p/Mpg123DecoderPlugin.cxx.o: in function `mpd_mpg123_scan_file(Path, TagHandler&)':
  Mpg123DecoderPlugin.cxx:(.text._ZL20mpd_mpg123_scan_file4PathR10TagHandler+0x84): undefined reference to `mpg123_length_64'
  /home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: src/decoder/plugins/libdecoder_plugins.a.p/Mpg123DecoderPlugin.cxx.o: in function `mpd_mpg123_file_decode(DecoderClient&, Path)':
  Mpg123DecoderPlugin.cxx:(.text._ZL22mpd_mpg123_file_decodeR13DecoderClient4Path+0x7a): undefined reference to `mpg123_length_64'
  /home/linuxbrew/.linuxbrew/opt/binutils/bin/ld: Mpg123DecoderPlugin.cxx:(.text._ZL22mpd_mpg123_file_decodeR13DecoderClient4Path+0x4e2): undefined reference to `mpg123_seek_64'
  collect2: error: ld returned 1 exit status
```

**Comment by manxorist** [comment]
The failure looks like it would be fixed by mpg123 1.32.3. See <https://github.com/Homebrew/homebrew-core/pull/146321>.

**Comment by Sean-Der** [comment]
@manxorist @chenrui333 Are you able to re-run CI?

mpg123 was merged, hopefully this fixes build?

**Comment by chenrui333** [comment]
#151236

**Pull request closed without merging**
