### PR TITLE
kubernetes-cli 1.20.5

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Do we still need the patch?

**Comment by derrabus** [comment]
The patch is this commit, right? https://github.com/kubernetes/kubernetes/commit/f719624654c68d143cad4e4af2f21cca0bfde8fd

Looks like it was merged into the 1.21 branch of Kubernetes only, so we still need it until 1.21 is released.

**Comment by carlocab** [comment]
On Big Sur:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12a3f18]
```

**Comment by carlocab** [comment]
Big Sur failure didn't go away on a re-run. Which is odd, given that it worked on the ARM runner, which is also on Big Sur.

**Comment by derrabus** [comment]
Yeah. Sorry, I can't do more about it. 🙁 

If someone with more experience in compiling Kubernetes wants to take over, please do so.

**Comment by billinghamj** [comment]
May be sensible to close in favour of #74832 now

**Comment by carlocab** [comment]
Thanks, @billinghamj, @derrabus.

**Comment by derrabus** [comment]
Thank you for taking over, @billinghamj!

**Pull request closed without merging**
