### PR TITLE
rust 1.15.0

### PR DESCRIPTION
**Pull request by mrageh**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Neither racer nor cargo bootstrap have been updated.

**Comment by ilovezfs** [comment]
I've updated the cargo bootstrap and the racer version in the PR. Note that the revision for the cargo bootstrap is found in https://github.com/rust-lang/rust/blob/1.15.0/src/stage0.txt

**Comment by ilovezfs** [comment]
@mrageh thanks for your contribution to Homebrew!

**Comment by fukamachi** [comment]
Is the SHA256 for rustc tarball correct?

```
brew install --with-racer rust
==> Using the sandbox
==> Downloading https://static.rust-lang.org/dist/rustc-1.15.0-src.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 33f3747d231ede34b56c6cc0ae6be8cbaa29d2fdb39d86f25693dceb9fc5f164
Actual: f655e4fac9c2abb93eb579e29c408e46052c0e74b7655cd222c63c6743457673
Archive: /Users/nitro_idiot/Library/Caches/Homebrew/rust-1.15.0.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by JCount** [comment]
@fukamachi They appear to have re-uploaded/modified the source tarball today, which is a bit troubling. I will try and look into this.

**Comment by JCount** [comment]
CC alexcrichton Any idea what might have happened here?

**Comment by alexcrichton** [comment]
@JCount we've been having some infrastructure hiccups unfortunately and we think we may have accidentally overwritten some artifacts. Sorry if that's causing any problems! I can confirm though that f655e4fac9c2abb93eb579e29c408e46052c0e74b7655cd222c63c6743457673 is now the current correct sha256 of the source tarball.

**Comment by JCount** [comment]
@alexcrichton Thank you for the clarification!

**Comment by brson** [comment]
As an update, for now we are not planning on taking any actions to correct this mistake. The source tarball for 1.15.0 will remain as it is now, after the re-publication. I'm sorry for the trouble, please contact me or @alexcrichton if this turns out to be a problem.

**Pull request closed without merging**
