### PR TITLE
texlab 5.4.1

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Comment by p-linnane** [comment]
@ZhongRuoyu The bottle commit was pushed here, but then it attempted to rebuild all the bottles again. Could this be related to the workflow change we just made?

**Comment by ZhongRuoyu** [comment]
Strangely, https://github.com/Homebrew/homebrew-core/labels/CI-published-bottle-commits wasn't there.

**Comment by ZhongRuoyu** [comment]
https://github.com/Homebrew/homebrew-core/actions/runs/4526568273/jobs/7971828893#step:16:14

`non-200 OK status code: 502 Bad Gateway body: "{\n   \"data\": null,\n   \"errors\":[\n      {\n         \"message\":\"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `E4C0:5A88:54C6374:5796BDE:6420B20B` when reporting this issue.\"\n      }\n   ]\n}\n"`

**Comment by ZhongRuoyu** [comment]
I *think* it's the first time we encountered this, so I'm attributing it to a transient GitHub issue. If we see this one more time, I think we may want to implement a retry mechanism for PR labelling. It's weird if we have to do this.

**Pull request merged**
