### PR TITLE
swiftlint 0.43.1

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks for opening this PR @chenrui333! Is this an automation? I usually create these PRs manually as part of my release process: https://github.com/realm/SwiftLint/blob/0.43.1/Releasing.md

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
@jpsim

Yes, @chenrui333 has automated these PRs for many formulae. You can set up your own automation as a GitHub workflow (it can be triggered when new releases are tagged, for example) using

https://github.com/dawidd6/action-homebrew-bump-formula

In principle, this shouldn't generate duplicate PRs. (It sometimes does because GitHub's API for querying open PRs isn't always up-to-date.)

**Comment by jpsim** [comment]
If someone else already has this automated, I'm happy to defer to that! Only issue is if that integration stops working, I'd like to be notified.

**Comment by carlocab** [comment]
@chenrui333 has this automated for a large number of formulae, so it's unlikely they'll notice it stops working for `swiftlint`. You're probably better off adding your own workflow -- it's less than a dozen lines in a `workflow.yml`. But it's up to you.

**Pull request closed without merging**
