### PR TITLE
asdf 0.7.0

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Tests are failing

**Comment by fxcoudert** [comment]
It's an install failure, actually:

```
Error: An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
/usr/local/Cellar/asdf/0.7.0/lib/commands/reshim.sh:
  expected replacement of "exec $(asdf_dir)/bin/private/asdf-exec " with "exec $(asdf_dir)/libexec/private/asdf-exec "
```

Let's please copy the main error message into the PR when we label failures, so it's recorded for posterity (Jenkins cleans up after a few days).

**Comment by vraravam** [comment]
This breaks asdf java for version oracle-8.141 - please revert/fix!

**Comment by fxcoudert** [comment]
@vraravam please report the bug, filling the full template, at: https://github.com/Homebrew/homebrew-core/issues

**Comment by vraravam** [comment]
@fxcoudert - sorry, i think the bug is on either `asdf` or its plugin - not in homebrew. Thanks!

**Pull request merged**
