### PR TITLE
Adding new formula nifi-registry for Apache NiFi Registry 0.1.0

### PR DESCRIPTION
**Pull request by apiri**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by apiri** [comment]
Please let me know if anything else is needed to be considered for merging.

**Review by fxcoudert — CHANGES_REQUESTED** [review]

**Comment by ilovezfs** [comment]
@apiri gentle ping on this

**Comment by apiri** [comment]
@fxcoudert @ilovezfs Sorry! These messages must have gotten mixed in with other notifications.  Will look to address these shortly.  Thanks for scoping out

**Comment by apiri** [comment]
@fxcoudert I removed the .bat files and also provided a matching of the output for formula test.  I did not update to remove the renaming of nifi-registry.sh => nifi-registry as this does not align with the work that had been done for the nifi formula which many in the Apache NiFi community have made use of.  If leaving the item as .sh is Homebrew policy I can make the change but was striving for consistency for our user's.  Let me know your thoughts and thanks for your time!

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
`/usr/local/Cellar/nifi-registry/0.1.0/bin/nifi-registry: line 46: /usr/local/Cellar/nifi-registry/0.1.0/bin/nifi-registry-env.sh: No such file or directory`

**Comment by fxcoudert** [comment]
Thanks @apiri again for your contribution to Homebrew!

**Pull request merged**
