### PR TITLE
libxml2: enable ICU support

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by danielnachun** [comment]
This is needed for https://github.com/Homebrew/homebrew-core/pull/103229, where the system `libxml2` can only be used if it includes ICU support.  Building `libxml2` with ICU support seems to be norm in Linux, given that both Arch Linux (https://archlinux.org/packages/core/x86_64/libxml2) and Debian (https://packages.debian.org/bullseye/libxml2) build it this way.

**Comment by iMichka** [comment]
The CI queue is full and we already have enough long builds. I think a run without reverse dependencies testing is fine.

I rev-bumped the formula because we need to make sure the updated formula with ICU is shipped to our users.

**Comment by danielnachun** [comment]
I was going to ask if we were okay with shipping this without dependent checks, as it's not a version bump, just a revision bump.  This should be pretty quick to test now!

**Comment by rouault** [comment]
Hello, this update breaks builds that rely on pkg-config --cflags. libxml-2.0.pc should incorporate the include path to ICU

**Pull request closed without merging**
