### PR TITLE
isl 0.19

### PR DESCRIPTION
**Pull request by commitay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Revision bumps needed for `mingw-w64`, `cloog`, `gcc@6`, and `gcc`.

**Comment by fxcoudert** [comment]
- The octave formula needs to be revision bumped for gcc.
- `pdal` failure seems random
- `cloog` fails because ISL [dropped the deprecated `isl_set_copy_basic_set`](https://groups.google.com/forum/#!topic/isl-development/JPK0aXJ33No), and cloog relies on it (and has not been updated in three years)

**Comment by fxcoudert** [comment]
For cloog, we could possibly build with the bundled ISL.

**Comment by commitay** [comment]
`--with-isl=bundled`

```
Linking /usr/local/Cellar/cloog/0.18.4_3...
Error: Could not symlink include/isl/aff.h
Target /usr/local/include/isl/aff.h
is a symlink belonging to isl. You can unlink it:
  brew unlink isl
```
```
$ brew link --overwrite --dry-run cloog
Would remove:
/usr/local/include/isl/aff.h
/usr/local/include/isl/aff_type.h
/usr/local/include/isl/arg.h
/usr/local/include/isl/ast.h
/usr/local/include/isl/ast_build.h
/usr/local/include/isl/ast_type.h
/usr/local/include/isl/constraint.h
/usr/local/include/isl/ctx.h
/usr/local/include/isl/flow.h
/usr/local/include/isl/hash.h
/usr/local/include/isl/hmap.h
/usr/local/include/isl/hmap_templ.c
/usr/local/include/isl/id.h
/usr/local/include/isl/id_to_ast_expr.h
/usr/local/include/isl/id_to_id.h
/usr/local/include/isl/id_to_pw_aff.h
/usr/local/include/isl/ilp.h
/usr/local/include/isl/list.h
/usr/local/include/isl/local_space.h
/usr/local/include/isl/lp.h
/usr/local/include/isl/map.h
/usr/local/include/isl/map_to_basic_set.h
/usr/local/include/isl/map_type.h
/usr/local/include/isl/mat.h
/usr/local/include/isl/maybe.h
/usr/local/include/isl/maybe_ast_expr.h
/usr/local/include/isl/maybe_basic_set.h
/usr/local/include/isl/maybe_id.h
/usr/local/include/isl/maybe_pw_aff.h
/usr/local/include/isl/maybe_templ.h
/usr/local/include/isl/multi.h
/usr/local/include/isl/obj.h
/usr/local/include/isl/options.h
/usr/local/include/isl/point.h
/usr/local/include/isl/polynomial.h
/usr/local/include/isl/polynomial_type.h
/usr/local/include/isl/printer.h
/usr/local/include/isl/printer_type.h
/usr/local/include/isl/schedule.h
/usr/local/include/isl/schedule_node.h
/usr/local/include/isl/schedule_type.h
/usr/local/include/isl/set.h
/usr/local/include/isl/set_type.h
/usr/local/include/isl/space.h
/usr/local/include/isl/stdint.h
/usr/local/include/isl/stream.h
/usr/local/include/isl/union_map.h
/usr/local/include/isl/union_map_type.h
/usr/local/include/isl/union_set.h
/usr/local/include/isl/union_set_type.h
/usr/local/include/isl/val.h
/usr/local/include/isl/val_gmp.h
/usr/local/include/isl/vec.h
/usr/local/include/isl/version.h
/usr/local/include/isl/vertices.h
/usr/local/include/isl/aff.h
/usr/local/include/isl/aff_type.h
/usr/local/include/isl/arg.h
/usr/local/include/isl/ast.h
/usr/local/include/isl/ast_build.h
/usr/local/include/isl/ast_type.h
/usr/local/include/isl/constraint.h
/usr/local/include/isl/ctx.h
/usr/local/include/isl/flow.h
/usr/local/include/isl/hash.h
/usr/local/include/isl/hmap.h
/usr/local/include/isl/id.h
/usr/local/include/isl/id_to_ast_expr.h
/usr/local/include/isl/id_to_pw_aff.h
/usr/local/include/isl/ilp.h
/usr/local/include/isl/list.h
/usr/local/include/isl/local_space.h
/usr/local/include/isl/lp.h
/usr/local/include/isl/map.h
/usr/local/include/isl/map_to_basic_set.h
/usr/local/include/isl/map_type.h
/usr/local/include/isl/mat.h
/usr/local/include/isl/multi.h
/usr/local/include/isl/obj.h
/usr/local/include/isl/options.h
/usr/local/include/isl/point.h
/usr/local/include/isl/polynomial.h
/usr/local/include/isl/polynomial_type.h
/usr/local/include/isl/printer.h
/usr/local/include/isl/schedule.h
/usr/local/include/isl/schedule_node.h
/usr/local/include/isl/schedule_type.h
/usr/local/include/isl/set.h
/usr/local/include/isl/set_type.h
/usr/local/include/isl/space.h
/usr/local/include/isl/stdint.h
/usr/local/include/isl/stream.h
/usr/local/include/isl/union_map.h
/usr/local/include/isl/union_map_type.h
/usr/local/include/isl/union_set.h
/usr/local/include/isl/union_set_type.h
/usr/local/include/isl/val.h
/usr/local/include/isl/val_gmp.h
/usr/local/include/isl/vec.h
/usr/local/include/isl/version.h
/usr/local/include/isl/vertices.h
/usr/local/lib/libisl.a -> /usr/local/Cellar/isl/0.19/lib/libisl.a
/usr/local/lib/libisl.dylib -> /usr/local/Cellar/isl/0.19/lib/libisl.dylib
/usr/local/lib/pkgconfig/isl.pc -> /usr/local/Cellar/isl/0.19/lib/pkgconfig/isl.pc
```

**Comment by fxcoudert** [comment]
We should report to cloog, and if they don't move, submit a patch to them.

Basically calls to `isl_set_copy_basic_set(x)` should be replaced with `bset_from_bmap(map_copy_basic_map(set_to_map(x)))`

**Comment by fxcoudert** [comment]
There's a cloog repo on github, which seems to be active… wonder if it's the same upstream: https://github.com/periscop/cloog/issues/37

And the issue was reported there: https://github.com/periscop/cloog/issues/37

**Comment by commitay** [comment]
I've asked the `cloog` dev mailinglist if https://github.com/periscop/cloog is official. 
They have a `0.18.5` tag and an `isl 0.19` patch that applies cleanly to that tag.
___
Is vendoring `isl 0.18` into `cloog` an option for now pending a response from upstream or is it better to patch it to work with `0.19`?

**Comment by fxcoudert** [comment]
cloog vendors its own isl by default, so if we (temporarily) remove the `--with-isl=system` it will use that.

**Comment by commitay** [comment]
`caffe` test failure looks random and passes later in the build.

**Comment by harenome** [comment]
Hello, was this resolved? Does the [latest CLooG release](https://github.com/periscop/cloog/releases/tag/cloog-0.19.0) solve your problems?

**Comment by commitay** [comment]
@harenome Is https://github.com/periscop/cloog now the upstream repo? 

https://www.bastoul.net/cloog/ hasn't been updated since `0.18.4` and doesn't link to the GitHub repo.

I asked the [dev mailing list](https://groups.google.com/forum/?hl=en#!topic/cloog-development/k7Ge_7v7yy8) a couple of weeks ago but haven't had a response yet.

**Comment by harenome** [comment]
@commitay yes this is the upstream repository

**Comment by ilovezfs** [comment]
@harenome why does https://www.bastoul.net/cloog/download.php show 0.18.4 and http://repo.or.cz/w/cloog.git ? Can it be updated to show 0.19.0 and https://github.com/periscop/cloog ?

**Pull request closed without merging**
