### PR TITLE
wireguard-tools 0.0.20180613

### PR DESCRIPTION
**Pull request by Tigger2014**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Tigger2014** [comment]
@zx2c4 It appears that

**Comment by Tigger2014** [comment]
@zx2c4 getentropy is not available on osx pre 10.12

Undefined symbols for architecture x86_64:
  "_getentropy", referenced from:
      _genkey_main in genkey.o
ld: symbol(s) not found for architecture x86_64

**Comment by zx2c4** [comment]
Yikes, thanks for letting me know. This patch will fix it:

https://git.zx2c4.com/WireGuard/patch/?id=9e5de8e95b24350479a962823c5e932236ee70d7

It will be part of the next snapshot, but you can temporarily patch this one for now.

**Comment by Tigger2014** [comment]
@zx2c4 a bit new to homebrew, i think the patch is done correctly, let me know if you think otherwise

**Comment by zx2c4** [comment]
Looks good, though you might want to include a comment that this should be removed post-20180613.

**Comment by Tigger2014** [comment]
@zx2c4  this failed to build still, if you can work out why ill add the next patch and add a comment at the same time
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/25830/version=el_capitan/testReport/brew-test-bot/el_capitan/install_wireguard_tools/

**Comment by Tigger2014** [comment]
sorted :+1:

**Comment by zx2c4** [comment]
:+1:

**Comment by ilovezfs** [comment]
Thanks again @Tigger2014! Note that the patch needed to be in a `stable do` block since it's already in head.

**Pull request closed without merging**
