### PR TITLE
gegl 0.4.14

### PR DESCRIPTION
**Pull request by alebcay**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
```
gegl-config.c:247:30: error: use of undeclared identifier '_SC_AVPHYS_PAGES'
    mem_available = sysconf (_SC_AVPHYS_PAGES) * sysconf (_SC_PAGESIZE);
```

**Comment by alebcay** [comment]
It looks like `_SC_AVPHYS_PAGES` is only usable on Linux, Solaris, and Cygwin. We may try `HW_USERMEM` or something like that as the equivalent, but this seems to be something upstream that's caused by an actual coding issue, not just a build/configuration error.

It can probably be patched, but its a bit outside of my wheelhouse at the moment. I'll see if I can get around to it after final exams.

**Comment by alebcay** [comment]
It turns out that `gegl` does implement platform-specific memory management/detection code. For some reason, we just happen to be triggering the Linux branch of the code. Can probably be fixed with defining an environment variable or passing a variable, etc.

**Comment by alebcay** [comment]
`gegl`'s platform-specific memory management/detection code mistakenly did not support macOS in 0.4.14. Patches fixing that are available upstream, so including them as `patch`es for now, to be removed in next release.

**Pull request closed without merging**
