### PR TITLE
glog 0.5.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
The patch had been merged upstream so I removed it. For the build, I followed upstream's readme.

**Comment by carlocab** [comment]
ARM, Big Sur, Catalina

```
Error: 6 failed steps!
brew test --retry --verbose ceres-solver
brew test --retry --verbose fizz
brew test --retry --verbose folly
brew test --retry --verbose opencv
brew test --retry --verbose opencv@3
brew test --retry --verbose wangle
```

Mojave

```
Error: 4 failed steps!
brew test --retry --verbose caffe
brew test --retry --verbose ceres-solver
brew test --retry --verbose opencv
brew test --retry --verbose opencv@3
```

**Comment by cho-m** [comment]
OpenCV still failing after revision bump:
```
Error: 2 failed steps!
brew test --retry --verbose opencv
brew test --retry --verbose opencv@3
```

Error while testing Python bindings:
```make
==> /opt/homebrew/opt/python@3.9/bin/python3 -c 'import cv2; print(cv2.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/cv2/__init__.py", line 102, in <module>
    bootstrap()
  File "/opt/homebrew/lib/python3.9/site-packages/cv2/__init__.py", line 90, in bootstrap
    import cv2
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/cv2/python-3.9/cv2.cpython-39-darwin.so, 2): Symbol not found: __ZN6google21kLogSiteUninitializedE
  Referenced from: /opt/homebrew/Cellar/opencv/4.5.2_1/lib/libopencv_sfm.4.5.dylib
  Expected in: /opt/homebrew/opt/glog/lib/libglog.0.dylib
 in /opt/homebrew/Cellar/opencv/4.5.2_1/lib/libopencv_sfm.4.5.dylib
```

**Review by bayandin — APPROVED** [review]

**Comment by carlocab** [comment]
Wait, where did all the failures go 😄

**Pull request closed without merging**
