### PR TITLE
llvm lld flang 19.1.1

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

- **llvm 19.1.1**
- **lld 19.1.1**
- **flang 19.1.1**

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]

**Comment by cho-m** [comment]
Based on https://github.com/orgs/Homebrew/discussions/5631, we probably should disable EH:
https://github.com/Homebrew/homebrew-core/blob/77f65298ec57b87241038503aabc6dfd1ead0497/Formula/l/llvm.rb#L111

This is how other repositories that ship `flang` build `llvm`. We are doing a bit of a hack by setting `-D LLVM_ENABLE_EH=OFF` which gets overridden when running `find_package(LLVM ...)`

**Comment by carlocab** [comment]
I'd just follow what Fedora are doing. LLVM's [lead maintainer](https://discourse.llvm.org/t/rfc-proposing-a-new-lead-maintainer-for-llvm/81290?u=carlocab) and one (out of two) of the LLVM release managers maintain the Fedora packages.

**Comment by cho-m** [comment]
Actually my comment was wrong and Fedora does disable. I confirmed by downloading RPM[^1][^2] and checking LLVMConfig.cmake
```cmake
set(LLVM_ENABLE_ASSERTIONS OFF)

set(LLVM_ENABLE_EH OFF)

set(LLVM_ENABLE_FFI TRUE)
if(LLVM_ENABLE_FFI)
  find_package(FFI)
endif()

set(LLVM_ENABLE_RTTI ON)
```

[^1]: https://koji.fedoraproject.org/koji/buildinfo?buildID=2549315
[^2]: https://kojipkgs.fedoraproject.org//packages/llvm/19.1.0/1.fc42/aarch64/llvm-devel-19.1.0-1.fc42.aarch64.rpm

**Comment by carlocab** [comment]
That's weird, since their spec files show `LLVM_ENABLE_EH=ON`:

https://src.fedoraproject.org/rpms/llvm/blob/3b5b15045a8c9449d53582df0842c21465e99e4f/f/build.spec.inc#_70
https://src.fedoraproject.org/rpms/llvm/blob/3b5b15045a8c9449d53582df0842c21465e99e4f/f/build.spec.inc#_241

Probably worth investigating further.

**Comment by cho-m** [comment]
> That's weird, since their spec files show `LLVM_ENABLE_EH=ON`:

Looks like it may be arch-specific. x86_64 rpm does have it enabled:
```
set(LLVM_ENABLE_ASSERTIONS OFF)

set(LLVM_ENABLE_EH ON)

set(LLVM_ENABLE_FFI TRUE)
if(LLVM_ENABLE_FFI)
  find_package(FFI)
endif()

set(LLVM_ENABLE_RTTI ON)
```

Anyway, I think the upstream CMake check (https://github.com/llvm/llvm-project/commit/f7e58c91587be78e80abb7f650dcb5c0b4205730) wasn't tested on Standalone mode which is why it currently works.

There should probably be a caveat as CMake LLVMFlang can't handle our `flang` which is usually a bad sign.

**Comment by carlocab** [comment]
We could just create a wrapper script that always adds `-l[std]c++` 🤷

Setting `LLVM_ENABLE_EH` could be a big change. Probably worth opening an issue/discussion for feedback, plus a note in `caveats` linking to the issue/discussion. Then if no one complains we can set it to `OFF` for LLVM 20.

CC @Bo98 for thoughts.

**Comment by Bo98** [comment]
> Setting LLVM_ENABLE_EH could be a big change.

It can affect ABI at least. Though I also agree we should try disable it & RTTI.

LLVM 20 is definitely a good time to make changes. Somewhat relatedly: perhaps worth considering if libcxx probably should be split to a separate formula. We've had regular bug reports about it since the LLVM C++ headers got prioritised again.

**Comment by carlocab** [comment]
> Or perhaps a config file next to it (when installed in `libexec`) that isn't linked to `bin`.

Testing creating a `libexec/"bin/flang.cfg"` that contains only `-lc++`. Seems to work. Will add it in a follow-up, plus some caveats.

**Review by cho-m — APPROVED** [review]

**Comment by carlocab** [comment]
`afl++` bakes in Cellar paths. Will have a fix separately.

**Pull request merged**
