### PR TITLE
docker-completion: update upstream source

### PR DESCRIPTION
**Pull request by kevinhwang**
https://github.com/docker/docker-ce is deprecated.

Unsure how to update the bottle stanzas though...

### CODE REVIEW

**Comment by carlocab** [comment]
You can ignore the bottle stanza. The install method needs updating, though.

**Comment by kevinhwang** [comment]
Gotcha, I updated them using https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker.rb as a reference.

**Comment by carlocab** [comment]
Thanks, could you squash your commits please? ([Doc ref](https://docs.brew.sh/Formula-Cookbook#push))

**Comment by kevinhwang** [comment]
Ah oops somehow messed up the branch by doing a shallow clone (I made the edits on github.com) of my fork and then fixupping and then pushing. Will reopen a new PR.

**Pull request closed without merging**
