### PR TITLE
consul-backinator 1.6.4

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
vendor/github.com/hashicorp/go-discover/provider/azure/azure_discover.go:66:39: azure.PublicCloud.OAuthConfigForTenant undefined (type azure.Environment has no field or method OAuthConfigForTenant)
vendor/github.com/hashicorp/go-discover/provider/azure/azure_discover.go:72:14: undefined: azure.NewServicePrincipalToken
```

**Comment by ilovezfs** [comment]
@leprechau it looks like we're still having a problem here. https://gist.github.com/ilovezfs/9bc3e1356f4df2ee07c122d2a96008a4

**Comment by leprechau** [comment]
@ilovezfs Yes, I just had time to troubleshoot this late last night.  It has to do with how I was calling `glide` in the formula vs my normal build process.  In the formula I am calling `glide install -v` whereas in my build script used to push releases I am just doing a `glide install`.  In short the `-v` strips nested vendor directories which results in a failed build in the `go-discover` package.  I have fixed this in my fork and will submit a new PR with the update.

**Comment by ilovezfs** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/24966

**Pull request closed without merging**
