### PR TITLE
swiftformat 0.40.7

### PR DESCRIPTION
**Pull request by nicklockwood**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
This is failing on Sierra (with Xcode 9.2) but not giving any output:

```
==> xcodebuild -project SwiftFormat.xcodeproj -scheme SwiftFormat (Command Line Tool) CODE_SIGN_IDENTITY= SYMROOT=build OBJROOT=build
```

**Comment by nicklockwood** [comment]
@fxcoudert welp. I can't reproduce this issue on Travis, so I think my only option is to drop Sierra support 😔

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Now it states
```
07:07:54 ==> brew uses --recursive swiftformat
07:08:26 ==> SKIPPING: swiftformat
07:08:26 A full installation of Xcode.app 9.3 is required to compile
07:08:26 this software. Installing just the Command Line Tools is not sufficient.
07:08:26 
07:08:26 Xcode 9.3 cannot be installed on macOS 10.12.
07:08:26 You must upgrade your version of macOS.
```

**Comment by nicklockwood** [comment]
@javian how can I indicate in the formula that 10.12 is explicitly not supported?

**Comment by fxcoudert** [comment]
@nicklockwood you can't. It's the latest version and the probably the most-used one, so if it's not supported we simply would not consider the formula in Homebrew core.

**Comment by nicklockwood** [comment]
@fxcoudert um, the latest version of macOS is 10.14 (Mojave) not 10.12 (Sierra).

**Comment by MikeMcQuaid** [comment]
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @nicklockwood!

**Pull request closed without merging**
