### PR TITLE
bdsup2sub: fix for java9 and broken deps

### PR DESCRIPTION
**Pull request by CamJN**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
should we revision bump?

**Comment by CamJN** [comment]
What are the rules there again? I think that previous installs should continue to work, but since I don't have my old one anymore I can't test that theory.

**Comment by ilovezfs** [comment]
If previous installs are fine then we can leave it.

**Comment by ilovezfs** [comment]
Thanks @CamJN!

**Pull request closed without merging**
