### PR TITLE
Juju 2.6.9

### PR DESCRIPTION
**Pull request by achilleasa**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
13:45:06 ==> /usr/local/Cellar/juju/2.6.9/bin/juju version
13:45:06 panic: cannot determine host series: unknown series ""
13:45:06 
13:45:06 goroutine 1 [running]:
13:45:06 github.com/juju/juju/vendor/github.com/juju/os/series.mustHostSeries(0x2540be400, 0x74aa4a0)
13:45:06 	/private/tmp/juju-20191003-43039-1k81yrt/juju-core_2.6.9/src/github.com/juju/juju/vendor/github.com/juju/os/series/series.go:50 +0x65
13:45:06 github.com/juju/juju/api.init()
13:45:06 	/private/tmp/juju-20191003-43039-1k81yrt/juju-core_2.6.9/src/github.com/juju/juju/api/certpool.go:19 +0x17f
13:45:06 Error: juju: failed
13:45:06 Failed executing:

**Comment by chenrui333** [comment]
Thanks @achilleasa for your contribution to Homebrew! :tada: 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
