### PR TITLE
sonobuoy 0.14.3

### PR DESCRIPTION
**Pull request by sc250024**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sc250024** [comment]
For some reason, Heptio deleted the `v0.14.3` tag. They even did a version bump here: https://github.com/heptio/sonobuoy/commit/439de5ff69f073598001165832920739b3cf1c61. Waiting for this to get re-released.

**Comment by sc250024** [comment]
@BrewTestBot Test this please

**Comment by johnSchnake** [comment]
Hi, thanks for your work on putting Sonobuoy into Homebrew!

However, we have run into an issue that is described  here: https://github.com/heptio/sonobuoy/issues/715 

Is there a way for you to set up the homebrew recipe to just download our release binaries from github? Otherwise you need to modify the build to match ours and also make sure that always stays in sync. It seems preferable to simply rely on our canonical builds.

**Comment by sc250024** [comment]
@fxcoudert What do you think about @johnSchnake 's comment? I know I've asked you about that before, and from what you said, Homebrew always prefers to build from source.

**Comment by SMillerDev** [comment]
Binary releases are not allowed in homebrew-core. If upstream could provide something like a makefile it might be easier to keep the builds in sync.

**Comment by sc250024** [comment]
@SMillerDev Thanks for the feedback, appreciate it!

@johnSchnake Does that work for you? I guess it would be `make build_sonobuoy` right?

**Comment by johnSchnake** [comment]
Yes, we have a makefile but it does use docker by default. @zubron can probably add a non-docker make target which would enable this and prevent drift (as opposed to modifying the build flags here) Would that work?

**Comment by SMillerDev** [comment]
A non-docker makefile would be great, it might not seem like it but homebrew prefers to let upstream ~~do the heavy lifting~~ define how to install their software 😁

**Comment by sc250024** [comment]
@johnSchnake `make brew` ?

**Comment by fxcoudert** [comment]
Merging while the discussion continues…

**Pull request closed without merging**
