### PR TITLE
node@14 14.21.1

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by derrabus** [comment]
The error message says:

> OpenSearch Dashboards was built with v14.20.0 and does not support the current Node.js version v14.21.0. Please use Node.js v14.20.0 or a higher patch version.

Is there something I can do about that? Or can we ignore that error and bump `opensearch-dashboards` after this PR has been merged?

**Comment by SMillerDev** [comment]
Can you raise this upstream? We can probably ignore it, but it'd be good to check.

**Comment by derrabus** [comment]
> Can you raise this upstream?

I wouldn't know what to ask for, tbh. The issue is that the `opensearch-dashboards` formula has a build step and during the build the exact node version the build is run with is saved. Since the bottle has been built with an older `node@14` binary, we get this error.

Rebuilding the package from source after building `node@14` 14.21.0 solved the issue locally. I've pushed a revision bump for this package.

Is there a way I can force a rebuild of `opensearch-dashboards` bottles whenever `node@14` is bumped?

**Comment by SMillerDev** [comment]
Ah, the situation is different than I expected. Might be good to ask upstream not to pin to a minor version then. Or pin to a minor version in their code, instead of on compiling. Currently it doesn't mean much since a rebuild will change it.

**Comment by derrabus** [comment]
PR updated for node 14.21.1.

**Comment by cho-m** [comment]
[ArchLinux https://github.com/archlinux/svntogit-community/blob/packages/opensearch-dashboards/trunk/PKGBUILD#L54](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2088)

**Comment by derrabus** [comment]
CI is green. Can we please merge? 🙏🏻

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
