### PR TITLE
Remove borg

### PR DESCRIPTION
**Pull request by iwittkau**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
-----

- ok-borg/borg is currently unmaintained, its backend is down, and users won't be able to use it without self-hosting a backend.
- It blocks updating the go formula (#47510) which contains [security fixes](https://golang.org/doc/devel/release.html#go1.13.minor).
- the borg formula contains deprecated fields which makes an easy fix more complicated

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]
lgtm

**Comment by chenrui333** [comment]
We might also want file a upstream issue for communications.

**Comment by iwittkau** [comment]
@chenrui333 done: https://github.com/ok-borg/borg/issues/67

**Comment by chenrui333** [comment]
Thanks @iwittkau for your contribution!!

**Pull request merged**
