### PR TITLE
szip: remove

### LINKED ISSUE #96930: szip formula should be removed
The szip has a license that appears to not be fully open source: https://support.hdfgroup.org/doc_resource/SZIP/Commercial_szip.html.

There is now an open-source replacement however: libaec. We already ship it so we should migrate away form szip as soon as possible.

---

Progress:
- [x] The two formulae have `conflicts_with` so we should probably think about handling that before any migration or users will get errors on upgrading. - #96933
- [x] Migrating dependents:
    - [x] hdf5@1.10 - #96928
    - [x] hdf5@1.8 - #96942
    - [x] hdf5 / hdf5-mpi - #97666
      - alembic
      - alpscore
      - armadillo
      - caffe
      - cdo
      - cgns
      - vtk
      - vtk@8.2
- [x] Remove `szip` - #98261

### PR DESCRIPTION
**Pull request by cho-m**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Alternatively, can directly remove given https://docs.brew.sh/Deprecating-Disabling-and-Removing-Formulae#removal
> A formula should be removed if it does not meet our criteria for [acceptable formulae](https://docs.brew.sh/Acceptable-Formulae) or [versioned formulae](https://docs.brew.sh/Versions), has a **non-open-source license**, or has been disabled for over a year.

Since `szip` to `libaec` migration was just merged, wasn't sure how well `brew upgrade` would handle disable vs removal.

Closes #96930

### CODE REVIEW

**Comment by Bo98** [comment]
> Since `szip` to `libaec` migration was just merged, wasn't sure how well `brew upgrade` would handle disable vs removal.

If everything is migrated, it shouldn't even be looking at the `szip` formula so it should be fine. We removed pdflib-lite recently without any complaints.

Alternatively if there's full compatibility between the two (compare the installed files first), then merging is a possibility via formula_renames.json.

**Comment by cho-m** [comment]
That's fine then.

I mainly wasn't sure how well information on removed formula is seen by users. In case of disabled/deprecated, they show up in `brew doctor`.

**Comment by Bo98** [comment]
https://github.com/Homebrew/brew/blob/b2b029e311ca64b77635e5ea2478fd2b5a32e656/Library/Homebrew/diagnostic.rb#L883-L907

**Comment by carlocab** [comment]
Let's do a formula rename or add an alias. That would be much nicer for existing users, especially since libaec is a drop-in replacement (right?)

**Comment by Bo98** [comment]
Only thing I'm not sure is how migration works for what might appear as a version downgrade 2.1.1 -> 1.0.6.

**Comment by cho-m** [comment]
Upgrade at least works, but info output shows multiple installs afterward and `szip` itself is still installed while `brew doctor` doesn't complain.
```console
% brew upgrade szip
Warning: Use libaec instead of deprecated szip
Warning: Use libaec instead of deprecated szip
==> Upgrading 1 outdated package:
libaec 1.0.6
==> Processing szip formula rename to libaec
==> Unlinking szip
==> Moving szip versions to /usr/local/Cellar/libaec
==> Relinking libaec
==> Downloading https://ghcr.io/v2/homebrew/core/libaec/manifests/1.0.6
Already downloaded: /Users/cho-m/Library/Caches/Homebrew/downloads/48d68ad44cb80773078814bf9ab07abf75fae62b28cc634138d9054361a1eb31--libaec-1.0.6.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libaec/blobs/sha256:2d40180340fb2ac382a9324d049dde7ab47f13d9ec812c9df66
Already downloaded: /Users/cho-m/Library/Caches/Homebrew/downloads/fc38995f8db88fc66293897f6f495b1faa1f8283fad78702f68b1d990cff6d44--libaec--1.0.6.monterey.bottle.tar.gz
==> Upgrading libaec
  2.1.1_1 -> 1.0.6

==> Pouring libaec--1.0.6.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/libaec/1.0.6: 20 files, 247.1KB
```

```console
% brew info szip
Warning: Use libaec instead of deprecated szip
libaec: stable 1.0.6 (bottled), HEAD
Adaptive Entropy Coding implementing Golomb-Rice algorithm
https://gitlab.dkrz.de/k202009/libaec
/usr/local/Cellar/libaec/1.0.6 (20 files, 247.1KB) *
  Poured from bottle on 2022-04-01 at 15:37:26
/usr/local/Cellar/szip/1.0.6 (20 files, 247.1KB)
  Poured from bottle on 2022-04-01 at 15:37:26
/usr/local/Cellar/libaec/2.1.1_1 (11 files, 144.3KB)
  Poured from bottle on 2022-04-01 at 15:36:57
/usr/local/Cellar/szip/2.1.1_1 (11 files, 144.3KB)
  Poured from bottle on 2022-04-01 at 15:36:57
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libaec.rb
License: BSD-2-Clause
==> Dependencies
Build: cmake ✘
==> Options
--HEAD
	Install HEAD version
```

**Comment by SMillerDev** [comment]
I'd suggest disabling it right away. Removals put people's install in a weird state AFAIK

**Comment by Bo98** [comment]
Removal is explicitly our policy though due to legal reasons.

> Removals put people's install in a weird state AFAIK

Can you elaborate a bit on this? Disabled formulae are ultimately removed too so if there's an issue there, we're just deferring it and I'd like to get it fixed.

**Comment by SMillerDev** [comment]
Well, disabling a formula will tell the user that the formula is disabled and complain loudly. If you have a removed formula AFAIK it'll just stay installed and nobody will be any wiser about it until brew fails to read it due to some syntax change.

**Comment by Bo98** [comment]
> Well, disabling a formula will tell the user that the formula is disabled and complain loudly

Where/when does it do this? I'm only aware of it doing it with new installs or `brew doctor` for existing (and `brew doctor` does cover removals too), so maybe I'm missing something.

**Comment by SMillerDev** [comment]
I thought it did that on updates too

**Comment by Bo98** [comment]
Tried it on liblas:

```
git -C $(brew --repo homebrew/core) checkout d4beb4452e1248e0b037da022e4fd5f9a538b1d7^
HOMEBREW_NO_AUTO_UPDATE=1 brew install --ignore-dependencies liblas
brew update
```

I received no notification about it being disabled. In fact I'm actually notified (once) about removed formulae like `pdflib-lite`.

**Comment by cho-m** [comment]
So how do we want to proceed here?
I think removing `szip` is fine.

As for rename, I don't mind either way. It has its quirks (which could be fixed in `brew`) as shown by previous example output where `brew info szip` is duplicated and messages on removed `szip` are no longer shown.

**Comment by Bo98** [comment]
Legally, I'd say this should be merged unless someone has a plan to fix the quirks in brew within the next couple days.

Or does the old version eventually get cleaned up? That's the main concern for me with the quirks - the only version isn't uninstalled in your exmaple.

**Review by SMillerDev — APPROVED** [review]

**Comment by cho-m** [comment]
> Or does the old version eventually get cleaned up? That's the main concern for me with the quirks - the old version isn't uninstalled in your exmaple.

Still installed after `brew upgrade`. I tried running `brew cleanup` but it didn't do anything and no warnings in `brew doctor`, so probably not ideal. Maybe if it was installed as dependency it might be removed via `brew autoremove`.

**Comment by Bo98** [comment]
Very likely due to any migration being seen as a version downgrade, which we don’t support.

**Pull request closed without merging**
