### PR TITLE
rust 1.53.0

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by carlocab** [comment]
You can update the `cargobootstrap` resource: https://github.com/rust-lang/rust/blob/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/src/stage0.txt#L15-L16

**Comment by carlocab** [comment]
`cargo` needed updating too.

**Comment by cho-m** [comment]
Intel failures (mostly due to `lexical-core` dependency)
- `grin-wallet` - compile error in lexical-core-0.7.4
- `pastel` - compile error in lexical-core-0.6.2
- `suricata` - compile error in vendored lexical-core
- `zola` - compile error in lexical-core-0.7.4
- `maturin` - Caused by: Failed to parse Cargo.toml at hello_world/Cargo.toml
- `watchman` - /tmp/watchman-20210620-52327-wlyv8o/watchman-2021.06.07.00/watchman_string.h:114:16: error: no member named 'data' in 'watchman_pending_fs'
- Same failures as #76780: `angle-grinder asuka cargo-audit cargo-watch gifski graph-tool ktmpl pc6001vx pdfpc vice wasm-pack`

**Comment by carlocab** [comment]
`watchman` sounds related to #79304 and #79383. I think it just doesn't compile with the new version of `folly`.

**Comment by cho-m** [comment]
For `lexical-core` issue, corresponding upstreams will need to do new release with a compatible version https://github.com/Alexhuszagh/rust-lexical/issues/65, so probably can ignore

I guess `maturin` is an issue with Homebrew test. Should fix in a separate PR rather than having to re-run CI here.

Bottled ARM failures are mostly the same. We hit `mpv` failure again, so seems to be failing more consistently.

---

Other than `maturin`, I don't think we can do much for other failures (without modifying lock dependencies), so I think okay to merge.

**Comment by carlocab** [comment]
```
==> Testing maturin
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210619-98088-dz0lcg.sb ruby -W1 -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/maturin.rb --verbose --retry
==> cargo new hello_world --bin
     Created binary (application) `hello_world` package
==> /usr/local/Cellar/maturin/0.10.6/bin/maturin build -m hello_world/Cargo.toml -b bin -o dist
💥 maturin failed
  Caused by: Failed to parse Cargo.toml at hello_world/Cargo.toml
  Caused by: missing field `authors` for key `package` at line 8 column 1
```
`cargo` probably changed the format of the `Cargo.toml` that it generates, and this broke `maturin`.

**Comment by cho-m** [comment]
I just tried on my local rustup setup and I see `authors` is not included in Cargo.toml with 1.53.0 (and 1.55.0 nightly).
I'll see if format changed, or if there is a new argument.

**Comment by messense** [comment]
cargo removed `authors` field by default with `cargo new`: https://github.com/rust-lang/cargo/pull/9282

It should be easily fixable by patching the `Cargo.toml` with a `authors` field.

**Review by cho-m — APPROVED** [review]
Although `lexical-core` issue will temporarily break the build of some Rust formulae, I don't think we should block Rust update on those upstream updates.

If necessary, we can try updating dependencies in lock files.

**Comment by carlocab** [comment]
Let's merge this. It looks like it's blocking 3 PRs.

**Pull request closed without merging**
