### PR TITLE
scipy: workaround for a SEGFAULT/SIGBUS on Apple Silicon

### LINKED ISSUE #13364: Segmentation fault on import of scipy.integrate on Apple M1 ARM silicon
SciPy can be installed under native Python 3.9.1 on an Apple M1 system running macOS Big Sur 11.1 using [these instructions](https://github.com/numpy/numpy/issues/17807#issuecomment-756328776). However, importing scipy.integrate gives a segmentation fault.

#### Reproducing code example:

```
$ brew install python@3.9
$ brew install openblas
$ OPENBLAS="$(brew --prefix openblas)" MACOSX_DEPLOYMENT_TARGET=11.1 python3 -m pip install cython --no-use-pep517
$ OPENBLAS="$(brew --prefix openblas)" MACOSX_DEPLOYMENT_TARGET=11.1 python3 -m pip install numpy --no-use-pep517
$ OPENBLAS="$(brew --prefix openblas)" MACOSX_DEPLOYMENT_TARGET=11.1 python3 -m pip install pandas --no-use-pep517
$ OPENBLAS="$(brew --prefix openblas)" MACOSX_DEPLOYMENT_TARGET=11.1 python3 -m pip install pybind11 --no-use-pep517
$ OPENBLAS="$(brew --prefix openblas)" MACOSX_DEPLOYMENT_TARGET=11.1 python3 -m pip install scipy --no-use-pep517
$ python3
Python 3.9.1 (default, Dec 29 2020, 02:24:05) 
[Clang 12.0.0 (clang-1200.0.32.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.integrate
```

#### Error message:

I'm not sure how to install gdb on M1 -- I'm not sure it's possible yet. If there is another tool I can use to get a stack trace, please advise. Here is the detail on where in the import process the error occurs, via the last bit of verbose output achieved via `python3 -vv`:

```
...
# trying /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/quadpack.cpython-39-darwin.so
# trying /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/quadpack.abi3.so
# trying /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/quadpack.so
# trying /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/quadpack.py
# /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/__pycache__/quadpack.cpython-39.pyc matches /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/quadpack.py
# code object from '/opt/homebrew/lib/python3.9/site-packages/scipy/integrate/__pycache__/quadpack.cpython-39.pyc'
# trying /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/_quadpack.cpython-39-darwin.so
# extension module 'scipy.integrate._quadpack' loaded from '/opt/homebrew/lib/python3.9/site-packages/scipy/integrate/_quadpack.cpython-39-darwin.so'
# extension module 'scipy.integrate._quadpack' executed from '/opt/homebrew/lib/python3.9/site-packages/scipy/integrate/_quadpack.cpython-39-darwin.so'
import 'scipy.integrate._quadpack' # <_frozen_importlib_external.ExtensionFileLoader object at 0x116030880>
import 'scipy.integrate.quadpack' # <_frozen_importlib_external.SourceFileLoader object at 0x1151608e0>
# trying /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/_ode.cpython-39-darwin.so
# trying /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/_ode.abi3.so
# trying /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/_ode.so
# trying /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/_ode.py
# /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/__pycache__/_ode.cpython-39.pyc matches /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/_ode.py
# code object from '/opt/homebrew/lib/python3.9/site-packages/scipy/integrate/__pycache__/_ode.cpython-39.pyc'
# trying /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/vode.cpython-39-darwin.so
# extension module 'scipy.integrate.vode' loaded from '/opt/homebrew/lib/python3.9/site-packages/scipy/integrate/vode.cpython-39-darwin.so'
# extension module 'scipy.integrate.vode' executed from '/opt/homebrew/lib/python3.9/site-packages/scipy/integrate/vode.cpython-39-darwin.so'
import 'scipy.integrate.vode' # <_frozen_importlib_external.ExtensionFileLoader object at 0x116041580>
# trying /opt/homebrew/lib/python3.9/site-packages/scipy/integrate/_dop.cpython-39-darwin.so
zsh: segmentation fault  /opt/homebrew/bin/python3 -vv -c "import scipy.integrate"
```

#### Scipy/Numpy/Python version information:
```
>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.6.0 1.19.5 sys.version_info(major=3, minor=9, micro=1, releaselevel='final', serial=0)
```

### PR DESCRIPTION
**Pull request by xght**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Temporary fix for https://github.com/iains/gcc-darwin-arm64/issues/32.

Would fix https://github.com/scipy/scipy/issues/13364 and https://github.com/Homebrew/homebrew-core/issues/69236.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks, @xght. Could you put `revision 1` in between the `license` and `head` lines? The revision will make sure that ARM users get an update that includes this fix when they do `brew upgrade`.

(Actually, it'll update `scipy` for everyone who does `brew upgrade`, but we have no way of targeting updates to specific OS versions.)

**Comment by xght** [comment]
> Thanks, @xght. Could you put `revision 1` in between the `license` and `head` lines? The revision will make sure that ARM users get an update that includes this fix when they do `brew upgrade`.

Done.

**Comment by schoeps** [comment]
I had a similar issue with `from scipy.sparse import linalg` and this changeset fixed it. Thanks.

**Comment by xght** [comment]
Should be fixed by https://github.com/iains/gcc-darwin-arm64/commit/02d30eeb2534a593216564c07e94f4d49f0b679e.

**Comment by Bo98** [comment]
It might be better then if the fix incorporated into `gcc` itself (cc @fxcoudert).

**Comment by fxcoudert** [comment]
Yes, that should be done in GCC. I will rebase GCC with that latest change and update the patch.

**Comment by carlocab** [comment]
I think this should be fixed by #71627.

**Comment by fxcoudert** [comment]
I'll include a revision bump in scipy.

**Pull request closed without merging**
