### PR TITLE
erlang@20: Fix Catalina build, add escript test

### PR DESCRIPTION
**Pull request by gromgit**
CI Xcode upgrade broke Catalina builds for all OTP versions, but upstream only plans to patch OTP 22 and 23.

This backports the official patch to OTP 20, disables kernel polling (also breaks Catalina build on Xcode 11.5), and adds the escript test from #57531.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Is 20 no longer officially supported then?

**Comment by gromgit** [comment]
> Is 20 no longer officially supported then?

I've posted that very question (along with OTP 21) to upstream, haven't heard back yet.

**Comment by gromgit** [comment]
@SMillerDev , upstream confirms that only two previous versions are supported as a matter of policy, so should `erlang@20` be deprecated, disabled, deleted, or something else?

**Comment by SMillerDev** [comment]
Deprecated with the date of the release that deprecated it.

**Pull request closed without merging**
