### PR TITLE
ocaml-num: use `change_make_var!` instead of regex

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Needed to get CI passing for https://github.com/Homebrew/brew/pull/9152.

### CODE REVIEW

**Comment by reitermarkus** [comment]
Marked this as syntax-only since the build failure (https://github.com/Homebrew/homebrew-core/pull/64433) shouldn't block this change.

**Comment by fxcoudert** [comment]
If the change is in `install` I don't think `CI-syntax-only` should be applied

**Comment by reitermarkus** [comment]
Well it's the same failure as in https://github.com/Homebrew/homebrew-core/pull/64433.

**Comment by fxcoudert** [comment]
We definitely shouldn't use `CI-syntax-only` to bypass known failures

**Comment by reitermarkus** [comment]
The failure is confirmed to have nothing to do with this change, however, so this is effectively a syntax-only change.

**Comment by SMillerDev** [comment]
"it was failing and still is, despite my change" is different from "this change only impacts brew syntax and no part of the install" though

**Comment by reitermarkus** [comment]
I would agree with your point if the thing failing would actually be the `ocaml-num` build itself. But the only thing failing is the `infer` dependent, which seems to be caused by `ocaml`, not `ocaml-num`.

Anyways, I disabled the new RuboCop for now to unblock https://github.com/Homebrew/brew/pull/9152.

**Comment by fxcoudert** [comment]
I'd rather force-merge a failing test, where I know why it fails, than make it not go through CI at all.
If the change impacts the install, then it should go through a full CI.

(And “effectively a syntax-only change” is not really relevant. There could be plenty of ways to screw up something that is “effectively” a syntax change, and the way we can prevent against those is by going through CI.)

**Comment by reitermarkus** [comment]
> I'd rather force-merge a failing test, where I know why it fails, than make it not go through CI at all.

It did go through CI and failed with the same error as https://github.com/Homebrew/homebrew-core/pull/64433, which is why I marked it as syntax-only. Will rebase so it fails CI again if that's preferable.

**Pull request merged**
