### PR TITLE
oath-toolkit 2.6.7

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
https://gitlab.com/oath-toolkit/oath-toolkit/-/commit/60d9902b5c20f27e70f8e9c816bfdc0467567e1a
New header requirement in `pam_oath/configure.ac` for `security/pam_modutil.h`

Not available in MacOS CLT:
```console
❯ cd /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/security
❯ ls
audit  openpam.h  openpam_attr.h  openpam_version.h  pam_appl.h  pam_constants.h  pam_modules.h  pam_types.h
```

**Comment by alebcay** [comment]
The folks at MacPorts are also working on figuring this one out, there may be some relevant discussion here: https://github.com/macports/macports-ports/pull/10932.

**Comment by nickgaya** [comment]
As @alebcay mentioned I ran into the same configure error with the MacPorts port.

On Mac OS, pam_modutil.h is not available, but since `getpwnam` (and related functions) are thread-safe on Mac OS, and not used in a re-entrant way in oath-toolkit, I believe it is safe to replace `getpwnam_r` with `getpwnam` in the pam_oath module.

**Comment by cho-m** [comment]
Shouldn't this be fixed upstream?
Unless upstream specifically doesn't support macOS (not sure if other BSD-based OS are impacted).

The `configure.ac` step for `security/pam_modutil.h` shouldn't cause an error. Instead, the corresponding macros should be used to decide whether to `#include <security/pam_modutil.h>` or to use an alternative like `getpwnam`.

Similar to what Yubikey's `pam-u2f` does for `pam_modutil_drop_priv` support, e.g.
- https://github.com/Yubico/pam-u2f/blob/86d9a59e5ce8a0a86b65912d73c5f29aeb9b66c8/configure.ac#L40-L45
- https://github.com/Yubico/pam-u2f/blob/86d9a59e5ce8a0a86b65912d73c5f29aeb9b66c8/drop_privs.h#L32-L34

**Comment by nickgaya** [comment]
It might be worth asking the upstream and see what they think about it.

**Comment by chenrui333** [comment]
looks like no response from upstream on that gitlab issue? :(

**Pull request closed without merging**
