### PR TITLE
Openvino 2023.0.2

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Why tests are failed? OpenCV formula was bumped

**Comment by ywwry66** [comment]
Looks like timeout and needs long build label.

**Comment by ilya-lavrenov** [comment]
@chenrui333 could you please add such label?

**Comment by ilya-lavrenov** [comment]
@chenrui333 @fxcoudert @carlocab could you please add such label?

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
