### PR TITLE
sslyze: build for Apple M1

### PR DESCRIPTION
**Pull request by carlocab**
See #68463.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`nassl` is building openssl internally, and that does not go well:

```
OPENSSL LEGACY: Starting...
Configuring for darwin64-x86_64-cc
```

**Comment by fxcoudert** [comment]
Reported at https://github.com/nabla-c0d3/nassl/issues/69

**Comment by carlocab** [comment]
Restarting tests to see if the `sslyze` failure at https://github.com/Homebrew/homebrew-core/pull/68476 has an independent cause.

**Comment by carlocab** [comment]
Ok, looks like patching `nassl` doesn't work like I though it would?

**Comment by carlocab** [comment]
```
ImportError: dlopen(/private/tmp/pip-build-env-f29v0ho_/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): Symbol not found: _ffi_prep_closure
      Referenced from: /private/tmp/pip-build-env-f29v0ho_/overlay/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
```
Still trying to call deprecated functions it seems

**Comment by chenrui333** [comment]
FYI, bumped sslyze to the latest, v4.0.1 #69622

**Comment by carlocab** [comment]
Superseded by #69622.

**Pull request closed without merging**
