### PR TITLE
hdf5@1.8: fix source sha256

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
I've asked upstream but got no answer: https://github.com/HDFGroup/hdf5/pull/279#issuecomment-787058349

**Comment by iMichka** [comment]
```
==> Analytics
install: 131 (30 days), 260 (90 days), 839 (365 days)
install-on-request: 125 (30 days), 253 (90 days), 808 (365 days)
build-error: 0 (30 days)
```

**Comment by iMichka** [comment]
At this point we could maybe just deprecate it, and leave the previous bottle untouched.

**Comment by iMichka** [comment]
Upstream confirmed the retag. This is ready to be merged.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
