### PR TITLE
tomcat 8.0.35 & 9.0.0.M6 (devel)

### PR DESCRIPTION
**Pull request by Jerzerak**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---
- Bump stable tomcat version from 8.0.33 to 8.0.35
- Bump stable fulldocs resource version from 8.0.33 to 8.0.35
- Bump devel tomcat version from 9.0.0.M4 to 9.0.0.M6
- Bump devel fulldocs version from 9.0.0.M4 to 9.0.0.M6

### CODE REVIEW

**Comment by DomT4** [comment]
There's a PR open for this in https://github.com/Homebrew/homebrew-core/pull/1193, which has been held up for a bit for the sake of discussion.

**Comment by Jerzerak** [comment]
@DomT4 Whoops, my bad...don't know how I missed that. I'm keeping this open for now as version 9.0.0.M6 is still a new commit, but feel free to close this until a decision is reached if you so wish.

**Comment by MikeMcQuaid** [comment]
I think it's worth pulling this as-is for now.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/16c9358061920aa87c6845a3deff5ba16ff6660b & https://github.com/Homebrew/homebrew-core/commit/3ca1d0827db61fa1108f6fdd42f94bdf1e72bd03. Thanks again @Jerzerak! 😺

**Pull request closed without merging**
