### PR TITLE
easyrpg-player 0.5.3

### PR DESCRIPTION
**Pull request by ilovezfs**
depend on speexdsp instead of speex

### CODE REVIEW

**Comment by ilovezfs** [comment]
https://github.com/EasyRPG/Player/issues/1292

**Comment by Ghabry** [comment]
I think the 'depends_on "speex"' must be 'depends_on "speexdsp"'. Because your configure script on Jenkins reports "SPEEXDSP... No"

**Comment by ilovezfs** [comment]
@Ghabry thanks! fixed.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
