### PR TITLE
libelf: fix urls

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by vszakats** [comment]
FWIW audit says:
```
libelf:
  * stable version should not decrease (from 0.8.14 to 0.8.13)
  * 'revision 1' should be removed
Error: 2 problems in 1 formula detected
```

This formula was once updated to 0.8.14, which got subsequently reverted: fa71ade8df6fb021502a09204a0adcd78c7c960d, 204991a27686b48ec70dd14e1869f4f2a7640b9d
That may be the reason for the false audit alarm.

**Comment by kousu** [comment]
Thanks for looking at this; good work. Maybe we should rehost libelf on github or something more stable than archive.org?

**Comment by vszakats** [comment]
I personally don't think it is necessary, `archive.org` is very stable for such backup purposes (it's used for several similar "lost" package hosts). But, if somebody uploads a backup to a Homebrew controlled location, we can add that as a `mirror` anytime.

**Comment by fxcoudert** [comment]
Thanks @vszakats

**Pull request merged**
