### PR TITLE
iwyu 0.19

### PR DESCRIPTION
**Pull request by FtZPetruska**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Bump to version 0.19, supporting LLVM 15.

The source URL was changed to the github release as https://include-what-you-use.org is currently unavailable. See https://github.com/include-what-you-use/include-what-you-use/issues/1134

### CODE REVIEW

**Comment by FtZPetruska** [comment]
> Full audit include-what-you-use --online --git --skip-style output
>  include-what-you-use:
>    * The homepage URL https://include-what-you-use.org/ is not reachable (HTTP status code 403)

CI failing due to the aforementioned upstream issue.

**Comment by Bo98** [comment]
Website issue seems to be fixed now, at least for me.

**Comment by FtZPetruska** [comment]
> Website issue seems to be fixed now, at least for me.

The [main page](https://include-what-you-use.org/) does load for me which seems to be enough to pass the audit. But the [downloads page](https://include-what-you-use.org/downloads/) is still returning 403 for me.

**Comment by Bo98** [comment]
Indeed, though the tarball itself (linked on home page) seems fine though.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
