### PR TITLE
ibex 2.5.1

### PR DESCRIPTION
**Pull request by ilovezfs**
needs C++11 now
use optim-lib=soplex to mirror upstream's CI defaults
remove param-estim to mirror upstream's CI defaults

### CODE REVIEW

**Comment by ProfessorCoal** [comment]
https://github.com/ilovezfs/homebrew-core/blob/6cad247545a0b123ef650f235d962ab3e71340d9/Formula/ammonite-repl.rb

**Comment by ilovezfs** [comment]
@ProfessorCoal ?

**Review by ilovezfs — COMMENTED** [review]
not announced http://ibex-lib.org/download

**Comment by ilovezfs** [comment]
Reported problem with ctc01 https://github.com/ibex-team/ibex-lib/issues/276

**Pull request closed without merging**
