### PR TITLE
unfs3: migrate to boneyard

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Created with `brew boneyard-formula-pr` because not functional on macOS (see https://github.com/Homebrew/homebrew-core/issues/7213).

Fixes https://github.com/Homebrew/homebrew-core/issues/7667.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by ryansch** [comment]
@MikeMcQuaid This formula works just fine on macOS Sierra.  It's a dependency of dinghy (https://github.com/codekitchen/dinghy) which is now uninstallable without jumping through hoops.

**Comment by codekitchen** [comment]
@MikeMcQuaid to echo what @ryansch said... my project [Dinghy](https://github.com/codekitchen/dinghy) uses unfs3 installed via homebrew. I can say for certain that there are at least 100 people inside and outside my company using this setup, and it's been working fine for over 2 years, starting with OS X 10.9 I believe, and still working fine in MacOS 10.12.

So while I haven't dug into why the initial reporter couldn't get it working, I'm very confident in saying that the homebrew install of unfs3 works on OS X, and should not have been moved to boneyard. What can I do to help get it re-instated? In the meantime I'm going to add it to [Dinghy's homebrew tap](https://github.com/codekitchen/homebrew-dinghy) so that people can install Dinghy again. Thanks.

**Comment by ilovezfs** [comment]
@codekitchen if you can open a PR adding it to core and CI is :green_apple: that would be a good first step.

**Comment by codekitchen** [comment]
Thanks @ilovezfs. I pushed up https://github.com/Homebrew/homebrew-core/pull/7825 as a straight revert of this commit, but it looks like that's not going to pass CI, since it appears that CI now fails if there's no `test do` block in the formula and unfs3 didn't have one.

It'd be nice if we could grandfather this back in, but if necessary I can have a go at adding a test block. It may take me a bit.

**Comment by codekitchen** [comment]
OK I got a chance to look over the docs on adding a test, and I added what I think is a reasonable test block. Moving this conversation over to #7825

**Pull request merged**
