### PR TITLE
dartsim 6.10.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
[ 86%] Linking CXX shared library ../../../lib/libdart-utils-urdf.dylib
cd /tmp/dartsim-20210410-8212-1hvvn7k/dart-6.10.0/dart/utils/urdf && /usr/local/Cellar/cmake/3.20.1/bin/cmake -E cmake_link_script CMakeFiles/dart-utils-urdf.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -fPIC -stdlib=libc++ -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.8 -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 6.10.0 -current_version 6.10.0 -o ../../../lib/libdart-utils-urdf.6.10.0.dylib -install_name @rpath/libdart-utils-urdf.6.10.dylib CMakeFiles/dart-utils-urdf.dir/DartLoader.cpp.o CMakeFiles/dart-utils-urdf.dir/urdf_world_parser.cpp.o  -Wl,-rpath,/tmp/dartsim-20210410-8212-1hvvn7k/dart-6.10.0/lib -Wl,-rpath,/tmp/dartsim-20210410-8212-1hvvn7k/dart-6.10.0/dart/external/odelcpsolver ../../../lib/libdart-utils.6.10.0.dylib ../../../lib/libdart.6.10.0.dylib ../../external/odelcpsolver/libdart-external-odelcpsolver.6.10.0.dylib /usr/local/lib/libccd.2.0.dylib /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libm.tbd /usr/local/Cellar/fcl/0.6.1/lib/libfcl.dylib /usr/local/lib/libassimp.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/liboctomap.1.9.6.dylib /usr/local/lib/liboctomath.1.9.6.dylib /usr/local/lib/libtinyxml2.8.0.0.dylib /usr/local/Cellar/urdfdom/1.0.4_2/lib/liburdfdom_sensor.dylib /usr/local/Cellar/urdfdom/1.0.4_2/lib/liburdfdom_model_state.dylib /usr/local/Cellar/urdfdom/1.0.4_2/lib/liburdfdom_model.dylib /usr/local/Cellar/urdfdom/1.0.4_2/lib/liburdfdom_world.dylib /usr/local/lib/libconsole_bridge.1.0.dylib 
cd /tmp/dartsim-20210410-8212-1hvvn7k/dart-6.10.0/dart/utils/urdf && /usr/local/Cellar/cmake/3.20.1/bin/cmake -E cmake_symlink_library ../../../lib/libdart-utils-urdf.6.10.0.dylib ../../../lib/libdart-utils-urdf.6.10.dylib ../../../lib/libdart-utils-urdf.dylib
[ 86%] Built target dart-utils-urdf
make[1]: *** [dart/gui/CMakeFiles/dart-gui.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by scpeters** [comment]
> ```
> [ 86%] Linking CXX shared library ../../../lib/libdart-utils-urdf.dylib
> cd /tmp/dartsim-20210410-8212-1hvvn7k/dart-6.10.0/dart/utils/urdf && /usr/local/Cellar/cmake/3.20.1/bin/cmake -E cmake_link_script CMakeFiles/dart-utils-urdf.dir/link.txt --verbose=1
> /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -fPIC -stdlib=libc++ -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.8 -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 6.10.0 -current_version 6.10.0 -o ../../../lib/libdart-utils-urdf.6.10.0.dylib -install_name @rpath/libdart-utils-urdf.6.10.dylib CMakeFiles/dart-utils-urdf.dir/DartLoader.cpp.o CMakeFiles/dart-utils-urdf.dir/urdf_world_parser.cpp.o  -Wl,-rpath,/tmp/dartsim-20210410-8212-1hvvn7k/dart-6.10.0/lib -Wl,-rpath,/tmp/dartsim-20210410-8212-1hvvn7k/dart-6.10.0/dart/external/odelcpsolver ../../../lib/libdart-utils.6.10.0.dylib ../../../lib/libdart.6.10.0.dylib ../../external/odelcpsolver/libdart-external-odelcpsolver.6.10.0.dylib /usr/local/lib/libccd.2.0.dylib /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libm.tbd /usr/local/Cellar/fcl/0.6.1/lib/libfcl.dylib /usr/local/lib/libassimp.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/liboctomap.1.9.6.dylib /usr/local/lib/liboctomath.1.9.6.dylib /usr/local/lib/libtinyxml2.8.0.0.dylib /usr/local/Cellar/urdfdom/1.0.4_2/lib/liburdfdom_sensor.dylib /usr/local/Cellar/urdfdom/1.0.4_2/lib/liburdfdom_model_state.dylib /usr/local/Cellar/urdfdom/1.0.4_2/lib/liburdfdom_model.dylib /usr/local/Cellar/urdfdom/1.0.4_2/lib/liburdfdom_world.dylib /usr/local/lib/libconsole_bridge.1.0.dylib 
> cd /tmp/dartsim-20210410-8212-1hvvn7k/dart-6.10.0/dart/utils/urdf && /usr/local/Cellar/cmake/3.20.1/bin/cmake -E cmake_symlink_library ../../../lib/libdart-utils-urdf.6.10.0.dylib ../../../lib/libdart-utils-urdf.6.10.dylib ../../../lib/libdart-utils-urdf.dylib
> [ 86%] Built target dart-utils-urdf
> make[1]: *** [dart/gui/CMakeFiles/dart-gui.dir/all] Error 2
> make: *** [all] Error 2
> ```

~~~
make[2]: *** No rule to make target `/System/Library/Frameworks/GLUT.framework/GLUT', needed by `lib/libdart-gui.6.10.0.dylib'.  Stop.
make[2]: *** Waiting for unfinished jobs....
~~~

**Comment by scpeters** [comment]
cc @jslee02

**Comment by jslee02** [comment]
It seems `/System/Library/Frameworks/GLUT.framework/GLUT` is not valid on macOS 11. Would it be possible to make [these lines](https://github.com/Homebrew/homebrew-core/pull/74912/files#diff-eeadab7c39b20ad43772fe75a89d1db2637b112f298cc3872113f759c0681026R33-R35) conditional to the macOS version? I don't currently have macOS 11 machine to test with this though.

**Comment by SMillerDev** [comment]
Maybe there is a way to prevent dartsim from trying to link agains X11/XQuartz at all?

**Comment by scpeters** [comment]
there is a more recent version in https://github.com/Homebrew/homebrew-core/pull/75406

**Pull request closed without merging**
