### PR TITLE
mx 5.300.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
<details>
<summary>test failure</summary>

```
==> /usr/local/Cellar/mx/5.300.3/bin/mx suites
Error while creating project com.oracle.jvmtiasmagent
Traceback (most recent call last):
  File "/usr/local/Cellar/mx/5.300.3/libexec/mx.py", line 17540, in <module>
    main()
  File "/usr/local/Cellar/mx/5.300.3/libexec/mx.py", line 17374, in main
    _mx_suite._init_metadata()
  File "/usr/local/Cellar/mx/5.300.3/libexec/mx.py", line 2445, in _init_metadata
    self._load_metadata()
  File "/usr/local/Cellar/mx/5.300.3/libexec/mx.py", line 2684, in _load_metadata
    self._load_projects()
  File "/usr/local/Cellar/mx/5.300.3/libexec/mx.py", line 2748, in _load_projects
    p = DefaultNativeProject(self, name, subDir, srcDirs, deps, workingSets, d, kind=native,
  File "/usr/local/Cellar/mx/5.300.3/libexec/mx_native.py", line 648, in __init__
    super(DefaultNativeProject, self).__init__(suite, name, subDir, srcDirs, deps, workingSets, d, **kwargs)
  File "/usr/local/Cellar/mx/5.300.3/libexec/mx_native.py", line 278, in __init__
    super(NinjaProject, self).__init__(suite, name, subDir, srcDirs, deps, workingSets, d, **kwargs)
  File "/usr/local/Cellar/mx/5.300.3/libexec/mx_native.py", line 193, in __init__
    super(MultiarchProject, self).__init__(suite, name, subDir, srcDirs, deps, workingSets, d, **kwargs)
  File "/usr/local/Cellar/mx/5.300.3/libexec/mx.py", line 7968, in __init__
    super(AbstractNativeProject, self).__init__(suite, name, subDir, srcDirs, deps, workingSets, d, theLicense,
  File "/usr/local/Cellar/mx/5.300.3/libexec/mx.py", line 6442, in __init__
    ensure_dir_exists(s)
  File "/usr/local/Cellar/mx/5.300.3/libexec/mx.py", line 4309, in ensure_dir_exists
    raise e
  File "/usr/local/Cellar/mx/5.300.3/libexec/mx.py", line 4303, in ensure_dir_exists
    os.makedirs(path)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 1] Operation not permitted: '/usr/local/Cellar/mx/5.300.3/libexec/java/com.oracle.jvmtiasmagent/include'

Error: mx: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected: 0
  Actual: 1
```

</details>

**Comment by chenrui333** [comment]
I could not reproduce the test failure in my local.

**Comment by SMillerDev** [comment]
> PermissionError: [Errno 1] Operation not permitted: '/usr/local/Cellar/mx/5.300.3/libexec/java/com.oracle.jvmtiasmagent/include'

It seems to want to run the `suites` command in it's own libexec directory.

**Comment by cho-m** [comment]
The script seems to use that directory:
```python
_mx_home = realpath(dirname(__file__))
...
class MXSuite(InternalSuite):
    def __init__(self):
        InternalSuite.__init__(self, _mx_home)
...
def main():
    ...
    _mx_suite = MXSuite()
    os.environ['MX_HOME'] = _mx_home
```
And needs file permissions to create any missing subdirectories.

**Pull request closed without merging**
