### PR TITLE
postgis 3.0.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@Rylan12 looks like it is `GPL-2.0` without anything indicating `-or-later` or `-only`. :(

**Comment by chenrui333** [comment]
license header ref:

```
/**********************************************************************
 *
 * PostGIS - Spatial Types for PostgreSQL
 * http://postgis.net
 *
 * This is free software; you can redistribute and/or modify it under
 * the terms of the GNU General Public Licence. See the COPYING file.
 *
 **********************************************************************/
```

**Review by SMillerDev — APPROVED** [review]

**Comment by Rylan12** [comment]
@chenrui333 from the [website](https://postgis.net):

> PostGIS is released under the GNU General Public License ([GPLv2](http://opensource.org/licenses/gpl-2.0.php) or later). Refer to [License FAQ](https://postgis.net/docs/manual-dev/PostGIS_FAQ.html#license_faq) for more information. PostGIS is developed by a group of contributors led by a Project Steering Committee.

Otherwise, we should use `GPL-2.0-only` in these cases.

**Comment by chenrui333** [comment]
> @chenrui333 from the [website](https://postgis.net):
> 
> > PostGIS is released under the GNU General Public License ([GPLv2](http://opensource.org/licenses/gpl-2.0.php) or later). Refer to [License FAQ](https://postgis.net/docs/manual-dev/PostGIS_FAQ.html#license_faq) for more information. PostGIS is developed by a group of contributors led by a Project Steering Committee.
> 
> Otherwise, we should use `GPL-2.0-only` in these cases.

that is a nice find.

**Pull request closed without merging**
