### PR TITLE
rust 1.76.0

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
## Source build failures

- [ ] (14-x86_64, 13-x86_64) `aptos` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/7832049914/job/21398662123?pr=162122#step:3:1242)): ``error: failed to get `aptos-protos` as a dependency of package `processor v1.0.0 (https://github.com/aptos-labs/aptos-indexer-processors.git?rev=4801acae7aea30d7e96bbfbe5ec5b04056dfa4cf#4801acae)` ``; unrelated to Rust update
- [x] `deno` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/7832049914/job/21398662459?pr=162122#step:3:10330)): ``error: casting `&T` to `&mut T` is undefined behavior, even if the reference is unused, consider instead using an `UnsafeCell` ``; denoland/deno#22376
- [ ] `grin` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/7832049914/job/21398662459?pr=162122#step:3:5385)): ``error[E0310]: the parameter type `T` may not live long enough``
- [ ] `grin-wallet` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/7832049914/job/21398662459?pr=162122#step:3:5688)): ``error[E0310]: the parameter type `T` may not live long enough``
- [ ] `lucky-commit` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/7832049914/job/21398662459?pr=162122#step:3:6989)): ``error[E0310]: the parameter type `T` may not live long enough``
- [ ] `tremor-runtime` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/7832049914/job/21398662459?pr=162122#step:3:10330)): `"OnigValue_struct_(unnamed_at_/opt/homebrew/Cellar/oniguruma/6_9_9/include/oniguruma_h_788_3)" is not a valid Ident`; unrelated to Rust update
- [ ] (x86_64) `pylyzer` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/7832049914/job/21398662123?pr=162122#step:3:8305)): `error[E0512]: cannot transmute between types of different sizes, or dependently-sized types`
- [ ] `wagyu` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/7832049914/job/21398662459?pr=162122#step:3:10877)): ``error[E0310]: the parameter type `T` may not live long enough``

## Test failures

- [ ] `cherrybomb` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/7832049914/job/21398662459?pr=162122#step:3:2718)): `Error: error sending request for url (https://cherrybomb.blstsecurity.com/tel): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known`; unrelated to Rust update

## Pre-existing issues

- [ ] `kapacitor` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/7832049914/job/21398662459?pr=162122#step:3:6500)): `error: private item shadows public glob re-export`
- [ ] (x86_64) `watchman` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/7832049914/job/21398662123?pr=162122#step:3:11633)): `ld: Undefined symbols`; https://github.com/Homebrew/homebrew-core/pull/118242#issuecomment-1367052317

## Checksum mismatch

- [ ] `gdrive` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/7832049914/job/21398662459?pr=162122#step:3:4795))

## Transient failures

- (14-arm64) `boringtun` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/7832049914/job/21398662459?pr=162122#step:3:1833)): `Timeout::Error: execution expired`

**Comment by ZhongRuoyu** [comment]
I've checked the failures and confirmed that they are all unrelated or non-blocking; details in comment above.

**Comment by chenrui333** [comment]
> * (14-arm64) `boringtun` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/7832049914/job/21398662459?pr=162122#step:3:1833)): `Timeout::Error: execution expired`

this is actually the reason

```
$ /opt/homebrew/Cellar/boringtun/0.5.2/bin/boringtun-cli utun --foreground
  2024-02-13T06:48:20.567539Z ERROR boringtun_cli: Failed to initialize tunnel, error: Connect("Operation not permitted(did you run with sudo?)")
    at boringtun-cli/src/main.rs:160
```

**Comment by ZhongRuoyu** [comment]
Failed on Linux this time with:

```
  cp: error writing '/home/linuxbrew/.linuxbrew/Cellar/rust/1.76.0/lib/librustc_driver-c1d05c71ae5d49be.so': No space left on device
  cp: error writing '/home/linuxbrew/.linuxbrew/Cellar/rust/1.76.0/lib/libstd-facb58fb987caff6.so': No space left on device
  cp: error writing '/home/linuxbrew/.linuxbrew/Cellar/rust/1.76.0/lib/libtest-cd354e64c4a69350.so': No space left on device
  mkdir: cannot create directory ‘/home/linuxbrew/.linuxbrew/Cellar/rust/1.76.0/lib/rustlib/etc’: No space left on device
  install: error: directory creation failed. see logs at '/home/linuxbrew/.linuxbrew/Cellar/rust/1.76.0/lib/rustlib/install.log'
  Build completed unsuccessfully in 0:04:13
  make: *** [Makefile:61: install] Error 1
  Error: An exception occurred within a child process:
    Errno::ENOSPC: No space left on device @ dir_s_mkdir - /github/home/bottles/logs/rust/build
```

https://github.com/Homebrew/homebrew-core/actions/runs/7878983243/job/21515941415?pr=162122

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
