### PR TITLE
pyqt 6.3.1

### PR DESCRIPTION
**Pull request by MehdiChinoune**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

It will probably fail because both sip and pyqt-builder were moved to python@3.10

### CODE REVIEW

**Comment by danielnachun** [comment]
I'd be fine with migrating this to `python@3.10` and using the allowlist so we aren't blocked by the conflict that happens due to `glib`, which will go away when https://github.com/Homebrew/homebrew-core/pull/103916 is merged.

On a related note, I'm going to explore the possibility of making `pyqt@5` into a "multi-Python" formula similar to `numpy` and the recently added `libpython-tabulate`.  This would allow the formula to provide packages for both Python 3.9 and Python 3.10, and would save us the pain of having to migrate `pyqt@5` and all of its dependents in one PR.  Instead its dependents could be migrated individually in separate PRs.

If we end up pursuing that strategy for `pyqt@5`, we'd probably want to do the same with `pyqt` eventually.  I don't think we have to do this yet for `pyqt` because it currently has no dependents, but eventually it will and at that point the split would probably be worth doing.

**Comment by MehdiChinoune** [comment]
> I don't think we have to do this yet for `pyqt` because it currently has no dependents, but eventually it will and at that point the split would probably be worth doing.

I have a project that depends on pyqt which no longer configure because of the mismatch of python version with sip/pyqt-builder

**Comment by danielnachun** [comment]
> I have a project that depends on pyqt which no longer configure because of the mismatch of python version with sip/pyqt-builder

Sorry if I wasn't clear above, but I think we **should** migrate `pyqt` to `python@3.10` which should fix that issue for you.  

What we should probably wait on for now is changing the formula so that it would be able to support multiple versions of Python.  Since I think the `python@3.10` migration will be done soon, I don't think we need to worry about supporting `python@3.9` for `pyqt`.  Where it could come up is when `python@3.11` comes out, but we aren't there yet.

To fix the current audit failure, you can just add `pyqt` to https://github.com/Homebrew/homebrew-core/blob/master/audit_exceptions/versioned_dependencies_conflicts_allowlist.json in a separate commit and it should pass the audit.

**Comment by MehdiChinoune** [comment]
```
error: could not create '/opt/homebrew/lib/python3.10/site-packages/PyQt6': Operation not permitted
```
How to fix this?

**Comment by danielnachun** [comment]
> ```
> error: could not create '/opt/homebrew/lib/python3.10/site-packages/PyQt6': Operation not permitted
> ```
> How to fix this?

Try changing:
```
resource("PyQt6-sip").stage do
      system "python3", *Language::Python.setup_install_args(prefix)
end
```
to
```
resource("PyQt6-sip").stage do
      system "python3", *Language::Python.setup_install_args(prefix), 
                        "--install-lib=#{prefix/Language::Python.site_packages("python3")}"
end
```
I'm hitting the same issue in `pyqt@5` and this seems to fix it so far.

**Review by danielnachun — APPROVED** [review]
This is ready to go now.  Thanks @MehdiChinoune!

**Pull request closed without merging**
