### PR TITLE
cnats 1.7.4

### PR DESCRIPTION
**Pull request by kozlovic**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by kozlovic** [comment]
@ilovezfs jenkins fails with a Not Found PR job. How do you recycle that (I submitted the PR with `brew bump-formula-pr`)?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by kozlovic** [comment]
@ilovezfs Error in log like this: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/13161/version=el_capitan/console
Not sure this is related to cnats?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks @kozlovic!

**Pull request closed without merging**
