### PR TITLE
onnxruntime: add formulae for past versions

### PR DESCRIPTION
**Pull request by minty99**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

I added past versions of `onnxruntime`, which were extracted from the final formulae in `homebrew-core` using command `brew extract --version=<version> onnxruntime tap-name`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Please indicate how this would fill our criteria for versioned formulas (https://docs.brew.sh/Versions) and why we might want to ship an older version?

**Comment by minty99** [comment]
@SMillerDev `onnxruntime` library is updated very fast and some features are continuously deprecated and system software requirements are continuously changed - which make errors to build applications which require older versions. For example, CUDA version requirement was raised in the latest release, but CUDA version update is not a small task in ML research or data centers. This is why I request to add older versions.

**Comment by SMillerDev** [comment]
But what about:
> Upstream should have a release branch for each formula version, and have an explicit policy of releasing security updates for each version when necessary.

**Comment by minty99** [comment]
@SMillerDev It have `rel-1.xx.x` branch and it seems the release branch. But I don't know about security updates - I'll ask the maintainers about it.

**Comment by minty99** [comment]
@SMillerDev 

https://github.com/microsoft/onnxruntime/discussions/13602#discussioncomment-4113651

It seems that they only patch the latest release 😢 then this PR can't be accepted, right? Thanks for your attention.

**Pull request closed without merging**
