### PR TITLE
git-annex 6.20160412

### PR DESCRIPTION
**Pull request by timhowes**

### CODE REVIEW

**Comment by apjanke** [comment]
Build failure.

```

cabal: Error: some packages failed to install:
wai-app-static-3.1.5 depends on wai-logger-2.2.5 which failed to install.
wai-extra-3.0.15 depends on wai-logger-2.2.5 which failed to install.
wai-logger-2.2.5 failed during the building phase. The exception was:
ExitFailure 1
yesod-1.4.3 depends on wai-logger-2.2.5 which failed to install.
yesod-auth-1.4.13.1 depends on wai-logger-2.2.5 which failed to install.
yesod-core-1.4.20.1 depends on wai-logger-2.2.5 which failed to install.
yesod-default-1.2.0 depends on wai-logger-2.2.5 which failed to install.
yesod-form-1.4.7 depends on wai-logger-2.2.5 which failed to install.
yesod-persistent-1.4.0.4 depends on wai-logger-2.2.5 which failed to install.
yesod-static-1.5.0.3 depends on wai-logger-2.2.5 which failed to install.
```

**Comment by timhowes** [comment]
Built fine on my machine. Seems to be some problem with installing haskell packages on the build server.

**Comment by zmwangx** [comment]
What about giving the ideas in https://github.com/Homebrew/legacy-homebrew/pull/49387 a try and see if that works? (In short, download a Stackage snapshot in a resource block and use that cabal.config to do the deps resolution.)

**Comment by ilovezfs** [comment]
@zmwangx That will actually guarantee it breaks. ;)
It's an upstream issue that is fixed. We just need to add fast-logger >= 2.4.5 or wait a couple days.
https://github.com/kazu-yamamoto/logger/commits/master

**Comment by zmwangx** [comment]
@ilovezfs 
> It's an upstream issue that is fixed.

I just assumed that it's a new version of a dependency that broke, so using a slightly older snapshot might solve the problem. I didn't investigate.

**Comment by ilovezfs** [comment]
@zmwangx Yup, fair enough. I think we can just be patient since this will take care of itself within a day or two.

**Comment by zmwangx** [comment]
No objection against that.

**Comment by ilovezfs** [comment]
If anyone is eager to build without resorting to a fixed cabal.config, this patches it, using yesodweb/yesod#1215
```
diff --git a/Formula/git-annex.rb b/Formula/git-annex.rb
index e34663e..1a32bae 100644
--- a/Formula/git-annex.rb
+++ b/Formula/git-annex.rb
@@ -27,16 +27,33 @@ class GitAnnex < Formula
   depends_on "gnutls"
   depends_on "quvi"
 
+  resource "yesod" do
+    url "https://github.com/yesodweb/yesod/archive/yesod/1.4.3.tar.gz"
+    sha256 "2beabbabcbc34e2523bea5f1f315292c1fe6bfb9ece369ff908b81cd57d52bc9"
+  end
+
   def install
-    install_cabal_package :using => ["alex", "happy", "c2hs"] do
-      # this can be made the default behavior again once git-union-merge builds properly when bottling
-      if build.with? "git-union-merge"
-        system "make", "git-union-merge", "PREFIX=#{prefix}"
-        bin.install "git-union-merge"
-        system "make", "git-union-merge.1", "PREFIX=#{prefix}"
+    resource("yesod").stage do
+      inreplace "yesod-core/Yesod/Core/Types.hs",
+                "import           Network.Wai.Logger                 (DateCacheGetter)",
+                "import           System.Date.Cache                  (DateCacheGetter)"
+      inreplace "yesod-core/yesod-core.cabal",
+                ", wai-logger            >= 0.2",
+                ", wai-logger            >= 0.2\n                   , date-cache"
+      buildpath.install "yesod-core"
+    end
+    cabal_sandbox do
+      cabal_sandbox_add_source "yesod-core"
+      install_cabal_package :using => ["alex", "happy", "c2hs"] do
+        # this can be made the default behavior again once git-union-merge builds properly when bottling.
+        if build.with? "git-union-merge"
+          system "make", "git-union-merge", "PREFIX=#{prefix}"
+          bin.install "git-union-merge"
+          system "make", "git-union-merge.1", "PREFIX=#{prefix}"
+        end
       end
+      bin.install_symlink "git-annex" => "git-annex-shell"
     end
-    bin.install_symlink "git-annex" => "git-annex-shell"
   end
 
   test do

```

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@timhowes @apjanke @zmwangx Upstream has fixed it, and CI succeeded.

**Comment by ilovezfs** [comment]
As I'd raised here https://github.com/Homebrew/legacy-homebrew/pull/50212#issuecomment-198208571 I was surprised the `Webapp` flag was removed. If you read the commit message in https://github.com/Homebrew/legacy-homebrew/pull/47950/commits the purpose was not to change the default, but to force the build to fail if something caused Webapp not to be supported, rather than allow for the possibility of Webapp becoming silently unsupported.

@csstaub @timhowes any thoughts on putting it back the way it was before we merge this?

**Comment by timhowes** [comment]
If the flag is already enabled, then does adding it actually change anything?

**Comment by ilovezfs** [comment]
Yes, as you can see the default is enabled for git-annex-5.20151218
(https://hackage.haskell.org/package/git-annex-5.20151218)

However, this issue occurred despite that: https://github.com/Homebrew/legacy-homebrew/issues/47346

Which was why @csstaub submitted this PR:
https://github.com/Homebrew/legacy-homebrew/pull/47950

Quoting his commit message,
>To address issue #47346 (git-annex-webapp missing), we explicitly
enable the "webapp" flag for git-annex. This should prevent git-annex
from being built without the webapp and make the build fail if there is
e.g. a dependency issue.

**Comment by csstaub** [comment]
I added the flag explicitly because the build would sometimes succeed, but silently not include the webapp functionality because some dependencies were missing. I haven't had time to dig into cabal to figure out how that happens. If you're dropping the flag, I would at least include a post-build test to make sure the webapp functionality is present to prevent https://github.com/Homebrew/legacy-homebrew/issues/47346 from re-occurring.

**Comment by apjanke** [comment]
Based on reading that history: Let's put the `webapp` flag back in with this PR and leave it in until there's confirmation on an upstream fix. It was already approved for inclusion; removing it seems to be asking for a silent regression.

**Comment by timhowes** [comment]
OK, so the flag helps by preventing the "backtracking" behavior in cabal:
https://www.haskell.org/cabal/users-guide/developing-packages.html#resolution-of-conditions-and-flags

In lieu of a test (or a way to disable backtracking), I'll add back the explicit flag.

**Comment by ilovezfs** [comment]
@timhowes Thank you for your contribution to Homebrew!

**Pull request closed without merging**
