### PR TITLE
buildifier 4.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
ERROR: /private/var/tmp/_bazel_brew/7a07f41d398974101452db9959c1717d/external/zlib/BUILD.bazel:31:11: Compiling inftrees.c failed: (Exit 1): wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 32 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 32 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
clang: error: unknown argument: '-fdebug-compilation-dir'
```

**Comment by chenrui333** [comment]
relates to https://github.com/bazelbuild/bazel/pull/12882

**Comment by carlocab** [comment]
@chenrui333 can you use the patch at https://github.com/bazelbuild/bazel/commit/58bb42ad7ca263a75c6eeef51482f805726663a5?

**Review by carlocab — APPROVED** [review]

**Comment by andig** [comment]
The patch cannot be applied:

```
==> Patching
141
==> Applying 58bb42a.patch
142
patch -g 0 -f -p1 -i /private/tmp/buildifier--patch-20210204-36590-1a2j5pl/58bb42a.patch
143
can't find file to patch at input line 27
144
Perhaps you used the wrong -p or --strip option?
```

**Pull request closed without merging**
