### PR TITLE
bdw-gc 8.0.2

### PR DESCRIPTION
**Pull request by Alhadis**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Released a [few hours ago](https://github.com/ivmai/bdwgc/releases/tag/v8.0.2).

### CODE REVIEW

**Comment by Moisan** [comment]
`rock` needs to have its revision bumped.

**Comment by Alhadis** [comment]
Okay, erm, is that how you do it...?

**Comment by Alhadis** [comment]
I pushed an amended commit. I figured you were going to squash-merge this, but if you prefer having two commits, no problem-o. 😉

> The reason we need to bump revision is to rebuild the formula bottle based on the new version of its dependency.

Yep, that's what I thought. Just wasn't sure about the nomenclature in question. =)

Thanks!

**Comment by Moisan** [comment]
Our policy in regard to squash-merge is to have one commit per file. So we squash multiple commits involving one file but keep different commits for different files.

**Comment by Moisan** [comment]
This issue with `rock` was preexisting. We're pushing to merge only green PR so we'll try to fix it first and resort to removing the formula as a last resort.

**Comment by Moisan** [comment]
We'll remove `rock` since it already fails on two platforms. I took the liberty of squashing your revision bump commit.

**Comment by Alhadis** [comment]
Is there something else that's required of me here?

**Comment by Moisan** [comment]
I forgot to remove the alias last time, this should be good now.

**Pull request closed without merging**
