### PR TITLE
cargo-udeps 0.1.31

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
Trying the upgrade to `openssl@3` and have it only for Linux, as for other rust packages.

**Comment by chenrui333** [comment]
for macOS builds
```
Undeclared dependencies with linkage: 
openssl@1.1
```

**Comment by Porkepix** [comment]
> for macOS builds
> 
> ```
> Undeclared dependencies with linkage: 
> openssl@1.1
> ```

Ok, rechanging the dependency to not only Linux and keeps `openssl@3` just to see, as Rust is supposed to be compatible with it and some other formulas were already updated to it without any issues.

**Comment by Porkepix** [comment]
Looks fine with `openssl@3` (don't know how the audit pick up the missing one then).

**Comment by Porkepix** [comment]
Should be good to merge?

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
