### PR TITLE
tomcat@10 10.0.2 (new formula)

### PR DESCRIPTION
**Pull request by moonfruit**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Tomcat 10 has been released, but it moves from Java EE 8 to Jakarta EE 9, and not compatible with previous versions.
Because Jakarta EE hasn't been used widely, so I think homebrew should remain formula `tomcat` at version 9 and add a versioned formula `tomcat@10`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
That's not really in line with the homebrew policy on versions. It's not used widely because it's new and if we make it difficult to install it'll never be widely used.

If it's an update it should be an update to the main formula.

**Comment by moonfruit** [comment]
If homebrew upgrade `tomcat` main formula to 10, It will make almost everyone's `tomcat` not working. They must install something like `tomcat@9`.

If homebrew's team is well with this, I will make a new commit that upgrade `tomcat` to 10 and add another `tomcat@9`.

**Comment by SMillerDev** [comment]
That is roughly what every major update for homebrew does. Please make sure version 9 will meet the requirements for versioned formula though: https://docs.brew.sh/Versions

**Comment by moonfruit** [comment]
OK, I made the commit that upgrade `tomcat` main formula to 10, add also add a `tomcat@9`. Please review, @SMillerDev.

**Review by SMillerDev — APPROVED** [review]
Thanks @moonfruit  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
