### PR TITLE
libxrender 0.9.11

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Will need to be requeued, I don't know what the cause of the linux cancellation was.

**Comment by SMillerDev** [comment]
Done

**Review by SMillerDev — DISMISSED** [review]

**Comment by SMillerDev** [comment]
Okay, lets try this again

**Comment by chenrui333** [comment]
openslide test failure is already addressed in #118939

**Review by cho-m — APPROVED** [review]

**Pull request closed without merging**
