### PR TITLE
tesseract 5.3.0

### PR DESCRIPTION
**Pull request by equal-l2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

`tesseract` is neural-network-based starting from version 4 and it bundles a bunch of tools useful for training a custom network.
With the change, the tools will also be installed with the main binary.

### CODE REVIEW

**Comment by equal-l2** [comment]
The failure is due to the timeout.
Can someone run the CI with ` CI-long-timeout` please?

**Comment by iMichka** [comment]
Rebased and running with long build label

**Comment by equal-l2** [comment]
5 formulae failed on test, which is caused by `qt`:
```
  CMake Error at qtwebengine/configure.cmake:63 (check_for_ulimit):
    Unknown CMake command "check_for_ulimit".
  Call Stack (most recent call first):
    qtbase/cmake/QtProcessConfigureArgs.cmake:242 (include)
```

It'll be fixed on qt 5.4.2.
https://bugreports.qt.io/browse/QTBUG-109046

**Comment by equal-l2** [comment]
#115926 seems to include the patch for the bug above, so let's wait until that PR is successfully merged.

**Comment by chenrui333** [comment]
need a rerun before the merge, the qt linux stuff would be addressed in that qt PR

**Comment by p-linnane** [comment]
Rebased and running with `ci-long-timeout`.

**Review by iMichka — DISMISSED** [review]

**Comment by SMillerDev** [comment]
Linux hit the 6hr limit, this will need a re-run.

**Review by SMillerDev — DISMISSED** [review]

**Comment by cho-m** [comment]
Cancelling Linux run as need to clean up old bottles on runner which caused build failure.

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
it has `icu4c` merge conflict

**Comment by equal-l2** [comment]
Should I do a rebase onto master?

**Comment by SMillerDev** [comment]
Let's wait until we get icu4c merged

**Comment by chenrui333** [comment]
5.3.0 release is in, while waiting for icu4c, we probably should bump this PR to use it.

**Review by chenrui333 — APPROVED** [review]

**Review by p-linnane — APPROVED** [review]

**Pull request closed without merging**
