### PR TITLE
node 11.13.0

### PR DESCRIPTION
**Pull request by dio-az**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
-----

### CODE REVIEW

**Comment by Moisan** [comment]
`npm` resource should be updated.

**Comment by Moisan** [comment]
Oops, just saw the previous `node` PR. So this is more of a question: does Node.js use a later version of npm than `6.7.0`?

**Comment by diogoazevedos** [comment]
@Moisan the [changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V11.md#2019-03-28-version-11130-current-targos) doesn't mention any `npm` update, so I believe that the current bundled version is `6.7.0`.

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
Thanks @diogoazevedos!

**Pull request closed without merging**
