### PR TITLE
mbedtls 2.25.0

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
10.15, 11.0:
```
Error: 7 failed steps!
brew install --verbose --build-bottle neko
brew install --build-from-source neko
brew install --only-dependencies --verbose --build-bottle haxe
brew install --verbose --build-bottle haxe
brew install --build-from-source haxe neko
brew install --only-dependencies --include-test hashlink
brew test --verbose hashlink
```

**Comment by carlocab** [comment]
@Rylan12 I think we have another case of missing bottles:
```
==> brew install --only-dependencies --include-test hashlink
==> FAILED
==> Downloading https://homebrew.bintray.com/bottles/neko-2.3.0_3.catalina.bottle.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "neko"
```

**Comment by carlocab** [comment]
I _think_ I've fixed `neko` now. It uses implicit function declarations while building. That'll have to be reported upstream.

**Comment by carlocab** [comment]
Ok, I think I understand the problem here.

It seems this can all be fixed by fixing the `neko` build failure. The problem is that `cmake` is looking for `libiconv`, but can no longer find it as it's checking the file system. This is why there are failures only on 11.0.

**Comment by Rylan12** [comment]
> @Rylan12 I think we have another case of missing bottles:

Interesting. The `neko` bottles aren't really missing. Because there was a revision bump for `neko`, the latest bottles haven't been uploaded yet. However, because `hashlink` depends on `neko`, it tried to install the _new_ neko version (2.3.0_3) from a bottle that doesn't yet exist.

I'm not sure if this is a CI bug or not. I don't totally understand all of `brew test-bot` so it's kind of hard to say. Maybe now that the `neko` build has been fixed CI will be able to use the source-version rather than the bottled (and nonexistent) version.

**Comment by carlocab** [comment]
Aha, you're right. It's _probably_ a bug, in that it doesn't make sense to look for bottles in circumstances where you know they're not going to be there. However, I think it's a minor enough one that isn't worth the effort to fix, as I think it emerges only when there are earlier errors in the CI run anyway.

Anyway, I hope I've fixed the `neko` build now, even on Big Sur, so it shouldn't be a problem. It's a bit of a dirty hack though. (Though I do think that every solution for this issue at the moment is going to be a dirty hack...)

**Comment by carlocab** [comment]
Ok. I solved one problem only to reveal another. Sigh.

**Comment by carlocab** [comment]
Oh, wait. Neko doesn't even have a Big Sur bottle. Guess that's #65000

**Comment by carlocab** [comment]
```
Error: 7 failed steps!
brew install --verbose --build-bottle neko
brew install --build-from-source neko
brew install --only-dependencies --verbose --build-bottle haxe
brew install --verbose --build-bottle haxe
brew install --build-from-source haxe neko
brew install --only-dependencies --include-test hashlink
brew test --verbose hashlink
```

@Rylan12 I think this should be good to merge? None of the 11.0 failures, `neko`, `haxe`, and `hashlink` have Big Sur bottles yet. #65000

As an aside, I think fixing `neko` should fix all three...

**Comment by carlocab** [comment]
Upstream report for `neko` build failure on Catalina: https://github.com/HaxeFoundation/neko/issues/215

**Review by Rylan12 — DISMISSED** [review]

**Comment by Rylan12** [comment]
Thanks, @carlocab!

Yeah, `neko` does seem to be the source of the problems here. Since they never worked on Big Sur, I agree this is okay to merge.

**Comment by Rylan12** [comment]
Ugh. Guess we can't merge without Big Sur bottles? I'll have to take a closer look when I've got more time later today...

**Comment by Rylan12** [comment]
@carlocab can you `disable!` `neko` (and, I guess, it's dependants) for Big Sur? That seems to be the way we want to handle these cases.

**Comment by carlocab** [comment]
Done. I set the date as the release date of Big Sur since that seems less arbitrary than any other.

**Comment by Rylan12** [comment]
@carlocab sorry, one more change here. Some other maintainers weighed in and reminded me that we can say:

```ruby
depends_on maximum_macos: :catalina
```

Although functionally very similar (possible identical?), I think this is preferred to a conditional disable.

This will also display a more accurate message when users try to install:

```console
$ brew install neko
neko: This formula either does not compile or function as expected on macOS
versions newer than Catalina due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

**Comment by carlocab** [comment]
Gotcha. Made it

    depends_on maximum_macos: [:catalina, :build]

as I tested the Catalina bottles locally, and tests passed for me. Or did you want to make it a hard dependency?

**Review by Rylan12 — DISMISSED** [review]

**Comment by Rylan12** [comment]
Looks good to me. I like the `[:catalina, :build]` solution to allow users to still use bottles. My only concern is that we won't remember to fix it, but since it's been reported upstream and in some of our issues I think it will be okay

**Comment by fxcoudert** [comment]
Regarding Big Sur, it's better to merge partial bottles (manually) than to add `maximum_macos` (which should be reserved for when upstream officially does not support building or running on a given macOS version).

For neko, it's not clear what is the specific Big Sur issue, please open a separate issue with them, including the build logs. Otherwise, it will not be fixed.

**Comment by Rylan12** [comment]
Sorry, @carlocab, mislead you a few times...

I'll remove those lines so we can get this through CI again and I'll merge manually when it's done (feel free to ping when that happens)

**Comment by carlocab** [comment]
Separate issue opened: https://github.com/Homebrew/homebrew-core/issues/66954

**Comment by carlocab** [comment]
```
Error: 2 failed steps!
brew install --verbose --build-bottle neko
brew install --build-from-source neko
```

`haxe` and `hashlink` failures went away for some reason?

@Rylan12 ping

**Comment by fxcoudert** [comment]
I'm on it… it will take some time and manual work, because some bottles have already been published in the previous attempts 😢

**Comment by Rylan12** [comment]
Thanks! I'll have time later to merge manually. Not sure how painful it will be so might take some time

**Comment by fxcoudert** [comment]
Done.

What's this sparkle thing?

**Comment by carlocab** [comment]
`/sparkle @user`

**Comment by SMillerDev** [comment]
They're a beta GitHub "thanks" feature that we enabled

**Comment by Rylan12** [comment]
Thanks again, @carlocab! (don't want to miss out on this sparkle action ✨😅)

**Comment by Rylan12** [comment]
Just curious, @fxcoudert, was it a big pain getting the bottles merged? It looked like `pr-pull` was failing when it encountered the missing Big Sur bottle. Did you just hack to ignore the error? Would a `brew pr-pull --ignore-missing-bottles` flag be helpful or is it not worth working on?

Sorry, I should have removed the old bottles from Bintray when they failed last time... that would have made it a tad easier I'm sure.

**Comment by fxcoudert** [comment]
@Rylan12  `brew pr-pull` worked fine locally. The only pain was removing the old bottles on Bintray

**Pull request closed without merging**
