### PR TITLE
psc-package: fix build and use ghc 8.10

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by dawidd6 — DISMISSED** [review]

**Comment by carlocab** [comment]
Can we use `ghc`? We don't have an ARM bottle for `ghc@8.10`.

**Comment by danielnachun** [comment]
I'm a bit confused.  We do seem to have an ARM bottle for GHC 8.10 but not for GHC 9.  I forgot to set `CI-force-arm` and I'm going to rerun with that to see if bottles on ARM.

**Comment by danielnachun** [comment]
Also, I wonder if this should be revision bumped because the binaries on all platforms are being built with a new compiler and will be different.

**Comment by danielnachun** [comment]
The ARM build worked with no issues.  We just need to decide if this should get a revision bump.

**Comment by danielnachun** [comment]
I pushed a revision bump because I think we need one after switching GHC versions.

**Comment by carlocab** [comment]
Do we? It's just a `:build` dependency, though.

**Comment by danielnachun** [comment]
That's true - is a revision bump only needed if the runtime dependencies have changed?

**Comment by carlocab** [comment]
A revision bump is needed if there are user-facing changes in the formula. Build-only changes usually aren't unless they fix bugs.

**Comment by danielnachun** [comment]
In that case I've removed the revision bump as there should not be any user-facing bugs.

**Review by SMillerDev — APPROVED** [review]

**Comment by carlocab** [comment]
ARM: https://github.com/Homebrew/homebrew-core/actions/runs/1311914349

Will need to dispatch Linux when that finishes.

**Comment by mitchblank** [comment]
At least right now we're also missing an Intel big_sur bottle for some reason?

**Comment by carlocab** [comment]
Yep, noticed that. I have a dispatch command queued for after the Linux one is finished.

**Comment by mitchblank** [comment]
Great.  If that succeeds would you mind trying a rebottle of `insect` next?  I don't know if it will succeed or not, but previous attempts failed due to `psc-package` being unavailable I think

**Pull request merged**
