### PR TITLE
jupyterlab: install and link jupyterlab, not only deps.

### PR DESCRIPTION
**Pull request by ivant**
Fixes:
- jupyterlab was being downloaded but not pip installed or linked.

Changes:
- Changed install to use virtualenv.
- Added a couple of tests to ensure that jupyterlab Python package
  and jupyter-lab binary are actually installed.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks @ivant for your contribution. Without people like you it would be impossible to maintain homebrew to the high standards people have come to expect of the project.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @ivant !!

**Comment by bubba** [comment]
@ivant Is there a way to install packages into the Jupyter kernel now? Packages previously installed via `pip3` no longer load

**Comment by ivant** [comment]
@bubba Can you give an example of how to reproduce the issue and the error messages? In general, it would be better to open a new bug for this.

**Comment by bubba** [comment]
@ivant running 

`pip3 install tensorflow`

And then inside a Jupyter notebook running

`import tensorflow`

Is enough to produce a `ModuleNotFoundError`

**Comment by bubba** [comment]
`sys.path` shows that it now looks for site-packages inside the virtual env used during installation rather than the one inside `/usr/local/Cellar/python`

**Comment by ivant** [comment]
@bubba It looks like `virtualenv` doesn't provide access to global site-packages by default on environment creation, see [here](https://github.com/pypa/virtualenv/blob/master/virtualenv.py#L635-L649). It can be overridden with `--system-site-packages` passed to `virtualenv`, unfortunately, current Homebrew code [doesn't seem to support it](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/language/python.rb#L197) (no way to instruct `venv.create` to pass that flag). That isn't hard to implement, but would need a change to `brew` and then another to `jupiterlab`; I can attempt it, though I can't commit on doing it quickly.

For now, there are two options that you can try:

1. _(Hacky)_ Remove the empty file that signals to Python to ignore the system-wide packages:

    ```
    rm -i /usr/local/Cellar/jupyterlab/1.2.3/libexec/lib/python*/no-global-site-packages.txt
    ```

2. (Possibly less convenient) Use `pip` inside the `jupyterlab` directory and install `tensorflow` confined to its environment:

    ```
    /usr/local/Cellar/jupyterlab/1.2.3/libexec/bin/pip3 install matplotlib
    ```

**Pull request closed without merging**
