### PR TITLE
neovim 0.6.1

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
PR created: 15 minutes ago

[Release tagged](https://github.com/neovim/neovim/releases/tag/v0.6.1): 5 minutes ago

suspicious

**Review by carlocab — APPROVED** [review]

**Comment by clason** [comment]
_very_ sus.

Only because the Windows build took such a long time (please don't add a `winbrew`...) ;)

**Comment by carlocab** [comment]
> (please don't add a `winbrew`...) ;)

Too late... https://docs.brew.sh/Installation#linux-or-windows-10-subsystem-for-linux

**Comment by clason** [comment]
Could be worse; could be full-blown MSVC builds...

**Pull request closed without merging**
