### PR TITLE
gnuplot 5.0.5

### PR DESCRIPTION
**Pull request by schoeps**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

and use c++11

This is relevant if compiling compiling `--with-qt5` and Xcode8.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@schoeps instead of manually slipping that in, you probably want `needs :cxx11 if build.with? "qt5"` together with `ENV.cxx11 if build.with? "qt5"`.

Also, I wonder if this should be `depends_on "qt5" => :recommended`. Any thoughts on that?

**Comment by MikeMcQuaid** [comment]
> Also, I wonder if this should be depends_on "qt5" => :recommended. Any thoughts on that?

@ilovezfs Would rather keep GUI stuff in packages as `:optional` wherever possible to vaguely maintain our ethos.

**Comment by ilovezfs** [comment]
it would be for the sake of the octave software not the ethos.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Octave needs a Qt5/GUI enabled gnuplot?

**Comment by ilovezfs** [comment]
```
          setenv('GNUTERM','qt')    # Requires QT; install gnuplot --with-qt5
```

**Comment by schoeps** [comment]
Well, but the user could change this setting in Octave. Nonetheless, qt is the most usable frontend of gnuplot on Mac.

**Comment by ilovezfs** [comment]
@schoeps do you mind converting this to a version bump PR? 5.0.5 was released.

@MikeMcQuaid Qt5 recommended seems appropriate since there's no Cask alternative to speak of.

**Comment by schoeps** [comment]
No problem, the new version is kind; all tests run through. I will happily enable qt5 once we have agreed on it.

**Comment by MikeMcQuaid** [comment]
@schoeps I've chatted with @ilovezfs and: let's add it back but keep it `:optional`.

**Comment by ilovezfs** [comment]
Thanks for the PR @schoeps :chart_with_upwards_trend:

**Pull request closed without merging**
