### PR TITLE
ice 3.7.8

### PR DESCRIPTION
**Pull request by externl**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
Not the latest release on GitHub: https://github.com/zeroc-ice/ice/releases/tag/v3.7.7

**Comment by externl** [comment]
https://github.com/zeroc-ice/ice/releases/tag/v3.7.8 is the latest release.

**Comment by carlocab** [comment]
Are you going to create one? Our tooling checks for the latest GitHub release for this formula via the `livecheck` block.

**Comment by externl** [comment]
Yes, but probably not until Monday now.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
