### PR TITLE
cockatrice: better dependency specification

### PR DESCRIPTION
**Pull request by tooomm**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

All listed dependencies are only required if building from source.

### CODE REVIEW

**Comment by tooomm** [comment]
Yep, there is a fixing pr in the upstream project already.
Will update here as soon as it's merged!

**Comment by tooomm** [comment]
`Unknown CMake command "qt5_use_modules".`
CMake error due to qt update to 5.11 is fixed on master upstream.

Also, added `mysql` as optional dependency.

**Comment by ilovezfs** [comment]
It's building the last stable tag not HEAD so what's fixed in upstream master wouldn't be relevant unless you backport the fix into the formula as a `patch do` block.

**Comment by tooomm** [comment]
You are totally right, my bad. Should have thought about that... 😄 
Will ping you here once a new version (with the fix included) is released.

**Comment by apjanke** [comment]
For posterity's sake, and so we have a link in this issue: the upstream PR is https://github.com/Cockatrice/Cockatrice/pull/3258.

**Comment by tooomm** [comment]
A new version with the qt fix is released.
I opened a separate PR for the version bump: https://github.com/Homebrew/homebrew-core/pull/29149

**Pull request closed without merging**
