### PR TITLE
dgraph 20.11.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
==== Need sudo access to install jemalloc
/bin/sh: /usr/bin/sudo: Operation not permitted
```

**Comment by carlocab** [comment]
Can we do `depends_on "jemalloc"` so it doesn't try to install its own?

**Comment by chenrui333** [comment]
yeah, let's try the old changes in the new release. 🤞

**Comment by carlocab** [comment]
Ah, yes, I just noticed you've tried it already 😅 I hope we have better luck this time!

**Comment by carlocab** [comment]
Ah, I have an idea

**Review by carlocab — APPROVED** [review]
🎉

**Comment by chenrui333** [comment]
Nice ;)

**Pull request closed without merging**
