### PR TITLE
nebula: add livecheck

### PR DESCRIPTION
**Pull request by jasikpark**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This PR sets up the nebula formula to detect new releases of the sofware automatically from the github releases

### CODE REVIEW

**Comment by jasikpark** [comment]
Seems like Github Actions are a bit angry today: https://githubstatus.com

**Comment by jasikpark** [comment]
force pushed to re-trigger ci

**Comment by jasikpark** [comment]
success 😁

**Comment by p-linnane** [comment]
Why do we need this? It doesn't look like upstream uses pre-releases or has any unusual tags. The default `:git` strategy is returning the current version as it is:
```
brew lc nebula
nebula: 1.6.1 ==> 1.6.1
```

**Comment by jasikpark** [comment]
ah, i didn't understand that the existence of a livecheck block was an override of default behavior, thx for the example of how it works by default 💜

**Comment by p-linnane** [comment]
If you'd like some furthur reading, here's a link to documentation about all of the existing default strategies: https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy

**Comment by jasikpark** [comment]
Thx!

**Pull request closed without merging**
