### PR TITLE
graphicsmagick 1.3.41

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by nandahkrishna — APPROVED** [review]

**Comment by mmuetzel** [comment]
It looks like Octave's test suite started to fail since this package was updated.
The failing tests are all related to .tif files with transparency.

See e.g.: https://github.com/gnu-octave/octave/actions/runs/5848434603/job/15855721314#step:13:88244

**Comment by mmuetzel** [comment]
See also this downstream report with a possible patch:
https://sourceforge.net/p/graphicsmagick/bugs/718/

**Comment by mmuetzel** [comment]
That patch was accepted upstream:
https://sourceforge.net/p/graphicsmagick/code/ci/a412298d004b8eb76400e0c897a6fe871f117f03/

@chenrui333: Would it be possible to cherry-pick that change for GraphicsMagick in Homebrew?
I don't have access to any Mac computer. So, I don't know how to test this properly before submitting a PR. But the CI for Octave is currently failing because of this.

**Comment by nandahkrishna** [comment]
@mmuetzel I've created a PR to patch `graphicsmagick` with your patch. Once merged, that should hopefully fix the  issues you're seeing.

**Comment by mmuetzel** [comment]
@nandahkrishna: I triggered the CI of Octave and the failing tests are passing again. 👍
Thank you very much for the swift reaction. 🚀

**Pull request merged**
