### PR TITLE
z3: remove outdated workaround

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This should have been fixed in 4.12.0. See Z3Prover/z3#6414.

### CODE REVIEW

**Review by ZhongRuoyu — DISMISSED** [review]

**Comment by carlocab** [comment]
We can also probably remove z3 from apache-arrow's dependencies.

**Comment by carlocab** [comment]
#128799

**Comment by carlocab** [comment]
Deps CI failed this time at `brew fetch standardese`. It timed out last time on Intel Big Sur, but succeeded everywhere else. No use rerunning this another time, I think.

**Comment by carlocab** [comment]
```
Error: The newest workflow run for #128704 is still in progress!
```
...It wasn't when I triggered it?

**Comment by ZhongRuoyu** [comment]
Sorry, it was me. I only wanted to be extra sure given the current low CI load. But yeah, let's move this along.

**Comment by carlocab** [comment]
Skipping dependents here. Nothing failed that was completed within the timeout.

**Review by ZhongRuoyu — DISMISSED** [review]

**Review by ZhongRuoyu — DISMISSED** [review]

**Pull request merged**
