### PR TITLE
go 1.15.5

### PR DESCRIPTION
**Pull request by mikehepple**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by tsuna** [comment]
Could we get this merged ASAP please? cc @chenrui333

**Comment by SMillerDev** [comment]
We always merge PRs as soon as possible, which is as soon as CI is green. Asking explicitly isn't going to help, resolving issues with the PR is going to help.

**Comment by mislav** [comment]
@SMillerDev I think someone from the Homebrew core team should look at this, since none of the CI failures look related nor caused by the Go upgrade.

<details>
<summary>cig formula failures</summary>

```
==> brew fetch --retry cig
==> brew install --build-from-source --only-dependencies cig
==> brew install --build-from-source cig
==> FAILED
==> Downloading https://github.com/stevenjack/cig/archive/v0.1.5.tar.gz
==> Downloading from https://codeload.github.com/stevenjack/cig/tar.gz/v0.1.5
==> godep restore
Last 150 lines from /Users/brew/actions-runner/_work/homebrew-core/homebrew-core/bottles/logs/cig/01.godep:
2020-11-13 00:22:58 +0000

godep
restore

Warning: ARNING]: godep should only be used inside a valid go package directory and
Warning: ARNING]: may not function correctly. You are probably outside of your $GOPATH.
Warning: ARNING]:	Current Directory: /private/tmp/cig-20201113-76226-1dk7ddb/cig-0.1.5
Warning: ARNING]:	$GOPATH: /private/tmp/cig-20201113-76226-1dk7ddb/cig-0.1.5
godep: WARNING: Godep workspaces (./Godeps/_workspace) are deprecated and support for them will be removed when go1.8 is released.
godep: WARNING: Go version (go1.15) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
godep: Dep (github.com/codegangsta/cli) restored, but was unable to load it with error:
	Package (errors) not found
godep: Dep (github.com/fatih/color) restored, but was unable to load it with error:
	Package (fmt) not found
godep: Dep (github.com/mitchellh/go-homedir) restored, but was unable to load it with error:
	Package (bytes) not found
godep: Dep (github.com/shiena/ansicolor) restored, but was unable to load it with error:
	Package (bytes) not found
godep: Dep (gopkg.in/yaml.v2) restored, but was unable to load it with error:
	Package (bytes) not found
godep: Error checking some deps.

READ THIS: https://docs.brew.sh/Troubleshooting


==> brew fetch --retry cig
==> brew install --only-dependencies cig
==> brew install cig
==> brew install --only-dependencies cig
==> brew linkage --test cig
==> brew install --only-dependencies --include-test cig
==> brew test --retry --verbose cig
==> brew uninstall --force cig
```
</details>

<details>
<summary>"found no classes" failures</summary>

```
==> brew fetch --retry direnv
==> FAILED
Error: No available formula with the name "direnv" 
In formula file: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/direnv.rb
Expected to find class Direnv, but found no classes.

==> brew fetch --retry direnv
==> FAILED
Error: No available formula with the name "direnv" 
In formula file: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/direnv.rb
Expected to find class Direnv, but found no classes.

==> brew fetch --retry dive
==> FAILED
Error: No available formula with the name "dive" 
In formula file: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/dive.rb
Expected to find class Dive, but found no classes.
```
</details>

**Comment by SMillerDev** [comment]
The "found no classes" ones are weird and I'll see if I can find anything there. But the other formulae failing should be verified that it isn't caused by the go upgrade by checking if it also happens in an independent PR.

**Comment by dawidd6** [comment]
```
==> brew install --build-from-source hasura-cli
==> FAILED
==> Downloading https://github.com/hasura/graphql-engine/archive/v1.3.3.tar.gz
==> Downloading from https://codeload.github.com/hasura/graphql-engine/tar.gz/v1.3.3
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "hasura-cli"
Download failed: https://github.com/hasura/graphql-engine/archive/v1.3.3.tar.gz
```
Looks like upstream took down this release, it isn't available anymore.

**Comment by chenrui333** [comment]
yeah, I would vote for the direct merge. This is just a patch version bump. We can fix the failed formulae in the following PRs.

**Comment by mikehepple** [comment]
This release fixes a critical security vulnerability so if there's any way to get this out we'd appreciate it!

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
proceed with a merge. thanks all!

**Comment by chenrui333** [comment]
looks like the catalina bottle was never there. 
image

**Comment by chenrui333** [comment]
Since the catalina machine can fallback to use mojave bottles, there is no outstanding issue to use go 1.15.5. Thanks!

**Pull request closed without merging**
