### PR TITLE
ack: move to a subdirectory.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
We are planning on sharding homebrew/core's `Formula` directory into subdirectories. `ack` is a good first candidate:

- I use it so will notice if it's 💔 
- it is not upgraded often
- it's a simple, quick install
- it's used a bit (590th in 365d) but not loads or a little

See also (and should probably wait for being in a release) https://github.com/Homebrew/brew/pull/15811

Equivalent homebrew-cask PR https://github.com/Homebrew/homebrew-cask/pull/152314

### CODE REVIEW

**Comment by chenrui333** [comment]
it would be just some syntax update, right?

**Comment by carlocab** [comment]
> it would be just some syntax update, right?

No, we should check that bottles build correctly.

**Comment by chenrui333** [comment]
I see, make sense.

**Comment by MikeMcQuaid** [comment]
> No, we should check that bottles build correctly.

They look correct (same checksum on Linux) but looks like at some point we broke our ability to generate `all:` bottles as the tarball differs on all macOS platforms (in exactly the same way).

**Comment by MikeMcQuaid** [comment]
> They look correct (same checksum on Linux) but looks like at some point we broke our ability to generate `all:` bottles as the tarball differs on all macOS platforms (in exactly the same way).

Fixed by https://github.com/Homebrew/brew/pull/15819 🎉

**Review by fxcoudert — APPROVED** [review]

**Pull request merged**
