### PR TITLE
folly: fix build on 10.12 and 10.11 with Xcode 8

### PR DESCRIPTION
**Pull request by ilovezfs**
Cf. https://github.com/facebook/folly/pull/488.

### CODE REVIEW

**Comment by ilovezfs** [comment]
See
https://github.com/facebook/folly/issues/486
https://github.com/facebook/folly/issues/482
https://github.com/facebook/folly/issues/484
https://github.com/Homebrew/homebrew-core/issues/5426

**Comment by yschimke** [comment]
Since the fix landed https://github.com/facebook/folly/commit/a34e06a196443023c4b5fe2c18579996565e57f1

This workaround is now breaking "brew install --HEAD folly"

**Comment by ilovezfs** [comment]
@yschimke perhaps you can encourage them to put out a new release :)

**Comment by yschimke** [comment]
I think there is a new release, is that what you need?

https://github.com/facebook/folly/releases

**Comment by ilovezfs** [comment]
@yschimke yup thanks for the heads up!

**Comment by ilovezfs** [comment]
@yschimke unfortunately it looks like while it's fixed for 10.12, it still fails to build on 10.11 + Xcode 8 :(

**Comment by ilovezfs** [comment]
@yschimke this gets it to work on 10.11 + Xcode 8 too: https://github.com/Homebrew/homebrew-core/pull/6024

**Pull request closed without merging**
