### PR TITLE
llvm 3.9.1

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
llvm 3.9.1 bugfix release

### CODE REVIEW

**Comment by ilovezfs** [comment]
Let's make sure the formulae that depend on this `=> :build` can still build successfully before merging this.

**Comment by ilovezfs** [comment]
Apparently `nvc` is already broken, which is not new to this release, but
```
  CXXLD    bin/nvc
Undefined symbols for architecture x86_64:
  "_LLVMLinkModules", referenced from:
      _link_context_bc_fn in libcgen.a(lib_libcgen_a-link.o)
     (maybe you meant: _LLVMLinkModules2)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [bin/nvc] Error 1
make: *** [all] Error 2
```

**Comment by ilovezfs** [comment]
Rust's `--with-llvm` option is also broken, but is also a preexisting issue: https://gist.github.com/ilovezfs/1eb14b90948d2079bb6e5abdaeac6a5f

**Comment by ilovezfs** [comment]
Thanks @JCount!

**Comment by JCount** [comment]
Thanks for doing the more extensive testing/verification @ilovezfs! I was trying to verify that the optional reverse dependencies that seemed to be broken were broken before the version bump, but was having limited success in that area.

**Comment by ilovezfs** [comment]
@JCount you're welcome. Unfortunately, in the case of nvc, it's not optional. It's => :build :(

**Comment by JCount** [comment]
I wonder why the bot was 🍏 then. Does the bot not test `:build` dependencies @ilovezfs?

**Comment by ilovezfs** [comment]
@JCount correct. That's why we get to find out about all the boost and gcc and ... breakage after the fact unless someone does "manual CI" for the build-time deps.

**Comment by JCount** [comment]
I will keep that in mind for the future. 👍

**Pull request closed without merging**
