### PR TITLE
harfbuzz 2.3.1

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Let's remove that Octave java test

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
On High Sierra,

```
16:16:38 ==> brew install gnome-builder
16:17:47 ==> FAILED
16:17:47 ==> Downloading https://homebrew.bintray.com/bottles/gnome-builder-3.28.4.high_sierra.bottle.tar.gz
16:17:47 Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/b2f7300e70e5fdaef84177b99d1547df08d6001ad92cac05c4f5c0de1cfa2cb8--gnome-builder-3.28.4.high_sierra.bottle.tar.gz
16:17:47 ==> Pouring gnome-builder-3.28.4.high_sierra.bottle.tar.gz
16:17:47 Error: Failed changing install name in /usr/local/Cellar/gnome-builder/3.28.4/lib/gnome-builder/libgnome-builder-plugins.dylib
16:17:47   from @@HOMEBREW_PREFIX@@/opt/json-glib/lib/libjson-glib-1.0.0.dylib
16:17:47     to /usr/local/opt/json-glib/lib/libjson-glib-1.0.0.dylib
16:17:47 Error: Unrecognized Mach-O magic: 0x00
16:17:47 Warning: Bottle installation failed: building from source.
```

cc @woodruffw for opinions

And when it tried to build from source, we got another error,

```
16:17:47 ==> meson --prefix=/usr/local/Cellar/gnome-builder/3.28.4 -Dwith_git=true -Dwith_autotools=true -Dwith_history=true -Dwith_webkit=false -Dwith_clang=false -Dwith_devhelp=false -Dwith_flatpak=false -Dwith_sysprof=false -Dwith_vapi=false -Dwith_vala_pack=false -Dwith_qemu=false -Dwith_safe_path=/usr/local/bin:/usr/bin:/bin ..
16:17:47 Last 150 lines from /Users/brew/Jenkins/workspace/core/logs/gnome-builder/01.meson:
16:17:47 2019-02-01 08:17:44 +0000
16:17:47 
16:17:47 meson
16:17:47 --prefix=/usr/local/Cellar/gnome-builder/3.28.4
16:17:47 -Dwith_git=true
16:17:47 -Dwith_autotools=true
16:17:47 -Dwith_history=true
16:17:47 -Dwith_webkit=false
16:17:47 -Dwith_clang=false
16:17:47 -Dwith_devhelp=false
16:17:47 -Dwith_flatpak=false
16:17:47 -Dwith_sysprof=false
16:17:47 -Dwith_vapi=false
16:17:47 -Dwith_vala_pack=false
16:17:47 -Dwith_qemu=false
16:17:47 -Dwith_safe_path=/usr/local/bin:/usr/bin:/bin
16:17:47 ..
16:17:47 
16:17:47 Fatal Python error: initsite: Failed to import the site module
16:17:47 ValueError: source code string cannot contain null bytes
16:17:47 
16:17:47 Current thread 0x00007fff8d4b7380 (most recent call first):
```

cc @tschoonj for opinions

**Comment by tschoonj** [comment]
This is something rather exotic... I will revise this next week, `gnome-builder` is quite outdated anyway and I will try to build the latest release with the latest vanilla `meson`....

**Comment by lembacon** [comment]
The CI is now mysteriously back to normal. 😅

Merging.

**Pull request closed without merging**
