### PR TITLE
libxml2 2.10.0

### PR DESCRIPTION
**Pull request by owine**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
This seems to have broken `xmlsec1`, which in turn broke `aqbanking` and `lasso`. Not sure if a rebuild will help.

**Comment by carlocab** [comment]
Seems to still be there, and hasn't been touched in decades: https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/xmlIO.c#L2177

**Comment by carlocab** [comment]
Let's try a rebuild.

**Comment by Bo98** [comment]
> Seems to still be there, and hasn't been touched in decades: https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/xmlIO.c#L2177

It'll be because of https://gitlab.gnome.org/GNOME/libxml2/-/commit/a0a0f3be93753e387e31e7de95904a24b3c876dd.

If we have dependents using it, it may be worth enabling it again.

**Comment by carlocab** [comment]
Let's see if rebuilding `libxmlsec1` works first. It may not actually need FTP support -- it's just using it because it found a `libxml2` that had it at build-time.

**Comment by carlocab** [comment]
Network error while trying to install `gdal` dependencies on Catalina. Not worth a re-run, I think.

**Review by carlocab — DISMISSED** [review]
Ok to rebuild `libxmlsec1`, @Bo98? Or would you rather re-enable FTP?

**Comment by carlocab** [comment]
I've opened some PRs for the Linux failures by they all look unrelated.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
