### PR TITLE
scrcpy 1.11

### PR DESCRIPTION
**Pull request by rom1v**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Upgrade to v1.11 just released (not tested, I have no macOS).

### CODE REVIEW

**Comment by SMillerDev** [comment]
Homebrew also works on Linux 😁.

Is the pre-built server no longer a jar file?

**Comment by rom1v** [comment]
> Homebrew also works on Linux

Oh, I didn't know that :+1:

However, it must still be tested on macOS. For example, building on Linux v1.10 worked, but on macOS it didn't work initially: https://github.com/Homebrew/homebrew-core/pull/42810

> Is the pre-built server no longer a jar file?

It's a jar file, but without extension anymore: https://github.com/Genymobile/scrcpy/commit/3da95b52bd21ae0f4d81ee933caea63b78191deb

**Comment by SMillerDev** [comment]
Thanks for the pull request @rom1v. Without people like you, even if they don't test their work 😉, it would be impossible to maintain homebrew to the high standards people have come to expect of the project.

**Comment by rom1v** [comment]
Homebrew helps me a lot to distribute scrcpy on macOS :+1: (it's easy for users)

And the process of updating a formula is simple enough that I can do it myself :ok_hand:

> even if they don't test their work :wink:

:smile: (to be fair, I did my part of manual testing before releasing v1.11 :wink:)

**Pull request closed without merging**
