### PR TITLE
libzip 1.2.0

### PR DESCRIPTION
**Pull request by s172262**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by s172262** [comment]
Many errors caused because "libzip 1.2.0" builds libzip.5.dylib against "libzip 1.1.2" building libzip.4.dylib.

**Comment by ilovezfs** [comment]
You'll need to revision bump those.

**Comment by JCount** [comment]
@s172262 This needs to be rebased on the current master, do you want to do it, or should I?

**Comment by JCount** [comment]
Thank you for contributing to Homebrew @s172262!! 🎆

**Pull request closed without merging**
