### PR TITLE
chezmoi 2.38.0

### PR DESCRIPTION
**Pull request by osalbahr**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by osalbahr** [comment]
```console
$ brew bump chezmoi
==> chezmoi
Current formula version:  2.37.0
Latest livecheck version: 2.38.0
Latest Repology version:  2.37.0
Open pull requests:       chezmoi 2.38.0 (https://github.com/Homebrew/homebrew-core/pull/140078)
Closed pull requests:     none
```

Latest is still https://github.com/twpayne/chezmoi/releases/tag/v2.37.0. Not sure why `livecheck` thought otherwise?

```console
$ brew livecheck chezmoi
chezmoi: 2.37.0 ==> 2.38.0
```

**Comment by p-linnane** [comment]
Livecheck is using the default `:git` strategy, which just grabs git tags. We should use the `:github_latest` strategy here if there is a delay between tagging and release.

**Comment by twpayne** [comment]
Please do use the `:github_latest` strategy.

chezmoi's release process is triggered by pushing a new tag. This release process occasionally fails for reasons beyond chezmoi's control, which may require changes to chezmoi and pushing a new tag.

homebrew-core should instead pick up the latest release from [chezmoi's Releases page](https://github.com/twpayne/chezmoi/releases).

**Comment by p-linnane** [comment]
Thanks for jumping in @twpayne. I'll push that here.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
