### PR TITLE
jpeg 9b

### PR DESCRIPTION
**Pull request by galexite**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

jpeg 9b

### CODE REVIEW

**Comment by DomT4** [comment]
Heh. Right off the bat, fair warning, people have attempted this before & ran away once they realised exactly what this entails.

It's not as simple as just bumping the version. You also need to:

* Bump the formula `revision` for _everything_ that is flagged by `brew uses jpeg`. That's 72 formulae in the core alone.
* Prepare PRs for `homebrew/science`, Python, Games, X11 & Versions with `revision` bumps for all formulae using `jpeg` in those taps as well, but _don't_ push that PR until the core PR is shipped.

If you're willing to put the effort in here, we'd absolutely love that, but this is not as simple as updating the one formula sadly.

**Comment by georgewhite5** [comment]
OK. I searched all GitHub pull requests on this repository for 'jpeg' as I wondered if 'jpeg' was held back for a reason. This must have been before the separation of 'brew' and 'homebrew-core'.

**Comment by DomT4** [comment]
Yeah. There was an ongoing discussion between Dec 2014 & Jan 2016 about getting it done, along with some initial attempts, but I think potentially everyone quit before even reaching the "file a PR" stage.

Sadly `jpeg` being incredibly widely used combined with the breaking releases has made bumping this a fairly huge deal.

**Comment by georgewhite5** [comment]
According to a simple find, the following formulae depend on jpeg (in some way):

```
./Formula/analog.rb
./Formula/argyll-cms.rb
./Formula/center-im.rb
./Formula/dcraw.rb
./Formula/devil.rb
./Formula/djvulibre.rb
./Formula/efl.rb
./Formula/epeg.rb
./Formula/fbida.rb
./Formula/fdroidserver.rb
./Formula/ffmpegthumbnailer.rb
./Formula/flactag.rb
./Formula/fltk.rb
./Formula/fontforge.rb
./Formula/freeswitch.rb
./Formula/gd.rb
./Formula/gdal.rb
./Formula/gdk-pixbuf.rb
./Formula/gegl.rb
./Formula/gnuplot.rb
./Formula/gocr.rb
./Formula/gource.rb
./Formula/gpac.rb
./Formula/gphoto2.rb
./Formula/graphicsmagick.rb
./Formula/gst-plugins-good.rb
./Formula/gst-plugins-ugly.rb
./Formula/htmldoc.rb
./Formula/imagemagick.rb
./Formula/imageworsener.rb
./Formula/imlib2.rb
./Formula/io.rb
./Formula/jasper.rb
./Formula/jp2a.rb
./Formula/jpeginfo.rb
./Formula/jpegoptim.rb
./Formula/jpegrescan.rb
./Formula/leptonica.rb
./Formula/libagar.rb
./Formula/libbpg.rb
./Formula/libgaiagraphics.rb
./Formula/libgeotiff.rb
./Formula/libgxps.rb
./Formula/libpano.rb
./Formula/libquicktime.rb
./Formula/libsvg.rb
./Formula/libtiff.rb
./Formula/libuvc.rb
./Formula/libwmf.rb
./Formula/links.rb
./Formula/little-cms.rb
./Formula/little-cms2.rb
./Formula/logstalgia.rb
./Formula/mal4s.rb
./Formula/mapnik.rb
./Formula/minidlna.rb
./Formula/mitmproxy.rb
./Formula/mjpegtools.rb
./Formula/mpv.rb
./Formula/open-scene-graph.rb
./Formula/openslide.rb
./Formula/pdf2htmlex.rb
./Formula/podofo.rb
./Formula/poppler.rb
./Formula/povray.rb
./Formula/qemu.rb
./Formula/sane-backends.rb
./Formula/sdl2_image.rb
./Formula/sdl_image.rb
./Formula/sfml.rb
./Formula/swftools.rb
./Formula/swi-prolog.rb
./Formula/tiff2png.rb
./Formula/ufraw.rb
./Formula/vice.rb
./Formula/vncsnapshot.rb
./Formula/volatility.rb
./Formula/webp.rb
./Formula/wine.rb
./Formula/wxmac.rb
./Formula/x11vnc.rb
./Formula/xplanet.rb
./Formula/zbar.rb
```

That's 83 in 'homebrew-core' only.

**Comment by DomT4** [comment]
Yes, `brew uses jpeg` doesn't include `:optional` or `:build` dependencies automatically, which accounts for the difference.

**Comment by ilovezfs** [comment]
@DomT4 would it be better to have the new and old version coexist in core for a while, as with qt and qt5, so that this doesn't need to be done in one monolithic PR?

**Comment by DomT4** [comment]
It's difficult here. We do already actually have a `jpeg9` formula in `homebrew/versions`.

The problem is, much like the upcoming OpenSSL 1.1.0 release (_whenever it does come_) having potentially both `jpeg 8x` and `jpeg 9x` in the same recursive dependency tree could cause some strange behaviour given they aren't compatible.

`jpeg` is so widespread that a misstep could be a complete nightmare 😕.

**Comment by ilovezfs** [comment]
@DomT4 Can those trees be separated into discrete branches?

**Comment by ilovezfs** [comment]
@DomT4 491 formulae in core: https://gist.github.com/ilovezfs/58e8b7340fe33a6915cb25170afb6ec6
```
brew uses --recursive --include-build --include-optional jpeg|grep -v homebrew
```

**Comment by DomT4** [comment]
I'm unsure how much crossover there is between `jpeg`-using formulae. Lots, I suspect.

Would be interesting to see how many standalone formulae only have the one `jpeg` in the recursive tree & could be updated, but I'm already fearing that wouldn't be a big number in proportion. It is incredibly prolific.

**Comment by ilovezfs** [comment]
@DomT4 these are the 37 standalones:
```
analog
argyll-cms
center-im
epeg
fdroidserver
flactag
freeswitch
gocr
gource
gst-plugins-ugly
htmldoc
imageworsener
io
jpeginfo
jpegoptim
jpegrescan
libagar
libbpg
libgxps
libuvc
links
logstalgia
mal4s
mapnik
minidlna
mitmproxy
mjpegtools
mpv
pdf2htmlex
povray
qemu
swftools
tiff2png
vice
vncsnapshot
volatility
x11vnc
```

**Comment by ilovezfs** [comment]
You can remove these 20 from that list if you also want to exclude anything with a dependency that itself also has jpeg as a dependency.
```
analog
argyll-cms
freeswitch
gocr
gource
gst-plugins-ugly
imageworsener
io
libgxps
links
logstalgia
mal4s
mapnik
minidlna
mjpegtools
mpv
pdf2htmlex
povray
qemu
tiff2png
```

**Comment by ilovezfs** [comment]
So that leaves these 17 with that restriction too:
```
center-im
epeg
fdroidserver
flactag
htmldoc
jpeginfo
jpegoptim
jpegrescan
libagar
libbpg
libuvc
mitmproxy
swftools
vice
vncsnapshot
volatility
x11vnc
```

**Comment by ilovezfs** [comment]
@DomT4 So here are some findings on those 17. The ones with problems were
```
flactag: only built with jpeg 8

libbpg: segfaults with both jpeg 8 and 9

mitmproxy: fine but would need libtiff rebuilt as well (undeclared dep)

swftools:
  a) segfault when running the command without any args (appears unrelated to jpeg 8 vs 9
  b) the test do is wrong (returns zero but the output file needs to specified with -o); currently it's just reporting file not found instead of doing the test.

vice: wouldn't build (appears unrelated to jpeg 8 vs 9):
Undefined symbols for architecture x86_64:
  "_Gestalt", referenced from:
      _platform_get_macosx_runtime_os in libplatform.a(platform_macosx.o)

volatility: wouldn't build:
ValueError: --enable-zlib requested but zlib not found, aborting.
```

**Comment by apjanke** [comment]
That's few enough issues that it seems like the upgrade is technically feasible. But someone still needs to do the work of revision-bumping everything in multiple taps and wrangling all the tests. @georgewhite5 are you interested in pursuing that? If not, let's close this out, because we can't merge it without that.

**Comment by ilovezfs** [comment]
@apjanke those are *only* the issues with the ones that are standalone (relevant if we temporarily had two separate versions of the formula to make the transition more manageable). There are probably a few million more issues with the ones that aren't standalone.

**Comment by DomT4** [comment]
Yeah. I really think this is worth putting off until we have the new version system in place, which I think is the only sane way we're going to be able to get this done, so I'm going to actually close here for now. Thank you nonetheless for the submission @georgewhite5; appreciate the willingness ❤️.

**Pull request closed without merging**
