### PR TITLE
gel: prevent failure if rdiscount updated

### PR DESCRIPTION
**Pull request by yjukaku**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
It should definitely fail if the replacement is no longer needed though.

**Comment by yjukaku** [comment]
@SMillerDev Thanks for reviewing the PR. Unfortunately, I don't really understand how the backwards compatibility story works for formulas. But I can tell you that gel@v3.0.0 (the current stable version on Homebrew) has

```
rdiscount (2.2.0.1)
```

in its `Gemfile.lock`.

The HEAD version of gel, `0.8.0.pre1`, has

```
rdiscount (2.2.0.2)
```

in its `Gemfile.lock`

I don't really understand why the formula has that `inreplace` call anyways 🤷‍♂️ , but then again, I'm not familiar with how formulas/updates work with Homebrew.

**Comment by yjukaku** [comment]
Ah, OK. I took a closer look at the formula's git history and it's clearly explained here 😅 :

https://github.com/Homebrew/homebrew-core/commit/56a71aff4c15b7386df030e1087f87185fa31df5

> The "rdiscount" dependency doesn't build on Big Sur; this was fixed
in its 2.2.0.2 version:
>  https://github.com/davidfstr/rdiscount/commit/48cf5d5b3818943adc76728aaaf5b40b6ab9825b
>
> The upstream "gel" package has already switched to using 2.2.0.2
> so this can be removed in the next update:
>  https://github.com/gel-rb/gel/commit/4a404cabba66b040087964216d9f8ecbf4a7cf16
>
> Closes https://github.com/Homebrew/homebrew-core/pull/70722.

I suppose we could either merge this PR, which would allow for the pre-release/HEAD version of `gel` to be installed properly, or we could just wait until that pre-release version becomes the stable release. 🤷‍♂️

**Comment by Bo98** [comment]
Could do a `unless build.head?` so that when the next stable version is released, we'll remember to remove the line entirely.

**Pull request closed without merging**
