### PR TITLE
opentsdb 2.4.0

### PR DESCRIPTION
**Pull request by bfontaine**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
No `configure`

**Comment by fxcoudert** [comment]
@bfontaine Please note in several cases failing like this PR: we prefer to build from the uploaded tarballs by maintainers (like `https://github.com/OpenTSDB/opentsdb/releases/download/v2.4.0/opentsdb-2.4.0.tar.gz`) rather than autogenerated ones from github (which sometimes miss generated files).

**Comment by bfontaine** [comment]
Yep of course; I forgot this case when writing my [auto-discover-updates-to-formulae-that-are-hosted-on-github script](https://github.com/bfontaine/homebrew-tools/blob/master/cmd/brew-checkupdates.rb), hence all those "cannot find `./configure`” errors. I’ll fix it for the next batch.

**Comment by bfontaine** [comment]
Test fails because there’s an issue with upstream’s `create_table.sh`: https://github.com/OpenTSDB/opentsdb/issues/1481

**Pull request closed without merging**
