### PR TITLE
go 1.17.5

### PR DESCRIPTION
**Pull request by Porkepix**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
Why were tests cancelled?

**Comment by bevanjkay** [comment]
@Loyalsoldier Tests have a timeout of 60 minute unless maintainers allow longer CI runs, to ensure CI machines aren't blocked by too many long runs.

**Comment by carlocab** [comment]
We already have two long-running CI jobs at the moment. A third one is going to cause huge delays, so we can restart this when those jobs are done.

**Comment by kidoman** [comment]
Go 1.17.4 is now officially released. It fixes a nasty crash on mac OS Monterey (apparent kernel bug.) How can I help get this released?

**Comment by SMillerDev** [comment]
Check all the failing dependent formulae and help fix them

**Comment by gonzaloserrano** [comment]
@SMillerDev where can we see that list?

**Comment by Loyalsoldier** [comment]
您好，邮件已收到。

**Comment by SMillerDev** [comment]
In the pull request "Checks"

**Comment by iMichka** [comment]
I opened a PR for `imgproxy` and `bosh-cli`: #90670, #90669

**Comment by jidicula** [comment]
fyi Go 1.17.5 was just released. Does that mean this PR should be closed and a new one opened?

**Comment by SMillerDev** [comment]
This one can also be updated

**Comment by stefanb** [comment]
Most of tests
> exceeded the maximum execution time of 60 minutes.

**Comment by stefanb** [comment]
🤔 Q: why do all dependancies need to be checked and rebuilt? 
Yes, it is true, that they depend on go, but upgrading go will not break them, as those binaries are already built and statically linked with NO external dependancies on go. They will continue to be functioning as before. 

I have noticed this problem with the last few go upgrades, most notably with the major revisions, eg #83413 with a huge list of fixes to dependants, which should be up to dependants to sort out, and giving them upgraded go binary would actually help them detect and fix those problems earlier.

**Comment by SMillerDev** [comment]
> Yes, it is true, that they depend on go, but upgrading go will not break them, as those binaries are already built and statically linked with NO external dependancies on go. They will continue to be functioning as before.

But how will we know they don't break with the newest Go version if we don't try and build them with that version?

> I have noticed this problem with the last few go upgrades, most notably with the major revisions, eg #83413 with a huge list of fixes to dependants, which should be up to dependants to sort out, and giving them upgraded go binary would actually help them detect and fix those problems earlier.

It is up to dependents to sort out, but if nobody checks if it works how would they ever know?

> and giving them upgraded go binary would actually help them detect and fix those problems earlier.

They can always run CI with pre-release Go builds to see if their software will stop working soon. Depending on Homebrew to suddendly break your build when you upgrade is just lazy and irrisponsible engineering.

**Comment by stefanb** [comment]
> > Yes, it is true, that they depend on go, but upgrading go will not break them, as those binaries are already built and statically linked with NO external dependancies on go. They will continue to be functioning as before.
> 
> But how will we know they don't break with the newest Go version if we don't try and build them with that version?

Do we _need_ to know that when upgrading Go? Yes it is _nice_ to know, but _not essential_ for go upgrade and that can be dealt with later. Their current, already build version won't be affected in any way way.

> > I have noticed this problem with the last few go upgrades, most notably with the major revisions, eg #83413 with a huge list of fixes to dependants, which should be up to dependants to sort out, and giving them upgraded go binary would actually help them detect and fix those problems earlier.
> 
> It is up to dependents to sort out, but if nobody checks if it works how would they ever know?

It will become obvious when somebody will eventually want to build the new dependant binary (either same or newer version, locally or when trying to bump the version in homebrew).

> > and giving them upgraded go binary would actually help them detect and fix those problems earlier.
> 
> They can always run CI with pre-release Go builds to see if their software will stop working soon. Depending on Homebrew to suddendly break your build when you upgrade is just lazy and irrisponsible engineering.

Yes, it is chicken and egg problem in a way, but current approach is blocking gradual evolution progress.

**Comment by andig** [comment]
I think we've had the argument before and it is probably better suited for discussions. I'd suggest here: https://github.com/Homebrew/discussions/discussions/2618

**Comment by iMichka** [comment]
- [ ] vgrep: #91180
- [ ] vault: #91181
- [ ] traefik@1: #91164
- [ ] skaffold: #91182

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Let's ship this. A few issues have been fixed, I'll make a second pass for `go` 1.17.6 ...

**Comment by iMichka** [comment]
Thanks @Porkepix for the pull request.

**Comment by AlekSi** [comment]
Thanks, everyone

**Pull request closed without merging**
