### PR TITLE
unisonlang M4g

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by p-linnane** [comment]
`12-arm64` ran for 3 and a half hours, `11-arm64` was over 12 hours. Something obviously hung there.

**Comment by chenrui333** [comment]
give another run.

**Comment by chenrui333** [comment]
that doesn't look right
image

**Comment by chenrui333** [comment]
let's see how it goes this time.

**Comment by chenrui333** [comment]
removing `long build` label as it should not need much time to build/test, [previous workflow run](https://github.com/Homebrew/homebrew-core/actions/runs/4096553737/jobs/7067922659)

**Review by p-linnane — APPROVED** [review]

**Pull request closed without merging**
