### PR TITLE
Added patch for https://bugs.kde.org/show_bug.cgi?id=381815

### PR DESCRIPTION
**Pull request by catap**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Is it a common crash or a very specific setup? We try to ship something as close to upstream as possible, unless bugs affect relatively common cases.

**Comment by catap** [comment]
@fxcoudert, it's a good question! I don't know :)

Anyway, I tried first time run valgrind at my machine and it crashed, so, I reported and fixed it.

But I'm not sure have I changed limits or haven't.  Can you show `ulimit -a` in console from you machine?

Because if I decrease it to 1024 it works fine.

**Comment by fxcoudert** [comment]
On both machines I tried (10.12 and 10.13, pretty much default installation), `ulimit -n` gives 256. If it doesn't trigger on a default setup, I say we don't patch it.

**Comment by fxcoudert** [comment]
Tried it on a 10.12 machine with default setup, valgrind works fine. I am closing this PR as “too localised to patch”.

**Comment by catap** [comment]
@fxcoudert any way I expect that it soon will be inside valgrind :)

**Pull request closed without merging**
