### PR TITLE
Secure URL(s) (1/2)

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`qemu` has an open PR with conflicting updates: https://github.com/Homebrew/homebrew-core/pull/14756, though this one resolves the removed test resource in a non-intrusive, yet secure way, plus this one secures the HEAD URL as well, so I recommend it over the open PR.

Unsure how to fix this in `qemu` though: "Description should start with a capital letter"

UPDATE: `qemu` removed.

### CODE REVIEW

**Comment by JCount** [comment]
@vszakats I am in the process of fixing `qemu`, the current issue that I am about to resolve is that 10.10's system curl cannot download the new test resource over HTTPS.

**Comment by vszakats** [comment]
@JCount Does this also happen with the `archive.org` URL (which points to the original test resource) in this patch?:
```diff
-    url "http://download.qemu.org/arm-test-0.2.tar.gz"
+    url "https://web.archive.org/web/20160514112837/wiki.qemu.org/download/arm-test-0.2.tar.gz"
```

**Comment by JCount** [comment]
I fixed it by simply mirroring it on bintray. The test file is only 820KB.

**Comment by vszakats** [comment]
Bintray used to be working, but anyhow if you think so, try it with this patch, it uses the same old image (~3MB with the old hash) and `archive.org` has a great chance to work well.

I'm removing `qemu` from this patch to avoid the conflict.

**Pull request merged**
