### PR TITLE
tasksh 1.1.0

### PR DESCRIPTION
**Pull request by kmarekspartz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/pull/4553. I guess they didn't include the fix yet.

**Comment by ilovezfs** [comment]
Yeah this is the exact same tarball from September when I closed the original PR. So closing this until there's actually a new tarball from upstream that isn't broken.

**Comment by zeckalpha** [comment]
"Broken" isn't well defined. It's working well enough for me, and they announced the release https://taskwarrior.org/news/news.20160905.2.html

**Comment by ilovezfs** [comment]
It doesn't pass the test block and hangs due to https://git.tasktools.org/projects/EX/repos/tasksh/commits/ccd21f4060ef5b73d096616bc1e80650947ffc32

**Comment by ilovezfs** [comment]
@zeckalpha If you throw in the patch from https://github.com/Homebrew/homebrew-core/pull/4553 I'll merge this since there was a release announcement.

**Comment by ilovezfs** [comment]
Patch url is https://raw.githubusercontent.com/Homebrew/formula-patches/71c6658/tasksh/tasksh-1.1.0-fix-hang.patch

**Comment by ilovezfs** [comment]
@zeckalpha I've added the patch for you.

**Comment by zeckalpha** [comment]
Awesome, thanks.

**Comment by ilovezfs** [comment]
@zeckalpha :rocket: 

Thanks for your contribution to Homebrew!

**Pull request closed without merging**
