### PR TITLE
juju 2.3.1

### PR DESCRIPTION
**Pull request by nskaggs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by battlemidget** [comment]
Just FYI, ive got a new version of juju-wait PR'd and waiting for that to merge. Once complete, I'll update my conjure-up package to rely on that runtime and remove the symlink conflict. From there this recipe should build without fail.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please
@battlemidget I see juju-wait was merged, what is the status on conjure-up?

**Comment by battlemidget** [comment]
@fxcoudert updating that this am

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Thanks @nskaggs for the pull request!

**Pull request closed without merging**
