### PR TITLE
atk: fix glib-utils

### PR DESCRIPTION
**Pull request by lukaso**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by lukaso** [comment]
Looks like a timeout. Not sure how to fix that as seems to be a CI error.

**Comment by SMillerDev** [comment]
It's timing out because the build takes too long, you're better off spliting the PR

**Comment by lukaso** [comment]
Done. !106668

**Comment by lukaso** [comment]
It looks like there are too many dependent formulas for the tests to complete in time.

**Comment by lukaso** [comment]
@cho-m is there more I need to do here to get this one merged? Thanks.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
