### PR TITLE
serialosc: fix `python3` references.

### PR DESCRIPTION
**Pull request by miles170**
See #110462.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by miles170** [comment]
```
  ../third-party/libuv/src/unix/thread.c: In function ‘thread_stack_size’:
  ../third-party/libuv/src/unix/thread.c:194:24: error: comparison of integer expressions of different signedness: ‘rlim_t’ {aka ‘long unsigned int’} and ‘long int’ [-Werror=sign-compare]
    194 |       if (lim.rlim_cur >= PTHREAD_STACK_MIN)
        |                        ^~
  ../third-party/libuv/src/unix/thread.c: In function ‘uv_thread_create_ex’:
  ../third-party/libuv/src/unix/thread.c:242:20: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘long int’ [-Werror=sign-compare]
    242 |     if (stack_size < PTHREAD_STACK_MIN)
```

**Comment by miles170** [comment]
> ```
>   ../third-party/libuv/src/unix/thread.c: In function ‘thread_stack_size’:
>   ../third-party/libuv/src/unix/thread.c:194:24: error: comparison of integer expressions of different signedness: ‘rlim_t’ {aka ‘long unsigned int’} and ‘long int’ [-Werror=sign-compare]
>     194 |       if (lim.rlim_cur >= PTHREAD_STACK_MIN)
>         |                        ^~
>   ../third-party/libuv/src/unix/thread.c: In function ‘uv_thread_create_ex’:
>   ../third-party/libuv/src/unix/thread.c:242:20: error: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘long int’ [-Werror=sign-compare]
>     242 |     if (stack_size < PTHREAD_STACK_MIN)
> ```

Upstream has already fixed this by [unix: don't allow too small thread stack size](https://github.com/libuv/libuv/commit/b5fa965bcb169f36ae58ebc35a48d85835f9756e)

**Comment by miles170** [comment]
@carlocab How should I patch the `libuv` submodule, `inreplace` or `patch`?

**Comment by carlocab** [comment]
Oh, this builds its own `libuv`. Not cool. Is there a way to use the `libuv` formula?

**Review by danielnachun — APPROVED** [review]

**Pull request closed without merging**
