### PR TITLE
iozone: fix checksum

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
relates to #88329

### CODE REVIEW

**Comment by iMichka** [comment]
See also: #87302

**Comment by iMichka** [comment]
Did you notify upstream?

**Comment by iMichka** [comment]
Ping @chenrui333 . If you did not contact upstream, let me know and I'll do it.

**Comment by iMichka** [comment]
I've sent upstream an email.

**Comment by chenrui333** [comment]
Thanks @iMichka!

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Upstream confirmed that this was a retag by email. No functional change. Merging.

**Comment by chenrui333** [comment]
Thanks @iMichka!

**Pull request closed without merging**
