### PR TITLE
imapsync 1.977

### PR DESCRIPTION
**Pull request by NikolausDemmel**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
I tried to install this, but I'm still on 10.12, so cannot use the bottle.

OK, so I don't know much about Perl, but this is what I tried so far:

1. The from source install before this PR fails, b/c there was a new release and the current version was moved to https://imapsync.lamiral.info/dist2/old_releases/1.945/imapsync-1.945.tgz. 
2. So I tried `brew bump-formula-pr` with the new release. While building the formula, it complained about missing `Encode::IMAPUTF7` module, so I added that.
3. Now the formula built, but when running `imapsync`, it complained about missing modules. Step by step I added `Socket6`, `IO::Socket::INET6`, and `Digest::HMAC_SHA1`.
4. With the added modules, the executable starts, but it crashes immediately with a `segmentation fault`. Maybe it's related to my of macos version.
5. I went back to the previous version if imapsync, with the updated url. There I also needed the `Socket6`, `IO::Socket::INET6`, and `Digest::HMAC_SHA1` modules compared to the current formula (not `Encode::IMAPUTF7`). However I also get the segmentation fault. At this point I suspect too old Perl on 10.12.
6. Looks like a similar story to #42235, not sure why #45488 was successful. Maybe newer macos version.

I think I'll have to give up and just use my linux box for this...

**Comment by Bo98** [comment]
> but it crashes immediately with a `segmentation fault`

Does it work with Homebrew Perl uninstalled?

**Comment by NikolausDemmel** [comment]
> Does it work with Homebrew Perl uninstalled?

Aha! Yes, after `brew unlink perl` the updated version seems to run:

```
$ imapsync  --testslive

[...]

Detected 0 errors

This imapsync is up to date. ( local 1.977 >= official 1.977 )( Use --noreleasecheck to avoid this release check. )
Homepage: https://imapsync.lamiral.info/
# Entering tests_live_result()
Live tests ended successfully
# Leaving  tests_live_result()
Exiting with return value 0 (EX_OK: successful termination) 0/50 nb_errors/max_errors
Log file is LOG_imapsync/2020_03_30_14_10_19_692_test1_test2.txt ( to change it, use --logfile filepath ; or use --nolog to turn off logging )
```

Can we easily specify that this formula should use system perl oven if the homebrew perl is installed?

**Comment by NikolausDemmel** [comment]
Just two notes for future reference:

1. The official Darwin binary seems to also work for me: https://imapsync.lamiral.info/dist2/imapsync_bin_Darwin
2. With brewed perl unlinked, I we don't seem to need the addition of `Socket6`, `IO::Socket::INET6`, and `Digest::HMAC_SHA1`, only `Encode::IMAPUTF7` (which is actually mentioned as a new dependency in the release notes).

**Comment by Bo98** [comment]
>Can we easily specify that this formula should use system perl oven if the homebrew perl is installed?

In the next version of Homebrew, 2.2.12, we will have a `rewrite_shebang detected_perl_shebang, "imapsync"` which can be used. It will make sure the correct version of Perl is used.

In the meantime, you can use `inreplace "imapsync", "#!/usr/bin/env perl", "#!/usr/bin/perl"` just before the `bin.install`.

**Comment by NikolausDemmel** [comment]
Thanks!

I tried with `rewrite_shebang`, but even after `brew update` I get this:

```
Error: An exception occurred within a child process:
  NameError: undefined local variable or method `detected_perl_shebang' for #<Formulary::FormulaNamespace9573767f2b8f88c83459e9d3be06a591::Imapsync:0x00007fcb6c8f43e8>
```

Anyway, for now I updated the formula with the suggested `inreplace`. Works for me.

**Review by Bo98 — APPROVED** [review]

**Pull request closed without merging**
