### PR TITLE
fnm: bottle big_sur_arm64

### PR DESCRIPTION
**Pull request by pckilgore**
@Schniz Not sure if you can do this without having an M1 on which to build.

- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks, @pckilgore. Bottled in 1ac7ae8187f27f2c8b3a16cefaccd9eb9cb7936a.

**Comment by pckilgore** [comment]
@carlocab 

I'm getting 404's on `brew install` for the arm bottle.  Worried I did something wrong here...

```
$ brew install fnm
==> Downloading https://homebrew.bintray.com/bottles/fnm-1.24.0_1.arm64_big_sur.bottle.1.t
##O#- #
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "fnm"
Download failed: https://homebrew.bintray.com/bottles/fnm-1.24.0_1.arm64_big_sur.bottle.1.tar.gz
```

**Comment by carlocab** [comment]
You need to revert your local changes to the formula. Try
```sh
brew update
git -C $(brew --repo homebrew/core) reset --hard origin/master
```

**Comment by pckilgore** [comment]
Well, I knew I messed something up 🙃 .  That got it, thanks.

**Pull request closed without merging**
