### PR TITLE
ipython@5: move to python3

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
It's this version still actively supported by upstream?

**Comment by bayandin** [comment]
`ipython@5` — the last version with `python@2` support, so it's ok to delete them together: https://ipython.readthedocs.io/en/stable/whatsnew/version5.html

**Comment by alebcay** [comment]
`ipython` 5.x is currently the LTS release, and it compiles fine with `python` 3. I have not seen anything to suggest that it's actually not supported any longer.

Unless the sole reason that `ipython@5` exists in this repo is for `python@2` compatibility, I see no reason for its deletion, seeing as it compiles just fine.

**Comment by bayandin** [comment]
> Unless the sole reason that `ipython@5` exists in this repo is for `python@2` compatibility, I see no reason for its deletion, seeing as it compiles just fine.

I think so. 

In general, I don't mind to keep this formula, but if it's possible to remove, I'm for removing

**Comment by alebcay** [comment]
> In general, I don't mind to keep this formula, but if it's possible to remove, I'm for removing

If the 5.x branch is no longer LTS/does not stay as LTS after the new year, then the right move would be to delete it, since we only carry the most recent version and older ones that are still supported.

**Comment by chenrui333** [comment]
Looking good for the merge?

**Comment by Bo98** [comment]
Tried to find a policy upstream, the closest I could find was [this](https://blog.jupyter.org/release-of-ipython-5-0-8ce60b8d2e8e) in 2016:

> With IPython, we usually only offer support for a single major release at a time; once a new major release comes out, previous major releases stop getting bug fixes. For the 5.x series releases we are making an exception to that rule: until the end of 2017 the core team will do its best to provide fixes for critical bugs in the 5.x release series. Beyond that, we will deprioritise this work, but we will continue to accept pull requests from the community to fix bugs through 2018 and 2019, and make releases when necessary.

**Comment by SMillerDev** [comment]
So, delete it with python2 then.

**Pull request closed without merging**
