### PR TITLE
Remove deprecated ENV.java_cache

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

RE: https://github.com/Homebrew/brew/pull/3109.
CC @DomT4

### CODE REVIEW

**Comment by DomT4** [comment]
I was planning on waiting for a new tag to save any mess with from-source non-developer installations but if you’re happy to move ahead I’m cool with it. Thanks for chasing up!

**Comment by ilovezfs** [comment]
New tag will probably be today or tomorrow so it's not going to make much difference either way, but I can wait on merging if it's a concern.

**Comment by ilovezfs** [comment]
Eww that sbt failure is ugly https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/7879/version=sierra/console

**Comment by ilovezfs** [comment]
Looks like it's a regression. So that may well be a bug with your PR but I haven't bisected it yet.

**Comment by ilovezfs** [comment]
```
0cb6307f2d5207c794760727df579cd8015b23e9 is the first bad commit
commit 0cb6307f2d5207c794760727df579cd8015b23e9
Author: Dominyk Tiller <dominyktiller@gmail.com>
Date:   Thu Aug 31 00:09:14 2017 +0100

    ENV: move java_cache to compat for future hard deprecation

:040000 040000 40c7893402c5b3c90d2e8fd30473c3e692293a43 a6a15029e6b4efd06981216fcc0429a8327e0265 M	Library
```
So we may need to revert.

**Comment by ilovezfs** [comment]
Ah it's because the test is unconditionally setting and replacing _JAVA_OPTIONS, not adding to it.

**Comment by ilovezfs** [comment]
So all of these need to be tweaked too
```
ammonite-repl.rb
16:    ENV["_JAVA_OPTIONS"] = "-Duser.home=#{testpath}"

apache-flink.rb
20:    ENV["_JAVA_OPTIONS"] = "-Djava.io.tmpdir=#{testpath} -Duser.home=#{testpath}"

civl.rb
23:    ENV["_JAVA_OPTIONS"] = "-Duser.home=#{testpath}"

jenkins-lts.rb
50:    ENV.append "_JAVA_OPTIONS", "-Djava.io.tmpdir=#{testpath}"

jenkins.rb
60:    ENV["_JAVA_OPTIONS"] = "-Djava.io.tmpdir=#{testpath}"

jetty-runner.rb
20:    ENV.append "_JAVA_OPTIONS", "-Djava.io.tmpdir=#{testpath}"

pmd.rb
19:    ENV["_JAVA_OPTIONS"] = "-Duser.home=#{buildpath}/java_user_home"

sbt.rb
41:    ENV["_JAVA_OPTIONS"] = "-Dsbt.log.noformat=true"

sbt@0.13.rb
44:    ENV["_JAVA_OPTIONS"] = "-Dsbt.log.noformat=true"
```

**Comment by ilovezfs** [comment]
And we have problems with these too:
```
Formula/antlr@3.rb:55:    ENV.prepend "CLASSPATH", "#{share}/java/antlr3.jar", ":"
Formula/grails@2.5.rb:23:    ENV["JAVA_HOME"] = `/usr/libexec/java_home`.chomp
Formula/hbase.rb:29:    ENV.java_cache if build.with? "lzo"
Formula/hbase.rb:48:        ENV["CPPFLAGS"] = "-I/System/Library/Frameworks/JavaVM.framework/Versions/Current/Headers"
Formula/jsvc.rb:23:    ENV.append "CPPFLAGS", "-I/System/Library/Frameworks/JavaVM.framework/Versions/Current/Headers"
Formula/libreadline-java.rb:23:    java_home = ENV["JAVA_HOME"]
Formula/libreadline-java.rb:36:      ENV["JAVAINCLUDE"] = "#{java_home}/include"
Formula/libreadline-java.rb:37:      ENV["JAVANATINC"]  = "#{java_home}/include/darwin"
Formula/libreadline-java.rb:39:      ENV["JAVAINCLUDE"] = "/System/Library/Frameworks/JavaVM.framework/Versions/Current/Headers/"
Formula/libreadline-java.rb:40:      ENV["JAVANATINC"]  = "/System/Library/Frameworks/JavaVM.framework/Versions/Current/Headers/"
Formula/libreadline-java.rb:49:      s.change_make_var! "JAVAINCLUDE", ENV["JAVAINCLUDE"]
Formula/libreadline-java.rb:50:      s.change_make_var! "JAVANATINC", ENV["JAVANATINC"]
Formula/mesos.rb:99:    # skip build javadoc because Homebrew sandbox ENV.java_cache
Formula/pmd.rb:30:            <version>#{ENV["JAVA_HOME"][/((\d\.?)+)\.\d/, 1]}</version>
Formula/pmd.rb:33:            <jdkHome>#{ENV["JAVA_HOME"]}</jdkHome>
Formula/pmd.rb:42:            <jdkHome>#{ENV["JAVA_HOME"]}</jdkHome>
Formula/sleuthkit.rb:31:    ENV.java_cache if build.with? "jni"
Formula/subversion@1.8.rb:106:    ENV.deparallelize if build.with? "java"
Formula/tee-clc.rb:23:    ENV["TF_ADDITIONAL_JAVA_ARGS"] = "-Duser.home=#{ENV["HOME"]}"
Formula/tomcat-native.rb:25:                            "--with-java-home=#{ENV["JAVA_HOME"]}",
Formula/upscaledb.rb:61:      args << "JDK=#{ENV["JAVA_HOME"]}"
```

**Comment by DomT4** [comment]
> So all of these may need to be tweaked too

Aye, anything that sets `_JAVA_OPTIONS` in-formula should probably switch to using `ENV.prepend "_JAVA_OPTIONS"` rather than stealing the whole string.

Sorry for the delay, had to sleep & then deal with life. Will check out the comment you left over in `brew`.

**Pull request merged**
