### PR TITLE
knot 2.6.0

### PR DESCRIPTION
**Pull request by oerdnj**
Signed-off-by: Ondřej Surý <ondrej@sury.org>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by oerdnj** [comment]
There's error linking knot-resolver, but that's right, the SONAMEs have been bumped. Is there anything I need to do to fix that?

**Comment by apjanke** [comment]
Sounds like the dependent `knot-resolver` formula needs a `revision` increment to handle this. That will cause `knot-resolver` to be rebuilt against the new `knot` and pick up the new SO version.

Add a `revision 1` line to `Formula/knot-resolver.rb` after the `head` line to this PR (as a separate commit, with comment "knot-resolver: revision bump for knot"). Grep the `Formula/` directory for "revision" if you need examples, or feel free to ask more questions here.

**Comment by oerdnj** [comment]
Ah, I see. It need to go together in one MR.

**Comment by ilovezfs** [comment]
Thank you @oerdnj!

**Pull request closed without merging**
