### PR TITLE
terragrunt 0.17.2

### PR DESCRIPTION
**Pull request by sc250024**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Glide has been remove from the project https://github.com/gruntwork-io/terragrunt/commit/8e36e0c2c84e14cf483ea97253c1760f0a87e13b so the build process needs to be revised.

**Comment by sc250024** [comment]
@fxcoudert Since the binaries for macOS are already pre-built as part of Terragrunt's releases (https://github.com/gruntwork-io/terragrunt/releases), is it possible to simply download the binaries? Or does Brew require building for all packages?

**Comment by fxcoudert** [comment]
@sc250024 Homebrew core only hosts formulas that build from source

**Comment by sc250024** [comment]
@fxcoudert Alright, clear. @javian I'm not sure what exactly needs to be changed as the Terragrunt, and I'm having some trouble running certain Brew commands after upgrading to Mojave. Should I close the PR? Or, if you know what needs to be modified, I can simply make those changes, and push. Either way is fine.

**Comment by javian** [comment]
The docs say `Terragrunt uses dep, a vendor package management tool for golang.` so I would start there as assume that glide has been replaced by dep. Not familiar with go so that's about as far as I can go.

**Comment by javian** [comment]
You might see how its done in one of the other formulas that use dep such as https://github.com/Homebrew/homebrew-core/blob/master/Formula/immortal.rb

**Comment by sc250024** [comment]
@javian I think that did the trick. I'm a Go-n00b, so let me know if that's "dirty".

**Comment by fxcoudert** [comment]
This is looking good, thanks @sc250024

**Pull request closed without merging**
