### PR TITLE
exiftool: update livecheck

### PR DESCRIPTION
**Pull request by rgoldberg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by samford — COMMENTED** [review]
The `exiftool` formula uses the latest version that's listed as a production release on the [upstream History page](https://exiftool.org/history.html). The `ver.txt` file contains the version of the newest release, regardless of whether it's a production release or not. At present, the file contains `12.69` but the current production release is 12.60, so the `livecheck` block in this PR would only be suitable if the formula used non-production releases as well.

-----

In the future, please explain your changes in the PR description, so that maintainers don't have to guess your intention. When it comes to `livecheck` blocks, I like to see a description of what's wrong (e.g., with an existing `livecheck` block or livecheck's default behavior) and what the PR aims to address.

**Review by singingwolfboy — APPROVED** [review]

**Comment by chenrui333** [comment]
@rgoldberg looks like the cpan file did not get updated, https://metacpan.org/dist/Image-ExifTool

**Comment by samford** [comment]
> @rgoldberg looks like the cpan file did not get updated, https://metacpan.org/dist/Image-ExifTool

I may not have been clear but this PR should _not_ have been merged, as the `ver.txt` file doesn't return the latest production version of `exiftool`. CPAN only has the production versions, so it's no surprise that 12.69 (a non-production version) is not available there.

I will open a PR in a moment to revert the `livecheck` block.

**Comment by chenrui333** [comment]
thanks @samford, make sense!

**Pull request merged**
