### PR TITLE
or-tools 9.3

### PR DESCRIPTION
**Pull request by Dekker1**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
```
  /tmp/or-tools-20220317-45591-pb4gbn/or-tools-9.3/ortools/lp_data/lp_parser.cc:267:7: error: no matching function for call to 'Consume'
    if (RE2::Consume(sp, *kNamePattern1, consumed_name)) return TokenType::NAME;
        ^~~~~~~~~~~~
```

**Comment by Dekker1** [comment]
It seems that the [release notes](https://github.com/google/or-tools/releases/tag/v9.3) refer to `Google re2 2021-11-01`, which is one version older than the version in Homebrew. This function is maybe removed in newer versions.

**Comment by cho-m** [comment]
The function still exists and (from quick skim through) I didn't see any related changes between versions.

Error is specifically that `or-tools` function call doesn't match declaration:
```
/opt/homebrew/include/re2/re2.h:421:15: note: candidate function template not viable: no known conversion from 'absl::string_view *' (aka 'basic_string_view<char> *') to 're2::StringPiece *' for 1st argument
    static bool Consume(StringPiece* input, const RE2& re, A&&... a) {
                ^
```

It might be that they are expecting `re2` to have been compiled with C++17 features (we only set C++11) as that will add support for `string_view`.

**Comment by cho-m** [comment]
Looks like `or-tools` is patching `re2` to modify `StringPiece` to `absl::string_view`: https://github.com/google/or-tools/blob/v9.3/patches/re2-2021-11-01.patch

Pretty much means we can't compile with system `re2` right now. May need to use bundled copy.

**Pull request closed without merging**
