### PR TITLE
macvim: set -fdeclspec only for clang

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by SeekingMeaning — DISMISSED** [review]

**Comment by fxcoudert** [comment]
Actually I'm wondering why we have to set `-fdeclspec` manually, doesn't ruby have a way to let vim/macvim/weechat know what flags it needs?

**Comment by iMichka** [comment]
Agreed that setting flags manually is not really portable. The 3 upstreams should add the flags themselves.

**Comment by fxcoudert** [comment]
vim has added it: https://github.com/vim/vim/commit/864a28b6a6ae4f1a56e230be26bc6d13e3f8b3d9

**Comment by iMichka** [comment]
The change made it to mccvim with https://github.com/vim/vim/commit/864a28b6a6ae4f1a56e230be26bc6d13e3f8b3d9
I added a comment that the hack can be removed after the next release.

**Pull request merged**
