### PR TITLE
sip 4.19.13

### PR DESCRIPTION
**Pull request by Noctem**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
The bintray mirror doesn't exist yet but I updated the version in the URL anyways, is that the way to handle this?

### CODE REVIEW

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by SMillerDev** [comment]
> The bintray mirror doesn't exist yet but I updated the version in the URL anyways, is that the way to handle this?

Yes it is, thanks

**Comment by SMillerDev** [comment]
@BrewTestBot test this please!

**Comment by chenrui333** [comment]
@BrewTestBot test this please!

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
- The `visp` failure is about post-install in `shared-mime-info`, so I don't think it requires a `visp` revision bump.
- Upstream have moved the sources, I've opened a PR for the latest version: https://github.com/Homebrew/homebrew-core/pull/44965

**Pull request closed without merging**
