### PR TITLE
mupdf 1.11

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Full Disclosure: I uninstalled `x11` after I left Homebrew, so I haven't tested this locally.

### CODE REVIEW

**Comment by DomT4** [comment]
Ugh, of course 👀.

**Comment by ilovezfs** [comment]
after deparallelizing the build,
```
clang -Wall -ffunction-sections -fdata-sections -pipe -O2 -DNDEBUG -fomit-frame-pointer  -Iinclude -Igenerated -Iscripts/freetype -Ithirdparty/freetype/include -Ithirdparty/harfbuzz/src -Ithirdparty/jbig2dec   -Iscripts/libjpeg -Ithirdparty/libjpeg  -Ithirdparty/mujs -Ithirdparty/openjpeg/src/lib/openjp2 -Ithirdparty/zlib -o build/release/source/gprf/gprf-doc.o -c source/gprf/gprf-doc.c
clang -Wall -ffunction-sections -fdata-sections -pipe -O2 -DNDEBUG -fomit-frame-pointer  -Iinclude -Igenerated -Iscripts/freetype -Ithirdparty/freetype/include -Ithirdparty/harfbuzz/src -Ithirdparty/jbig2dec   -Iscripts/libjpeg -Ithirdparty/libjpeg  -Ithirdparty/mujs -Ithirdparty/openjpeg/src/lib/openjp2 -Ithirdparty/zlib -o build/release/source/gprf/gprf-skeleton.o -c source/gprf/gprf-skeleton.c
rm -f build/release/libmupdf.a
xcrun ar cr build/release/libmupdf.a build/release/source/fitz/archive.o build/release/source/fitz/bbox-device.o build/release/source/fitz/bidi-std.o build/release/source/fitz/bidi.o build/release/source/fitz/bitmap.o build/release/source/fitz/buffer.o build/release/source/fitz/colorspace.o build/release/source/fitz/compressed-buffer.o build/release/source/fitz/context.o build/release/source/fitz/crypt-aes.o build/release/source/fitz/crypt-arc4.o build/release/source/fitz/crypt-md5.o build/release/source/fitz/crypt-sha2.o build/release/source/fitz/device.o build/release/source/fitz/directory.o build/release/source/fitz/document-all.o build/release/source/fitz/document.o build/release/source/fitz/draw-affine.o build/release/source/fitz/draw-blend.o build/release/source/fitz/draw-device.o build/release/source/fitz/draw-edge.o build/release/source/fitz/draw-glyph.o build/release/source/fitz/draw-mesh.o build/release/source/fitz/draw-paint.o build/release/source/fitz/draw-path.o build/release/source/fitz/draw-scale-simple.o build/release/source/fitz/draw-unpack.o build/release/source/fitz/error.o build/release/source/fitz/filter-basic.o build/release/source/fitz/filter-dct.o build/release/source/fitz/filter-fax.o build/release/source/fitz/filter-flate.o build/release/source/fitz/filter-jbig2.o build/release/source/fitz/filter-leech.o build/release/source/fitz/filter-lzw.o build/release/source/fitz/filter-predict.o build/release/source/fitz/filter-sgi.o build/release/source/fitz/filter-thunder.o build/release/source/fitz/font.o build/release/source/fitz/ftoa.o build/release/source/fitz/function.o build/release/source/fitz/geometry.o build/release/source/fitz/getopt.o build/release/source/fitz/glyph.o build/release/source/fitz/halftone.o build/release/source/fitz/harfbuzz.o build/release/source/fitz/hash.o build/release/source/fitz/image.o build/release/source/fitz/jmemcust.o build/release/source/fitz/link.o build/release/source/fitz/list-device.o build/release/source/fitz/load-bmp.o build/release/source/fitz/load-gif.o build/release/source/fitz/load-jpeg.o build/release/source/fitz/load-jpx.o build/release/source/fitz/load-jxr.o build/release/source/fitz/load-png.o build/release/source/fitz/load-pnm.o build/release/source/fitz/load-tiff.o build/release/source/fitz/memento.o build/release/source/fitz/memory.o build/release/source/fitz/noto.o build/release/source/fitz/outline.o build/release/source/fitz/output-cbz.o build/release/source/fitz/output-pcl.o build/release/source/fitz/output-png.o build/release/source/fitz/output-pnm.o build/release/source/fitz/output-ps.o build/release/source/fitz/output-pwg.o build/release/source/fitz/output-svg.o build/release/source/fitz/output-tga.o build/release/source/fitz/output.o build/release/source/fitz/path.o build/release/source/fitz/pixmap.o build/release/source/fitz/pool.o build/release/source/fitz/printf.o build/release/source/fitz/separation.o build/release/source/fitz/shade.o build/release/source/fitz/stext-device.o build/release/source/fitz/stext-output.o build/release/source/fitz/stext-paragraph.o build/release/source/fitz/stext-search.o build/release/source/fitz/store.o build/release/source/fitz/stream-open.o build/release/source/fitz/stream-prog.o build/release/source/fitz/stream-read.o build/release/source/fitz/string.o build/release/source/fitz/strtod.o build/release/source/fitz/strtof.o build/release/source/fitz/svg-device.o build/release/source/fitz/tempfile.o build/release/source/fitz/test-device.o build/release/source/fitz/text.o build/release/source/fitz/time.o build/release/source/fitz/trace-device.o build/release/source/fitz/track-usage.o build/release/source/fitz/transition.o build/release/source/fitz/tree.o build/release/source/fitz/ucdn.o build/release/source/fitz/untar.o build/release/source/fitz/unzip.o build/release/source/fitz/util.o build/release/source/fitz/writer.o build/release/source/fitz/xml.o build/release/source/fitz/zip.o build/release/generated/DroidSansFallback.o build/release/generated/DroidSansFallbackFull.o build/release/generated/NotoEmoji-Regular.o build/release/generated/NotoKufiArabic-Regular.o build/release/generated/NotoNaskhArabic-Regular.o build/release/generated/NotoNastaliqUrdu-Regular.o build/release/generated/NotoSans-Regular.o build/release/generated/NotoSansArmenian-Regular.o build/release/generated/NotoSansAvestan-Regular.o build/release/generated/NotoSansBalinese-Regular.o build/release/generated/NotoSansBamum-Regular.o build/release/generated/NotoSansBatak-Regular.o build/release/generated/NotoSansBengali-Regular.o build/release/generated/NotoSansBrahmi-Regular.o build/release/generated/NotoSansBuginese-Regular.o build/release/generated/NotoSansBuhid-Regular.o build/release/generated/NotoSansCanadianAboriginal-Regular.o build/release/generated/NotoSansCarian-Regular.o build/release/generated/NotoSansCham-Regular.o build/release/generated/NotoSansCherokee-Regular.o build/release/generated/NotoSansCoptic-Regular.o build/release/generated/NotoSansCuneiform-Regular.o build/release/generated/NotoSansCypriot-Regular.o build/release/generated/NotoSansDeseret-Regular.o build/release/generated/NotoSansDevanagari-Regular.o build/release/generated/NotoSansEgyptianHieroglyphs-Regular.o build/release/generated/NotoSansEthiopic-Regular.o build/release/generated/NotoSansGeorgian-Regular.o build/release/generated/NotoSansGlagolitic-Regular.o build/release/generated/NotoSansGothic-Regular.o build/release/generated/NotoSansGujarati-Regular.o build/release/generated/NotoSansGurmukhi-Regular.o build/release/generated/NotoSansHanunoo-Regular.o build/release/generated/NotoSansHebrew-Regular.o build/release/generated/NotoSansImperialAramaic-Regular.o build/release/generated/NotoSansInscriptionalPahlavi-Regular.o build/release/generated/NotoSansInscriptionalParthian-Regular.o build/release/generated/NotoSansJavanese-Regular.o build/release/generated/NotoSansKaithi-Regular.o build/release/generated/NotoSansKannada-Regular.o build/release/generated/NotoSansKayahLi-Regular.o build/release/generated/NotoSansKharoshthi-Regular.o build/release/generated/NotoSansKhmer-Regular.o build/release/generated/NotoSansLao-Regular.o build/release/generated/NotoSansLepcha-Regular.o build/release/generated/NotoSansLimbu-Regular.o build/release/generated/NotoSansLinearB-Regular.o build/release/generated/NotoSansLisu-Regular.o build/release/generated/NotoSansLycian-Regular.o build/release/generated/NotoSansLydian-Regular.o build/release/generated/NotoSansMalayalam-Regular.o build/release/generated/NotoSansMandaic-Regular.o build/release/generated/NotoSansMeeteiMayek-Regular.o build/release/generated/NotoSansMongolian-Regular.o build/release/generated/NotoSansMyanmar-Regular.o build/release/generated/NotoSansNKo-Regular.o build/release/generated/NotoSansNewTaiLue-Regular.o build/release/generated/NotoSansOgham-Regular.o build/release/generated/NotoSansOlChiki-Regular.o build/release/generated/NotoSansOldItalic-Regular.o build/release/generated/NotoSansOldPersian-Regular.o build/release/generated/NotoSansOldSouthArabian-Regular.o build/release/generated/NotoSansOldTurkic-Regular.o build/release/generated/NotoSansOriya-Regular.o build/release/generated/NotoSansOsmanya-Regular.o build/release/generated/NotoSansPhagsPa-Regular.o build/release/generated/NotoSansPhoenician-Regular.o build/release/generated/NotoSansRejang-Regular.o build/release/generated/NotoSansRunic-Regular.o build/release/generated/NotoSansSamaritan-Regular.o build/release/generated/NotoSansSaurashtra-Regular.o build/release/generated/NotoSansShavian-Regular.o build/release/generated/NotoSansSinhala-Regular.o build/release/generated/NotoSansSundanese-Regular.o build/release/generated/NotoSansSylotiNagri-Regular.o build/release/generated/NotoSansSymbols-Regular.o build/release/generated/NotoSansSyriacEastern-Regular.o build/release/generated/NotoSansSyriacEstrangela-Regular.o build/release/generated/NotoSansSyriacWestern-Regular.o build/release/generated/NotoSansTagalog-Regular.o build/release/generated/NotoSansTagbanwa-Regular.o build/release/generated/NotoSansTaiLe-Regular.o build/release/generated/NotoSansTaiTham-Regular.o build/release/generated/NotoSansTaiViet-Regular.o build/release/generated/NotoSansTamil-Regular.o build/release/generated/NotoSansTelugu-Regular.o build/release/generated/NotoSansThaana-Regular.o build/release/generated/NotoSansThai-Regular.o build/release/generated/NotoSansTibetan-Regular.o build/release/generated/NotoSansTifinagh-Regular.o build/release/generated/NotoSansUgaritic-Regular.o build/release/generated/NotoSansVai-Regular.o build/release/generated/NotoSansYi-Regular.o build/release/generated/NotoSerif-Regular.o build/release/generated/NotoSerifArmenian-Regular.o build/release/generated/NotoSerifBengali-Regular.o build/release/generated/NotoSerifDevanagari-Regular.o build/release/generated/NotoSerifGeorgian-Regular.o build/release/generated/NotoSerifGujarati-Regular.o build/release/generated/NotoSerifKannada-Regular.o build/release/generated/NotoSerifKhmer-Regular.o build/release/generated/NotoSerifLao-Regular.o build/release/generated/NotoSerifMalayalam-Regular.o build/release/generated/NotoSerifTamil-Regular.o build/release/generated/NotoSerifTelugu-Regular.o build/release/generated/NotoSerifThai-Regular.o build/release/generated/SourceHanSansCN-Regular.o build/release/generated/SourceHanSansJP-Regular.o build/release/generated/SourceHanSansKR-Regular.o build/release/generated/SourceHanSansTW-Regular.o build/release/generated/Dingbats.o build/release/generated/NimbusMonoPS-Bold.o build/release/generated/NimbusMonoPS-BoldItalic.o build/release/generated/NimbusMonoPS-Italic.o build/release/generated/NimbusMonoPS-Regular.o build/release/generated/NimbusRoman-Bold.o build/release/generated/NimbusRoman-BoldItalic.o build/release/generated/NimbusRoman-Italic.o build/release/generated/NimbusRoman-Regular.o build/release/generated/NimbusSans-Bold.o build/release/generated/NimbusSans-BoldOblique.o build/release/generated/NimbusSans-Oblique.o build/release/generated/NimbusSans-Regular.o build/release/generated/StandardSymbolsPS.o build/release/generated/CharisSIL-B.o build/release/generated/CharisSIL-BI.o build/release/generated/CharisSIL-I.o build/release/generated/CharisSIL-R.o build/release/source/pdf/pdf-annot-edit.o build/release/source/pdf/pdf-annot.o build/release/source/pdf/pdf-appearance.o build/release/source/pdf/pdf-clean-file.o build/release/source/pdf/pdf-clean.o build/release/source/pdf/pdf-cmap-load.o build/release/source/pdf/pdf-cmap-parse.o build/release/source/pdf/pdf-cmap-table.o build/release/source/pdf/pdf-cmap.o build/release/source/pdf/pdf-colorspace.o build/release/source/pdf/pdf-crypt.o build/release/source/pdf/pdf-device.o build/release/source/pdf/pdf-encoding.o build/release/source/pdf/pdf-event.o build/release/source/pdf/pdf-field.o build/release/source/pdf/pdf-font.o build/release/source/pdf/pdf-form.o build/release/source/pdf/pdf-function.o build/release/source/pdf/pdf-graft.o build/release/source/pdf/pdf-image.o build/release/source/pdf/pdf-interpret.o build/release/source/pdf/pdf-js.o build/release/source/pdf/pdf-layer.o build/release/source/pdf/pdf-lex.o build/release/source/pdf/pdf-metrics.o build/release/source/pdf/pdf-nametree.o build/release/source/pdf/pdf-object.o build/release/source/pdf/pdf-op-buffer.o build/release/source/pdf/pdf-op-filter.o build/release/source/pdf/pdf-op-run.o build/release/source/pdf/pdf-outline.o build/release/source/pdf/pdf-page.o build/release/source/pdf/pdf-parse.o build/release/source/pdf/pdf-pattern.o build/release/source/pdf/pdf-pkcs7.o build/release/source/pdf/pdf-portfolio.o build/release/source/pdf/pdf-repair.o build/release/source/pdf/pdf-resources.o build/release/source/pdf/pdf-run.o build/release/source/pdf/pdf-shade.o build/release/source/pdf/pdf-store.o build/release/source/pdf/pdf-stream.o build/release/source/pdf/pdf-type3.o build/release/source/pdf/pdf-unicode.o build/release/source/pdf/pdf-write.o build/release/source/pdf/pdf-xobject.o build/release/source/pdf/pdf-xref.o build/release/source/xps/xps-common.o build/release/source/xps/xps-doc.o build/release/source/xps/xps-glyphs.o build/release/source/xps/xps-gradient.o build/release/source/xps/xps-image.o build/release/source/xps/xps-link.o build/release/source/xps/xps-outline.o build/release/source/xps/xps-path.o build/release/source/xps/xps-resource.o build/release/source/xps/xps-tile.o build/release/source/xps/xps-util.o build/release/source/xps/xps-zip.o build/release/source/svg/svg-color.o build/release/source/svg/svg-doc.o build/release/source/svg/svg-parse.o build/release/source/svg/svg-run.o build/release/source/cbz/mucbz.o build/release/source/cbz/muimg.o build/release/source/cbz/mutiff.o build/release/source/html/css-apply.o build/release/source/html/css-parse.o build/release/source/html/epub-doc.o build/release/source/html/html-doc.o build/release/source/html/html-font.o build/release/source/html/html-layout.o build/release/source/gprf/gprf-doc.o build/release/source/gprf/gprf-skeleton.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: build/release/libmupdf.a(time.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: build/release/libmupdf.a(track-usage.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: build/release/libmupdf.a(gprf-doc.o) has no symbols
xcrun ranlib 
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: no archives specified
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib [-sactfqLT] [-] archive [...]
make: *** [build/release/libmupdf.a] Error 1
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make install build=release verbose=yes CC=clang prefix=/usr/local/Cellar/mupdf/1.11
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```

**Comment by DomT4** [comment]
Giving up on this one. Tried a bunch of different tweaks locally with no success, and there's no security issue that I'm aware of here, so how much I care enough to plow more time into this is fairly limited. Will let someone who uses the software take a run at it instead 😄.

**Comment by fxcoudert** [comment]
Two bugs reported and fixed… https://github.com/Homebrew/homebrew-core/pull/13156

**Comment by DomT4** [comment]
Thanks @fxcoudert, appreciate you picking this up ❤️

**Pull request closed without merging**
