### PR TITLE
datamash: migrate from homebrew/science

### PR DESCRIPTION
**Pull request by fxcoudert**
See https://github.com/Homebrew/homebrew-core/issues/15619

### CODE REVIEW

**Comment by iMichka** [comment]
@fxcoudert getting the following style audit error on Linuxbrew:
```
datamash:
  * C: 5: col 3: Please use "https://ftp.gnu.org/gnu/datamash/datamash-1.1.1.tar.gz" instead of https://ftpmirror.gnu.org/datamash/datamash-1.1.1.tar.gz.
==> FAILED
==> brew style datamash
```
The error can also be seen on the mac build. Was the url kept like this on purpose or did this slip through?

**Comment by fxcoudert** [comment]
Because the `ftp.gnu.org` URL is already used as a mirror, so it made no sense to change it

**Comment by iMichka** [comment]
I would have inverted both urls. So that the mirror actually points to the mirror.

**Comment by fxcoudert** [comment]
Indeed, fixed in https://github.com/Homebrew/homebrew-core/commit/a6b4f9c45f9a1dfd99cabe5e22cc9c3a8e538c04

**Comment by iMichka** [comment]
Thanks!

**Pull request closed without merging**
