### PR TITLE
yazpp: add test

### PR DESCRIPTION
**Pull request by vidusheeamoli**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The `yazpp` formula was missing tests. In this test, I made an incorrect API connection and tried catching the exception.

Please let me know if I can add some other test cases as well.

Thank you and have a nice weekend! 🚀

### CODE REVIEW

**Comment by SMillerDev** [comment]
CI problems caused the test failure.

**Comment by vidusheeamoli** [comment]
@SMillerDev  Thank you for the heads up. Is there a way to re-run tests? Also, I will keep you posted and will let you know once the tests pass 👍

**Comment by Bo98** [comment]
Yes, we'll restart the Jenkins job once the CI is working again. The GitHub Actions ones should start automatically once things are back to normal.

**Comment by vidusheeamoli** [comment]
Hello @Bo98! Even after the tests were re-run, jenkins points to the same error. Is there anything that can be done from my side to trigger the test re-run ?

Thank you,
Vidushee

**Comment by Bo98** [comment]
The CI network hasn't recovered yet so the tests haven't been rerun yet. I'm hoping it will do at some point today.

**Comment by vidusheeamoli** [comment]
Thank you for the update! @Bo98  😄

**Comment by Bo98** [comment]
@BrewTestBot test this please

**Comment by Bo98** [comment]
```
==> brew test yazpp --verbose
==> FAILED
Testing yazpp
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200303-23755-14s1883.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/yazpp.rb --verbose
==> /usr/bin/clang++ -std=c++11 -I/usr/local/Cellar/yazpp/1.6.5/include -L/usr/local/Cellar/yazpp/1.6.5/lib -lyaz -lzoompp test.cpp -o test
ld: library not found for -lyaz
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by vidusheeamoli** [comment]
@Bo98 Thank you for the heads up. It is fixed now. 😃

**Pull request merged**
