### PR TITLE
m4 1.4.19

### PR DESCRIPTION
**Pull request by moonfruit**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by gromgit** [comment]
Why was the `on_linux` block removed? Did it actually break the build?

**Comment by moonfruit** [comment]
I checked the Linux patch for m4 1.4.18 and m4 1.4.19 codes. I found what the patch does is already done by 1.4.19, so it doesn't need anymore.

**Comment by gromgit** [comment]
> I checked the Linux patch codes for m4 1.4.18 and the codes from m4 1.4.19. I found that what the patch does is already done by 1.4.19, so it doesn't need anymore.

Maybe it's just me, but I don't think it's a good idea to remove Linux-related stuff in the _macOS_ core tap without actually testing the build on a Linux box, since there's no Linux CI here to confirm whether it actually breaks the build.

Fortunately, my build / test of your changes in an official Ubuntu 18.04 Docker container were successful. :grin:

**Comment by moonfruit** [comment]
OK, I will pay attention next time.

**Comment by carlocab** [comment]
ARM failures are unrelated:
```
Error: 3 failed steps!
brew test --retry --verbose lanraragi
brew test --retry --verbose monkeysphere
brew test --retry --verbose mytop
```

**Comment by carlocab** [comment]
Big Sur

```
Error: 5 failed steps!
brew test --retry --verbose innotop
brew test --retry --verbose lanraragi
brew test --retry --verbose monkeysphere
brew test --retry --verbose mytop
brew test --retry --verbose pympress
```

Catalina

```
Error: 4 failed steps!
brew test --retry --verbose autoconf@2.69
brew test --retry --verbose lanraragi
brew test --retry --verbose pympress
brew test --retry --verbose subversion
```

Mojave

```
Error: 2 failed steps!
brew test --retry --verbose lanraragi
brew test --retry --verbose pympress
```

**Comment by carlocab** [comment]
`pympress` needs investigating. While I don't see how this can be caused by the `m4` updated, I can't reproduce the error here with the existing version of `m4`.

**Comment by carlocab** [comment]
`lanraragi` fixed in #78466.

**Comment by SMillerDev** [comment]
HQX failure on ARM should be fixed by: https://github.com/Homebrew/homebrew-core/pull/81077

**Comment by SMillerDev** [comment]
Linux issues aborted the build:
```
==> Downloading http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1-Small-Region.svs
/home/linuxbrew/.linuxbrew/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/3.2.1-70-g5659d74\ \(Linux\;\ x86_64\ Ubuntu\ 16.04.7\ LTS\)\ curl/7.47.0 --header Accept-Language:\ en --fail --silent --retry 3 --location --remote-time --output /home/linuxbrew/.cache/Homebrew/downloads/cf13121b7684eb022c9cc9e5b335dbbdc8e6bb09aab3d6a446caa6acc7b3490b--CMU-1-Small-Region.svs.incomplete http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1-Small-Region.svs
/home/linuxbrew/.linuxbrew/bin/curl: error while loading shared libraries: libldap-2.5.so.0: cannot open shared object file: No such file or directory
```
```
 ==> brew linkage --test openjdk
==> FAILED
Missing libraries:
  unexpected (/home/linuxbrew/.linuxbrew/lib/libnet.so)
  expected (libjvm.so)
```
```
 ==> /home/linuxbrew/.linuxbrew/Cellar/leiningen/2.9.6/bin/lein test
Picked up _JAVA_OPTIONS: -Duser.home=/home/linuxbrew/.cache/Homebrew/java_cache -Djava.io.tmpdir=/tmp
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/linuxbrew/.linuxbrew/Cellar/openjdk/16.0.1/libexec/lib/libnio.so: /home/linuxbrew/.linuxbrew/Cellar/openjdk/16.0.1/libexec/lib/libnio.so: undefined symbol: reuseport_available
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
```
```
 ==> Pouring jruby--9.2.19.0.x86_64_linux.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /home/linuxbrew/.linuxbrew
Could not symlink bin/racc
Target /home/linuxbrew/.linuxbrew/bin/racc
is a symlink belonging to ruby. You can unlink it:
  brew unlink ruby
```
```
==> Pouring heimdal--7.7.0_1.x86_64_linux.bottle.tar.gz
Error: The `brew link` step did not complete successfully
Error: Could not symlink include/gssapi/gssapi.h
Target /home/linuxbrew/.linuxbrew/include/gssapi/gssapi.h
is a symlink belonging to krb5. You can unlink it:
  brew unlink krb5
```

**Comment by dawidd6** [comment]
- `ruby` and `jruby` conflict with each other because both install `racc` binary, even on macOS
- `heimdal` and `krb5` conflict with each other because both install `krb5-config` binary, even on macOS (just look at the tests)

```
 ==> brew linkage --test openjdk
==> FAILED
Missing libraries:
  unexpected (/home/linuxbrew/.linuxbrew/lib/libnet.so)
  expected (libjvm.so)
```
I guess it's a leftover from some formula which wasn't uninstalled properly?


```
==> Downloading http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1-Small-Region.svs
/home/linuxbrew/.linuxbrew/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/3.2.1-70-g5659d74\ \(Linux\;\ x86_64\ Ubuntu\ 16.04.7\ LTS\)\ curl/7.47.0 --header Accept-Language:\ en --fail --silent --retry 3 --location --remote-time --output /home/linuxbrew/.cache/Homebrew/downloads/cf13121b7684eb022c9cc9e5b335dbbdc8e6bb09aab3d6a446caa6acc7b3490b--CMU-1-Small-Region.svs.incomplete http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1-Small-Region.svs
/home/linuxbrew/.linuxbrew/bin/curl: error while loading shared libraries: libldap-2.5.so.0: cannot open shared object file: No such file or directory
```
This is a known issue and it should be fixed, just dunno how to do it properly for now.

**Comment by SMillerDev** [comment]
libnet.so does seem to be part of openjdk: https://pkgs.org/download/libnet.so()(64bit)

**Comment by SMillerDev** [comment]
I don't think any of these issues are caused by this PR, but I'll try and fix them regardless.

---

ARM
```
Error: 3 failed steps!
brew test --retry --verbose cucumber-cpp
brew install nutcracker
brew test --retry --verbose solr@7.7
```
11
```
brew install nutcracker
brew test --retry --verbose pympress
brew test --retry --verbose solr@7.7
```
10.15
```
brew install nutcracker
brew test --retry --verbose pympress
brew install --only-dependencies siril
brew test --retry --verbose solr@7.7
```
10.14
```
brew install nutcracker
brew test --retry --verbose solr@7.7
```

---

```
 ==> /usr/local/Cellar/solr@7.7/7.7.3_1/bin/solr -i
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp

ERROR: Failed to get system information from http://localhost:59833/solr due to: org.apache.http.client.ClientProtocolException: Expected JSON response from server but received: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/admin/info/system. Reason:
<pre>    Not Found</pre></p><h3>Caused by:</h3><pre>javax.servlet.ServletException: javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.
```

```
Error: The `brew link` step did not complete successfully
Could not symlink include/yaml.h
Target /usr/local/include/yaml.h
is a symlink belonging to libyaml. You can unlink it:
  brew unlink libyaml

To force the link and overwrite all conflicting files:
  brew link --overwrite nutcracker

To list all files that would be deleted:
  brew link --overwrite --dry-run nutcracker

Possible conflicting files are:
/usr/local/include/yaml.h -> /usr/local/Cellar/libyaml/0.2.5/include/yaml.h
/usr/local/lib/libyaml-0.2.dylib -> /usr/local/Cellar/libyaml/0.2.5/lib/libyaml-0.2.dylib
/usr/local/lib/libyaml.a -> /usr/local/Cellar/libyaml/0.2.5/lib/libyaml.a
/usr/local/lib/libyaml.dylib -> /usr/local/Cellar/libyaml/0.2.5/lib/libyaml.dylib
/usr/local/lib/pkgconfig/yaml-0.1.pc -> /usr/local/Cellar/libyaml/0.2.5/lib/pkgconfig/yaml-0.1.pc
```

**Comment by carlocab** [comment]
`nutcracker` installing its own `libyaml` is pretty annoying. It doesn't even seem to need the copy it installs because it links statically.

**Comment by SMillerDev** [comment]
Yeah, upstream seems pretty insistent on keeping this setup. Debian maintainers have already tried and given up on convincing them otherwise.

I can't reproduce the Solr issue 😢

**Comment by carlocab** [comment]
Even with the new version of `m4`? I remember last I looked at this I couldn't get the `pympress` failure on the existing (pre-version-bump) `m4` bottle.

**Comment by carlocab** [comment]
Ported Debian's patch for `nutcracker`. Seemed to fix things for me locally.

**Pull request closed without merging**
