### PR TITLE
go 1.8.2

### PR DESCRIPTION
**Pull request by cblecker**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by cblecker** [comment]
@ilovezfs @MikeMcQuaid FYI, as this is a security fix: https://groups.google.com/d/msg/golang-announce/B5ww0iFt1_Q/TgUFJV14BgAJ

**Comment by ilovezfs** [comment]
I'm wondering if we should just wait for 1.8.3 since they say it's coming out later today. Thoughts?

**Comment by cblecker** [comment]
Yeah, I thought about that too, but am unsure if it got delayed as it's been nearly 9 hours since 1.8.2 got tagged. Unsure if they are waiting on CI or something to go green before the next cut.

Maybe we hold off a little bit longer to reduce work, but if we don't see it in a couple hours merge? My other PR for 1.7.6 can for sure be merged, as they won't cut non-security releases for 1.7 anymore.

**Comment by ilovezfs** [comment]
OK, let's assume 1.8.3 is dead in the water for now.

`godep` will need a revision bump.

**Comment by cblecker** [comment]
Done

**Comment by ilovezfs** [comment]
Shipped! :closed_lock_with_key:

**Pull request closed without merging**
