### PR TITLE
zeek: renamed from bro

### PR DESCRIPTION
**Pull request by chenrui333**
Per https://github.com/Homebrew/homebrew-core/pull/46587#issuecomment-554408135, rename bro to `zeek`.

cc @dominiklohmann, @EricFromCanada

### CODE REVIEW

**Comment by Bo98** [comment]
As a FYI about the `bison` warning: https://github.com/Homebrew/homebrew-core/pull/46587#issuecomment-552184434

**Comment by chenrui333** [comment]
@Bo98 yeah, I just read the thread, looks like `zeek` using its own version of `caf`, how should we proceed with this?

**Comment by Bo98** [comment]
I fixed that in #46735. Since we're renaming `bro`, the fix should be in place.

**Comment by chenrui333** [comment]
So sounds like we can go for a merge?

**Comment by Bo98** [comment]
I think so. Not sure if the bottle warning really matters.

**Pull request closed without merging**
