### PR TITLE
stout 1.3.2

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> go build -o /usr/local/Cellar/stout/1.3.2/bin/stout -v github.com/cloudflare/stout/src
src/github.com/cloudflare/stout/src/utils.go:15:2: cannot find package "github.com/sspencer/go-ini" in any of:
	/private/tmp/stout-20190513-20191-xuyueg/Stout-1.3.2/src/github.com/cloudflare/stout/vendor/github.com/sspencer/go-ini (vendor tree)
	/usr/local/Cellar/go/1.12.5/libexec/src/github.com/sspencer/go-ini (from $GOROOT)
	/private/tmp/stout-20190513-20191-xuyueg/Stout-1.3.2/src/github.com/sspencer/go-ini (from $GOPATH)
```

**Comment by chenrui333** [comment]
relates to https://github.com/cloudflare/Stout/issues/52

**Comment by chenrui333** [comment]
Looks like this formula is not well-maintained, as the website is also claimed down, https://github.com/cloudflare/Stout/issues/60

**Comment by chenrui333** [comment]
Should be fixed now.

**Comment by chenrui333** [comment]
Adding a better fix.

**Comment by chenrui333** [comment]
@fxcoudert commits squashed :)

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by chenrui333** [comment]
Thanks @zbeekman!

**Pull request closed without merging**
