### PR TITLE
apache-flink 1.11.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> brew test --verbose apache-flink
==> FAILED
Testing apache-flink
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200708-99572-sziucs.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/apache-flink.rb --verbose
==> /usr/local/Cellar/apache-flink/1.11.0/libexec/bin/start-cluster.sh
Starting cluster.
Starting standalonesession daemon on host Catalina.
Starting taskexecutor daemon on host Catalina.
==> /usr/local/Cellar/apache-flink/1.11.0/bin/flink run -p 1 /usr/local/Cellar/apache-flink/1.11.0/libexec/examples/streaming/WordCount.jar --input input --output result
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/private/tmp/apache-flink-test-20200708-99573-h0v3wb -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
Job has been submitted with JobID d564b06a12d5f74d5d1b05acb4deee75

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: org.apache.flink.client.program.ProgramInvocationException: Job failed (JobID: d564b06a12d5f74d5d1b05acb4deee75)
```

**Comment by pnowojski** [comment]
@zhijiangW and me are taking look into this failure

**Comment by zhijiangW** [comment]
We have found the problem and record it in the [jira](https://issues.apache.org/jira/browse/FLINK-18612).

At the moment, we can bypass this bug by either setting the parallelism more than 1 or setting the output in absolute path instead. In addition, it would be better to always execute stop-cluster.sh no matter with the WordCount result, otherwise it might retain some processors after WordCount test failure.

**Comment by pnowojski** [comment]
@zhijiangW , by increasing parallelism do you mean changing the following line:
```
    system bin/"flink", "run", "-p", "1",
           libexec/"examples/streaming/WordCount.jar", "--input", "input",
           "--output", "result"
```
to:
```
    system bin/"flink", "run", "-p", "2",
           libexec/"examples/streaming/WordCount.jar", "--input", "input",
           "--output", "result"
```
? @chenrui333 would you like to update the PR, or should we do it?

**Comment by zhijiangW** [comment]
@pnowojski @chenrui333 , the easiest way for bypassing this bug is adjusting "result" to "result/1", which i already verified locally.

**Comment by zhijiangW** [comment]
Also we need to adjust the verify results by 
```
 assert_predicate testpath/"result/1", :exist?
 assert_equal expected, (testpath/"result/1").read
```

**Comment by zhijiangW** [comment]
I submitted a separate PR #58133  for fixing the issue.

**Pull request closed without merging**
