### PR TITLE
binutils 2.36

### PR DESCRIPTION
**Pull request by carlocab**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
This builds fine for me outside of Homebrew locally, so I don't know what's wrong. Admittedly, I've got a bunch of extra stuff in my environment that may be helping things along.

**Comment by iMichka** [comment]
You will also need this #69709 to make the linux build pass.

**Comment by carlocab** [comment]
Yup, but that I suspect that impediment is minor compared to the non-reproducible build failure.

**Comment by iMichka** [comment]
I merged my change, don't forget to rebase to make it take effect.

**Comment by carlocab** [comment]
Also, the wheezy_tests failed. I don't understand the error message though. 😅

**Comment by carlocab** [comment]
Oh, and cherry on top:
```
❯ brew install -sv binutils
[snip]
==> Summary
🍺  /usr/local/Cellar/binutils/2.36: 139 files, 121.7MB, built in 5 minutes 5 seconds
```

**Comment by fxcoudert** [comment]
It also works for me. I'm not sure why, but I see a warning on CI that could explain the failure:

```
*** Warning: Linking the shared library libctf-nobfd.la against the
*** static library ./../intl/libintl.a is not portable!
```

For some reason I don't have this warning in my local build.

**Comment by carlocab** [comment]
Comparing the output of running the `configure` script locally with `brew install -si`, there is one difference. In [CI](https://github.com/Homebrew/homebrew-core/pull/69699/checks?check_run_id=1761300955#step:7:77):
```
checking for isl 0.15 or later... no
```
whereas locally
```
checking for isl 0.15 or later... yes
```
Doesn't seem related to the error, but 🤷

**Comment by iMichka** [comment]
```
brew linkage binutils
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/lib/libgcc_s.so.1 (gcc)
  /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6 (gcc)
Dependencies with no linkage:
  zlib
```

This is what I have with the previous linux bottle, so you are right, it is probably using its internal zlib.
I would prefer to use the internal zlib for this case: binutils is one of the 2 first bottles that are installed by homebrew on linux, and it's a good thing if it does not depend on anything.
I'll revert my workflow change: #69734

Once this is done you can remove the zlib dependency and this should be good to go for the linux side.

**Comment by carlocab** [comment]
>it's a good thing if it does not depend on anything

It still uses zlib, so I think it would be good if it could depend on Homebrew zlib (or macOS zlib, if compatible). Deduplication and all that.

**Comment by iMichka** [comment]
I fixed the linux CI with 69736.

Can you try the `--with-system-zlib` flag?

**Comment by carlocab** [comment]
Aha:
```
❯ brew linkage binutils
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/gettext/lib/libintl.8.dylib (gettext)
Undeclared dependencies with linkage:
  gettext
```

**Comment by carlocab** [comment]
Unfortunately there doesn't appear to a be `--{without,disable}-gettext` flag.

**Comment by iMichka** [comment]
You need to rebase this to fix the linux build (I think).

Bringing in `gettext` on linux might be an issue, and it looks like the linux build did not complain about this. Because `gettext` depends on `libxml2` -> `python@3.9` and so on. So I'd rather avoid this on Linux if possible.

**Comment by iMichka** [comment]
You can try: `--disable-nls`

```
--disable-nls
This disables internationalization as i18n is not needed for the temporary tools.
```

Whatever that means :D

**Comment by carlocab** [comment]
Better, thanks:
```
❯ brew linkage binutils
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libz.1.dylib
```

**Comment by iMichka** [comment]
I made another fix for the Linux build: #69752
Can you rebase again?

**Review by iMichka — DISMISSED** [review]

**Comment by carlocab** [comment]
I'm a bit wary of the `--disable-nls` flag. IIUC, this enables compatibility with systems whose language isn't set to English. I wouldn't be opposed to someone wanting to remove the flag, even if it entails the added dependency.

**Comment by iMichka** [comment]
We could add it for Mac only.

Right now on linux, most of the time, we disable internalisation, because it makes the dependency tree become really huge in a lot of ways. This is something we might work on one day, but it's really not on my priority list.

**Comment by carlocab** [comment]
```
==> Downloading bottles for workflow: wheezy_tests.yml
/usr/bin/curl --disable --globoff --show-error --user-agent Linuxbrew/2.7.5-223-g565becc\ \(Linux\;\ x86_64\ Ubuntu\ 18.04.5\ LTS\)\ curl/7.58.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/repos/Homebrew/homebrew-core/actions/runs/512628298/artifacts --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --header Authorization:\ token\ ****** --dump-header /tmp/github_api_headers20210126-2701-1a7h327
Error: No artifact with the name `bottles` was found!
```

Ping @iMichka

**Comment by iMichka** [comment]
See #69869

**Pull request closed without merging**
