### PR TITLE
include-what-you-use 0.21

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
good work! can you also update the livecheck?

**Comment by p-linnane** [comment]
Looks like upstream did not update the download page on their site. We could switch to GitHub.

**Comment by p-linnane** [comment]
Might be a CDN delay then. I am still seeing the old version as the latest on their download page.

**Review by ZhongRuoyu — APPROVED** [review]
```console
$ brew lc iwyu
include-what-you-use: 0.20 ==> 0.21
```

**Pull request merged**
