### PR TITLE
osm2pgsql: switch to luajit-openresty

### PR DESCRIPTION
**Pull request by kiracus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by SMillerDev — DISMISSED** [review]

**Comment by carlocab** [comment]
```
==> /usr/local/Cellar/osm2pgsql/1.4.1_1/bin/osm2pgsql --version
2021-02-04 09:49:32  osm2pgsql version 1.4.1
Compiled using the following library versions:
Libosmium 2.16.0
Proj [API 4] Rel. 7.2.1, January 1st, 2021
Lua 5.1.4 (LuaJIT 2.1.0-beta3)
Error: osm2pgsql: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </LuaJIT/> was expected to be =~
<"">.
```
You probably wanted to redirect `stderr`. Though, this version test really doesn't do anything; I don't think there's use in adding it.

**Comment by kiracus** [comment]
@carlocab Thanks. Should be fixed in the latest commit.
Since the PR switches from luajit to luagitopenresty, the build still contains luagit support.
The unit test I add here indeed verifies the build contents luajit support.
Please check https://github.com/openstreetmap/osm2pgsql#using-luajit

**Comment by carlocab** [comment]
Yes, but the build already specifies `-DWITH_LUAJIT=ON`.

Is there a chance that CMake is told to use LuaJIT but doesn't error out when it can't find LuaJIT?

**Comment by kiracus** [comment]
You are right. In CMake, `luajit` is required when the flag is set.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
