### PR TITLE
pygobject3 3.20.1

### PR DESCRIPTION
**Pull request by aleb**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by apjanke** [comment]
I'm having trouble pulling this in. Might be a problem with the build.

```
$ brew pull --bottle 600
Warning: Current branch is pull: do you need to pull inside master?
==> Fetching patch
######################################################################## 100.0%
==> Applying patch
Applying: pygobject3 3.20.1
Applying: pygobject3: Fix description
==> Patch closes issue #600
Error: Failure while executing: /usr/bin/curl -f#LA Homebrew/0.9.9\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.9.5)\ curl/7.30.0 --silent --fail -o /dev/null -I https://github.com/BrewTestBot/homebrew-core/compare/homebrew:master...pr-600
```

@BrewTestBot test this please

Maybe that will be sufficient to fix it.

Also, if you have time, would you mind squashing this to a single commit? Description and audit fixes can be included in the same commits as version bumps.

**Comment by DomT4** [comment]
One of the downstream jobs failed:

```
Error: pygobject-2.28.6.mavericks.bottle.1.tar.gz is already published. Please remove it manually from
https://bintray.com/homebrew/bottles/pygobject/view#files
```

**Comment by apjanke** [comment]
Hmm. Maybe this is a limitation of test-bot and `brew pull` and treatment of multi-file PRs with bottles.

@aleb, would you mind removing the change to `Formula/pygobject.rb` from this PR and making a separate PR for it?

**Comment by DomT4** [comment]
> Hmm. Maybe this is a limitation of test-bot and brew pull and treatment of multi-file PRs with bottles.

It's not, as such. It's a security feature; If bottles have already been published for a formula the CI isn't allowed to overwrite them, a maintainer has to do so. If they aren't being used you can delete them off the server as the output suggests, and then reschedule the bottle job and it'll pass fine.

**Comment by apjanke** [comment]
That makes sense. I just mean, a limitation of how we work with that publish-once design: this PR affects two formulae, but a bottle should only be published for one of them (`pygobject3`), and the re-publishing for the other one (`pygobject`) shouldn't be attempted, or the failure should be ignored. I don't know this part of the `brew` code very well, so I'm not sure if that's something we should be able to detect or not. (Maybe checking whether the bottle is already published and comparing the checksum against the newly-published bottle, and skip the publishing attempt if it matches?)

**Comment by aleb** [comment]
Removed the description change to pygobject and squashed the commits.

**Comment by apjanke** [comment]
The build + pull is working now. Thanks. And thanks for the diagnosis, DomT4.

Merged. Thank you for your contribution to Homebrew!

**Pull request closed without merging**
