### PR TITLE
pinot 0.11.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
```
2022-09-08T08:06:43.4718550Z Initiating client connection, connectString=localhost:61887 sessionTimeout=30000 watcher=org.apache.helix.zookeeper.impl.client.ZkClient@6a714237
2022-09-08T08:06:43.4719130Z Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
2022-09-08T08:06:43.4719460Z jute.maxbuffer value is 4194304 Bytes
2022-09-08T08:06:43.4719720Z zookeeper.request.timeout value is 0. feature enabled=
2022-09-08T08:06:43.4727420Z Opening socket connection to server localhost/127.0.0.1:61887. Will not attempt to authenticate using SASL (unknown error)
2022-09-08T08:06:43.4727830Z Socket connection established, initiating session, client: /127.0.0.1:61890, server: localhost/127.0.0.1:61887
2022-09-08T08:06:43.4728220Z Session establishment complete on server localhost/127.0.0.1:61887, sessionid = 0x100476f8f880001, negotiated timeout = 30000
2022-09-08T08:06:43.4728550Z zkclient 0, zookeeper state changed ( SyncConnected )
2022-09-08T08:06:43.4728870Z Failed to find cluster config for cluster: PinotCluster, skipping applying cluster config
2022-09-08T08:06:43.4729190Z ZkClient AsyncCallback retry thread is interrupted.
2022-09-08T08:06:43.4729450Z Terminate ZkClient AsyncCallback retry thread.
2022-09-08T08:06:43.4729680Z Interrupted waiting for success
2022-09-08T08:06:43.4729910Z java.lang.InterruptedException: null
2022-09-08T08:06:43.4730170Z 	at java.lang.Object.wait(Native Method) ~[?:?]
2022-09-08T08:06:43.4730440Z 	at java.lang.Object.wait(Object.java:338) ~[?:?]
2022-09-08T08:06:43.4731160Z 	at org.apache.helix.zookeeper.zkclient.callback.ZkAsyncCallbacks$DefaultCallback.waitForSuccess(ZkAsyncCallbacks.java:248) [pinot-all-0.11.0-jar-with-dependencies.jar:0.11.0-1b4d6b6b0a27422c1552ea1a936ad145056f7033]
2022-09-08T08:06:43.4732020Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.issueSync(ZkClient.java:1616) [pinot-all-0.11.0-jar-with-dependencies.jar:0.11.0-1b4d6b6b0a27422c1552ea1a936ad145056f7033]
2022-09-08T08:06:43.4732780Z 	at org.apache.helix.zookeeper.zkclient.ZkClient.access$300(ZkClient.java:85) [pinot-all-0.11.0-jar-with-dependencies.jar:0.11.0-1b4d6b6b0a27422c1552ea1a936ad145056f7033]
2022-09-08T08:06:43.4733510Z 	at org.apache.helix.zookeeper.zkclient.ZkClient$4.run(ZkClient.java:1642) [pinot-all-0.11.0-jar-with-dependencies.jar:0.11.0-1b4d6b6b0a27422c1552ea1a936ad145056f7033]
2022-09-08T08:06:43.4734260Z 	at org.apache.helix.zookeeper.zkclient.ZkEventThread.run(ZkEventThread.java:99) [pinot-all-0.11.0-jar-with-dependencies.jar:0.11.0-1b4d6b6b0a27422c1552ea1a936ad145056f7033]
2022-09-08T08:06:43.4734850Z zkclient 0, sycnOnNewSession with sessionID 100476f8f880001 async return code: OK and proceeds
2022-09-08T08:06:43.4735320Z Closing zkclient uid:0, zk:State:CONNECTED Timeout:30000 sessionid:0x100476f8f880001 local:/127.0.0.1:61890 remoteserver:localhost/127.0.0.1:61887 lastZxid:3 xid:3 sent:3 recv:3 queuedpkts:0 pendingresp:0 queuedevents:0
2022-09-08T08:06:43.4735680Z Session: 0x100476f8f880001 closed
2022-09-08T08:06:43.4735870Z Closed zkclient with uid:0
2022-09-08T08:06:43.4736110Z EventThread shut down for session: 0x100476f8f880001
```

**Comment by iMichka** [comment]
@kbastani might be able to help with this error. Or anyone knowing how `pinot` works.

**Comment by chenrui333** [comment]
This is the java module access thing, let me see if I can get it passed thru.

**Comment by chenrui333** [comment]
This is mostly the java modules access issue

**Comment by chenrui333** [comment]
@kbastani when you got chance, can you help this upgrade? Thanks!

**Comment by chenrui333** [comment]
#121621

**Comment by chenrui333** [comment]
pinot 0.12.0 works fine now with jdk11

**Pull request closed without merging**
