### PR TITLE
emscripten@3.1.29 (new formula)

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
`tree-sitter` is a dependency for important formulae like `emacs` and `neovim`. `tree-sitter` requires a specific version of `emscripten` to build. We can't vendor it without also vendoring Python, Node, etc. This PR adds that specific version of `emscripten` as a versioned formula and includes a caveat stating it should not be used for any other purpose. I've also switched `tree-sitter` to build with this new version, but didn't revision bump it since this isn't a runtime dependency.

Followup to https://github.com/Homebrew/homebrew-core/pull/158812 & https://github.com/Homebrew/homebrew-core/pull/158869.

### CODE REVIEW

**Comment by p-linnane** [comment]
Not sure how to handle this alias issue. cc @Homebrew/core for ideas on that as well as the overall approach.

**Comment by bayandin** [comment]
> Not sure how to handle this alias issue. 

I would create an alias as the audit suggests 😄 

```
        cd /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases
        ln -s ../Formula/e/emscripten.rb emscripten@3.1
```

**Comment by Bo98** [comment]
This seems better as a resource of `tree-sitter`.

**Comment by p-linnane** [comment]
It vendors it's own Python/Node if we do it that way.

**Comment by bayandin** [comment]
> The current latest version of `emscripten` is also v3.1.x, so that alias wouldn't make sense here.

it can be read as `@3.1` — the latest 3.1.x version homebrew has, and `@3.1.29` — excatly version 3.1.29. So it does make some sense.

> It vendors it's own Python/Node if we do it that way.

We can use these as build/test dependencies in `tree-sitter`, so don't need to vendor them (or do you mean something else by "vendoring")? I kinda like the idea of having it as a resource a bit more.

**Comment by p-linnane** [comment]
I misread the alias part, thinking it was wanting to me to alias **this** formula as `emscripten@3.1` 🤦‍♂️. Thanks for pointing that out, and will fix if we move forward with this formula.

RE: vendoring: we have to use [their emsdk](https://emscripten.org/docs/getting_started/downloads.html) as the resource and select the version of `emscripten`. When doing so, it pulls down its own Python/Node as part of the process. There doesn't appear to be a way to avoid that.

**Comment by MikeMcQuaid** [comment]
> It vendors it's own Python/Node if we do it that way.

I think this may be better than a dedicated formula, even if these all get vendored. It's clear upstream is brittle enough that it expects to work this way.

**Comment by MikeMcQuaid** [comment]
> it can be read as `@3.1` — the latest 3.1.x version homebrew has, and `@3.1.29` — excatly version 3.1.29. So it does make some sense.

If we go this way: agreed.

**Comment by p-linnane** [comment]
If we are ok accepting those vendored dependencies I'm happy to just add the resource to `tree-sitter`. I know we usually deprecate formulae for vendoring these kinds of things, so I was trying to avoid that.

**Comment by MikeMcQuaid** [comment]
@p-linnane Fine with me. It's regrettable but for software that's too popular: we kinda just have to suck it up or end up in a world of pain 😭

**Comment by Bo98** [comment]
> It vendors it's own Python/Node if we do it that way.

How? Can't we do everything we're doing in a separate formula in tree-sitter instead?

**Comment by p-linnane** [comment]
The `emscripten` formula is pretty large, and takes anywhere from 3 to 7 hours to build. It would completely balloon the `tree-sitter` formula if we were to try and do that.

I've opened https://github.com/Homebrew/homebrew-core/pull/158998 to use `emsdk` as a resource.

**Comment by Bo98** [comment]
Ah ok so the plan is to just using prebuilt emsdk instead?

**Comment by p-linnane** [comment]
Unfortunately it's the best option we have.

**Comment by Bo98** [comment]
Other option is to not build wasm at all I guess if it's unsustainable given it does work but will mean `tree-sitter web-ui` downloads the wasm at runtime:

https://github.com/tree-sitter/tree-sitter/issues/718#issuecomment-685010492

**Pull request closed without merging**
