### PR TITLE
ghc 9.2.5

### PR DESCRIPTION
**Pull request by fishtreesugar**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by Bo98** [comment]
This fixes https://gitlab.haskell.org/ghc/ghc/-/issues/21964, which is good.

Though the nature of the issue means that I think the boostrap is also affected. Given 9.0.x is dead, I wonder if we can bootstrap 9.2.5 with 9.2.5.

**Comment by fishtreesugar** [comment]
[x86_64 binaries compiled with 9.2.5 and run in MacOS Ventura immediately segfault](https://gitlab.haskell.org/ghc/ghc/-/issues/22437) looks like that's not totally fixed

**Comment by Bo98** [comment]
That's disappointing. We haven't tested x86_64 on macOS 13 ourselves yet, so not sure how widespread it is given the single report.

**Comment by Bo98** [comment]
Actually that issue mentions `upx`, which is very much known by us to routinely break on macOS updates.

**Comment by Bo98** [comment]
Anyhow, looks like we're hitting https://gitlab.haskell.org/ghc/ghc/-/issues/21188 sadly.

**Comment by fishtreesugar** [comment]
Shall we rollback to bootstrap via GHC 9.0.2?

**Comment by Bo98** [comment]
I guess if we want to merge 9.2.5 quickly and deal with Ventura separately, but we will soon need to bootstrap with 9.2 if we want to support Ventura.

**Comment by fishtreesugar** [comment]
hmm, https://gitlab.haskell.org/ghc/ghc/-/issues/21666#note_433880 maybe we could give hadrian a try,  but hadrian hasn't provide [a bootstrap plan of 9.2.5 yet](https://gitlab.haskell.org/ghc/ghc/-/tree/master/hadrian/bootstrap) :-(

**Comment by Bo98** [comment]
Yeah, that's unfortunate. I guess we could use a binary cabal-install instead for building Hadrian. #110865 has experimented with that approach.

**Comment by Bo98** [comment]
> Ah we could slightly modify `plan-bootstrap-9_2_2.json` to support 9.2.5 I believe

It would be good if upstream provided a 9.2.5 (and I suppose ideally a tarball too but that's less important: https://downloads.haskell.org/~ghc/9.4.3/hadrian-bootstrap-sources/). But we can probably host something on `formula-patches` in the interim.

**Pull request closed without merging**
