### PR TITLE
bettercap 2.23

### PR DESCRIPTION
**Pull request by djerfy**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by LBN-JCH** [comment]
Okay I see tomorrow :/

```
19:19:22 ==> make build
19:19:22 # github.com/bettercap/bettercap/modules/api_rest
19:19:22 modules/api_rest/api_rest_controller.go:98:30: mod.record.Session.Index undefined (type *recording.Record has no field or method Index)
19:19:22 modules/api_rest/api_rest_controller.go:109:23: mod.record.Session.Index undefined (type *recording.Record has no field or method Index)
19:19:22 modules/api_rest/api_rest_controller.go:114:55: mod.record.Session.Index undefined (type *recording.Record has no field or method Index)
19:19:22 modules/api_rest/api_rest_controller.go:257:29: mod.record.Events.Index undefined (type *recording.Record has no field or method Index)
19:19:22 modules/api_rest/api_rest_controller.go:267:22: mod.record.Events.Index undefined (type *recording.Record has no field or method Index)
19:19:22 make: *** [build] Error 2
```

**Comment by djerfy** [comment]
Okay I see the problem tomorrow: 
```
19:19:51 ==> make build
19:19:51 # github.com/bettercap/bettercap/modules/api_rest
19:19:51 modules/api_rest/api_rest_controller.go:98:30: mod.record.Session.Index undefined (type *recording.Record has no field or method Index)
19:19:51 modules/api_rest/api_rest_controller.go:109:23: mod.record.Session.Index undefined (type *recording.Record has no field or method Index)
19:19:51 modules/api_rest/api_rest_controller.go:114:55: mod.record.Session.Index undefined (type *recording.Record has no field or method Index)
19:19:51 modules/api_rest/api_rest_controller.go:257:29: mod.record.Events.Index undefined (type *recording.Record has no field or method Index)
19:19:51 modules/api_rest/api_rest_controller.go:267:22: mod.record.Events.Index undefined (type *recording.Record has no field or method Index)
19:19:51 make: *** [build] Error 2
```

**Comment by djerfy** [comment]
No found solution for the moment :( I don't have this problem on build from sources..

**Comment by equal-l2** [comment]
The problem is that Gopkg.lock in `bettercap` specifies the wrong version of `bettercap/record`.
`record.Record.Index` has introduced in https://github.com/bettercap/recording/commit/1f9c73ba, but Gopkg.lock specifies an older commit https://github.com/bettercap/recording/commit/1396b95.

**Comment by djerfy** [comment]
I close this pull request, this version will not be available on Homebrew because there is a problem on a dependency (`bettercap/record` module). Thank you @equal-l2 for you details.

**Pull request closed without merging**
