### PR TITLE
open-mpi 4.1.6

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
`get_iplayer` failure

**Review by p-linnane — APPROVED** [review]

**Review by ZhongRuoyu — APPROVED** [review]

**Comment by sighingnow** [comment]
Hi folks, we have a package [vineyard](https://github.com/Homebrew/homebrew-core/blob/master/Formula/v/vineyard.rb) which depends on open-mpi. The open-mpi package was upgraded 3 days ago, but the vineyard bottles didn't get rebuilt.

When `brew install vineyard` it installs the old vineyard bottles and new version of open-mpi, causing shared library cannot be found errors.

Can anyone help me trigger the rebuild? or given me some guidance about how to trigger such a revision build. Thanks!

**Comment by p-linnane** [comment]
@sighingnow Our PR's go through dependent testing to make sure there are no failures like that. `vineyard` was successfully installed and had it's `test` block run against these new `open-mpi` bottles.

My recommendation is to update the `test` block on `vineyard` to check for this somehow.

**Comment by sighingnow** [comment]
> My recommendation is to update the test block on vineyard to check for this somehow.

Got it. Thank you @p-linnane. I will try to fix it on the vineyard formula.

**Pull request merged**
