### PR TITLE
amfora 1.9.2

### PR DESCRIPTION
**Pull request by makew0rld**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by makeworld-the-better-one** [comment]
```ruby
  bottle do
    sha256 cellar: :any_skip_relocation, arm64_monterey: "08ec5163a79f6c92982ee1b99657a052832ad92f787e7347571ec3d20f82434f"
    sha256 cellar: :any_skip_relocation, arm64_big_sur:  "4d37d2bfd27691d2b2a69f5ec5ef94b3af3afbca7fe399dc0af3bb3eec4cab3e"
    sha256 cellar: :any_skip_relocation, monterey:       "3f19f19c2611c9fb2df16c2859d2f6834fdef3b3a86c034d0b90d2f2b555c4b6"
    sha256 cellar: :any_skip_relocation, big_sur:        "f6701ae1c9412787d6e41e7792b0f78016fe1157948995707b6c41b1b33d0e1e"
    sha256 cellar: :any_skip_relocation, catalina:       "edc5b5c87ac6afe8434e1aeffa9672a17e4ca3ce0b9579c758f27d531c75f146"
    sha256 cellar: :any_skip_relocation, mojave:         "f9246c3f85984e0b1d57daef632186b8e04a2a06350f92ed9562b914e1e80ce4"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "34814dc0a1da5f88b639b084ac819fafc2ed49824b28166317bfc9bbce68d840"
  end
```

I am not sure how to update these hashes. Would appreciate guidance on that.

**Comment by chenrui333** [comment]
`bottle` block would be automatically handled by @BrewTestBot (no need to touch it)

**Comment by chenrui333** [comment]
test failure
```
    Minitest::Assertion: Expected /\#\ New\ Tab/ to match "".
```

**Comment by makeworld-the-better-one** [comment]
@chenrui333 I believe that test failed because the lines it's looking for are now preceded with a bunch of spaces. Could the output of `amfora -v` be used for the test instead?

**Comment by chenrui333** [comment]
> @chenrui333 I believe that test failed because the lines it's looking for are now preceded with a bunch of spaces. Could the output of `amfora -v` be used for the test instead?

we actually prefer some functional test (do you think you can update the test to achieve it?)

**Comment by makeworld-the-better-one** [comment]
Maybe the best way would be to left-strip the lines before matching? Or a regex that skips over the spaces? I'm not sure how to do that though, I don't know Ruby sorry. Any chance I could get some help with it?

cc @vladimyr

**Comment by chenrui333** [comment]
let me see if I can help with the test.

**Comment by chenrui333** [comment]
Should be good now, passed in my local.

**Comment by chenrui333** [comment]
@makeworld-the-better-one Also submitted a PR to upgrade the repo to use go1.17 :)
makeworld-the-better-one/amfora#282

**Review by chenrui333 — APPROVED** [review]

**Comment by makeworld-the-better-one** [comment]
Can you explain what the test is doing? But glad to see it works, thank you!

Also I assume that PR is not necessary for merge?

**Comment by chenrui333** [comment]
Yeah, that PR is not blocking this PR merge.

Basically, doing some tests with the app (amfora, then 1, then 1, snapshot the operations, and assert the output, that it)

**Comment by makeworld-the-better-one** [comment]
Yeah, gotcha. Not sure why the input made the test work but glad it does.

**Comment by chenrui333** [comment]
> Yeah, gotcha. Not sure why the input made the test work but glad it does.

same here. Now it is up to date with the latest release. 🎉

**Pull request closed without merging**
