### PR TITLE
gmp 6.2.0

### PR DESCRIPTION
**Pull request by dunn**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by bayandin** [comment]
Revision bump for `mlton` and `ncview` are required

**Comment by dunn** [comment]
I'll try revision bumps, but I tried rebuilding those locally against the new gmp and it didn't seem to help.

**Comment by bayandin** [comment]
I have missed it, but we have the previous attempt in https://github.com/Homebrew/homebrew-core/pull/49171 and it failed with the same error.

Will keep this open for now for the case if you have any ideas what's going on

**Comment by dunn** [comment]
Oops, sorry about the duplicate PR!  I'm out of ideas, so I'll close this one.

**Pull request closed without merging**
