### PR TITLE
audit fixes for formulae with available upgrades

### PR DESCRIPTION
**Pull request by ilovezfs**
Note that the libmicrohttpd commit was moved to https://github.com/Homebrew/homebrew-core/pull/2230.

### CODE REVIEW

**Comment by ilovezfs** [comment]
libmodbus download is failing, yet I have no problems downloading it locally.

**Comment by ilovezfs** [comment]
Also, not sure why this happened, but we're distributing 3.1.1 as current stable, yet upstream designates 3.0.6 as current stable.

**Comment by ilovezfs** [comment]
Moved libmodbus to a separate PR: https://github.com/Homebrew/homebrew-core/pull/2226

**Comment by MikeMcQuaid** [comment]
👍

**Comment by ilovezfs** [comment]
@MikeMcQuaid would you pull this with or without the bottles?

**Comment by MikeMcQuaid** [comment]
Without as it doesn't seem like it'll affect any bottle contents.

**Comment by ilovezfs** [comment]
@MikeMcQuaid it will for libmicrohttpd

**Comment by MikeMcQuaid** [comment]
@ilovezfs I see. Probably need to split that into a separate PR, then.

**Comment by ilovezfs** [comment]
OK

**Pull request closed without merging**
