### PR TITLE
aws-sdk-cpp 1.9.170

### PR DESCRIPTION
**Pull request by jeroen**
Created with `brew bump-formula-pr`. Edit: the patch was merged upstream.

Edit: this needs `CI-long-timeout`

### CODE REVIEW

**Comment by jeroen** [comment]
I think the linux build fails because of OOM. Tried twice but doesn't seem to make a difference.

**Comment by carlocab** [comment]
Probably needs the self-hosted runner, but there are three or four other PRs waiting on it too.

**Comment by jeroen** [comment]
Thanks. Is there something I need to do to make it use the self-hosted runner?

**Comment by iMichka** [comment]
Re-running this. We have issues with our Linux self-hosted CI, I am trying to find out what is going on.

**Review by chenrui333 — APPROVED** [review]

**Comment by iMichka** [comment]
It worked. I increased the runner's memory from 12 Gb to 24 Gb.

This means that `aws-sdk-cpp` needs now more than 12 Gb of RAM to build. That's more than `llvm` and `rust` ...

Sponsors are welcome to pay for the increased hardware costs: https://github.com/sponsors/Homebrew, so that we can continue to ship `aws` stuff for free :)

**Pull request closed without merging**
