### PR TITLE
tokyo-tyrant: boneyard

### PR DESCRIPTION
**Pull request by apjanke**
Upstream development looks moribund.
Per discussion in https://github.com/Homebrew/legacy-homebrew/pull/37707

Goes with Homebrew/homebrew-boneyard#112
Goes with Homebrew/homebrew-php#3165

### CODE REVIEW

**Comment by DomT4** [comment]
👍 but will need to give PHP a heads-up. They use this in 6/7 formulae I believe.

**Comment by apjanke** [comment]
Yup. Thanks for catching that. I'll look in to it.

```
[/usr/local/Library/Taps/homebrew/homebrew-php/Formula on ⇄ master]
$ grep tokyo-tyrant *
php53-tokyotyrant.rb:  depends_on "tokyo-tyrant"
php54-tokyotyrant.rb:  depends_on "tokyo-tyrant"
php55-tokyotyrant.rb:  depends_on "tokyo-tyrant"
php56-tokyotyrant.rb:  depends_on "tokyo-tyrant"
```

**Comment by apjanke** [comment]
Making this "do not merge" until I get feedback from `homebrew/php`.

**Comment by apjanke** [comment]
Notified homebrew-php in https://github.com/Homebrew/homebrew-php/pull/3159.

**Comment by DomT4** [comment]
I'd be surprised if they want it, but we'll see.

**Comment by apjanke** [comment]
PHP has chosen to delete. Added a deletion PR over there: Homebrew/homebrew-php#3165

**Comment by DomT4** [comment]
This looks safe to 🚢 now. PHP have purged those formulae.

**Comment by MikeMcQuaid** [comment]
👍

**Comment by apjanke** [comment]
Rebased and merged.

**Pull request merged**
