### PR TITLE
fop 2.9

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Review by ZhongRuoyu — COMMENTED** [review]
Not announced yet: https://xmlgraphics.apache.org/fop/news.html

**Comment by chenrui333** [comment]
release email, https://lists.apache.org/thread/7wcbsomn8xjnw4lxqtw4oo9bf5fd6j19

**Comment by chenrui333** [comment]
I think wen can just ship it, the release notes is already in the codebase
https://github.com/apache/xmlgraphics-fop/commit/caba469ffe74ac9afa1ce189fbbb2643637d94f1

**Review by iMichka — APPROVED** [review]
It's in the news now :)

**Comment by chenrui333** [comment]
> It's in the news now :)

news is finally coming! XD

**Pull request merged**
