### PR TITLE
brew-postgresql-upgrade-database: add new command.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
This works nicely for me so let's throw it threw the review process and ask some users to test and see how it goes.

### CODE REVIEW

**Review by ilovezfs — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Actually, I think I make make this an external command instead.

**Comment by seebq** [comment]
If this works, great, I would support it (coming from this gist): 

https://gist.github.com/giannisp/ebaca117ac9e44231421f04e7796d5ca

Untested but I would approve!

**Review by ilovezfs — APPROVED** [review]

**Comment by mhw** [comment]
Hmm; the documentation says `brew postgresql-upgrade-database`, but the file containing the script is named `brew-postgresql-data-upgrade.rb` so you need to use `brew postgresql-data-upgrade` instead. On the plus side, the upgrade script worked fine for me once I figured out how to run it.

**Comment by MikeMcQuaid** [comment]
@mhw Oops, thanks, fixed in https://github.com/Homebrew/homebrew-core/commit/d474d480f34a5e7b9ce8948aa88c8fe88d5a61fd.

**Comment by olivierlacan** [comment]
@MikeMcQuaid This is so nice I finally upgraded an [old PG upgrade guide][1] I had lying around into [a post][2] that mentions this new command.

Thanks so much for putting the work into this. I remember thinking "why doesn't this exist" for years and that was the primary motivation behind that old brain dump of a Gist.

I did find that if postmaster.pid is locked, which stops or prevents the upgrade, re-running the commands tends to die at the [topmost version-checking conditional][3] even if the old data directory hasn't been upgraded yet.

I solved the issue by remove postmaster.pid and opening the `/usr/local/var/log/pg_upgrade_server.log` file which had the full upgrade command:

```
-----------------------------------------------------------------
  pg_upgrade run on Wed Feb  7 07:45:02 2018
-----------------------------------------------------------------

command: "/usr/local/Cellar/postgresql/9.5.0/bin/pg_ctl" -w -l "pg_upgrade_server.log" -D "/usr/local/var/postgres.old" -o "-p 50432 -c autovacuum=off -c autovacuum_freeze_max_age=2000000000  -c listen_addresses='' -c unix_socket_permissions=0700" start >> "pg_upgrade_server.log" 2>&1
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....FATAL:  pre-existing shared memory block (key 5432001, ID 65536) is still in use
HINT:  If you're sure there are no old server processes still running, remove the shared memory block or just delete the file "postmaster.pid".
 stopped waiting
pg_ctl: could not start server
Examine the log output.
``` 
I just re-ran the command at the top which did the trick.

I think not being able to re-run the upgrade command stems from the fact that call to  `mv` the `datadir` to `old_datadir` and initialize the new datadir happen much earlier than the actual `pg_ctl` upgrade command which then fails due to `postmaster.pid`, leaving the upgrade process in a state the script can't recover from.

Maybe it would help to check for `postmaster.pid` before running the `initdb` command?

[1]: https://gist.github.com/olivierlacan/e1bf5c34bc9f82e06bc0
[2]: http://olivierlacan.com/posts/migrating-homebrew-postgres-to-a-new-version/#update
[3]: https://github.com/Homebrew/homebrew-core/blob/ac2ba2b02772708fe648363e4ef9dad891d89ef6/cmd/brew-postgresql-upgrade-database.rb#L13-L17

**Comment by MikeMcQuaid** [comment]
@olivierlacan Thanks for the kind words! 

> Maybe it would help to check for postmaster.pid before running the initdb command?

Seems like a good idea. Could you try and open a pull request (as you seem to understand this better than I do)? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Pull request merged**
