### PR TITLE
kustomize: Fix the version string (x.y.z -> kustomize/vx.y.z)

### PR DESCRIPTION
**Pull request by icy**
kustomize: Fix the version string (x.y.z -> kustomize/vx.y.z)

The official binary will print an actual tag

```
$ kustomize version
{Version:kustomize/v3.8.1
```

while the current binary built by Homebrew just prints `{Version:3.8.1}`.
This PR will ensure that `kustomize version` command from the Homebrew binary
uses the same format string.

Explanation
===========

The official kustomize binary is built by (google) cloud build tools.
The build configuration is found at
https://github.com/kubernetes-sigs/kustomize/blob/ba0f583ee5cc47ca436df1910e467613c5e04980/releasing/cloudbuild.sh#L91

This template {.Version} actually uses any current tag (e.g, kustomize/v3.8.2)
https://github.com/kubernetes-sigs/kustomize/blob/ba0f583ee5cc47ca436df1910e467613c5e04980/releasing/cloudbuild.sh#L5

The build tool (goreleaser) is happy to use this non-sematic version
as a specific option is used, as seen in
https://github.com/kubernetes-sigs/kustomize/blob/ba0f583ee5cc47ca436df1910e467613c5e04980/releasing/cloudbuild.sh#L124

In short, the official build flag is, e.g,

    -X sigs.k8s.io/kustomize/api/provenance.version=kustomize/v3.8.2

not

    -X sigs.k8s.io/kustomize/api/provenance.version=3.8.2

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by icy** [comment]
cc: @monopole maybe you have a look and give some advice. Many thanks

**Comment by jonchang** [comment]
It looks like it's just the git tag. We could pass the output of `git tag --contains` instead?

**Comment by icy** [comment]
> It looks like it's just the git tag.

Exactly.

> We could pass the output of `git tag --contains` instead?

The command will print two tags, for example

```
$ git tag --contains
cmd/config/v0.7.0
kustomize/v3.8.2
```

(`git tag --points-at HEAD`) may also generate multiple outputs. I think we may need another command and/or arguments instead.

**Comment by jonchang** [comment]
> The command will print two tags, for example

Is that certainly the case? If you run `brew fetch -s kustomize` and then run `git tag --contains` in the directory that's checked out, what happens?

**Comment by icy** [comment]
> > The command will print two tags, for example
> 
> Is that certainly the case?

Definitively not ;)

> If you run `brew fetch -s kustomize` and then run `git tag --contains` in the directory that's checked out, what happens?

There is only single tag. Thanks for your pointing out. I didn't know that. (I understand that's because `brew fetch` doesn't fetch all tags from the remote .)

I have fixed in the recent commit.  

In the `test` block for the formula, there is still a hard-coded way

```
assert_match "kustomize/v#{version}", shell_output("#{bin}/kustomize version")
```

Do you think that's fine to keep this?

Thanks

**Review by SMillerDev — APPROVED** [review]
Thanks @icy ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by icy** [comment]
> Thanks @icy ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! +1 tada

Thanks a lot for your approval and your feedback. I'm happy that my tiny work helps Homebrew and its users:)

**Pull request closed without merging**
