### PR TITLE
Add `utid` formula

### PR DESCRIPTION
**Pull request by holdhack**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`utid` is the continuation of `duti` under another name, as per #13147

### CODE REVIEW

**Comment by fxcoudert** [comment]
`GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)`

**Comment by chdiza** [comment]
Also, it wasn't forked from the real `duti` repo, it was forked from someone's fork of the real `duti` repo.

**Comment by ilovezfs** [comment]
@jorvi what has changed in the situation since https://github.com/Homebrew/homebrew-core/pull/13147 ?

**Comment by jorvi** [comment]
Not much. There is basically the original repo (more or less abandoned). Russel his repo (from which I forked since he got rid of autoconf, but he is unresponsive) and @nivekkagicom his repo.
My premise basically: I use duti to set up my computer via dotfiles, and I believe there's a decent chunk of people who used duti via homebrew. Since duti got removed, I'd at least like to offer them an alternative with this. I'll be both the formula and repo maintainer, so that also smooths things out :)

**Comment by ilovezfs** [comment]
`duti` has not been removed https://github.com/Homebrew/homebrew-core/blob/master/Formula/duti.rb

**Comment by ilovezfs** [comment]
@jorvi given that we still have `duti` in homebrew/core, I'm closing this for now. But if `utid` becomes a project in its own right, with a homepage, and meets our notability requirements, we would be happy to reconsider it for inclusion. Until then, please consider hosting this in your own tap. See https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap

**Comment by jorvi** [comment]
@ilovezfs:

```
$ brew install duti
Error: No available formula with the name "duti" 
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

duti was deleted from homebrew/core in commit e1f1ba00:
  duti: fix for 10.13 (https://github.com/Homebrew/homebrew-core/issues/15416)
  - Recognize darwin17.* (like what's been done for the past two years);
  - Use a better test.

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show e1f1ba00^:Formula/duti.rb

If you still use this formula consider creating your own tap:
  http://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html
```

**Comment by ilovezfs** [comment]
@jorvi Interesting. For me
```
iMac-TMP:homebrew-core joe$ brew install duti
==> Downloading https://homebrew.bintray.com/bottles/duti-1.5.3.el_capitan.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring duti-1.5.3.el_capitan.bottle.2.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/duti/1.5.3: 5 files, 40.6KB
iMac-TMP:homebrew-core joe$ 
```

What is the output of `brew config` and `brew doctor` and `git -C $(brew --repo homebrew.core) status`?

**Comment by ilovezfs** [comment]
Sorry `git -C $(brew --repo homebrew/core) status` not `git -C $(brew --repo homebrew/core).status` ... I cannot type.

**Comment by jorvi** [comment]
brew config  
```
HOMEBREW_VERSION: 1.2.6-4-gac2cbd2
ORIGIN: https://github.com/Homebrew/brew
HEAD: ac2cbd2137006ebfe84d8584ccdcb5d78c1130d9
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 941ca36839ea354031846d73ad538e1e44e673f4
Core tap last commit: 85 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: N/A
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

brew doctor
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl https://github.com


```

git -C $(brew --repo homebrew/core) status
```
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    Formula/duti.rb

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.DS_Store
	Formula/.DS_Store
	Formula/utid.rb

no changes added to commit (use "git add" and/or "git commit -a")


```

I see the problem now.. I thought git pull + git reset --hard would completely mirror remote. Oh well, another thing learned. Sorry!

**Comment by ilovezfs** [comment]
No problem! Glad you've got it figured out!

**Pull request closed without merging**
