### PR TITLE
cargo-audit 0.15.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
license ref, https://github.com/RustSec/rustsec#license

**Comment by Moiss27** [comment]
> Created with `brew bump-formula-pr`.

what did you people do to my life, why is my email buried in this shit please explain

**Comment by Moiss27** [comment]
why is my email and life at the center of this shit, my life has been destroyed and im guessing you all play a part in that giant hack

**Comment by Moiss27** [comment]
now you all are very real, cant hide behind your screen name, i told you i will find whoever did this to me

**Comment by claui** [comment]
@Moiss27 Please check the _Watch_ button at the top of the page on https://github.com/homebrew/homebrew-core. You may have accidentally pressed it, possibly leading to a flood of email notifications. That’s a GitHub feature.
Try un-watching the homebrew-core repository and let me know if you still get unwanted emails.

**Comment by carlocab** [comment]
Screenshot 2021-07-03 at 16 41 23

You'll want to click either "Participating and @mentions" or "Ignore".

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
