### PR TITLE
URL updates for dupes imports

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by vszakats** [comment]
Jenkins was fine for `nano`, `ncurses` and `screen`. Failed for an obscure reason after subsequently committing `diffstat`. It tests okay locally:
```
$ brew test ./diffstat.rb 
Testing diffstat
==> Using the sandbox
```

**Comment by vszakats** [comment]
Looking up the PR that I though to be conflicting with this, it's in fact not, so this seems clear to merge.

**Comment by vszakats** [comment]
Any ❤️ for this one? Anything to fix on it?

**Comment by MikeMcQuaid** [comment]
Thanks again @vszakats!

**Pull request merged**
