### PR TITLE
git-fixup 1.3.0

### PR DESCRIPTION
**Pull request by glensc**
Created with:
```
brew bump-formula-pr git-fixup --url=https://github.com/keis/git-fixup/archive/v1.3.0.tar.gz
```

Inspired by https://github.com/Homebrew/homebrew-core/pull/38287

Refs:
- https://github.com/keis/git-fixup/pull/45

### CODE REVIEW

**Comment by glensc** [comment]
1.3.0 was released 9 days ago, why homebrew does not pick up the update automatically?

- https://github.com/keis/git-fixup/pull/45

**Comment by dawidd6** [comment]
We don't have an automated updating process (yet).

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you @glensc!

**Comment by zbeekman** [comment]
@glensc 
> 1.3.0 was released 9 days ago, why homebrew does not pick up the update automatically?

Upstream could always try using: https://github.com/marketplace/actions/bump-homebrew-formula to automate homebrew version bumps.

**Pull request closed without merging**
