### PR TITLE
pandoc-crossref 0.2.4.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sjackman** [comment]
```
Testing pandoc-crossref
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20161201-65551-tkt03b.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pandoc-crossref.rb --verbose
==> /usr/local/Cellar/pandoc/1.19/bin/pandoc -F /usr/local/Cellar/pandoc-crossref/0.2.4.1/bin/pandoc-crossref -o out.html hello.md
==> /bin/cat -et
Error: pandoc-crossref: failed
<"<p>Demo for pandoc-crossref. See equation eq.M-BM- 1 for cross-referencing. Display equations are labelled and numbered</p>$\n<p><br /><span class=\"math display\"><em>P</em><sub><em>i</em></sub>(<em>x</em>)=<em>u</em><em>m</em><sub><em>i</em></sub><em>a</em><sub><em>i</em></sub><em>x</em><sup><em>i</em></sup>M-bM-^@M-^AM-bM-^@M-^A(1)</span><br /></p>$\n"> expected but was
<"<p>Demo for pandoc-crossref. See equation eq.M-BM- 1 for cross-referencing. Display equations are labelled and numbered</p>$\n<p><span id=\"eq:eqn1\"><br /><span class=\"math display\"><em>P</em><sub><em>i</em></sub>(<em>x</em>)=<em>u</em><em>m</em><sub><em>i</em></sub><em>a</em><sub><em>i</em></sub><em>x</em><sup><em>i</em></sup>M-bM-^@M-^AM-bM-^@M-^A(1)</span><br /></span></p>$\n">.
```
https://bot.brew.sh/job/Homebrew%20Core/12422/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/test_pandoc_crossref/

**Comment by sjackman** [comment]
@ilovezfs Could you please update the test output? You may to simply the test to simply
```ruby
assert_match "See equation eq.M-BM- 1 for cross-referencing.", …
```

**Comment by lierdakil** [comment]
Um. Quick question. pandoc-crossref has a testsuite included. Why even bother with external tests that basically rehash included ones?
Disclamer: I don't know first thing about OSX, and have less than zero knowledge of homebrew.

**Comment by MikeMcQuaid** [comment]
> Um. Quick question. pandoc-crossref has a testsuite included. Why even bother with external tests that basically rehash included ones?
> Disclamer: I don't know first thing about OSX, and have less than zero knowledge of homebrew.

@lierdakil We're doing runtime integration tests to test our packaging/installation rather than testing the code works.

**Comment by lierdakil** [comment]
@MikeMcQuaid: I think in that case checking for non-zero exit code should be sufficient, right? I mean, if you're just checking if everything can find everything else and doesn't suddenly fail with something like "undefined library function".

**Comment by ilovezfs** [comment]
@lierdakil note that it's @MikeMcQuaid usually making that particular argument ;)

**Comment by ilovezfs** [comment]
@lierdakil I'd recommend reading the conversation in this PR: https://github.com/Homebrew/brew/pull/208

**Comment by sjackman** [comment]
@ilovezfs Do you agree then with reducing the test?
```ruby
assert_match "See equation eq.M-BM- 1 for cross-referencing.", …
```

**Comment by ilovezfs** [comment]
:rocket:

**Comment by sjackman** [comment]
Thanks, Joe.

**Comment by ilovezfs** [comment]
you're welcome :)

**Pull request closed without merging**
