### PR TITLE
ACE 6.4.2

### PR DESCRIPTION
**Pull request by jwillemsen**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by woodruffw** [comment]
Broken linkage on Yosemite only:

```
ace:
  * The installation was broken.
    Broken dylib links found:
      libExport_Lib.dylib
        libIPC_Tests_Server.dylib
        libTimer.dylib
        libtqtd.dylib
```

**Comment by jwillemsen** [comment]
@woodruffw Yes, I did see that but no idea why, as far as I remember we had that with 6.4.1 also as part of the automated build. Nothing changed in this area

**Comment by woodruffw** [comment]
Probably some minor oversight in their build scripts/makefiles. I'll take a look at them in a bit...

**Comment by fxcoudert** [comment]
The broken linkage is only in the `share/ace/examples` folder (in one of the examples actually, `Service_Configurator/IPC-tests/server`). Either we ignore the audit message, or we remove these examples.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Given that the tests work locally, the linkage issue is Yosemite-only, and is in one of the examples, I will be merging this shortly.

**Comment by jwillemsen** [comment]
Any idea why this fails with only yosemite? Very likely the same issue will happen with the next ACE version when we don't know the cause of this failure

**Comment by fxcoudert** [comment]
@jwillemsen no I am not sure what is triggering the issue. I do not have a Yosemite box to test myself, and since it is only in one of the examples it shouldn't be too much of a problem.

I have merged this through #11511 (for some reason I couldn't pull this request, I had to create another one).

**Comment by fxcoudert** [comment]
@jwillemsen thanks again for your contribution to Homebrew!

**Pull request closed without merging**
