### PR TITLE
imagemagick 6.9.7-0

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

---

Please remember to
```
brew mirror imagemagick
```
when merging.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Thanks!

**Comment by RandomDSdevel** [comment]
Just a random comment from a passing observer, but it appears you may have flipped the `url` and `mirror` stanzas this PR around, @zmwangx(, or was that intentional…?  Not sure what you meant by the 'Please remember to `brew mirror imagemagick` when merging.' part of this PR's description…)

**Comment by zmwangx** [comment]
> you may have flipped

Not me.

> was that intentional…

Intentional.

>  Not sure what you meant by the 'Please remember to brew mirror imagemagick when merging.' part of this PR's description…

You don't need to understand that. Only maintainers can use `brew mirror`, and it uploads the tarball to Bintray so that the URL https://dl.bintray.com/homebrew/mirror/imagemagick-6.9.7-0.tar.xz works.

**Comment by RandomDSdevel** [comment]
@zmwangx:  
>> …you may have flipped…
>
> Not me.  
>
> …

My apologies, then.  I didn't remember seeing the Bintray URL being the default before from my end-user perspective, though, so I wonder who did…?  

> …
>
>> …was that intentional…?  …
>
> Intentional.  
>
> …

Was it intentional on your part to leave things as they were, though, or is the new URL/mirror order expected now, at least for this formula?  I tend to keep an eye on major changes to Homebrew, even as a lowly end user, but I don't seem to have gotten the memo about this one.  

> …
>
>> …Not sure what you meant by the 'Please remember to brew mirror imagemagick when merging.' part of this PR's description…)  
>
> You don't need to understand that.  Only maintainers can use `brew mirror`…

Ah, so it's a developer command.  That solves _one_ mystery, then!  

> …, and it uploads the tarball to Bintray so that the URL https://dl.bintray.com/homebrew/mirror/imagemagick-6.9.7-0.tar.xz works.  

So I've gathered, but I'm _still_ wondering when the policy of doing so started, even as a currently still relatively inactive contributor.  Guess I should go do some digging, then…

**Comment by zmwangx** [comment]
```
grep -r dl.bintray.com
```

**Comment by RandomDSdevel** [comment]
And the results of running that command on my machine under `$(brew --prefix)` were:  

```
Caskroom/xquartz/.metadata/2.7.11/20161114190421.192/Casks/xquartz.rb:  url "https://dl.bintray.com/xquartz/downloads/XQuartz-#{version}.dmg"
Cellar/imagemagick/6.9.7-0/.brew/imagemagick.rb:  url "https://dl.bintray.com/homebrew/mirror/imagemagick-6.9.7-0.tar.xz"
Homebrew/Library/Homebrew/dev-cmd/mirror.rb:      destination_url = "https://dl.bintray.com/homebrew/mirror/#{filename}"
Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/apache-couchdb.rb:  url "https://dl.bintray.com/apache/couchdb/mac/#{version}/Apache-CouchDB-#{version}.zip"
Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/coyim.rb:  url "https://dl.bintray.com/twstrike/coyim/v#{version}/mac-bundle/coyim.dmg"
Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/ipe.rb:  url "https://dl.bintray.com/otfried/generic/ipe/#{version.major_minor}/ipe-#{version}-mac.dmg"
Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/squirrel.rb:  # dl.bintray.com/lotem/rime was verified as official when first introduced to the cask
Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/squirrel.rb:  url "https://dl.bintray.com/lotem/rime/Squirrel-#{version}.zip"
Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/vienna.rb:  url "https://dl.bintray.com/viennarss/vienna-rss/Vienna#{version}.tar.gz"
Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/xquartz.rb:  url "https://dl.bintray.com/xquartz/downloads/XQuartz-#{version}.dmg"
Homebrew/Library/Taps/caskroom/homebrew-versions/Casks/xquartz-beta.rb:  url "https://dl.bintray.com/xquartz/downloads/XQuartz-#{version}.dmg"
Homebrew/Library/Taps/homebrew/homebrew-apache/mod_fastcgi.rb:  url "https://dl.bintray.com/homebrew/mirror/mod_fastcgi-2.4.6.tar.gz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/artifactory.rb:  url "https://dl.bintray.com/jfrog/artifactory/jfrog-artifactory-oss-4.15.0.zip"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bibclean.rb:  mirror "https://dl.bintray.com/homebrew/mirror/bibclean-2.17.tar.gz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/dependency-check.rb:  url "https://dl.bintray.com/jeremy-long/owasp/dependency-check-1.4.4-release.zip"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/epstool.rb:  mirror "https://dl.bintray.com/homebrew/mirror/epstool-3.08.tar.gz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/griffon.rb:  url "https://dl.bintray.com/content/aalmiray/Griffon/griffon-1.5.0-bin.tgz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/groovy.rb:  url "https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.4.7.zip"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/groovysdk.rb:  url "https://dl.bintray.com/groovy/maven/apache-groovy-sdk-2.4.7.zip"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hping.rb:  mirror "https://dl.bintray.com/homebrew/mirror/hping-3.20051105.tar.gz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/imagemagick.rb:  url "https://dl.bintray.com/homebrew/mirror/imagemagick-6.9.7-0.tar.xz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lrzsz.rb:  url "https://dl.bintray.com/homebrew/mirror/lrzsz-0.12.20.tar.gz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/opencc.rb:  url "https://dl.bintray.com/byvoid/opencc/opencc-1.0.4.tar.gz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb:  mirror "https://dl.bintray.com/homebrew/mirror/openssl-1.0.2j.tar.gz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/osc.rb:    url "https://dl.bintray.com/pycurl/pycurl/pycurl-7.43.0.tar.gz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/primesieve.rb:  url "https://dl.bintray.com/kimwalisch/primesieve/primesieve-5.7.0.tar.gz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/protobuf.rb:    mirror "https://dl.bintray.com/homebrew/mirror/gmock-1.7.0.zip"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pushpin.rb:  url "https://dl.bintray.com/fanout/source/pushpin-1.14.0.tar.bz2"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rtpbreak.rb:  mirror "https://dl.bintray.com/homebrew/mirror/rtpbreak-1.3a.tgz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sbt.rb:  url "https://dl.bintray.com/sbt/native-packages/sbt/0.13.13/sbt-0.13.13.tgz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sbt.rb:    url "https://dl.bintray.com/sbt/native-packages/sbt/1.0.0-M4/sbt-1.0.0-M4.tgz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/snow.rb:  url "https://dl.bintray.com/homebrew/mirror/snow-20130616.tar.gz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tcc.rb:  mirror "https://dl.bintray.com/homebrew/mirror/tcc-0.9.26.tar.bz2"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/vert.x.rb:  url "https://dl.bintray.com/vertx/downloads/vert.x-3.3.3-full.tar.gz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/webp.rb:  mirror "https://dl.bintray.com/homebrew/mirror/webp-0.5.1.tar.gz"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xlslib.rb:  mirror "https://dl.bintray.com/homebrew/mirror/xlslib-package-2.5.0.zip"
Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zurl.rb:  url "https://dl.bintray.com/fanout/source/zurl-1.7.1.tar.bz2"
Homebrew/Library/Taps/homebrew/homebrew-versions/libpng12.rb:  mirror "https://dl.bintray.com/homebrew/mirror/libpng-1.2.54.tar.xz"
Homebrew/Library/Taps/homebrew/homebrew-versions/openssl101.rb:  mirror "https://dl.bintray.com/homebrew/mirror/openssl-1.0.1u.tar.gz"
```

I presume you got a similar list, @zmwangx?  In any case, [Homebrew/brew](https://github.com/Homebrew/brew) PR [#263](https://github.com/Homebrew/brew/pull/263) and related issues in [these issue and pull request search results](https://github.com/Homebrew/brew/issues?utf8=✓&q=brew%20mirror) actually helped me quench my curiosity to a more satisfactory degree, so I'll shut up now.

**Pull request closed without merging**
