### PR TITLE
libx11 1.8.5

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dancingfrog** [comment]
Is this a fix? `libx11 1.8.5` is failing to build on my system:
```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 13.4 (22F66)
      Kernel Version: Darwin 22.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      User Name: John Hall (johnhall)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2 hours, 40 minutes

$ brew --version
Homebrew 4.0.20
Homebrew/homebrew-core (git revision bb0b763bf02; last commit 2023-06-03)
```

**Comment by JollyRoger8X** [comment]
> Is this a fix? `libx11 1.8.4` is failing to build on my system:

I'm seeing build failures as well in macOS 12.6.6 (21G646). 😕

**Comment by dancingfrog** [comment]
So this *works* if I copy this formula into my local homebrew install (i.e. overwrite `/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libx11.rb`) and install it with:
```
brew install /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libx11.rb
```
... and then pin the formula to avoid the effects of `brew update`/`upgrade`:
```
brew pin libx11
```

**Comment by dancingfrog** [comment]
Please merge!

**Comment by michael-spadafora** [comment]
+1

**Comment by mariano-daniel** [comment]
> So this _works_ if I copy this formula into my local homebrew install (i.e. overwrite `/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libx11.rb`) and install it with:
> 
> ```
> brew install /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libx11.rb
> ```
> 
> ... and then pin the formula to avoid the effects of `brew update`/`upgrade`:
> 

Did not work for me for some reason:

```
$ brew install /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libx11.rb 
Warning: No available formula or cask with the name "/opt/homebrew/library/taps/homebrew/homebrew-core/formula/libx11.rb".
Please tap it and then try again: brew tap /opt
```

Tried tapping it, getting error `Error: Invalid tap name '/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libx11.rb'`

**Comment by Sternbach-Software** [comment]
What if brew would use `gmake` which is built for Silicon? make is built for  x86_64 i386.

**Comment by JollyRoger8X** [comment]
> So this _works_ if I copy this formula into my local homebrew install (i.e. overwrite `/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libx11.rb`) and install it with:
> 
> ```
> brew install /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libx11.rb
> ```
> 
> ... and then pin the formula to avoid the effects of `brew update`/`upgrade`:
> 
> ```
> brew pin libx11
> ```

Hmm... For some reason when I replace contents of the `libx11.rb` file at that path with the [changed file in this commit](https://raw.githubusercontent.com/Homebrew/homebrew-core/538ed26b5d6868144611338e332b4d119479224a/Formula/libx11.rb) and then do `brew install`, I get this error:

```
# brew install ~/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/libx11.rb 
Error: Failed to load cask: /Users/jr/.homebrew/Library/Taps/homebrew/homebrew-core/Formula/libx11.rb
Cask 'libx11' is unreadable: wrong constant name #<Class:0x00007fc19490ff80>
```

I'm not sure what I'm doing wrong here...

**Comment by jmcphers** [comment]
@JollyRoger8X I observed exactly the same thing when attempting the workaround. I notice we're both using user-level installations of Homebrew, so I wonder if that's got something to do with it.

In the install and compilation logs, however, I noticed that -- despite the "cask is unreadable" error -- it _is_ actually 1.8.5 that is getting downloaded and compiled. 

So the `stropts.h` compilation issue, whatever its source, is probably not addressed in 1.8.5.

**Comment by JollyRoger8X** [comment]
> @JollyRoger8X I observed exactly the same thing when attempting the workaround. I notice we're both using user-level installations of Homebrew, so I wonder if that's got something to do with it.
> 
> In the install and compilation logs, however, I noticed that -- despite the "cask is unreadable" error -- it _is_ actually 1.8.5 that is getting downloaded and compiled.
> 
> So the `stropts.h` compilation issue, whatever its source, is probably not addressed in 1.8.5.

That's what I'm thinking as well.

Luckily I have a copy of my `~/.homebrew` directory from another Mac that has the older version of `libx11` compiled properly. 

For now I'm just going to replace it with the good one and ping it with `brew pin libx11` until some time in the future.

**Comment by snazzybunny** [comment]
Is there any fix for this? Work around gives me `Cask 'libx11' is unreadable: wrong constant name #<Class:0x00007fdc7d824fb8>`

**Comment by dancingfrog** [comment]
I also get the "cask is unreadable error", followed by brew parsing the
contents of `
<your-specific-homebrew-install-dir>/Library/Taps/homebrew/homebrew-core/Formula/libx11.rb`


For folx getting Cask 'libx11' is unreadable: wrong constant name
#<Class:0x00007fdc7d824fb8> , did you run `brew update --force` *before*
replacing the contents of `libx11.rb`?

Thanks,
John Hall

Software Developer

Mapping & Data Analytics |  Center On Rural Innovation

he | him



(510) 306-1376
***@***.***
www.ruralinnovation.us
2 Quechee Road, Hartland, VT, 05048



[image: facebook] <https://www.facebook.com/RuralInno>
[image: twitter] <https://twitter.com/Ruralinno>
[image: linkedin] <https://www.linkedin.com/company/11099658>
[image: instagram] <https://www.instagram.com/ruralinno/>


Follow us on YouTube
<https://www.youtube.com/channel/UCyqbtSrv4Nad9vVv4dQptcA/featured?view_as=subscriber>

**Comment by dancingfrog** [comment]
I also get the "cask is unreadable" error, followed by brew parsing the contents of `<your-specific-homebrew-install-dir>/Library/Taps/homebrew/homebrew-core/Formula/libx11.rb`


For folx getting `Cask 'libx11' is unreadable: wrong constant name #<Class:0x00007fdc7d824fb8>` , did you run `brew update --force` *before*
replacing the contents of `libx11.rb`?

**Comment by kolibabas** [comment]
> Luckily I have a copy of my `~/.homebrew` directory from another Mac that has the older version of `libx11` compiled properly.
> 
> For now I'm just going to replace it with the good one and pin it with `brew pin libx11` until some time in the future.

@JollyRoger8X Which version is this? / More generically, which version of libx11 is the last "known good" to brew?

**Comment by JollyRoger8X** [comment]
> > Luckily I have a copy of my `~/.homebrew` directory from another Mac that has the older version of `libx11` compiled properly.
> > For now I'm just going to replace it with the good one and pin it with `brew pin libx11` until some time in the future.
> 
> @JollyRoger8X Which version is this? / More generically, which version of libx11 is the last "known good" to brew?

Well my working homebrew installation says it's version 1.8.4:

```
# brew info libx11
==> libx11: stable 1.8.4 [pinned at 1.8.4]
X.Org: Core X11 protocol client library
https://www.x.org/
/Users/jr/.homebrew/Cellar/libx11/1.8.3 (1,054 files, 7.0MB)
  Built from source on 2023-02-25 at 20:06:47
/Users/jr/.homebrew/Cellar/libx11/1.8.4 (1,054 files, 7.0MB) *
  Built from source on 2023-05-03 at 15:20:37
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libx11.rb
License: MIT
==> Dependencies
Build: pkg-config ✔, util-macros ✔, xtrans ✘
Required: libxcb ✔, xorgproto ✔
==> Analytics
install: 111,883 (30 days), 18,222 (90 days), 3,075,678 (365 days)
install-on-request: 1,192 (30 days), 280 (90 days), 28,945 (365 days)
build-error: 1,774 (30 days)
```

But it's definitely not that simple, because I remember trying to install version 1.8.4 during troubleshooting this issue and still had failures.

**Comment by dancingfrog** [comment]
Ok, wish I knew a better around and that brew provided more output
regarding the compilation and/or linking errors. Have you tried doing a
standard homebrew installation so that it installs "pours" (binary) of
library dependencies?

**Comment by JollyRoger8X** [comment]
> @dancingfrog yes so I tried arch --x86_64 /usr/local/homebrew/bin/brew /usr/local/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libx11.rb after doing a brew update --force.
> 
> ```
> 
> make[2]: *** [all-recursive] Error 1
> make[1]: *** [all] Error 2
> make: *** [all-recursive] Error 1
> 
> Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!
> 
> These open issues may also help:
> libx11 1.8.5 https://github.com/Homebrew/homebrew-core/pull/132483
> ```

Look a few lines earlier in that output and you should see a path to the build log (it will be something like: `~/Library/Logs/Homebrew/libx11/02.make`). That file will have the actual error message in it.

**Comment by snazzybunny** [comment]
> @snazzybunny:
> 
> > @dancingfrog yes so I tried arch --x86_64 /usr/local/homebrew/bin/brew /usr/local/homebrew/Library/Taps/homebrew/homebrew-core/Formula/libx11.rb after doing a brew update --force.
> > ```
> > 
> > make[2]: *** [all-recursive] Error 1
> > make[1]: *** [all] Error 2
> > make: *** [all-recursive] Error 1
> > 
> > Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!
> > 
> > These open issues may also help:
> > libx11 1.8.5 https://github.com/Homebrew/homebrew-core/pull/132483
> > ```
> 
> Look a few lines earlier in that output and you should see a path to the build log (it will be something like: `~/Library/Logs/Homebrew/libx11/02.make`). That file will have the actual error message in it.

Thank you. Looks like it is the same.

`In file included from xim_trans.c:30:
In file included from /usr/local/homebrew/Cellar/xtrans/1.5.0/include/X11/Xtrans/transport.c:64:
/usr/local/homebrew/Cellar/xtrans/1.5.0/include/X11/Xtrans/Xtranslcl.c:81:11: fatal error: 'stropts.h' file not found
# include <stropts.h>
          ^~~~~~~~~~~
...
1 error generated.
make[3]: *** [xim_trans.lo] Error 1
make[3]: *** Waiting for unfinished jobs....`

**Comment by JollyRoger8X** [comment]
> /usr/local/homebrew/Cellar/xtrans/1.5.0/include/X11/Xtrans/Xtranslcl.c:81:11: fatal error: 'stropts.h' file not found

Right. And if you take a look at the extras 1.5.0 source:

https://www.x.org/archive/individual/lib/xtrans-1.5.0.tar.gz

Line 81 is:

```
# include <stropts.h>
```

Interestingly, if you look at the _previous_ version of trans (1.4.0):

https://www.x.org/archive/individual/lib/xtrans-1.4.0.tar.gz

This include was conditionalized with `#ifdef __sun` like so:

```
#ifdef __sun
# include <stropts.h>
#else
# include <sys/stropts.h>
#endif
```

**Comment by snazzybunny** [comment]
@JollyRoger8X that makes sense. Did you replace stropts.h with sys/stropts.h to make it work?

**Comment by JollyRoger8X** [comment]
@snazzybunny:

> @JollyRoger8X that makes sense. Did you replace stropts.h with sys/stropts.h to make it work? Dont think stropts.h exists in OSX. Tried to comment it out and that didn't work either.

I haven't tried that, but I would be interested in the results.

I ended up just swapping my homebrew installation with a working one from another machine in their interest of expediency. 🙂

**Comment by snazzybunny** [comment]
I wish I had another machine with a working version :/. Hopefully it gets solved soon.

**Comment by JollyRoger8X** [comment]
Yeah, I got lucky.

😕🤞🏼

**Comment by desepticon** [comment]
I hope someone comes up with a fix for this as well. I'm on an Apple Silicon Mac and already have that version of homebrew installed. I'm trying to separately install the x86_64 version so I can run the new Apple Games Porting Toolkit, which is needed for that.

Been getting this error when install libx11. Very frustrating. Can't check it out until then.

**Comment by JollyRoger8X** [comment]
I haven't tried this myself, but I think if you can:
1. Tell Homebrew install version 1.4.0 of `xtrans`, and then 
2. Pin it down with `brew pin xtrans`, 
...you should avoid these errors.

**Comment by gl-mc** [comment]
> 2\. brew pin xtrans

That fixed the problem for me. I used the approach for downloading xtrans 1.4.0 detailed here: https://stackoverflow.com/a/7787703 and used the following version of xtrans: https://raw.githubusercontent.com/Homebrew/homebrew-core/cac285fb184abb168914776f932df264b8be025e/Formula/xtrans.rb

I had to unlink xtrans (which sat at version 1.5.0), then download xtrans.rb to a local file and then execute brew install xtrans.rb.

**Comment by lo-tp** [comment]
Working work around:
- Save this [xtrans.rb](https://[raw.githubusercontent.com/Homebrew/homebrew-core/cac285fb184abb168914776f932df264b8be025e/Formula/xtrans.rb](https://raw.githubusercontent.com/Homebrew/homebrew-core/cac285fb184abb168914776f932df264b8be025e/Formula/xtrans.rb)) to a local file
- Install it with `brew install xtrans.rb`
- rename the installed 1.4.0 xtans.rb to 1.5.0: `mv YourHomeBrewPath/Cellar/xtrans/1.4.0 YourHomeBrewPath/Cellar/xtrans/1.4.0
- Install libx11 1.8.4

**Comment by snazzybunny** [comment]
I'm getting this error now with the above suggestions lol. Thanks everyone.

`xim_trans.c:30:10: fatal error: 'X11/Xtrans/transport.c' file not found
#include <X11/Xtrans/transport.c>
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [xim_trans.lo] Error 1
make[3]: *** Waiting for unfinished jobs....`

**Comment by daladim** [comment]
Note: I applied @lo-tp suggestions. I was then greeted by a 
```
Error: An exception occurred within a child process:
  RuntimeError: YourHomebrewInstallationPath/opt/xtrans not present or broken
Please reinstall xtrans. Sorry :(
```

To fix it, I had to edit the link at `YourHomebrewInstallationPath/opt/xtrans`, so that it points at `YourHomebrewInstallationPath/Cellar/xtrans/1.5.0` as well

...and now I am running into the same error as @snazzybunny :-(

**Comment by daladim** [comment]
So, if I understand correctly, homebrew ships a broken xtrans package (but the libx11 package itself is fine)

**Comment by rossyoung5** [comment]
> I ran into the same issue as @snazzybunny . Here's how to fix (inspired by what @lo-tp wrote):
> 
> * Save this [xtrans.rb for version 1.4.0](https://raw.githubusercontent.com/Homebrew/homebrew-core/cac285fb184abb168914776f932df264b8be025e/Formula/xtrans.rb) to a local file
> * Install it with `brew install /path/to/xtrans.rb`
> * you now need to trick brew into thinking it did install 1.5.0.
>   You can rename 1.4.0 into 1.5.0, but since some formulae will try to include files from 1.4.0 (that was e.g. the error @snazzybunny has described), it is better to create a link: `cd YourHomebrewInstall/Cellar/xtrans ; ln -s 1.4.0 1.5.0`
> 
> Note: the previous steps also avoid such errors:
> 
> ```
> Error: An exception occurred within a child process:
>   RuntimeError: YourHomebrewInstallationPath/opt/xtrans not present or broken
> Please reinstall xtrans. Sorry :(
> ```
> 
> Now I was able to install libx11 by running `brew install libx11`

Can confirm this workaround is successful. Thanks for the persistence @daladim

**Comment by JollyRoger8X** [comment]
Teamwork makes the dream work! 

Thanks, everyone, for your contributions! 😊👍🏼

**Comment by miccal** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-core/pull/133898

**Comment by shingoxy** [comment]
> I ran into the same issue as @snazzybunny . Here's how to fix (inspired by what @lo-tp wrote):
> 
> * Save this [xtrans.rb for version 1.4.0](https://raw.githubusercontent.com/Homebrew/homebrew-core/cac285fb184abb168914776f932df264b8be025e/Formula/xtrans.rb) to a local file
> * Install it with `brew install /path/to/xtrans.rb`
> * you now need to trick brew into thinking it did install 1.5.0.
>   You can rename 1.4.0 into 1.5.0, but since some formulae will try to include files from 1.4.0 (that was e.g. the error @snazzybunny has described), it is better to create a link: `cd YourHomebrewInstall/Cellar/xtrans ; ln -s 1.4.0 1.5.0`
> 
> Note: the previous steps also avoid such errors:
> 
> ```
> Error: An exception occurred within a child process:
>   RuntimeError: YourHomebrewInstallationPath/opt/xtrans not present or broken
> Please reinstall xtrans. Sorry :(
> ```
> 
> Now I was able to install libx11 by running `brew install libx11`

Great, solved my problem when installing gaming porting toolkit on my M1 Pro macbook with Ventura.

Thanks!

**Pull request closed without merging**
