### PR TITLE
Updated xhyve to most active fork.

### PR DESCRIPTION
**Pull request by fmckeogh**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Current brew formula references dead, broken project; all active work is being done on dwoz's fork.

### CODE REVIEW

**Comment by apjanke** [comment]
I see a lot more recent commits on dwoz's fork, but not much in terms of stars and watchers on GitHub. Do you have a link to any community discussion, like a mailing list/forum/announcement/project web site, that would establish `dwoz/xhyve` as the new official repo?

If `dwoz/xhyve` is going to be the new main repo going forward, you might want to de-fork it from `mist64/xhyve`; it's GitHub convention that main/canonical repos for projects shouldn't be forks of other repos. GitHub support can assist with this, I believe.

Also note that since the Homebrew formula only has a stable release and no `devel` or `HEAD`, this change will have no effect on what's actually installed, since there are no newer releases from the `dwoz/xhyve` repo.

**Comment by chocol4te** [comment]
My main reason for this PR was that the current formula does not function. Neither of the two releases work correctly on Sierra or High Sierra, and the current HEAD will not boot on any system.

There was discussion [here](https://github.com/mist64/xhyve/issues/124) of moving development, and a few organisations were made, but no coherent structure was created nor any decisions made. I felt since dwoz's was the only fork where any work was being done it should be used, hopefully sparking a switch.

However, an alternative would be to remove the formula entirely as there seems little momentum or need anymore, especially due to the rise of containerisation.

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ brew formula-analytics xhyve
install events in the last 30 days for xhyve
=====================================================================================================
1 | xhyve                                                                           | 1,415 |  74.71%
2 | xhyve --HEAD                                                                    |   479 |  25.29%
=====================================================================================================
Total                                                                               | 1,894 |    100%
=====================================================================================================
```
Finding it hard to believe it doesn't work on Sierra at all.

**Comment by chocol4te** [comment]
Oh, very sorry, I must be mistaken. I believe I was testing on the wrong fork. Sorry.

**Comment by ilovezfs** [comment]
No worries. I hope the upstream situation improves here so it's easier for people to make contributions, but going to pass on this PR. Thanks for bringing the stagnation to our attention.

**Pull request closed without merging**
