### PR TITLE
erlang 24.0.6

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by carlocab** [comment]
Looks like this fails to build the docs on Linux with
```
error : xmlAddEntity: invalid redeclaration of predefined entity
```

Can we just skip this step on Linux, maybe? CC @gromgit @Homebrew/linux

**Comment by alaadahmed** [comment]
any hope? 😕

**Comment by Bo98** [comment]
Looks like this is the error:

```
 escript: exception error: no match of right hand side value {error,beam_lib,
                                                    {not_a_beam_file,
                                                     '/tmp/erlang-20210904-16421-1wqctvd/otp_src_24.0.6/erts/preloaded/ebin/._atomics.beam'}}
```

That `._atomics.beam` should not be there. The 24.0.6 tarball seems to be busted and contains a lot of hidden metadata files.

**Comment by alaadahmed** [comment]
I think this should be closed because we already have version 24.1.2, and no sense to keep this issue opened.

**Pull request closed without merging**
