### PR TITLE
elixirscript 0.20.0

### PR DESCRIPTION
**Pull request by Jerzerak**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---
- Bump elixirscript stable version from 0.19.0 to 0.20.0

### CODE REVIEW

**Comment by DomT4** [comment]
Install died:
```
==> mix std_lib
Could not find "rebar", which is needed to build dependency :fs
I can install a local copy which is just used by Mix
Shall I install rebar? [Yn] ** (Mix) Could not find "rebar" to compile dependency :fs, please ensure "rebar" is available
```

**Comment by Jerzerak** [comment]
@DomT4 Sorry, just noticed this...I'll get this fixed ASAP!

**Comment by ilovezfs** [comment]
@Jerzerak There's a 0.21.0 now

**Comment by ilovezfs** [comment]
Closing in favor of https://github.com/Homebrew/homebrew-core/pull/3158.

@Jerzerak maybe you can do the next update when it comes out!

**Pull request closed without merging**
