### PR TITLE
chibi-scheme: use tarball with stable hash

### PR DESCRIPTION
**Pull request by lassik**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by lassik** [comment]
cc @ashinn from https://github.com/ashinn/chibi-scheme

**Review by SMillerDev — CHANGES_REQUESTED** [review]
Downgrading to http and a completely different host seems like a problem. Why change this?

**Comment by lassik** [comment]
The old tarball was auto-generated by GitHub from a Git tag. Those are not guaranteed to have stable hashes.

Chanegd from HTTP to HTTPS.

**Comment by lassik** [comment]
The old tarball was auto-generated by GitHub from a Git tag. Those are not guaranteed to have stable hashes.

Chanegd from HTTP to HTTPS.

**Comment by ashinn** [comment]
FWIW made a github release with a stable asset: https://github.com/ashinn/chibi-scheme/releases/download/0.11/chibi-scheme-0.11.0.tgz

**Comment by daeho-ro** [comment]
I opened a PR for url changes to the release artifact here,
- https://github.com/Homebrew/homebrew-core/pull/196493

and close this.

**Pull request closed without merging**
