### PR TITLE
kyma-cli 1.11.1

### PR DESCRIPTION
**Pull request by clebs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Moisan** [comment]
Thank you @clebs  for your first contribution! Without people like you, we couldn't run this project.

Note that next time you can use `brew bump-formula-pr` to quickly bump a formula version.

**Comment by clebs** [comment]
Hi @Moisan,
Thanks for such a quick response! 

I actually tried to use that tool and it was unfortunately impossible to get it to work...

So I resorted to the manual guide on the documentation.

What is the reason for rejecting the PR?

**Comment by jonchang** [comment]
We use a rebase workflow so pull requests won't show up as merged. This change was committed in https://github.com/Homebrew/homebrew-core/commit/93b1e3832d8d4574ec68c6a60b3ee9b72317d3a6

**Comment by clebs** [comment]
Hi @jonchang,
ah I see... Thanks for clarifying! I was confused because in other version bump PRs I saw a comment saying a merge had been triggered.

**Pull request closed without merging**
