### PR TITLE
cppzmq (new formula)

### PR DESCRIPTION
**Pull request by jmuncaster**
Add C++ interface to ZeroMQ.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
We've generally passed on header-only C++ projects in the past as our feeling is they are better fits for a language-specific package manager or vendoring in your projet.

**Comment by jmuncaster** [comment]
I am not aware of a comparable C++ specific package alternative. We use homebrew to avoid vendoring and to simplify new project setup. Is there really a difference between a header-only C++ library and a compiled one? Indeed, some calability (template libraries) cannot be distributed in compiled form.

**Comment by MikeMcQuaid** [comment]
> Is there really a difference between a header-only C++ library and a compiled one? Indeed, some capability (template libraries) cannot be distributed in compiled form.

Yes. In this case all Homebrew is really doing for you is moving files into a particular location.

Passing on this for now, sorry. Please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead. Thanks!

**Comment by jmuncaster** [comment]
Thanks for the tip

For posterity: `brew tap jmuncaster/homebrew-header-only`

**Pull request closed without merging**
