### PR TITLE
nodebrew: remove formula

### PR DESCRIPTION
**Pull request by rhysd**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- N/A: Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- N/A: Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I removed `nodebrew` formula because nodebrew installed with Homebrew does not work because of `curl` problem and the author of nodebrew won't fix this issue. Homebrew should no longer provide `nodebrew` formula.

https://github.com/hokaccha/nodebrew/issues/57

### CODE REVIEW

**Comment by ilovezfs** [comment]
You need to run
```
mkdir -p ~/.nodebrew/src
```

**Comment by rhysd** [comment]
@ilovezfs Then I think we should make the directory in this formula. Is that acceptable?

**Comment by ilovezfs** [comment]
We generally try not to alter anything in $HOME. It would be nice if upstream would create ~/.nodebrew/src just in time if it doesn't already exist.

**Comment by rhysd** [comment]
But as I said the author will never fix this. Then my second suggestion is adding a note to this formula. What do you think?

**Comment by ilovezfs** [comment]
>But as I said the author will never fix this.

This may not be true if you point out that it works fine as long as the `src` directory exists.

**Comment by MikeMcQuaid** [comment]
I don't think we should remove formulae because one part of the functionality doesn't work.

**Comment by rhysd** [comment]
@ilovezfs OK, I report this to the repository at first.

**Comment by rhysd** [comment]
@MikeMcQuaid `nodebrew install` and `nodebrew install-binary` not working means that nodebrew does not work at all.

**Comment by MikeMcQuaid** [comment]
Ok.

**Comment by ilovezfs** [comment]
@rhysd there have been 2,453 install events in the last 30 days without anyone else raising this, so it's likely working for at least a few of the people installing it.

**Comment by rhysd** [comment]
@ilovezfs maybe because I already saw some people gave up using nodebrew via homebrew silently. But, yeah, as you're saying, I also think all 2453 people faced this issue. Thank you for the information.

**Comment by mecca831** [comment]
The formula actually tries to create the folders by calling `nodebrew setup_dirs` but it's not working. See https://github.com/Homebrew/homebrew-core/blob/master/Formula/nodebrew.rb#L12

**Comment by mecca831** [comment]
Turned out `$HOME` is set to a temp folder and `.nodebrew` is created there. Anyway to specify the correct `$HOME` so the formula will work?

    ==> echo $HOME
    /private/tmp/nodebrew-20170727-74028-hens6d/nodebrew-0.9.7/.brew_home

**Comment by MikeMcQuaid** [comment]
We don't allow writing to `$HOME` from a formula.

**Comment by mecca831** [comment]
How would you suggest this be handled? `nodebrew` expects `~/.nodebrew/src` to exist after installation.

**Comment by MikeMcQuaid** [comment]
Tell the user to manually create it in the `caveats` in the short-term and change `nodebrew`'s behaviour in the longer-term. Note that the current system won't work with any multiuser package manager.

**Comment by mecca831** [comment]
PR created for the caveat update.

> Note that the current system won't work with any multiuser package manager.
By current system you mean homebrew? Can you elaborate more on this?

**Comment by MikeMcQuaid** [comment]
@mecca831 I mean any software that relies on the installer/package manager creating files in `$HOME` will not work for multiple users unless it creates these files in every `$HOME` directory. In general global configuration like this should be change in the upstream project so it can be done in the Homebrew prefix and/or run on first run automatically.

**Pull request closed without merging**
