### PR TITLE
git-mediate 1.1.0

### PR DESCRIPTION
**Pull request by yairchu**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Error: [S-4804]
         Stack failed to construct a build plan.
         
         While constructing the build plan, Stack encountered the following errors. The 'Stack
         configuration' refers to the set of package versions specified by the snapshot (after any
         dropped packages, or pruned GHC boot packages; if a boot package is replaced, Stack prunes
         all other such packages that depend on it) and any extra-deps:
         
         In the dependencies for base-compat-0.13.1:
           * unix needed, but this GHC boot package has been pruned from the Stack configuration. You
             need to add the package explicitly to extra-deps. (latest matching version is 2.8.5.1).
         The above is/are needed due to git-mediate-1.1.0 -> base-compat-0.13.1
         
         In the dependencies for git-mediate-1.1.0:
           * directory must match >=1.2, but this GHC boot package has been pruned from the Stack
             configuration. You need to add the package explicitly to extra-deps. (latest matching
             version is 1.3.8.5).
           * filepath must match >=1.3, but this GHC boot package has been pruned from the Stack
             configuration. You need to add the package explicitly to extra-deps. (latest matching
             version is 1.5.3.0).
           * process must match >=1.2, but this GHC boot package has been pruned from the Stack
             configuration. You need to add the package explicitly to extra-deps. (latest matching
             version is 1.6.23.0).
         The above is/are needed since git-mediate is a build target.
         
         In the dependencies for optparse-applicative-0.18.1.0:
           * process must match >=1.0 && <1.7, but this GHC boot package has been pruned from the
             Stack configuration. You need to add the package explicitly to extra-deps. (latest
             matching version is 1.6.23.0).
         The above is/are needed due to git-mediate-1.1.0 -> optparse-applicative-0.18.1.0
         
         In the dependencies for unix-compat-0.7.2:
           * unix must match >=2.6 && <2.9, but this GHC boot package has been pruned from the Stack
             configuration. You need to add the package explicitly to extra-deps. (latest matching
             version is 2.8.5.1).
         The above is/are needed due to git-mediate-1.1.0 -> unix-compat-0.7.2
         
         Some different approaches to resolving some or all of this:
         
           * Recommended action: try adding the following to your extra-deps in
             /tmp/git-mediate-20240920-4787-2a8ejz/git-mediate-1.1.0/stack.yaml
             (project-level configuration):
             
             - directory-1.3.8.5@sha256:fbeec9ec346e5272167f63dcb86af513b457a7b9fc36dc818e4c7b81608d612b,3166
             - filepath-1.5.3.0@sha256:0c64bc9a4f5946c86a8f0527bf40c8ba51e2c02d36eea0e20ea558c8d94166e8,4945
             - process-1.6.23.0@sha256:684028fb5ac3d1c7657fe516f2a442d95a53ae2fcf6f6151[544](https://github.com/Homebrew/homebrew-core/actions/runs/10962867636/job/30443201385?pr=191364#step:4:545)f3ed5289f6320,2644
             - unix-2.8.5.1@sha256:3f702a252a313a7bcb56e3908a14e7f9f1b40e41b7bdc8ae8a9605a1a8686f06,9808
```

**Comment by yairchu** [comment]
Thanks @chenrui333!

I found that I needed to explicitly specify to use `ghc@9.6` to build and now it just works, no more build failure etc.

How do we move forward now?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@yairchu works for us, can you log an issue about the ghc 9.8 or ghc 9.10 support? Thanks!

**Comment by yairchu** [comment]
> @yairchu works for us, can you log an issue about the ghc 9.8 or ghc 9.10 support? Thanks!

I just checked locally and there's no issue with building with 9.8 (by changing the "resolver" in `stack.yaml` to `nightly-2024-09-23`).

Now looking into 9.10 as well.

**Comment by yairchu** [comment]
Adding info on build with GHC 9.10, using `stack test --compiler ghc-9.10.1` (overriding GHC version from resolver as no stackage resolver for GHC 9.10 is available yet), looks like adding the following to `stack.yaml` makes the build work:

```
extra-deps:
- directory-1.3.8.5@sha256:fbeec9ec346e5272167f63dcb86af513b457a7b9fc36dc818e4c7b81608d612b,3166
- filepath-1.4.300.2@sha256:345cbb1afe414a09e47737e4d14cbd51891a734e67c0ef3d77a1439518bb81e8,5900
- process-1.6.23.0@sha256:684028fb5ac3d1c7657fe516f2a442d95a53ae2fcf6f6151544f3ed5289f6320,2644
- unix-2.8.5.1@sha256:3f702a252a313a7bcb56e3908a14e7f9f1b40e41b7bdc8ae8a9605a1a8686f06,9808
```

(which won't be necessary when stackage moves on to support GHC 9.10)

**Pull request merged**
