### PR TITLE
libqalculate and qalculate-gtk 4.3.0

### PR DESCRIPTION
**Pull request by m-zheng**
Update libqalculate and qalculate-gtk to 4.3.0 in a single PR to pass all tests.

### CODE REVIEW

**Comment by m-zheng** [comment]
The build failed on Ubuntu mysteriously. Can any reviewers have a look because the error message is not informative?

**Comment by carlocab** [comment]
This seems to be the error:
```
  /bin/bash: line 1: gdbus-codegen: command not found
```

**Comment by m-zheng** [comment]
> This seems to be the error:
> 
> ```
>   /bin/bash: line 1: gdbus-codegen: command not found
> ```

Thanks @carlocab. A quick google shows `apt-get install libglib2.0-dev-bin` can fix the error. But I have no ideas how/where to execute the command. Can you kindly assist or point me to the right direction so that I can follow up?

**Comment by carlocab** [comment]
We don't want to use `apt`, since that's not portable. Dependencies should be managed by `brew`.

I think this should've been fixed on `master` now, though. I've rebased this to see if that helps.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
