### PR TITLE
flow 0.49.0

### PR DESCRIPTION
**Pull request by mroch**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
should be
```
  url "https://github.com/facebook/flow/archive/v0.49.0.tar.gz"
  sha256 "f682e87c95baba37f8303534a91b7518b9281299bc78fd4c568f893e4b7bd3c5"
  head "https://github.com/facebook/flow.git"
```

**Comment by mroch** [comment]
Do you mean to pull `head` inside the `stable` block, or remove the block?

**Comment by ilovezfs** [comment]
The latter :)

**Comment by mroch** [comment]
thanks @ilovezfs!

**Comment by ilovezfs** [comment]
You're welcome! Thanks for the PR @mroch! Shipped :rocket:

**Pull request closed without merging**
