### PR TITLE
ppsspp 1.16.3

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
```
2023-09-22T12:26:03.1903714Z /tmp/ppsspp-20230922-16041-16lrner/SDL/SDLVulkanGraphicsContext.cpp: In member function ‘bool SDLVulkanGraphicsContext::Init(SDL_Window*&, int, int, int, int, int, std::string*)’:
2023-09-22T12:26:03.1904287Z /tmp/ppsspp-20230922-16041-16lrner/SDL/SDLVulkanGraphicsContext.cpp:117:81: error: ‘union SDL_SysWMinfo::<unnamed>’ has no member named ‘wl’
2023-09-22T12:26:03.1904652Z   117 |                 vulkan_->InitSurface(WINDOWSYSTEM_WAYLAND, (void*)sys_info.info.wl.display, (void *)sys_info.info.wl.surface);
2023-09-22T12:26:03.1904780Z       |                                                                                 ^~
2023-09-22T12:26:03.1905223Z /tmp/ppsspp-20230922-16041-16lrner/SDL/SDLVulkanGraphicsContext.cpp:117:115: error: ‘union SDL_SysWMinfo::<unnamed>’ has no member named ‘wl’
2023-09-22T12:26:03.1905765Z   117 |                 vulkan_->InitSurface(WINDOWSYSTEM_WAYLAND, (void*)sys_info.info.wl.display, (void *)sys_info.info.wl.surface);
2023-09-22T12:26:03.1905915Z       |                                                                                                                   ^~
2023-09-22T12:26:03.1906164Z make[2]: *** [CMakeFiles/native.dir/build.make:121: CMakeFiles/native.dir/SDL/SDLVulkanGraphicsContext.cpp.o] Error 1
2023-09-22T12:26:03.1906308Z make[2]: *** Waiting for unfinished jobs....
2023-09-22T12:26:03.1906552Z make[2]: Leaving directory '/tmp/ppsspp-20230922-16041-16lrner/build'
2023-09-22T12:26:03.1906714Z make[1]: *** [CMakeFiles/Makefile2:573: CMakeFiles/native.dir/all] Error 2
2023-09-22T12:26:03.1906934Z make[1]: Leaving directory '/tmp/ppsspp-20230922-16041-16lrner/build'
2023-09-22T12:26:03.1907040Z make: *** [Makefile:149: all] Error 2
2023-09-22T12:26:03.1907050Z 
2023-09-22T12:26:03.1907181Z [34m==>[0m [1mFormula[0m
2023-09-22T12:26:03.1907471Z Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/p/ppsspp.rb
```

**Comment by iMichka** [comment]
Let's try with 1.16.3

**Comment by SMillerDev** [comment]
```
  /tmp/ppsspp-20230924-16045-1yibjgs/SDL/SDLVulkanGraphicsContext.cpp: In member function ‘bool SDLVulkanGraphicsContext::Init(SDL_Window*&, int, int, int, int, int, std::string*)’:
  /tmp/ppsspp-20230924-16045-1yibjgs/SDL/SDLVulkanGraphicsContext.cpp:117:81: error: ‘union SDL_SysWMinfo::<unnamed>’ has no member named ‘wl’
    117 |                 vulkan_->InitSurface(WINDOWSYSTEM_WAYLAND, (void*)sys_info.info.wl.display, (void *)sys_info.info.wl.surface);
        |                                                                                 ^~
  /tmp/ppsspp-20230924-16045-1yibjgs/SDL/SDLVulkanGraphicsContext.cpp:117:115: error: ‘union SDL_SysWMinfo::<unnamed>’ has no member named ‘wl’
    117 |                 vulkan_->InitSurface(WINDOWSYSTEM_WAYLAND, (void*)sys_info.info.wl.display, (void *)sys_info.info.wl.surface);
        |                                                                                                                   ^~
  make[2]: *** [CMakeFiles/native.dir/build.make:121: CMakeFiles/native.dir/SDL/SDLVulkanGraphicsContext.cpp.o] Error 1
  make[2]: Leaving directory '/tmp/ppsspp-20230924-16045-1yibjgs/build'
  make[1]: *** [CMakeFiles/Makefile2:573: CMakeFiles/native.dir/all] Error 2
```

**Comment by iMichka** [comment]
Looks like our `sdl` has no wayland support (similar issue as https://github.com/anbox/anbox/issues/915).

**Pull request closed without merging**
