### PR TITLE
rust 1.18.0

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@alexcrichton for cargo is it correct to build the latest tag (0.19.0) to pair with 1.18.0? And should we be bootstrapping cargo from

https://static.rust-lang.org/dist/2017-04-27/cargo-nightly-x86_64-apple-darwin.tar.gz

or from something else?

(It looks like https://github.com/rust-lang/rust/blob/1.18.0/src/stage0.txt no longer records the revision so I assume we're back to the nightly with the same date?)

**Review by ilovezfs — CHANGES_REQUESTED** [review]
Let's get cargo bootstrap updated to whatever it should be now.

**Comment by ilovezfs** [comment]
@JCount thinks the correct cargo bootstrap URL is now

https://static.rust-lang.org/dist/2017-04-27/cargo-0.18.0-x86_64-apple-darwin.tar.gz

based on

https://github.com/rust-lang/rust/blob/1.18.0/src/bootstrap/bootstrap.py#L204

**Comment by ilovezfs** [comment]
Thanks @Alex! Shipped :rocket:

**Comment by alexcrichton** [comment]
Looks good to me!

**Comment by alex** [comment]
Thanks for dragging this over the finish line, I was off the grid for a bit :)

**Pull request closed without merging**
