### PR TITLE
hledger 0.27.1

### PR DESCRIPTION
**Pull request by ilovezfs**
- version bump
- builds with GHC 8 without patching

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
👍

**Comment by ilovezfs** [comment]
Not sure what's up with the test, but I opened an issue for that: https://github.com/simonmichael/hledger/issues/352

**Comment by ilovezfs** [comment]
Looks like upstream knows what the problem is and is going to tag a new release for us! https://github.com/simonmichael/hledger/issues/351#issuecomment-221908883

**Comment by MikeMcQuaid** [comment]
@ilovezfs 🎉 Happy to apply upstream commit as a patch if it makes it faster.

**Comment by ilovezfs** [comment]
Woo hoo :green_apple:

**Comment by simonmichael** [comment]
Thanks!

**Pull request closed without merging**
