### PR TITLE
dlib.rb<add gui support using X11>

### PR DESCRIPTION
**Pull request by cxwx**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
This is against our acceptable formula rules: https://docs.brew.sh/Acceptable-Formulae#stuff-that-builds-a-gui-by-default-but-doesnt-have-to

**Comment by cxwx** [comment]
so homebrew doesn't accept any formula with X11 lib?

**Comment by SMillerDev** [comment]
More accurately we don't accept additions that require X11. Existing formula are accepted.

**Comment by cxwx** [comment]
thanks anyway.

**Comment by iMichka** [comment]
You can still host the formula in a tap, see https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap and https://docs.brew.sh/Taps

**Comment by cxwx** [comment]
> You can still host the formula in a tap, see https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap and https://docs.brew.sh/Taps

well, thanks for advise

**Pull request closed without merging**
