### PR TITLE
gdal 3.2.0

### PR DESCRIPTION
**Pull request by mprince**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@mprince you would get some inspirations from this PR, #63953

**Comment by chenrui333** [comment]
@mprince, just a note, we actually separate out the changes for each formula into its own commit.

**Comment by chenrui333** [comment]
let me help you out a bit

**Comment by mprince** [comment]
@chenrui333 it makes sense. I know you would like one commit for the changes of the current formula and I see you do that when merging to master. I will note that for next time. Thanks for making the changes.

**Comment by chenrui333** [comment]
no problem, thanks for your contributions!

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
