### PR TITLE
chezmoi 2.9.5

### PR DESCRIPTION
**Pull request by twpayne**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
This is not marked as a release on https://github.com/twpayne/chezmoi/releases

**Comment by twpayne** [comment]
It's in progress: https://github.com/twpayne/chezmoi/actions/runs/1660461248

**Comment by twpayne** [comment]
Now released: https://github.com/twpayne/chezmoi/releases/tag/v2.9.5

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Thanks @twpayne !

**Pull request closed without merging**
