### PR TITLE
swift 5.9

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Inreplace issue:
```
    expected replacement of "-enable-library-evolution>" with "\\0 \"$<$<COMPILE_LANGUAGE:Swift>:SHELL:-Xfrontend -disable-implicit-concurrency-module-import>\" \"$<$<COMPILE_LANGUAGE:Swift>:SHELL:-Xfrontend -disable-implicit-string-processing-module-import>\""

```

**Comment by chenrui333** [comment]
this PR has to wait a bit (lots of long build PRs rn)

**Comment by FullQueueDeveloper** [comment]
Any updates on merging this PR?

**Comment by Bo98** [comment]
Will be taking a look at this tomorrow afternoon.

**Comment by Bo98** [comment]
Might take a couple CI runs as usual - experimenting here in hope the SDK issue is fixed.

**Comment by SMillerDev** [comment]
```
2023-09-25T09:40:42.9774931Z <unknown>:0: warning: the '-enable-experimental-cxx-interop' flag is deprecated; please pass '-cxx-interoperability-mode=' instead
2023-09-25T09:40:42.9775189Z <unknown>:0: note: Swift will maintain source compatibility for imported APIs based on the selected compatibility mode, so updating the Swift compiler will not change how APIs are imported
2023-09-25T09:40:42.9775397Z <unknown>:0: warning: unable to perform implicit import of "_Concurrency" module: no such module found
2023-09-25T09:40:42.9775497Z ninja: build stopped: subcommand failed.
2023-09-25T09:40:42.9775522Z 
```

**Comment by SMillerDev** [comment]
```console
2023-09-28T07:00:35.0043000Z env MACOSX_DEPLOYMENT_TARGET=10.15 /home/linuxbrew/.linuxbrew/opt/cmake/bin/cmake -G Ninja -DCMAKE_MAKE_PROGRAM=/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/ninja -DCMAKE_BUILD_TYPE:=Release -DCMAKE_Swift_FLAGS=' -module-cache-path "/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/module-cache"' -DCMAKE_Swift_COMPILER:=/home/linuxbrew/.linuxbrew/Cellar/swift/5.9/libexec/bin/swiftc -DCMAKE_C_COMPILER:=/home/linuxbrew/.linuxbrew/Cellar/swift/5.9/libexec/bin/clang -DCMAKE_AR:PATH=/home/linuxbrew/.linuxbrew/opt/binutils/bin/ar -DCMAKE_RANLIB:PATH=/home/linuxbrew/.linuxbrew/opt/binutils/bin/ranlib -DLLBuild_DIR=/tmp/swift-20230928-9967-1785byu/build/llbuild-linux-x86_64/cmake/modules -DTSC_DIR=/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/tsc/cmake/modules -DArgumentParser_DIR=/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-argument-parser/cmake/modules -DSwiftDriver_DIR=/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-driver/cmake/modules -DSwiftSystem_DIR=/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-system/cmake/modules -DSwiftCollections_DIR=/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-collections/cmake/modules -DSwiftCrypto_DIR=/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-crypto/cmake/modules -DSwiftASN1_DIR=/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-asn1/cmake/modules -DSwiftCertificates_DIR=/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-certificates/cmake/modules /tmp/swift-20230928-9967-1785byu/swiftpm
2023-09-28T07:00:35.0043412Z --- bootstrap: note: Building SwiftPM (with a freshly built swift-bootstrap)
2023-09-28T07:00:35.0043581Z Error: close error: Unknown error -1
2023-09-28T07:00:35.0048421Z env SWIFTCI_USE_LOCAL_DEPS=1 SWIFTPM_MACOS_DEPLOYMENT_TARGET=10.15 LD_LIBRARY_PATH=/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/tsc/lib:/tmp/swift-20230928-9967-1785byu/build/llbuild-linux-x86_64/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/yams/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-argument-parser/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-crypto/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-driver/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-system/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-collections/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-asn1/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-certificates/lib:/home/linuxbrew/.linuxbrew/Cellar/swift/5.9/libexec/lib/swift/linux SWIFT_EXEC=/home/linuxbrew/.linuxbrew/Cellar/swift/5.9/libexec/bin/swiftc SWIFT_DRIVER_SWIFT_EXEC=/home/linuxbrew/.linuxbrew/Cellar/swift/5.9/libexec/bin/swiftc CC=/home/linuxbrew/.linuxbrew/Cellar/swift/5.9/libexec/bin/clang SWIFTPM_CUSTOM_LIBS_DIR=/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/pm /tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/bin/swift-bootstrap --build-path /tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64 --configuration release -Xswiftc -module-cache-path -Xswiftc /tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/module-cache -Xmanifest -module-cache-path -Xmanifest /tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/module-cache
2023-09-28T07:00:35.0053418Z --- bootstrap: error: Command '['env', 'SWIFTCI_USE_LOCAL_DEPS=1', 'SWIFTPM_MACOS_DEPLOYMENT_TARGET=10.15', 'LD_LIBRARY_PATH=/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/tsc/lib:/tmp/swift-20230928-9967-1785byu/build/llbuild-linux-x86_64/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/yams/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-argument-parser/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-crypto/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-driver/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-system/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-collections/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-asn1/lib:/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/swift-certificates/lib:/home/linuxbrew/.linuxbrew/Cellar/swift/5.9/libexec/lib/swift/linux', 'SWIFT_EXEC=/home/linuxbrew/.linuxbrew/Cellar/swift/5.9/libexec/bin/swiftc', 'SWIFT_DRIVER_SWIFT_EXEC=/home/linuxbrew/.linuxbrew/Cellar/swift/5.9/libexec/bin/swiftc', 'CC=/home/linuxbrew/.linuxbrew/Cellar/swift/5.9/libexec/bin/clang', 'SWIFTPM_CUSTOM_LIBS_DIR=/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/pm', '/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/x86_64-unknown-linux-gnu/bootstrap/bin/swift-bootstrap', '--build-path', '/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64', '--configuration', 'release', '-Xswiftc', '-module-cache-path', '-Xswiftc', '/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/module-cache', '-Xmanifest', '-module-cache-path', '-Xmanifest', '/tmp/swift-20230928-9967-1785byu/build/swiftpm-linux-x86_64/module-cache']' returned non-zero exit status 1.
```

**Pull request closed without merging**
