### PR TITLE
evince 43.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  meson.build:521:6: ERROR: Program 'gtk-update-icon-cache' not found or not executable
```

**Comment by chenrui333** [comment]
> This should depend on `gtk+4` now instead of `gtk+3`.

I guess it requires gtk+3?
`gtk_dep = dependency('gtk+-3.0', version: gtk_req_version)`

**Comment by chenrui333** [comment]
relates to https://github.com/GNOME/evince/commit/48bebe4d17f4e65778a72d7eac85b9961366e51c

**Comment by chenrui333** [comment]
Looks like meson core support issue, related PR, https://github.com/mesonbuild/meson/pull/8272

**Comment by chenrui333** [comment]
Raise a PR of [deprecating gtk2](https://github.com/Homebrew/homebrew-core/pull/111069), for this PR, I think we can disable the cache update.

**Comment by eli-schwartz** [comment]
A better solution is to have the gtk4 recipe build two binary packages:
- gtk4
- gtk-update-icon-cache

And the latter would contain gtk4-update-icon-cache as well as a symlink for gtk-update-icon-cache.

The non-upstream gtk3-update-icon-cache name isn't needed. Neither gtk2 nor gtk3 nor gtk4 binary packages would have an update-icon-cache binary of any description, but they would depend on the "gtk-update-icon-cache" binary package.

There would only ever be one binary, plus one alias, and it would be shared between all 3 packages without conflicting.

**Comment by cho-m** [comment]
What's a bit disappointing is that Meson's `gnome.post_install()` checks for `DESTDIR` at the end while GNOME's post-install scripts would check at the beginning.

Even though none of the commands are going to be run (i.e. `DESTDIR=/`), the build fails on finding the command.

https://mesonbuild.com/Gnome-module.html#gnomepost_install
> If `DESTDIR` is specified during installation all scripts will be skipped.

**Comment by chenrui333** [comment]
continuing with [43.1](https://github.com/Homebrew/homebrew-core/pull/117320)

**Pull request closed without merging**
