### PR TITLE
ssh3 0.1.7 (new formula)

### PR DESCRIPTION
**Pull request by pthariensflame**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Comment by pthariensflame** [comment]
It's odd that audit is failing here when it didn't locally.
Regardless, the `v0.1.4-bsd` tag is the same as the `v0.1.4` release tag plus selected patches that allow the server binary to run under macOS (and also other BSDs).

**Comment by p-linnane** [comment]
The issue is simply that upstream has that release marked as a GitHub pre-release. They will need to address that if we are going to include this.

**Comment by pthariensflame** [comment]
> The issue is simply that upstream has that release marked as a GitHub pre-release. They will need to address that if we are going to include this.

In that case I'll wait until they release the next version and maintain this locally until then.

**Comment by indianets** [comment]
@pthariensflame the tag 'v0.1.4-bsd' is pre-release, but 'v0.1.4' is a release tag, I would request you to update that and push once.

**Comment by pthariensflame** [comment]
> @pthariensflame the tag 'v0.1.4-bsd' is pre-release, but 'v0.1.4' is a release tag, I would request you to update that and push once.

The problem is that `v0.1.4-bsd` has critical fixes for the Mac, so I'd rather wait until `v0.1.5` is properly released rather than having to carry all of the prerelease as patches.

**Comment by indianets** [comment]
> The problem is that `v0.1.4-bsd` has critical fixes for the Mac, so I'd rather wait until `v0.1.5` is properly released rather than having to carry all of the prerelease as patches.

Yes, that's very clear to me and everyone. but as `v0.1.4-bsd` is not production-ready (as it has been marked pre-release by the developer themself), you can't help but add `v0.1.4` and and and enjoy the "SSH3 Client" and when `-bsd` version matures in future, we will automatically have "SSH3 Server".

**Comment by pthariensflame** [comment]
(I just want to make sure the formula still functions with the RC, in preparation for the actual release.)

**Comment by indianets** [comment]
I don't think you understood this comment [#issuecomment-1865314879](https://github.com/Homebrew/homebrew-core/pull/157909#issuecomment-1865314879).

Pre-release formula/version cannot be added.

**Comment by pthariensflame** [comment]
> I don't think you understood this comment [#issuecomment-1865314879](https://github.com/Homebrew/homebrew-core/pull/157909#issuecomment-1865314879).
> 
> Pre-release formula/version cannot be added.

I'm well aware; I'm using the prerelease to test so this formula can be ready when the release actually happens.  I don't intend this to be merged until then.

**Comment by indianets** [comment]
Sorry, I understand your intention now.

> I don't intend this to be merged until then.

Could you please explain what could be wrong in pushing stable version `v0.1.4` which will bumped to the stable `v0.1.5` when that releases?

**Comment by pthariensflame** [comment]
> Could you please explain what could be wrong in pushing stable version `v0.1.4` which will bumped to the stable `v0.1.5` when that releases?

There would be nothing *wrong*, but also nothing particularly *useful*, at least to me.  I would like the formula for its server component, so merging v0.1.4 initially would be more work for basically no gain.

**Comment by indianets** [comment]
Well, the stable version does provide working SSH3 client on macOS, and I am using that to test on my machine. I understand you are more interested in Server binary which lacks in that release.

I think stable version is still usable and useful for community, may not be as useful to you.

**Comment by pthariensflame** [comment]
> Well, the stable version does provide working SSH3 client on macOS, and I am using that to test on my machine. I understand you are more interested in Server binary which lacks in that release.
> 
> I think stable version is still usable and useful for community, may not be as useful to you.

That's a fair argument!

I think if v0.1.5 releases in the next few days, I'll stick with my plan, but if not I'll revert to yours in order to get at least something there.

**Comment by indianets** [comment]
@pthariensflame you should check and update ssh3 to 0.1.7 as two stable versions have been released since. If you are not interested, I can push the latest version in a new PR referring this.

**Comment by pthariensflame** [comment]
@indianets Thank you!  I'm so sorry for forgetting about this!
I'll update the PR.

**Comment by pthariensflame** [comment]
@p-linnane The original issue has disappeared; is this formula ready for inclusion?

**Comment by pthariensflame** [comment]
Seems ready now!

**Comment by pthariensflame** [comment]
Any news on this?

**Comment by p-linnane** [comment]
> Any news on this?

Sorry for the delay. Rebased and rerunning now that we've merged Go 1.22.0.

**Review by p-linnane — APPROVED** [review]
Looks good to me. Would like one more maintainer to weigh in before we merge.

**Pull request merged**
