### PR TITLE
gopass-jsonapi: sha256 update

### PR DESCRIPTION
**Pull request by arpagon**
update sha256sums from https://github.com/gopasspw/gopass-jsonapi/releases/download/v1.15.2/gopass-jsonapi_1.15.2_SHA256SUMS

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Why did they change?

**Comment by arpagon** [comment]
I simply saw that there is a mismatch with the sha256sums reported by the developer.

https://github.com/gopasspw/gopass-jsonapi/releases/download/v1.15.2/gopass-jsonapi_1.15.2_SHA256SUMS

**Comment by SMillerDev** [comment]
But the were wouldn't have merged the shasum if it was wrong so that means it was updated in place. Could you ask upstream why? Because that could be a sign their downloads were compromised.

**Comment by arpagon** [comment]
> But the were wouldn't have merged the shasum if it was wrong so that means it was updated in place. Could you ask upstream why? Because that could be a sign their downloads were compromised.

https://github.com/gopasspw/gopass-jsonapi/issues/98

**Comment by arpagon** [comment]
Fixexd in version https://github.com/gopasspw/gopass-jsonapi/releases/tag/v1.15.3

**Pull request closed without merging**
