### PR TITLE
fortio 1.16.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ldemailly** [comment]
going to make 1.17.0 if you don't mind where fewer files are needed thanks to golang 1.16 embed support

**Comment by ldemailly** [comment]
if you don't mind closing this one in favor of https://github.com/Homebrew/homebrew-core/pull/79826/files

**Comment by ldemailly** [comment]
Also note that 1.16.1 was exactly like 1.16.0 except on windows (ie not relevant change for brew)
See #79826 for updates

**Comment by cho-m** [comment]
Closing as superceded by #79826

**Pull request closed without merging**
