### PR TITLE
kibana 5.6.0

### PR DESCRIPTION
**Pull request by jasontedor**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Lines 29–38 should be replaced by:

```
     # do not build packages for other platforms
     inreplace buildpath/"tasks/config/platforms.js", /('(linux-x64|windows-x64)',?(?!;))/, "// \\1"
```

Then line 31 becomes:

```
mkdir_p buildpath/".node_binaries/#{resource("node").version}/darwin-x64"
```

and line 48 becomes:

```
     prefix.install Dir["build/kibana-#{version}-darwin-x86_64/{bin,config,node_modules,optimize,package.json,src,ui_framework,webpackShims}"]
```

**Comment by jasontedor** [comment]
@fxcoudert I am happy to look into making that change, but does it need to be done in a version bump PR?

**Comment by ilovezfs** [comment]
I don't think I understand why any of those changes would need to be made, and no they do not need to be made in a version bump PR.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks @jasontedor! Shipped :rocket:

**Comment by jasontedor** [comment]
Thanks @ilovezfs!

**Comment by ilovezfs** [comment]
@jasontedor you're welcome! FYI, @fxcoudert made the tweaks he was describing above here: https://github.com/Homebrew/homebrew-core/pull/17976

**Pull request closed without merging**
