### PR TITLE
libfabric 1.4.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jsquyres** [comment]
I can't tell why the CI test failed on El Cap...?  Is this a libfabric failure, or a brew infrastructure failure, or ...?

**Comment by ilovezfs** [comment]
@jsquyres it's a libfabric failure, specifically a problem when using the Xcode 8 SDK on El Capitan caused by the weak symbol clock_gettime, which is defined in the time.h header but not actually available at run time unless you're on Sierra.

**Comment by jsquyres** [comment]
Can you point me to the specific failure?  I'm able to build libfabric 1.4 on my El Cap-based (10.11.6) laptop with Xcode 8.1 (8B62), and run its executables.

**Comment by ilovezfs** [comment]
You're probably building against the Xcode 7 Command Line Tools, not Xcode 8. The full log is here: https://bot.brew.sh/job/Homebrew%20Core/10613/version=el_capitan/consoleText

If you make sure `xcode-select -p` is pointing at `/Applications/Xcode.app/Contents/Developer` and you set `SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk` you should be able to reproduce it outside of Homebrew.

If not, `brew install -dvs libfrabic` and you can enter the shell by choosing option 5 when it goes :boom:

**Comment by jsquyres** [comment]
Forgive me, on multiple levels...

1. Yes, `xcode-select -p` is pointing at `/Applications/Xcode.app/Contents/Developer`.  
1. I exported `SDKROOT` to the value you specified, but I apparently only had one meaningful subdir in there, anyway.
1. I did the build again (from a vanilla libfabric 1.4.0 tarball), and it still worked fine.  [Here's a gist showing the full output](https://gist.github.com/jsquyres/0e4dbce2a32e3c1e59f9c58eb264c44b).

So I installed Homebrew (gasp!) and then tried `brew install -dvs libfabric`  It downloads and builds libfabric 1.3.0 -- not 1.4.0.  So I can't see if the fix in v1.4.0 made a difference (via homebrew, anyway).

**Comment by ilovezfs** [comment]
```
brew pull 6551
```

Then you can test 1.4.0

**Comment by jsquyres** [comment]
Perfect; that got it.

I see off the bat that when I run configure/make myself, it uses gcc.  But when homebrew runs configure/make, it uses clang.  I'll dig into this...

**Comment by ilovezfs** [comment]
@jsquyres thanks. You may also want to peruse our collection of these and the various workarounds: https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+is%3Aclosed+label%3Aclock_gettime

Also, you may find the logs in ~/Library/Logs/Homebrew/libfabric useful since you can see what command was handed to our so-called "superenv" shims, and then what command was actually executed.

**Comment by jsquyres** [comment]
After a bunch of builds, I figured out the difference.  Recall:

1. When I build libfabric outside of Homebrew, it compiles and runs fine.
1. When Homebrew builds libfabric, it fails to compile.
1. I'm on an El Cap-based (10.11.6) laptop with Xcode 8.1 (8B62).

The difference is in the environment that Homebrew is using to build libfabric.  If I add these two environment variables to my environment, I can replicate the error that Homebrew encounters (i.e., that libfabric fails to build):

```
export 'SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk'
export 'ac_cv_search_clock_gettime=no'
```

Specifically: Homebrew is setting these env variables before it invokes libfabric's configure script.  If I set either one of these without the other, libfabric still builds/works fine.  It is the combination of *both* of these env variables that causes the problem.

I'll have to admit ignorance here of why the SDKROOT variable matters -- to my unknowning eye, I only have one SDK installed:

```
$ ls -l /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
total 8
drwxr-xr-x  5 root  wheel  170 Jan 27  2019 MacOSX.sdk/
lrwxr-xr-x  1 root  wheel   10 Oct 29 10:23 MacOSX10.12.sdk@ -> MacOSX.sdk
```

That being said, I think if you update your libfabric formula to *not* set `ac_cv_search_clock_gettime` and instead let libfabric's configure figure it out, then the Right Things will happen.

**Comment by ilovezfs** [comment]
@jsquyres you're saying a cached value of ac_cv_search_clock_gettime=no causes your configure to choose to use clock_gettime? How can that possibly be correct?

**Comment by jsquyres** [comment]
@ilovezfs Libfabric provides its own `clock_gettime` on platforms that don't have it; that was our workaround to the portability issue.  It means we don't have to do things like this in our code base:

```c
#if HAVE_CLOCK_GETTIME
    clock_gettime(...);
#else
    something_else(...);
#endif
```

**Comment by ilovezfs** [comment]
OK, but what does that have to do with the standard `ac_cv_search_clock_gettime` check returning "no"?

**Comment by jsquyres** [comment]
The problem appears to be that MacOSX10.12.sdk *does* contain `clock_gettime`, even on OS X 10.11.6.  Hence, when you force the use of MacOSX10.12.sdk *and* you force the (incorrect) answer of `no` in `ac_cv_search_clock_gettime`, things go badly -- as they should.

Here's a trivial test that shows this:

```sh
# My simple configure script for this test
$ cat configure.ac
AC_INIT([bogus], [0.1], [bogus@example.com])

have_clock_gettime=no
AC_SEARCH_LIBS([clock_gettime],[rt],
		[have_clock_gettime=yes],
		[have_clock_gettime=nonono])
```
```sh
# My simple test script
$ cat run
#!/bin/sh

autoconf

export SDKROOT=
echo "======= WITH DEFAULT SDK (SDKROOT is unset)"
echo "======= SDKROOT=$SDKROOT"
./configure

export 'SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk'
echo "======= WITH 10.12 SDK"
echo "======= SDKROOT=$SDKROOT"
./configure
```

Ok, let's now run this script on my OS X 10.11.x El Cap machine with Xcode 8.1 (8B62):

```sh
$ ./run
======= WITH DEFAULT SDK (SDKROOT is unset)
======= SDKROOT=
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for library containing clock_gettime... no
======= WITH 10.12 SDK
======= SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for library containing clock_gettime... none required
```

Notice the "none required" output -- meaning that `clock_gettime` was found.

**Comment by jsquyres** [comment]
@bturrubiates and I were looking closer at this, and he found https://github.com/Homebrew/brew/commit/1d7aa1fe0.

Is this perhaps a difference between Xcode 8.0 and 8.1?  I ask because if I build libfabric out of the box, calls to `clock_gettime()` seem to be working fine...?

**Comment by ilovezfs** [comment]
10.11 does not have clock_gettime. It's only defined in the Xcode 8/8.1 time.h header and in the libsystem_c.tbd file as a weak symbol.

**Comment by jsquyres** [comment]
Ok, I see the issue now: MacOS can be **evil** with regards to `clock_gettime(3)`.  Sigh.

I opened a PR with what I hope is the fix: https://github.com/ofiwg/libfabric/pull/2508

If this is the fix, can you pull this patch into your brew recipe?  Or do we need to do a v1.4.1 release?  (I'm a little hesitant to do a 1.4.1 release just for this issue...)

**Comment by ilovezfs** [comment]
@jsquyres LOL. You aren't alone in that sentiment. Erlang upstream had a similar reaction: https://bugs.erlang.org/browse/ERL-256?focusedCommentId=11634&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-11634

Adding the patch is no problem. No need for you to do a new release until you're ready.

**Comment by jsquyres** [comment]
Thanks @ilovezfs.  Let's see how my PR shakes out.

**Comment by ilovezfs** [comment]
OK, here's what I'm seeing with the patch in place: https://gist.githubusercontent.com/ilovezfs/23938f7c49efa89aec7323040dfa48e3/raw/68f8f29cf7d1ae732a54ed2dc6b6ac0d284bdaec/gistfile1.txt

**Comment by jsquyres** [comment]
Blech!  After all that, I forgot to test the SDKROOT+ac_cv_search_clock_gettime combination.  PR updated with what I think is the fix.

**Comment by ilovezfs** [comment]
@jsquyres this looks like it works. However, I think you may want to use a different name for your fallback implementation. If you attempt to link libfabric with `-Wl,-no_weak_imports` and `export MACOSX_DEPLOYMENT_TARGET=10.11` or pass `-mmacosx-version-min=10.11`, then it will fail with
```
ld: weak import of symbol '_clock_gettime' not supported because of option: -no_weak_imports for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
since that symbol name is not permitted on 10.11 with `-no_weak_imports` even if you've provided a custom implementation. Since Apple is recommending people use `-no_weak_imports` when possible, that is likely to become a problem for you given that you're using the colliding symbol name.

This has already caused problems elsewhere where software has provided a custom implementation and called it "clock_gettime"

**Comment by jsquyres** [comment]
Yoinks. Ok.

**Comment by jsquyres** [comment]
@ilovezfs It took forever, but I think we finally got the right fix committed upstream: https://github.com/ofiwg/libfabric/pull/2508

**Comment by ilovezfs** [comment]
@jsquyres nice work! Let's give it a try

**Comment by ilovezfs** [comment]
@jsquyres it worked for me locally and now CI :green_apple:. As you can see, I've modified the formula to build 16326406506adf8b3f8b30d802453064395d3341 as 1.4.1-alpha1 so that it could go through CI, but it would be great if you could create a new version (preferably a release tarball but just a new tag would work too if we throw in the Autotools dependencies, as I've done here).

**Comment by jsquyres** [comment]
I don't know if we're ready to do a 1.4.1 release, or if we'll do one just for this fix.

Would it be possible to download the 1.4.0 tarball, but then apply a patch file corresponding to ofiwg/libfabric@0b0c889?

**Comment by ilovezfs** [comment]
@jsquyres shipped! My apologies for the delay.

**Pull request closed without merging**
