### PR TITLE
edencommon fb303 fbthrift fizz folly mvfst wangle watchman 2023.11.13.00

### PR DESCRIPTION
**Pull request by razvanazamfirei**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@razvanazamfirei can you split the commits out?

**Comment by chenrui333** [comment]
@razvanazamfirei can you split the commits out?

**Comment by razvanazamfirei** [comment]
@chenrui333, sure!

**Review by chenrui333 — APPROVED** [review]
Thanks!

**Pull request merged**
