### PR TITLE
sync_gateway: use `Utils.git_head`

### PR DESCRIPTION
**Pull request by SeekingMeaning**
See https://github.com/Homebrew/homebrew-core/issues/68805

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
```
Error: 2.8.0 tag should be 61ca30a14f10edf40a26f7b2189c962c16a04b8a
but is actually e2e7d4286f84e3d101e2ea0d9ee868c66e6243f1
```

**Comment by bbrks** [comment]
> ```
> Error: 2.8.0 tag should be 61ca30a14f10edf40a26f7b2189c962c16a04b8a
> but is actually e2e7d4286f84e3d101e2ea0d9ee868c66e6243f1
> ```
> 
> [forums.couchbase.com/t/git-tag-commit-changed/29118](https://forums.couchbase.com/t/git-tag-commit-changed/29118)

Oops, sorry! I replied in the forum, but it was an intentional change:

> Hi!
>
>Apologies for the disruption, this change was intentional to fix an incorrect commit for the 2.8.0 tag
>
>The old sha was accidentally behind by a few commits, so I recently moved the tag forwards to match the binaries that we shipped as 2.8.0
>
>Thanks,
>Ben

**Comment by fxcoudert** [comment]
@SeekingMeaning I don't know how you triggered that merge, but if you use `brew pr-publish` please pass `--autosquash`… otherwise this leads to multiple commits not being squashed, as in this case:

```
commit b0ceb70942db6a3b347a959e158e0dd8c7d9ebf8
Author: Seeker <meaningseeking@protonmail.com>
Date:   2021-01-18 11:15:47 -0800

    sync_gateway: bump revision
    
    Closes #69226.
    
    Signed-off-by: Seeker <meaningseeking@protonmail.com>

commit 532d2cfc403ad1e928ffab86264c381af3b95bbc
Author: Seeker <meaningseeking@protonmail.com>
Date:   2021-01-18 11:14:29 -0800

    sync_gateway: update git revision

commit 1db002f16cf5370147bb704b2116e354c3eabdc7
Author: Seeker <meaningseeking@protonmail.com>
Date:   2021-01-16 19:58:13 -0800

    sync_gateway: use `Utils.git_head`
```

**Comment by SeekingMeaning** [comment]
Yikes, my bad! I used the workflow dispatch to trigger the merge; I should have passed in `--autosquash` in the Additional arguments field

**Pull request closed without merging**
