### PR TITLE
mesos 1.11.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
/usr/local/Cellar/openjdk@8/1.8.0+275/libexec/openjdk.jdk/Contents/Home/jre
configure: using JAVA_HOME=/usr/local/Cellar/openjdk@8/1.8.0+275/libexec/openjdk.jdk/Contents/Home
checking whether or not we can build with JNI... ld: framework not found JavaVM
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ld: framework not found JavaVM
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure: error: failed to build with JNI
  -------------------------------------------------------------------
  It appears we were unable to compile against the JNI. This is most
  likely due to one of the following issues:
    1. You do not have a JDK installed on your system.
    2. All JDKs installed on your system have deprecated JNI headers.
  It is advised to install OpenJDK on your system, as the JDK that
  ships with OS X has deprecated JNI headers.
  -------------------------------------------------------------------
```

**Comment by bayandin** [comment]
> ```
> Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache
> /usr/local/Cellar/openjdk@8/1.8.0+275/libexec/openjdk.jdk/Contents/Home/jre
> configure: using JAVA_HOME=/usr/local/Cellar/openjdk@8/1.8.0+275/libexec/openjdk.jdk/Contents/Home
> checking whether or not we can build with JNI... ld: framework not found JavaVM
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ld: framework not found JavaVM
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> configure: error: failed to build with JNI
>   -------------------------------------------------------------------
>   It appears we were unable to compile against the JNI. This is most
>   likely due to one of the following issues:
>     1. You do not have a JDK installed on your system.
>     2. All JDKs installed on your system have deprecated JNI headers.
>   It is advised to install OpenJDK on your system, as the JDK that
>   ships with OS X has deprecated JNI headers.
>   -------------------------------------------------------------------
> ```

It looks like we need to enable this `openjdk@8` workaround for Big Sur as well (haven't tested it yet):
https://github.com/Homebrew/homebrew-core/blob/12a24e934538f74f874114c0b57570f165d2f565/Formula/openjdk@8.rb#L78-L86

@jonchang is there any particular reason why it was limited to pre Big Sur versions?

**Comment by jonchang** [comment]
Only just saw this but from what I recall it was because the 11.c SDK doesn't have those files. Or maybe I had tested it locally and couldn't get it to work (it's been a while so I don't recall the exact details)

**Comment by jonchang** [comment]
Let's see if u282 magically fixed this build...

**Pull request closed without merging**
