### PR TITLE
folly 0.57.0

### PR DESCRIPTION
**Pull request by ashwanthkumar**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install folly`
- [x] Does your submission pass `brew audit --strict --online folly` (after doing `brew install folly`)?

---

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Failing to build on 10.9: http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1914/version=mavericks/testReport/junit/brew-test-bot/mavericks/install_folly/

**Comment by ashwanthkumar** [comment]
I've built this on Mavericks but using gcc-4.9 and not using the default clang. Is it fair to drop support for mavericks?

**Comment by mikemcquaid** [comment]
That points towards needing a `fails_with :clang` for the Mavericks build number you can get from http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1914/version=mavericks/testReport/brew-test-bot/mavericks/config/

**Comment by ashwanthkumar** [comment]
Updated the formula. Folly has very loose support for GCC5 so dropped support for GCC5 as well. From the build I saw that it didn't build for Mavericks at all, Is there a way to notify users to use gcc version < 5?

**Comment by mikemcquaid** [comment]
I think it's fine as is, thanks.

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
