### PR TITLE
commandbox 3.6.0

### PR DESCRIPTION
**Pull request by bdw429s**
updated hashes

### CODE REVIEW

**Comment by bdw429s** [comment]
@neutric This is the same release I sent earlier today, but I needed to update the binaries on S3, so sending over an update with the new sha hashes.  Thanks!

**Comment by fxcoudert** [comment]
Thanks @bdw429s for your contribution!

**Comment by neutric** [comment]
Thanks also for providing context for the hash change. :D

**Comment by ilovezfs** [comment]
In the future: please bump the version rather than just changing the checksums. As it is, people who have already downloaded the file are going to be getting checksum mismatch errors now.

>but I needed to update the binaries on S3

Why? This is still an unexplained change.

**Comment by bdw429s** [comment]
@ilovezfs @nijikon I realize updating a binary is not desired.  Our build process had placed the wrong binary on S3.  I realized it right away but the original pull was merged so fast I didn't get a chance to update it ( https://github.com/Homebrew/homebrew-core/pull/10836 ).  All of the release material and documentation for the 3.6.0 release had been written so it was not a trivial change to bump the version. 

Please note, the first homebrew version had literally only been merged a couples hours prior and in the middle of the night so I would be surprised if anyone at all had downloaded it.  Had the old binary been there for weeks, I wouldn't have done this.

**Comment by ilovezfs** [comment]
OK, thanks. Typically, uploading a duplicate named https://downloads.ortussolutions.com/ortussolutions/commandbox/3.6.0/commandbox-bin-3.6.0.1.zip would be the way to go in that case.

>in the middle of the night 

:night_with_stars: 

We have users all over the world ;)

**Pull request merged**
