### PR TITLE
git-town 2.1.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by charlierudolph** [comment]
Thanks @ilovezfs. I was just about to do this. Out of curiosity, how did you know git town made a new release?

**Comment by ilovezfs** [comment]
By diffing the output of a complete `brew livecheck` run against the prior run.

```
Josephs-MacBook-Pro:lc joe$ new
> git-town
> icu4c
> unshield
Josephs-MacBook-Pro:lc joe$ diff 532.txt 533.txt |grep git-town
< git-town (guessed) : 2.0.0 ==> 2.0.0
> git-town (guessed) : 2.0.0 ==> 2.1.0
```

**Comment by charlierudolph** [comment]
Woah very cool. Is the `bump-formula-pr` command going to be exposed in the future?

**Comment by ilovezfs** [comment]
@charlierudolph it'a already exposed in the `dev-cmd` folder. If you `export HOMEBREW_DEVELOPER=1` it will be available to you.

**Comment by MikeMcQuaid** [comment]
> If you export HOMEBREW_DEVELOPER=1 it will be available to you.

That's no longer necessary. You can just run it. `man brew` lists it, too.

**Pull request closed without merging**
