### PR TITLE
earthly: improve shell completion

### PR DESCRIPTION
**Pull request by alexcb**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alexcb** [comment]
@SMillerDev here's the change you requested in https://github.com/Homebrew/homebrew-core/pull/61331 hope this does the trick.
Thanks.

**Comment by SMillerDev** [comment]
Can you make sure the commit has the same name as the pull request? It'll get confusing if a lot of commits claim to be updating to the same version.

**Comment by alexcb** [comment]
I renamed the commit to `earthly: improve shell completion` (which matches this renamed PR now).

**Review by SMillerDev — DISMISSED** [review]
Thanks @alexcb  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by alexcb** [comment]
We have a new version that we released today, so we can move these changes into that PR: https://github.com/Homebrew/homebrew-core/pull/61839/files

**Pull request closed without merging**
