### PR TITLE
mvnvm: undeprecate

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

relates to:
- #134216
- #134124

### CODE REVIEW

**Review by p-linnane — APPROVED** [review]
Weird. I kept an eye on it for a few days. Figures it would come back the day after finally opening the deprecation PR 🤦‍♂️

**Comment by chenrui333** [comment]
> Weird. I kept an eye on it for a few days. Figures it would come back the day after finally opening the deprecation PR 🤦‍♂️

not just this formula, but some others as well. no worries.

**Comment by chenrui333** [comment]
I think the homepage might some issue, I am gonna raise into the upstream.

**Comment by chenrui333** [comment]
raises an issue about the homepage access, https://bitbucket.org/mjensen/mvnvm/issues/40/mvnvmorg-site-seems-not-accessible

**Pull request merged**
