### PR TITLE
ansible 2.2.1.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by woodruffw** [comment]
Classic:

```
ansible:
  * The homepage https://www.ansible.com/ is not reachable (HTTP status code 403)
```

**Comment by woodruffw** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
This is known: https://github.com/Homebrew/homebrew-core/issues/8847#issuecomment-272668388

**Comment by woodruffw** [comment]
Weird, I wonder if they're doing some nasty `User-Agent` checking to exclude bots...

**Comment by steve-eaccent** [comment]
`brew audit --online ansible` fails even with the existing ansible package `2.2.0`, so it seems like that's a separate issue. 2.2.1 fixes a major security vulnerability, so it'd be nice to get this release to the public. Is it worth blocking this PR?

**Comment by ilovezfs** [comment]
That has nothing to do with reason it's blocked.

> fixes a major security vulnerability

Thanks for the heads up. I'll prioritize this accordingly.

**Comment by ilovezfs** [comment]
@steve-eaccent PR refreshed with the needed changes.

**Comment by JCount** [comment]
Not supposed to have pushed that commit.

**Comment by JCount** [comment]
now it is done.

**Pull request closed without merging**
