### PR TITLE
cmatrix 2.0

### PR DESCRIPTION
**Pull request by evilr00t**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by evilr00t** [comment]
I guess it would be useful to bump the version as some people were asking ow to get recent version on MacOS https://github.com/abishekvashok/cmatrix/issues/88

**Comment by chenrui333** [comment]
Can you update the commit message format as `cmatrix 2.0`? Thanks!

**Comment by evilr00t** [comment]
@chenrui333 that's done now. 👍

**Comment by fxcoudert** [comment]
Thanks @evilr00t for your contribution to Homebrew!

**Pull request closed without merging**
