### PR TITLE
Added libtorrent rtorrent formulas

### PR DESCRIPTION
**Pull request by zawapete**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by zawapete** [comment]
I found at https://github.com/Homebrew/homebrew-science/issues/6394 how to fix the `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
using ::signbit;` issue. It seem it solved on mojave but not on high sierra. any hint?

**Comment by mistydemeo** [comment]
For context, this was removed two years ago because we couldn't get it to build: https://github.com/Homebrew/homebrew-core/issues/157 Looks like the situation is a little better now!

**Comment by zawapete** [comment]
@mistydemeo indeed. Also the problem to build seems to appear only on high sierra on homebrew environment. with standard build process I'm able to build on the same os

**Comment by zawapete** [comment]
@fxcoudert do you know how to fix the issue on high sierra? the prolem happens only when building through homebrew environment

**Comment by zawapete** [comment]
bump

**Comment by SMillerDev** [comment]
@brewtestbot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
