### PR TITLE
workflows/tests: enable ephemeral 12-arm64.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
I vaguely recall @Bo98 saying this should just work so: let's try it.

### CODE REVIEW

**Review by Bo98 — APPROVED** [review]
Fine with me.

Note that any tests using OpenCL will break, but I've communicated that a couple times before so hopefully people are ready by now.

**Comment by carlocab** [comment]
Is this going to change our runner capacity?

**Comment by Bo98** [comment]
Non-ephemeral is currently 3x 11-arm64 and 3x 12-arm64.

Ephemeral is 6 slots shared between 12-arm64 and 13-arm64. So 13-arm64 capacity will reduce as a result.

**Comment by MikeMcQuaid** [comment]
> I take it there's no way to use the bare metal 12-arm64 machines to add capacity to our ephemeral queue?

Correct 😭

**Pull request merged**
