### PR TITLE
percona-server 5.7.20-19

### PR DESCRIPTION
**Pull request by raymondelooff**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by raymondelooff** [comment]
This build will fail due to an error in the new version of Percona Server. Issue reported: https://bugs.launchpad.net/percona-server/+bug/1741647

**Comment by ilovezfs** [comment]
did you try commenting it out?

**Comment by raymondelooff** [comment]
I've tried commenting it out, but that doesn't solve the issue because the same statement is used in multiple files. I've updated the description of the reported bug.

**Comment by ilovezfs** [comment]
```
diff --git a/include/my_sys.h b/include/my_sys.h
index dffe40b..18c7a08 100644
--- a/include/my_sys.h
+++ b/include/my_sys.h
@@ -578,9 +578,6 @@ extern size_t my_fwrite(FILE *stream,const uchar *Buffer,size_t Count,
 		      myf MyFlags);
 extern my_off_t my_fseek(FILE *stream,my_off_t pos,int whence,myf MyFlags);
 extern my_off_t my_ftell(FILE *stream,myf MyFlags);
-#if !defined(HAVE_MEMSET_S)
-void memset_s(void *dest, size_t dest_max, int c, size_t n);
-#endif
 
 /* implemented in my_syslog.c */
 
diff --git a/mysys/my_malloc.c b/mysys/my_malloc.c
index b64c2ce..d95cf7a 100644
--- a/mysys/my_malloc.c
+++ b/mysys/my_malloc.c
@@ -323,17 +323,4 @@ char *my_strndup(PSI_memory_key key, const char *from, size_t length, myf my_fla
   return ptr;
 }
 
-#if !defined(HAVE_MEMSET_S)
-void memset_s(void *dest, size_t dest_max, int c, size_t n)
-{
-#if defined(WIN32)
-  SecureZeroMemory(dest, n);
-#else
-  volatile unsigned char *p = (unsigned char*)(dest);
-  while (dest_max-- && n--) {
-    *p++ = c;
-  }
-#endif
-} 
-#endif
 
```
works. so question is why that definition isn't passed along by cmake

**Comment by ilovezfs** [comment]
```
ENV.prepend "CPPFLAGS", "-DHAVE_MEMSET_S=1"
```
fixes it for now.

**Comment by raymondelooff** [comment]
Nice! I've added the temporary fix.

**Comment by ilovezfs** [comment]
Thanks again @raymondelooff! :sparkle:

**Pull request closed without merging**
