### PR TITLE
kind: fix test, use `main` branch for `--HEAD`

### PR DESCRIPTION
**Pull request by shuuji3**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Currently, `kind` package cannot be installed using `--HEAD`. This is because the branch name was renamed from `master` to `main`. Also, `brew test kind` was failed.

This PR fixes the above two issues by appending `main` branch name and fixing the test assertion message.

### Install with `--HEAD`

```shell
❯ brew install --head kind
Updating Homebrew...
==> Cloning https://github.com/kubernetes-sigs/kind.git
Updating /Users/shuuji3/Library/Caches/Homebrew/kind--git
fatal: couldn't find remote ref refs/heads/master
Error: Failed to download resource "kind"
Failure while executing; `git fetch origin` exited with 128. Here's the output:
fatal: couldn't find remote ref refs/heads/master
```

### Test

```shell
❯ brew test kind
==> Testing kind
==> /opt/homebrew/Cellar/kind/0.10.0/bin/kind get kubeconfig --name homebrew 2>&1
Error: kind: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /failed\ to\ list\ clusters/ to match "ERROR: could not locate any control plane nodes\n".
/opt/homebrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.14.4/lib/minitest/assertions.rb:183:in `assert'
/opt/homebrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.14.4/lib/minitest/assertions.rb:295:in `assert_match'
/opt/homebrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kind.rb:38:in `block in <class:Kind>'
/opt/homebrew/Homebrew/Library/Homebrew/formula.rb:1975:in `block (3 levels) in run_test'
/opt/homebrew/Homebrew/Library/Homebrew/utils.rb:558:in `with_env'
/opt/homebrew/Homebrew/Library/Homebrew/formula.rb:1974:in `block (2 levels) in run_test'
/opt/homebrew/Homebrew/Library/Homebrew/formula.rb:924:in `with_logging'
/opt/homebrew/Homebrew/Library/Homebrew/formula.rb:1973:in `block in run_test'
/opt/homebrew/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/opt/homebrew/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/opt/homebrew/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/opt/homebrew/Homebrew/Library/Homebrew/formula.rb:2224:in `mktemp'
/opt/homebrew/Homebrew/Library/Homebrew/formula.rb:1967:in `run_test'
/opt/homebrew/Homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Homebrew/Library/Homebrew/test.rb:48:in `<main>'
```

## Confirmation after the change

I did test for two patterns: `brew install kind --build-from-source` and `brew install kind --HEAD`.

```shell
❯ brew uninstall --force kind; brew install --build-from-source kind; brew test kind; brew audit --strict kind; brew style kind
Uninstalling kind... (8 files, 8.3MB)
Updating Homebrew...
==> Downloading https://github.com/kubernetes-sigs/kind/archive/v0.10.0.tar.gz
Already downloaded: /Users/shuuji3/Library/Caches/Homebrew/downloads/bd92f5dd9abc22fe37f64ae666690a665493935fa4c6689ec7feef5e9141d5d4--kind-0.10.0.tar.gz
==> go build -o /opt/homebrew/Cellar/kind/0.10.0/bin/kind
==> Caveats
fish completions have been installed to:
  /opt/homebrew/share/fish/vendor_completions.d
==> Summary
🍺  /opt/homebrew/Cellar/kind/0.10.0: 8 files, 8.3MB, built in 13 seconds
==> Testing kind
==> /opt/homebrew/Cellar/kind/0.10.0/bin/kind get kubeconfig --name homebrew 2>&1

1 file inspected, no offenses detected
```

```shell
❯ brew uninstall --force kind; brew install --HEAD kind; brew test kind; brew audit --strict kind; brew style kind
Uninstalling kind... (8 files, 8.3MB)
Updating Homebrew...
==> Cloning https://github.com/kubernetes-sigs/kind.git
Updating /Users/shuuji3/Library/Caches/Homebrew/kind--git
==> Checking out branch main
Already on 'main'
Your branch is up to date with 'origin/main'.
HEAD is now at 247fea5a Merge pull request #2176 from BenTheElder/new-node-image
==> go build -o /opt/homebrew/Cellar/kind/HEAD-247fea5/bin/kind
==> Caveats
fish completions have been installed to:
  /opt/homebrew/share/fish/vendor_completions.d
==> Summary
🍺  /opt/homebrew/Cellar/kind/HEAD-247fea5: 8 files, 8.3MB, built in 14 seconds
Removing: /Users/shuuji3/Library/Caches/Homebrew/kind--0.10.0.tar.gz... (1.8MB)
==> Testing kind
==> /opt/homebrew/Cellar/kind/HEAD-247fea5/bin/kind get kubeconfig --name homebrew 2>&1

1 file inspected, no offenses detected
```

### CODE REVIEW

**Comment by shuuji3** [comment]
Thanks for fixing the typo, @nandahkrishna!

It looks like that the test was failed because `docker` was not installed in the CI environment:
https://github.com/Homebrew/homebrew-core/pull/77346/checks?check_run_id=2590293041#step:7:60

How can we handle a case like this? In my environment, I installed Docker for arm64 macOS and the test was passed. The following is the version of Docker on my end:

```shell
❯ docker version
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:13 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by nandahkrishna** [comment]
Does `kind` require `docker` to work? Then I think it should have a `depends_on "docker"`. That wasn't present when this formula was added to homebrew-core, and wasn't updated afterwards either.

**Comment by shuuji3** [comment]
Thanks for the suggestion. Yes, `kind` requires the `docker` command but people install `docker` in various ways, and perhaps many of them use the Docker Desktop GUI application to install `docker`. 

There is a Homebrew cask for docker but I don't think depending on cask is a good idea because some users install docker in another way and `kind` is intended to be lightweight single go binary. The install documentation is here: https://kind.sigs.k8s.io/docs/user/quick-start/#installation and it intends `brew install kind` as an equivalent of `curl <kind binary file>`.

**Comment by shuuji3** [comment]
OK, I found the `ko` formula. This tool is similar one as `kind`. `ko` is also written in Golang and provided as a single binary command using `docker`.

This formula (https://github.com/Homebrew/homebrew-core/blob/485d1c3c9ef597d9931069d533716b0f2dc7b438/Formula/ko.rb#L16) depending `docker` only for the build dependencies. It should work well for the `kind` formula.

**Comment by nandahkrishna** [comment]
Makes sense, I'd forgotten about https://github.com/Homebrew/homebrew-core/pull/31582. Using it for the test alone should be okay.

**Review by nandahkrishna — COMMENTED** [review]
Similar to `localstack`, this should work instead:
```ruby
test do
  ENV["DOCKER_HOST"] = "unix://#{testpath}/invalid.sock"

  # Should error out as creating a kind cluster requires root
  status_output = shell_output("#{bin}/kind get kubeconfig --name homebrew 2>&1", 1)
  assert_match "Cannot connect to the Docker daemon", status_output
end
```

**Comment by shuuji3** [comment]
Thanks, I didn't know #31582. I uninstalled Docker on the local machine and test it. The test should pass now.

**Comment by nandahkrishna** [comment]
Thanks @shuuji3!

**Comment by shuuji3** [comment]
@nandahkrishna Thanks for helping to resolve the issue! 😃

**Pull request merged**
