### PR TITLE
signal-cli 0.8.5

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
If CI succeeds we should try building with Homebrew `rust` to see if we can get ARM support with this.

**Comment by cho-m** [comment]
> Homebrew `rust` to see if we can get ARM support with this.

I think upstream still uses features that require a nightly toolchain.

It may still be worth trying to force ARM as some required nightly versions have been updated to newer `nightly-2021-06-08`, e.g. https://github.com/signalapp/zkgroup/blob/v0.7.3/rust-toolchain

**Review by carlocab — APPROVED** [review]
ARM still failed, but that's fine. Let's skip re-running this, as I think the test is just flaky for some reason.

**Comment by neomsg-git** [comment]
The `rust-toolchain` file of zkgroup needs to contain `nightly`. Then `make libzkgroup` has to be called. This will fix it for M1 systems. While zkgroup already [addressed this issue](https://github.com/signalapp/zkgroup/issues/17), signal-cli still uses an older version of it. [Until the maintainer of signal-cli decides to update this dependency](https://github.com/AsamK/signal-cli/issues/719), we will have to use this workaround.

**Pull request closed without merging**
