### PR TITLE
lanraragi 0.7.8

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by carlocab** [comment]
```
! Installing the dependencies failed: Module 'Mojolicious::Plugin::Status' is not installed
```

**Comment by Difegue** [comment]
@chenrui333 iirc from my (failed) 0.7.7 PR, the formula needs  
```
depends_on "zstd"
```  
for `Sereal::Encoder` (and henceforth `Mojolicious::Plugin::Status`) to build on some machines.

**Comment by carlocab** [comment]
Looks like it's trying to modify something in the formula prefix during the test, which is why it's failing.

**Comment by Difegue** [comment]
The app creates *.pid files in its `script` directory to keep track of currently running worker processes. This used to work fine in previous brew versions but perhaps something has changed since last time? 😅  

I'll make a note as the upstream maintainer to move the creation of those .pid files somewhere else for a future release.

**Comment by carlocab** [comment]
Did it? I don't think anything's changed since then. Tests have always run in a sandbox, which restricts locations where you can write things to. If you were writing in a subdirectory of `HOME` previously, or something like that, the `brew` does set `HOME` appropriately so it's somewhere you can write to.

**Pull request closed without merging**
