### PR TITLE
docker docker-completion 27.3.0

### PR DESCRIPTION
**Pull request by cv3x**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Comment by calvinit** [comment]
`Help wanted`, what is the problem? Is it the problem of Homebrew itself?  @chenrui333 @stefanb 
```
Error: /opt/homebrew/Cellar/docker-completion/27.3.0 is not a directory
```

**Comment by stefanb** [comment]
Interesting.

Complete log before failure:

>  ==> Downloading https://ghcr.io/v2/homebrew/core/docker/manifests/27.3.0
  curl: (56) The requested URL returned error: 404
  ==> Fetching dependencies for docker: docker-completion
  ==> Downloading https://ghcr.io/v2/homebrew/core/docker-completion/manifests/27.3.0
  curl: (56) The requested URL returned error: 404
  ==> Fetching docker-completion
  ==> Downloading https://ghcr.io/v2/homebrew/core/docker-completion/blobs/sha256:4d749c41af20db8f943d3415cf57d[55](https://github.com/Homebrew/homebrew-core/actions/runs/10953126109/job/30418196093?pr=191307#step:3:56)cc932f3301af10aca65cf8cda90e67b23
  ==> Installing dependencies for docker: docker-completion
  ==> Installing docker dependency: docker-completion
  ==> Downloading https://ghcr.io/v2/homebrew/core/docker-completion/manifests/27.3.0
  curl: ([56](https://github.com/Homebrew/homebrew-core/actions/runs/10953126109/job/30418196093?pr=191307#step:3:57)) The requested URL returned error: 404
  ==> Pouring docker-completion--27.3.0.all.bottle.tar.gz
  Error: /opt/homebrew/Cellar/docker-completion/27.3.0 is not a directory
  Error: /opt/homebrew/Cellar/docker-completion/27.3.0 is not a directory

**Comment by carlocab** [comment]
This is a `test-bot` bug. Opened a fix at Homebrew/homebrew-test-bot#1227.

**Review by carlocab — APPROVED** [review]
Thanks!

**Review by Rylan12 — APPROVED** [review]

**Pull request merged**
