### PR TITLE
monero 0.17.3.0

### PR DESCRIPTION
**Pull request by selsta**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by selsta** [comment]
We now set `UPNPC_NO_INSTALL` in CMake: https://github.com/monero-project/monero/blob/v0.17.3.0/external/CMakeLists.txt#L41

Should I remove these lines?

https://github.com/Homebrew/homebrew-core/blob/427823d29a93fa13d5d73683b59d932c3f7c0372/Formula/monero.rb#L41-L43

**Comment by carlocab** [comment]
> Should I remove these lines?

Yes, please. It'll probably error out anyway when it tries to `rm` a file that doesn't exist.

**Comment by selsta** [comment]
@carlocab updated

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request closed without merging**
