### PR TITLE
Updates llvm to the current package

### PR DESCRIPTION
**Pull request by jkthorne**

### CODE REVIEW

**Comment by SMillerDev** [comment]
Are you sure the newest version is supported? Because it's failing to build with it.

**Comment by DomT4** [comment]
IIRC `llvm 6.0.1` support will land in the next release. It's upstream and we could consider accepting a patch I guess, but as far as I'm aware https://github.com/crystal-lang/crystal/pull/6380 hasn't yet made it into a release. CC @felixbuenemann.

**Comment by wontruefree** [comment]
It seems to work locally with llvm 6.0.1.  I am having trouble finding the failed message output on CI for the individual operating systems.

**Comment by wontruefree** [comment]
I am building it locally and it seems to work.  I dont know why but I can close this until the new crystal is released.

**Comment by felixbuenemann** [comment]
Yes, Crystal 0.26.0 contains the compile fixes for LLVM 6.0, older versions require a patch.

**Comment by SMillerDev** [comment]
@wontruefree will you update this PR or are you gonna make a new one for 0.26?

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-core/pull/31086.

**Pull request closed without merging**
