### PR TITLE
zstd 1.3.3

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
boost linkage issue in osquery, depends on #21894

**Comment by ilovezfs** [comment]
I know.

**Comment by fxcoudert** [comment]
@ilovezfs I know you know 😄, I'm marking it for the record (since I wondered, checked, and found it… someone else might)

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
