### PR TITLE
monit 5.17.1

### PR DESCRIPTION
**Pull request by tkoenig**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Does your submission pass `brew audit monit`?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by tkoenig** [comment]
I'm not sure if  I am supposed to run  `brew audit --online --strict monit`, which raises the following issues below, but I did follow the [contributing guidelines](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) for version updates.

```
==> audit problems
monit:
 * Use pkgshare instead of (share/"monit")
 * Use pkgshare instead of (share/"monit")
```

**Comment by apjanke** [comment]
> I'm not sure if I am supposed to run `brew audit --online --strict monit`

It's not required, but it is desirable. And if you find audit problems when doing so, we appreciate them being fixed, and audit fixes can always be included with version updates. Do you mind rolling a fix for those in to this PR while you're in there?

**Comment by DomT4** [comment]
Yeah, `(share/"monit").install "monitrc"` should just be `pkgshare.install "monitrc"` and in the test `share/"monit/monitrc"` becomes `pkgshare/"monitrc"`.

It's the same directory, we've just employed some shorthand for it.

**Comment by tkoenig** [comment]
@apjanke done! 
Is there an documentation somewhere what `brew audit --online --strict`does?
It is confusing if you apply the changes then run the audit and it still fails until I push the changes?

**Comment by mikemcquaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
