### PR TITLE
slackcat 1.5

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> go build -o /usr/local/Cellar/slackcat/1.5/bin/slackcat -ldflags -X main.version=1.5
# github.com/vektorlab/slackcat
./slackcat.go:125:24: multiple-value api.FilesUpload() in single-value context
```

**Comment by igas** [comment]
Hi @fxcoudert ,

Upstream in makefile using git and we have tarball, should we switch to git tags in this case?

https://github.com/bcicen/slackcat/blob/1783046c2a99637f18178ab1ca1912f286746bd5/Makefile#L3

Thanks

**Comment by fxcoudert** [comment]
@igas we can switch to git tag

**Comment by igas** [comment]
@BrewTestBot test this please

**Comment by igas** [comment]
https://github.com/bcicen/slackcat/pull/61

**Pull request closed without merging**
