### PR TITLE
apache-flink 1.1.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by apjanke** [comment]
SHA mismatch when fetching from a mirror.

```
        ==> Downloading https://www.apache.org/dyn/closer.lua?path=flink/flink-1.1.2/flink-1.1.2-bin-hadoop27-scala_2.11.tgz
==> Best Mirror http://mirrors.ukfast.co.uk/sites/ftp.apache.org/flink/flink-1.1.2/flink-1.1.2-bin-hadoop27-scala_2.11.tgz
Downloaded to: /Users/brew/Library/Caches/Homebrew/apache-flink-1.1.2.tgz
SHA256: 3a5def68f0c9ff7c944b80c26d6fb09d29fa20d6f7c3a8b48579dbf91bfcec46
==> Retrying download
==> Downloading https://www.apache.org/dyn/closer.lua?path=flink/flink-1.1.2/flink-1.1.2-bin-hadoop27-scala_2.11.tgz
==> Best Mirror http://mirrors.ukfast.co.uk/sites/ftp.apache.org/flink/flink-1.1.2/flink-1.1.2-bin-hadoop27-scala_2.11.tgz
Warning: Formula reports different SHA256: ad77e4300db2b2b6ec2d09aa9520364a5a124e893a812cd01a6e0c2c60632bb8
Downloaded to: /Users/brew/Library/Caches/Homebrew/apache-flink-1.1.2.tgz
SHA256: 3a5def68f0c9ff7c944b80c26d6fb09d29fa20d6f7c3a8b48579dbf91bfcec46
```

Maybe a transient problem with the mirror?

@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@apjanke fixed.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@MikeMcQuaid uh oh https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/7460/version=el_capitan/console

looks like everything queued will be failing ...

**Comment by MikeMcQuaid** [comment]
@ilovezfs I'm looking at it but you can ignore those warnings and pull regardless. It's because we remove `HOMEBREW_CELLAR` on cleanup between builds.

**Comment by ilovezfs** [comment]
Yeah, directory is not even there :)

**Comment by MikeMcQuaid** [comment]
@ilovezfs will be fixed by https://github.com/Homebrew/brew/pull/899. Duplicate checks 😭

**Pull request closed without merging**
