### PR TITLE
libraw: Update to 0.19.2 and enable OpenMP

### PR DESCRIPTION
**Pull request by niheaven**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

I've made a mistake when pull and push in vscode... So close #35997 and reopen one.

@fxcoudert I've changed `//` to `/` and yes single slash is okay. To OpenMP support, the docs of libraw ([link](https://www.libraw.org/docs/Install-LibRaw.html)) show that `--enable-openmp` is the default option if supported, and it's better to add it.

### CODE REVIEW

**Comment by fxcoudert** [comment]
@niheaven does “no slash” work? I think it should

**Comment by niheaven** [comment]
@fxcoudert Yes, it does. So here, no double slash, no single slash, no space that should be escapedd.

**Comment by niheaven** [comment]
@fxcoudert I'm confused... See #36026, so one PR for one bumped app (5 PRs), or one commit for one app (1 PR, 5 commits in it)?

**Comment by SMillerDev** [comment]
one commit for five apps (1 PR, 5 commits in it, libraw first) please

**Comment by niheaven** [comment]
@fxcoudert @SMillerDev Is this commits order okay? One commit for one formula and libraw first.

**Comment by fxcoudert** [comment]
@niheaven thanks, that's perfect (1 PR, 5 commits)… except in the meantime another PR updated `siril`, so you will have to rebase now. Sorry!

**Comment by niheaven** [comment]
@fxcoudert Rebased, okay now.

**Comment by fxcoudert** [comment]
No, not rebased, you have a merge commit which should be removed. Right now our CI cannot test, and we can't merge.

**Comment by fxcoudert** [comment]
And now we're having some trouble with our CI: https://github.com/Homebrew/homebrew-test-bot/issues/231

**Comment by niheaven** [comment]
I don't know why... :scream_cat:
It's not mine... :crying_cat_face:
I just do nothing... :smile_cat:

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
CI is fixed 🎊 
@BrewTestBot test this please

**Pull request closed without merging**
