### PR TITLE
solr 7.5.0

### PR DESCRIPTION
**Pull request by abhinav-shrivastava**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by abhinav-shrivastava** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
```
solr:
  * Formula has other versions so create a versioned alias:
      cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases
      ln -s ../Formula/solr.rb solr@7.5
  * Formula has invalid versioned aliases:
      solr@7.4
```

I will fix this when I merge…

**Comment by fxcoudert** [comment]
Thanks @abhinav-shrivastava for the pull request

**Pull request closed without merging**
