### PR TITLE
oil 0.8.0

### PR DESCRIPTION
**Pull request by gromgit**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Please also make an issue for the HAVE_EPOLL upstream

**Comment by gromgit** [comment]
> Please also make an issue for the HAVE_EPOLL upstream

In progress: https://github.com/oilshell/oil/pull/825

**Comment by gromgit** [comment]
@SMillerDev , looks like at least the uploaded bottle for Catalina is correct, but the checksum recorded in the formula is wrong:
```
$ brew install oil
==> Downloading https://homebrew.bintray.com/bottles/oil-0.8.0.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/abcca1e8d09418c37353e4e3dd4d402ef0b88ae5a62145505a8f0a1013ebab98?response-content-disposition=attachment%3Bfilename%3D%22oil-0.8.0.catalina.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 8e5714ec5cc0700623b37e8c6e64c2fc85bec5cb91a48ecdd23c2139d2e0615c
  Actual: abcca1e8d09418c37353e4e3dd4d402ef0b88ae5a62145505a8f0a1013ebab98
 Archive: /Users/aho/Library/Caches/Homebrew/downloads/65373c6de720a8356853494fd5746ec2fe9d79c6e234789ea16c5bbea7a3347d--oil-0.8.0.catalina.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
...
$ tar tvf /Users/aho/Library/Caches/Homebrew/downloads/65373c6de720a8356853494fd5746ec2fe9d79c6e234789ea16c5bbea7a3347d--oil-0.8.0.catalina.bottle.tar.gz
drwxr-xr-x  0 brew   staff       0 Sep  4 00:59 oil/0.8.0/
-rw-r--r--  0 brew   staff     683 Sep  4 00:59 oil/0.8.0/INSTALL_RECEIPT.json
drwxr-xr-x  0 brew   staff       0 Sep  4 00:59 oil/0.8.0/bin/
drwxr-xr-x  0 brew   staff       0 Sep  4 00:59 oil/0.8.0/.brew/
-rw-r--r--  0 brew   staff   11562 Sep  4 00:59 oil/0.8.0/LICENSE.txt
drwxr-xr-x  0 brew   staff       0 Sep  4 00:59 oil/0.8.0/share/
drwxr-xr-x  0 brew   staff       0 Sep  4 00:59 oil/0.8.0/share/man/
drwxr-xr-x  0 brew   staff       0 Sep  4 00:59 oil/0.8.0/share/man/man1/
-rw-r--r--  0 brew   staff    1641 Sep  4 00:59 oil/0.8.0/share/man/man1/osh.1
-rw-r--r--  0 brew   staff     682 Sep  4 00:59 oil/0.8.0/.brew/oil.rb
lrwxr-xr-x  0 brew   staff       0 Sep  4 00:59 oil/0.8.0/bin/osh -> oil.ovm
-r-xr-xr-x  0 brew   staff 3801057 Sep  4 00:59 oil/0.8.0/bin/oil.ovm
lrwxr-xr-x  0 brew   staff       0 Sep  4 00:59 oil/0.8.0/bin/oil -> oil.ovm
```

**Comment by SMillerDev** [comment]
That's the old hash, you didn't go back to master after fixing the EPOLL issue

**Comment by gromgit** [comment]
Oops. I blame a very nice Trappist beer over dinner. :rofl:

**Pull request closed without merging**
