### PR TITLE
fakeroot 1.22

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like this still doesn't behave particularly well on post-SIP platforms given the test result 😓.

**Comment by ilovezfs** [comment]
Not surprising. What is somewhat surprising is that it has bottles despite the failing test.

**Comment by DomT4** [comment]
Maybe it was just pushed through in one of those giant new OS X/macOS bottle runs last year or the year before? IIRC as long as a formula built the bottle was pulled, and notes were made about failing tests to chase up. I could be remembering something else though.

**Comment by ilovezfs** [comment]
Seems likely. :see_no_evil:

**Comment by DomT4** [comment]
Personally I tend to think given Yosemite CI support is near-death unless upstream can find a fix here fairly soon it's probably just worth removing 🤷‍♂️.

**Comment by ilovezfs** [comment]
Na, I'm happy to believe it's still useful in SIPless environments. It probably just needs a --version test so we stop revisiting this problem over and over.

**Comment by DomT4** [comment]
I thought the broad policy was that brew didn't really support SIP-free environments, but yeah, I guess simplifying the test is the way to go if you're happy to keep this alive.

If it wouldn't stop the CI from being able to bottle this you could create a custom Requirement that checked in with `csrutil` as to whether SIP was enabled or not, but, not really worth it 🙈.

**Comment by ilovezfs** [comment]
Yeah, it just seems a tad on the ironic side to remove something that helps avoid using sudo  in a SIPless state in the name of security.

**Comment by DomT4** [comment]
Aye. It's just a pain to lose the ability to CI test it at least as effectively as is done currently with Yosemite's upcoming demise.

**Comment by ilovezfs** [comment]
True, but considering the number of formulae without any `test do` block at all, I cannot get to worked up about that.

**Pull request closed without merging**
