### PR TITLE
gdk-pixbuf 2.36.3

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by woodruffw** [comment]
Looks like the dynamic loader can't find `/usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib`. Since this is a minor bump, maybe upstream made a build/install change?

**Comment by tschoonj** [comment]
It looks like they made a mistake in configure.ac: the libtool version number was accidentally decreased.

**Comment by tschoonj** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=776892

**Comment by nijikon** [comment]
#9940

**Pull request closed without merging**
