### PR TITLE
opendetex 2.8.2

### PR DESCRIPTION
**Pull request by valkum**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
This is a fork of opendetex, not the original project, unless I am mistaken?

**Comment by valkum** [comment]
This is correct. The original detex was hosted on google code and there is no work done in a lot of years. The fork took over the development i assume, as there is not other repo which had a commit in the last 1.5 years.
Furthermore the fork added basic testing and fixed some memory leaks, which i assume is good.

**Comment by ilovezfs** [comment]
The original author has blessed the fork so we're good: https://www.cs.purdue.edu/homes/trinkle/detex/

**Comment by ilovezfs** [comment]
We should probably use https://github.com/pkubowicz/opendetex for the homepage now, too.

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew @valkum! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
