### PR TITLE
yle-dl 20201022

### PR DESCRIPTION
**Pull request by mprince**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
dependencies need to be updated.

**Comment by mprince** [comment]
@chenrui333 do you know which packages need to be updated or should i go through all the resources blocks and check off each one?

**Comment by chenrui333** [comment]
@mprince this is some gist written by @samford, which I feel pretty handy for myself.
https://gist.github.com/samford/5db4657f7943733445b15ef79cb38016

**Comment by samford** [comment]
I went ahead and updated the resource blocks, so this should be good to go once CI is green.

**Review by samford — APPROVED** [review]
Thanks, @mprince!

**Comment by mprince** [comment]
Thanks you @samford!

**Pull request closed without merging**
