### PR TITLE
mysql mysql-client 8.0.29

### PR DESCRIPTION
**Pull request by yahonda**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by yahonda** [comment]
Cherry-pick the commit at #100133 for mysql-client 8.0.29 because mysql and mysql-client packages need to be the same version.

**Comment by bayandin** [comment]
1. It looks like 8.0.29 hasn't been released officially yet: [Changes in MySQL 8.0.29 (Not yet released, General Availability)](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-29.html)
2. We got some linkage problems:
```
Full linkage --test innotop output
  Broken dependencies:
    /opt/homebrew/opt/mysql-client/lib/libcrypto.1.1.dylib (mysql-client)
    /opt/homebrew/opt/mysql-client/lib/libssl.1.1.dylib (mysql-client)
```
Probably because https://bugs.mysql.com/bug.php?id=103227 has been fixed. We don't remove `libcrypto` for `mysql-client` as we do for `mysql`, and some dependant formulae have picked this version (maybe we should think about an audit for such kinds of cases?)

**Comment by yahonda** [comment]
Thanks for the review. 

> It looks like 8.0.29 hasn't been released officially yet: [Changes in MySQL 8.0.29 (Not yet released, General Availability)](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-29.html)

I did not check the release note when I opened this pull request and found the release note is out finally. https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-29.html

**Comment by bayandin** [comment]
Failures on Linux:
```
brew linkage --cached --test --strict mytop
brew linkage --cached --test --strict ntopng
brew linkage --cached --test --strict percona-toolkit
brew linkage --cached --test --strict percona-xtrabackup
brew linkage --cached --test --strict sysbench
```

It happened because listed formulae depend on `mysql-client` but somehow are able to find `mysql` during the build and link with it instead. I've tried to work it around by setting mysql_config to the one from `mysql-client` but it seems it wasn't enough

**Comment by bayandin** [comment]
I think we can get this correctly built by splitting it into 2 PRs: one with removing libssl/libcrypto from `mysql-client` 8.0.28 and revision bumps for all dependent formulae the second one with `mysql` and `mysql-client` update to 8.0.29.

**Comment by chenrui333** [comment]
only linkage failure on linux build

```
  Unused missing linkage information:
    metadata_cache.so
```

**Comment by bayandin** [comment]
> only linkage failure on linux build
> 
> ```
>   Unused missing linkage information:
>     metadata_cache.so
> ```

Fixed

**Review by SMillerDev — APPROVED** [review]
@bayandin is this ready to merge?

**Comment by bayandin** [comment]
> @bayandin is this ready to merge?

It is! 
Not sure why @BrewTestBot keeps adding `automerge-skip` label.

**Comment by carlocab** [comment]
> > @bayandin is this ready to merge?
> 
> 
> 
> It is! 
> 
> Not sure why @BrewTestBot keeps adding `automerge-skip` label.

One of the commits modifies two formulae.

**Pull request closed without merging**
