### PR TITLE
envoy 1.23.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  source/extensions/filters/http/file_system_buffer/filter.cc:402:53: error: no viable constructor or deduction guide for deduction of template arguments of 'weak_ptr'
            config_->storageBufferPath(), [this, me = std::weak_ptr(shared_from_this()),
                                                      ^
...
  source/extensions/filters/http/file_system_buffer/filter.cc:405:52: error: use of undeclared identifier 'me'
              dispatcher->post([this, me = std::move(me), &state, file_handle]() {
                                                     ^
  source/extensions/filters/http/file_system_buffer/filter.cc:406:20: error: use of undeclared identifier 'me'
                if (!me.lock()) {
                     ^
  3 errors generated.
```

**Comment by cho-m** [comment]
LLVM may need https://github.com/llvm/llvm-project/commit/83564056d4b186c9fcf016cdbb388755009f7b5a which was added to LLVM 11
- macOS 10.15 runner uses Xcode 12.4 / Apple Clang 12.0.0, which maps to LLVM 10.0.0
- Xcode 12.5 / Apple Clang 12.0.5 updated to LLVM 11.1.0.

In current version, can try using `llvm` formula or making `:big_sur` the minimum.

Alternatively, can check with upstream as https://github.com/envoyproxy/envoy/tree/main/bazel#supported-compiler-versions claims minimum LLVM/Clang as 9 (though they test with 14). Not sure how reliable that page is given that GCC claims 9+ but I haven't been able to build with GCC 10+.

**Comment by SMillerDev** [comment]
We can't update partially. Either brew provides 1.23.0 or it doesn't.

**Comment by cpakulski** [comment]
The options to fix it are:
- upgrade compilers used on 10.15
- run a simple text reformatting after cloning repo. The fix is in the single line of c++ code.

**Pull request closed without merging**
