### PR TITLE
dolt 0.16.0

### PR DESCRIPTION
**Pull request by oscarbatori**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks @oscarbatori ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by oscarbatori** [comment]
No thanks needed, I am sort of professionally motivated here...

Any chance we could get this in? There is a stale version number in the current version that is not disastrous but a bit sloppy (it's sort of our fault for the way we historically published releases.

Appreciate the work you do on the tool.

**Comment by SMillerDev** [comment]
I'm happy people update homebrew packages, doesn't matter if they get paid for it. I'll merge this later, I can't merge from my phone.

**Comment by oscarbatori** [comment]
Fantastic Sean, thanks a bunch!

**Pull request closed without merging**
