### PR TITLE
poetry: migrate to python@3.10

### PR DESCRIPTION
**Pull request by henryiii**
poetry: migrate to python@3.10

### CODE REVIEW

**Comment by henryiii** [comment]
I think this is expecting `python3` to be valid? Looks like it running on Python 3.5 from the error...

**Comment by SMillerDev** [comment]
We can use `rewrite_shebang detected_python_shebang, "file"`

**Comment by henryiii** [comment]
If poetry can be pointed at different pythons, doesn't that apply to python 3.10 too? so if we leave it pointing at python3, we need to keep requiring the package that provides python3 (python@3.9), but users can use 3.10 just like they can use 3.7 and 3.8?

**Comment by carlocab** [comment]
Sorry, I meant Catalina and _Big Sur_, not Mojave. I thought that Mojave had `python3` too. Maybe it's just too old?

**Comment by carlocab** [comment]
Pushed a fix. Added a label to build dependents from source to make sure this didn't break anything.

**Comment by henryiii** [comment]
Looks like python 3.5 is trying to run it on Ubuntu?

**Pull request closed without merging**
