### PR TITLE
qt@5.5: add SYMROOT

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by nijikon** [comment]
#10839

**Comment by fxcoudert** [comment]
No, the build system is inside the script. The message is an audit issue coming from a comment: https://github.com/Homebrew/brew/pull/2199#issuecomment-287768076

**Comment by nijikon** [comment]
Yup, noticed that, will try to fix it if I will figure out how.

**Comment by ilovezfs** [comment]
What @fxcoudert said.

**Pull request closed without merging**
