### PR TITLE
semgrep 0.47.0

### PR DESCRIPTION
**Pull request by brendongo**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Fails to build with this error:
```
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ dir_chdir - tree-sitter
```

**Comment by brendongo** [comment]
Looking into build failure

**Comment by carlocab** [comment]
I see that this seems to be installing its own version of `tree-sitter`. Can this be made to use the `tree-sitter` formula instead?

**Comment by brendongo** [comment]
Yeah we're moving things around in the semgrep repo right now. Should be doable but right now it's installing deep in an install script. Can work on pulling that out and relying on tree-sitter formula in next week's release :D

**Comment by carlocab** [comment]
Sounds good. Thanks, @brendongo.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
