### PR TITLE
cassandra-reaper 1.4.2

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
Will check on it later.

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
How to resolve `Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter` issue? 

I tried to upgrade Java8 to Oracle JDK `1.8.0_211` from Oracle JDK `jdk1.8.0_152`, and have tested against both JDK versions, seems failed both.

**Comment by chenrui333** [comment]
Still waiting for feedback.

**Comment by chenrui333** [comment]
@zbeekman yeah, I have used Oracle JDK to do the test in my local, like this formula. It seems failed to me as well.

**Comment by zbeekman** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
The tag `1.4.2` doesn't seem to be in the repository (and releases) anymore. The latest release is currently `1.4.3`. Could you update the version accordingly?

**Comment by chenrui333** [comment]
@Moisan Try with the latest release now.

**Comment by chenrui333** [comment]
Same issue as before:
```
14:14:53 19:14:45,445 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file-appender] - openFile(/var/log/cassandra-reaper/reaper.log,true) call failed. java.io.FileNotFoundException: /var/log/cassandra-reaper/reaper.log (No such file or directory)
14:14:53 	at java.io.FileNotFoundException: /var/log/cassandra-reaper/reaper.log (No such file or directory)
14:14:53 	at 	at java.base/java.io.FileOutputStream.open0(Native Method)
14:14:53 	at 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:292)
14:14:53 	at 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
14:14:53 	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
14:14:53 	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
14:14:53 	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
14:14:53 	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)
14:14:53 	at 	at io.dropwizard.logging.AbstractOutputStreamAppenderFactory.build(AbstractOutputStreamAppenderFactory.java:30)
14:14:53 	at 	at io.dropwizard.logging.DefaultLoggingFactory.configure(DefaultLoggingFactory.java:143)
14:14:53 	at 	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:83)
14:14:53 	at 	at io.dropwizard.cli.Cli.run(Cli.java:78)
14:14:53 	at 	at io.dropwizard.Application.run(Application.java:93)
14:14:53 	at 	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:100)
14:14:53 19:14:45,445 |-INFO in ch.qos.logback.classic.AsyncAppender[async-file-appender] - Attaching appender named [file-appender] to AsyncAppender.
14:14:53 19:14:45,445 |-INFO in ch.qos.logback.classic.AsyncAppender[async-file-appender] - Setting discardingThreshold to 51
14:14:53 
14:14:53 java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
14:14:53 	at io.cassandrareaper.resources.auth.ShiroJwtProvider.getSigningKey(ShiroJwtProvider.java:63)
14:14:53 	at io.cassandrareaper.resources.auth.ShiroJwtProvider.<init>(ShiroJwtProvider.java:44)
14:14:53 	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:249)
14:14:53 	at io.cassandrareaper.ReaperApplication.run(ReaperApplication.java:81)
14:14:53 	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
14:14:53 	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
14:14:53 	at io.dropwizard.cli.Cli.run(Cli.java:78)
14:14:53 	at io.dropwizard.Application.run(Application.java:93)
14:14:53 	at io.cassandrareaper.ReaperApplication.main(ReaperApplication.java:100)
14:14:53 Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
14:14:53 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
14:14:53 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
14:14:53 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
14:14:53 	... 9 more
14:14:53 ==> curl -Im3 -o- http://localhost:8080/webui/
```

**Comment by chenrui333** [comment]
Will try new release 1.4.4 now.

**Comment by fxcoudert** [comment]
Closing for now.

**Pull request closed without merging**
