### PR TITLE
cmake cmake-docs 3.27.5

### PR DESCRIPTION
**Pull request by dnhn**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Not announced yet: https://cmake.org/download/

**Comment by dnhn** [comment]
> Not announced yet: https://cmake.org/download/

Updated.

**Comment by fxcoudert** [comment]
To whoever will approve and merge this: please dispatch new Sonoma bottles with `brew dispatch-build-bottle --macos 14,14-arm64 --issue 142161 --upload cmake`

**Comment by p-linnane** [comment]
I am keeping an eye on this and will take care of it.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
