### PR TITLE
Changed download link to be more org friendly

### PR DESCRIPTION
**Pull request by jake32321**
- [yes] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [yes] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [yes] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [yes] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Current download url is not org. friendly and is blocked.  Suggest using Github URL with checksum to resolve this issue.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Does this work for you?
```
  url "https://dl.bintray.com/rabbitmq/all/rabbitmq-server/3.7.4/rabbitmq-server-generic-unix-3.7.4.tar.xz"
  mirror "https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.4/rabbitmq-server-generic-unix-3.7.4.tar.xz"
  sha256 "a00b6067ab8f6ea1644fd88f128e3d045b71600c9e0a65021e12453e6000bdb0"
```

**Comment by jake32321** [comment]
sadly it doesn't. Still running into the same issue.

**Comment by ilovezfs** [comment]
@michaelklishin any thoughts here?

**Comment by jake32321** [comment]
one of the issues I ran into was that there were some issues I needed to resolve with `brew doctor` with a missing path that needed to be exported.  With that link and checksum I was able to get it to work for me.

**Comment by ilovezfs** [comment]
If having it as a mirror does not work, we'll need to pass on this PR as we want to use the canonical URL. Thanks nonetheless @jake32321

**Comment by michaelklishin** [comment]
Team RabbitMQ has a strong preference towards Bintray for a few reasons:

 * We have to pick one primary distribution channel and GitHub is not a frontrunner (it provides no support for package repositories, for example)
 * Bintray offers a CDN (GitHub does, too)
 * Bintray offers basic downloads statistics (GitHub offers none)
 * Bintray's limits for OSS projects are well known and we know their support is very helpful (GitHub limits are not known and we have no prior experience with their support in critical situations)

Therefore I 👎 this change on behalf of our team.

I don't know how I feel about a single user's org firewall configuration struggles leading to changes that affect every single user. But I don't maintain this formula, so 🤷‍♂️.

**Comment by ilovezfs** [comment]
@michaelklishin in case it was not clear from the above, the url has not been changed. Thanks for weighing in.

**Pull request closed without merging**
