### PR TITLE
newt rebuild bottle

### LINKED ISSUE #35291: Byobu - byobu-config does not work on OS X 10.14.2
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## `brew config` output:
```
HOMEBREW_VERSION: 1.8.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 858c5e1afb0eb00079a4f014e8fbedf9065d50e4
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1e763c8e81b8fc68b46b2a585c4b1c372581ea31
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
```
## `brew doctor` output:
```
anudeepsamaiya@orion:~$ brew doctor
Your system is ready to brew.
anudeepsamaiya@orion:~$
```

To help us debug your issue please explain:
- What you were trying to do (and why)
  I was trying to configure `byobu` using `byobu-config`
- What happened (include command output)
   The following output was thrown:
   ```
   ERROR: Could not import the python snack module
   ```
- What you expected to happen
   To have `byobu-config` screen available.
- Step-by-step reproduction instructions (by running `brew install` commands)
```
==> Installing dependencies for byobu: libpng
==> Installing byobu dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.36.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libpng-1.6.36.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.36: 27 files, 1.2MB
==> Installing byobu
==> Downloading https://homebrew.bintray.com/bottles/byobu-5.127.mojave.bottle.tar.gz
Already downloaded: /Users/anudeepsamaiya/Library/Caches/Homebrew/downloads/3fe19a65f2242c25abf8e714481a8a13b67b15da5dc7b36872a6d57221c29407--byobu-5.127.mojave.bottle.tar.gz
==> Pouring byobu-5.127.mojave.bottle.tar.gz
==> Caveats
Add the following to your shell configuration file:
  export BYOBU_PREFIX=/usr/local
==> Summary
🍺  /usr/local/Cellar/byobu/5.127: 161 files, 651.5KB
==> Caveats
==> byobu
Add the following to your shell configuration file:
  export BYOBU_PREFIX=/usr/local
```
```
anudeepsamaiya@orion:~$ $BYOBU_PREFIX
bash: /usr/local: Is a directory
```
```
anudeepsamaiya@orion:~$ byobu-config
ERROR: Could not import the python snack module
anudeepsamaiya@orion:~$
```

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
For some reason the old bottle didn't install python components.

This fixes #35291

### CODE REVIEW

**Comment by anudeepsamaiya** [comment]
@SMillerDev how can this PR be merged?

**Comment by albertmichaelj** [comment]
Will this be fixed soon? I'm running into the same issue as 
https://github.com/Homebrew/homebrew-core/issues/35291 Thanks!

**Comment by SMillerDev** [comment]
@Brewtestbot test this please

**Comment by albertmichaelj** [comment]
It seems like the snack module is still not being found. What needs to be done to ensure that it is included? I'm pretty new to the homebrew recipe scene, but I can try to help out. Is it a function for python2.7 vs python3?

This is blocking me from using byobu, so I'd really like to push on this if I can figure out what is going on.

**Comment by SMillerDev** [comment]
That shouldn't cause the failure only on Mojave, I suspect it's something in python path or something like that.

**Comment by martinslota** [comment]
I'm also having this problem - I think that the snack library is simply missing from the package for mojave (and not for the older versions of Mac OS).

Is there some way I could help find a solution or a workaround?

**Comment by SMillerDev** [comment]
> Is there some way I could help find a solution or a workaround?

If you could get newt to include the snack module properly 👼

**Comment by martinslota** [comment]
@BrewTestBot Could you test this again?

**Comment by MikeMcQuaid** [comment]
@BrewTestBot test this please

**Comment by martinslota** [comment]
@BrewTestBot Could you please test this again?

**Comment by martinslota** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
