### PR TITLE
tree-sitter: deprecate

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
Pins to specific releases of `emscripten`.
- https://github.com/Homebrew/homebrew-core/pull/155983
- https://github.com/tree-sitter/tree-sitter/issues/2803
- https://github.com/Homebrew/homebrew-core/pull/158865

### CODE REVIEW

**Comment by p-linnane** [comment]
Turns out this is used by `emacs`, `neovim`, `rizin`, and `semgrep`. Not sure how we should/can handle this.

**Review by MikeMcQuaid — COMMENTED** [review]
> Turns out this is used by `emacs`, `neovim`, `rizin`, and `semgrep`. Not sure how we should/can handle this.

Given these are high-profile, widely used formulae: I think vendoring the specific `emscripten` version in the `tree-sitter` formula feels appropriate. If it's still supported and preferable: we could have an `emscripten@something` formula added.

**Comment by clason** [comment]
> Can we pare down tree-sitter to only include libs?

You can (and arguably should) separate the two, but the CLI is definitely used in the wild (required to work with -- and even install some -- tree-sitter parsers).

Alternatively, you could request tree-sitter to allow building without WASM support; however, the project is poorly maintained these days so I wouldn't get my hopes up.

**Comment by p-linnane** [comment]
It appears `tree-sitter` uses v3.1.29 of `emscripten` which is from December 2022. Since `tree-sitter` is the only formula we package that uses `emscripten`, I will vendor it in a new PR. I don't think it makes sense to have a versioned formula for it.

**Comment by p-linnane** [comment]
Vendoring `emsdk` in the `tree-sitter` formulae makes it vendor its own Python, Node, etc. So a versioned formula is going to be the only way to go. I'll get a PR for that up later tonight.

**Pull request closed without merging**
