### PR TITLE
rocksdb 6.3.6

### PR DESCRIPTION
**Pull request by y8**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Bump `osquery` revision to fix the test step issue.

**Comment by y8** [comment]
Should I squash commits?

**Comment by chenrui333** [comment]
I think it is fine, I can squash the commits while merging the PR.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
PR build looks good now, merging.

**Comment by chenrui333** [comment]
Interesting, 

```
curl: (22) The requested URL returned error: 404 Not Found

Error: Failure while executing; `/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.1.15-75-gaca815d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --fail --progress-bar --write-out \\n --silent --fail --user chenrui:****** --request POST --header Content-Type:\ application/json --data \{\"publish_wait_for_secs\":\ 0\} https://api.bintray.com/content/homebrew/bottles/osquery/3.3.2_8/publish` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
