### PR TITLE
filebeat 5.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
Changed build process I guess: https://bot.brew.sh/job/Homebrew%20Core/10206/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_filebeat/

**Comment by ruflin** [comment]
@dunn With the release of filebeat 5.0 the `filebeat.yml` file is not in the `etc` directory anymore but directly in the top directory. (like 28)

**Comment by ilovezfs** [comment]
I'll leave this to someone else.

**Comment by ruflin** [comment]
@ilovezfs I will pick this up and will adjust it based on https://github.com/Homebrew/homebrew-core/pull/6441

**Comment by ruflin** [comment]
Follow up PR can be found here: https://github.com/Homebrew/homebrew-core/pull/6315

**Pull request closed without merging**
