### PR TITLE
workflows: add missing HOMEBREW_DEVELOPER: 1

### PR DESCRIPTION
**Pull request by iMichka**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
What does it do?

**Comment by iMichka** [comment]
As we have it set in the macOS tests too, I thought it would be good to have it set for Linux too.

I'm trying to upload logs in failed linux builds.

**Comment by dawidd6** [comment]
https://github.com/Homebrew/homebrew-test-bot/blob/8c327484819bf6f8b0212cea0abd3eb7ed780abd/cmd/test-bot.rb#L90

This line is not executed on Linux and it should be if we want the logs in PWD.

HOMEBREW_DEVELOPER is already set in test-bot.

**Comment by iMichka** [comment]
But why is it set again here: https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/tests.yml#L94?

So the realy fix needs to go into test-bot then. I'll have a look later today, but anyone can poke at it if they want.

**Comment by dawidd6** [comment]
IMO it's unnecessary, but I don't know who added it and why.

**Pull request closed without merging**
