### PR TITLE
isl 0.22

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Bumped all formula where there was a linkage issue, as was done in #38553.

**Comment by fxcoudert** [comment]
GCC on Mojave has an issue: https://github.com/Homebrew/homebrew-core/pull/45585
and: https://github.com/Homebrew/homebrew-core/issues/46393

**Comment by Bo98** [comment]
@BrewTestBot test this please

**Comment by Bo98** [comment]
On wait, gcc needs to be revision 3. My bad, sorry! GitHub doesn't show any merge conflicts on this pull request for some reason.

**Comment by fxcoudert** [comment]
- `ipopt` needs a revision bump
- random `gcc` parallel build failure on Mojave 😢

**Pull request closed without merging**
