### PR TITLE
s4cmd 2.1.0 (new formula)

### LINKED ISSUE #175: Homebrew support
It would be nice to have homebrew support like s3cmd

https://github.com/Homebrew/homebrew-core/blob/master/Formula/s3cmd.rb

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

- closes bloomreach/s4cmd#175

### CODE REVIEW

**Comment by chenrui333** [comment]
interesting, this PR did not get tagged with `python` and `new formula` labels. 🤔

**Comment by bayandin** [comment]
Is this project maintained/supported?
The last meaningful commit was in Apr 2019. And the previous one in Oct 2018 (it has 75 open issues and 19 PRs).

Also @chenrui333 had the same question in https://github.com/bloomreach/s4cmd/issues/175#issuecomment-653920755

**Comment by chenrui333** [comment]
I think this project is still maintained based on this commit, https://github.com/bloomreach/s4cmd/commit/be8dd08a97e0827547ca1dfedbf2878f7ba3adab

I will file a PR to add homebrew install documentation to that repo.

**Comment by dawidd6** [comment]
> interesting, this PR did not get tagged with `python` and `new formula` labels. 🤔

Because this PR modifies two files.

**Comment by chenrui333** [comment]
that sounds about right.

**Comment by chenrui333** [comment]
ready for the merge?

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
