### PR TITLE
Add alternative versions for PyPy3

### PR DESCRIPTION
**Pull request by tonybaloney**
The PyPy3 formula is PyPy3.7.

There are major versions 3.8 and 3.9. These are not compatible with 3.7, so they should be optional versions (just like Python 3.7, 3.8 etc)

This PR adds 3.8 and 3.9

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by henryiii** [comment]
Please see https://github.com/Homebrew/homebrew-core/pull/88123#discussion_r746699633 . The @ is not supposed to be used for different flavors of a formula, but only for "old" versions. If there was a PyPy 8 release, then there could be a pypy3.9@7, for example.

**Comment by tonybaloney** [comment]
@henryiii thanks. PyPy's versions is a bit confusing

PyPy refers to the Python 2.7 compatible interpreter
PyPy3 refers to the Python 3+ compatible interpreter.

Within PyPy3 there are then releases to match compatibility with the equivalent Python versions
- 3.7 
- 3.8 
- 3.9

They also run an internal versioning scheme, which is currently v7.3.8. https://doc.pypy.org/en/latest/release-v7.3.8.html 

So for the v7.3.8 release there are builds for Python 3.7, 3.8 and 3.9

pypy3.9-v7.3.8-src.tar.bz2
pypy3.8-v7.3.8-src.tar.bz2
pypy3.7-v7.3.8-src.tar.bz2

I don't think general users would know or care whether they installed v7. or v8 of PyPy, since they should be compatible within the version of Python they're targeting.

So, I would expect
`brew install python@3.9` 
To be equivalent to 
`brew install pypy@3.9`

That in mind, and after reading the linked issue. I think the following makes sense.

- `pypy@2.7` - the current `pypy` recipe
- `pypy@3.7` - the current `pypy3`
- `pypy@3.8` - added `pypy3` recipe (in this PR but I'll rename)
- `pypy` as the `pypy3@3.9` recipe
- `pypy3` -> `pypy` as an alias (is this just a symbolic link?)

Please let me know what you think

**Comment by carlocab** [comment]
> I don't think general users would know or care whether they installed v7. or v8 of PyPy, since they should be compatible within the version of Python they're targeting.

I disagree. If users don't care, why should we ever update the existing `pypy` and `pypy3` formulae?

In any case, even if users don't care, that's not a reason to misuse the `@`-scheme for identifying versions of the formula.

**Comment by tonybaloney** [comment]
> > I don't think general users would know or care whether they installed v7. or v8 of PyPy, since they should be compatible within the version of Python they're targeting.
> 
> I disagree. If users don't care, why should we ever update the existing `pypy` and `pypy3` formulae?
> 
> In any case, even if users don't care, that's not a reason to misuse the `@`-scheme for identifying versions of the formula.

Ok. That makes sense. 

I'm not clear on the alternative solution though. 

Pypy currently installs 2.7-7.3.8 and pypy3 installs 3.7-7.3.8

The latest version of pypy is 3.9-7.3.8 

Anyone wanting to run Python >3.7 on pypy can't do so using either recipe today.

**Comment by henryiii** [comment]
I think the alternate was just to label the formula "pypy3.8", and if there's ever a need for an "old" version, it would be "pypy3.8@7", etc. Though I think the last PR got stuck because the author didn't know how to add a dot to a formula name. Possibly "DOT", like "AT"? Not sure either, though.

**Comment by henryiii** [comment]
The latest version of PyPy is 7.3.8, and it comes in four flavors, 2.7, 3.7, 3.8, and 3.9 (beta). There will be a 7.3.9 in about a week, FYI, due to an ABI mistake with 3.7 I think. Or maybe 3.8, or both, I've forgotten which.

**Comment by carlocab** [comment]
A `pypy3.8` formula should just be named `pypy3.8.rb` with the class declaration
```ruby
class Pypy38 < Formula
```

**Comment by tonybaloney** [comment]
> A `pypy3.8` formula should just be named `pypy3.8.rb` with the class declaration
> ```ruby
> class Pypy38 < Formula
> ```

Got it. I'll put that together then. Is there a way of sharing code between recipes since they're pretty much identical except for the URL, version and SHA

**Comment by gromgit** [comment]
> Is there a way of sharing code between recipes since they're pretty much identical except for the URL, version and SHA

Not that I know of, and it's far better that each formula stand alone. Otherwise, when a specific version (probably the latest) requires changes to its `install` block, you'd have to break up the formulae anyway.

**Comment by carlocab** [comment]
```ruby
class Pypy38 < Pypy3
```
_might_ work. That said, things like the `livecheck` and `bottle` blocks should be different. And we probably also actually want slightly different `install` methods so that these formulae don't conflict with each other.

**Comment by gromgit** [comment]
> ```
> class Pypy38 < Pypy3
> ```

Does this trigger a rebuild of `pypy38` if `pypy3` changes blocks that are not overridden in the child formula? If not, that would be a good reason not to inherit formula definitions this way.

**Comment by carlocab** [comment]
> > ```
> > class Pypy38 < Pypy3
> > ```
> 
> 
> Does this trigger a rebuild of `pypy38` if `pypy3` changes blocks that are not overridden in the child formula? If not, that would be a good reason not to inherit formula definitions this way.

Actually, it probably does something worse: `pypy38` will inherit `pypy3`'s `revision`s without corresponding rebuilds.

**Comment by tonybaloney** [comment]
Please can you review this PR again? I've made adjustments based on the discussion naming plan

**Comment by tonybaloney** [comment]
please hold, seeing there are conflicts if you try and install all 3

**Comment by tonybaloney** [comment]
please hold, seeing there are conflicts if you try and install all 3

**Comment by tonybaloney** [comment]
Alright, can install all 3 recipes side-by-side. The 3.9 branch has different build artefacts so it was a bit confusing.

Please review

**Comment by tonybaloney** [comment]
Alright, can install all 3 recipes side-by-side. The 3.9 branch has different build artefacts so it was a bit confusing.

Please review

**Comment by tonybaloney** [comment]
This isn't stale

**Comment by henryiii** [comment]
Agreed. :) Though the PyPy version has likely bumped over the last week. @carlocab perhaps?

**Comment by tonybaloney** [comment]
Can the bot un-close the PR?

**Pull request closed without merging**
