### PR TITLE
dvc: use openssl@1.1 instead of 1.0

### PR DESCRIPTION
**Pull request by efiop**
Per https://github.com/Homebrew/homebrew-core/pull/45709#issuecomment-554689997

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
You'll want to bump the revision (add `revision 1` after the first `sha256` line) so that people can get the update.

**Comment by efiop** [comment]
@Bo98 Thanks for catching that one! Updated.

**Comment by fxcoudert** [comment]
Thank you @efiop

**Comment by Bo98** [comment]
This seems to not link to OpenSSL 1.1 properly. The formula is not installing the pip dependencies from source, which might be a part of the problem.

```
$ brew linkage dvc
System libraries:
  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libffi.dylib
  /usr/lib/libncurses.5.4.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)
Variable-referenced libraries:
  @executable_path/../.Python
  @loader_path/../.dylibs/libopenblasp-r0.3.7.dylib
  @loader_path/libgcc_s.1.dylib
  @loader_path/libgfortran.3.dylib
  @loader_path/libquadmath.0.dylib
  @rpath/libarrow.14.dylib
  @rpath/libarrow_boost_filesystem.dylib
  @rpath/libarrow_boost_regex.dylib
  @rpath/libarrow_boost_system.dylib
  @rpath/libarrow_flight.14.dylib
  @rpath/libarrow_python.14.dylib
  @rpath/libgandiva.14.dylib
  @rpath/libparquet.14.dylib
  @rpath/libplasma.14.dylib
Undeclared dependencies with linkage:
  openssl
```

**Comment by efiop** [comment]
@Bo98 Great catch! Preparing a PR right now. Thanks! 🙂

**Comment by efiop** [comment]
@Bo98 FYI: Created https://github.com/Homebrew/homebrew-core/pull/46860 , please take a look. Thank you! 🙂

**Pull request closed without merging**
