### PR TITLE
jj: Change to libgit2@1.7

### LINKED ISSUE #177686: jj VCS cannot find correct libgit2
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
~
➜ brew gist-logs jj
Error: No logs.

~
➜ brew config
HOMEBREW_VERSION: 4.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c98a33a376e5b35ebc801d0f7d6ba7b9eb118ac
Last commit: 10 days ago
Core tap JSON: 18 Jul 05:25 UTC
Core cask tap JSON: 18 Jul 05:25 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: hx
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false

~
➜ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Tried to follow the jujutsu VCS tutorial yesterday, got a dyld error about it being unable to locate the correct libgit2 version. It seems that it explicitly searches for libgit2@1.7, but the formula depends on libgit2 as of this writing:

```
➜ brew info jj
==> jj: stable 0.19.0 (bottled), HEAD
Git-compatible distributed version control system
https://github.com/martinvonz/jj
Installed
/opt/homebrew/Cellar/jj/0.19.0 (14 files, 15.8MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-07-18 at 07:27:35
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/j/jj.rb
License: Apache-2.0
==> Dependencies
Build: pkg-config ✔, rust ✔
Required: libgit2 ✔, openssl@3 ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 647 (30 days), 1,846 (90 days), 4,397 (365 days)
install-on-request: 648 (30 days), 1,846 (90 days), 4,397 (365 days)
build-error: 14 (30 days)
```

When I list libgit2's lib folder, it shows me the versioned dylib for libgit2 v1.8.1:

```
~
➜ ls /opt/homebrew/opt/libgit2/lib
libgit2.1.8.1.dylib libgit2.1.8.dylib   libgit2.a           libgit2.dylib       pkgconfig
```

So this seems to be a version mismatch of libgit2 for the jj formula.

### What happened (include all command output)?

```
~
➜ jj --version
dyld[73987]: Library not loaded: /opt/homebrew/opt/libgit2/lib/libgit2.1.7.dylib
  Referenced from: <E8960ED2-AAE3-34EB-9B6F-057F96828A15> /opt/homebrew/Cellar/jj/0.19.0/bin/jj
  Reason: tried: '/opt/homebrew/opt/libgit2/lib/libgit2.1.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libgit2/lib/libgit2.1.7.dylib' (no such file), '/opt/homebrew/opt/libgit2/lib/libgit2.1.7.dylib' (no such file), '/opt/homebrew/Cellar/libgit2/1.8.1/lib/libgit2.1.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/libgit2/1.8.1/lib/libgit2.1.7.dylib' (no such file), '/opt/homebrew/Cellar/libgit2/1.8.1/lib/libgit2.1.7.dylib' (no such file)
zsh: abort      jj
```

### What did you expect to happen?

jj just printing me the version.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install jj
jj --version
```

### PR DESCRIPTION
**Pull request by nicholasjng**
Depend on libgit2@1.7 instead of the unpinned version. jj itself currently expects libgit2 < 1.8, so this change allows the dynamic linker to pick up the right shared library.

Addresses #177686.

New contributor, just thought I'd submit it quickly after the encouragement in https://github.com/Homebrew/homebrew-core/issues/177686#issuecomment-2236903619.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by nicholasjng** [comment]
Needs a `revision 1` line probably below the `head` metadata field.

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/pull/166767

**Review by cho-m — APPROVED** [review]

**Review by carlocab — APPROVED** [review]
Thanks!

**Review by carlocab — APPROVED** [review]
Thanks!

**Pull request merged**
