### PR TITLE
cadence-workflow 0.25.0

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
it builds out fine in my local ventura arm.

**Comment by chenrui333** [comment]
really frustrating
```
  protoc...
  arch: posix_spawnp: .bin/protoc-3.14.0: Bad CPU type in executable
  arch: posix_spawnp: .bin/protoc-3.14.0: Bad CPU type in executable
  arch: posix_spawnp: .bin/protoc-3.14.0: Bad CPU type in executable
  arch: posix_spawnp: .bin/protoc-3.14.0: Bad CPU type in executable
  make: *** [.build/protoc] Error 1
```

**Comment by chenrui333** [comment]
the protoc version they use in the repo is really old (3.14.0 vs 21.12)

**Comment by cho-m** [comment]
If only ARM Ventura fails, that is usually a sign of x86_64 binaries being used. Our ephemeral CI runner doesn't include Rosetta.

**Comment by ZhongRuoyu** [comment]
It turned out that Rosetta is not a real requirement. While `EMULATE_X86` is set to `arch -x86_64` for `Darwin arm64` (https://github.com/uber/cadence/blob/v0.25.0/Makefile#L81-L85), it is only used to invoke `protoc`, a dummy zero-byte executable generated by `.fake-codegen`. So, a `EMULATE_X86=` trick fixed the build here.

(Actually, there are other occurrences of `EMULATE_X86` in the [Makefile](https://github.com/uber/cadence/blob/v0.25.0/Makefile) as well. But they are only used for linting targets that are not used during the build.)

As for why `protoc` is handled this way: https://github.com/uber/cadence/blob/v0.25.0/Makefile#L307-L310

```Makefile
# buildkite / release-only target to avoid building / running codegen tools (protoc is unable to be run on alpine).
# this will ensure that committed code will be used rather than re-generating.
# must be manually run before (nearly) any other targets.
.fake-codegen: .fake-protoc .fake-thrift
```

The proto files committed at the [`.gen`](https://github.com/uber/cadence/tree/v0.25.0/.gen) directory will be used instead.

Also, `v0.25.0` was retagged three days ago, and it's the latest release now: https://github.com/uber/cadence/releases/tag/v0.25.0.

**Comment by chenrui333** [comment]
> Also, `v0.25.0` was retagged three days ago, and it's the latest release now: https://github.com/uber/cadence/releases/tag/v0.25.0.

that sucks 🤦

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
