### PR TITLE
Go 1.14

### PR DESCRIPTION
**Pull request by leonklingele**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Review by un000 — APPROVED** [review]
Go!

**Review by rentziass — APPROVED** [review]
:shipit:

**Review by meeDamian — APPROVED** [review]

**Comment by chenrui333** [comment]
Can we always create companion PRs for the previous version for this kind of change?

**Comment by chenrui333** [comment]
That being said, I am glad we made it so quickly.

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/pull/50704

**Comment by leonklingele** [comment]
Sure thing! Will do from now on.

**Comment by chenrui333** [comment]
Thanks, appreciate it!

**Pull request closed without merging**
