### PR TITLE
docker and docker-completion: fix revision hash

### PR DESCRIPTION
**Pull request by andrasmaroy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
Tag was updated in #22174  but the commit hash wasn't, updated according to the [official repo](https://github.com/docker/docker-ce/releases/tag/v17.12.0-ce).

### CODE REVIEW

**Review by ilovezfs — CHANGES_REQUESTED** [review]
These are verified at build time, so if they retagged we need an explanation from upstream as to what happened in order to rule out malicious circumstances.

**Comment by andrasmaroy** [comment]
As you can see in the link above, the tag in this formula points to the hash I've updated to, don't know what happened there. How and who to contact upstream with this?

**Comment by ilovezfs** [comment]
Yes, this PR updates the hash to something different from what it was originally in https://github.com/Homebrew/homebrew-core/pull/22174 at which time it was verified as being correct. For security we don't change the tag commit hash without an explanation. Contact info is here https://www.docker.com/company/contact

**Comment by andrasmaroy** [comment]
Support request number 00037354 created at Docker.

**Comment by ilovezfs** [comment]
@andrasmaroy thanks! We'll also need to bump the formula revision here, and make the same changes for the `docker` formula, which was built from that same tag.

**Comment by ilovezfs** [comment]
to bump revisions you need to add
```
revision 1
```

**Comment by r-chris** [comment]
This should also affect the `docker.rb` formula as it points to the same hash in the same repo.

**Comment by r-chris** [comment]
The release was done 9 days ago, but someone appears to have re-tagged this only a day ago: https://github.com/docker/docker-ce/tags

**Comment by rmg** [comment]
I'm not sure how the verification was done the first time, but it is pretty clear from the actual contents of the original commit sha1 that it is not the correct commit for that tag.

Is there anything that can be done to prevent this sort of problem in the future? The process as-is (which seems pretty reasonable) appears to make it easier to make the mistake in the first place than it is to fix it afterwards.

**Comment by ilovezfs** [comment]
@rmg yes. Ask upstream never to retag.

**Comment by ulfw** [comment]
Is there anything a homebrew user can do now to install / update the completions?

**Comment by AlanHohn** [comment]
@ulfw Yep. `brew edit docker-completion`, replace the revision hash, save, and `brew upgrade docker-completion`.

Since this is a Git repository, you'll now have local edits that will interfere with `brew update` of that formula. To fix this you can `git checkout` the file. In this case:

```
cd /usr/local/Homebrew/Library/Taps/homebrew
git checkout Formula/docker-completion.rb
```

**Comment by ilovezfs** [comment]
This will be taken care of by
https://github.com/Homebrew/homebrew-core/pull/22729
https://github.com/Homebrew/homebrew-core/pull/22730

Thanks for bringing it to our attention @andrasmaroy!

**Pull request closed without merging**
