### PR TITLE
rust 1.74.0

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by Bo98** [comment]
Requires 10.12 as of this release so maybe worth marking as `depends_on macos: :sierra` given how popular Rust is: https://blog.rust-lang.org/2023/09/25/Increasing-Apple-Version-Requirements.html

**Comment by ZhongRuoyu** [comment]
Thanks @Bo98! Indeed that seems to be the issue. Let's see if it builds with the `compile.rs` patch...

**Comment by ZhongRuoyu** [comment]
> If it only fails to build on 12-arm64, shouldn't the patch only be applied there?

It's possible but either should work; the patch should have no impact on the other platforms since the error didn't occur.

**Comment by Bo98** [comment]
>If it only fails to build on 12-arm64, shouldn't the patch only be applied there?

Generally, I say to apply the patch everywhere. If a patch is for some reason considered unsafe to apply everywhere, then such a patch should probably not be included at all.

In this case, upstream have patched it for all, unconditionally, so we'll trust that.

**Comment by chenrui333** [comment]
looks good so far 🤞

**Comment by Bo98** [comment]
> Is the Linux job not considering ` CI-build-dependents-from-source`?

No it doesn't. I don't remember the historical reasons for this. It will do any Linux-only formulae however.

That check is largely for API compatiblity checks so it might be worth making it split those among runners.

> Also, question: considering it does anyway the job of building these formulas when this tag is present, why not have those formulas benefiting of a compilation with the last compiler, to get rid of potential bugs, security issues and so on

This is probably also reasonable. Or at least for Rust & Go specifically.

**Comment by ZhongRuoyu** [comment]
## Source build failures

- [ ] `gping` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675252?pr=154526#step:3:5353)): `error[E0283]: type annotations needed`
- [ ] (x86_64) `gptline` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675114?pr=154526#step:3:5754)): `src/libImaging/Jpeg2K.h:11:10: fatal error: 'openjpeg.h' file not found`
- [ ] `leaf-proxy` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675252?pr=154526#step:3:7311)): ``error[E0425]: cannot find value `VERSION_3_2_0` in crate `protobuf` ``
- [ ] `solana` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675252?pr=154526#step:3:10676)): ``error: assigning to `&T` is undefined behavior, consider using an `UnsafeCell` ``
- [ ] `tremor-runtime` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675481?pr=154526#step:3:10544)): ``error: no rules expected the token `:` ``

## Pre-existing issues

- [x] `flux` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675481?pr=154526#step:3:3907)): `error: private item shadows public glob re-export`; influxdata/flux#5440
- [ ] `gluon` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675481?pr=154526#step:3:4595)): `error[E0308]: mismatched types`; gluon-lang/gluon#951
- [x] `grin-wallet` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675481?pr=154526#step:3:5284)): `error: variable does not need to be mutable`; mimblewimble/grin-wallet#684
- [ ] `influxdb` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675481?pr=154526#step:3:5837)): `error: private item shadows public glob re-export` 
- [ ] `influxdb@1` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675481?pr=154526#step:3:6088)): `error: private item shadows public glob re-export`
- [ ] `kapacitor` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675481?pr=154526#step:3:6530)): `error: private item shadows public glob re-export`
- [ ] (x86_64) `pushpin` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675363?pr=154526#step:3:9290)): `include/GFp/check.h:27:11: fatal error: 'assert.h' file not found`
- [ ] (x86_64) `watchman` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675114?pr=154526#step:3:13875)): `ld: Undefined symbols`; https://github.com/Homebrew/homebrew-core/pull/118242#issuecomment-1367052317

## Checksum mismatch

- [ ] `neovide` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675252?pr=154526#step:3:8379))
- [ ] `wasmer` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675252?pr=154526#step:3:12271))

## Transient failures

- (14-arm64) `boringtun` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675252?pr=154526#step:3:1740)): `Timeout::Error: execution expired`
- (12-x86_64) `tcl-tk` ([logs](https://github.com/Homebrew/homebrew-core/actions/runs/6895219009/job/18768675621?pr=154526#step:3:3867)): `Error: bad URI(is not URI?): "https://downloads.sourceforge.net/project/incrtcl/[incr%20Tcl_Tk]-4-source/itk%204.1.0/itk4.1.0.tar.gz?download&failedmirror=deac-riga.dl.sourceforge.net"`

**Review by chenrui333 — APPROVED** [review]

**Comment by ZhongRuoyu** [comment]
Failures are non-blocking; merging now :shipit:

**Comment by chenrui333** [comment]
I will followup with those failures (after all, rust is just build dependency for many formulae)

**Pull request merged**
