### PR TITLE
Remove ld-find-code-refs formula

### PR DESCRIPTION
**Pull request by carmenquan**
Having this formula conflicts with our current release process with GoReleaser. Until we can update our release process, we'd like to request this formula be removed. 

-----

### CODE REVIEW

**Review by carlocab — CHANGES_REQUESTED** [review]
We don't remove formulae unless they don't work, are no longer under development, or have an non-open source license.

Sorry!

**Comment by chenrui333** [comment]
Yeah, agree, we don't need to remove this formula (both tap and core would work for the end users).

**Comment by InTheCloudDan** [comment]
@carlocab Can you clarify the stance a bit further please? We are committed to and maintain our own tap of CLI application which we will keep up to date automatically. 

Given Goreleaser has no support of Homebrew Core, this formula would rely on @chenrui333 maintaining. Which while we appreciate it, we can't guarantee that going forward. By not removing the formula it is at a much higher risk of going stale and impacting our customers.

**Comment by carlocab** [comment]
Which part needs clarification?

> We are committed to and maintain our own tap of CLI application which we will keep up to date automatically.

That's fine. It's your tap; you can manage it however you please.

> Given Goreleaser has no support of Homebrew Core, this formula would rely on @chenrui333 maintaining.

Anyone can make a pull request against the formula, so I wouldn't say that this relies only on @chenrui333.

> Which while we appreciate it, we can't guarantee that going forward. By not removing the formula it is at a much higher risk of going stale and impacting our customers.

No guarantees from you are expected. I'm not sure whom you think of as your customers, but I imagine at least some users of this software would appreciate a variety of sources to install this from. That said, you can avoid your customers using a stale version by directing them to your tap and/or opening pull requests against the formula in Homebrew/core.

You can easily automate the latter with something like https://github.com/dawidd6/action-homebrew-bump-formula.

Lastly: could you clarify what you mean by "stale"? Formulae in Homebrew/core, especially the ones hosted on GitHub, are typically updated very quickly.

**Pull request closed without merging**
