### PR TITLE
portaudio 19.7.0

### PR DESCRIPTION
**Pull request by nrolland**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by nandahkrishna — APPROVED** [review]
Thanks @nrolland!

**Comment by tetsuzawa** [comment]
Hi!
I'm not not familiar with HomeBrew formula, but I want to ask about it.
Is it necessary to rewrite hash of bottle when updating the version?

https://github.com/nrolland/homebrew-core/blob/46c9516edf810dc1f6ba3a4c8677780401e1362e/Formula/portaudio.rb#L12-L15

Thank you.

**Comment by nrolland** [comment]
I am not familiar with it either. As per [their documentation](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request)

> Make your changes. For formulae, use brew edit or your favourite text editor, following all the guidelines in the Formula Cookbook.
> If there’s a `bottle do` block in the formula, don’t remove or change it; we’ll update it when we pull your PR.

The hash of your formula is computed by either `brew create`,  or, in the case of a simple version bump, by the invocation of `brew bump-formula-pr`, from the input you give. you should look at `brew bump-formula-pr --help` to know what to give to this command.

I think they update those hash upon successful "bottling" (aka compilation). the reasoning being, I guess, that if I and they compiled against the same version of the dependencies, it should succeed equally (with additional reliablity/security benefits)

**Comment by nrolland** [comment]
From https://docs.brew.sh/Bottles

> Bottles are created using the Brew Test Bot, usually when people submit pull requests to Homebrew. The bottle do block is updated by maintainers when they merge a pull request. For the Homebrew organisations’ taps they are uploaded to and downloaded from GitHub Packages.

**Pull request closed without merging**
