### PR TITLE
vale 2.3.0

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
Can you offer any input on these errors @jdkato ? I've been looking into them all evening, and I am stumped. There's a test that's supposed to run during `brew test vale` but it doesn't trigger, and thus the test fails. 

I tried all sorts of things locally, including the example here - https://docs.errata.ai/vale/styles#capitalization

And it never triggers… Did something change in config 2.3?

This part down - https://github.com/Homebrew/homebrew-core/blob/ac1921cf9fb8e61f6ee72ef47acf733aac5f6140/Formula/vale.rb#L22

**Comment by jdkato** [comment]
This is a regression related to the new `Vocab` feature in v2.3.0. I'll push a fix ASAP.

**Comment by jdkato** [comment]
@ChrisChinchilla: This should be fixed in [`v2.3.1`](https://github.com/errata-ai/vale/releases/tag/v2.3.1), sorry for the hassle.

**Comment by dtrodrigues** [comment]
Thanks for the quick fix @jdkato! I've opened a new PR for 2.3.1: https://github.com/Homebrew/homebrew-core/pull/59449

**Comment by dtrodrigues** [comment]
And thanks for opening your first PR in HomeBrew @ChrisChinchilla!

**Pull request closed without merging**
