### PR TITLE
youtube-dl 2017.05.14

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
:tv:

**Comment by zmwangx** [comment]
```
             ......................................................             
    .',::clloddodddoddddddddddddddddddddddddddddddddddddddddddddddooolcc;,'.    
  .coxOOOOkkxxxdddddddddddddxxxxxxkkkkkkkkkkkkxxxxxxxddddddddddddxxxkkOOkkxdl.  
 .ooxxolc:;;,,,,;:cllllllccc:::;;;;,,,,,,,,,,;;;;:::cccclllllc:;,,,,;;:cloxkol. 
 ,ddxc:;''..':lddoc;,'......                        .......,;coddl:'..'',:cxdd, 
 ,oxd:;'..,okkdc;,'...........                  .............',:ldkko;..';:ddd: 
 ;oxd:,''o0Oxo:;,''.......................................''',,;:ldk00o'.,:oxdc 
 :oxo:,,kKOxoc;;,,''''''''........................'''''',,,;;;::cloxk0Kk;,:oxdc 
 cdxo:,xX0kdl::;;;,,,,,,,,,''''''''''''''''''''',,,,,,;;;;:::ccllodxkOKXk,:oxdc 
 ldxo:lKKOxdlcc:::::;;;;;;;;;,,,,,,,,,,,,,,,,;;;;;;;;::::cccclloodxkkO0KXo:oxoc 
 lodo:xXKOkdolllcccccc:::::::::::::::::::::::::::::ccccclllloooddxxkO00KXk:oxol 
 lddo:OXKOkxddoolllllllllccccccccccccccccccccclllllllllooooodddxxxkOO0KKX0coxol 
 ldxo:0XK0OkxxddddooooooooooooooooooooooooooooooooooddddddddxxxxkkOO00KKX0clxdc 
 coxl:OXKK0OkkxxxxxxxxddddddddddddddddddddddxxxxxxxxxxxxxxxxxkkkkOO00KKXXO:lxoc 
 coxl;xXXKK0OOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOO00KKKXXx;lxol 
 cdxl;cKXXKK000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000KKKXXKc;lxol 
 ldxl;'dXXXXKKK00000000000000000000000000000000000000000000000000KKKXXXXd,;cxdc 
 :dxl;''dXXXXXKKKKKKKK0000000000000000000000000000000000KKKKKKKKKXXXXXXd'';cddc 
 ;dxl;'.'cOXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXOc'.';lddc 
 ;dxo,'...'ckKXXXXXXXXXXXXXXXXXKKKKKXXXXKKKKXXXXXXXXXXXXXXXXXXXXXXKkc'...',oxd: 
 ;ddd;,'.....,coxO0000000000000KKKKKKKKKKKKKKKKKK0000000000000Oxoc,.....',,ddd: 
 ,dodc''..'''...'',:cloddxxkkkkOOOOOOOOOOOOOOOOOOOkkkxxddolc:,''...''''.''cddx; 
 ,doollc:::;;;;,;;;,,;;;;;;;::cccccccccllllcccccc:::;;;;;;;,,,;;,;;;;::ccllodx; 
 ,ddO000OxolloxkOOOOOOOkOOkkOOOOOOkOOOkOOOOOOOOOOkkkOOOkkOOOOO0OkxolloxO000Odd; 
 ;dkK0kc,.. ...'cdkkkkkxxkkkkkxxxxxxxxxxxxxxxxxxxxkkkkxxkkxxkOdc,... ..'ck0Kko; 
 ;dk0Oo,'.'..''.,cdxdxxddxxkxxxxxxxxxxxxxxxxxxxxxxkkkkkkxdddxdc;.....'.''lk0kd; 
 'xx0Oko;''''',;ldxxxxkxxkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOxdxxdl;,''''';okkOxx, 
  cxxxxkkxdoodxkOkxkxxdxxkkkkkkkOOOOOOOOOOOOOOOOOkkkkkkkkkkxkxkOkxdoodxkkxxxxc  
   ..'',,;kkOOOd;;::;;;;;::::::::::::::::::::::::::::;;;;;;;;;;;dOkkkk:,,''..   
          ';::;.                                                .;::;'          
```

**Comment by ilovezfs** [comment]
Oooo … is it 4K?

**Comment by zmwangx** [comment]
It's 72p.

**Comment by ilovezfs** [comment]
Good enough!

**Comment by zmwangx** [comment]
RAM efficiency is amazing on this thing.

**Pull request merged**
