### PR TITLE
tree-sitter 0.20.8

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by ZhongRuoyu — COMMENTED** [review]
Not the latest release on GitHub yet: https://github.com/tree-sitter/tree-sitter/releases

**Comment by clason** [comment]
But it's the latest tag, that's enough for homebrew: https://github.com/tree-sitter/tree-sitter/tags

(Release just means a tag with release artifacts.)

**Comment by SMillerDev** [comment]
@clason if upstream uses releases and doesn't mark this as one, that's a clear indication that it's not a supported release yet and therefor not good enough for Homebrew.

**Comment by chenrui333** [comment]
raise an upstream issue to ask if that is an intended release, https://github.com/tree-sitter/tree-sitter/issues/2125

**Comment by chenrui333** [comment]
#127501

**Pull request closed without merging**
