### PR TITLE
aurora-cli 0.21.0

### PR DESCRIPTION
**Pull request by thinker0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by thinker0** [comment]
* Fail mojave_testing ?

**Comment by fxcoudert** [comment]
```
Successfully installed Markdown-2.1.1 Pygments-1.4 ansicolors-1.0.2 asn1crypto-0.24.0 certifi-2018.8.24 cffi-1.11.1 chardet-3.0.4 contextlib2-0.5.5 cryptography-2.3.1 docutils-0.12 enum34-1.1.6 fasteners-0.14.1 faulthandler-2.6 futures-3.0.5 idna-2.6 ipaddress-1.0.22 monotonic-1.5 packaging-16.8 pantsbuild.pants-1.6.0 pathspec-0.5.0 pex-1.3.2 psutil-4.3.0 pycparser-2.18 pyopenssl-17.3.0 pyparsing-2.2.0 pystache-0.5.3 pywatchman-1.4.1 requests-2.18.4 scandir-1.2 setproctitle-1.1.10 setuptools-30.0.0 six-1.11.0 subprocess32-3.2.7 twitter.common.collections-0.3.9 twitter.common.confluence-0.3.9 twitter.common.dirutil-0.3.9 twitter.common.lang-0.3.9 twitter.common.log-0.3.9 twitter.common.options-0.3.9 urllib3-1.22 wheel-0.29.0
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

07:43:55 00:00 [main]
               (To run a reporting server: ./pants server)
07:44:25 00:30   [setup]
07:44:26 00:31     [parse]fatal: not a git repository (or any of the parent directories): .git

               Executing tasks in goals: gen -> pyprep -> binary
07:44:27 00:32   [gen]
07:44:27 00:32     [thrift-py]
07:44:27 00:32       [cache]    
                   No cached artifacts for 4 targets.
                   Invalidated 4 targets.
07:44:27 00:32       [execute]
FAILURE: Unable to find binary thrift version 0.10.0. Update --binaries-path-by-id to find binaries for (u'darwin', u'18')


07:44:27 00:32   [complete]
               FAILURE
```

**Comment by thinker0** [comment]
retest this please

**Comment by thinker0** [comment]
@fxcoudert Thanks ^__________^;

**Comment by fxcoudert** [comment]
Thanks @thinker0, it is now merged!

**Pull request closed without merging**
