### PR TITLE
cpanminus 1.9003

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
Looks like `cpanm` doesn't exist in the tarball any more 👀

**Comment by ilovezfs** [comment]
Looking inside the tarball is cheating.

**Comment by DomT4** [comment]
😈

**Comment by chdiza** [comment]
The latest official version of `cpanminus` is 1.7042, unless I'm missing something.  It's the most recent thing in the `devel` branch (the main branch for that repo), and is the version that gets installed by following the README installation instructions.  I think the 1.9x series under "releases" are just tests.

**Comment by apjanke** [comment]
That's my reading of http://search.cpan.org/~miyagawa/App-cpanminus-1.7042/lib/App/cpanminus.pm (search results on CPAN for "cpanminus") too. This PR should probably be dropped as a spurious release.

**Comment by DomT4** [comment]
Agree with the above two comments. Sorry ILZ 😢.

**Comment by ilovezfs** [comment]
looks like this will need a custom livecheckable https://github.com/youtux/homebrew-livecheck/tree/master/Livecheckables

**Pull request closed without merging**
