### PR TITLE
sfml 2.5.1

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
Hold on this, additional upstream changes have rendered some patches/replaces here unnecessary. Fixing now.

**Comment by alebcay** [comment]
Build is failing (locally and on CI) with

```
CMake Error at cmake_install.cmake:120 (file):
  file cannot create directory: /usr/local/share/SFML.  Maybe need
  administrative privileges.
```

Even though we're passing the correct `CMAKE_INSTALL_PREFIX` in `std_cmake_args`, it seems to want to touch stuff outside of the install prefix.

**Comment by fxcoudert** [comment]
Yeah: see https://github.com/SFML/SFML/issues/1496 and https://www.sfml-dev.org/tutorials/2.5/compile-with-cmake.php

**Comment by alebcay** [comment]
Ah, I see. You can leave it to me to avoid reading documentation. Also, I noticed that the CMake config files have moved location from `share/SFML/cmake` to `lib/cmake`, not sure if that's something we should try to fix on our end or if we should just leave it be.

**Comment by alebcay** [comment]
Regarding test failures, it appears that `csfml` depends explicitly on SFML 2.4 (e.g. searching for `libsfml-graphics.2.4`). This should hopefully be fixed with bumping `csfml` to 2.5.

**Comment by fxcoudert** [comment]
Please update the two formulas in a single PR: one PR, two commits. That way they will be tested together, and merged together.

**Comment by alebcay** [comment]
@BrewTestBot test this please

**Comment by alebcay** [comment]
The Sierra build failure is identical to the one mentioned in https://github.com/Homebrew/legacy-homebrew/issues/47668, so I figure the issue is something to do with Xcode vs CLT headers both being present and the wrong one getting picked up.

**Comment by fxcoudert** [comment]
You could try:

```
ENV["SDKROOT"] = MacOS.sdk_path if MacOS.version == :sierra
```

or

```
ENV.delete("SDKROOT") if MacOS.version == :sierra
```

**Comment by alebcay** [comment]
Well, that seemed to fix it.

**Comment by fxcoudert** [comment]
https://i.gifer.com/QUjL.gif

**Pull request closed without merging**
