### PR TITLE
skylighting 0.8.5 (new formula)

### PR DESCRIPTION
**Pull request by pthariensflame**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Completes the work begun with #55874, although the two could be merged in either order.  `skylighting` is the official replacement for `highlighting-kate`.

### CODE REVIEW

**Comment by pthariensflame** [comment]
Can someone help me figure out what's gone wrong here?  :(

**Comment by bayandin** [comment]
```
Error: skylighting: failed
An exception occurred within a child process:
  NameError: uninitialized constant #<Class:0x00007f988a907908>::DATA
```

It seems you're not allowed to use DATA in a test block.

**Comment by pthariensflame** [comment]
That’s really unfortunate.

**Comment by pthariensflame** [comment]
@bayandin @alebcay Seems to be good now!

**Review by SMillerDev — APPROVED** [review]
Thanks @pthariensflame ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
