### PR TITLE
john: add share symlink ~can't add test block~

### LINKED ISSUE #47164: john: fopen: /usr/local/share/john/john.conf: No such file or directory
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install `john` formula, and run it

## What happened (include command output)

I run `john` command, and see this:

<details>
  <summary>Command output</summary>
  <pre>
$ john
fopen: /usr/local/share/john/john.conf: No such file or directory
  </pre>
</details>

## What you expected to happen

No error, and john runs like this:

```
$ john
John the Ripper password cracker, version 1.9.0
Copyright (c) 1996-2019 by Solar Designer
```

## Step-by-step reproduction instructions (by running `brew install` commands)

Just run:

```shell
brew install john
```
It download a bottle and installed as normal. And then:

```
$ john
fopen: /usr/local/share/john/john.conf: No such file or directory
```

As i checked it, `/usr/local/share/john` not even exist. And this is how i fix it manually:

```shell
cd /usr/local/share
ln -s /usr/local/Cellar/john/1.9.0/libexec john
cd john
cp john.ini john.conf
```

and now it seem works.

My versions:

```
$ brew config
HOMEBREW_VERSION: 2.1.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3aa7624284c43180a3f3a71aeaa9263092868e12
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 992e817c65f5ab22df5d7f1eb08e38924eeafd9a
Core tap last commit: 62 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_202
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
CLT headers: 10.3.0.0.1.1562985497
```

Discussion before at discourse.brew.sh: [https://discourse.brew.sh/t/john-fopen-usr-local-share-john-john-conf-no-such-file-or-directory-is-it-reproducible/6328](https://discourse.brew.sh/t/john-fopen-usr-local-share-john-john-conf-no-such-file-or-directory-is-it-reproducible/6328)

### PR DESCRIPTION
**Pull request by Amar1729**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes #47164
- adds a symlink `/usr/local/share/john -> PREFIX/john/libexec`
- removes the rename of `john.conf` to `john.ini` (code expects `john.conf`)

`john` code seems to default to `john.conf`:
- https://github.com/magnumripper/JohnTheRipper/search?utf8=%E2%9C%93&q=conf&type=
- https://github.com/magnumripper/JohnTheRipper/blob/c586a678f3ad7c92f4296957c24eba6ffb95d4b3/run/netntlm.pl#L198

Also, added a test block that runs john's internal benchmarks.

### CODE REVIEW

**Comment by chenrui333** [comment]
==> brew test john --verbose
==> FAILED
Testing john
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200128-89834-yiqg2x.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/john.rb --verbose
==> john --test
mkdir: /Users/brew/.john: Operation not permitted
Error: john: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.

**Comment by Amar1729** [comment]
Weird. Not sure how to get `john` to use a location other than `/Users/brew` as `$HOME`, but that's the reason the test is currently failing ...

**Comment by Amar1729** [comment]
I removed the `test` block because i think any call to `john` will attempt to create `JOHN_PRIVATE_HOME`, which is hardcoded to `~/.john`. It doesn't seem to be possible to change this by setting `$HOME` or `$JOHN` in the test block before running it.

**Comment by fxcoudert** [comment]
We really need a test block. `john` has had issues in the past which we don't necessarily see because of lack of test.

**Pull request closed without merging**
