### PR TITLE
sonarqube-lts: remove `bottle :unneeded`

### PR DESCRIPTION
**Pull request by carlocab**
See #75943.

### CODE REVIEW

**Comment by carlocab** [comment]
```
❯ sha256sum *.tar.gz
a7f098abd01364b122321f3d499eab3cd5f7c7937840458b69aa0c23b258d29c  sonarqube-lts--7.9.6.arm64_big_sur.bottle.tar.gz
bc64eb4fa05eed433a19d2c46c75e8c8724863b735b97498e011211927151a32  sonarqube-lts--7.9.6.big_sur.bottle.tar.gz
bc64eb4fa05eed433a19d2c46c75e8c8724863b735b97498e011211927151a32  sonarqube-lts--7.9.6.catalina.bottle.tar.gz
5e2da8f76ac6256cb6e631816bb6b1aed82ec5921b5f1cc786548e58d4012dfe  sonarqube-lts--7.9.6.mojave.bottle.tar.gz
```

**Comment by samford** [comment]
For what it's worth, [version 8.9 is also the new LTS](https://www.sonarqube.org/sonarqube-8-9-lts/). Not sure if we want to handle the version bump and removing `bottle :unneeded` in one PR but thought I might mention it.

**Comment by carlocab** [comment]
Yes, handling it in the same PR will just delay the version bump. We can do that in a separate PR.

**Review by SMillerDev — DISMISSED** [review]

**Comment by chenrui333** [comment]
```
cb7b43a7396102cfa85ab32e9647bf04ae88dfb5855104d52e664f71338cc9fc  sonarqube-lts--7.9.6.arm64_big_sur.bottle.1.tar.gz
975d8370e016c2fd615699e67787c5ea2a00cd202ed6faa259964461a57384c5  sonarqube-lts--7.9.6.big_sur.bottle.1.tar.gz
975d8370e016c2fd615699e67787c5ea2a00cd202ed6faa259964461a57384c5  sonarqube-lts--7.9.6.catalina.bottle.1.tar.gz
b4ffb6a083fc4eb59d55b9fc5ddaa95dce91408a6439f905c5d92a9c44be3b20  sonarqube-lts--7.9.6.mojave.bottle.1.tar.gz
```

**Comment by MikeMcQuaid** [comment]
@carlocab and others: I think it's good to fix this stuff up but I don't think it should block these PRs. We can make these fixes after stuff is bottled.

**Pull request closed without merging**
