### PR TITLE
flac: use brewed curl for url

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
This is a test PR for the new download strategy using brewed curl. Do not merge as this needs a new brew release.
I'll open a companion PR for test-bot as we might need to install brewed curl.

**Comment by iMichka** [comment]
Companion PR: https://github.com/Homebrew/brew/issues/11705

**Comment by iMichka** [comment]
Looks like I need to implement the same logic for the `homepage` url :(

**Comment by SMillerDev** [comment]
Maybe just pass it through archive.org for now? With a comment to switch it back when macOS allows TLS 1.3?

**Comment by iMichka** [comment]
Here is a fix for the homepage check: https://github.com/Homebrew/brew/pull/11896

**Comment by iMichka** [comment]
All green. We need a new brew release before merging this though.

**Comment by iMichka** [comment]
https://github.com/Homebrew/homebrew-core/actions/runs/1156519853

**Pull request merged**
