### PR TITLE
tsduck 3.30-2710

### PR DESCRIPTION
**Pull request by lelegard**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
```
  ==> make NOGITHUB=1 NOTEST=1 install SYSPREFIX=/usr/local/Cellar/tsduck/3.30-2710
  install -d -m 755 /usr/local/Cellar/tsduck/3.30-2710/lib
  rm -rf /usr/local/Cellar/tsduck/3.30-2710/include/tsduck
  install -d -m 755 /usr/local/Cellar/tsduck/3.30-2710/lib /usr/local/Cellar/tsduck/3.30-2710/include/tsduck
  install: mkdir /usr/local/Cellar/tsduck/3.30-2710/lib: File exists
  make[2]: *** [install-devel] Error 71
```

**Comment by lelegard** [comment]
Hi @carlocab 

~~~
  install -d -m 755 /usr/local/Cellar/tsduck/3.30-2710/lib /usr/local/Cellar/tsduck/3.30-2710/include/tsduck
  install: mkdir /usr/local/Cellar/tsduck/3.30-2710/lib: File exists
~~~

How is this possible that `install -d` fails on an existing directory? 

1. `install -d <some-dir>` is supposed to do nothing if the directory exists. In fact this is a common pattern in most installation scripts.
2. In the same set of tasks, the "12-arm64" task completes successfully, running the same steps while the task "12" fails.
3. On my Intel Mac running macOS 12, `brew install --HEAD tsduck` completes successfully.
4. On an Ubuntu VM, the same command completes successfully in a linuxbrew environment 
5. On all Linux distros, the same native make operation also completes successfully.
6. These parts of the `make install` process did not change since the previous version.

The first reason is sufficient to say that this diagnosis is not normal. There is something weird on the build system.

**Comment by lelegard** [comment]
Hi @carlocab 

Any idea why the second run succeeded while "12" failed in the first one?
Anything I should worry about?

**Comment by Bo98** [comment]
I suspect it's parallelism issue with the two `install` command running at the same time. The nature of such issues would mean it won't happen every time.

The check for whether the directory exists and the mkdir itself isn't one atomic operation: https://github.com/apple-oss-distributions/file_cmds/blob/33b70023633480b68256b8cbb2dd8b0533f70bdf/install/xinstall.c#L786-L788

**Comment by lelegard** [comment]
Thanks @Bo98 

> I suspect it's parallelism issue with the two `install` commands running at the same time.

I have opened a related question here: https://github.com/Homebrew/discussions/discussions/3076

**Pull request closed without merging**
