### PR TITLE
pipenv 11.7.1

### PR DESCRIPTION
**Pull request by amancevice**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Submitted for consideration: that project releases too often, and we want to limit the number of updates we consider.

snap

**Comment by ilovezfs** [comment]
@fxcoudert based on https://github.com/Homebrew/homebrew-core/issues/22429 we should not throttle this one unless it really gets out of control.

**Comment by amancevice** [comment]
Agreed its releases are rapid-fire, but the current 11.6.1 build was not working at all for me.

**Comment by ilovezfs** [comment]
And now we're at 11.6.9

Yeah, we may need a not-more-than-once-per-day rule here.

**Comment by amancevice** [comment]
madness

**Comment by commitay** [comment]
> the current 11.6.1 build was not working at all for me.

This is not uncommon with `pipenv` updates, sometimes the test will catch it and sometimes not. I'm looking at improving the test.

**Comment by commitay** [comment]
Thanks @amancevice!

**Comment by commitay** [comment]
> the current 11.6.1 build was not working at all for me

@amancevice Can you please provide some details as to how it was not working?

**Comment by amancevice** [comment]
It looks like I was experiencing this issue: https://github.com/pypa/pipenv/issues/1717

I powered up for the morning and ran `brew update`, saw that pipenv had an upgrade, ran `brew upgrade` and was then pretty much unable to `pipenv install` anything (namely `boto3`) without the lock step failing.

I saw in the (history)[https://github.com/pypa/pipenv/blob/master/HISTORY.txt) that pipenv had been upgraded to 11.6.4 with these logs:

```
11.6.4:
 - Fix a bug.
11.6.3:
 - Depend on certifi.
11.6.2:
 - Properly vendor certifi.
 - Better support for --extra-index-url for private PyPI servers.
 - Bug fixes.
```

Seemed like a pretty good reason to see SSLError messages, so I thought I'd be a champ and update the formula, which seemed to resolve the issue, and open this PR.

**Comment by kennethreitz** [comment]
We've had some integration issues since trying to support the latest VS Code release — basically, and have been seeing a lot of adoption and lots of strange edge cases brought up, responded to with quick patch releases.

The releases will slow down as soon as possible. I absolutely hate this — just seeking stability.

**Comment by kennethreitz** [comment]
e.g. "just trying to make everyone happy" over here :)

**Comment by kennethreitz** [comment]
An impossible task, of course.

**Comment by ilovezfs** [comment]
@kennethreitz no worries. Thanks for the details. That helps.

**Pull request closed without merging**
