### PR TITLE
reminiscence 0.5.1

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
No license information could be found in the source tarball. Source files from earlier versions (in particular, 0.2.2 and earlier) suggest that it's GPL-3.0-or-later:

```
/* REminiscence - Flashback interpreter
 * Copyright (C) 2005-2015 Gregory Montoir
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
```

References:
- http://cyxdown.free.fr/reminiscence/REminiscence-0.2.2.tar.bz2
- https://metadata.ftp-master.debian.org/changelogs//contrib/r/reminiscence/reminiscence_0.2.1-2_copyright

**Comment by SMillerDev** [comment]
I'd go with `:cannot_represent` then

**Comment by ZhongRuoyu** [comment]
Does `:cannot_represent` fit here? I think `:cannot_represent` is used for the non-standard ones. But technically, it's not that it ["cannot be represented"](https://docs.brew.sh/License-Guidelines#specifying-a-license), but rather, it can't be found anywhere.

**Comment by SMillerDev** [comment]
I think it's better than making up a license based on earlier releases. Alternatively, we can just leave it missing.
FreeBSD doesn't have a license for it either and Ubuntu says it's GPL3, but ships 0.2.1.

**Comment by ZhongRuoyu** [comment]
Mmm. Let's keep it as is, maybe.

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
