### PR TITLE
openconnect: make before make install

### PR DESCRIPTION
**Pull request by toonetown**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Due to the way the makefiles are set up, the `make` command has to be run prior to running `make install`

### CODE REVIEW

**Comment by zmwangx** [comment]
Please explain which components are not built when `make` isn't run first. It has been that way for years. I find it hard to believe any component is missing, when we've had thousands of install events in just a few months without a single complaint.

**Comment by toonetown** [comment]
I believe that this is due to a change that has been made to the upstream code.  For example, I am able to run `brew install --build-from-source openconnect` and it will build and install version 7.07 just fine, however this is the error that I get when running `brew install --HEAD openconnect`:

```
2016-09-22 14:10:11 -0600

make
install

Making install in tests
make[1]: *** No rule to make target `../libopenconnect.la', needed by `serverhash'.  Stop.
make[1]: *** Waiting for unfinished jobs....
  CC       lzstest.o
  CC       seqtest.o
  CC       serverhash.o
make: *** [install-recursive] Error 1
```

It looks like something might have changed in their makefiles where the tests are being built first, but they are depending on the library being built.

**Comment by zmwangx** [comment]
That looks like a regression that should be reported to upstream first.

**Comment by toonetown** [comment]
> That looks like a regression that should be reported to upstream first.

Done - I reported it to them.

**Comment by dwmw2** [comment]
Fixed by http://git.infradead.org/users/dwmw2/openconnect.git/commitdiff/2c329c9b6445306d2135192ce42bf48698fc0a33

Thanks.

**Comment by toonetown** [comment]
> Fixed by http://git.infradead.org/users/dwmw2/openconnect.git/commitdiff/2c329c9b6445306d2135192ce42bf48698fc0a33

Wow - super fast turnaround!  Closing this in favor of that fix.  (I have verified that it works).

**Pull request closed without merging**
