### PR TITLE
gpgme: add Qt bindings

### PR DESCRIPTION
**Pull request by sl1pkn07**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

https://github.com/Homebrew/homebrew-core/issues/39173

superseeed https://github.com/Homebrew/homebrew-core/pull/39197

### CODE REVIEW

**Comment by fxcoudert** [comment]
Well it is definitely linking against Qt:

```
        Broken dependencies:
  /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore (qt)
```

**Comment by sl1pkn07** [comment]
with what? with the core gpgme or with the qt bindings?

if is last statement, can be fixed if add qt dependency into the program which needs gpgme qt bindings as dependency

**Comment by fxcoudert** [comment]
Thanks @sl1pkn07, merging

**Comment by robertleeblairjr** [comment]
I know that this was closed and accepted to require QT but I believe it should have been optional provided the parameter passed of disabling the GPG test. If the parameter '--disable-gpg-test' isn't passed, then GnuPG is required if QT is installed. So, kind of a catch-22 is created by the test suite. Any way that this can be resubmitted for removing the QT dependency? Of course, some correction to adding in this parameter would need to be made to avoid this same conflict in the future.

**Comment by sl1pkn07** [comment]
can you explain better (with console output) ehat is the problem?

greetings

**Comment by robertleeblairjr** [comment]
I have little experience in building these suites. But, according to my readings of building these packages from another project, then it requires passing a parameter to disable the test suite. Because the test suite has additional requirements which aren't satisfied without having additional dependencies. So, you're left with either installing all of those dependencies for the test suite during the make procedure. One of the tests requires GnuPG 2.2.17 which is only required if QT or SWIG are installed. But, GnuPG 2.2.17 is optional if QT or SWIG aren't installed for the test. So, from the links below for a more pure GPGME package, then QT is not required but optional. Of course, this is on the FreeBSD platform which is referencing creating linux distros from scratch.

[ftp://ftp7.freebsd.org/sites/www.linuxfromscratch.org/blfs/view/systemd/postlfs/gpgme.html](url)

[ftp://ftp7.freebsd.org/sites/www.linuxfromscratch.org/blfs/view/systemd/postlfs/gnupg.html](url)

**Comment by robertleeblairjr** [comment]
BTW. Check the other reference link for the PR #41780 GnuPG 2.2.17.

**Comment by sl1pkn07** [comment]
if you mean needs have set `'--disable-gpg-test` in the make rules, then is nothing to do in this PR. this PR only adds gpgme Qt bindings

**Comment by robertleeblairjr** [comment]
To build GPGME only has one requirement. To GPG test has multiple requirements. So, QT wasn't ever required to build but optional for tests. This was discussed previously in other PRs that are closed.

**Comment by sl1pkn07** [comment]
as you say, you talk about gpgme test, not gpgme Qt bindings, nothing to do in this PR, if you want add `--disable-gpg-test`, please fill a PR with that change

**Comment by robertleeblairjr** [comment]
What are the requirements for building GPGME only?
What are the requirements for testing the GPGME build only?

**Comment by robertleeblairjr** [comment]
The requirements for installing GPGME, which Travis does during its testing of the PR, requires --disable-gpg-test for GPGME. Otherwise, it will fail with not having met the requirements of QT bindings. The QT bindings aren't required for building/installing GPGME. However, this is my understanding of reading GPGME make/build instructions which I provided a link to in a previous reply. Can you help me to understand why QT bindings are required and not optional? Because, the build instructions from other sources contradicts what you're saying.

**Comment by sl1pkn07** [comment]
you sure? you test build gpgme Qt bindings without Qt installed ? (see the main comment in https://github.com/Homebrew/homebrew-core/issues/39173). i'm invite you to try it

**Comment by robertleeblairjr** [comment]
That doesn't show requirements for GPGME. It's a PR you made because of another binary package having problems of requiring QT bindings with GPGME. Every other source I've looked for states that QT is optional for GPGME. Arch and/or KMyMoney aren't the de facto for requiring it. Can you provide me a source of building/installing GPGME standalone that requires QT?
Thank you.

**Comment by sl1pkn07** [comment]
Is a optional

~~~
depends_on "qt" => [:build, :test]
~~~

Qt only need for build and for test

~~~
    (testpath/"CMakeLists.txt").write("find_package(QGpgme REQUIRED)")
    system "cmake", ".", "-Wno-dev"
~~~

**Comment by robertleeblairjr** [comment]
Does GPGME require GPG for tests?
Does GPGME build/install require QT or only if configured to include QT?
According to GPGME install and readme; it does not require QT for a generic build.

[https://github.com/gpg/gpgme/blob/master/README](url)

[https://github.com/gpg/gpgme/blob/master/INSTALL](url)

**Comment by sl1pkn07** [comment]
python and python2 neither

**Comment by robertleeblairjr** [comment]
I guess have a dev to look at it. They would know the policy of brew on macOS quite well. But, according to every source I've found QT isn't required and you've not provided any source to state that it's required other than referring to one program for KDE and Arch builds. Perhaps, the other build dependencies aren't required either and exceptions were made because they didn't break other packages or interfere with them for maintaining. However, the change that was pushed for GPGME to include QT as a dependency broke the GPG formula for build/tests.

**Comment by sl1pkn07** [comment]
https://www.archlinux.org/packages/core/x86_64/qgpgme/

https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gpgme

**Comment by robertleeblairjr** [comment]
Those are for Arch with KDE which has requirements of QT for specific packages installed. This isn't Arch, KDE, or even related to those build requirements and dependencies. It's also for "**Q**GPGME" and not "GPGME".

**Comment by sl1pkn07** [comment]
Qgpgme is part of gpgme, as you can see in the pkgbuild

**Comment by robertleeblairjr** [comment]
@SMillerDev Can you take a look at whether GPGME that's being maintained by brew requires QT bindings or it's optional? Everything that I've found related to it states optional, even though, there are other dependencies which have been made as exceptions, as well. If QT is made as an exception, then the GPG PR would require some assistance with updating. Thanks.

**Comment by robertleeblairjr** [comment]
QGPGME is just for QT bindings but it's not a requirement to build the base package GPGME. Can you provide me a source that states GPGME base package requires QT bindings? I've look quite a while and can only find the references of it being optional.

**Comment by sl1pkn07** [comment]
python and python2 either

**Comment by robertleeblairjr** [comment]
> python and python2 either
> 
> why python and python2 yes and Qt no?
> 
> greetings

Probably because an exception was made. Who could answer this question as to why python was included as a dependency would be a developer or someone who worked on GPGME base package and encountered a problem that they added it as an exception. However, there are other dependencies which were added for specific reasons, as well. But, you've not provided any source that shows QT bindings are required for building GPGME base package. Why don't you ask brew devs and maintainers who've collaborated on it will make an exception? But, it looks like it was added based upon the decision by one person. If it's fine that QT is a dependency now because of other packages, then an exception would need to be made for GPG now during build/test by Travis because that PR has been open for over 2 weeks.

**Comment by sl1pkn07** [comment]
python/python2 is only a bindings, like Qt, no need for other purpose in gpgme

python and python2 is added because is need by other packages, like this PR adds

**Comment by robertleeblairjr** [comment]
>On Mon 2016-04-11 13:17:49 -0400, Andre Heinecke wrote:

>   I've integrated the C++ and Qt Libraries for GpgME from the KDE Initiative as 
>   language provider into GpgME in the branch "gpgmepp".
>
>   I think that branch is now ready for a merge into master.
>
>   Build can be controlled by the --enable-languages configure option. So
>
>   --enable-languages=no
>
>   Will build only the C library.
>
>   GpgMEpp is a C++ wrapper / binding around GpgME closely follows the API of 
>   GpgME itself. (Requires C++11)
>
>   QGpgME is more of a "Qt library" to work with GpgMEpp then a binding. Has a 
>   Job based Qt API that takes Qt data structures as gpgme data type providers. 
>   (Requires Qt5 and GpgMEpp)
>
>   The API is mostly compatible with KF5GpgMEpp and KF5QGpgME which
>   was released as part of KDE-Applications. Small changes might be caused by the 
>   removal of boost classes from public API as I've ported both libraries away 
>   from boost to c++11.
>
>   My current plan is to no longer release KF5GpgMEpp with KDE-Applications 16.08 
>   and depend on the libraries from GpgME for that release.

**Comment by sl1pkn07** [comment]
>2016

**Comment by robertleeblairjr** [comment]
> python/python2 is only a bindings, like Qt, no need for other purpose in gpgme
> 
> python and python2 is added because is need by other packages, like this PR adds

Your argument is because of exceptions that were made in the past to add in those dependencies which weren't required. So, there was a reason those were added-in but it still doesn't negate the fact that they weren't required for the base package build. Thus, the argument you're making is QT needs to be made a dependency because of one package in the tap and those conflicts which are occurring would need resolution/exceptions, as well. I wouldn't know the answer to why python was added. You would need to ask someone with knowledge of why the exceptions were made.

**Comment by robertleeblairjr** [comment]
> > 2016

So? it was provided as evidence that QT isn't required for GPGME but is an optional package because of KDE and its applications.

**Comment by sl1pkn07** [comment]
Qt is necesary for build the Qt bindings, no more, no less, as python/python2 is necessary for build the python bindings.

if you have problems with Qt bindings, you have the same problem with the python bindings

**Comment by robertleeblairjr** [comment]
GPGME comes with bindings for Lisp, C++, QT, Python2, and Python3. Perhaps, QT wasn't added since it is a framework built on C++. But, those bindings aren't required for the base package. However, the base package itself is probably quite useless without some bindings. For the brew maintained formula, then exceptions were made for bindings for whatever reasons that I can't answer but someone who is a dev, maintainer, etc. could. Since, an exception was made for that dependency, then perhaps they would make it for QT. But, they also may have had to finagle other formula, such as GPG when it was built. It's strange that QT wasn't added but it doesn't mean that this topic hasn't came up before and was addressed with why it wasn't added.

**Pull request closed without merging**
