### PR TITLE
libowfat 0.33

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by mistydemeo — COMMENTED** [review]
Looks like I'm the author of the patch that no longer applies I'll review.

**Comment by mistydemeo** [comment]
The patch has been applied in this new release; you can remove it entirely.

**Comment by chenrui333** [comment]
```
  ./byte.h:14:10: fatal error: 'libowfat/compiler.h' file not found
  #include <libowfat/compiler.h>
           ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by chenrui333** [comment]
looks like header file is missing in the artifact

**Comment by chenrui333** [comment]
@mistydemeo got some time to fix the build issue, can you take a look at this new PR, #125418. Thanks!

**Pull request closed without merging**
