### PR TITLE
mpv 0.28.2

### PR DESCRIPTION
**Pull request by schorsch888**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
This needs the next version of ffmpeg, which isn't released yet. Thanks, though

**Comment by XiangChen888** [comment]
Ok, I see. Thanks for information. But there is a bug in mpv version 0.27.2. For details you could read https://github.com/mpv-player/mpv/issues/4926. This bug was fixed in newer version. Perhaps some better solutions?

**Comment by ilovezfs** [comment]
@XiangChen888 you can `brew install --HEAD ffmpeg && brew install --HEAD mpv` and see how that goes.

**Comment by XiangChen888** [comment]
Thanks!

**Pull request closed without merging**
