### PR TITLE
ansible-lint 5.0.0

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
This version seems to launch `ansible` in a subprocess. The only way I found to get the test to work is to depend on the `ansible` formula while keeping the `ansible-base` resource.

**Comment by carlocab** [comment]
Maybe it could be a test dependency? Also, won't `ansible-base` get removed with another `bump-formula-pr`?

**Comment by Moisan** [comment]
> Maybe it could be a test dependency?

It cannot be a test dependency because `ansible-lint` simply doesn't work on the command line without it. 

> Also, won't `ansible-base` get removed with another bump-formula-pr?

Yes it would get removed. Altough it is currently a resource in the `ansible` formula but, from what I understand of the virtualenv installations, these things are separated.

**Comment by carlocab** [comment]
Ok, fair enough on the `ansible` dependency.

Ping @Rylan12 for avoiding `ansible-base` getting removed with the next `bump-formula-pr`. Though, have you tried building it without the `ansible-base` resource? Maybe it only needs it for the `ansible` dependency.

**Comment by Moisan** [comment]
I tried building without `ansible-base` and I get the same error as before when running the test (or  `ansible-lint` on the command line): `No module named 'ansible'`.

**Comment by carlocab** [comment]
Ok, guess we have to make sure it doesn't get removed then...

**Review by carlocab — APPROVED** [review]

**Comment by Rylan12** [comment]
@carlocab @Moisan we can add `ansible-base` as an extra package for `ansible-lint` to `pypi_formula_mappings.json`.

This keeps `ansible-base`, but it also re-adds `cffi`, `cryptography`, and `pycparser` as they are dependencies of `ansible-base`.

Currently, running `brew update-python-resources` seems to change the resources significantly from what was merged in this PR. That's fine, but if we're unable to automatically update the resources correctly we should just disable resource updates for `ansible-lint` instead of continuing to open PRs that make changes we don't want. Ideally, though, we can specify an appropriate configuration in `pypi_formula_mappings.json` that would allow auto-updates to continue.

**Pull request closed without merging**
