### PR TITLE
gcc 10.1.0

### PR DESCRIPTION
**Pull request by fxcoudert**
Release notes: https://gcc.gnu.org/gcc-10/changes.html

### CODE REVIEW

**Comment by bayandin** [comment]
```
In file included from ../../../../../libstdc++-v3/src/c++17/fs_dir.cc:30:
/private/tmp/gcc-20200507-28842-210ql0/gcc-10.1.0/build/x86_64-apple-darwin18/libstdc++-v3/include/filesystem:44:10: fatal error: bits/fs_fwd.h: No such file or directory
   44 | #include <bits/fs_fwd.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```

And also

```
==> brew audit --skip-style gcc --online
==> FAILED
Error: 2 problems in 1 formula detected
gcc:
  * Formula has other versions so create a versioned alias:
      cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases
      ln -s ../Formula/gcc.rb gcc@10.1
  * Formula has invalid versioned aliases:
      gcc@9
```

**Comment by bayandin** [comment]
And fails on Catalina (most of them requires a revision bump):
```
brew audit --skip-style gcc --online
brew linkage --test abyss
brew linkage --test adios2
brew linkage --test arpack
brew linkage --test augustus
brew linkage --test cgns
brew linkage --test cp2k
brew linkage --test dungeon
brew linkage --test dynare
brew linkage --test eccodes
brew linkage --test fastme
brew linkage --test fftw
brew linkage --test gromacs
brew linkage --test hdf5
brew linkage --test hdf5@1.10
brew linkage --test hdf5@1.8
brew linkage --test ipopt
brew linkage --test json-fortran
brew linkage --test kahip
brew linkage --test kim-api
brew linkage --test lapack
brew linkage --test libxc
brew linkage --test mpich
brew linkage --test netcdf
brew linkage --test nwchem
brew linkage --test octave
brew linkage --test open-mpi
brew linkage --test openblas
brew linkage --test openfast
brew linkage --test openkim-models
brew linkage --test packmol
brew linkage --test petsc
brew linkage --test petsc-complex
brew linkage --test pgplot
brew linkage --test plplot
brew linkage --test pnetcdf
brew linkage --test qrupdate
brew linkage --test r
brew linkage --test reprepro
brew linkage --test root
brew linkage --test scalapack
brew linkage --test scipy
brew test --verbose abyss
brew test --verbose adios2
brew test --verbose arcade-learning-environment
brew test --verbose armadillo
brew test --verbose arpack
brew test --verbose astrometry-net
brew test --verbose aubio
brew test --verbose augustus
brew test --verbose biosig
brew test --verbose caffe
brew test --verbose ceres-solver
brew test --verbose cgns
brew test --verbose clp
brew test --verbose coinutils
brew test --verbose cp2k
brew test --verbose csound
brew test --verbose dungeon
brew test --verbose dynare
brew test --verbose fastme
brew test --verbose fftw
brew test --verbose gmt
brew test --verbose gmt@5
brew test --verbose gnuradio
brew test --verbose graph-tool
brew test --verbose gromacs
brew test --verbose imake
brew test --verbose ipopt
brew test --verbose json-fortran
brew test --verbose kahip
brew test --verbose lammps
brew test --verbose lapack
brew test --verbose libbi
brew test --verbose mlpack
brew test --verbose mpich
brew test --verbose netcdf
brew test --verbose numpy
brew test --verbose numpy@1.16
brew test --verbose nwchem
brew test --verbose octave
brew test --verbose open-mpi
brew test --verbose openblas
brew test --verbose opencoarrays
brew test --verbose opencv
brew test --verbose opencv@2
brew test --verbose opencv@3
brew test --verbose openfast
brew test --verbose packmol
brew test --verbose petsc
brew test --verbose petsc-complex
brew test --verbose pgplot
brew test --verbose pnetcdf
brew test --verbose proteinortho
brew test --verbose qrupdate
brew test --verbose r
brew test --verbose rawtoaces
brew test --verbose reprepro
brew test --verbose scipy
brew test --verbose shogun
brew test --verbose siril
brew test --verbose superlu
brew test --verbose urh
```

**Comment by oscarbg** [comment]
hope can be fixed soon..  waiting for new static analyzer..

**Comment by fxcoudert** [comment]
The Mojave failure is a semi-random parallel-build issue (sadly). Hopefully it won't trigger on the next build.

**Comment by alebcay** [comment]
`imake` still needs revision bump:
```
==> brew test --verbose imake
==> FAILED
Testing imake
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200509-29646-kcbvmt.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/imake.rb --verbose
==> /usr/local/Cellar/imake/1.0.8_1/bin/imake -v -s/dev/null -f/dev/null -T/dev/null 2>&1
Error: imake: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </\/usr\/local\/opt\/gcc\/bin\/cpp\-1/> was expected to be =~
<"/usr/local/opt/gcc/bin/cpp-9 -I. -D__amd64__ -D__amd64__ -traditional -D__APPLE__ -D__DARWIN__ Imakefile.c \n" +
"/usr/local/Cellar/imake/1.0.8_1/bin/imake: No such file or directory\n" +
"/usr/local/Cellar/imake/1.0.8_1/bin/imake: Cannot exec /usr/local/opt/gcc/bin/cpp-9.\n" +
"  Stop.\n" +
"/usr/local/Cellar/imake/1.0.8_1/bin/imake: Exit code 1.\n" +
"  Stop.\n">.
```

Homebrew internals also might need some adjustment for `gcc` 10:
```
==> Running Formulae#formula!(openblas)
Error: undefined method `gcc-1_build_version' for DevelopmentTools:Class
/usr/local/Homebrew/Library/Homebrew/compilers.rb:142:in `compiler_version'
/usr/local/Homebrew/Library/Homebrew/compilers.rb:121:in `block (2 levels) in find_compiler'
/usr/local/Homebrew/Library/Homebrew/compilers.rb:119:in `reverse_each'
/usr/local/Homebrew/Library/Homebrew/compilers.rb:119:in `block in find_compiler'
/usr/local/Homebrew/Library/Homebrew/compilers.rb:116:in `each'
/usr/local/Homebrew/Library/Homebrew/compilers.rb:116:in `find_compiler'
/usr/local/Homebrew/Library/Homebrew/compilers.rb:101:in `compiler'
/usr/local/Homebrew/Library/Homebrew/compilers.rb:84:in `select_for'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:242:in `install_gcc_if_needed'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:600:in `formula!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:20:in `block in run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:19:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:19:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:94:in `run_tests'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:35:in `block in run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:25:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_runner.rb:25:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:95:in `run!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/test-bot.rb:74:in `test_bot'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by Bo98** [comment]
`brew` received preliminary support for GCC 10, but not all cases were tested because GCC 10 wasn't released yet (support was needed as Fedora 32 shipped with GCC 10 despite it not being released).

I've fixed the above error here: https://github.com/Homebrew/brew/pull/7528

`version_suffix` needs to also be modified in the GCC formula similarly to slice `\d+` rather than `\d`.

(Also: should we add `gcc@9` versioned formula here?)

**Comment by SMillerDev** [comment]
> Also: should we add gcc@9 versioned formula here?

Only if it's needed for homebrew formula.

**Comment by Bo98** [comment]
Or someone inevitably asks for it.

**Comment by fxcoudert** [comment]
> should we add gcc@9 versioned formula here?

I am not sure what the current criteria are, and whether they changed from before. But GCC 9 is supported, and historically older versions of GCC have large numbers of downloads. I would argue it makes sense to carry it, because it is very useful to users (especially given the high time and disk requirements of building one's own compiler from source).

**Comment by Bo98** [comment]
The requirements are the same as far as I know. The only thing new is that we have a deprecation system now, but that can't be applied here since there isn't a specific EOL date yet.

**Comment by fxcoudert** [comment]
**This should be not be shipped until a new brew is shipped with https://github.com/Homebrew/brew/pull/7528 in**

**Comment by fxcoudert** [comment]
It builds and tests `gcc` fine, then gets into an infinite loop of `brew install gcc` once it moves to testing `openblas`:

```
==> Running Formulae#formula!(openblas)
==> brew install gcc
==> brew install gcc
==> brew install gcc
```

**Comment by Bo98** [comment]
Ah, I see GFortran has been making some breaking changes...

---

Build failure:

* adios2 - GFortran 10 incompatibility (type mismatch)
* arpack - GFortran 10 incompatibility (rank mismatch) - patch at https://github.com/opencollab/arpack-ng/commit/9418632214acf6d387896ab29a8f5bdff2d4e38a.patch?full_index=1
* augustus - [this line](https://github.com/Homebrew/homebrew-core/blob/f57eb58b7feeade07234fe3c23f34f8015562544/Formula/augustus.rb#L41) needs to use `version_suffix`
* cp2k - fails because it needs scalapack which has a build failure
* dungeon - GFortran 10 incompatibility (different than the other failures: `Error: BOZ constant at (1) uses nonstandard postfix syntax [see '-fno-allow-invalid-boz']`)
* dynare - fails because it needs arpack which has a build failure
* eccodes - fails because it needs netcdf which has a build failure
* libbi - fails because it needs netcdf which has a build failure
* gcc@9 - docs fail to build:

```
../../gcc/doc//invoke.texi:1785: Unknown command `9-20200509-55160-10y5gr9/gcc-9.3.0/build/gcc/../../gcc'.
../../gcc/doc//invoke.texi:1784: @include `/private/tmp/gcc/../libiberty/at-file.texi': No such file or directory.
```
* ipopt - GFortran 10 incompatibility (type mismatch) in the mumps resource - reported at https://listes.ens-lyon.fr/sympa/arc/mumps-users/2020-05/msg00000.html
* mpich - GFortran 10 incompatibility - reported at https://lists.mpich.org/pipermail/discuss/2020-January/005863.html - they do not currently plan on fixing the issue and currently suggest the `-fallow-argument-mismatch` workaround
* netcdf - GFortran 10 incompatibility (rank mismatch) - reported at https://github.com/Unidata/netcdf-fortran/issues/212
* nwchem - fails because it needs scalapack which has a build failure
* octave - fails because it needs arpack which has a build failure
* petsc - fails because it needs netcdf and scalapack which have a build failure
* petsc-complex - fails because it needs netcdf and scalapack which have a build failure
* pgplot - GFortran 10 compatibility (type mismatch) - not been updated in 19 years - (also the build doesn't properly fail on the `system` call exit code - can we split up that combined `system` line into separate ones?)
* pnetcdf - GFortran 10 incompatibility (type mismatch)
* scalapack - GFortran 10 incompatibility (rank mismatch) - reported at https://github.com/Reference-ScaLAPACK/scalapack/issues/21
* scipy - GFortran 10 incompatibility (rank mismatch) - patch at https://github.com/scipy/scipy/commit/2190a7427a8d10a3a506294e87ff1330c426cb63.patch?full_index=1 - will be included in 1.5.0

Most of the GFortran 10 incompatibilities can be fixed with `-fallow-argument-mismatch` (useful for, say, pgplot which probably won't be updated) - however if that is used, it might be worth leaving a comment that it should be removed if/when upstream fix the problem (the flag is "strongly discouraged").

---

Test failure:

* csound - known random failure
* qrupdate - GFortran 10 incompatibility (type mismatch) - not been updated in 8 years but it is just a test failure and we can easily pass `-fallow-argument-mismatch`
* r - the gss resource has gone missing (replaced by gss_2.2-0.tar.gz)

---

Audit failures (can be resolved in separate PRs first if desired):

* cgns - shim reference in include/cgnsBuild.defs
* hdf5 - shim references in share/hdf5/libhdf5.settings and libhdf5 library (dylib & a)
* hdf@1.10 - same as above
* hdf@1.8 - same as above
* open-mpi - shim reference in bin/ompi_info and bin/orte-info
* plplot - shim references in share/plplot5.15.0/examples/c++/Makefile and share/plplot5.15.0/examples/c/Makefile - these files should not be installed in the first place
* root - shim references in include/root/compiledata.h, lib/root/libProof.so and lib/root/libCore.so

**Comment by Bo98** [comment]
brew 2.2.16 is now released btw

**Comment by stevenweaver** [comment]
What is necessary to expedite this? A lot of people are waiting to get their hands on the static analyzer.

**Comment by SMillerDev** [comment]
Fixing all of the software that depends on GCC to work with GCC 10.

**Comment by SMillerDev** [comment]
> Most of the GFortran 10 incompatibilities can be fixed with -fallow-argument-mismatch [...] (the flag is "strongly discouraged").

How about we add this as a solution and add an audit to make sure next package updates are warned about it?

**Comment by sjackman** [comment]
Could `gcc` be an alias to `gcc@10.rb`?

On Homebrew on Linux, bottles are built using Ubuntu 16.04 LTS (Xenial Xerus), and the default version of GCC is 5, which is the GCC version of Ubuntu 16. On Linux, `gcc` could then be an alias to `gcc@5.rb`.

Here's a related PR on Linuxbrew-core https://github.com/Homebrew/linuxbrew-core/pull/20241

cc @imichka

**Comment by sjackman** [comment]
@iMichka Just reminded me that we don't have a mechanism for `Aliases/gcc` to be different once Homebrew-core and Linuxbrew-core are merged.

**Comment by Bo98** [comment]
Possibly, though I don’t know how that will work when homebrew-core and linuxbrew-core are merged.

**Comment by sjackman** [comment]
> Possibly, though I don’t know how that will work when homebrew-core and linuxbrew-core are merged.

😭 Yeah, that's a problem. Perhaps before the merger of Homebrew-core and Linuxbrew-core we can test changing `Aliases/gcc` to GCC 9. We're not ready for that change right now though.

**Comment by DesWurstes** [comment]
Hi, many of the packages were updated. To see what else needs to be patched, maybe it's time to rebase?

**Comment by fxcoudert** [comment]
Going at it again, this time with:
- patches for arpack, scalapack
- update of netcdf-fortran resource
- flags for pnetcdf, pgplot, mpich
- test flag for qrupdate

**Comment by fxcoudert** [comment]
Current status:

- `hdf5` has:

```
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      lib/libhdf5.a
      lib/libhdf5.200.dylib
      share/hdf5/libhdf5.settings
```

- `netcdf` fails with this issue (reported at https://github.com/Unidata/netcdf-fortran/issues/266):

```
CMake Error: File /tmp/netcdf--fortran-20200626-12044-7c8f0i/netcdf-fortran-4.5.3/netCDF-FortranConfig.cmake.in does not exist.
CMake Error at /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/CMakePackageConfigHelpers.cmake:330 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1117 (configure_package_config_file)
```

**Comment by issyl0** [comment]
Bad news: Looks like CI hasn't been running on this. GitHub was in the middle of [an incident impacting Actions](https://www.githubstatus.com/incidents/d60fmldlvw48) about 13 hours ago when you pushed. 😭

**Comment by fxcoudert** [comment]
Here we go again

**Comment by SMillerDev** [comment]
The run from 2 days ago on 10.13 was still going so I cancelled that one.

**Comment by fxcoudert** [comment]
- `muparser` now needs a revision bump
- 

And I would like to ignore the following pre-existing issues: `hdf5 netcdf`

```
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      lib/libhdf5.a
      lib/libhdf5.200.dylib
      share/hdf5/libhdf5.settings

  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      bin/nf-config
      bin/ncxx4-config
      bin/nc-config
      lib/pkgconfig/netcdf.pc
      lib/pkgconfig/netcdf-fortran.pc
      lib/cmake/netCDF/netCDFConfig.cmake
      lib/libnetcdf.settings
      lib/libnetcdf-cxx.settings
```

**Comment by fxcoudert** [comment]
Failures are:

- muparser, needs a revision bump
- mlpack, I don't understand it right now
- x264, needs a revision bump (for 10.13 only)

Test failure:

- adios2
- ncview, only on 10.14… random fluke?

Pre-existing audit failures:
- hdf5, hdf5@1.10, hdf5@1.8
- netcdf, pnetcdf
- pgplot
- plplot

---

None of the failures are for high-usage formula, except `x264`, but it only affects 10.13 (5.94% of users). I would like to merge in the current state, because:

- this PR bit rots super fast, due to the many revisions
- I will quickly rebuild the needed bottle for x264
- I will investigate the rest later today

@Homebrew/core what do you think?

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
