### PR TITLE
terminal-notifier 2.0.0

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by julienXX** [comment]
Thank you @zmwangx!

**Comment by zmwangx** [comment]
@julienXX No problem, but am I right that you've switched back to an app bundle?

**Comment by julienXX** [comment]
Yes see https://github.com/julienXX/terminal-notifier/releases/tag/2.0.0 for the changes.

**Comment by zmwangx** [comment]
Yeah, I'm afraid brew doesn't like app bundles now... I wonder if it's okay get by by installing `terminal-notifier.app/Contents/MacOS/terminal-notifier`, or if a cask migration is required.

**Comment by julienXX** [comment]
I believe a cask migration is required :/

**Comment by ilovezfs** [comment]
Does it actually launch a GUI app?

**Comment by zmwangx** [comment]
At least `terminal-notifier.app/Contents/MacOS/terminal-notifier` works for what I do with it.

**Comment by julienXX** [comment]
@zmwangx if you run it manually yes but I believe if you get it out of the bundle it won't work.

**Comment by zmwangx** [comment]
A symlink would work into `bin` would work.

**Comment by julienXX** [comment]
@ilovezfs no, it is currently packaged as an application bundle because NSUserNotification does not work from a ‘Foundation tool’.

**Comment by julienXX** [comment]
@zmwangx would a symlink be okay with brew policies?

**Comment by ilovezfs** [comment]
Then I don't think we need to ship off to cask.

**Comment by zmwangx** [comment]
Actually, a symlink does not seem to work.

```diff
diff --git a/Formula/terminal-notifier.rb b/Formula/terminal-notifier.rb
index d147a85671..dcde0f87ec 100644
--- a/Formula/terminal-notifier.rb
+++ b/Formula/terminal-notifier.rb
@@ -22,7 +22,8 @@ class TerminalNotifier < Formula
                "SYMROOT=build",
                "-verbose",
                "CODE_SIGN_IDENTITY="
-    bin.install "build/Release/terminal-notifier"
+    prefix.install "build/Release/terminal-notifier.app"
+    bin.install_symlink prefix/"terminal-notifier.app/Contents/MacOS/terminal-notifier"
   end
 
   test do
```

```console
$ ls -l /usr/local/Cellar/terminal-notifier/2.0.0/bin/terminal-notifier
lrwxr-xr-x 1 zmwang admin 57 Nov  1 13:25 /usr/local/Cellar/terminal-notifier/2.0.0/bin/terminal-notifier -> ../terminal-notifier.app/Contents/MacOS/terminal-notifier
$ /usr/local/Cellar/terminal-notifier/2.0.0/bin/terminal-notifier -message hello
2017-11-01 13:26:52.499 terminal-notifier[21208:1735896] No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, exiting
$ /usr/local/Cellar/terminal-notifier/2.0.0/terminal-notifier.app/Contents/MacOS/terminal-notifier -message hello  # This one works.
```

**Comment by zmwangx** [comment]
Wait, I'm just being dumb. A wrapper would do.

**Comment by zmwangx** [comment]
Fixed.

**Comment by ilovezfs** [comment]
:bell:

**Pull request closed without merging**
