### PR TITLE
buildifier buildozer 5.0.0

### PR DESCRIPTION
**Pull request by eikemeier**
Signed-off-by: Oliver Eikemeier <eikemeier@fillmore-labs.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
> One formula per commit; one commit per formula.

@eikemeier, can you separate out the one commit out into two commits? Thanks!

**Comment by eikemeier** [comment]
> > One formula per commit; one commit per formula.
> 
> @eikemeier, can you separate out the one commit out into two commits? Thanks!

No, I can't. You'll get

```
buildifier:
  * Version of `buildozer` (4.2.5) should match version of `buildifier` (5.0.0)
Error: 1 problem in 1 formula detected
Error: `brew audit` failed!
```

or 
```
buildozer:
  * Version of `buildifier` (4.2.5) should match version of `buildozer` (5.0.0)
```

See also https://github.com/Homebrew/homebrew-core/pull/93074 😃

**Comment by nandahkrishna** [comment]
The PR that you linked to does change only one formula per commit. You needn't create separate PRs for the 2 formulae, just 2 separate commits in this PR. That way, the audit won't complain.

**Comment by eikemeier** [comment]
> The PR that you linked to does change only one formula per commit. You needn't create separate PRs for the 2 formulae, just 2 separate commits in this PR. That way, the audit won't complain.

Ah, thanks. Is there any documentation besides the source?

**Comment by nandahkrishna** [comment]
> Ah, thanks. Is there any documentation besides the source?

You can find documentation at https://docs.brew.sh. For information on PR guidelines, you can take a look at:

* https://docs.brew.sh/Formula-Cookbook (specifically, [here](https://docs.brew.sh/Formula-Cookbook#push)).
* https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

**Review by nandahkrishna — APPROVED** [review]
Thanks, @eikemeier!

**Comment by chenrui333** [comment]
yeah, I was not referring to separate out the commits into two PRs, but more referring to separate out one commit into two in this PR.

**Pull request closed without merging**
