### PR TITLE
vala 0.36.0

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
The gnome-builder build failure is fixed upstream already. A new release of gnome-builder is imminent as gnome-3.24 is being shipped this weekend.

**Comment by tschoonj** [comment]
The valabind problem is also fixed upstream already. No idea when they'll produce a new release though.

**Comment by tschoonj** [comment]
@DomT4 I you agree I will merge this one in. Afterwards feel free to rebase your webkitgtk-removal branch against origin/master.

**Comment by DomT4** [comment]
Feel free. Happy to chase you in if it's easier.

**Comment by tschoonj** [comment]
Done!

**Comment by DomT4** [comment]
Cool. https://github.com/Homebrew/homebrew-core/pull/11243 has been rebased/pushed again.

**Pull request closed without merging**
