### PR TITLE
metabase: migrate to Cask

### PR DESCRIPTION
**Pull request by AnastasiaSulyagina**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?

---

Deleting metabase from homebrew-core as part of deduplication process . See context [here](https://github.com/caskroom/homebrew-cask/issues/15603). 

_Please note that this PR is created to continue case-by-case discussions from thread linked above and if decision is made not to remove the formula, PR will be closed._ 

cc @MikeMcQuaid

### CODE REVIEW

**Comment by DomT4** [comment]
I thought `metabase` the formula & `metabase` the Cask were different things? Am I misremembering?

**Comment by MikeMcQuaid** [comment]
Homebrew's is a jar: http://www.metabase.com/start/other.html and Cask's is a DMG/app: http://www.metabase.com/start/mac.html (and outdated).

**Comment by ilovezfs** [comment]
"The Mac Application is the easiest way to setup Metabase locally on Mac OS X for personal use. Note that currently the Mac Application is not setup for shared use, so some Metabase features which involve the rest of your team won’t be possible."

**Comment by tdsmith** [comment]
ping @kdoh; what do you think about the relative utility of metabase's Mac app and the .jar Homebrew installs?

**Comment by DomT4** [comment]
I'm absolutely fine with this being migrated if that's the correct thing to do FWIW; my question was just driven by the belief they were different but both equally valid installation methods.

**Comment by MikeMcQuaid** [comment]
Let's pass on this for now but thanks for the PR @AnastasiaSulyagina

**Pull request closed without merging**
