### PR TITLE
poppler 20.08.0

### PR DESCRIPTION
**Pull request by crunchtime-ali**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
```
Error: 12 failed steps!
brew linkage --test diff-pdf
brew test --retry --verbose diff-pdf
brew linkage --test gdal
brew test --retry --verbose gdal
brew test --retry --verbose gmt
brew test --retry --verbose gmt@5
brew test --retry --verbose mapserver
brew test --retry --verbose pdal
brew linkage --test pdftoipe
brew test --retry --verbose pdftoipe
brew test --retry --verbose points2grid
brew test --retry --verbose simple-tiles
```

**Comment by Bo98** [comment]
Specifically, `diff-pdf`, `gdal` and `pdftoipe` need a revision bump due to ABI incompatible changes in this release.

**Comment by crunchtime-ali** [comment]
> ```
> Error: 12 failed steps!
> brew linkage --test diff-pdf
> brew test --retry --verbose diff-pdf
> brew linkage --test gdal
> brew test --retry --verbose gdal
> brew test --retry --verbose gmt
> brew test --retry --verbose gmt@5
> brew test --retry --verbose mapserver
> brew test --retry --verbose pdal
> brew linkage --test pdftoipe
> brew test --retry --verbose pdftoipe
> brew test --retry --verbose points2grid
> brew test --retry --verbose simple-tiles
> ```

What do I need to do? Just bump the formula revisions for `diff-pdf`, `gdal` and `pdftoipe`?

**Comment by Bo98** [comment]
Yes. `brew bump-revision --message="for poppler" <formula>` can do that and create the commits for you.

**Comment by miccal** [comment]
[`gdal` may need some patches.](https://github.com/OSGeo/gdal/pull/2825)

**Comment by miccal** [comment]
@jonchang the patch tries to apply the changes to the files `gdal/configure` and `gdal/configure.ac`, but I _think_ they should be applied to just the files `configure` and `configure.ac` at the top level of the directory tree?

**Comment by Bo98** [comment]
Something like `:p2` should sort that.

**Comment by miccal** [comment]
This PR can be closed -- I have updated `poppler` to 20.09.0 [here](https://github.com/Homebrew/homebrew-core/pull/60513).

**Comment by chenrui333** [comment]
Thanks @miccal @crunchtime-ali !!

**Pull request closed without merging**
