### PR TITLE
cargo-llvm-lines 0.4.27

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Not the latest release: https://github.com/dtolnay/cargo-llvm-lines/releases

**Comment by SMillerDev** [comment]
Should have a livecheck then

**Comment by cho-m** [comment]
It is released on Crates.io https://crates.io/crates/cargo-llvm-lines which is used by default installation:
```console
❯ cargo search cargo-llvm-lines
cargo-llvm-lines = "0.4.27"    # Count the number of lines of LLVM IR across all instantiations of a generic function.
```

Can probably request upstream to mark as latest, but it is probably a correct release.

**Review by nandahkrishna — APPROVED** [review]
Has now been marked as latest, no change to `sha256`.

**Review by carlocab — APPROVED** [review]

**Pull request merged**
