### PR TITLE
libsigc++ 3.0.0

### PR DESCRIPTION
**Pull request by tschoonj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Given it's published by the same organization (Gnome) as the current `libsigc++`, doesn't it make sense to update it as `libsigc++`, and call the old one `libsigc++@2` (if it's really needed by other formulas)?

**Comment by tschoonj** [comment]
I could do that, but expect `libsigc++@2` to be around for a long time then.

**Comment by fxcoudert** [comment]
> expect libsigc++@2 to be around for a long time then

As long as it's maintained…

**Comment by tschoonj** [comment]
By the way the new libsigc++ 3.0.0 release requires C++17... So that makes it Mojave only I assume?

**Comment by fxcoudert** [comment]
> libsigc++ 3.0.0 release requires C++17... So that makes it Mojave only I assume?

`pprint` has `depends_on :macos => :high_sierra # needs C++17`

**Comment by tschoonj** [comment]
In this case the audit warning `Versioned formulae should use keg_only :versioned_formula` can be ignored since both formulas do not have conflicting files.

**Comment by tschoonj** [comment]
@fxcoudert how about this one? Thanks!

**Comment by fxcoudert** [comment]
Some of those bottles were overwritten (I think) but the CI job of the OpenSSL migration. So we'll have to rerun it before merging. I would prefer we do this after the `nordugrid-arc` removal (https://github.com/Homebrew/homebrew-core/pull/43934) if you don't mind.

Then I'll have to deal with conflicts on the OpenSSL migration PR, and re-run that one.

**Comment by tschoonj** [comment]
Ok thanks for the update. Let me know when you need me to do something here.

**Comment by fxcoudert** [comment]
@tschoonj you can remove the `nordugrid-arc` commit and rebase the rest on top of master

**Comment by tschoonj** [comment]
Done!

**Comment by iMichka** [comment]
> libsigc++@2:
>  * Versioned formulae should use `keg_only :versioned_formula`

Is there a reason why this audit warning was ignored?

**Comment by tschoonj** [comment]
Yes: both formulas can be installed alongside each other without conflicts

**Comment by iMichka** [comment]
Cool. Thanks! So there is some flexibility here regarding that audit. Good to know.

**Comment by fxcoudert** [comment]
> there is some flexibility here regarding that audit

The way I see it: the audits are here to make us think hard about decisions that would be unusual, and therefore suspicious. But if we have consensus to override it, by all means we should do what is best for our users and the project.

**Pull request closed without merging**
