### PR TITLE
increase version of istioctl to 1.6.0

### PR DESCRIPTION
**Pull request by christophebeling**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by pascal-hofmann** [comment]
Builds fail because istioctl now requires docker for building. No idea how to get this fixed.

@christophebeling You might want to increase version to 1.6.1 which was released today.

**Comment by SMillerDev** [comment]
How does it require docker for building?

**Comment by pascal-hofmann** [comment]
> How does it require docker for building?

See https://github.com/Homebrew/homebrew-core/pull/55797/checks?check_run_id=739892893#step:6:124

**Comment by SMillerDev** [comment]
I see that it tries to run docker, but I'm trying to find out why. For most builds that require docker it's just because it's easier, but that doesn't work for macOS binaries.

**Comment by marcnyholm** [comment]
I'm not used to work with make, but it seems setting `BUILD_WITH_CONTAINER=0` will bypass the docker run https://github.com/istio/istio/blob/1.6.0/Makefile#L56.
The same goes for 1.6.1.

**Comment by pascal-hofmann** [comment]
This PR can be closed in favor of https://github.com/Homebrew/homebrew-core/pull/56380.

**Pull request closed without merging**
