### PR TITLE
mmctl 6.2.0

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
Upstream issue, looks like 6.2.0 is gone: https://github.com/mattermost/mmctl/issues/417

**Comment by iMichka** [comment]
Let's ship this, upstream did not respond, but the release is gone so let's go back to the previous one. This is ready to be reviewed.

**Review by branchv — DISMISSED** [review]

**Comment by chenrui333** [comment]
They just made a new release, saving us a bit with `version_scheme` reset. 🤣

**Review by chenrui333 — APPROVED** [review]

**Comment by iMichka** [comment]
What a mess. Thanks for the final update.

**Pull request closed without merging**
