### PR TITLE
libffi 3.2.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
You may be interested in https://github.com/Homebrew/legacy-homebrew/pull/50312.

**Comment by ilovezfs** [comment]
@DomT4 It appears that just removing `ENV.universal_binary` fixes this.

**Comment by ilovezfs** [comment]
Formulae that are (potentially) impacted if libffi's universal option were removed:
```
atk
aubio
cairo
fribidi
gdb
gdk-pixbuf
gegl
glib
gnuradio
gobject-introspection
graphviz
gtk+
gtk+3
gts
harfbuzz
libcouchbase
libevent
libidl
libmpd
libmpdclient
ola
openal-soft
pango
pulseaudio
py2cairo
pygobject
pygobject3
pygtk
r3
ruby
sdl2_mixer
sdl_mixer
subversion
uhd
wine
homebrew/science/genometools
homebrew/science/hwloc
homebrew/science/opencv
homebrew/science/openni
homebrew/science/rmblast
homebrew/versions/gegl02
homebrew/versions/llvm33
homebrew/versions/llvm34
homebrew/versions/llvm35
homebrew/versions/llvm36
homebrew/versions/llvm37
homebrew/versions/llvm38
homebrew/versions/ruby20
homebrew/versions/ruby21
homebrew/versions/ruby22
homebrew/versions/subversion18
```

**Comment by ilovezfs** [comment]
This is the patch that cpython uses (only required a minor update): https://gist.githubusercontent.com/ilovezfs/d30d8d5d8733c7cbfeb49cb8de9d3b0e/raw/e122d7a231e38aca33b2d724950ff44603fc38c7/gistfile1.txt

It works with 3.2.1. (The patch would need a couple of adjustments to apply cleanly to HEAD.)

**Comment by DomT4** [comment]
> It appears that just removing ENV.universal_binary fixes this.

It does, yeah, but we've been reluctant to pull that trigger because it could be laughably breaking for users.

**Comment by ilovezfs** [comment]
@DomT4 any thoughts on the patch above from cpython?

**Comment by DomT4** [comment]
Any idea if that has ever been submitted upstream/their feelings on that?

**Comment by MikeMcQuaid** [comment]
@ilovezfs Ping?

**Comment by ilovezfs** [comment]
@MikeMcQuaid why aren't we just killing universal here? That seems to be the right thing to do given that upstream still hasn't fixed this unless the goal is maintaining a 32-bit compatible fork indefinitely.

**Comment by DomT4** [comment]
You'd also have to kill `:universal` from anything that `brew uses libffi`, and then you'd have to kill `:universal` from anything that `brew uses` anything you'd just previously killed. Welcome to the rabbit hole 😕.

**Comment by ilovezfs** [comment]
Sounds like a good idea to me.

**Comment by DomT4** [comment]
If you're willing to put in the time & effort, feel free to take a whack at it. It's a pretty significant job though, for both you & CI.

`brew uses libffi`:
```
gforth
glib
gnu-smalltalk
gobject-introspection
gsettings-desktop-schemas
guile
idris
io
llvm
micropython
rakudo-star
sagittarius-scheme
homebrew/tex/lilypond
homebrew/versions/guile18
homebrew/versions/llvm33
homebrew/versions/llvm34
homebrew/versions/llvm35
homebrew/versions/llvm36
homebrew/versions/llvm37
homebrew/versions/llvm38
```

That's immediately anything that `brew uses` any of:
* `gobject-introspection`
* `glib`
* `llvm`

And then anything that `brew uses` them, and so on right down the tree.

**Comment by ilovezfs** [comment]
Yes, that's how universal works. I was asking Mike what's desirable here.

**Comment by MikeMcQuaid** [comment]
@ilovezfs My personal view is we should kill universal for anything except popular packages that need it i.e. `wine`.

**Comment by ilovezfs** [comment]
I just pinged upstream about this in the preexisting issue that they still have open: https://github.com/libffi/libffi/issues/180#issuecomment-252409442

**Comment by MikeMcQuaid** [comment]
@ilovezfs At this point I'd be in favour of just assuming they won't accept the patch and killing universal.

**Comment by nijikon** [comment]
So what, are we killing universal here? @ilovezfs

**Comment by MikeMcQuaid** [comment]
I'd like to.

**Comment by ilovezfs** [comment]
It's one of the wine deps so, no, we're not killing universal on it until/unless that vendor project is completed.

**Comment by fxcoudert** [comment]
Closing in favour of the newer #10908

**Comment by ilovezfs** [comment]
Shipped. Finally.

**Pull request closed without merging**
