### PR TITLE
couchbase-transactions-cxx 1.0.0 (new formula)

### PR DESCRIPTION
**Pull request by davidkelly**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks for your PR, @davidkelly. CI failed with the following error:
```
couchbase-transactions-cxx:
  * HEAD: The URL https://github.com/couchbase/couchbase-transactions-cxx.git is not a valid git URL
Error: 1 problem in 1 formula detected
```

When you fix this, please squash your changes with your first commit, and use the commit message
```
couchbase-transactions-cxx 1.0.0 (new formula)
```
as mentioned in the [contribution guidelines](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md#to-add-a-new-formula-for-foo-version-234-from-url).

**Review by carlocab — CHANGES_REQUESTED** [review]
It also looks like it provides its own copies of `libcouchbase`, `nlohmann-json`, and `spdlog` in the `deps` directory.

It should depend on the equivalent Homebrew formulae instead.

**Comment by davidkelly** [comment]
@carlocab Oops - I forgot the repo is still private.  I'll have that go public tomorrow.  

We submoduled `nlohmann-json`, `spdlog` and `libcouchbase` as they are purely internal dependencies we use.  We don't want users of the library to conflict if they are using their own versions, in the apps they will use this lib in.  We followed the same pattern that `libcouchbase` did for internal dependencies, like `snappy` for instance.

**Comment by carlocab** [comment]
`libcouchbase` and `snappy` probably shouldn't be doing those either, but no one's noticed till you pointed it out. 😄

See also https://docs.brew.sh/Acceptable-Formulae#stuff-that-requires-vendored-versions-of-homebrew-formulae.

**Comment by davidkelly** [comment]
I meant that `libcouchbase` has some internal dependencies, and at least one of them (`snappy`) is also available in brew. 
IDK what `snappy` itself does - don't want to get them in trouble :)

Of course, we build and link these statically, so the dependencies don't leak into the user's system.  However, for tracking outdated dependencies, this does obfuscate things.  

I'll ponder this a bit, and bounce it off the `libcouchbase` maintainer as well.

**Pull request closed without merging**
