### PR TITLE
black: remove resources declarations

### PR DESCRIPTION
**Pull request by chenrui333**
Remove resource declarations for the formula (would be easier for bump the version in the future)

### CODE REVIEW

**Comment by SMillerDev** [comment]
Do we have a lockfile from upstream verifying hashes with strictly pinned versions?

**Comment by chenrui333** [comment]
@SMillerDev They have piplock file
https://github.com/psf/black/blob/master/Pipfile.lock

**Comment by SMillerDev** [comment]
That isn't used in the implementation you're proposing though. So ever install would potentially be different.

**Comment by Moisan** [comment]
I spent a moment trying to get `pipenv` and `piplock` to work with this formula. It doesn't work so far but here is my best attempt:
```
    ENV["WORKON_HOME"] = libexec
    system "pipenv", "install", "--ignore-pipfile"
```
`--ignore-pipfile` forces to use the piplock file.
[`pipenv` doesn't have an option (yet)](https://github.com/pypa/pipenv/issues/746) to build the in a precise directory its virtual environment. The nearest thing is `WORKON_HOME` which is the directory in which it will create a folder named by using a hash unknown before execution. We can find back the location of the environment with
```
pyenv shell
pyenv --where
```
I was hoping that once we get the exact location of the virtualenv, we could do something like `bin.install_symlink "#{libexec}/#{the_venv_folder}/bin/black" => "black"` to symlink the binary like we usually do.

**Comment by Moisan** [comment]
Tried again but couldn't get it to work, anyone else is welcome to give it a try.

**Comment by chenrui333** [comment]
With this recipe repo as rescue, I am good for closing the PR now. :)
https://github.com/dawidd6/homebrew-update-pypi-resources

Thanks @Moisan for your efforts, really appreciate it!!

**Pull request closed without merging**
