### PR TITLE
hello: test changes to triage workflow

### PR DESCRIPTION
**Pull request by carlocab**
- hello: add an irrelevant change
- hello: add another irrelevant change

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
:(

[Error: Resource not accessible by integration](https://github.com/Homebrew/homebrew-core/actions/runs/4574290889/jobs/8075731164?pr=127182#step:2:6)

From https://github.com/Homebrew/actions/blob/master/check-commit-format/main.js and https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28, I think the workflow also needs `contents: read` and `statuses: write`. Not sure if `issues: write` is needed because `client.rest.issues` is also used.

**Comment by carlocab** [comment]
Yea, I added `contents: read` at #127183. I guess we also need `statuses: write`.

**Comment by carlocab** [comment]
`pull-requests` seems to include `issues`, so I think we're covered by `pull-requests: write`.

**Comment by carlocab** [comment]
#127184

**Comment by ZhongRuoyu** [comment]
It worked! 🎉

**Comment by carlocab** [comment]
Seems to work now. Thanks for the `statuses` tip!

**Pull request closed without merging**
