### PR TITLE
deno 0.19.0

### PR DESCRIPTION
**Pull request by chrmoritz**
Created with `brew bump-formula-pr`.

I guess it's time to drop the fragile workaround for Sierra support, because homebrew is starting to support Catalina and dropping Sierra support anyway.

### CODE REVIEW

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
Mojave fails with:

```
22:20:27 Caused by:
22:20:27   process didn't exit successfully: `/private/tmp/deno-20190929-84257-hzcehw/target/release/build/deno-5f0417f691912e7f/build-script-build` (exit code: 101)
22:20:27 --- stdout
22:20:27 cargo:rerun-if-env-changed=DENO_BUILD_PATH
22:20:27 cargo:rerun-if-env-changed=APPVEYOR_REPO_COMMIT
22:20:27 cargo:rustc-env=GN_OUT_DIR=/private/tmp/deno-20190929-84257-hzcehw/target/release
22:20:27 cargo:rustc-link-search=native=/private/tmp/deno-20190929-84257-hzcehw/target/release/obj
22:20:27 ERROR at //build/config/mac/mac_sdk.gni:80:5: Script returned non-zero exit code.
22:20:27     exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines")
22:20:27     ^----------
22:20:27 Current dir: /private/tmp/deno-20190929-84257-hzcehw/target/release/
22:20:27 Command: python /private/tmp/deno-20190929-84257-hzcehw/core/libdeno/build/mac/find_sdk.py --print_sdk_path --print_bin_path 10.14
22:20:27 Returned 1.
22:20:27 stderr:
22:20:27 
22:20:27 Traceback (most recent call last):
22:20:27   File "/private/tmp/deno-20190929-84257-hzcehw/core/libdeno/build/mac/find_sdk.py", line 127, in <module>
22:20:27     print(main())
22:20:27   File "/private/tmp/deno-20190929-84257-hzcehw/core/libdeno/build/mac/find_sdk.py", line 90, in main
22:20:27     'to continue.')
22:20:27 __main__.SdkError: 'Install Xcode, launch it, accept the license agreement, and run `sudo xcode-select -s /path/to/Xcode.app` to continue.'
22:20:27 
22:20:27 See //build/toolchain/mac/BUILD.gn:15:1: whence it was imported.
22:20:27 import("//build/config/mac/mac_sdk.gni")
22:20:27 ^--------------------------------------
22:20:27 See //BUILD.gn:4:1: which caused the file to be included.
22:20:27 group("default") {
22:20:27 ^-----------------
22:20:27 no binary download
22:20:27 release: Writing gn options to '/private/tmp/deno-20190929-84257-hzcehw/target/release/args.gn'.
22:20:27   is_official_build=true
22:20:27   symbol_level=0
22:20:27   clang_base_path="/usr/local/opt/llvm"
22:20:27   clang_use_chrome_plugins=false
22:20:27   mac_deployment_target="10.14"
22:20:27   treat_warnings_as_errors=false
22:20:27 /private/tmp/deno-20190929-84257-hzcehw/gn/out/gn gen /private/tmp/deno-20190929-84257-hzcehw/target/release
22:20:27 
22:20:27 --- stderr
22:20:27 thread 'main' panicked at 'assertion failed: status.success()', core/build.rs:96:9
22:20:27 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
22:20:27 
22:20:27 warning: build failed, waiting for other jobs to finish...
22:20:27 error: failed to compile `deno_cli v0.19.0 (/private/tmp/deno-20190929-84257-hzcehw/cli)`, intermediate artifacts can be found at `/private/tmp/deno-20190929-84257-hzcehw/target`
```

**Comment by chrmoritz** [comment]
@fxcoudert This (`deno` and `v8` too) should probably `depends_on :xcode => :build`. Other than that I can't reproduce this locally. Are you sure XCode is properly setup on the build bots (including accepting the license agreement)? Because from the error it looks like `xcode-select -print-path` isn't working correctly on the Mojave and Catalina bot?

**Comment by fxcoudert** [comment]
> Are you sure XCode is properly setup on the build bots (including accepting the license agreement)? 

That would be consistent with some other issues we're seeing right now. Will check.

**Comment by chrmoritz** [comment]
@fxcoudert Looks like that is the issue here. `v8` (and therefor `deno`) build system expect it to point to a full XCode installation.
```
==> xcode-select -print-path
/Library/Developer/CommandLineTools
```

**Comment by SMillerDev** [comment]
Shouldn't it depend on xcode then?

**Comment by chrmoritz** [comment]
> Shouldn't it depend on xcode then?

Yeah, it should and I've already made the change in this PR to depend on it.

**Comment by chrmoritz** [comment]
Also it looks like that Apple `clang` 11 is new enough to build `v8`, so we need `llvm` only on High Sierra.

**Comment by chrmoritz** [comment]
I've changed the `xcode-select --print-path` workaround to use `MacOS::Xcode.bundle_path` instead of hardcoding it to `/Applications/Xcode.app`.

Should be ready now. Please take another look.

**Pull request closed without merging**
