### PR TITLE
jhipster update dependencies to require Yarn and Java 8

### PR DESCRIPTION
**Pull request by jdubois**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jdubois** [comment]
Sorry about the build failure: Jenkins says it can't merge my PR, but it is indeed mergeable according to GitHub... Not sure what I can do here!

**Comment by ilovezfs** [comment]
What's the output of `git remote`?

**Comment by jdubois** [comment]
```
origin
upstream
```

I guess you'll also want:

```
git remote get-url origin
https://github.com/jdubois/homebrew-core.git

git remote get-url upstream
https://github.com/Homebrew/homebrew-core.git

**Comment by ilovezfs** [comment]
Cool. So you can fix it by doing

```
git fetch upstream
git reset upstream/master
git commit -am "jhipster: depend on yarn and Java 8"
git push -f
```

**Comment by jdubois** [comment]
Just did your commands, thanks @ilovezfs !

**Comment by ilovezfs** [comment]
OK, I see you had other changes in your tree. Try this:

```
git fetch upstream
git reset upstream/master
git add Formula/jhipster.rb
git commit -m "jhipster: depend on yarn and Java 8"
git push -f
```

**Comment by jdubois** [comment]
Done :-)

**Comment by ilovezfs** [comment]
@jdubois all better :)

After this PR is merged, you'll want to do this:
```
git fetch upstream
git reset --hard upstream/master
git push -f
```

And next time you open a PR, try doing so from a branch other than master as it will make the process a bit less involved.

**Comment by jdubois** [comment]
Will do, thanks a lot!

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Shipped! Thanks for the PR @jdubois :100:

**Comment by jdubois** [comment]
Great!!! Thanks

**Pull request closed without merging**
