### PR TITLE
crowdin 2.0.17

### PR DESCRIPTION
**Pull request by ihor-popyk**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ihor-popyk** [comment]
Hi @ilovezfs 
Check this please, I changed the url.
Thanks!

**Comment by ilovezfs** [comment]
@ihor-popyk I think we can just use https://crowdin.com/downloads/crowdin-cli-2.0.17.zip

**Comment by ihor-popyk** [comment]
This old url will navigate to a redirect. I think it's better to use the new one.

**Comment by ilovezfs** [comment]
The redirect is fine. I'd prefer not to have `v2` hard coded in the URL since it will interfere with automation.

**Comment by ihor-popyk** [comment]
ok. changed to https://crowdin.com/downloads/crowdin-cli-2.0.17.zip

**Comment by ilovezfs** [comment]
Thanks @ihor-popyk!

**Pull request merged**
