### PR TITLE
ungit 1.4.48

### PR DESCRIPTION
**Pull request by adonh**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alebcay** [comment]
```
Error: ungit: failed
An exception occurred within a child process:
  TypeError: no implicit conversion from nil to integer
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ungit.rb:30:in `kill'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ungit.rb:30:in `ensure in block in <class:Ungit>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ungit.rb:31:in `block in <class:Ungit>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1724:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:475:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1723:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:867:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1722:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1961:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1960:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1716:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:30:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:29:in `<main>'
```

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by ashendon** [comment]
@Moisan tests pass locally for me, so not sure why the CI is unhappy.
```> brew test Formula/ungit.rb
Testing ungit
## Ungit started ##

Took 728ms to start server.
==> curl -s 127.0.0.1:8448/
> echo $?
0```

**Comment by Moisan** [comment]
I can also run the tests locally without issue. My first guess would to be to try to increase the `sleep` call, for example using `sleep 10` to try to see if the issue is the server not having enough time to start.

**Comment by ashendon** [comment]
looks like the problem got fixed by using a unique TCP port so as not to conflict with any test failures from a prior package.

**Pull request closed without merging**
