### PR TITLE
lean 3.18.4

### PR DESCRIPTION
**Pull request by pthariensflame**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Updates URLs to the new home of Lean 3 ~~, and adds `lean@3` alias in preparation for Lean 4~~.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Unless there proves to be sufficient demand and support we won't be making a versioned formula so please remove the alias.

**Comment by pthariensflame** [comment]
@SMillerDev Done!

**Review by dawidd6 — APPROVED** [review]

**Comment by semorrison** [comment]
@pthariensflame, I'm not sure it makes sense have formulas for Lean itself. Versions come out pretty rapidly, and we have a great tool [`elan`](https://github.com/Kha/elan) for automatically providing the best version. Providing people with the capability to get Lean via `brew install lean` seems almost a disservice -- a week later they're stuck!

**Comment by pthariensflame** [comment]
@semorrison Do you think it would make sense to at least provide `elan` as a Homebrew formula?

**Pull request closed without merging**
