### PR TITLE
ed 1.15

### PR DESCRIPTION
**Pull request by echosa**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by igas** [comment]
```
Stable: The URL https://ftp.gnu.org/ed/ed-1.15.tar.lz is not reachable (HTTP status code 404)
```

**Comment by igas** [comment]
@BrewTestBot test this please

**Comment by echosa** [comment]
Oops! I messed up the URL! Sorry! It should be:

```
https://ftp.gnu.org/gnu/ed/ed-1.15.tar.lz
```

**Comment by igas** [comment]
Thank you @echosa!

**Pull request closed without merging**
