### PR TITLE
appscale-tools 3.7.1

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
The 'requests[security]>=2.20.0' distribution was not found and is required by appscale-tools
```

Resources need to be updated

**Comment by chenrui333** [comment]
Still needs some other dep update.

**Comment by chenrui333** [comment]
Dont know why it still complains after adding the needed dep:
```
18:54:44     raise DistributionNotFound(req, requirers)
18:54:44 pkg_resources.DistributionNotFound: The 'azure-servicebus~=0.21.1' distribution was not found and is required by azure
18:54:44 Error: appscale-tools: failed
18:54:44 Failed executing:
```

**Comment by chenrui333** [comment]
appscale-tools 3.7.2 just got released

**Pull request closed without merging**
