### PR TITLE
curl-libressl 7.71.1,  nghttp2-libressl 1.41.0, libevent-libressl 2.1.12 (new formulae)

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Related: #57931

> Another solution would be to create a new `curl-libressl` formula, like we have a `curl-openssl` formula, and vendor libressl in it.
> 
> Whatever we do we need to be extra cautious because all of this touches core security aspects of all our libraries and we would like to avoid bad surprises to our end users. People have been used to get `curl` and `curl-openssl` like they are right now, so changing what we ship might potentially have an impact on our users. As far as I know there is right now only 1 or 2 persons interested in having curl with a newer `libressl` version, which is not that many people compared to our whole user base.

-----

> The new `libressl` formulae should be `keg_only :provided_by_macos`.

Should be noted that `nghttp2` and `libevent` are not provided by macOS but by `homebrew/core`

-----

```console
% brew deps --tree curl-libressl
curl-libressl
├── libressl
├── c-ares
├── jansson
├── jemalloc
├── libev
├── libevent-libressl
│   └── libressl
└── nghttp2-libressl
    ├── c-ares
    ├── jansson
    ├── jemalloc
    ├── libev
    ├── libressl
    └── libevent-libressl
        └── libressl
```

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
```
==> FAILED
Error: 1 problem in 1 formula detected
libevent-libressl:
  * Dependency 'libressl' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.


==> FAILED
Error: 1 problem in 1 formula detected
nghttp2-libressl:
  * Dependency 'libressl' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.


==> FAILED
Error: 1 problem in 1 formula detected
curl-libressl:
  * Dependency 'libressl' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.
```

**Comment by rgoldberg** [comment]
A curl formula attempting to have all the features that are included with the macOS builtin curl shouldn't be called `curl-libressl`, as the builtin might not use LibreSSL in the future.  It should be called something like `curl-macos-aligned`, `curl-macos-superset`, etc.

I think `aligned` or `superset`, etc. are more appropriate than `parity` because different versions of macOS might have different curl features installed. I assume that we wouldn't want to change the curl features that are installed based on the version of macOS that it is being installed upon, so a superset of the features in all supported versions of macOS would make the most sense.  A superset isn't parity.

A `curl-libressl` formula can be made in addition to my proposed `curl-macos-superset` formula, but they would serve different purposes.

**Review by MikeMcQuaid — COMMENTED** [review]
I don't see the benefit of the added formulae here based on the request from a single user, sorry.

**Comment by SeekingMeaning** [comment]
Closing in favor of #58274

**Pull request closed without merging**
