### PR TITLE
OrientDB 2.2.5

### PR DESCRIPTION
**Pull request by robfrank**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
Test is failing:
```
==> /usr/local/Cellar/orientdb/2.2.5/bin/orientdb start
Starting OrientDB server daemon...
==> curl -I localhost:2480
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 2480: Connection refused
==> /usr/local/Cellar/orientdb/2.2.5/bin/orientdb stop
Stopping OrientDB server daemon...
Error: orientdb: failed
<0> expected but was
<7>.
```

I'd maybe try another port.

**Comment by robfrank** [comment]
I'm sorry, I did the audit strict and test, do you use some other procedures?

**Comment by DomT4** [comment]
Yeah, I'm not sure this is your fault as such. I suspect those ports are having issues on CI for whatever reason. Does `orientdb` allow specifying which port to use?

**Comment by robfrank** [comment]
With the orientdb script it isn't possible to override ports, that orient reads from configuration.

We can add another inreplace section to change the port, similar to:
```
 inreplace "#{libexec}/config/orientdb-server-config.xml", "</properties>",
       <<-EOS.undent
         <entry name="server.database.path" value="#{var}/db/orientdb" />
         </properties>
       EOS
```

But, 2480 should be available, it is over 1024.

**Comment by apjanke** [comment]
Test passes locally on my El Cap box. On the CI, it passed on Mavericks but failed on Yosemite and El Cap.

And I remoted in to the El Cap CI box and did `brew intall orientdb; brew test orientdb` against the current orientdb 2.2.2 bottle, and it passed. It was using the same port 2480. So the particular port doesn't seem like an issue.

```
elcapitanvm:manual-test brew$ brew install orientdb
==> Downloading https://homebrew.bintray.com/bottles/orientdb-2.2.2.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring orientdb-2.2.2.el_capitan.bottle.tar.gz
==> Caveats
Use `orientdb <start | stop | status>`, `orientdb-console` and `orientdb-gremlin`.
==> Summary
🍺  /usr/local/Cellar/orientdb/2.2.2: 226 files, 64.4M
elcapitanvm:manual-test brew$ brew test -v orientdb
Testing orientdb
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160725-79101-g1teu7.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/orientdb.rb -v
==> /usr/local/Cellar/orientdb/2.2.2/bin/orientdb start
Starting OrientDB server daemon...
==> curl -I localhost:2480
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   120    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
==> /usr/local/Cellar/orientdb/2.2.2/bin/orientdb stop
Stopping OrientDB server daemon...
elcapitanvm:manual-test brew$
```

Maybe it's something transient on the CI boxes. Let's just try it again to get another data point.

@BrewTestBot test this please

**Comment by apjanke** [comment]
And lookee there, it passed. Calling this a transient test bot issue.

Merged. Thank you for your contribution to Homebrew!

**Pull request closed without merging**
