### PR TITLE
gdbm 1.19

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
license header ref:

```
/* gdbm.h  -  The include file for dbm users.  -*- c -*- */

/*  This file is part of GDBM, the GNU data base manager, by Philip A. Nelson.
    Copyright (C) 1990-1991, 1993, 2011, 2016-2020 Free Software
    Foundation, Inc.

    GDBM is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2, or (at your option)
    any later version.

    GDBM is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with GDBM. If not, see <http://www.gnu.org/licenses/>.  

    You may contact the author by:
       e-mail:  phil@cs.wwu.edu
      us-mail:  Philip A. Nelson
                Computer Science Department
                Western Washington University
                Bellingham, WA 98226
       
*************************************************************************/
```

**Comment by ajh17** [comment]
I believe the `--without-readline` option should no longer be necessary. I was able to build (albeit I don't use homebrew) gdbm 1.19 with readline support, and gdbmtool was linked correctly by adding the readline dependency:

```bash
otool -L /usr/local/opt/gdbm/bin/gdbmtool
/usr/local/opt/gdbm/bin/gdbmtool:
        /usr/local/opt/gdbm/lib/libgdbm.6.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/local/opt/readline/lib/libreadline.8.dylib (compatibility version 8.0.0, current version 8.0.0)
        /usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)

```

I couldn't find a commit in the upstream repository which indicated that this was fixed though, but I don't think readline detection was ever 'broken', even in gdbm 1.13. Indeed, I'm able to build gdbm 1.13 with readline support by simply including the readline header and library prefixes.

I think this formula should try linking readline or update the comment to accurately reflect the reason for skipping the readline dependency.

**Comment by fxcoudert** [comment]
The option is there to avoid opportunistic linkage, like most `--without-` options in Homebrew. We decided that feature was not really useful (most users install gdbm as a dependency for its library).

**Comment by moonfruit** [comment]
Why this pull request is closed? @chenrui333 @fxcoudert

**Comment by fxcoudert** [comment]
> This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Pull request closed without merging**
