### PR TITLE
xplr 0.4.3 (new formula)

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alebcay** [comment]
```
Error: xplr: failed
An exception occurred within a child process:
  ArgumentError: invalid byte sequence in UTF-8
```

Any ideas why something might be a UTF-8 byte sequence in everything except Apple Silicon?

**Comment by carlocab** [comment]
Could be broken so it's just spitting out garbage on ARM. You could try SSHing into `bigsur-arm5` to see what it does since it's not on the actions queue.

**Comment by alebcay** [comment]
Well, I guess the text encoding just wasn't UTF-8? Frankly now I'm not sure if the encoding change really fixed this or if the previous failure was just a fluke.

**Review by carlocab — APPROVED** [review]
Character encoding is voodoo.

**Pull request closed without merging**
