### PR TITLE
v8 10.7.193.16

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by fxcoudert** [comment]
Looking good, but `gn` and others need to be updated…

**Comment by chenrui333** [comment]
> Looking good, but `gn` and others need to be updated…

all those are up to date :)

**Comment by fxcoudert** [comment]
I don't see how. According to https://chromium.googlesource.com/v8/v8.git/+/refs/tags/10.7.193.16/DEPS#49

- `'gn_version': 'git_revision:b4851eb2062f76a880c07f7fa0d12913beb6d79e'`
- `trace_event` should be `521ac34ebd795939c7e16b37d9d3ddb40e8ed556`
- `build` should be `4157fb6cb44135013300168c9f4c5b95d04acf70`
- `icu` should be `20f8ac695af59b6c830def7d4e95bfeb13dd7be5`
- `zlib` should be `f48cb14d487038d20c85680e29351e095a0fea8b`

**Comment by chenrui333** [comment]
> I don't see how. According to https://chromium.googlesource.com/v8/v8.git/+/refs/tags/10.7.193.16/DEPS#49
> 
> * `'gn_version': 'git_revision:b4851eb2062f76a880c07f7fa0d12913beb6d79e'`
> * `trace_event` should be `521ac34ebd795939c7e16b37d9d3ddb40e8ed556`
> * `build` should be `4157fb6cb44135013300168c9f4c5b95d04acf70`
> * `icu` should be `20f8ac695af59b6c830def7d4e95bfeb13dd7be5`
> * `zlib` should be `f48cb14d487038d20c85680e29351e095a0fea8b`
> 
> Am I missing something?

my bad, I might checked wrong url, just updated.

**Review by fxcoudert — APPROVED** [review]

**Comment by chenrui333** [comment]
```
  clang (LLVM option parsing): Unknown command line argument '-simplifycfg-hoist-common-skip-limit=0'.  Try: 'clang (LLVM option parsing) --help'
  clang (LLVM option parsing): Did you mean '--simplifycfg-hoist-common=0'?
  ninja: build stopped: subcommand failed.
```

**Comment by cho-m** [comment]
Probably a flag from LLVM development branch which will be available with LLVM 16. Unless we add a workaround, we will be stuck on current `v8` version until LLVM 16 is released.

**Pull request closed without merging**
