### PR TITLE
kubernetes-helm 2.7.2

### PR DESCRIPTION
**Pull request by cblecker**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
2.7.0 is still marked as the latest version. https://github.com/kubernetes/helm/releases/latest

**Comment by cblecker** [comment]
@ilovezfs Release notes are now available, and it's marked as latest

**Comment by cblecker** [comment]
@ilovezfs bumping to 2.7.2 for a security fix
https://github.com/kubernetes/helm/releases/tag/v2.7.2

**Comment by ilovezfs** [comment]
Thanks @cblecker! :lock:

**Pull request closed without merging**
