### PR TITLE
aerc 0.8.1

### PR DESCRIPTION
**Pull request by ancarda**
Created with `brew bump-formula-pr`.

This PR replaces #95510

* [x] Double check everything isn't completely broken now (see comment)

### CODE REVIEW

**Comment by ancarda** [comment]
Before merging, I'd like some time to review this commit closely: https://git.sr.ht/~rjarry/aerc/commit/bb0f1801402e as it seems the Makefile has changed substantially

* [ ] Double check everything isn't completely broken now

Is there a way to test installing using this formula? I think `uninstall --zap` and install with `--HEAD` will probably work too.

**Comment by SMillerDev** [comment]
Removing a formula just removes al it's files all the time, there is no `--zap` for that.

**Comment by ancarda** [comment]
Do you mean `brew remove <formula>` doesn't need `--zap`? Maybe we need to update the man page as it lists `--zap` here:

```
   uninstall, remove, rm [options] installed_formula|installed_cask [...]
       Uninstall a formula or cask.

       -f, --force
              Delete all installed versions of formula. Uninstall even if cask is not installed, overwrite existing files and ignore errors when removing files.

       --zap  Remove all files associated with a cask. May remove files which are shared between applications.
```

Anyhow, I nuked `~/Library/Preferences/aerc` and re-ran the wizard on 0.8.1. Everything seems to work fine, both with older config and current config. I'm pretty confident this can go in 🙂

**Comment by SMillerDev** [comment]
> `--zap  Remove all files associated with a cask.`

This isn't a cask, it's a formula so this does nothing.

**Comment by ancarda** [comment]
Argh that serves me right for responding first thing in the morning. Thanks, @SMillerDev!

Can this be merged?

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
