### PR TITLE
Use free_port instead of predefined in test

### PR DESCRIPTION
**Pull request by bayandin**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This PR replaces usages of predefined ports with provided by [`free_port`](https://github.com/Homebrew/brew/pull/7225).

DO NOT MERGE until the next homebrew release with https://github.com/Homebrew/brew/pull/7225

PS: Not all the formula with predefined ports are fixed. I've use `git grep -l -P ':\d{4}' Formula/ ` to find suspicious formulae

### CODE REVIEW

**Review by Bo98 — COMMENTED** [review]
CI hung on testing `tinyproxy`.

**Comment by bayandin** [comment]
> CI hung on testing `tinyproxy`.

Thanks! I've reverted adding an option `-d` from `tinyproxy`. And fixed passing argument to jenkinses

**Comment by Bo98** [comment]
Worked fine on Jenkins. GitHub Actions hung on testing `armor`:

```
2020-04-06T22:20:17.5764600Z [34m==>[0m [1mbrew test armor --verbose[0m
2020-04-06T22:20:19.1375460Z Testing armor
2020-04-06T22:20:19.1472010Z /usr/bin/sandbox-exec -f /private/tmp/homebrew20200406-2075-g1o637.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/armor.rb --verbose
2020-04-06T22:20:21.6672040Z 
2020-04-06T22:20:21.6679610Z    ___
2020-04-06T22:20:21.6680200Z   / _ | ______ _  ___  ____
2020-04-06T22:20:21.6682310Z  / __ |/ __/  ' \/ _ \/ __/
2020-04-06T22:20:21.6682680Z /_/ |_/_/ /_/_/_/\___/_/    v0.4.14
2020-04-06T22:20:21.6682810Z 
2020-04-06T22:20:21.6683000Z Uncomplicated, modern HTTP server
2020-04-06T22:20:21.6683320Z https://armor.labstack.com
2020-04-06T22:20:21.6690930Z ________________________O/_______
2020-04-06T22:20:21.6691560Z                         O\
2020-04-06T22:20:21.6715300Z â‡¨ serving from http://localhost:50987 (Local)
2020-04-06T22:20:21.6716120Z â‡¨ serving from http://192.168.122.2:50987 (Intranet)
2020-04-06T22:20:22.3878310Z [34m==>[0m [1mcurl -sI http://localhost:50987[0m
2020-04-06T22:20:22.4042260Z {"time":"2020-04-06T23:20:22.399883+01:00","id":"","remote_ip":"::1","host":"localhost:50987","method":"HEAD","uri":"/","user_agent":"curl/7.64.1","status":200,"error":"","latency":618794,"latency_human":"618.794Âµs","bytes_in":0,"bytes_out":1077}
```

**Comment by SMillerDev** [comment]
@MikeMcQuaid is this week going to have a HB release?

**Comment by MikeMcQuaid** [comment]
@smillerdev Yes, probably. We've had a bunch of issues that made me want to hold off.

**Comment by Bo98** [comment]
`armor` still hangs on the GitHub Actions runners, but I'd deal with that in a separate PR.

**Comment by MikeMcQuaid** [comment]
We have a 2.2.12 tag now 🎉

**Comment by bayandin** [comment]
- `brew audit serveit --online`:
```
Stacktrace
        Error: 1 problem in 1 formula detected
serveit:
  * 'revision 1' should be removed
```

The only failure, since it's not caused by these changes I'm merging it

**Pull request merged**
