### PR TITLE
coreutils 8.27

### PR DESCRIPTION
**Pull request by zmwangx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Annoying. Mirrors were supposed to be strict failure only for exactly this reason, but of course here we've hit a corner case that wasn't handled.

**Comment by zmwangx** [comment]
```
$ curl -IL https://ftpmirror.gnu.org/coreutils/coreutils-8.26.tar.xz
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.4.6 (Trisquel GNU/Linux)
Date: Thu, 09 Mar 2017 06:58:48 GMT
Connection: keep-alive
Location: http://open-source-box.org/coreutils/coreutils-8.26.tar.xz
X-Frame-Options: DENY
X-Content-Type-Options: nosniff

HTTP/1.1 200 OK
Date: Thu, 09 Mar 2017 05:10:50 GMT
Server: Apache/2.2.16 (Ubuntu)
Last-Modified: Wed, 30 Nov 2016 19:14:17 GMT
ETag: "7e0881-58a844-5428982dc9440"
Accept-Ranges: bytes
Content-Length: 5810244
Content-Type: application/x-tar
```

**Comment by ilovezfs** [comment]
Yeah. Most of them don't have it yet.

**Comment by ilovezfs** [comment]
:lollipop: :balloon: :candy:

**Pull request closed without merging**
