### PR TITLE
publish-commit-bottles: handle PRs with no bottles to publish

### PR DESCRIPTION
**Pull request by carlocab**
This should avoid errors like the one at #127904.

### CODE REVIEW

**Comment by carlocab** [comment]
Needs `fromJson`, I think.

**Comment by carlocab** [comment]
Seems to work: https://github.com/Homebrew/homebrew-core/actions/runs/4648422734/jobs/8226103670

**Comment by carlocab** [comment]
Ok, now it works.

**Review by ZhongRuoyu — APPROVED** [review]

**Review by dawidd6 — APPROVED** [review]

**Comment by carlocab** [comment]
And in https://github.com/Homebrew/homebrew-core/pull/127919...

**Pull request merged**
