### PR TITLE
boring 0.9.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.<details>
  <summary>release notes</summary>
  <pre>* Adds shell completions for bash, zsh, and fish
* Now creates a commented-out default config on first use
* Bumps some golang.org/x dependencies</pre>
</details>

### CODE REVIEW

**Comment by chenrui333** [comment]
cc @alebeck any idea why it does not print version in CI? Thanks!

**Comment by alebeck** [comment]
Hi, the newest version suppresses "interactive" outputs if stdout is not a terminal. The idea was to minimize side effects if boring is run in a unix pipe, as done in the new shell completion scripts. I'm trying to figure out how to adapt the tests accordingly, possibly with `PTY.spawn`? Thanks :)

**Comment by alebeck** [comment]
I could also simply remove the two asserts that check for "interactive" outputs, and keep the last one that checks actual config functionality. Whatever you prefer.

**Comment by chenrui333** [comment]
oh, that makes sense, I think we'd still like to check the version, any reason why not adding a separate version subcommand?

**Comment by alebeck** [comment]
I could add a version subcommand, but then these two asserts would still be failing:

```
    assert output.end_with?("No tunnels configured.\n")
    assert_predicate test_config, :exist?
```

The problem is that neither the "No tunnels configured.\n" message would be output nor the empty config file created if we're not in a terminal. So even with the version subcommand I would have to remove these two asserts -- or just use `PTY.spawn` for everything in the first place?

**Comment by chenrui333** [comment]
yeah, that is true, let's update the test first, can you followup with the version subcommand? thanks!

**Comment by alebeck** [comment]
sure, that works!

**Review by daeho-ro — APPROVED** [review]

**Pull request merged**
