### PR TITLE
Remove more options

### PR DESCRIPTION
**Pull request by fxcoudert**
Based on analytics, moving some of them to defaults, removing some…

### CODE REVIEW

**Comment by jcarpent** [comment]
@fxcoudert  why do want to remove the options?
For instance, in my case, having optional `with-collada-dom` for OSG is fundamental. But, now, as this option has been removed, I need to find a trick to fix this issue.

**Comment by fxcoudert** [comment]
@jcarpent in this specific case, because that option has been used 3 times in 3 months, and we cannot test for options so they bitrot over time and users complain. It's not ideal to remove them either, because they have some (few) users, but we have determined that in some cases it is the best we can do for the overall community. See #31510 for a discussion.

**Comment by jcarpent** [comment]
@fxcoudert Thank you very much for this quick answer. I do understand the complexity induced by the options.
I need to find a trick on my side to compensate for this loss. If you have any trick on this side?

**Comment by fxcoudert** [comment]
@jcarpent you can host a copy of the old formula in a personal tap: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Pull request closed without merging**
