### PR TITLE
zplug 2.2.1

### PR DESCRIPTION
**Pull request by ilovezfs**
fix the test

### CODE REVIEW

**Comment by DomT4** [comment]
Test failed.

**Comment by ilovezfs** [comment]
@apjanke does the test fix look sane or should that not be needed?

**Comment by apjanke** [comment]
Probably shouldn't be necessary, IMHO.

This looks like an issue with installing zplug to a non-default location. Looks to me like we should set `ZPLUG_HOME` inside the test (as described in the caveats) instead of creating new files.

**Comment by ilovezfs** [comment]
@apjanke better?

**Comment by apjanke** [comment]
Better! This looks right to me.

**Comment by ilovezfs** [comment]
@apjanke great. Thanks for taking a look at this, since, as you know, I'm pretty zsh challenged.

**Pull request closed without merging**
