### PR TITLE
boost: fix for boost::process with xcode15

### PR DESCRIPTION
**Pull request by nega0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
This is https://github.com/boostorg/process/commit/5f795d9e62c81893a44c58162abd3b8c0c6beb8c which addresses https://github.com/boostorg/process/issues/342. This fix should make its way into boost 1.84. With out it, `boost::process` chokes itself on MacOSX14.0.sdk (CLT).

```console
$ clang++ --version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

$ cat foo.cc
#include <boost/process.hpp>

$ clang++ -std=c++17 -Wall -g -O0 -I/opt/homebrew/opt/boost/include -c foo.cc |& rg error:
/opt/homebrew/opt/boost/include/boost/process/detail/posix/handles.hpp:36:20: error: expected unqualified-id
/opt/homebrew/opt/boost/include/boost/process/detail/posix/handles.hpp:36:20: error: unexpected type name 'DIR': expected expression
/opt/homebrew/opt/boost/include/boost/process/detail/posix/handles.hpp:36:20: error: use of undeclared identifier '_dirp'
/opt/homebrew/opt/boost/include/boost/process/detail/posix/handles.hpp:120:24: error: expected unqualified-id
/opt/homebrew/opt/boost/include/boost/process/detail/posix/handles.hpp:120:24: error: unexpected type name 'DIR': expected expression
/opt/homebrew/opt/boost/include/boost/process/detail/posix/handles.hpp:120:24: error: use of undeclared identifier '_dirp'
```

### CODE REVIEW

**Comment by iMichka** [comment]
Hey, I did not notice this was a patch for `boost`, got confused by the `process` name and thought this was a different unrelated formula. I tried the patch locally with boost 1.83 and it did not apply (#151447). Looks like a different patch (or not patch) will be needed there. I am close to complete #151447 so I would rather add the patch after 1.83 is merged

**Comment by nega0** [comment]
> I tried the patch locally with boost 1.83 and it did not apply

Did you have the directory correct? The patch is against `boost::process` not `boost`. You'll need to compensate if you applying against `boost`. (The directories are different again in the source package from https://boost.org)

```console
$ curl -sOL https://github.com/boostorg/boost/releases/download/boost-1.83.0/boost-1.83.0.tar.xz

$ tar xf boost-1.83.0.tar.xz

$ curl -sL https://github.com/boostorg/process/commit/5f795d9e62c81893a44c58162abd3b8c0c6beb8c.patch| patch --dry-run -p1 -d boost-1.83.0/libs/process
patching file 'include/boost/process/detail/posix/handles.hpp'
```

Regardless this PR does the right thing wrt the patch.

Happy to wait until https://github.com/Homebrew/homebrew-core/pull/151447 drops and adjust.

**Comment by SMillerDev** [comment]
This builds fine now, I think we can merge this without dependent testing.

**Review by SMillerDev — APPROVED** [review]

**Review by fxcoudert — APPROVED** [review]

**Comment by nega0** [comment]
Fixed with Homebrew/homebrew-core@dbaa389be05ea644dca811efe4ea91f744632b53

**Pull request merged**
