### PR TITLE
uniutils 2.28

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
Looks like the download URL is going to an HTML page instead right now. The homepage has links going to this URL but they don't download a valid tarball.

**Comment by chenrui333** [comment]
notified upstream via author's email

**Comment by chenrui333** [comment]
```
   ./install-sh -c -d '/opt/homebrew/Cellar/uniutils/2.28/share/man/man1'
  /bin/sh: ./install-sh: Permission denied
```

**Comment by chenrui333** [comment]
needs upstream patch on this

**Comment by chenrui333** [comment]
#153226

**Pull request closed without merging**
