### PR TITLE
ugrep 3.0.6

### PR DESCRIPTION
**Pull request by cybniv**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by cybniv** [comment]
> New v3: performance enhancements and other improvements with a redesigned search engine. Search speeds are significantly increased when searching very large files (several GB). Added a new T3 benchmark with a large 13GB file to demonstrate the improvements. More features will be added soon!

**Comment by SMillerDev** [comment]
Can it build in parallel yet? Or rather, are line 19-22 still needed?

**Comment by cybniv** [comment]
> Can it build in parallel yet? Or rather, are line 19-22 still needed?

I encountered no problems with line 19-22 removed, even with `$CFLAGS=-O2`.

```
λ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by fxcoudert** [comment]
@cybniv please remove the lines, if they can be

**Comment by cybniv** [comment]
@fxcoudert @SMillerDev ugrep [3.0.6](https://github.com/Genivia/ugrep/releases/tag/v3.0.6) was released in the meantime, with only [minor changes](https://github.com/Genivia/ugrep/compare/v3.0.5...v3.0.6).

What would be your preference:
1) Another commit on top of the previous and change the PR title to `ugrep 3.0.6` (branch name could be changed, too)
2) Amend 3.0.5 commit and force-push, change PR title etc.
3) Open new PR

**Comment by fxcoudert** [comment]
@cybniv update to 3.0.6, squash everything into a single `ugrep 3.0.6` commit please. (I've killed tests for now, so they don't run for nothing)

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thank you @cybniv for your contribution to Homebrew!

**Pull request closed without merging**
