### PR TITLE
gtop 0.1.5 (new formula)

### PR DESCRIPTION
**Pull request by aksakalli**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by aksakalli** [comment]
gtop is terminal monitoring dashboard written in nodejs, it was requested by macOS community to create a brew package: https://github.com/aksakalli/gtop/issues/27

**Review by ilovezfs — CHANGES_REQUESTED** [review]
This needs a test block that exercises, and verifies, the functionality of the installed software.

**Comment by michaelcurry** [comment]
@ilovezfs: Can you please point to documentation that gives an example of how to do this?

**Comment by ilovezfs** [comment]
dep, faas-cli, jose, jupyter

**Pull request closed without merging**
