### PR TITLE
postgresql@12: fix broken formula

### LINKED ISSUE #62930: Unable to initialize PostgreSQL 12 database
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I want to set up a PostgreSQL 12 database.

## What happened (include command output)

I try to generate a data directory using:
```
❯ /usr/local/opt/postgresql@12/bin/initdb --locale=C -E UTF-8 /usr/local/var/postgresql@12
```

(Side note: the output of `brew info postgresql@12` does not give the correct command for setting up a PostgreSQL 12 database.)

But I get:
```
performing post-bootstrap initialization ... 2020-10-15 09:04:05.276 CDT [36419] FATAL:  could not access file "$libdir/dict_snowball": No such file or directory
```

<details>
  <summary>Command output</summary>
  <pre>
❯ /usr/local/opt/postgresql@12/bin/initdb --locale=C -E UTF-8 /usr/local/var/postgresql@12
The files belonging to this database system will be owned by user "dev".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /usr/local/var/postgresql@12 ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... America/Chicago
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... 2020-10-15 09:04:05.276 CDT [36419] FATAL:  could not access file "$libdir/dict_snowball": No such file or directory
2020-10-15 09:04:05.276 CDT [36419] STATEMENT:  CREATE FUNCTION dsnowball_init(INTERNAL)
	    RETURNS INTERNAL AS '$libdir/dict_snowball', 'dsnowball_init'
	LANGUAGE C STRICT;

child process exited with exit code 1
initdb: removing data directory "/usr/local/var/postgresql@12"
  </pre>
</details>

## What you expected to happen

It should be possible to create a PostgreSQL database.

## Step-by-step reproduction instructions (by running `brew install` commands)

* `brew install postgresql@12`
* `/usr/local/opt/postgresql@12/bin/initdb --locale=C -E UTF-8 /usr/local/var/postgresql@12`

### PR DESCRIPTION
**Pull request by ashkulz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

fixes #62930

### CODE REVIEW

**Comment by jonchang** [comment]
https://github.com/Homebrew/homebrew-core/blob/79c1756bcefedcaef7a89b83b90fffbd7ecb7e42/Formula/postgresql%4012.rb#L66-L73

Any reason why we shouldn't just pass all of these arguments to both `make` calls just to be sure?

**Comment by ashkulz** [comment]
@jonchang installation worked after this, and I thought a minimal diff would be more likely to be approved 🙂

Do you want me to add all the arguments to the `make` invocation? Another alternative is to remove it altogether, as I'm pretty sure `install-world` would depend on the default target.

**Comment by jonchang** [comment]
Yeah, we might as well. Set up a new `make_args` and then pass it to both make invocations. That way if postgres decides to switch things up on us again it'll be easier to modify both calls. Thanks!

**Comment by ashkulz** [comment]
@jonchang I've only done it for this specific formula, do you want me to do it for the `postgresql` formula as well?

**Comment by jonchang** [comment]
@ashkulz either in this one or a separate pull request. We're currently having CI issues so regardless this will take a bit of time to get fixed in Homebrew. Thanks for your hard work on this!

**Comment by ashkulz** [comment]
Cool, once this is merged I'll open up a separate PR 👍

**Comment by ashkulz** [comment]
@jonchang this breaks the build as now the paths returned by `pg_config` don't use the values from `configure`. I'm inclined to revert back to my original approach, which just undoes the "smart" handling of `pkglibdir`. Ideally, there should've been a configure option for that as well :man_shrugging:

**Comment by jonchang** [comment]
Yeah, that sounds good. Unfortunately there doesn't seem to be a configure option, but I'll send an email to their bugs mailing list linking to this change.

**Comment by jonchang** [comment]
@ashkulz Thanks for contributing to Homebrew! This has been merged.

**Comment by jonchang** [comment]
I note that Debian has carried around a similar patch for at least a decade, so we'll see if contacting the postgres maintainers will solve anything... https://salsa.debian.org/postgresql/postgresql/-/blob/1ffe3b5551ba1d24d72f3ef5918cde32429e3fda/debian/patches/50-per-version-dirs.patch

**Pull request closed without merging**
