### PR TITLE
dart-sdk 3.1.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
[3576/3760] STAMP obj/runtime/bin/standalone_dart_io.stamp
[3577/3760] LINK ./gen_snapshot_product
[3578/3760] STAMP obj/runtime/bin/standalone_dart_io_product.stamp
[3579/3760] LINK ./dart_precompiled_runtime
ld64.lld: warning: cannot export hidden symbol Dart_LoadELF
>>> defined in obj/runtime/bin/elf_loader.elf_loader.o

ld64.lld: warning: cannot export hidden symbol Dart_LoadELF_Memory
>>> defined in obj/runtime/bin/elf_loader.elf_loader.o

ld64.lld: warning: cannot export hidden symbol Dart_UnloadELF
>>> defined in obj/runtime/bin/elf_loader.elf_loader.o
[3580/3760] STAMP obj/runtime_precompiled.stamp
[3581/3760] COPY exe.stripped/gen_snapshot_product dart-sdk/bin/utils/gen_snapshot
[3582/3760] STAMP obj/sdk/copy_gen_snapshot_exe.stamp
[3583/3760] LINK ./gen_snapshot
[3584/3760] COPY gen_snapshot_product.sym dart-sdk/bin/utils/gen_snapshot.sym
[3585/3760] STAMP obj/sdk/copy_gen_snapshot_sym.stamp
[3586/3760] STAMP obj/sdk/copy_gen_snapshot.stamp
[3587/3760] STAMP obj/utils/compiler/dart2js_create_snapshot_entry.stamp
[3588/3760] ACTION //runtime/bin:generate_snapshot_bin(//build/toolchain/mac:clang_arm64)
[3589/3760] STAMP obj/runtime/bin/generate_snapshot_bin.stamp
[3590/3760] LINK ./dart_precompiled_runtime_product
ld64.lld: warning: cannot export hidden symbol Dart_LoadELF
>>> defined in obj/runtime/bin/elf_loader_product.elf_loader.o

ld64.lld: warning: cannot export hidden symbol Dart_LoadELF_Memory
>>> defined in obj/runtime/bin/elf_loader_product.elf_loader.o

ld64.lld: warning: cannot export hidden symbol Dart_UnloadELF
```

**Comment by ntkme** [comment]
It's not upstream issue, instead the formula itself is wrong. See https://github.com/dart-lang/sdk/issues/53464#issuecomment-1712267875.

So instead of running:

```
    system "fetch", "--no-history", "dart"
```

It should be:

```
    system "gclient", "config", "--name", "sdk", "https://dart.googlesource.com/sdk.git@#{version}"
    system "gclient", "sync", "--no-history"
```

Note that with fetch command you cannot specify a git ref to clone, so gclient should be explicitly used to clone the repo with a git ref.

**Comment by chenrui333** [comment]
@ntkme thanks for the pointer, I will look a bit tomorrow. Also if you have bandwidth, feel free to submit a PR :)

**Comment by chenrui333** [comment]
@ntkme can you help on this?

**Comment by ntkme** [comment]
@chenrui333 PR opened at https://github.com/Homebrew/homebrew-core/pull/142101

**Comment by chenrui333** [comment]
Thanks @ntkme!

**Pull request closed without merging**
