### PR TITLE
openldap 2.5.4

### PR DESCRIPTION
**Pull request by miccal**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by nandahkrishna** [comment]
I think `curl`, `heimdal` and `lighttpd` need revision bumps.

**Comment by chenrui333** [comment]
```
openldap.c:83:17: error: static declaration of 'ldap_connect' follows non-static declaration
static CURLcode ldap_connect(struct Curl_easy *data, bool *done);
                ^
/usr/local/opt/openldap/include/ldap.h:1554:1: note: previous declaration is here
ldap_connect( LDAP *ld );
^
openldap.c:210:17: error: static declaration of 'ldap_connect' follows non-static declaration
static CURLcode ldap_connect(struct Curl_easy *data, bool *done)
                ^
/usr/local/opt/openldap/include/ldap.h:1554:1: note: previous declaration is here
ldap_connect( LDAP *ld );
^
/bin/sh ../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H   -I../include -I../lib -I../lib  -DBUILDING_LIBCURL  -DCURL_HIDDEN_SYMBOLS -isystem /usr/local/Cellar/openssl@1.1/1.1.1k/include -isystem /usr/local/Cellar/openssl@1.1/1.1.1k/include -isystem /usr/local/Cellar/libssh2/1.9.0_1/include -isystem /usr/local/Cellar/openssl@1.1/1.1.1k/include -isystem /usr/local/Cellar/rtmpdump/2.4+20151223_1/include -isystem /usr/local/Cellar/libidn2/2.3.0/include -isystem /usr/local/Cellar/nghttp2/1.43.0/include  -fvisibility=hidden -Qunused-arguments -Os -Werror=partial-availability  -c -o libcurl_la-pop3.lo `test -f 'pop3.c' || echo './'`pop3.c
2 errors generated.
```

**Comment by cho-m** [comment]
`curl` upstream issue: curl/curl#7004

May want to see if fix patches cleanly: https://github.com/curl/curl/commit/8bdde6b14ce3b5fd71c772a578fcbd4b6fa6df19

**Comment by nandahkrishna** [comment]
Thanks @cho-m, the patch applies cleanly.

On ARM:
```
brew install php
brew install php@7.4
brew test --retry --verbose phpunit
```

**Comment by cho-m** [comment]
I guess those `php` formulas need revision bumps too.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
