### PR TITLE
apache-arrow apache-arrow-glib 14.0.0

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  Broken dependencies:
    /opt/homebrew/opt/llvm@15/lib/libLLVM.dylib (llvm@15)
```

**Comment by p-linnane** [comment]
Opened an upstream issue: https://github.com/v6d-io/v6d/issues/1608

**Comment by sighingnow** [comment]
> Opened an upstream issue: [v6d-io/v6d#1608](https://github.com/v6d-io/v6d/issues/1608)

Thanks for reporting. I have fixed it in vineyard and bump-up the version here: https://github.com/Homebrew/homebrew-core/pull/153132

**Comment by sighingnow** [comment]
Hi @p-linnane would you mind to rebase this pr against main? as #153132 has been merged.

**Comment by p-linnane** [comment]
Thank you @sighingnow. I've rebased with the new version of `vineyard`.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
