### PR TITLE
eject 0.1.23

### PR DESCRIPTION
**Pull request by KingOfBrian**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Test is failing: https://bot.brew.sh/job/Homebrew%20Core/11969/version=any_sierra/testReport/junit/brew-test-bot/sierra/test_eject/

**Comment by edwardloveall** [comment]
@KingOfBrian Looks like you just need to update the output of the xib. Copy and paste the xml inside the formula and save it as `view.xib` or whatever, then run it through eject. Paste that output into the formula for the swift code and run `brew test eject` to make sure it passes.

**Comment by MikeMcQuaid** [comment]
@edwardloveall If this is going to change often it may be worth matching on a substring or using a simpler XIB?

**Comment by edwardloveall** [comment]
@MikeMcQuaid it's actually the simplest xib I could create from Xcode. It's not a huge change to the swift code so I don't see it being a big problem, even if it changes often. Also, as the tool matures I'm sure the swift output will settle down.

**Comment by KingOfBrian** [comment]
Thanks @edwardloveall and @MikeMcQuaid -- I updated the expected output, and it's passing `brew test eject`. Thanks for the help, my first brew work. I'll make sure I verify test before future updates!

**Comment by mistydemeo** [comment]
Thanks, merged!

For future references we prefer fix commits like the "fix output" commit to be squashed into the primary commit.

**Comment by MikeMcQuaid** [comment]
@edwardloveall Cool, no worries!

**Pull request closed without merging**
