### PR TITLE
netdata 1.34.1

### PR DESCRIPTION
**Pull request by rickard-von-essen**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
This currently fails to start on _Big Surr_

**Comment by rickard-von-essen** [comment]
Native installer also fails on macOS, see https://github.com/netdata/netdata/issues/12717

**Comment by cho-m** [comment]
One issue is `post_install` failed while modifying `netdata/netdata.conf`, which usually means the file was changed and regex pattern no longer matches for inreplace

This then means that `(var/"cache/netdata/unittest-dbengine/dbengine").mkpath` was never run, so the `var/"cache/netdata"` directory does not exist during test:
```
2022-04-19 01:22:11: netdata ERROR : MAIN : uv_fs_scandir(/opt/homebrew/var/cache/netdata): no such file or directory (errno 2, No such file or directory)
```

**Review by chenrui333 — APPROVED** [review]

**Comment by rickard-von-essen** [comment]
@chenrui333 actually this is broken on Big Surr it SIGABRT. Can we revert this? Should I create a PR for that?

(I'm working on a fix but it will take some more days)

**Pull request closed without merging**
