### PR TITLE
qemu 5.1.0

### PR DESCRIPTION
**Pull request by roolebo**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by roolebo** [comment]
I have no idea why GPL-2.0 is considered a deprecated license :) It's used by Linux and QEMU which are far from being deprecated.

**Comment by gromgit** [comment]
The license isn't deprecated, the `GPL-2.0` license ID is. See the list at https://spdx.org/licenses/.

According to the [overall QEMU license](https://git.qemu.org/?p=qemu.git;a=blob_plain;f=LICENSE;hb=HEAD) the appropriate license ID should be `GPL-2.0-only`.

**Comment by roolebo** [comment]
@gromgit thanks! I will update it.

**Comment by roolebo** [comment]
@gromgit I'm getting response on qemu IRC, it's actually a mix of licenses: "2 months ago I started to look at that, I found the following: BSD, BSD-2-Clause, BSD-3-Clause, GCC, LGPL-2.0-only, LGPL-2.0-or-later, LGPL-2.1-or-later, GPL-2.0-only, GPL-2.0-or-later, GPL-3.0-or-later, plus 2 or 3 combinations of dual licenses"

**Comment by roolebo** [comment]
@gromgit here's the value of qemu license tag on SLES: "BSD-3-Clause AND GPL-2.0-only AND GPL-2.0-or-later AND LGPL-2.1-or-later AND MIT"

**Comment by gromgit** [comment]
From the main license file:

> The QEMU emulator as a whole is released under the GNU General Public License, version 2.

Since Homebrew uses the product as a whole, rather than specific source files that may have other licenses, the overall license should apply.

**Review by SMillerDev — APPROVED** [review]
Thanks @roolebo  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
