### PR TITLE
kustomize 3.0.0

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
I opened an [issue upstream](https://github.com/kubernetes-sigs/kustomize/issues/1311).

**Comment by darklore** [comment]
Package name has been updated.
https://github.com/kubernetes-sigs/kustomize/blob/v3.0.0/releasing/goreleaser.yaml#L11
So we should add "v3" to ldflags too.
https://github.com/Homebrew/homebrew-core/blob/master/Formula/kustomize.rb#L29-L31

**Comment by igas** [comment]
Thank you for spotting this @darklore!

**Comment by Moisan** [comment]
Closing my upstream issue then :).

**Pull request closed without merging**
