### PR TITLE
postgresql 11.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`libpqxx` needs a revision bump

**Comment by chenrui333** [comment]
Bump PR, https://github.com/Homebrew/homebrew-core/pull/41181

**Comment by SMillerDev** [comment]
Needs to be in the same pr or CI will fail

**Comment by fxcoudert** [comment]
Yes, please apply the libpqxx 6.4.5 update as a second commit in this same PR.

**Comment by chenrui333** [comment]
```
23:20:06 running bootstrap script ... 2019-06-22 16:20:05.010 BST [9958] FATAL:  could not create shared memory segment: No space left on device
23:20:06 2019-06-22 16:20:05.010 BST [9958] DETAIL:  Failed system call was shmget(key=5432001, size=56, 03600).
23:20:06 2019-06-22 16:20:05.010 BST [9958] HINT:  This error does *not* mean that you have run out of disk space.  It occurs either if all available shared memory IDs have been taken, in which case you need to raise the SHMMNI parameter in your kernel, or because the system's overall limit for shared memory has been reached.
23:20:06 	The PostgreSQL documentation contains more information about shared memory configuration.
23:20:06 child process exited with exit code 1
23:20:06 initdb: removing data directory "/private/tmp/postgrest-test-20190622-9897-1lyirj/test_postgrest_formula"
23:20:06 Error: postgrest: failed
23:20:06 Failed executing:
23:20:06 /usr/local/Homebrew/Library/Homebrew/formula.rb:1914:in `block in system'
```

**Comment by chenrui333** [comment]
looks like the shared memory shortage on the machine?

**Comment by fxcoudert** [comment]
I don't think that has changed, so not sure why this is failing.

**Comment by chenrui333** [comment]
refreshed `libpqxx`

**Comment by chenrui333** [comment]
06:33:11 ==> brew pull --clean https://github.com/Homebrew/homebrew-core/pull/41161
06:33:13 ==> FAILED
06:33:13 fatal: ref HEAD is not a symbolic ref
06:33:13 ==> Fetching patch 
06:33:13 Patch: https://github.com/Homebrew/homebrew-core/pull/41161.patch
06:33:13 ==> Applying patch
06:33:13 Applying: postgresql 11.4
06:33:13 Applying: libpqxx: revision for postgresql
06:33:13 Using index info to reconstruct a base tree...
06:33:13 M	Formula/libpqxx.rb
06:33:13 Falling back to patching base and 3-way merge...
06:33:13 Auto-merging Formula/libpqxx.rb
06:33:13 CONFLICT (content): Merge conflict in Formula/libpqxx.rb
06:33:13 error: Failed to merge in the changes.
06:33:13 Patch failed at 0002 libpqxx: revision for postgresql
06:33:13 hint: Use 'git am --show-current-patch' to see the failed patch
06:33:13 When you have resolved this problem, run "git am --continue".
06:33:13 If you prefer to skip this patch, run "git am --skip" instead.
06:33:13 To restore the original branch and stop patching, run "git am --abort".
06:33:13 Error: Patch failed to apply: aborted.
06:33:14 Homebrew/brew 2.1.6-22-g3cef10889 (Merge pull request #6249 from MikeMcQuaid/rubocop-performance-fixes)
06:33:14 
06:33:14 Testing tap homebrew/core with:
06:33:14   origin/master   e06f16ebc0 (gitlab-runner: update 12.0.0 bottle.)
06:33:14   HEAD            e06f16ebc0 (gitlab-runner: update 12.0.0 bottle.)
06:33:14   diff_start_sha1 e06f16ebc0
06:33:14   diff_end_sha1   e06f16ebc0

**Comment by fxcoudert** [comment]
Capture d’écran 2019-06-28 à 23 06 52

We don't use merge commits, otherwise CI doesn't know how to deal with them. You need to rebase as two commits on top of clean master.

**Comment by chenrui333** [comment]
I see. I will rebase my commits.

**Comment by chenrui333** [comment]
This PR is good for merge?

**Comment by xeron** [comment]
@chenrui333 this change fails to build on 10.14 due to MacOS `perl.h` location. Could be fixed by using homebrew perl or by removing `--with-perl`.

**Pull request closed without merging**
