### PR TITLE
folly 2021.06.28.00, fizz wangle 2021.07.05.00, watchman 2021.07.12.00

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
`watchman` follows a similar release schedule, so we should bump it too along with `folly`, `fizz`, and `wangle`.

**Comment by carlocab** [comment]
Looks like `watchman` still doesn't build.

**Comment by EricFromCanada** [comment]
wangle 2021.07.05.00 is out.

**Comment by chenrui333** [comment]
Sounds good, let's give the new release a try.

**Comment by carlocab** [comment]
`fizz` and `wangle` are actually on 2021.07.12.00 now, but let's see if this builds first...

**Comment by carlocab** [comment]
Still fails, sadly:
```
In file included from /tmp/watchman-20210717-10638-1ni1blh/watchman-2021.07.12.00/watchman/tests/PendingCollectionTest.cpp:4:
In file included from /tmp/watchman-20210717-10638-1ni1blh/watchman-2021.07.12.00/watchman/PendingCollection.h:10:
/tmp/watchman-20210717-10638-1ni1blh/watchman-2021.07.12.00/watchman/watchman_string.h:114:16: error: no member named 'data' in 'watchman_pending_fs'
      : s_(str.data()), e_(str.data() + str.size()) {}
           ~~~ ^
/opt/homebrew/include/gtest/gtest-printers.h:215:12: note: in instantiation of function template specialization 'w_string_piece::w_string_piece<watchman_pending_fs, 0>' requested here
    *os << value;
           ^
/opt/homebrew/include/gtest/gtest-printers.h:312:12: note: in instantiation of function template specialization 'testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter::PrintValue<watchman_pending_fs, void, std::__1::basic_ostream<char> &>' requested here
  Printer::PrintValue(value, os);
           ^
/opt/homebrew/include/gtest/gtest-printers.h:441:13: note: in instantiation of function template specialization 'testing::internal::PrintWithFallback<watchman_pending_fs>' requested here
  internal::PrintWithFallback(value, os);
            ^
/opt/homebrew/include/gtest/gtest-printers.h:691:5: note: in instantiation of function template specialization 'testing::internal::PrintTo<watchman_pending_fs>' requested here
    PrintTo(value, os);
    ^
/opt/homebrew/include/gtest/gtest-printers.h:617:26: note: in instantiation of member function 'testing::internal::UniversalPrinter<watchman_pending_fs>::Print' requested here
    UniversalPrinter<T>::Print(*ptr, os);
                         ^
```

**Comment by bevanjkay** [comment]
All formulae are now at `2021.07.20.00`

**Comment by carlocab** [comment]
Continued in #81599.

**Pull request closed without merging**
