### PR TITLE
platypus: add homebrew-cask to caveat

### PR DESCRIPTION
**Pull request by vitorgalvao**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Refs https://github.com/Homebrew/homebrew-core/issues/1950.

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/b9dca474ba3d85b8bf7429b9b4f2a1997f1fd148. Thanks for changing these to match the preferred style, appreciate that.

**Comment by vitorgalvao** [comment]
> Thanks for changing these to match the preferred style, appreciate that.

When there are thousands of files that share a structure, the smallest divergence makes it that much harder to parse when we’re looking at a bunch of them. I’m nitpicky about that as well.

**Comment by DomT4** [comment]
A lot of it is making things easy for new contributors as well. Despite us having various templates & documentation overwhelming what people do when they want to find answers on how to do something is check other formulae. All it takes is a few deviations for it to start spreading, and then you lose control of the preferred style.

I regularly make people eye roll with pickiness, but I try to be fussy for a reason rather than just because.

**Comment by vitorgalvao** [comment]
> I regularly make people eye roll with pickiness

We try to enforce style rules with [`rubocop-cask`](https://github.com/caskroom/rubocop-cask). Having a Travis build fail because the style wasn’t followed and a command to automatically fix it (`brew cask style --fix`) in general seems to work in decreasing eye rolls.

**Pull request merged**
