### PR TITLE
pcalc 2.0.1 (new formula)

### PR DESCRIPTION
**Pull request by alt-romes**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Add formula for [pcalc](https://github.com/alt-romes/programmer-calculator)

### CODE REVIEW

**Comment by alt-romes** [comment]
I'll retry in 3 days, when the repository is old enough to pass the tests :)

**Review by SMillerDev — DISMISSED** [review]
Thanks @alt-romes  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by SMillerDev** [comment]
@alt-romes can you squash all your commits into one `pcalc 2.0.1 (new formula)` please.

**Comment by alt-romes** [comment]
It should be alright now, and thank you 👍 🎉 !

**Pull request closed without merging**
