### PR TITLE
selenium-server 4.14.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by iMichka** [comment]
Not a release yet: https://github.com/SeleniumHQ/selenium/releases

**Comment by chenrui333** [comment]
it is actually latest release, the artifact is in the 4.14 release

image

**Comment by chenrui333** [comment]
it is actually latest release, the artifact is in the 4.14 release

Releases_·_SeleniumHQ_selenium

**Review by p-linnane — APPROVED** [review]
That's an awful way to do releases 🤦‍♂️

**Pull request merged**
