### PR TITLE
sqlite 3.35.5

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Tests failing:
[x] bcoin
[x] bpytop
[x] cargo-edit 
[ ] cash-cli upstream issue https://github.com/xxczaki/cash-cli/issues/79
[x] dnstwist
[x] dprint
[ ] gitup #75636
[ ] global
[ ] hsd
[ ] hyperkit
[ ] opencascade
[ ] pipx
[ ] rustscan
[ ] sslyze
[ ] swift
[ ] topgrade
[ ] wasm-pack
[ ] xxh
[ ] youtube-dlc

**Comment by carlocab** [comment]
Rebased to pull in some more fixes (e.g. `cash-cli`), plus the ARM runner crashed for some reason anyway.

**Comment by carlocab** [comment]
Mojave:
```
Error: 8 failed steps!
brew bottle --verbose --json sqlite --only-json-tab
brew test --retry --verbose caffe
brew test --retry --verbose global
brew test --retry --verbose hyperkit
brew test --retry --verbose opencascade
brew test --retry --verbose swift
brew test --retry --verbose wasm-pack
brew test --retry --verbose youtube-dlc
```
Other nodes look similar, sans the `bottle` failure. Other than the `bottle` failure I'd say this would've been good to merge.

**Review by carlocab — APPROVED** [review]
`bottle` failure should be fixed. Restarting CI, and barring any more weirdness, this should be good to merge when it's done.

**Comment by carlocab** [comment]
`llvm@11`: #76030

**Comment by carlocab** [comment]
Failures look nearly identical to #76174, so I doubt they're caused by the version bump. Merging.

**Pull request closed without merging**
