### PR TITLE
luyten: migrate to gui

### PR DESCRIPTION
**Pull request by ilovezfs**
See discussion here: https://github.com/Homebrew/homebrew-core/pull/3357#discussion_r72778372

CC @UniqMartin @DomT4

### CODE REVIEW

**Comment by UniqMartin** [comment]
:+1:

> CC @UniqMartin @DomT4

We don't get a notification if you retroactively add this. :wink: (But maybe this was intentional?)

**Comment by DomT4** [comment]
I kind of hate migrating things to taps other than the 💀-yard these days given how badly looked after taps have become, but if this is untestable in a sane way I guess this is fine.

**Comment by ilovezfs** [comment]
>We don't get a notification if you retroactively add this. :wink: (But maybe this was intentional?)

@UniqMartin Ug. No, not intentional. That's somewhat annoying.

>I kind of hate migrating things to taps other than the :skull:-yard these days given how badly looked after taps have become, but if this is untestable in a sane way I guess this is fine.

@DomT4 The best we can do, I think, is verifying either there are no exceptions or there is a HeadlessException and an exit status of 0. I'm happy to throw that in if you'd prefer to keep this in core.

**Comment by DomT4** [comment]
It's entirely GUI based, I think it's fair enough to relocate it, just anxious about us seemingly using taps more often than not to ditch software we don't love very much & it then gets universally ignored. Not a criticism of you or this PR; a broader concern I've voiced quite a few times by now.

**Comment by ilovezfs** [comment]
@DomT4 Have you seen https://en.wikipedia.org/wiki/It's_a_Good_Life_%28The_Twilight_Zone%29

It definitely does feel like we're wishing them into a cornfield.

**Comment by DomT4** [comment]
😄 It's alright, some of our formulae are already _"grotesque, walking horror"s_ 😉

**Comment by ilovezfs** [comment]
>some

understatement of the year?

**Pull request closed without merging**
