### PR TITLE
heroku 6.12.11

### PR DESCRIPTION
**Pull request by jdx**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@dickeyxxx the build failed https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/4915/version=sierra/testReport/junit/brew-test-bot/sierra/install_heroku/

**Comment by dickeyxxx** [comment]
can you run it again?

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
Thanks @dickeyxxx! Shipped!

**Pull request closed without merging**
