### PR TITLE
gpg1: gpgkeys_* are called without the suffix

### PR DESCRIPTION
**Pull request by tcely**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 thoughts?

**Comment by DomT4** [comment]
I don't entirely understand OP's desire to tweak this in terms of a major upside but there's no harm to the proposed changes; even without the suffix they wouldn't bump into anything from the primary `gnupg` formula if both were in the same `$PATH`.

**Comment by tcely** [comment]
The `gpg1` binary has the libexec/"gnupg" directory hard-coded and calls those binaries without the suffix. Adding the symbolic links to the binaries that were installed with the suffix for the names `gpg1` uses allows `gpg1` to fetch keys from a key server.

Without those links it will just complain that `gpgkeys_curl` doesn't exist in that directory (or similar for `gpgkeys_hkp` too).

This isn't related to `PATH` in any way since these are both in the `libexec` directory. `gpgbin` might be put into the `PATH` by the user, but the results in that directory aren't changing so that's neither here nor there.

**Comment by DomT4** [comment]
> Without those links it will just complain that gpgkeys_curl doesn't exist in that directory (or similar for gpgkeys_hkp too).

Thanks, _that's_ the information I was after. I've abandoned the 1.4 branch for personal use so it's been a while since I've had to touch any of that. Throwing the more detailed explanation into the commit message or something next time would be a useful step.

> This isn't related to PATH in any way since these are both in the libexec directory. gpgbin might be put into the PATH by the user, but the results in that directory aren't changing so that's neither here nor there.

Eh. Never underestimate the weird & wonderful things users will do, given even the smallest chance.

**Comment by tcely** [comment]
I threw the detailed explanation into the commit message.

**Review by DomT4 — APPROVED** [review]

**Comment by tcely** [comment]
@ilovezfs Please update the status. The changes were reviewed and approved.

**Comment by DomT4** [comment]
This is still fine with me FWIW Joe.

**Comment by tcely** [comment]
Is there a label that can be applied to this so that stale bot doesn't email me about this? I know you want us to be patient about pull requests, but having the bot pester me seems backwards to me. ;-)

**Comment by zbeekman** [comment]
@DomT4 are we still waiting for @ilovezfs or should we merge this? FWIW, LGTM.

**Review by zbeekman — APPROVED** [review]
I vote we 🚢 it. Do we need to wait for any reason?

**Comment by DomT4** [comment]
It'll need to go back through CI at this point to get a new bottle but once that's done it can go in.

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Would you mind sticking a `revision 1` underneath the `sha256` line? That's the last thing I think needs doing here.

**Comment by tcely** [comment]
@DomT4 Is that the line you're looking for?

**Comment by DomT4** [comment]
Would you mind rebasing this against an up-to-date master branch as well? Apologies to be a pain; the conflict was only just pointed out to me by the web UI here 🙃.

**Comment by tcely** [comment]
@DomT4 All set

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/8319ffd314cb39db9ef920f5b138b74f0255aad7. Thank you for your contribution to Homebrew @tcely; we appreciate it!

**Pull request closed without merging**
