### PR TITLE
carthage 0.34.0

### PR DESCRIPTION
**Pull request by jdhealy**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Review by mendesbarreto — APPROVED** [review]

**Comment by jdhealy** [comment]
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/50240/version=catalina/console

> 15:52:28 *** Cloning xcconfigs
> 15:52:28 A shell task (/usr/bin/env git clone --bare --quiet https://github.com/jspahrsummers/xcconfigs.git /private/tmp/carthage-test-20191021-55452-mk3td5/.carthage/dependencies/xcconfigs) failed with exit code 128:
> 15:52:28 fatal: the remote end hung up unexpectedly

I'm wondering if there was a network blip…

@mendesbarreto, is it possible for you to re-kick the Catalina job?

**Comment by jdhealy** [comment]
@chenrui333, apologies don't quite know who to ask — could you re-kick [the Catalina job](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/50240/version=catalina/console)?

**Comment by dawidd6** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
This is great, thanks @jdhealy

**Pull request closed without merging**
