### PR TITLE
vault 1.1.0

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
Revision bump for `safe` probably needed.

**Comment by janbrunrasmussen** [comment]
What is blocking this?

**Comment by SMillerDev** [comment]
Safe breaking when we merge this is blocking. @igas can you check if it's a known issue?

**Comment by thenoid** [comment]
Give unto me

**Comment by igas** [comment]
Yeah, safe is the problem for every vault release. And we know their response https://github.com/starkandwayne/safe#attention-homebrew-users

**Pull request closed without merging**
