### PR TITLE
ghostscript 9.20

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dunn** [comment]
Just a revision bump for libspectre, looks like.

**Comment by forkbomber** [comment]
Ghostscript 9.19 from master fails during patching on 10.12:

```
patching file base/unix-dll.mak
Hunk #1 FAILED at 64.
1 out of 1 hunk FAILED -- saving rejects to file base/unix-dll.mak.rej
==> Kept temporary files
Temporary files retained at /tmp/ghostscript-20161017-7580-pdxnip
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1
```

This PR branch installs successfully.

**Comment by ilovezfs** [comment]
@forkbomber that's a regression caused by 1e62c645

**Comment by forkbomber** [comment]
@ilovezfs yes, I hope that would expedite this PR :)

**Comment by ilovezfs** [comment]
actually it's causing a re-review of 1e62c64 since this isn't the only one affected :(

**Comment by ilovezfs** [comment]
This release breaks  the `djvu` option, and the problem has not been fixed in `djvu` head yet.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by dunn** [comment]
libspectre needs revisioning as per usual.

**Comment by ilovezfs** [comment]
@dunn should we just kill the djvu option?

**Comment by dunn** [comment]
Fine with me, unless analytics show it's being used a ton.

**Comment by MikeMcQuaid** [comment]
Not seeing any installs in the last month using that option.

**Comment by sevenfx** [comment]
I'm having trouble installing ghostscript on mac sierra using `brew install ghostscript` -- any suggestions?

Here's the failure:
```
==> ./configure --prefix=/usr/local/homebrew/Cellar/ghostscript/9.19 --disable-cups --disable-compile-inits --disable-gtk
==> make install
Last 15 lines from /Users/sevenfx7/Library/Logs/Homebrew/ghostscript/02.make:
rm: /usr/local/homebrew/Cellar/ghostscript/9.19/share/ghostscript/9.19/lib: is a directory
```

**Comment by MikeMcQuaid** [comment]
@sevenfx `brew update` and try again. If that still fails, please create a new issue. Thanks!

**Pull request closed without merging**
