### PR TITLE
jboss-forge 3.9.7.Final

### PR DESCRIPTION
**Pull request by gastaldi**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
18:27:13 ==> brew audit jboss-forge --online
18:27:36 ==> FAILED
18:27:36 Error: 1 problem in 1 formula detected
18:27:36 jboss-forge:
18:27:36   * Stable: version 3.9.7.Final is redundant with version scanned from URL
```

**Comment by gastaldi** [comment]
Have this changed recently? I've followed the same.procedures since ever to update it

**Comment by Bo98** [comment]
Yes, we've made some improvements to the version-detection system. You can remove the `version "3.9.7.Final"` as it is now able to be detected from the URL.

**Comment by chenrui333** [comment]
CI hiccup

@BrewTestBot test this please

**Comment by chenrui333** [comment]
Thanks @gastaldi!!

**Pull request merged**
