### PR TITLE
tbb 2021.8.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by equal-l2** [comment]
`caffe` failed due to network flakiness.

**Comment by chenrui333** [comment]
we have rerun three times, still the regression failure on 11 runner.
image

**Comment by equal-l2** [comment]
I checked every failure and found they are because of `connection reset by peer` (errno 54).
Maybe it is worth implementing retrying feature to `brew`.

**Comment by cho-m** [comment]
> I checked every failure and found they are because of `connection reset by peer` or `SSL_read: SSL_ERROR_SYSCALL` (both indicate `errno 54`).
> Maybe it is worth implementing retrying feature in the fetch stage to `brew`.

I had discussed this with other maintainers on Slack and `brew fetch` does retry but we currently don't get the dependencies there. Instead, we get them during `brew install --only-dependencies` which doesn't retry.

Needs a fix in homebrew-test-bot to pass do `brew fetch --deps` instead.

**Comment by chenrui333** [comment]
networking failure on `11` runner for `caffe` build
```
  curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
```

**Comment by chenrui333** [comment]
Merging as it is just networking failure. (formula has already been regression tested in other builds)

**Pull request closed without merging**
