### PR TITLE
dasht 2.2.0

### PR DESCRIPTION
**Pull request by JCount**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by JCount** [comment]
I blame https://github.com/Homebrew/homebrew-core/pull/14000 😑


.........

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/16847
https://github.com/Homebrew/homebrew-core/pull/16859
https://github.com/sunaku/dasht/issues/24

We'll probably just need to remove it.

```
Josephs-MacBook-Pro:~ joe$ brew formula-analytics dasht
install events in the last 30 days for dasht
================================================================================
1 | dasht                                                          | 1 | 100.00%
================================================================================
Total                                                              | 1 |    100%
================================================================================
Josephs-MacBook-Pro:~ joe$ 
```

**Comment by daleeidd** [comment]
Is there any way to keep this formula? I have the latest `wget` installed via Homebrew, and this formula installs fine for me. I do not believe it is a tenable position to remove modern formulas just because there are legacy dependency conflicts for some.

**Comment by ilovezfs** [comment]
@daleeidd yes, you can submit a pull request to upstream to get it using `curl`.

**Comment by daleeidd** [comment]
@ilovezfs I would like to try and address the more fundamental problem of not being able to use dependencies that may be more suited to the formula's use case like using `wget` over `curl`.

I thought one of the main benefits of Homebrew was that we could install and use the latest software; hence why most people use it to install the latest `git`. Doesn't requiring a formula to use a particular dependency go against that? Isn't solving the problem of using `wget` as a dependency raising a red flag for Homebrew – when `wget` itself installs fine – the real issue that should be address?

**Comment by ilovezfs** [comment]
@daleeidd we do not allow mixing openssl versions in dependency trees. Since we're not going to switch wget back to openssl from openssl@1.1, dasht needs to use curl. There's nothing that wget can do in this case that curl cannot, so I'm not eager to switch dasht's other dependencies to openssl just to accommodate the unnecessary use of wget, which we really shouldn't even alllow as a dependency.

**Comment by ilovezfs** [comment]
`socat` builds successfully with `openssl@1.1`.

`w3m` does not:
```
When you exit this shell, you will return to the menu.
bash-3.2$ make -j1
(cd libwc && make CC='clang' OPTS='')
make[1]: Nothing to be done for `all'.
clang  -I. -I. -g -O2 -I./libwc -I/usr/local/Cellar/openssl@1.1/1.1.0f/include  -DHAVE_CONFIG_H -DAUXBIN_DIR=\"/usr/local/Cellar/w3m/0.5.3/libexec/w3m\" -DCGIBIN_DIR=\"/usr/local/Cellar/w3m/0.5.3/libexec/w3m/cgi-bin\" -DHELP_DIR=\"/usr/local/Cellar/w3m/0.5.3/share/w3m\" -DETC_DIR=\"/usr/local/Cellar/w3m/0.5.3/etc\" -DCONF_DIR=\"/usr/local/Cellar/w3m/0.5.3/etc/w3m\" -DRC_DIR=\"~/.w3m\" -DLOCALEDIR=\"/usr/local/Cellar/w3m/0.5.3/share/locale\" -o w3m main.o file.o buffer.o display.o etc.o search.o linein.o table.o local.o form.o map.o frame.o rc.o menu.o mailcap.o image.o symbol.o entity.o terms.o url.o ftp.o mimehead.o regex.o news.o func.o cookie.o history.o backend.o keybind.o anchor.o parsetagx.o tagtable.o istream.o version.o   -L. -lindep  -lgc -L./libwc -lwc -L/usr/local/Cellar/openssl@1.1/1.1.0f/lib -lssl -lcrypto -lssl -lcrypto -ltermcap
Undefined symbols for architecture x86_64:
  "_RAND_egd", referenced from:
      _openSSLHandle in url.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [w3m] Error 1
```

**Comment by daleeidd** [comment]
Fair enough. Thank you for clarifying the issue. I do not know the exact issue with mixing versions of OpenSSL in the dependency tree, but I am sure there is a good reason for that rule.

**Comment by ilovezfs** [comment]
@daleeidd It looks like Debian has a patch for openssl@1.1 for w3m. So I will use that :)

**Comment by daleeidd** [comment]
@ilovezfs Excellent. Thank you. If it doesn't work, just let me know and I will work on using `curl` for `dasht`.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@daleeidd https://github.com/Homebrew/homebrew-core/pull/17285 and https://github.com/Homebrew/homebrew-core/pull/17286 are merged, so this should be :green_apple: now.

**Comment by ilovezfs** [comment]
Yup, it's :green_heart:. Merged.

**Pull request merged**
