### PR TITLE
hss 1.8

### PR DESCRIPTION
**Pull request by six-ddc**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
_Maintainers, please do not merge before https://github.com/Homebrew/homebrew-core/pull/35778 is merged._

**Comment by fxcoudert** [comment]
Can you please rebase on top of current master? Thanks

**Comment by six-ddc** [comment]
@fxcoudert done

**Comment by fxcoudert** [comment]
Hum, it doesn't apply cleanly. Can you squash the two commits into a single commit on top of master?

**Comment by six-ddc** [comment]
Look troublesome, maybe I should create new PR, Thanks.

**Pull request closed without merging**
