### PR TITLE
gitversion 5.8.0

### PR DESCRIPTION
**Pull request by arturcic**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
```
/usr/local/Cellar/dotnet/5.0.207/libexec/sdk/5.0.207/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. 
```
I guess this needs a newer `dotnet`?

**Comment by arturcic** [comment]
Yes, @asbjornu is working on it

**Comment by asbjornu** [comment]
Looks like [.NET 6 isn't tagged in `source-build`](https://github.com/dotnet/source-build/tags) yet. 😕

**Comment by arturcic** [comment]
@asbjornu seems like there are some instructions on how to build for 6.0 version https://github.com/dotnet/source-build#building. It seems the tag is on the [dotnet/installer](https://github.com/dotnet/installer) repository instead

**Comment by asbjornu** [comment]
Yes, I've started poking at it in https://github.com/dotnet/source-build/issues/2602#issuecomment-967621779. :)

**Comment by asbjornu** [comment]
An `in progress` label would be appreciated.

**Comment by chenrui333** [comment]
Any update on this, looks like 5.8.1 should be the latest?

**Comment by carlocab** [comment]
It's blocked until we have dotnet 6, I think.

**Comment by arturcic** [comment]
Yes it is blocked. We need the dotnet 6

**Comment by asbjornu** [comment]
I've started rebuilding the Homebrew formula for .NET 6, but as you can see from https://github.com/dotnet/installer/issues/12871, I've run into issues. Once they are all ironed out, we should be good to go.

**Comment by asbjornu** [comment]
#92991 submitted.

**Comment by cho-m** [comment]
`gitversion` is going to have to be updated in same PR as `dotnet` due to dependent testing.

I added `gitversion 5.8.1` to #92991.

Also noting that my local attempt at building on M1 via `--runtime osx-arm64` failed with AppHost error as commented in the other PR. It may be picking the wrong framework version, but not sure why. Can revisit separately as I think CI should ignore ARM failures when there is no existing bottle.

**Comment by cho-m** [comment]
Closing as commit has been cherry-picked into #92991. May need some help triaging why ARM isn't building.

**Pull request closed without merging**
