### PR TITLE
pdns: update pdns to accept remote backend option.

### PR DESCRIPTION
**Pull request by csawyerYumaed**
add option for remote backend.
I rarely write ruby, so this maybe can be done better, I have no idea, but it works for me.

- [ X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@Habbie any thoughts here? Also, is there a way to build this both backends so we can avoid adding an option?

**Comment by Habbie** [comment]
Building with both backends just involves a string contatenation. In related news https://github.com/PowerDNS/pdns/issues/5607 complains that the mysql backend is not available.

**Comment by Habbie** [comment]
We could also build with all backends that are feasible in terms of brew dependencies, but I suspect not all users would like pdns pulling in 20 deps if they don't care about all these backends. Opinions on this balance?

**Comment by csawyerYumaed** [comment]
I would think being able to select backends using --with-<BLAH>, would be better, since, besides me, there seems to be zero call for any of the other backends.

**Comment by ilovezfs** [comment]
@Habbie I didn't realize there were so many choices 🙈

**Comment by ilovezfs** [comment]
Thanks for the PR @csawyerYumaed!

**Pull request merged**
