### PR TITLE
tmuxinator 3.0.4

### PR DESCRIPTION
**Pull request by Altynai**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Thanks @Altynai, for our CI and merge process we need one change: one commit per formula: `tmuxinator 3.0.4` and `tmuxinator-completion 3.0.4` (although it's unclear to me why we have a separate and conflicting formula for the completion itself)…

**Comment by Altynai** [comment]
@fxcoudert good catch, I think only bumping `tmuxinator` should be good enough, updated the pr accordingly

**Comment by fxcoudert** [comment]
No, please update both, but in two separate commits in the same PR

**Comment by Altynai** [comment]
@fxcoudert fixed

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
