### PR TITLE
Add requests-credssp package to ansible formula

### PR DESCRIPTION
**Pull request by jkroepke**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
See #38795

### CODE REVIEW

**Comment by jkroepke** [comment]
Did I miss something?

**Review by jonchang — CHANGES_REQUESTED** [review]
Thanks for the pull request @jkroepke. Please add `revision 1` so that users will get this change when they run `brew upgrade`.

**Comment by jkroepke** [comment]
Done

**Comment by jonchang** [comment]
Please address this audit message

```
22:22:18 ==> brew audit ansible --online
22:23:45 ==> FAILED
22:23:45 Error: 1 problem in 1 formula detected
22:23:45 ansible:
22:23:45   * C: 9: col 3: `revision` (line 9) should be put before `head` (line 8)
```

**Comment by fxcoudert** [comment]
Thanks @jkroepke, merging

**Pull request closed without merging**
