### PR TITLE
theharvester 3.0.1

### PR DESCRIPTION
**Pull request by igas**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Fails during test.

**Comment by apjanke** [comment]
I can reproduce the test failure manually using this PR, but not on master.

It looks like this is a regression/change in behavior from theharvester 2.7 to 3.0. Version 2.7 picks up a few emails from the brew.sh site; version 3.0 picks up none.

```
$ /usr/local/Cellar/theharvester/2.7/bin/theharvester -d brew.sh -l 1 -b all 2>&1
[...]
Full harvest..
[-] Searching in Google..
	Searching 0 results...
[-] Searching in PGP Key server..
[-] Searching in Bing..
	Searching 50 results...
[-] Searching in Exalead..
	Searching 50 results...


[+] Emails found:
------------------
[...]
pixel-1541719418116020-web-@brew.sh
security@brew.sh
```

```
$ /usr/local/Cellar/theharvester/3.0/bin/theharvester -d brew.sh -l 1 -b all 2>&1 | cat
[...]
Full harvest on brew.sh
[-] Searching in Google..
	Searching 0 results...
[-] Searching in PGP Key server..
	Searching PGP results...
[-] Searching in Netcraft server..
	Searching Netcraft results..
[-] Searching in ThreatCrowd server..
	Searching Threatcrowd results..
	Searching Netcraft results..
[-] Searching in CRTSH server..
	Searching CRT.sh results..
[-] Searching in Virustotal server..
	Searching Virustotal results..
[-] Searching in Bing..
	Searching 50 results...
[...]
[+] Emails found:
------------------
No emails found
```

Comparing the list of data sources from theharvester 2.7 to 3.0, looks like Exalead was removed. Perhaps the email results were coming from there.

Generally it's not Homebrew's job to closely police package behavior; the `brew test` is just a smoke test to make sure our build work and the package is working as designed. I'd suggest modifying the test so it passes under the new 3.0 version (maybe by checking for a discovered hostname instead, like "docs.brew.sh").

**Comment by igas** [comment]
Bumped to 3.0.1

**Comment by igas** [comment]
Updated test to use pgp only and switched to python3

**Comment by igas** [comment]
Can we restart CI please?

**Pull request closed without merging**
