### PR TITLE
rust: fix cargo manpages

### PR DESCRIPTION
**Pull request by vladimyr**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Continuation of #57029
/cc @chenrui333

### CODE REVIEW

**Comment by chenrui333** [comment]
Does not make sense of having another 36 hours just for the manpage change 😅 

Merged the PR

**Comment by chenrui333** [comment]
made a mistake (due to the revision error)

**Comment by chenrui333** [comment]
```
$ brew upgrade rust
==> Upgrading 1 outdated package:
rust 1.44.1 -> 1.44.1_1
==> Upgrading rust 1.44.1 -> 1.44.1_1
==> Downloading https://homebrew.bintray.com/bottles/rust-1.44.1_1.mojave.bottle.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.4.3-23-g6d27367\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --fail --retry 3 --location --remote-time --continue-at 0 --output /Users/rchen/Library/Caches/Homebrew/downloads/d24355b1d2421d51a4c76599e9bd999f7735c6f09de11ba03a73f7cf7133c903--rust-1.44.1_1.mojave.bottle.tar.gz.incomplete https://homebrew.bintray.com/bottles/rust-1.44.1_1.mojave.bottle.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "rust"
Download failed: https://homebrew.bintray.com/bottles/rust-1.44.1_1.mojave.bottle.tar.gz
```

After the revert

```
$ git pull origin master
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), 806 bytes | 403.00 KiB/s, done.
From https://github.com/Homebrew/homebrew-core
 * branch                    master     -> FETCH_HEAD
   1de9e6c2083..3a878adf363  master     -> origin/master
Updating 1de9e6c2083..3a878adf363
Fast-forward
 Formula/rust.rb | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)

$ brew upgrade rust
Warning: rust 1.44.1 already installed
```

**Comment by chenrui333** [comment]
@vladimyr let's table this change after the sqlite and gcc merge.

I happened to trigger a boost PR as well. These all take lots of CI time.

**Comment by vladimyr** [comment]
> made a mistake (due to the revision error)

Did I make a revision error? 🤔

**Comment by chenrui333** [comment]
my bad, we can revisit it later. I will use your commit to create a new PR :)

**Pull request merged**
