### PR TITLE
terraform: build for Apple Silicon

### PR DESCRIPTION
**Pull request by fxcoudert**
One of the most-downloaded formula with no Apple Silicon bottle… let's try to fix it

### CODE REVIEW

**Comment by fxcoudert** [comment]
Does this mean we're not actually building from source?

```
==> /opt/homebrew/Cellar/terraform/0.14.4_1/bin/terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/aws...

Error: Incompatible provider version

Provider registry.terraform.io/hashicorp/aws v3.22.0 does not have a package
available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.
```

**Comment by chenrui333** [comment]
> Does this mean we're not actually building from source?
> 
> ```
> ==> /opt/homebrew/Cellar/terraform/0.14.4_1/bin/terraform init
> 
> Initializing the backend...
> 
> Initializing provider plugins...
> - Finding latest version of hashicorp/aws...
> 
> Error: Incompatible provider version
> 
> Provider registry.terraform.io/hashicorp/aws v3.22.0 does not have a package
> available for your current platform, darwin_arm64.
> 
> Provider releases are separate from Terraform CLI releases, so not all
> providers are available for all platforms. Other versions of this provider may
> have different platforms supported.
> ```

yeah, terraform provider are pre-built binary, the registry in [here](https://registry.terraform.io/)

**Comment by chenrui333** [comment]
terraform is in its [own repo](https://github.com/hashicorp/terraform), while provider is in [another repo]([url](https://github.com/hashicorp/terraform-provider-aws))

**Comment by aimileus** [comment]
Apparently this issue was fixed by an upstream update, because a newer version has an ARM bottle. https://github.com/Homebrew/brew/issues/10152#issuecomment-787407730

**Pull request closed without merging**
