### PR TITLE
renovate: increase throttle to 50 releases

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
The current throttle is not sufficient, as we shipped 16 releases of this formula in the last 3 weeks.

### CODE REVIEW

**Comment by Bo98** [comment]
Only allowing one release every 6 weeks feels a little excessive:

https://github.com/renovatebot/renovate/releases/tag/36.0.0
https://github.com/renovatebot/renovate/releases/tag/36.50.0
https://github.com/renovatebot/renovate/releases/tag/36.100.0

**Comment by p-linnane** [comment]
How about 25?

**Comment by Bo98** [comment]
I think the issue is that throttling doesn't work at all for this formula rather than the magic value here:

image

image

**Comment by Bo98** [comment]
> Actually, I don't think I made it clear what the current audit does. Every 10 releases is only a single increment of the minor version. So with my proposed change it would be 36.105.0, 36.110.0, 36.115.0, etc. as opposed to 50 increments of the minor version.

Seems like it only checks the patch version: https://github.com/Homebrew/brew/blob/afbea15d5cc2129b03498ebcc5e96dc5641c8874/Library/Homebrew/formula_auditor.rb#L722

**Comment by p-linnane** [comment]
Right. Which is less useful for this project, despite them using them sparingly.

**Comment by Bo98** [comment]
Honestly these throttles should probably be date based rather than math based

**Comment by p-linnane** [comment]
Agreed, that would be much better given there's no consistency.

**Comment by p-linnane** [comment]
@Bo98 Any issue merging this as is while we explore time-based audits?

**Comment by Bo98** [comment]
Not sure what merging this is supposed to achieve given it only checks patch versions?

**Pull request closed without merging**
