### PR TITLE
schismtracker: move to cask

### PR DESCRIPTION
**Pull request by equal-l2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?

-----

As per the discussion in Homebrew/homebrew-core#44665, schismtracker will be moved from core to cask.

PR in cask: https://github.com/Homebrew/homebrew-cask/pull/70048

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Needs to be added to [`tap_migrations.json`](https://github.com/Homebrew/homebrew-core/blob/master/tap_migrations.json) as well.

**Review by vitorgalvao — CHANGES_REQUESTED** [review]
Needs to be added to [`tap_migrations.json`](https://github.com/Homebrew/homebrew-core/blob/master/tap_migrations.json) as well.

**Comment by equal-l2** [comment]
@vitorgalvao done.

**Review by vitorgalvao — APPROVED** [review]

**Comment by equal-l2** [comment]
https://github.com/Homebrew/homebrew-cask/pull/70048 has merged.

**Comment by SMillerDev** [comment]
Thanks @equal-l2! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request merged**
