### PR TITLE
kops 1.5.3

### PR DESCRIPTION
**Pull request by sdomula**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by dnelson** [comment]
The following error is thrown when running `brew upgrade kops` on Sierra:
```
==> Using the sandbox
==> Downloading https://github.com/kubernetes/kops/archive/1.5.3.tar.gz
==> Downloading from https://codeload.github.com/kubernetes/kops/tar.gz/1.5.3
######################################################################## 100.0%
==> make -C /private/tmp/kops-20170310-6756-6fzgg8/kops-1.5.3/src/k8s.io/kops
Last 15 lines from /Users/dnelson/Library/Logs/Homebrew/kops/01.make:
2017-03-10 09:49:27 -0800

make
-C
/private/tmp/kops-20170310-6756-6fzgg8/kops-1.5.3/src/k8s.io/kops

fatal: Not a git repository (or any of the parent directories): .git
Makefile:76: *** "sha1sum command is not available (on MacOS try 'brew install md5sha1sum')".  Stop.
```

**Comment by bfontaine** [comment]
> Makefile:76: *** "sha1sum command is not available (on MacOS try 'brew install md5sha1sum')".  Stop.

Seems like it needs a `depends_on "sha1sum" => :build`

**Comment by dnelson** [comment]
I have confirmed that adding ` depends_on "md5sha1sum" => :build` fixes the build

**Comment by ilovezfs** [comment]
That's reportable as an upstream bug since it should use the macOS `shasum` command.

**Comment by dnelson** [comment]
They seem to have gone down the `depends_on` route themselves: https://github.com/kubernetes/kops/pull/1932

**Comment by ilovezfs** [comment]
Even more a reason to report it. That's not OK.

**Comment by dnelson** [comment]
I'm working on a PR. Yay makefiles.

**Comment by ilovezfs** [comment]
Thank you. :bowing_man:

**Comment by dnelson** [comment]
I still think it would be good to add the depends_on for 1.5.3.

**Comment by ilovezfs** [comment]
If your PR works, we can apply it as a patch ...

**Comment by dnelson** [comment]
my PR can be found at https://github.com/kubernetes/kops/pull/2097

**Comment by JCount** [comment]
@sdomula Thank you for your contribution to Homebrew! 👍 

@dnelson Thank you very much for not merely reporting the build error upstream, but opening a PR to fix it!! 💯

**Pull request closed without merging**
