### PR TITLE
fastlane 2.138.0

### PR DESCRIPTION
**Pull request by joshdholtz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by bayandin** [comment]
Thanks @joshdholtz!

**Comment by joshdholtz** [comment]
Thank you! ❤️

**Comment by bayandin** [comment]
@joshdholtz you may be interested in using` brew bump-formula-pr` for creating a PR next time 👍

**Comment by joshdholtz** [comment]
@bayandin Ah, I wasn't aware of that one! I'm actually going to add the GitHub Action for bumping after a release is made but I just didn't get time before I had to get this release out 😔 I will give that formula a try if the GitHub Action doesn't work out. Thanks! 🙏

**Comment by bayandin** [comment]
[GitHub action](https://github.com/mislav/bump-homebrew-formula-action) was the next thing I was going to recommend to try 😄
Well done anyway, glad to see you among the Homebrew contributors 🎉

**Pull request closed without merging**
