### PR TITLE
babel 7.0.0

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chrmoritz** [comment]
```
Error: Cannot find module '@babel/core'
```

We now have to either 1. bundle `@babel/core` in addition to the cli similar to what we're doing for [`webpack`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/webpack.rb) or 2. just depend on a local `@babel/core` installation in every project (which would be a breaking change for curent users of the fomula) and update the test according to this.

I guess the formula wouldn't make much sense anymore if we choose option 2. Also [upstream recommends](https://babeljs.io/docs/en/babel-cli#install) installing both modules locally too. If we want to keep this as a (globa) homebrew package it should work standalone (option 1) imho.

**Comment by lembacon** [comment]
@chrmoritz Thanks for your opinions. I'm not an expert with `node`, if you would like to handle the `7.0.0` version bump for `babel`, I'm happy to close this pull request in favor of yours. 😺

**Comment by chrmoritz** [comment]
Sure, I can come up with something for option1 (installing as a standalone global homebrew package, bundling both the cli and `@babel/core`). Anyone who wants more control on a project level should follow upstreams advice and install both locally anyway.

**Comment by lembacon** [comment]
Closing in favor of @chrmoritz's upcoming pull request.

**Pull request closed without merging**
