### PR TITLE
storj-uplink 1.47.4

### PR DESCRIPTION
**Pull request by rogeriopradoj**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Review by carlocab — COMMENTED** [review]
There's a tag for 1.47.4, but it seems 1.47.3 is still registered as the latest release on GitHub.

**Comment by rogeriopradoj** [comment]
@carlocab

Should I update this PR to bump to v1.4.3?

Em seg., 7 de fev. de 2022 02:20, Carlo Cabrera ***@***.***>
escreveu:

**Comment by carlocab** [comment]
Maybe -- though it would probably be better to ask upstream what the status of 1.47.4 is. Usually patch versions bumps that don't show up as the latest release are just oversights

**Review by iMichka — CHANGES_REQUESTED** [review]
Yes, this definitively needs a clarification from upstream. Can you open an issue on their tracker?

**Pull request closed without merging**
