### PR TITLE
gnu-apl 1.8

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
Failure on High Sierra. Making the change to the `ENV.delete['SDKROOT']` line made issues related to `::signbit` disappear, but the rest of these failures are still here.

```
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/complex:246:
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:316:9: error: no member named 'isinf' in the global namespace
00:03:52.097 using ::isinf;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:318:9: error: no member named 'isnormal' in the global namespace
00:03:52.097 using ::isnormal;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:317:9: error: no member named 'isnan' in the global namespace
00:03:52.097 using ::isnan;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:318:9: error: no member named 'isnormal' in the global namespace
00:03:52.097 using ::isnormal;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:319:9: error: no member named 'isgreater' in the global namespace
00:03:52.097 using ::isgreater;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:318:9: error: no member named 'isnormal' in the global namespace
00:03:52.097 using ::isnormal;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:319:9: error: no member named 'isgreater' in the global namespace
00:03:52.097 using ::isgreater;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:319:9: error: no member named 'isgreater' in the global namespace
00:03:52.097 using ::isgreater;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:320:9: error: no member named 'isgreaterequal' in the global namespace
00:03:52.097 using ::isgreaterequal;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:320:9: error: no member named 'isgreaterequal' in the global namespace
00:03:52.097 using ::isgreaterequal;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:321:9: error: no member named 'isless' in the global namespace
00:03:52.097 using ::isless;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:321:9: error: no member named 'isless' in the global namespace
00:03:52.097 using ::isless;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:320:9: error: no member named 'isgreaterequal' in the global namespace
00:03:52.097 using ::isgreaterequal;
00:03:52.097       ~~^/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:322:9: error: no member named 'islessequal' in the global namespace
00:03:52.097 using ::islessequal;
00:03:52.097       ~~^
00:03:52.097 
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:322:9: error: no member named 'islessequal' in the global namespace
00:03:52.097 using ::islessequal;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:321:9: error: no member named 'isless' in the global namespace
00:03:52.097 using ::isless;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:323:9: error: no member named 'islessgreater' in the global namespace
00:03:52.097 using ::islessgreater;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:323:9: error: no member named 'islessgreater' in the global namespace
00:03:52.097 using ::islessgreater;
00:03:52.097       ~~^
00:03:52.097 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:322:9: error: no member named 'islessequal' in the global namespace
00:03:52.098 using ::islessequal;
00:03:52.098       ~~^
00:03:52.098 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:324:9: error: no member named 'isunordered' in the global namespace
00:03:52.098 using ::isunordered;
00:03:52.098       ~~^
00:03:52.098 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:324:9: error: no member named 'isunordered' in the global namespace
00:03:52.098 using ::isunordered;
00:03:52.098       ~~^
00:03:52.098 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:323:9: error: no member named 'islessgreater' in the global namespace
00:03:52.098 using ::islessgreater;
00:03:52.098       ~~^
00:03:52.098 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
00:03:52.098 using ::isunordered;
00:03:52.098       ~~^
00:03:52.098 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
00:03:52.098 using ::isunordered;
00:03:52.098       ~~^
00:03:52.098 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:324:9: error: no member named 'isunordered' in the global namespace
00:03:52.098 using ::isunordered;
00:03:52.098       ~~^
00:03:52.098 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:325:9: error: no member named 'isunordered' in the global namespace
00:03:52.098 using ::isunordered;
00:03:52.098       ~~^
00:03:52.098 13 errors generated.
00:03:52.098 make[2]: *** [Connection.lo] Error 1
00:03:52.098 make[2]: *** Waiting for unfinished jobs....
00:03:52.098 13 errors generated.
00:03:52.098 make[2]: *** [SqliteArgListBuilder.lo] Error 1
00:03:52.098 13 errors generated.
00:03:52.098 make[2]: *** [apl-sqlite.lo] Error 1
00:03:52.098 make[1]: *** [install-recursive] Error 1
00:03:52.098 make: *** [install-recursive] Error 1
```

**Comment by Moisan** [comment]
`ENV.delete("HOMEBREW_SDKROOT")` has also helped in this case sometimes.

**Comment by alebcay** [comment]
I'm pleasantly surprised that `ENV.delete("HOMEBREW_SDKROOT")` fixed the trick. In any case, build is succeeding now.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
