### PR TITLE
curl-rustls 8.9.1 (new formula)

### PR DESCRIPTION
**Pull request by kpcyrd**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Not really sure we want to add another variant of `curl` just for a different TLS backend.

You might want to consider hosting this in an external tap. This is what Cloudflare does for a variant of `curl` that uses Quiche. See https://github.com/cloudflare/homebrew-cloudflare/blob/69bb5d5cee96c85937f87c2212941b4a2ec7d2cd/curl.rb.

**Comment by kpcyrd** [comment]
Thanks for the quick response! Would you be interested in a patch that enables it as additional vtls backend in the regular curl package?

https://everything.curl.dev/usingcurl/tls/backends.html

It could then be selected with `CURL_SSL_BACKEND=rustls curl`.

**Comment by carlocab** [comment]
> Thanks for the quick response! Would you be interested in a patch that enables it as additional vtls backend in the regular curl package?

No, sorry. Homebrew installs `curl` by default for users whose system `curl` is too old, and this often requires building `curl` from source. This means we want to keep the build dependencies of `curl` to a minimum. (Or, at least, we don't want to add any more than there are currently.)

**Comment by kpcyrd** [comment]
I see, fair enough. :)

**Pull request closed without merging**
