### PR TITLE
enzyme 0.0.10

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Let's try this with LLVM 12.

**Comment by nandahkrishna** [comment]
```
Error: SHA256 mismatch
Expected: edd9d419d1f94d5c717da3a2f2b20df8ea2a2b26a555fbb3d45afe9d95b73412
  Actual: 6fcee5390541e259f26def103f0423df990ebf364933cf2a3610a08de3b0691f
```

**Comment by carlocab** [comment]
Must've retagged.

**Comment by carlocab** [comment]
> This has been retagged 17 minutes ago. We probably need a `livecheck` using the `GithubLatest` strategy here.

I think we can skip it for now. Seems like they retagged it to fix a build failure. Don't think they intend to do that regularly.

**Comment by nandahkrishna** [comment]
Ah, alright then. I'll remove it for now, we can revisit adding it in the future if the automated PRs are created before a release is marked as the latest.

**Review by carlocab — DISMISSED** [review]

**Comment by nandahkrishna** [comment]
Accidentally reverted the checksum change along with the `livecheck` 🤦🏻‍♂️

**Review by carlocab — APPROVED** [review]

**Review by nandahkrishna — APPROVED** [review]

**Comment by wsmoses** [comment]
Just noticing this now. Regarding LLVM 12, we weren't testing LLVM 12 explicitly (just llvm main branch), which since diverged from 12 in terms of compatibility. Happily we now test 12 and it should build.

**Comment by carlocab** [comment]
Thanks for letting us know, @wsmoses. If you'd like to open a PR to update the formula, that'd help. Otherwise, I'll try to find time to open a PR later.

When you do, you may wish to add `revision 1` right after the `license` line so that users who have `enzyme` installed get the updated version when they do `brew upgrade`.

**Comment by carlocab** [comment]
Opened #77959.

**Comment by carlocab** [comment]
Ah wait, this should apply to the next version, shouldn't it? Oops. Haven't had my coffee yet.

**Comment by wsmoses** [comment]
Actually even one past that, the patch to restore llvm12 support landed in v0.0.12, so might as well just bump the version.

My apologies for the confusion (in contrast to you needing coffee, I need to go to bed :P).

**Comment by carlocab** [comment]
Ah, right. Thanks; I amended my PR to also bump the version.

**Pull request closed without merging**
