### PR TITLE
haxe 3.4.3

### PR DESCRIPTION
**Pull request by Continuities**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew @Continuities! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by thomasuster** [comment]
@ilovezfs Did you close this on accident?

**Comment by ilovezfs** [comment]
@thomasuster I merged it in https://github.com/Homebrew/homebrew-core/pull/18078#event-1251115430. Anything that has a bottle gets pulled with `brew pull --bottle` and not merged via the GitHub GUI, which we only use for merging commits that don't require a new bottle.

**Comment by ilovezfs** [comment]
in https://github.com/Homebrew/homebrew-core/commit/2ed0d3893aad1826b5e8c23b175729254ab7d3da

**Pull request closed without merging**
