### PR TITLE
graph-tool 2.57

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by count0** [comment]
@chenrui333 @p-linnane I can't seem to be able to access the build logs to see what happened.

**Comment by chenrui333** [comment]
> @chenrui333 @p-linnane I can't seem to be able to access the build logs to see what happened.

build logs are in here, https://github.com/Homebrew/homebrew-core/actions/runs/5417552605/jobs/9849299479

**Comment by count0** [comment]
> > @chenrui333 @p-linnane I can't seem to be able to access the build logs to see what happened.
> 
> build logs are in here, https://github.com/Homebrew/homebrew-core/actions/runs/5417552605/jobs/9849299479

Not really... It just says “Error: graph-tool 2.57 did not build”, with no other information. I would like to actually see the compilation logs.

It's really strange that it fails to compile on *all* targets. Could the builds be re-triggered from the start?

**Comment by p-linnane** [comment]
You can grab the verbose logs by running:
`gh run download 5417552605 --repo Homebrew/homebrew-core`

**Comment by count0** [comment]
> You can grab the verbose logs by running: `gh run download 5417552605 --repo Homebrew/homebrew-core`

The issue here seems to be some python dependencies that are not installing properly. It seems to fail installing "ninja". The build stops before graph-tool even has a chance to build.

I'm not sure how to fix this.

**Comment by chenrui333** [comment]
Should be good now, there were some issues of build the dependencies.

**Comment by count0** [comment]
@chenrui333 This looks like it's good to go!

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
