### PR TITLE
WIP upx 3.92

### PR DESCRIPTION
**Pull request by mistydemeo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

UPX 3.92 fixes support for building/running on Sierra. The tests are currently not running: compressing executables is broken (every result returns `NotCompressibleException`), but decompressing executables works.

### CODE REVIEW

**Comment by ilovezfs** [comment]
Odd. I thought this release was supposed to have full Sierra support.

**Comment by mistydemeo** [comment]
Yeah, I thought so too.

**Comment by mistydemeo** [comment]
After some debugging, it looks like the issue is that 3.92 is producing moderately larger executables compared to 3.91. When creating an executable, upx compares the size of the compressed executable to the original, and raises `NotCompressibleException` if it isn't at least 512 bytes smaller: https://github.com/upx/upx/blob/master/src/packer.cpp#L328-L335

Our test program produces a binary that's 8432 bytes, and that seems to be around the threshold that no longer gets an appreciable size gain. With both tests running on El Cap, 3.91 produces a 4096-byte output while 3.92 produces a 8816 byte binary - e.g., a 384-byte *increase*.

3.92 *does* still work fine on non-trivial binaries, so I think an adjustment to the test is in order.

**Comment by mistydemeo** [comment]
Updated to test against UPX's own binary, which gets a compression ratio of about 33.78% and exits 0.

**Pull request closed without merging**
