### PR TITLE
teleport 12.0.4

### PR DESCRIPTION
**Pull request by p-linnane**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
not marked as latest release yet

**Comment by SMillerDev** [comment]
Asked in https://github.com/gravitational/teleport/pull/22250

**Comment by chenrui333** [comment]
it is the latest release now

**Review by chenrui333 — APPROVED** [review]

**Review by chenrui333 — DISMISSED** [review]

**Comment by ZhongRuoyu** [comment]
@BrewTestBot did this in https://github.com/Homebrew/homebrew-core/pull/124612.

**Pull request closed without merging**
