### PR TITLE
hatch 1.6.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
Okay I'm so confused… Error looks relatively easy to fix, there's the cryptography Python package that require a Rust compiler on build.
But just to be sure I wanted to crosscheck that with release notes and tags diff, and here I saw that while 1.6.0 is the one tagged latest stable release on GitHub, there also exist older releases and tags going up to v1.11.0, see https://github.com/pypa/hatch/releases

So I don't know against what to compare nor why the version numbers looks messy like that…

**Comment by branchvincent** [comment]
> So I don't know against what to compare nor why the version numbers looks messy like that…

Hatch's repo contains releases from two separate packages, `hatch` and `hatchling`. You could compare the two tags directly: https://github.com/pypa/hatch/compare/hatch-v1.5.0...hatch-v1.6.0

It looks like `cryptography` is not new, but rather a linux-specific dependency pulled in through `SecretStorage`: https://github.com/jaraco/keyring/blob/f9142e2ab8f237708a88c52d0fc4cf4f1cba50b2/setup.cfg#L24. We have not noticed this before due to `brew update-python-resources`'s limitation of only considering the current platform.

**Comment by Porkepix** [comment]
> > So I don't know against what to compare nor why the version numbers looks messy like that…
> 
> Hatch's repo contains releases from two separate packages, `hatch` and `hatchling`. You could compare the two tags directly: [pypa/hatch@hatch-v1.5.0...hatch-v1.6.0](https://github.com/pypa/hatch/compare/hatch-v1.5.0...hatch-v1.6.0)
> 
> It looks like `cryptography` is not new, but rather a linux-specific dependency pulled in through `SecretStorage`: [jaraco/keyring@`f9142e2`/setup.cfg#L24](https://github.com/jaraco/keyring/blob/f9142e2ab8f237708a88c52d0fc4cf4f1cba50b2/setup.cfg#L24). We have not noticed this before due to `brew update-python-resources`'s limitation of only considering the current platform.

Mmmh, looks like mac requires it too, looking at new test fails?

**Comment by branchvincent** [comment]
Tests fail since we still attempt to install Linux-only dependencies on mac. Instead, we need to conditionally install them (`SecretStorage`and `jeepney` + their recursive deps), see [`organize-tool`](https://github.com/Homebrew/homebrew-core/blob/1a727bed0524f15e0a8ac8a992d03ac39f6e7c47/Formula/organize-tool.rb#L94-L100) for a similar situation

**Comment by Porkepix** [comment]
> Tests fail since we still attempt to install Linux-only dependencies on mac. Instead, we need to conditionally install them (`SecretStorage`and `jeepney` + their recursive deps), see [`organize-tool`](https://github.com/Homebrew/homebrew-core/blob/1a727bed0524f15e0a8ac8a992d03ac39f6e7c47/Formula/organize-tool.rb#L94-L100) for a similar situation

So each and every dependencies should be checked one by one on every release now? Because this can include a lot of them.
As for unneeded dependencies installed, this shouldn't create fails to install *too many* dependencies even if it's not the best thing to do, right?

**Comment by Porkepix** [comment]
Curiously 1.6.1 doesn't seems to encounter the issue anymore without changing anything: https://github.com/Homebrew/homebrew-core/pull/113375

**Pull request closed without merging**
