### PR TITLE
hugo 0.112.0

### PR DESCRIPTION
**Pull request by divinerites**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by divinerites** [comment]
For the maintainer I'm not sure but looks like the failing cause is on the homebrew side (and not a faulty hugo code)

Can you confirm ? Thanks a lot.

```
Minitest::Assertion: Expected #<Pathname:/private/tmp/hugo-test-20230523-77394-15ur341/hops-yeast-malt-water/config.toml> to be exist?.
  /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.18.0/lib/minitest/assertions.rb:183:in `assert'
  /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.18.0/lib/minitest/assertions.rb:397:in `assert_predicate'
  /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/hugo.rb:29:in `block in <class:Hugo>'
  /opt/homebrew/Library/Homebrew/formula.rb:2345:in `block (3 levels) in run_test'
  /opt/homebrew/Library/Homebrew/extend/kernel.rb:498:in `with_env'
  /opt/homebrew/Library/Homebrew/formula.rb:2344:in `block (2 levels) in run_test'
  /opt/homebrew/Library/Homebrew/formula.rb:985:in `with_logging'
  /opt/homebrew/Library/Homebrew/formula.rb:2343:in `block in run_test'
  /opt/homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
  /opt/homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
  /opt/homebrew/Library/Homebrew/mktemp.rb:75:in `run'
  /opt/homebrew/Library/Homebrew/formula.rb:2621:in `mktemp'
  /opt/homebrew/Library/Homebrew/formula.rb:2337:in `run_test'
  /opt/homebrew/Library/Homebrew/test.rb:44:in `block in <main>'
  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
  /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/lib/ruby/2.6.0/timeout.rb:[108](https://github.com/Homebrew/homebrew-core/actions/runs/5055304110/jobs/9071517305?pr=131697#step:3:110):in `timeout'
  /opt/homebrew/Library/Homebrew/test.rb:48:in `<main>'
```

**Comment by divinerites** [comment]
Will close this one because it seems like the ruby time-out. Will reopen an other one if this accidental timeout was the cause.

**Comment by divinerites** [comment]
Upon advice from hugo maintainer, I submitted a PR (https://github.com/Homebrew/homebrew-core/pull/131702) with a changed filename for file conf.
But this cause the same error. So I closed this new PR.
We still have to find the cause of this error.

**Review by chenrui333 — APPROVED** [review]

**Comment by divinerites** [comment]
Thanks a lot @chenrui333

**Review by divinerites — COMMENTED** [review]
all is fine. Thanks

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
