### PR TITLE
freerdp: revision bump (ffmpeg 5.0)

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

This suffered a linkage failure in #93167. We're rebuilding it
separately to avoid a long CI run.

### CODE REVIEW

**Comment by carlocab** [comment]
Needs rebasing.

**Comment by carlocab** [comment]
@Bo98 would you know if there are any problems with the `CoreDevice` framework, but only on Intel Big Sur? I keep seeing problems with it. See also #92024

**Review by Bo98 — APPROVED** [review]
Fixed in today's ops maintenance window (hopefully).

**Comment by carlocab** [comment]
```
objc[54049]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x20ae1f788) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10ec782b8). One of the two will be used. Which one is undefined.
objc[54049]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x20ae1f7d8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10ec78308). One of the two will be used. Which one is undefined.
objc[54133]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x20ae1f788) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10d1c02b8). One of the two will be used. Which one is undefined.
objc[54133]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x20ae1f7d8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10d1c0308). One of the two will be used. Which one is undefined.
```
https://github.com/Homebrew/homebrew-core/runs/5088783291?check_suite_focus=true#step:8:22

Not sure if that's something we expect to see.

**Comment by Bo98** [comment]
I get that too when running `xcodebuild -version`. It doesn't seem to break anything and is probably a bug rather than our issue.

**Pull request closed without merging**
