### PR TITLE
qt 5.11.0

### PR DESCRIPTION
**Pull request by fxcoudert**
Qt 5.11 is nearly upon us: https://wiki.qt.io/Qt_5.11_Release
Testing the release candidate

### CODE REVIEW

**Comment by ilovezfs** [comment]
I don't think any will since it only affects framework builds and we and [MacPorts](https://github.com/macports/macports-ports/blob/master/aqua/qt5/Portfile#L757) have been distributing framework builds with pc files.

**Comment by fxcoudert** [comment]
Pull request updated with final released version. Go Jenkins!

**Comment by ilovezfs** [comment]
@dakcarto Just FYI it looks like this broke the PyQt build. https://jenkins.brew.sh/job/Homebrew%20Testing/864/

**Comment by ilovezfs** [comment]
Several reverse dependencies' builds are now broken: https://github.com/Homebrew/homebrew-core/issues/28455

**Pull request closed without merging**
