### PR TITLE
libssh2 1.10.0

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by branchvincent** [comment]
is it ok to skip recursive deps here? it's testing every single rust formula

**Comment by chenrui333** [comment]
I think it is fine, it would also test the linkage as well.

**Comment by branchvincent** [comment]
```
Error: 3 failed steps!
brew test --retry --verbose eureka
brew test --retry --verbose notcurses
brew test --retry --verbose oakc
```

I can reproduce `eureka` on master

**Comment by carlocab** [comment]
`notcurses` has been seen in a bunch of other PRs.

**Comment by SMillerDev** [comment]
`oakc` has a dependency on rust, which has a dependency on this. Could it be that it's the only formula that actually uses the rust `libssh2` dependency and rust needs a bump?

**Comment by carlocab** [comment]
`rust` is only a build dependency, though, so I doubt the failure is related.

**Comment by SMillerDev** [comment]
Yeah, I think `oakc` has a PTY issue on the build servers since recently. So it seems that all failures are pre-existing.

**Comment by carlocab** [comment]
Might be related to recent sandbox changes, maybe? @Bo98

**Comment by Bo98** [comment]
Well it took a while to find one at least.

Looks like a winsize issue, even though I thought I covered that. Does it only happen in CI?

**Comment by SMillerDev** [comment]
> Does it only happen in CI?

I couldn't reproduce it at least.

**Comment by Bo98** [comment]
I guess `$stdout.winsize` doesn't return a sensible winsize in the CI or something, which makes you wonder how it worked before since `oakc` must have been able to pick up a `width > 5` from somewhere.

**Comment by carlocab** [comment]
> Well it took a while to find one at least.

We'd have found it sooner if I connected the dots sooner 😅

**Comment by Bo98** [comment]
Should be fixed now.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
