### PR TITLE
fabio 1.4.4

### PR DESCRIPTION
**Pull request by magiconair**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by magiconair** [comment]
@ilovezfs Why did you close it? What did I miss?

**Comment by magiconair** [comment]
ah, you merged it. Duh. pls ignore. Thx

**Comment by ilovezfs** [comment]
That's what you'll always see if the formula has bottles. It's in master now.

**Pull request closed without merging**
