### PR TITLE
Add formula aliases for Java casks.

### PR DESCRIPTION
**Pull request by reitermarkus**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Needed for https://github.com/Homebrew/homebrew-cask/pull/72284 and https://github.com/Homebrew/homebrew-cask-versions/pull/8149.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Shouldn't this be an alias?

**Comment by reitermarkus** [comment]
Not sure what's the semantic difference between a rename and an alias. Technically it's a rename from the casks to the formulae.

**Comment by SMillerDev** [comment]
Aliases are things that people will likely keep searching for. Renames are just used to point people's system to the new name for a formula AFAIK.

**Comment by MikeMcQuaid** [comment]
Yeh, agreed an alias would be preferable in this case to ease `brew install java` working and not ending up with PRs to make it other formula.

**Comment by SMillerDev** [comment]
If we do java11, maybe we need java8 and java13?

**Comment by reitermarkus** [comment]
We don't “need” any of these. These merely exist so that the casks are migrated properly once they are removed.

**Comment by zbeekman** [comment]
Is this ready to 🚢 ?

**Pull request closed without merging**
