### PR TITLE
bigloo 4.4a

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
*** ERROR:configure:Can't configure Java (see configure.log for details).
```

**Comment by chenrui333** [comment]
will revisit it later.

**Comment by mitchblank** [comment]
FWIW the project has their own homebrew tap that they are pointing people to.  Should we just remove?  https://www-sop.inria.fr/indes/fp/Bigloo/download.html

Their formulae https://gitlab.inria.fr/mserrano/hopbrew/-/tree/master/Formula

cc @manuel-serrano

**Comment by manuel-serrano** [comment]
Dear Mitchell,

> FWIW the project has their own homebrew tap that they are pointing people to.  Should we just remove?  https://www-sop.inria.fr/indes/fp/Bigloo/download.html
> 
> Their formulae https://gitlab.inria.fr/mserrano/hopbrew/-/tree/master/Formula
> 
> cc @manuel-serrano
I'm not entirely sure if I fully understand the implication of this mail.

My general take on that is that for sure we should be avoid duplicating
work. If there is already an "official" tap supporting Bigloo with
a recent Bigloo version, I will be more than glad to point it from
the Bigloo home page and stop maintaining something separately on my side.

In any case, I'm willing to help,

Sincerely,

-- 
Manuel

**Pull request closed without merging**
