### PR TITLE
dpkg 1.20.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
checking for po4a >= 0.59... configure: error: cannot find po4a >= 0.59
```

**Comment by alebcay** [comment]
Just ran some builds/checks off of this branch locally, noticed:
```
❯ brew linkage dpkg
System libraries:
  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  /usr/lib/libSystem.B.dylib
  /usr/lib/libbz2.1.0.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/gettext/lib/libintl.8.dylib (gettext)
  /usr/local/opt/xz/lib/liblzma.5.dylib (xz)
Undeclared dependencies with linkage:
  gettext
```

**Comment by chenrui333** [comment]
> Just ran some builds/checks off of this branch locally, noticed:
> 
> ```
> ❯ brew linkage dpkg
> System libraries:
>   /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
>   /usr/lib/libSystem.B.dylib
>   /usr/lib/libbz2.1.0.dylib
>   /usr/lib/libz.1.dylib
> Homebrew libraries:
>   /usr/local/opt/gettext/lib/libintl.8.dylib (gettext)
>   /usr/local/opt/xz/lib/liblzma.5.dylib (xz)
> Indirect dependencies with linkage:
>   gettext
> ```

Thanks for the checking, let me do the same in my local too!

**Comment by chenrui333** [comment]
@alebcay I have the same in my local too, how should we proceed on that?

**Comment by chenrui333** [comment]
I will mark this PR as `do not merge` and let's have some internal discussions on this before the merge. :)

**Comment by alebcay** [comment]
I think simply adding `depends_on "gettext"` will suffice, unless I'm missing something here.

**Comment by chenrui333** [comment]
> I think simply adding `depends_on "gettext"` will suffice, unless I'm missing something here.

Fair point, let me add that.

**Comment by chenrui333** [comment]
Yeah, I think @Bo98 mention this implicit transitive dependency before.

**Pull request closed without merging**
