### PR TITLE
fcl 0.6.0

### PR DESCRIPTION
**Pull request by scpeters**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jslee02** [comment]
The test should be updated as the FCL's API has changed in the new version. It should be like:
```cpp
      #include <fcl/geometry/shape/box.h>
      #include <cassert>
      int main() {
        assert(fcl::Boxd(1, 1, 1).computeVolume() == 1);
      }
```

**Comment by scpeters** [comment]
@jslee02 does FCL depend on eigen now?

**Comment by jslee02** [comment]
[Correct](https://github.com/flexible-collision-library/fcl/blob/master/CMakeLists.txt#L139-L157)!

**Comment by scpeters** [comment]
I think dartsim needs a revision bump, and it looks like the high-sierra build failed

@jslee02: is fcl using c++17 now? would you expect the high-sierra build to fail?

**Comment by jslee02** [comment]
[fcl uses C++11](https://github.com/flexible-collision-library/fcl/blob/a13c681e41eb8180cba7d4fd32637511f588cb82/CMakeModules/CompilerSettings.cmake#L36). Hm, I don't know why the high-sierra build fails.

**Comment by scpeters** [comment]
it looks like test_sphere_box is failing to compile. I'll try disabling test compilation.

**Pull request closed without merging**
