### PR TITLE
fb-adb 2.0.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> ../configure --prefix=/usr/local/Cellar/fb-adb/2.0.0
checking build system type... x86_64-apple-darwin16.1.0
checking host system type... x86_64-apple-darwin16.1.0
configure: error: Android SDK location not given
```

**Comment by vladshablinsky** [comment]
Even if `--with-android-sdk` is given It needs more than Android SDK, it also need build-tools, which can't be found in `android-sdk`.

**Comment by ilovezfs** [comment]
seems to need the SDK specifically with API 19, and then still fails with
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C stub-x86/ FB_ADB_RECURSIVE=1 libfb-adb.a.stripped
i686-linux-android-gcc -DPACKAGE_NAME=\"fb-adb\" -DPACKAGE_TARNAME=\"fb-adb\" -DPACKAGE_VERSION=\"2.0.0\" -DPACKAGE_STRING=\"fb-adb\ 2.0.0\" -DPACKAGE_BUGREPORT=\"mzlee@fb.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"fb-adb\" -DVERSION=\"2.0.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DSIZEOF_OFF_T=4 -DHAVE_MACHINE_ENDIAN_H=1 -DHAVE_ENDIAN_H=1 -DHAVE_FEATURES_H=1 -DHAVE_PIPE2=1 -DHAVE_PTSNAME=1 -DHAVE_FUNOPEN=1 -DHAVE_FTRUNCATE64=1 -DHAVE_REALPATH=1 -DHAVE_STRUCT_STAT_ST_BLOCKS=1 -DHAVE_STRUCT_STAT_ST_BLKSIZE=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DHAVE_STRUCT_DIRENT_D_TYPE=1 -I. -I../../stub-x86/..  -I. -DSHA2_USE_INTTYPES_H=1 -DFBADB_STUB=1  -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -DNDEBUG=1 -fvisibility=hidden -std=gnu99 -Wno-free-nonheap-object -Wno-initializer-overrides  -flto -frandom-seed=0 -I/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/include/darwin -MT adb.o -MD -MP -MF .deps/adb.Tpo -c -o adb.o ../../stub-x86/../adb.c
make[2]: i686-linux-android-gcc: No such file or directory
make[2]: *** [adb.o] Error 1
make[1]: *** [stub-x86/.update-lib] Error 2
make: *** [all-recursive] Error 1
```

**Comment by ilovezfs** [comment]
I'll leave this to someone else.

**Comment by Manouchehri** [comment]
Could you reopen this? fb-adb fails to build even with 1.4.4.

```bash
nitro:~ dave$ brew install fb-adb
==> Using the sandbox
==> Downloading https://github.com/facebook/fb-adb/archive/1.4.4.tar.gz
Already downloaded: /Users/dave/Library/Caches/Homebrew/fb-adb-1.4.4.tar.gz
==> ./autogen.sh
==> ../configure --prefix=/usr/local/Cellar/fb-adb/1.4.4
Last 15 lines from /Users/dave/Library/Logs/Homebrew/fb-adb/02.configure:
checking the archiver (ar) interface... ar
checking for ppoll... no
checking for signalfd4... no
checking for dup3... no
checking for mkostemp... yes
checking for kqueue... yes
checking for pipe2... no
checking for ptsname... yes
checking for accept4... no
checking for fopencookie... no
checking for funopen... yes
checking for clock_gettime... yes
checking for execvpe... no
configure: error: could not find Android cross-compiler for i686-pc-linux-android
configure: error: ../../stub-x86/configure failed for stub-x86

READ THIS: http://docs.brew.sh/Troubleshooting.html

```

**Comment by Manouchehri** [comment]
Also mentioned at https://github.com/facebook/fb-adb/issues/55.

**Pull request closed without merging**
