### PR TITLE
zstd 1.1.2

### PR DESCRIPTION
**Pull request by nijikon**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
Audit failed due to a non-executable file in `bin`.

```
failed: brew audit zstd --online

Stacktrace

        Error: 1 problem in 1 formula
zstd:
  * Non-executables were installed to "/usr/local/Cellar/zstd/1.1.2/bin"
    The offending files are:
      /usr/local/Cellar/zstd/1.1.2/bin/zstdless
```

Looks like a broken script in the installation? It doesn't have an executable permissions bit or a shebang line.

```
[/usr/local/Cellar/zstd/1.1.2/bin]
$ ls -l zstdless
-r--r--r-- 1 janke admin 18 Dec 22 17:05 zstdless
[/usr/local/Cellar/zstd/1.1.2/bin]
$ cat zstdless
zstdcat $@ | less
```

What's weird is that `zstdless` is `+x` in the source distribution and is installed with `@install -m 755 zstdless $(DESTDIR)$(BINDIR)/zstdless`, which seems like the right permissions.

Seems like a bug that should be reported upstream.

**Comment by apjanke** [comment]
Interestingly, I installed it from outside `brew`, and `zstdless` kept its `+x` permissions. Is there something in `brew install` that modifies permissions of files based on whether they have a shebang or something similar?

**Comment by apjanke** [comment]
Reported the lack of shebang upstream: https://github.com/facebook/zstd/issues/496

But I don't think this is actually an upstream issue, since `zstdless` seems to be losing its `+x` bit specifically under `brew`. I don't know why. Will look in to it when I have some time.

**Comment by tdsmith** [comment]
>  Is there something in brew install that modifies permissions of files based on whether they have a shebang or something similar?

Yes, the cleaner does this.

**Comment by apjanke** [comment]
Okay, I see [where the cleaner does this](https://github.com/Homebrew/brew/blob/8f85eb64c4875fed514150dec755cb267a96df74/Library/Homebrew/cleaner.rb#L103-L115). Thanks.

I submitted [an upstream patch](https://github.com/facebook/zstd/pull/497) to add a shebang. We could pull that in and get it working. Or wait to see if it's merged in a near-future version.

**Comment by ilovezfs** [comment]
:+1: to merging it with your fix and not waiting on upstream. We broke it, we bought it.

**Comment by nijikon** [comment]
@apjanke Nice work, added the patch, waiting for CI.

**Pull request closed without merging**
