### PR TITLE
Poppler 0.71.0

### PR DESCRIPTION
**Pull request by edporras**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by edporras** [comment]
One again, [pdftoipe](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pdftoipe.rb]) is broken. I've pushed [PR 31](https://github.com/otfried/ipe-tools/pull/31) with the necessary changes but, unfortunately, the [patch from my last PR](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pdftoipe.rb#L21) is no longer available. However, it was merged but they didn't publish a new release. I've asked if they could push one with these changes; otherwise, we'd have to switch the formula to pull from head.

Let me know if there's anything else you'd like me to do. Thx.

**Comment by fxcoudert** [comment]
For pdftoipe we can use the previous commit as patch #1 (`https://github.com/otfried/ipe-tools/commit/fe6cfdb6.diff?full_index=1`) and your new PR as patch #2. Hopefully they will release a new version.

**Comment by edporras** [comment]
Pushed your suggestion for now. If they accept my PR and do a release, I'll bump pdftoipe and submit it on its own.

**Comment by sadhen** [comment]
@edporras 

`brew install poppler --with-qt` failed.

```
g-ir-scanner: link: clang -o /private/tmp/poppler-20181118-15650-1tpmata/poppler-0.71.0/glib/tmp-introspectCYQQRm/Poppler-0.18 /private/tmp/poppler-20181118-15650-1tpmata/poppler-0.71.0/glib/tmp-introspectCYQQRm/Poppler-0.18.o -L. -Wl,-rpath,. -lpoppler-glib -L/tmp/poppler-20181118-15650-1tpmata/poppler-0.71.0 -Wl,-rpath,/tmp/poppler-20181118-15650-1tpmata/poppler-0.71.0 -L/usr/local/Cellar/glib/2.58.1/lib -L/usr/local/opt/gettext/lib -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -lintl -Wl,-framework -Wl,CoreFoundation
dyld: Library not loaded: @executable_path/libplds4.dylib
  Referenced from: /tmp/poppler-20181118-15650-1tpmata/poppler-0.71.0/libpoppler.82.dylib
  Reason: image not found
Command '[u'/private/tmp/poppler-20181118-15650-1tpmata/poppler-0.71.0/glib/tmp-introspectCYQQRm/Poppler-0.18', u'--introspect-dump=/private/tmp/poppler-20181118-15650-1tpmata/poppler-0.71.0/glib/tmp-introspectCYQQRm/functions.txt,/private/tmp/poppler-20181118-15650-1tpmata/poppler-0.71.0/glib/tmp-introspectCYQQRm/dump.xml']' returned non-zero exit status -6
```

**Pull request closed without merging**
