### PR TITLE
alexjs 6.0.0

### PR DESCRIPTION
**Pull request by lembacon**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by lembacon** [comment]
```
13:28:42 ==> brew audit alexjs --online
13:29:03 ==> FAILED
13:29:03 Error: undefined method `count' for nil:NilClass
13:29:03 /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:133:in `block in audit'
13:29:03 /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:123:in `each'
13:29:03 /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:123:in `audit'
13:29:03 /usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

🙃🙃🙃

**Comment by lembacon** [comment]
Related to Homebrew/brew#4753, @GauthamGoli can you please take a look?

**Comment by GauthamGoli** [comment]
Looking into it.

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
```
14:55:44 ==> brew audit alexjs --online
14:56:07 ==> FAILED
14:56:07 Error: undefined method `positive?' for nil:NilClass
14:56:07 /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:163:in `audit'
14:56:07 /usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

Another one. 😂 @GauthamGoli

**Comment by GauthamGoli** [comment]
Thats so sloppy of me to let that through. Fixing it.

**Comment by lembacon** [comment]
@BrewTestBot test this please

**Comment by lembacon** [comment]
```
13:00:19 ==> brew audit alexjs --online
13:00:43 ==> FAILED
13:00:43 Error: undefined method `count' for nil:NilClass
13:00:43 /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:133:in `block in audit'
13:00:43 /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:123:in `each'
13:00:43 /usr/local/Homebrew/Library/Homebrew/dev-cmd/audit.rb:123:in `audit'
13:00:43 /usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

Yet another one, 😂 @GauthamGoli.

**Comment by GauthamGoli** [comment]
@lembacon All good now.

**Comment by lembacon** [comment]
Thanks @GauthamGoli!

**Pull request closed without merging**
