### PR TITLE
wasmer 1.0.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Won't work for ARM yet; needs a new `Cargo.lock` file: https://github.com/Homebrew/homebrew-core/issues/68301

**Comment by carlocab** [comment]
Upstream issue: https://github.com/wasmerio/wasmer/issues/1986#issuecomment-754752923

**Comment by ezfe** [comment]
@carlocab Looks like version 1.0.0 fails for a different reason unrelated to `--locked`?

```sh
➜  wasmer git:(aa03cab26) cargo install --path .
error: specified package `wasmer-workspace v1.0.0 (/Users/ezekielelin/temp_dev/wasmer)` has no binaries
```

Might be misinterpreting this though, apologies if I am

**Comment by carlocab** [comment]
@ezfe Hm, yes, that's entirely possible. I don't have access to an ARM machine myself, and I have a large number of packages to look at, so my method of identifying stale lock files might be a bit crude...

That said, CI (https://github.com/Homebrew/homebrew-core/pull/68089) didn't report a failure for wasmer on ARM when we dropped the `--locked` flag but did report a failure when we had it,  so 🤷. On the other hand, wasmer CI seems to have zero build issues (https://github.com/wasmerio/wasmer/issues/1986), so, again, 🤷.

If you've got an ARM machine you can use, and don't mind looking into what's going on, I'd greatly appreciate it.

**Comment by ezfe** [comment]
@carlocab Yup I have an ARM MacBook Air - I do see it's failing with the error I listed (same as when I run brew install with the modified formula). If there's something I can do to help debug this please let me know what to run. I'm not super familiar with Rust so I don't know how to assess that error beyond its face value.

**Comment by carlocab** [comment]
Thanks, @ezfe. Try reporting the error message you saw over at https://github.com/wasmerio/wasmer/issues/1986; they'll have a better idea of what's going on with your build.

**Comment by ezfe** [comment]
So we've learned that the install command needs to change the `--path .` to be `--path lib/cli` here, but we're also waiting for something else unrelated to be fixed.

**Comment by richiksc** [comment]
@ezfe The `enumset`/`syn` should not be an issue as long as `syn` is pinned to a version <1.0.58 in `Cargo.lock`, which it is in wasmer's Cargo.lock file.

@chenrui333  I think if we change the build command to lib/cli it should build.

**Comment by richiksc** [comment]
Update: I was able to build it succesfully locally on my M1 machine by running:

```
% cargo install --locked --path lib/cli
```

**Comment by carlocab** [comment]
I pushed a commit that I think does the same thing. Will change it if it turns out to not be equivalent.

**Comment by richiksc** [comment]
> I pushed a commit that I think does the same thing. Will change it if it turns out to not be equivalent.

@carlocab This works:

```
% cd lib/cli
% cargo install --locked --path .
```

So I'd assume the formula should work now too. We'll see.

/sparkle @carlocab for fixing the build and overall effort to port formulae to ARM

**Comment by carlocab** [comment]
Test failed, but I guess that's progress:
```
==> brew test --verbose wasmer
==> FAILED
==> Testing wasmer
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210107-47518-1cj7mtm.sb ruby -W0 -I $LOAD_PATH -- /opt/homebrew/Library/Homebrew/test.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/wasmer.rb --verbose
==> /opt/homebrew/Cellar/wasmer/1.0.0/bin/wasmer run /private/tmp/wasmer-test-20210107-47519-1y752si/sum.wasm --invoke sum 1 2
error: failed to run `/private/tmp/wasmer-test-20210107-47519-1y752si/sum.wasm` (no compilers enabled)
│   1: module instantiation failed (engine: jit, compiler: headless)
╰─> 2: Validation error: The JITEngine is not compiled with compiler support, which is required for validating

Error: wasmer: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.
```

**Comment by richiksc** [comment]
Yep, I tried generating a `sum.wasm` file by running a quick Ruby script with the `[...].pack('H*')` from the test block and wrote it to a file. The version I built locally from `cargo install --locked --path lib/cli` came up with the same error:

```
% cargo install --locked --path lib/cli
[build succesful]
% wasmer run sum.wasm --invoke sum 1 2
error: failed to run `sum.wasm` (no compilers enabled)
│   1: module instantiation failed (engine: jit, compiler: headless)
╰─> 2: Validation error: The JITEngine is not compiled with compiler support, which is required for validating
```

I was thinking, maybe we are only building the CLI, and the Wasmer engine needs to be built separately as of 1.0.0.. The documentation for Wasmer says that to build wasmer from source you need to run `make build-wasmer`: https://docs.wasmer.io/ecosystem/wasmer/building-from-source#building-the-wasmer-runtime.

I tried compiling with that on my machine, and nope, same error.
```
% make build-wasmer
% wasmer run sum.wasm --invoke sum 1 2
error: failed to run `sum.wasm` (no compilers enabled)
│   1: module instantiation failed (engine: jit, compiler: headless)
╰─> 2: Validation error: The JITEngine is not compiled with compiler support, which is required for validating
```

**Comment by richiksc** [comment]
I was able to get it to build and run on my M1 local machine with this:

```
% cargo install --locked --path lib/cli --features "cranelift"
% wasmer run sum.wasm --invoke sum 1 2
3
```

🎉🎉🎉

Looks like as of Wasmer 1.0, you have to specify which compiler it should use. The default compiler, which is compatible with arm64 as well as being the one provided in their CI releases, is `cranelift`.

**Comment by carlocab** [comment]
@richiksc Sorry, I haven't really had the chance to look at this properly. Can you open a new PR with the changes you propose? Ping me when you do so I can add the flag to force the ARM runner to attempt a build.

**Pull request closed without merging**
