### PR TITLE
babel 7.14.8

### PR DESCRIPTION
**Pull request by bevanjkay**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by bevanjkay** [comment]
Looks like the same failure as in #81556.

Could be fixed in Homebrew/brew#11750 see;
https://github.com/Homebrew/homebrew-core/pull/81556#issuecomment-883459827

**Comment by carlocab** [comment]
I think `babel-cli` can be update to 7.14.8.

**Comment by bevanjkay** [comment]
I'm new to the world of homebrew-core, is that something we do manually, or is there an automatic way to resolve resource blocks?

**Comment by carlocab** [comment]
They're mostly done automatically for resources from PyPI, but everything else needs to be done manually, sadly.

**Comment by carlocab** [comment]
If #81591 is merged as-is you can rebase this to fix the audit error.

**Comment by carlocab** [comment]
Oops. That new CI error is my fault. Fixed in Homebrew/brew#11755.

**Comment by bevanjkay** [comment]
@carlocab it will still fail until #81591 is merged anyway

**Comment by carlocab** [comment]
Different kind of failure though -- #81591 removes an audit failure that we could choose to ignore. Homebrew/brew#11755 fixes an install failure that we can't ignore.

**Comment by bevanjkay** [comment]
Thanks @carlocab 🥳

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Huh, bottles are all the same. Looks like this installs macOS native modules on Linux too.

**Pull request closed without merging**
