### PR TITLE
meson-internal: fix head

### PR DESCRIPTION
**Pull request by yurikoles**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
I'm actually not sure it makes sense to have HEAD at all for this internal formula. @tschoonj ?

**Comment by javian** [comment]
The upstream issue that is in the patch seems to have been resolved now - is this still an issue ? We have more Formulae depending on the `internal` version rather than the release package which seems a bit odd =)

**Review by tschoonj — COMMENTED** [review]
This is pointless: the patch will not apply as master has diverged considerably and would need to be rewritten considerably.

Fortunately, soon this Formula will become redundant as many GNOME packages are now setting `-compatibility_version` and `-current_version` to appropriate values. There's also going to be a fix in `gobject-introspection` to get workable typelibs when generated with meson.

I will remove this formula when all dependents have been stripped of it.

**Comment by fxcoudert** [comment]
Thanks @tschoonj. I've removed HEAD as it doesn't make sense for this formula: https://github.com/Homebrew/homebrew-core/commit/8066ec3f38bdcdcaae377cc2b1e87324968092f8

**Pull request closed without merging**
