### PR TITLE
solr 8.1.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
I thought the apache url was supposed to assign a mirror on its own? That way the mirror and url might end up to be the same

**Comment by chenrui333** [comment]
yeah, you are right, I will switched it back, sorry for the confusion. :)

**Comment by chenrui333** [comment]
you are right, the mirror is indeed a redundant thing. I found out yesterday too, but did not have a chance to remove it yet. :)

**Comment by SMillerDev** [comment]
Thanks @chenrui333! Without contributions like yours it'd be impossible to keep homebrew going! 👍 🎉

**Pull request merged**
