### PR TITLE
create-dmg 1.0.0.7

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by pthariensflame** [comment]
I don't understand the error here.  :(

**Comment by Bo98** [comment]
Previous attempts: #45310, #50981

**Comment by chenrui333** [comment]
upstream issue, https://github.com/andreyvit/create-dmg/issues/92

**Comment by iMichka** [comment]
Fixed by #55413

**Pull request closed without merging**
