### PR TITLE
krakend 0.5.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@alombarte any idea what's wrong with the test here?

**Comment by alombarte** [comment]
We haven't released yet! Why there is this PR?

**Comment by ilovezfs** [comment]
Because `brew livecheck` picked up the new tag. I'll close the PR.

**Comment by ilovezfs** [comment]
Superseded by https://github.com/Homebrew/homebrew-core/pull/28847

**Pull request closed without merging**
