### PR TITLE
luvit 2.11.3

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
👍 when 🍏.

**Comment by ilovezfs** [comment]
@DomT4 Fixed the problem. Pretty odd. I'm not sure they *ever* run `make install` given that the regression occurred in May (https://github.com/luvit/luvit/commit/86a06bf4ee05b39e098d9845365d5a330f31360b) and still exists in HEAD.

**Comment by ilovezfs** [comment]
Strange. I cannot reproduce the problem with `test-bot` locally.
```
...it-20160622-41688-1fsi191/luvit-2.11.1/deps/readline.lua:471: attempt to call method 'set_mode' (a nil value)
```

**Comment by DomT4** [comment]
That is odd. The patch seems to have made CI happy, at least 😕.

**Comment by ilovezfs** [comment]
@DomT4 Well yes, we have an excellent upstream in this case: https://github.com/luvit/luvit/issues/911#issuecomment-227894137

**Comment by DomT4** [comment]
Nice. Decent of them to offer to cut a new tag with the fixes.

**Comment by creationix** [comment]
Sorry for all the release noise.  I hope the new 2.11.3 tag will work out when the dust settles.

**Comment by ilovezfs** [comment]
@creationix it's no bother at all. Thank you for being so helpful and responsive!

**Comment by ilovezfs** [comment]
@creationix Shipped. Thanks again!

**Pull request closed without merging**
