### PR TITLE
presto 0.254

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by nandahkrishna — APPROVED** [review]

**Comment by samford** [comment]
@chenrui333 The latest version listed on the [first-party download page](https://prestodb.io/download.html) and documentation is `0.253.1`. Per the explanatory comment before the `livecheck` block in this formula, we check the download page instead of Maven (or GitHub tags) because sometimes the [Maven directory listing](https://repo1.maven.org/maven2/com/facebook/presto/presto-server/) will contain a version that isn't yet referenced on the first-party download page, documentation pages, etc.

Unless I'm missing something, it may not be appropriate to treat a new Presto version as officially released until it's listed on the download page. If so, we should wait until that happens to create a version bump PR.

Let's keep an eye on this to see how long it takes for the download page and documentation to be updated to `0.254`. It's only been a day or two since this version was tagged and added on Maven, so it may be a short-term issue.

**Comment by nandahkrishna** [comment]
Sorry, before approving this PR I read the comment above the block indicating that the download page was often outdated. I checked the GitHub repository and found the tag, which is why I approved it. Will be careful next time, thanks Sam.

**Comment by nandahkrishna** [comment]
@samford Actually it seems like there might have been some problem on their side, although I can't be too sure.

The `0.254` version was released a couple of days ago, and `0.253.1` was released a short while before this pull request was created. Their (`presto`'s) automated website updation process seems to have overwritten the changes made for `0.254` (in https://github.com/prestodb/prestodb.github.io/commit/44f56ceb40c8e1eb334aaddf29d92ec253a0f7c2) when `0.253.1` was released (https://github.com/prestodb/prestodb.github.io/commit/3b112b326e32d4fcc73d7be1dcd611c3d0cb2361).

It seems like the `release-0.254` branch has more (newer) commits and `0.253.1` was released to bring a fix (https://github.com/prestodb/presto/commit/4428cf732e8f6b3743d209d2c2327b848cc4c893) to the older `release-0.253` branch (https://github.com/prestodb/presto/commit/672e0b24561142769b150cde14e56959000be635).

If you think it's preferable, I can raise an issue upstream to clarify.

**Comment by samford** [comment]
> If you think it's preferable, I can raise an issue upstream to clarify.

Thanks for looking into this, @nandahkrishna. If you wouldn't mind, I think raising an issue is a good idea. What I'm primarily interested in knowing:

* Is `0.254` the newest stable version or `0.253.1`?
* Should users check the first-party download page (https://prestodb.io/download.html) for the latest stable version or is the newest version on Maven considered the latest stable version? That is to say, if the download page refers to an older version (`0.253.1`) than the newest version on Maven (`0.254`), which is considered the latest stable version?

This would also serve to make them aware of the issue with `0.253.1` overwriting changes from `0.254` on the website (whether that was intentional or not).

**Pull request closed without merging**
