### PR TITLE
elasticsearch 6.8.0

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
```
11:22:46 ==> brew install --verbose elasticsearch
11:22:53 
11:22:53 ==> brew audit elasticsearch --online
11:23:01 ==> FAILED
11:23:01 ==> Installing 'bundler' gem
11:23:01 Successfully installed bundler-2.0.1
11:23:01 1 gem installed
11:23:01 Error: No such file or directory @ rb_sysopen - /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-performance-1.2.0/config/default.yml
11:23:01 
11:23:01 ==> brew style elasticsearch
11:23:03 ==> FAILED
11:23:03 Error: No such file or directory @ rb_sysopen - /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/rubocop-performance-1.2.0/config/default.yml
11:23:03 
```

**Comment by chrmoritz** [comment]
This looks like a current issue with the CI and unrelated to all the PR failing because of it atm. Also notable is that `brew doctor` reports some uncommitted modifications to brew.

BTW: I've started to look into getting the elastic formulae upgraded to version 7 in https://github.com/Homebrew/homebrew-core/compare/master...chrmoritz:elastic7, but I couldn't get `elasticsearch` 7 to work yet.

**Comment by fxcoudert** [comment]
@BrewTestBot test this please

**Comment by zbeekman** [comment]
@chenrui333 can you please update the aliases?

**Comment by chenrui333** [comment]
@zbeekman sure, updating it now.

**Comment by chenrui333** [comment]
Should be good now!

**Comment by zbeekman** [comment]
🍻Thanks!

**Pull request closed without merging**
