### PR TITLE
wine 1.9.15 (devel)

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by DomT4** [comment]
The [Mavericks failure](http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/5242/version=mavericks/testReport/junit/brew-test-bot/mavericks/install___devel_wine/) seems to be a legit one. Happened identically twice in a row.

**Comment by DomT4** [comment]
The failure may have been a false flag after all. Another build later (before your recent push) actually passed. The `wine` formula does this sometimes 😕.

**Comment by apjanke** [comment]
Failed everywhere with a 404 error on an upstream dependency.

@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/4ba4049fb7956b0aa034b862761cb953146a721e. Thanks again @uyjulian! 😺

**Pull request merged**
