### PR TITLE
nut: switch to `openssl@3`

### PR DESCRIPTION
**Pull request by chenrui333**
See #134251.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Error: Failure while executing; `/usr/bin/env /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Linuxbrew/4.0.24-19-g1c081f3\ \(Linux\;\ x86_64\ 5.15.0-1039-azure\)\ curl/7.81.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET [https://github.com/networkupstools/nut/releases/download/v2.8.0/nut-2.8.0.tar.gz`](https://github.com/networkupstools/nut/releases/download/v2.8.0/nut-2.8.0.tar.gz%60) exited with 22. Here's the output:
  curl: (22) The requested URL returned error: 404
  HTTP/2 404
```

**Comment by jimklimov** [comment]
Interesting, thanks. Some time ago a "signed" tag (with GPG sig) was made for same commit, I wonder if github auto-published it instead of the original plain tarball.

**Comment by chenrui333** [comment]
We might also need to update our livecheck on the homebrew side as well.

**Comment by cho-m** [comment]
Looks like our options are the new tag (`v2.8.0-signed`) or the homepage:
```console
❯ curl -sL https://github.com/networkupstools/nut/releases/download/v2.8.0-signed/nut-2.8.0.tar.gz | sha256sum
c3e5a708da797b7c70b653d37b1206a000fcb503b85519fe4cdf6353f792bfe5  -

❯ curl -sL http://www.networkupstools.org/source/2.8/nut-2.8.0.tar.gz | sha256sum
c3e5a708da797b7c70b653d37b1206a000fcb503b85519fe4cdf6353f792bfe5  -
```

**Comment by chenrui333** [comment]
I will update to use the homepage one then

**Comment by chenrui333** [comment]
> Looks like our options are the new tag (`v2.8.0-signed`) or the homepage:
> 
> ```
> ❯ curl -sL https://github.com/networkupstools/nut/releases/download/v2.8.0-signed/nut-2.8.0.tar.gz | sha256sum
> c3e5a708da797b7c70b653d37b1206a000fcb503b85519fe4cdf6353f792bfe5  -
> 
> ❯ curl -sL http://www.networkupstools.org/source/2.8/nut-2.8.0.tar.gz | sha256sum
> c3e5a708da797b7c70b653d37b1206a000fcb503b85519fe4cdf6353f792bfe5  -
> ```

I am actually seeing a different sha

```
$ curl -sL //github.com/networkupstools/nut/releases/download/v2.8.0-signed/nut-2.8.0.tar.gz | shasum -a 256
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  -
```

**Comment by chenrui333** [comment]
linkage verified

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
