### PR TITLE
gdb: add --enable-tui by default

### PR DESCRIPTION
**Pull request by tienhv**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

Add --enable-tui as a default option in building gdb.

### CODE REVIEW

**Comment by DomT4** [comment]
I thought it already was a default, as long as a recent & capable enough `ncurses` was available?

**Comment by dunn** [comment]
Yeah, I don't see this in the `./configure --help` options list.

**Comment by tienhv** [comment]
@DomT4 Might be you are right, on my computer, `--enable-tui ` is enable by default. So it could be the same with other computers.  This could be closed without any change.

**Comment by dunn** [comment]
OK.  Thank you for the submission! ❤️

**Pull request closed without merging**
