### PR TITLE
tunnel 0.5.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
14:53:02 ==> brew test tunnel --verbose
14:53:06 ==> FAILED
14:53:06 Testing tunnel
14:53:06 /usr/bin/sandbox-exec -f /private/tmp/homebrew20191109-95061-rekxg1.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tunnel.rb --verbose
14:53:06 ==> /usr/local/Cellar/tunnel/0.5.3/bin/tunnel ping
14:53:06 dial tcp: missing address
14:53:06 Error: tunnel: failed

**Comment by chenrui333** [comment]
test failed locally on Mojave machine as well.

$ /usr/local/Cellar/tunnel/0.5.3/bin/tunnel ping
dial tcp: missing address

**Comment by vishr** [comment]
@chenrui333 I have fixed the test case and created a new [PR](https://github.com/Homebrew/homebrew-core/pull/46575). You might want to close this one.

**Comment by chenrui333** [comment]
Sounds good. Closing it now.

**Pull request closed without merging**
