### PR TITLE
seal 3.6.4

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
From #74733

> This may no longer support Mojave, as I don't think Mojave supports `aligned_alloc`.
>
>Also, the build seems to be downloading `zlib` ([here](https://github.com/Homebrew/homebrew-core/pull/74733/checks?check_run_id=2285605746#step:7:69)) and `zstd` ([here](https://github.com/Homebrew/homebrew-core/pull/74733/checks?check_run_id=2285605746#step:7:83)).

**Comment by danielnachun** [comment]
Could we retain Mojave support by building with brewed `clang` or `gcc` on that OS?

**Comment by carlocab** [comment]
I doubt it, as I think the problem is that the system calls needed by `aligned_alloc` just aren't there.

**Comment by carlocab** [comment]
It currently vendors the following dependencies: `cpp-gsl`, `zstd`, `zlib`, and `hexl`. We don't currently have a formula for `hexl`.

We can add one, but it doesn't look like it meets the requirements yet: https://github.com/intel/hexl

I suppose we can add it as a resource for this formula.

**Comment by carlocab** [comment]
Figured out a way to keep Mojave support.

**Comment by carlocab** [comment]
Can't get `seal` to find `zstd`. I think `zstd` needs to be built with `cmake` in order to provide the `cmake` modules that allow it to be found.

**Comment by danielnachun** [comment]
Interestingly your solution for getting Mojave to work might actually allow us to build `seal` with `gcc-5` instead of `gcc-10` on Linux.  I'm not sure if it's preferable to use `aligned_alloc` if possible, but I'll have to see if adding the extra flags you used actually lets it build with `gcc-5` at all.

**Comment by carlocab** [comment]
Possibly. The flags as in the current version of the formula will skip using `aligned_alloc` on Linux.

**Comment by carlocab** [comment]
`arangodb` test failure fixed in #75397.

**Comment by carlocab** [comment]
Rebased to pull in fix from https://github.com/Homebrew/homebrew-core/pull/75397.

**Comment by danielnachun** [comment]
@carlocab is this ready to merge now?  It's passing CI with no further issues.

**Comment by carlocab** [comment]
I think so, but I was hoping someone else would review my changes here :)

**Comment by danielnachun** [comment]
> It currently vendors the following dependencies: `cpp-gsl`, `zstd`, `zlib`, and `hexl`. We don't currently have a formula for `hexl`.
> 
> We can add one, but it doesn't look like it meets the requirements yet: https://github.com/intel/hexl
> 
> I suppose we can add it as a resource for this formula.

What was the reason `hexl` couldn't be made into a formula yet?  I have no problem with adding it as a resource, I was just curious what requirement it didn't meet.

**Comment by carlocab** [comment]
If we tried:
```
hexl:
  * GitHub repository not notable enough (<30 forks, <30 watchers and <75 stars)
Error: 1 problem in 1 formula detected
```

**Comment by danielnachun** [comment]
I didn't know there was notability requirement.  Although we shouldn't delay this formula any more over this, I wonder if we should allow an exception if the formula is a dependency of a formula that does meet those requirements.

**Review by danielnachun — APPROVED** [review]
Now that this passes CI, this looks good to me.

**Comment by carlocab** [comment]
If it's a dependency of multiple formulae, then sure. Otherwise I'm inclined to wait till it meets notability requirements.

**Pull request closed without merging**
