### PR TITLE
tin 2.4.3

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
Any ideas why `curl` can't get the file? I can access it just fine from a web browser. Could we maybe mirror it?

**Comment by fxcoudert** [comment]
```
Linking tin v2.4.3 ...
clang  -o ./tin  ./active.o ./art.o ./attrib.o ./auth.o ./charset.o ./color.o ./config.o ./cook.o ./curses.o ./debug.o ./envarg.o ./feed.o ./filter.o ./getline.o ./global.o ./group.o ./hashstr.o ./header.o ./help.o ./inews.o ./init.o ./joinpath.o ./keymap.o ./lang.o ./langinfo.o ./list.o ./lock.o ./mail.o ./main.o ./memory.o ./mimetypes.o ./misc.o ./my_tmpfile.o ./newsrc.o ./nntplib.o ./nrctbl.o ./options_menu.o ./page.o ./parsdate.o ./pgp.o ./plp_snprintf.o ./post.o ./prompt.o ./read.o ./refs.o ./regex.o ./rfc1524.o ./rfc2045.o ./rfc2046.o ./rfc2047.o ./save.o ./screen.o ./search.o ./select.o ./sigfile.o ./signal.o ./strftime.o ./string.o ./tags.o ./tcurses.o ./tmpfile.o ./thread.o ./version.o ./wildmat.o ./xref.o -L../pcre -lpcre  -lcurses  -liconv  
Undefined symbols for architecture x86_64:
  "_bindtextdomain", referenced from:
      _main in main.o
  "_gettext", referenced from:
      _read_news_active_file in active.o
      _create_save_active_file in active.o
      _do_read_newsrc_active_file in active.o
      _show_art_msg in art.o
      _index_group in art.o
      _read_overview in art.o
      _make_threads in art.o
      ...
  "_textdomain", referenced from:
      _main in main.o
```

**Comment by zbeekman** [comment]
The test is garbage too. Only about 1 install per 3 days.

If we can't get this sorted, might consider removal...

**Comment by zbeekman** [comment]
From bzr: http://bzr.tin.org/README.MAC

> configure needs at least the argument:
> --with-domain-name=<your domain>

That might explain the `_textdomain` and `_bindtextdomain` symbols? And maybe it needs gettext linkage now? The state of documentation for the project does not inspire a lot of confidence...

**Pull request closed without merging**
