### PR TITLE
pcb2gcode 2.2.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by carlocab** [comment]
Seems like the vendored boost can be dropped? https://github.com/Homebrew/homebrew-core/pull/30914#issuecomment-412073152

**Comment by chenrui333** [comment]
try out boost 1.75 per https://github.com/pcb2gcode/pcb2gcode/pull/494

**Comment by carlocab** [comment]
```
❯ brew unbottled --tag=arm64_big_sur pcb2gcode
==> Populating dependency tree...
==> :arm64_big_sur bottle status
pcb2gcode: ready to bottle
```
Should we try an ARM build?

**Comment by carlocab** [comment]
This is the build error.
```
checking for glibmm-2.4 >= 2.8... no
configure: error: Package requirements (glibmm-2.4 >= 2.8) were not met:

No package 'glibmm-2.4' found
```
Not sure if they need something newer than 2.4 (we have 2.68), or they just really need 2.4. The 2.8 is confusing, since glibmm appears to be a very old version. [1] glibmm seems to have changed version schemes at some point.

[1] https://download.gnome.org/sources/glibmm/

**Comment by chenrui333** [comment]
> ```
> ❯ brew unbottled --tag=arm64_big_sur pcb2gcode
> ==> Populating dependency tree...
> ==> :arm64_big_sur bottle status
> pcb2gcode: ready to bottle
> ```
> 
> Should we try an ARM build?

i think it would be the same thing.

**Comment by chenrui333** [comment]
> This is the build error.
> 
> ```
> checking for glibmm-2.4 >= 2.8... no
> configure: error: Package requirements (glibmm-2.4 >= 2.8) were not met:
> 
> No package 'glibmm-2.4' found
> ```
> 
> Not sure if they need something newer than 2.4 (we have 2.68), or they just really need 2.4. The 2.8 is confusing, since glibmm appears to be a very old version. [1] glibmm seems to have changed version schemes at some point.
> 
> [1] https://download.gnome.org/sources/glibmm/

we are doing glibmm-2.68, i think it is sufficient.  (`-lglibmm-2.68`)

**Comment by carlocab** [comment]
Maybe there's a problem in their build script? (Or perhaps pkg-config) Since it doesn't seem to think glibmm-2.68 satisfies the requirement.

**Comment by chenrui333** [comment]
> Maybe there's a problem in their build script? (Or perhaps pkg-config) Since it doesn't seem to think glibmm-2.68 satisfies the requirement.

yeah, that is what I think, this is indeed pretty weird.

**Comment by chenrui333** [comment]
Gonna close this one, revisit later.

**Pull request closed without merging**
