### PR TITLE
node@14 14.19.0

### PR DESCRIPTION
**Pull request by derrabus**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Does this install `corepack`? We might want to avoid the potential conflicts it creates...

**Comment by carlocab** [comment]
Ping @derrabus

**Comment by derrabus** [comment]
I've just built the formula locally and can confirm that `corepack` is installed to the formula's bin directory. The `node@16` formula does this as well. How shall we proceed? Remove `corepack` from both formulae?

**Comment by carlocab** [comment]
Hmmm. No, now that I think about it, we can just ignore it. The `corepack` formula is built with the unversioned `node`, plus `node@14` and `node@16` are keg-only.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
