### PR TITLE
platypus 5.4

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
The artifact has some issue

**Review by SMillerDev — DISMISSED** [review]

**Review by fxcoudert — DISMISSED** [review]

**Review by SMillerDev — DISMISSED** [review]

**Comment by fxcoudert** [comment]
I do not know why the CI is green because the bottles actually fail to build.

**Comment by SMillerDev** [comment]
Probably because only macOS 12 is eligible and that one does not have a bottle so it's failure doesn't block the CI.

**Comment by fxcoudert** [comment]
`2022-10-12T11:25:41.1961830Z [31mError:[0m Failure while executing; /usr/bin/env PATH=/opt/homebrew/opt/unzip/bin:/opt/homebrew/Library/Homebrew/shims/mac/super:/usr/bin:/bin:/usr/sbin:/sbin unzip -o /Users/brew/Library/Caches/Homebrew/downloads/97f5412663fb585ec8aade7a3f19052d8d35e44be8fabe9e6145ef6efe2c0838--platypus5.4.src.zip -d /private/tmp/d20221012-90757-pluwk4 exited with 1.`

**Comment by iMichka** [comment]
The zip file is weird. I have opened an issue upstream: https://github.com/sveinbjornt/Platypus/issues/240

**Pull request closed without merging**
