### PR TITLE
pyenv 2.0.5

### PR DESCRIPTION
**Pull request by shigemk2**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
```
pyenv:
  * A top-level "man" directory was found.
    Homebrew requires that man pages live under "share".
    This can often be fixed by passing `--mandir=#{man}` to `configure`.
```

**Comment by memark** [comment]
Probably caused by
https://github.com/pyenv/pyenv/pull/2032

**Comment by bayandin** [comment]
> Not sure what needs to be done though.

if `make` doesn't support MANDIR then something like `share.install prefix/"man"` should help I guess.

**Comment by thecesrom** [comment]
Would a simple `man1.install` help?

```ruby
      man1.install "#{prefix}/man/man1/pyenv.1"
```

**Comment by bayandin** [comment]
> Would a simple `man1.install` help?
> 
> ```ruby
>       man1.install "#{prefix}/man/man1/pyenv.1"
> ```

It will install manpages, but it won't do anything with the top-level man directory, and the audit will fail again.

We already have `share.install prefix/"man"` in a bunch of other formulae, so it's ok to add it here.
```bash
$ git grep -l 'share.install prefix/"man"' 
Formula/ccze.rb
Formula/dune.rb
Formula/hydra.rb
Formula/innotop.rb
Formula/midicsv.rb
Formula/mytop.rb
Formula/ngs.rb
Formula/percona-toolkit.rb
Formula/ucspi-tcp.rb

```

**Review by bayandin — APPROVED** [review]
Thanks for checking this @thecesrom!

**Pull request closed without merging**
