### PR TITLE
triage(long build): add `python-setuptools`

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----
- https://github.com/Homebrew/homebrew-core/pull/154945

### CODE REVIEW

**Review by dtrodrigues — APPROVED** [review]

**Comment by Bo98** [comment]
Should setuptools have as many runtime dependencies as it does? Some of them seem off.

**Comment by branchvincent** [comment]
some might be wrong but there are a lot of projects that assume `pkg_resources` is available (they really should use `importlib` now). we prob want to at least create upstream bugs for those cases

**Comment by Bo98** [comment]
It would be good to document why, say, opencv needs it at runtime.

**Comment by branchvincent** [comment]
Good catch, that one's not right: #155121

**Pull request merged**
