### PR TITLE
phockup@1.2.0 (new formula)

### PR DESCRIPTION
**Pull request by ivandokov**
This formula installs the photos and videos sorting software called phockup (photo backup).
The software will collect all files from an input directory and transfer them to an output directory
without changing the files content. It will only rename the files and place them in the proper directory
for the year, month and day.

### CODE REVIEW

**Comment by ivandokov** [comment]
Since this is my first time interacting with homebrew from backend side of the app I'll need some help to fix the error from `brew audit --strict phockup` because it is too generic and I have no idea what's wrong.

```Error: Error running `rubocop --format json --force-exclusion --parallel --config /usr/local/Homebrew/Library/.rubocop.yml /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/phockup.rb```

**Comment by ilovezfs** [comment]
This will be fixed once https://github.com/Homebrew/brew/pull/2718 is merged.

**Comment by ivandokov** [comment]
@ilovezfs is this holding up the merge?

**Comment by ivandokov** [comment]
@ilovezfs this error sounds like a not fair one. Do you accept only popular software?
```
Error: 1 problem in 1 formula
phockup:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
```

**Comment by JCount** [comment]
@ivandokov As a matter of general policy, we generally do not accept self-submissions for new formula. Furthermore, the reason for that audit failure you are getting is not meant as an insult to your project, but is rather a necessary element to prevent `homebrew-core` from becoming unmaintainable. 

Adding a formula to the main core repository has an impact on the total overhead maintainers have to deal with, so unfortunately, we cannot accept all formula submissions. One of the easiest ways, and objectively fairest, is to look at how much community involvement there is with the given open source project.
```
Error: 1 problem in 1 formula
phockup:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
```
The essence of the meaning behind this audit failure, is not strictly based on popularity in the general sense, but rather whether there seems to be an active community around the project. 

What you can do would be to host a third-party tap, and see if you can get more people involved/interested in your project, and transform it from being mainly a personal project into a community-oriented project.

**Comment by ivandokov** [comment]
It's quite hard to attract people to try your software when they have to manually install it with more than 1 step. 
At the moment I'm working on a snap application for Ubuntu and other snapd supported OSes. With a single command they can try my software, but it will be cool if I can target Mac users too.

Can you please point me to a documentation/guide of how I can create this third-party tap. Thanks.

**Comment by ilovezfs** [comment]
@ivandokov https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap

**Comment by ivandokov** [comment]
Thank you for your info. I already created my [third-party tap](https://github.com/ivandokov/homebrew-contrib) and it works just fine

**Comment by ilovezfs** [comment]
@ivandokov you're welcome!

**Pull request closed without merging**
