### PR TITLE
fontforge: add dependency on woff2

### PR DESCRIPTION
**Pull request by ahankinson**
Generating WOFF2 fonts with the current fontforge installation does not work. Adding the woff2 library dependency allows it to work correctly.

Refs #111516

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

The tests fail on my machine, but I think they are failing anyway; this change does not affect anything to do with the tests, and the package works fine.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks. Can we add a test that adding this dependency works as expected?

**Comment by ahankinson** [comment]
That would actually be quite awkward.

The problem that I had, and that this fixes, is that **without** adding this WOFF2 dependency, Fontforge will still happily convert the font; it will just be a PostScript Type 1 font instead of a WOFF2. So we would have to call the test with a font file (I'm not sure if any are shipped, so we would need to add one?) and then somehow dig through the (binary) output to verify that the output is WOFF2. 

I'm not really that clever. 😄 

The (upstream) fix to fontforge would be to fail creating WOFF2 if the library isn't bundled. But since I'm just a bit of a drive-by committer that debugged a specific problem and a fix that I verified to work on a couple machines, I'm afraid that's a bit out of scope for me here.

**Comment by carlocab** [comment]
> So we would have to call the test with a font file (I'm not sure if any are shipped, so we would need to add one?) and then somehow dig through the (binary) output to verify that the output is WOFF2.

What kind of font file do we need? Does anything that ships with macOS work? If not, we can add one as a `resource` block.

As for checking whether it is WOFF2, I suspect `file` should be able to do the job -- it's quite good at working out file types, so we can leave the binary parsing to `file` and just check the text output it generates.

> I'm afraid that's a bit out of scope for me here.

I disagree -- that is, at least, if you intend for your change to stick. If you don't, then I'd agree that the test may be out-of-scope. Without a test then anyone can come along to "clean up" the formula by removing "unneeded" dependencies, sees that the test passes, and submits a PR, which will likely be merged.

You might be tempted to leave a comment, but a reviewer is likely to dismiss that comment as outdated and no longer applicable unless it is supported by a test that will fail when the necessary functionality is removed.

**Comment by ahankinson** [comment]
Ok, I will ask the fontforge folks for help.

**Comment by ahankinson** [comment]
@carlocab I think this is ready for re-review now.

**Review by carlocab — DISMISSED** [review]
Nice work! Cleaned this up a little bit for you.

**Review by carlocab — DISMISSED** [review]

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
