### PR TITLE
odin: add patch to fix test

### PR DESCRIPTION
**Pull request by Rylan12**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fix the test for 11.0 for #66450

This was reported upstream in https://github.com/odin-lang/Odin/issues/792 and was resolved in https://github.com/odin-lang/Odin/pull/768. The patch does not apply cleanly, so I needed to rewrite it.

### CODE REVIEW

**Comment by carlocab** [comment]
That was on my to-do list. Though it had been there for a while now. Thanks for fixing this!

**Comment by Rylan12** [comment]
> That was on my to-do list. Though it had been there for a while now.

Story of my life

**Comment by carlocab** [comment]
Ah, now I remember why I left it. I remember trying to build Odin off their master branch using `brew install --HEAD` and that didn't work either. That then gave me the impression that it would take more work to fix, and gave up. Guess I should've persisted for a bit longer...

**Comment by Rylan12** [comment]
Hmm maybe we'll have to deal with that when there's a new release... 😦

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
