### PR TITLE
prestd 1.0.12

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Upstream latest release is `1.0.9`. Did we merge `1.0.10` while it was a pre-release?

**Comment by chenrui333** [comment]
I dont think 1.0.10 is a pre-release, but we can wait a bit on this PR merge though.

**Comment by avelino** [comment]
sorry for the inconvenience, I am working on a release generation fix

**Comment by avelino** [comment]
we had a problem with the generation of version `1.0.11`, I fixed it and we generated version `1.0.12`

do i need to do anything in homebrew?

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
