### PR TITLE
clojure 1.8.0.135, 1.9.0-alpha20.176 (devel)

### PR DESCRIPTION
**Pull request by puredanger**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
We don't include general information in the `caveats`, only Homebrew-specific information.

**Comment by puredanger** [comment]
@fxcoudert sorry about that, fixed

**Comment by ilovezfs** [comment]
Thanks @puredanger!

For future reference, when a PR updates both stable and devel the commit subject should be
```
clojure 1.8.0.135, 1.9.0-alpha20.176 (devel)
```

**Comment by puredanger** [comment]
Noted, thanks!

**Pull request merged**
