### PR TITLE
Git 2.25.1

### PR DESCRIPTION
**Pull request by leonklingele**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by leonklingele** [comment]
#50333 was incomplete.

**Comment by shigemk2** [comment]
Should I send one pull request with git and git-gui?
https://github.com/Homebrew/homebrew-core/pull/50334
https://github.com/Homebrew/homebrew-core/pull/50333

**Comment by leonklingele** [comment]
👍🏼 and make sure to increase the version of the other sources to 2.25.1

**Comment by shigemk2** [comment]
I see. Thank you so much.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by fxcoudert** [comment]
- `git.rb` has an extra blank line at line 166.
- The test is failing

**Comment by chenrui333** [comment]
Close in favor of #50683

**Pull request closed without merging**
