### PR TITLE
hadolint 2.2.0

### PR DESCRIPTION
**Pull request by Tenzer**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Looks like this isn't showing as the latest release on GitHub yet: https://github.com/hadolint/hadolint/releases

Can we double check that this isn't just an oversight?

**Comment by Tenzer** [comment]
It's possible I've been too quick at creating this PR and they haven't finished the work related to making a new release yet. We can wait a bit until a new GitHub release is created before merging.

**Comment by carlocab** [comment]
Just adding label to make sure it's not merged accidentally. Ping me when it's the latest release on GitHub.

Thanks, @Tenzer.

**Comment by Tenzer** [comment]
It has been fully released now: https://github.com/hadolint/hadolint/releases/tag/v2.2.0.

**Review by carlocab — APPROVED** [review]
Thanks @Tenzer!

**Pull request closed without merging**
