### PR TITLE
ansible: add proxmoxer support

### PR DESCRIPTION
**Pull request by domrim**
Bumps revision and adds the python library proxmoxer to add support
for the community.general.proxmox modules & plugins

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by domrim** [comment]
can this get merged? ci runs finally seem to be fine :)

**Comment by SMillerDev** [comment]
This will also need to be added to https://github.com/Homebrew/homebrew-core/blob/master/pypi_formula_mappings.json otherwise it's gone on the next update

**Comment by domrim** [comment]
> This will also need to be added to https://github.com/Homebrew/homebrew-core/blob/master/pypi_formula_mappings.json otherwise it's gone on the next update

thanks for the info. fixed it

**Review by iMichka — DISMISSED** [review]

**Comment by iMichka** [comment]
Thanks @domrim !

**Pull request closed without merging**
