### PR TITLE
freetype 2.10.2

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by issyl0** [comment]
```
==> FAILED
Broken dependencies:
  /usr/local/opt/gmp/lib/libgmp.10.dylib (gmp)

==> brew install --only-dependencies --include-test allureofthestars
==> brew test --verbose allureofthestars
==> FAILED
Testing allureofthestars
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200510-5315-p4qfnx.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/allureofthestars.rb --verbose
==> /usr/local/Cellar/allureofthestars/0.9.5.0/bin/Allure --dbgMsgSer --dbgMsgCli --logPriority 0 --newGame 3 --maxFps 100000 --stopAfterFrames 50 --automateAll --keepAutomated --gameMode battle --setDungeonRng 7 --setMainRng 7
dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /usr/local/Cellar/allureofthestars/0.9.5.0/bin/Allure
  Reason: image not found
```

Revision bump for gmp?

**Comment by chenrui333** [comment]
> ```
> ==> FAILED
> Broken dependencies:
>   /usr/local/opt/gmp/lib/libgmp.10.dylib (gmp)
> 
> ==> brew install --only-dependencies --include-test allureofthestars
> ==> brew test --verbose allureofthestars
> ==> FAILED
> Testing allureofthestars
> /usr/bin/sandbox-exec -f /private/tmp/homebrew20200510-5315-p4qfnx.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/allureofthestars.rb --verbose
> ==> /usr/local/Cellar/allureofthestars/0.9.5.0/bin/Allure --dbgMsgSer --dbgMsgCli --logPriority 0 --newGame 3 --maxFps 100000 --stopAfterFrames 50 --automateAll --keepAutomated --gameMode battle --setDungeonRng 7 --setMainRng 7
> dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
>   Referenced from: /usr/local/Cellar/allureofthestars/0.9.5.0/bin/Allure
>   Reason: image not found
> ```
> 
> Revision bump for gmp?

that is good point! try that now

**Comment by chenrui333** [comment]
same error, wonder if `allureofthestars` still re-buildable.

**Comment by SMillerDev** [comment]
```
Error: 4 failed steps!
brew linkage --test allureofthestars
brew test --verbose allureofthestars
brew test --verbose mat2
brew test --verbose mlton
```

**Comment by chenrui333** [comment]
not actively working on this, closing the PR now.

**Pull request closed without merging**
