### PR TITLE
pygitup 1.6.1

### PR DESCRIPTION
**Pull request by msiemens**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by igas** [comment]
```
pkg_resources.DistributionNotFound: The 'click>=7.0.0' distribution was not found and is required by git-up
```

**Comment by igas** [comment]
@msiemens formula needs resource updates.

**Comment by msiemens** [comment]
@igas Should be fixed now, the tests are now passing 🙂

**Comment by Moisan** [comment]
When we bump a formula version, we want to also update the version of all its resources. For example, the latest version of `colorama` is currently 0.4.1. Could you update the other resources too please?

**Comment by msiemens** [comment]
@Moisan Done!

By the way, is there a way to update the download URLs and hashes automatically in cases like this one?

**Comment by fxcoudert** [comment]
Thanks @msiemens!

**Pull request closed without merging**
