### PR TITLE
python@3.10: remove include_dirs, library_dirs from distutils.cfg

### PR DESCRIPTION
**Pull request by mkoeppe**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Homebrew's python3 installs `distutils.cfg`, which injects include and library paths into the build of every user package. The injected directories appear at the beginning of the paths and hence take precedence over paths configured by the packages' build systems. (We encountered this in the SageMath project in https://trac.sagemath.org/ticket/31335; our workaround is to use `SETUPTOOLS_USE_DISTUTILS=local`, thus disabling homebrew's copy of distutils.) 
In this PR, we remove one item from these paths, with the eventual goal of removing `distutils.cfg` altogether. `distutils.cfg` is an outdated and problematic mechanism, which is moreover set to be ineffective for packages that use `setuptools` when `setuptools` (again) makes `SETUPTOOLS_USE_DISTUTILS=local` the standard behavior (https://github.com/pypa/setuptools/pull/2896). See also #76621.

### CODE REVIEW

**Comment by Bo98** [comment]
I'd rather the include/library directories were all dealt with at the same time rather than removing a random one. I definitely agree they should go, even if I'm a little cautious at what we're potentially breaking here.

(I'm aware of the future setuptools issue in regards to `prefix` but I am already working on a solution for that)

>  The injected directories appear at the beginning of the paths and hence take precedence over paths configured by the packages' build systems.

More of a side note this, but this is pretty much specific to your use of the compiler-level `CPATH`. Unless something changed recently, `CFLAGS` and the use of `Extension`'s `include_dirs` in `setup.py` don't behave this way.

**Comment by mkoeppe** [comment]
> I'd rather the include/library directories were all dealt with at the same time rather than removing a random one. I definitely agree they should go, even if I'm a little cautious at what we're potentially breaking here.

OK, I have made this change

**Comment by mkoeppe** [comment]
ping?

**Comment by Bo98** [comment]
Apologies for the late response. This has been merged as a part of 3.10.2. We decided it was best to remove `distutils.cfg` entirely all at the same time rather than selectively remove parts over time. We're monitoring if anything has broken so let us know if it makes things better or worse for you.

I'm not entirely sure yet what we'll backport to Python 3.9 and earlier. We could backport this bit if needed, but there'll still be some form of `distutils.cfg` that's around for those versions.

**Comment by mkoeppe** [comment]
Thanks for the update!

**Pull request closed without merging**
