### PR TITLE
latexindent 3.23

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by p-linnane** [comment]
Not the latest release: https://github.com/cmhughes/latexindent.pl/releases

**Comment by cmhughes** [comment]
If anyone can help with the latexindent.pl issue, please do let me know. I am unsure why this has stopped working, all help welcome.

**Comment by cmhughes** [comment]
This should now be resolved from the point of view of `latexindent.pl`, with credit to @chenrui333 and @eggplants

**Comment by chenrui333** [comment]
> This should now be resolved from the point of view of `latexindent.pl`, with credit to @chenrui333 and @eggplants

np, happy to help 🎉

**Comment by p-linnane** [comment]
@cmhughes v3.23 is still not a GitHub release. Are you able to cut the release and mark it as latest please?

**Comment by cmhughes** [comment]
Done, I hope. Can you try now?

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
