### PR TITLE
mavsdk 1.4.16

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.

### CODE REVIEW

**Comment by carlocab** [comment]
Check with unversioned `grpc`/`protobuf`?

**Comment by carlocab** [comment]
> Check with unversioned `grpc`/`protobuf`?

But we should probably try only after merging #132957.

**Comment by chenrui333** [comment]
> > Check with unversioned `grpc`/`protobuf`?
> 
> But we should probably try only after merging #132957.

totally, I can revisit it after the other PR.

**Comment by carlocab** [comment]
This should fix the CI failure: #132988

**Comment by carlocab** [comment]
The protobuf patch fixed one error, but it looks like there is now a problem with gRPC.

**Comment by carlocab** [comment]
Pushed a fix for `grpc`. Will upstream if it works.

**Review by carlocab — APPROVED** [review]

**Review by branchv — APPROVED** [review]

**Review by carlocab — APPROVED** [review]

**Pull request merged**
