### PR TITLE
New formula: wal2json

### PR DESCRIPTION
**Pull request by singingwolfboy**
Repository is here: https://github.com/eulerto/wal2json

Writing a test for this was difficult. I ended up using the example query in the README for the project.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Does it require a local postgres version at runtime?

**Comment by singingwolfboy** [comment]
@SMillerDev yes, this is a plugin for Postgres, so you can't use it without Postgres. I marked that the formula `depends_on "postgresql"` -- is there anything else I need to do?

**Comment by SMillerDev** [comment]
No, that makes sense. Just wanted to make sure we couldn't just get away with a build dependency.

**Comment by singingwolfboy** [comment]
After several attempts, the Jenkins build is finally passing! 🎉  I think this pull request is ready for human review.

**Comment by SMillerDev** [comment]
Can you rebase on the latest master please?

**Comment by singingwolfboy** [comment]
@SMillerDev Done

**Comment by SMillerDev** [comment]
@singingwolfboy can you reword your commit to be `<formula_name> <version> (new formula)`?

**Comment by singingwolfboy** [comment]
@SMillerDev done, and rebased as well. In the future, will there be a lint rule to check for how the commit name is worded?

**Comment by SMillerDev** [comment]
There is one before merging but maybe that should be here as well yeah.

**Comment by SMillerDev** [comment]
Thanks a lot @singingwolfboy. Without people like you we wouldn't be able to maintain homebrew to the high standards people have come to expect from us.

**Pull request closed without merging**
