### PR TITLE
terraform 0.12.15

### PR DESCRIPTION
**Pull request by dio-az**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?
-----

### CODE REVIEW

**Comment by chenrui333** [comment]
relates to #46726

**Comment by diogoazevedos** [comment]
@chenrui333 should we close #46726?

**Comment by chenrui333** [comment]
yeah, please! Thanks!

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
20:34:45 go test -mod=vendor -timeout=2m -parallel=4 github.com/hashicorp/terraform/terraform github.com/hashicorp/terraform/tfdiags github.com/hashicorp/terraform/tools/loggraphdiff github.com/hashicorp/terraform/tools/terraform-bundle
20:34:45 ok  	github.com/hashicorp/terraform/terraform	4.366s
20:34:45 ok  	github.com/hashicorp/terraform/tfdiags	0.013s
20:34:45 ?   	github.com/hashicorp/terraform/tools/loggraphdiff	[no test files]
20:34:45 ?   	github.com/hashicorp/terraform/tools/terraform-bundle	[no test files]
20:34:45 go test -mod=vendor -timeout=2m -parallel=4 github.com/hashicorp/terraform/tools/terraform-bundle/e2etest github.com/hashicorp/terraform/version
20:34:45 ok  	github.com/hashicorp/terraform/tools/terraform-bundle/e2etest	2.717s
20:34:45 ?   	github.com/hashicorp/terraform/version	[no test files]
20:34:45 make: *** [test] Error 1
20:34:45

**Comment by chenrui333** [comment]
@diogoazevedos, looks like failed in the build? I am going to test myself as well.

**Comment by chenrui333** [comment]
catalina install works fine for me locally.

```
$ brew reinstall terraform
==> Reinstalling terraform
==> Downloading https://homebrew.bintray.com/bottles/terraform-0.12.15.catalina.bottle.tar.gz
##O=#  #
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "terraform"
Download failed: https://homebrew.bintray.com/bottles/terraform-0.12.15.catalina.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Installing dependencies for terraform: gox
==> Installing terraform dependency: gox
==> Downloading https://homebrew.bintray.com/bottles/gox-1.0.1.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/66/6693416aef377d44385c25eb786d25f963258c0895491beedbf
######################################################################## 100.0%
==> Pouring gox-1.0.1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/gox/1.0.1: 5 files, 3.9MB
==> Downloading https://github.com/hashicorp/terraform/archive/v0.12.15.tar.gz
==> Downloading from https://codeload.github.com/hashicorp/terraform/tar.gz/v0.12.15
######################################################################## 100.0%
==> make tools test bin
🍺  /usr/local/Cellar/terraform/0.12.15: 6 files, 50.3MB, built in 9 minutes 44 seconds
Removing: /usr/local/Cellar/terraform/0.12.9... (6 files, 49.2MB)
```

**Comment by chenrui333** [comment]
test step locally.
```
$ brew test terraform
Testing terraform
==> /usr/local/Cellar/terraform/0.12.15/bin/terraform init
==> /usr/local/Cellar/terraform/0.12.15/bin/terraform graph
```

**Comment by dawidd6** [comment]
Installation fails because `go test` fails:
```
2019/11/15 01:35:12 listen tcp 127.0.0.1:8080: bind: address already in use
```

**Comment by chenrui333** [comment]
Removed `tests` goal

**Pull request closed without merging**
