### PR TITLE
qscintilla2: fix build with Xcode 8

### PR DESCRIPTION
**Pull request by ilovezfs**
CC @schoeps @justinclift @dpo

### CODE REVIEW

**Comment by justinclift** [comment]
As a note, upstream has completely ignore the bug report about this on their mailing list:

&nbsp; &nbsp; https://www.riverbankcomputing.com/pipermail/qscintilla/2016-October/001160.html

Looking through their archives, they seem to ignore 95% of everything.  Would recommend steering clear of QScintilla2 for new projects. 😦

**Comment by ilovezfs** [comment]
@justinclift is it possible there's some other mechanism for contacting/reporting other than the mailing list?

**Comment by justinclift** [comment]
Their contact page directs people to the mailing list, and also says:

> Unless you are a commercial customer, do not email Riverbank directly.

So, I'm thinking no?

**Comment by ilovezfs** [comment]
```
You are buying 1 PyQt commercial license at £350.00.
```

If they're going to ignore anyone who hasn't given them $429.00, then it sounds like the project needs to be forked or not used. I suspect it's worth emailing support@riverbankcomputing.com and hoping they don't look a gift horse in the mouth since macOS is one of their officially supported platforms for paying customers.

**Comment by justinclift** [comment]
Hmmm, I'll give it a few more days before doing that.  Just in case.

**Comment by ilovezfs** [comment]
Yup, no problem.

**Pull request closed without merging**
