### PR TITLE
maven 3.5.2

### PR DESCRIPTION
**Pull request by bric3**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?  <==== **Is it applicable ?**
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Here's an update for maven 3.5.2. 

-----------------------------------------------------
Manual pull request because `hub` has issues.

<details><summary>`brew bump-formula-pr`</summary>

```sh
brew bump-formula-pr --strict maven --url="https://www.apache.org/dyn/closer.cgi\?path\=maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz" --sha256="beb91419245395bd69a4a6edad5ca3ec1a8b64e41457672dc687c173a495f034"                                        •100%
Already up-to-date.
==> replace / +mirror \"https:\/\/archive.apache.org\/dist\/maven\/maven-3\/3.5.0\/binaries\/apache-maven-3.5.0-bin.tar.gz\"\n/m with ""
==> replace "https://www.apache.org/dyn/closer.cgi?path=maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz" with "https://www.apache.org/dyn/closer.cgi\\?path\\=maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz"
==> replace "beb91419245395bd69a4a6edad5ca3ec1a8b64e41457672dc687c173a495f034" with "beb91419245395bd69a4a6edad5ca3ec1a8b64e41457672dc687c173a495f034"
M	Formula/maven.rb
Switched to a new branch 'maven-3.5.2'
[maven-3.5.2 b9413df2cd] maven 3.5.2
 1 file changed, 1 insertion(+), 2 deletions(-)


Error: cannot get remote from 'hub'!
```

</details>

-----------------------------------------------------

 Indicates the source and target version to 1.8.

By default the compiler plugin of maven assumes a source and target
level aimed at Java 1.5 (5) by default :

https://maven.apache.org/plugins/maven-compiler-plugin/index.html

The used java version on jenkins.brew.sh is not logged, but since the
`maven` formula depend on the `java` formula which targets java 9 it
explains why the build is failing, as Java 9 dropped support for
Java 1.5 (5) : http://openjdk.java.net/jeps/182

To fix this the test pom indicates a more recent source level.

### CODE REVIEW

**Comment by bric3** [comment]
It seems the test is deprecated, the error is about the target / source level :

```
Target option 1.5 is no longer supported. Use 1.6 or later.
```

**Comment by bric3** [comment]
Ok found the issue, see ba20536, the basics behinds it is that the test doesn't specify which version of java the tests runs on, and the current one seems to be java 9, that removed source and target 1.5. Unfortunately if not explicitly set, maven uses 1.5 as a default source and target.

**Comment by ilovezfs** [comment]
@bric3 it looks like the email address you're committing from is not associated with your GitHub account. Can you please fix that so that the contributor statistics will be correct?

**Comment by ilovezfs** [comment]
@bric3 could I convince you to open PRs fixing the tests in maven@3.0 and maven@3.3? :innocent:

**Comment by bric3** [comment]
Ah you're right I commited with my company email. Re-authoring.

Yes sure, I'll fix other maven formulas.

**Comment by ilovezfs** [comment]
@bric3 regarding `hub` you need to use stable or HEAD. devel doesn't work.

**Pull request merged**
