### PR TITLE
readline 7.0.1

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This may also require revision bumps for other formulae.

### CODE REVIEW

**Comment by ilovezfs** [comment]
The CI issue with postgresql turns out to be a `brew test` bug and a `brew test-bot` bug. While `brew test foo` requires `bar` to be linked if `foo` depends on `bar`, `brew test bar` will not require `bar` to be linked, which would only be appropriate if `bar` is `keg_only`. The postgresql error is what you get if you run `brew test postgresql` with postgresql unlinked. The reason it is unlinked is that it `conflicts_with` with postgres-xc, and so test-bot will unlink postgresql so that it can install and test postgres-xc. But it doesn't relink postgresql after the postgres-xc test is completed, and since `brew test` doesn't error out requiring postgresql be linked before running, the weird error output in the CI log occurs because postgresql is tested while unlinked.

CC @MikeMcQuaid

**Comment by ilovezfs** [comment]
@JCount thanks for the :gift: Your contribution to Homebrew is much appreciated.

**Comment by MikeMcQuaid** [comment]
@ilovezfs `brew test`s should be written such that they work unlinked.

**Comment by ilovezfs** [comment]
@MikeMcQuaid then shouldn't we unlink before running the test?

**Comment by MikeMcQuaid** [comment]
@ilovezfs Could do, yep.

**Comment by ilovezfs** [comment]
Would be quite interesting to see how many fail!

**Comment by JCount** [comment]
I see the Jenkins standing in a sea of 🔥

**Comment by ilovezfs** [comment]
@JCount :see_no_evil:

**Pull request closed without merging**
