### PR TITLE
gnupg 2.1.20

### PR DESCRIPTION
**Pull request by neutric**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Reported https://dev.gnupg.org/T3047

**Comment by neutric** [comment]
Thanks @ilovezfs!

**Comment by adam-moss** [comment]
Just to ask before I submit an work up a PR - is there any objection to including the build option `--enable-large-secmem` in this formula?  If not should this be defaulted or as a `--with` type option?  Thanks.

**Comment by DomT4** [comment]
Looks like upstream has fixed already, and pointed out what needs to be cherry picked here 🎉

**Comment by neutric** [comment]
Yep, will put those patches in asap.

**Comment by ilovezfs** [comment]
@DomT4 unfortunately the patches don't quite seem to solve it yet :see_no_evil: 

https://dev.gnupg.org/T3047#95217

**Comment by ilovezfs** [comment]
Of course the switcheroo of `make install` and `make check` works again https://dev.gnupg.org/T3047#95238.

**Comment by ilovezfs** [comment]
And looks like it works now in the original order with an additional fix from upstream: https://dev.gnupg.org/T3047#95251

**Comment by neutric** [comment]
I'll try and remember to switch the make order back come next release.

**Comment by neutric** [comment]
Again, thanks so much for your help @ilovezfs 🍌

**Comment by ilovezfs** [comment]
you're welcome

**Comment by DomT4** [comment]
Now I can go back to debugging whether the issues I've had locally with 2.1.x are simply caused by the way I use it or not 😓. Thanks for getting the update sorted @neutric ❤️.

**Pull request closed without merging**
