### PR TITLE
Update jpeg sha256sum

### LINKED ISSUE #68728: jpeg sources differ
If you look at https://github.com/Homebrew/homebrew-core/blob/master/Formula/jpeg.rb, it lists three different locations for source files. The first one, https://www.ijg.org/files/jpegsrc.v9d.tar.gz produces a different checksum than the one listed in the .rb file. The second one, https://dl.bintray.com/homebrew/mirror/jpeg-9d.tar.gz, produces a 404. Only the third one, https://fossies.org/linux/misc/jpegsrc.v9d.tar.gz, produces the checksum listed in the .rb file.

The modification date for the first one appears to be January 7th 2021, while the last one January 12th 2020. After unpacking both archives, and running a diff, the contents appear to be identical. Just the archives are different.

No need to use brew to verify, you can download the files however you want (I used wget).

As a result, trying to build jpeg fails.

# Bug report

## What you were trying to do (and why)

Build the jpeg bottle from source. Doesn't matter why.

## What happened (include command output)
<pre>
Error: SHA256 mismatch
Expected: 99cb50e48a4556bc571dadd27931955ff458aae32f68c4d9c39d624693f69c32
  Actual: 6c434a3be59f8f62425b2e3c077e785c9ce30ee5874ea1c270e843f273ba71ee
</pre>

## Step-by-step reproduction instructions (by running `brew install` commands)
<pre>brew install --build-bottle jpeg</pre>

### PR DESCRIPTION
**Pull request by PeterSurda**
- source was silently updated without bumping the version
- fixes #68728
- haven't tested anything

### CODE REVIEW

**Comment by PeterSurda** [comment]
Regarding CI failures, I did contact upstream and the change appears legitimate. There was apparently some encoding issue with the original file, that caused problems on some platforms. When I run a diff on the contents of both on linux, it doesn't show any differences. I don't know why they didn't bump the version, maybe they didn't realise it will cause problems downstream. The mirror has also been updated with the new version.

**Review by SMillerDev — APPROVED** [review]

**Comment by jonchang** [comment]
Thanks for tracking this down @PeterSurda, and thanks for contributing to Homebrew!

**Comment by robni7** [comment]
Hiya, it seems that the checksum has again changed, this time into `2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a`

I know too little about the workings of Brew to suggest another pull request, but I hope a dev can pick it up from here.
Cheers ;)

**Comment by yakejiao** [comment]
Error: SHA256 mismatch
Expected: 6c434a3be59f8f62425b2e3c077e785c9ce30ee5874ea1c270e843f273ba71ee
  Actual: 2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a

**Comment by andida** [comment]
> Error: SHA256 mismatch Expected: 6c434a3be59f8f62425b2e3c077e785c9ce30ee5874ea1c270e843f273ba71ee Actual: 2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a

I face the same issue

**Comment by andida** [comment]
> Error: SHA256 mismatch Expected: 6c434a3be59f8f62425b2e3c077e785c9ce30ee5874ea1c270e843f273ba71ee Actual: 2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a

I solved the problem on my MAC.  edit jpeg:
1.
`brew edit jpeg`
2. find the sha256 6c434a3be59f8f62425b2e3c077e785c9ce30ee5874ea1c270e843f273ba71ee, change it to 2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a
3.save and exit 
then reinstall: 
`brew install --build-bottle jpeg`

**Comment by Bo98** [comment]
Looks like there's something wrong with your Homebrew installation not updating. The current version of the formula does _not_ have that sha256. You should investigate why that is (e.g. does `brew update` error?)

**Pull request merged**
