### PR TITLE
grafana 4.0.1

### PR DESCRIPTION
**Pull request by torkelo**
Grafana Version Update

### CODE REVIEW

**Comment by woodruffw** [comment]
Test block failure:

```
==> /usr/local/Cellar/grafana/4.0.1/bin/grafana-server -v
Version 4.0.1 (commit: unknown-dev)
Error: grafana: failed
execution expired
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/grafana.rb:115:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/grafana.rb:115:in `block (2 levels) in <class:Grafana>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/grafana.rb:113:in `block in <class:Grafana>'
```

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by nijikon** [comment]
You are awesome, thanks for your contribution! :tada:

**Pull request closed without merging**
