### PR TITLE
scala@3.3 3.3.3 (new formula)

### PR DESCRIPTION
**Pull request by hamzaremmal**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [X] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by hamzaremmal** [comment]
Scala 3 has to development branches at the moment Scala 3.lts and Scala 3.next.

More info: https://www.scala-lang.org/blog/2022/08/17/long-term-compatibility-plans.html#our-solution-scala-lts--scala-next

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@hamzaremmal, thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Comment by hamzaremmal** [comment]
> ⛔ It looks like @BrewTestBot cannot push to your PR branch. For future pull requests, please [allow maintainers to edit your PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to simplify the merge process.

@chenrui333 I've just allowed the modification of the PR. The bot should be able to proceed now.

**Comment by chenrui333** [comment]
@hamzaremmal thanks, that is helpful, rerun the merge.

**Pull request merged**
