### PR TITLE
lean 3.49.0

### PR DESCRIPTION
**Pull request by tchajed**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tchajed** [comment]
It looks like mathlib doesn't have a 3.49.0 branch. It actually doesn't seem to be compatible, so I opened https://github.com/leanprover-community/mathlib/issues/17486.

**Comment by chenrui333** [comment]
> It looks like mathlib doesn't have a 3.49.0 branch. It actually doesn't seem to be compatible, so I opened [leanprover-community/mathlib#17486](https://github.com/leanprover-community/mathlib/issues/17486).

yeah, they always released mathlib a couple of days later

**Comment by chenrui333** [comment]
This is my previous issue on the similar matter, https://github.com/leanprover-community/mathlib/issues/14234

**Comment by tchajed** [comment]
This PR should now work, since mathlib created a lean-3.49.0 branch.

**Comment by chenrui333** [comment]
This should be marked `in progress` in the first place 😄

**Comment by chenrui333** [comment]
Gonna do a rerun before the approval/merge

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
