### PR TITLE
duck 7.3.0

### PR DESCRIPTION
**Pull request by dkocher**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
build only failed on highsierra:

```
     [exec] 
     [exec] ProcessInfoPlistFile /private/tmp/duck-20200327-64570-16bn052/cli/osx/target/duck.bundle/Contents/Info.plist /private/tmp/duck-20200327-64570-16bn052/cli/osx/target/Cyberduck.build/Release/cli.build/Preprocessed-Info.plist (in target: cli)
     [exec]     cd /tmp/duck-20200327-64570-16bn052
     [exec]     builtin-infoPlistUtility /private/tmp/duck-20200327-64570-16bn052/cli/osx/target/Cyberduck.build/Release/cli.build/Preprocessed-Info.plist -expandbuildsettings -platform macosx -o /private/tmp/duck-20200327-64570-16bn052/cli/osx/target/duck.bundle/Contents/Info.plist
     [exec] 
     [exec] ** BUILD FAILED **
     [exec] 
     [exec] 
     [exec] The following build commands failed:
     [exec] 	CompileC /private/tmp/duck-20200327-64570-16bn052/cli/osx/target/Cyberduck.build/Release/cli.build/Objects-normal/x86_64/main.o /tmp/duck-20200327-64570-16bn052/cli/osx/src/main/objc/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
     [exec] (1 failure)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Cyberduck 7.3.0:
[INFO] 
[INFO] Cyberduck .......................................... SUCCESS [  6.045 s]
[INFO] core ............................................... SUCCESS [ 28.745 s]
[INFO] binding ............................................ SUCCESS [  3.022 s]
[INFO] profiles ........................................... SUCCESS [  0.158 s]
[INFO] test ............................................... SUCCESS [  2.007 s]
[INFO] importer ........................................... SUCCESS [  0.668 s]
[INFO] libcore ............................................ SUCCESS [ 21.210 s]
[INFO] cryptomator ........................................ SUCCESS [  1.751 s]
[INFO] oauth .............................................. SUCCESS [  4.301 s]
[INFO] udt ................................................ SUCCESS [  1.456 s]
[INFO] irods .............................................. SUCCESS [  2.543 s]
[INFO] webdav ............................................. SUCCESS [ 24.489 s]
[INFO] s3 ................................................. SUCCESS [  6.717 s]
[INFO] spectra ............................................ SUCCESS [  6.801 s]
[INFO] googlestorage ...................................... SUCCESS [  1.785 s]
[INFO] openstack .......................................... SUCCESS [  1.573 s]
[INFO] azure .............................................. SUCCESS [  1.701 s]
[INFO] ssh ................................................ SUCCESS [  7.908 s]
[INFO] ftp ................................................ SUCCESS [  4.063 s]
[INFO] googledrive ........................................ SUCCESS [  1.502 s]
[INFO] backblaze .......................................... SUCCESS [  2.243 s]
[INFO] dropbox ............................................ SUCCESS [  1.218 s]
[INFO] nio ................................................ SUCCESS [  0.438 s]
[INFO] hubic .............................................. SUCCESS [  0.305 s]
[INFO] onedrive ........................................... SUCCESS [  2.256 s]
[INFO] dracoon ............................................ SUCCESS [ 14.649 s]
[INFO] storegate .......................................... SUCCESS [  1.964 s]
[INFO] brick .............................................. SUCCESS [  0.345 s]
[INFO] nextcloud .......................................... SUCCESS [  0.218 s]
[INFO] manta .............................................. SUCCESS [  4.692 s]
[INFO] protocols .......................................... SUCCESS [  0.626 s]
[INFO] cli ................................................ SUCCESS [  5.804 s]
[INFO] cli-osx ............................................ FAILURE [ 23.497 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:08 min
[INFO] Finished at: 2020-03-27T15:16:49Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (run-ant-target) on project cli-osx: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /private/tmp/duck-20200327-64570-16bn052/cli/osx/build.xml:49: exec returned: 65
[ERROR] around Ant part ...<ant antfile="/private/tmp/duck-20200327-64570-16bn052/cli/osx/build.xml" dir="." target="build"/>... @ 9:101 in /private/tmp/duck-20200327-64570-16bn052/cli/osx/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :cli-osx
```

**Comment by dkocher** [comment]
```
     [exec] :10
     [exec] : fatal error: could not build module 'CoreFoundation'
     [exec] #include <CoreFoundation/CoreFoundation.h>
     [exec]  ~~~~~~~~^
     [exec] 1 error generated.
     [exec] While building module 'Foundation' imported from /tmp/duck-20200327-28368-18n3vdu/cli/osx/src/main/objc/launcher.h:20:
     [exec] While building module 'ApplicationServices
     [exec] ' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSAppleEventDescriptor.h:8:
```

**Comment by Bo98** [comment]
Try rebase this and try again. It looks like an SDK issue and I've made some tweaks to SDK selection recently that might fix the issue.

**Comment by dkocher** [comment]
We have rebased. No idea what is going on here.
```
clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-weak -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/7n/ds5ftpq91qzbfp6g9238m38w0000gp/C/org.llvm.clang/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DNS_BLOCK_ASSERTIONS=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.8 -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -iquote /private/tmp/duck-20200405-89925-oakto1/cli/osx/target/Cyberduck.build/Release/cli.build/duck-generated-files.hmap -I/private/tmp/duck-20200405-89925-oakto1/cli/osx/target/Cyberduck.build/Release/cli.build/duck-own-target-headers.hmap -I/private/tmp/duck-20200405-89925-oakto1/cli/osx/target/Cyberduck.build/Release/cli.build/duck-all-target-headers.hmap -iquote /private/tmp/duck-20200405-89925-oakto1/cli/osx/target/Cyberduck.build/Release/cli.build/duck-project-headers.hmap -I/private/tmp/duck-20200405-89925-oakto1/cli/osx/target/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/JavaVM.framework/Headers -I/private/tmp/duck-20200405-89925-oakto1/cli/osx/target/Cyberduck.build/Release/cli.build/DerivedSources/x86_64 -I/private/tmp/duck-20200405-89925-oakto1/cli/osx/target/Cyberduck.build/Release/cli.build/DerivedSources -Wall -Wno-four-char-constants -Wno-unknown-pragmas -F/private/tmp/duck-20200405-89925-oakto1/cli/osx/target -F/tmp/duck-20200405-89925-oakto1/lib -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/JavaVM.framework/Versions/A/Frameworks -MMD -MT dependencies -MF /private/tmp/duck-20200405-89925-oakto1/cli/osx/target/Cyberduck.build/Release/cli.build/Objects-normal/x86_64/main.d --serialize-diagnostics /private/tmp/duck-20200405-89925-oakto1/cli/osx/target/Cyberduck.build/Release/cli.build/Objects-normal/x86_64/main.dia -c /tmp/duck-20200405-89925-oakto1/cli/osx/src/main/objc/main.m -o /private/tmp/duck-20200405-89925-oakto1/cli/osx/target/Cyberduck.build/Release/cli.build/Objects-normal/x86_64/main.o
     [exec] /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2/module.modulemap:1:8: 
     [exec] error: redefinition of module 'libxml2'
     [exec] module libxml2 [system] [extern_c] {
```

**Comment by dkocher** [comment]
@Bo98 Could you have a look. Rebasing did not resolve the issue.

**Comment by jd-a** [comment]
A simple version bump to the more recent version 7.3.1.32784 still fails to build correctly

**Comment by Bo98** [comment]
Can I see the logs of the error you are seeing for 7.3.1? My comment is outdated - a fix for High Sierra SDK landed a few days ago.

**Comment by Bo98** [comment]
#54318

**Pull request closed without merging**
