### PR TITLE
txt2man 1.6.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 is it me or is the test actually dying in a ball of flames?

I'm not sure how this is passing CI.

**Comment by DomT4** [comment]
Yeah, it seems to fail locally:
```
==> /usr/local/Cellar/txt2man/1.6.0/bin/txt2man test.txt
==> /usr/local/Cellar/txt2man/1.6.0/bin/src2man test.c 2>&1
==> /usr/local/Cellar/txt2man/1.6.0/bin/bookman -t Test -o test /usr/local/Cellar/txt2man/1.6.0/share/man/man1/bookman.1 /usr/local/Cellar/txt2man/1.6.0/share/man/man1/src2man.1 /usr/local/Cellar/txt2man/1.6.0/share/man/man1/txt2man.1
/usr/local/Cellar/txt2man/1.6.0/bin/bookman: line 92: [: "/usr/local/Cellar/txt2man/1.6.0/share/man/man1/src2man.1",: binary operator expected
```

Been hanging there for a while.

**Comment by ilovezfs** [comment]
This diff seems to fix it
```
diff --git a/Formula/txt2man.rb b/Formula/txt2man.rb
index 0f6b181..a5343bf 100644
--- a/Formula/txt2man.rb
+++ b/Formula/txt2man.rb
@@ -15,6 +15,12 @@ class Txt2man < Formula
   depends_on "gawk"
 
   def install
+    # --lines is not POSIX
+    inreplace "bookman" do |s|
+      s.gsub! "head --lines=-1", "tail -r | tail +2 | tail -r"
+      s.gsub! "[ $1 ]", "[[ $1 ]]"
+    end
+
     system "make", "install", "prefix=#{prefix}"
   end
 
@@ -42,7 +48,7 @@ class Txt2man < Formula
     assert_match(/\\fBmain\ \\fP\-\ do\ stuff\n/, File.read("main.3").lines.to_a[4])
 
     # bookman
-    system "#{bin}/bookman", "-t", "Test", "-o", "test", Dir["#{man1}/*"]
+    system "#{bin}/bookman", "-t", "Test", "-o", "test", *Dir["#{man1}/*"]
     assert File.exist?("test")
   end
 end
```
though I still get a warning
```
<standard input>:7: warning: numeric expression expected (got `i')
```

How is this passing CI? LOL

**Comment by ilovezfs** [comment]
Lovely: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6470/version=el_capitan/testReport/brew-test-bot/el_capitan/test_txt2man/

**Comment by DomT4** [comment]
Does this impact the current version? Otherwise I'm wondering if it's best to just report this upstream & sit on it until we get some portability we can backport.

**Comment by ilovezfs** [comment]
I'll check. More generally, I'd like to understand how
```
        Testing txt2man
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160818-86929-1duxayu.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/txt2man.rb --verbose
==> /usr/local/Cellar/txt2man/1.6.0/bin/txt2man test.txt
==> /usr/local/Cellar/txt2man/1.6.0/bin/src2man test.c 2>&1
==> /usr/local/Cellar/txt2man/1.6.0/bin/bookman -t Test -o test /usr/local/Cellar/txt2man/1.6.0/share/man/man1/bookman.1 /usr/local/Cellar/txt2man/1.6.0/share/man/man1/src2man.1 /usr/local/Cellar/txt2man/1.6.0/share/man/man1/txt2man.1
/usr/local/Cellar/txt2man/1.6.0/bin/bookman: line 92: [: "/usr/local/Cellar/txt2man/1.6.0/share/man/man1/src2man.1",: binary operator expected
head: illegal option -- -
usage: head [-n lines | -c bytes] [file ...]
<standard input>:7: warning: numeric expression expected (got `i')
```
is passing CI so that we know this isn't happening in other formulae. That's pretty concerning since it means we need to manually check test-bot `test --verbose` output for everything if it cannot be trusted.

**Comment by ilovezfs** [comment]
Um, looks like it impacts current version too...
```
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160820-7402-b6owg9.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/txt2man.rb -vd
/usr/local/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/txt2man.rb
==> /usr/local/Cellar/txt2man/1.5.6/bin/txt2man test.txt
==> /usr/local/Cellar/txt2man/1.5.6/bin/src2man test.c 2>&1
==> /usr/local/Cellar/txt2man/1.5.6/bin/bookman -t Test -o test /usr/local/Cellar/txt2man/1.5.6/share/man/man1/bookman.1 /usr/local/Cellar/txt2man/1.5.6/share/man/man1/src2man.1 /usr/local/Cellar/txt2man/1.5.6/share/man/man1/txt2man.1
head: illegal option -- -
usage: head [-n lines | -c bytes] [file ...]
cat: ["/usr/local/Cellar/txt2man/1.5.6/share/man/man1/bookman.1",: No such file or directory
cat: "/usr/local/Cellar/txt2man/1.5.6/share/man/man1/src2man.1",: No such file or directory
cat: "/usr/local/Cellar/txt2man/1.5.6/share/man/man1/txt2man.1"]: No such file or directory
<standard input>:7: warning: numeric expression expected (got `i')
cat: ["/usr/local/Cellar/txt2man/1.5.6/share/man/man1/bookman.1",: No such file or directory
cat: "/usr/local/Cellar/txt2man/1.5.6/share/man/man1/src2man.1",: No such file or directory
cat: "/usr/local/Cellar/txt2man/1.5.6/share/man/man1/txt2man.1"]: No such file or directory
```
Something tells me know one is using this. :skull: time?

**Comment by DomT4** [comment]
20 "known" downloads total, used by one formula (`rfcdiff`), FWIW.

**Comment by ilovezfs** [comment]
oy:
```
==> make -f Makefile.common tool=rfcdiff sources=rfcdiff.pyht prefix=/usr/local/Cellar/rfcdiff/1.45 install
head: illegal line count -- -1
/usr/bin/sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
/usr/bin/sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
./rfcdiff --help | txt2man -t "rfcdiff 1" > rfcdiff.1
gzip -f rfcdiff.1 -c > rfcdiff.1.gz
install rfcdiff /usr/local/Cellar/rfcdiff/1.45/bin
install -m 644 rfcdiff.1.gz /usr/local/Cellar/rfcdiff/1.45/share/man/man1/
rm rfcdiff.1
```
lol

**Comment by ilovezfs** [comment]
Did I mention the install completed?
```
==> Summary
🍺  /usr/local/Cellar/rfcdiff/1.45: 6 files, 51.5K, built in 0 seconds
```
sigh

**Comment by DomT4** [comment]
Don't know whether to 😆 or 😢. Apparently this software never throws a failure, despite repeated obvious failures.

Kind of tempting to boneyard `rfcdiff`, `txt2man` & `idcomments`.

**Comment by ilovezfs** [comment]
might be worth putting env script wrappers around them pointing to gnubin and call it a day

**Comment by DomT4** [comment]
Analytics would seem to indicate it's not a valuable use of time/effort, but entirely up to you.

**Comment by ilovezfs** [comment]
@DomT4 It's already done. This PR is refreshed. And: https://github.com/Homebrew/homebrew-core/pull/4075

**Comment by ilovezfs** [comment]
@DomT4 may make sense to boneyard anyway since I'm not sure we want a gnubin env script wrapper precedent, but at least they work.

**Comment by DomT4** [comment]
My gut feeling is that unless upstream shows any movement towards supporting the BSD utils it isn't cross-platform in terms of OS X, and nobody has noticed/reported this problem to us before we stumbled across it, so probably a good 💀 candidate. But if you're happy to work on this, by all means, feel free.

**Comment by ilovezfs** [comment]
I think it should get merged to master in working condition, and then boneyarded to avoid setting a precedent.

**Comment by ilovezfs** [comment]
Or we can just boneyard it as-is. I really don't care either way, but I think the precedent is bad.

**Comment by DomT4** [comment]
If you're happy to kill it, I'd probably kill it here, and presumably `rfcdiff` + `idcomments` unless `rfcdiff` is happy to build without this around.

**Comment by ilovezfs** [comment]
kill it here meaning with or without the PRs merged first?

**Comment by DomT4** [comment]
I probably wouldn't merge the PRs, to avoid doing the confusing thing of merging a fix & then immediately rejecting the fix we just  merged.

**Comment by ilovezfs** [comment]
okie dokie

**Pull request closed without merging**
