### PR TITLE
perl 5.38.0

### PR DESCRIPTION
**Pull request by briandfoy**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
Please squash your commits into one with the message `perl 5.38.0`. Thanks.

**Comment by SMillerDev** [comment]
Dropped the merge commit that didn't need to be there.

**Comment by briandfoy** [comment]
It looks like the failed tests are all the deps checks. Several formula depend on the old perl@36.

What's the process when this happens? Do those need to be modified by hand or is there another automated step that should recompile them?

**Comment by p-linnane** [comment]
> It looks like the failed tests are all the deps checks. Several formula depend on the old perl@36.
> 
> What's the process when this happens? Do those need to be modified by hand or is there another automated step that should recompile them?

We need to do revision bumps for the affected formulae, so that they rebuild against the newest `perl`. I've pushed those there.

**Review by p-linnane — APPROVED** [review]
Thanks for your first contribution @briandfoy!

**Review by ZhongRuoyu — APPROVED** [review]
Thanks @briandfoy and @p-linnane!

**Comment by briandfoy** [comment]
Looking at the failures in the one failing check:

* mnoarch tries to download `https://www.mhonarc.org/release/MHonArc/tar/MHonArc-2.6.19.tar.bz2%60` but gets a 404. Remove the `%60` and it's found. I don't know why that extra character is there in just one architecture.
* asciiaquarium fails it's test because it expects to have four characters that it grabs and gets three (or something unprintable maybe). I've tried this program fro 2015 (with no updates since then) on Perl v5.38 without problem. But, the asciiquarium.rb is a couple years out of date on the versions of the Perl modules this program needs.

**Comment by aferreira** [comment]
For reference: https://github.com/Homebrew/homebrew-core/pull/135640 was a previous attempt to upgrade perl to 5.38.0

**Comment by chenrui333** [comment]
Only on `13`
```
brew install --verbose --build-bottle bioperl
brew test --verbose asciiquarium
brew fetch --retry mhonarc --build-bottle --force
brew install --verbose --build-bottle mhonarc
```

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @briandfoy and @p-linnane! 🚢

**Comment by chenrui333** [comment]
actually there are couple of conflicts

**Comment by p-linnane** [comment]
Two formulae had Sonoma bottles pushed to them while this PR was running. I've fixed the conflicts and rebased this.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
