### PR TITLE
gnuradio: add GR_SOAPY as an installed core package

### PR DESCRIPTION
**Pull request by NeuroForLunch**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks, @NeuroForLunch. Can you amend your commit to follow the commit style guide, as requested in the PR template? We put the name of the formula first in our commit messages.

**Comment by argilo** [comment]
You'll also need to add `soapysdr` as a dependency, since the gr-soapy package depends on it. And the revision number should be incremented to 2.

I made these changes here before noticing that there was already an open pull request for gr-soapy: https://github.com/argilo/homebrew-core/commit/37854dbd8c437589ebc166595e251d6e705d7bde

**Comment by carlocab** [comment]
Looks like we'll need a `soapysdr` formula then, as there currently isn't one.

**Comment by argilo** [comment]
To add some context, the gnuradio formula was updated to 3.9.2.0 in #79118. This release added the new "gr-soapy" module, which adds support for the SoapySDR framework: https://github.com/gnuradio/gnuradio/releases/tag/v3.9.2.0

**Comment by argilo** [comment]
> Looks like we'll need a soapysdr formula then

The formula is here: https://github.com/pothosware/homebrew-pothos

But I'm guessing the gnuradio formula can't depend on it since it's outside homebrew-core?

**Comment by carlocab** [comment]
> But I'm guessing the gnuradio formula can't depend on it yet since it's outside homebrew-core?

This is correct.

**Comment by NeuroForLunch** [comment]
> Thanks, @NeuroForLunch. Can you amend your commit to follow the commit style guide, as requested in the PR template? We put the name of the formula first in our commit messages.

Sorry about that. I made the same mistake on the 2 new formulas I just submitted. There's just so many files in the homebrew-core repo that I was updating it on github and not locally as my system would freeze up.

**Comment by carlocab** [comment]
Updating the Python resources as well since we're already making changes to the formula.

**Comment by NeuroForLunch** [comment]
GNU radio is so finicky that maybe it should be left with the dependencies that worked before?

**Comment by carlocab** [comment]
Ah, no, that was my mistake from the update I pushed. Let me fix it.

**Comment by NeuroForLunch** [comment]
Nice work ✅

**Review by carlocab — APPROVED** [review]
Thanks again for your contributions, @NeuroForLunch.

**Comment by NeuroForLunch** [comment]
@carlocab, how can we make an arm bottle? I didn't realize one of the passing tests didn't make an arm bottle.

Warning: gnuradio has not yet been bottled on ARM!
==> SKIPPED gnuradio

**Comment by carlocab** [comment]
Does gnuradio work on ARM? My understanding is that it doesn't, but this information may be outdated by a version or two.

**Comment by carlocab** [comment]
gnuradio doesn't work on ARM. It depends on `volk`, but `volk` doesn't work on ARM yet AFAIK.

**Pull request closed without merging**
