### PR TITLE
up 0.5.5 (new formula)

### PR DESCRIPTION
**Pull request by jacobwgillespie**
Add new formula for Apex Up (https://up.docs.apex.sh/).

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Hmm...  looks like this is failing due to the use of `go_resource` and `go get` for build tools.  Is there a recommended way to work around this?  I'm trying to follow existing patterns like the `consul` formula, and I am fairly sure that vendoring is not the correct answer here like the linter is suggesting, since these are build tools and not dependencies.

**Comment by ilovezfs** [comment]
https://github.com/jteeuwen/go-bindata is not something a new formula should be using because its upstream is gone.

**Comment by jacobwgillespie** [comment]
@ilovezfs what's the recommended alternative, given that it's used in the up repo to build itself?  I know [other formulas](https://github.com/Homebrew/homebrew-core/blob/3eac46376541251dfd439a330a9b642a5ad72722/Formula/consul.rb#L33-L36) are using it, although in that case it's the Hashicorp fork.

**Comment by ilovezfs** [comment]
@jacobwgillespie at bare minimum upstream should have their own forked repo for it like consul did in https://github.com/hashicorp/consul/issues/3868. Alternatively, they could switch to a similar tool with an upstream that actually exists.

**Comment by ilovezfs** [comment]
It looks like some people are having success switching to Kevin Burke's fork. See

https://github.com/Dr-Terrible/go-overlay/issues/76#issuecomment-360482724
https://github.com/kevinburke/go-bindata

**Comment by ilovezfs** [comment]
Actually, I'm going to make a formula for that fork and suggest the other projects adopt it.

**Comment by ilovezfs** [comment]
You can use `depends_on "go-bindata" => :build` now. See https://github.com/Homebrew/homebrew-core/pull/24801

**Comment by ilovezfs** [comment]
I've opened
https://github.com/containous/traefik/issues/2965
https://github.com/hashicorp/consul/issues/3930

**Comment by jacobwgillespie** [comment]
Awesome, thank you, I have updated this to use `go-bindata` directly.

**Comment by commitay** [comment]
https://docs.brew.sh/Acceptable-Formulae
> We don’t like tools that upgrade themselves
> Software that can upgrade itself does not integrate well with Homebrew’s own upgrade functionality.

https://github.com/apex/up/blob/master/internal/cli/upgrade/upgrade.go

**Pull request closed without merging**
