### PR TITLE
terraform 0.9.8

### PR DESCRIPTION
**Pull request by cblecker**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cblecker** [comment]
CI didn't trigger :(

**Comment by cblecker** [comment]
Oh, there it goes

**Comment by Techcadia** [comment]
Would like to see this merged since it fixes a few bugs in TF

**Comment by cblecker** [comment]
@Techcadia The Homebrew maintainers are very good at merging these in a timely manner. It's only been 6 hours since release :)

**Comment by cblecker** [comment]
Updating PR for v0.9.8, as v0.9.7 had a bug:
https://github.com/hashicorp/terraform/blob/v0.9.8/CHANGELOG.md

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
@cblecker thanks for the upgrade! :motor_boat:

**Pull request closed without merging**
