### PR TITLE
pdns 4.4.1

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
CC @fxcoudert, it's `bigsur-arm-6` again.

**Review by carlocab — DISMISSED** [review]

**Comment by chenrui333** [comment]
@carlocab after another look at this PR, I think it is good for the merge. The first downloadable party does have the distributed artifact (and it is just matter of announcement though). What do you think?

**Review by carlocab — APPROVED** [review]
_Now_, it's announced as released. Just today, in fact.

**Comment by chenrui333** [comment]
I see, good timing ;)

**Pull request closed without merging**
