### PR TITLE
mysql@5.5 5.5.56

### PR DESCRIPTION
**Pull request by neutric**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by neutric** [comment]
The default for the _WITH_SSL_ CMake option changed from `no`, which is no longer permitted, to `bundled` (=use the SSL library bundled with the distribution), see [release notes](https://dev.mysql.com/doc/relnotes/mysql/5.5/en/news-5-5-56.html).

Right now we choose `-DWITH_SSL=yes` (=use the system SSL library if present, else the library bundled with the distribution.) and then overwrite that choice with `-DWITH_SSL=system`. Should this be changed to match the upstream default? If not, which one do we keep?

/CC @DomT4

**Comment by DomT4** [comment]
>  If not, which one do we keep?

We want to use Homebrew's OpenSSL, essentially. Bundled crypto libraries are a nightmare when a vulnerability later comes along 😓.

**Comment by neutric** [comment]
Thanks for your speedy reply! Do we get that one with `-DWITH_SSL=system`?

**Comment by ilovezfs** [comment]
Aren't we using bundled crypto with node?

**Comment by DomT4** [comment]
> Thanks for your speedy reply! Do we get that one with -DWITH_SSL=system?

No worries! I try to keep on top of direct pings 😄. Yes, I think the argument we'd want to retain is `Do we get that one with -DWITH_SSL=system?` here if the new default is always-on.

> Aren't we using bundled crypto with node?

Yes. I don't love it, but `node` at least rush releases for crypto/ssl/tls vulnerabilities, which, er, `mysql` does not have such an ideal record on.

Part of the reason here is that upstream disable SSLv2 & SSLv3 in their OpenSSL, and Homebrew has only managed to do SSLv2 so far.

**Comment by neutric** [comment]
@DomT4 Thanks for the feedback! 🍌 🍺

**Pull request closed without merging**
