### PR TITLE
wpscan: delete

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
regarding this formula, the creator wrote a blog post regarding the license.
https://blog.dewhurstsecurity.com/2015/01/21/wpscan-licensing.html

**Comment by SMillerDev** [comment]
@Homebrew/plc this seems like a mongodb type situation. Opinions?

**Comment by jonchang** [comment]
Yeah, it looks like it switched from the MySQL licensing model to the mongodb licensing model. We shouldn't update the formula to any versions released under the new license.

**Comment by jonchang** [comment]
Hmm, looks like the last version that was licensed under the GPL was version 2.6:

https://github.com/wpscanteam/wpscan/tree/2.6

https://github.com/wpscanteam/wpscan/compare/2.6...2.7#diff-9879d6db96fd29134fc802214163b95a

We probably need to revert wpscan to v2.6 if we are to continue shipping it in homebrew/core. I guess the question at this point is whether it's worth shipping something so outdated or if we should just remove it from Homebrew/core entirely.

**Comment by gromgit** [comment]
IMO, stepping back from 3.8.6 to 2.6 is far too big a move. Since third party taps are easy to set up, I think it's best to disable it entirely, and let someone from the community carry the `wpscan` flag going forward.

**Comment by sjackman** [comment]
Remove `wpscan` because it's not DFSG.

Reference https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

**Comment by SMillerDev** [comment]
@chenrui333 please remove the formula

**Review by SMillerDev — APPROVED** [review]

**Comment by jonchang** [comment]
The PLC voted 3-0 to remove this formula. Thanks for the input @gromgit @chenrui333

**Comment by chenrui333** [comment]
Sorry to hear about that, I will create an issue to let them know about this decision.

**Comment by chenrui333** [comment]
@jonchang @SMillerDev is there anyway that I can find the old installation data for this formula?

**Comment by Bo98** [comment]
Stats are still on formulae.brew.sh. ~2000 in the last 30 days, ~4000 in the last 90. That doesn't really matter though when it's a license issue.

Just like MongoDB, upstream aren't going to suddenly change their license to return to Homebrew. And that's fine. It's a trade-off I imagine they're happy with. wpscan doesn't exist in many package managers anymore just like the latest MongoDB version doesn't.

**Comment by ethicalhack3r** [comment]
Ryan here from WPScan. Just seeing this now.

Aside from changing to an Open Source license, if there's anything we can do to change this decision please let me know.

**Comment by SMillerDev** [comment]
No, all software in homebrew core must be using an open source license. We use the Debian standard for this: https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

You can consider hosting it in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by ethicalhack3r** [comment]
Thank you for information.

**Pull request merged**
