### PR TITLE
mysql mysql 8.4.2

### PR DESCRIPTION
**Pull request by yahonda**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by yahonda** [comment]
This pull request has been opened based on the comment https://github.com/Homebrew/homebrew-core/pull/170446#issuecomment-2217488592

**Comment by yahonda** [comment]
There is a build failure.
https://github.com/Homebrew/homebrew-core/actions/runs/9860163114/job/27225771791?pr=176823#step:3:5990

```
  /tmp/mysql-20240709-28457-vh5dsv/mysql-8.4.1/storage/ndb/plugin/ndb_binlog_purger.cc:79:20: error: no member named 'any_of' in namespace 'std::ranges'
    if (std::ranges::any_of(m_purge_files, [filename](const auto &request) {
        ~~~~~~~~~~~~~^
  /tmp/mysql-20240709-28457-vh5dsv/mysql-8.4.1/storage/ndb/plugin/ndb_binlog_purger.cc:98:25: error: no member named 'none_of' in namespace 'std::ranges'
             std::ranges::none_of(m_purge_files, [session](const auto &request) {
             ~~~~~~~~~~~~~^
```

**Comment by SMillerDev** [comment]
That looks to be unsupported in the CLang version on macOS 12. I guess you'll need to make older macOS versions depend on LLVM from Homebrew.

**Comment by yahonda** [comment]
Addressed the RuboCop offense below.

https://github.com/Homebrew/homebrew-core/actions/runs/9874031780/job/27267599481?pr=176823#step:5:24
```
  Taps/homebrew/homebrew-core/Formula/m/mysql.rb:54:3: C: [Correctable] FormulaAudit/ComponentsOrder: conflicts_with (line 54) should be put before fails_with (line 49)
    conflicts_with "mariadb", "percona-server", ...
```

**Comment by SMillerDev** [comment]
```
  Undefined symbols for architecture x86_64:
    "std::exception_ptr::__from_native_exception_pointer(void*)", referenced from:
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::runtime_error>(std::runtime_error) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::invalid_argument>(std::invalid_argument) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<mysql_harness::syntax_error>(mysql_harness::syntax_error) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::__1::future_error>(std::__1::future_error) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::__1::system_error>(std::__1::system_error) in handler.cc.o
    "___cxa_init_primary_exception", referenced from:
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::runtime_error>(std::runtime_error) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::invalid_argument>(std::invalid_argument) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<mysql_harness::syntax_error>(mysql_harness::syntax_error) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::__1::future_error>(std::__1::future_error) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::__1::system_error>(std::__1::system_error) in handler.cc.o
  ld: symbol(s) not found for architecture x86_64
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  make[2]: *** [library_output_directory/libmysqlharness.1.dylib] Error 1
  make[1]: *** [router/src/harness/src/CMakeFiles/harness-library.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
```

**Comment by yahonda** [comment]
No release notes available yet, MySQL Community Server 8.4.2 LTS is available https://dev.mysql.com/downloads/mysql/8.4.html

**Comment by yahonda** [comment]
`Undefined symbols for architecture arm64` also happens.

https://github.com/Homebrew/homebrew-core/actions/runs/10053517699/job/27786491301?pr=176823#step:3:2736

```
  Undefined symbols for architecture arm64:
    "std::exception_ptr::__from_native_exception_pointer(void*)", referenced from:
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::runtime_error>(std::runtime_error) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::invalid_argument>(std::invalid_argument) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<mysql_harness::syntax_error>(mysql_harness::syntax_error) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::__1::future_error>(std::__1::future_error) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::__1::system_error>(std::__1::system_error) in handler.cc.o
    "___cxa_init_primary_exception", referenced from:
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::runtime_error>(std::runtime_error) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::invalid_argument>(std::invalid_argument) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<mysql_harness::syntax_error>(mysql_harness::syntax_error) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::__1::future_error>(std::__1::future_error) in loader.cc.o
        std::exception_ptr std::make_exception_ptr[abi:ne180100]<std::__1::system_error>(std::__1::system_error) in handler.cc.o
  ld: symbol(s) not found for architecture arm64
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
 ```

**Comment by yahonda** [comment]
Thanks for the information. However, I'm not confident if MySQl 8.4 does not support macOS 12 anymore because the latest EOL for macOS information is macOS v10.15 aka macOS Catalina.

"MySQL Product Support EOL Announcements"
https://www.mysql.com/support/eol-notice.html

> Support EOL for macOS v10.15
> Due to very low demand, MySQL has stopped development and support for macOS 10.15. MySQL 8.0 is the only supported version on macOS. Users of MySQL 5.7 are encouraged to upgrade to MySQL 8.0. Source and binaries for previously released versions will continue to be available from the archives.

**Comment by yahonda** [comment]
Closing this pull request as https://github.com/Homebrew/homebrew-core/pull/179792 has been merged.

**Pull request closed without merging**
