### PR TITLE
go 1.16.5

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by branchvincent** [comment]
Big Sur ARM

<details>
  <summary>Error: 50 failed steps!</summary>
  
```
brew test --retry --verbose akamai
brew test --retry --verbose awsweeper
brew install --build-from-source cacli
brew install --build-from-source cf-tool
brew install --build-from-source circleci
brew install --build-from-source --only-dependencies clair
brew install --build-from-source clair
brew install --build-from-source consul
brew test --retry --verbose cql
brew test --retry --verbose darksky-weather
brew test --retry --verbose darksky-weather
brew install --build-from-source --only-dependencies docker-machine-driver-hyperkit
brew install --build-from-source docker-machine-driver-hyperkit
brew install --build-from-source --only-dependencies dockviz
brew install --build-from-source dockviz
brew install --build-from-source drone-cli
brew install --build-from-source dvm
brew install --only-dependencies --include-test envconsul
brew test --retry --verbose envconsul
brew install --build-from-source envoy
brew install --build-from-source --only-dependencies fabio
brew install --build-from-source fabio
brew install --build-from-source --only-dependencies geoipupdate
brew install --build-from-source geoipupdate
brew install --build-from-source --only-dependencies git-annex-remote-rclone
brew install --build-from-source git-annex-remote-rclone
brew install --build-from-source gotop
brew install --build-from-source --only-dependencies ironcli
brew install --build-from-source ironcli
brew test --retry --verbose jabba
brew install --build-from-source kube-linter
brew install --build-from-source linkerd
brew install --build-from-source mpdviz
brew test --retry --verbose packr
brew test --retry --verbose packr
brew install --build-from-source peco
brew install --build-from-source pilosa
brew test --retry --verbose server-go
brew install --build-from-source source-to-image
brew install --only-dependencies --include-test stolon
brew test --retry --verbose stolon
brew install --build-from-source td
brew install --build-from-source telegraf
brew install --build-from-source teleport
brew test --retry --verbose terrascan
brew test --retry --verbose terrascan
brew install --build-from-source --only-dependencies vert
brew install --build-from-source vert
brew install --build-from-source virgil
brew test --retry --verbose vitess
```
</details>

Mojave

```
Error: 12 failed steps!
brew install --build-from-source cacli
brew test --retry --verbose fn
brew test --retry --verbose jabba
brew install --build-from-source linkerd
brew test --retry --verbose packr
brew test --retry --verbose packr
brew install --build-from-source peco
brew install --build-from-source td
brew install --build-from-source telegraf
brew install --build-from-source teleport
brew test --retry --verbose terrascan
brew test --retry --verbose terrascan
```

**Comment by AlekSi** [comment]
The same story happened the last time: https://github.com/Homebrew/homebrew-core/pull/76791

**Comment by andig** [comment]
Last time we went for merging nonetheless. Can we do the same now?

**Comment by SMillerDev** [comment]
Last time someone checked if any of the builds were impacted by the merge. If someone does that for this update and nothing is found we can merge.

**Comment by andig** [comment]
> Last time someone checked if any of the builds were impacted by the merge. If someone does that for this update and nothing is found we can merge.

I would like to contribute and have enough go experience. I'm still unsure though how to operate brew for testing locally and coming up with the right insights/conclusion. E.g. how would I get 1.16.5 installed locally (through brew so its actually used) and then use that to execute the failing tests?

**Comment by andig** [comment]
>  I'm still unsure though how to operate brew for testing locally and coming up with the right insights/conclusion. E.g. how would I get 1.16.5 installed locally (through brew so its actually used) and then use that to execute the failing tests?

I'd really like to help but don't know where to start.

**Comment by SMillerDev** [comment]
> I'd really like to help but don't know where to start.

You can run the failing commands printed at the "Output brew test-bot --only-json-tab --only-formulae failures" step in CI with the current go version to see if they fail there.

**Comment by bayandin** [comment]
It looks like problems with go.sum caused by this `go` release (see https://github.com/golang/go/issues/46214 and https://github.com/golang/go/issues/45332#issuecomment-811936317).
- For `packr` test we could try to add `go mod tidy` after `go mod download`. 
- For `peco` we need to raise an upstream issue for adding `go mod tidy` to [`go mod download` ](https://github.com/peco/peco/blob/v0.5.8/Makefile#L37-L39) or alternatively ask to add `go.sum` to the repo

**Comment by andig** [comment]
> For packr test we could try to add go mod tidy after go mod download.

Should be added upstream then?

**Comment by andig** [comment]
> > I'd really like to help but don't know where to start.
> 
> You can run the failing commands printed at the "Output brew test-bot --only-json-tab --only-formulae failures" step in CI with the current go version to see if they fail there.

Don't I need to install the brewed version of 1.16.5 first? How? Sorry if the questions sound dumb but I'm totally failing to understand how "testing a non-released formula in conjunction with others formulas" works.

**Comment by bayandin** [comment]
> > For packr test we could try to add go mod tidy after go mod download.
> 
> Should be added upstream then?

Nope, Homebrews test is the only thing that fails for `packr`, so we need to update / fix the test in the formula only



> > > I'd really like to help but don't know where to start.
> > 
> > 
> > You can run the failing commands printed at the "Output brew test-bot --only-json-tab --only-formulae failures" step in CI with the current go version to see if they fail there.
> 
> Don't I need to install the brewed version of 1.16.5 first? How? Sorry if the questions sound dumb but I'm totally failing to understand how "testing a non-released formula in conjunction with others formulas" works.

You do need it. To make it you can either apply changes from this PR to your go formula (`brew edit go`) and then upgrade it via `brew upgrade --build-from-source go` command, or you can checkout exactly this branch  by `brew --repo homebrew/homebrew-core && gh pr checkout 78666` (`gh` is a tool that you'll need to install)  and upgrade `go`.

**Comment by andig** [comment]
/cc @jlk could you kindly check the `terrascan` errors:

```
❯ brew test --retry --verbose terrascan
==> Testing terrascan
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210607-95925-19gz715.sb ruby -W1 -- /opt/homebrew/Library/Homebrew/test.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/terrascan.rb --verbose --retry
==> /opt/homebrew/Cellar/terrascan/1.6.0/bin/terrascan scan -f /private/tmp/terrascan-test-20210607-95926-1jcdwut/ami.tf -t aws
==> Testing terrascan (again)
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210607-95944-78dfhh.sb ruby -W1 -- /opt/homebrew/Library/Homebrew/test.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/terrascan.rb --verbose --retry
==> /opt/homebrew/Cellar/terrascan/1.6.0/bin/terrascan scan -f /private/tmp/terrascan-test-20210607-95945-1tzt5jq/ami.tf -t aws
Error: terrascan: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected /\tPolicies\ Validated\ \ :\t203\n\tViolated\ Policies\ \ \ :\t0\n\tLow\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\t0\n\tMedium\ \ \ \ \ \ \ \ \ \ \ \ \ \ :\t0\n\tHigh\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\t0\n/ to match "\n\nScan Summary -\n\n\tFile/Folder         :\t/private/tmp/terrascan-test-20210607-95945-1tzt5jq/ami.tf\n\tIaC Type            :\tterraform\n\tScanned At          :\t2021-06-07 11:20:50.52527 +0000 UTC\n\tPolicies Validated  :\t208\n\tViolated Policies   :\t0\n\tLow                 :\t0\n\tMedium              :\t0\n\tHigh                :\t0\n\t\n\n".
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.14.4/lib/minitest/assertions.rb:183:in `assert'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.14.4/lib/minitest/assertions.rb:295:in `assert_match'
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/terrascan.rb:45:in `block in <class:Terrascan>'
/opt/homebrew/Library/Homebrew/formula.rb:1973:in `block (3 levels) in run_test'
/opt/homebrew/Library/Homebrew/utils.rb:571:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:1972:in `block (2 levels) in run_test'
/opt/homebrew/Library/Homebrew/formula.rb:924:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:1971:in `block in run_test'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/opt/homebrew/Library/Homebrew/formula.rb:2224:in `mktemp'
/opt/homebrew/Library/Homebrew/formula.rb:1965:in `run_test'
/opt/homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Library/Homebrew/test.rb:48:in `<main>'
```

**Comment by SMillerDev** [comment]
> You do need it. To make it you can either apply changes from this PR to your go formula (brew edit go) and then upgrade it via brew upgrade --build-from-source go command, or you can checkout exactly this branch by brew --repo homebrew/homebrew-core && gh pr checkout 78666 (gh is a tool that you'll need to install) and upgrade go.

Since CI tests against 1.16.5, running the same tests against 1.16.4 should be enough to determine if this is caused by the update right?

> /cc jlk could you kindly check the terrascan errors:

That's not really the way to solve this. You should run the test blocks, check what they do and try and figure out if the cause can be traced back to Go or an issue with the test.

**Comment by andig** [comment]
> > /cc jlk could you kindly check the terrascan errors:
> 
> That's not really the way to solve this. You should run the test blocks, check what they do and try and figure out if the cause can be traced back to Go or an issue with the test.

Understood. The errors are inside the ruby script. I cannot determine the root cause and jlk already replied on go 1.16.4.

**Comment by andig** [comment]
How would one solve the checksum errors (manual PR?):

```
❯ brew bump-formula-pr --sha256 18131af75eea19d0fa7ac3c0c97d9cf941a4e77acf233be6324b208833d02cea --url https://github.com/influxdata/telegraf/archive/v1.18.3.tar.gz telegraf
Error: These pull requests may be duplicates:
telegraf 1.18.3 https://github.com/Homebrew/homebrew-core/pull/77727
Duplicate PRs should not be opened. Use --force to override this error.
```

i.e., how do we determine if the checksum should be updated? Is it worth checking this or should we assume, that the currently available upstream SHA is correct and just apply it? At any rate it is the artefact currently publicly available for download.

**Comment by SMillerDev** [comment]
> Understood. The errors are inside the ruby script. I cannot determine the root cause.

```console
  Minitest::Assertion: Expected /\tPolicies\ Validated\ \ :\t203\n\tViolated\ Policies\ \ \ :\t0\n\tLow\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\t0\n\tMedium\ \ \ \ \ \ \ \ \ \ \ \ \ \ :\t0\n\tHigh\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\t0\n/ to match "\n\nScan Summary -\n\n\tFile/Folder         :\t/private/tmp/terrascan-test-20210607-95945-1tzt5jq/ami.tf\n\tIaC Type            :\tterraform\n\tScanned At          :\t2021-06-07 11:20:50.52527 +0000 UTC\n\tPolicies Validated  :\t208\n\tViolated Policies   :\t0\n\tLow                 :\t0\n\tMedium              :\t0\n\tHigh                :\t0\n\t\n\n".
```

`Minitest::Assertion: Expected (string) to match (other string)` so the formula has issues in the `assert_match` statement in the test.

You'll need to check the output of the failing command outside of the test block and see if the test is expecting the wrong thing, or that the output is broken.

---

> how do we determine if the checksum should be updated?

We ask upstream if they retagged their release and/or if the file change is intentional. We err on the side of caution here because it would be very bad if we shipped compromised software.

**Comment by andig** [comment]
> > Understood. The errors are inside the ruby script. I cannot determine the root cause.
> 
> ```
>   Minitest::Assertion: Expected /\tPolicies\ Validated\ \ :\t203\n\tViolated\ Policies\ \ \ :\t0\n\tLow\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\t0\n\tMedium\ \ \ \ \ \ \ \ \ \ \ \ \ \ :\t0\n\tHigh\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ :\t0\n/ to match "\n\nScan Summary -\n\n\tFile/Folder         :\t/private/tmp/terrascan-test-20210607-95945-1tzt5jq/ami.tf\n\tIaC Type            :\tterraform\n\tScanned At          :\t2021-06-07 11:20:50.52527 +0000 UTC\n\tPolicies Validated  :\t208\n\tViolated Policies   :\t0\n\tLow                 :\t0\n\tMedium              :\t0\n\tHigh                :\t0\n\t\n\n".
> ```
> 
> `Minitest::Assertion: Expected (string) to match (other string)` so the formula has issues in the `assert_match` statement in the test.
> 
> You'll need to check the output of the failing command outside of the test block and see if the test is expecting the wrong thing, or that the output is broken.

terrascan: Seems output now contains timestamp (`Scanned At`) which would need to be ignored in the test- would need a Ruby fix in the testcase

**Comment by andig** [comment]
https://github.com/Homebrew/homebrew-core/pull/78879 should solve td

**Comment by andig** [comment]
Linkerd confirmed SHA change in https://github.com/linkerd/linkerd2/issues/6233#issuecomment-856228237

**Comment by branchvincent** [comment]
Remaining non-ARM failures:
- [ ] `dgraph` test failure
- [ ] `influxdb` test failure
- [ ] `cacli` checksum
- [ ] `fn` test failure
- [ ] `jabba` test failure
- [ ] `linkerd` git sha #78894
- [ ] `peco` needs `go mod tidy` https://github.com/peco/peco/issues/525
- [ ] `telegraf` checksum https://github.com/influxdata/telegraf/issues/9334
- [ ] `teleport` checksum
- [ ] `terrascan` needs test update

**Comment by cho-m** [comment]
> * For `peco` we need to raise an upstream issue for adding `go mod tidy` to [`go mod download` ](https://github.com/peco/peco/blob/v0.5.8/Makefile#L37-L39) **or alternatively ask to add `go.sum` to the repo**

`peco` did add `go.sum` in recent commit https://github.com/peco/peco/commit/ea18d1890f82838fde558c0200c4da81c1ae7a94

**Comment by nandahkrishna** [comment]
I opened #79070 to deprecate `dgraph`, as they dropped support for macOS.

**Comment by carlocab** [comment]
> Remaining non-ARM failures:
> 
> - [x] `dgraph` test failure
> 
> - [ ] `influxdb` test failure
> 
> - [ ] `cacli` checksum
> 
> - [ ] `fn` test failure
> 
> - [ ] `jabba` test failure
> 
> - [x] `linkerd` git sha #78894
> 
> - [x] `peco` needs `go mod tidy` https://github.com/peco/peco/issues/525
> 
> - [ ] `telegraf` checksum https://github.com/influxdata/telegraf/issues/9334
> 
> - [x] `teleport` checksum #78778
> 
> - [x] `terrascan` needs test update #78898

Can these test failures be reproduced from their existing bottles?

**Comment by andig** [comment]
Telegraf is https://github.com/Homebrew/homebrew-core/pull/78999, just needs merge

**Comment by carlocab** [comment]
Yep, but that's a checksum failure and not a test failure. I was asking about the `brew test` failures.

**Comment by nandahkrishna** [comment]
Installed `go 1.16.5` from the bottle and `influxdb` from its bottle as well, failed the first time it ran but I've rerun the test 5 more times and it passed, assuming it's just some transient failure.

**Comment by nandahkrishna** [comment]
As for the checksum failure with `cacli`, I think it's a result of renaming their repository (now at https://github.com/cloud-annotations/cloud-annotations).

The tag was pushed and the release was created on 21 Apr 2020, and hasn't been updated since. The formula was updated on 11 June 2020. I went and checked a [WayBack Machine snapshot](https://web.archive.org/web/20201115201545if_/https://github.com/cloud-annotations/training/releases) of the repository before it was renamed, and the commit hash associated with the tag has not changed.

This leads me to believe that the checksum change is due to the renaming. The name of the directory within GitHub source code archives contains the project name, and now that the repository has been renamed, the checksum will change as a result. Not sure how we can ask them, but I'll see if it's possible to check this with renaming and reproducing the archiving step locally.

**Comment by carlocab** [comment]
Yes, renaming the repo will change the tarball checksum. That's happened to other formulae before. This might be ready to go, I think.

**Comment by carlocab** [comment]
Here are the ARM failures with bottles:
```
cacli
circleci
cql
darksky-weather
geoipupdate
linkerd
packr
peco
td
telegraf
teleport
terrascan
```
Some of them didn't show up on the Intel nodes: `circleci`, `cql`, `darksky-weather`, `geoipupdate`. Have we looked into these?

**Comment by branchvincent** [comment]
> Have we looked into these?

I have not, but from the logs:

* `circleci`

```
==> brew install --build-from-source --only-dependencies clair
Error: rpm: no bottle available!
```

* `cql`

```
==> brew test --retry --verbose cql
Timeout::Error: execution expired
```

* `darksky-weather`

```
==> brew test --retry --verbose darksky-weather
http request to https://geocode.jessfraz.com/forecast failed with status code: 403
```

* `geoipupdate`

```
==> brew install --build-from-source --only-dependencies geoipupdate
Error: ghc: no bottle available!
```

**Comment by carlocab** [comment]
Ah, I see. Some of those were only bottled on ARM recently (i.e. after the CI run here). I think we're ready to merge this now.

**Review by carlocab — APPROVED** [review]
Great work here, @branchvincent, @andig.

**Pull request closed without merging**
