### PR TITLE
cffi: do not force `python-setuptools` dependency

### PR DESCRIPTION
**Pull request by cho-m**
There is a `cffi` feature that uses setuptools, which is used in test, but upstream intentionally does not enforce requirement as dependency: https://github.com/python-cffi/cffi/blob/main/src/cffi/_shimmed_dist_utils.py#L5

Currently, this dependency cascades down to all `python-cryptography` dependents. Instead, dependents that need the feature should add setuptools to the virtualenv.

- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

```console
❯ pipgrip --tree cffi
cffi (1.16.0)
└── pycparser (2.21)
```

### CODE REVIEW

**Comment by cho-m** [comment]
This may lead to dependent build/test failures as `python-setuptools` has been sneaking into various dependency trees via `python-cryptography --> cffi --> python-setuptools`.

**Review by p-linnane — APPROVED** [review]
@cho-m Good to merge when you're ready.

**Comment by carlocab** [comment]
Could we rewrite the test so that we don't need `setuptools` at all?

**Comment by cho-m** [comment]
> Could we rewrite the test so that we don't need `setuptools` at all?

I could use one of the in-line examples like https://cffi.readthedocs.io/en/latest/overview.html#simple-example-abi-level-in-line

**Review by carlocab — APPROVED** [review]
Nice.

**Pull request merged**
