### PR TITLE
apache-zeppelin 0.7.0

### PR DESCRIPTION
**Pull request by slothspot**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
`brew style` failures: https://bot.brew.sh/job/Homebrew%20Core/16414/version=sierra/testReport/junit/brew-test-bot/sierra/style_apache_zeppelin/

`brew test` failures: https://bot.brew.sh/job/Homebrew%20Core/16414/version=sierra/testReport/junit/brew-test-bot/sierra/test_apache_zeppelin/

**Comment by slothspot** [comment]
Hi @MikeMcQuaid, I introduced style problem intentionally trying to figure out how much time does it take for Jetty to start, and I don't understand the problem why zeppelin service doesn't start. So if it's possible, could you extract logs folder from test execution to help me analyze this problem?
On my laptop, I have zeppelin ready to use in approx 40 secs on 1st launch and in less than 15 sec for consecutive launches.

**Comment by MikeMcQuaid** [comment]
@slothspot Sorry, that's not possible. If necessary we can have a simpler test if you can make one that's more reliable.

**Comment by JCount** [comment]
@slothspot Closing this due to inactivity, it will be replaced with a new PR to update `apache-zeppelin`.

**Pull request closed without merging**
