### PR TITLE
buildifier|buildozer: disable because they're not compiling anymore

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
You forgot to split your commits 😅

**Review by carlocab — DISMISSED** [review]

**Review by carlocab — APPROVED** [review]

**Comment by Loyalsoldier** [comment]
Actually in Go v1.16, we can just use `go install github.com/bazelbuild/buildtools/buildifier@version` and `go install github.com/bazelbuild/buildtools/buildozer@version` to build and install them.

**Comment by carlocab** [comment]
@Loyalsoldier this was attempted in #70924 and #70921, but didn't work out. If you know how to fix it, please do open a PR. Thanks!

**Comment by Loyalsoldier** [comment]
@carlocab I have filed an issue to upstream https://github.com/bazelbuild/buildtools/issues/961

Hope they would switch to Go modules instead. And if they don't like the idea, we then can use `go install github.com/bazelbuild/buildtools/buildifier@version` to build and install it, after Go formula updated to v1.16 in Homebrew.

**Comment by Bo98** [comment]
Bazel should be enough to guarantee reproducibility, without the need for Go modules. I don't know why `bazelisk` is used here, but I think should discontinue using that. It doesn't have the patches we apply to Bazel and is likely why these builds were not reproducible.

**Comment by Loyalsoldier** [comment]
I am trying to re-enable buildifier and buildozer in Go v1.16, but it build failed on my test. Here are my changes. I wonder what's the problem?

https://github.com/Loyalsoldier/homebrew-core/commit/0db7db0ba7e81b880e7da350d734d1907bb9ed05

**Comment by Loyalsoldier** [comment]
Since upstream has enabled go module for buildifier and buildozer. I think it's time to re-enable these two formulas.

**Comment by SMillerDev** [comment]
Please make a pull request to fix the builds and re-enable the formula once that commit has actually landed in a release.

**Comment by Loyalsoldier** [comment]
> Please make a pull request to fix the builds and re-enable the formula once that commit has actually landed in a release.

Done in https://github.com/Homebrew/homebrew-core/pull/72219 and https://github.com/Homebrew/homebrew-core/pull/72220

**Pull request merged**
