### PR TITLE
hashicorp packer 1.4.5 => 1.5.0

### PR DESCRIPTION
**Pull request by ndobbs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

https://github.com/hashicorp/packer/blob/master/CHANGELOG.md#150-december-18-2019

### CODE REVIEW

**Comment by bayandin** [comment]
Thanks @ndobbs, there is an already open PR for this: https://github.com/Homebrew/homebrew-core/pull/48110

**Comment by ndobbs** [comment]
My apologies, when I started this work around an hour ago ( I had to break to get kids on the bus ) when I checked the PR did not exist. 

Cheers!

**Comment by ndobbs** [comment]
> Thanks @ndobbs, there is an already open PR for this: #48110

My apologies, I started this work around an hour ago ( I had to break to get kids on the bus ) when I checked the PR did not exist.

Cheers!

**Comment by bayandin** [comment]
No worries!
Also, you may be interested in  using `brew bump-formula-pr` next time for creating PR 👍

**Pull request closed without merging**
