### PR TITLE
mercurial: move to Python 3

### PR DESCRIPTION
**Pull request by fxcoudert**
Now supported

### CODE REVIEW

**Comment by glandium** [comment]
This should be reverted.

Mercurial python 3 support is beta. Third party extensions are still very much python 2.7 in most cases, and this change just breaks them in the worst manner possible. Mercurial doesn't have code in place yet to handle this transition smoothly. It also has, according to https://www.mercurial-scm.org/wiki/Python3, incompatibilities with upcoming python 3.8, meaning it will automatically be subtly broken when homebrew updates to python 3.8.

**Comment by nils-ohlmeier** [comment]
This changed destroyed my dev environment and now I have to manually revert the change for the time being.
If not reverted there should be at least an option to compile mercurial with Python 2 for developers who have extensions installed which still depend on Python 2.

**Comment by iMichka** [comment]
I think this will need to be handled in a private, separate tap (e.g. host a Python 2 version of Mercurial).

If this is feature is still marked as beta, then we may revert it.

Anyway, 1/1/2020 either mercurial supports Python3 and we update it to Python3, or we may remove it completely from homebrew.

Would mercurial work with system Python 2 though? We may just remove the Python dependency here for mac.

**Comment by nils-ohlmeier** [comment]
I don't know if it works with system Python 2. But I'm willing to give it a try if someone can show me how to update the formula to remove the homebrew python dep and replace it with system python :-)

**Comment by fxcoudert** [comment]
Thanks for the feedback. I'm locking discussion here, and opening a PR to discuss a possible move back to Python 2.

**Comment by MikeMcQuaid** [comment]
> Mercurial python 3 support is beta. Third party extensions are still very much python 2.7 in most cases, and this change just breaks them in the worst manner possible. Mercurial doesn't have code in place yet to handle this transition smoothly. It also has, according to https://www.mercurial-scm.org/wiki/Python3, incompatibilities with upcoming python 3.8, meaning it will automatically be subtly broken when homebrew updates to python 3.8.

@glandium Will Mercurial have that code in place before Python 2.7 is EOL (and removed from Homebrew) at the end of this year?

**Pull request closed without merging**
