### PR TITLE
binutils: test Linux build

### PR DESCRIPTION
**Pull request by dawidd6**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by iMichka** [comment]
I think we could also build `zlib` with wheezy. It would then be part of the `binutils/patchelf` list. It happens that we built zlib with ubuntu 16.04 for years now and it worked. But I remember that @sjackman was also building `zlib` with an older OS version a long time ago.

So my recommendation is to add `zlib` to the `wheezy` build list.

**Comment by carlocab** [comment]
```
==> Bottling binutils--2.36.1.x86_64_linux.bottle.1.tar.gz...
tar --create --numeric-owner --format pax --owner 0 --group 0 --sort name --pax-option globexthdr.name=/GlobalHead.%n,exthdr.name=%d/PaxHeaders/%f,delete=atime,delete=ctime --file /tmp/bottles/binutils--2.36.1.x86_64_linux.bottle.1.tar binutils/2.36.1
tar: unrecognized option '--sort'
```
https://github.com/Homebrew/homebrew-core/pull/80035/checks?check_run_id=2917935126#step:8:52

**Comment by iMichka** [comment]
> tar: unrecognized option '--sort'

We could remove `sort` for wheezy? I guess it's just there for `:all` bottles.

**Comment by carlocab** [comment]
Does `brew` know that you're running in wheezy?

**Comment by dawidd6** [comment]
https://github.com/Homebrew/homebrew-linux-dev/pull/201

Imma put newer tar in this oldtimer

**Comment by dawidd6** [comment]
> Does brew know that you're running in wheezy?

`HOMEBREW_ON_DEBIAN7` env var is set in `brew.sh` and `Dockerfile`.

**Comment by dawidd6** [comment]
Once the image is built and pushed, I'm going to restart this build and see if it succeed. Then close this PR and dispatch zlib build with upload.

**Pull request closed without merging**
