### PR TITLE
minio 20200718184816

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
Could replace `"-trimpath", "-o", bin/"minio"` with `*std_go_args`

Missing `head` stanza

**Review by SeekingMeaning — COMMENTED** [review]
Could replace `"-trimpath", "-o", bin/"minio"` with `*std_go_args`

Missing `head` stanza

**Comment by chenrui333** [comment]
good call, updating it now.

**Comment by SeekingMeaning** [comment]
Oh yeah also `prefix.install_metafiles` can be deleted, right?

**Comment by chenrui333** [comment]
> Oh yeah also `prefix.install_metafiles` can be deleted, right?

that sounds about right too

**Review by SeekingMeaning — APPROVED** [review]

**Pull request closed without merging**
