### PR TITLE
grafana 7.5.7

### PR DESCRIPTION
**Pull request by zserge**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
license mismatch
```
grafana:
  * Formula license ["Apache-2.0"] does not match GitHub license ["AGPL-3.0"].
Error: 1 problem in 1 formula detected
```

**Comment by chenrui333** [comment]
The license update would be something for 8.0 release (related PR, grafana/grafana#33184)

**Comment by nandahkrishna** [comment]
Just adding a note here that build failed on 10.14 (as of now). There seem to have been similar failures (across platforms) in previous PRs.

**Comment by carlocab** [comment]
Could the change at https://github.com/Homebrew/homebrew-core/pull/74747 help here?

**Comment by carlocab** [comment]
Fixed Mojave but broke Catalina and Big Sur 😅

**Comment by nandahkrishna** [comment]
Latest commit seems to have worked! Only license-related audit failures.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
