### PR TITLE
acmetool 0.0.56

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed.

**Comment by DomT4** [comment]
I really wish they'd move to the vendor system. 👍 whenever you're happy.

**Comment by ilovezfs** [comment]
@DomT4 yeah filing an issue requesting vendoring crossed my mind. This is absurd. And that src/github.com/hlandau/buildinfo/gen raw output is grim to put it in Domese.

**Comment by DomT4** [comment]
Yeah, from what I've seen setting up vendoring isn't that difficult & it's _considerably_ more stable for well... just about everyone involved really.

**Pull request closed without merging**
