### PR TITLE
vim 8.0.0002

### PR DESCRIPTION
**Pull request by lembacon**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by DomT4** [comment]
There's a couple of hot fixes out already. Don't know if we want to bump this to `8.0.0002` prior to merging to get on top of those?

**Comment by lembacon** [comment]
@DomT4 Bumped to `8.0.0002`. 😜

**Comment by DomT4** [comment]
Thanks! I'll go ahead & merge this once the CI is happy again. Don't think I've ever seen so much excitement for a `vim` release before 😄.

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/7084bda96c1d45f7ed1e6e934763041e79d2684f. Thank you for another contribution to Homebrew @lembacon; we appreciate it! :smiley_cat:

**Comment by douglarek** [comment]
Now vim 8.0.0003 is out 😄

**Pull request closed without merging**
