### PR TITLE
graph-tool 2.30

### PR DESCRIPTION
**Pull request by count0**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by count0** [comment]
@BrewTestBot test this please

**Comment by count0** [comment]
@BrewTestBot test this please

**Comment by count0** [comment]
@scpeters  @SMillerDev one of the bottles seem to be failing, and I don't know why. Could you give a hand?

**Comment by count0** [comment]
@BrewTestBot test this please

**Comment by count0** [comment]
All checks have completed, but the last jenkins step is stuck for days now... Could someone try to unclog this?

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by count0** [comment]
@SMillerDev It seems we are good to go!

**Comment by SMillerDev** [comment]
Yes it does! Thanks @count0 ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
