### PR TITLE
sile: update --HEAD to track upstream development branch (Rusty)

### PR DESCRIPTION
**Pull request by alerque**

### CODE REVIEW

**Comment by alerque** [comment]
This is still being worked on and trying to fix the `--HEAD` installs to be actually meaningful.

**Comment by chenrui333** [comment]
@alerque just FYI, while you are working on this PR, I have bump the formula to the 0.14.13 release. Thanks!

**Comment by alerque** [comment]
Pssshaw. Scram bot.

**Comment by cho-m** [comment]
Fixed up style and added `poppler` as build was failing on missing `pdfinfo`.

However, doesn't build yet:
```
checking for luajit.h... yes
checking for Lua header version... 5.4
checking if Lua header version matches 5.1... no
configure: error: cannot find headers for specified LUA_INCLUDE
```

**Comment by cho-m** [comment]
@alerque The HEAD build currently fails due to multiline makefile syntax at https://github.com/sile-typesetter/sile/blob/develop/build-aux/rust_boilerplate.mk.in#L60-L61

At least on macOS, this is not a single line and needs a backslash otherwise the build will fail:
```
    Finished release [optimized] target(s) in 1m 13s
CARGO_TARGET_DIR=/private/tmp/sile-20231206-9855-hyeik6/target /usr/local/opt/rust/bin/cargo build --quiet --message-format=json --features luajit   --features variations --release --locked |
/bin/sh: -c: line 1: syntax error: unexpected end of file
make[2]: *** [/private/tmp/sile-20231206-9855-hyeik6/target/release/sile] Error 2
make[2]: *** Deleting file `/private/tmp/sile-20231206-9855-hyeik6/target/release/sile'
make[1]: *** [all-recursive] Error 1
```

**Comment by alerque** [comment]
Thanks, I'll deal with that!

**Comment by alerque** [comment]
@cho-m Fixed. The main Makefile also has a few multi-liners, but it also specifies `.ONESHELL`. Apparently that property is inherited for included Makefiles in GNU, but not on BSD. I just added a line continuation to that line so it shouldn't be an issue any more.

**Comment by alerque** [comment]
We'll need to add another resource block for compat53. That is a requirement for LuaJIT (and other older Luas) that 5.4 did not need. If possible LuaJIT is almost certainly the best route to take here though so it's worth overcoming that.

**Comment by cho-m** [comment]
> We'll need to add another resource block for compat53.

I added it https://github.com/Homebrew/homebrew-core/pull/149942/files#diff-3eb1279f99561316a5b5d8760ed698b7e59328c530212cc887e177dda19289e2R37

I think HEAD should be possible to build now.

**Review by p-linnane — APPROVED** [review]

**Pull request merged**
