### PR TITLE
ophcrack 3.6.1

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by DomT4** [comment]
I am shocked to see you not change a `#{bin}` to `bin` in the test 😉.

👍 whenever 🍏.

**Comment by ilovezfs** [comment]
@DomT4 I should teach `bump-formula-pr` to do that, huh!

**Comment by ilovezfs** [comment]
@DomT4 no scolding about my inadvertently killing the mirror? :)

**Comment by DomT4** [comment]
The mirror hasn't been updated upstream yet, I checked 😄.

**Comment by ilovezfs** [comment]
>The mirror hasn't been updated upstream yet, I checked :smile:.

I should not have doubted you. The Debian pipes are now unclogged and it's available, so I'll throw it back in.

**Comment by ilovezfs** [comment]
mirror re-added and grotesque `#{bin}` corrected in post

**Comment by DomT4** [comment]
> I should not have doubted you. 

I don't see why not, I doubt myself fairly often 😄. I'm planning to add code to the core to fetch the mirror & check it still exists soonish so we should stop missing dead mirrors.

**Pull request closed without merging**
