### PR TITLE
git-annex: readd S3 support.

### LINKED ISSUE #60505: git-annex lost Amazon S3 support
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
  `Error: no logs` ?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

<details><summary><code>brew config</code></summary>

```
    user@users-iMac homebrew-core % brew config
    HOMEBREW_VERSION: 2.4.16
    ORIGIN: https://github.com/Homebrew/brew
    HEAD: 2a4c9f610e69b9fed1eec61ac2c53e4b11a32e4c
    Last commit: 29 hours ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: 41a4db231ecd421c896b57ad802611c590ab33a2
    Core tap last commit: 15 minutes ago
    Core tap branch: master
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_CASK_OPTS: []
    HOMEBREW_MAKE_JOBS: 4
    CPU: quad-core 64-bit penryn
    Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
    Clang: 11.0 build 1103
    Git: 2.24.2 => /Library/Developer/CommandLineTools/usr/bin/git
    Curl: 7.64.1 => /usr/bin/curl
    macOS: 10.15.4-x86_64
    CLT: 11.4.1.0.1.1586360307
    Xcode: N/A
    user@users-iMac homebrew-core % brew doctor
    Your system is ready to brew.
```

</details>

## What you were trying to do (and why)

Use git-annex to share scientific data.

## What happened (include command output)

We have a dataset whose content is on AWS, via git-annex (https://github.com/spine-generic/data-multi-subject/); all the datasets in https://openneuro.org and most in https://portal.conp.ca are the same.

But since the middle of the month or so this has been happening:

<details>
  <summary>Command output</summary>

```
julien-macbook:~/code/spine-generic/data-multi-subject $ git checkout -b jca/17-defacing
Switched to a new branch 'jca/17-defacing'
julien-macbook:~/code/spine-generic/data-multi-subject $ git remote
amazon
origin
julien-macbook:~/code/spine-generic/data-multi-subject $ 
julien-macbook:~/code/spine-generic/data-multi-subject $ gs
 M sub-cmrra02/anat/sub-cmrra02_T2w.nii.gz
 M sub-cmrra04/anat/sub-cmrra04_T2w.nii.gz
 M sub-cmrra05/anat/sub-cmrra05_T2w.nii.gz
 M sub-oxfordFmrib07/anat/sub-oxfordFmrib07_T1w.nii.gz
 M sub-stanford06/anat/sub-stanford06_T1w.nii.gz
julien-macbook:~/code/spine-generic/data-multi-subject $ gc
(recording state in git...)
[jca/17-defacing 4ea269a7] Fixed defacing in a few subjects
 5 files changed, 5 insertions(+), 5 deletions(-)
julien-macbook:~/code/spine-generic/data-multi-subject $ git annex sync --content amazon
git-annex: there is no available git remote named "amazon"
julien-macbook:~/code/spine-generic/data-multi-subject $ git remote
amazon
origin
julien-macbook:~/code/spine-generic/data-multi-subject $ 
```

and this:

```
julien-macbook:~/code/spine-generic/data-multi-subject $ git annex enableremote amazon
enableremote amazon 
git-annex: Unknown remote type S3 (pick from: git gcrypt p2p bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs hook external)
failed
git-annex: enableremote: 1 failed
```

The most underlying issue is that git-annex has lost its S3 support. The telling symptom is that this doesn't say "S3" or "aws" anywhere:

```
git annex version                                         
git-annex version: 8.20200720.1
build flags: Assistant Webapp Pairing WebDAV FsEvents TorrentParser MagicMime Feeds Testsuite
dependency versions: bloomfilter-2.0.1.0 cryptonite-0.27 DAV-1.3.4 feed-1.3.0.1 ghc-8.6.5 http-client-0.7.1 persistent-sqlite-2.10.6.2 torrent-10000.1.1 uuid-1.3.13 yesod-1.6.0.2
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2BP512E BLAKE2BP512 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL
remote types: git gcrypt p2p bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs hook external
operating system: darwin x86_64
supported repository versions: 8
upgrade supported from repository versions: 0 1 2 3 4 5 6 7
```

</details>

## What you expected to happen

A working copy should say "build flags: ... S3 ..." and "dependency versions: aws-0.22":

```
git annex version
git-annex version: 8.20200720.1
build flags: Assistant Webapp Pairing S3 WebDAV FsEvents TorrentParser MagicMime Feeds Testsuite
dependency versions: aws-0.22 bloomfilter-2.0.1.0 cryptonite-0.27 DAV-1.3.4 feed-1.3.0.1 ghc-8.6.5 http-client-0.7.1 persistent-sqlite-2.10.6.2 torrent-10000.1.1 uuid-1.3.13 yesod-1.6.0.2
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2BP512E BLAKE2BP512 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs hook external
operating system: darwin x86_64
supported repository versions: 8
upgrade supported from repository versions: 0 1 2 3 4 5 6 7
```

This was working for us a month ago.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew update
brew install git-annex
git annex version
```

### PR DESCRIPTION
**Pull request by kousu**
Fixes #60505

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This readds the package settings lost in https://github.com/Homebrew/homebrew-core/pull/59330/.

I didn't readd the `using: ["alex", "happy", "c2hs"],` part because I couldn't figure out how; it means, "build this package with these tools". It sounds like something that cabal v2 already specifies implicitly? I'm not really sure. Anyway the package builds and works for me without them.

### CODE REVIEW

**Comment by kousu** [comment]
There are a lot of *other* flags that could be enabled too. This only addresses #60505; if you look in my report, you'll see that the difference was that "dependency versions" lost "aws-0.22".

The older version was enabling "S3" and "webapp"; it seems that webapp is on by default now, and I don't know what the --constraints were for but they don't seem to be necessary anymore: https://github.com/Homebrew/homebrew-core/pull/59330/files

**Comment by kousu** [comment]
Failing because `icon-license` isn't in https://spdx.org/licenses/. Here's what git-annex's COPYRIGHT says about it:

```
Files: doc/logo* */favicon.ico standalone/osx/git-annex.app/Contents/Resources/git-annex.icns
Copyright: 2007 Henrik Nyh <http://henrik.nyh.se/>
           2010 Joey Hess <id@joeyh.name>
           2013 John Lawrence
License: icon-license
  Free to modify and redistribute with due credit, and obviously free to use.
```

Thoughts on how to handle this? It's pretty similar to CC-BY but it's not CC-BY.

**Comment by kousu** [comment]
If the ambiguous license is a problem, I have a from my bud @singpolyma to replace the icons with https://thenounproject.com/, or just patch them out of the package and let things break. I figure they're probably mostly used in the Assistant and the Webapp, and those should (should) be able to handle not having icons. But maybe they can't.

**Comment by SMillerDev** [comment]
I'd say for usability it would be good to keep the icons, so making a patch to use open source ones would be great.

**Comment by kousu** [comment]
The license is libre, it's just not on SPDX's list.

Patching all the icons is kinda out of scope for what I was originally trying to fix. Is there a way to get this in and deal with the license later? I could just remove "icons-license" from the list, or is there a close-enough option on the SPDX list that we could relabel it as?

**Comment by jonchang** [comment]
Since COPYRIGHT is distributed in the bottle, and we don't include the documentation anyway we don't need to worry about the icon license.

**Review by jonchang — APPROVED** [review]
@kousu thanks for contributing to Homebrew!

**Pull request closed without merging**
