### PR TITLE
planck 2.9.0

### PR DESCRIPTION
**Pull request by ilovezfs**
require Java 8 specifically at build time

### CODE REVIEW

**Comment by ilovezfs** [comment]
```
==> Verifying planck-2.9.0.tar.gz checksum
tar xzf /Users/brew/Library/Caches/Homebrew/planck-2.9.0.tar.gz
==> ./script/build-sandbox
Fetching Google Closure compiler...
Cleaning up Google Closure compiler archive...
### Building planck-cljs
Build Failed.
Error: No such file or directory - planck-c/build/planck
```

**Comment by mfikes** [comment]
@ilovezfs On a fresh box, if you do `brew install leiningen`, you don't get Java installed as well. This makes me wonder if the Planck formula now needs to explicitly specify that Java is a `:build` dep, whereas previously this was unnecessary.

**Comment by ilovezfs** [comment]
@mfikes it's incompatible with Java 9. That's why the build fails.

**Comment by mfikes** [comment]
Thanks @ilovezfs !

**Comment by ilovezfs** [comment]
@mfikes you're welcome! It would be great if you could work on adding Java 9 support so that users don't need to have 2 versions of Java installed.

**Comment by ilovezfs** [comment]
@mfikes I just saw https://github.com/mfikes/planck/issues/546! Thanks :)

**Pull request closed without merging**
