### PR TITLE
aws-google-auth: switch to pypi source and update livecheck

### PR DESCRIPTION
**Pull request by chenrui333**
aws-google-auth: switch to pypi source

### CODE REVIEW

**Comment by fxcoudert** [comment]
If the source tarball checksum changes, then the source is not the same and we have to test it, so it's not `CI-syntax-only`

**Review by Rylan12 — COMMENTED** [review]
We should add:

```ruby
livecheck do
  url :stable
end
```

Otherwise, livecheck will use the `head` url.

**Review by Rylan12 — COMMENTED** [review]
We should change the `livecheck` to use the new PyPI URL:

```ruby
livecheck do
  url :stable
end
```

Huh, reviewed twice I guess... 😕

**Comment by chenrui333** [comment]
@Rylan12 make sense, just added the livecheck block.

**Review by Rylan12 — APPROVED** [review]

**Pull request closed without merging**
