### PR TITLE
newrelic-infra-agent: add support for arm

### PR DESCRIPTION
**Pull request by rubenruizdegauna**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
Why `CI-no-bottles` @carlocab? Don't we want bottles?

**Comment by carlocab** [comment]
We do, but those can be dispatched separately

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Bottle build at https://github.com/Homebrew/homebrew-core/actions/runs/3057448619.

Thanks @rubenruizdegauna!

**Comment by carlocab** [comment]
Bottled in https://github.com/Homebrew/homebrew-core/commit/265220d0e1ed2d07a683ffc1119d3903545faa14.

**Pull request merged**
