### PR TITLE
Snort 2.9.15

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
Relates to https://github.com/Homebrew/homebrew-core/pull/43296

**Comment by chenrui333** [comment]
04:41:17 ==> brew install ./snort--2.9.15.catalina.bottle.tar.gz
04:41:25 ==> FAILED
04:41:25 Warning: The post-install step did not complete successfully
04:41:25 You can try again using `brew postinstall snort`
04:41:25 ==> An exception occurred within a child process:
04:41:25   Errno::EACCES: Permission denied @ rb_sysopen - /usr/local/etc/snort/classification.config

**Comment by timesflying** [comment]
Yes, as I have written. Same old story as with Snort versions 2.9.13, 2.9.14, 2.9.14.1.

**Comment by chenrui333** [comment]
18:58:45 ==> brew install ./snort--2.9.15.mojave.bottle.tar.gz
18:58:53 ==> FAILED
18:58:53 Warning: The post-install step did not complete successfully
18:58:53 You can try again using `brew postinstall snort`
18:58:53 ==> An exception occurred within a child process:
18:58:53   Errno::EACCES: Permission denied @ rb_sysopen - /usr/local/etc/snort/attribute_table.dtd

**Comment by chenrui333** [comment]
@timesflying how can we submit an upstream issue for the source code?

**Pull request closed without merging**
