### PR TITLE
glib: formula cleanup

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by tschoonj** [comment]
Would anyone mind if I boneyard `gst-plugins-bad@0.10`? No other formula appears to be using it

**Comment by MikeMcQuaid** [comment]
@tschoonj Check the usage numbers in analytics. Shout on Slack if you need help doing that.

**Comment by tschoonj** [comment]
Feel free to merge this one in: the glib bottles don't need an update but the gst-plugins-bad@0.10 ones do.

Thanks

**Comment by fxcoudert** [comment]
29 downloads in one month for `gst-plugins-bad@0.10`, vs 578 for `gst-plugins-bad`.
5% usage means I would support boneyarding.

**Pull request closed without merging**
