### PR TITLE
openjdk 23.0.1

### PR DESCRIPTION
**Pull request by cv3x**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Comment by calvinit** [comment]
This PR needs to wait for the `questdb` Formula to be [upgraded to version 8.1.4](https://github.com/questdb/questdb/pull/5065#issuecomment-2425110358) before proceeding.

**Comment by fxcoudert** [comment]
Incorporating the changes in https://github.com/Homebrew/homebrew-core/pull/195392

**Comment by calvinit** [comment]
The [homepage](https://vsl.cis.udel.edu/civl/) of `civl` formula cannot be accessed. Can the check of this dep be skipped this time? @chenrui333 
```
curl: (28) Failed to connect to vsl.cis.udel.edu port 443 after 75003 ms: Couldn't connect to server
```

Additionally, the `rm -rf /Users/brew/Library/Caches/Homebrew` command failed to execute due to permission issues;
```
rm: /Users/brew/Library/Caches/Homebrew/java_cache/.gradle/caches/modules-2: Permission denied
rm: /Users/brew/Library/Caches/Homebrew/java_cache/.gradle/caches: Permission denied
rm: /Users/brew/Library/Caches/Homebrew/java_cache/.gradle: Permission denied
rm: /Users/brew/Library/Caches/Homebrew/java_cache: Permission denied
rm: /Users/brew/Library/Caches/Homebrew: Permission denied
```
the `public.dhe.ibm.com` domain cannot be resolved.
```
curl: (6) Could not resolve host: public.dhe.ibm.com
```
It seems that there are problems with the environment checks.

**Comment by chenrui333** [comment]
> The [homepage](https://vsl.cis.udel.edu/civl/) of `civl` formula cannot be accessed. Can the check of this dep be skipped this time? @chenrui333

yeah, we should deprecate it, I will followup a bit.

**Comment by chenrui333** [comment]
## for teku

it would be some license check issue

```
  > Task :generateLicenseReport
  Module com.github.jnr:jffi:1.3.13 has multiple license reported:
  Apache License, Version 2.0
  GNU Lesser General Public License version 3
  Consider adding module license information in overrideLicenses.
  
  Module org.jupnp:org.jupnp.support:3.0.2 has multiple license reported:
  "CDDL-1.0";link="https://opensource.org/license/cddl-1-0/";description="Common Development and Distribution License 1.0"
  CDDL-1.0
  Consider adding module license information in overrideLicenses.
```

## for tsduck

it is the libvatek compatibility issue, upstream bug report, https://github.com/VisionAdvanceTechnologyInc/vatek_sdk_2/issues/9

**Comment by chenrui333** [comment]
All the issues are not related to this patch version update, merging.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
@calvinit thanks for the great work on this! 💯

**Pull request merged**
