### PR TITLE
zabbix 3.2.1

### PR DESCRIPTION
**Pull request by javian**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by javian** [comment]
This is the error from the bot
```
==> Verifying zabbix-3.2.1.tar.gz checksum
Error: SHA256 mismatch
Expected: 8926b96ef05cba041d05329130f40e8e1311ad201e58c75d22005eda4075c091
Actual: faac18463d2ac4fbe093ea462f9c24c3e68343ba5edc39ee2ec1d6365126a5db
Archive: /Users/brew/Library/Caches/Homebrew/zabbix-3.2.1.tar.gz
```
And when I check on my machine I see the following
```
➜  homebrew-core git:(master) shadhl https://downloads.sourceforge.net/projects/zabbix/files/ZABBIX%20Latest%20Stable/3.2.1/zabbix-3.2.1.tar.gz
acb5b44e30512a8062ec486c12757c17c3fef79106b05507c6b876c0deaf7866
```
I'm guessing this has something to do with sourceforge ?

**Comment by javian** [comment]
Found the issue so it should be fine after the bot checked.

**Comment by javian** [comment]
The problem is now that
```
Testing zabbix
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20161030-61174-uzmipj.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zabbix.rb --verbose
==> /usr/local/Cellar/zabbix/3.2.1/sbin/zabbix_agentd --print
agent.hostname                                [s|Zabbix server]
agent.ping                                    [u|1]
agent.version                                 [s|3.2.1]
system.localtime[utc]                         [u|1477819836]
system.run[echo test]                         [m|ZBX_NOTSUPPORTED] [Remote commands are not enabled.]
web.page.get[localhost,,80]                   [t|]
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/zabbix/3.2.1/sbin/zabbix_agentd
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/zabbix/3.2.1/sbin/zabbix_agentd
  Expected in: /usr/lib/libSystem.B.dylib

Error: zabbix: failed
Failed executing: /usr/local/Cellar/zabbix/3.2.1/sbin/zabbix_agentd --print
/usr/local/Homebrew/Library/Homebrew/formula.rb:1733:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1671:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1671:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zabbix.rb:63:in `block in <class:Zabbix>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1571:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:832:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1570:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1564:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by eagleflo** [comment]
This was merged in as part of #6698 with a patch that works around the `_clock_gettime` issue. Feel free to close.

**Comment by javian** [comment]
@eagleflo do you know if the patch has been reported upstream ?

**Pull request closed without merging**
