### PR TITLE
Add Redex

### PR DESCRIPTION
**Pull request by kageiit**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by zmwangx** [comment]
We don't accept head-only formulae here, unfortunately. You need to talk to the upstream to have them tag a release.

**Comment by MikeMcQuaid** [comment]
Closing until there's a release.

**Comment by kageiit** [comment]
Release happened last week. I'll update the pr today

**Comment by kageiit** [comment]
@MikeMcQuaid I updated my remote branch with the release tag. Can you reopen this PR or should i just make a new one?

**Pull request closed without merging**
