### PR TITLE
avrdude: use elfutils on Linux

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

How do we rebuild only the Linux bottle?

### CODE REVIEW

**Comment by carlocab** [comment]
> How do we rebuild only the Linux bottle?

We could try deleting the existing Linux bottle, remove the `:x86_64_linux` line and see if `dispatch-build-bottle` works.

**Comment by cho-m** [comment]
How well does it handle alignment changes?

i.e. can I just delete Linux line without reformatting the other bottles?

**Comment by carlocab** [comment]
I think we should fix the alignment too as I think pushing this to master will cause all tap syntax jobs to fail.

**Review by dawidd6 — APPROVED** [review]

**Comment by dawidd6** [comment]
https://github.com/Homebrew/homebrew-core/runs/3392332302?check_suite_focus=true

**Comment by cho-m** [comment]
We need to delete old bottle from package https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Favrdude

**Comment by dawidd6** [comment]
AFAIK we can't delete packages once uploaded, so we might have to rebuild all bottles anyway.

**Comment by cho-m** [comment]
I do see a **Delete version** under `...` menu at https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Favrdude/versions?filters%5Bversion_type%5D=untagged but I don't know if it will do anything.

**Comment by dawidd6** [comment]
Hmm, that's new I think. Imma try it. Worst case scenario: we'll rebuild all bottles. Best case scenario: we will upload just a new Linux bottle.

**Comment by dawidd6** [comment]
Need a rebuild then I guess.

**Comment by cho-m** [comment]
Not sure how it will handle the modified bottles/syntax. I guess we can try rebuild. If something goes wrong, we may need to revert some things.

**Comment by iMichka** [comment]
What is the status of this? I will need to bump the revision in linuxbrew-core to revision 2, so maybe better just bump it here too?

If we hesitate to bump revisions because we might loose old macOS bottles, we need to implement OS-specific revisions in brew.

**Comment by cho-m** [comment]
Nothing has been done yet. We still need to decide how we want to upload the Linux bottle, whether via rebuild, revision bump, or some other method.

I'll probably let someone more familiar with GitHub packages and best-practices for rebuilds/revisions to comment on this.

---

I did take a look at `elftoolchain` as macOS `libelf`-replacement, which would result in a revision bump for macOS. I got it to build (with some workarounds needed due to `bmake`), but there are some issues:
- Current release (2016) has arch-logic that blocks build on ARM. SVN trunk has commits from 2020 that may fix this.
- There is a fairly large amount of shadowing/conflicts. Not only does it include common tools like `ar` and `ld`, but it also includes a DWARF library which conflicts with `libdwarf`. The easiest approach would probably be `keg_only`. Alternatively can do some `libexec` installation plus symlinking based on conflicts.

**Comment by iMichka** [comment]
Follow up PR: #83811

**Pull request merged**
