### PR TITLE
openjdk@11: use `llvm` to avoid Apple clang 16 failure

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Review by carlocab — APPROVED** [review]
LGTM. Does their build have any default `-O` flags (in release mode?) that get set without arg refurbishment?

**Comment by Bo98** [comment]
> Does their build have any default `-O` flags (in release mode?) that get set without arg refurbishment?

Yeah they use all args. `-O3` is the was libjvm should be built with (but is also the thing that crashes).

Slightly cautious doing this given we could just use the Sonoma bottle that works fine on a faster optimisation. Idea in the other PR was to try report this to Apple so that it can be fixed before Sonoma Xcode support ends in December.

If we want to push ahead anyway: can we at least do a benchmark between the two?

**Comment by cho-m** [comment]
On side note, `-fsanitize=undefined` does show some UB:
```
Compiling 4 files for BUILD_JIGSAW_TOOLS
Optimizing the exploded image
ad_aarch64.cpp:12188:6: runtime error: member call on null pointer of type 'RegisterImpl'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ad_aarch64.cpp:12188:6 in
/private/tmp/openjdkA17-20240917-4348-lho1d6/jdk17u-jdk-17.0.12-ga/src/hotspot/cpu/aarch64/vmreg_aarch64.inline.hpp:29:28: runtime error: member call on null pointer of type 'RegisterImpl *'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /private/tmp/openjdkA17-20240917-4348-lho1d6/jdk17u-jdk-17.0.12-ga/src/hotspot/cpu/aarch64/vmreg_aarch64.inline.hpp:29:28 in
/private/tmp/openjdkA17-20240917-4348-lho1d6/jdk17u-jdk-17.0.12-ga/src/hotspot/cpu/aarch64/register_aarch64.hpp:61:9: runtime error: member call on null pointer of type 'const RegisterImpl *'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /private/tmp/openjdkA17-20240917-4348-lho1d6/jdk17u-jdk-17.0.12-ga/src/hotspot/cpu/aarch64/register_aarch64.hpp:61:9 in
ad_aarch64.cpp:12189:6: runtime error: member call on null pointer of type 'RegisterImpl'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ad_aarch64.cpp:12189:6 in
ad_aarch64.cpp:12189:18: runtime error: member call on null pointer of type 'VMRegImpl'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ad_aarch64.cpp:12189:18 in
/private/tmp/openjdkA17-20240917-4348-lho1d6/jdk17u-jdk-17.0.12-ga/src/hotspot/share/code/vmreg.hpp:100:9: runtime error: member call on null pointer of type 'VMRegImpl *'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /private/tmp/openjdkA17-20240917-4348-lho1d6/jdk17u-jdk-17.0.12-ga/src/hotspot/share/code/vmreg.hpp:100:9 in
/private/tmp/openjdkA17-20240917-4348-lho1d6/jdk17u-jdk-17.0.12-ga/src/hotspot/share/code/vmreg.hpp:114:12: runtime error: member call on null pointer of type 'const VMRegImpl *'
```

**Comment by cho-m** [comment]
Alternatively, we could use `llvm` by disabling the `ptrauth.h` usage:
```
inreplace "src/hotspot/os_cpu/bsd_aarch64/pauth_bsd_aarch64.inline.hpp" do |s|
  s.sub! "#include <ptrauth.h>", ""
  s.sub! "return ptrauth_strip(ptr, ptrauth_key_asib);", "return ptr;"
end
```

Related: https://github.com/openjdk/jdk/commit/6fab8a2d6a97dbd2ffceca275716d020cb9f1eea

**Comment by Bo98** [comment]
Does the latest JDK trigger any UB (given we're seeing similar miscompiles with that)?

**Comment by cho-m** [comment]
> Does the latest JDK trigger any UB (given we're seeing similar miscompiles with that)?

There is UB. Some have been reported upstream. The last ones using Apple Clang are:
```
/private/tmp/openjdk-20240918-2656-jahbcl/jdk22u-jdk-22.0.2-ga/src/hotspot/cpu/aarch64/bytes_aarch64.hpp:36:64: runtime error: load of misaligned address 0x00011e5e46d9 for type 'u2' (aka 'unsigned short'), which requires 2 byte alignment
0x00011e5e46d9: note: pointer points here
 00 3e 1d  b8 13 00 9a 00 05 03 ac  1c 1d b8 11 00 60 3d a7  ff e2 04 ac ff 01 d9 03  99 12 31 39 12
              ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /private/tmp/openjdk-20240918-2656-jahbcl/jdk22u-jdk-22.0.2-ga/src/hotspot/cpu/aarch64/bytes_aarch64.hpp:36:64 in
/private/tmp/openjdk-20240918-2656-jahbcl/jdk22u-jdk-22.0.2-ga/src/hotspot/share/c1/c1_Instruction.cpp:386:16: runtime error: left shift of negative value -566407518720
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /private/tmp/openjdk-20240918-2656-jahbcl/jdk22u-jdk-22.0.2-ga/src/hotspot/share/c1/c1_Instruction.cpp:386:16 in
/private/tmp/openjdk-20240918-2656-jahbcl/jdk22u-jdk-22.0.2-ga/src/hotspot/share/ci/ciTypeFlow.hpp:211:62: runtime error: load of value 4294967295, which is not a valid value for type 'Cell'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /private/tmp/openjdk-20240918-2656-jahbcl/jdk22u-jdk-22.0.2-ga/src/hotspot/share/ci/ciTypeFlow.hpp:211:62 in
/private/tmp/openjdk-20240918-2656-jahbcl/jdk22u-jdk-22.0.2-ga/src/hotspot/cpu/aarch64/bytes_aarch64.hpp:36:64: runtime error: load of misaligned address 0x00011e60140d for type 'u2' (aka 'unsigned short'), which requires 2 byte alignment
0x00011e60140d: note: pointer points here
 b8 00 07 b8 00 0d b1  ff 01 69 39 00 00 00 00  08 00 34 00 35 00 00 00  00 00 01 00 37 00 01 00  98
             ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /private/tmp/openjdk-20240918-2656-jahbcl/jdk22u-jdk-22.0.2-ga/src/hotspot/cpu/aarch64/bytes_aarch64.hpp:36:64 in
/private/tmp/openjdk-20240918-2656-jahbcl/jdk22u-jdk-22.0.2-ga/src/hotspot/cpu/aarch64/bytes_aarch64.hpp:36:64: runtime error: load of misaligned address 0x00011e601d59 for type 'u2' (aka 'unsigned short'), which requires 2 byte alignment
0x00011e601d59: note: pointer points here
 43 12 11  ff 00 25 00 04 07 00 08  07 02 ed 07 00 56 07 02  ee 00 01 07 00 92 01 fa  00 03 4c 07 00
              ^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /private/tmp/openjdk-20240918-2656-jahbcl/jdk22u-jdk-22.0.2-ga/src/hotspot/cpu/aarch64/bytes_aarch64.hpp:36:64 in
Exception in thread "main" java.lang.ClassFormatError: StackMapTable format error: bad verification type
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:52)
make[3]: *** [/private/tmp/openjdk-20240918-2656-jahbcl/jdk22u-jdk-22.0.2-ga/build/macosx-aarch64-server-release/buildtools/create_symbols_javac/_the.COMPILE_CREATE_SYMBOLS_batch] Error 1
```

**Comment by cho-m** [comment]
Some non-deterministic behavior for `openjdk@11` now with 1st run passing and 2nd run failing. At least better now given pre-patch I hit a failure on every local run.

**Review by carlocab — APPROVED** [review]
LGTM, but the failure specific to Apple Clang needs to be reported to Apple.

**Comment by cho-m** [comment]
May need to split this PR to try some re-runs to see if the JDK 11 failure can be reproduced on JDK 17.

---

Also, just noting that the failure difference between JDK 17 and 21 is due to https://github.com/openjdk/jdk/commit/bbc57483ce4904efa5ff4c8384a74ee7f8776317 so newer JDK gets a "cleaner" exception:
```
Error: Unable to initialize main class build.tools.jigsaw.AddPackagesAttribute
Caused by: java.lang.ClassFormatError: StackMapTable format error: access beyond the end of attribute
```

Prior to this, the original exception gets passed up. If run with sanitizer, then it ends up being a UndefinedBehaviorSanitizer error like:
```
==75620==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x0000ffff0001 (pc 0x000106f57b9c bp 0x00016f8f2aa0 sp 0x00016f8f2a90 T17584548)
==75620==The signal is caused by a READ memory access.
    #0 0x106f57b9c in Chunk::next() const+0x1c (libjvm.dylib:arm64+0x3f7b9c)
    #1 0x106f43a8c in ChunkPool::allocate()+0x3c (libjvm.dylib:arm64+0x3e3a8c)
    #2 0x106f43928 in Chunk::operator new(unsigned long, AllocFailStrategy::AllocFailEnum, unsigned long)+0x3c (libjvm.dylib:arm64+0x3e3928)
    #3 0x106f44a78 in Arena::grow(unsigned long, AllocFailStrategy::AllocFailEnum)+0x54 (libjvm.dylib:arm64+0x3e4a78)
    #4 0x10779924c in PhaseIdealLoop::Dominators()+0x164 (libjvm.dylib:arm64+0xc3924c)
    #5 0x107edb044 in PhaseIdealLoop::build_and_optimize()+0x95c (libjvm.dylib:arm64+0x137b044)
    #6 0x10728b42c in PhaseIdealLoop::PhaseIdealLoop(PhaseIterGVN&, LoopOptsMode)+0x84 (libjvm.dylib:arm64+0x72b42c)
    #7 0x10727afa0 in PhaseIdealLoop::optimize(PhaseIterGVN&, LoopOptsMode)+0x38 (libjvm.dylib:arm64+0x71afa0)
    #8 0x107272b64 in Compile::Optimize()+0x3fc (libjvm.dylib:arm64+0x712b64)
    #9 0x107270574 in Compile::Compile(ciEnv*, ciMethod*, int, Options, DirectiveSet*)+0xb28 (libjvm.dylib:arm64+0x710574)
    #10 0x107100438 in C2Compiler::compile_method(ciEnv*, ciMethod*, int, bool, DirectiveSet*)+0x128 (libjvm.dylib:arm64+0x5a0438)
    #11 0x1072982b0 in CompileBroker::invoke_compiler_on_method(CompileTask*)+0x854 (libjvm.dylib:arm64+0x7382b0)
    #12 0x1072974b4 in CompileBroker::compiler_thread_loop()+0x2e0 (libjvm.dylib:arm64+0x7374b4)
    #13 0x1084cfa20 in JavaThread::thread_main_inner()+0xa0 (libjvm.dylib:arm64+0x196fa20)
    #14 0x1084cf830 in JavaThread::run()+0x15c (libjvm.dylib:arm64+0x196f830)
    #15 0x1084cbdf8 in Thread::call_run()+0xb0 (libjvm.dylib:arm64+0x196bdf8)
    #16 0x1080ca9a8 in thread_native_entry(Thread*)+0x178 (libjvm.dylib:arm64+0x156a9a8)
    #17 0x1880eb2e0 in _pthread_start+0x84 (libsystem_pthread.dylib:arm64e+0x72e0)
    #18 0x1880e60f8 in thread_start+0x4 (libsystem_pthread.dylib:arm64e+0x20f8)
```

Though the exact stack trace differs between runs. Maybe deparallelizing will help.

**Comment by cho-m** [comment]
Looks like LLVM 19 throws errors on some UB:
```
  /private/tmp/openjdkA11-20240928-11194-2ss9s6/jdk11u-jdk-11.0.24-ga/src/jdk.pack/share/native/common-unpack/constants.h:206:33: error: expression is not an integral constant expression
    206 |     AO_UNUSED_MBZ             = (-1)<<13, // options bits reserved for future use.
        |                                 ^~~~~~~~
```

Can try https://github.com/openjdk/jdk/commit/51be7db96f3fc32a7ddb24f8af19fb4fc0577aaf

**Comment by cho-m** [comment]
Haven't seen any failures after a number of attempts. Maybe 2nd UB fix helped or low chances of hitting

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
15-arm64 bottle dispatched

**Pull request merged**
