### PR TITLE
zsh-yarn-autocompletions 1.0.0 (new formula)

### PR DESCRIPTION
**Pull request by g-plane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
This is my first time to publish a package, so any advice is welcomed.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> yarn-autocompletions add
Error: zsh-yarn-autocompletions: failed
No such file or directory - yarn-autocompletions
```

**Comment by DomT4** [comment]
Should probably be building this from source.

**Comment by fxcoudert** [comment]
Oh yes, I didn't see that it was binary (because it is rare for completion stuff).
We'll need a formula that builds from source, @g-plane: https://docs.brew.sh/Acceptable-Formulae.html

**Comment by DomT4** [comment]
Aye, I only picked up on it from the URL name making me slightly suspicious. Definitely not something I’ve seen often for completions.

**Pull request closed without merging**
