### PR TITLE
elm-format 0.8.5

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
==> cabal v2-install --jobs=6 --max-backjumps=100000 --install-method=copy --installdir=/usr/local/Cellar/elm-format/0.8.5/bin
cabal: Cannot find the program 'ghc'. User-specified path 'ghc-8.10.4' does
not refer to an executable and the program is not on the system path.
```

**Comment by chenrui333** [comment]
```
==> cabal v2-install --jobs=6 --max-backjumps=100000 --install-method=copy --installdir=/usr/local/Cellar/elm-format/0.8.5/bin
cabal: Cannot find the program 'ghc'. User-specified path 'ghc-8.10.4' does
not refer to an executable and the program is not on the system path.
```

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/pull/70591

**Comment by chenrui333** [comment]
revisit after ghc merge

**Comment by carlocab** [comment]
```
cabal: Failed to unpack avh4-lib-0.0.0.1 (which is required by exe:elm-format
from elm-format-0.8.5). The exception was:
Invalid file name in tar archive: "avh4-lib-0.0.0.1/../"
```

**Pull request closed without merging**
