### PR TITLE
mpv 0.29.1

### PR DESCRIPTION
**Pull request by slokhorst**
Includes fixes for macOS Mojave issues.

Again compatible with Python 3, so reverted commit b314a662626e0a7fd61fb8f2a5e12fbbb04651e6.

### CODE REVIEW

**Comment by fxcoudert** [comment]
`mps-youtube` is failing:

```
WARNING: Unknown codec av01.0.05M.08
WARNING: Unknown codec av01.0.05M.08
WARNING: Unknown codec av01.0.05M.08
WARNING: Unknown codec av01.0.05M.08
WARNING: Unknown codec av01.0.05M.08
WARNING: Unknown codec av01.0.05M.08
WARNING: Unknown codec av01.0.05M.08
WARNING: Unknown codec av01.0.05M.08
```

**Comment by bgeet** [comment]
Should use python3 everywhere and remove python2 cruft as done in:
https://github.com/Homebrew/homebrew-core/pull/30369

**Comment by slokhorst** [comment]
@bgeet thanks, fixed.

@fxcoudert I think this is an issue with mps-youtube, not mpv. `brew test mps-youtube` fails even when I have mpv 0.28.2 installed.

**Comment by bgeet** [comment]
@slokhorst thanks

Also noticed that the old pull-request #30369 had updated docutils to 1.4, which is the latest release.
Would do the same here.

**Comment by fxcoudert** [comment]
`mps-youtube` failure is preexisting. Merging

**Pull request closed without merging**
