### PR TITLE
python{,-tk}@3.10 3.10.6

### PR DESCRIPTION
**Pull request by triallax**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

I bumped `pip` arbitrarily to the latest version, please tell me if I shouldn't do that.

### CODE REVIEW

**Comment by bayandin** [comment]
> I bumped pip arbitrarily to the latest version, please tell me if I shouldn't do that.

Thanks, that is exactly what we want!

**Comment by cho-m** [comment]
I have a feeling `vim` is going to fail on Linux like last few version/revision bumps and will need a revision bump.

`protobuf@3` test should be fixed in #107312

`chapel` has been failing in multiple PRs but haven't looked into reason.

May want to also check on `ykdl`. Could be network issue or outdated test URL, but should make sure (or at least confirm it occurs on other PRs or locally to know it is unrelated to PR).

**Comment by branchvincent** [comment]
`ykdl` is unrelated (confirmed locally on master), the translated response is 

> Sorry, this video cannot be viewed due to copyright reasons

**Comment by cho-m** [comment]
`vim` needs a revision bump for Linux failure.

---

Everything else:
- `chapel` should be fixed in #107405.
- `gdb` should be fixed in #107389
- `llvm@13` can be ignored as caused by GCC 12 update. Working on fix in #107018
- `streamlink` can be ignored. Don't know cause but has happened for a while on self-hosted Linux but hard to reproduce.

**Review by carlocab — APPROVED** [review]
Linux failures are unrelated.

**Pull request closed without merging**
