### PR TITLE
llvm 4.0.1

### PR DESCRIPTION
**Pull request by rillian**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by rillian** [comment]
I removed the `revision` key from the Formula, since `brew audit --strict` complained about it. It also complains
```
llvm:
  * Dependency graphviz should not use option dot
```
but I don't understand what the correct for that would be, other than just removing graphviz.

**Comment by rillian** [comment]
I think the jenkins failures are from the audit, so I removed the optional graphviz dependency and updated to https urls where possible.

**Comment by ilovezfs** [comment]
>but I don't understand what the correct fix for that would be, other than just removing graphviz.

It's a false positive. Moving the comment to be above that line should avoid the failure.

**Comment by ilovezfs** [comment]
Thanks for the PR @rillian! :tada:

**Pull request closed without merging**
