### PR TITLE
Add 32-bit ELF cross compilers (and improve x86_64 ones)

### PR DESCRIPTION
**Pull request by roolebo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

The PR improves cross-compiler support on macOS by providing dedicated `i686-elf-` toolchain targeting 32-bit Intel CPUs.

Packaging of `x86_64-elf-binutils` and `x86_64-elf-gcc` was reworked to support installation of the second toolchain. Build options were pruned to carry only required options going forward.

### CODE REVIEW

**Comment by Bo98** [comment]
> No, i686-elf-gcc fails with the message

Passing `SED=/usr/bin/sed` to `configure` may fix that, like we already do with the main GCC formula.

**Comment by roolebo** [comment]
@Bo98 thanks! I will look into that.

**Comment by roolebo** [comment]
I'll replace pruning of locale directory `(share/"locale").rmtree` in the packages with `--disable-nls` option for `./configure`. It looks more sane.

**Comment by roolebo** [comment]
@Bo98 Do I need anything else for the PR?

**Review by jonchang — APPROVED** [review]

**Pull request closed without merging**
