### PR TITLE
rustup-init 1.5.0

### PR DESCRIPTION
**Pull request by alex**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
@alex 1.4.0 has been posted for a while, but I've not opened a PR for it because 1.3.0 is still marked as the latest release (https://github.com/rust-lang-nursery/rustup.rs/releases/latest), a situation which doesn't appear to have changed. Maybe they're forgetting to hit the publish button on GitHub?

**Comment by alex** [comment]
I think they're just not using the github UI for releases. The release was announced on the mailing list: https://users.rust-lang.org/t/rustup-1-5-0-released/11529

**Comment by ilovezfs** [comment]
Do you mind opening an issue about this?

**Comment by ilovezfs** [comment]
:bowing_man:

**Comment by ilovezfs** [comment]
Thanks @alex! :ship: :package:

**Pull request closed without merging**
