### PR TITLE
t-completion: update sha

### PR DESCRIPTION
**Pull request by chenrui333**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
close for now, will reopen once got confirmation from the upstream (I did also email them)

**Comment by sferik** [comment]
Sorry for the delay. I don't recall re-tagging this release, but I suppose it's possible, since it was (exactly) one year ago. Would it be safer for me to tag and release a new version (4.0.1) instead?

**Comment by sferik** [comment]
Okay, I just tagged and released version 4.1.1.

**Comment by chenrui333** [comment]
@sferik no worries, thanks for the new tag (but I also saw the master builds all failed :) )

**Comment by sferik** [comment]
There's an issue with the CI at the moment but the tests are passing when I run them locally.

**Pull request closed without merging**
