### PR TITLE
manticoresearch 3.5.0

### PR DESCRIPTION
**Pull request by adriannuta**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by SeekingMeaning — COMMENTED** [review]
Please squash commits

**Comment by SMillerDev** [comment]
Did manticore move away from github?

**Comment by adriannuta** [comment]
> Did manticore move away from github?

No, I suspect you ask because of `head` removal. I added it back.

**Comment by SMillerDev** [comment]
> No, I suspect you ask because of `head` removal. I added it back.

And also the different download url. Which one is the official way to download the source?

**Comment by SeekingMeaning** [comment]
> Which one is the official way to download the source?

https://github.com/manticoresoftware/manticoresearch/releases/tag/3.5.0

links to https://manticoresearch.com/downloads/

which links to https://repo.manticoresearch.com/repository/manticoresearch_source/release/manticore-3.5.0-200722-1d34c49-release-source.tar.gz

**Review by SMillerDev — APPROVED** [review]
Thanks @adriannuta  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Comment by adriannuta** [comment]
> And also the different download url. Which one is the official way to download the source?

Both github and our hosted is ok. The hosted tarball is made from `make tarball` - it just adds revision info in a file, but we're switch this to be available in git tarball as well, next release I'll switch to use github tarball. Sorry for the confusion.

**Pull request closed without merging**
