### PR TITLE
meson: Apply patch to fix regression in 0.49.0

### PR DESCRIPTION
**Pull request by z3ntu**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

See https://github.com/mesonbuild/meson/pull/4652 (for issue https://github.com/mesonbuild/meson/issues/4641)

### CODE REVIEW

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
Thanks @z3ntu for the pull request!

**Comment by z3ntu** [comment]
Now `brew install meson --HEAD` is broken ^^ Looking at the [homebrew documentation](https://docs.brew.sh/Formula-Cookbook#patches), the patch block should probably be wrapped in a `stable do` .. `end` block

**Comment by fxcoudert** [comment]
A follow-up PR scoping the patch in a stable block would be appreciated :)

**Comment by z3ntu** [comment]
Opened #35587

**Pull request closed without merging**
