### PR TITLE
libgit2 1.2.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by branchvincent** [comment]
```
  #error You need a compatible libgit2 version (1.1.x)
   ^
  1 error generated.
  error: command '/opt/homebrew/Library/Homebrew/shims/mac/super/clang' failed with exit code 1
  Building wheel for pygit2 (PEP 517): finished with status 'error'
  ERROR: Failed building wheel for pygit2
Failed to build pygit2
```

**Comment by chenrui333** [comment]
requires a libgit2 patch for pygit2 before proceeding further

**Comment by alok** [comment]
i thought libgit2 stopped using `master` and switched to `main`. should this be updated for that?

**Comment by chenrui333** [comment]
> i thought libgit2 stopped using `master` and switched to `main`. should this be updated for that?

@alok, it can be addressed separately.

**Comment by jeroen** [comment]
Don't give up yet, almost there 💪 
```
Error: 3 failed steps!
brew install --verbose --build-bottle dvc
brew install --verbose --build-bottle gitless
brew install --verbose --build-bottle literate-git
```

**Comment by carlocab** [comment]
Seeing the error for `cargo-outdated` in #85750 (https://github.com/Homebrew/homebrew-core/pull/85750/checks?check_run_id=3680683610#step:7:47). This makes me think the error is unrelated to the `libgit2` version bump.

**Comment by Bo98** [comment]
The new `cargo-edit` update bumps `libgit2-sys` to be 1.2.0-compatible. The `cargo-outdated` lockfile is on the 1.1.0-compatible version. I suspect this is why you're seeing issues.

**Review by carlocab — APPROVED** [review]
That took a bit. Let's ship this before we get bitten by merge conflicts...

**Pull request closed without merging**
