### PR TITLE
various formulae: replace compound `unless` with `if`

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is part of https://github.com/Homebrew/brew/pull/10256, which adds a rubocop that disallows `unless` statements with multiple conditions

Truth table for reference:

<table class="truthTable">
<tr class="header">
<th class="variable">p</th>
<th class="variable">q</th>
<th class="expression">!(p && q)</th>
<th class="expression">!p || !q</th>
<th class="expression">!(p || q)</th>
<th class="expression">!p && !q</th>
</tr>
<tr>
<td>F</td><td>F</td><td>T</td><td>T</td><td>T</td><td>T</td>
</tr>
<tr>
<td>F</td><td>T</td><td>T</td><td>T</td><td>F</td><td>F</td>
</tr>
<tr>
<td>T</td><td>F</td><td>T</td><td>T</td><td>F</td><td>F</td>
</tr>
<tr>
<td>T</td><td>T</td><td>F</td><td>F</td><td>F</td><td>F</td>
</tr>
</table>

### CODE REVIEW

**Comment by carlocab** [comment]
I don't mind getting rid of `unless`s, but simultaneously making the substitution

   !(p && q) => (!p) || (!q)

is, I think, a regression for readability. I'd prefer you just stuck with the `!(p && q)` form. Or does rubocop complain about those too?

**Comment by SeekingMeaning** [comment]
Yes, it doesn't like `if !condition`

**Comment by SeekingMeaning** [comment]
An alternative is to create a variable and then do `unless variable`

**Comment by carlocab** [comment]
Nah, that's annoying too. Your changes are fine then.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
