### PR TITLE
gdb 8.2.1

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by igas** [comment]
```
aarch64-linux-tdep.c:327:7: error: no matching function for call to 'store_integer'
      store_integer ((gdb_byte *)&vg_target, sizeof (uint64_t), byte_order,
      ^~~~~~~~~~~~~
./defs.h:553:13: note: candidate template ignored: requirement 'Or<is_same<unsigned long long, long>, is_same<unsigned long long, unsigned long> >::value' was not satisfied [with T = unsigned long long]
extern void store_integer (gdb_byte *addr, int len, enum bfd_endian byte_order,
            ^
1 error generated.
make[2]: *** [aarch64-linux-tdep.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-gdb] Error 2
make: *** [all] Error 2
```

**Comment by timotheecour** [comment]
@fxcoudert @Moisan this gdb fails ; it's the old bug https://github.com/Homebrew/homebrew-core/issues/34750 again that crashes with:
```
[New Thread 0x1003 of process 63839]
[New Thread 0xf03 of process 63839]
```

the only thing that's worked on OSX so far is https://github.com/Homebrew/homebrew-core/pull/35006 from @roolebo but that PR wasn't merged, why?

**Comment by kemlath** [comment]
On a freshly installed Mojave with Xcode 10

Taking gdb.rb from https://raw.githubusercontent.com/Homebrew/homebrew-core/311be07ab50b75b55cf4462ea9b8d7acf955f968/Formula/gdb.rb

Tried "brew install gdb.rb --HEAD" 

Fails to build with:

CXX    c-varobj.o
In file included from c-exp.y:38:
In file included from ./defs.h:670:
In file included from ./utils.h:24:
In file included from ./exceptions.h:23:
./ui-out.h:80:3: error: expected identifier
  VARIABLE,
  ^
c-exp.c:176:18: note: expanded from macro 'VARIABLE'
#define VARIABLE 299
                 ^
1 error generated.
make[2]: *** [c-exp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-gdb] Error 2
make: *** [all] Error 2

**Comment by timotheecour** [comment]
@kemlath can you please open a new issue? (since unfortunately this can't be reopened); otherwise it'll never be fixed, and we're back to square one with no way to get gdb working on OSX

**Comment by kemlath** [comment]
I finally got a working gdb version under Mojave. No more need for sudo or password entry to debug your code.
What I'm describing here is not a home-brew solution but a working gdb under Mojave none the  less.
If like me you'r hard pressed to have  gdb under Mojave this should be of help.

It seems that the most current version rom today 5.1.2019 of gdb fixes things. There are still some minor compile issues and intricacies with regard to signing it under Mojave (entitlements and such) but all this is explained in great detail below.

1.) Download ftp://sourceware.org/pub/gdb/snapshots/current/gdb-8.2.50.20190105.tar.xz

2.) Build using GCC-8 and G++-8 NOT CLANG:
CC=gcc-8 CXX=g++-8 ./configure --prefix=/usr/local/opt/gdb/ --disable-debug --disable-dependency-tracking --enable-targets=all --with-python=/usr

3.) Codesign it with the right! entitlements (assuming gdb_cert is a valid code sig):

codesign --entitlements gdb.xml -fs gdb_cert /usr/local/opt/gdb/bin/gdb

Important "gdb_cert" has to be a valid code signing cert from the SYSTEM keychain (login keychain won't do)

The entitlements in gdb.xml look like:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.cs.disable-executable-page-protection</key>
    <true/>
    <key>com.apple.security.cs.debugger</key>
    <true/>


    <key>com.apple.security.get-task-allow</key>
    <true/>


</dict>
</plist>

Not sure if all of them are needed...
I stumbled upon the need for entitlement "com.apple.security.cs.debugger" while googling
and ended up adding putting all of them in there in my despair.

You can check the entitlements via

codesign -d --entitlements - /usr/local/opt/gdb/bin/gdb

3.) Maybe optionally call (didn't help with gdb 8.2.1 form homebrew)

DevToolsSecurity -enable

4.) Maybe optionally call (didn't help on Mojave with gdb 8.2.1 form homebrew but was nescessary under el Capitan)

sudo dseditgroup -o edit -a <your user name> -t user procmod
Which adds you to group procmod.
It's just because only users in procmod can use function task_for_pid

5.) Enjoy ;)

Caveats:

The compile initially fails because of some problems in gb/darwin-nat.c
(some variables are double defined and that make gcc fail)

Patch darwin-nat.c as below to get rid of some compiler errors

--- ./gdb-8.2.50_working/gdb/darwin-nat.c	2019-01-05 19:51:48.000000000 +0100
+++ ./gdb-8.2.50.20190105/gdb/darwin-nat.c	2019-01-05 02:49:08.000000000 +0100
@@ -687,7 +687,7 @@
       /* Not a known inferior.  This could happen if the child fork, as
 	 the created process will inherit its exception port.
 	 FIXME: should the exception port be restored ?  */
-      // kern_return_t kret;
+      kern_return_t kret;
       mig_reply_error_t reply;

       inferior_debug
@@ -1125,14 +1125,14 @@

 	  if (!priv->no_ptrace)
 	    {
-	      pid_t pid_res;
+	      pid_t res;
 	      int wstatus;

-	      pid_res = wait4 (inf->pid, &wstatus, 0, NULL);
-	      if (pid_res < 0 || pid_res != inf->pid)
+	      res = wait4 (inf->pid, &wstatus, 0, NULL);
+	      if (res < 0 || res != inf->pid)
 		{
 		  printf_unfiltered (_("wait4: res=%d: %s\n"),
-				     pid_res, safe_strerror (errno));
+				     res, safe_strerror (errno));
 		  status->kind = TARGET_WAITKIND_IGNORE;
 		  return minus_one_ptid;
 		}
@@ -1148,7 +1148,7 @@
 		}

 	      inferior_debug (4, _("darwin_wait: pid=%d exit, status=0x%x\n"),
-			      pid_res, wstatus);
+			      res, wstatus);

 	      /* Looks necessary on Leopard and harmless...  */
 	      wait4 (inf->pid, &wstatus, 0, NULL);
@@ -1559,7 +1559,7 @@
          signaled thus darwin_decode_message function knows that the kill
          signal was sent by gdb and will take the appropriate action
          (cancel signal and reply to the signal message).  */
-      priv = get_darwin_inferior (inf);
+      darwin_inferior *priv = get_darwin_inferior (inf);
       for (darwin_thread_t *thread : priv->threads)
         thread->signaled = 1;

**Comment by kemlath** [comment]
Sorry the above comment lost the formatting 

This is what the entitlements xml file must look like

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.cs.disable-executable-page-protection</key>
    <true/>
    <key>com.apple.security.cs.debugger</key>
    <true/>
    <key>com.apple.security.get-task-allow</key>
    <true/>
</dict>
</plist>
```

Heres the diff for  darwin-nat.c

```
--- ./gdb-8.2.50_working/gdb/darwin-nat.c	2019-01-05 19:51:48.000000000 +0100
+++ ./gdb-8.2.50.20190105/gdb/darwin-nat.c	2019-01-05 02:49:08.000000000 +0100
@@ -687,7 +687,7 @@
       /* Not a known inferior.  This could happen if the child fork, as
 	 the created process will inherit its exception port.
 	 FIXME: should the exception port be restored ?  */
-      // kern_return_t kret;
+      kern_return_t kret;
       mig_reply_error_t reply;

       inferior_debug
@@ -1125,14 +1125,14 @@

 	  if (!priv->no_ptrace)
 	    {
-	      pid_t pid_res;
+	      pid_t res;
 	      int wstatus;

-	      pid_res = wait4 (inf->pid, &wstatus, 0, NULL);
-	      if (pid_res < 0 || pid_res != inf->pid)
+	      res = wait4 (inf->pid, &wstatus, 0, NULL);
+	      if (res < 0 || res != inf->pid)
 		{
 		  printf_unfiltered (_("wait4: res=%d: %s\n"),
-				     pid_res, safe_strerror (errno));
+				     res, safe_strerror (errno));
 		  status->kind = TARGET_WAITKIND_IGNORE;
 		  return minus_one_ptid;
 		}
@@ -1148,7 +1148,7 @@
 		}

 	      inferior_debug (4, _("darwin_wait: pid=%d exit, status=0x%x\n"),
-			      pid_res, wstatus);
+			      res, wstatus);

 	      /* Looks necessary on Leopard and harmless...  */
 	      wait4 (inf->pid, &wstatus, 0, NULL);
@@ -1559,7 +1559,7 @@
          signaled thus darwin_decode_message function knows that the kill
          signal was sent by gdb and will take the appropriate action
          (cancel signal and reply to the signal message).  */
-      priv = get_darwin_inferior (inf);
+      darwin_inferior *priv = get_darwin_inferior (inf);
       for (darwin_thread_t *thread : priv->threads)
         thread->signaled = 1;
```

**Comment by timotheecour** [comment]
@kemlath  thanks a lot for writing this up ; any chance you could write it in a readme.md in some repo so others can send PR's against it ?

**Comment by kemlath** [comment]
Not sure how to place it in a repo  but I've created a gist

[https://gist.github.com/kemlath/7285356f97f67af5023cf99ee57317d6](url)

**Comment by kemlath** [comment]
After further testing gdb works what I would call intermittently 

It still sometimes (quite a few times actually) lock itself up.
A sample taken through the ActivityMonitor suggests it hangs at 

Call graph:
    2630 Thread_13783   DispatchQueue_1: com.apple.main-thread  (serial)
      2630 darwin_decode_message(mach_msg_header_t*, darwin_thread_info**, inferior**, target_waitstatus*) (.isra.93)  (in gdb) + 2258  [0x100113962]
        2630 __wait4_nocancel  (in libsystem_kernel.dylib) + 10  [0x7fff610125de]

**Comment by timotheecour** [comment]
I'm re-opening the bug https://sourceware.org/bugzilla/show_bug.cgi?id=23949 that was closed since gdb still seems unusable on OSX

**Comment by fxcoudert** [comment]
Support for building gdb HEAD is now added: https://github.com/Homebrew/homebrew-core/commit/fa7e2f143d2656e49700dcb4a63dd33fd52ceba3
I'm going to lock the conversation here, but I suggest the best place to actually fix these issues is upstream.

**Pull request closed without merging**
