### PR TITLE
pgpool-ii 4.4.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Porkepix** [comment]
If I read and understand https://docs.brew.sh/License-Guidelines correctly, a license such as https://pgpool.net/mediawiki/index.php/pgpool-II_License is a `license :cannot_represent`?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
> If I read and understand https://docs.brew.sh/License-Guidelines correctly, a license such as https://pgpool.net/mediawiki/index.php/pgpool-II_License is a `license :cannot_represent`?

you can also use [this tool](https://tools.spdx.org/app/check_license/) to help determine, if no matches found, you can file a [new license request](https://tools.spdx.org/app/submit_new_license/)

**Comment by chenrui333** [comment]
For the previous license effort, https://github.com/Homebrew/homebrew-core/pull/60057

**Comment by Porkepix** [comment]
@chenrui333 Yeah, but that one seems pretty custom, SPDX can't provide information for every custom license, right?
But `:cannot_represent` isn't a good answer here?

**Pull request closed without merging**
