### PR TITLE
osm2pgsql: handle multiple local Luas

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Fixes https://github.com/Homebrew/homebrew-core/pull/13977.

### CODE REVIEW

**Comment by JCount** [comment]
@DomT4 Nice job! 💯 I can independently confirm this does indeed fix building with multiple `lua` versions installed. I personally think this is G2G, but waiting for feedback from @ilovezfs probably is prudent. 😸

**Review by JCount — APPROVED** [review]

**Comment by ilovezfs** [comment]
Is it correct to say this patching would be unnecessary if we used `keg_only :versioned_formula` for the versioned luas?

**Comment by DomT4** [comment]
For _this specific project_ it seems likely.

More broadly because CMake gives so few craps about Homebrew trying to contain its behaviour who knows; it's really down to how wide the upstream `FindLua` file is. If they chose to target Homebrew specifically by checking various subdirectories of `/usr/local/opt` then we'd be completely powerless until the day where we find a _"tame CMake"_ mechanism.

**Comment by ilovezfs** [comment]
>If they chose to target Homebrew specifically by checking various subdirectories of /usr/local/opt then we'd be completely powerless

If they ever do that, I will eat my :tophat:

**Comment by ilovezfs** [comment]
This seems fine for now, though I'd say this is more confirmation that keg_only is the future of versioned lua formulae.

**Comment by ilovezfs** [comment]
Thanks @DomT4

**Comment by DomT4** [comment]
> If they ever do that, I will eat my 🎩

Nothing surprises me that much any more.

We tried to hide our OpenSSL away in multiple ways and you can still find more than 240k results for `/usr/local/opt/openssl` and another 7k for `brew --prefix openssl` on GitHub fairly easily, although obviously, not all those are compile-related.

I certainly agree it's unlikely, but my concern is that it's unlikely because not wanting to use the standard version of `lua` is a relatively unusual use-case,  rather than being unlikely because Homebrew has any power to stop it happening if pressure is applied to upstream projects by users.

**Pull request merged**
