### PR TITLE
newrelic-infra-agent: migrate to tap

### PR DESCRIPTION
**Pull request by brushknight**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Removing formula as we moved into our own tap. https://github.com/newrelic/homebrew-tap/blob/main/Formula/newrelic-infra-agent.rb

Not sure if should I check any of checkboxes.

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]

**Comment by bayandin** [comment]
Is there any problem with homebrew's package?
We don't remove formulaу from homebrew-core in favour of upstream taps; see https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#official-vendor-taps

**Comment by brushknight** [comment]
Current formula is compiling but not working due to go 1.17 issues with gopsutils. We would like to keep newrelic-infra-agent in our own brew tap to be able to react quickly to any issue that happens. MacOS is a new platform for us and with any change of go some things breaks. Once we will be confident enough in our code stability we will open a PR to homebrew-core again.

**Comment by SMillerDev** [comment]
Yeah, that's not how it works. It's open source, we package it, the only way to change that is to change the license to prohibit us from packaging it.

**Comment by brushknight** [comment]
Well, then we need to fix `go` version in the formula to `1.16` in other case it wont work.

**Comment by brushknight** [comment]
https://github.com/Homebrew/homebrew-core/pull/84487

**Comment by rubenruizdegauna** [comment]
Hi @SMillerDev, we understand how open source works, and you are right, we cannot forbid you packaging it. But that's not the point. 
The point is to package something that would work and would give value to the users, and we would love that. But right now taking into account the nature of the infra-agent this is not possible without a huge amount of time/work. That's why we prefer to deliver it for now using our own tap where we have less restrictions and we can deliver a working product. Once the agent is ready, we would be more than happy to add it to the official repo again :)

**Comment by brushknight** [comment]
closing as https://github.com/Homebrew/homebrew-core/pull/84487 got merged 🎉

**Pull request closed without merging**
