### PR TITLE
ffmpeg 4.1.3

### PR DESCRIPTION
**Pull request by ykursadkaya**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
High Sierra node is headless again:

```
Error: mps-youtube: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: Some warnings were raised.
<"_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.\n_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.\n_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.\n_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.\n"> expected to be empty.
```

**Comment by ykursadkaya** [comment]
I have no clue about this error but I found this on Stackoverflow:
[https://stackoverflow.com/questions/13966595/build-unity-project-with-jenkins-failed/15202453#15202453](https://stackoverflow.com/questions/13966595/build-unity-project-with-jenkins-failed/15202453#15202453)

I don't know if it's relevant or anything but another problem (not sure if it is the same) was solved in here with the exact same error in Unity and Jenkins

@fxcoudert 

#38584

**Comment by ykursadkaya** [comment]
It seems like mps-youtube error is fixed on High Sierra #38732

**Comment by retokromer** [comment]
What is the status of this? (The amended formula works fine on my end.)

**Comment by zbeekman** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
