### PR TITLE
tests: test on Ubuntu 18.04.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
This will need some fixes before it can be merged.

Currently it's just always skipping dependents. Perhaps we want to skip even more than this?

CC @carlocab @Bo98 @danielnachun @sjackman @iMichka for thoughts/help

Feel free to push to this PR!

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> I think what we should be testing is whether the Linux bottle we just built works on `ubuntu-18.04`, instead of building from source (as that may mask some Homebrew `glibc` weirdness).

@carlocab hmm, so a build that only runs when the whole matrix has completed based on downloading the 22.04 Linux build?

That'd be quite a change from what we have today, not sure how we'd do it 🤔

**Comment by carlocab** [comment]
Well, the "easy" way of doing it is with a workflow that runs on every push to `master` that just does `brew install && brew test`.

Of course, this then makes it really easy to ignore failures, but at least we'd know about what's broken and try to fix it after if desired.

We could maybe get @BrewTestBot to post a comment somewhere for failures too.

**Comment by MikeMcQuaid** [comment]
> Well, the "easy" way of doing it is with a workflow that runs on every push to `master` that just does `brew install && brew test`.

@carlocab Yeh, I was thinking of something like this. Good idea! Nice to have on macOS too or not bother?

**Comment by danielnachun** [comment]
Agreed with the comments so far about wanting to just test the bottle in 18.04 rather than trying to build from source there.  And the idea of doing this after pushing to master sounds great too - I think we already do a syntax check when we do this?  It would be logical to follow that with a quick install and test check, which would post a comment in the PR that is being merged indicating that it has failed.

Would it make the most sense for this to happen in the publish and commit and dispatch build bottle workflow?  We don't need to test this when we make syntax-only changes (either with `CI-syntax-only` or with `CI-no-bottles`).  We only need to test it when we are actually pushing new bottles.

**Comment by MikeMcQuaid** [comment]
> And the idea of doing this after pushing to master sounds great too - I think we already do a syntax check when we do this?

Yeh, we do.

> It would be logical to follow that with a quick install and test check, which would post a comment in the PR that is being merged indicating that it has failed.

Not sure it'll be easy to detect the PR but that would be ideal.

> Would it make the most sense for this to happen in the publish and commit and dispatch build bottle workflow?

No, I don't think so. We don't want that to fail.

I still think the ideal case would be to block bad PRs going out but we don't really have a solution to this yet.

@danielnachun would you be able to pick up the work on this `master` job? `brew test-bot` should be able to detect the changes based on GitHub Actions variables on a push and then we can run a reduced subset of tests there.

**Comment by MikeMcQuaid** [comment]
Still debating how best to handle this between:
1. a post-merge `master` job
2. a job in one of our existing workflows that uses the artifacts from existing jobs after they have completed

the temptation to do 2) is that we eventually want to do this to be able to cache more results between repeated rebuilds

**Comment by MikeMcQuaid** [comment]
Passing on this. It doesn't seem to be a high priority for anyone.

**Pull request closed without merging**
