### PR TITLE
infer 0.9.4 update

### PR DESCRIPTION
**Pull request by akotulski**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Update `sha256` of infer tarball after hotfixing it

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Did the tag change or just the macOS tarball?

**Comment by akotulski** [comment]
I changed tarball
I moved the tag to different hash (with hotfix)
I kept the name of the tag (via `git push --force`)

**Comment by MikeMcQuaid** [comment]
Anyone who has `git fetch --tags` the existing tag will not be updated to the new one. Git doesn't update local tags which have changed because tags are intended to be static. For Homebrew, this will break the checksum for anyone who used the previous tag. As a result, would you consider either in this case or in future releasing a new version instead of repackaging an existing one? Thanks.

**Comment by akotulski** [comment]
I don't fully understand how brew is using tags when deciding whether to update.
Is it only matter of tag names, or do I have to create new release on github as well?
I could create 0.9.4.1 tag (instead of reusing 0.9.4) in our repo if that helps.

**Comment by MikeMcQuaid** [comment]
> I don't fully understand how brew is using tags when deciding whether to update.

We download the `infer-osx-v0.9.4.tar.xz` file and cache it and at installation time verify that the file matches the checksum.

> I could create 0.9.4.1 tag (instead of reusing 0.9.4) in our repo if that helps.

I think that would be better for the users of your GitHub repository. For Homebrew ideally the old tarball would stay with the old checksum and we could have a 0.9.4.1 tarball with the new checksum/contents and upgrade to that instead.

**Comment by akotulski** [comment]
ok, does it summarize what you are suggesting?
1. create new git tag (not strictly required by brew)
2. create new github release linked to the tag (not strictly required by brew)
3. have different URL to the tarball (brew will get confused if URL stays the same)

**Comment by MikeMcQuaid** [comment]
@akotulski Yep!

**Pull request closed without merging**
