### PR TITLE
arduino-cli 0.14.0

### PR DESCRIPTION
**Pull request by chenrui333**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by silvanocerza** [comment]
@chenrui333 thanks! Was about to create a PR too. :)

**Comment by chenrui333** [comment]
@silvanocerza, while I have you in here, can you confirm the license or test changes (looks like alpha got introduced) are right? Thanks!

**Comment by silvanocerza** [comment]
I confirm we added `alpha` in the version. Not sure what you mean about the license though, it has not been changed since Aug 7, 2018. :thinking:

**Comment by chenrui333** [comment]
yeah, that is fine. I did a bunch of license PRs, that license header looks like GPL-3.0-only in the new license list.
You can checkout more info in here, https://spdx.org/licenses/GPL-3.0-only.html

**Comment by silvanocerza** [comment]
Oh ok, didn't know about that. Thanks for taking care of this!

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
