### PR TITLE
syncthing 1.3.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by alebcay** [comment]
```
==> /usr/local/Cellar/syncthing/1.3.1/bin/syncthing -generate ./
/usr/local/Cellar/syncthing/1.3.1/bin/syncthing: /usr/local/Cellar/syncthing/1.3.1/bin/syncthing: cannot execute binary file
Error: syncthing: failed
```

Failure on Catalina only.

**Comment by Kriechi** [comment]
Is there any update on this?
Is it a test error in syncthing itself? I haven't found any reports for Catalina and syncthing...

**Comment by chenrui333** [comment]
@BrewTestBot test this please

**Comment by chenrui333** [comment]
@Kriechi, I think this is ready to merge, I will rebuild the bottles and merge from there.

**Pull request closed without merging**
