### PR TITLE
halide: migrate `jpeg` to `jpeg-turbo` and add head

### PR DESCRIPTION
**Pull request by cho-m**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
No `libpng` & `jpeg-turbo` linkage. Probably worth checking how these dependencies are used.

**Comment by carlocab** [comment]
It's in their `dependencies` directory: https://github.com/halide/Halide/tree/main/dependencies

**Comment by cho-m** [comment]
Still need to look further, but I think build step only uses them for tutorials/etc that aren't installed.

JPEG/PNG are picked up by the installed CMake files if available, so it may be useful when someone is building their own Halide project.

However, this does mean it may be better to wait on this PR as `jpeg-turbo` will not be detected by `cmake` without adding paths due to keg-only status. May want to see if worth swapping to `jpeg-turbo` as linked formula once more formulae are migrated.

**Comment by carlocab** [comment]
Fine with swapping after migration.

**Review by branchv — APPROVED** [review]

**Pull request closed without merging**
