### PR TITLE
[wip] kubeless 0.4.0

### PR DESCRIPTION
**Pull request by ngtuna**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ngtuna** [comment]
cc @ilovezfs. Not sure what's wrong with the last validation. I ran `brew install --build-from-source kubeless` successfully and v0.4.0 was installed. However, the next validation returned error:

Full log below:

```
$ brew install --build-from-source Formula/kubeless.rb 
Updating Homebrew...
==> Cloning https://github.com/kubeless/kubeless.git
Cloning into '/Users/tuna/Library/Caches/Homebrew/kubeless--git'...
remote: Counting objects: 7789, done.
remote: Compressing objects: 100% (5613/5613), done.
remote: Total 7789 (delta 2167), reused 5850 (delta 1782), pack-reused 0
Receiving objects: 100% (7789/7789), 15.91 MiB | 2.29 MiB/s, done.
Resolving deltas: 100% (2167/2167), done.
Note: checking out '4f4f531f6a1b685bf3842b26cfff5ca7eee533cc'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

==> Checking out tag v0.4.0
==> go build -o /usr/local/Cellar/kubeless/0.4.0/bin/kubeless -ldflags -w -X github.com/kubeless/kubeless/cmd/kubeless/version.VERSION=v0.4.
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/kubeless
Target /usr/local/bin/kubeless
already exists. You may want to remove it:
  rm '/usr/local/bin/kubeless'

To force the link and overwrite all conflicting files:
  brew link --overwrite kubeless

To list all files that would be deleted:
  brew link --overwrite --dry-run kubeless

Possible conflicting files are:
/usr/local/bin/kubeless
==> Summary
🍺  /usr/local/Cellar/kubeless/0.4.0: 5 files, 23.3MB, built in 43 seconds

$ /usr/local/Cellar/kubeless/0.4.0/bin/kubeless version
Kubeless version: v0.4.0 (4f4f531)

$ brew link --overwrite kubeless
Linking /usr/local/Cellar/kubeless/0.4.0... 1 symlinks created

$ brew audit --strict kubeless
==> Installing or updating 'rubocop' gem
Fetching: parallel-1.12.1.gem (100%)
Successfully installed parallel-1.12.1
Fetching: ast-2.4.0.gem (100%)
Successfully installed ast-2.4.0
Fetching: parser-2.4.0.2.gem (100%)
Successfully installed parser-2.4.0.2
Fetching: powerpack-0.1.1.gem (100%)
Successfully installed powerpack-0.1.1
Fetching: rainbow-3.0.0.gem (100%)
Successfully installed rainbow-3.0.0
Fetching: ruby-progressbar-1.9.0.gem (100%)
Successfully installed ruby-progressbar-1.9.0
Fetching: unicode-display_width-1.3.0.gem (100%)
Successfully installed unicode-display_width-1.3.0
Fetching: rubocop-0.52.1.gem (100%)
Successfully installed rubocop-0.52.1
8 gems installed
kubeless:
  * stable version should not decrease (from 0.3.4 to 0.3.3)
Error: 1 problem in 1 formula
```

**Comment by fxcoudert** [comment]
The test is failing:

```
==> /usr/local/Cellar/kubeless/0.4.0/bin/kubeless function deploy --from-file test.py --runtime python2.7 --handler test.foo test
time="2018-02-14T17:14:01Z" level=fatal msg="Unable to read the configmap: couldn't get version/kind; json parse error: invalid character 'O' looking for beginning of value"
```

**Comment by ilovezfs** [comment]
I reported it upstream: https://github.com/kubeless/kubeless/issues/595

**Comment by ilovezfs** [comment]
`kubectl` is `Formula["kubernetes-cli"].opt_bin/"kubectl"` not `bin/"kubectl"`

**Comment by ngtuna** [comment]
@ilovezfs I was aware of that but I had to go out for couple of hours. I made the PR as wip. Will let you know once I can have time to fix it today.

**Comment by ilovezfs** [comment]
```
Testing kubeless
/usr/bin/sandbox-exec -f /tmp/homebrew20180217-98716-jqajjw.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubeless.rb --verbose
==> /usr/local/opt/kubernetes-cli/bin/kubectl create ns kubeless
error: couldn't get version/kind; json parse error: invalid character 'O' looking for beginning of value
Error: kubeless: failed
Failed executing: /usr/local/opt/kubernetes-cli/bin/kubectl create ns kubeless
```

**Comment by ngtuna** [comment]
I am seeing @andresmgot sent out #24303 to fix this. We should work on that PR and close this one.

**Pull request closed without merging**
