### PR TITLE
clojure 1.8.0.135, 1.9.0-alpha20.176 (devel)

### PR DESCRIPTION
**Pull request by puredanger**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
why the close?

**Comment by puredanger** [comment]
I guess I didn't need to close. wrong version #s though.

**Comment by ilovezfs** [comment]
you can force push to this one if you want :)

**Comment by ilovezfs** [comment]
Ah I see you opened https://github.com/Homebrew/homebrew-core/pull/18445. That's fine.

**Pull request closed without merging**
