### PR TITLE
dcd 0.15.0

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
linux build failure

```
  /usr/bin/ld: bin/dcd-client.o: relocation R_X86_64_32 against symbol `__dmd_personality_v0' can not be used when making a PIE object; recompile with -fPIE
  /usr/bin/ld: failed to set dynamic section sizes: bad value
```

**Comment by chenrui333** [comment]
rebased after #118296

**Comment by chenrui333** [comment]
```
  /usr/bin/ld: bin/dcd-server.o: relocation R_X86_64_32 against symbol `__dmd_personality_v0' can not be used when making a PIE object; recompile with -fPIE

```

**Review by danielnachun — APPROVED** [review]
I pushed a fix for this - all it need was for `-fPIC` to be added to `DFLAGS`.  Unlike GCC, `dmd` does not have a way to do this automatically, but we don't have many D formulae so this isn't hard to add when needed.

**Pull request closed without merging**
