### PR TITLE
deno 1.12.0

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by SMillerDev** [comment]
the `gn` resource is now at a new commit: https://github.com/denoland/rusty_v8/tree/v0.25.3

**Comment by branchvincent** [comment]
> the `gn` resource is now at a new commit: https://github.com/denoland/rusty_v8/tree/v0.25.3

where do you see the new commit? i checked the previous location but it's no longer accurate: https://github.com/denoland/chromium_buildtools/blob/3655cd61062a8e8282d2d01df0a19aae410d336d/DEPS

**Comment by branchvincent** [comment]
ok so i found
* https://github.com/denoland/rusty_v8/blob/6a81d042a744c5e88046372bddd96d918d09cbee/tools/ninja_gn_binaries.py#L21
* https://github.com/denoland/ninja_gn_binaries/commit/f1f539701cd498e6f8c67b1a815fa001c9aaa223
* https://gn.googlesource.com/gn.git/+/53d92014bf94c3893886470a1c7c1289f8818db0

i can go ahead and push this change unless someone wants to double check me here

**Comment by carlocab** [comment]
> i can go ahead and push this change unless someone wants to double check me here

Go ahead, but please also update the comment to reflect the change in how to check for the right `gn` revision.

**Review by nandahkrishna — APPROVED** [review]
Thanks, @branchvincent!

**Pull request closed without merging**
