### PR TITLE
tintin 2.02.41

### PR DESCRIPTION
**Pull request by chiefmikey**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by p-linnane** [comment]
@chiefmikey Your base branch is out of date, which has introduced conflicts. You also have 10 PR's open right now, with 7 of them in a failed state. Please do not open any more PR's until you resolve the issues with your existing ones.

**Comment by p-linnane** [comment]
I see you've closed all your open PR's. This isn't what I meant with my comment. If you open a PR to bump a formula, you need to be prepared to at least attempt and fix any failures. Blindly bumping many formulae and leaving them in a failed state  is detrimental because anyone else who attempts to bump them will receive a warning about an existing closed PR. This may reduce community contributions. Please open PR's only for formulae you are willing to try and fix if they fail to build.

**Comment by chiefmikey** [comment]
@p-linnane I understand, sorry I wasn't trying to be dramatic I just wanted to clear up the PRs for now. Unfortunately life is  currently preventing me from having capacity for manual intervention so I will hold off on running my script until I'm available for that and will also implement a solution to prevent the outdated branches. Of course my goal is for these automated contributions to actually be beneficial so I'm open to any other feedback as well, or if its just not a useful thing I can work on other ways to contribute!

**Comment by p-linnane** [comment]
Thank you for your kindly worded response. We do have [an autobump workflow](https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/autobump.yml) that runs on a schedule. If you can identify projects that reliably update without manual intervention it would be appreciated if you could open PR's to add them to that workflow.

Your contributions are very appreciated. We have limited time as maintainers to triage and fix formulae at scale, hence my requests. I look forward to further contributions from you as time allows. Cheers!

**Comment by chiefmikey** [comment]
@p-linnane No problem! Totally understandable and thanks for your feedback. I will continue working in quality from your suggestions. I very much respect all of the maintainers here that have been working with my PRs at all hours on all days. Feel free to reach out and looking forward to continuing to work with you all!

**Pull request closed without merging**
