### PR TITLE
apache-spark: fix to use java 17

### PR DESCRIPTION
**Pull request by robsonpeixoto**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Referencies:
- https://spark.apache.org/docs/3.3.0/
- https://books.japila.pl/pyspark-internals/Setup/

### CODE REVIEW

**Comment by robsonpeixoto** [comment]
I need a help with it: https://github.com/Homebrew/homebrew-core/pull/106315/files#diff-bce855593d4d586a36dfa3283b1e56aed7084676ec421d5e945966901a716bdaR25
How can I do it?

**Comment by SMillerDev** [comment]
So does it not actually work? Or does upstream just suggest to use the LTS?

**Comment by robsonpeixoto** [comment]
Is a upstream suggestion:

> Spark runs on Java 8/11/17, Scala 2.12/2.13, Python 3.7+ and R 3.5+. Java 8 prior to version 8u201 support is deprecated as of Spark 3.2.0. For the Scala API, Spark 3.3.0 uses Scala 2.12. You will need to use a compatible Scala version (2.12.x).

References:
- https://spark.apache.org/docs/3.2.0/ => `Spark runs on Java 8/11 ...`
- https://spark.apache.org/docs/3.3.0/ => `Spark runs on Java 8/11/17 ...`

**Comment by SMillerDev** [comment]
Seeing how we only downgrade dependencies that are broken I don't think we want to merge this.

**Pull request closed without merging**
