### PR TITLE
logstash 8.0.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by cho-m** [comment]
ARM is not bottled, but it looks like the audit failure is now capable of failing PRs.

Linux is bottled, but failing in test:
```
  ==> Testing logstash
  ==> /home/linuxbrew/.linuxbrew/Cellar/logstash/8.0.1/bin/logstash -e '' --path.data=/tmp/logstash-test-20220306-20053-13dtxgp/data --path.logs=/tmp/logstash-test-20220306-20053-13dtxgp/logs --path.settings=/tmp/logstash-test-20220306-20053-13dtxgp/config --log.level=fatal
  Error: logstash: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected /hello\ world/ to match "Could not find java; set LS_JAVA_HOME or ensure java is in PATH.\n".
```

Looks like `logstash` no longer uses `JAVA_HOME` (https://github.com/elastic/logstash/commit/d51afe54d5a2150e63a2254a2b66d20a9d433222) and instead uses `LS_JAVA_HOME`.

**Comment by cho-m** [comment]
Monterey can be ignored since we don't have `openjdk@11` bottle yet. Upstream should provide support for `openjdk@17` in a future release (available in development HEAD).

ARM isn't bottled yet, but it did build on `11-arm64` even though audit failed. May be worth checking if support exists, or can just ignore for this PR.

**Comment by cho-m** [comment]
As note for future, ARM is failing because directories and some files are missing execute bit, so file type check fails on permissions.

Not important for current merge as ARM hasn't been bottled yet.

**Comment by chenrui333** [comment]
Thanks @cho-m!

**Pull request closed without merging**
