### PR TITLE
gstreamer family 1.18.3

### PR DESCRIPTION
**Pull request by tschoonj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
@tschoonj do you have an idea why the `gst-python` one doesn't work on ARM? https://github.com/Homebrew/homebrew-core/runs/1701046657?check_suite_focus=true

**Comment by tschoonj** [comment]
Probably because of this: 

```
 ** (process:17794): WARNING **: 05:03:55.910: Failed to load shared library 'libgstreamer-1.0.0.dylib' referenced by the typelib: dlopen(libgstreamer-1.0.0.dylib, 9): image not found
59
```

Was the gstreamer bottle pulled in before this test was run?

**Comment by fxcoudert** [comment]
Yeah it's there, I think the likely cause is it's not trying to find it outside `/usr/local`
Is there a way we can pass a path to meson?

**Comment by tschoonj** [comment]
The problem is `dlopen` itself: to make it work you would need to set `LD_LIBRARY_PATH`, `DYLD_LIBRARY_PATH` or `DYLD_FALLBACK_LIBRARY_PATH`.

Alternatively you could also regenerate all typelibs after ensuring the full path to the dylib is put into the corresponding gir file...

**Pull request closed without merging**
