### PR TITLE
poppler, poppler-qt5 22.04.0

### PR DESCRIPTION
**Pull request by yurikoles**
- poppler 22.04.0
- poppler-qt5 22.04.0

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by yurikoles** [comment]
Rebased and force-pushed to trigger a rebuilds.

**Comment by yurikoles** [comment]
```
No more than 2 PRs at a time may use "CI-long-timeout".
```

**Comment by yurikoles** [comment]
@chenrui333 it seems that you assigned a wrong label. `long build` is [a special case auto-assigned label for some formulas](https://github.com/Homebrew/homebrew-core/blob/ce9639a3e46908afe436f9339aba7ba9ff4d2fa8/.github/workflows/triage.yml#L137), that [needs a `CI-long-timeout` anyway](https://github.com/Homebrew/homebrew-core/blob/ce9639a3e46908afe436f9339aba7ba9ff4d2fa8/.github/workflows/tests.yml#L134).

**Comment by SMillerDev** [comment]
No, `long build` is just an indicator to maintainers that it needs the other label when it becomes available.

**Comment by yurikoles** [comment]
Reported https://github.com/jwilk/pdf2djvu/issues/153

**Comment by yurikoles** [comment]
We need a `CI-long-timeout` here.

**Comment by cho-m** [comment]
Please fix the commit history first. You can see the bot added `automerge-skip`, which is often a sign something is off.

Here, the issue is last merge commit. That should be dropped and the commits should be rebased instead

**Comment by yurikoles** [comment]
> Please fix the commit history first. You can see the bot added `automerge-skip`, which is often a sign something is off.
> 
> Here, the issue is last merge commit. That should be dropped and the commits should be rebased instead

Done, thank you for clarification.

**Review by fxcoudert — APPROVED** [review]

**Comment by yurikoles** [comment]
Whoops, merged before https://github.com/Homebrew/formula-patches/pull/858, `pdf2djvu` still uses patch from my fork. https://github.com/Homebrew/homebrew-core/blob/cb530cebe93f9bff2ce546e3e5602cf5a1f5a2fd/Formula/pdf2djvu.rb#L38-L40

**Comment by fxcoudert** [comment]
Sorry @yurikoles I've merged the patch, can you make a PR to adjust the formula? ping me on it, I'll review

**Pull request closed without merging**
