### PR TITLE
influxdb 1.4.0

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by spott** [comment]
There is no influxdb 1.4.0 out yet.  Why was this version bumped?

Here is the release page of influxdb: https://github.com/influxdata/influxdb/releases

And here is the download page from influxcloud: https://portal.influxdata.com/downloads

Neither mentions a 1.4.0 release...

**Comment by ilovezfs** [comment]
It means they published the tag and then deleted the tag. Please report it to upstream.

**Comment by spott** [comment]
To InfluxDB?

**Comment by ilovezfs** [comment]
Indeed.

**Comment by spott** [comment]
I’m sorry, I don’t understand. What am I supposed to tell them? To release
1.4.0 sooner?

**Comment by ilovezfs** [comment]
@spott see https://github.com/influxdata/influxdb/issues/9107

**Comment by ilovezfs** [comment]
@spott 1.4.1 is now released so you can `brew update` and it'll be fixed.

**Pull request closed without merging**
