### PR TITLE
ponyc 0.3.1

### PR DESCRIPTION
**Pull request by SeanTAllen**

### CODE REVIEW

**Comment by SeanTAllen** [comment]
closing as CI doesnt seem to be picking up my most recent change.

**Comment by DomT4** [comment]
It's interesting the proposed fix in https://github.com/Homebrew/homebrew-core/pull/4817#issuecomment-247191622 whilst producing a more complete failure also produced a more consistent failure, which makes me wonder if there is a situation going on where it's picking up bits from the `llvm` dependency & other bits from the system. Strange situation.

> closing as CI doesnt seem to be picking up my most recent change.

It can take a good 5 minutes sometimes to pick up on a new push. Try to give it a little more space.

**Comment by SeanTAllen** [comment]
@DomT4 will do on the waiting longer.

**Comment by SeanTAllen** [comment]
@DomT4 is there a way for me to say "you need at least clang X to build this. stdatomic.h is supposed to exist in clang 3.6 and later. unfortunately, jenkins truncates output for el capitan and yosemite so I can see what they have configured differently when they work vs mavericks which makes this pretty much impossible for me to diagnose. 

at this point i'm fairly frustrated. is it possible to not create a bottle for Mavericks?

**Comment by DomT4** [comment]
Yeah, extremely easily. Just whomp a `depends_on :macos => :yosemite` into the formula.

**Comment by DomT4** [comment]
If it's useful though:
```
OS X: 10.9.5-x86_64
Xcode: 6.2
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600

# clang --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

```
OS X: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700

# clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

```
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
Clang: 7.3 build 703

# clang --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Pull request closed without merging**
