### PR TITLE
sourcery 0.16.2

### PR DESCRIPTION
**Pull request by Liquidsoul**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Liquidsoul** [comment]
Seems like our Swift 5 update won't work on Sierra anymore 🤔 
I do not know if it's possible to skip the check on Sierra in the formula?

**Comment by SMillerDev** [comment]
Which xcode version is needed? Because currently it defines 2

**Comment by Liquidsoul** [comment]
Now we need Xcode 10.2, I'll see to change this in the formula here.

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Comment by Moisan** [comment]
Thank you @Liquidsoul !

**Pull request closed without merging**
