### PR TITLE
iozone 3.494

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
relates to relates to https://github.com/Homebrew/homebrew-core/pull/116656

**Comment by danielnachun** [comment]
This is actually building with the host GCC so it is not affected by the Homebrew GCC formula not using `-fPIE` by default.  This formula has no dependents so the failure is not caused by a dependency needing to be rebottled.  In this case somehow the `-fPIE` CFLAG is not being added properly, so we probably just need to add it manually.

**Comment by danielnachun** [comment]
I tested this locally and it turns out the problem here was that the source archive had some pre-built binaries already in it.  This was causing the `make` to skip building them, and the build subsequently failed when it tried to link to those binaries later.

The solution here is trivial - we just need to run `make clean` first to clean up the old binaries and rebuild them.  I will push the fix.

**Comment by chenrui333** [comment]
> I tested this locally and it turns out the problem here was that the source archive had some pre-built binaries already in it. This was causing the `make` to skip building them, and the build subsequently failed when it tried to link to those binaries later.
> 
> The solution here is trivial - we just need to run `make clean` first to clean up the old binaries and rebuild them. I will push the fix.

Thanks!

**Comment by chenrui333** [comment]
Some irrelevant livecheck failure

**Pull request closed without merging**
