### PR TITLE
sourcery 1.5.0

### PR DESCRIPTION
**Pull request by Moisan**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
We should try to see if we can get this to stop building universal binaries. Background in #81666.

**Comment by Moisan** [comment]
There doesn't seem to be a way to not build it. I tried to remove it but the test failed since `sourcery` was looking for that dylib.

**Comment by carlocab** [comment]
Hmm, ok. Let's add this to the [allowlist](https://github.com/Homebrew/homebrew-core/blob/master/audit_exceptions/universal_binary_allowlist.json) for now. Do you mind opening an issue upstream asking if it would be possible to add a build option that deactivates building a universal version of the relevant dylib? We can then fix it that way when the issue is resolved.

**Comment by Moisan** [comment]
Upstream has an open issue for it: https://github.com/krzysztofzablocki/Sourcery/issues/908 . I'll add the to the allowlist in this PR for now.

**Comment by carlocab** [comment]
You'll need to rebase, as you have a merge conflict. And squash your commit, since BrewTestBot won't be able to autosquash this...

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
