### PR TITLE
gprof2dot 2016.10.13

### PR DESCRIPTION
**Pull request by zbeekman**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

It's not a new formula

---

### CODE REVIEW

**Comment by indera** [comment]
👍

**Comment by MikeMcQuaid** [comment]
`fetch` and `install` are failing: https://bot.brew.sh/job/Homebrew%20Core/9332/version=any_sierra/testReport/junit/brew-test-bot/sierra/install_gprof2dot/

If there's issues with a PR please push changes to it rather than closing and reopening in future, too. Thanks!

**Comment by zbeekman** [comment]
> fetch and install are failing: https://bot.brew.sh/job/Homebrew%20Core/9332/version=any_sierra/testReport/junit/brew-test-bot/sierra/install_gprof2dot/

sorry, borked the URL update... forgot pypi has a hash in the URL.

> If there's issues with a PR please push changes to it rather than closing and reopening in future, too. Thanks!

Sure, sorry about that...

This should be good to go, if there are no other issues.

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request closed without merging**
