### PR TITLE
subversion: generate Python bindings by default

### PR DESCRIPTION
**Pull request by queengooborg**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

This is to fix `viewvc` as listed on #13133.

### CODE REVIEW

**Comment by fxcoudert** [comment]
I'd be tempted to take this opportunity to do a cleanup: remove the without-perl and without-ruby options (which are never used), thus depend on swig unconditionally, and remove the then-unnecessary swig dep in viewvc.

**Comment by vinyldarkscratch** [comment]
@fxcoudert I'm about to push a commit that will make you very happy...once GitHub starts working again.  >~<

**Comment by ilovezfs** [comment]
The question is whether
```
      system "make", "swig-py"
      system "make", "install-swig-py"
      (lib/"python2.7/site-packages").install_symlink Dir["#{lib}/svn-python/*"]
```
work fine with system Python. I suspect it does.

**Comment by ilovezfs** [comment]
```
diff --git a/Formula/subversion.rb b/Formula/subversion.rb
index 1dc07d3b98..3eec22a658 100644
--- a/Formula/subversion.rb
+++ b/Formula/subversion.rb
@@ -27,7 +27,7 @@ class Subversion < Formula
 
   # Always build against Homebrew versions instead of system versions for consistency.
   depends_on "sqlite"
-  depends_on "python" => :optional
+  depends_on "python" if MacOS.version <= :snow_leopard
   depends_on :perl => ["5.6", :recommended]
 
   # Bindings require swig
@@ -130,11 +130,9 @@ class Subversion < Formula
     system "make", "tools"
     system "make", "install-tools"
 
-    if build.with? "python"
-      system "make", "swig-py"
-      system "make", "install-swig-py"
-      (lib/"python2.7/site-packages").install_symlink Dir["#{lib}/svn-python/*"]
-    end
+    system "make", "swig-py"
+    system "make", "install-swig-py"
+    (lib/"python2.7/site-packages").install_symlink Dir["#{lib}/svn-python/*"]
 
     if build.with? "perl"
       # In theory SWIG can be built in parallel, in practice...
```

**Comment by vinyldarkscratch** [comment]
@ilovezfs Added your patch, thank you!  😄

**Comment by vinyldarkscratch** [comment]
Yay, it's building again!

**Comment by ilovezfs** [comment]
@vinyldarkscratch this needs to be rebased on master as it's now conflicted.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by vinyldarkscratch** [comment]
@ilovezfs Conflicts fixed now!  :wink:

**Comment by vinyldarkscratch** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
need to use git rebase

**Comment by vinyldarkscratch** [comment]
Ah, derp -- doing a `brew upgrade && brew update` now (and I'm seeing a few formulas that need to be fixed, which I'll help out with), will rebase once it's done!

**Comment by ilovezfs** [comment]
@DomT4 are you aware of any problem with using system Python for this?

**Comment by DomT4** [comment]
I don't think so. As far as I'm aware there's workarounds in place for Python 2.6, and there's no Python interface for running `svn co` which could throw SSL/TLS issues, so... it should be okay, theoretically.

**Comment by ilovezfs** [comment]
Thanks again @vinyldarkscratch! ❇️

**Pull request closed without merging**
