### PR TITLE
e2fsprogs 1.46.5

### PR DESCRIPTION
**Pull request by alebcay**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  Undefined symbols for architecture x86_64:
    "__et_list", referenced from:
        _initialize_ss_error_table in ss_err.o
    "_com_err_va", referenced from:
        _ss_error in error.o
  ld: symbol(s) not found for architecture x86_64
```

**Comment by alebcay** [comment]
Looks like might need to not patch out the flat namespace usage and add this to the allowlist, seeing as the program might need that to build. Would appreciate some additional feedback/thoughts on this.

**Comment by carlocab** [comment]
> Looks like might need to not patch out the flat namespace usage and add this to the allowlist, seeing as the program might need that to build. Would appreciate some additional feedback/thoughts on this.

The missing symbols look like they should be coming from `libcom_err`, which is generated earlier in the build. This seems more like a case of bad linker flags than actually needing the `-flat_namespace` flag. Does removing the `-flat_namespace` patch fix the build error? I'd be a bit surprised if it does.

**Comment by alebcay** [comment]
> > Looks like might need to not patch out the flat namespace usage and add this to the allowlist, seeing as the program might need that to build. Would appreciate some additional feedback/thoughts on this.
> 
> The missing symbols look like they should be coming from `libcom_err`, which is generated earlier in the build. This seems more like a case of bad linker flags [*] than actually needing the `-flat_namespace` flag. Does removing the `-flat_namespace` patch fix the build error? I'd be a bit surprised if it does.
> 
> [*] It probably just needs an `-lcom_err` somewhere.

Well, the build was working earlier before I removed `-flat_namespace` and `-undefined warning` (build succeeded earlier, audit failed due to flat namespace). I'll try fiddling with it some more and see if I can figure it out.

**Comment by carlocab** [comment]
#107961

**Pull request closed without merging**
