### PR TITLE
monetdb 11.43.9

### PR DESCRIPTION
**Pull request by sjoerdmullender**
Autogenerated PR as part of the release

### CODE REVIEW

**Comment by sjoerdmullender** [comment]
What went wrong with the test?  I downloaded the file logs-12-arm64.zip and looked at the contents, but I don't see any errors there.  In the Details section for the failed CI test, I see one error: "Error: no block given (yield)" but I have no idea what that means.
Without understanding what went wrong, it'll be hard for me to fix the problem.

By the way, one problem (warning) that I saw I can fix: some dependencies in a previous version were still marked as dependencies.  I will remove those the next time I submit a PR.

**Comment by SMillerDev** [comment]
@Homebrew/brew any recent changes that could cause this?

```
   ==> Detecting if monetdb--11.43.9.arm64_monterey.bottle.tar.gz is relocatable...
  Error: no block given (yield)
```

**Comment by carlocab** [comment]
Probably https://github.com/Homebrew/brew/pull/12534. Now reverted.

**Review by SMillerDev — APPROVED** [review]
Thanks @sjoerdmullender  ! Without contributions like yours it'd be impossible to keep homebrew going with the high standards that users have come to expect from the project. You can feel good knowing that you've made the world a tiny bit better for homebrew users around the world! 👍 🎉

**Pull request closed without merging**
