### PR TITLE
termius: remove setuptools resource

### PR DESCRIPTION
**Pull request by JCount**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Review by ilovezfs — APPROVED** [review]

**Comment by ilovezfs** [comment]
It would be good if there were an audit check for this. CC @tdsmith @MikeMcQuaid

**Comment by tdsmith** [comment]
We could; it's harmless.

**Comment by MikeMcQuaid** [comment]
@ilovezfs What specifically; having a resource named `setup tools`?

**Comment by ilovezfs** [comment]
@MikeMcQuaid yes specifically a resource named setuptools together with virtualenv, since the virtualenv is already providing a newish version of setuptools.

**Pull request closed without merging**
