### PR TITLE
hyperkit 0.20200224

### PR DESCRIPTION
**Pull request by mjgallag**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Bo98** [comment]
@BrewTestBot test this please

**Comment by mjgallag** [comment]
FYI won't work until there is a new tag, see https://github.com/moby/hyperkit/issues/267#issuecomment-590980109.

**Comment by Bo98** [comment]
Ok, thank you. The logs had already expired so I couldn't see back to why it failed.

**Comment by mjgallag** [comment]
ah sorry should have linked earlier, hope they tag soon

**Comment by Bo98** [comment]
The solver timeout should be solved with https://github.com/Homebrew/homebrew-core/commit/148a0593d00ecbf5ebbddcd257883dbe2aa3c775. I was previously getting timeouts even with `OPAMSOLVERTIMEOUT` set to 5 minutes. What seemed to work better was setting opam to use the external aspcud solver. In fact, it seems like this used to be the case (aspcud is in the list of hyperkit's dependencies in the formula) but an opam update changed the default behaviour to favour the internal solver.

**Comment by mjgallag** [comment]
@Bo98 it's now building successfully and no longer getting `TypeError: no implicit conversion of Integer into String`(https://github.com/moby/hyperkit/issues/267#issuecomment-590980109)! All I can think of is that `aspcud` provides different set of dependency versions than the new internal  `opam` solver. Are you able to merge this? Thanks for figuring this out!

**Comment by Bo98** [comment]
Oh wow. Glad it worked. I'll merge it just now.

**Pull request closed without merging**
