### PR TITLE
wxpython: depend on six and pillow

### LINKED ISSUE #79562: brew install wxpython succeeds, yet homebrew python cannot find module
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
odd@greek ~ % brew config
HOMEBREW_VERSION: 3.1.12-93-g736278c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 736278c02068d6f999989d4e4c89b6acd91b69d2
Last commit: 76 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ea8e4c8596be1a310bff521ffaaf8dea8758db5b
Core tap last commit: 87 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-arm64
CLT: 12.5.0.0.1.1617976050
Xcode: 12.5
Rosetta 2: false
todd@greek ~ % 
todd@greek ~ % 
todd@greek ~ % 
todd@greek ~ % brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to use the Python wxpython module after an apparent success brew install of wxpython.

### What happened (include all command output)?

A simple import of the module fails, using the homebrew version of Python.  (Other modules installed in the same way work fine.)

Here is the apparent successful install:

todd@greek ~ % brew install wxpython
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 06253790e to 736278c02.
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Downloading https://ghcr.io/v2/homebrew/core/wxpython/manifests/4.1.1_1
Already downloaded: /Users/todd/Library/Caches/Homebrew/downloads/e3048ea3c654afe0835b00bc7dc23cb21256877f3315615a951233b4eb52a940--wxpython-4.1.1_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/wxpython/blobs/sha256:016eaf4f3
Already downloaded: /Users/todd/Library/Caches/Homebrew/downloads/73e224303e86b1e337b1571cbe728b81896bf0f40f1f2b3cda1a9588766224b0--wxpython--4.1.1_1.arm64_big_sur.bottle.tar.gz
==> Pouring wxpython--4.1.1_1.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/wxpython/4.1.1_1: 1,192 files, 63.1MB

And here is the inability to find it:

todd@greek ~ % which python3
/opt/homebrew/bin/python3
todd@greek ~ % 
todd@greek ~ % python3
Python 3.9.5 (default, May  3 2021, 19:12:05) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'wx'
>>> 
>>> 
todd@greek ~ % 

### What did you expect to happen?

I expected the

   import wx

in python3 to succeed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
As above:

  brew install wxpython

followed by invoking python and loading the module:

  python3
  import wx
```

### PR DESCRIPTION
**Pull request by carlocab**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Closes #79562.

For the record, I couldn't get this to link with macOS `zlib` and brewed `libpng` but this isn't a regression caused by the changes here. The existing bottle reports no linkage to `libpng`, and only reports linkage to `zlib` through the bundled Pillow.

### CODE REVIEW

**Comment by carlocab** [comment]
#79798 might allow us to `depend_on "wxmac"` instead of using the vendored one.

**Comment by carlocab** [comment]
Actually, looking into it some more, it seems like a huge pain getting `wxpython` to not use the bundled `wxmac`. I think this can do for now.

**Review by nandahkrishna — COMMENTED** [review]
Should we add `numpy`, `pillow` and `six` to `exclude_packages` in `pypi_formula_mappings.json`? I just ran `brew update-python-resources wxpython` (in this PR branch) and it added these dependencies as resources.

**Comment by carlocab** [comment]
Sure. We can do it in a separate PR to save CI time.

**Review by nandahkrishna — APPROVED** [review]

**Comment by carlocab** [comment]
Opened an upstream issue for the lack of `zlib` and `libpng` linkage. https://github.com/wxWidgets/Phoenix/issues/1978

**Pull request closed without merging**
