### PR TITLE
heroku 7.0.9

### PR DESCRIPTION
**Pull request by epistrephein**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jdxcode** [comment]
this line needs to be removed now:

https://github.com/Homebrew/homebrew-core/pull/26984/files#diff-bf152f026ccb42ad2656c0582a6c8136R21

**Comment by epistrephein** [comment]
@jdxcode Thanks, I was trying to debug the problem.
Rebased and re-pushed.

**Comment by jdxcode** [comment]
tested and works great

**Review by jdx — APPROVED** [review]

**Comment by jdxcode** [comment]
for the moment no, this message isn't in the CLI anymore

**Comment by commitay** [comment]
Thanks @epistrephein and @jdxcode!

**Pull request closed without merging**
