### PR TITLE
mesa 22.1.6

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Review by carlocab — COMMENTED** [review]
The website says the lates release is 22.1.3.

**Comment by Porkepix** [comment]
> The website says the lates release is 22.1.3.

Same website have release notes up to 22.1.5 (same version as Homebrew currently have): https://docs.mesa3d.org/relnotes.html

And the repo have a tag for 22.1.6… so, don't know what should be trusted…

**Comment by carlocab** [comment]
If there are release notes in the documentation then that's fine. But I wouldn't trust a tag on its own. Is there a release announcement on the mailing list?

**Comment by Porkepix** [comment]
> If there are release notes in the documentation then that's fine. But I wouldn't trust a tag on its own. Is there a release announcement on the mailing list?

The repo have no release note in main branch nor in this tag for 22.1.6… (or rather exists in the tag but crete an empty file: https://gitlab.freedesktop.org/mesa/mesa/-/commit/898d3ec35d7aba7dc7bdc592f9f646eb16cac28d)

But the release was indeed announced on MLs:
- https://lists.freedesktop.org/archives/mesa-dev/2022-August/225840.html
- https://lists.freedesktop.org/archives/mesa-announce/2022-August/000683.html

Arch also just released it: https://archlinux.org/packages/extra/x86_64/mesa/

**Review by carlocab — APPROVED** [review]
Ok, thanks for investigating!

**Pull request closed without merging**
