### PR TITLE
libdap 3.20.4

### PR DESCRIPTION
**Pull request by alebcay**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
@brewtestbot test this please!

**Comment by alebcay** [comment]
@BrewTestBot test this please.

**Comment by alebcay** [comment]
```
running bootstrap script ... 2019-08-05 05:51:49.948 BST [35794] FATAL:  could not create shared memory segment: No space left on device
2019-08-05 05:51:49.948 BST [35794] DETAIL:  Failed system call was shmget(key=5432001, size=56, 03600).
2019-08-05 05:51:49.948 BST [35794] HINT:  This error does *not* mean that you have run out of disk space.  It occurs either if all available shared memory IDs have been taken, in which case you need to raise the SHMMNI parameter in your kernel, or because the system's overall limit for shared memory has been reached.
	The PostgreSQL documentation contains more information about shared memory configuration.
child process exited with exit code 1
```

**Comment by alebcay** [comment]
CI passing now.

**Comment by Moisan** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
