### PR TITLE
gdal: Add c-blosc to gdal

### PR DESCRIPTION
**Pull request by ateucher**
Add blosc compression library to gdal build as it is required to open many .zarr files

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by stefanb** [comment]
According to https://gdal.org/en/stable/development/building_from_source.html#blosc this may require setting:
* BLOSC_INCLUDE_DIR
* BLOSC_LIBRARY

and
* GDAL_USE_BLOSC=ON to make sure it is used

**Comment by ateucher** [comment]
I don't think it does require setting those, as on that page under `GDAL_USE_BLOSC` it also says "Defaults to ON when Blosc is found."

It appears to be finding it fine without setting those vars:

Before (using current bottled gdal):

```
$ brew reinstall gdal
$ gdalinfo ZARR:"/vsigs/gcp-public-data-arco-era5/co/single-level-reanalysis.zarr":/time
ERROR 1: Decompressor blosc not handled
ERROR 1: Decompressor blosc not handled
ERROR 1: Decompressor blosc not handled
...
ERROR 1: Decompressor blosc not handled
gdalinfo failed - unable to open 'ZARR:/vsigs/gcp-public-data-arco-era5/co/single-level-reanalysis.zarr:/time'.
```

After: 

```
$ HOMEBREW_NO_INSTALL_FROM_API=1 brew reinstall --build-from-source gdal
$ gdalinfo ZARR:"/vsigs/gcp-public-data-arco-era5/co/single-level-reanalysis.zarr":/time
Driver: Zarr/Zarr
Files: /vsigs/gcp-public-data-arco-era5/co/single-level-reanalysis.zarr/time/.zarray
Size is 374016, 1
Origin = (-0.500000000000000,-0.500000000000000)
Pixel Size = (1.000000000000000,1.000000000000000)
Metadata:
  calendar=proleptic_gregorian
  long_name=initial time of forecast
  standard_name=forecast_reference_time
Corner Coordinates:
Upper Left  (  -0.5000000,  -0.5000000)
Lower Left  (  -0.5000000,   0.5000000)
Upper Right (  374015.500,      -0.500)
Lower Right (  374015.500,       0.500)
Center      (  187007.500,       0.000)
Band 1 Block=374016x1 Type=Int64, ColorInterp=Undefined
  Unit Type: hours since 1979-01-01 00:00:00
```

**Comment by stefanb** [comment]
Would it make sense to verify it in test?
Currently test runs `gdalinfo --formats`. 
That test could be extended to expect `Zarr -raster,multidimensional raster- (rw+vs): Zarr` or just `Zarr` for some flexibility.

**Comment by ateucher** [comment]
It's a good idea, though even with current bottle `Zarr` is listed (but doesn't have blosc compressor).

`gdalinfo --format Zarr` gives:

```
... a lot of other metadata ....
 
Other metadata items:
    COMPRESSORS=blosc,zlib,gzip,lzma,zstd,lz4
    FILTERS=delta
    BLOSC_COMPRESSORS=blosclz,lz4,lz4hc,zlib,zstd
```

We could test for that?

**Comment by ateucher** [comment]
Or just look for the presence of the `BLOSC_COMPRESSORS` line? Something like:

```
assert_match "BLOSC_COMPRESSORS", shell_output("#{bin}/gdalinfo --format Zarr")
```

**Comment by ateucher** [comment]
Force-pushed my squashed commits to conform to commit style guide

**Review by stefanb — APPROVED** [review]
Thanks!

**Pull request merged**
