### PR TITLE
mosquitto 2.0.14

### PR DESCRIPTION
**Pull request by EricFromCanada**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Moisan** [comment]
Fails on ARM with
```
  Undefined symbols for architecture arm64:
    "_mosquitto_callback_register", referenced from:
        _mosquitto_plugin_init in mosquitto_payload_modification.c.o
    "_mosquitto_callback_unregister", referenced from:
        _mosquitto_plugin_cleanup in mosquitto_payload_modification.c.o
    "_mosquitto_calloc", referenced from:
        _callback_message in mosquitto_payload_modification.c.o
  ld: symbol(s) not found for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Also the [homepage](https://mosquitto.org/download/) only mention `2.0.13`.

**Comment by chenrui333** [comment]
Raised an issue to confirm about this.

**Review by chenrui333 — APPROVED** [review]

**Comment by EricFromCanada** [comment]
The failure was coming from plugins that were being compiled by default despite them being [only examples](https://www.eclipse.org/lists/mosquitto-dev/msg02576.html).

**Comment by EricFromCanada** [comment]
Homepage has been updated to 2.0.14.

**Pull request closed without merging**
