### PR TITLE
node@9 9.11.1

### PR DESCRIPTION
**Pull request by jasonseminara**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ryenus** [comment]
Too bad this wasn't part of the node 10 formulae update 👎

**Comment by ilovezfs** [comment]
Thanks for the suggestion @jasonseminara. However, we only add `node@*` versioned formulae for the LTS releases, which is not the case here.

**Comment by ryenus** [comment]
[Here][1] is a reason this.

[1]: https://github.com/anodynos/upath/pull/15

**Comment by ilovezfs** [comment]
@ryenus I don't follow. Use `node@8`, no?

**Comment by ryenus** [comment]
maybe yes, but if one is previously using node v9, having an option to install the same version, namely node@9, is probably the best.

**Comment by chrmoritz** [comment]
Assuming you didn't removed node 9.11.1 from the Cellar yet, you could just go back with `brew switch node 9.11.1`. Node 9 is currently in maitance only and will only receive an update again, if there will be a security update released until June, when it will become finally EOL.

And regarding the issue with incorrect engines ranges in upath: You could just set `ignore-engines` to `true` in your yarn config to stop yarn from erroring out on unmatched engine ranges (in npm it would be only a warning btw).

**Comment by ilovezfs** [comment]
Thanks @anodynos!

**Pull request closed without merging**
