### PR TITLE
elm-format 0.8.6

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
  ==> cabal v2-update
  Config file path source is default config file.
  Config file not found:
  /tmp/elm-format-20230302-6904-glqh26/.brew_home/.cabal/config
  Writing default configuration to
  /tmp/elm-format-20230302-6904-glqh26/.brew_home/.cabal/config
  Error: cabal: Cannot find the program 'ghc'. User-specified path 'ghc-9.2.5'
  does not refer to an executable and the program is not on the system path.
```

**Comment by avh4** [comment]
elm-format author here :wave:   FYI, elm-format development now uses ghc 9.2 (specifically 9.2.5) instead of ghc 8.10

**Comment by chenrui333** [comment]
> elm-format author here 👋 FYI, elm-format development now uses ghc 9.2 (specifically 9.2.5) instead of ghc 8.10

@avh4 why not 9.2.6 or 9.2.7?

**Comment by chenrui333** [comment]
https://www.githubstatus.com/incidents/qfby3shb6r3w

**Comment by avh4** [comment]
> why not 9.2.6 or 9.2.7?

ah, those hadn't been released yet when I started the latest dev cycle.  I'd expect it should work fine if homebrew builds with either of those.

**Comment by chenrui333** [comment]
> > why not 9.2.6 or 9.2.7?
> 
> ah, those hadn't been released yet when I started the latest dev cycle. I'd expect it should work fine if homebrew builds with either of those.

it does not, as you have hardcoded 9.2.5 somewhere.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
