### PR TITLE
New formula liblemon, follow the guidelines

### PR DESCRIPTION
**Pull request by zhaofeng-shu33**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
- New formulas should be build without patching
- And be actively maintained… last lemon version is dated July 2014, and doesn't build without patch

**Comment by zhaofeng-shu33** [comment]
I have removed the patch;
The library is actively maintained, as can be seen from the latest commit (4 weeks ago, https://lemon.cs.elte.hu/trac/lemon/changeset/1425/lemon/). The development branch has not been released yet.

**Comment by zhaofeng-shu33** [comment]
Looking forward to further response.

**Comment by fxcoudert** [comment]
Yes, I see some commits, but no active development in mailing-lists, no response to requests to ship a new release (date August 2018). And we have no idea how notable / widely used the software is.

As such, I am going to close and recommend that you maintain this as a personal tap: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
In the future, we could consider it for inclusion in Homebrew core, either based on analytics from the tap, or on a new release being shipped.

**Pull request closed without merging**
