### PR TITLE
dasel 2.4.1

### PR DESCRIPTION
**Pull request by TomWright**
[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
Duplicate of #151691

**Comment by TomWright** [comment]
The lastest version of my tool isn't available - I can delete the tag, release and release again to raise another PR but can we re-open this PR instead?

```
$ brew upgrade dasel
==> Downloading https://formulae.brew.sh/api/formula.jws.json
################################################################################################################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
################################################################################################################################################################################################################################################### 100.0%
==> Upgrading 1 outdated package:
dasel 2.3.6 -> 2.4.0
==> Downloading https://ghcr.io/v2/homebrew/core/dasel/manifests/2.4.0
################################################################################################################################################################################################################################################### 100.0%
==> Fetching dasel
==> Downloading https://ghcr.io/v2/homebrew/core/dasel/blobs/sha256:839fd9b567995eaea40b79118a0f7fedef395e2cd09f05c92542ae061ff38a96
################################################################################################################################################################################################################################################### 100.0%
==> Upgrading dasel
  2.3.6 -> 2.4.0
```

**Comment by chenrui333** [comment]
my bad. yeah, this is not a duplicate, sorry about it.

gonna rebase this PR now.

**Comment by chenrui333** [comment]
Should be good now.

**Review by chenrui333 — APPROVED** [review]

**Comment by TomWright** [comment]
Thank you @chenrui333 , I appreciate it

**Pull request merged**
