### PR TITLE
homebank 5.7.1

### PR DESCRIPTION
**Pull request by AAS**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by AAS** [comment]
Any ideas how to fix "checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool" error on linux?

**Comment by cho-m** [comment]
Probably need to wait for #150703

**Comment by chenrui333** [comment]
rebased to the latest master and updated the linux build

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @AAS!

**Pull request merged**
