### PR TITLE
envoy: remove linux build

### PR DESCRIPTION
**Pull request by codefromthecrypt**
I don't expect this change to be universally popular. However, I think
it is the most pragmatic way to isolate the impact of envoy on
maintainers and end users. Specifically, this removes the linux build
and in doing so removes fragile and complex configuration. It also will
reduce the time to land new versions on OS/x.

I believe this is justified beyond the technical dept recovered. Envoy
is not often installed on linux with homebrew. To the degree it can be
used, it can't be used on arm64 which is a supported Envoy platform on
Linux. The few using linuxbrew have other options including the official
docker images, func-e, and in the future, formal system packages and
tarballs.

Once we remove this, maintaining homebrew envoy's primary audience, OS/x
is easier and faster. We can focus energy on what's not available
elsewhere: a macOS build of Envoy. We can focus on the larger audience
which extends larger still when Envoy completes arm64+osx (likely in
version 1.21). Maintainers do not have to run very long linux builds
anymore, and CI resources can be conserved for projects more often used.

More details on the discussion are here, but I'm raising this PR as a
call to action. If the homebrew leads decide it is better to keep trying
to build on Linux, the main impact is continued longer and more complex
work to release new versions to end users. That's not the worst outcome,
but I believe they deserve better, hence this issue.

See https://github.com/Homebrew/discussions/discussions/2271

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
> but also burden the maintainers like me equally on every release as if the build fails it fails right? What am I missing?

It wouldn't try and build because it depends on macOS in that case

**Comment by codefromthecrypt** [comment]
So, the thing with homebrew/ubuntu16.04 is not that python3 can't be found, it is that the floor version of it isn't 3.5 and that's what's on the linuxbrew. I'll see if this problem happens if you are running normal ubuntu:16.05, though iirc that doesn't install python3 by default..

```
==> /home/linuxbrew/.linuxbrew/opt/bazelisk/bin/bazelisk build --compilation_mode=opt --curses=no --show_task_finish --verbose_failures --action_env
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/envoy/01.bazelisk:
    exec(code, run_globals)
  File "/tmp/envoy-20211013-11014-1hkv4c2/.brew_home/_bazel/2931c46125cf9af168cbcf060ba9d0f4/external/rules_python/python/pip_install/extract_wheels/__main__.py", line 5, in <module>
    main()
  File "/tmp/envoy-20211013-11014-1hkv4c2/.brew_home/_bazel/2931c46125cf9af168cbcf060ba9d0f4/external/rules_python/python/pip_install/extract_wheels/__init__.py", line 87, in main
    subprocess.run(pip_args, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'wheel', '-r', '/tmp/envoy-20211013-11014-1hkv4c2/.brew_home/_bazel/2931c46125cf9af168cbcf060ba9d0f4/external/envoy/source/extensions/filters/network/kafka/requirements.txt', '--require-hashes']' returned non-zero exit status 1
)
ERROR: Analysis of target '//source/exe:envoy-static' failed; build aborted: Analysis failed
INFO: Elapsed time: 115.773s
INFO: 0 processes.
```

**Comment by danielnachun** [comment]
We don't use system Python on Linux because we can't control what version the user has (if they even have one).  Using a specific version of GCC is also not an issue - we have to do this all the time.  We have several maintainers (including myself) with extensive knowledge of GCC and Python, and we have far more complex Linux-specific code in other formulae.  

If you are hitting Linux build problems in the future please tag the Linux maintainers with @Homebrew/linux (or ask someone to do it if you don't have permission - I can't recall if non-maintainers can use that tag).

**Comment by carlocab** [comment]
For reference:
```
❯ curl --location --silent https://formulae.brew.sh/api/formula-linux/envoy.json | jq '.analytics'
{
  "install": {
    "30d": {
      "envoy": 4
    },
    "90d": {
      "envoy": 30
    },
    "365d": {
      "envoy": 88
    }
  },
  "install_on_request": {
    "30d": {
      "envoy": 4
    },
    "90d": {
      "envoy": 30
    },
    "365d": {
      "envoy": 88
    }
  },
  "build_error": {
    "30d": {
      "envoy": 0
    }
  }
}
```

On macOS:
```
{
  "install": {
    "30d": {
      "envoy": 477
    },
    "90d": {
      "envoy": 1739
    },
    "365d": {
      "envoy": 5725
    }
  },
  "install_on_request": {
    "30d": {
      "envoy": 477
    },
    "90d": {
      "envoy": 1742
    },
    "365d": {
      "envoy": 5729
    }
  },
  "build_error": {
    "30d": {
      "envoy": 0
    }
  }
}
```

**Comment by carlocab** [comment]
Thanks for all the work you've put into maintaining the Envoy formula, @codefromthecrypt. I don't want you to feel like you're wasting your time.

If we face more build issues on Linux on the next version bump, even after giving the Linux maintainers a chance to have a look, I'm in favour of getting rid of the Linux build. I don't think this much time and effort (from anyone) is worth the 5 Linux users using the Envoy formula, nor is it worth significant delays to shipping updates to thousands of macOS users.

**Comment by danielnachun** [comment]
That's true - I think the biggest issue here was that it seemed that Linux maintainers were not made aware that this was the blocker.  @codefromthecrypt please tag me or @Homebrew/linux if you hit build failures again.  It's actually uncommon for Linux to be the more difficult platform to build on.

One thing that may help get this to work better on Linux is to use `llvm` as the Arch Linux AUR script does.  Since this was last tried to there have been a lot of changes and improvements to `llvm` on Linux so that may smooth out the C++ issues.  I'm also going to take a look at what's going on with the PATH in `bazel` because it shouldn't need to use any host OS binaries.  Hopefully we can make this formula more stable on Linux so that it's not a burden in the future!

**Pull request closed without merging**
