### PR TITLE
openjdk@8 1.8.0-402

### PR DESCRIPTION
**Pull request by cv3x**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by calvinit** [comment]
@chenrui333 Hi, **NEED HELP**: There seems to be some problems with building this PR on MacOS. How did you successfully compile it in the previous version [1.8.0-392](https://github.com/Homebrew/homebrew-core/pull/151920)?
Thank you.

**Comment by chenrui333** [comment]
you need to do a single commit and rebase to the latest master.

**Comment by calvinit** [comment]
> you need to do a single commit and rebase to the latest master.

I mean I will get some clang compiler errors on MacOS platform.

**Comment by SMillerDev** [comment]
> I mean I will get some clang compiler errors on MacOS platform.

That should be reported upstream, last time it was only sonoma.

**Comment by calvinit** [comment]
> > I mean I will get some clang compiler errors on MacOS platform.
> 
> That should be reported upstream, last time it was only sonoma.

How did you solve it last time? Maybe your experience will be helpful to me.

**Comment by SMillerDev** [comment]
> How did you solve it last time? Maybe your experience will be helpful to me.

Nobody solved it last time, it never worked on Sonoma.

**Comment by calvinit** [comment]
> > How did you solve it last time? Maybe your experience will be helpful to me.
> 
> Nobody solved it last time, it never worked on Sonoma.

Currently encountering errors while building C++ （.../jdk8u-jdk8u402-ga/hotspot/src/share/vm/code/compiledIC.cpp:225:15: error: comparison between pointer and integer ('address' (aka 'unsigned char *') and 'bool')). I've tried adding [`-Wno-pointer-integer-compare`](https://releases.llvm.org/15.0.0/tools/clang/docs/DiagnosticsReference.html#wpointer-integer-compare) diagnostic flag but it's still not working!

According to the official [README-builds.html](https://github.com/openjdk/jdk/blob/jdk8-b120/README-builds.html) for OpenJDK, it seems to require [Xcode 4.5.2](https://developer.apple.com/xcode/) and the "Command line tools". However, the current MacOS system may not be able to download and use such an old version. Is there any other way to proceed?

**Comment by SMillerDev** [comment]
I'd still like to suggest reporting it to the developers. If they don't have a solution we'll have to disable OpenJDK 8 in Homebrew.

**Pull request closed without merging**
