### PR TITLE
mkdocs: fix linkage

### PR DESCRIPTION
**Pull request by p-linnane**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by Bo98** [comment]
Seems weird to be syntax only to introduce a dependency when the current bottles aren't using it no?

**Comment by p-linnane** [comment]
Working through a bunch of indirect linkage stuff so we can get https://github.com/Homebrew/brew/pull/16718 merged.

**Comment by p-linnane** [comment]
Ok this is strange. Compiling locally I'm not seeing any linkage with `libyaml` like all of the other formulae we've had to push this to recently: https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged+fix+linkage

Using `arxiv_latex_cleaner` as an example, our current bottles show this linkage:
```
╰─ brew linkage arxiv_latex_cleaner
System libraries:
  /usr/lib/libSystem.B.dylib
Homebrew libraries:
  /opt/homebrew/opt/libyaml/lib/libyaml-0.2.dylib (libyaml)
Undeclared dependencies with linkage:
  libyaml
Dependencies with no linkage:
  pillow
```
This is despite `libyaml` not being in the tree (other than due to the PR where I added it). Not sure what is going on here now.

**Comment by Bo98** [comment]
`arxiv_latex_cleaner` bottles were rebuilt in https://github.com/Homebrew/homebrew-core/pull/163288. Do you have another example where bottles were not rebuilt?

**Comment by Bo98** [comment]
`arxiv_latex_cleaner` bottles were rebuilt in https://github.com/Homebrew/homebrew-core/pull/163377. Do you have an example where bottles were not rebuilt?

**Comment by Bo98** [comment]
To be clear, the behaviour I expect is that libyaml linkage is introduced by adding this dependency (and is a good idea to do so), but would require a bottle rebuild for that to show.

**Comment by p-linnane** [comment]
So essentially we need to do a rebuild and publish those bottles when adding `libyaml` for `pyyaml`? I can run back through and check everything and rebuild if so.

**Comment by Bo98** [comment]
Yes

**Comment by p-linnane** [comment]
Thank you for the clarification. I have a better understanding now. I've kicked off a rebuild in this PR, and will run back through the previous ones to get those handled as well.

**Review by Bo98 — APPROVED** [review]

**Pull request merged**
