### PR TITLE
libvpx 1.13.0

### PR DESCRIPTION
**Pull request by miccal**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Needs a re-run on the self-hosted Linux runner.

Also, not really a fan of skipping recursive dependents here given that there is broken linkage.

**Comment by carlocab** [comment]
Big Sur ARM failed to download Qt for some reason. Killing the tests for now to try to clear up the build queue.

**Comment by chenrui333** [comment]
on 13

```
  qt@5:
    * Files were found with references to the Homebrew shims directory.
      The offending files are:
        mkspecs/qmodule.pri
```

on 11, the following formulae build failures are all due to the download failure with `qt_bottle_manifest` resource

- fceux
- mkvdts2ac3
- mkvtomp4
- pc6001vx
- qmmp

LGTM for merging

**Comment by chenrui333** [comment]
I will followup some regression checks on 11

**Review by chenrui333 — APPROVED** [review]

**Comment by carlocab** [comment]
Qt bottles are broken. They have linkage with `ffmpeg`, and there is no Big Sur bottle.

**Comment by carlocab** [comment]
Qt rebottle: https://github.com/Homebrew/homebrew-core/actions/runs/4215647731

**Comment by carlocab** [comment]
Big Sur bottle build: https://github.com/Homebrew/homebrew-core/actions/runs/4215652947

Bottle will need to be manually uploaded.

**Pull request closed without merging**
