### PR TITLE
ocaml 4.11.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
11.0

```
brew install --build-from-source bibtex2html
brew install --build-from-source comby
brew install --verbose --build-bottle camlp5
brew install --verbose --build-bottle hyperkit
brew install --build-from-source camlp5
brew install --only-dependencies --verbose --build-bottle ledit
brew install --verbose --build-bottle ledit
brew install --verbose --build-bottle ocaml-num
```

10.14, 10.15

```
Error: 8 failed steps!
brew install --build-from-source bibtex2html
brew install --build-from-source comby
brew install --verbose --build-bottle camlp5
brew test --verbose hyperkit
brew install --build-from-source camlp5
brew install --only-dependencies --verbose --build-bottle ledit
brew install --verbose --build-bottle ledit
brew install --verbose --build-bottle ocaml-num
```

**Comment by chenrui333** [comment]
bibtex2html site issue, https://github.com/backtracking/bibtex2html/issues/30
camlp5 build issue report, https://github.com/camlp5/camlp5/issues/71

**Comment by fxcoudert** [comment]
Once you rebase on top of master, we can see how it goes on ARM, which it is supposed to support in this version.

**Comment by chenrui333** [comment]
hyperkit issue report, https://github.com/moby/hyperkit/issues/301

**Comment by chenrui333** [comment]
camlp5 7.14 #67908

**Comment by carlocab** [comment]
There's a version 4.11.1 now. Try that?

**Comment by chenrui333** [comment]
<details>
<summary>build status</summary>

10.14, 10.15, 11.0
```
Error: ocamlsdl has been disabled!
==> SKIPPED ocamlsdl
Error: 7 failed steps!
brew install --build-from-source comby
brew install --build-from-source coq
brew test --retry --verbose ocaml-zarith
brew test --retry --verbose ocaml-zarith
brew test --verbose hyperkit
brew install --verbose --build-bottle ledit
brew install --verbose --build-bottle ocaml-num
```

11-arm

```
Error: ocamlsdl has been disabled!
==> SKIPPED ocamlsdl
Error: 31 failed steps!
brew install --verbose --build-bottle ocaml
brew install --build-from-source ocaml
brew install --only-dependencies --verbose --build-bottle ocamlbuild
brew install --verbose --build-bottle ocamlbuild
brew install --build-from-source ocaml ocamlbuild
brew install --only-dependencies --verbose --build-bottle hevea
brew install --verbose --build-bottle hevea
brew install --build-from-source ocaml
brew install --only-dependencies --verbose --build-bottle camlp5
brew install --verbose --build-bottle camlp5
brew install --build-from-source ocaml
brew install --only-dependencies --verbose --build-bottle ocaml-findlib
brew install --verbose --build-bottle ocaml-findlib
brew install --build-from-source hevea ocaml ocamlbuild
brew install --only-dependencies --verbose --build-bottle coccinelle
brew install --verbose --build-bottle coccinelle
brew install --build-from-source ocaml
brew install --only-dependencies --verbose --build-bottle hyperkit
brew install --verbose --build-bottle hyperkit
brew install --build-from-source ocaml
brew install --only-dependencies --verbose --build-bottle lablgtk
brew install --verbose --build-bottle lablgtk
brew install --build-from-source camlp5 ocaml
brew install --only-dependencies --verbose --build-bottle ledit
brew install --verbose --build-bottle ledit
brew install --build-from-source ocaml ocamlbuild
brew install --only-dependencies --verbose --build-bottle menhir
brew install --verbose --build-bottle menhir
brew install --build-from-source ocaml ocaml-findlib
brew install --only-dependencies --verbose --build-bottle ocaml-num
brew install --verbose --build-bottle ocaml-num
```

</details>

**Comment by kit-ty-kate** [comment]
> There's a version 4.11.1 now. Try that?

4.11.1 is not compatible with macOS/arm64. Please use 4.10.2 instead, 4.10.2 was released precisely for fast merge in homebrew. What was blocking before? I can't see the previous logs

**Comment by kit-ty-kate** [comment]
For the `ocaml-num` failure, my guess is that the test from `hyperkit` is changing the environment. Are the tests sandboxed?

**Comment by kit-ty-kate** [comment]
I opened a PR on your repository, just in case this is the issue.

**Pull request closed without merging**
