### PR TITLE
phrase-cli 2.9.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  # github.com/phrase/phrase-cli/cmd
  cmd/api_comment_reactions.go:49:29: undefined: api.ReactionCreateOpts
  cmd/api_comment_reactions.go:66:38: client.CommentReactionsApi undefined (type *phrase.APIClient has no field or method CommentReactionsApi)
  cmd/api_comment_reactions.go:120:29: undefined: api.ReactionDeleteOpts
  cmd/api_comment_reactions.go:138:38: client.CommentReactionsApi undefined (type *phrase.APIClient has no field or method CommentReactionsApi)
  cmd/api_comment_reactions.go:188:29: undefined: api.ReactionShowOpts
  cmd/api_comment_reactions.go:206:38: client.CommentReactionsApi undefined (type *phrase.APIClient has no field or method CommentReactionsApi)
  cmd/api_comment_reactions.go:261:29: undefined: api.ReactionsListOpts
  cmd/api_comment_reactions.go:286:38: client.CommentReactionsApi undefined (type *phrase.APIClient has no field or method CommentReactionsApi)
```

**Review by ZhongRuoyu — COMMENTED** [review]
Not marked as the latest release yet: https://github.com/phrase/phrase-cli/releases

**Comment by SMillerDev** [comment]
This should have a livecheck then.

**Comment by chenrui333** [comment]
> This should have a livecheck then.

I think this is mostly because of the release build issue, now it is the latest release.

**Review by ZhongRuoyu — APPROVED** [review]

**Pull request merged**
