### PR TITLE
solr 9.2.0

### PR DESCRIPTION
**Pull request by ZhongRuoyu**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
Not the latest release yet: https://solr.apache.org/news.html

**Comment by ZhongRuoyu** [comment]
```
  Error: ==> Testing solr
  ==> /opt/homebrew/Cellar/solr/9.2.0/bin/solr -i
  Your current version of Java is too old to run this version of Solr.
  We found major version , using command '/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home/bin/java -version', with response:
  Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
  openjdk version "19.0.2" 2023-01-17
  OpenJDK Runtime Environment Homebrew (build 19.0.2)
  OpenJDK 64-Bit Server VM Homebrew (build 19.0.2, mixed mode, sharing)
  
  Please install latest version of Java 11 or set JAVA_HOME properly.
```

**Comment by ZhongRuoyu** [comment]
Related to https://github.com/apache/solr/commit/025c0305fa829baa770f62c81654af8a708753d9#diff-49c29c8f653341f48008c38f5f2cf970fa430cdca29181c819d7bdcfcc722980R164.

```bash
# test that Java exists, is executable and correct version
JAVA_VER=$("$JAVA" -version 2>&1)
# ...
JAVA_VER_NUM=$(echo "$JAVA_VER" | head -1 | awk -F '"' '/version/ {print $2}' | sed -e's/^1\.//' | sed -e's/[._-].*$//')
```

`_JAVA_OPTIONS` is set in our test environment, so the first line of output will not contain the version string:

```
Picked up _JAVA_OPTIONS: -Duser.home=/Users/ruoyu/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment Homebrew (build 19.0.2)
OpenJDK 64-Bit Server VM Homebrew (build 19.0.2, mixed mode, sharing)
```

Even though `head -1` is used here, the `Picked up _JAVA_OPTIONS` output did not affect the version check because Bash truncates them into one line. But not when double quotes are added:

```console
$ JAVA_VER=$(java -version 2>&1)
$ echo $JAVA_VER
Picked up _JAVA_OPTIONS: -Duser.home=/Users/ruoyu/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp openjdk version "19.0.2" 2023-01-17 OpenJDK Runtime Environment Homebrew (build 19.0.2) OpenJDK 64-Bit Server VM Homebrew (build 19.0.2, mixed mode, sharing)
$ echo "$JAVA_VER"
Picked up _JAVA_OPTIONS: -Duser.home=/Users/ruoyu/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment Homebrew (build 19.0.2)
OpenJDK 64-Bit Server VM Homebrew (build 19.0.2, mixed mode, sharing)
```

**Comment by ZhongRuoyu** [comment]
Reported upstream at https://issues.apache.org/jira/browse/SOLR-16721.

**Comment by ZhongRuoyu** [comment]
```
No file to patch.  Skipping patch.
```

**Comment by janhoy** [comment]
Cool way of adding a patch to the formula!

**Review by SMillerDev — APPROVED** [review]

**Pull request merged**
