### PR TITLE
e2fsprogs 1.46.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
Not an official release? http://e2fsprogs.sourceforge.net

**Comment by carlocab** [comment]
From `NOTICE`
```
This package, the EXT2 filesystem utilities, are made available under
the GNU Public License version 2, with the exception of the lib/ext2fs
and lib/e2p libraries, which are made available under the GNU Library
General Public License Version 2, the lib/uuid library which is made
available under a BSD-style license and the lib/et and lib/ss
libraries which are made available under an MIT-style license.  Please
see lib/uuid/COPYING for more details for the license for the files
comprising the libuuid library, and the source file headers of the
libet and libss libraries for more information.
```

**Comment by carlocab** [comment]
`lib/uuid` looks like `BSD-3-clause`:
```
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, and the entire permission notice in its entirety,
   including the disclaimer of warranties.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. The name of the author may not be used to endorse or promote
   products derived from this software without specific prior
   written permission.
```

**Comment by carlocab** [comment]
From `lib/ext2fs/tdb.c`
```
   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2 of the License, or (at your option) any later version.
```

**Comment by carlocab** [comment]
I guess this might be:
```
license all_of: ["GPL-2.0-or-later", "LGPL-2.0-or-later", "LGPL-2.0-only", "BSD-3-Clause", "MIT"]
```
`LGPL-2.0-only` is from `lib/e2p`, which contains no licensing information aside from the one in `NOTICE`.

**Comment by chenrui333** [comment]
it is actually on sourceforge.
image

**Comment by chenrui333** [comment]
on the homepage, it said

```
License
GNU Library or Lesser General Public License version 2.0 (LGPLv2), GNU General Public License version 2.0 (GPLv2)

```

**Comment by carlocab** [comment]
Doesn't look complete though, given the `NOTICE` in the tarball

**Comment by chenrui333** [comment]
yeah, I think we SDPX does not have a general exception handling for GPL-2.0 licenses yet. :(

**Review by carlocab — APPROVED** [review]
We can just fix the license in a follow-up PR.

**Comment by chenrui333** [comment]
yeah, check out this repo. https://github.com/spdx/license-list-XML

We should probably work with them more on the license clarification stuff.

**Pull request closed without merging**
