### PR TITLE
opencv 4.4.0

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dawidd6** [comment]
```
/tmp/visp-20200726-80264-kzu1ij/visp-3.3.0/modules/vision/src/key-point/vpKeyPoint.cpp:2450:35: error: no member named 'SIFT' in namespace 'cv::xfeatures2d'; did you mean 'cv::SIFT'?
    m_extractors[extractorName] = cv::xfeatures2d::SIFT::create();
                                  ^~~~~~~~~~~~~~~~~~~~~
                                  cv::SIFT
/usr/local/Cellar/opencv/4.4.0/include/opencv4/opencv2/features2d.hpp:251:20: note: 'cv::SIFT' declared here
class CV_EXPORTS_W SIFT : public Feature2D
                   ^
```

**Comment by jonchang** [comment]
https://github.com/opencv/opencv/wiki/ChangeLog#version440

>     SIFT (Scale-Invariant Feature Transform) algorithm has been moved to the main repository (patent on SIFT is expired)

**Comment by jonchang** [comment]
> Since the patent for SIFT expired recently, SIFT features moved from `opencv_contrib` to the main `opencv` repository.
> 
> To fix the issue, I think that updating
> ```
> cv::xfeatures2d::SIFT
> ```
> with
> ```
> cv::SIFT
> ```
> should solve the issue.

https://github.com/lagadic/visp/issues/759#issuecomment-626918257

**Comment by chenrui333** [comment]
Thanks @jonchang!

**Pull request closed without merging**
