### PR TITLE
youtube-dl 2017.08.23

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@zmwangx are you feeling OK?

**Comment by zmwangx** [comment]
Totally. Just too lazy to type `bump-youtube-dl 2017.08.23` today. :trollface:

**Comment by ilovezfs** [comment]
@zmwangx Oh good. You had me worried. Lucky for me, I only need to type `bfpr youtube-dl`

**Comment by zmwangx** [comment]
Holy shit, I should optimize that version string away.

**Comment by ilovezfs** [comment]
>Holy shit, I should optimize that version string away.

I highly recommend it. That alone should be enough to prevent carpal tunnel syndrome.

**Comment by zmwangx** [comment]
Yeah. In fact what's better is having nothing to type. I was planning to further streamline the process through a cron script that automatically raises PRs whenever a new version is detected for one of those formulae that hardly ever required human intervention. It will be running on the DO droplet that is currently shooting me emails when new versions are detected. I just haven't got to that yet.

**Pull request merged**
