### PR TITLE
yarn: fix global installation prefix

### PR DESCRIPTION
**Pull request by chrmoritz**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Refs: #16083

This PR fixes `yarn`'s global installation prefix by using env wrapper scripts to set the correct PREFIX environment variable pointing to `HOMEBREW_PREFIX`. Previously the yarn global prefix was incorrectly auto-detected as `HOMEBREW_PREFIX/Cellar/node/<version>/bin` and global yarn modules got symlinked next to the node executable in node's own cellar. This has caused 2 issues: modules globally installed with yarn where not put into the users $PATH and it broke native addon installation in yarn depending formulas (see #16083 for for details).

`fsevents` usage in core formulas depending on `yarn` (checked = build tested with a fixed `yarn`)
* [x] `chronograf`: yes, only in build deps
* [x] `grafana`: yes, only in build deps
* [x] `metabase`: yes, only in build deps
* `lumo`: no

### CODE REVIEW

**Comment by ilovezfs** [comment]
One concern I have is whether this will create problems for users who are already setting `PREFIX` for yarn in their environment to some other value.

**Comment by chrmoritz** [comment]
The [recommended/documented way for setting yarns global prefix](https://yarnpkg.com/en/docs/cli/global#defining-install-location) is using `yarn config set prefix <path>`, which writes to `~/.yarnrc` and still takes preference over setting the `PREFIX` env variable.

User of the undocumented `$PREFIX` would be indeed affected by this change, but they would have at least a official way to restore their old behavior using yarn config.

**Comment by ilovezfs** [comment]
Cool. Mind revision bumping this too?

**Comment by chrmoritz** [comment]
Added a revision bump and a devel version for 0.28.4.

**Comment by ilovezfs** [comment]
Thanks @chrmoritz!

**Comment by danez** [comment]
This breaks nvm in certain situations because now every script I run via yarn has `$PREFIX` set, but NVM throws if this is set.
My example would be a nodejs script which gets called via `yarn run`. This script is spawning "git commit" and forwarding all process.env to it. The precommit hook tries to enable nvm which throws.

For now I uninstalled yarn and installed it with the install script instead of brew.

**Pull request merged**
