### PR TITLE
cbmc 6.3.1

### PR DESCRIPTION
**Pull request by db-ci-cprover**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tautschnig** [comment]
Thank you @carlocab for adding the reverted patch, was about to create a PR that has that revert!

**Review by iMichka — APPROVED** [review]

**Comment by tautschnig** [comment]
What to make of
```
==> Fetching Homebrew/core...
fatal: remote error: upload-pack: not our ref 3bd3163d97052ef6428d9888fe8c0a86d7fbd3d9
fatal: remote error: upload-pack: not our ref 3bd3163d97052ef6428d9888fe8c0a86d7fbd3d9
fatal: remote error: upload-pack: not our ref 3bd3163d97052ef6428d9888fe8c0a86d7fbd3d9
fatal: remote error: upload-pack: not our ref 3bd3163d97052ef6428d9888fe8c0a86d7fbd3d9
fatal: remote error: upload-pack: not our ref 3bd3163d97052ef6428d9888fe8c0a86d7fbd3d9
fatal: remote error: upload-pack: not our ref 3bd3163d97052ef6428d9888fe8c0a86d7fbd3d9
fatal: remote error: upload-pack: not our ref 3bd3163d97052ef6428d9888fe8c0a86d7fbd3d9
fatal: remote error: upload-pack: not our ref 3bd3163d97052ef6428d9888fe8c0a86d7fbd3d9
fatal: remote error: upload-pack: not our ref 3bd3163d97052ef6428d9888fe8c0a86d7fbd3d9
fatal: remote error: upload-pack: not our ref 3bd3163d97052ef6428d9888fe8c0a86d7fbd3d9
Error: The process '/bin/bash' failed with exit code 128
```
?

**Comment by tautschnig** [comment]
Now I'm confused about the job statuses here, could anyone advise?

**Comment by carlocab** [comment]
Seems like the jobs didn't run. Restarted them now.

**Pull request merged**
