### PR TITLE
yarn 1.9.2

### PR DESCRIPTION
**Pull request by zebastiane**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@Daniel15 any idea what happened with the upstream PR not getting opened? Maybe 🤖 failed.

**Comment by Daniel15** [comment]
There was some issue with our tooling, so @arcanis had to manually bump this version from RC to latest, which doesn't kick off any of the post release jobs (like pushing to Homebrew and Chocolatey). I'm currently on vacation but I'll look into it once I'm back.

**Comment by thedoctor** [comment]
_eagerly awaits this merge for CI reasons_

**Comment by ilovezfs** [comment]
Thanks for the PR @zebastiane! Merged.

@Daniel15 Ah, OK. Enjoy your vacation!

**Pull request merged**
