### PR TITLE
boost 1.83

### PR DESCRIPTION
**Pull request by iMichka**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

Taking over from #139380, to benefit from the build cache for this complex PR.

### CODE REVIEW

**Comment by fxcoudert** [comment]
- `votca`: ChangeLog part of patch does not apply, this should work: https://github.com/Homebrew/formula-patches/blob/81862a091ac2fc2df5c5d79a28bb95fee0a67e7c/votca/boost-1.83.patch
- `upscaledb`: not actively maintained, needs lots of patches. Try to see if it builds by passing `BOOST_TIMER_ENABLE_DEPRECATED`, otherwise deprecate it?

**Comment by iMichka** [comment]
Yes the new `votca` patch should work. Thanks will push the fix.

Given https://github.com/cruppstahl/upscaledb/issues/134, I will deprecate `upscaledb`. I think the ranlib issue is not a boost issue, but the issue we had with Xcode 14 were there is a mixup with .a / .la files.

**Comment by SMillerDev** [comment]
`graph-tool` seems to be failing on Linux because it tries to build patchelf and some other things Homebrew provides

**Comment by SMillerDev** [comment]
If this run stays with just `cucumber-cpp` on macOS and `graph-tool` on Linux, I think we should just merge it.

**Review by SMillerDev — APPROVED** [review]
I think this can be merged

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
let's ship it. 🚀

**Comment by chenrui333** [comment]
for graphql-tool linux build, it can be followed up with https://github.com/Homebrew/homebrew-core/pull/150091

**Comment by ZhongRuoyu** [comment]
Rebased due to `redex` conflict.

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
regression works fine for me
```
==> Testing redex
==> /opt/homebrew/Cellar/redex/2017.10.31_13/bin/redex --ignore-zipalign redex-test.apk -o redex-test-out.apk
```

**Pull request merged**
