### PR TITLE
bluepill 5.4.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
2020-07-04 01:24:07.068 xcodebuild[2588:5134538] Couldn't create intermediates directory: You don’t have permission to save the file “Intermediates.noindex” in the folder “Build”.
2020-07-04 01:24:08.280 xcodebuild[2588:5134538] [MT] IDELogStore: Failed to open log store at /Users/brew/Library/Developer/Xcode/DerivedData/Bluepill-adeyatilsoaxvafrtwvnzrgyfrab/Logs/Test
2020-07-04 01:24:08.280 xcodebuild[2588:5134538] [MT] IDELogStore: Failed to open Test log store: Error Domain=IDEFoundationErrorDomain Code=1 "Unable to create log store directory at '/Users/brew/Library/Developer/Xcode/DerivedData/Bluepill-adeyatilsoaxvafrtwvnzrgyfrab/Logs/Test': (513) You don’t have permission to save the file “Test” in the folder “Logs”." UserInfo={NSLocalizedDescription=Unable to create log store directory at '/Users/brew/Library/Developer/Xcode/DerivedData/Bluepill-adeyatilsoaxvafrtwvnzrgyfrab/Logs/Test': (513) You don’t have permission to save the file “Test” in the folder “Logs”.}. User info: {
    NSLocalizedDescription = "Unable to create log store directory at '/Users/brew/Library/Developer/Xcode/DerivedData/Bluepill-adeyatilsoaxvafrtwvnzrgyfrab/Logs/Test': (513) You don\U2019t have permission to save the file \U201cTest\U201d in the folder \U201cLogs\U201d.";
}.
Build Preparation
Couldn't create workspace arena folder '/Users/brew/Library/Developer/Xcode/DerivedData/Bluepill-adeyatilsoaxvafrtwvnzrgyfrab': You don’t have permission to save the file “Bluepill-adeyatilsoaxvafrtwvnzrgyfrab” in the folder “DerivedData”.
```

**Comment by SeekingMeaning** [comment]
Might be fixable with something like:

```ruby
args << "-UseNewBuildSystem=NO" if MacOS::Xcode.version >= "10.0"
```

Sources:

- https://trac.macports.org/ticket/57204
- https://github.com/macports/macports-ports/blob/master/aqua/aquaterm/Portfile

**Comment by chenrui333** [comment]
Local build works for me as well (mojave, xcode 11.2)

**Comment by chenrui333** [comment]
local build on Mojave machine is fine.

```
CodeSign /tmp/bluepill-20200705-60634-1umdzs1/Release/bp (in target 'bp' from project 'bp')
    cd /tmp/bluepill-20200705-60634-1umdzs1/bp
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate

Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --entitlements /Users/rchen/Library/Developer/Xcode/DerivedData/Bluepill-femavkgmctrqbucjaoztgpspjcbf/Build/Intermediates.noindex/bp.build/Release/bp.build/bp.xcent --timestamp=none /tmp/bluepill-20200705-60634-1umdzs1/Release/bp

** BUILD SUCCEEDED **

NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.
==> Cleaning
==> Finishing up
ln -s ../Cellar/bluepill/5.4.1/bin/bluepill bluepill
ln -s ../Cellar/bluepill/5.4.1/bin/bp bp
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200705-60863-vg77a1.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bluepill.rb
NOTE:  Most system logs have moved to a new logging system.  See log(1) for more information.
```

**Comment by SeekingMeaning** [comment]
I think I figured it out: homebrew/brew#7897

It appears that this specific change breaks formulae that use xcodebuild:

```patch
   # Xcode projects expect access to certain cache/archive dirs.
   def allow_write_xcode
-    allow_write_path "/Users/#{ENV["USER"]}/Library/Developer"
+    allow_write_path "#{ENV["HOME"]}/Library/Developer"
   end
```

**Comment by SeekingMeaning** [comment]
Rebase?

**Comment by chenrui333** [comment]
Sure, doing that now.

**Comment by chenrui333** [comment]
Thanks @SeekingMeaning!!

**Pull request closed without merging**
