### PR TITLE
semgrep 1.28.0

### PR DESCRIPTION
**Pull request by semgrep-release**
Bump semgrep to version 1.28.0

### CODE REVIEW

**Comment by spencerdrak** [comment]
It appears that this this was a timeout of the build at the ~90 min mark, is that correct? If any other action is needed on our part, happy to address it.

**Comment by chenrui333** [comment]
> It appears that this this was a timeout of the build at the ~90 min mark, is that correct? If any other action is needed on our part, happy to address it.

yeah, just some timeout, which happened before.

**Comment by p-linnane** [comment]
Rebased to deal with a rubocop change.

**Review by chenrui333 — APPROVED** [review]

**Comment by p-linnane** [comment]
@spencerdrak I've opened a pr (https://github.com/Homebrew/homebrew-core/pull/134553) which will automatically label `semgrep` PR's with the https://github.com/Homebrew/homebrew-core/labels/long%20build label. This will prevent the builds from starting until we have an available https://github.com/Homebrew/homebrew-core/labels/CI-long-timeout label to successfully complete the run.

**Pull request merged**
