### PR TITLE
truetree 0.7 (new formula)

### PR DESCRIPTION
**Pull request by x13a**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by x13a** [comment]
Patch is submitted: https://github.com/themittenmac/TrueTree/pull/12

**Comment by chenrui333** [comment]
need a new release for that patch.

**Comment by x13a** [comment]
> a new release

and if the author is unreachable in timely manner, can we merge it with a patch?

**Comment by SMillerDev** [comment]
> and if the author is unreachable in timely manner, can we merge it with a patch?

That would be a good reason to avoid merging it altogether, since software should be maintained to be in Homebrew/core

**Comment by chenrui333** [comment]
@x13a upstream has made a new release, https://github.com/themittenmac/TrueTree/releases/tag/V0.8, can you file a new PR and give another shot? Thanks!

**Comment by x13a** [comment]
> can you file a new PR and give another shot?

ok

**Pull request closed without merging**
