### PR TITLE
infracost 0.6.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by aliscott** [comment]
@chenrui333 I've sent a PR to your branch to fix the version and tests.

**Comment by aliscott** [comment]
Test failure looks like an unrelated network issue?
```
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining
```

**Comment by aliscott** [comment]
@chenrui333 are you able to re-run the failing check? It looks like it hit a network issue with GitHub.

**Comment by chenrui333** [comment]
yeah, rerunning. no worries.

**Comment by aliscott** [comment]
@chenrui guessing the failures are due to https://github.com/Homebrew/homebrew-core/issues/61772 so assuming this will have to wait for it to be fixed on GitHub's end?

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
