### PR TITLE
ponyc: depend on llvm@3.9

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

CC @SeanTAllen

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
==> make config=release destdir=/usr/local/Cellar/ponyc/0.11.3_1 install verbose=1
make: /usr/local/opt/llvm@3.9/bin/llvm-config-3.9: Command not found
Makefile:225: WARNING: Unsupported LLVM version: 
Makefile:226: Please use LLVM 3.7.1, 3.8.1, or 3.9.1
```

**Comment by ilovezfs** [comment]
hm

**Comment by ilovezfs** [comment]
Oh of course.

**Comment by ilovezfs** [comment]
@SeanTAllen shipped

**Comment by SeanTAllen** [comment]
thank you

**Comment by ilovezfs** [comment]
You're welcome.

**Pull request closed without merging**
