### PR TITLE
mariadb 10.4.8

### PR DESCRIPTION
**Pull request by andyli**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by fxcoudert** [comment]
```
Undefined symbols for architecture x86_64:
  "_BIO_free", referenced from:
      _auth_sha256_client in sha256_pw.c.o
  "_BIO_new_mem_buf", referenced from:
      _auth_sha256_client in sha256_pw.c.o
  "_ERR_clear_error", referenced from:
      _auth_sha256_client in sha256_pw.c.o
  "_PEM_read_bio_RSA_PUBKEY", referenced from:
      _auth_sha256_client in sha256_pw.c.o
  "_RSA_free", referenced from:
      _auth_sha256_client in sha256_pw.c.o
  "_RSA_public_encrypt", referenced from:
      _auth_sha256_client in sha256_pw.c.o
  "_RSA_size", referenced from:
      _auth_sha256_client in sha256_pw.c.o
```

**Comment by SMillerDev** [comment]
Why can't it work with the default openssl?

**Comment by andyli** [comment]
Not sure, but I've just reported it in https://jira.mariadb.org/browse/MDEV-20779

**Comment by Bo98** [comment]
The issue has been fixed upstream: https://github.com/MariaDB/mariadb-connector-c/commit/ee91b2c98a63acb787114dee4f2694e154630928

Though it's not released yet - I'm not sure when it will be.

**Comment by fxcoudert** [comment]
> The issue has been fixed upstream

We could carry this patch and ship this version.

**Comment by Bo98** [comment]
I was about to go ahead and start the process of doing so, but I've noticed that CVEs have just been published for 10.4.9 so perhaps I'll wait a couple days as there may be a release imminent. This issue has been blocking various MariaDB formulae from updating and there's security fixes we're missing out on so I won't wait longer than that.

**Comment by Bo98** [comment]
mariadb: #46342
mariadb@10.3: #46341
mariadb@10.2: #46340
mariadb@10.1: #46339
mariadb@10.0: EOL - suggested to remove #46338
mariadb-connector-c: pending 3.1.5 release - should be this week hopefully
mariadb-connector-odbc: runs on a different release schedule

**Comment by fxcoudert** [comment]
@Bo98 for some reason most of these URLs return 404

**Comment by Bo98** [comment]
It's because MariaDB has tons of mirrors and some are slow at updating. It picks a random mirror each time you hit the URL.

If you rerun the tests they will eventually work - they all seemed to work first time for me locally but I guess I was lucky.

I've looked at a couple of the logs again just now and a couple of them are working now. I imagine many more mirrors will start working around now as we head into overnight US time.

**Comment by Bo98** [comment]
To give you a picture, here's me looking at the mirrors which failed before:

* http://mirrors.ukfast.co.uk/sites/mariadb//mariadb-10.4.9/source/mariadb-10.4.9.tar.gz - now working
* http://nyc2.mirrors.digitalocean.com/mariadb//mariadb-10.4.9/source/mariadb-10.4.9.tar.gz - now working
* http://ftp.igh.cnrs.fr/pub/mariadb//mariadb-10.4.9/source/mariadb-10.4.9.tar.gz - now working
* http://mirror.netcologne.de/mariadb//mariadb-10.4.9/source/mariadb-10.4.9.tar.gz - now working
* http://mirror.biznetgio.com/mariadb//mariadb-10.4.9/source/mariadb-10.4.9.tar.gz - server is down entirely (timeout)
* http://mirror.jaleco.com/mariadb//mariadb-10.3.19/source/mariadb-10.3.19.tar.gz - NOT working
* http://ftp.nluug.nl/db/mariadb//mariadb-10.3.19/source/mariadb-10.3.19.tar.gz - now working
* http://mirror.kku.ac.th/mariadb//mariadb-10.3.19/source/mariadb-10.3.19.tar.gz - NOT working
* http://espejito.fder.edu.uy/mariadb//mariadb-10.3.19/source/mariadb-10.3.19.tar.gz - now working
* http://mirrors.n-ix.net/mariadb//mariadb-10.3.19/source/mariadb-10.3.19.tar.gz - NOT working
* http://mirror.aarnet.edu.au/pub/MariaDB//mariadb-10.2.28/source/mariadb-10.2.28.tar.gz - NOT working
* http://ftp.hosteurope.de/mirror/mariadb.org//mariadb-10.2.28/source/mariadb-10.2.28.tar.gz - now working
* https://mirror.serverion.com/mariadb/mariadb-10.2.28/source/mariadb-10.2.28.tar.gz - now working
* http://ftp.bme.hu/pub/mirrors/mariadb//mariadb-10.2.28/source/mariadb-10.2.28.tar.gz - now working
* http://mariadb.mirror.iweb.com//mariadb-10.1.42/source/mariadb-10.1.42.tar.gz - NOT working
* http://download.nus.edu.sg/mirror/mariadb//mariadb-10.1.42/source/mariadb-10.1.42.tar.gz - now working
* http://ftp.hosteurope.de/mirror/mariadb.org//mariadb-10.1.42/source/mariadb-10.1.42.tar.gz - now working

The Mojave buildbot managed to build MariaDB 10.1 at least.

**Pull request closed without merging**
