### PR TITLE
pick 1.5.0

### PR DESCRIPTION
**Pull request by fornwall**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --new-formula <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by fornwall** [comment]
Hm, the tests pass for me locally. Perhaps the test uses something that's not installed in the CI environment? Looking into it.

**Comment by apjanke** [comment]
Test is passing now. Maybe a transient problem with the CI? Do you mind taking the debugging code back out to see if it works now, and so we can grab a copy of the test failures if they happen?

**Comment by fornwall** [comment]
@apjanke Thanks! I backed it out and it seems to fail. I'm not used to jenkins, can you find the test-suite.log file generated by the test run?

**Comment by apjanke** [comment]
Build failure is [here](https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/8125/). Clicking on "Details" under "All checks have failed" will get you to that page. Then click on the OS you're interested in (generally, any will do) and scroll to the bottom; it will link you to logs from the test failures there.

[Here](https://gist.github.com/apjanke/5519a185743e63d545a55992268bfdad) is a copy of the failure log as a gist.

The build runs but then all the tests fail. Maybe it's something about running under the test-bot environment? Odd that that would show up just this version, though.

**Comment by mptre** [comment]
Could the contents of `test-suite.log` be dumped on failure to aid debugging?

```sh
make check || cat test-suite.log
```

**Comment by fornwall** [comment]
I've changed

    system "make", "check"

to

    system "make check || (cat test-suite.log && exit 1)"

which I guess make sense to have anyway. The error causing the tests to fail seems to be:

    /dev/tty: Device not configured

**Comment by mptre** [comment]
Did this ever work? Does `sandbox-exec` prohibit read/write from
`/dev/tty`?

**Comment by apjanke** [comment]
@BrewTestBot test this please

**Comment by fornwall** [comment]
Closing this one in favour of https://github.com/Homebrew/homebrew-core/pull/5608

**Pull request closed without merging**
