### PR TITLE
openjdk 18; openjdk@17 17.0.2 (new formula)

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks may require updates.

### CODE REVIEW

**Comment by Bo98** [comment]
`openjdk@17` can also stay around as a LTS-supported release.

**Comment by bayandin** [comment]
Yep, I will push`openjdk@17` and fix for `micronauts` (and probably `derby`).

Meanwhile, is there any ideas on what to do with `lcm`?
```
==> brew linkage --cached --test --strict lcm
==> FAILED
Full linkage --cached --test --strict lcm output
  Files with missing rpath:
    /opt/homebrew/Cellar/lcm/1.4.0_6/bin/lcm-logger
    /opt/homebrew/Cellar/lcm/1.4.0_6/bin/lcm-logplayer
    /opt/homebrew/Cellar/lcm/1.4.0_6/lib/lua/5.4/lcm.so
```

**Comment by cho-m** [comment]
> Meanwhile, is there any ideas on what to do with `lcm`?

That's unrelated and can be fixed outside PR.
Probably need to set `CMAKE_INSTALL_RPATH` like in #96793, but we have been rebuilding bottles rather than revision bumping.

**Comment by cho-m** [comment]
`11-arm64`-only failure for `openjdk@17`:
```
  checking if static build is enabled... disabled, default
  configure: xcodebuild output: objc[27541]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1fb26f788) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10d1182b8). One of the two will be used. Which one is undefined.
  configure: error: Failed to determine Xcode version.
  /private/tmp/openjdkA17-20220324-26344-1iex7et/jdk17u-jdk-17.0.2-ga/build/.configure-support/generated-configure.sh: line 84: 5: Bad file descriptor
  configure exiting with result code 1
```

Odd since it built previously. XCode is same as Intel Monterey.

**Comment by Bo98** [comment]
That is fixed in 17.0.3 by https://github.com/openjdk/jdk17u-dev/commit/c36c1c2213f0ce92eed1dd3ed994d0309c4cc3d8

**Comment by cho-m** [comment]
Other failures:
- [ ] `jython` (10.15)
    ```
    ==> /usr/local/Cellar/jython/2.7.2/bin/jython -c "from java.util import Date; print Date()"
      No Java runtime present, requesting install.
    ``` 
- [ ]  `opensearch` (10.15, 11) - on side note **(not related to failure)**, Homebrew install version has SNAPSHOT in name. Not sure if this is intended, but this makes OpenSearch think it is running a pre-release
    ```
    [2022-03-25T01:17:44,143][INFO ][o.o.n.Node               ] [BigSur] node name [BigSur], node ID [GiNPB0dCSUaQYLM-aKW2FQ], cluster name [opensearch_homebrew], roles [master, remote_cluster_client, data, ingest]
      ==> curl -s -XGET localhost:60913/
      
      Killing child processes...
    ``` 
- [ ] `trino` (10.15, 11) - based on logs, may need to increase timeout in separate PR.
  ```
  2022-03-25T03:16:12.022Z	INFO	main	io.trino.server.PluginManager	Registering resource group configuration manager db
  2022-03-25T03:16:12.023Z	INFO	main	io.trino.server.PluginManager	-- Finished loading plugin /private/tmp/trino-test-20220325-56018-b2sop2/plugin/resource-group-managers --
  2022-03-25T03:16:12.023Z	INFO	main	io.trino.server.PluginManager	-- Loading plugin /private/tmp/trino-test-20220325-56018-b2sop2/plugin/session-property-managers --
  Query 20220325_031611_00000_45w2u failed: Trino server is still initializing
  io.trino.spi.TrinoException: Trino server is still initializing
  	at io.trino.security.AccessControlManager$InitializingSystemAccessControl.delegate(AccessControlManager.java:1321)
  ```

**Comment by bayandin** [comment]
It looks like all `jython`, `opensearch`, and `trino` failures are preexistent.

Regarding `jython`, for some reason, the `jython` script is wrapped in `write_env_script` with JAVA_HOME (when installed from the bottle on Catalina).

**Comment by cho-m** [comment]
Failures are expected for `jetty` (Linux) and `jython` (Catalina).

Looks like `jython` issue is due to Catalina bottle existing prior to `openjdk` dependency & ENV script fix https://github.com/Homebrew/homebrew-core/commit/0e3e8be13f0bcec89f7762b7d13f9409b1c5e4d0. Also, the existing bottles (including Monterey) are set up to use Python 2, so they may be broken on fresh Monterey without Python 2.

**Comment by SMillerDev** [comment]
@cho-m and @bayandin do you feel this is good to merge?

**Review by cho-m — DISMISSED** [review]
LGTM.

**Comment by bayandin** [comment]
@SMillerDev go for it!

**Comment by EricFromCanada** [comment]
For the next versions of v17 & v18 of OpenJDK, I suggest adding `depends_on :xcode` since they expect to be able to use `metal`:
```
...
checking for metal... [not found]
checking if metal can be run using xcrun... no
configure: error: XCode tool 'metal' neither found in path nor with xcrun
```

**Comment by SMillerDev** [comment]
That seems like a very heavy dependency for Java though.

**Comment by EricFromCanada** [comment]
The alternative being to somehow disable its `metal` requirement. I didn't see any obvious configure flags, though.

**Comment by SMillerDev** [comment]
Maybe a build dependency will be enough. Might be good to do that change async from the Java releases though to make sure it's not blocking those

**Pull request closed without merging**
