### PR TITLE
llvm: add flang

### PR DESCRIPTION
**Pull request by tschoonj**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by fxcoudert** [comment]
> Flang is still a work in progress for this release and is included for experimentation and feedback

As far as I understand, Flang is currently an experimental project, and not a standalone compiler. From the release notes:

> Flang is able to parse a comprehensive subset of the Fortran language and check it for correctness. Flang is not yet able to generate LLVM IR for the source code and thus is unable to compile a running binary.
> By default, Flang will parse the Fortran file hello.f90 then unparse it to a canonical Fortran source file. Flang will then invoke an external Fortran compiler to compile this source file and link it, placing the resulting executable in hello.bin.

which means we would need to make `llvm` depend on `gcc`, which I don't think is desirable.

**Comment by fxcoudert** [comment]
Build failure on 10.13:

```
2020-10-18T18:00:28.2156130Z In file included from /tmp/llvm-20201018-2919-1hlerwe/llvm-project-11.0.0/flang/runtime/io-api.cpp:12:
2020-10-18T18:00:28.2158130Z In file included from /tmp/llvm-20201018-2919-1hlerwe/llvm-project-11.0.0/flang/runtime/edit-input.h:13:
2020-10-18T18:00:28.2161200Z /tmp/llvm-20201018-2919-1hlerwe/llvm-project-11.0.0/flang/runtime/io-stmt.h:65:12: error: cannot initialize return object of type 'Fortran::runtime::io::OpenStatementState *' with an rvalue of type 'decltype(auto)'
2020-10-18T18:00:28.2162430Z     return std::visit(
2020-10-18T18:00:28.2162980Z            ^~~~~~~~~~~
2020-10-18T18:00:28.2164600Z /tmp/llvm-20201018-2919-1hlerwe/llvm-project-11.0.0/flang/runtime/io-stmt.h:65:12: error: call to unavailable function 'visit': introduced in macOS 10.14
2020-10-18T18:00:28.2165560Z     return std::visit(
2020-10-18T18:00:28.2165850Z            ^~~~~~~~~~
2020-10-18T18:00:28.2168600Z /tmp/llvm-20201018-2919-1hlerwe/llvm-project-11.0.0/flang/runtime/io-api.cpp:724:22: note: in instantiation of function template specialization 'Fortran::runtime::io::IoStatementState::get_if<Fortran::runtime::io::CloseStatementState>' requested here
2020-10-18T18:00:28.2170370Z   if (auto *close{io.get_if<CloseStatementState>()}) {
2020-10-18T18:00:28.2170960Z                      ^
2020-10-18T18:00:28.2182360Z /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/variant:1524:26: note: candidate function [with _Visitor = (lambda at /tmp/llvm-20201018-2919-1hlerwe/llvm-project-11.0.0/flang/runtime/io-stmt.h:66:9), _Vs = <const std::__1::variant<std::__1::reference_wrapper<Fortran::runtime::io::OpenStatementState>, std::__1::reference_wrapper<Fortran::runtime::io::CloseStatementState>, std::__1::reference_wrapper<Fortran::runtime::io::NoopCloseStatementState>, std::__1::reference_wrapper<Fortran::runtime::io::InternalFormattedIoStatementState<Direction::Output> >, std::__1::reference_wrapper<Fortran::runtime::io::InternalFormattedIoStatementState<Direction::Input> >, std::__1::reference_wrapper<Fortran::runtime::io::InternalListIoStatementState<Direction::Output> >, std::__1::reference_wrapper<Fortran::runtime::io::InternalListIoStatementState<Direction::Input> >, std::__1::reference_wrapper<Fortran::runtime::io::ExternalFormattedIoStatementState<Direction::Output> >, std::__1::reference_wrapper<Fortran::runtime::io::ExternalFormattedIoStatementState<Direction::Input> >, std::__1::reference_wrapper<Fortran::runtime::io::ExternalListIoStatementState<Direction::Output> >, std::__1::reference_wrapper<Fortran::runtime::io::ExternalListIoStatementState<Direction::Input> >, std::__1::reference_wrapper<Fortran::runtime::io::UnformattedIoStatementState<Direction::Output> >, std::__1::reference_wrapper<Fortran::runtime::io::UnformattedIoStatementState<Direction::Input> >, std::__1::reference_wrapper<Fortran::runtime::io::ExternalMiscIoStatementState> > &>] has been explicitly made unavailable
2020-10-18T18:00:28.2191580Z constexpr decltype(auto) visit(_Visitor&& __visitor, _Vs&&... __vs) {
2020-10-18T18:00:28.2192050Z                          ^
```

**Comment by tschoonj** [comment]
I didn't realise that it depended on `gfortran` to do the actual compilation. Disappointing...

Under these circumstances, I agree that there's no reason to add it to the formula.

**Comment by carlocab** [comment]
@tschoonj 

The llvm formula has been updated to include mlir, so flang now builds for me using [this formula](https://github.com/carlocab/homebrew-personal/blob/main/Formula/flang.rb) on my tap: 
```
brew install carlocab/personal/flang
```
It takes a horrendously long time, so I suggest passing the `-v` flag. It won't make it go any faster, but it made waiting for it more bearable for me for some reason. Ninja also seemed faster than make, but I don't mind changing it back to make if you have a strong opinion about it.

**Comment by tschoonj** [comment]
Thanks for the update, but flang is pretty useless at this point as it just sends everything through to gfortran, assuming it managed to parse the source code.

**Comment by carlocab** [comment]
Yes, it's not able to compile/link code yet, but it can still do some things (which admittedly in my limited view aren't really that practical, but I don't think I did this for practical reasons anyway).

**Pull request closed without merging**
