### PR TITLE
ta-lib 0.6.0

### PR DESCRIPTION
**Pull request by mario4tier**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  /opt/homebrew/Cellar/automake/1.17/share/aclocal-1.17/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
  configure.ac:10: the top level
  autom4te: error: /opt/homebrew/opt/m4/bin/m4 failed with exit status: 1
  aclocal: error: /opt/homebrew/Cellar/autoconf/2.72/bin/autom4te failed with exit status: 1
  autoreconf: error: aclocal failed with exit status: 1
```

**Comment by mario4tier** [comment]
ta-lib 0.6.1 has now a fix for the missing VERSION file in src.tar.gz  

Will open a new PR for 0.6.1

Thanks!

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/202273

**Comment by chenrui333** [comment]
Thanks @mario4tier!

**Pull request closed without merging**
