### PR TITLE
next-ls 0.10.3 (new formula)

### PR DESCRIPTION
**Pull request by mhanberg**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  --> Generating wrapper metadata file...
  ** (MatchError) no match of right hand side value: {"", 137}
      (burrito 0.8.0) lib/steps/build/pack_and_build.ex:67: Burrito.Steps.Build.PackAndBuild.create_metadata_file/3
      (burrito 0.8.0) lib/steps/build/pack_and_build.ex:19: Burrito.Steps.Build.PackAndBuild.execute/1
      (burrito 0.8.0) lib/builder/builder.ex:139: anonymous fn/3 in Burrito.Builder.run_phase/2
      (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
      (elixir 1.15.4) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
      (burrito 0.8.0) lib/builder/builder.ex:88: Burrito.Builder.build/1
      (mix 1.15.4) lib/mix/tasks/release.ex:1064: Mix.Tasks.Release.run_steps/1
      (mix 1.15.4) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
```

**Comment by mhanberg** [comment]
So, two problems.

1) Locally at least, `epmd` will open a macOS dialog that prompts the user to allow the exe to accept incoming connections. could this be happening in the CI and obviously no one is there to click anything?

2) the macos 11 runner seems to not have enough memory. It's failing when we run `zig version` to get the zig version. What is the workaround? can I exclude macos 11 from the formula? Must i instead submit a cask that downloads the prebuilt binaries from my GitHub releases?

**Comment by SMillerDev** [comment]
> Locally at least, epmd will open a macOS dialog that prompts the user to allow the exe to accept incoming connections. could this be happening in the CI and obviously no one is there to click anything?

Could be, although that depends on the firewall settings AFAIK.

> the macos 11 runner seems to not have enough memory. It's failing when we run zig version to get the zig version. What is the workaround?

That seems unlikely since that's the only one that runs unvirtualized AFAIK. Could you try running `zig version` in the test and see if it fails?
> can I exclude macos 11 from the formula? 

You could, but preferably not.
> Must i instead submit a cask that downloads the prebuilt binaries from my GitHub releases?

I'd rather exclude macOS 11, but either way [We frown on authors submitting their own work unless it is very popular.](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff)

**Comment by mhanberg** [comment]
Going to go ahead with my own tap for now, thanks for your time!

**Comment by mhanberg** [comment]
As I was setting up a tap for this formula, I still wanted to get the test passing for the future if someone else adds it to homebrew-core.

I learned that the problem was 1) I needed to set erlang as a runtime dependency and not only as a build dependency, because we use `epmd` which is included by the homebrew formula, and potentially I also needed to call epmd as `"#{Formula["erlang"].prefix}/bin/epmd"`

**Pull request closed without merging**
