### PR TITLE
neovim 0.9.5

### PR DESCRIPTION
**Pull request by clason**
Created with `brew bump-formula-pr`.

- [x] `resource` blocks have been checked for updates.
<details>
  <summary>release notes</summary>
  <pre>```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
```
This is a maintenance release, focusing on bugfixes.
Notably, fixes were made for issues with using and testing Nvim on less common platforms, like big endian platforms.

### Bug Fixes
- **defaults**: Set 'fsync' #26039
- Dont create data dir if it's a broken symlink
- Make InspectTree handle nested injection
- Remove nested for_each_tree in TSTreeView (#26331)
- **api**: Use a conditional stack for nvim_cmd
- **change**: Update fold after on_bytes
- **deps**: Bump libmpack from luarocks
- **extmark_to_array**: Convert conceal_char to bytes
- **highlight**: Apply 'winblend' to float border
- **inccommand**: Save and restore '[ and '] marks
- **inccommand**: Don't crash with "split" and 'n' flag
- **lsp**: Handle NUL bytes in popup text
- **lua**: Correct return value for on_key with no arguments
- **lua**: Crash in nlua_error
- **man**: Make :Man with a range work
- **mappings**: Fix mapset() not replacing map with backslash
- **marks**: Handle switching buffer properly
- **mouse**: Avoid dragging after click label popupmenu callback
- **mouse**: Avoid dragging when clicking next to popupmenu
- **move**: Check the correct buffer
- **oldtest**: Always use a 64-bit int for swapfile block number
- **options**: Setting 'scroll' with resized grid
- **quickfix**: Check if delete failed in qf_fill_buffer()
- **set_bool_option**: Use int value to make bool Object
- **set_option_from_tv**: Use v_bool to access boolean option
- **terminal**: Assign channel to terminal earlier
- **terminal**: Avoid Insert mode in Terminal buffer
- **terminal**: Don't lose focus on <MouseMove>
- **terminal**: Keep focus when scrolling number column of another window
- **terminal**: Make backslashes in 'shell' work on Windows
- **treesitter**: Foldexpr tweaks
- **treesitter**: Remove incompatible c query (again)
- **ui**: Empty line before the next message after :silent command

### Build System
- Fix universal mac builds
- **ci**: Ensure correct headers are used on macOS


### Documentation
- List NVIM_APPNAME as env on manpage
- **starting.txt**: Correct step number

### Performance
- Remove redundant strlen in skipwhite

### Testing
- Fix dependencies between test cases and test flakiness

## Install

### Windows

#### Zip

1. Download **nvim-win64.zip**
2. Extract the zip
3. Run `nvim-qt.exe`

#### MSI

1. Download **nvim-win64.msi**
2. Run the MSI
3. Search and run `nvim-qt.exe` or run `nvim.exe` on your CLI of choice

### macOS

1. Download **nvim-macos.tar.gz**
2. Run `xattr -c ./nvim-macos.tar.gz` (to avoid "unknown developer" warning)
3. Extract: `tar xzvf nvim-macos.tar.gz`
4. Run `./nvim-macos/bin/nvim`

### Linux (x64)

#### AppImage
1. Download **nvim.appimage**
2. Run `chmod u+x nvim.appimage && ./nvim.appimage`
   - If your system does not have FUSE you can [extract the appimage](https://github.com/AppImage/AppImageKit/wiki/FUSE#type-2-appimage):
     ```
     ./nvim.appimage --appimage-extract
     ./squashfs-root/usr/bin/nvim
     ```

#### Tarball

1. Download **nvim-linux64.tar.gz**
2. Extract: `tar xzvf nvim-linux64.tar.gz`
3. Run `./nvim-linux64/bin/nvim`

### Other

- Install by [package manager](https://github.com/neovim/neovim/wiki/Installing-Neovim)

## SHA256 Checksums

```
44ee395d9b5f8a14be8ec00d3b8ead34e18fe6461e40c9c8c50e6956d643b6ca  nvim-linux64.tar.gz
0c82e5702af7a11fbb916a11b4a82e98928abf8266c74b2030ea740340437bf9  nvim.appimage
e3f3174d75c038915330db86bf685c704cb9be86863ee592a07e21203d32ced2  nvim.appimage.zsync
19d2366e0d6da001583bd0b8a3db59f69ce3dda5fa41f3064c6778cef3edd34c  nvim-macos.tar.gz
de6dc1f0edb45f5f225ee24ce80a4fcbc3a337932037e98ae143975fca2556bf  nvim-win64.zip
006b8578f0b6717bc5a987f12bc0746c61c20e6ba777fde6d4aa53ee54b937cd  nvim-win64.msi
```
</pre>
</details>

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by clason** [comment]
I don't understand why the neovim-qt tests fail on macOS (which apparently don't test neovim-qt itself but just neovim's remote functionality, which works fine locally).

**Comment by oneslash** [comment]
I have asked for help in the discussions forum, https://github.com/neovim/neovim/discussions/26841. I hope we will get some answer soon.

**Comment by rolfb** [comment]
Seems like the input and expected output is wrong in the tests for `neovim-qt`?

https://github.com/Homebrew/homebrew-core/blob/ea654098b199bcfd70587330704ebf56ae9ae780/Formula/n/neovim-qt.rb#L49-L51

**Comment by rolfb** [comment]
@claso Not sure if I'm following correctly, but from what I can tell the tests for `neovim-qt` are run because they depend on `neovim` and there seems to be a return guard for the tests if the OS is Linux and is running on Github Actions which mean the test which is failing on macos isn't even executed on linux?

https://github.com/Homebrew/homebrew-core/blob/ea654098b199bcfd70587330704ebf56ae9ae780/Formula/n/neovim-qt.rb#L41

**Comment by clason** [comment]
Again, that is obvious -- the question is _why_ this test is failing (and why _this_ specific test is run for neovim-qt, when all it does is exercise Neovim's remote functionality), when I cannot reproduce the failure locally.

These questions need to be answered by a homebrew/neovim-qt maintainer; guessing won't get us anywhere.

**Comment by rolfb** [comment]
@clason How does Neovim's remote functionality play into this? Did I miss something? The checks which are failing are continuous integration tests which are run on Github Actions on pull requests to this repository and it's not surprising that you are unable to reproduce it locally.

**Comment by clason** [comment]
Did you actually look at the failing neovim-qt test? (Because I did.)

**Comment by clason** [comment]
I mean the actual _test_, i.e., the steps it executes.

**Comment by rolfb** [comment]
If you have found a different error message or cause, then please share it here or provide a link?

**Comment by rolfb** [comment]
@clason nevermind, I see what you mean now. The testcommand is failing to edit the content.

**Comment by rmbrad** [comment]
The `neovim-qt` test failure seems to be related to the fsync default change in https://github.com/neovim/neovim/pull/26034. Changing this line:

https://github.com/Homebrew/homebrew-core/blob/ea654098b199bcfd70587330704ebf56ae9ae780/Formula/n/neovim-qt.rb#L56

to

```
nvimqt_pid = spawn bin/"nvim-qt", "--nofork", "--", "--listen", testserver, "--cmd", "set nofsync"
```

allows the test to pass. Moving the assert after the sending the `:q` command is sent will fix the test regardless of `fsync` setting.

**Comment by gengdz** [comment]
Who can tell me when this PR will be merged?

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @clason!

**Pull request merged**
