### PR TITLE
reminiscence 0.4.9

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
```
ogg_player.cpp:11:10: fatal error: 'stb_vorbis.c' file not found
#include "stb_vorbis.c"
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [ogg_player.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by chenrui333** [comment]
reaching out to the maintainer about the license situation (looks like no license is bundled with the artifact)

**Comment by chenrui333** [comment]
This artifact checksum instability is really weird. :(

**Comment by chenrui333** [comment]
reached to the upstream about missing the license in the distribution tarball file.

**Comment by Moisan** [comment]
I think you should add `depends_on "libvorbis"` instead of using a resource file.

**Review by Moisan — APPROVED** [review]

**Pull request closed without merging**
