### PR TITLE
terminalizer 0.7.2 (new formula)

### PR DESCRIPTION
**Pull request by curoky**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----
**Terminalizer:** Record your terminal and generate animated gif images or share a web player.

**website:** [terminalizer.com](https://terminalizer.com/)

**Github**: [faressoft/terminalizer](https://github.com/faressoft/terminalizer) GitHub stars GitHub forks

### CODE REVIEW

**Comment by fxcoudert** [comment]
It's failing on ARM because it looks like it's downloading binaries, which is not allowed in Homebrew.

**Comment by curoky** [comment]
@fxcoudert Yeah, and terminalizer depend on `electron@v7.3.3` which not support darwin-arm64. 

https://github.com/faressoft/terminalizer/blob/v0.7.2/package.json#L50
https://github.com/electron/electron/releases/tag/v7.3.3

```
npm ERR! GotError [HTTPError]: Response code 404 (Not Found) for electron/electron@v7.3.3 electron-v7.3.3-darwin-arm64.zip (download)
```

**Comment by fxcoudert** [comment]
But even on Intel, are we building electron from source or downloading it? The latter is not acceptable

**Comment by curoky** [comment]
It seems that Terminalizer does not support darwin-arm64, should we skip CI on arm64?

**Comment by fxcoudert** [comment]
We need to understand whether, on Intel, it's actually building from source or downloading binaries.

**Comment by curoky** [comment]
> But even on Intel, are we building electron from source or downloading it? The latter is not acceptable

Terminalizer is a nodejs app, not have real binary, binary is also the source.

Similar to most nodejs formulas, Terminalizer is also use [package-lock.json](https://github.com/faressoft/terminalizer/blob/v0.7.2/package-lock.json) to manange dependencies. And it has more than 750 dependencies.

**Pull request closed without merging**
