### PR TITLE
Deprecate :emacs - part1

### PR DESCRIPTION
**Pull request by ilovezfs**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dunn** [comment]
I missed this discussion.  What's the rationale?

**Comment by ilovezfs** [comment]
All requirements with a `default_formula` have been deprecated so that the bottles and source builds are more closely aligned.

**Comment by dunn** [comment]
Gotcha.  `depends_on "emacs"` is a bit unfortunate though, since even we recommend people install the Cask.

**Comment by ilovezfs** [comment]
They're all unfortunate in one or another but it's for the best :)

**Comment by ilovezfs** [comment]
@dunn any idea if we can just drop the `depends_on :emacs => :build` for nesc?

**Comment by dunn** [comment]
Don't know off the top of my head.  

Meaning let's try and see if it breaks!

**Pull request merged**
