### PR TITLE
OrientDB 2.2.7

### PR DESCRIPTION
**Pull request by robfrank**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Squash commits by running `brew update; git checkout $YOUR_BRANCH; git rebase --interactive origin/master` and then mark each commit other than the first as `squash` or `fixup` then `git push -f`. Thanks!

**Comment by apjanke** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Mike's comment needs addressing. CI can't merge this for testing as-is because it trips over.

**Comment by MikeMcQuaid** [comment]
Closing this due to no response.

**Pull request closed without merging**
