### PR TITLE
openssl@1.1 1.1.1h

### PR DESCRIPTION
**Pull request by miccal**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by miccal** [comment]
10.15 failures:
```
Error: 12 failed steps!
brew test --retry --verbose bandcamp-dl
brew test --retry --verbose bzt
brew test --retry --verbose get-flash-videos
brew install --only-dependencies komposition
brew install --only-dependencies libmspub
brew install --only-dependencies libpq
brew install --only-dependencies libxmlsec1
brew install --only-dependencies mlt
brew linkage --test mlt
brew install --only-dependencies ola
brew install --only-dependencies pangomm
brew test --retry --verbose pcl
```
&nbsp;
10.14 failures:
```
Error: 13 failed steps!
brew test --retry --verbose bandcamp-dl
brew test --retry --verbose bzt
brew test --retry --verbose get-flash-videos
brew install --only-dependencies komposition
brew install --only-dependencies libmspub
brew install --only-dependencies libpq
brew install --only-dependencies libxmlsec1
brew install --only-dependencies mlt
brew linkage --test mlt
brew install --only-dependencies ola
brew install --only-dependencies pangomm
brew test --retry --verbose pcl
brew install --only-dependencies pyqt
```
&nbsp;
10.13 failures:
```
Error: 12 failed steps!
brew test --retry --verbose bandcamp-dl
brew test --retry --verbose bzt
brew test --retry --verbose get-flash-videos
brew install --only-dependencies komposition
brew install --only-dependencies libmspub
brew install --only-dependencies libpq
brew install --only-dependencies libxmlsec1
brew install --only-dependencies mlt
brew linkage --test mlt
brew install --only-dependencies ola
brew install --only-dependencies pangomm
brew test --retry --verbose pcl
```
&nbsp;
I think the failure of `pyqt` for 10.14 was a one-off.
&nbsp;
As for the remainder:
```
bandcamp-dl
bzt
get-flash-videos
komposition
libmspub
libpq
libxmlsec1
mlt
ola
pangomm
pcl
```
I would like some advice as to if these just require a revision-bump? I do not want to trigger another CI run until necessary.

**Comment by SMillerDev** [comment]
If the errors are about linkage it's just a revision bump.

**Comment by miccal** [comment]
I successfully built `openssl@1.1` version `1.1.1h` from source locally and `brew test` passed.

I then built all the failing formula from source and ran `brew test` for each (where possible), and below are my findings.

&nbsp;

First, the good news -- `libmspub`, `libpq`, `mlt`, `pangomm` and `pcl` all successfully built from source and passed `brew test`, so these will just need a revision bump.

&nbsp;

`bandcamp-dl`, `bzt` and `get-flash-videos` built from source fine but `brew test` failed, the output of which is shown below:

For `bandcamp-dl`:
```
|-> brew test bandcamp-dl 
==> Testing bandcamp-dl
==> /usr/local/Cellar/bandcamp-dl/0.0.8-12_3/bin/bandcamp-dl --artist=iamsleepless --album=rivulets
Last 15 lines from /Users/XXX/Library/Logs/Homebrew/bandcamp-dl/test.01.bandcamp-dl:

Traceback (most recent call last):
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/bin/bandcamp-dl", line 33, in <module>
    sys.exit(load_entry_point('bandcamp-downloader==0.0.8.post12', 'console_scripts', 'bandcamp-dl')())
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/__main__.py", line 93, in main
    album = bandcamp.parse(url, True, arguments['--embed-lyrics'], arguments['--debug'])
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcamp.py", line 40, in parse
    bandcamp_json = BandcampJSON(self.soup, debugging).generate()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 25, in generate
    self.js_to_json()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 50, in js_to_json
    self.get_js()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 37, in get_js
    self.js_data = self.body.find("script", {"src": False}, text=re.compile(self.target)).string
AttributeError: 'NoneType' object has no attribute 'string'
Error: bandcamp-dl: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/bandcamp-dl/0.0.8-12_3/bin/bandcamp-dl --artist=iamsleepless --album=rivulets
/usr/local/Homebrew/Library/Homebrew/formula.rb:2026:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1964:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1964:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bandcamp-dl.rb:97:in `block in <class:BandcampDl>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1835:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:496:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1834:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:894:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1833:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2075:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1827:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:42:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:41:in `<main>'
```

&nbsp;

For `bzt`:
```
|-> brew test bzt
==> Testing bzt
==> /usr/local/Cellar/bzt/1.15.0/bin/bzt -v -o execution.executor=apiritif -o execution.iterations=1 -o execution.scenario.requests.0=https://gettaurus.org/
Last 15 lines from /Users/XXX/Library/Logs/Homebrew/bzt/test.01.gettaurus.org:
    from hdrpy import HdrHistogram, RecordedIterator
  File "/usr/local/Cellar/bzt/1.15.0/libexec/lib/python3.7/site-packages/hdrpy/__init__.py", line 29, in <module>
    import numpy
  File "/usr/local/Cellar/bzt/1.15.0/libexec/lib/python3.7/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
[2020-09-25 14:25:50,720 INFO Engine] Post-processing...
[2020-09-25 14:25:50,721 DEBUG Engine.Configuration] Dumping YAML config into /private/tmp/bzt-test-20200925-98507-gscy73/2020-09-25_14-25-50.610328/effective.yml
[2020-09-25 14:25:50,736 DEBUG Engine.Configuration] Dumping JSON config into /private/tmp/bzt-test-20200925-98507-gscy73/2020-09-25_14-25-50.610328/effective.json
[2020-09-25 14:25:50,737 INFO root] Artifacts dir: /private/tmp/bzt-test-20200925-98507-gscy73/2020-09-25_14-25-50.610328
[2020-09-25 14:25:50,737 WARNING root] Done performing with code: 1
[2020-09-25 14:25:50,737 DEBUG root] Closing log handler: /private/tmp/bzt-test-20200925-98507-gscy73/2020-09-25_14-25-50.610328/bzt.log
[2020-09-25 14:25:50,963 DEBUG urllib3.connectionpool] Starting new HTTPS connection (1): gettaurus.org:443
[2020-09-25 14:25:52,252 DEBUG urllib3.connectionpool] https://gettaurus.org:443 "GET /updates/?version=1.15.0&installID=macos-38f9d3075511 HTTP/1.1" 200 40
[2020-09-25 14:25:52,253 DEBUG Engine] Taurus updates info: {'latest': '1.15.0', 'needsUpgrade': False}
[2020-09-25 14:25:52,253 DEBUG Engine] Installation is up-to-date
Error: bzt: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/bzt/1.15.0/bin/bzt -v -o execution.executor=apiritif -o execution.iterations=1 -o execution.scenario.requests.0=https://gettaurus.org/
/usr/local/Homebrew/Library/Homebrew/formula.rb:2026:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1964:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1964:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bzt.rb:245:in `block in <class:Bzt>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1835:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:496:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1834:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:894:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1833:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2075:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1827:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:42:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:41:in `<main>'
```

&nbsp;

For `get-flash-videos`:
```
|-> brew test get-flash-videos
==> Testing get-flash-videos
==> /usr/local/Cellar/get-flash-videos/1.25.99.03/bin/get_flash_videos http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
Last 15 lines from /Users/XXX/Library/Logs/Homebrew/get-flash-videos/test.01.get_flash_videos:
2020-09-25 14:27:43 +0800

/usr/local/Cellar/get-flash-videos/1.25.99.03/bin/get_flash_videos
http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm

Using method 'bbc' plugin version 0.02 for http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
Downloading http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
rtmpdump: ERROR: Closing connection: NetStream.Failed
Download failed, no valid file downloaded
Couldn't download any videos.
Error: get-flash-videos: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/get-flash-videos/1.25.99.03/bin/get_flash_videos http://news.bbc.co.uk/2/hi/programmes/hardtalk/9560793.stm
/usr/local/Homebrew/Library/Homebrew/formula.rb:2026:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1964:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1964:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/get-flash-videos.rb:77:in `block in <class:GetFlashVideos>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1835:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:496:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1834:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:894:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1833:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2075:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1827:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:42:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:41:in `<main>'
```

&nbsp;

Finally `komposition`, `libxmlsec1` and `ola` did not build from source, and the relevant parts of the builds illustrating the errors are shown below:

For `komposition`:
```
==> cabal v2-install --jobs=4 --max-backjumps=100000 --install-method=copy --installdir=/usr/local/Cellar/komposition/0.2.0_3/bin
Last 15 lines from /Users/XXX/Library/Logs/Homebrew/komposition/02.cabal:

Failed to build gi-glib-2.0.23. The failure occurred during the configure
step.
Build log (
/private/tmp/komposition-20200925-3874-4l7ty9/komposition-0.2.0/.brew_home/.cabal/logs/ghc-8.8.4/g-glb-2.0.23-82204c21.log
):
[1 of 1] Compiling Main             ( /private/tmp/cabal-install.-4071/dist-newstyle/tmp/src-4071/gi-glib-2.0.23/dist/setup/setup.hs, /private/tmp/cabal-install.-4071/dist-newstyle/tmp/src-4071/gi-glib-2.0.23/dist/setup/Main.o )
Linking /private/tmp/cabal-install.-4071/dist-newstyle/tmp/src-4071/gi-glib-2.0.23/dist/setup/setup ...
Unknown GIR element "docsection" when processing namespace "GLib", aborting.
CallStack (from HasCallStack):
  error, called at lib/Data/GI/CodeGen/API.hs:199:16 in hskll-g-0.23.1-542485de:Data.GI.CodeGen.API
cabal: Failed to build gi-glib-2.0.23 (which is required by
exe:komposition-split from komposition-0.2.0 and exe:komposition from
komposition-0.2.0). See the build log above for details.
```

&nbsp;

For `libxmlsec1`:
```
==> make install
Last 15 lines from /Users/XXX/Library/Logs/Homebrew/libxmlsec1/02.make:
         ^~~~~~~
bignum.c:22:10: fatal error: 'nss.h' file not found
#include <nss.h>
         ^~~~~~~
1 error generated.
make[2]: *** [libxmlsec1_nss_la-crypto.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
1 error generated.
make[2]: *** [libxmlsec1_nss_la-app.lo] Error 1
make[2]: *** [libxmlsec1_nss_la-ciphers.lo] Error 1
1 error generated.
make[2]: *** [libxmlsec1_nss_la-bignum.lo] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

&nbsp;

For `ola`:
```
==> make install
Last 15 lines from /Users/XXX/Library/Logs/Homebrew/ola/03.make:
  m_httpd = MHD_start_daemon(MHD_NO_FLAG,
            ^~~~~~~~~~~~~~~~
/usr/local/include/microhttpd.h:2425:1: note: candidate function not viable: no known conversion from 'int (*)(void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, size_t *, void **)' (aka 'int (*)(void *, MHD_Connection *, const char *, const char *, const char *, const char *, unsigned long *, void **)') to 'MHD_AccessHandlerCallback' (aka 'MHD_Result (*)(void *, MHD_Connection *, const char *, const char *, const char *, const char *, unsigned long *, void **)') for 5th argument
MHD_start_daemon (unsigned int flags,
^
/bin/sh ./libtool  --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H -I.    -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -I/usr/local/Cellar/protobuf@3.6/3.6.1.3_2/include  -g -O2 -std=gnu++11 -D_THREAD_SAFE  -c -o common/http/OlaHTTPServer.lo common/http/OlaHTTPServer.cpp
3 errors generated.
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -I/usr/local/Cellar/protobuf@3.6/3.6.1.3_2/include -g -O2 -std=gnu++11 -D_THREAD_SAFE -c olad/plugin_api/Universe.cpp -o olad/plugin_api/libolaserverplugininterface_la-Universe.o >/dev/null 2>&1
make[2]: *** [common/http/HTTPServer.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -I/usr/local/Cellar/protobuf@3.6/3.6.1.3_2/include -g -O2 -std=gnu++11 -D_THREAD_SAFE -c common/http/OlaHTTPServer.cpp  -fno-common -DPIC -o common/http/.libs/OlaHTTPServer.o
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -I/usr/local/Cellar/protobuf@3.6/3.6.1.3_2/include -g -O2 -std=gnu++11 -D_THREAD_SAFE -c olad/plugin_api/UniverseStore.cpp -o olad/plugin_api/libolaserverplugininterface_la-UniverseStore.o >/dev/null 2>&1
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./include -I./include -Wall -Wformat -W -fvisibility-inlines-hidden -pthread -I/usr/local/Cellar/protobuf@3.6/3.6.1.3_2/include -g -O2 -std=gnu++11 -D_THREAD_SAFE -c common/http/OlaHTTPServer.cpp -o common/http/OlaHTTPServer.o >/dev/null 2>&1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```

**Comment by dtrodrigues** [comment]
The bandcamp issue has a PR upstream: https://github.com/iheanyi/bandcamp-dl/pull/167

**Comment by SMillerDev** [comment]
I just did some tests without updating to see what is actually caused by this PR.

`Ola` and `komposition` fail for me locally too. `libxmlsec1` works, I think it might require xcode to function so you can try adding that requirement in your next run. 

As for the test failures, `get-flash-videos` fails locally too and `bzt` works. 

---

I'd be fine with you pushing all the revision bumps, adding the upstream bandcamp patch and xcode dependency and merging if those are fixed by this.

That would leave the following with an old bottle/failure:

- [ ] ola
- [ ] komposition
- [ ] get-flash-videos

**Comment by miccal** [comment]
Thank you @dtrodrigues and @SMillerDev, I will invest some time into this tomorrow.

**Comment by miccal** [comment]
@jnozsc very kindly updated `bandcamp-dl` and `libxmlsec1` in separate PR's.

I have revision-bumped `libmspub`, `libpq`, `mlt`, `pangomm` and `pcl`.

Let's see how it goes ...

**Comment by miccal** [comment]
Oh bother :(

10.15 failures:
```
Error: 10 failed steps!
brew test --retry --verbose freexl
brew test --retry --verbose game-music-emu
brew test --retry --verbose get-flash-videos
brew test --retry --verbose gtksourceview3
brew test --retry --verbose libepoxy
brew install --only-dependencies libodfgen
brew install --only-dependencies libxmlsec1
brew install --only-dependencies ola
brew install --only-dependencies paps
brew install --only-dependencies gdal
```
&nbsp;
10.14 failures:
```
Error: 6 failed steps!
brew test --retry --verbose get-flash-videos
brew install --only-dependencies libodfgen
brew install --only-dependencies libxmlsec1
brew install --only-dependencies ola
brew install --only-dependencies paps
brew install --only-dependencies gdal
```
&nbsp;
10.13 failures:
```
Error: 6 failed steps!
brew test --retry --verbose get-flash-videos
brew install --only-dependencies libodfgen
brew install --only-dependencies libxmlsec1
brew install --only-dependencies ola
brew install --only-dependencies paps
brew install --only-dependencies gdal
```

**Comment by SMillerDev** [comment]
I'm expecting the new ones to be second level dependencies and just be fixed with a version bump (except for xmlsec)

**Comment by miccal** [comment]
> I'm expecting the new ones to be second level dependencies and just be fixed with a version bump (except for xmlsec)

Thanks @SMillerDev -- I will hopefully have some time to investigate this later today.

**Comment by miccal** [comment]
> Thanks @SMillerDev -- I will hopefully have some time to investigate this later today.

Apologies, I did not have time to investigate this today, but I will try to do it tomorrow.

**Comment by miccal** [comment]
Working on the assumption that the 10.15 test failures that were not present in the 10.14 and 10.13 tests are a one-off, I have just gone through the 10.14 and 10.13 failures.

`libodfgen` and `paps` successfully built from source on my 10.14 machine, so I have given these a revision bump.

The `gdal` error is because of the revision bump of `libpq`, but re-building `gdal` from source resulted in errors as seen in https://github.com/Homebrew/homebrew-core/pull/61096, which is odd since I was building version `3.1.2`.

I cannot build `libxmlsec1` from source, as I do not (and cannot -- long story ...) have a full Xcode installed on this particular machine.

It also took me over an hour to push to `homebrew-core` with these `fatal: unable to access 'https://github.com/miccal/homebrew-core/': transfer closed with outstanding read data remaining` errors!

Anyway, lets see how this one goes ...

**Comment by miccal** [comment]
Sigh ...

10.15 failures:
```
Error: 13 failed steps!
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch origin +refs/heads/master
brew test --retry --verbose freexl
brew test --retry --verbose game-music-emu
brew test --retry --verbose get-flash-videos
brew test --retry --verbose gtksourceview3
brew test --retry --verbose howdoi
brew test --retry --verbose libepoxy
brew install --only-dependencies libpst
brew install --only-dependencies libxmlsec1
brew install --only-dependencies ola
brew install --only-dependencies pcb
brew install --only-dependencies sphinx-doc
brew install --only-dependencies gdal
```
&nbsp;
10.14 failures:
```
Error: 9 failed steps!
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch origin +refs/heads/master
brew test --retry --verbose bzt
brew test --retry --verbose get-flash-videos
brew test --retry --verbose howdoi
brew install --only-dependencies libpst
brew install --only-dependencies libxmlsec1
brew install --only-dependencies ola
brew install --only-dependencies pcb
brew install --only-dependencies gdal
```
&nbsp;
10.13 failures:
```
Error: 8 failed steps!
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch origin +refs/heads/master
brew test --retry --verbose get-flash-videos
brew test --retry --verbose howdoi
brew install --only-dependencies libpst
brew install --only-dependencies libxmlsec1
brew install --only-dependencies ola
brew install --only-dependencies pcb
brew install --only-dependencies gdal
```
&nbsp;
I suspect that `libpst` and `pcb` are just bumps.

**Comment by SMillerDev** [comment]
The issue with gdal is really apache arrow.

**Comment by miccal** [comment]
> The issue with gdal is really apache arrow.

https://github.com/Homebrew/homebrew-core/pull/61840#issuecomment-703227959

I think the best thing would be to assist with https://github.com/Homebrew/homebrew-core/pull/61096 if possible and come back to this, perhaps?

**Comment by fxcoudert** [comment]
I've fixed gdal, I'm hoping this can get the ball rolling here

**Comment by miccal** [comment]
I have gone back to the first round of tests working on the assumption that the failures in the subsequent tests were as a result of the issues with `gdal`.

So I have now just revision-bumped `libmspub`, `libpq`, `mlt`, `pangomm` and `pcl`, and also revision-bumped `gdal` on account of bumping `libpq`.

Now that `gdal` is building successfully, this next CI run will hopefully give a better idea of things.

**Comment by miccal** [comment]
10.15 failures:
```
Error: 3 failed steps!
brew test --retry --verbose bandcamp-dl
brew test --retry --verbose get-flash-videos
brew install --verbose --build-bottle pcl
```
&nbsp;
10.14 failures:
```
Error: 4 failed steps!
brew test --retry --verbose bandcamp-dl
brew test --retry --verbose bzt
brew test --retry --verbose get-flash-videos
brew install --verbose --build-bottle pcl
```
&nbsp;
10.13 failures:
```
Error: 4 failed steps!
brew test --retry --verbose bandcamp-dl
brew test --retry --verbose bzt
brew test --retry --verbose get-flash-videos
brew install --verbose --build-bottle pcl
```
&nbsp;
@SMillerDev and @fxcoudert thoughts? `pcl` now failing for some reason, although I have bumped it.

**Comment by sharris40** [comment]
Looks like Eigen 3.3.8 is busted. Upstream bug: https://gitlab.com/libeigen/eigen/-/issues/2011

**Comment by sharris40** [comment]
I finished looking into the problems:

bandcamp-dl: Upstream bug https://github.com/iheanyi/bandcamp-dl/issues/170
bzt: Seems to be using a private copy of Python, and the numpy in that copy is compiled against Accelerate, which is a notoriously buggy setup. Both PYPI and we compile numpy against OpenBLAS instead. This is probably going to be hard to fix.
get-flash-videos: Network failure. Tests probably need to be fixed.
pcl: Issue in Eigen. See my previous comment.

**Comment by miccal** [comment]
Thank you @sharris40 for your help, it is very much appreciated.

**Comment by fxcoudert** [comment]
I think at this point this needs to be merged. @SMillerDev ?

**Review by fxcoudert — DISMISSED** [review]

**Comment by sharris40** [comment]
Please hold off while we fix `eigen`. Python 3.8.6 got merged accidentally, and things are a bit broken now.

**Comment by SMillerDev** [comment]
That wasn't accidental. I think the brew ecosystem shipping up to date software is more important than one formula being broken.

**Comment by sharris40** [comment]
Okay, got it.

My PR does revbump `pcl` again. If you still want it to go ahead, we'll need to bump it some more here as well.

**Comment by miccal** [comment]
Rebased.

**Comment by fxcoudert** [comment]
On 10.15:

```
brew test --retry --verbose bandcamp-dl
brew test --retry --verbose get-flash-videos
```

On 10.13:

```
brew test --retry --verbose bandcamp-dl
brew test --retry --verbose get-flash-videos
brew test --retry --verbose libsoundio
```

**Comment by miccal** [comment]
Thank you @fxcoudert.

**Pull request closed without merging**
