### PR TITLE
zabbix-cli 2.0.1 (new formula)

### PR DESCRIPTION
**Pull request by cblecker**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Add a new formula for the zabbix-cli tool.

### CODE REVIEW

**Comment by cblecker** [comment]
@lembacon Any update on this? :)

**Comment by cblecker** [comment]
@fxcoudert Sorry for the ping, but this one might have fallen through the cracks. Any chance I could get a review? Thank you!

**Comment by zbeekman** [comment]
@BrewTestBot test this please

**Comment by cblecker** [comment]
@zbeekman Looks like CI is still passing

**Comment by zbeekman** [comment]
Thanks for your contribution to Homebrew! 🎉 🥇 

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
