### PR TITLE
traefik 2.3.3

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

---

[`action-homebrew-bump-formula`](https://github.com/dawidd6/action-homebrew-bump-formula)

### CODE REVIEW

**Comment by chenrui333** [comment]
traefik failed on 10.15

**Comment by chenrui333** [comment]
```
==> Testing traefik
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201119-60559-2f3hzl.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/traefik.rb --verbose
/usr/local/Cellar/traefik/2.3.3/bin/traefik: /usr/local/Cellar/traefik/2.3.3/bin/traefik: cannot execute binary file
==> curl -sIm3 -XGET http://127.0.0.1:54693/

Error: traefik: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<7>.
```

**Comment by djerfy** [comment]
@chenrui333 I don't have a problem on macOS 10.15.7, strange... Can you relaunch job?

**Comment by djerfy** [comment]
Build failed on 10.14 due to runner shutdown (timeout?):

```text
The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
```

**Review by fxcoudert — APPROVED** [review]

**Pull request closed without merging**
