### PR TITLE
Remove some more :recommended

### PR DESCRIPTION
**Pull request by fxcoudert**

### CODE REVIEW

**Comment by fxcoudert** [comment]
`scipy`, `numpy`, `sip` and `pyqt` all fail to build with:

```
==> Installing numpy
==> Downloading https://files.pythonhosted.org/packages/2d/80/1809de155bad674b494248bcfca0e49eb4c5d8bee58f26fe7a0dd45029e2/numpy-1.15.4.zip
Already downloaded: /Users/brew/Library/Caches/Homebrew/downloads/dbbfdd4b742ea270e6a4d598416cf123e0f6bc1c1b5501e98ff1369e22031796--numpy-1.15.4.zip
Error: Empty installation
```

I cannot reproduce locally 😢

**Review by kqf — COMMENTED** [review]
Why options where removed from `Formula/root.rb` formula?

**Comment by fxcoudert** [comment]
See #31510 for rationale behind removal of options.

**Comment by kqf** [comment]
Thanks a lot, I've missed it.

**Pull request closed without merging**
