### PR TITLE
azure-cli 0.10.15

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@chrmoritz any idea how to get fibers to build its libraries from source?

```
bash-3.2$ cd /usr/local/Cellar/azure-cli/0.10.15/libexec/lib/node_modules/azure-cli/node_modules/fibers/bin
bash-3.2$ find . -type f -exec file "{}" \;
./.npmignore: empty
./darwin-ia32-46/fibers.node: Mach-O bundle i386
./darwin-ia32-48/fibers.node: Mach-O bundle i386
./darwin-x64-46/fibers.node: Mach-O 64-bit bundle x86_64
./darwin-x64-48/fibers.node: Mach-O 64-bit bundle x86_64
./darwin-x64-57/fibers.node: Mach-O 64-bit bundle x86_64
./linux-ia32-46/fibers.node: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, not stripped
./linux-ia32-48/fibers.node: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, not stripped
./linux-x64-46/fibers.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
./linux-x64-48/fibers.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
./repl: a node script text executable
./win32-ia32-46/fibers.node: PE32 executable for MS Windows (DLL) (GUI) Intel 80386 32-bit
./win32-ia32-48/fibers.node: PE32 executable for MS Windows (DLL) (GUI) Intel 80386 32-bit
./win32-x64-46/fibers.node: PE32+ executable for MS Windows (DLL) (GUI) Mono/.Net assembly
./win32-x64-48/fibers.node: PE32+ executable for MS Windows (DLL) (GUI) Mono/.Net assembly
bash-3.2$
```

**Comment by chrmoritz** [comment]
@ilovezfs: fibers is already build from source in this formula, because it doesn't ship with prebuilds for node@8 yet. What you are seeing is caused by the fact, that fiber doesn't use the common prebuild modules like `prebuild` or `node-pre-gyp`, but instead implemented it's own script, which uploads prebuilds for all supported platforms to npm (which is quite uncommon).

What you are seeing there are the unneeded prebuild binaries for the different platforms with the `NODE_MODULE_VERSION` suffix (48 for node@6 and 46 for node@4). Because node@8 is not supported/prebuild yet, the `darwin-x64-57` was build from source at install time and is the only one which is actual used/needed out of them. We could just remove all binaries with a `-46` or `-48` suffix at the end of the build.

**Comment by ilovezfs** [comment]
>Because node@8 is not supported/prebuild yet

When it is, how will we avoid the binaries?

**Comment by ilovezfs** [comment]
>We could just remove all binaries with a -46 or -48 suffix at the end of the build.

That sounds like a good idea. Or we could just add `cxxstdlib_check :skip` to shut it up.

**Comment by chrmoritz** [comment]
> When it is, how will we avoid the binaries?

It looks like `fibers` are only generating prebuilds for LTS versions. As long as we keep this formula on a current/latest node version we should be fine. Unfortunately `fibers`'s custom build script doesn't listen to something passed to npm to force source builds (like `--build-from-source` for `prebuild` and `node-pre-gyp`). If we would end up with a node version with a binary available we would need to cd to fibers after the global npm install and run ` PATH="/usr/local/opt/node/libexec/lib/node_modules/npm/bin/node-gyp-bin:$PATH" node build.js -f` to rebuild it from source.

**Pull request closed without merging**
