### PR TITLE
guile: include missing texinfo as build dependency

### PR DESCRIPTION
**Pull request by august-feng**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
which os are you using? maybe it should be 

```
  on_system :linux, macos: :ventura_or_newer do
    depends_on "texinfo" => :build
  end
```

**Comment by augustfengd** [comment]
> which os are you using? maybe it should be
> 
> ```
>   on_system :linux, macos: :ventura_or_newer do
>     depends_on "texinfo" => :build
>   end
> ```

I'm on MacOS Ventura. Should I make the changes above?

**Comment by SMillerDev** [comment]
I think that's the more correct version.

**Comment by augustfengd** [comment]
Oops, sorry forgot to update the PR. It's done now.

**Review by fxcoudert — APPROVED** [review]

**Comment by augustfengd** [comment]
Hey @fxcoudert! could you help me merge this? I'm not sure what's still required as the merge button is still blocked for me.

> **Merging is blocked**
>
> Merging can be performed automatically with 1 approving review.

**Review by SMillerDev — APPROVED** [review]

**Comment by augustfengd** [comment]
Ah, so everything is green from here but only those with write access can merge. 😅 

> **This branch has no conflicts with the base branch**
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Pull request merged**
