### PR TITLE
semgrep 0.6.1 (new formula)

### PR DESCRIPTION
**Pull request by rcoh**
semgrep is a semantic grep tool that allows searching code with patterns
that match on the AST. It is composed of two pieces -- semgrep-core, an
OCaml library, and `semgrep`, a Python wrapper that exposes a clean CLI
interface.

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
```
[34m==>[0m [1mopam init --no-setup --disable-sandboxing[0m
[NOTE] Will configure from built-in defaults.
Checking for available remotes: rsync and local, git.
  - you won't be able to use mercurial repositories unless you install the hg command on your system.
  - you won't be able to use darcs repositories unless you install the darcs command on your system.


<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><>  ðŸ« 
[default] Initialised

<><> Creating initial switch (ocaml-system>=4.02.3) <><><><><><><><><><><><>  ðŸ« 

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  ðŸ« 

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  ðŸ« 
âˆ— installed base-bigarray.base
âˆ— installed base-threads.base
âˆ— installed base-unix.base
âˆ— installed ocaml-system.4.09.0
âˆ— installed ocaml-config.1
âˆ— installed ocaml.4.09.0
Done.
# Run eval $(opam env) to update the current shell environment
[34m==>[0m [1mopam switch create ocaml-base-compiler.4.07.1[0m

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  ðŸ« 
[ocaml-base-compiler.4.07.1] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  ðŸ« 
âˆ— installed base-bigarray.base
âˆ— installed base-threads.base
âˆ— installed base-unix.base
[ERROR] The compilation of ocaml-base-compiler failed at "/usr/local/Homebrew/Library/Homebrew/shims/mac/super/make -j5 world".

#=== ERROR while compiling ocaml-base-compiler.4.07.1 =========================#
# context              2.0.7 | macos/x86_64 |  | https://opam.ocaml.org#88a179f5
# path                 /private/tmp/opamroot20200504-58648-1d9nxut/ocaml-base-compiler.4.07.1/.opam-switch/build/ocaml-base-compiler.4.07.1
# command              /usr/local/Homebrew/Library/Homebrew/shims/mac/super/make -j5 world
# exit-code            2
# env-file             /private/tmp/opamroot20200504-58648-1d9nxut/log/ocaml-base-compiler-59165-d0f245.env
# output-file          /private/tmp/opamroot20200504-58648-1d9nxut/log/ocaml-base-compiler-59165-d0f245.out
### output ###
# [...]
# #include <X11/Xlib.h>
#          ^~~~~~~~~~~~
# make[3]: *** [draw.o] Error 1
# 1 error generated.
# make[3]: *** [color.o] Error 1
# 1 error generated.
# make[3]: *** [open.o] Error 1
# 1 error generated.
# make[3]: *** [text.o] Error 1
# make[2]: *** [otherlibraries] Error 2
# make[1]: *** [all] Error 2
# make: *** [world] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  ðŸ« 
â”Œâ”€ The following actions failed
â”‚ Î» build ocaml-base-compiler 4.07.1
â””â”€ 
â”Œâ”€ The following changes have been performed (the rest was aborted)
â”‚ âˆ— install base-bigarray base
â”‚ âˆ— install base-threads  base
â”‚ âˆ— install base-unix     base
â””â”€ 

<><> ocaml-base-compiler.4.07.1 troubleshooting <><><><><><><><><><><><><><>  ðŸ« 
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.
# Run eval $(opam env) to update the current shell environment
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] y
```
```

**Comment by chenrui333** [comment]
@rcoh ping on this PR. :)

**Comment by rcoh** [comment]
Sorry, got sidetracked! Will hopefully get the build failures fixed today.

**Comment by chenrui333** [comment]
@rcoh Thanks a lot for the quick turn-around, the formula is 🚀  to go!!

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
I did the editing in the browser instead of editor, did not realize the spaces stuff :(

**Comment by chenrui333** [comment]
@rcoh Again, thanks for your contribution to Homebrew! :tada: 🥇

Without awesome contributors like you, it would be impossible to maintain Homebrew to the high level of quality users have come to expect. Thank you!!!!

**Pull request closed without merging**
