### PR TITLE
atmos 1.18.0

### PR DESCRIPTION
**Pull request by cloudpossebot**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Review by p-linnane — DISMISSED** [review]

**Comment by chenrui333** [comment]
base branch is outdated.

**Review by p-linnane — DISMISSED** [review]

**Comment by chenrui333** [comment]
Let me do a quick test. Maybe we can just manually the bottle block.

**Comment by chenrui333** [comment]
> @chenrui333 So this exists: https://github.com/homebrew/homebrew-core/pkgs/container/core%2Fatmos/59130308?tag=1.18.0
> 
> Any idea what we do here? Merge this and rebuild?

I tried manually updating the bottle block, the checksum mismatch.

```
$ brew reinstall atmos
==> Fetching atmos
==> Downloading https://ghcr.io/v2/homebrew/core/atmos/manifests/1.18.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/atmos/manifests/1.18.0
######################################################################## 100.0%
Error: Couldn't find manifest matching bottle checksum.
```

**Comment by cho-m** [comment]
> I tried manually updating the bottle block, the checksum mismatch.

Did you try to bottle block from https://github.com/Homebrew/homebrew-core/actions/runs/3708262128/jobs/6285633433#step:10:67 ?

These were uploaded in first merge workflow. If there are no problems with the bottles, can try using that bottle block.

If there are problems, either need someone with package write permission to delete the existing upload or to go for a rebuild later.

**Comment by p-linnane** [comment]
@cho-m Just tried and it's working locally. Should I just push that to this PR and then we'll merge it manually?

**Comment by cho-m** [comment]
> @cho-m Just tried that block and it's working locally. I verified the hashes in the manifest as well. Should I just push that to this PR and then we'll merge it manually?

Yeah, you can just add the bottles in a separate commit to this PR (matching standard @BrewTestBot commit message, e.g. `atmos: update 1.18.0 bottle.`) and then run CO with `CI-syntax-only` tag.

We may need to manually do `Rebase and merge` to avoid auto-squashing commits.

**Comment by chenrui333** [comment]
```
==> Downloading https://ghcr.io/v2/homebrew/core/atmos/manifests/1.18.0
Already downloaded: /Users/rui/Library/Caches/Homebrew/downloads/a3c4e335767391504277b67174d68393b55ac1482b41e2dcea0420f3cab29dde--atmos-1.18.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/atmos/blobs/sha256:af2b8902255480b5b3e103f0691d288cc55b7217afd4f62b4c3114867bdbedce
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:af2b8902255480b5b3e103f0691d288cc55b7217afd4f62b4c3114867bdbedce?se=2022-12-17T01%3A15%3A00Z&sig=96%2FxQyeDEaVXsXe7L
######################################################################## 100.0%
```

**Review by chenrui333 — APPROVED** [review]

**Comment by chenrui333** [comment]
Thanks @cho-m @p-linnane!!

**Pull request merged**
