### PR TITLE
audacious 4.0.1

### PR DESCRIPTION
**Pull request by chenrui333**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
```
Successfully compiled Vgm_Emu.cc (plugin).
Compiling plugin.cc (plugin)...
Successfully compiled configure.cc (plugin).
Successfully compiled plugin.cc (plugin).
Successfully compiled lyricwiki.cc (plugin).
Linking lyricwiki-qt.bundle...
Successfully compiled Audacious_Driver.cc (plugin).
Successfully linked lyricwiki-qt.bundle.
Leaving directory lyricwiki-qt.
Successfully compiled Ym2413_Emu.cc (plugin).
Successfully compiled Ym2612_Emu.cc (plugin).
Linking console.bundle...
Successfully linked console.bundle.
Leaving directory console.
make[2]: *** [all] Error 2
make[1]: *** [src] Error 2
make: *** [all] Error 2
```

**Comment by Bo98** [comment]
This is fixed in https://github.com/audacious-media-player/audacious-plugins/commit/04c2a49db02aed3c88f0fb5f91ae2f35b8266335

**Comment by chenrui333** [comment]
```
cp -p /Users/brew/Library/Caches/Homebrew/downloads/34c6186f80a8a90a0b47489684fb5101e8f2ccb33dc8571045973706cd339862--04c2a49.patch /private/tmp/audacious--patch-20200413-63590-1ikq4oe/04c2a49.patch
[34m==>[0m [1mPatching plugins[0m
[34m==>[0m [1mApplying 04c2a49.patch[0m
patch -g 0 -f -p1 -i /private/tmp/audacious--patch-20200413-63590-1ikq4oe/04c2a49.patch
patching file src/qtglspectrum/gl-spectrum.cc
can't find file to patch at input line 161
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/qtglspectrum/meson.build b/src/qtglspectrum/meson.build
|index 0d5ac01e9517af836e454a4f2fd752a4dd1318aa..ddd198f57d9f3435c8d0c210cb7c50c9bdd37018 100644
|--- a/src/qtglspectrum/meson.build
|+++ b/src/qtglspectrum/meson.build
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
[31mError:[0m Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/audacious--patch-20200413-63590-1ikq4oe/04c2a49.patch` exited with 1.
==> [1m[31mFAILED[0m[0m

```

**Comment by chenrui333** [comment]
Will checkout on this tomorrow.

**Pull request closed without merging**
