### PR TITLE
Fixed erroneous requirement of Xcode 9.0 - this is not mandatory

### PR DESCRIPTION
**Pull request by les-okta**
- [X] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

PR to revert most recent erroneous change.

### CODE REVIEW

**Comment by Bo98** [comment]
I'm confused. Why did the other person get a build-time error saying it required Xcode 9?

cc @leonklingele

**Comment by les-okta** [comment]
I've no idea.  But we have hundreds of machines running Mojave and they install the command line tools, homebrew and `mysql-client` from scratch and the full Xcode.app is definitely not required for installation.  I confirmed this with a full build from source per the instructions here:  https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#to-contribute-a-fix-to-the-foo-formula.

**Comment by Bo98** [comment]
Right, I understand now. CLT only installations.

**Comment by les-okta** [comment]
@fxcoudert or @SMillerDev - to confirm, the following was run after this PR's edits were made without errors or warnings:

```bash
cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
brew uninstall --force mysql-client 
brew install --build-from-source mysql-client
brew test mysql-client
brew audit --strict mysql-client
```

Is there anything else I need to do for this PR to be approved?  Thanks for the guidance!

**Comment by SMillerDev** [comment]
You could make an issue upstream for https://github.com/mysql/mysql-server/blob/8.0/cmake/os/Darwin.cmake#L30-L37 to mention xcode isn't needed.

**Comment by les-okta** [comment]
@SMillerDev Happy to do that tomorrow (it's late here). In the meantime, can this be merged now that the CI checks have passed?

**Comment by SMillerDev** [comment]
I still want to check if clang 9 is in the CLT to avoid the build being a false positive. And see if we have a way to require a specific clang version. I understand your work flow is broken but there's no need to rush into a solution that might break it for even more people.

**Comment by les-okta** [comment]
I definitely understand your concern, but the previous version did not have that line - my PR only reverts to what was already working previously.

Based on this, is it possible to merge now and deliberate on adding it back in after the research is complete?  It's better to revert to what was working, and only add it back in once we have confirmation, no?

**Comment by les-okta** [comment]
Also, my comment https://github.com/Homebrew/homebrew-core/pull/46930#issuecomment-555726595 shows that only CLT is required - not Xcode.app.  Isn't this confirmation?  Thoughts?

**Comment by SMillerDev** [comment]
It just shows that it works on your machine without xcode. That doesn't mean that it will always work with just CLT.

**Comment by fxcoudert** [comment]
@SMillerDev I'm reverting this right now, and will find a better fix later. Most users install from bottles, and we prefer to have it working for these users, and broken from a smaller subset (install from source, older Xcode).

**Comment by fxcoudert** [comment]
@les-okta @leonklingele 

I'm wondering if a proper fix wouldn't be:

```
  fails_with :clang do
    build 900
```

**Comment by leonklingele** [comment]
Looks like a better fix is, as taken from the mysql formula:

```patch
diff --git a/Formula/mysql-client.rb b/Formula/mysql-client.rb
index d721697288..8e3b6f7409 100644
--- a/Formula/mysql-client.rb
+++ b/Formula/mysql-client.rb
@@ -14,6 +14,9 @@ class MysqlClient < Formula

   depends_on "cmake" => :build

+  # GCC is not supported either, so exclude for El Capitan.
+  depends_on :macos => :sierra if DevelopmentTools.clang_build_version == 800
+
   depends_on "openssl@1.1"

   def install
```

I'd even change it to:

```patch
diff --git a/Formula/mysql-client.rb b/Formula/mysql-client.rb
index d721697288..ce5b5770e7 100644
--- a/Formula/mysql-client.rb
+++ b/Formula/mysql-client.rb
@@ -14,6 +14,9 @@ class MysqlClient < Formula

   depends_on "cmake" => :build

+  # GCC is not supported either, so exclude for El Capitan.
+  depends_on :macos => :sierra if DevelopmentTools.clang_build_version < 900
+
   depends_on "openssl@1.1"

   def install
```

Does that look reasonable?

**Comment by Bo98** [comment]
It's possible (though I hope no-one is) to have Sierra with Clang 8. If checking on the OS could be avoided then that would be ideal.

**Comment by fxcoudert** [comment]
At this point we're not trying to catch all combinations of OS/Xcode. Sierra is already not really supported, so people using it with older versions of Xcode should expect trouble.

**Comment by leonklingele** [comment]
https://github.com/Homebrew/homebrew-core/pull/47019

**Pull request merged**
