### PR TITLE
erlang@26 26.2.5 (new formula)

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
# Description

This creates new formula `erlang@26`, for Erlang/OTP 26.2.5, from the previous `erlang.rb` formula. It is done in preparation for introducing 27.0.1, from https://github.com/Homebrew/homebrew-core/pull/178020.

## Further considerations

- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

### CODE REVIEW

**Comment by woodruffw** [comment]
Thanks for your PR @paulo-ferraz-oliveira! Am I understanding correctly that this is being done in preparation for changing the `erlang` formula over to `27`?

In terms of fixing the CI: we already have an `erlang@26` alias, which I believe you'll need to delete: https://github.com/Homebrew/homebrew-core/blob/master/Aliases/erlang%4026. Once that's deleted the CI should be slightly happier.

**Comment by paulo-ferraz-oliveira** [comment]
👋 

> Thanks for your PR @paulo-ferraz-oliveira! Am I understanding correctly that this is being done in preparation for changing the erlang formula over to 27?

Yes, there's already a [concurrent pull request](https://github.com/Homebrew/homebrew-core/pull/178020) for this (locally Brew's happy, and yesterday the only "Failed" I saw in the logs was something for Linux, dependencies, but it didn't stop CI from moving forward, because I "ran into trouble" trying to do it in the same place 😄 

> In terms of fixing the CI: we already have an erlang@26 alias

Yes, sorry, I was still running the CI locally, as per the pull request header. You were too fast 😄

**Comment by chenrui333** [comment]
it might be a better idea to build this key_only formula along with #178020 (otherwise it would require rebase and rebuild)

**Comment by paulo-ferraz-oliveira** [comment]
> it might be a better idea to build this key_only formula along with https://github.com/Homebrew/homebrew-core/pull/178020 (otherwise it would require rebase and rebuild)

I initially had the two files being changed in the same pull request, but:

1. kept running into "Commit style" failures in CI
2. reading the contributing guide didn't help, because there's a rule stating 1 commit per formula, 1 formula per commit, which made it unclear to me that I could commit two formulas in the same pull request (and even changing the alias)

I then searched the history to understand how it was done and couldn't find an example of a commit (or pull request) where multiple things were changed at once, so went with the closest to what I could find.

You suggest I merge these two pull requests? (and hopefully won't run into issues later)

Also, it's possible that this update (for 27.0.1) won't like the dependencies and fail there, and I don't know how to fix that (not the failures, but the process).

**Comment by paulo-ferraz-oliveira** [comment]
Is something missing for this to be merged as is? I don't mind rebasing #178020 on top of the main branch on it's so. Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
I'll handle this in #178020.

**Pull request closed without merging**
