### PR TITLE
gzip 1.13

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by fxcoudert — APPROVED** [review]

**Comment by iMichka** [comment]
I killed the Linux job as it will try to install pyqt in a loop; prioritising #139534 instead to fix pyqt first.

**Comment by fxcoudert** [comment]
If that was the only Linux failure, I'd say we ship this.

**Comment by iMichka** [comment]
Yes, I think we can go ahead with this. No need to wait for a full CI run.

**Comment by chenrui333** [comment]
I agree, most of the linux jobs that we ran into so far are pyqt related. merging this.

**Pull request merged**
