### PR TITLE
erlang@19 19.3.6.4 & erlang@18 18.3.4.7

### PR DESCRIPTION
**Pull request by DomT4**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

IMO, `erlang@17` could just 💀 at this point, but I'll see how ILZ feels.

### CODE REVIEW

**Comment by ilovezfs** [comment]
I added it for riak, remember?

**Comment by DomT4** [comment]
Ah, no I didn't; your memory is better than mine here 😉.

**Comment by ilovezfs** [comment]
Every @ formula leaves a permanent scar.

**Comment by DomT4** [comment]
Heh, now there's something easy to believe.

**Comment by DomT4** [comment]
Okay. So. Either `erlang@18` did build fine locally or I managed to build `erlang@19` twice without noticing and I need to sleep.

**Comment by ilovezfs** [comment]
Let's pretend that didn't happen.

@BrewTestBot test this please

**Comment by ilovezfs** [comment]
btw couchdb bottle is broken again due to a test-bot bug (its config files decide to go missing)

**Comment by ilovezfs** [comment]
hurray it passed that time except for the broken couchdb thing. So probably some transient parallelization issue :see_no_evil:

**Comment by ilovezfs** [comment]
:tea:

**Comment by DomT4** [comment]
> So probably some transient parallelization issue

Yay. Always fun 😅.

**Pull request closed without merging**
