### PR TITLE
whisper-cpp: 1.6.0

### PR DESCRIPTION
**Pull request by BingoKingo**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by chenrui333** [comment]
@BingoKingo some syntax issue, can you run `brew style --fix whisper-cpp` and squash commits, forced update your PR? thanks!

**Comment by chenrui333** [comment]
looks like the rebase was not clean, you might have to do it again.

image

**Comment by chenrui333** [comment]
```
  ==> /home/linuxbrew/.linuxbrew/Cellar/whisper-cpp/1.5.5/bin/whisper-cpp samples -m for-tests-ggml-tiny.bin
  error: input file not found 'samples'
  error: no input files specified
```

**Comment by BingoKingo** [comment]
@chenrui333 Fixed.

**Pull request closed without merging**
