### PR TITLE
openssl 1.0.2m

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
:tada:

**Comment by ilovezfs** [comment]
The apr-util bottle is broken on high sierra due to opportunistic linkage unrelated to this PR.

**Comment by ilovezfs** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/20184.

**Comment by alex** [comment]
thanks!

**Comment by ilovezfs** [comment]
Looks like mysql-connector-c and mysql-cluster will need to declare conflicts on each other. Also unrelated to this PR.

**Comment by ilovezfs** [comment]
The open-mpi failure on High Sierra is caused by the test hard-coding 4 cores, but the High Sierra VM only has 3. Also, unrelated to this PR.

**Comment by ilovezfs** [comment]
It's not clear why https://github.com/Homebrew/homebrew-core/pull/6779 was green since pulledpork appears to just be broken.

**Comment by ilovezfs** [comment]
Thanks @alex!

**Comment by alex** [comment]
Thank you!

**Pull request closed without merging**
