### PR TITLE
switch to HTTPS for Git access on sf.net

### PR DESCRIPTION
**Pull request by vszakats**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

It became possible after this update:
https://sourceforge.net/blog/small-but-significant-changes-to-project-pages/

There are about 44 more, SVN checkouts included.

### CODE REVIEW

**Comment by vszakats** [comment]
Failures seem unrelated to these updates. One is a build failure, plus there seem to be some intermittent errors where https://downloads.sourceforge.net/ URL denies access via port 443.

**Comment by ilovezfs** [comment]
The https://downloads.sourceforge.net/ false positives are rife.

**Comment by vszakats** [comment]
Kind of strange that it's still unfixed, and not indicated on the usual sf.net ops spots. Let's hope it recovers.

**Comment by ilovezfs** [comment]
@vszakats fix for doxymacs build: https://github.com/Homebrew/homebrew-core/pull/10855

**Comment by ilovezfs** [comment]
Thanks @vszakats :closed_lock_with_key:

**Pull request merged**
