### PR TITLE
llvm@13: fix python3 reference

### PR DESCRIPTION
**Pull request by danielnachun**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by cho-m** [comment]
Test is still using `"python3"`

**Comment by danielnachun** [comment]
That is deliberate because we want it to try to use whatever version of Python 3 is provided by brew or macOS.  We make symlinks for libclang for Python 3.7 and up.  That avoids a possible versioned dependency conflict between llvm and any of its dependents that use a specific version of Python 3.  @carlocab is that the correct explanation of how this works?  I just backported the setup from `llvm`/`llvm@14`.

**Comment by carlocab** [comment]
It's not really for the dependency conflicts, since `python@3.*` will not produce those anymore. It was mostly to avoid needing a Homebrew Python 3 installed during the test, but also to make sure that what we've installed is flexible about the Python version.

Since it's just used in the `install` method we don't need a separate `python3` method, though. And the definition of `site_package` could be moved much lower to be closer to the point of use. We needed it before the `args` array for `lldb` before, but we don't ship `lldb` with this formula anymore.

**Comment by cho-m** [comment]
This does mean we will want to migrate `llvm@*` before migrating next `python@3.{11,12,...}` alias as the test would be broken on Linux as the bindings won't exist yet.

Not sure how we were planning to handle the upcoming Python 3.11 migration. It won't matter if we end up doing a similar process like previous migrations (`python@3.11` creation with altinstall, migrate almost all dependents, `python@3.11` as alias).

**Review by jonchang — APPROVED** [review]

**Pull request closed without merging**
