### PR TITLE
go 1.17.6

### PR DESCRIPTION
**Pull request by jidicula**
Created with `brew bump-formula-pr`.

`resource` blocks may require updates.

### CODE REVIEW

**Comment by Moisan** [comment]
`orgalorg` seems to have been retagged. I [opened an issue upstream](https://github.com/reconquest/orgalorg/issues/38) to confirm.

**Comment by dadrian** [comment]
@Moisan Do we have to wait for `orgalorg` to respond? Manually auditing the two commits in `orgalorg` indicates the difference is entirely in the Github Actions workflow YAML, changing the Go version used in CI. In the mean time, anyone on Monterey running `go test` on a package where tests create subprocesses is experiencing [SIGABRTs](https://github.com/golang/go/issues/50073) on a regular basis, so it would be very nice to get this merged.

**Comment by iMichka** [comment]
Here is a PR to fix `orgalorg`: #92847. Ideally they should respond quickly, checksum changes are a major security concern. As the change looks legit we are going to move forward a little bit quicker ...

**Comment by iMichka** [comment]
I will rebase this soon. Our CI queue is full so we need to prioritise.
I added the `skip-recursive-dependents` label to skip one level of dependencies, else the job times out after 3 days.

**Review by carlocab — APPROVED** [review]
In favour of merging this as soon as CI finishes.

**Comment by jidicula** [comment]
```
brew fetch --build-from-source --retry leaf
brew fetch --build-from-source --retry lean-cli
brew fetch --build-from-source --retry leaps
brew fetch --build-from-source --retry lefthook
brew fetch --build-from-source --retry lego
brew fetch --build-from-source --retry lf
brew fetch --build-from-source --retry liqoctl
brew fetch --build-from-source --retry logcli
brew test --retry --verbose logcli
brew fetch --build-from-source --retry lunchy-go
```

**Review by iMichka — APPROVED** [review]

**Comment by iMichka** [comment]
Agreed, let's ship this. Most of the errors look unrelated (networking errors). `skip-recursive-dependents` was not enough to finish the build in 3 day so this is a little bit worrying, but the CI-build-depents-from-source flag maybe overrides that one.

**Pull request closed without merging**
