### PR TITLE
rethinkdb 2.4.1

### PR DESCRIPTION
**Pull request by chenrui333**
followup of #59643

### CODE REVIEW

**Comment by carlocab** [comment]
Why not use the patch from the commit in your PR?

**Comment by chenrui333** [comment]
that also works. let me update to use my patch.

**Comment by carlocab** [comment]
Thanks. A resource-block-style patch is better since it's less prone to being changed accidentally. See, for example, https://github.com/Homebrew/homebrew-core/pull/66898.

**Comment by chenrui333** [comment]
I see, that is a good lesson learned. Thanks!

**Comment by fxcoudert** [comment]
If it works on Big Sur, I'd like to try ARM to see if it works; if it doesn't feel free to remove the label.

**Comment by chenrui333** [comment]
looks like it does not quite work.

**Comment by fxcoudert** [comment]
Sorry, I think we had to try :) I'll restart the tests again, without ARM, so we can merge.

**Comment by chenrui333** [comment]
totally, also link the upstream ARM build issue tracker. :)

**Pull request closed without merging**
