### PR TITLE
asciinema 1.3.0

### PR DESCRIPTION
**Pull request by youtux**
- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

Asciinema switched to Python 3 (see https://github.com/asciinema/discussions/issues/143).
Therefore the simple version bump in PR https://github.com/Homebrew/homebrew-core/pull/2966 will not work.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@youtux please do not deliberately duplicate pull requests.

**Comment by youtux** [comment]
@ilovezfs I was not *deliberately* duplicating your PR, I created this one after the announce by the asciinema team. I found your PR just before submitting mine.

**Comment by ilovezfs** [comment]
@youtux In the future, please just ask first if you see there's a duplicate that you'd like to replace.

**Comment by anbotero** [comment]
👍

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/4834810ab662769ccccb4a664d24acaea6b129e2. Thank you for another contribution to Homebrew @youtux; we appreciate it! :smiley_cat:

**Pull request closed without merging**
