### PR TITLE
ruby-build 20231225

### PR DESCRIPTION
**Pull request by mislav**
Created by https://github.com/mislav/bump-homebrew-formula-action

### CODE REVIEW

**Comment by ingemar** [comment]
Bump!

**Comment by ssaunier** [comment]
👋 sorry I'm new to Homebrew, I guess as soon as this one gets merged we'll have the 3.3.0 definition available after a:

```bash
brew upgrade ruby-build
```

Right?

Merry Christmas!

**Comment by mechiland** [comment]
> 👋 Sorry I'm new to Homebrew, I guess as soon as this one gets merged we'll have the 3.3.0 definition available after a:
> 
> ```shell
> brew update
> brew upgrade ruby-build
> ```
> 
> Right?
> 
> Merry Christmas!

Yes. Just wait the team to approve this PR.

**Comment by mechiland** [comment]
> 👋 Sorry I'm new to Homebrew, I guess as soon as this one gets merged we'll have the 3.3.0 definition available after a:
> 
> ```shell
> brew update
> brew upgrade ruby-build
> ```
> 
> Right?
> 
> Merry Christmas!

Yes. Just wait the team to approve this PR.

**Review by bevanjkay — APPROVED** [review]

**Pull request merged**
