### PR TITLE
rust 1.50.0

### PR DESCRIPTION
**Pull request by Bo98**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by carlocab** [comment]
On ARM:

<details><summary>Error: 74 failed steps!</summary>
<p>

```
Error: 74 failed steps!
brew install --build-from-source amp
brew fetch --retry asuka
brew install --build-from-source bandwhich
brew install --build-from-source boringtun
brew test --retry --verbose caffe
brew test --retry --verbose chromaprint
brew install --build-from-source click
brew install --build-from-source --only-dependencies dartsim
brew install --build-from-source dartsim
brew install --build-from-source --only-dependencies dog
brew install --build-from-source dog
brew install --build-from-source dprint
brew install --build-from-source --only-dependencies efl
brew install --build-from-source efl
brew install --build-from-source fblog
brew test --retry --verbose ffmpegthumbnailer
brew install --build-from-source ffsend
brew test --retry --verbose fnm
brew install --build-from-source git-trim
brew install --build-from-source gjs
brew install --build-from-source --onl-dependencies gnuradio
brew install --build-from-source gnuradio
brew install --build-from-source grin
brew install --build-from-source grin-wallet
brew test --retry --verbose ktmpl
brew install --only-dependencies --include-test kubie
brew test --retry --verbose kubie
brew install --build-from-source --only-dependencies lablgtk
brew install --build-from-source lablgtk
brew test --retry --verbose libgit2-glib
brew test --retry --verbose mat2
brew install --build-from-source --only-dependencies mlpack
brew install --build-from-source mlpack
brew test --retry --verbose mlt
brew install --build-from-source --only-dependencies moc
brew install --build-from-source moc
brew install --build-from-source mpv
brew install --build-from-source ocrmypdf
brew install --build-from-source openalpr
brew test --retry --verbose openimageio
brew install --build-from-source pcb2gcode
brew install --build-from-source pdfpc
brew install --build-from-source --only-dependencies pdfsandwich
brew install --build-from-source pdfsandwich
brew install --build-from-source --only-dependencies pushpin
brew install --build-from-source pushpin
brew install --build-from-source --only-dependencies qmmp
brew install --build-from-source qmmp
brew install --build-from-source rbspy
brew install --build-from-source ripgrep-all
brew install --build-from-source rm-improved
brew install --build-from-source root
brew install --build-from-source rustscan
brew test --retry --verbose saltwater
brew install --build-from-source shadowenv
brew install --build-from-source silicon
brew install --build-from-source --only-dependencies siril
brew install --build-from-source siril
brew install --build-from-source so
brew test --retry --verbose so
brew install --build-from-source sonic
brew install --build-from-source spotifyd
brew install --build-from-source ssh-permit-a38
brew install --build-from-source tree-sitter
brew test --retry --verbose tree-sitter
brew install --build-from-source uutils-coreutils
brew install --build-from-source vice
brew install --build-from-source visp
brew install --build-from-source volta
brew install --build-from-source wagyu
brew install --build-from-source wapm
brew install --build-from-source wasm-pack
brew test --retry --verbose xdot
brew install --build-from-source zimy
```

</p>
</details>

Most of these failures haven't been bottled for ARM. The ones that have been are: `mpv`, `so`, and `tree-sitter`.

`tree-sitter` is likely due to problems with `emscripten`: #70200 The `emscripten` (build-only) dependency is optional. We can drop it on ARM, or drop it altogether. Also relevant on Linux: https://github.com/Homebrew/linuxbrew-core/issues/22225

**Comment by Bo98** [comment]
Seems like they might all be pre-existing failures. I think I have patch that should cover node dependents (emscripten etc) - I'll experiment over the weekend.

11 failures on 10.14 is a little bit concerning, but it seems it's that high because a few are just network failures. The rest should be fixable in one pass.

(10.15 and 11.0 still going as I write this.)

**Comment by Peneheals** [comment]
I know that High Sierra is not supported and I'm not complaining at all, just want to note that this issue was mentioned after my `brew install --build-from-source rust` command almost ( :D ) finished. These are the last few rows (I expanded with 10 more relevant rows from the mentioned cargo log file). Maybe it helps, may not:

```
(...)
==> Installing rust dependency: libssh2
==> Pouring libssh2-1.9.0_1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libssh2/1.9.0_1: 184 files, 941.6KB
==> Installing rust
==> ./configure --prefix=/usr/local/Cellar/rust/1.49.0_1 --release-channel=stabl
==> make
==> make install
==> ./install.sh --prefix=/private/tmp/rust-20210218-9205-5rhxia/rustc-1.49.0-sr
==> cargo install /usr/local/Cellar/rust/1.49.0_1 --features curl-sys/force-syst
Last 25 lines from /Users/chp/Library/Logs/Homebrew/rust/05.cargo:
   Compiling cargo v0.50.0 (/private/tmp/rust--cargo-20210218-9205-1maehiy)
   Compiling rustfix v0.5.1
   Compiling crates-io v0.31.1 (/private/tmp/rust--cargo-20210218-9205-1maehiy/crates/crates-io)
   Compiling git2 v0.13.17
   Compiling git2-curl v0.14.1
error[E0283]: type annotations needed
   --> src/cargo/util/config/de.rs:530:63
    |
530 |                 seed.deserialize(Tuple2Deserializer(1i32, env.as_ref()))
    |                                                           ----^^^^^^--
    |                                                           |   |
    |                                                           |   cannot infer type for type parameter `T` declared on the trait `AsRef`
    |                                                           this method call resolves to `&T`
    |
    = note: cannot satisfy `std::string::String: AsRef<_>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0283`.
error: failed to compile `cargo v0.50.0 (/private/tmp/rust--cargo-20210218-9205-1maehiy)`, intermediate artifacts can be found at `/private/tmp/rust--cargo-20210218-9205-1maehiy/target`

Caused by:
  could not compile `cargo`

To learn more, run the command again with --verbose.

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
rust 1.50.0 https://github.com/Homebrew/homebrew-core/pull/70922
Rust-dependent formulae on Apple Silicon - upstream issue tracker https://github.com/Homebrew/homebrew-core/issues/68301

Error: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
```

Maybe this is the related issue, and the problem almost solved? https://github.com/rust-lang/cargo/issues/9124

**Comment by Bo98** [comment]
That'll be fixed by this update (1.50.0). I hope to get it shipped this weekend.

**Comment by blazczak** [comment]
Same issue as @Peneheals. After hours of chewing on make, the build failed with that exact same error.

**Comment by carlocab** [comment]
ARM failures with bottles:
```
brew install --build-from-source cargo-c
brew install --build-from-source mpv
brew install --build-from-source varnish
```

**Comment by Bo98** [comment]
ARM:

- `cargo-c` - surprising failure, logs actually show it was built successfully.
- `mpv` - pre-existing
- `varnish` - url changed again

Big Sur:

- `asuka` - known failure, unbottled on Big Sur
- `gjs` - actual breakage, can be fixed by updating mozjs to 78.8.0 (might do that in a separate PR)
- `ktmpl` - pre-existing
- `varnish` - as with ARM
- `vice` - I cannot reproduce this, but it is definitely not Rust related
- `wasm-pack` - pre-existing

Catalina:

- `deno` - random failure, `deno` builds are not very stable
- `gjs` - as above
- `ktmpl` - as above
- `ppsspp` - disk space issue
- `varnish` - as above
- `vice` - as above
- `wasm-pack` - as above

Mojave:

- `gjs` - as above
- `ktmpl` - as above
- `varnish` - as above
- `vice` - as above
- `wasm-pack` - as above

**Comment by carlocab** [comment]
`vice` almost certainly isn't due to this version bump. I've encountered it in a previous Rust version bump. I think the issue is that one of its (possibly recursive) dependencies is unlinked prior to its build because of a `conflicts_with` call, and that causes `vice` to fail to build.

**Comment by Bo98** [comment]
(2 days CI run is too long to warrant re-running just for `gjs` and the random `cargo-c` failure)

**Comment by Bo98** [comment]
> one of its (possibly recursive) dependencies is unlinked prior to its build because of a `conflicts_with` call, and that causes `vice` to fail to build.

This will be a test-bot bug then - I'll look into this.

**Comment by carlocab** [comment]
`vice` [complains](https://github.com/Homebrew/homebrew-core/pull/70922/checks?check_run_id=2000539075#step:7:4852) about `glew` not being installed, because it was unlinked [here](https://github.com/Homebrew/homebrew-core/pull/70922/checks?check_run_id=2000539075#step:7:3881).

**Comment by carlocab** [comment]
Looks like there are a bunch of Rust-dependent formulae that don't have ARM bottles but didn't show up as a failure on the ARM runner. Going to dispatch bottle jobs for those.

**Comment by blazczak** [comment]
Re-tried and was able to build rust from source

```
==> ./configure --prefix=/usr/local/Cellar/rust/1.50.0 --release-channel=stable
==> make
==> make install
==> ./install.sh --prefix=/private/tmp/rust-20210305-84198-9tnp6/rustc-1.50.0-sr
==> cargo install /usr/local/Cellar/rust/1.50.0 --features curl-sys/force-system
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/rust/1.50.0: 20,084 files, 708.7MB, built in 545 minutes 17 seconds
```

Thanks for fixing the underlying issue.

**Pull request closed without merging**
