### PR TITLE
magic-wormhole: migrate to `python@3.12`

### PR DESCRIPTION
**Pull request by branchv**
magic-wormhole: migrate to `python@3.12`

### CODE REVIEW

**Comment by chenrui333** [comment]
```
/private/tmp/magic-wormhole--spake2-20231029-6915-15b4eyh/spake2-0.8/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
  LONG_VERSION_PY['git'] = '''
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "<pip-setuptools-caller>", line 34, in <module>
  File "/private/tmp/magic-wormhole--spake2-20231029-6915-15b4eyh/spake2-0.8/setup.py", line 62, in <module>
    version=versioneer.get_version(),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/magic-wormhole--spake2-20231029-6915-15b4eyh/spake2-0.8/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/private/tmp/magic-wormhole--spake2-20231029-6915-15b4eyh/spake2-0.8/versioneer.py", line 1412, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/magic-wormhole--spake2-20231029-6915-15b4eyh/spake2-0.8/versioneer.py", line 342, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
error: subprocess-exited-with-error
```

**Comment by chenrui333** [comment]
https://github.com/magic-wormhole/magic-wormhole/issues/509

**Comment by branchvincent** [comment]
@chenrui333 I think you copied the wrong log in your issue. But looks like upstream already made changes to support 3.12, just needs to be released

**Comment by chenrui333** [comment]
oh yeah, that is right, let me update that issue and close it.

**Review by chenrui333 — APPROVED** [review]

**Pull request merged**
