### PR TITLE
vit: switch to pypi source and update head and livecheck

### PR DESCRIPTION
**Pull request by chenrui333**
vit: switch to pypi source

### CODE REVIEW

**Comment by fxcoudert** [comment]
If the source tarball checksum changes, then the source is not the same and we have to test it, so it's not `CI-syntax-only`

**Comment by chenrui333** [comment]
Sounds good with me, I will do the rebase and have CI regression test it.

**Review by dtrodrigues — COMMENTED** [review]
Can the head url be updated to https://github.com/vit-project/vit ?

**Review by Rylan12 — COMMENTED** [review]
We should change the `livecheck` to use the new PyPI URL:

```ruby
livecheck do
  url :stable
end
```

**Review by Rylan12 — APPROVED** [review]

**Pull request closed without merging**
