### PR TITLE
atuin 0.9.1

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by chenrui333** [comment]
```
  ==> atuin history list
  thread 'main' panicked at 'failed to find ATUIN_SESSION - check your shell setup: NotPresent', atuin-client/src/database.rs:30:35
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  Error: test failed
  
  Error: atuin: failed
  An exception occurred within a child process:
    Minitest::Assertion: Expected: 0
    Actual: 101
```

**Comment by conradludgate** [comment]
With normal usage of atuin, the `atuin init zsh` script gets run which sets up the `ATUIN_SESSION` environment variable. So this is expected (this has existed for many versions)

I'm not familiar with how homebrew formulas are set up, but there should be a way to create the environment variable I presume

**Comment by ellie** [comment]
Using `ATUIN_SESSION=literallyanyvalueatall atuin history list` instead should work - we do expect this variable to be present

**Comment by chenrui333** [comment]
Thanks both, the test works for me now.

**Review by SMillerDev — APPROVED** [review]

**Pull request closed without merging**
