### PR TITLE
wget 1.19

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
GNU.

**Comment by JCount** [comment]
Upstream bug report at http://savannah.gnu.org/bugs/?50223

**Comment by zmwangx** [comment]
Upstream problem is almost resolved now. That said, I want to bring up a different topic (bringing up now because I might very well forget about it later): I suggest making `--with-iri` the default. Arguments supporting this suggestion:

- It is the default in upstream's `configure`, we're disabling it with the option `--disable-iri`;
- It only introduces a very lightweight dependency, `libidn`;
- It's 2017 now, IRI is widely used and even being promoted to basically the same status as URI in W3's [HTML5 working draft](https://dev.w3.org/html5/spec-LC/urls.html).

**Comment by ilovezfs** [comment]
@zmwangx that sounds fine since this is already saddled with the rather heavy openssl => :recommended

**Comment by ilovezfs** [comment]
Will be fixed in 1.19.1 in a few days

**Comment by DomT4** [comment]
The `openssl` shouldn't be recommended. That was presumably another oversight by Mike when `libressl` was removed from the core with a sledgehammer. It should be the default.

If you have `openssl` installed already `--without-openssl` is simply ignored:
```
/usr/local/bin/wget:
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
```
And if you don't have `openssl` installed already `wget` just fails:
```
checking for libssl... no
configure: error: --with-ssl=openssl was given, but SSL is not available.
```

**Comment by ilovezfs** [comment]
>openssl shouldn't be recommended

Can't we do this:
```
if build.with? "openssl"
  args << "--with-ssl=openssl" 
else
  args << "--with-openssl=no"
end
```

**Comment by DomT4** [comment]
I'm not sure what practical use a wget without SSL/TLS capability has in 2017.

**Comment by ilovezfs** [comment]
>I'm not sure what practical use a wget without SSL/TLS capability has in 2017.

OK, so it's a "that's useless" objection as opposed to a "recommended can't work here" objection.

**Comment by zmwangx** [comment]
> I'm not sure what practical use a wget without SSL/TLS capability has in 2017.

Actually, the default SSL backend of Wget is GnuTLS rather than OpenSSL (yeah, I know, the GnuTLS project has been condemned by various people), so not compiled against OpenSSL != no SSL capability.

**Comment by ilovezfs** [comment]
Right but we don't depend on gnutls here so I guess you'd get no ssl or gnutls depending on whether gnutls happened to be installed?

**Comment by zmwangx** [comment]
The formula has to be modified anyway, so adding GnuTLS could be an option... Not that I'm in favor of that, just pointing out OpenSSL isn't the only way to go.

**Comment by ilovezfs** [comment]
I think current Orthodox Brewism would require, non-optionally, both openssl and libidn.

**Comment by DomT4** [comment]
All I can add is good luck to anyone getting a second crypto option added optionally given recent discussions on this. Rather you than me :')

**Comment by MikeMcQuaid** [comment]
@DomT4 The passive aggressive comments aren't welcome. Just because I don't immediately reply to them doesn't mean 1) I don't read them and 2) it's most blatantly obvious you aren't talking about me.

In this case I'm fine with making OpenSSL not `:recommended` but a mandatory dependency. Increasingly I think `:recommended` just adds to our support burden and isn't terribly useful to users when it's not `Install Y rather than X`.

**Comment by DomT4** [comment]
For the record beyond my reply to you elsewhere, on my final comment above, I was referring simply to the team consensus being fairly strong option simplification, and knowing that anyone pushing against that firmly was likely to end up frustrated. This was maybe left unclear because I replied via email quickly rather than quoting the zmw comment specifically. But I don't see how that was unfair given the prior public discussions that happened at the time.

**Comment by MikeMcQuaid** [comment]
> This was maybe left unclear because I replied via email quickly rather than quoting the zmw comment specifically.

Perhaps, yes. Let's both try to not reply to things too quickly if it removes necessary context.

**Pull request closed without merging**
