### PR TITLE
include-what-you-use 0.14

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by issyl0** [comment]
Line 14: `depends_on "llvm" # include-what-you-use 0.13 is compatible with llvm 9.0`

The IWYU docs say that this version is compatible with LLVM 10, which our `llvm` formula is. 🤷 In any case, when this works that comment needs to be removed. 😄

**Comment by chenrui333** [comment]
Another thing worth calling out is upstream seems moved to use Ninja build instead of automake

**Comment by chenrui333** [comment]
same issue with the compilation

```
Last 15 lines from /Users/rchen/Library/Logs/Homebrew/include-what-you-use/02.ninja:
In file included from ../iwyu_ast_util.h:19:
In file included from ../iwyu_port.h:16:
In file included from /usr/local/opt/llvm/include/llvm/Support/raw_ostream.h:16:
In file included from /usr/local/opt/llvm/include/llvm/ADT/SmallVector.h:21:
/usr/local/opt/llvm/include/llvm/Support/type_traits.h:101:64: error: a space is required between consecutive right angle brackets (use '> >')
          ::llvm::detail::copy_construction_triviality_helper<T>> {};
                                                               ^~
                                                               > >
/usr/local/opt/llvm/include/llvm/Support/type_traits.h:112:64: error: a space is required between consecutive right angle brackets (use '> >')
          ::llvm::detail::move_construction_triviality_helper<T>> {};
                                                               ^~
                                                               > >
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
ninja: build stopped: subcommand failed.
```

My current diff.
```
diff --git a/Formula/include-what-you-use.rb b/Formula/include-what-you-use.rb
index ea6783dbf8c..6bc74577746 100644
--- a/Formula/include-what-you-use.rb
+++ b/Formula/include-what-you-use.rb
@@ -10,26 +10,30 @@ class IncludeWhatYouUse < Formula
     sha256 "b7dbc7e9f3504f1902b9f63de1c802812729c2ae395c4d85b0dab5a10835bd60" => :high_sierra
   end

+  depends_on "llvm" => :build
   depends_on "cmake" => :build
-  depends_on "llvm" # include-what-you-use 0.13 is compatible with llvm 9.0
+  depends_on "ninja" => :build

   uses_from_macos "ncurses"
   uses_from_macos "zlib"

   def install
+    ENV["CLANG_PATH"] = Formula["llvm"].opt_bin/"clang"
+
     # We do not want to symlink clang or libc++ headers into HOMEBREW_PREFIX,
     # so install to libexec to ensure that the resource path, which is always
     # computed relative to the location of the include-what-you-use executable
     # and is not configurable, is also located under libexec.
     args = std_cmake_args + %W[
+      -GNinja
       -DCMAKE_INSTALL_PREFIX=#{libexec}
       -DCMAKE_PREFIX_PATH=#{Formula["llvm"].opt_lib}
     ]

     mkdir "build" do
       system "cmake", *args, ".."
-      system "make"
-      system "make", "install"
+      system "ninja", "-v"
+      system "ninja", "install", "-v"
     end
```

**Comment by chenrui333** [comment]
not actively working on this, close the PR now.

**Pull request closed without merging**
