### PR TITLE
Fix remaining Boost packages  on Apple silicon

### PR DESCRIPTION
**Pull request by andysan**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

Patch Boost's build system to build cleanly on Apple Silicon. This ports PR #59257 to the remaining boost packages.

### CODE REVIEW

**Comment by carlocab** [comment]
Thanks; can you include a comment before each patch that explains when they can be removed? A link to a tracking issue, PR, or similar would also work.

**Comment by andysan** [comment]
> Thanks; can you include a comment before each patch that explains when they can be removed? A link to a tracking issue, PR, or similar would also work.

It has already been merged upstream, but there is currently no upstream release that includes it. I added a note saying that this is the case to remind whoever update the formula to remove the patch when they bump the Boost version.

**Comment by carlocab** [comment]
boost-bcp [did not build](https://github.com/Homebrew/homebrew-core/pull/68272/checks?check_run_id=1645527166#step:7:128).

```
Error: 1 failed steps!
brew install --verbose --build-bottle boost-bcp
```

```
ld: unknown/unsupported architecture name for: -arch armv4t
clang: error: linker command failed with exit code 1 (use -v to see invocation)

    "g++"  -o "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/bcp" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/add_dependent_lib.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/add_path.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/bcp_imp.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/copy_path.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/file_types.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/fileview.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/main.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/path_operations.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/scan_cvs_path.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/licence_info.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/scan_licence.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/output_licence_info.o" "../../bin.v2/libs/filesystem/build/darwin-12.0.0/release/link-static/visibility-hidden/libboost_filesystem.a" "../../bin.v2/libs/regex/build/darwin-12.0.0/release/link-static/visibility-hidden/libboost_regex.a"       -Wl,-dead_strip -no_dead_strip_inits_and_terms -arch arm 
       

...failed darwin.link ../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/bcp...
```

**Comment by andysan** [comment]
> boost-bcp [did not build](https://github.com/Homebrew/homebrew-core/pull/68272/checks?check_run_id=1645527166#step:7:128).
> 
> ```
> Error: 1 failed steps!
> brew install --verbose --build-bottle boost-bcp
> ```
> 
> ```
> ld: unknown/unsupported architecture name for: -arch armv4t
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
>     "g++"  -o "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/bcp" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/add_dependent_lib.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/add_path.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/bcp_imp.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/copy_path.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/file_types.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/fileview.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/main.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/path_operations.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/scan_cvs_path.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/licence_info.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/scan_licence.o" "../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/output_licence_info.o" "../../bin.v2/libs/filesystem/build/darwin-12.0.0/release/link-static/visibility-hidden/libboost_filesystem.a" "../../bin.v2/libs/regex/build/darwin-12.0.0/release/link-static/visibility-hidden/libboost_regex.a"       -Wl,-dead_strip -no_dead_strip_inits_and_terms -arch arm 
>        
> 
> ...failed darwin.link ../../bin.v2/tools/bcp/darwin-12.0.0/release/link-static/bcp...
> ```

Weird, I was certain I had tested that one Weirdly,it turns out the boost-bcp package uses b2 from boost-build rather than the private copy like all of the other boost packages. I have dropped the separate change to boost-bcp.rb since that isn't needed and applied it to boost-build instead (which solves the issue for any package that depends on boost-build).

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
Thanks for your contribution, @andysan!

**Pull request closed without merging**
