### PR TITLE
ruby 3.2.0

### PR DESCRIPTION
**Pull request by dawidd6**
Created with `brew bump-formula-pr`.

~~`resource` blocks may require updates.~~

### CODE REVIEW

**Comment by dawidd6** [comment]
`weechat` fails to build:

```
--   Found python3-embed, version 3.10
  -- Checking for one of the modules 'ruby-3.1;ruby-3.0;ruby-2.7;ruby-2.6;ruby-2.5;ruby-2.4;ruby-2.3;ruby-2.2;ruby-2.1;ruby-2.0;ruby-1.9;ruby'
  CMake Error at src/plugins/CMakeLists.txt:116 (message):
    Ruby not found

```

**Comment by faisal** [comment]
Can you add a `depends_on "rust" => :build` for the source build, as is used for HEAD builds? Without using Rust to build, the produced Ruby won't include YJIT support.

**Comment by faisal** [comment]
N.b. Ruby 3.2 explicitly shifted a number of dependencies -- see "No longer bundle 3rd party sources" in https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/. Have you considered if this formula depends on the right things, with an eye to what's described in https://github.com/ruby/ruby/blob/master/doc/contributing/building_ruby.md?

Also, I am surprised this builds without explicitly depending on bison. The Ruby 3.2 build docs claim this is a build requirement, and HEAD won't build without it (so we have it as an explicit dependency for HEAD builds already), but I have confirmed this will build from source without it (on macOS Ventura, with the latest Xcode and Command Line Tools installed).

**Comment by faisal** [comment]
This changes the PR up to what the Ruby build docs claim is needed (including `rust` for YJIT support) and in my tests on macOS Ventura (at least) produces a working binary:

```
diff --git a/Formula/ruby.rb b/Formula/ruby.rb
index d1aa4f3d34e..6c865809b78 100644
--- a/Formula/ruby.rb
+++ b/Formula/ruby.rb
@@ -40,13 +40,15 @@ class Ruby < Formula
 
   keg_only :provided_by_macos
 
-  depends_on "pkg-config" => :build
+  depends_on "autoconf" => :build # Also depended by libyaml, but declaring here for clarity
+  depends_on "bison" => :build
+  depends_on "rust" => :build
   depends_on "libyaml"
-  depends_on "openssl@1.1"
+  depends_on "openssl"
   depends_on "readline"
 
+  uses_from_macos "gperf"
   uses_from_macos "libffi"
-  uses_from_macos "libxcrypt"
   uses_from_macos "zlib"
 
   def api_version
```

**Comment by dawidd6** [comment]
If I put `depends_on "rust" => :build` to the `ruby` formula we get a circular dependency to `ruby`:
```
rust[build]
  curl
    openldap
      util-linux
        asciidoctor[build]
          ruby
```

**Comment by faisal** [comment]
I suspect this works on macOS because Homebrew can rely on the built-in Ruby before it builds its (bottle-only) Ruby.

Is this dependency only an issue if building everything from source? If so, is it reasonable to expect users to bootstrap, e.g. install a bottled Rust, then use that to build Ruby from source, and then if necessary go back and build Rust from source as well? Are there any other good examples of circular dependencies, and how Homebrew handles them or expects users to handle them?

**Comment by SMillerDev** [comment]
If building util-linux with meson the asciidoctor dependency isn't required. But I'll wait for other suggestions from @Homebrew/maintainers

**Comment by danielnachun** [comment]
I would love to see us drop the `asciidoctor` build dependency for `util-linux`.  `util-linux` is a non-relocatable dependency of `curl` and complicates the Linux bootstrapping process substantially on older systems.  And as per our usual policy, documentation is readily available online.

**Comment by dawidd6** [comment]
CI tests were not triggered...

**Comment by dawidd6** [comment]
On Linux:
```
==> Testing style-check
  ==> /home/linuxbrew/.linuxbrew/Cellar/style-check/0.14/bin/style-check.rb -v paper.tex
  (none):118: warning: mismatched indentations at 'else' with 'if' at 83
  (none):120: warning: mismatched indentations at 'end' with 'else' at 118
  (none):159: warning: assigned but unused variable - r
  (none):161: warning: assigned but unused variable - windows_detect_bug_avoider
  /home/linuxbrew/.linuxbrew/Cellar/style-check/0.14/bin/style-check.rb:166:in `do_cns': undefined method `=~' for false:FalseClass (NoMethodError)
  	from /home/linuxbrew/.linuxbrew/Cellar/style-check/0.14/bin/style-check.rb:216:in `block (2 levels) in <main>'
  	from /home/linuxbrew/.linuxbrew/Cellar/style-check/0.14/bin/style-check.rb:191:in `each'
  	from /home/linuxbrew/.linuxbrew/Cellar/style-check/0.14/bin/style-check.rb:191:in `each_with_index'
  	from /home/linuxbrew/.linuxbrew/Cellar/style-check/0.14/bin/style-check.rb:191:in `block in <main>'
  	from /home/linuxbrew/.linuxbrew/Cellar/style-check/0.14/bin/style-check.rb:184:in `each'
  	from /home/linuxbrew/.linuxbrew/Cellar/style-check/0.14/bin/style-check.rb:184:in `<main>'
  paper.tex:1:19: Today I worked on homebrew (homebrew)
```

**Comment by faisal** [comment]
And there's a new Rubygems release: https://github.com/rubygems/rubygems/releases/tag/v3.4.2

**Comment by faisal** [comment]
This patches the rubygems lines to the latest and greatest: https://github.com/dawidd6/homebrew-core/pull/2

**Comment by chenrui333** [comment]
13-arm test failure

```
  ==> /usr/bin/clang++ test.cpp -o test -I/opt/homebrew/Cellar/cucumber-cpp/0.5_9/include -L/opt/homebrew/Cellar/cucumber-cpp/0.5_9/lib -lcucumber-cpp -I/opt/homebrew/opt/boost/include -L/opt/homebrew/opt/boost/lib -lboost_regex -lboost_system -lboost_program_options -lboost_filesystem -lboost_chrono -pthread
  ==> /private/tmp/cucumber-cpp-test-20230103-86767-1urfr7g/bin/cucumber --publish-quiet
  Unable to contact the wire server at localhost:3902. Is it up? (Cucumber::Wire::Connection::ConnectionError)
```

**Comment by cho-m** [comment]
This PR may need to manually squash commits per formula given it is labeled `automerge-skip` due to modifying Alias.

**Comment by faisal** [comment]
I think this is a test/env issue. The specific test passes for me on my machine.

Possibly more info here: https://stackoverflow.com/a/50781824

**Comment by dawidd6** [comment]
Same issue happened earlier with Ruby 3.1.0: https://github.com/Homebrew/homebrew-core/pull/92024

**Comment by faisal** [comment]
> Same issue happened earlier with Ruby 3.1.0: #92024

If the `cucumber-cpp` CI failure is otherwise unrelated to this PR, should we we open an issue to track down and address the underlying cause of failure, and land this PR in the meantime?

**Comment by faisal** [comment]
It looks like this also happened with Boost 1.75: https://github.com/Homebrew/homebrew-core/pull/66792.

**Comment by cho-m** [comment]
@dawidd6 can you squash the commits, unless you are planning to manually merge. Would make it easier to pr-publish later on without having to manually tweak commits.

**Comment by faisal** [comment]
The cucumber-cpp project's issues list hints at some general problems with the wire protocol and with Ruby 3.1 and later, e.g. https://github.com/cucumber/cucumber-cpp/issues/200. @jermus67 might have thoughts on what's going on here.

**Review by cho-m — DISMISSED** [review]

**Comment by cho-m** [comment]
In separate PR, we should try adding a sleep after the fork in `cucumber-cpp` test.

**Review by chenrui333 — DISMISSED** [review]

**Comment by chenrui333** [comment]
let's merge the PR for now and followup the test updates separately.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
