### PR TITLE
python@3.8 3.8.3

### PR DESCRIPTION
**Pull request by jnozsc**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
Failed on Catalina tests:
```
brew test --verbose alure
brew test --verbose dromeaudio
brew test --verbose game-music-emu
brew test --verbose glyr
brew linkage --test gst-plugins-bad
brew test --verbose h2o
brew test --verbose nanomsg
brew test --verbose nng
brew linkage --test nvc
```

**Comment by jnozsc** [comment]
it is quite weird that those failed testing are not depends on `python@3.8`, I thought I could just bump those Formula when there is a dependence issue on `python@3.8`, but now I am not sure which Formula I should continue work on it.

**Comment by alebcay** [comment]
Failures:
<details>
<summary>Details</summary>

```
==> /usr/local/Cellar/alure/1.2_1/bin/alureplay /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/test.wav
Killing child processes...
Error: alure: failed
An exception occurred within a child process:
  Timeout::Error: execution expired
/usr/local/Homebrew/Library/Homebrew/formula.rb:1978:in `gets'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1978:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1951:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1951:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/alure.rb:36:in `block in <class:Alure>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1821:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1820:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:888:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1819:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2063:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2062:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1813:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:35:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:34:in `<main>'
```

</details>

<details>
<summary>Details</summary>

```
==> brew test --verbose dromeaudio
==> FAILED
Testing dromeaudio
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200514-44181-ewfkqw.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/dromeaudio.rb --verbose
==> /usr/local/Cellar/dromeaudio/0.3.0/bin/DromeAudioPlayer /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/test.mp3
DromeAudio Exception: AudioDriverOSX::AudioDriverOSX(): AudioUnitSetProperty (for StreamFormat) failed
Audio driver initialization failed
Error: dromeaudio: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/dromeaudio/0.3.0/bin/DromeAudioPlayer /usr/local/Homebrew/Library/Homebrew/test/support/fixtures/test.mp3
/usr/local/Homebrew/Library/Homebrew/formula.rb:2013:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1951:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1951:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/dromeaudio.rb:26:in `block in <class:Dromeaudio>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1821:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1820:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:888:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1819:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2063:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2062:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1813:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:35:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:34:in `<main>'
```

</details>

**Comment by alebcay** [comment]
Accidentally closed/reopened the PR, but cancelled the new CI run. Old CI results should still be present.

**Comment by Bo98** [comment]
Most/all of them seem unrelated from first glance. Audio-related formulae fail a lot on the CI. The couple of linkage failures are not due to Python.

**Comment by Bo98** [comment]
The `nvc` issue is actually because it has LLVM as a build-only dependency. It seems like it should be a runtime dependency (or perhaps use system `libc++` instead if possible). This can be handled in a separate PR.

I think I know how to fix `percona-server` - I did something similar to MySQL a while back. It basically needs to use brew protobuf. I can handle this in a separate PR.

**Comment by jnozsc** [comment]
I have [nvc](https://github.com/Homebrew/homebrew-core/pull/54741)  and  [gst-plugins-bad](https://github.com/Homebrew/homebrew-core/pull/54770) fixing PRs accordingly.

**Comment by jnozsc** [comment]
Hi @Bo98 , 

Both `vnc` and `gst-plugins-bad` fixing PRs have been merged. 
I rebase on `master`, 
hopefully it will pass in next CI. 

If `percona-server` still has any issue, 
I may need your help on that.

**Comment by jnozsc** [comment]
@Bo98 it seems all of leftover are timeout/donwload issue with audio files for testing.

I am not sure whether there is anything else I can do for this PR

**Comment by SMillerDev** [comment]
Timeout issues are usually a test having a kill statement at the end that isn't triggered. Those can be removed nowadays so that should fix those.

As for the audio downloads, maybe we can look for alternative files?

**Comment by jnozsc** [comment]
thanks 

for `10.13` and `10.14`, CI fails on 
```
2020-05-28T10:30:23.4058680Z Error: 4 failed steps!
2020-05-28T10:30:23.4061130Z brew test --verbose agda
2020-05-28T10:30:23.4062400Z brew test --verbose alure
2020-05-28T10:30:23.4063230Z brew test --verbose bnfc
2020-05-28T10:30:23.4100710Z brew test --verbose dromeaudio
```

for `10.15`, CI fails on
```
2020-05-28T13:17:28.7597300Z brew test --verbose agda
2020-05-28T13:17:28.7597880Z brew test --verbose alure
2020-05-28T13:17:28.7598440Z brew test --verbose aom
2020-05-28T13:17:28.7599330Z brew test --verbose bnfc
2020-05-28T13:17:28.7630610Z brew test --verbose dromeaudio
```

When I read these formulas
https://github.com/Homebrew/homebrew-core/blob/master/Formula/agda.rb
https://github.com/Homebrew/homebrew-core/blob/master/Formula/alure.rb
https://github.com/Homebrew/homebrew-core/blob/master/Formula/bnfc.rb
https://github.com/Homebrew/homebrew-core/blob/master/Formula/bnfc.rb
https://github.com/Homebrew/homebrew-core/blob/master/Formula/dromeaudio.rb

I am confused that there is no kill statement?  
cc @SMillerDev

**Comment by jnozsc** [comment]
I believe I met the same issue as https://github.com/Homebrew/homebrew-core/pull/55191

**Comment by Bo98** [comment]
* `agda` - known - #55253
* `alure` - well-known random audio failure
* `aom` - networking blip (xiph.org servers are a little unreliable) - test passed fine on other runs
* `bnfc` - known - #55253
* `dromeaudio` - well-known random audio failure

**Review by Bo98 — DISMISSED** [review]

**Comment by Bo98** [comment]
Never seen that happen before. GitHub is currently serving corrupt zips for CI artifacts.

**Comment by Bo98** [comment]
Despite the corruption, the bottles themselves were salvageable and only the log files were lost in the damage. I've merged this manually.

Thanks and sorry that the process wasn't smooth!

**Comment by jnozsc** [comment]
thank all for helping on this.

**Pull request closed without merging**
