### PR TITLE
git-cola 4.0.1

### PR DESCRIPTION
**Pull request by PythonCoderAS**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by PythonCoderAS** [comment]
git-cola is a Python package. Not sure why it isn't declared as one.

**Comment by iMichka** [comment]
I see. Good catch, let's try this.
You are missing `include Language::Python::Virtualenv`, which can be added below the class / formula definition.

**Comment by iMichka** [comment]
> You do not seem to have PyQt5, PySide, or PyQt4 installed.

**Comment by PythonCoderAS** [comment]
> > You do not seem to have PyQt5, PySide, or PyQt4 installed.

That's odd because PyQt5 is declared as a dependency. Is the virtualenv not able to use the homebrew paths?

**Pull request closed without merging**
