### PR TITLE
Kibana 6.6.0 rebuild 1

### PR DESCRIPTION
**Pull request by mistic**
This PR fixes an issue with the current formula which was not including some assets folders introduced on `v6.6.0`. More info about the problem could be found https://github.com/elastic/kibana/issues/30186

@fxcoudert we need to generate new bottles, built with this PR formula, and also adding a bottle revision. Also, do you have any idea why we have such a complex formula, building almost everything from source, when a simpler and quicker solution would just be downloading the official built artifact that already includes everything we need?

### CODE REVIEW

**Comment by fxcoudert** [comment]
Homebrew ships open source software, built from source.

**Comment by mistic** [comment]
@fxcoudert thanks for the info. The idea was just prevent things like that to happening in the future, but I can agree with the `Homebrew` policy. I changed the logic behind which files/folder include from the build which could help avoid some other similar situations in the future.

**Comment by mistic** [comment]
@fxcoudert it looks like the build is green! Do you think we can get this merged please?

**Comment by fxcoudert** [comment]
poke @chrmoritz: does this seem ok to you?

**Comment by chrmoritz** [comment]
Yeah, sure. Ideally we should find a test, which actually tests some functionality too, but I guess this could be quite difficult here.

**Comment by fxcoudert** [comment]
Thanks @mistic for the pull request!

**Pull request closed without merging**
