### PR TITLE
youtube-dl: add shell completions and manpage

### PR DESCRIPTION
**Pull request by kidonng**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by DesWurstes** [comment]
Maybe:

```ruby
    zsh_completion.install "youtube-dl.zsh"
    man1.install "youtube-dl.1"
```

**Comment by kidonng** [comment]
@DesWurstes It seems like zsh completions is built-in: https://github.com/ytdl-org/youtube-dl/blob/01c92973ddebe6429f5a03855e41c412889c96dc/youtube-dl.plugin.zsh

However your suggestion on adding manpage is fine 👍

**Comment by kidonng** [comment]
Bump ⌛

**Comment by Rylan12** [comment]
Thanks for the PR, @kidonng! Sorry for the wait, must have slipped under maintainers radar.

The merge messed up our automerge system a little bit (in the future, we prefer rebases). No worries, though! I'll fix the conflict and push new changes. We will need CI to run again, though, but should be good then!

**Review by Rylan12 — DISMISSED** [review]

**Comment by Rylan12** [comment]
Thanks again, @kidonng! Not quote sure what happened with the merge but it looks like it _was_ successfully merged in https://github.com/Homebrew/homebrew-core/commit/94f246e04ff322b8a9b78d873962071c8da4a2d5.

**Pull request closed without merging**
