### PR TITLE
objfw 1.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Midar** [comment]
Should the test run `make check` to run the test suite? The previous release always ran the tests as part of a regular `make`, but 1.0 no longer does this.

**Comment by chenrui333** [comment]
what is the benefit of running `make check` in the package distribution level (I feel like that is more of the upstream's pipeline work)

**Comment by Midar** [comment]
It's up to you, but if you want to have a test that tests if things actually work (rather than just whether you can compile hello world), feel free to run `make check`. It's by no means necessary :).

**Comment by chenrui333** [comment]
that is true.

**Comment by chenrui333** [comment]
still failed with linkage failure

```
  @executable_path references in libraries:
    @executable_path/../Frameworks/ObjFW.framework/ObjFW
```

**Comment by Midar** [comment]
The following diff should help with that:

```diff
Index: build-aux/m4/buildsys.m4
==================================================================
--- build-aux/m4/buildsys.m4
+++ build-aux/m4/buildsys.m4
@@ -312,11 +312,11 @@
 		AS_IF([test x"$host_is_ios" = x"yes"], [
 			FRAMEWORK_LDFLAGS='-dynamiclib -current_version ${LIB_MAJOR}.${LIB_MINOR} -compatibility_version ${LIB_MAJOR}'
 			FRAMEWORK_LDFLAGS_INSTALL_NAME='-Wl,-install_name,@executable_path/Frameworks/$$out/$${out%.framework}'
 		], [
 			FRAMEWORK_LDFLAGS='-dynamiclib -current_version ${LIB_MAJOR}.${LIB_MINOR} -compatibility_version ${LIB_MAJOR}'
-			FRAMEWORK_LDFLAGS_INSTALL_NAME='-Wl,-install_name,@executable_path/../Frameworks/$$out/$${out%.framework}'
+			FRAMEWORK_LDFLAGS_INSTALL_NAME='-Wl,-install_name,${prefix}/Frameworks/$$out/$${out%.framework}'
 		])
 
 		AC_SUBST(FRAMEWORK_LDFLAGS)
 		AC_SUBST(FRAMEWORK_LDFLAGS_INSTALL_NAME)
 		AC_SUBST(FRAMEWORK_LIBS)

```

The `./autogen.sh` needs to be made unconditional then, though.

**Comment by chenrui333** [comment]
> The following diff should help with that:
> 
> ```diff
> Index: build-aux/m4/buildsys.m4
> ==================================================================
> --- build-aux/m4/buildsys.m4
> +++ build-aux/m4/buildsys.m4
> @@ -312,11 +312,11 @@
>  		AS_IF([test x"$host_is_ios" = x"yes"], [
>  			FRAMEWORK_LDFLAGS='-dynamiclib -current_version ${LIB_MAJOR}.${LIB_MINOR} -compatibility_version ${LIB_MAJOR}'
>  			FRAMEWORK_LDFLAGS_INSTALL_NAME='-Wl,-install_name,@executable_path/Frameworks/$$out/$${out%.framework}'
>  		], [
>  			FRAMEWORK_LDFLAGS='-dynamiclib -current_version ${LIB_MAJOR}.${LIB_MINOR} -compatibility_version ${LIB_MAJOR}'
> -			FRAMEWORK_LDFLAGS_INSTALL_NAME='-Wl,-install_name,@executable_path/../Frameworks/$$out/$${out%.framework}'
> +			FRAMEWORK_LDFLAGS_INSTALL_NAME='-Wl,-install_name,${prefix}/Frameworks/$$out/$${out%.framework}'
>  		])
>  
>  		AC_SUBST(FRAMEWORK_LDFLAGS)
>  		AC_SUBST(FRAMEWORK_LDFLAGS_INSTALL_NAME)
>  		AC_SUBST(FRAMEWORK_LIBS)
> ```
> 
> The `./autogen.sh` needs to be made unconditional then, though.

tried in my local, still the same issue

```
$ brew audit --strict objfw
Broken dependencies:
  /opt/homebrew/Cellar/objfw/1.0/Frameworks/ObjFW.framework/ObjFW (objfw)
objfw
  * objfw has broken dynamic library links:
```

**Comment by Midar** [comment]
Oh, I just realized, looking at the paths, that it builds the framework with paths for iOS, not for macOS.

I'm not familiar with homebrew these days, is there a way to get the full build logs? We could just change the path in the buildsys.m4 file, but I'd rather know *why* it is detected as iOS rather than macOS, as the check is a preprocessor check to see if the following evaluates to yes:

```c
                        #include <TargetConditionals.h>                 
                                                                            
                        #if (defined(TARGET_OS_IPHONE) && TARGET_OS_IPHONE) || \
                            (defined(TARGET_OS_SIMULATOR) && \             
                            TARGET_OS_SIMULATOR)                              
                        yes    
                        #endif
```

**Comment by chenrui333** [comment]
this is the build log from my local, https://gist.github.com/chenrui333/624d41f28eb85a9929b0c2e8671faf6d. let me know if you need more info. :)

**Comment by Midar** [comment]
NVM, the paths are correct. The issue is not that it's a broken symlink, it's the it's the library itself instead of a symlink. I'll come up with a fix upstream.

**Comment by Midar** [comment]
Can you try patching in https://github.com/ObjFW/ObjFW/commit/a1f0375af9eff8ee23670b6b10c905ba5c496ff5?

**Comment by Midar** [comment]
And also https://github.com/ObjFW/ObjFW/commit/8d648f86bdde927d94976b1728b3c1ab36a3b9d6, actually. The fix was incomplete.

**Comment by Midar** [comment]
@chenrui333 Ping. Can you please reopen?

**Pull request closed without merging**
