### PR TITLE
snapcraft: use python-certifi formula

### PR DESCRIPTION
**Pull request by alex**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [x] Have you ensured that your commits follow the [commit style guide](https://docs.brew.sh/Formula-Cookbook#commit)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source <formula>`)? If this is a new formula, does it pass `brew audit --new <formula>`?

-----

### CODE REVIEW

**Comment by alex** [comment]
```
Failed to execute: /opt/homebrew/Cellar/snapcraft/7.3.1_1/libexec/bin/pip
```

Not sure what to make of this

**Comment by Bo98** [comment]
Because of https://github.com/Homebrew/brew/commit/d1f60aea49d35fc0ba8f02a1f4fd26d0a369e071, the `system libexec/"bin/pip", ...` likely needs changing to `system "python3.11", "-m", "pip", ...` or similar.

**Comment by Bo98** [comment]
Similar change in another PR that this overlaps with: https://github.com/Homebrew/homebrew-core/pull/138655/files#diff-4504e511f400c5664cbb50b48f5db1c4cf571dfeac31f07facc01c42e5128ad3R429

**Comment by alex** [comment]
Thanks. Going to close this and I'll re-send after that one merges. (This is what I get for searching, then going to do a chore, then sending the PR...)

**Pull request closed without merging**
