### PR TITLE
b2-tools 0.6.2

### PR DESCRIPTION
**Pull request by ilovezfs**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@DomT4 PR refreshed.

**Comment by DomT4** [comment]
You're worked harder than most of us on this; unless all the resources are build only we tend to dump 'em all in `libexec`, heh. 👍

**Comment by ilovezfs** [comment]
@DomT4 upstream made that relatively easy since `python setup.py nosetests` triggers (it just does it without asking) pip installs for whatever it needs but cannot find.

**Pull request closed without merging**
