### PR TITLE
hadolint 2.9.1

### PR DESCRIPTION
**Pull request by branchv**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Review by iMichka — DISMISSED** [review]
Not yet marked as stable release

**Review by carlocab — DISMISSED** [review]
It's the latest release on Hackage: https://hackage.haskell.org/package/hadolint

**Comment by cho-m** [comment]
It might be worth waiting in case upstream retags release.

hadolint/hadolint#792 - GitHub latest release pending on Docker builds. It is possible they will just reuse existing tag once Docker builds are available, or they may retag if they merge in anything necessary to fix their CI build.

Code will probably be similar, but may reduce risk of checksum mismatch in future.

**Comment by mathbunnyru** [comment]
v2.9.1 was released, and there is v2.9.0 on the release page, so I think it would be better to update right to v2.9.1.

**Review by carlocab — APPROVED** [review]

**Pull request closed without merging**
