### PR TITLE
gnuplot: add libcerf support

### PR DESCRIPTION
**Pull request by equal-l2**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

`libcerf` enables gnuplot to use some special functions, `cerf` for example.

### CODE REVIEW

**Comment by woodruffw** [comment]
I think our current policy in core is to avoid cross-tap dependencies, wherever possible.

ping @ilovezfs for an opinion

**Comment by ilovezfs** [comment]
Optional cross tap dependencies are permissible. However, in the last month libcerf has 17 installs, so I'm thinking this option isn't really going to be used.

**Comment by equal-l2** [comment]
Actually I don't know any package using `libcerf` other than gnuplot.
Providing `libcerf` in `resource` block might be better.

**Comment by ilovezfs** [comment]
>Providing libcerf in resource block might be better.

Can you build it in statically? How long does it take to build?

**Comment by equal-l2** [comment]
> Can you build it in statically?

Yes.

> How long does it take to build?

The build takes only a minute including `configure` step.

**Comment by ilovezfs** [comment]
Sounds fine to me.

Out of interest: what does it do? :)

**Comment by equal-l2** [comment]
> what does it do?

You mean what `libcerf` itself does?
`libcerf` provides implementation of `cerf` and `cerfc` math functions, which are "reserved" in C99 but not implemented.
`libcerf` also provides some special math functions.

With libcerf, gnuplot can use these math functions.

**Review by MikeMcQuaid — APPROVED** [review]
Will leave the final call up to @ilovezfs

**Review by ilovezfs — APPROVED** [review]

**Comment by JCount** [comment]
CI git checkout went :boom:

**Comment by JCount** [comment]
Thank you for your contribution to Homebrew, @equal-l2!

**Pull request closed without merging**
