### PR TITLE
agda 2.6.3

### PR DESCRIPTION
**Pull request by Porkepix**
Created by `brew bump`

---

Created with `brew bump-formula-pr`.

~`resource` blocks may require updates.~

### CODE REVIEW

**Comment by chenrui333** [comment]
build failure

```
/opt/homebrew/Cellar/agda/2.6.3/lib/agda/src/Data/Float/Base.agda:68,19-25
Agda.Builtin.Maybe.Maybe Word.Word64 !=< Word.Word64
when checking that the expression toWord has type
Float → Word.Word64
```

**Comment by chenrui333** [comment]
> build failure
> 
> ```
> /opt/homebrew/Cellar/agda/2.6.3/lib/agda/src/Data/Float/Base.agda:68,19-25
> Agda.Builtin.Maybe.Maybe Word.Word64 !=< Word.Word64
> when checking that the expression toWord has type
> Float → Word.Word64
> ```

relates to https://github.com/agda/agda-stdlib/issues/1883

**Comment by chenrui333** [comment]
yeah, that is what i think, but if they have the patches, we can also give them a try.

**Comment by pthariensflame** [comment]
`agda-stdlib` 1.7.2 is now released!  If we could update this it would be good.

**Review by chenrui333 — APPROVED** [review]

**Pull request closed without merging**
