### PR TITLE
miniserve 0.5.0

### PR DESCRIPTION
**Pull request by chenrui333**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SMillerDev** [comment]
```
error[E0554]: #![feature] may not be used on the stable release channel
  --> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/literalext-0.1.1/src/lib.rs:19:37
   |
19 | #![cfg_attr(feature = "proc-macro", feature(proc_macro))]
   |                                     ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
   Compiling opaque-debug v0.2.2
error: Could not compile `literalext`.
warning: build failed, waiting for other jobs to finish...
```

**Comment by equal-l2** [comment]
The dependency `literalext` requires nightly. See https://github.com/svenstaro/miniserve/issues/122.
(I'm currently looking for a workaround...)

**Comment by chenrui333** [comment]
@equal-l2 any update on this? :)

**Comment by equal-l2** [comment]
Nope. Unless `miniserve` drops `maud` or `maud` supports stable Rust, we cannot build `miniserve` with stable Rust and cannot update formula.

**Comment by chenrui333** [comment]
Another way of thinking this (although not ideal, it is to pull the HEAD of `literalext`), and it should be able to solve the PR build issue?

**Comment by equal-l2** [comment]
Unfortunately, `maud` itself (e.g. not only its dependencies) requires nightly Rust.

**Comment by chenrui333** [comment]
looks like we can do something like @mistydemeo did in #43440

**Comment by chenrui333** [comment]
Should be good now, tested locally.

**Review by mistydemeo — APPROVED** [review]

**Pull request closed without merging**
