### PR TITLE
numpy 1.17.4

### PR DESCRIPTION
**Pull request by bayandin**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by bayandin** [comment]
- `brew-test-bot.high_sierra.test caffe`: https://github.com/BVLC/caffe/issues/6864#issuecomment-554878222
- `brew-test-bot.high_sierra.linkage --test grib-api` looks like a problem with high_sierra bottle. It fails for me with the same error, but after reinstalling from the source it works

Both 
- `brew-test-bot.high_sierra.install --only-dependencies mapnik`
- `brew-test-bot.high_sierra.test pgrouting` 
fails with `FATAL:  could not create shared memory segment: No space left on device` message. Probably not an error really https://github.com/Homebrew/homebrew-core/pull/46858#issuecomment-555047108

**Comment by Bo98** [comment]
grib-api will be an opportunistic linking problem.

**Comment by fxcoudert** [comment]
- For grib-api: https://github.com/Homebrew/homebrew-core/pull/46924
- The caffe test is a bad test anyway, because it downloads a 250 MB file. We need something simpler.

**Comment by bayandin** [comment]
Thanks!

**Pull request closed without merging**
