### PR TITLE
go 1.15.8

### PR DESCRIPTION
**Pull request by qinxin0720**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by carlocab** [comment]
All Intel Nodes:
```
Error: 7 failed steps!
brew audit go --online --git --skip-style
brew install --build-from-source buildifier
brew install --build-from-source buildozer
brew install --build-from-source charm-tools
brew test --retry --verbose gost
brew test --retry --verbose gost
brew install --build-from-source ioctl
```

Only on Catalina and Mojave:
```
brew install --build-from-source envoy
```

The `revision 1` line needs to be removed to fix the `audit` failure.

**Comment by carlocab** [comment]
`gost` failure seems spurious:
```
Error: gost: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </200\ OK/> was expected to be =~
<"HTTP/1.1 200 Connection established\r\n" +
```

**Comment by gromgit** [comment]
> `ioctl` is a `sha256` mismatch:

As I write this, v1.1.3 is in fact the latest release. v1.1.4 is just an ordinary tag, and was probably force-retagged (the current tag is 11 days old, 3 days *after* it was PR'd into Homebrew core).

**Comment by carlocab** [comment]
>v1.1.3 is in fact the latest release

Whoops 🙈

**Comment by Loyalsoldier** [comment]
Any update?

**Comment by vvvvv** [comment]
how can we move this forward?

**Comment by carlocab** [comment]
We need to investigate the failures above: https://github.com/Homebrew/homebrew-core/pull/70446#issuecomment-774333544

The ones outstanding are buildifier, buildozer, charm-tools, and envoy.

**Comment by vvvvv** [comment]
buildifier 3.5.0 depends on bazelisk which is a "A user-friendly launcher for Bazel". Because bazelisk downloads the newest version of bazel (4.0.0) it seems buildifier failes to build because outdated syntax is being used.  
Building buildifier 4.0.0 failes because of #70328 

buildozer failes because of the same issues.  

Both buildifier and buildozer are being build with bazelisk even tho they could easily be build with just `go build`.  
Thank god for an easy build system like bazel which produces reproducible builds...

**Comment by SMillerDev** [comment]
If you can switch them to `go build` I think that would be great for brew maintainability.

**Comment by Loyalsoldier** [comment]
Why to build them from source code instead of using the prebuilt binary released by the official?

**Comment by SMillerDev** [comment]
> Why to build them from source code instead of using the prebuilt binary released by the official?

Because Homebrew needs to do it's own optimization for software for it to work well.

**Comment by vvvvv** [comment]
> If you can switch them to `go build` I think that would be great for brew maintainability.

I updated buildifier and buildozer to 4.0.0 and simplified the build process (see #70921 and  #70924).  

Hope we can move forward with releasing go 1.15.8 now.

**Comment by SMillerDev** [comment]
We still need to solve/investigate the failures for:
```
brew install --build-from-source charm-tools 
brew install --build-from-source envoy
brew install --build-from-source ioctl
```

**Comment by vvvvv** [comment]
> We still need to solve/investigate the failures for:
> 
> ```
> brew install --build-from-source charm-tools 
> brew install --build-from-source envoy
> brew install --build-from-source ioctl
> ```

`brew install --build-from-source ioctl` was already fixed yesterday #70883.  
`brew install --build-from-source envoy` failes because it uses bazelisk which uses bazel.  
`brew install --build-from-source charm-tools` builds just fine.  

Please move this forward.  
How can totally unrelated issues block this update?  
You wouldn't block a nodejs update if some third party node module fails to build because it depends on a docker in a private registry would you?

**Comment by SMillerDev** [comment]
> How can totally unrelated issues block this update?

We first have to determine that it's unrelated.
> You wouldn't block a nodejs update if some third party node module fails to build because it depends on a docker in a private registry would you?

I would, until it was certain that nodejs wasn't to blame for this.

**Comment by vvvvv** [comment]
> > How can totally unrelated issues block this update?
> 
> We first have to determine that it's unrelated.

I investigated every issue.  
What do you need from me to trust me?  
I resolved #70883, and fixed #70921 and #70924 to actually depend on go rather than depending on software unrelated to go.  
You don't like my fix - ok - but waiting till unrelated packages fix their code is a totally unacceptable sulotion.  
Go has a version contract that states [updates wont break any code depending on go v1.x.x](https://golang.org/doc/go1compat).  
Homebrews integration tests are at fault not the go version trying to get released.

**Comment by SMillerDev** [comment]
> What do you need from me to trust me?

I need time to read answers and actually confirm what I'm reading with prior attempts 

> I resolved #70883, and fixed #70921 and #70924 to actually depend on go rather than depending on software unrelated to go.

It's not really fixed until it's merged.
> You don't like my fix - ok - but waiting till unrelated packages fix their code is a totally unacceptable sulotion.

It has been for the past 10+ years of Homebrew's existence.

> Go has a version contract that states updates wont break any code depending on go v1.x.x.

That is assuming no software developer does anything weird, which is quite a stretch.

> Homebrews integration tests are at fault not the go version trying to get released.

They're at fault for finding issues in software?

---
If you need go versions quickly I'd recommend maintaining your own tap.
The goal for Go in homebrew is not just to provide people with Go, but also to provide Homebrew with Go. This simply means that we need to be certain nothing new breaks when we update.

In addition to that, we're a volunteer based project. Not everyone has time or energy to fix Go first. We don't have any obligation to support your request for updates, please read https://mikemcquaid.com/2018/03/19/open-source-maintainers-owe-you-nothing/ for more information.

**Comment by vvvvv** [comment]
I'm not your enemy I'm just trying to explain to you that go isn't at fault here.  

IMHO bazelisk is at fault and should never have been accepted into homebrew because it doesn't depend on "bazel" (as stated in the formula https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/bazelisk.rb#L17, rather it depends on go) **but** bazelisk itself fetches a "good version of bazek" (as in it downloads a version of bazel it thinks is suitable) and uses that (see https://github.com/bazelbuild/bazelisk/#about-bazelisk ).  
This means bazelisk actually does depends on bazel.  

The current situation is a follows:  
Every package that uses bazelisk for building fails because bazel 4.0.0 is fetched by bazelisk which fails because of errors related to google c++ protobuf.  

Take your time to understand whats going on.  
I didn't want to come of as putting stress on you.  
I'm just stating that there is a problem in the release process of go totally unrelated to go which should be resolved asap, not when those unrelated packages resolve these issues in upstream.

**Comment by carlocab** [comment]
Thanks for your effort in getting this PR to move along, @vvvvv. We'd also appreciate some patience on your end: we don't always have the time to conduct a careful expedient review. Shipping broken software is worse than shipping outdated ones, I think.

That said, I do agree with your assessment that these build failures are not regressions caused by go1.15.8. To test this, I built the failing formula on GitHub runners (with Big Sur and Catalina) using go1.15.7, and found the exact same failures:

[Big Sur](https://github.com/carlocab/homebrew-personal/pull/37/checks?check_run_id=1876005589)
[Catalina](https://github.com/carlocab/homebrew-personal/pull/37/checks?check_run_id=1876005599)

**Comment by carlocab** [comment]
Ok, I rebased this PR against master and then dropped the `revision` to fix the audit error.

While we're waiting for CI to finish, it'd help if someone could try to fix `charm-tools`.

**Comment by vvvvv** [comment]
invastigating charm-tools:  
 - dependency jsonschema needs wheel pkg installed for setup

A PR was submitted that explicitly includes `wheel` #70950

**Comment by vvvvv** [comment]
investigating envoy:  

`envoy` uses `bazelisk` as its build system.  
Like with the other pkgs which use `bazelisk` it failes due to google protobuf compilation errors. 


```
2021-02-12 00:56:28 +0100

/usr/local/opt/bazelisk/bin/bazelisk
build
--curses=no
--show_task_finish
--verbose_failures
--action_env=PATH=/usr/local/bin:/opt/local/bin:/usr/bin:/bin
--test_output=all
//source/exe:envoy-static

2021/02/12 00:56:28 Downloading https://releases.bazel.build/3.7.2/release/bazel-3.7.2-darwin-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: ignoring _JAVA_OPTIONS in environment.
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
DEBUG: /private/var/tmp/_bazel_v/e9519541c677c849d1e7d78bb6002417/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_v/e9519541c677c849d1e7d78bb6002417/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_v/e9519541c677c849d1e7d78bb6002417/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_v/e9519541c677c849d1e7d78bb6002417/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /private/var/tmp/_bazel_v/e9519541c677c849d1e7d78bb6002417/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:14: 
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
Loading: 0 packages loaded
    currently loading: source/exe
Analyzing: target //source/exe:envoy-static (1 packages loaded, 0 targets configured)
INFO: SHA256 (https://golang.org/dl/?mode=json&include=all) = 7008033e0ab99ec03d6eb9593445b9a94bec029ac91450ffb4318c059ca427dc
Analyzing: target //source/exe:envoy-static (18 packages loaded, 6 targets configured)
Analyzing: target //source/exe:envoy-static (18 packages loaded, 6 targets configured)
Analyzing: target //source/exe:envoy-static (18 packages loaded, 6 targets configured)
Analyzing: target //source/exe:envoy-static (27 packages loaded, 181 targets configured)
Analyzing: target //source/exe:envoy-static (27 packages loaded, 181 targets configured)
Analyzing: target //source/exe:envoy-static (311 packages loaded, 10494 targets configured)
Analyzing: target //source/exe:envoy-static (379 packages loaded, 11583 targets configured)
Analyzing: target //source/exe:envoy-static (413 packages loaded, 13168 targets configured)
Analyzing: target //source/exe:envoy-static (498 packages loaded, 14999 targets configured)
Analyzing: target //source/exe:envoy-static (639 packages loaded, 16401 targets configured)
Analyzing: target //source/exe:envoy-static (754 packages loaded, 25477 targets configured)
INFO: Analyzed target //source/exe:envoy-static (755 packages loaded, 41502 targets configured).
INFO: Found 1 target...
[0 / 1,606] [Prepa] Creating source manifest for //source/exe:envoy-static
INFO: From CcCmakeMakeRule external/envoy/bazel/foreign_cc/zlib/include [for host]:
[65 / 1,904] Compiling com_google_protobuf/src/google/protobuf/message.cc [for host]; 2s processwrapper-sandbox ... (4 actions, 3 running)
rules_foreign_cc: Cleaning temp directories
INFO: From Linking external/com_google_protobuf/libprotobuf_lite.a [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf_lite/io_win32.o has no symbols
[111 / 1,904] Compiling com_google_protobuf/src/google/protobuf/util/message_differencer.cc [for host]; 6s processwrapper-sandbox ... (4 actions, 3 running)
[138 / 1,904] Compiling com_google_protobuf/src/google/protobuf/compiler/objectivec/objectivec_helpers.cc [for host]; 5s processwrapper-sandbox ... (4 actions, 3 running)
[184 / 1,904] Compiling com_google_protobuf/src/google/protobuf/util/internal/default_value_objectwriter.cc [for host]; 4s processwrapper-sandbox ... (4 actions, 3 running)
[265 / 1,904] Compiling com_google_protobuf/src/google/protobuf/descriptor.cc [for host]; 23s processwrapper-sandbox ... (4 actions, 3 running)
INFO: From Linking external/com_google_protobuf/libprotobuf.a [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/error_listener.o has no symbols
INFO: From Executing genrule @io_opentracing_cpp//:generate_version_h:
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- clang-tidy not found.
-- Configuring done
-- Generating done
-- Build files have been written to: /var/folders/ym/vpxhn1k56hz7v4r2fh46w0sm0000gn/T/tmp.6a1U9hGF
-- Cache values
BUILD_DYNAMIC_LOADING:BOOL=ON
BUILD_MOCKTRACER:BOOL=OFF
BUILD_SHARED_LIBS:BOOL=ON
BUILD_STATIC_LIBS:BOOL=ON
BUILD_TESTING:BOOL=OFF
CLANG_TIDY_EXE:FILEPATH=CLANG_TIDY_EXE-NOTFOUND
CMAKE_BUILD_TYPE:STRING=
CMAKE_EXECUTABLE_FORMAT:STRING=MACHO
CMAKE_INSTALL_PREFIX:PATH=/usr/local
CMAKE_OSX_ARCHITECTURES:STRING=
CMAKE_OSX_DEPLOYMENT_TARGET:STRING=
CMAKE_OSX_SYSROOT:PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
ENABLE_LINTING:BOOL=ON
INFO: From Executing genrule @com_lightstep_tracer_cpp//:generate_version_h:
CMake Warning at CMakeLists.txt:74 (message):
  WITH_GRPC is not set; building without dynamic loading support.


-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /var/folders/ym/vpxhn1k56hz7v4r2fh46w0sm0000gn/T/tmp.NsrHu8ER
-- Cache values
BUILD_SHARED_LIBS:BOOL=ON
BUILD_STATIC_LIBS:BOOL=ON
CMAKE_BUILD_TYPE:STRING=
CMAKE_EXECUTABLE_FORMAT:STRING=MACHO
CMAKE_INSTALL_PREFIX:PATH=/usr/local
CMAKE_OSX_ARCHITECTURES:STRING=
CMAKE_OSX_DEPLOYMENT_TARGET:STRING=
CMAKE_OSX_SYSROOT:PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
DEFAULT_SSL_ROOTS_PEM:STRING=
HEADERS_ONLY:BOOL=ON
WITH_CARES:BOOL=OFF
WITH_DYNAMIC_LOAD:BOOL=ON
WITH_GRPC:BOOL=OFF
WITH_LIBEVENT:BOOL=OFF
INFO: From Linking external/com_google_absl/absl/debugging/libdebugging_internal.a [for host]:
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_absl/absl/debugging/_objs/debugging_internal/elf_mem_image.o has no symbols
/Library/Developer/CommandLineTools/usr/bin/libtool: file: bazel-out/host/bin/external/com_google_absl/absl/debugging/_objs/debugging_internal/vdso_support.o has no symbols
[1,233 / 3,325] Compiling com_google_absl/absl/time/internal/cctz/src/time_zone_info.cc [for host]; 3s processwrapper-sandbox ... (4 actions, 3 running)
ERROR: /private/var/tmp/_bazel_v/e9519541c677c849d1e7d78bb6002417/external/upb/upbc/BUILD:19:10: C++ compilation of rule '@upb//upbc:protoc-gen-upb' failed (Exit 1): cc_wrapper.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_v/e9519541c677c849d1e7d78bb6002417/sandbox/processwrapper-sandbox/347/execroot/envoy && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
    PWD=/proc/self/cwd \
  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/upb/upbc/_objs/protoc-gen-upb/message_layout.d '-frandom-seed=bazel-out/host/bin/external/upb/upbc/_objs/protoc-gen-upb/message_layout.o' -iquote external/upb -iquote bazel-out/host/bin/external/upb -iquote external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -iquote external/com_google_absl -iquote bazel-out/host/bin/external/com_google_absl -iquote external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -isystem external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -isystem bazel-out/host/bin/external/envoy/bazel/foreign_cc/zlib/include -g0 -g0 -Wextra -Werror -Wno-long-long -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/upb/upbc/message_layout.cc -o bazel-out/host/bin/external/upb/upbc/_objs/protoc-gen-upb/message_layout.o)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox cc_wrapper.sh failed: error executing command 
  (cd /private/var/tmp/_bazel_v/e9519541c677c849d1e7d78bb6002417/sandbox/processwrapper-sandbox/347/execroot/envoy && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
    PWD=/proc/self/cwd \
  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/upb/upbc/_objs/protoc-gen-upb/message_layout.d '-frandom-seed=bazel-out/host/bin/external/upb/upbc/_objs/protoc-gen-upb/message_layout.o' -iquote external/upb -iquote bazel-out/host/bin/external/upb -iquote external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -iquote external/com_google_absl -iquote bazel-out/host/bin/external/com_google_absl -iquote external/bazel_tools -iquote bazel-out/host/bin/external/bazel_tools -isystem external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -isystem bazel-out/host/bin/external/envoy/bazel/foreign_cc/zlib/include -g0 -g0 -Wextra -Werror -Wno-long-long -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/upb/upbc/message_layout.cc -o bazel-out/host/bin/external/upb/upbc/_objs/protoc-gen-upb/message_layout.o)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/upb/upbc/message_layout.cc:3:
In file included from /usr/local/include/google/protobuf/descriptor.pb.h:25:
/usr/local/include/google/protobuf/arenastring.h:306:53: error: unused parameter 'default_value' [-Werror,-Wunused-parameter]
                                 const std::string* default_value,
                                                    ^
/usr/local/include/google/protobuf/arenastring.h:307:41: error: unused parameter 'arena' [-Werror,-Wunused-parameter]
                                 Arena* arena) {
                                        ^
In file included from external/upb/upbc/message_layout.cc:3:
In file included from /usr/local/include/google/protobuf/descriptor.pb.h:26:
In file included from /usr/local/include/google/protobuf/generated_message_table_driven.h:34:
In file included from /usr/local/include/google/protobuf/map.h:56:
/usr/local/include/google/protobuf/map_type_handler.h:611:1: error: unused parameter 'arena' [-Werror,-Wunused-parameter]
STRING_OR_BYTES_HANDLER_FUNCTIONS(STRING)
^
/usr/local/include/google/protobuf/map_type_handler.h:572:35: note: expanded from macro 'STRING_OR_BYTES_HANDLER_FUNCTIONS'
      TypeOnMemory* value, Arena* arena) {                                    \
                                  ^
/usr/local/include/google/protobuf/map_type_handler.h:612:1: error: unused parameter 'arena' [-Werror,-Wunused-parameter]
STRING_OR_BYTES_HANDLER_FUNCTIONS(BYTES)
^
/usr/local/include/google/protobuf/map_type_handler.h:572:35: note: expanded from macro 'STRING_OR_BYTES_HANDLER_FUNCTIONS'
      TypeOnMemory* value, Arena* arena) {                                    \
                                  ^
In file included from external/upb/upbc/message_layout.cc:3:
In file included from /usr/local/include/google/protobuf/descriptor.pb.h:29:
/usr/local/include/google/protobuf/generated_message_reflection.h:239:61: error: unused parameter 'type' [-Werror,-Wunused-parameter]
  static uint32 OffsetValue(uint32 v, FieldDescriptor::Type type) {
                                                            ^
5 errors generated.
Target //source/exe:envoy-static failed to build
INFO: Elapsed time: 355.207s, Critical Path: 32.37s
INFO: 1418 processes: 1069 internal, 348 processwrapper-sandbox, 1 worker.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

HOMEBREW_VERSION: 3.0.1-23-g3f39c20
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3f39c204cf12a88516c48918212b1c2474446aed
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cebdc164b139c2e20b7c2d8054cd566ea6a55a44
Core tap last commit: 30 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_BOOTSNAP: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/11
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/automake/bin:/usr/local/opt/bazelisk/bin:/usr/local/opt/cmake/bin:/usr/local/opt/coreutils/bin:/usr/local/opt/go/bin:/usr/local/opt/libtool/bin:/usr/local/opt/ninja/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by carlocab** [comment]
Ok, so there are some new failures, unfortunately. All the previous ones are still there, just listing the new ones below.

All:
```
brew install --build-from-source aerc
brew install --build-from-source ksync
```

Catalina and Mojave:
```
brew test --retry --verbose darksky-weather
```

Only Catalina:
```
brew install --build-from-source krakend
```

I'll try to have a closer look at these shortly.

**Comment by carlocab** [comment]
|Failed Formula|Version(s)|Comment|
|:---:|:---:|---|
|`aerc`|All|Checksum mismatch|
|`ksync`|All|Checksum mismatch|
|`darksky-weather`|10.14, 10.15| `http request to https://geocode.jessfraz.com/forecast failed with status code: 403`|
|`krakend`|10.15|`Get "https://proxy.golang.com.cn/github.com/gin-gonic/gin/@v/v1.6.3.zip": stopped after 10 redirects`|

The new failures are unrelated to the version bump.

**Review by carlocab — APPROVED** [review]

**Comment by carlocab** [comment]
aerc: #71189

**Pull request closed without merging**
