### PR TITLE
Adds caveat about asdf shims

### PR DESCRIPTION
**Pull request by deiga**
- [x] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Is your test running fine `brew test <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
This doesn't seem like a very homebrew specific message. Isn't this better suited to be documented upstream? 

> You can run `source <install_dir>/asdf.sh` to get access to the shims.

Or something like that

**Comment by deiga** [comment]
@SMillerDev I don't really understand your point. This caveat explains how to get `asdf` functional, without it doesn't work fully. 
And installing something with homebrew you would assume, that things you install work unless they tell you that they don't work.

For example `brew info mongodb` tells you what you need to do to get mongo actually running

**Comment by MikeMcQuaid** [comment]
> This caveat explains how to get `asdf` functional, without it doesn't work fully.

This is not what caveats are for. They are for Homebrew specific limitations or deviations from how the software is typically configured. There are already documented here: https://asdf-vm.com/#/core-manage-asdf-vm?id=add-to-your-shell

**Comment by MikeMcQuaid** [comment]
@SMillerDev has offered to submit a PR to update the docs for this

**Comment by deiga** [comment]
@MikeMcQuaid Since Homebrew deviates on the location of the installation and the corresponding file that needs to be loaded, I would think this is a Homebrew specific thing.
I think it's a bit heavy for upstream to be aware and keep track of where and how Homebrew formulas install files

**Comment by MikeMcQuaid** [comment]
Passing on this, sorry.

**Pull request closed without merging**
