### PR TITLE
opencv: enable tbb by default

### PR DESCRIPTION
**Pull request by papr**
tbb is required when one wants to use opencv in a multiprocessing
application. See this opencv issue thread for details:
https://github.com/opencv/opencv/issues/5150#issuecomment-197398154

### CODE REVIEW

**Comment by ilovezfs** [comment]
please bump the revision :)

**Review by ilovezfs — APPROVED** [review]

**Comment by papr** [comment]
Is this the correct way to bump the revision?

**Comment by ilovezfs** [comment]
yup :)

**Comment by ilovezfs** [comment]
Thanks for your first contribution to Homebrew, @papr! Without people like you submitting PRs we couldn't run this project. You rock!

**Comment by Gromina** [comment]
Thanks guys. Did not expect that you will correct this bug in the day when I met it

**Pull request closed without merging**
