### PR TITLE
wine 3.1 (devel)

### PR DESCRIPTION
**Pull request by uyjulian**

### CODE REVIEW

**Comment by ilovezfs** [comment]
I'm reluctant to re-add wine devel here given it doubles the build time to 2 hours.

**Comment by uyjulian** [comment]
Why? Wasn't the build time 2 hours before?

**Comment by ilovezfs** [comment]
Yes, but one hour sounds awfully nice …

**Comment by ilovezfs** [comment]
@uyjulian going to pass on this for now. If there's significant demand for the devel version with some rationale behind it, we could revisit it. Also, I think for the next version we should remove the patch as Apple has provided upstream instructions on how it should be fixed and we don't want to carry the patch forever.

**Comment by dholm** [comment]
@ilovezfs I'm interested in the devel version. Wine [releases annually](https://www.winehq.org/news/2018011801) except for bugfixes and their [FAQ recommends trying the development releases](https://wiki.winehq.org/FAQ#Which_version_of_Wine_should_I_use.3F) unless an application is not working with current stable.

**Comment by ilovezfs** [comment]
@dholm wine-devel is in caskroom/homebrew-versions.

**Comment by dholm** [comment]
@ilovezfs It only appears to offer 3.0-rc6 though (https://dl.winehq.org/wine-builds/macosx/download.html).

**Comment by ilovezfs** [comment]
@dholm yup. Someone needs to open a PR over there for 3.1. Feel free to do so!

**Comment by d235j** [comment]
@ilovezfs the cask version is installed from a .pkg which makes it less than desirable and the annual release cycle is problematic. Why not have either --devel or a specific version of the more frequent release?

**Comment by d235j** [comment]
@ilovezfs additionally regarding the patch, someone needs to reach out to upstream about providing a reduced testcase as they claimed (to me, on IRC) that they had tried Apple's suggestions, and those did not work.

**Pull request closed without merging**
